### ISSUE TITLE
Left navigation menu doesn't collapse as expected in integration editor  

### ISSUE THREAD

**Issue by dongniwang** [syndesisio/syndesis#1010]
Was looking at the staging site with the UXD team, noticed the left navigation menu (hamburger menu) doesn't collapse automatically when in integration editor view. Clicking on the hamburger icon does nothing... 

The left navigation menu should collapse when users are in integration editor view (create integration flow) . 

cc: @seanforyou23 @gashcrumb @sjcox-rh @amysueg 

<img width="1432" alt="screen shot 2018-01-10 at 2 52 46 pm" src="https://user-images.githubusercontent.com/24943812/34792479-21fa72ee-f616-11e7-8232-8926626b4180.png">

**Comment by gashcrumb** [comment]
Is this still an issue?  I haven't seen it locally at least, I would suspect also with this kind of issue there should be some kind of relevant error(s) in the javascript console, be good if you could post a screenshot of that too.

**Comment by amysueg** [comment]
@gashcrumb I'm using the QE site here - https://syndesis-qe.b6ff.rh-idev.openshiftapps.com/dashboard  

and the hamburger icon doesn't do anything for me, in any of the views. Sorry couldn't really make out what was happening in the javascript console, but maybe you could try it from this link?

**Comment by gashcrumb** [comment]
Can't reproduce locally, even against an instance in minishift.  Given that the hamburger icon does nothing it appears that the script that controls hiding and showing the nav bar isn't running.

I notice the help menu is missing the 'Sample Integration Tutorials' link, I added that in early December last year, so my first suspicion is that what's on staging is kinda ancient.  @rhuss @dsimansk any idea what version is running on this instance?

We should seriously consider sticking the current commit SHA of the console in the page title or something so it's easy to spot what's running :-)

**Comment by zregvart** [comment]
Not sure when QE instance is updated, the latest from `master` should always be at:

https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/dashboard

@gashcrumb created #1347 for backend, we create `src/version.json` and add the same information for the UI

**Comment by kcbabo** [comment]
I can confirm this happens with 1.2.7 tag on Ignite cluster.

**Comment by gashcrumb** [comment]
@kcbabo wonder are you getting this error in the javascript console:

```
Error: Error: No setting found with the specified group/key [branding/productBuild]!
```

with a big stack trace?  The qe instance is showing this too and I'm suspecting it's related.

**Comment by kcbabo** [comment]
Yup, I see the same.

**Comment by gashcrumb** [comment]
I think this totally unrelated commit fixed it on master at least -> https://github.com/syndesisio/syndesis/commit/6da7f0b71e702c1292eb8046375818cc9a7aadd7#diff-9aa9034c6f35c37a4d480788ca9ac91aR68 will check the 1.2.x branch.

**Comment by gashcrumb** [comment]
This should be all set.
