### ISSUE TITLE
When editing integration, I can't remove second step after the one added 

### ISSUE THREAD

**Issue by tplevko** [syndesisio/syndesis#1020]
There is a strange behavior when I edit integration. When I insert a new step between some existing steps, I can't remove the step, which is right behind this inserted step. It happens also when I insert 2 new steps, I don't think this is desirable behavior. There is a recording of the behavior:
![cant_remove_second_item](https://user-images.githubusercontent.com/4180208/34822336-e1e890f8-f6c6-11e7-8d1e-2dc530f3c644.gif)

**Comment by kahboom** [comment]
Oh, this is quite an annoying bug.
