### ISSUE TITLE
lombok.Data anno is not processed via ./tools/bin/syndesis

### ISSUE THREAD

**Issue by igarashitm** [syndesisio/syndesis#1034]
When I run `./tools/bin/syndesis` without building sql connector ahead, I got
```
java.lang.Error: 
Unresolved compilation problems: 
	The method getTableNames() is undefined for the type SqlStatementMetaData
	The method getInParams() is undefined for the type SqlStatementMetaData
	The method getTypeValue() is undefined for the type SqlParam
	The method getName() is undefined for the type SqlParam
	The method getTypeValue() is undefined for the type SqlParam
	The method getTypeValue() is undefined for the type SqlParam
```
those are supposed to be added by the annotation processor. `./tools/bin/syndesis` should trigger it for the sql connector build.

**Comment by KurtStam** [comment]
I cannot reproduce it. 

It seems to be caused the fact that ./tools/bin/syndesis runs 'mvnw install', and it never deleted the old compiled code.

**Comment by igarashitm** [comment]
FYI - `./tools/bin/syndesis -c` to run `clean` goal
