### ISSUE TITLE
Support extension dependencies override

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#1038]
To support platform upgrades, the project generator should be able to override extension dependencies if  needed i.e. a bump of the build number may not require extension developers to rebuild their code. 

In case of incompatible upgrades:
- project generator should fail
- integration should be disabled

**Comment by lburgazzoli** [comment]
@gashcrumb, I this should be part of #971: is there a specific epic/issue for extension/connector upgrades ?

**Comment by gashcrumb** [comment]
Not yet!

**Comment by lburgazzoli** [comment]
So I'll assign to #971 as interim

**Comment by lburgazzoli** [comment]
keep it open
