### ISSUE TITLE
Implement the polished UI for Import/Export based on new UXD

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis#1053]
New UXD is has been finalized.  Lets start working on the UI bits for it. 

Once https://github.com/syndesisio/syndesis/pull/1022 is merged, the primary import APIs changes will be available.

We just need an additional API to query if "Additional Configuration" is required for integrations/connections #1052.  But I think UI impl can make progress without this implemented yet.

**Comment by chirino** [comment]
@gashcrumb plz reassign if needed.

**Comment by chirino** [comment]
Oh an feel free to push additional changes to #1022 while it's in flight to get merged.  All the current UI work there is poop anyways :)

**Comment by chirino** [comment]
Last designs I got were: https://redhat.invisionapp.com/share/7GFAZ8C24

**Comment by kahboom** [comment]
Closing and breaking up into multiple issues.
