### ISSUE TITLE
[Custom connectors] Make Extension a base interface for different extension types

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#1055]
As we are adding support to add connectors through extension mechanism we should make the current Extension object in our model a base interface like:

```java
@JsonTypeInfo(
    use      = JsonTypeInfo.Id.NAME,
    include  = JsonTypeInfo.As.EXISTING_PROPERTY,
    property = "extensionType"
)
@JsonSubTypes({
    @JsonSubTypes.Type(
        value = StepExtension.class,
        name  = Extension.TYPE_STEP),
    @JsonSubTypes.Type(
        value = ConnectorExtension.class,
        name  = Action.TYPE_CONNECTOR)
})
interface Extension {
    String getExtensionType();
}
```

**Comment by dongniwang** [comment]
@lburgazzoli @gashcrumb @kahboom  - just wanted to check in here and see what kind of UX design is needed for Custom Connectors. 

I can update the Extension List page and the Extension Details page to reflect the case where users have connector extensions. Do you need any other designs?

**Comment by lburgazzoli** [comment]
@dongniwang I guess #806 should be the right place to discuss this :)
