### ISSUE TITLE
[Custom connectors] Create a new top level app module extension

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#1056]
We should create a new top level module with some sub modules containing all the bits extension related.

i.e. we can have the following sub modules:

- **extension-bom** the bom used by extension developers, should include camel, spring-boot and syndesis dependencies
- **extension-maven-plugin** should be the new place for syndesis-maven-plugin bits related to extensions 
- **extension-api** for contains any developer facing API and annotations
- **extension-converter** for meta data converter

**Comment by lburgazzoli** [comment]
@nicolaferraro can you have a look at this one while working on #1037

**Comment by nicolaferraro** [comment]
:+1:

**Comment by apupier** [comment]
For information, I created https://issues.jboss.org/browse/FUSETOOLS-2757 to track actions required on Fuse Tooling side after this update.
