### ISSUE TITLE
API awesomeness

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#1058]
This epic is just the anchor issue for all API & Domain refactorings we want to get in before going GA.

We would like the API to be awesome:
 - Consistent (all endpoints should be returning consistent data structures)
 - Right fit for the UI (remove unneeded data)
 - Malleable (easy to collaborate on and make joint changes)

**Comment by rhuss** [comment]
A suggestion of using GraphQL can be found at #993

**Comment by zregvart** [comment]
Lets mention other issues relevant to this: #42, #449, #848, #540, #810, #136

**Comment by deeleman** [comment]
We've been discussing this issue in the UI team standup calls along these days and, whatever approach we eventually take in regards of formalizing the exchange of data between the UI and the API, there two particular requests we'd need to be taken into consideration:

- A formal, strict, top-level interface to inform of errors, regardless scope: either errors on the request payload (informing of Bad Request errors), errors upon processing data, validation errors, etc. This would give us the opportunity to digest and process error data in a more easy and standardized way, reusing the same interfaces for all data models  throughout the app. At this point, there is not a standard error output between API endpoints.
- A common, typed scheme for the response body for all calls. Some responses return data observing a `{ id: ..., kind: ... }` model. Others return the information as is, with all the data already hanging from the top. When returning collections, some responses come inside a ` { items: <collection_here> }` wrapper, and some others as a JSON array. We need to standardize this so we can reuse our own interface models clientside across the board.

These are the major concerns. We have some suggestions about the schemas we'd like to have for these two concerns above, which we can share here if you wish.

**Comment by chirino** [comment]
This issue is not actionable enough.  Lets create more concrete issues that can be completed.
