### ISSUE TITLE
Editing the integration name ends with inactive status

### ISSUE THREAD

**Issue by abouchama** [syndesisio/syndesis#1064]
If we edit the **integration name** in the UI, the status of this integration flow result to **Inactive**.
If we try to Reactivate it nothing happens, the status change only from **In progress** to **Inactive**.

**Comment by zregvart** [comment]
I feel we need to detect if the change in the integration model affects the running integration pod and only then redeploy the integration. One idea would be to perform hashing the data that the project generator uses and remember last revision's hash for comparison.

cc @iocanel @chirino

**Comment by iocanel** [comment]
This https://github.com/syndesisio/syndesis/pull/881 partially addressed that.

By partially I mean that it will `deactivate` and automatically `activate` in a couple of seconds.
Why `deactivate`? Cause it will create a new revision/deployment for the integration.
Why do we need a new revision? Cause the name goes into the pom of the project (this can easily change of course).
