### ISSUE TITLE
Implement updated integration detail page

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#1069]
This tracks getting the history table re-introduced to the detail page

https://github.com/syndesisio/syndesis/blob/master/ux/designs/integration_details/integration_details_page.md#basic-layout

Tasks:

* [x] Add kebab menu to toolbar, move existing buttons other than 'Edit' into it
* [x] Remove 'Status' section
* [x] Add 'History' section
* [x] Implement [expanding row items](https://github.com/syndesisio/syndesis/blob/master/ux/designs/integration_details/integration_details_page.md#expanding-a-row) for history rows
* [x] Add 'Draft' section
* [x] Connect 'History' section buttons/menus
* [x] Connect 'Draft' section buttons
* [x] Implement 'History' section [status indicators](https://github.com/syndesisio/syndesis/blob/master/ux/designs/integration_details/integration_details_page.md#status-indicators)
* [x] Add 'Published Version' text next to name
* [x] Implement 'Publishing' indicator next to the name
* [ ] Implement [inline notification area](https://github.com/syndesisio/syndesis/blob/master/ux/designs/integration_details/integration_details_page.md#status-indicators) for errors and warnings
* [ ] Connect 'republish' button

**Comment by dongniwang** [comment]
@gashcrumb - I remember adding BOM version to integration history as a new requirement. Do you happen to have an example BOM version handy? Just wanted to see what it looks like so I can suggest a place for it on this page. Thanks!

**Comment by gashcrumb** [comment]
This tracking issue has gone stale...
