### ISSUE TITLE
We require `apiBase` property for custom API connectors

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#1077]
If `apiBase` is not defined in `config.json` URL being used by `ApiConnectorService` contains `undefined`, like:

    https://syndesis..../undefined/api/v1undefined/api/v1/connectors?query=connectorGroupId=swagger-connector-template

This is currently manifested at our staging (https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/) environment. I wonder if this will occur when we productize, if so that would make it a blocker for TP3.

@deeleman can you take a look?
cc @dsimansk

**Comment by dsimansk** [comment]
@zregvart it was address in templates by https://github.com/syndesisio/syndesis/commit/1dc67c68c48fc717094828947aedb66a2a133ff1 The staging env wasn't redeployed from newer template since then most probably.

**Comment by zregvart** [comment]
Cool, let me see if I can apply new templates to staging

**Comment by zregvart** [comment]
I changed the UI config map on staging manually, seems to be OK now.
