### ISSUE TITLE
API connector: replace icon placeholder by an icon when selected

### ISSUE THREAD

**Issue by mastepan** [syndesisio/syndesis#1080]
Please replace this icon placeholder by an icon itself when selected.
![replaceapiconnectoriconplaceholder](https://user-images.githubusercontent.com/8707251/34988303-9e793024-fabe-11e7-8e90-d471c52c3afc.png)
![replaceapiconnectoriconplaceholder2](https://user-images.githubusercontent.com/8707251/34988561-68f724d2-fabf-11e7-8f14-b2f11d0043cc.png)

**Comment by dsimansk** [comment]
@zregvart @rhuss wdyt? It seems like a minor issue that can be safely deferred to TP4.

**Comment by zregvart** [comment]
Yeah I think that would be nice, not sure if it's that easy to do with all the restrictions in the browser. I'm sure @deeleman has a good idea on how this can be done. I would target TP4 with this.
