### ISSUE TITLE
There should be only one "import extension" action button on Extension empty state page 

### ISSUE THREAD

**Issue by dongniwang** [syndesisio/syndesis#1086]
This applies to both API client connector and Extension empty states. The top right small action button should only appear in the list view. 

![screen shot 2018-01-15 at 1 29 48 pm](https://user-images.githubusercontent.com/24943812/34999414-9cfcfffa-faaf-11e7-9e3a-66599700348b.png)

cc: @seanforyou23 @gashcrumb @kahboom @deeleman (not sure who worked on this feature, so I tagged all of you...)

**Comment by gashcrumb** [comment]
@dongniwang shouldn't need to tag anybody, any of the UI folks can pick this up and work on it :-)
