### ISSUE TITLE
Remove cached java inspection endpoint

### ISSUE THREAD

**Issue by igarashitm** [syndesisio/syndesis#1088]
#880 enabled to feed java inspection result via `specification` property on the DataShape. Once all the connectors are configured to use this, we no longer need cached java inspection endpoint at `/mapper/v1/java-inspections`. Let's remove this to simplify how datamapper step retrieve the inspection result.

Note that this is going to be invalid once we introduce intermediate connection (required to retrieve cached inspection result from the endpoint)
https://github.com/syndesisio/syndesis/blob/4a7abdbb7fec25a8a2e938153aaca30f83f8e3d4/app/ui/src/app/integrations/edit-page/step-configure/data-mapper/data-mapper-host.component.ts#L154-L159

**Comment by gashcrumb** [comment]
@igarashitm is this still relevant?
