### ISSUE TITLE
As a citizen integrator, monitor integrations and the integration environment

### ISSUE THREAD

**Issue by kcbabo** [syndesisio/syndesis#1091]
As a citizen integrator, I need the ability to monitor my overall integration environment and individual integrations.

For the overall integration environment, I would like to see:
* Number of active integrations
* System uptime
* Total number successful integration executions
* Total number of failed integration executions

For each integration, I would like to see:
* Number of processed messages
* Number of errors
* Last processed timestamp
* Integration uptime

Metrics need to survive restarts or failures of the Syndesis infrastructure and integration runtimes.

**Comment by chirino** [comment]
@kcbabo define 'System uptime'

**Comment by chirino** [comment]
@kcbabo is 'Number of processed messages' == 'number successful integration executions' ??

**Comment by chirino** [comment]
@kcbabo is 'Last processed timestamp' the time at which the integration execution started, or it ended?

**Comment by kcbabo** [comment]
@chirino I'm happy to provide my thoughts on these questions, but I don't believe there is a canonical definition of these metrics, so open to interpretation.  I would say the most important thing is that the metric naming is clear and the behavior consistent.  

- System uptime : time that Syndesis itself has been up.  Logically, I think this equates to the amount of time between Syndesis being ready to use on startup and now.
- Number of processed messages : I was thinking about total number of integration executions, but we could also limit it to successful runs.
- Last processed timestamp : this is a tough one.  I would suggest time it started, but definitely open to discussion. :-)
