### ISSUE TITLE
As a citizen integrator, add additional information to an integration log

### ISSUE THREAD

**Issue by kcbabo** [syndesisio/syndesis#1095]
As a citizen integrator, I want the ability to add a log step to an integration flow that allows me to record additional information in the integration log.  Additional log information will include one or more of the following:
* Message context (e.g. message headers and exchange properties)
* Message content (current message body)
* Custom information (Simple language expression)
The log step configuration page should allow me to select any/all of the above to be reported in the integration log.  When viewing a log entry produced by the log step, the details portion of the log entry should contain all of the log data produced by the step.

If a custom log message is provided, the UI should perform a basic syntax validation of the text prior to accepting the step configuration.

**Comment by iocanel** [comment]
From the server side, there is nothing else to be done.
The part that I am not sure if exists, is the validation, which is ui.

I am going to throw the issue at @gashcrumb  to close, reassign or do whatever it needs.

**Comment by gashcrumb** [comment]
I guess the remaining this is a syntax validator, that's kinda useful for a couple spots.  Created https://github.com/syndesisio/syndesis/issues/2189 I think we can close this user story issue though.
