### ISSUE TITLE
Monitoring Logs

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#1100]
Logging aspect for monitoring (Splitting up #968 into Monitoring & Logging)

**Comment by rhuss** [comment]
see: [Monitoring notes](https://docs.google.com/document/d/1cWiuzqvAEL2jjBnUqbGV7o4bLLZZZRAmbNZHszTKsWU/edit)

## User Stories
[Integration Log](https://github.com/syndesisio/syndesis/issues/1093)
[Link to Technical Log](https://github.com/syndesisio/syndesis/issues/1094)
[Log Step](https://github.com/syndesisio/syndesis/issues/1095)

**Comment by paoloantinori** [comment]
outstanding work listed here:
- https://github.com/syndesisio/syndesis/issues/1855
- https://github.com/syndesisio/syndesis/issues/1856
- https://github.com/syndesisio/syndesis/issues/1857
