### ISSUE TITLE
Monitoring Metrics

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#1101]
## VF2F Notes

see: [Monitoring notes](https://docs.google.com/document/d/1cWiuzqvAEL2jjBnUqbGV7o4bLLZZZRAmbNZHszTKsWU/edit)

## User Stories
[Integration Metrics](https://github.com/syndesisio/syndesis/issues/1091)
[Link to Technical Metrics](https://github.com/syndesisio/syndesis/issues/1092)

## UXD
[Design](https://github.com/syndesisio/syndesis/issues/1067)

## UI
[UI](https://github.com/syndesisio/syndesis/issues/1025)

## API
[api-design](https://github.com/syndesisio/syndesis/issues/1065)

## Back end
[Data Gathering](https://github.com/syndesisio/syndesis/issues/1023)
[SQL](https://github.com/syndesisio/syndesis/issues/1014)
[Prometheus](https://github.com/syndesisio/syndesis/issues/1013)

**Comment by rhuss** [comment]
Replacement in favor of #968 to split up the Epic into two parts (Metrics, Logging)

**Comment by Stefan365** [comment]
@Kurt, 
may I ask something about these metrics?

If I create integration e.g. to/from DB using 'periodic SQL invocation'/'insert into todo'
after while when I inspect DB, I can see those periodical inserts in the DB.

But when I use 

```api/v1/metrics/integrations```
I see:
```
{
  "errorCode": 500,
  "userMsg": "Please contact the administrator and file a bug report",
  "developerMsg": "Internal Server Exception. null"
}
```

and when I use id of that specific integration, e.g:

```/api/v1/metrics/integrations/-L59bfv3gg56UbOG8IJf```

I see this:
```
{
  "messages": 0,
  "errors": 0
}
```

Is there any trick to make these work, or is it just under construction?
(for syndesis instance I'm using syndesis master branch:
https://raw.githubusercontent.com/syndesisio/syndesis/master/app/deploy/syndesis-restricted.yml)
thanks for advice

**Comment by KurtStam** [comment]
@Stefan365 that should have worked. Two questions:
1. Is it using jsonDB or prometheus?
2. Any errors in the rest pod?

**Comment by Stefan365** [comment]
@KurtStam 
1. probably you are asking about metrics persistence - I haven't chosen any, so probably I'm using default one.
(the integration itself uses PostresDB connection on both sides)

2. I don't see any error on rest pod (there are some warns see attachment).
[rest.log](https://github.com/syndesisio/syndesis/files/1717037/rest.log)

[rest.log](https://github.com/syndesisio/syndesis/files/1717034/rest.log)

**Comment by KurtStam** [comment]
@Stefan365 Looks like the default is now prometheus which seems broken. Also when I switch back to sql there is stuff broken :(. I will report back when things work again.

**Comment by KurtStam** [comment]
https://github.com/syndesisio/syndesis/pull/1536 makes the default the database again

**Comment by KurtStam** [comment]
Working on some bugs but I think we can close the story.
