### ISSUE TITLE
Document REST API principles/style

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#1104]

**Comment by gashcrumb** [comment]
@zregvart are you really going to get a chance to do this?  Do you remember what the principles and style is now since this issue was raised?

:-)

**Comment by zregvart** [comment]
I think I can add a chapter to the Syndesis Developer Handbook that details the use of HTTP methods, showcases the use of mixins we use (from https://github.com/syndesisio/syndesis/tree/master/app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/operations) and how to properly raise/handle exceptions. I would like to do this, though I'm no Roland when it comes to writing documentation.

**Comment by gashcrumb** [comment]
Sounds good!  Probably anything is better than nothing :-)
