### ISSUE TITLE
Auto-generate REST API endpoints catalogue (eg: http://apidocjs.com/)

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#1105]

**Comment by zregvart** [comment]
I wonder what benefit apiDoc provides over Swagger we already use?

**Comment by deeleman** [comment]
> I wonder what benefit apiDoc provides over Swagger we already use?

TBH none, that was just a suggestion only, since I am not aware wether we're currently using Swagger UI or any other visual UI tool available for the developers to chime in.

If that's the case, I'd say we can close this issue (and I'd appreciate if someone shares the link w/ me)

**Comment by gashcrumb** [comment]
Yeah, like I've used swagger UI here and there more when we were using a staging server.  I've also in the past fetched the swagger json from the backend and pasted it into editor.swagger.io.

I wonder though, we don't actually check this into source control do we?  Like currently if I want to see the swagger, I have an instance of the rest API running, don't I?

I wonder if maybe the build should generate a swagger.json file that's checked into source control, then it's pretty easy to see when changes are made and what exactly those changes are, at least for starters.

**Comment by zregvart** [comment]
Created #1121, so closing this.
