### ISSUE TITLE
UXD to visualize Step ID

### ISSUE THREAD

**Issue by igarashitm** [syndesisio/syndesis#1111]
#1110 needs Steps to have an identifier (suggestion : step 1, step 2, …)
Step id should be visible in:
* Integration Visualization Panel (IVP)
* Collapsed IVP
* Data mapper source labels (e.g. Status (Step 1))

Need UX design showing step IDs

**Comment by dongniwang** [comment]
Reference: https://github.com/syndesisio/syndesis/issues/1138

**Comment by TovaCohen** [comment]
I'm seeing "Step 1", "Step 2", "Step 3" and so on in the UX designs for showing logging, integration visualization, and data mapper enhancements. These "Step n" labels are being applied to both connections and steps. Until now, a step was a data operation between connections. So I'm concerned that applying "Step n" labels to connections is going to cause confusion. In place of "Step n", could we use just a number, "1", "2", "3" and so on? In prompts and user doc, we could refer to these as "order IDs".

**Comment by igarashitm** [comment]
Hi @TovaCohen , IIRC we are considering to migrate Steps and Connections, i.e. Connection is going to be a kind of Steps. Until we implement it, wording might be unstable there...

**Comment by dongniwang** [comment]
@igarashitm @TovaCohen - Agreed with Tomo, there's a discussion a few weeks ago about consolidating both steps and connections together in the UI screen where users add additional steps/connections after configuring start and finish connections. We definitely want to review the wording here to make sure we are not causing unnecessary confusion. 

Adding @amysueg @sjcox-rh @kcbabo here for discussion.

**Comment by kcbabo** [comment]
Everything that happens in an integration flow is a step.  The "start" step and "finish" step are special in that they need to be connections (at least for now), but these are still steps.

**Comment by TovaCohen** [comment]
Issue to clarify the UI:
https://github.com/syndesisio/syndesis/issues/1530

**Comment by dongniwang** [comment]
UX design PR #1671 is created to address this. Please review.

**Comment by igarashitm** [comment]
#1671 has been merged. Thanks @dongniwang :+1:
