### ISSUE TITLE
Fix codacy quote rule for typescript files

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#1112]
Noticed on some of the open PRs the codacy check is failing with this:

```
' should be " 
```

Our tslint in the UI is set up the opposite, i.e. we want `'`.

**Comment by zregvart** [comment]
With #1146 Codacy should ignore the UI, I think we still need to fix this long term, but at least with this the annoyance should be lesser

**Comment by gashcrumb** [comment]
Nope
