### ISSUE TITLE
Upgrade Syndesis Infrastructure

### ISSUE THREAD

**Issue by kcbabo** [syndesisio/syndesis#1117]
As an expert integrator, I'm responsible for making sure my team's integration infrastructure is kept current with updates through one of the following update policies:
* Automatic - Syndesis infrastructure detects and installs updates as they are available.
* Manual - Syndesis infrastructure is only updated when I request it.

The default update policy should be automatic, but I should be able to change the update policy at the time my environment is installed/provisioned or at a later time.

The current version of Syndesis infrastructure should be visible in the Syndesis UI so I can keep track of which version of Syndesis is in use.  Updates always result in my environment upgrading to the most recent version, regardless of which version I was on prior to upgrade.

Syndesis infrastructure will not be available during an upgrade, but deployed integrations will continue to run.  A static "upgrade in progress" page should be served at the Syndesis UI during updates so that my team does not mistake an update for a general outage.

I should receive a notification when an update is available, including the scheduled update date/time in the event that automatic updates are enabled.  Automatic updates should be scheduled for times which minimize downtime (e.g. early Saturday AM).

**Comment by chirino** [comment]
@rhuss I think we also need an issue to upgrade an older version export's models when it's being imported into an new system.

**Comment by rhuss** [comment]
@chirino good point. You mean to allow an import of an older exported zip ? (by doing some transformations). 

It similar to the schema upgrade model, but should probably included directly in the import functionality. However the import could share the same logic like the update schema. A difference is with respect to the rollback, e.g. when on of the migration steps from one version to the next one fails. In the upgrade story, we simply restore the whole database backup, which we can't do when doing an import.

So the import transformations should happen in memory without writing to the db

**Comment by paoloantinori** [comment]
PR currently pending

**Comment by paoloantinori** [comment]
Hi @rhuss  could you provide an update on this story, in particular regarding the sub tasks  still pending?

**Comment by rhuss** [comment]
Yes, I will pick up the story again on Monday and consolidate the GitHub issues around it.

**Comment by heiko-braun** [comment]
Closed with 7.0
