### ISSUE TITLE
Upgrade integration runtime

### ISSUE THREAD

**Issue by kcbabo** [syndesisio/syndesis#1118]
As an expert integrator, I'm responsible for making sure that the runtime used in deployed integrations is kept current with updates.  Integration runtime updates should always be a manual process that I trigger through republishing an integration.  Publishing an integration should always use the most current version of the integration runtime available.

The runtime version of an integration should be visible in the Syndesis UI when viewing an integration, the currently published version and all prior revisions.  The UI should also indicate if an integration is not using the most recent available version of the integration runtime.

In the event of a failed integration update, I need the ability to republish a version of the integration from history that uses a prior version of the integration runtime.  In this case, publish should use the integration runtime version from that point in history and not the most current integration runtime version.

**Comment by lburgazzoli** [comment]
Follow up #2442
