### ISSUE TITLE
Check into the SCM REST API swagger.json

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#1121]
We should update `swagger.json` during the build and keep it up to date in git.

Taken from #1105

**Comment by gashcrumb** [comment]
It'd be nice too if we could tweak the swagger file to be more usable by clients -> #87

**Comment by gashcrumb** [comment]
Or another consideration, generate the swagger once, check it in, improve it and then later use it to generate the server-side and client-side models.
