### ISSUE TITLE
Add Prometheus Server to Syndesis templates

### ISSUE THREAD

**Issue by dhirajsb** [syndesisio/syndesis#1125]
Add a Docker image for Prometheus server to Syndesis template. The most critical requirement is that the server should be limited to a short duration of metrics being stored to reduce resource usage.

**Comment by zregvart** [comment]
I bet @jimmidyson has something ready for this.

**Comment by jimmidyson** [comment]
Already done in #1081

**Comment by jimmidyson** [comment]
Already done in #1081

**Comment by dhirajsb** [comment]
@jimmidyson is #1081 still wip? Also, review is pending for #1156 for the metrics API.

**Comment by zregvart** [comment]
#1081 was merged
