### ISSUE TITLE
[Upgrade] UX Design for Upgrade 

### ISSUE THREAD

**Issue by dongniwang** [syndesisio/syndesis#1128]

**Comment by amysueg** [comment]
See User Story here -- https://github.com/syndesisio/syndesis/issues/1117

**Comment by dongniwang** [comment]
User Story for [Upgrade integration runtime](https://github.com/syndesisio/syndesis/issues/1118)

**Comment by dongniwang** [comment]
Here's the [designs](https://redhat.invisionapp.com/share/CQGR6XBVF2B) for Upgrade. Please review.

**Comment by dongniwang** [comment]
Updated UX design available for review. Click [here](https://redhat.invisionapp.com/share/TMHF3EF9P3H) to review and provide your comments. Thank you! 

Updates include: 
- New design option for showing inline notificatino when a new runtime is available 
- Ability to filter for integrations that require a runtime update

@kcbabo @lburgazzoli @gashcrumb @paoloantinori @amysueg @sjcox-rh

FYI - UX Tracker https://syndesisio.github.io/syndesis-ux/

**Comment by kcbabo** [comment]
Looks great!  I prefer option 1 for the integration update notification page.

**Comment by gaughan** [comment]
Looks great. UX Approved by PM

**Comment by dongniwang** [comment]
@lburgazzoli 

- Modification Notes: Is this an easy addition to the integration editor? If not, I'm OK with leaving that out for now. 
- I recommend showing only one icon in the status column and the rule is to always the highest priority in the column (Error > Warning > Info). 

Can you explain a little bit more what do you mean by "disable an integration to be published if the runtime upgrade requires reconfiguration"? Currently, there are several things that could trigger "configuration required", e.g. Import an integration, connection configuration updates. 

cc: @gashcrumb

**Comment by lburgazzoli** [comment]
1. About Modification Notes, I think it is trivial but that's a question for @gashcrumb 
2. so that's mean that a configuration required ha higher priority than integration update right ? in that case I'm fine with the proposal.

**Comment by gashcrumb** [comment]
I think at least on a first pass I'd drive modification notes by generating them based on what changes were done in the editor.

Implementation-wise I'm not sure how filtering by notification on integrations is going to pan out, but we'll give it a go at least, so +1 from me overall.

**Comment by dongniwang** [comment]
Thanks @lburgazzoli and @gashcrumb. I'm going to mark the design as "Ready for Dev" in the UX tracker. 

Let me know if you encounter anything while implementing the design, I'm happy to work with you to find an alternative solution.

**Comment by dongniwang** [comment]
See latest UX design in [UX tracker](https://syndesisio.github.io/syndesis-ux/). Closing this issue.
