### ISSUE TITLE
Add prometheus jmx exporter config

### ISSUE THREAD

**Issue by dhirajsb** [syndesisio/syndesis#1129]
Add a JMX exporter config for prometheus to collect high level metrics for integrations.

**Comment by jimmidyson** [comment]
Don't these already exist? The default jmx exporter config exports camel metrics - see https://github.com/fabric8io-images/s2i/blob/master/java/images/jboss/prometheus-config.yml. What more do you need?

**Comment by dhirajsb** [comment]
@KurtStam we should discuss which mbeans and properties we want to monitor. We can use the [JON Camel plugin configuration](https://github.com/jboss-fuse/jon-plugins/blob/master/camel/src/main/resources/META-INF/rhq-plugin.xml) as a template for this.

**Comment by dhirajsb** [comment]
@jimmidyson the default config exposes practically everything in a Camel route. We will probably want to only get higher level metrics to reduce the number of metrics collected.

**Comment by jimmidyson** [comment]
Do it via relabeling config in Prometheus - that way can do it centrally
rather than reconfiguring every pod.
