### ISSUE TITLE
As a citizen integrator, access output data from all prior steps in an integration flow in a data mapping.

### ISSUE THREAD

**Issue by kcbabo** [syndesisio/syndesis#1132]
As a citizen integrator, I often need to combine multiple sources of data to create data needed for a step in an integration flow.  To address this use case, I need the ability to access data from all prior steps in an integrationn flow within a data mapping step.  Given the following integration flow ...

**Twitter (1) -> Log (2) -> Data Mapping (3) -> Database (4) -> Filter (5) -> Data Mapping (6)-> Tech Extension (7) -> Data Mapping (8) -> Salesforce (9)**

* Data Mapping at step (3) has access to data from step (1)
* Data Mapping at step (6) has access to data from steps (1,3,4)
* Data Mapping at step (8) has access to data from steps (1,3,4,6,7)

Data mapping is the only step at this time that can address multiple buckets of data.  Filter and other data-aware steps will only address the current data available in the integration flow (i.e. output of prior step).

To make it easier to associate data with specific steps in an integration flow, each step that produces output data should have a unique ID/index.  The ID should be visible in the following places:
* Main integration editor (Integration Visualization Panel or IVP)
* Data mapper source labels
* Collapsed IVP that is visible in the left frame of the data mapper

Changes to an integration flow (e.g. removing or adding a step between existing steps) should automatically update IDs as needed.

**Comment by rhuss** [comment]
@kcbabo So when you say a datamapper have access to the the output of other previous datamapper (which actually are the inputShapes of the following connector), doesn't this make the logic too complicated ?

If we would make available only the outputShapes of any previous connector / extension, you can still achieve  everything you describe. You just would need to re-add the mapping from a previous mapping if you want to access this data (but I might have not understood it correctly).

**Comment by kcbabo** [comment]
@rhuss data mapper has access to all output data produced from prior steps, whether it was a data mapping step or not.  That seems easier, more consistent to me, but I may be overlooking an important runtime detail as I'm prone to do. ;-)

**Comment by igarashitm** [comment]
@kcbabo do you think ATM it's not really important to produce multiple documents via datamapper? Say JMS (10) with a different data shape. Are we going to induce customers to put a separate datamapper step for it?

**Comment by kcbabo** [comment]
Yeah, I'm cool with single output for data mapper.  As you mentioned, this means you need a data mapper step for each output you want to create.

**Comment by igarashitm** [comment]
It turned out that the datamapper step doesn't have action, i.e. it doesn't hold any DataShape behind the scene. Not yet sure about other steps. Do we want to add action into datamapper step internally and get it involved?

@gashcrumb do you know if we are adding action for filter step or not? if yes where in the code?

**Comment by gashcrumb** [comment]
no, not for either filter steps, but yeah, probably adding `action` to the data mapper step and following the same object format should do the job really.

**Comment by igarashitm** [comment]
I'm not yet really sure if it helps users, allowing datamapper output as an input of subsequent datamapper (datamapper chaining). @kcbabo if the original intention was to simplify things, we can leave it as-is for now, i.e. not involve datamapper output. Ah but we still want output of filter step?

**Comment by igarashitm** [comment]
nope, Keith's original story doesn't involve filter output (5)  :-)

**Comment by igarashitm** [comment]
Oh wait, if we don't have data shapes on some of steps, it's going to be hard to provide data type mismatch indicator (#700)...

**Comment by igarashitm** [comment]
So 
* Any step changing data shape should define data shapes on its action
   * datamapper step should have input/output data shape on its action. filter is not
* Any step defines output data shape appears in subsequent datamapper step

Then data shape mismatch indicator can look at the Step.action.descriptor.{input,output}DataShape. No action means it doesn't change data shape.

**Comment by igarashitm** [comment]
Now we support this usecase, closing.
