### ISSUE TITLE
Assign unique IDs to steps when they're added to an integration

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#1133]
As part of data bucket support we'll need to add unique IDs to each step in an integration so that the data mapper and potentially other components can correlate this ID to the data shapes.

Related to #1110 

Created from #1114

**Comment by gashcrumb** [comment]
One note this will have a backend part too as the `Step` model needs to support having an `id` attribute if it doesn't already.

**Comment by lburgazzoli** [comment]
@gashcrumb Step already support ID, there will be  a new Metadata object (as a simple key/map) that can be used to associate arbitrary data to a step.

**Comment by igarashitm** [comment]
In current-flow.service.ts, they are generating Step ID via `createStepWithId()` so we can just use it. closing.
