### ISSUE TITLE
As a citizen integrator, specify data type when a connector doesn't provide one

### ISSUE THREAD

**Issue by kcbabo** [syndesisio/syndesis#1134]
As a citizen integrator, I want to use type-aware functionality in Syndesis (e.g. data mapper, filter) with connectors that don't have a native data type (e.g. AMQ, S3).  To address this gap, I need the ability to specify data type information when I use a typeless connection in an integration.  The following use cases need to be addressed:
* Specifying the output type for a typless connection in the Start step
* Specifying the input and output type for a typeless connection used between Start and Finish
* Specifying the input type for a typless connection used in the Finish step

I expect to be able to be able to specify type information when I configure the connection action in the integration flow.  Type configuration should allow me to select from the following data type descriptions for input and/or output:

JSON schema
JSON instance document
XML schema
XML instance document

Configuration of the data type should only be offered when the connector defines an input/output as untyped.

In some cases, I'm perfectly happy to use typeless connections without specifying data types, so specification of a data type should be an optional part of connection configuration.

**Comment by paoloantinori** [comment]
closing this since this since it is just the user story.

overall progress are seen on the enclosing epic
