### ISSUE TITLE
Pass step indicies along with step IDs to data mapper

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#1137]
We need to pass along a list of steps to the data mapper that have data shapes, along with their index in the integration flow, step ID and output data shape.  Might be worth building a new structure like:

```javascript
{
output: {
  name: 'Salesforce',
  id: '<generated>',
  dataShape: {}   // <-- input data shape of next step goes here
},
inputs: {
  steps: [
    {
       name: 'Twitter',
       id: '<generated>',
       dataShape: {} // <-- output data shape of this step
    },
    {
        name: 'Database',
        id: '<generated>',
        dataShape: {} // <-- output data shape of this step
     }
  ]
 }
}
```

This can then be passed as an input to the data mapper host component.

Related to #1110

Created from #1114

**Comment by igarashitm** [comment]
How about adding `CurrentFlow.getPreviousStepsWithOutputDataShape(position)` ? I'll give it a shot.

**Comment by gashcrumb** [comment]
So yeah, really if we just inject the CurrentFlow service into the host component this issue can be closed, as the host component should then have everything it needs.  The parent controller only needs to pass along the position in the flow the user is looking at then.
