### ISSUE TITLE
Show step index on integration visualization panel

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#1138]
We'll want some indicator of a step's actual position in the flow so that the user has some correlation between the integration visualization in the editor and the data mapper UI.

This will require some UXD input, also not sure if the indices should also be visible from the integration detail view, I kinda think not :-).

Related to #1110

Created from #1114

**Comment by dongniwang** [comment]
@gashcrumb - when you say "a step's actual position", is that different from just "step 1, step 2, step 3..."? 

And the integration detail view, you're referring to the page with integration version history, right?

**Comment by gashcrumb** [comment]
> @gashcrumb - when you say "a step's actual position", is that different from just "step 1, step 2, step 3..."?

Right, I don't know why I worded it that way now :-)  Just that we should number the steps somehow in the view.

> And the integration detail view, you're referring to the page with integration version history, right?

Correct!

**Comment by igarashitm** [comment]
@dongniwang This one and #1111 are to address same thing, so you may want to pick one of them for UXD and I'll take the other for applying UXD outcome in the UI :-)
