### ISSUE TITLE
[Describe Data Shape] UX design for describe data shape 

### ISSUE THREAD

**Issue by dongniwang** [syndesisio/syndesis#1139]
Update existing UX design so describe data shape is part of the action config. in create integration workflow. 

User Story: https://github.com/syndesisio/syndesis/issues/1134

**Comment by dongniwang** [comment]
@dhirajsb - for the copy and paste option, is it only available when users selects json instance document, and therefore, users don't need to specify root element for it?  

Right now, users can either upload, import via URL, or import via copy and paste.

**Comment by dhirajsb** [comment]
@dongniwang as we discussed on irc, copy past should be valid for both schema and instance docs. For schema docs, user must specify which root element to use.

**Comment by dongniwang** [comment]
@dhirajsb - thank you! That's addressed in the UX design PR #1194. 

Closing this issue since PR is merged.
