### ISSUE TITLE
Editing datamapper: can't cancel changes easilly when editing integration

### ISSUE THREAD

**Issue by tplevko** [syndesisio/syndesis#1149]
There is an issue with datamapper editing. I can't easily remove the changes I made, the only way to cancel them is to exit the Integration editing completely. The issue:
![out](https://user-images.githubusercontent.com/4180208/35156426-17c8bd18-fd31-11e7-8bcd-6dc5ba514bcf.gif)

The biggest problem however with this issue is, that when I don't exit the integration editing, and I hit "edit integration", even though I hit cancel before in the datamapper editing section, the new integration contains the changes in datamapper.

**Comment by gashcrumb** [comment]
Yeah, definitely need a 'Cancel' button next to that 'Done' button.  I think at the moment, as changes are made in the datamapper UI we go and update the step right away in the integration.  So another change for this is to not do that and instead maintain the changes in the host component, and then only commit that to the step when 'Done' is clicked.

**Comment by tplevko** [comment]
I think I also noticed one thing related to this: 
![out](https://user-images.githubusercontent.com/4180208/35322517-e5406932-00ea-11e8-80be-4434b6430c3b.gif)

I think it's related. When editing some other steps (as shown the basic filter), whe I hit the cancel button, it works as expected. But in the case of datamapper, after I hit cancel, the datamapper remains in the edited integration.
