### ISSUE TITLE
Import/Export: UI: Import a Single Integration

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis#1153]
## Overview
Add missing UI logic to implement adjustments based on finalized UXD for Import feature (part of the Import/Export epic). Here we need to support the ability to import a single Integration.

## To Do

Architectural Setup: (PR #1254 )
- [x] IntegrationImport service
- [x] Parent module
- [x] Parent template setup
- [x] Child component
- [x] Child template setup
- [x] Models for single import upload
- [x] Reducer for single import upload
- [x] Actions for single import upload
- [x] Effects
- [x] Routing
~~Extend existing Integration model and store to support import.~~ (probably not necessary)

Feature Implementation:
- [x] Cancel and redirect modal
- [x] File upload setup
- [ ] Review page
- [ ] Upload validation
- [ ] Toast notification on upload
- [ ] Handle new Connections in component & template
- [ ] Actions for import edit after upload
- [ ] Reducer for import edit
- [ ] Models for import edit
- [ ] API wiring

Additional:
- [ ] Demo video
- [ ] Unit tests
- [ ] Docs

Once these are in place they will be re-used for Multiple Integration.

cc @chirino 

## Relevant Designs

Full UX Designs: https://github.com/syndesisio/syndesis/blob/master/ux/designs/importexport/importexport.md

![](https://github.com/syndesisio/syndesis/raw/master/ux/designs/importexport/img/import.png)

![](https://github.com/syndesisio/syndesis/raw/master/ux/designs/importexport/img/importdrop.png)

![](https://github.com/syndesisio/syndesis/raw/master/ux/designs/importexport/img/inprogress.png)

![](https://github.com/syndesisio/syndesis/raw/master/ux/designs/importexport/img/uploaderror.png)

![](https://github.com/syndesisio/syndesis/raw/master/ux/designs/importexport/img/uploadsuccessful.png)

![](https://github.com/syndesisio/syndesis/raw/master/ux/designs/importexport/img/importerror.png)

![](https://github.com/syndesisio/syndesis/raw/master/ux/designs/importexport/img/importsuccessful.png)

## Relevant Stuff
- [InVision: Design](https://redhat.invisionapp.com/share/7GFAZ8C24#/screens/273121651)
- Original GH issue for the UI work: https://github.com/syndesisio/syndesis/issues/1053
- UI Issue for Importing Multiple Integrations: #1154
- UI Issue for Exporting Integrations: #1155
- UXD PR for changes: https://github.com/syndesisio/syndesis/pull/1140
- Add an API to find out if "Additional Configuration" for an Integration or Connection: https://github.com/syndesisio/syndesis/issues/1052

**Comment by chirino** [comment]
@kahboom what's the status of this?

**Comment by kahboom** [comment]
@chirino - When you import an integration that already exists, and apparently it does not duplicate the integration, is that because it does not get imported/persisted at all (because of, for instance, a unique identifier conflict), or because it just replaces the existing integration?

Either way, this should be apparent to the user. It may be useful to provide an error during the validation process. cc @sjcox-rh @dongniwang

**Comment by sjcox-rh** [comment]
@kahboom @chirino When exactly is the validation process, when the user uploads an integration using the drag and drop import box, or when the user uploads and is taken to the integration summary page?

Either way, if this is really the case, I agree there should be an error message for this use case. 

Either one of these, I'm just not sure where it would be more appropriate. I'm leaning towards the integration detail page.

<img width="799" alt="screen shot 2018-02-16 at 7 35 27 am" src="https://user-images.githubusercontent.com/16257540/36315384-64413da2-12ec-11e8-9a66-f8694d869f0f.png">

<img width="920" alt="screen shot 2018-02-16 at 7 35 43 am" src="https://user-images.githubusercontent.com/16257540/36315388-67c9dfe2-12ec-11e8-9548-fef05a052bd0.png">

**Comment by kahboom** [comment]
Carrying on the conversation here: #1639

@chirino - I'll be opening a separate issue for this and a few outstanding items as well, to make it easier to track the epic.

**Comment by chirino** [comment]
@kahboom imports create or update integrations. The import result object tells you if it did a create or an update along with the id of the integration or connection

**Comment by kahboom** [comment]
@chirino I know that, but the designs require an additional review and subsequent editing step that right now are not in place. It's easier to break it up than to ball it all into one big issue imho.
