### ISSUE TITLE
Import/Export: UI: Import Multiple Integrations

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis#1154]
## Overview
Add missing UI logic to implement adjustments based on finalized UXD for Import feature (part of the Import/Export epic). Here we need to support the ability to import multiple Integrations.

There will be a lot of code re-use code from Single Integrations (reducers, models, actions), extending as necessary. #1153

## To Do

Architectural Setup:
- [x] Adjust IntegrationImport service to support multi-import upload
~~Adjust child component to support multi-upload*~~
- [x] Adjust child template to support multi-upload
- [x] Adjust models to support multi-import upload
~~Adjust reducer to support multi-import upload*~~
~~Adjust actions to support multi-import upload*~~
~~Adjust effects to support multi-import upload*~~

* Refer to this issue #1650 

Feature Implementation:
- [x] Adjust file uploader to support multi-import upload
- [x] Toast notification on upload* (see #1545 )
- [x] API wiring

### Relevant Designs

Full UX Designs: https://github.com/syndesisio/syndesis/blob/master/ux/designs/importexport/importexport.md

![](https://github.com/syndesisio/syndesis/raw/master/ux/designs/importexport/img/importmultiple.png)

![](https://github.com/syndesisio/syndesis/raw/master/ux/designs/importexport/img/reviewmultiple.png)

![](https://github.com/syndesisio/syndesis/raw/master/ux/designs/importexport/img/reviewmultipleexpand.png)

![](https://github.com/syndesisio/syndesis/raw/master/ux/designs/importexport/img/importlist.png)

## Relevant Stuff
- [InVision: Design](https://redhat.invisionapp.com/share/7GFAZ8C24#/screens/273121651)
- Original GH issue for the UI work: https://github.com/syndesisio/syndesis/issues/1053
- UI Issue for Importing a Single Integration: #1153 
- UI Issue for Exporting Integrations: #1155
- UXD PR for changes: https://github.com/syndesisio/syndesis/pull/1140
- API PR for exporting multiple integrations: https://github.com/syndesisio/syndesis/pull/1022
- Add an API to find out if "Additional Configuration" for an Integration or Connection: https://github.com/syndesisio/syndesis/issues/1052

@chirino :
>We just need an additional API to query if "Additional Configuration" is required for integrations/connections #1052. But I think UI impl can make progress without this implemented yet.

**Comment by chirino** [comment]
@kahboom what's the status of this?  Got screenshots?
