### ISSUE TITLE
Refactor Salesforce connectors as new simplified connectors

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#1166]
See #765

**Comment by rhuss** [comment]
actually this should be done for every connector which we want to maintain.

However, I have a question around the usage of `camel-connector-maven-plugin`, as it used in _old style_ connectors, but also in `rest-swagger-connector`: Does it have to generate code below `src/main/` (i.e. the spring-boot stuff ?). This poses a severe headache, especially for releasing stuff. Actually I reall would like to keep out all generated code from `src/main`.

@lburgazzoli any ideas ?

**Comment by lburgazzoli** [comment]
At the moment the `camel-connector-maven-plugin` does write stuffs in `src/main` but the new connector do not need such things so once we have all the connectors migrated we should not have this issue anymore. 

I'm working on salesforce migration at the moment.

**Comment by lburgazzoli** [comment]
@zregvart can we close this or is there anything I missed ?

**Comment by zregvart** [comment]
We're done here. Thanks @lburgazzoli :100:
