### ISSUE TITLE
[Custom connectors] Allow extension developers to provide a icon for connectors

### ISSUE THREAD

**Issue by nicolaferraro** [syndesisio/syndesis#1177]
A icon can be embedded in the jar file and then used by syndesis when displaying the connector.

**Comment by zregvart** [comment]
@nicolaferraro here _users_ are the custom connector developers? We already have endpoints for users to set/upload icons for connectors if that's of any help here.

**Comment by nicolaferraro** [comment]
Yes @zregvart, I meant custom connector developers. The best user experience would be to allow them to embed the icon in the package, so they don't have to upload it separately.

We may use the icon endpoints under the hood to do the job.
