### ISSUE TITLE
Box Connector

### ISSUE THREAD

**Issue by rohanmars** [syndesisio/syndesis#1188]
Implement Box connector component.

**Comment by rohanmars** [comment]
The current camel box component doesn't support OAUTH providing an accessToken on the URL, which means it's not a straight forward integration path into Syndesis. Currently, the component takes the username/password for the end user within the URI and then preforms it's own OAUTH flow.  It's not possible to capture the client id and secret using syndesis OAUTH settings as this confuses the inbuilt flow. The user and enterprise auth modes of the box component have additional problems, namely in that they are hardcoded to look for key files on disk.

This connector ideally needs upstream box component optimizations for it to work within the Syndesis OAUTH framework.

**Comment by mastepan** [comment]
QE will verify issues related to this epic. Closing.
