### ISSUE TITLE
datamapper should only work on latest data instance of same data shape

### ISSUE THREAD

**Issue by igarashitm** [syndesisio/syndesis#1191]
~~Camel Message body is possibly modified in the middle of integration flow at runtime. But we can't make a deep copy for every step/connection as it wastes lots of memory. In order to capture the "old" message which is supposed to be modified in the following step/connection, we need to provide "preserve output message" option for each step/connection, so that the user can explicitly enable it only for required one.~~

~~UXD question: how do we provide that option? A checkbox on each step/connection?~~

Changed the direction - see https://github.com/syndesisio/syndesis/issues/1191#issuecomment-395865495 and https://github.com/syndesisio/syndesis/issues/1191#issuecomment-395871961

**Comment by igarashitm** [comment]
We don't do this at first place. Let's go forward without this and see.

**Comment by igarashitm** [comment]
No that's not gonna work well as String is not Clonable...

**Comment by igarashitm** [comment]
Copying a comment from Hiram on #1115:
> Even cloning is not guaranteed to be a deep copy. Best solution would be to serialize/marshal to store the body and then deserialize/unmarshal to get it back. Not all bodys can be serialized. Perhaps we should create explicit steps that can do the marshal/unmarshal.

**Comment by amysueg** [comment]
Is this an option for configuration when creating a new connection?  Or is this a system-wide configuration? @chirino @igarashitm

**Comment by igarashitm** [comment]
@amysueg sorry for messing it up, but we decided to defer this one for now, so I removed this one from #1110 Data Buckets Epic. This is something for post GA.

**Comment by igarashitm** [comment]
Oops sorry, I was supposed to answer the question as well. This is an option for the action configuration which has output data shape.

**Comment by amysueg** [comment]
We need a use case for this enhancement request, @kcbabo . Not sure we want to add a checkbox to a form for something that is infrequently or rarely done.

**Comment by kcbabo** [comment]
I don't think we need to keep a copy of a given message's state at each step.  We should just keep each different type of object for use by data mapper.  IOW, if I have org.Foo and org.Bar in my integration flow and org.Foo is modified in two steps, there should still only be one entry for org.Foo in the data mapper.

**Comment by kcbabo** [comment]
The way I phrased my earlier comment was a bit confusing.  What I mean is that any given data shape name should only show up in the mapper once.  If outputs of multiple steps have the same data shape name, then the mapper should only use the data for that name from the most recent step.

This avoids any requirement for a user to mark data output to be saved.  Users will always get the "latest" version of data for any given data shape name involved in an integration flow.

**Comment by igarashitm** [comment]
So syndesis would need to have some flag on each steps, whether it produces new data shape or work on existing data shape. If there's latter, datamapper should only pick up the last one. This is still UI but internal model, so removing uxd label.
