### ISSUE TITLE
Add `controls` attribute alongside connector form definitions

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#1204]
Ideally we should just define the control order as part of the form definition, otherwise this switch/case is gonna get kinda big:

https://github.com/syndesisio/syndesis/pull/1202/files#diff-28b4a582e947fd283b192ca194ed84b5R48

So next to `properties` I propose having `controls` which is an array of ids from the `properties` map, the UI can use this in several places to guarantee the control order of forms.

**Comment by lburgazzoli** [comment]
@gashcrumb would it make sense to add an index field instead ? We can use the same logic also for Steps and maybe other collection like stuffs. The java model would be something like:

```java
interface WithIndex {
    Optional<Integer> getIndex();
}

interface Step extends WithIndex {
}

interface ConfigurationProperty extends WithIndex {
}
```

UI could then sort properties according to the index and properties with no index are sorted Lexicographical after those with index.

**Comment by gashcrumb** [comment]
I think that'd work fine too :-)

**Comment by zregvart** [comment]
I would not use _index_ as a term for this, might collide with the persistence layer, I would prefer _order_.

**Comment by gashcrumb** [comment]
good point.  `order`, `position`, `priority` whatever works :-)

**Comment by lburgazzoli** [comment]
so let's have `Ordered` ?

**Comment by lburgazzoli** [comment]
Will work on it

**Comment by gashcrumb** [comment]
Lemme reopen this and get a PR for the UI side of things, then this can be closed.
