### ISSUE TITLE
Change heading for custom step config to match heading for builtin step config

### ISSUE THREAD

**Issue by TovaCohen** [syndesisio/syndesis#1208]
After you upload an extension so that you have a custom step, and after you choose that custom step to add it to an integration, the configuration page (if needed) for the custom step had the heading "Configure Extension":
![configureextension](https://user-images.githubusercontent.com/25067106/35341951-de861876-00f4-11e8-957f-98e0ba15610f.png)

For TP4, can this change to have the format **Configure** _action-name_ **Step**, which would be parallel with the heading for built-in steps:
![configurebasicfilterstep](https://user-images.githubusercontent.com/25067106/35341959-e143c626-00f4-11e8-8307-758f4b2049ce.png)

For example, if the name of the custom step is Enrich Data, then the page heading would be "**Configure Enrich Data Step**". If this is not possible, then please change "**Configure Extension**" to "**Configure Custom Step**".

**Comment by lburgazzoli** [comment]
@syndesisio/ui-api do anyone have some spare time to look at this ?
