### ISSUE TITLE
AMQP Connector for enMaase and AMQ7

### ISSUE THREAD

**Issue by dhirajsb** [syndesisio/syndesis#1216]
The AMQP connector will be similar to the AMQ connector, except it should use AMQP protocol instead of OpenWire. 
It should support all the same operations as the AMQ user story. As long as an `amqp(s)` connection URI is provided for an enMaase install, no other special configuration should be needed.

**Comment by dhirajsb** [comment]
@kcbabo do you want to create a skeleton user store for this, which just references AMQ connector. 
The only differences I have so far is that AMQP uses the term `connectionUri` instead of `brokerUrl`. All other actions and options are the same, ignoring AMQP specific options, which might be too much for a Citizen Integrator anyway.

**Comment by kcbabo** [comment]
Yep, can do.  I'm fine with basic options at first.  We can add more advanced stuff based on feedback and use cases.

**Comment by dhirajsb** [comment]
Implemented support for PEM certificates with #1571

**Comment by dhirajsb** [comment]
Reopening until the UI issues discovered from UX review #1683 are fixed.

**Comment by dhirajsb** [comment]
@paoloantinori there is an open issue about reordering field #1696, which I'll fix today. I'll re-close this epic after that issue is resolved.

**Comment by paoloantinori** [comment]
great, thank you!

**Comment by paoloantinori** [comment]
Hey Dhiraj, any update on this epic?

**Comment by dhirajsb** [comment]
Re-closing issue as pending UI issues have been resolved.
