### ISSUE TITLE
Relax Codacy Rule: Avoid catching generic exceptions such as NullPointerException, RuntimeException, Exception in try-catch block

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis#1219]
This code style is useful and very common.

![syndesis_-_codacy_-_pullrequests](https://user-images.githubusercontent.com/103255/35349311-9b84e930-0108-11e8-98cb-aa12279c1043.jpg)

**Comment by gashcrumb** [comment]
Stale
