### ISSUE TITLE
Relax Codacy Rule: Avoid assignments in operands

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis#1221]
Example:

https://www.codacy.com/app/zregvart/syndesis/file/14074711020/issues/source?bid=6285454&fileBranchId=6285458#l128

The 'while( (c=is.read())>=0 )' is a classic how to read an input stream expression.  Everyone should instantly recognize what it's doing.

**Comment by gashcrumb** [comment]
Stale
