### ISSUE TITLE
Enable support for broker and client PEM certificates in AMQP Connector

### ISSUE THREAD

**Issue by dhirajsb** [syndesisio/syndesis#1225]
Camel AMQP connector doesn't provide an easy way of configuring Broker and Client certificates for SSL `amqps` connections. 
A workaround is to use the following options in the underlying AMQP client and add them on the connection URL in the connector:
* transport.keyStoreLocation - default is to read from the system property "javax.net.ssl.keyStore"
* transport.keyStorePassword - default is to read from the system property "javax.net.ssl.keyStorePassword"
* transport.trustStoreLocation - default is to read from the system property "javax.net.ssl.trustStore"
* transport.trustStorePassword - default is to read from the system property "javax.net.ssl.trustStorePassword"

This requires creating _temporary_ trust stores within the connector, storing them in temporary local files and adding these options to the connection URL. 

This workaround may go away in the future, when Syndesis supports adding TLS certificates using secrets.

**Comment by zregvart** [comment]
@dhirajsb I think this was done, right?
