### ISSUE TITLE
[UI] Broken.  net::ERR_INSECURE_RESPONSE

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis#1232]
Multiple occurrences of ` net::ERR_INSECURE_RESPONSE` errors break the UI in multiple places.

The skeleton of the page is there but many features do not work, as a side effect of those errors.

```
polyfills.bundle.js:7828 GET https://syndesis.192.168.42.160.nip.io/api/v1/users net::ERR_INSECURE_RESPONSE
```

<details>
  <summary>Click to expand</summary>
<pre><code>
core.es5.js:1020 ERROR {message: "An unexpected HTTP error occured. Please check stack strace", debugMessage: "An unexpected HTTP error occured. Please check stack strace", status: undefined}
defaultErrorLogger @ core.es5.js:1020
webpackJsonp.../../../core/@angular/core.es5.js.ErrorHandler.handleError @ core.es5.js:1080
next @ core.es5.js:4503
schedulerFn @ core.es5.js:3635
webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:238
webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.next @ Subscriber.js:185
webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber._next @ Subscriber.js:125
webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber.next @ Subscriber.js:89
webpackJsonp.../../../../rxjs/Subject.js.Subject.next @ Subject.js:55
webpackJsonp.../../../core/@angular/core.es5.js.EventEmitter.emit @ core.es5.js:3621
(anonymous) @ core.es5.js:3912
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ polyfills.bundle.js:6016
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run @ polyfills.bundle.js:5776
webpackJsonp.../../../core/@angular/core.es5.js.NgZone.runOutsideAngular @ core.es5.js:3844
onHandleError @ core.es5.js:3912
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.handleError @ polyfills.bundle.js:6020
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask @ polyfills.bundle.js:5819
ZoneTask.invoke @ polyfills.bundle.js:6111
XMLHttpRequest.send (async)
scheduleTask @ polyfills.bundle.js:7828
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ polyfills.bundle.js:6035
onScheduleTask @ polyfills.bundle.js:5925
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ polyfills.bundle.js:6029
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleTask @ polyfills.bundle.js:5860
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleMacroTask @ polyfills.bundle.js:5883
(anonymous) @ polyfills.bundle.js:7852
send @ VM1171:3
(anonymous) @ common-http.umd.js:1815
webpackJsonp.../../../../rxjs/Observable.js.Observable._trySubscribe @ Observable.js:171
webpackJsonp.../../../../rxjs/Observable.js.Observable.subscribe @ Observable.js:159
subscribeToResult @ subscribeToResult.js:22
webpackJsonp.../../../../rxjs/operator/mergeMap.js.MergeMapSubscriber._innerSub @ mergeMap.js:130
webpackJsonp.../../../../rxjs/operator/mergeMap.js.MergeMapSubscriber._tryNext @ mergeMap.js:127
webpackJsonp.../../../../rxjs/operator/mergeMap.js.MergeMapSubscriber._next @ mergeMap.js:110
webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber.next @ Subscriber.js:89
webpackJsonp.../../../../rxjs/observable/ScalarObservable.js.ScalarObservable._subscribe @ ScalarObservable.js:49
webpackJsonp.../../../../rxjs/Observable.js.Observable._trySubscribe @ Observable.js:171
webpackJsonp.../../../../rxjs/Observable.js.Observable.subscribe @ Observable.js:159
webpackJsonp.../../../../rxjs/operator/mergeMap.js.MergeMapOperator.call @ mergeMap.js:85
webpackJsonp.../../../../rxjs/Observable.js.Observable.subscribe @ Observable.js:156
webpackJsonp.../../../../rxjs/operator/filter.js.FilterOperator.call @ filter.js:58
webpackJsonp.../../../../rxjs/Observable.js.Observable.subscribe @ Observable.js:156
webpackJsonp.../../../../rxjs/operator/map.js.MapOperator.call @ map.js:54
webpackJsonp.../../../../rxjs/Observable.js.Observable.subscribe @ Observable.js:156
webpackJsonp.../../../../rxjs/operator/catch.js.CatchOperator.call @ catch.js:79
webpackJsonp.../../../../rxjs/Observable.js.Observable.subscribe @ Observable.js:156
webpackJsonp.../../../common/@angular/common.es5.js.ObservableStrategy.createSubscription @ common.es5.js:2628
webpackJsonp.../../../common/@angular/common.es5.js.AsyncPipe._subscribe @ common.es5.js:2742
webpackJsonp.../../../common/@angular/common.es5.js.AsyncPipe.transform @ common.es5.js:2719
(anonymous) @ AppComponent.html:125
debugUpdateRenderer @ core.es5.js:13105
checkAndUpdateView @ core.es5.js:12256
callViewAction @ core.es5.js:12599
execEmbeddedViewsAction @ core.es5.js:12557
checkAndUpdateView @ core.es5.js:12252
callViewAction @ core.es5.js:12599
execEmbeddedViewsAction @ core.es5.js:12557
checkAndUpdateView @ core.es5.js:12252
callViewAction @ core.es5.js:12599
execComponentViewsAction @ core.es5.js:12531
checkAndUpdateView @ core.es5.js:12257
callWithDebugContext @ core.es5.js:13467
debugCheckAndUpdateView @ core.es5.js:13007
webpackJsonp.../../../core/@angular/core.es5.js.ViewRef_.detectChanges @ core.es5.js:10174
(anonymous) @ core.es5.js:4812
webpackJsonp.../../../core/@angular/core.es5.js.ApplicationRef_.tick @ core.es5.js:4812
webpackJsonp.../../../core/@angular/core.es5.js.ApplicationRef_._loadComponent @ core.es5.js:4787
webpackJsonp.../../../core/@angular/core.es5.js.ApplicationRef_.bootstrap @ core.es5.js:4775
(anonymous) @ core.es5.js:4546
webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_._moduleDoBootstrap @ core.es5.js:4546
(anonymous) @ core.es5.js:4508
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ polyfills.bundle.js:6016
onInvoke @ core.es5.js:3890
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ polyfills.bundle.js:6015
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run @ polyfills.bundle.js:5776
(anonymous) @ polyfills.bundle.js:6411
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask @ polyfills.bundle.js:6049
onInvokeTask @ core.es5.js:3881
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask @ polyfills.bundle.js:6048
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask @ polyfills.bundle.js:5816
drainMicroTaskQueue @ polyfills.bundle.js:6244
ZoneTask.invoke @ polyfills.bundle.js:6115
XMLHttpRequest.send (async)
scheduleTask @ polyfills.bundle.js:7828
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ polyfills.bundle.js:6035
onScheduleTask @ polyfills.bundle.js:5925
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ polyfills.bundle.js:6029
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleTask @ polyfills.bundle.js:5860
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleMacroTask @ polyfills.bundle.js:5883
(anonymous) @ polyfills.bundle.js:7852
send @ VM1171:3
(anonymous) @ common-http.umd.js:1815
webpackJsonp.../../../../rxjs/Observable.js.Observable._trySubscribe @ Observable.js:171
webpackJsonp.../../../../rxjs/Observable.js.Observable.subscribe @ Observable.js:159
subscribeToResult @ subscribeToResult.js:22
webpackJsonp.../../../../rxjs/operator/mergeMap.js.MergeMapSubscriber._innerSub @ mergeMap.js:130
webpackJsonp.../../../../rxjs/operator/mergeMap.js.MergeMapSubscriber._tryNext @ mergeMap.js:127
webpackJsonp.../../../../rxjs/operator/mergeMap.js.MergeMapSubscriber._next @ mergeMap.js:110
webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber.next @ Subscriber.js:89
webpackJsonp.../../../../rxjs/observable/ScalarObservable.js.ScalarObservable._subscribe @ ScalarObservable.js:49
webpackJsonp.../../../../rxjs/Observable.js.Observable._trySubscribe @ Observable.js:171
webpackJsonp.../../../../rxjs/Observable.js.Observable.subscribe @ Observable.js:159
webpackJsonp.../../../../rxjs/operator/mergeMap.js.MergeMapOperator.call @ mergeMap.js:85
webpackJsonp.../../../../rxjs/Observable.js.Observable.subscribe @ Observable.js:156
webpackJsonp.../../../../rxjs/operator/filter.js.FilterOperator.call @ filter.js:58
webpackJsonp.../../../../rxjs/Observable.js.Observable.subscribe @ Observable.js:156
webpackJsonp.../../../../rxjs/operator/map.js.MapOperator.call @ map.js:54
webpackJsonp.../../../../rxjs/Observable.js.Observable.subscribe @ Observable.js:156
(anonymous) @ toPromise.js:68
ZoneAwarePromise @ polyfills.bundle.js:6427
toPromise @ toPromise.js:66
webpackJsonp.../../../../../src/app/config.service.ts.ConfigService.initialize @ config.service.ts:22
(anonymous) @ config.service.ts:81
webpackJsonp.../../../core/@angular/core.es5.js.ApplicationInitStatus.runInitializers @ core.es5.js:2807
(anonymous) @ core.es5.js:4506
_callAndReportToErrorHandler @ core.es5.js:4406
(anonymous) @ core.es5.js:4504
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ polyfills.bundle.js:6016
onInvoke @ core.es5.js:3890
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ polyfills.bundle.js:6015
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run @ polyfills.bundle.js:5776
webpackJsonp.../../../core/@angular/core.es5.js.NgZone.run @ core.es5.js:3821
webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_._bootstrapModuleFactoryWithZone @ core.es5.js:4495
(anonymous) @ core.es5.js:4537
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ polyfills.bundle.js:6016
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run @ polyfills.bundle.js:5776
(anonymous) @ polyfills.bundle.js:6411
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask @ polyfills.bundle.js:6049
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask @ polyfills.bundle.js:5816
drainMicroTaskQueue @ polyfills.bundle.js:6244
Promise resolved (async)
scheduleQueueDrain @ polyfills.bundle.js:6203
scheduleMicroTask @ polyfills.bundle.js:6211
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ polyfills.bundle.js:6038
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleTask @ polyfills.bundle.js:5860
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleMicroTask @ polyfills.bundle.js:5880
scheduleResolveOrReject @ polyfills.bundle.js:6409
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneAwarePromise.then @ polyfills.bundle.js:6498
webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_._bootstrapModuleWithZone @ core.es5.js:4537
webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_.bootstrapModule @ core.es5.js:4522
../../../../../src/main.ts @ main.ts:12
__webpack_require__ @ inline.bundle.js:55
3 @ polyfills.ts:19
__webpack_require__ @ inline.bundle.js:55
webpackJsonpCallback @ inline.bundle.js:26
(anonymous) @ main.bundle.js:1
</code></pre>
</details>

It looks like the first error happens here:

```
(anonymous) | @ | config.service.ts:81
```

```
export function appConfigInitializer(configService: ConfigService): () => Promise<ConfigService> {
  return () => configService.initialize();
}
```

**Comment by paoloantinori** [comment]
It might be the effect of an out of sync `config.json`

```
{
  "commment":"This config should for testing against a minishift using the syndesis-dev application templates.",
  "apiBase": "https://syndesis.192.168.42.160.nip.io",
  "apiEndpoint": "/api/v1",
  "mapperEndpoint": "/mapper/v1",
  "branding": {
    "logoWhiteBg": "assets/images/syndesis-logo-svg-white.svg",
    "logoDarkBg": "assets/images/syndesis-logo-svg-white.svg",
    "productBuild": false,
    "iconWhiteBg": "assets/images/glasses_logo_square.png",
    "iconDarkBg": "assets/images/glasses_logo_square.png",
    "appName": "Syndesis - DEVELOPMENT",
    "favicon32": "/favicon-32x32.png",
    "favicon16": "/favicon-16x16.png",
    "touchIcon": "/apple-touch-icon.png"
  },
  "datamapper": {
    "baseJavaInspectionServiceUrl": "/v2/atlas/java/",
    "baseXMLInspectionServiceUrl": "/v2/atlas/xml/",
    "baseJSONInspectionServiceUrl": "/v2/atlas/json/",
    "baseMappingServiceUrl": "/v2/atlas/",
    "discardNonMockSources": false,
    "addMockJSONMappings": false,
    "addMockJavaSingleSource": false,
    "addMockJavaSources": false,
    "addMockXMLInstanceSources": false,
    "addMockXMLSchemaSources": false,
    "addMockJSONSources": false,
    "addMockJavaTarget": false,
    "addMockXMLInstanceTarget": false,
    "addMockXMLSchemaTarget": false,
    "addMockJSONTarget": false,
    "debugDocumentServiceCalls": false,
    "debugMappingServiceCalls": false,
    "debugClassPathServiceCalls": false,
    "debugValidationServiceCalls": false,
    "debugFieldActionServiceCalls": false,
    "debugDocumentParsing": false
  },
  "features" : {
    "logging": false
  }
}
```

while I'm actually running against `.xip`

**Comment by gashcrumb** [comment]
Just change your config.json to xip
