### ISSUE TITLE
[UI] Issue in API Client Connectors page

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis#1236]
Opening `/customizations/api-connector` throws an exception in browser console.

```
 https://syndesis.192.168.42.160.xip.io/api/v1getApiConnectorList 404 (Not Found)
```

It seems to miss a `/` after `v1` token

**Comment by paoloantinori** [comment]
possibly relates to #1211

**Comment by paoloantinori** [comment]
possibly relates to #1211

**Comment by deeleman** [comment]
In the resulting URL, the segment `getApiConnectorList` should have been replaced by `/connectors?query=connectorGroupId%3D{template}` being `{template}` whatever template we are wanting to fetch.

Inn that case the API endpoints information seems to be missing. Please double check that there is an `src/app/customizations/api-connector/api-connector.api.ts` file in your system

**Comment by deeleman** [comment]
Ups, I just saw your PR. checking...
