### ISSUE TITLE
Settings/OAuth management suggestions

### ISSUE THREAD

**Issue by michael-coker** [syndesisio/syndesis#1248]
When you click "Settings" in the vertical nav:

* ~~Should the top/underlined "OAuth Client Management" text match the `<h1>` text underneath it that currently says "OAuth Application Management"?~~
    * ~~Currently, what's the point of the top/underlined text? I could see if there were more things to configure under "Settings," that "OAuth Client Management" could be a tab/link for OAuth settings, alongside other tabs beside it that switched out the panel content with settings for various parts of the application, but as it stands I don't see the point of that text.~~
* When you register or edit the client id/secret of an app:
   ~~* You have to click "Save" and "OK." If the save is successful, could clicking save close the expanded area and display a toast notification instead?~~
    * The inline notification for "Registration successful! You can validate these values when creating a connection for [application]" needs a period.
* ~~The arrow on the left of rows isn’t vertically centered.~~
* ~~At the 991px responsive breakpoint, the text by the icon in a row (i.e., “salesforce” or “twitter”) shifts up and isn’t vertically centered.~~
* Should clicking on the name or anywhere on the row (except for the “remove” button) expand/contract the row (edit it)?
    * This is mentioned in the 2nd bullet under [List View with Simple Expansion](http://www.patternfly.org/pattern-library/content-views/list-view/#design).
* ~~Add “cursor: pointer;” (or even better, some markup like making it an `<a>` with either an ‘href’ attr or adding `role=”button”` to the `<a>`) to the arrow on the left of the row to indicate it’s clickable.~~
    * ~~Or if making the entire row clickable, the whole row should have a pointer cursor.~~
* When you expand a list item on this page, the save, cancel, and ok buttons: 
    * are flush with the input fields above at < 992px.
    * have too much space between them and the inputs above from 992px - 1021px.

**Comment by gashcrumb** [comment]
@michael-coker do you want to work on this one too?

**Comment by michael-coker** [comment]
@gashcrumb sure! I forgot about this one, and this was before I had worked on the app at all. At a glance, I think only a couple of these are applicable, but I'll take a look later today or tomorrow.
