### ISSUE TITLE
Leaving form fields empty yields the corresponding data with a value of 'null' instead of ''

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#1250]
Basically we should figure out why this is happening and take out these code blocks:

https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/integration/edit-page/step-configure/step-configure.component.ts#L157-L162

https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/integration/edit-page/current-flow.service.ts#L409-L414

**Comment by gashcrumb** [comment]
Also I don't like that checkboxes produce the string `"true"` vs an actual boolean.

**Comment by gashcrumb** [comment]
Most likely we should also add a sanitize() function to the form factory service to ensure the values produced correlate to the form configuration.

**Comment by gashcrumb** [comment]
@seanforyou23 Do you want to tackle this one along with #1560?  Probably worth rolling it all into one task maybe?

**Comment by seanforyou23** [comment]
@gashcrumb seems logical to me!
