### ISSUE TITLE
System Metrics: UX Design

### ISSUE THREAD

**Issue by sjcox-rh** [syndesisio/syndesis#1251]
System metrics will be shown on the Home Page. PR up soon to show proposed design.

**Comment by sjcox-rh** [comment]
PR created for proposed changes to Home page to incorporate system metrics.

PR #1252 1252

I've also included a couple questions:

  1.  Discuss functionality to drill down per card. To drill down, click on active text within cards. Is this something we would want for TP4?
    - For Example: Clicking on "53 Connections" could take user to Connections page.

  2. How long will messages be? If long, will there be a need to take user to a separate page to view full message?

@chirino @rhuss @akieling @gashcrumb @amysueg @dongniwang @michael-coker @seanforyou23

**Comment by deeleman** [comment]
@KurtStam Do the designs provided have any impact on the current API implementation? Thx.

**Comment by gashcrumb** [comment]
I think these have been produced, I don't see a reason to keep this issue open.
