### ISSUE TITLE
Add icon for AMQP Connector

### ISSUE THREAD

**Issue by amysueg** [syndesisio/syndesis#1257]
Need an icon for the AMQP Connector, should be similar I think to AMQ connector? @dhirajsb @kcbabo maybe you could add your thoughts here.

This issue is part of this epic: https://github.com/syndesisio/syndesis/issues/1216

**Comment by dhirajsb** [comment]
@kcbabo PM probably has stronger feelings about what icon to use.

**Comment by sjcox-rh** [comment]
Will create the icon once i get a little more details :]

**Comment by kcbabo** [comment]
AMQP has its own icon, so that's a possibility:
https://www.amqp.org/

Probably worth getting Jack's input as the PM for AMQ.  I'll spin up a thread with him.

**Comment by sjcox-rh** [comment]
Here is the link for the svg version of the [AMQP icon](https://drive.google.com/file/d/1bdMoDmcZNJix2-X2kbJ3SkJDhdzC8bwq/view?usp=sharing).

I've also included the png as well. 
![_ipaas_connectionicons_amqp](https://user-images.githubusercontent.com/16257540/35582615-22fd18e8-05a4-11e8-97f5-f736c6fb2926.png)

@amysueg @kcbabo @dhirajsb

**Comment by amysueg** [comment]
Looks good to me. Thanks @sjcox-rh

**Comment by paoloantinori** [comment]
Hi @amysueg , is this issue completed? can I close it?

**Comment by amysueg** [comment]
AFAIK this is complete, so I'll close it, thanks @paoloantinori  for the reminder.
