### ISSUE TITLE
Error page required for OAuth redirection failure

### ISSUE THREAD

**Issue by honghuac** [syndesisio/syndesis#1277]
This is a two part issue:

1. Numerous attempts to connect to Salesforce using OAuth fails with this current state of Syndesis, despite recreation of the Connected App (Fuse Ignite instance) in the Salesforce console. Error displayed: `error=invalid_client_id&error_description=client%20identifier%20invalid`

2. Recommend creating an error page as part of the exception handling of the OAuth redirection error, page must include a hyperlink to return the Fuse Ignite administrator back to the Fuse Ignite dashboard.

**Comment by rhuss** [comment]
@honghuac sorry, that page does not come from us but directly from Salesforce. We do not have any influence to change this error message as it happens before the redirect back to our application. You can verify this by looking at the URL in your browser.

Also, afaik there is now way to tell salesforce to use a different error page if the callback URL configured in Salesforce is different than that specified during the OAuth handshake 

All we can do is to document this (as we do now) and explain how to fix this in the documentation.

'hope you dont mind if I close this issue, feel free to reopen if you think we could do more here.
