### ISSUE TITLE
OAuth Application Management items unable to load

### ISSUE THREAD

**Issue by honghuac** [syndesisio/syndesis#1279]
All the items (*Salesforce* and *Twitter*) located on the OAuth Application Management page failed to load today: ![oauth-err](https://user-images.githubusercontent.com/8625482/35498164-2aae13ae-0508-11e8-986c-59b7199525eb.png)

No relevant error messages could be found to explain this phenomena, in any of the Pods.

**Comment by rhuss** [comment]
@honghuac could you please check the JavaScript console whether any errors are reported there ?

**Comment by honghuac** [comment]
@rhuss No javascript errors, only redirection / 502 bad gateway errors:
https://gist.github.com/honghuac/6a8b87646100f2da3e377967d7d9fb1b

After a few retrys, the items show up again. Very erratic.

**Comment by gashcrumb** [comment]
Connectivity issue
