### ISSUE TITLE
"Mention" action missing from New Integration wizard page

### ISSUE THREAD

**Issue by honghuac** [syndesisio/syndesis#1281]
The "Mention" action is missing from the "Choose an Action" page

![mention-err](https://user-images.githubusercontent.com/8625482/35501838-095b2fee-0516-11e8-81a2-fefd030d1dc2.png)

**Comment by gashcrumb** [comment]
I believe this boiled down to an environment issue, reopen if this still occurs and provide any error messages that show up in your browser's developer console.
