### ISSUE TITLE
Missing Connections from the "New Integration" page

### ISSUE THREAD

**Issue by honghuac** [syndesisio/syndesis#1282]
Despite creating both Salesforce and Twitter connections, these two connections disappear intermittently from the *New Integration* page. Even the PostgresDB connection disappears along with these.

![no_connect](https://user-images.githubusercontent.com/8625482/35502193-2601b158-0517-11e8-9c6f-bd6b47bf43de.png)

**Comment by zregvart** [comment]
Hi @honghuac, thanks for reporting this, can you see any errors in the JavaScript console or in the Network tabs in the Development tools? Anything that you can send over to help us find the cause of this would be helpful, thanks!

**Comment by honghuac** [comment]
@zregvart Not a problem, happy to help. This is not a Javascript error, I observed repeated outage of the REST Pod whenever this issue appears. However, the log entries does not reflect anything useful, let me keep track on it.

**Comment by zregvart** [comment]
Perhaps there could be more information in events (`$ oc get events`). Could be the health checks restarting the rest pod, we had those issues before.

**Comment by honghuac** [comment]
This problem occurs with 1.2.2-fix as well. And it forced me to manually redeploy the REST Pod that died. No events that indicate anything wrong. Will keep monitoring.

**Comment by gashcrumb** [comment]
This is due to connectivity...
