### ISSUE TITLE
HTML/CSS updates for Support Page

### ISSUE THREAD

**Issue by amysueg** [syndesisio/syndesis#1288]
Bring the UI implementation of the Support Page inline with the UX design. See #334 for details.

@paoloantinori @dongniwang @sjcox-rh

**Comment by michael-coker** [comment]
Some notes from our 1.30.18 UX Sync meeting

* Use progressive disclosure for "specific integrations" toolbar/list instead of enabling/disabling the checkboxes
* Under "Select the integrations to capture diagnostics for:", only indent the toolbar/list displayed under "specific integrations" (remove other indentations)

**Comment by michael-coker** [comment]
Submitted a PR ([1361](https://github.com/syndesisio/syndesis/pull/1361)) and got some feedback on the structure and best practices. Going to spend some time looking through resources and make modifications as needed.

There are 3 pieces that need to be implemented in angular. @paoloantinori can you add the functionality for these, and I'll take care of the layout/styling?

* Pagination in the list of integrations - 5 results per page
* The "select all" link will select all integrations that match the current filter (selects all integrations if no filter applied)
* When you apply a filter, the output "_n_ Results" always returns "0 Results," even when there are integrations listed that matched the applied filters

**Comment by michael-coker** [comment]
@amysueg Submitted a new PR, and it was approved. https://github.com/syndesisio/syndesis/pull/1444/files

The page still needs
* pagination implementation
* "select all" link to select all integrations that match the current filter

@paoloantinori can you help with the 2 parts above?

**Comment by paoloantinori** [comment]
Hi @michael-coker  could you re-link to the UX definition document showing those last to missing parts, to use it as a guide for the implementation

**Comment by amysueg** [comment]
@paoloantinori Support Page UX designs are here: https://github.com/dongniwang/syndesis/blob/d57cdde868ca61922a546cbeb457340430c66c6b/ux/designs/support-page/support-page.md

Merged PR for UX design is #1168 

HTH

**Comment by paoloantinori** [comment]
Thanks!

**Comment by dongniwang** [comment]
Thanks @amysueg for providing the design link. 

@paoloantinori - you can find all UX design here: https://github.com/syndesisio/syndesis/tree/master/ux

**Comment by amysueg** [comment]
Can this issue be closed now?

**Comment by michael-coker** [comment]
@amysueg It's all done with the exception of a comment I left in https://github.com/syndesisio/syndesis/pull/1586, which probably should have been mentioned here instead.

https://github.com/syndesisio/syndesis/pull/1586#issuecomment-366050428

> Thanks @paoloantinori! I ran this by @sjcox-rh and she suggested allowing "Select All" to toggle selecting all filtered integrations, and updating the link text to "Deselect All" when all filtered integrations are selected.

Otherwise the page looks great!

**Comment by paoloantinori** [comment]
This has been merged
