### ISSUE TITLE
Create Concur connector based on the API connector

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#1290]
Concur has a REST API that would be a good use case to showcase the API connector.

**Comment by zregvart** [comment]
Let's make it epic.

**Comment by TovaCohen** [comment]
Will this connector require user doc for TP4?
If yes, can you tell me (or point me to) the information users will need?

**Comment by sjcox-rh** [comment]
@zregvart, I'm assuming we need a Concur icon as well?

**Comment by zregvart** [comment]
> Will this connector require user doc for TP4?
> If yes, can you tell me (or point me to) the information users will need?

I think we will need documentation for it, these are facts that I'm aware now:
 - it'll be using OAuth in setup and to create connections
 - we'll have support for [fetching and creating list items](https://developer.concur.com/api-explorer/v3-0/ListItems.html) operation

**Comment by zregvart** [comment]
> @zregvart, I'm assuming we need a Concur icon as well?

I think it would be OK to nick one of the logos from the [press kit](https://www.concur.com/en-us/logos).

**Comment by sjcox-rh** [comment]
@zregvart Great glad they had that resource available, works for me. Feel free to reach out if you need anything from me on this connection.

**Comment by zregvart** [comment]
Superseded by #2632
