### ISSUE TITLE
Support using proprietary JDBC Drivers with the DB Connector

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#1291]
- support uploading the driver: https://github.com/syndesisio/syndesis/issues/1752
- support using the driver in the verifier to fetch metadata and verify the connection https://github.com/syndesisio/syndesis/issues/1755
- support using the driver in the actual integration itself https://github.com/syndesisio/syndesis/issues/1753

**Comment by TovaCohen** [comment]
Hi Kurt, will this require user doc?
Thanks!

**Comment by KurtStam** [comment]
Yes is will. I still haven't made much progress on it so I it wil likely be for Sprint 25 instead.

**Comment by TovaCohen** [comment]
I'm trying to identify the doc work required for TP4. Should this epic have the **targettp4** label?
Please let me know when the is ready for doc.  Thanks!

**Comment by KurtStam** [comment]
Work is completed.

**Comment by KurtStam** [comment]
@TovaCohen I still owe you some documentation on this and will work on that next week along with a full end2end demo.

**Comment by TovaCohen** [comment]
Perfect. I was going to bug you next week. This is my Jira for doing the doc:
https://issues.jboss.org/browse/FUSEDOC-2387

You can add information there or in an email or a google document. Whatever works best for you. Also if you prefer to talk me through the information, we can get on BJ and I can record it.  I'll wait to hear back from you when you're ready.

**Comment by TovaCohen** [comment]
Hi @KurtStam , just checking in about the user doc for this feature. We are going to freeze the doc that we have at the end of the day, Wednesday March 28th and that will be the doc that we provide with TP4.
If this made it into TP4, then it would be great if we can document it by then. Should I set up a BJ call for Friday and we can go over what needs to be documented?

**Comment by TovaCohen** [comment]
Hi @KurtStam , just checking in about the user doc for this feature. We are going to freeze the doc that we have at the end of the day, Wednesday March 28th and that will be the doc that we provide with TP4.
If this made it into TP4, then it would be great if we can document it by then. Should I set up a BJ call for Friday and we can go over what needs to be documented?

**Comment by KurtStam** [comment]
I think we are good on this? Happy to have a meeting to go over any residual questions.

**Comment by TovaCohen** [comment]
Yes. All set. I'll add details about the questions you just responded to, but what we have in place already is just fine.  Thanks!
