### ISSUE TITLE
Kebab menu broken in integration list

### ISSUE THREAD

**Issue by kcbabo** [syndesisio/syndesis#1296]
I'm unable to select any option in the kebab menu on the integration list page.  The menu is visible upon click, but selecting an option does nothing.  Using Chrome.

**Comment by gashcrumb** [comment]
@rhuss probably need to cherry-pick this one -> https://github.com/syndesisio/syndesis/commit/ae8c9f855cd93e61fca7196b8b8f72a975eef6c6

**Comment by rhuss** [comment]
@gashcrumb could you do please the upgrade on this branch as it seems that no automatic cherry pick works (there has been some renaming from integrations to integration or so in the ui dis) ?

It should go on top of branch 1.2.x please.

Thanks !

**Comment by gashcrumb** [comment]
Should be fixed with the next build.
