### ISSUE TITLE
SQL Query checker: ResultSet not positioned properly

### ISSUE THREAD

**Issue by Stefan365** [syndesisio/syndesis#1302]
Query checker alarms "ResultSet not positioned properly, perhaps you need to call next."
when there is mixture of parameters and literal values in SQL query.

Examples
WRONG (alarm):
INSERT INTO TODO(task, completed) VALUES (:#TASK, 0);

OK:
INSERT INTO TODO(task, completed) VALUES (:#TASK, :#COMPLETED);
INSERT INTO TODO(task, completed) VALUES ('Some taks', 0);

(this occurs in TP3)

**Comment by KurtStam** [comment]
https://github.com/syndesisio/syndesis/pull/1477
