### ISSUE TITLE
Provide data shape name/description for builtin connectors

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#1307]
With #1245 we have two new properties on the data shapes, we should set values for them in all data shapes that we ship.

**Comment by paoloantinori** [comment]
Entries to cover:
<details>
  <summary><b>Entries in Connectors, click to expand</b></summary>
<pre><code>
16:38 $ pwd && !!
pwd && ag -g '.*src.*json$' | xargs -n1 ag '(output|input)DataShape' -l | xargs -n1 -I {}  sh -c "echo {}; jq  ' ..|(.outputDataShape?,.inputDataShaper?)' {}" | ag -v null


/data/repositories/work/syndesis/syndesis/app/connectors/connectors


aws-s3-connector/src/main/resources/META-INF/syndesis/connector/aws-s3.json
{
  "kind": "none"
}
{
  "name": "S3Object",
  "description": "Represent one Amazon S3 Object",
  "kind": "java",
  "type": "com.amazonaws.services.s3.model.S3Object"
}
{
  "name": "S3Object",
  "description": "Represent one Amazon S3 Object",
  "kind": "java",
  "type": "com.amazonaws.services.s3.model.S3Object"
}
twitter-connector/src/main/resources/META-INF/syndesis/connector/twitter.json
{
  "name": "Status",
  "description": "Represent one single status of a user",
  "kind": "java",
  "type": "twitter4j.Status"
}
{
  "name": "Status",
  "description": "Represent one single status of a user",
  "kind": "java",
  "type": "twitter4j.Status"
}
jms/amqp-connector/src/main/resources/META-INF/syndesis/connector/amqp.json
{
  "kind": "none"
}
{
  "kind": "*"
}
{
  "kind": "*"
}
sql/src/main/resources/META-INF/syndesis/connector/sql.json
{
  "kind": "json-schema"
}
{
  "kind": "json-schema"
}
{
  "kind": "json-schema"
}
{
  "kind": "json-schema"
}
</code></pre>
</details>

<details>
  <summary><b>Entries in DAO, click to expand</b></summary>
<pre><code>
6:42 $ pwd && ag -g '.*src.*json$' | xargs -n1 ag '(output|input)DataShape' -l | xargs -n1 -I {}  sh -c "echo {}; jq  ' ..|(.outputDataShape?,.inputDataShaper?)' {}" | ag -v null

/data/repositories/work/syndesis/syndesis/app/rest/dao

src/main/resources/io/syndesis/dao/deployment.json
{
  "kind": "java",
  "type": "org.apache.camel.component.salesforce.api.dto.CreateSObjectResult"
}
{
  "kind": "none"
}
{
  "kind": "none"
}
{
  "kind": "json-schema"
}
{
  "kind": "json-schema"
}
{
  "kind": "none"
}
{
  "kind": "java",
  "type": "org.apache.camel.component.salesforce.api.dto.CreateSObjectResult"
}
{
  "kind": "json-schema"
}
{
  "kind": "json-schema"
}
{
  "kind": "java",
  "type": "io.syndesis.connector.salesforce.SalesforceIdentifier"
}
{
  "kind": "none"
}
{
  "type": "*"
}
{
  "type": "*"
}
src/main/resources/io/syndesis/dao/demo-data.json
{
  "kind": "java",
  "type": "twitter4j.Status"
}
{
  "kind": "none"
}
{
  "kind": "any"
}
{
  "kind": "any"
}
{
  "kind": "any"
}
{
  "kind": "any"
}
{
  "kind": "any"
}
{
  "kind": "any"
}
{
  "kind": "any"
}
{
  "kind": "any"
}
{
  "kind": "any"
}
{
  "kind": "any"
}
{
  "kind": "any"
}
{
  "kind": "any"
}
{
  "kind": "any"
}
{
  "kind": "any"
}
{
  "kind": "any"
}
{
  "kind": "any"
}
{
  "kind": "any"
}
{
  "kind": "any"
}
{
  "kind": "any"
}
{
  "kind": "none"
}
{
  "kind": "any"
}
{
  "kind": "any"
}
{
  "kind": "any"
}
{
  "kind": "any"
}
{
  "kind": "any"
}
{
  "kind": "any"
}
{
  "kind": "any"
}
{
  "kind": "any"
}
{
  "kind": "any"
}
{
  "kind": "any"
}
{
  "kind": "any"
}
{
  "kind": "any"
}
{
  "kind": "any"
}
{
  "kind": "none"
}
{
  "kind": "java",
  "type": "io.syndesis.connector.daytrade.Trade"
}
{
  "kind": "java",
  "type": "io.syndesis.connector.daytrade.Trade"
}
{
  "kind": "any"
}
{
  "kind": "any"
}
{
  "kind": "any"
}
{
  "kind": "java",
  "type": "io.syndesis.connector.tradeinsight.Suggestion"
}
{
  "kind": "java",
  "type": "io.syndesis.connector.tradeinsight.Suggestion"
}
{
  "kind": "java",
  "type": "io.syndesis.connector.tradeinsight.Suggestion"
}

</code></pre>
</details>

**Comment by paoloantinori** [comment]
@zregvart I don't see many entries, deserving a description. Am I looking at the data correctly?

I'm assuming we are not caring of entries of kind `any`, `none` and `json-schema`.

**Comment by zregvart** [comment]
@paoloantinori I think that list might be missing actions tagged as `dynamic` (SQL, Salesforce), and we should care about all data shapes that are supported by the mapper (type/kind being: `xml`/`xml-schema`, `java`/`java class name`, `json`/`json-schema`).

**Comment by paoloantinori** [comment]
Okay, so it's still the full list in my post above, and my prev comment doesn't count, since the original list already enlist everything that has a `*datashape` node and list the corresponding content, suggesting which are the source files impacted.

**Comment by paoloantinori** [comment]
And to further specify, regarding `dynamic` actions, probably there are connectors like Saleforce where the missing information can be extracted programmatically, probably around this section:

https://github.com/syndesisio/syndesis/blob/master/app/verifier/src/main/java/io/syndesis/verifier/v1/metadata/SalesforceMetadataRetrieval.java#L78-L79

While other like `sql` that might not be able to automatically generate anything meaningful.

**Comment by igarashitm** [comment]
I updated Twitter, SQL and Salesforce(JSON) connectors to have a bit enriched name&description. For example SQL connector shows SQL statrement as a description.

**Comment by zregvart** [comment]
@igarashitm cool thanks, less work :)

**Comment by igarashitm** [comment]
Let's close this one for now, Twitter, SQL and Salesforce were the well used ones among us and took care of them, then we got the "describe data type" with accepting data type name&description. Let's see if there's anything else we want to improve and file for each.
