### ISSUE TITLE
 Eliminate the atlasmap pod by embedding it’s rest services in the syndesis-rest pod.

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis#1308]
Theres no good reason to isolate the atlasmap rest services in their own pod and take on the associated memory budget expense.  We should be able expose them as rest services from the syndesis-rest pod.

**Comment by zregvart** [comment]
I wonder if that'll complicate dependency management as the two projects might differ in versions of the libraries used.

**Comment by chirino** [comment]
Atlasmap is light on dependencies.  It should be easy to version align those deps.
