### ISSUE TITLE
Don't generate config.json into src/

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#1318]
This is dangerous as it can easily happen that a generated, personal config.json ends up in a release:

* No `mvn clean` will remove this file. I guess there is no command which will remove this (except doing it manually)
* It doesn't show up on `git status` as its included in .gitignore

Actually no code should be generated or copied temporarily below src/ and this is always gives headaches (same for the code generated by the old connectors into src/).

Can we find an alternative solution (beside always having to clone from GitHub afresh) ?

**Comment by chirino** [comment]
We could run a little ant in the mvn build to delete it.

**Comment by gashcrumb** [comment]
You can just do `git clean -f -X`which will remove untracked files including ones that are in `.gitignore`

**Comment by rhuss** [comment]
My question is why this config.json is generated in `src/` in the first place and not in `target/`.

**Comment by gashcrumb** [comment]
It's for development, as the dev server serves out the html files and assets from `ui/src/`, and it's only currently created via `yarn start:minishift` and `yarn start:minishift-aot` I believe.

It probably can be changed easily enough, but means mucking around with the dev server configuration.

**Comment by gashcrumb** [comment]
above comments address this

**Comment by gashcrumb** [comment]
Should revisit this, maybe `mvn clean` could be set up to delete this file, as it can be annoying

@dhirajsb FYI

**Comment by gashcrumb** [comment]
Might just nuke it as part of building all the UI code, no reason for this file to ever get built into the docker image.
