### ISSUE TITLE
JsonDBTest intermittently fails

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#1345]
Once in a long while JsonDBTest fails with:

```
java.lang.AssertionError: 

Expected size:<2> but was:<1> in:
<[{"name"="Ana Chirino"}]>
	at io.syndesis.jsondb.impl.JsonDBTest.testPush(JsonDBTest.java:324)
```

We should investigate, this could mean that we're missing a cache invalidation or there could be race condition.

**Comment by KurtStam** [comment]
@zregvart does this still happen, or can this issue be closed out?

**Comment by zregvart** [comment]
Let's close this I haven't seen this for a while.
