### ISSUE TITLE
TP3 branding configuration

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis#1355]
What's the actual configuration to enable branded UI?

For the following config
```
"branding": {
        "productBuild": "true",
        "logoWhiteBg": "assets/images/FuseOnlineLogo_Black.svg",
        "logoDarkBg": "assets/images/FuseOnlineLogo_White.svg",
        "iconWhiteBg": "",
        "iconDarkBg": "",
        "appName": "Fuse Online",
        "favicon32": "/favicon-32x32.png",
        "favicon16": "/favicon-16x16.png",
        "touchIcon": "/apple-touch-icon.png"
     }
``` 
![screen shot 2018-02-01 at 15 11 19](https://user-images.githubusercontent.com/5637792/35682781-30186fea-0762-11e8-8665-a1f02d39ab2e.png)

Switching to icons produces icon and alt name displayed also.
```
"branding": {
        "productBuild": "true",
        "logoWhiteBg": "",
        "logoDarkBg": "",
        "iconWhiteBg": "assets/images/FuseOnlineLogo_Black.svg",
        "iconDarkBg": "assets/images/FuseOnlineLogo_White.svg",
        "appName": "Fuse Online",
        "favicon32": "/favicon-32x32.png",
        "favicon16": "/favicon-16x16.png",
        "touchIcon": "/apple-touch-icon.png"
     }
```

![screen shot 2018-02-01 at 15 13 14](https://user-images.githubusercontent.com/5637792/35682867-73ac4c2c-0762-11e8-8236-00e2955b350d.png)

**Comment by gashcrumb** [comment]
@kcbabo what's the right logo BTW?

@dsimansk your second config is the right one.

**Comment by dsimansk** [comment]
@gashcrumb for the second config there're 2 html elements with one for icon, one for logo. The second "Fuse Online" text is actually `alt` from `img` tag, right?
```
<a _ngcontent-c0="" class="navbar-brand" routerlink="/" href="/">
 
<img _ngcontent-c0="" alt="" class="navbar-brand-icon product" src="assets/images/FuseOnlineLogo_White.svg">
 
<img _ngcontent-c0="" class="navbar-brand-name product" src=" " alt="Fuse Online">
 
</a>
```

**Comment by kcbabo** [comment]
Should be the same logo we used for TP2, right?  I believe that @sjcox-rh might have worked with the brand team to get a version that was suitable for the banner.

**Comment by gashcrumb** [comment]
> Should be the same logo we used for TP2, right? I believe that @sjcox-rh might have worked with the brand team to get a version that was suitable for the banner.'

Yeah, but for tp2 I think I changed the logo and mucked with the banner several times, so I honestly can't definitively say what it should be.  Let's just be happy it's not:

![](http://media.riffsy.com/images/806fa85fc55a55de66ab310e500b5f0f/tenor.gif)

> @gashcrumb for the second config there're 2 html elements with one for icon, one for logo. The second "Fuse Online" text is actually alt from img tag, right?

Yup, I think that was the result of above tp2 muckery :-)

**Comment by dsimansk** [comment]
@kcbabo this would be the combination of logo and `appName: Ignite`.

![screen shot 2018-02-01 at 17 56 53](https://user-images.githubusercontent.com/5637792/35691695-763ba200-0779-11e8-91b0-f1ea577ee158.png)

**Comment by kcbabo** [comment]
Works for me!  We can save the nyan cat for GA.

**Comment by sjcox-rh** [comment]
@kcbabo yup I provided the "RED HAT FUSE ONLINE" logo. 

Is it intentional to have the "Ignite" portion slightly smaller than the rest of the logo? @dsimansk 

Not that anything is wrong with it, I'm just curious :]

**Comment by kcbabo** [comment]
Ignite is not an official part of the logo, it should definitely be separate (image followed by text).  I don't have an opinion on relative sizing however.

**Comment by gashcrumb** [comment]
@dsimansk @kcbabo @sjcox-rh Hey!  Should we taco 'bout what the branding should be for tp4?

**Comment by dsimansk** [comment]
@gashcrumb the current impl in TP3, when CM is configured with FuseOnlineLogo and enabled product property. 

The html code as below, that results in displaying of logo and app name.
```html
<a _ngcontent-c0="" class="navbar-brand" routerlink="/" href="/">
          <!----><img _ngcontent-c0="" alt="" class="navbar-brand-icon product" src="assets/images/FuseOnlineLogo_White.svg">
          <!---->
          <!----><span _ngcontent-c0="" class="navbar-brand-name">Ignite</span>
        </a>
```
However, the upstream branding is defined in way that takes app name as alt to logo image.
```
<a _ngcontent-c0="" class="navbar-brand" routerlink="/" href="/">
          <!----><img _ngcontent-c0="" alt="" class="navbar-brand-icon" src="assets/images/glasses_logo_square.png">
          <!----><img _ngcontent-c0="" class="navbar-brand-name" src="assets/images/syndesis-logo-svg-white.svg" alt="Syndesis">
          <!---->
        </a>
```

**Comment by gashcrumb** [comment]
Yes, we put in crazy hacks in tp2 to get the logos straightened out, I'd like to make sure that we have the right logos in place so I can clean up these crazy hacks, or at least formalize the logic a bit better :-)

**Comment by kcbabo** [comment]
@gashcrumb - is there a question around which logo to use from a product standpoint?  I'm good with the current approach of Red Hat Fuse Online Logo followed by "Ignite" as text.

**Comment by gashcrumb** [comment]
Ah, k, gotcha...  Then nothing is needed for this one.
