### ISSUE TITLE
SQL verifier not being detected

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#1357]
The SQL verifier extension ([SqlConnectorVerifierExtension](https://github.com/syndesisio/syndesis/blob/master/app/connectors/connectors/sql/sql-common/src/main/java/io/syndesis/connector/sql/SqlConnectorVerifierExtension.java)) is not part of the SQL Camel component so when [ComponentVerifier](https://github.com/syndesisio/syndesis/blob/master/app/connectors/connector-verifier/src/main/java/io/syndesis/verifier/api/ComponentVerifier.java) tries to [resolve it](https://github.com/syndesisio/syndesis/blob/b371c00a0148d732505192592ebe0bbbc0920596/app/connectors/connector-verifier/src/main/java/io/syndesis/verifier/api/ComponentVerifier.java#L93) it does not resolve.

So verification of SQL connection doesn't work.

**Comment by KurtStam** [comment]
@zregvart we had a regression?

**Comment by KurtStam** [comment]
@lburgazzoli The DB Connector encompasses 4 connectors:

- sql-connector
- sql-connector-start
- sql-stored-connector
- sql-stored-connector-start

An in the deployment.json the Connector is called 'sql', with 4 actions. It looks like I can't combine 4 connectors under a common name anymore?

**Comment by lburgazzoli** [comment]
if the behavior has changed it is definitively unintended but I do not get how it was working, as the [SqlVerifier](https://github.com/syndesisio/syndesis/blob/master/app/verifier/src/main/java/io/syndesis/verifier/impl/SqlVerifier.java) declares "getConnectorAction" (which is the name of the underlying component to use) has always been "sql" instead of one of the real action to use.

@KurtStam what should be the right connector to invoke ?
@zregvart looks like salesforce is done the same way

**Comment by lburgazzoli** [comment]
@zregvart no sorry, salesforce has its own verifier so it is fine

**Comment by lburgazzoli** [comment]
@KurtStam or we just need to use [SqlConnectorVerifierExtension](https://github.com/syndesisio/syndesis/blob/master/app/connectors/connectors/sql/sql-common/src/main/java/io/syndesis/connector/sql/SqlConnectorVerifierExtension.java) as verifier for sql stuffs, correct ?

**Comment by zregvart** [comment]
> @KurtStam or we just need to use SqlConnectorVerifierExtension as verifier for sql stuffs, correct ?

I think that is so, yes.

**Comment by KurtStam** [comment]
@lburgazzoli That's set here no: https://github.com/syndesisio/syndesis/blob/master/app/verifier/src/main/java/io/syndesis/verifier/impl/SqlVerifier.java#L35

**Comment by KurtStam** [comment]
@lburgazzoli thx this does the trick.
