### ISSUE TITLE
oauth pod keeps crashing

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#1365]
As a workaround you need to issue

    local currentUser=$(oc whoami)
    oc login -u system:admin
    oc adm policy add-cluster-role-to-user system:auth-delegator -z syndesis-oauth-client
    oc login -u $currentUser

before installing syndesis.

**Comment by zregvart** [comment]
Not a workaround, a required step as per our install scripts (currently)

https://github.com/syndesisio/syndesis/blob/bf5f1c89f44296b12c6b116bcde165e3fac1eee6/tools/bin/commands/install#L43

**Comment by abouchama** [comment]
This command doesn't work with openshift version 3.7.0
`oc adm policy --as system:admin add-cluster-role-to-user system:auth-delegator -z syndesis-oauth-client`

It works only with openshift version **3.6.0**.
