### ISSUE TITLE
UI, empty collections issues

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis#1371]
Related to this refactoring: https://github.com/syndesisio/syndesis/pull/1353

There are still some issues with:
- extensions
- s3 connectors (probably connectors more in general)

I'm working on this.

cc @gashcrumb @lburgazzoli @oscerd

**Comment by oscerd** [comment]
S3 connector fix is coming.

**Comment by paoloantinori** [comment]
This pr
