### ISSUE TITLE
Datamapper initialization omits datashape from extension

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis#1375]
When I have JMS -> My ext(with defined shape) -> Datamapper -> DB. Looking at the initialization of Datamapper in network tab, there's query for `jms connector` and `db connector` not the custom extension.

The extension is here: https://github.com/dsimansk/syndesis-extension-tp3

@lburgazzoli @gashcrumb @igarashitm

**Comment by lburgazzoli** [comment]
It looks correct, extensions do embed the inspection so in the generated extension metadata you should see a specification element with some json in it. As result the backend is not involved.

**Comment by igarashitm** [comment]
Ack from UI, I recently talked with Stan about it that we expect extension
to hold full datashape definition while we do lazy fetch for OOTB
connectors.

**Comment by dsimansk** [comment]
https://gist.github.com/dsimansk/5fb6ab2ac63f157bcf7457628c28044c everything seems to be present in the generated extension json.

**Comment by gashcrumb** [comment]
@igarashitm BTW, were we correct that the UI code accidentally looks at input shapes for previous steps and output shapes for subsequent steps?  We might need to fix that on the tp3 branch...

**Comment by igarashitm** [comment]
datamapper host uses inputDataShape as an outputDataShape and vice versa, so it's only a matter of existing check. basic-fliter step seems to be doing something a bit advanced... not yet sure how it goes.

**Comment by paoloantinori** [comment]
@igarashitm can you verify if this hasn't been fixed already?

**Comment by igarashitm** [comment]
I believe this works fine now, as all data shape aware step embed full data shape definition. No longer have extension only exception.
