### ISSUE TITLE
Improve cancel dialog in API Connector setup

### ISSUE THREAD

**Issue by kcbabo** [syndesisio/syndesis#1377]
Noticed the following when trying to cancel during the middle of adding a new API Connector.

When you click on cancel, the resulting dialog provides two options : Continue and Cancel.  Probably worth a run through UXD as:

1.  I'm used to seeing the default order being Cancel then OK, with OK being the default.
2. In this case "Cancel" means OK, which is not very intuitive based on they layout.

There's also a typo in the message : "loose" instead of "lose".

**Comment by zregvart** [comment]
Roping in @syndesisio/uxd
