### ISSUE TITLE
[integration] replace configuredProperties secret values with placeholders at project generation time

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#1381]

**Comment by gashcrumb** [comment]
With no indication of exactly what tasks are involved is this issue ever going to be completed?

**Comment by zregvart** [comment]
Actually, I think we do this now. (@lburgazzoli please reopen if not true)

**Comment by lburgazzoli** [comment]
The idea of this "issue" is that at runtime an integration should not have the logic to understand if a property is a secret or not but this logic should be moved at project generation time only, runtime should the the configured property as it is.

@gashcrumb was a placeholder for some idea :)
@zregvart not yet done

**Comment by lburgazzoli** [comment]
keep it open
