### ISSUE TITLE
Do not generate PushTopics with Names longer that 25 characters

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#1385]
When Salesforce streaming connector creates a PushTopic it should supply a Name that is not longer than 25 characters.

As per [documentation](https://developer.salesforce.com/docs/atlas.en-us.210.0.api.meta/object_ref/pushtopic.htm).

**Comment by oscerd** [comment]
Discussing with @zregvart we can go with

`syn_" + sObjectName + "_[c|r|u|d|x]`

If the name is longer than 25 then we can trim the sObjectName to the remaining length.

Just for reminder.
