### ISSUE TITLE
Settings page, 'save' button doesn't come back out of the 'submitting' state

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#1387]
Once you copypasta your credentials and click 'Save' it stays in it's submitting state with the little spinny.  The network request completes with an HTTP 204 but the page doesn't pick up the response.

**Comment by gashcrumb** [comment]
This also appears to happen when saving an integration as a draft, most likely that page also follows the same pattern as the 'settings' page.

**Comment by gashcrumb** [comment]
I wonder, did we change the backend so that `PUT` doesn't return the updated object?

**Comment by gashcrumb** [comment]
@zregvart @lburgazzoli any ideas on ^^^

**Comment by zregvart** [comment]
Actually update never returned anything (it could and it would be easy to do so)

https://github.com/syndesisio/syndesis/blob/4d10f337c94added769b2df2fc1d6c45cb08e301/app/rest/rest/src/main/java/io/syndesis/rest/v1/handler/setup/OAuthAppHandler.java#L130

**Comment by zregvart** [comment]
@gashcrumb would you like the `PUT /setup/oauth-apps/{connector-id}` endpoint to return updated connector?

**Comment by gashcrumb** [comment]
Haven't had a chance really to fully understand what changed to introduce this, if that's been the behavior all along then this is likely a client-side issue.
