### ISSUE TITLE
UX: Revisit Connection Details Page after TP4

### ISSUE THREAD

**Issue by sjcox-rh** [syndesisio/syndesis#1390]
Reference #222 

Want to revisit the details pages throughout iPaaS to discuss consistency of both design and implementation.

**Comment by gashcrumb** [comment]
Is this in progress at all?

**Comment by michael-coker** [comment]
@sjcox-rh I'm reviewing the UXD backlog and pinging to see if there has been any update? And would it be OK to assign this to you (or someone else on the team) so it's on someone's radar?

**Comment by dongniwang** [comment]
This will be addressed by the working on **UX: Align the look and feel of Integration Details and Connection Details** https://github.com/syndesisio/syndesis/issues/2818. Closing this issue for now.
