### ISSUE TITLE
No build integrations

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#1397]
We should deploy integration pods without running an S2I build. To do that we should generate a base container image that includes the always needed bits, like always used jars and skeleton application. Additional jars should be provided via volume. Configuration should be done via Secrets or ConfigMaps. Classpath for the integration pod should be calculated based on the connectors used and provided via configuration.

Old description:
_So here is an idea that I just thought of. What would it take for us to never build the image for a integration pod, but rather use the same image and parameterize it enough so it still works. The only thing that’s currently missing is the classpath. We can probably compute that when we generate the integration project relying on Maven dependency resolution. And to do that we need all POMs, or there is a clever hack by having dependencies.properties precomputed (Maven dependency plug-in can do that)._

_Am I missing anything else?_

**Comment by rhuss** [comment]
@zregvart originally there was even the idea to avoid S2I alltogether provide a universal runtime which loads connectors on demand. (OSGi anyone ?). Although I still think its a good idea (as it will safe all the s2i hassle), it has been rejected at that time.

However, using our fat S2I alone is probably not good enough (and only tune the classpath) as we have to consider extension and custom connector jars, too.

Having all dependencies for all connectors (remember, we currently only have a handful and already 1GB) in a single image, doesn't scale on many levels (build times, push and pull times, ....). Actually an integraton should only download or install what it requires.

**Comment by lburgazzoli** [comment]
If we are able to create a list of deps and the path of the related jars, we can use the same technology behind extension that basically extends spring-boot classpath

**Comment by gashcrumb** [comment]
I think this would be awesome, should we create an epic from this issue and close this discussion?

**Comment by zregvart** [comment]
I think we agreed to try this, so I removed `cat/discussion` and converted this to epic.

**Comment by heiko-braun** [comment]
Closed in favour of #4143
