### ISSUE TITLE
JavaScript error when opening "OAuth Settings"

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#1407]
Happens on master:

![image](https://user-images.githubusercontent.com/99080/35792186-1631d4bc-0a4c-11e8-9504-dd1a44dc2c70.png)

**Comment by rhuss** [comment]
No form is showing up afterwards

**Comment by deeleman** [comment]
Could be related to the ng tour dependency. Will take a look along today.

**Comment by gashcrumb** [comment]
I guess this still happens?  Doing a build to see what the current state is.

**Comment by seanforyou23** [comment]
I do remember seeing this at a point during the angular upgrade, but it was fixed after a session with @deeleman where we made some adjustments to app/ui/src/polyfills.ts - supplying common rxjs operands at a global level for the app components. I built with latest from master this morning and, for me, the oauth settings sections expand and display the forms fine. I'm trying to reproduce this right now, @rhuss if there are any specifics steps you took to trigger this which may be necessary to see the error please let me know.

**Comment by rhuss** [comment]
@seanforyou23 not that happens to me nearly everywhere and also @gashcrumb could reproduce it. We could nail it down to --aot which causes this kind of issue. However that is hard to debug because I could not get sourcemaps running for --aot compiled code.
