### ISSUE TITLE
OAuthProxy Pod deployment fails - using latest OpenShift Templates

### ISSUE THREAD

**Issue by honghuac** [syndesisio/syndesis#1409]
Attempt to install the latest Syndesis app (using `syndesis-restricted` template on the master branch) - results in failure, the OAuthProxy Pod fails to spin up. This error does not occur with *branch 1.2.2-fix*, in fact, with the code in that branch the app installs smoothly.

Error in OAuthproxy pod, due to the code in master branch, is "_Container: syndesis-oauthproxy —  Crash loop back off"_ on the web console.

The log file for the pod is :

*2018/02/05 08:14:33 main.go:134: Invalid configuration:*
--
`  | unable to load OpenShift configuration: unable to retrieve authentication information for tokens: User "system:serviceaccount:fuse-7234:syndesis-oauth-client" cannot create tokenreviews.authentication.k8s.io at the cluster scope: User "system:serviceaccount:fuse-7234:syndesis-oauth-client" cannot create tokenreviews.authentication.k8s.io at the cluster scope (post tokenreviews.authentication.k8s.io)`

**Comment by paoloantinori** [comment]
you should either use official provisioning steps, as described here:

https://doc.syndesis.io/#syndesis-install

or add the missing step in your workflow that is:

```
add_auth_delegator_role() {
    local currentUser=$(oc whoami)
    oc login -u system:admin
    oc adm policy add-cluster-role-to-user system:auth-delegator -z syndesis-oauth-client
    oc login -u $currentUser
}

add_auth_delegator_role
```

**Comment by KurtStam** [comment]
@paoloantinori So do we need to update this then: http://syndesis.io/quickstart/ ?

**Comment by paoloantinori** [comment]
Yes, despite this being a transitory situation, since it's already been reported that this approach is not compatible with OS3.7.

At the moment the official quickstart lacks this step.

**Comment by KurtStam** [comment]
The PR updates the Quickstart instructions on syndesis.io.

**Comment by zregvart** [comment]
I think we can close this now.
