### ISSUE TITLE
Twitter mention action, config page throws `SyntaxError: Unexpected token u in JSON at position 0`

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#1418]
As the action object doesn't have `propertyDefinitionSteps` in the response, so this line of code blows up:

https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts#L194

**Comment by oscerd** [comment]
Same for copy object of AWS S3, at leaat this morning 

That action has an empty collection in his definition. Not sure if twitter mention has the same situation

**Comment by gashcrumb** [comment]
It does, as there's no settings for that action.  The previous code didn't hit this error, but the updated version references an undefined object ->

https://github.com/syndesisio/syndesis/commit/b1283287adf4d94a244058a325b7da46f5f70156
