### ISSUE TITLE
[custom api connector] Icon can't be changed sometimes

### ISSUE THREAD

**Issue by mastepan** [syndesisio/syndesis#1433]
If I want to change an icon on the api connector detail page, sometimes it works, sometimes doesn't.
I'm putting down 2 cases that may be related. 

**Case1:**

- Petstore api connector: If I change a connector's icon, the icon of a connection based on this connector will be changed

- TODO api connector: If I change a connector's icon, the icon of a connection based on this connector will NOT be changed

Why it behaves in different way for different connectors?

**Case 2:**

On Connector detail page:

1. I change an icon from icon 1 to icon 2

- the icon displayed on the connector detail page is still 1

2. I change an icon to icon 3
- the icon displayed on the connector detail page changes to Icon 2

and so on...
That means that displaying the icon is 1 step behind the current setting.
Refreshing the page refreshes the icon to the current state that is set.

**Comment by dsimansk** [comment]
I'm reopening this issue because the described behaviour is still not fixed. And the linked PR seems to target different issue.

Cc @deeleman @mastepan

**Comment by deeleman** [comment]
> I'm reopening this issue because the described behaviour is still not fixed. And the linked PR seems to target different issue.

These references issues and PRs have been edited to remove the wrong links to this issue. On a side note, I have tested this issue and I do not seem to be able to replicate it in my environment. Apparently the UI responds as expected in the case scenarios reported by @mastepan.

Perhaps @zregvart can provide more insights on wether this is  a backend or frontend issue.

**Comment by dsimansk** [comment]
@deeleman if I'm reading correctly the Network tab. Upon API connector create wizard submission I don't see image in a multipart Request Payload.
```
POST /api/v1/connectors/custom HTTP/1.1
Host: syndesis.192.168.64.17.nip.io
Connection: keep-alive
Content-Length: 7232
Pragma: no-cache
Cache-Control: no-cache
Accept: application/json, text/plain, */*
Origin: https://syndesis.192.168.64.17.nip.io
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.170 Safari/537.36 Vivaldi/1.95.1077.50
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryW0hpTCYRinsRuX74
DNT: 1
Referer: https://syndesis.192.168.64.17.nip.io/customizations/api-connector/create/swagger-connector
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
Cookie: b2a2e2613ad00502bbe3dae4fed6f03a=c9a2d616f7e76033981b5930dd3daa19; _oauth_proxy=ZGV2ZWxvcGVyQGNsdXN0ZXIubG9jYWx8WnJrTUVXTzVDYUt6bm93MUVVUVFoS2dmOFZ1V1NDZjQ0anBmeXQ4Tjk1U0haWkNXd0xMajA3QjZrYnRGbEY0ZU43U1dRSGJXMk9aRFpkRT18LTYyMTM1NTk2ODAwfA==|1520494649|xRBA3qf_SEprXTXW9k0G-8Yo38c=


------WebKitFormBoundaryW0hpTCYRinsRuX74
Content-Disposition: form-data; name="specification"
false
------WebKitFormBoundaryW0hpTCYRinsRuX74
Content-Disposition: form-data; name="connectorSettings"; filename="connectorSettings"
Content-Type: application/json
------WebKitFormBoundaryW0hpTCYRinsRuX74--
```

But when I submit icon directly via API connector detail page
```
PUT /api/v1/connectors/i-L759jLCnXRAdo4dXCZRz HTTP/1.1
Host: syndesis.192.168.64.17.nip.io
Connection: keep-alive
Content-Length: 21490
Pragma: no-cache
Cache-Control: no-cache
Accept: application/json, text/plain, */*
Origin: https://syndesis.192.168.64.17.nip.io
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.170 Safari/537.36 Vivaldi/1.95.1077.50
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryDIjFR05RykZmknNi
DNT: 1
Referer: https://syndesis.192.168.64.17.nip.io/customizations/api-connector/i-L759jLCnXRAdo4dXCZRz
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
Cookie: b2a2e2613ad00502bbe3dae4fed6f03a=c9a2d616f7e76033981b5930dd3daa19; _oauth_proxy=ZGV2ZWxvcGVyQGNsdXN0ZXIubG9jYWx8WnJrTUVXTzVDYUt6bm93MUVVUVFoS2dmOFZ1V1NDZjQ0anBmeXQ4Tjk1U0haWkNXd0xMajA3QjZrYnRGbEY0ZU43U1dRSGJXMk9aRFpkRT18LTYyMTM1NTk2ODAwfA==|1520494649|xRBA3qf_SEprXTXW9k0G-8Yo38c=


------WebKitFormBoundaryDIjFR05RykZmknNi
Content-Disposition: form-data; name="icon"; filename="ok-1976099_960_720.png"
Content-Type: image/png

------WebKitFormBoundaryDIjFR05RykZmknNi
Content-Disposition: form-data; name="connector"; filename="connector"
Content-Type: application/json

------WebKitFormBoundaryDIjFR05RykZmknNi--
```
