### ISSUE TITLE
[custom api connector] "Used by integrations by X times" shows 0 despite it's being used

### ISSUE THREAD

**Issue by mastepan** [syndesisio/syndesis#1435]
![todointegration](https://user-images.githubusercontent.com/8707251/35859868-1517388c-0b42-11e8-9ffa-4b2994d13d43.png)

![todoconnector](https://user-images.githubusercontent.com/8707251/35859804-c4d8c7d2-0b41-11e8-8e0a-8d30c8129539.png)

**Comment by deeleman** [comment]
i can confirm this is mainly a frontend issue related to the way we handle state for API Custom Connectors. Contrary to the other modules, the Custom API connector area is fully reactive, and relies on a slice of state persisted in the Redux store. That is why that list is only fetched ONCE and only refreshed when a new custom API connector is created.

So, the workaround for this entails dispatching a new Redux REFRESH action (which already exists) whenever a new integration makes use of said custom connector. Problem is that I do not know where and when should we dispatch that action. Perhaps @zregvart can help and point to the exact process or operation that initiates such change.
