### ISSUE TITLE
Pod with a new integration can replace any other existing pod on openshift with same name

### ISSUE THREAD

**Issue by mastepan** [syndesisio/syndesis#1438]
If there is an existing pod named X and you create and publish a new integration also with the very same name X then the old pod will be replaced by the new one. It can destroy whole Syndesis app.

**Comment by zregvart** [comment]
I think we should generate pod names of integrations and use labels to link them to Syndesis integration.

**Comment by zregvart** [comment]
We agreed to add a prefix names of objects we create on OpenShift. Perhaps `s-`?
