### ISSUE TITLE
[custom api connector] Disallow deleting a connector while there exists a related connection

### ISSUE THREAD

**Issue by mastepan** [syndesisio/syndesis#1442]
If there is a connection created from a custom connector we need to disallow deleting the connector. Because there is data missing for the connection then. (at least an icon what I have noticed)

**Comment by mastepan** [comment]
Or...each connection may have own data set independent on the connector once created. Then the connector can be easily deleted without any side-effects.
Otherwise we would need to solve changing-data chain from connector through connection to integration.

**Comment by deeleman** [comment]
Fixed by #1685
