### ISSUE TITLE
Fix circular references

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#1445]
Currently when the UI is built we get a bunch of warnings about circular references.  These need to be fixed, they create noise and can create hard to solve runtime problems.

**Comment by deeleman** [comment]
Perhaps we can enlist here them all in the issue description, so we can go ticking them as we fix them

**Comment by gashcrumb** [comment]
I feel like we might want to just bite the bullet and fix 'em all.  

Once it's fixed can we change our compiler config to turn this warning into an error?

**Comment by deeleman** [comment]
I'm afraid we can't, sorry. The `showCircularDependencies` setting is only designed to throw messages as warnings and the [CLI configuration API](https://github.com/angular/angular-cli/wiki/angular-cli) does not provide other tools for this.

**Comment by gashcrumb** [comment]
Ah, bummer, would have been a good CI check.  Well, we can still keep an eye out for 'em as a team, if they come up here and there it won't be as much effort to fix after this initial work.

**Comment by gashcrumb** [comment]
This seems like a [super interesting way](https://www.reddit.com/r/typescript/comments/4v7uzn/best_practices_for_avoiding_weird_circular/) to handle runtime issues with circular references, giving `forwardRef` a try here in some of the tests where I've really seen serious problems :-)

**Comment by deeleman** [comment]
That seems more of a way to patch an issue rather than preventing it :) 

Basically you're telling the DI that such dependency is not there already, which is true because it's undefined, and this is because the circular reference. If something else declares and hence injects that dependency by chance, then you're sorted. Otherwise, whatever was broken will keep... broken.

**Comment by gashcrumb** [comment]
Yeah, it's a way of deferring when the reference is actually evaluated, after the whole script is loaded vs being evaluated as the script is interpreted.

I've a PR that adds these to the integration list module as that one is shared by multiple modules since it's components are re-used in a couple different places, it's also let me clean up at least one test where I basically had to pull in individual components rather than just import the modules.

I'm finding that the barrels are a big cause of these circular dependencies, in fact I also hit that circular reference error from the AOT compiler while looking at that stuff.  But they add a ton of convenience when referencing dependent files, otherwise it's back to using file paths.  So I think I'd rather keep these as they are.  If we hit a runtime issue we can first try juggling imports or resort to `forwardRef`.

**Comment by gashcrumb** [comment]
Wonder, should we move from `target` `es5` to `es6`?  I guess with `es6` the direct references are replaced with bindings that work in the same way as `forwardRef`.  I like the barrels and I still haven't come across a way to suppress the warnings but still have barrels, and am starting to wonder if pursuing this is going to be worthwhile...

**Comment by gashcrumb** [comment]
@deeleman I propose we suppress the circular reference warnings and move on with our lives :-)

**Comment by deeleman** [comment]
Agreed
