### ISSUE TITLE
Blank error message on the Salesforce "Create or Update Record" page

### ISSUE THREAD

**Issue by honghuac** [syndesisio/syndesis#1451]
I am using Syndesis code base TP1.2.2 fix

This error message (which is blank) shows up - during configuration of Salesforce connection in the Integration setup:

![blank-err-sfdc-create-rec](https://user-images.githubusercontent.com/8625482/35906192-939f3096-0c24-11e8-8d7c-044848223859.png)

**Comment by honghuac** [comment]
Here is the trace from Google Chrome, https://gist.github.com/honghuac/ee438e250a4df5d44bd49e3bc06e2a10

No javascript errors. Only "502 Bad Gateway" and "Unexpected end of JSON input" errors.

**Comment by gashcrumb** [comment]
This is also due to connectivity
