### ISSUE TITLE
Configure Basic Filter Step - drop down list fails to appear

### ISSUE THREAD

**Issue by honghuac** [syndesisio/syndesis#1453]
The drop down list of Twitter "fields" fails to appear in the left most field on the "Configure Basic Filter Step" wizard page.

![eval-data](https://user-images.githubusercontent.com/8625482/35906899-2ffb9c0c-0c27-11e8-8150-6aa23a2beb05.png)

**Comment by honghuac** [comment]
Here is the trace from Google Chrome, https://gist.github.com/honghuac/ee438e250a4df5d44bd49e3bc06e2a10

No javascript errors. Only "502 Bad Gateway" and "Unexpected end of JSON input" errors.

**Comment by zregvart** [comment]
This should be fixed
