### ISSUE TITLE
Revisiting individual connections in an integration - "done" button fails

### ISSUE THREAD

**Issue by honghuac** [syndesisio/syndesis#1454]
The "Done" button seen on the configuration page of every connection introduced into an integration fails on subsequent revisits to the integration.

**Comment by honghuac** [comment]
Here is the trace from Google Chrome, https://gist.github.com/honghuac/ee438e250a4df5d44bd49e3bc06e2a10

No javascript errors. Only "502 Bad Gateway" and "Unexpected end of JSON input" errors.

**Comment by gashcrumb** [comment]
Connectivity issue
