### ISSUE TITLE
Configuration of Data Mapper page - shows up with no fields

### ISSUE THREAD

**Issue by honghuac** [syndesisio/syndesis#1455]
The data mapper page fails to load with any fields:

![blank-data-mapper](https://user-images.githubusercontent.com/8625482/35907288-6e94bbfa-0c28-11e8-8075-0bdde09b22b4.png)

**Comment by honghuac** [comment]
Here is the trace from Google Chrome, https://gist.github.com/honghuac/ee438e250a4df5d44bd49e3bc06e2a10

No javascript errors. Only "502 Bad Gateway" and "Unexpected end of JSON input" errors.

**Comment by gashcrumb** [comment]
Connectivity issue
