### ISSUE TITLE
502 Gateway error appears - when attempting to save Integration as draft

### ISSUE THREAD

**Issue by honghuac** [syndesisio/syndesis#1456]
A 502 Gateway error appears - when attempting to save Integration as draft.

![502-gateway](https://user-images.githubusercontent.com/8625482/35907435-e791225a-0c28-11e8-845e-fc2578125bb7.png)

**Comment by honghuac** [comment]
Here is the trace from Google Chrome, https://gist.github.com/honghuac/ee438e250a4df5d44bd49e3bc06e2a10

No javascript errors. Only "502 Bad Gateway" and "Unexpected end of JSON input" errors.

**Comment by gashcrumb** [comment]
Connectivity issue
