### ISSUE TITLE
Draft Integrations went missing

### ISSUE THREAD

**Issue by honghuac** [syndesisio/syndesis#1458]
Using TP3, draft integrations (previously saved) disappears after a few reloads of the Fuse Ignite console....

**Comment by honghuac** [comment]
And then reloads later, the dashboard shows up

![int-board](https://user-images.githubusercontent.com/8625482/35908565-109dd442-0c2c-11e8-9660-508b9ee09c0b.png)

**Comment by paoloantinori** [comment]
hi, can you check in the browser console for any error?

I'd like to understand if it's some manifestation of a late response or if it's really reported and/or logged

**Comment by honghuac** [comment]
@paoloantinori 

Here is the trace from Google Chrome, https://gist.github.com/honghuac/ee438e250a4df5d44bd49e3bc06e2a10

No javascript errors. Only "502 Bad Gateway" and "Unexpected end of JSON input" errors.

**Comment by gashcrumb** [comment]
This was due to connectivity to the backend.
