### ISSUE TITLE
[Connections] Remove View and Edit options from kebab menu

### ISSUE THREAD

**Issue by mastepan** [syndesisio/syndesis#1468]
**View** and **Edit** options does the same thing - bring a user to a connection's detail page. Same as if a user clicks a connection rectangle. The question is why?
I suggest to remove those 2 options from the menu if there aren't any clear plans of using them different way.

Also more visually noticeable highlighting of the connections rectangles when the mouse is over them would help. (in case a user can't find how to edit a connection. But I suppose it won't happen either.)
![vieweditconnectionremove](https://user-images.githubusercontent.com/8707251/35924157-8b046be2-0c22-11e8-9b68-cd0b4b0a540e.png)

**Comment by zregvart** [comment]
@syndesisio/uxd any thoughts on this?

**Comment by sjcox-rh** [comment]
Hmm, I agree that those options aren't needed under the kabob menu. My concern now is that with only only option available (Delete), we no longer need the kabob menu. However, don't think we should have an "x" of delete button on every card.

We can get rid of all action from the card view page and only allow delete on the details page. @amysueg @michael-coker @seanforyou23, @dongniwang  thoughts?

**Comment by michael-coker** [comment]
> We can get rid of all action from the card view page and only allow delete on the details page. 

Sounds good to me!

**Comment by mastepan** [comment]
@sjcox-rh I think the problem is different concepts of deleting Integrations, connections and custom connectors. What about to review all that areas and find a common solution?

@zregvart Do we know that there will not be any other actions than "Delete" (connections or custom connectors list) in the future? If there will be, we can let the kebab menu live...

I'd say it's always more convenient to offer easily accessible, visible and intuitive options instead of hiding them to a detail page.

**Comment by zregvart** [comment]
> @zregvart Do we know that there will not be any other actions than "Delete" (connections or custom connectors list) in the future? If there will be, we can let the kebab menu live...

Can't tell for sure, we can have "Duplicate" for instance or filter integrations using selected connection. If we're going to have those, hard to tell...

**Comment by amysueg** [comment]
For Integrations, the kabob menu contains a number of actions:
<img width="205" alt="screen shot 2018-02-13 at 1 03 49 pm" src="https://user-images.githubusercontent.com/31700119/36165727-80bb8eea-10be-11e8-9ed2-0698702a8b90.png">

I don't think there is much harm in providing more than one way of accessing the details (selecting the Connection card or selecting the menu and choosing view or edit), especially since we could then have a model where additional commands could be added.  Will it ever be valid to "export" a Connection? or Duplicate as @zregvart  says above?

I'm ok leaving it as is.

The only question I have is whether there is currently a difference between view and edit, or can there be if permissions are set for certain users who can only view? If so, then leaving both choices is valid.

**Comment by amysueg** [comment]
We are going to split out the issue of the visual design of the cards themselves. @seanforyou23 will open a separate patternfly repo ticket for that. Thanks for that feedback @mastepan 

The UX team discussed the original issue of the kebab menu on the connection cards. We agree that we should remove the kebab altogether. Edit/View and "select card" all do the same thing, and Delete is available from the details page. None of us think it is a good idea to leave "Delete" by itself as a button on the Connection card - it's just pretty un-welcoming. Until we understand usage patterns better, we think it is likely ok to leave Delete as an action on the details page.

**Comment by mastepan** [comment]
@amysueg Thank you and all UX team. Delete action on a detail page is one of the possibilities - the advantage is that it is more difficult to delete a connection accidentally (I know about confirmation dialogs but who reads them if in a hurry? :) ). My concern was we would have different approaches of deleting items from different lists. This is wrong I think. I will create a separate issue for that then and we can discuss it later.

**Comment by gashcrumb** [comment]
This needs to be turned into actionable issue(s)...

**Comment by mastepan** [comment]
> This needs to be turned into actionable issue(s)...

@gashcrumb @amysueg @seanforyou23 is there any such issue? We should keep track of it somewhere. If there is any, could you link it here please?
