### ISSUE TITLE
Unable to see the drop down "menu"/option for API connector in Integration editor view

### ISSUE THREAD

**Issue by weimeilin79** [syndesisio/syndesis#1485]
Using Tag 1.2.8
I created an API connector via the attached swagger doc. 
[https://raw.githubusercontent.com/weimeilin79/tp3demo/master/swaggerv2.yaml](https://raw.githubusercontent.com/weimeilin79/tp3demo/master/swaggerv2.yaml)

After I implemented my integration, I was not able to see the drop down option in the edit menu. 
(see diagram)

<img width="643" alt="screen shot 2018-02-08 at 2 03 22 pm" src="https://user-images.githubusercontent.com/2534483/35992870-8dadfc98-0cd9-11e8-8025-811d56a40f03.png">

**Comment by gashcrumb** [comment]
It may be because that particular action has no properties to edit.  The UI doesn't know this until it queries the backend currently, typically you'll see an info box in the main area notifying you, the UI then transitions back to the 'save or add step' page.

**Comment by weimeilin79** [comment]
So in this case, I am using a real-life HSBC swagger doc where they publish online as one of the open banking support in UK. 
I see most of them has parameter defined but not properties. Can you also support parameters too?

**Comment by zregvart** [comment]
Our current way of handling query/path/header parameters is by combining them with the body into a unified data shape. This way we have them available in the mapper step. Ideally we would have them in separate shape(s) from the body, but this is where we are now.

Would you expect them as properties of the action?  We have no support for evaluation in those, i.e. only way to use previous step's values in Syndesis is by leveraging mapping step.

**Comment by weimeilin79** [comment]
That make sense, but it's just that when you click on API connector nothing happens compare to other connectors.. I will close this issue.
