### ISSUE TITLE
UX Design: Integration Activity (Formerly Logs)

### ISSUE THREAD

**Issue by sjcox-rh** [syndesisio/syndesis#1487]
Designs for viewing integration level activity.

Introduced tabs within Integration summary page, one of them being Activity. From there user can:
- View details of each integration run and status of individual steps within each run.
- View full output of a specific step within a run
- Filter integration runs via a new date range tool

**Comment by paoloantinori** [comment]
Hi @sjcox-rh any update on this?

**Comment by sjcox-rh** [comment]
@paoloantinori the PR for the designs were merged. Should I close this or wait until implementation is complete?

**Comment by paoloantinori** [comment]
Close it please, this task was just to track the creation of UX design.
