### ISSUE TITLE
Blank action for API Client connectors

### ISSUE THREAD

**Issue by weimeilin79** [syndesisio/syndesis#1489]
If both the summary and description is available in the swagger doc (Yes, sometimes people do that.. ), the list of action will be blank. 

<img width="1565" alt="screen shot 2018-02-08 at 2 12 29 pm" src="https://user-images.githubusercontent.com/2534483/35993180-83e66fbe-0cda-11e8-9f2b-8add5153cc86.png">

**Comment by mastepan** [comment]
current behavior is as follows:
* summary specified - **summary text** printed
* summary property present but with no text - **null** printed
* summary unspecified - **task type and path** printed

Is it correct? I'd say if summary property is specified but doesn't have any text  then the result should be as if it is not specified at all. What do you think @zregvart ?

**Comment by zregvart** [comment]
> Is it correct? I'd say if summary property is specified but doesn't have any text then the result should be as if it is not specified at all. What do you think @zregvart ?

yes that makes sense, I've created #2223 to fix that.
