### ISSUE TITLE
Message connection gets reset, and never re-connects again. 

### ISSUE THREAD

**Issue by weimeilin79** [syndesisio/syndesis#1490]
When I have integration that connects to a broker, if I leave it running long enough, it'll get a reset exceptions, and never actually resets the connect, but instead just died. 

The integration should keep running and connection should retry to connect when timeout.

`
2018-02-08 18:29:48.120  WARN 1 --- [169.135.3:61617] o.a.camel.component.sjms.SjmsEndpoint    : Execution of JMS message listener failed. Caused by: [javax.jms.JMSException - Connection reset]
--
  | javax.jms.JMSException: Connection reset
  | at org.apache.activemq.util.JMSExceptionSupport.create(JMSExceptionSupport.java:54) ~[activemq-client-5.14.5.jar!/:5.14.5]
  | at org.apache.activemq.ActiveMQConnection.onAsyncException(ActiveMQConnection.java:1948) ~[activemq-client-5.14.5.jar!/:5.14.5]
  | at org.apache.activemq.ActiveMQConnection.onException(ActiveMQConnection.java:1967) ~[activemq-client-5.14.5.jar!/:5.14.5]
  | at org.apache.activemq.transport.TransportFilter.onException(TransportFilter.java:114) ~[activemq-client-5.14.5.jar!/:5.14.5]
  | at org.apache.activemq.transport.ResponseCorrelator.onException(ResponseCorrelator.java:126) ~[activemq-client-5.14.5.jar!/:5.14.5]
  | at org.apache.activemq.transport.TransportFilter.onException(TransportFilter.java:114) ~[activemq-client-5.14.5.jar!/:5.14.5]
  | at org.apache.activemq.transport.TransportFilter.onException(TransportFilter.java:114) ~[activemq-client-5.14.5.jar!/:5.14.5]
  | at org.apache.activemq.transport.WireFormatNegotiator.onException(WireFormatNegotiator.java:173) ~[activemq-client-5.14.5.jar!/:5.14.5]
  | at org.apache.activemq.transport.AbstractInactivityMonitor.onException(AbstractInactivityMonitor.java:345) ~[activemq-client-5.14.5.jar!/:5.14.5]
  | at org.apache.activemq.transport.TransportSupport.onException(TransportSupport.java:96) ~[activemq-client-5.14.5.jar!/:5.14.5]
  | at org.apache.activemq.transport.tcp.TcpTransport.run(TcpTransport.java:219) ~[activemq-client-5.14.5.jar!/:5.14.5]
  | at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
  | Caused by: java.net.SocketException: Connection reset
  | at java.net.SocketInputStream.read(SocketInputStream.java:210) ~[na:1.8.0_151]
  | at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[na:1.8.0_151]
  | at sun.security.ssl.InputRecord.readFully(InputRecord.java:465) ~[na:1.8.0_151]
  | at sun.security.ssl.InputRecord.read(InputRecord.java:503) ~[na:1.8.0_151]
  | at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983) ~[na:1.8.0_151]
  | at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940) ~[na:1.8.0_151]
  | at sun.security.ssl.AppInputStream.read(AppInputStream.java:105) ~[na:1.8.0_151]
  | at org.apache.activemq.transport.tcp.TcpBufferedInputStream.fill(TcpBufferedInputStream.java:50) ~[activemq-client-5.14.5.jar!/:5.14.5]
  | at org.apache.activemq.transport.tcp.TcpTransport$2.fill(TcpTransport.java:634) ~[activemq-client-5.14.5.jar!/:5.14.5]
  | at org.apache.activemq.transport.tcp.TcpBufferedInputStream.read(TcpBufferedInputStream.java:59) ~[activemq-client-5.14.5.jar!/:5.14.5]
  | at org.apache.activemq.transport.tcp.TcpTransport$2.read(TcpTransport.java:619) ~[activemq-client-5.14.5.jar!/:5.14.5]
  | at java.io.DataInputStream.readInt(DataInputStream.java:387) ~[na:1.8.0_151]
  | at org.apache.activemq.openwire.OpenWireFormat.unmarshal(OpenWireFormat.java:268) ~[activemq-client-5.14.5.jar!/:5.14.5]
  | at org.apache.activemq.transport.tcp.TcpTransport.readCommand(TcpTransport.java:240) ~[activemq-client-5.14.5.jar!/:5.14.5]
  | at org.apache.activemq.transport.tcp.TcpTransport.doRun(TcpTransport.java:232) ~[activemq-client-5.14.5.jar!/:5.14.5]
  | at org.apache.activemq.transport.tcp.TcpTransport.run(TcpTransport.java:215) ~[activemq-client-5.14.5.jar!/:5.14.5]
  | ... 1 common frames omitted
`

**Comment by zregvart** [comment]
Can you double check that that isn't just a exception being logged on first connection reset with the broker? By default Camel JMS component has a 5s recovery interval and it should reconnect after that.

cc @dhirajsb

**Comment by gashcrumb** [comment]
Is this still an issue or can it be closed?
