### ISSUE TITLE
syndesis-upgrade: "upgrade_stateful_resources"

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#1514]
#### Upgrade stateful resources

Now that the database has been migrated, the current infrastructure config maps might need to be upgraded, too.

This upgrade is similar to the DB migration, except that upgrade shell scripts are used for each version:

.Example ConfigMap upgrade
```
/upgrade-configmaps/
    ...
    1.3.sh
    1.4.sh
    ...
```

Again, as for JsonDB upgrades, these scripts are specific for a _target_ version.
In general, these upgrades scripts are used to add default values for new features (if not present) or change defaults.
As input the get a pointer to a copy of the extracted configmap files which they should adopt in place.

NOTE: No resources from generated integration pods are upgraded. This needs to be done as part of the Integration Upgrade process.

Finally, the generated upgraded configmaps are applied with `oc replace` to the cluster, overwriting the existing configmaps.

#### Rollback
A rollback replays all the original configmaps extracted in a previous configmap files

**Comment by avano** [comment]
@rhuss @dsimansk 

do we support user changes in (for example) syndesis configmaps? If yes, how they will be handled during upgrade process?

In ideal world upgrade should preserve user changes (if they are non-conflicting with the changes done by upgrade itself), but it may be a non-trivial task to do so

**Comment by avano** [comment]
@rhuss @dsimansk 

and one more thing - if there is no DB schema change or no configmap change, will the migrate directory for target version be empty / not used?

**Comment by rhuss** [comment]
@avano sorry, just saw your comments.

* The idea is that for configmaps and secrets there must be a dynamic script be written, which takes care of user specific changes (if possible). E.g. migrate the value or whatever. There can't be a general solution for this purpose, but if required this can be done with this hook (i.e. a script in `migration/resources` which does some oc and shell magic)

* The migrate directory will be just empty for this version (or even not existing, doesn't matter)
