### ISSUE TITLE
Integration editor remove duplicated/redundant css across editor pages

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#1534]
There's too much copypasta across editor pages in these files:

* [ ] https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/integration/edit-page/action-configure/action-configure.component.scss
* [ ] https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/integration/edit-page/action-select/action-select.component.scss
* [ ] https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/integration/edit-page/connection-select/connection-select.component.scss
* [ ] https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/integration/edit-page/integration-basics/integration-basics.component.scss
* [ ] https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/integration/edit-page/save-or-add-step/save-or-add-step.component.scss
* [ ] https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/integration/edit-page/step-configure/step-configure.component.scss
* [ ] https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/integration/edit-page/step-select/step-select.component.scss

i.e. css that's doing a lot of page layout for the toolbar etc.  This kind of stuff should probably go into the parent component here:

https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/integration/edit-page/edit-page.component.scss

**Comment by gashcrumb** [comment]
The big problem here is when you go and create a new editor page, the layout is totally wrong.  Until you copy stuff from one of the indicated files :-)

**Comment by michael-coker** [comment]
Submitted PR https://github.com/syndesisio/syndesis/pull/1549
