### ISSUE TITLE
Able to create duplicate connections

### ISSUE THREAD

**Issue by honghuac** [syndesisio/syndesis#1538]
During the course of testing, I was able to create duplicate connections. This is proof that the duplicate entity check can be circumvented.

![duplicate-connections](https://user-images.githubusercontent.com/8625482/36133499-4d63e34e-10b9-11e8-8f10-6da6a92a6450.png)

**Comment by zregvart** [comment]
I can reproduce this as in the final step of create connection wizard if I click the _Create_ button it takes a bit of time for the connection to be created allowing me to click the _Create_ button the second time.

Looks like we need locking support in jsondb to prevent race conditions, and we probably should disable buttons that issue POST requests on click.

cc @gashcrumb @chirino

**Comment by KurtStam** [comment]
@gashcrumb fixed disabling the 'create' button in a different PR.
