### ISSUE TITLE
Apply consistent case in connector descriptions

### ISSUE THREAD

**Issue by TovaCohen** [syndesisio/syndesis#1548]
When a user clicks Create Connection to display the connectors, each connector card provides a description but the use of case in these descriptions is not consistent.  Most of them use initial uppercase for all important words. The one for Twitter, has a  longer description that uses uppercase for just the first word. 

I know this seems trivial, but consistent style conventions do make the UI easier for the user to quickly process and understand. 

Since a user can create whatever description they want for a connector they create, and they are unlikely to use initial cap on every important word, could we make all the connector descriptions have initial uppercase and uppercase for proper nouns? And as long as we are doing that, could we make the connector descriptions a bit more helpful? I suggest:

Amazon S3
Direct object storage and retrieval

AMQ
AMQ message broker

Database
Invoke SQL or a stored procedure

Salesforce
The way it is now is fine: Cloud-based Customer Relationship Management

Twitter
Direct and event-driven interaction with tweets, timelines, mentions, searches

**Comment by oscerd** [comment]
Fixed.

**Comment by oscerd** [comment]
Let me wait for the end of the build at least.

**Comment by TovaCohen** [comment]
Thanks for taking care of this!
