### ISSUE TITLE
Config form input fields for steps/connections in the editor are too long

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#1550]
This has been bugging me for awhile, basically all the forms in the editor have really long input fields that stretch across the page, especially bad on widescreen monitors.

I don't know if this is really inline with the designs also.  Here's an example:

![download](https://user-images.githubusercontent.com/351660/36171911-4b83c99a-10d2-11e8-9216-25cef623896e.png)

**Comment by michael-coker** [comment]
@gashcrumb should they be something closer to the oath configuration form field length (or shorter than that)? Or do you have an example another page that currently displays them the way you're envisioning?

![screen shot 2018-02-13 at 3 07 58 pm](https://user-images.githubusercontent.com/35148959/36173824-df581304-10cf-11e8-9b43-d344044ad732.png)

**Comment by gashcrumb** [comment]
TBH even those forms seem a bit long to me...

So the connection configuration page in the create connection wizard isn't too bad, but part of that is the way the page is designed.

Normally bootstrap forms at least seem to have some max width built-in but somehow we've managed to break that in our own forms.  Though as I look at the patternfly example form page it's kinda got the same problem => https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/forms.html

@dongniwang I dunno, what do you think?

**Comment by michael-coker** [comment]
I think @dongniwang is out on PTO for the rest of the week.

@sjcox-rh what do you think?

**Comment by michael-coker** [comment]
We can easily just use the bootstrap grid to display the form itself in a more narrow column. No CSS required, and the column width can be different per component. What about this? Also, should the buttons under the form be flush with the right edges of the form inputs?

## before
![screen shot 2018-02-13 at 4 18 44 pm](https://user-images.githubusercontent.com/35148959/36176921-c8df2734-10d9-11e8-83f4-a4d02c598e73.png)

## after
![screen shot 2018-02-13 at 4 19 39 pm](https://user-images.githubusercontent.com/35148959/36176923-c8edbc2c-10d9-11e8-94ff-34aeb0922481.png)

**Comment by michael-coker** [comment]
@gashcrumb looks like the existing input length is inline with the designs from UXD. I'm not sure if that's the latest design, since there are some discrepancies (for example, everything's in a white box, the button alignment is different) 

From https://github.com/syndesisio/syndesis/blob/master/ux/designs/describe-data/describe-data.md

![](https://github.com/syndesisio/syndesis/raw/master/ux/designs/describe-data/img/describe-data-configaction.png)

**Comment by michael-coker** [comment]
@gashcrumb how about this? 

![screen shot 2018-02-14 at 11 02 41 am](https://user-images.githubusercontent.com/35148959/36217430-042c3adc-1177-11e8-8d42-550b4d411187.png)

**Comment by gashcrumb** [comment]
@michael-coker that's a huge improvement :-)

I'll have to see if I can get that `fields marked with * are required` text in there, otherwise the padding on the top (between the form element top and the first control) looks a little out of balance as compared to the bottom.

**Comment by michael-coker** [comment]
@gashcrumb (sorry, been in meetings)

> I'll have to see if I can get that fields marked with * are required text in there

I can always add it in the HTML, too.

> padding on the top (between the form element top and the first control) looks a little out of balance as compared to the bottom.

Agreed,  but if you reference the design from UXD above, the spacing is similar. 

How about this? It mimics the card layout for configuring a connection.

![screen shot 2018-02-14 at 2 56 38 pm](https://user-images.githubusercontent.com/35148959/36227639-4af61c24-1197-11e8-9b5e-f1b2be20c1f1.png)

Here's the connection configuration page for reference.

![screen shot 2018-02-14 at 2 51 12 pm](https://user-images.githubusercontent.com/35148959/36227405-986f0840-1196-11e8-813c-40b8d048b9a8.png)

**Comment by gashcrumb** [comment]
> I can always add it in the HTML, too.

I think it needs to be conditional based on the form config, created #1573 to track that

> How about this? It mimics the card layout for configuring a connection.

Perfect!  Ship it!  :-)

**Comment by michael-coker** [comment]
@gashcrumb created https://github.com/syndesisio/syndesis/pull/1574 and left a comment in the PR description about one part of it I wasn't sure about.

**Comment by amysueg** [comment]
can this be close since the related PR #1574 is merged?

**Comment by michael-coker** [comment]
@amysueg yep!

**Comment by amysueg** [comment]
Looks awesome! Thanks @mcoker!![bitmoji](https://render.bitstrips.com/v2/cpanel/43533bc8-de9f-4e89-9f7d-f9a64b6254c4-cc737c0e-145d-4d97-aea9-1fdd38b44e0a-v1.png?transparent=1&palette=1&width=246)
