### ISSUE TITLE
Use 'kind' for the data shape type consistently, and pick either '*' or 'any'

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#1551]
Currently I see in an integration I've created:

```
"inputDataShape": {
            "kind": "none"
          },
          "outputDataShape": {
            "name": "some name",
            "type": "any",
            "specification": "{}"
          },
```

for the start connection (I added the stuff in the output), I added a JMS request response as a middle step, it's data shapes look like:

```
          "inputDataShape": {
            "type": "any"
          },
          "outputDataShape": {
            "type": "*"
          },
```

Can we settle on either `kind` or `type` and also settle on if it should be `any` or `*`?

**Comment by igarashitm** [comment]
datamapper expects `DataShape.kind` is one of 
* none
* any
* java
* json-schema
* json-instance
* xml-schema
* xml-instance

`DataShape.type` is a special property for `DataShape.kind === 'java'`, which holds a class name. Other than that it's not going to be used anywhere.

**Comment by igarashitm** [comment]
I think it's better to introduce `DataShapeKind` enum in both of backend and UI, then make `DataShape.kind` being that enum.
