### ISSUE TITLE
Need a 'userDefined' boolean property on the DataShape type

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#1552]
Right now I'm using `type` for determining if I need to prompt for a data shape schema.  However I'll need to set the type/kind to something based on the user input.  Once that's set I'll have no way of determining that the data shape was actually user defined.

We need a boolean property on the data shape type that the UI can use to indicate that a data shape has a user defined type set so the UI knows that it needs to make that page available as the user configures a step.

**Comment by lburgazzoli** [comment]
Can we use tags as we do in other places ?

**Comment by gashcrumb** [comment]
Does the data shape type have tags?  Or do you mean tags on the integration?  If the latter that seems like an abuse of tags, the original intent for tags was grouping and filtering.

**Comment by lburgazzoli** [comment]
No data shape does not have tags but we can add them if needed si it may be more flexible that a dedicated boolean.

**Comment by gashcrumb** [comment]
true, really just an attribute of name/value pairs like `properties` would be more suitable perhaps?

**Comment by lburgazzoli** [comment]
we have [WithMetadata](https://github.com/syndesisio/syndesis/blob/master/app/core/model/src/main/java/io/syndesis/model/WithMetadata.java) that could do the job

**Comment by gashcrumb** [comment]
Yep, I think that'd work!

**Comment by dhirajsb** [comment]
Created PR #1585

**Comment by gashcrumb** [comment]
With that merged this can be closed, thanks Dhiraj!
