### ISSUE TITLE
[import] fail to import an integration using sampledb - "Unable to decrypt key password"

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis#1557]
Trying to publish an integration from a different cluster that uses db connector fails with this error:

**Unable to decrypt key password**

The error per se makes sense, since the imported `model.json` contains this section:

```json
"connection": {
    "configuredProperties": {
        "password": "»ENC:3b463fe7a81bd633c6483dc38203e3dbb29e6f37b3358f85160869fef90129b90a6797cf7b247be3344d3eddd7a1eeb4",
        "schema": "sampledb",
        "url": "jdbc:postgresql://syndesis-db:5432/sampledb",
        "user": "sampledb"
    },
    "connectorId": "sql",
    "description": "Connection to SampleDB",
    "icon": "fa-database",
    "id": "5",
    "isDerived": false,
    "name": "PostgresDB",
    "tags": [
        "sampledb"
    ]
},
```

My question is: should we improve the UX in any way? Prechecking what we are about to import and we know for sure it's going to fail? Adding metedata at export time?

Currently the failed Integration shows just this:

![screenshot from 2018-02-14 12-05-08](https://user-images.githubusercontent.com/1520602/36201162-61063cc8-117f-11e8-94c7-1680d0250670.png)

@chirino what's your opinion here?

**Comment by chirino** [comment]
So it’s expected that after an import connections will need to be re-configured for the new env. We need to mark those connections as failing verification and needing user updates. I think there is some Uxd for this. Btw this can also
Occur when a connector gets upgraded and changes config fields for a connection

**Comment by chirino** [comment]
Basically we need a integration and connection validation api. Where it reports back any error associated with each and reports those on the appropriate detail pages. 

You should be able to enter in the right password for the db connection and the problem goes away right?

**Comment by lburgazzoli** [comment]
We have something similar for the extensions so you first upload the binary, then the backend does a validation of the extension content and reports errors. We may generalize the import of resources and have some hooks for validation according to the type.
