### ISSUE TITLE
Unable to publish unpublished integration using it's "version 1"

### ISSUE THREAD

**Issue by tplevko** [syndesisio/syndesis#1559]
When I unpublished integration and afterwards I tried to publish it using the history "version:1", where there is also "publish" option in the dropdown window, the integration won't start. The whole history seems to not work as expected, I encounter the same issue, when I try to revert the integration to some point in the history, the integration simply won't start.
![out](https://user-images.githubusercontent.com/4180208/36202915-ed740edc-1185-11e8-96fa-192d63e46b66.gif)

**Comment by paoloantinori** [comment]
@iocanel  could you have a look to this?

**Comment by iocanel** [comment]
This issue has been fixed. Though last time I checked it had also been shadowed by the removal of `history` from the integratio details page. 

Not sure what's the current status.

**Comment by deeleman** [comment]
The History tab was reinstated a couple of days ago

**Comment by iocanel** [comment]
Now that history is back I managed to verify that it works as expected.
