### ISSUE TITLE
Correct the labels for the main steps for creating an API connector

### ISSUE THREAD

**Issue by TovaCohen** [syndesisio/syndesis#1561]
@zregvart @kahboom @sjcox-rh 

When a user clicks "Create API Connector", the API Client Connector page displays the main work flow:
![image](https://user-images.githubusercontent.com/25067106/36209346-82b1e400-1169-11e8-80dc-64ad914d0a85.png)

These labels really need to change:

Upload Swagger               >>>  Upload Swagger Specification 
Review Swagger Action   >>>  Review Actions
Security                             >>>  Specify Security
General Connector Info    >>>  Review/Edit Connector Details

And then of course the box title in each step needs to change to match those labels. 
I confirmed these changes with both Rachel and SJ a while ago. But somehow this never made it in.

**Comment by gashcrumb** [comment]
This was fixed in the linked PR, thanks @zregvart !
