### ISSUE TITLE
DB connector Periodic SQL/Stored Procedure Invocation actions not working

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis#1566]
On a fresh build, the PostgresDB connection is the only Connection provided OOTB (it seems), so I selected it to create an Integration, but neither of the actions are working properly.

I think @KurtStam was not able to reproduce the issue, so this might be just a problem in my env.

### To reproduce:
1. From the Dashboard or Integrations list page, select Create Integration.
2. Select PostgresDB (or equivalent) as the connection. If there is no PostgresDB connection, create one using the Database connector.
3. Select either option as the action ("Periodic stored procedure invocation" or "Periodic SQL invocation").
4. Name your stored procedure (or add the SQL statement, depending on which action you selected) to activate the "Done" button.
5. Click the blue activated "Done" button.

At this point, nothing happens, but a few errors in the browser console appear. See screenshots below.

```
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
ERROR Error: Uncaught (in promise): SyntaxError: Unexpected token u in JSON at position 0
SyntaxError: Unexpected token u in JSON at position 0
```

Network tab:
```
{"errorCode":500,"developerMsg":"Unable to fetch and process metadata"}
```

### Screenshots

<img width="1680" alt="screenshot 2018-02-14 11 26 10" src="https://user-images.githubusercontent.com/3844502/36215485-415ba0ca-117a-11e8-8d47-2dde58e550f4.png">

<img width="1680" alt="screenshot 2018-02-14 11 26 40" src="https://user-images.githubusercontent.com/3844502/36215487-430d326c-117a-11e8-95cd-b854e04bd1a5.png">

### Logs

Tried to obtain verifier and REST pod logs to no avail. Potentially could be a UI-related issue, however, the OS console is showing a toast notification "Server connection interrupted" which means it could need further testing.

<img width="1679" alt="screenshot 2018-02-14 11 21 07" src="https://user-images.githubusercontent.com/3844502/36215180-62edf630-1179-11e8-8f40-447ea1533c48.png">

<img width="1677" alt="screenshot 2018-02-14 11 21 40" src="https://user-images.githubusercontent.com/3844502/36215184-6475159c-1179-11e8-988b-3d95744f5099.png">

cc @KurtStam

**Comment by KurtStam** [comment]
@kahboom 

1. When using the Stored procedure actions, this is supposed to be a list you pick from, and it should list the available stored procedures. I will add one by default (task for me), but it seems like a UI bug that you can try to type something.

2. Try to use Periodic SQL Invocation and type "SELECT * FROM CONTACT", and then as the finish action select the Stored Procedure invocation, and select 'add_lead'.

Does that work at least?

**Comment by KurtStam** [comment]
I created to new issue to create a default stored procedure: https://github.com/syndesisio/syndesis/issues/1773
