### ISSUE TITLE
Slack Connector

### ISSUE THREAD

**Issue by sunilmeddr** [syndesisio/syndesis#1572]
Implement Slack Syndesis connector component.

Connector level Parameters
-webhookUrl

Actions
-Send to Channel
-Send to User

Action Parmeters
--username
--iconUrl

Verifier
No (but implement)

Unit Test Approach
undefined

**Comment by dsimansk** [comment]
@kcbabo it this Connector required for the GA? I wonder if it wouldn't be better to implement it as an optional Extension similar to IRC and Telegram extensions.

@rhuss @lburgazzoli wdyt?

**Comment by kcbabo** [comment]
It's one of the connectors that Sunil is looking at.  Whether it's in for GA will depend on if we can get it done in TP4.

**Comment by dsimansk** [comment]
@kcbabo @paoloantinori 
Jus to sanity check. Slack connector made to TP4. Does it mean we will ship it for GA? However it haven't been tested by QE yet. We can probably give it a spin in a upcoming days, but I still wonder if there a requirement to have Slack connector vs. other chat platforms.

**Comment by paoloantinori** [comment]
As far as I know, this was one of the connectors we commissioned to MediaDriver and that we have reviewed and merged. So I consider this a core integrator, and even if we had any requirement for other chat platforms, it won't probably be implemented by tomorrow, that is the last day of development.
So please go ahead.

**Comment by kcbabo** [comment]
Slack is definitely in scope for GA.
