### ISSUE TITLE
When creating integration in Draft state, indefinite waiting for redirect to integration page

### ISSUE THREAD

**Issue by tplevko** [syndesisio/syndesis#1578]
I create simple integration and saved it as a draft. I expected redirect to integrations listing, the page however did not redirect. I experienced this issue on newest build of syndesis.

![indefinite_draft](https://user-images.githubusercontent.com/4180208/36248514-111b671a-1238-11e8-9e62-8ea98d74aef4.gif)

**Comment by gashcrumb** [comment]
Staying in the editor when just saving was discussed here -> https://github.com/syndesisio/syndesis/issues/239 and I recently changed the editor to do that.

Will look into what happened with that button behavior though.

**Comment by gashcrumb** [comment]
Can't seem to reproduce this locally on master, any javascript console errors perhaps?

**Comment by tplevko** [comment]
I seems like the root cause of the indefinite waiting is that after I click "save as draft", the site is not redirected to integrations, and rather the view stays on the new integration page. The indefinite waiting occurs after second click on "save as draft", which seems to try to create the integration, which already exists. This occurs in the log:

{{
2018-02-16 09:51:45,245 INFO [CurrentFlow] Error saving integration: {
  "_body": "[{\"error\":\"UniqueProperty\",\"message\":\"Value 'test' is not unique\",\"property\":\"create.obj.name\"}]",
  "status": 400,
  "ok": false,
  "statusText": "Bad Request",
}}

Full log is attached.
[Uploading error_saving_integration.log…]()

**Comment by tplevko** [comment]
And one more gif :)
![save_as_draft](https://user-images.githubusercontent.com/4180208/36300257-ce0fba74-1300-11e8-9044-bc60e2835123.gif)

**Comment by gashcrumb** [comment]
Ah yes, missed that there was a second click.  Seems like we're not getting the ID back into the integration properly, will look into it, thanks!
