### ISSUE TITLE
New version on every integration stop/start

### ISSUE THREAD

**Issue by tplevko** [syndesisio/syndesis#1602]
Every time I stop and then start an integration, the newly started integration is started from new version (no integration editing needed). This in my view causes unnecessary version creation, where the newly created "version x" is basically the same as the "version x-1". This after several starts/stops and edits would lead to confusion in versions on integration export. 

The behavior:
![versions_new_integration_start](https://user-images.githubusercontent.com/4180208/36372821-843b6d68-1566-11e8-9a65-4a77c8548f0b.gif)

**Comment by paoloantinori** [comment]
ping @kcbabo

**Comment by kcbabo** [comment]
Are you asking whether I think stopping/starting an integration should change the version?  If so, my answer is no, it shouldn't. :-)

**Comment by paoloantinori** [comment]
@tplevko Publish and Unpublish is not equivalent to Stop/Start. A publish is expected to re-build and create a new version.

**Comment by tplevko** [comment]
@kcbabo @paoloantinori Thank you for the explanation. I however would like to ask, so there won't be any scale up and scale down option for user (as would be the equivalent from start/stop operation)?

**Comment by kcbabo** [comment]
We do not support scale up/down of integration containers through the Synedesis UI at this point.  I'm not sure we'll ever support that - scale up/down would be better handled by the Syndesis runtime automatically based on utilization.
