### ISSUE TITLE
Remove the limitation of one integration route for minishift installation

### ISSUE THREAD

**Issue by abouchama** [syndesisio/syndesis#1608]
Deploying syndesis project on Minishift is still limited to only one integration route, even if we have more cpus & memory defined.

Is it possible to turn this limitation to off ?  or expose it as a configuration to have the control on it ?

**Comment by zregvart** [comment]
You can change deployment of `syndesis-rest` to include `CONTROLLERS_MAX_INTEGRATIONS_PER_USER=0` and `CONTROLLERS_MAX_DEPLOYMENTS_PER_USER=0` to have unlimited integrations and deployments.
