### ISSUE TITLE
Liveness probe for REST Pod should be switched off

### ISSUE THREAD

**Issue by honghuac** [syndesisio/syndesis#1616]
In the TP3 release of Syndesis, both readiness and liveness probes continue to cause the REST pod to restart and redeploy. Below are the log entries arising from the probe.

`5:26:57 PM | Warning | Unhealthy | Readiness probe failed: Get http://10.1.7.122:8181/health: dial tcp 10.1.7.122:8181: getsockopt: connection refused28 times in the last 10 minutes
-- | -- | -- | --`
`5:25:07 PM | Warning | Unhealthy | Liveness probe failed: Get http://10.1.7.122:8080/api/v1/version: dial tcp 10.1.7.122:8080: getsockopt: connection refused`

These health checks are unnecessary and only causes long wait times for creation and testing of integrations.

**Comment by zregvart** [comment]
We're getting awful experience because of pod restarts due to liveness probes. We should either remove them or configure them correctly.

Let me dial in some OpenShift/Kubernetes support by calling @chirino, @iocanel and @rhuss for help.

**Comment by kcbabo** [comment]
REST server would bounce every once in a while in TP3 for me.  With the TP4 tag (1.3.1), I'm seeing the rest server pod fall over left and right.  Not sure if it's due to this issue or something else, but definitely something that needs to be addressed prior to GA.

**Comment by kcbabo** [comment]
Hmm ... looking at the pod details page, I see this:
Terminated at Mar 14, 2018 10:31:40 AM with exit code 137 (OOMKilled)

So perhaps the issue with 1.3.1 is more around mem limits than liveness probe?
