### ISSUE TITLE
Support page enhancements

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#1617]
There is an e-mail "fuse-online-tech-preview@redhat.com" mentioned - do we know how will this e-mail look like after we leave technical preview phase?

Maybe we can add more information about versions used in syndesis instance - like Camel version and some other versions which may be useful, wdyt?

Can we please add IDs to elements which carry important information from testing perspective such as syndesis version (now it is just paragraph element) so our tests will stay relevant even in case of design change?

**Comment by dsimansk** [comment]
@paoloantinori is it possible to expect any movement before TP4?

**Comment by paoloantinori** [comment]
I don't know if the information about text will be known in advance. @TovaCohen could help on this.

I don't think we'll be adding any functionality enhancement to this, for tp4, but if you need different markup to help with selenium test, you can modify the markup metadata directly here:

https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/support/support.component.html

**Comment by TovaCohen** [comment]
It sounds like you want to add some explanatory information to the support page -- is that right? 
What does "information about text" mean?
If you can tell me what the user needs to know, then I can suggest how to write it.
