### ISSUE TITLE
Blank page with no errors sometimes when adding a data mapper step

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#1621]
Hmm, well you can't see it that well but in this case I've added a middle connection and a data mapping step after that connection, and I've defined the types as JSON instance data.  The first data mapper step in the flow loads up fine, but the second one does not

![datamapper-issue](https://user-images.githubusercontent.com/351660/36430716-dd5dcc52-1623-11e8-92bd-c28220511174.gif)

@igarashitm FYI

**Comment by gashcrumb** [comment]
So really the only issue with the data mapper is no error is shown, as it turns out the SQL connector returns `json-schema` for the `kind` on the input data shape in that last step with no specification if the SQL to invoke doesn't have an input parameter, in this case the SQL connector should have `none` for it's input data shape.

**Comment by igarashitm** [comment]
Now required pieces are all ready:
* #1624 fixes to respect SQL connector returns `none` if there's no parameter for the SQL
* atlasmap/atlasmap#297 fixes initialization error handling in atlasmap so it displays the error message if there's no source or target document.
* #1627 uses atlasmap/atlasmap#297

**Comment by igarashitm** [comment]
merged
