### ISSUE TITLE
Do we need a 'nothing' connector?

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#1630]
So you can start from `nothing` or end with `nothing`.

Can anyone think of a good use case?

**Comment by dsimansk** [comment]
Maybe to demo/test extension functionality, external connectivity etc. Then the use case might be`Timer->Ext->Log?->Nothing`.

**Comment by gashcrumb** [comment]
A connector that produces periodic messages or just acts as a sink would be handy for testing/development, especially if they both had *any* types for input and output, and if you could also maybe specify the message in the action configuration in a textarea.

**Comment by gashcrumb** [comment]
Let's continue discussing and maybe then update the description once a consensus is reached.
