### ISSUE TITLE
Prometheus Pod stopped with error  - Opening Storage Failed

### ISSUE THREAD

**Issue by honghuac** [syndesisio/syndesis#1634]
![prome-pod-err](https://user-images.githubusercontent.com/8625482/36526245-6c540c58-17e8-11e8-8f81-fc0452f7bd1c.png)

This error appeared today, while Fuse Ignite was idling.

**Comment by dhirajsb** [comment]
Is the mount volume NFS by any chance? There was a known [issue](https://github.com/prometheus/prometheus/issues/3534) reported for v2.0.0, so I have bumped the version to 2.0.1 in a [new PR](https://github.com/syndesisio/syndesis/pull/1863).

**Comment by dhirajsb** [comment]
@honghuac once you confirm that this doesn't happen with Prometheus 2.1.0, can you please close this issue?

**Comment by dhirajsb** [comment]
Closing after version change. Please reopen if it doesn't fix the Prometheus issue.
