### ISSUE TITLE
API connector: ignore certificate error config

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis#1637]
This issue boils down to general support for certificates per Syndesis infra deployment https://github.com/syndesisio/syndesis/issues/224

When running on-premise in a cluster with self-signed certificate or consuming internal API endpoint with self-certificate. It might be useful to allow users to ignore certificate errors with a configurable parameter.

There're at least 2 aspects:
- consuming swagger file from self-signed https endpoint
- passing ignore config param to Camel integration runtime

**Comment by dsimansk** [comment]
@zregvart from the feedback I've seen it seems that there're some users asking for this config option. Wdyt? Do we need Keith to make a decision on it?

**Comment by zregvart** [comment]
> @zregvart from the feedback I've seen it seems that there're some users asking for this config option. Wdyt? Do we need Keith to make a decision on it?

I used to do a lot of PKI, so my opinion is skewed towards not trusting certificates that are not trusted and never allowing the user to circumvent that.

In general I think the users should be better of communicating with endpoints  that have trusted, valid certificates.

That being said I think a proper solution to this is not on a connector by connector basis, but having a centrally managed trust (#224).

**Comment by zregvart** [comment]
Let's not do this, but add proper support for custom PKI in what follows #224.
