### ISSUE TITLE
integration history view, no data for detail view

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#1652]
In the integration history design there's a number of fields shown -> https://github.com/syndesisio/syndesis/blob/master/ux/designs/integration_details/integration_details_page.md#expanding-a-row

None of this data is being returned from the API call so there's nothing to currently show in the detail area for a row, so it's just blank.

**Comment by deeleman** [comment]
@gashcrumb Perhaps this issue is no longer relevant?

**Comment by gashcrumb** [comment]
Agreed!  At least requires more specific issues :-)
