### ISSUE TITLE
Review Data Buckets UXD

### ISSUE THREAD

**Issue by igarashitm** [syndesisio/syndesis#1654]
@dongniwang is specifically concerning about the multiple source documents are shown expanded, which is supposed to be really longer and always need to scroll.
This is also related to the unresolved issue https://github.com/atlasmap/atlasmap/issues/105

Cc: @amysueg , @sjcox-rh

**Comment by amysueg** [comment]
Design decision is collapsing the sources in the source card in the default view.

**Comment by dongniwang** [comment]
Latest PR #1671 is created to address this. Please review.

**Comment by igarashitm** [comment]
#1671 has been merged. Thanks @dongniwang :+1:

**Comment by igarashitm** [comment]
#1686 - Forgot to add this link, impl ticket for collapsing source docs
