### ISSUE TITLE
When exceeded salesforce API call limit, connection message "unexpected HTTP error"

### ISSUE THREAD

**Issue by tplevko** [syndesisio/syndesis#1659]
There is this message, when I exceeded salesforce API calls limit: "An unexpected HTTP error occured. Please check stack strace".
I want to ask, whether there could be a better way to notify the user, that he exceeded the salesforce API call limit, because looking into stack trace (there is a typo at least) is quite cumbersome.

The screenshots:

![salesforce_api_calls_exceeded](https://user-images.githubusercontent.com/4180208/36587559-d4056232-1885-11e8-9038-6364f762ad9f.png)
![an_unexpected_salesforce_error](https://user-images.githubusercontent.com/4180208/36587571-df6cf234-1885-11e8-874b-01ec7b3694ce.png)

**Comment by zregvart** [comment]
We should handle this better. I wonder if you get the integration running is the error count increasing in the metrics, I think it should.
