### ISSUE TITLE
Reduce vertical space between steps in integration editor

### ISSUE THREAD

**Issue by michael-coker** [syndesisio/syndesis#1672]
From @kcbabo 

> When creating an integration, the amount of space between steps is really large.  We had talked about eliminating some of that space, but I don't think it's been implemented.  Interestingly, when you save/publish an integration space between steps collapses down.

**Comment by amysueg** [comment]
Thanks for creating this issue @michael-coker - can you check in with @sjcox-rh  regarding the visual design aspect of this?

**Comment by michael-coker** [comment]
@kcbabo just to make sure I'm looking at the right thing, are you referring to this?

![screen shot 2018-02-26 at 9 18 11 am](https://user-images.githubusercontent.com/35148959/36678364-27253c6a-1ad6-11e8-999e-3f6fd98cf34f.png)

And you would prefer it look closer to this?

![screen shot 2018-02-26 at 9 17 53 am](https://user-images.githubusercontent.com/35148959/36678380-30ed6e2a-1ad6-11e8-8f41-07b2b9a00905.png)

**Comment by kcbabo** [comment]
Yes and yes.

**Comment by michael-coker** [comment]
@kcbabo @sjcox-rh adjusted the space and took screenshots of the workflow for your review. Let me know if this looks OK. https://drive.google.com/drive/folders/1Kln6Xqu0WCezLfkQPHldkHegiZL4hKS-?usp=sharing

**Comment by kcbabo** [comment]
LGTM!
