### ISSUE TITLE
missing id for select element  

### ISSUE THREAD

**Issue by Stefan365** [syndesisio/syndesis#1675]
Element 
```
<select class="duration-input__select ng-pristine ng-valid ng-touched">
```
is missing id.

![missing_id](https://user-images.githubusercontent.com/2714974/36669241-8234da0c-1af4-11e8-889e-45f4ca4856e6.png)

**Comment by Stefan365** [comment]
text of issue corrected.

**Comment by dsimansk** [comment]
@kahboom @gashcrumb could we add an `id` or `name` attribute to be easily targetable from test code?
