### ISSUE TITLE
FTP connector: Order of items in connection configuration form

### ISSUE THREAD

**Issue by Stefan365** [syndesisio/syndesis#1678]
I think items in FTP configuration form should be listed/sorted in more user friendly way. see picture.

![ftp_configuration](https://user-images.githubusercontent.com/2714974/36675792-45986012-1b0a-11e8-9f14-8eda0a8798b2.png)

**Comment by dsimansk** [comment]
@seanforyou23 how is the ordering enforced, just by the ordering of parameters in connector?

**Comment by dsimansk** [comment]
@sunilmeddr fyi

**Comment by gashcrumb** [comment]
So yeah, the forms should be rendered in whatever order the fields come back from the backend.  We've a [client-side hack](https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/connections/common/configuration/configuration.service.ts#L35-L42) at the moment that we can use to specify an exact order, and then there's an open issue to either add support at the backend for an additional attribute or an `index` property to fields: #1204

**Comment by lburgazzoli** [comment]
@gashcrumb @dsimansk can you tell me which is the order you whant them to be displayed ? I'm working on some connectors stuffs so I can take it

**Comment by zregvart** [comment]
I think we implemented this.
