### ISSUE TITLE
FTP connector: datashape definition display errors in UI

### ISSUE THREAD

**Issue by Stefan365** [syndesisio/syndesis#1692]
Steps to reproduce:
1. Select Create Integration.
2. Select start connection FTP.
3. Select action "download" and specify details
4. Select finish connection FTP.
5. Select action "upload" and specify details.
6. add datamapper step. 
7. then you are provided wit datamapper gui.

this looks strange, see pictures.
![ftp_datamapper1](https://user-images.githubusercontent.com/2714974/36728069-c84be640-1bbf-11e8-9f9e-122c6530e4b9.png)
![ftp_datamapper2](https://user-images.githubusercontent.com/2714974/36728075-cabbda98-1bbf-11e8-85cb-256a4e49d4c7.png)

Perhaps in some cases (like FTP?) datamapper step doesn't make sense and user shouldn't have this option.

**Comment by dsimansk** [comment]
@igarashitm Tomo, is there anything that can be done on Atlasmap side?

**Comment by igarashitm** [comment]
I don't know about the background though, having Camel Message as a data type is a wrong way to do IMHO. Instead FTP kind of connector should be shapeless, i.e. it should be kind=`any` and user should step into "describe data type" scenario.

**Comment by dsimansk** [comment]
@sunilmeddr it seems that it'd be better to switch FTP/SFTP connectors to shapeless variant.

Cc @lburgazzoli @paoloantinori any other opinions?

**Comment by lburgazzoli** [comment]
@igarashitm is correct, we should make ftp/ftps as shapeless or we need to define a custom payload but shapeless is better imho.

**Comment by igarashitm** [comment]
Yep, please note that the JMS connector is shapeless ATM, so I would put FTP* into same category. If we consider about introducing DTO, I think we should take JMS into account as well.

**Comment by lburgazzoli** [comment]
@dsimansk @igarashitm I0m working on it
