### ISSUE TITLE
UI: Show Notification Messages associated with Connections/Integrations

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis#1695]
A new api data is available to get connection or integration related notifications.
Integration Overview objects can now contain a "messages" field.

```
"messages": [{
"level":"INFO", // "WARN" or "ERROR"
"message": "the message"
}]
```

You can get similar messages for a connection by hitting:

```
curl /api/v1/connections/5/bulletins
{
  "id": "5",
  "createdAt": 0,
  "updatedAt": 0,
  "messages": [{
    "level":"INFO", // "WARN" or "ERROR"
    "message": "the message"
  }]
}
```

**Comment by chirino** [comment]
This issue is related to the import epic.
On import of a connection, if the connection has secrets that need to be reset, an associated message will be created for it.

The upgrade epic is related too. 
When an integration is using a connector/conneciton that has been updated, there should be a upgrade available notice posted as a message to let the user know to trigger a publish to pickup the update.

**Comment by chirino** [comment]
These new APIs can be used to drive these notifications shown in this UXD design:
https://github.com/syndesisio/syndesis/blob/master/ux/designs/importexport/importexport.md

![syndesis_importexport_md_at_master_ _syndesisio_syndesis](https://user-images.githubusercontent.com/103255/36735231-ab45c3c0-1ba3-11e8-8b59-ec331ea34947.jpg)

**Comment by chirino** [comment]
And should also show integration specific notification messages somewhere on the integration details page similar to:

![syndesis_integration_details_page_md_at_master_ _syndesisio_syndesis](https://user-images.githubusercontent.com/103255/36736106-b69c5e26-1ba5-11e8-9a6f-63092d891fee.jpg)

**Comment by gashcrumb** [comment]
A problem with making this a separate remote invocation at least for connections is on that list view the UI is going to have to make a separate call for each connection, that's going to suck when a user has lots of connections.  Would it make more sense to inline the property in the connection object?

And the use case for the connection views is really whether or not the user needs to reset it's credentials, I wonder does it really need to be a list of messages that the UI needs to parse?  Seems like a simple boolean on the connection object whether or not the credentials need to be updated should suffice?

**Comment by chirino** [comment]
I'm not sure we want to update the connection object when something happens external to the connection.  For example when a connector upgrade is available.

**Comment by gashcrumb** [comment]
So what kind of message is that API going to return?  The thing is, the design for the list page there only seems to require adding a simple indicator that the connection needs some attention by the user.  But then the API is returning some unbounded array of message objects with levels and some string message.  What's the UI going to with all that extra information?  I could see this as more useful on the connection detail page where we have the space to show a list of various messages to the user, but seems like too much info for the list page, and there's still the problem that we'd need to fetch this for each connection in the list.

**Comment by gashcrumb** [comment]
Also any pointers on getting a message returned for an integration overview?

**Comment by chirino** [comment]
@gashcrumb Integration Overview objects now contain a "messages" field.

Not sure what are all the messages that could potentially be shown to a user at this point.  The only ones that come to mind are due to bad-configuration, or upgrades being available that can be applied.

**Comment by gashcrumb** [comment]
Right, was hoping there was a definitive way I could get an integration now to put something in that field just to get the alerts showing up on the page somewhere.  Worst case I can add some dummy data I guess.

**Comment by chirino** [comment]
Nope.. we don't have anything populating those messages for integrations yet. :(

**Comment by chirino** [comment]
Even the connection case is hard to trigger

**Comment by paoloantinori** [comment]
//subscribing to this thread

**Comment by gashcrumb** [comment]
So we have support on the integration detail page currently for displaying these messages.

For connections I still maintain that the API isn't feasible, the connection objects returned by the API should inline these messages, otherwise it's multiple requests that further complicate the frontend logic.

@dongniwang FYI is there a design handy for the integration list view when an integration has some kind of message that may require user attention?

**Comment by paoloantinori** [comment]
Thanks @gashcrumb to clarify the remaining issue. 

Remaining activity:
- display connections related messages

Obstacle:
- current backend API is not usable by UI as is. Doesn't scale

Suggested solution:
- augment current returned Connection object to include required information, mimicking what is currently done for Integration

Actions:
- find someone on backend side to take ownership of this activity

**Comment by sjcox-rh** [comment]
@gashcrumb @paoloantinori Here is a mock up for displaying alerts on the integration list view.

<img width="1014" alt="screen shot 2018-03-12 at 9 32 24 pm" src="https://user-images.githubusercontent.com/16257540/37322781-ec6af44e-263c-11e8-9d87-7259cd8508b8.png">

This is from the [Import/Export designs](https://github.com/syndesisio/syndesis/blob/master/ux/designs/importexport/importexport.md). If there is an error within a specific integration, it should be called out within the row, such as shown above.

You can also utilize toast notifications except those are more fleeting and disappear.

**Comment by gashcrumb** [comment]
Gonna split this out into separate issues at this point...

**Comment by gashcrumb** [comment]
Created #2148 and #2149, @sjcox-rh @dongniwang am assuming there should also be an inline notification on the connection detail page as well, much like the integration detail page when there's messages related to that connection correct?  Is there a design already for that?  If not I can make it work.

**Comment by gashcrumb** [comment]
Created #2151 for the connection detail page.  Now that these are all split out into separate tasks we can consider this issue as tracking the integration detail page inline notification, which is done.
