### ISSUE TITLE
Fields in AMQP Connection creation page are out of order

### ISSUE THREAD

**Issue by dhirajsb** [syndesisio/syndesis#1696]
The fields should appear in the following order when creating an AMQP connection:

* Connection URI
* User Name
* Password
* Client ID
* Skip Certificate Check 
* Broker Certificate - should be multiline text
* Client Certificate - should be multiline text

They appear to be in right order when 'editing' the connection after it has been created.

**Comment by dhirajsb** [comment]
@seanforyou23 can  you fix this? Or if you already have a mechanism for this, can you let me know what I need to do in the backend to fix this?

**Comment by lburgazzoli** [comment]
@dhirajsb once #1698 get merged you can add a `order` field to `ConfigurationProperty` to determine the order of the properties. Of course @syndesisio/ui-api need to adapt the code.

**Comment by dhirajsb** [comment]
@lburgazzoli this has been fixed for the AMQ connector, do you know how it's being done currently for it?

**Comment by gashcrumb** [comment]
A client side hack, but really we should get that out of there in favor of #1698

**Comment by lburgazzoli** [comment]
Should be this hack: https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/connections/common/configuration/configuration.service.ts#L35-L42

**Comment by seanforyou23** [comment]
@dhirajsb sorry just saw your question. The comments from lburgazzoli and gashcrumb are spot on. Looks like 1698 was merged recently so with that in place, are you able to handle this on your end? Just don't want to complicate the problem by adding to the temporary client side adjustment, if we can help it.

**Comment by dhirajsb** [comment]
@seanforyou23, no problem, I will make that change, test and close this issue myself.

**Comment by dhirajsb** [comment]
@seanforyou23 I've added AMQP order fields in #1800, do you need to add logic to the UI to sort {{controls}} based on that field?

**Comment by dhirajsb** [comment]
Looks like the fields are already ordered by the 'order' property. Closing this issue.
