### ISSUE TITLE
Integration "In Progress" misleading

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#1710]
When an integration is about to be published, we get a progressmeter with an "In Progress" label:

![image](https://user-images.githubusercontent.com/99080/36749328-b9c5b50c-1bfa-11e8-8d4e-a2acc0487f96.png)

However, I wonder whether this isn't misleading as this could also be read as that an integration is actually in 'in progress' (aka _active_). Wouldn't be a label like 'Publishing' better ?

**Comment by amysueg** [comment]
UX reviewed this and we agree. Please change the progress indicator label from "In Progress" to "Publishing" @TovaCohen do you agree?

Removing notif/uxd label and assigning to @michael-coker
