### ISSUE TITLE
UX front end dev -- CSS fit-and-finish for Extension configuration pages

### ISSUE THREAD

**Issue by amysueg** [syndesisio/syndesis#1714]
The design for Extensions is here https://github.com/syndesisio/syndesis/blob/master/ux/designs/technical_extensions/tech_ext.md

The screenshot below shows some vert alignment issues. 
<img width="394" alt="screen shot 2018-02-27 at 4 24 43 pm" src="https://user-images.githubusercontent.com/24943812/36755621-c2d07fda-1bda-11e8-9e18-5f234709b4e4.png">

Thanks for taking a look at the pages to ensure the CSS is in good shape and the implementation matches the UX design.

@dongniwang @sjcox-rh @seanforyou23

**Comment by michael-coker** [comment]
@TovaCohen the wording on the extension import page reads

> To import an extension, it must be packaged as a .jar file. To update an extension in the breadcrumbs above, click Extensions and in the list of extensions, click Update for the appropriate extension.

Should the second sentence be something like this instead?

> To update an extension, click Extensions in the breadcrumbs above, and in the list of extensions, click Update for the appropriate extension.

**Comment by amysueg** [comment]
Thank you @michael-coker !
