### ISSUE TITLE
Bug 🐛 - DB to DB Integration container yields an error on Minishift Console 😿

### ISSUE THREAD

**Issue by deeleman** [syndesisio/syndesis#1722]
### The problem

After successfully creating an Integration on Syndesis between two DB connections, I try to consume the `/activity/integrations/{integrationId}` API endpoint, but it returns an empty collection all the time.

After checking the Minishift Console, we can see the following error notified at the overview page:

![captura de pantalla 2018-02-28 a las 14 29 06](https://user-images.githubusercontent.com/1104146/36789815-262be386-1c93-11e8-9216-30687d5b0cc4.png)

After checking the application console, we can reach to the following exception at the logs:

```bash
java.lang.IllegalArgumentException: There's no DataShapeKinds with string ' none'
at io.syndesis.model.DataShapeKinds.fromString(DataShapeKinds.java:51) 
~[common-model-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
```

This prevents that integration to be deployed, hence the empty activity dataset returned by the API.

### Steps to reproduce

1. Go to integrations, remove any previous existing integration and click on `Create Integration``
2. Select `PostgreDB`and then click on `Periodic SQL Invocation`
3. Enter `SELECT * FROM CONTACT` as _SQL Statement_ and set the _Period_ to 2000 or whatever rocks your boat. Click on _Done_ when... done.
4. Select again `PostgreDB` as the target connection and then click on `Periodic Stored Procedure Invocation`.
5. Select `add_lead`, click _Done_.
6. Add an intermediate step and click `Datamapper`. In the two areas displayed, drag `company` from one area to another and save your changes.
7. Click _Publish_ at the top right corner.
6. Wait for the Integration to be _published_ and then check its status at the Minishift Console.

**Comment by KurtStam** [comment]
@deeleman Can you also add the exact steps to create the integration so I can reproduce?

**Comment by deeleman** [comment]
With pleasure @KurtStam. :) I added a _Steps to Reproduce_ block to the issue abstract.

**Comment by KurtStam** [comment]
@deeleman Thx did you also add a dataMapper step?

**Comment by dsimansk** [comment]
@KurtStam I've also experienced this. There's not very informative NPE in [runtime log](https://gist.github.com/dsimansk/82e5ac4fd8a27db39e3bebc00245fbfd) and including whole export zip too.

[db-db-export.zip](https://github.com/syndesisio/syndesis/files/1767919/db-db-export.zip)

**Comment by KurtStam** [comment]
@dsimansk I think the NPE is a different issue and this just got fixed here: https://github.com/syndesisio/syndesis/issues/1713

**Comment by KurtStam** [comment]
@deeleman I cannot reproduce your issue. Can you update to the latest and ping me so we can build the integration together?
