### ISSUE TITLE
Integration should always load the latest connection object

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#1729]
## This is a...

<pre><code>
[*] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Currently when an integration object is stored, copies of a connection are stored with it, so when a connection object is changed, the integration object doesn't see those changes.

## Expected behavior

Ideally when an integration object is loaded from the database, it should load connection objects by reference rather than the stored copy.

@KurtStam @lburgazzoli @chirino @rhuss FYI

## Tasks involved / Steps to Reproduce

1. 
2.
3.
4.

**Comment by lburgazzoli** [comment]
I guess we should also add some info to let the ui aware that something has changed right ?

**Comment by KurtStam** [comment]
Personally I would expect that with document based storage the document would get updated if an underlaying object is updated that was included in the current document. If this is undesirable we'd need to version documents.

**Comment by lburgazzoli** [comment]
We should maybe distinguish between an integration that should always use references and a deployed integration that should also include all the bits, i.e.:

```java
interface Integration {
}

interface DeployedIntegration extends Integration {
    List<Connection> getConnections();
    List<Connector> getConnectors();
    List<Extension> getExtensions();
}
```
