### ISSUE TITLE
DashboardComponent test regression

### ISSUE THREAD

**Issue by seanforyou23** [syndesisio/syndesis#1732]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

The issue lay somewhere between the DashboardComponent and DashboardMetricsComponent. During work on https://github.com/syndesisio/syndesis/pull/1703 it was discovered that there is an issue with said tests passing. The error that arises seems unrelated to the work that was done in the PR. See comments from that PR for more details on what's been observed.

## Expected behavior

The DashboardComponent and DashboardMetricsComponent test suites should continue to work.

## Screenshot

https://gist.github.com/seanforyou23/e5c5d17ca9bbec31a7d6678219225891

## Tasks involved / Steps to Reproduce

1. Re-enable the busted test - https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/dashboard/dashboard.component.spec.ts#L35
2. Run the test and watch it fail

**Comment by deeleman** [comment]
Fixed as per #1726
