### ISSUE TITLE
Show data type label on the steps in collapsed IVP

### ISSUE THREAD

**Issue by igarashitm** [syndesisio/syndesis#1736]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Let's just restore showing data type label by hovering on each steps in the collapsed IVP.

## Expected behavior

Show data type label by hover on each steps in the collapsed IVP

## Screenshot

![screenshot from 2018-02-28 15-00-20](https://user-images.githubusercontent.com/265462/36810532-f7fd03c2-1c98-11e8-8355-b8e3dd2eec77.png)

## Tasks involved / Steps to Reproduce

1. 
2.
3.
4.

**Comment by igarashitm** [comment]
#1735 came first. woot!

**Comment by gashcrumb** [comment]
Yep, this should be all set.
