### ISSUE TITLE
Unable to add steps

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#1744]
## This is a...

<pre><code>
[ ] Feature request
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Unable to add steps between connections, the error shown on browser's console is:

```
main.34c31e3c4bd63a61a994.bundle.js:1 ERROR TypeError: Cannot read property 'properties' of undefined
    at t.getProperties (main.34c31e3c4bd63a61a994.bundle.js:1)
    at n.loadFormSetup (1.2418b268c2b57bd28321.chunk.js:1)
    at n.loadForm (1.2418b268c2b57bd28321.chunk.js:1)
    at e._next (1.2418b268c2b57bd28321.chunk.js:1)
    at e.__tryOrSetError (polyfills.00b2490f9e8f9b4c7b5e.bundle.js:1)
    at e.next (polyfills.00b2490f9e8f9b4c7b5e.bundle.js:1)
    at e._next (polyfills.00b2490f9e8f9b4c7b5e.bundle.js:1)
    at e.next (polyfills.00b2490f9e8f9b4c7b5e.bundle.js:1)
    at e._next (polyfills.00b2490f9e8f9b4c7b5e.bundle.js:1)
    at e.next (polyfills.00b2490f9e8f9b4c7b5e.bundle.js:1)
Ct @ main.34c31e3c4bd63a61a994.bundle.js:1
```

## Screenshot

![image](https://user-images.githubusercontent.com/1868933/36830395-c227b39c-1d23-11e8-9909-155265e6a675.png)

## Tasks involved / Steps to Reproduce

1. Create an integration
2. Add a `Periodic SQL Invocation` action
3. Add a `Invoke Stored procedure` action
4. Add a datamapper step

**Comment by paoloantinori** [comment]
When double checking this for @lburgazzoli  I actually hit a different error:

<details>
  <summary><b>Click to expand</b></summary>
<pre><code>
TypeError: this.getStepConfig(...) is undefined
Stack trace:
8Dgd/e.StepStore</t.prototype.getProperties@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.34c31e3c4bd63a61a994.bundle.js:1:676871
2nki/l.IntegrationStepConfigureComponent</n.prototype.loadFormSetup@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/1.2418b268c2b57bd28321.chunk.js:1:26478
2nki/l.IntegrationStepConfigureComponent</n.prototype.loadForm@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/1.2418b268c2b57bd28321.chunk.js:1:26159
2nki/l.IntegrationStepConfigureComponent</n.prototype.ngOnInit/this.routeSubscription<@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/1.2418b268c2b57bd28321.chunk.js:1:27172
E9/g/u</e.prototype.__tryOrSetError@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.00b2490f9e8f9b4c7b5e.bundle.js:1:18911
E9/g/u</e.prototype.next@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.00b2490f9e8f9b4c7b5e.bundle.js:1:18019
E9/g/a</e.prototype._next@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.00b2490f9e8f9b4c7b5e.bundle.js:1:17133
E9/g/a</e.prototype.next@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.00b2490f9e8f9b4c7b5e.bundle.js:1:16816
qqDE/s</e.prototype._next@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.00b2490f9e8f9b4c7b5e.bundle.js:1:92313
E9/g/a</e.prototype.next@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.00b2490f9e8f9b4c7b5e.bundle.js:1:16816
eoFs/s</e.prototype._subscribe@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.34c31e3c4bd63a61a994.bundle.js:1:2123645
AP4T/u</t.prototype._trySubscribe@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.00b2490f9e8f9b4c7b5e.bundle.js:1:13711
TO51/l</e.prototype._trySubscribe@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.00b2490f9e8f9b4c7b5e.bundle.js:1:32400
AP4T/u</t.prototype.subscribe@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.00b2490f9e8f9b4c7b5e.bundle.js:1:13540
qqDE/i</t.prototype.call@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.00b2490f9e8f9b4c7b5e.bundle.js:1:91995
AP4T/u</t.prototype.subscribe@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.00b2490f9e8f9b4c7b5e.bundle.js:1:13458
2nki/l.IntegrationStepConfigureComponent</n.prototype.ngOnInit@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/1.2418b268c2b57bd28321.chunk.js:1:26942
Jo/</<@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.34c31e3c4bd63a61a994.bundle.js:1:1040276
Jo/<@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.34c31e3c4bd63a61a994.bundle.js:1:1039676
Jo@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.34c31e3c4bd63a61a994.bundle.js:1:1038574
ws@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.34c31e3c4bd63a61a994.bundle.js:1:1049243
W/<@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/1.2418b268c2b57bd28321.chunk.js:1:175247
updateDirectives@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.34c31e3c4bd63a61a994.bundle.js:1:1046547
Ko@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.34c31e3c4bd63a61a994.bundle.js:1:1038222
is@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.34c31e3c4bd63a61a994.bundle.js:1:1045266
rs@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.34c31e3c4bd63a61a994.bundle.js:1:1044929
Ko@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.34c31e3c4bd63a61a994.bundle.js:1:1038247
is@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.34c31e3c4bd63a61a994.bundle.js:1:1045266
ns@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.34c31e3c4bd63a61a994.bundle.js:1:1044664
Ko@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.34c31e3c4bd63a61a994.bundle.js:1:1038369
is@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.34c31e3c4bd63a61a994.bundle.js:1:1045266
rs@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.34c31e3c4bd63a61a994.bundle.js:1:1044929
Ko@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.34c31e3c4bd63a61a994.bundle.js:1:1038247
is@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.34c31e3c4bd63a61a994.bundle.js:1:1045266
rs@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.34c31e3c4bd63a61a994.bundle.js:1:1044929
Ko@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.34c31e3c4bd63a61a994.bundle.js:1:1038247
is@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.34c31e3c4bd63a61a994.bundle.js:1:1045266
ns@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.34c31e3c4bd63a61a994.bundle.js:1:1044664
Ko@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.34c31e3c4bd63a61a994.bundle.js:1:1038369
LMZF/</zi</t.prototype.detectChanges@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.34c31e3c4bd63a61a994.bundle.js:1:1020018
LMZF/</dn</t.prototype.tick/<@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.34c31e3c4bd63a61a994.bundle.js:1:983450
LMZF/</dn</t.prototype.tick@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.34c31e3c4bd63a61a994.bundle.js:1:983411
next/<@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.34c31e3c4bd63a61a994.bundle.js:1:981777
eFQL/</</</c</t.prototype.invoke@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.00b2490f9e8f9b4c7b5e.bundle.js:1:49627
onInvoke@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.34c31e3c4bd63a61a994.bundle.js:1:973922
eFQL/</</</c</t.prototype.invoke@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.00b2490f9e8f9b4c7b5e.bundle.js:1:49554
eFQL/</</</o</e.prototype.run@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.00b2490f9e8f9b4c7b5e.bundle.js:1:44781
LMZF/</Ve</t.prototype.run@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.34c31e3c4bd63a61a994.bundle.js:1:974629
next@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.34c31e3c4bd63a61a994.bundle.js:1:981754
LMZF/</Fe</e.prototype.subscribe/i<@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.34c31e3c4bd63a61a994.bundle.js:1:972571
E9/g/u</e.prototype.__tryOrUnsub@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.00b2490f9e8f9b4c7b5e.bundle.js:1:18801
E9/g/u</e.prototype.next@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.00b2490f9e8f9b4c7b5e.bundle.js:1:18076
E9/g/a</e.prototype._next@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.00b2490f9e8f9b4c7b5e.bundle.js:1:17133
E9/g/a</e.prototype.next@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.00b2490f9e8f9b4c7b5e.bundle.js:1:16816
TO51/l</e.prototype.next@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.00b2490f9e8f9b4c7b5e.bundle.js:1:31831
LMZF/</Fe</e.prototype.emit@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.34c31e3c4bd63a61a994.bundle.js:1:972330
Ue@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.34c31e3c4bd63a61a994.bundle.js:1:975078
onHasTask@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.34c31e3c4bd63a61a994.bundle.js:1:974067
eFQL/</</</c</t.prototype.hasTask@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.00b2490f9e8f9b4c7b5e.bundle.js:1:50621
eFQL/</</</c</t.prototype._updateTaskCount@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.00b2490f9e8f9b4c7b5e.bundle.js:1:50888
eFQL/</</</o</e.prototype._updateTaskCount@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.00b2490f9e8f9b4c7b5e.bundle.js:1:47064
eFQL/</</</o</e.prototype.runTask@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.00b2490f9e8f9b4c7b5e.bundle.js:1:45684
v@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.00b2490f9e8f9b4c7b5e.bundle.js:1:52542
eFQL/</</</a</e.invokeTask@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.00b2490f9e8f9b4c7b5e.bundle.js:1:51432
_@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.00b2490f9e8f9b4c7b5e.bundle.js:1:62097
g@https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.00b2490f9e8f9b4c7b5e.bundle.js:1:62329
main.34c31e3c4bd63a61a994.bundle.js:1:956838

</code></pre>
</details>

**Comment by lburgazzoli** [comment]
@paoloantinori  same error on firefox, other one was chrome

**Comment by paoloantinori** [comment]
Error is with this 2 lines, reverting them, it shows back the selection of the kind of step:

https://github.com/syndesisio/syndesis/commit/f9162d5eec462b44b2a813738e6a5c141625f99c#diff-bb63de206c2f78cec23ac9434331dc14R648

@gashcrumb  could you have a look , since I'm not sure of their role in the scope of your original commit?

**Comment by gashcrumb** [comment]
That's strange, that's not how the code should look :-/

**Comment by gashcrumb** [comment]
This is how it should be -> https://github.com/syndesisio/syndesis/pull/1738/files#diff-bb63de206c2f78cec23ac9434331dc14R641

lemme check master...

**Comment by gashcrumb** [comment]
Ah, well doesn't matter, I see it's broken here anyways, will look into it :-)

**Comment by paoloantinori** [comment]
thanks @gashcrumb
