### ISSUE TITLE
Update Pod names in product templates to use ignite-* instead of syndesis-* 

### ISSUE THREAD

**Issue by kcbabo** [syndesisio/syndesis#1751]
## This is a...
<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report 
[ ] Documentation issue or request
</code></pre>

## The problem
Product template uses "ignite" images, but the pod names are still syndesis-*.  Pod names should use "ignite" as well.

**Comment by rhuss** [comment]
@paoloantinori this https://github.com/syndesisio/syndesis/blob/422ec4637ef3788add7a39fa469eb11afc4ba5f9/app/rest/rest/src/main/java/io/syndesis/rest/v1/handler/support/SupportUtil.java#L69 must be then updated, too. I suggest to use a more flexible way to match platform pods (maybe even configure it, as this might change anytime ?)

**Comment by paoloantinori** [comment]
I'll do. It makes sense to encapsulate the changing part of that logic.

Anyhow the whole naming mismatch is an internal, and doesn't really introduce any mismatch.

Most of RH MW project refer directly to upstream project names, despite their product name is different.

**Comment by rhuss** [comment]
@paoloantinori @kcbabo How urgent is this ? tbh, I think we should do this before going to GA as these names shine through to the OpenShift console which people will see, too.

I add a "triage" label to consider this for a GA target label.

**Comment by paoloantinori** [comment]
Traditionally, in other RH projects, upstream project names leaked often in the product internals, and, as long as they were internals, it's never been a blocker issue.

Can't tell if we have different requirements nowadays, but I can take care of discovering this.

**Comment by kcbabo** [comment]
I would not consider this a blocker, but I do think it could create confusion.  The images are all named ignite-* and the pods are syndesis-*.  It's desirable to have productized components carry product names (images, Maven artifacts, etc.).

**Comment by paoloantinori** [comment]
@rhuss hi, some activity occurred around templates recently. Any chance that this got into already?

**Comment by rhuss** [comment]
No, no work has been done here yet. However this should be considered when we are moving to a template repo for prod. Going to tackle this next week.

**Comment by paoloantinori** [comment]
Hi @rhuss are you planning to address this in the next days? otherwise please file this as a post ga activity.

**Comment by rhuss** [comment]
I plan to make the move tomorrow. not sure I will made it wrt of all the ohter work (+ a brand new talk I have to give next wednesday). will mark it accordingly.

**Comment by dsimansk** [comment]
@rhuss @paoloantinori any plans to address naming for GA since there's a fuse-ignite-install repository and fuse-ignite-* templates?

**Comment by rhuss** [comment]
I could tackle starting next week. Not sure whether this is already to late, but it should be straight forward.

**Comment by paoloantinori** [comment]
Unless @rhuss has already a fix for this, we are deciding to leave this out.

**Comment by rhuss** [comment]
btw, is 'ignite-' still a thing ? Guess its now 'fuse-online-' (or maybe even only 'fuse-' ?).

'happy that I procrastinated that issue away ;-)
