### ISSUE TITLE
Add 'type' to extension upload

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#1752]
## This is a...

<pre><code>
[*] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
The user wants to use a proprietary db let's say Oracle. We don't (and can't for licensing reasons) ship the Oracle Driver. The user should upload this driver jar using the extension mechanism with type 'JDBC-driver'.

## Expected behavior
Driver is uploaded and wrapped inside an extension archive after adding some metadata. The REST pod calls an endpoint on the verifier to add this jar its classpath and the user can now create a new Connection to connect to an Oracle DB. Only one Oracle Driver version should be used, so we should prevent the user from uploading more then one driver of the same type or only use the latest uploaded version.

See also: https://github.com/syndesisio/syndesis/issues/1291

**Comment by lburgazzoli** [comment]
I had some discussion around this topic and we would need a more complex page in order to generate an extension from a simple jar such as a jdbc driver, this is because we need to set a logical id, a version and something more to properly support extension lifecycle. 

So if UI/UX can implement such page by the end of the sprint, I'm ok with that otherwise we should leverage the current extension workflow so drivers (jdbc, jms, etc) should be packaged by the extension-maven-plugin as any other extension (we'll provide an archetype for that) . This of course add some works on the user side but it is the easier way to get this feature implemented in a week and we can work on a better user experience after GA.

@KurtStam @chirino @kcbabo what do you think ?

**Comment by nicolaferraro** [comment]
+1. The archetype and a working example will guide users to wrap the jar in a syndesis extension.

If we later decide to add a specific UI for uploading a plain jar, the rest services can do the wrapping automatically.

**Comment by kcbabo** [comment]
Works for me.  One silly question - how does a user associate the driver extension with their connector/connection?

**Comment by KurtStam** [comment]
@kcbabo The driver is put on the classpath and then he can use the appropriate connection for that driver.

**Comment by lburgazzoli** [comment]
@kcbabo for this first step the project generator will go through the extensions and perform a match according to some tags, i.e. the `sql` connector will be associated to any `library` extension that has a tag like `jdbc` (naming is not yet defined). 

Future syndesis release should have a page to choose what `library` extension the integration should include.

**Comment by kcbabo** [comment]
Let's say I've uploaded two drivers as extensions:

- Extension A : Oracle Driver
- Extension B : DB2 Driver

Now I create a new connection called "My Oracle".  How do I make the association between Extension A and My Oracle to make sure the driver is on the class path?

Then I come along and create another connection called "My DB2".  Same question as above, but I would only want Extension B on the class path.

**Comment by kcbabo** [comment]
Thanks @lburgazzoli 

Does that mean that if I upload multiple drivers they would all be on the class path?  Will that be a problem with conflicting libs?

**Comment by KurtStam** [comment]
@kcbabo As long as we limit one per DB vendor we should be ok. My suggestion is to only use the last upload for a specific driver upload (so it a different version is uploaded for the same oracle thin driver we'd use the last one uploaded).

**Comment by KurtStam** [comment]
@kcbabo I think it's a bit misleading to talk about an 'extension' here. We will unwrap it and take out the driver jar. We simply add the driver jar to the classpath of the verifier and integration (the latter only when a SQL/SQLStored component is involved)

**Comment by zregvart** [comment]
> Does that mean that if I upload multiple drivers they would all be on the class path? Will that be a problem with conflicting libs?

@kcbabo, @lburgazzoli, @KurtStam  I think the easiest way is to put all drivers on the classpath and then use service discovery (as described in [DriverManager](https://docs.oracle.com/javase/8/docs/api/java/sql/DriverManager.html)), and mandate that the extension contains the appropriate META-INF if the JDBC driver jar doesn't.

**Comment by nicolaferraro** [comment]
Yes, the driver will be chosen automatically using the connection url, assuming that the `Driver` class is correctly registered for service discovery. 

I think it's better not to put other info that is needed at runtime in the top-level extension jar for now. So we can treat this kind of extensions as just an archive with external jars.

**Comment by KurtStam** [comment]
Right we already do this now for the drivers PostgreSQL, MySQL and Derby etc.

**Comment by nicolaferraro** [comment]
This has been implemented in https://github.com/syndesisio/syndesis/pull/1794
