### ISSUE TITLE
Add JDBC type extensions to integrations using the Camel SQL-connector

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#1753]
## This is a...

<pre><code>
[*] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Expected behavior
For all Integrations using the SQL or SQLStored connectors we should add all JDBC driver extensions using the extension mechanism. We don't need to care which drivers are actually used, we can simply add them all. Note that we should only use one for each vendor, and maybe pick the last uploaded.

See also: https://github.com/syndesisio/syndesis/issues/1291

**Comment by nicolaferraro** [comment]
This has been implemented in https://github.com/syndesisio/syndesis/pull/1816
