### ISSUE TITLE
Add JDBC Driver to the verifier classpath

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#1755]
## This is a...

<pre><code>
[*] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
The verifier needs to verify connection info to a database, and should be able to use drivers that were uploaded by the user.

## Expected behavior
After driver upload, the REST layer should call an endpoint on the verifier to add that jar to a PV that is on its classpath. The verifier should then kill itself so that the driver is actually loaded on the classpath.

## API Endpoints and Schemas

See also: https://github.com/syndesisio/syndesis/issues/1291

**Comment by KurtStam** [comment]
@lburgazzoli working on it on branch: https://github.com/KurtStam/syndesis/commits/drivers
It currently adds the PV on /deployment/ext and it adds the /deployment/ext to the verifier classpath. So currently I can at least manually copy in a ojdbc6.jar and test a 'verify' a connection. Next for me is adding the REST endpoint that can be called to upload a jar, and which then exits so the pod restarts.

**Comment by lburgazzoli** [comment]
Is the oracle driver taken into account ? because using classpath was not reliable while developing extensions, instead what works is [PropertiesLauncher](https://docs.spring.io/spring-boot/docs/current/reference/html/executable-jar.html#executable-jar-property-launcher-features)

**Comment by lburgazzoli** [comment]
btw, we should also take into account upgrading/deleting drivers

**Comment by KurtStam** [comment]
@lburgazzoli you are right that '-cp' didn't;t work and I changed it. It's working now. Still need to add the verifier REST endpoint.
