### ISSUE TITLE
Add direct link to "describe data type" page of previous step from data type mismatch indicator

### ISSUE THREAD

**Issue by igarashitm** [syndesisio/syndesis#1756]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

#1734 added a direct link to add a datamapper step right before the one requires it. But if the previous step is a **shapeless connector**, i.e. output data type kind is `any`, then datamapper step can't consume that data until they add a user defined data type from "describe data type" configuration.

## Expected behavior

So let's add a direct link to the "describe data type" page of the previous step, if the output `kind` of that step is `any`. This makes data mapping UX even better :-)

## Screenshot

![screenshot from 2018-03-01 10-45-26](https://user-images.githubusercontent.com/265462/36854417-f2bb14d4-1d3e-11e8-9191-0562048b7b0f.png)

## Tasks involved / Steps to Reproduce

1. 
2.
3.
4.

**Comment by gashcrumb** [comment]
@kcbabo uh, so thanks to that call I'm totally confused what to do for this one....  😕

**Comment by kcbabo** [comment]
Ah, I see what Tomo meant now.

I agree that a warning should be shown if a connection requires a specific data type and the previous data type isn't specified.  Tomo's suggestion of direct linking to the prior connection's "describe data type" page sounds interesting, but I'm not sure how that would work if there are multiple shapeless connections in the flow prior to that point.

Taking the specific example Tomo provided, maybe just have a warning that no data type has been specified and leave it at that?

**Comment by igarashitm** [comment]
You mean show a warning when the step right before itself has `any` output while it expects typed data? I think that's still fine. But looking at all the preceding steps for indicator will be a bit more complicated.

**Comment by gashcrumb** [comment]
I think though that really each step is only concerned with the previous step's output.  It's only the datamapper that is able to 'see' all the previous steps output data shape.

**Comment by igarashitm** [comment]
So unless we want a special indicator for datamapper step, we only need to look at the step right before itself.

**Comment by igarashitm** [comment]
BTW datamapper's input data shape is always `any`, so it never has the mismatch indicator ATM. A bit like a cheat though as it only accepts typed data :-)

**Comment by igarashitm** [comment]
merged #1762
