### ISSUE TITLE
Add default Stored Procedure 'Periodic Stored Procedure Invocation'

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#1773]
## This is a...

<pre><code>
[*] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
The user is presented with a blank box at the moment.

## Expected behavior
We should create a stored procedure that does not take any IN arguments, only OUT.

**Comment by dsimansk** [comment]
@KurtStam it feels like `create_lead` is not the most descriptive name for the stored procedure. In fact the procedure itself uses select and has only OUT params. Would it make sense to name it `fetch_lead` or `retrieve_` or `select_`? Wdyt?
