### ISSUE TITLE
Mapping with `kind=java` not using inspections

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#1782]
## This is a...
<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

When using input data shapes with `kind=java` a ``No data type specification was found for subsequent step` error is displayed.

## Expected behavior

I think for data shapes with `kind=java`, or perhaps in general with data shapes that have no `specification` inspection endpoint should be invoked.

Perhaps a proper solution is to migrate all connectors that have `kind=java` to the newest model, as I think the connector Maven plugin will set `specification` on the data shape.

## Screenshot

![screenshot-2018-3-2 syndesis - development](https://user-images.githubusercontent.com/1306050/36894055-87acd520-1e0a-11e8-9209-d9e809f912bf.png)

## Tasks involved / Steps to Reproduce
1. Create a integration with Salesforce Fetch Record action at the end
2. Try to add data mapping step

See #1166

**Comment by zregvart** [comment]
Perhaps we could use add result of inspections to `specification` on the server side, if that makes sense?

**Comment by zregvart** [comment]
Can be workaround by not adding the mapper via the warning popup that the mapper is missing, that is by clicking on the `+` and adding mapping step.

**Comment by igarashitm** [comment]
Due to classpath problem, in Syndesis we decided not to use online inspection for Java Document, instead put inspection result into `DataShape.specification`. So yes, right direction is to invoke offline inspection via maven plugin and put the result into specification.
