### ISSUE TITLE
Connections should be updated when Connectors are upgraded

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis#1788]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
Connections should be updated when connectors are upgraded so that Integrations notice that use them are notified that they need to be republished.

## Expected behavior
Upgrading a connector should result in integration using the connector/connection as having a message saying the integration should be replublished.

**Comment by lburgazzoli** [comment]
I guess we can improve our `DataManager` to 

- assign (and upgrade) a revision to entities
- pre computed bulletins each time an entity is updated and for dependentat entities
- pre computed bulletins at startup

We then need to make the `DataManager` available to db upgrade scripts so we can leverage it in case upgrading the db schema also requires changes to a connector and so on.

When the UI asks for an Integration we should also check if the integration uses outdated components (checking the revision) and mark it as "outdated" till the integration gets re-deployed (this is needed as one may save an integration as a draft which should clear the bulletins but the running integration is still based on old components).

**Comment by lburgazzoli** [comment]
@gashcrumb I think this can be closed right ?
