### ISSUE TITLE
Incorrect total integration count in the donut

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#1791]
## This is a...

[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request

## The problem

Integration total is incorrect on the dashboard

## Expected behavior

I have 2 integrations here and the total is showing 4

## Screenshot

![screenshot from 2018-03-02 10-43-29](https://user-images.githubusercontent.com/351660/36907557-e84b9794-1e06-11e8-9bca-91e103d4c0ce.png)

**Comment by gashcrumb** [comment]
Ah, the problem is how we're counting them really.  Since 'Draft' is no longer a state, it's possible to have integrations that are published but have a draft, or unpublished and have a draft.  So when the donut chart data is assembled in my case there's 1 published, 1 unpublished and 2 in draft because both integrations have some changes.

@dongniwang @seanforyou23 wonder should we revisit what data this donut chart shows?  Otherwise we look mathematically challenged :-)

**Comment by amysueg** [comment]
UX discussed and we think the "donut" should only count "published" and "unpublished" integrations. Assigning to @seanforyou23 & removing notif/uxd label.
