### ISSUE TITLE
Update to API connector creation UI when authentication type is available

### ISSUE THREAD

**Issue by mcoker** [syndesisio/syndesis#1804]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
When creating an API connector, if there is only one authentication type available, you're left with a form with only one selectable field that can't be unselected.

## Expected behavior
If there is only one authentication type available, we should display an alert or info box stating the authentication type to use instead of form fields that you can't change. The UI should be similar to when creating an integration and you select an action that has no configurable properties.

## Screenshot
The current UI when there is only one authentication type available

![screen shot 2018-03-02 at 4 36 40 pm](https://user-images.githubusercontent.com/35148959/36925435-86fb853a-1e38-11e8-93f5-a6831b959056.png)

Here is a screenshot of the integration step mentioned above

![screen shot 2018-03-02 at 4 40 00 pm](https://user-images.githubusercontent.com/35148959/36925447-930ca084-1e38-11e8-929b-e950d7ed4fad.png)

## Tasks involved / Steps to Reproduce
1. Create an API connector and use this as the swagger URL https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/api/v1/swagger.json
2. Click "next" to review actions
3. Click "next" to see the single "authentication type"

To see the integration step mentioned above
1. Create a new integration
2. Choose a twitter connection
3. Choose "mention"

@TovaCohen @zregvart @dongniwang @amysueg @seanforyou23

**Comment by sjcox-rh** [comment]
@michael-coker, thanks for catching this. Agreed it's a bit of a pointless behavior to give the user fields they can't update when there is only one authentication type available. I think showing an inline notification similar to the integration step behavior you have shown would be appropriate that way it's a consistent behavior.

**Comment by michael-coker** [comment]
@zregvart just pinging you to make sure you saw this issue, and see if you want to try to include it in this sprint or the next. Thanks!

**Comment by zregvart** [comment]
Would love to see this in this sprint if possible, anyone at @syndesisio/ui-api have free time to do this?

**Comment by michael-coker** [comment]
@sjcox-rh per https://github.com/syndesisio/syndesis/issues/2568, how do you feel about skipping the step entirely if there is only one option available, and just taking folks to the next step automatically?

**Comment by sjcox-rh** [comment]
@michael-coker I'd be okay with that as long as the step that was automatically skipped was shown in the review step. Does that make sense?

Just so the user is aware of a detail that was automatically selected for them (even though it was the only option).

**Comment by kahboom** [comment]
@michael-coker - I think the third step makes a lot of sense if we had the option of "No Authentication", which I thought we used to have. It's not just meant to be a review step for authentication, but also to provide options. I suppose with the Apicurio editor then we can just do it from there, and in that case it wouldn't make sense to keep as a step anymore @dongniwang .  Maybe we should be including this in the review page (the second step, maybe as a warning if they don't have a security method specified) or the final review, as @michael-coker suggests.

**Comment by dongniwang** [comment]
First, I'm fine with having the "No Authentication" as an option for step 3. I think the initial idea of having Step 2 - Review Action is to allow users to review what kind of actions they want to bring in to use in Syndesis. And then Step 3 - Specifying Security is for users to tell Syndesis how to access/communicate to this connector on their behalf. 

@zregvart may know better here.
