### ISSUE TITLE
Step ID's in integration editor don't update when you remove a step

### ISSUE THREAD

**Issue by michael-coker** [syndesisio/syndesis#1815]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
When you remove a step from the left nav in the integration editor, the step ID's don't update.

## Expected behavior
Step ID's should update when removing a step.

## Screenshot
![screen shot 2018-03-05 at 9 48 44 am](https://user-images.githubusercontent.com/35148959/36984628-efebec8c-205a-11e8-9582-bc466685eaab.png)

![screen shot 2018-03-05 at 9 48 51 am](https://user-images.githubusercontent.com/35148959/36984627-efcfaf4a-205a-11e8-88ab-9ed9c95b0048.png)
![screen shot 2018-03-05 at 9 48 54 am](https://user-images.githubusercontent.com/35148959/36984626-efbccd76-205a-11e8-815d-b211413ae9bf.png)

## Tasks involved / Steps to Reproduce
1. Create an integration
2. Choose start/finish connection
3. Add a step
4. Remove the step

@gashcrumb @dongniwang

**Comment by gashcrumb** [comment]
Hmm, probably just need to force a redraw in the parent component that holds those steps.
