### ISSUE TITLE
API Connector Form: Order and Spacing

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#1817]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

The spacing in the API connectors form is inconsistent, as well as the order

By convention, you normally enter the user first, then the password. not vice versa:

## Expected behavior

"user" should come before "password", spacing between lines should be the same everywhere.

## Screenshot

![image](https://user-images.githubusercontent.com/99080/36749094-0b303ca6-1bfa-11e8-821e-1171a93609c1.png)

Related to #1709

**Comment by michael-coker** [comment]
@rhuss can you provide the swagger file that enables those fields to be shown? I tried the swagger.json from my todo app and don't see those fields. https://photos.app.goo.gl/QU1qMlsA6nyZ96gv1

**Comment by zregvart** [comment]
@michael-coker looks like that's the TODO app Swagger file if you have a running minishift instance it should be available at `https://todo-syndesis.$(minishift ip).nip.io/swagger.json`. In case you can't access that I've created a gist with at https://gist.github.com/zregvart/af1f18e05d3911e2fa0779a3204509be

**Comment by michael-coker** [comment]
@zregvart thanks, but that's the file I was using. I tried yours and got the same output in the screenshots from my previous comment. "HTTP Basic Authentication" is a radio button, not a select box/dropdown, and there are no form fields below it.

![screen shot 2018-03-08 at 4 29 49 pm](https://user-images.githubusercontent.com/35148959/37180234-f1f763cc-22ed-11e8-9077-2af6f42ed7f8.png)

**Comment by zregvart** [comment]
@michael-coker perhaps it's this older version: https://github.com/syndesisio/todo-example/blob/1ff5cf90a9e1c6c60cd3701b3d077844527aa44a/swagger.json

**Comment by michael-coker** [comment]
@zregvart same thing, still not seeing the form fields.

**Comment by deeleman** [comment]
You’re looking into different sections of the site, I’m afraid

**Comment by michael-coker** [comment]
@deeleman ah! Found it now, thanks!

**Comment by michael-coker** [comment]
@gashcrumb @deeleman that space is coming from a hidden `input` element with the text "Swagger specification of the service" shown via `*ngIf="showHint"` in [syndesis-form-control.component.html](https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/common/ui-patternfly/syndesis-form-control.component.html).

1) What's the point of that text/input? I'm assuming the text shouldn't be shown (since it's associated with a hidden input field), and a form row shouldn't be generated for a hidden input.
2) I'm not sure where the data comes from that generates these form fields...

![screen shot 2018-03-09 at 8 43 36 am](https://user-images.githubusercontent.com/35148959/37213138-c145f3d6-2376-11e8-9a1e-edcd66adcfc7.png)

**Comment by gashcrumb** [comment]
Aha!  Yes, we support hidden inputs to sneak extra data into the configured properties for a connection like this.  We need the input to render on the page but not take up any actual space.

@seanforyou23 can you work with @michael-coker on this?

**Comment by michael-coker** [comment]
That output also shows up on the connection details page, and the spacing of the values is off (which I can fix in CSS)

![screen shot 2018-03-09 at 9 37 57 am](https://user-images.githubusercontent.com/35148959/37215539-cdda514e-237d-11e8-806f-e84a5be4372c.png)

**Comment by michael-coker** [comment]
@seanforyou23 I took a stab at hiding rows that have a hidden input field on the branch [form-order-spacing](https://github.com/michael-coker/syndesis/tree/form-order-spacing).

**Comment by gashcrumb** [comment]
@michael-coker want to create a PR with that branch?  Might need to rebase it first too just to be on the safe side...

**Comment by michael-coker** [comment]
@gashcrumb https://github.com/syndesisio/syndesis/pull/2044
