### ISSUE TITLE
Response from integration activity is not ordered

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#1818]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

The response from `/api/v1/activity/integrations/{id}` doesn't seem to be ordered. On refresh from the UI this becomes a usability issue.

Actually I'm not entirely that it makes sense for the API to return 10 records for a newly created & published integration. Seems to me that the number of records should be about 2?

## Expected behavior

Activities should have deterministic order, probably chronological.

## Screenshot
![issue-2018-03-05_17 12 17](https://user-images.githubusercontent.com/1306050/36986113-4c7c116e-2099-11e8-8958-edc3adfcae7a.gif)

## API Endpoints and Schemas

`/api/v1/activity/integrations/{id}`

## Tasks involved / Steps to Reproduce

1. Create & publish integration
2. Refresh integration activity screen
3.
4.

**Comment by deeleman** [comment]
Reassigned to me. We will handle this from the frontend as a sort of temporary solution until the activity list becomes too huge
