### ISSUE TITLE
Monitoring Metrics: values aren't updated in Integration Detail view

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis#1824]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
Metrics values aren't reflected when accessed via Integration Details->Metrics. However on Dashboard is seems fine.

## Expected behavior
Metrics have same values displayed in both widgets.

## Screenshot
Dashboard:
<img width="1168" alt="screen shot 2018-03-05 at 20 32 22" src="https://user-images.githubusercontent.com/5637792/36995541-9c151aca-20b4-11e8-9c30-948079dc7ed5.png">

Integration Detail:
<img width="1186" alt="screen shot 2018-03-05 at 20 32 16" src="https://user-images.githubusercontent.com/5637792/36995547-a07e75e8-20b4-11e8-98fe-8793a3269813.png">

Cc @deeleman @Stefan365

**Comment by deeleman** [comment]
@dsimansk I do not seem to be able to replicate it, mostly because my VM seems to be broken as usual.

Could you please inspect the Network tab in your browser's dev tools to see what response are you getting from the calls polling the API `activity` endpoints for both the dashboard and the integration page? Thanks.

**Comment by dsimansk** [comment]
@deeleman 

Request to: `https://myproject.192.168.64.17.nip.io/api/v1/metrics/integrations`
```
{"metricsProvider":"prometheus","messages":54,"errors":0,"start":1520426613540,"lastProcessed":1520426854939}
```

But request to specific integration: `https://myproject.192.168.64.17.nip.io/api/v1/metrics/integrations/i-L7-TpQ4QJxTm7m9pHRcz`
```
{"metricsProvider":"prometheus","messages":0,"errors":0,"integrationDeploymentMetrics":[]}
```

**Comment by deeleman** [comment]
Thanks @dsimansk 

Looking at this ATM

**Comment by Stefan365** [comment]
FYI, perhaps similar problem is with Activity tab:

Endpoit: /api/v1/activity/integrations/i-L7-o5Wy9t4Vc_1eDNoSz
returns:
[]

**Comment by deeleman** [comment]
@Stefan365 Perhaps those might be somewhat related, but initially that is a different issue on a different endpoint, that the backend folks are already aware of. :)

**Comment by dhirajsb** [comment]
@rhuss this is happening because integration id and deployment version annotations were removed from integration pods. Prometheus metrics was using those annotations to lookup associated metrics. 

What's the reasoning for removing those annotations? What are we supposed to use instead?

**Comment by dhirajsb** [comment]
@dsimansk just ran this on latest master and it seems to be working again. The integration id itself, and pod annotations and labels had changed, but it's back where prometheus metrics service can lookup the right label again.

**Comment by dhirajsb** [comment]
![image](https://user-images.githubusercontent.com/181691/37113356-0b712cd8-21fa-11e8-8334-b843e3e59642.png)

See the latest screen shot, which shows the network call returning total message count of 1, but the display is not updating for some reason. Same for the timestamps.

**Comment by deeleman** [comment]
The UI expects a different response schema, that’s why neither the message count nor the timestamp reflect those changes.

I would kindly refer you to the spec issue for the UI in the EPIC acceptance criteria but... yay, it doesn’t exist! So your safest bet is:

- [ ] check back the previous posts in this very same thread to discover the schema we expect for messages and timestamp.
- [ ] I can update all the front end implementation to honor the new schema featured in this new API response, in which case I’ll require you to contribute with a schema definition (which also explains what item in the integrationDeploymentMetrics array shall we pick when there’s more than one). The latter is required to prevent more issues like this in one or two days.

Pick one @dhirajsb , I’m easy ;)

**Comment by deeleman** [comment]
All right, I'll take over this one, so we can get it done for tomorrow.

**Comment by dhirajsb** [comment]
@deeleman sorry I missed this earlier. But, the response being returned currently from the backend does match the one mentioned earlier in the thread. See the sample (pretty printed) output below:
```
{
  "metricsProvider": "prometheus",
  "messages": 1,
  "errors": 0,
  "start": 1520453276978,
  "lastProcessed": 1520450183250
  "integrationDeploymentMetrics": [
    {
      "version": "1",
      "messages": 1,
      "errors": 0,
      "start": 1520453276978,
      "lastProcessed": 1520450183250
    }
  ]
}
```
Note that start and lastProcessed in the root node will be missing if the integration is not currently active.

**Comment by deeleman** [comment]
I know @dhirajsb. The implementation already took that into consideration, displaying “n/a” when such information is missing.

**Comment by deeleman** [comment]
Actually, the problem was originated because the integration metrics object returned for a specific integration neglected the ID parameter in the response, which was part of the original definition so the front end expected it to locate and replace the piece of state in our local store.

This is why sticking to the original schema (or any formal, public schema that we can use to validate our implementation) is so crucial.
