### ISSUE TITLE
API Connector: delete button is missing

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis#1827]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
There's no `Delete` button anymore in the listed item.

## Expected behavior
Delete button is displayed in a listed item.

## Screenshot
<img width="1231" alt="screen shot 2018-03-05 at 21 18 14" src="https://user-images.githubusercontent.com/5637792/36997768-fb3092ae-20ba-11e8-88a0-5bf79eedde28.png">

**Comment by dsimansk** [comment]
@deeleman there's PR https://github.com/syndesisio/syndesis/pull/1679 that removes delete button, but there's no substitute for the action. Am I missing anything here?

**Comment by deeleman** [comment]
The reason why that delete button was removed was because of #1442. unfortunately I messed up big time the reference in all those PRs and that issue also points to an unrelated PR too.

**Comment by deeleman** [comment]
@dsimansk  All the wrong references between PR's and issues have been fixed to make our lives easier in the future. Now I just wait for your final call on what to do with that DELETE button in reference to #1442. If you consider that no further action is required after assessing that issue, please proceed to close this issue. Otherwise please let me know how to proceed here.

**Comment by dsimansk** [comment]
@deeleman imho wrt #1442 and consistency with Extensions listing. There should be `Delete` button present but when API connector has an related Connection user should be warned by modal similar to extension's one. Therefor user is still able to delete connector when taking warning into consideration.

@mastepan @zregvart wdyt?

![screen shot 2018-03-07 at 08 08 26](https://user-images.githubusercontent.com/5637792/37078354-33a67f02-21df-11e8-9247-72131f85dac5.png)

**Comment by deeleman** [comment]
The question here is: Would deleting such connection eventually lead to leave the application in a bad state at some point?

- [ ] **No** -> Awesome! Then let's trigger a confirmation modal and call it a day.
- [ ] **Yes** -> Then let's just display a label reading `Delete disabled - Remove dependant connections first`. Another approach would be to delete all related connections in the same action. From an UI POV we should then trigger a modal like the one you attached above that would warn the user that deleting the connector will also delete all the related connections. This obviously sounds like more overhead to me tho.

**Comment by zregvart** [comment]
We should get @syndesisio/uxd opinion on this, the as I reed [the design](https://github.com/syndesisio/syndesis/blob/master/ux/designs/apiconnector/apiconnector.md#api-connector-list) the button is always there.

Deleting a connector doesn't influence the running integration, it does influence editing and then re-publishing the integration.

**Comment by mastepan** [comment]
> Deleting a connector doesn't influence the running integration, it does influence editing and then re-publishing the integration.
Actually it influences editing of a connection created from the connector...or? It doesn't mean we can't use an existing connection in an integration. 

I'd prefer more complex solution:
1. give a user ability to delete any connector (after warning dialog)
2. be able to revoke an original connector from any connection based on that connector. It means we would store the connector but wouldn't show the deleted ones in the connectors list.

**Comment by sjcox-rh** [comment]
@zregvart @mastepan @deeleman I still believe we should allow the user the option to delete custom connectors even if it is being used. It would be strange to have a delete button on some connectors that aren't being used, and not showing it for others. 

If the connector is being used, a modal should appear informing the user that deleting this connection may cause issues as it's currently in use. This way the user is warned prior to deleting if they still choose to do so. 

So similar to the modal that @dsimansk mentioned above would be great!

**Comment by deeleman** [comment]
What's the final decision on this? @zregvart @mastepan @dsimansk

> If the connector is being used, a modal should appear informing the user that deleting this connection may cause issues as it's currently in use. This way the user is warned prior to deleting if they still choose to do so.

@sjcox-rh  Should this become the final way to go, I'll expect UXD to supply the copywriting for this, thanks.

**Comment by dsimansk** [comment]
@deeleman I vote to go for simple solution now. Reinstate the delete button as it was and maybe add a modal if it's quick win. And revisit the more complext behaviour for GA. Wdyt? @mastepan @zregvart

**Comment by amysueg** [comment]
I agree to keep it simple for now and I like @sjcox-rh 's suggestion.

@deelman wrote 
> @sjcox-rh Should this become the final way to go, I'll expect UXD to supply the copywriting for this, thanks.

@deeleman Sure thing, and we will rely on @TovaCohen 's expertise here as well.

**Comment by TovaCohen** [comment]
I'm not sure of the details, but here's a start:

> Warning!
> There are integrations that use connections created from this connector. You can delete this connector but the consequence of doing so is that you cannot edit connections that were created from this connector. 
> 
> An integration that is running and that uses a connection created from this connector continues to run. You can create new integrations and add connections created from this connector. 
> 
> Are you sure you want to delete the "xyz" connector?
> 
>                                                       Cancel     Delete

**Comment by mastepan** [comment]
Thanks @TovaCohen
What about this? :

> Warning!
> You will not be able to edit any connection that was created from this connector.
> 
> It doesn't influence running integrations.
> You can still create, run and edit integrations and add connections created from this connector.
> 
> Are you sure you want to delete the "xyz" connector?

                                                  Cancel     Delete

**Comment by TovaCohen** [comment]
@mastepan thanks for the clarifications. 
I think it is important to explicitly assure the user that published integrations continue to run. Since a user creates an integration by adding a bunch of things to it, it is reasonable for the user to wonder whether the integration will continue running after deleting something that was needed to create the integration. So I think this deserves a sentence of its own. 

The Red Hat convention is to not use contractions in text. 
Here's my update:

> Warning!
> If you delete this connector, then you cannot edit a connection that you created from this connector. 
> 
> Any integrations that are running and that use a connection that was created from this connector continue to run. You can still add connections created from this connector to integrations. You can create, run, and edit integrations that use connections created from this connector. 
> 
> Are you sure you want to delete the "xyz" connector?
>                                                                                     Cancel      Delete

**Comment by mastepan** [comment]
@TovaCohen I agree we shouldn't omit any important information. I'm just trying to keep the text as short as possible. That's why I prefer slightly different formulations. I don't insist on exact text that follows. I'm just evolving your idea trying to make it a bit shorter.

version 3:

> Warning!
> You will not be able to edit any connection that was created from this connector.
> 
> You can still add connections created from this connector to integrations.
> It has no impact on running integrations.
> 
> Are you sure you want to delete the "xyz" connector?
> Cancel Delete
>

**Comment by paoloantinori** [comment]
Actions:
- add button back
- decide what text to display

**Comment by deeleman** [comment]
@TovaCohen @mastepan Perhaps we should agree on a final content ASAP, since we initially agreed on taking action on this issue by tomorrow as the latest.

**Comment by TovaCohen** [comment]
How's this:

> Warning!
> 
> You can no longer edit a connection that was created from this connector. 
> 
> You can still add connections created from this connector to integrations. Deleting this connector does not affect running integrations.
> 
> Are you sure you want to delete the "xyz" connector?

Background:
Some UI text conventions are described here:
https://www.patternfly.org/styles/terminology-and-wording/

When that does not address something, then I refer to the 
Glossary of Terms and Conventions for Product Documentation[1] and
to the IBM Style Guide, which is the style guide we use for customer documentation. 

I can't think of a good reason not to apply user doc conventions to UI text and messages. Let me know if you think otherwise. 

The IBM Style Guide says:
Do not use contractions in technical information.
Use past or future tense only when you cannot use present tense or it does not make sense to use
present tense.

In your latest revision, in the second paragraph, it is unclear what "It" in the second sentence refers to.

**Comment by TovaCohen** [comment]
[1] http://ccs-jenkins.gsslab.brq.redhat.com:8080/job/glossary-of-terms-and-conventions-for-product-documentation-branch-master/lastSuccessfulBuild/artifact/index.html

**Comment by mastepan** [comment]
> How's this:
> 
> Warning!
> 
> You can no longer edit a connection that was created from this connector.
> 
> You can still add connections created from this connector to integrations. Deleting this connector does not affect running integrations.
> 
> Are you sure you want to delete the "xyz" connector?

Great! Thanks @TovaCohen 
@deeleman We definitely can go with this one.

> I can't think of a good reason not to apply user doc conventions to UI text and messages. Let me know if you think otherwise.
I neither. It wasn't my intention. Thanks a lot for the guidelines :)

> In your latest revision, in the second paragraph, it is unclear what "It" in the second sentence refers to.
You're right. It might be misleading.
