### ISSUE TITLE
Integration Editor: `Save as Draft` doesn't proceed to next page

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis#1828]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
`Save as Draft` successfully submit a request to backend but doesn't process to detail page afterwards.

## Expected behavior
User should be redirected to `Integration Detail` after successful submit op.

## Tasks involved / Steps to Reproduce

1. Create integration 
2. `Save as Draft`

**Comment by gashcrumb** [comment]
It was decided in a previous issue that clicking 'save as draft' should keep you in the editor and not redirect you to the detail page -> https://github.com/syndesisio/syndesis/issues/239#issuecomment-362679645

**Comment by dsimansk** [comment]
@gashcrumb maybe a toast notification upon success without be useful then.
