### ISSUE TITLE
[extensions] do not override "partial json" info

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#1833]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

The extension-maven-plugin generates extension meta-data from maven project and from "partial json" but it does override name, description, version whit values from the mavebn project or plugin configuration, for more info see https://github.com/lburgazzoli/syndesis-extension-example-xml/issues/7

## Screenshot

The maven plugin itself then needs to check each of these values if its specified in the maven plugin config section or not. If its not specified then it should not touch the values in the json if its already defined.

## Tasks involved / Steps to Reproduce

1. 
2.
3.
4.

**Comment by lhein** [comment]
@nicolaferraro feel free to reach out to me for any questions.
