### ISSUE TITLE
Support password OAuth flow

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#1840]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

For #1290 we need to support OAuth password flow.

## Tasks involved
1. We need to differentiate in the UI between supported OAuth flows
2. For token flow we need to do exactly as we do now
3. For password flow we need to prompt for username/password
4. In credentials we need to exchange username/password/clientId/clientSecret for OAuth token, store it in client state, and apply it to the newly create connection (as we do now)

**Comment by zregvart** [comment]
We didn't end up needing this for #1290 (Concur connector), we managed to use the authorization code grant flow (the only flow we support in OAuth). There was one user that provided feedback needing this. Not sure if it's a priority.

**Comment by KurtStam** [comment]
Seems to me that we can close this.
