### ISSUE TITLE
'enum' field isn't consistently set for SQL stored procedure form

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#1842]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

After removing and re-adding an SQL stored procedure step, I found that the select element was replaced by a regular input, and checking the server response I noticed no `enum` property was present in the response.

## Expected behavior

When removing and re-adding the same step the controls in the configuration form should behave consistently, in this case I'd expect the select element to still be present.

## Tasks involved / Steps to Reproduce

1) Create an integration and use the SQL stored prodedure for the last step, save it
2) Delete the last step
3) When prompted to complete the last step, use the SQL stored procedure again
4) On the configuration page the control is a regular input control instead of a select element

**Comment by zregvart** [comment]
Could be due to the timeout added in #1829, would you mind setting `META_TIMEOUT` environment variable on the `syndesis-server` pod to `10000` (10 seconds) to see if that's the case?

**Comment by gashcrumb** [comment]
So I did that and can't reproduce it, however I also took out the environment variable and still can't reproduce it.  I haven't actually rebuilt any of the backend since yesterday, and I'm suspicious that this isn't so easy to reproduce.  This is something I came across while investigating a totally unrelated issue, so raised it just in case :-)

**Comment by zregvart** [comment]
Hmm, I wonder why you would get an data shape with empty enum, that seemed to me something we added in #1829; with this we should look at the metadata implementation in the `syndesis-meta`.

I know we have/had issues with that, for instance this could be the same issue that we have when using sql stored procedure at the start position.

cc @KurtStam, @lburgazzoli

**Comment by zregvart** [comment]
I believe this was fixed with #1899
