### ISSUE TITLE
Unreadable error when integration fails

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#1847]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

![out](https://user-images.githubusercontent.com/14313995/37041015-7125058a-215b-11e8-9ae9-483e36a4af21.gif)

## Expected behavior

Reasonable failure message, maybe add a line that more information and the exception can be found in openshift logs

## Tasks involved / Steps to Reproduce

1.  Publish invalid integration
2.  Hover with mouse over red cross icon

**Comment by gashcrumb** [comment]
Yeah, we should probably not even use the attribute from the integration that contains that message and instead just show a more general statement with a link to the activity log.  Doing that will require us to be able to link directly to the activity log tab, @deeleman is that possible now or would we need to implement that?

**Comment by deeleman** [comment]
We should implement that. Tabs in the integration detail page are not implemented as routable components. We should wrap those (including the activity log once it is restored) in a child router outlet and assign route links to the detail view tabs.

So there’re 2 tasks required for this, actually

**Comment by gashcrumb** [comment]
Yep, lemme create an issue for that.

**Comment by amysueg** [comment]
UX took a look at this and like Stan and Pablo's recommendations.
