### ISSUE TITLE
[monitoring] The Integration Activity Steps sub view should trigger a raw logs modal per step

### ISSUE THREAD

**Issue by deeleman** [syndesisio/syndesis#1856]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
With a detailed steps activity sub view per Integration activity entry at the Integration detail view (as defined by #1855 ), we need a way to access, view and copy the raw logs for each step log so we can use those elsewhere.

## Expected behavior
We will want to append an additional action button at the right of each row in the Steps activity sub table (as depicted in the screenshot below) which will trigger a modal window wrapping the raw log with copy-to-clipboard functionality.

## Screenshot
![captura de pantalla 2018-03-06 a las 20 57 37](https://user-images.githubusercontent.com/1104146/37055081-0d6e5796-2181-11e8-93ce-8f07f6707cdb.png)

## API Endpoints and Schemas

TBD @chirino Could you fill this out? Thx

## Tasks involved / Steps to Reproduce

1. Create and deploy an integration. Wait for its `published` status.
2. Go to the integration detail view and click on activity
3. On the activity rows displayed (if any), click on the arrow on the left.
4. Check that a sub view contained tabular data matching the design above is rendered
5. Click on the `View` button where available to see the raw log displayed in a modal window. The logs should be wrapped by a scrollable div. Two buttons reading `Copy` and `Close` should allow for copying the modal contents to the clipboard and closing the modal popup, respectively.
6. Click on the `Copy` button. Its label should change to `Copied!` and pasting the clipboard contents in any text file should yield the raw log we just saw at the modal, in its entirety.

**Comment by deeleman** [comment]
@chirino Perhaps we should remove the `target/tp4` label for this one. Do you agree?

**Comment by chirino** [comment]
Do we really need this?  Are we not already showing the log step output or failure in the table?

**Comment by deeleman** [comment]
@chirino Who are you asking to? This is not my call I just formalized the task to give it an actionable context. :)

Perhaps you should ping @kcbabo

**Comment by kcbabo** [comment]
This looks awesome!  The minimal requirement we had was that log output (including detailed error information if available) was visible in the activity viewer.  If we already have that in place today, then I would say this particular issue can be pushed out of GA scope.

I will say that wha is proposed here looks great from an end user standpoint and I'm sure this would be very useful!  Would love to see this in the next release.

As an aside, I wonder how the existing output cell in the table will scale to handle large amounts of output (e.g. stack trace).  Seems like what is being proposed in this issue would be a good way to handle that case.

**Comment by deeleman** [comment]
This is how it looks with the logs embedded in place. The logs area is vertically scrollable. Disregard the `n/a` name in the steps of the screenshot attached. This belong to a legacy integration

![captura de pantalla 2018-03-16 a las 16 05 57](https://user-images.githubusercontent.com/1104146/37527814-38087f4a-2933-11e8-801f-e2a4a9cb64cb.png)

**Comment by kcbabo** [comment]
That looks great!

**Comment by chirino** [comment]
This issue seems done to me.
