### ISSUE TITLE
[monitoring]  Users should be redirected to the Openshift Console for Integration full detailed logs

### ISSUE THREAD

**Issue by deeleman** [syndesisio/syndesis#1857]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
The Integration activity view allows for checking basic activity logs. However, users might require a more finegrained level of detail when it comes to track down Integration logs, which can only be accessed from the OpenShift console itself.

## Expected behavior
Users should be able to click on a link at the Integration activity tab that would redirect them to the OpenShift console tab for that integration hence accessing its detailed logs.

Such redirection will happen in a separate browser tab.

## Screenshot
![captura de pantalla 2018-03-06 a las 21 10 17](https://user-images.githubusercontent.com/1104146/37055724-b6db3078-2182-11e8-9e27-eebd01cbeac6.png)

## API Endpoints and Schemas

@chirino Can you expand on this? Thx

## Tasks involved / Steps to Reproduce

1. Create and deploy an integration. Wait for its published status.
2. Go to the integration detail view and click on activity
3. Locate a link reading `View Log in OpenShift`at the top right, before the _Refresh_ functionality.
4. Click on the link and double check that the user is redirected to the OpenShift console and, more specifically, to the console view.

**Comment by sjcox-rh** [comment]
@deeleman I would think opening a new tab would be ideal since it brings the user to a new product. This way the user can still have iPaaS open while viewing the full logs in the OpenShift console.

**Comment by deeleman** [comment]
Thanks for your feedback @sjcox-rh. I’ve updated the acceptance criteria to reflect your input.

**Comment by deeleman** [comment]
@chirino Perhaps we should remove the `target/tp4` label for this one. Do you agree?

**Comment by chirino** [comment]
@deeleman your call.  Generally this just needs a link to URLs like:
`https://192.168.64.10:8443/console/project/syndesis/browse/pods/i-sql-2-reverb-2-7vx48?tab=logs`

The `https://192.168.64.10:8443/console` and `/syndesis` parts should be a configuration setting(s) in config.json.  The `i-sql-2-reverb-2-7vx48` part of the URL is the pod name that that you can get from the pod field of each activity.  The rest of the URL is static.

**Comment by chirino** [comment]
Should be fixed once #2049 is merged.
