### ISSUE TITLE
Integration Editor: Salesforce objects are not selectable from list anymore 

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis#1865]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
There used to be dropdown `select` element populated from Salesforce API to list all available sObject names to be used in the integration. In latest version there's `input` element without autocompletion working

```
<input _ngcontent-c38="" class="form-control ng-touched ng-dirty ng-invalid" autocomplete="on" name="sObjectName" placeholder="" spellcheck="false" type="text" required="" id="sObjectName">
```

## Expected behavior
User is able to select sObject from list.

## Screenshot
![screen shot 2018-03-07 at 09 27 23](https://user-images.githubusercontent.com/5637792/37081448-c3e70d70-21e9-11e8-99d3-33b38d073bdf.png)

**Comment by dsimansk** [comment]
@paoloantinori @gashcrumb fyi

**Comment by zregvart** [comment]
@dsimansk does the `syndesis-meta` pod log show any errors? With #1829 we added a fallback response if the metadata retrieval fails (fix for #1659), though at that point a notification should be shown with the error from the `syndesis-meta`. Can you inspect the network response for the `/api/v1/connections/{connectionId}/actions/{actionId}` and see if the properties in the action definition have `enum` values listed there?

**Comment by dsimansk** [comment]
`syndesis-meta` log is quiet:
```
2018-03-07 11:37:45.489  INFO 1 --- [  XNIO-3 task-4] o.a.c.c.s.internal.SalesforceSession     : Login at Salesforce loginUrl: https://login.salesforce.com/services/oauth2/token
2018-03-07 11:37:45.894  INFO 1 --- [  XNIO-3 task-4] o.a.c.c.s.internal.SalesforceSession     : Login successful
```

And response from `/api/v1/connections/{connectionId}/actions/{actionId}` seems also fine:
https://gist.github.com/dsimansk/eb1500682c74598707b80330fab069ef

**Comment by gashcrumb** [comment]
Wonder if this is similar to https://github.com/syndesisio/syndesis/issues/1842 will have to see if I can reproduce today.

**Comment by gashcrumb** [comment]
Yep, response back is:

```
  "propertyDefinitionSteps": [
    {
      "description": "Specify the Salesforce object name of the record to create or update.",
      "name": "Name of the object",
      "properties": {
        "sObjectName": {
          "componentProperty": false,
          "defaultValue": "Contact",
          "deprecated": false,
          "description": "Name of the Salesforce object",
          "displayName": "Object name",
          "group": "common",
          "javaType": "java.lang.String",
          "kind": "parameter",
          "required": true,
          "secret": false,
          "type": "string"
        }
      }
    },
    {
      "description": "Specify the field name that holds the identifying value.",
      "name": "Identifier field name",
      "properties": {
        "sObjectIdName": {
          "componentProperty": false,
          "deprecated": false,
          "description": "Field name of the identifier",
          "displayName": "Identifier field",
          "group": "common",
          "javaType": "java.lang.String",
          "kind": "parameter",
          "required": true,
          "secret": false,
          "type": "string"
        }
      }
    }
  ],
  "_meta": {}
```

so no select control for you.

**Comment by zregvart** [comment]
yup, should be fixed by #1886

**Comment by tplevko** [comment]
Can't verify this ATM, we have a small issue with salesforce API, it seems I have to wait till morning. 
![hit_the_roof](https://user-images.githubusercontent.com/4180208/37341840-2b2b6f0c-26c3-11e8-8c22-97b69cba7620.png)

**Comment by tplevko** [comment]
Seems to work OK now, closing this.
