### ISSUE TITLE
Basic Filter: list of field names for Salesforce object is empty

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis#1867]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
`datalist` element is not empty when Basic Filter is added to integration like `SF->Basic Filter->Datamapper->DB`. Resulting in no autocompletion for SF object fields to filter. However same use case with Twitter Mention action is working fine.

## Expected behavior
User is able to select field name to filter on from a populated list.

Cc @gashcrumb @paoloantinori

**Comment by zregvart** [comment]
I thought we fixed this with #1295?

**Comment by dsimansk** [comment]
@gashcrumb this can definitely be related to env timeout issues. I can't reproduce it on reseted Minishift instance.

**Comment by zregvart** [comment]
I believe this was fixed with #1899
