### ISSUE TITLE
Deployments hanging in OS after integration delete, pods scaled to 0

### ISSUE THREAD

**Issue by tplevko** [syndesisio/syndesis#1872]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

I tried to delete integration. The delete action in syndesis removed the integration from syndesis, there is however a deployment in OpenShift hanging, with pods scaled to 0.

## Screenshot

![deployments_hanging](https://user-images.githubusercontent.com/4180208/37091306-f119bcd4-2207-11e8-9a05-07ed4f5af70f.png)

## Tasks involved / Steps to Reproduce

1. Create integration
2. Delete integration
3. Go to OpenShift console
4. See, there is a deployment left after the integration was deleted

**Comment by dsimansk** [comment]
We need to able to completely clean all OpenShift resources, because of limits applied to Ignite cluster etc. Therefor this is marked as blocker issue.

**Comment by dsimansk** [comment]
@tplevko I can' reproduce this issue anymore.

**Comment by tplevko** [comment]
Seems to work now, fixed in: https://github.com/syndesisio/syndesis/pull/1871
