### ISSUE TITLE
Add support for new controlHint and labelHint properties in back-end

### ISSUE THREAD

**Issue by seanforyou23** [syndesisio/syndesis#1881]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

We have support for these new properties in our form factory provider service, but until they are "a thing" in the back-end we can't use them in our model driven forms.

Until this happens, and after https://github.com/syndesisio/syndesis/pull/1664/ has been merged, we'll notice a "regression" in our model driven forms where what _used_ to be tooltip text attached and duplicated across a label and its form control counterpart will become description text that renders below a given form control.

Merging https://github.com/syndesisio/syndesis/pull/1664/ before this is in place will cause our model driven forms to come out of sync with our UX designs until these properties are updated to use the new *correct property names in the various *.json files.

It's the last puzzle piece for resolving https://github.com/syndesisio/syndesis/issues/992

## Expected behavior

The properties `labelHint` and `controlHint` in `app/connector/activemq/src/main/resources/META-INF/syndesis/connector/activemq.json` and similar type files, should be provided as part of the payload with the rest of the form properties.

## Screenshot

<img width="840" alt="screen shot 2018-03-07 at 10 38 15 am" src="https://user-images.githubusercontent.com/5942899/37101762-506e62c0-21f4-11e8-85b2-b475a255cbb2.png">

## API Endpoints and Schemas

`/api/v1/connectors`

## Tasks involved / Steps to Reproduce

1. Specify a `labelHint` property in `app/connector/activemq/src/main/resources/META-INF/syndesis/connector/activemq.json` for any form property, for example `brokerUrl`
2. Begin watching network traffic in your browser dev tools
3. Begin adding an AMQ connection, and when you get to the configuration screen, notice the tooltip doesn't show up
4. Also notice the call to `https://syndesis.x.x.x.x.nip.io/api/v1/connectors` didn't return the new property.

**Comment by dhirajsb** [comment]
@seanforyou23 after modifying the activemq.json, you'd have to rebuild the `syndesis/syndesis-server` image and restart the `syndesis-server-*` pod to see the updated hints. I'm trying that right now, just takes a while. 
Is the plan to rename all `description` fields to `labelHint` to restore the previous behavior? I am not sure there is enough time to go through all the connectors to come up with new descriptions and control hints in this sprint. @rhuss wdyt?

**Comment by dhirajsb** [comment]
@seanforyou23 the backend needs to add those fields to `ComponentDefinition.Property` interface. Working on it now.

**Comment by seanforyou23** [comment]
@dhirajsb yes exactly replacing `description` with `labelHint` across the board would be the thing to do. Not all form fields need both description, labelHint, and controlHint, they are just options for when a UX design calls for it. Once these properties are supported I will decorate the appropriate form definitions with controlHint and description as necessary. Of course, anyone is welcome to :)

**Comment by dhirajsb** [comment]
Added PR https://github.com/syndesisio/syndesis/pull/1888 to add the missing `labelHint` and `controlHint` fields. I haven't changed any connector properties. Is that something you can do @seanforyou23 ?

**Comment by seanforyou23** [comment]
Yes I'd be happy to pick up the remaining bits!

**Comment by seanforyou23** [comment]
Awesome @dhirajsb thank you and I will look at this first thing today!

**Comment by seanforyou23** [comment]
This seems to be working great @dhirajsb - Just going through the different connectors and comparing to the UX designs.. keep you posted.

**Comment by dhirajsb** [comment]
Closed this for the backend, @seanforyou23 might want to create a new issue to add hint fields for rest of the connectors??

**Comment by seanforyou23** [comment]
I just referenced #992 when I posted the PR since it was pretty much leftovers from that work anyway. Hope that's ok.
