### ISSUE TITLE
Increase default timeout for meta invocation and inform the user of a timeout

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#1886]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

#1867, #1842 and #1865 point to a common cause in #1659, we should increase the default timeout (say from 1.5s to 3s) and notify the user in case of a timeout.

**Comment by gashcrumb** [comment]
I'd argue that even 3 seconds is too short if we're talking about having bounds to making requests to external systems.

**Comment by zregvart** [comment]
We should probably measure that, I can set it to any value, do we have a timeout setting on the Ajax requests I don't want to go over that.

**Comment by gashcrumb** [comment]
Hmm, good question, I don't think we explicitly set one, @deeleman do you know?
