### ISSUE TITLE
Add an API to fetch the user's maximum allowed integrations.

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#1887]
## This is a...

<pre><code>
[ x ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Breaking this out from the discussion on #246 

Currently when quotas are enabled there's no way for the UI to query what the quota limits are.

## Expected behavior

The UI needs a way to fetch a user's quota limits so that it can properly reflect that a user's quota is reached and do things like disable publish buttons/actions.

## API Endpoints and Schemas

TBD - ideally there should be some top level context like `/quota` that returns the max allowed integrations,  and if the user cannot create any more integrations.

## Tasks involved / Steps to Reproduce

HIgh level tasks

1. Create appropriate endpoint in the backend to expose quota limits
2. Identify what actions in the UI need to be hidden or disabled when a limit is reached
3. Fetch quota limits periodically from the backend, ideally server side events could notify the UI when it needs to update it's view of the quota limits
4. Update related controls to react properly when a quota limit is hit.

**Comment by zregvart** [comment]
This done @KurtStam ?

**Comment by KurtStam** [comment]
Yes the API was added https://github.com/syndesisio/syndesis/pull/4067. I think there is still a UI task outstanding.

**Comment by gashcrumb** [comment]
This bit's done, so no need to keep this issue open.
