### ISSUE TITLE
Updating integration description toast notification says "Updated undefined"

### ISSUE THREAD

**Issue by michael-coker** [syndesisio/syndesis#1890]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
From the integration details page, if you edit the description and click "Save", the toast notification says "Update Successful Updated undefined"

## Expected behavior
I would expect it to say "Update Successful" or "Update Successful. Updated integration [integration name]." or something to that effect. @TovaCohen do you know what that should say?

## Screenshot
![screen shot 2018-03-07 at 4 51 33 pm](https://user-images.githubusercontent.com/35148959/37123087-9b05556c-2228-11e8-9112-619417ae8f4a.png)

## Tasks involved / Steps to Reproduce
1. Go to the integration details page for an integration
2. Click the pencil beside the description and then click "Save"
3. See the toast notification in the top/right.

**Comment by TovaCohen** [comment]
Based on the description of toast notifications here:
http://www.patternfly.org/pattern-library/communication/toast-notifications/ 
The text can be either of these:

**Update successful.
Update saved.**

without any additional text. Keep the period. Only the first word is capitalized. Bold the text. 

After I edited a description, I also edited and saved the name of the integration and this notification appeared:
![image](https://user-images.githubusercontent.com/25067106/37152941-0980f7d2-22a9-11e8-96fc-6f464fa94c3f.png)
Should I create a separate issue to fix that?

**Comment by michael-coker** [comment]
@TovaCohen thanks! Re: the other error, there is an issue for it already https://github.com/syndesisio/syndesis/issues/1823

**Comment by gashcrumb** [comment]
Honestly do we really even need notifications for updating the name or description?  Seems gratuitous...

**Comment by gashcrumb** [comment]
Cool, I'll take those out and am fixing the behavior too.  This makes it easier as well given that the API we're using can actually update multiple attributes in one request, so makes for way complicated toast notifications...
