### ISSUE TITLE
Failing logging UnitTest breaks the build

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#1891]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[*] Bug report  
[ ] Documentation issue or request
</code></pre>

[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 21.218 s <<< FAILURE! - in io.syndesis.server.logging.jsondb.controller.ActivityTrackingControllerTest
[ERROR] testLogsController(io.syndesis.server.logging.jsondb.controller.ActivityTrackingControllerTest)  Time elapsed: 21.093 s  <<< ERROR!
org.awaitility.core.ConditionTimeoutException: 
Assertion condition defined as a lambda expression in io.syndesis.server.logging.jsondb.controller.ActivityTrackingControllerTest expected:<"{
  "activity" : {
    "exchanges" : {
      "my-integration" : {
        "-L38cZ51d1L876xV4vEF" : "{\"id\":\"-L38cZ51d1L876xV4vEF\",\"logts\":\"2018-01-12T21:22:02.068338027Z\",\"at\":1516285084034,\"pod\":\"test-pod-x23x\",\"ver\":\"3\",\"status\":\"done\",\"failed\":false,\"steps\":[{\"id\":\"-L38cZ5Nd1L876xV4vEI\",\"at\":1516285084056,\"duration\":18087},{\"id\":\"-L38cZ5Od1L876xV4vEJ\",\"at\":1516285084057,\"duration\":494949},{\"id\":\"-L38cZ5Jd1L876xV4vEH\",\"at\":1516285084052,\"duration\":582977,\"messages\":[\"Hello World\"]}]}",
        "-L38cZ5Pd1L876xV4vEL" : "{\"id\":\"-L38cZ5Pd1L876xV4vEL\",\"logts\":\"2018-01-12T21:22:02.068338027Z\",\"at\":1516285084058,\"pod\":\"test-pod-x23x\",\"ver\":\"3\",\"status\":\"done\",\"failed\":true,\"steps\":[{\"id\":\"-L38cZ5Pd1L876xV4vEN\",\"at\":1516285084058,\"duration\":213613,\"messages\":[\"Hello World\"]}]}",
        "-L38cZ5Ud1L876xV4vEQ" : "{\"id\":\"-L38cZ5Ud1L876xV4vEQ\",\"logts\":\"2018-01-12T21:22:02.068338027Z\",\"at\":1516285084063,\"pod\":\"test-pod-x23x\",\"ver\":\"3\",\"status\":\"done\",\"failed\":false,\"steps\":[{\"id\":\"-L38cZ5Vd1L876xV4vET\",\"at\":1516285084064,\"duration\":4242},{\"id\":\"-L38cZ5Vd1L876xV4vEU\",\"at\":1516285084064,\"duration\":70724},{\"id\":\"-L38cZ5Vd1L876xV4vES\",\"at\":1516285084064,\"duration\":247312,\"messages\":[\"Hello World\"]}]}"
      }
    },
    "integrations" : {
      "my-integration" : true
    },
    "pods" : {
      "test-pod-x23x" : {
        "time" : "2018-01-12T21:22:02.068338027Z"
      }
    }
  }
}"> but was:<null> within 20 seconds.
	at io.syndesis.server.logging.jsondb.controller.ActivityTrackingControllerTest.testLogsController(ActivityTrackingControllerTest.java:107)
Caused by: org.junit.ComparisonFailure: 
expected:<"{
  "activity" : {
    "exchanges" : {
      "my-integration" : {
        "-L38cZ51d1L876xV4vEF" : "{\"id\":\"-L38cZ51d1L876xV4vEF\",\"logts\":\"2018-01-12T21:22:02.068338027Z\",\"at\":1516285084034,\"pod\":\"test-pod-x23x\",\"ver\":\"3\",\"status\":\"done\",\"failed\":false,\"steps\":[{\"id\":\"-L38cZ5Nd1L876xV4vEI\",\"at\":1516285084056,\"duration\":18087},{\"id\":\"-L38cZ5Od1L876xV4vEJ\",\"at\":1516285084057,\"duration\":494949},{\"id\":\"-L38cZ5Jd1L876xV4vEH\",\"at\":1516285084052,\"duration\":582977,\"messages\":[\"Hello World\"]}]}",
        "-L38cZ5Pd1L876xV4vEL" : "{\"id\":\"-L38cZ5Pd1L876xV4vEL\",\"logts\":\"2018-01-12T21:22:02.068338027Z\",\"at\":1516285084058,\"pod\":\"test-pod-x23x\",\"ver\":\"3\",\"status\":\"done\",\"failed\":true,\"steps\":[{\"id\":\"-L38cZ5Pd1L876xV4vEN\",\"at\":1516285084058,\"duration\":213613,\"messages\":[\"Hello World\"]}]}",
        "-L38cZ5Ud1L876xV4vEQ" : "{\"id\":\"-L38cZ5Ud1L876xV4vEQ\",\"logts\":\"2018-01-12T21:22:02.068338027Z\",\"at\":1516285084063,\"pod\":\"test-pod-x23x\",\"ver\":\"3\",\"status\":\"done\",\"failed\":false,\"steps\":[{\"id\":\"-L38cZ5Vd1L876xV4vET\",\"at\":1516285084064,\"duration\":4242},{\"id\":\"-L38cZ5Vd1L876xV4vEU\",\"at\":1516285084064,\"duration\":70724},{\"id\":\"-L38cZ5Vd1L876xV4vES\",\"at\":1516285084064,\"duration\":247312,\"messages\":[\"Hello World\"]}]}"
      }
    },
    "integrations" : {
      "my-integration" : true
    },
    "pods" : {
      "test-pod-x23x" : {
        "time" : "2018-01-12T21:22:02.068338027Z"
      }
    }
  }
}"> but was:<null>
	at io.syndesis.server.logging.jsondb.controller.ActivityTrackingControllerTest.lambda$testLogsController$0(ActivityTrackingControllerTest.java:109)

23:13:53.496 [Logs Controller] INFO io.syndesis.server.logging.jsondb.controller.ActivityTrackingController - Batch ingestion work thread done.
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   ActivityTrackingControllerTest.testLogsController:107 » ConditionTimeout Asser...
[INFO] 
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

**Comment by rhuss** [comment]
fixed with #1885
