### ISSUE TITLE
Provide external database connectivity capabilities and tutorial

### ISSUE THREAD

**Issue by honghuac** [syndesisio/syndesis#1892]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Documentation issue or request
</code></pre>

Regarding use cases involving external databases, provide database connectivity features which are easy to use as well as a tutorial that explains the use of these features.

Currently, how can a Citizen Developer utilize the [SQL connector](https://github.com/syndesisio/syndesis/tree/master/app/connector/sql) in an integration for multiple database connections? Please explain / demonstrate.

**Comment by KurtStam** [comment]
You'd need a different DB connector for each database you'd want to connect to.

**Comment by TovaCohen** [comment]
The tutorial that provides instructions for obtaining data from Salesforce and then saving it in a database is here: 
https://access.redhat.com/documentation/en-us/red_hat_jboss_fuse/7.0-tp/html/ignite_sample_integration_tutorials/salesforce-to-db

The general doc for connecting to a database is here:
https://access.redhat.com/documentation/en-us/red_hat_jboss_fuse/7.0-tp/html/integrating_applications_with_ignite/connecting-to-applications#connecting-to-databases 

That's all we have so far. For TP4 and GA there will be additional doc. 
Can you tell me more about this use case:
> How can a Citizen Developer utilize the SQL connector in an integration for multiple database connections? 
I can write better user doc for you if I know more about what you want to do. Why do you want to connect to multiple databases in an integration? Can you give me an example?
Thanks!

**Comment by KurtStam** [comment]
@TovaCohen maybe we can add a sentence the 'general doc' somewhere that says something along the lines of: "You will need a to create a different DBConnection for each Database you want to connect to in your integration".

**Comment by TovaCohen** [comment]
Sure. The "Connecting to SQL database" section now has this introduction:

> Connecting to SQL databases
> 
> In an integration, you can connect to any of the following types of databases:
> 
> Apache Derby
> 
> MySQL
> 
> PostgreSQL
> 
> You create a separate connection for each database that you want to connect to in an integration. You can use the same connection in multiple integrations.
> 
> A database connection operates on a table that you specify or invokes a stored procedure that you specify. The database table or the stored procedure must exist when an integration connects to the database.

Let me know if anything needs to change.

**Comment by KurtStam** [comment]
@TovaCohen Looks good to me.
