### ISSUE TITLE
Missing icons: HTTPS, MQTT

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis#1907]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
There're missing icons for the following connectors **HTTPS** (probably should be the same as HTTP), **MQTT** and **SFTP** (tracked separately in #1706). 

Note: FTP icon seems a bit generic maybe.

## Screenshot
![screen shot 2018-03-08 at 16 59 49](https://user-images.githubusercontent.com/5637792/37161128-266116cc-22f2-11e8-90e4-5ea6f11af1b8.png)

Cc @dongniwang @sjcox-rh

**Comment by sjcox-rh** [comment]
@dsimansk Thanks for bringing this to our attention. The icon for sftp has already been delivered but I can work on https and mqtt today. As for https, I will probably do the same thing I did to differentiate ftp from sftp, so I will provide an updated icon for http as well that you can swap the old one out for.

**Comment by sjcox-rh** [comment]
@dsimansk Here are the icons for https and mqtt:

![connectionicons_https](https://user-images.githubusercontent.com/16257540/37359534-18864362-26ab-11e8-86b9-e7b09a281fa2.png)

![connectionicons_mqtt](https://user-images.githubusercontent.com/16257540/37359526-124af66e-26ab-11e8-8caa-bf5eb697694a.png)

I've also created a new folder within the UX branch which includes all the png and svg's of all ipaas connection icons. Currently waiting on PR to be approved before anyone can access

PR #1963 

FYI: @gashcrumb @kahboom

**Comment by sjcox-rh** [comment]
@dsimansk Here are the png's for https and mqtt:

![connectionicons_https](https://user-images.githubusercontent.com/16257540/37359967-336eea02-26ac-11e8-8d73-d686f2820c58.png)

![connectionicons_mqtt](https://user-images.githubusercontent.com/16257540/37359978-394f388c-26ac-11e8-93d8-6ef8a2f28e44.png)

I've created a new folder within the UX branch where you can find all the connection icon svg's as well as png's. Still waiting on that PR to get merged before you have access to the svg's files for https and mqtt.

PR #1963 

fyi, @gashcrumb

**Comment by sjcox-rh** [comment]
@dsimansk Here is the folder containing all the svgs

https://github.com/syndesisio/syndesis/tree/master/ux/connections_icons/svg

**Comment by gashcrumb** [comment]
thanks @sjcox-rh I'll get those in now :-)
