### ISSUE TITLE
Replace instances of activate/deactivate with publish/unpublish

### ISSUE THREAD

**Issue by TovaCohen** [syndesisio/syndesis#1909]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
The UI should no longer refer to activate/deactivate since those integration states no longer exist. 
I don't have a list of all the instances that need to be updated. A few examples are below. I hope you can search and find all instances. 

## Expected behavior
The desired behavior is that all appropriate references are to publish and unpublish. 
For example, when you try to publish an integration, the current behavior is that you get this popup:

## Screenshot

![image](https://user-images.githubusercontent.com/25067106/37162996-adc15786-22c4-11e8-864a-7fb863f32db9.png)

This should be updated to: "Confirm Publication" and "Are you sure you want to publish the xyz integration?"
The corresponding behavior exists when you click Unpublish. That is, the popup says "Confirm Deactivation" when it should say "Confirm Unpublish" and then the message should be "Are you sure you want to unpublish the xyz integration?"

Since "Confirm Unpublish" is awkward, maybe change the title of both popups to just "Confirm". 

Here's another example: this toast notification: "Integration is activating. Please allow a moment for the integration to fully activate." should be: "Publishing integration. Your integration will start running in a few moments. "
## Tasks involved / Steps to Reproduce

- In the list of integrations, for an integration that is not published, click Publish.
- In the list of integrations, for an integration that is published, click Unpublish.

**Comment by michael-coker** [comment]
@TovaCohen 

Re: changing 

> "Integration is activating. Please allow a moment for the integration to fully activate."

to

> "Publishing integration. Your integration will start running in a few moments. "

When unpublishing an integration, how should that text read? Currently it's:

> Unpublishing integration. Please allow a moment for the integration to unpublish.

**Comment by michael-coker** [comment]
@TovaCohen 

Also, re:

> Since "Confirm Unpublish" is awkward, maybe change the title of both popups to just "Confirm".

There are 4 modals that pop up like that. "Confirm Replace Draft" and "Confirm Deletion" are the other two. Should those simply say "Confirm" too?

**Comment by TovaCohen** [comment]
For unpublish:
**Unpublishing integration.** It takes a few moments to unpublish the integration.

Oh good, I knew there were other instances of "Confirm Whatever". Glad you could find them. And yes, I think they can all be titled with just
 **Confirm**
