### ISSUE TITLE
Place "create new connection" UI elements inside a card-like component.

### ISSUE THREAD

**Issue by amysueg** [syndesisio/syndesis#1916]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
The "+" icon, text, and "create connection" button appear to float on the page. I think we could enhance the user experience by collecting these items and surrounding them with a "card-like" design. That could imply to a user that once they create a new connection it will generate a new card. Could use a dimmed "white" background, a dotted outline, or whatever SJ comes up with for us to review. :-)

## Expected behavior
Same behaviors, just a visual design change.

## Screenshot
<img width="1043" alt="groupfloatingelements" src="https://user-images.githubusercontent.com/31700119/37180437-f8928ad2-22f6-11e8-8350-5583511d53dc.png">

@dongniwang @michael-coker @seanforyou23 fyi -- need to think about everywhere in the UI where this appears... dashboard?

**Comment by deeleman** [comment]
> need to think about everywhere in the UI where this appears... dashboard?

If this UI element is meant to be rendered in different parts of the site, a reusable component is the way to go. Actually, ew should build a single, unique , configurable component for ALL “create” actions.

**Comment by michael-coker** [comment]
@amysueg I think that's the only spot we have a "create" action in a list of cards like that. A couple of areas we could add another would be:

on the connections list page

![screen shot 2018-03-09 at 9 11 38 am](https://user-images.githubusercontent.com/35148959/37214477-d9dc6002-237a-11e8-8be1-0a9f2106a4b7.png)

And the connections list on the dashboard
![screen shot 2018-03-09 at 9 13 05 am](https://user-images.githubusercontent.com/35148959/37214496-ea66ebae-237a-11e8-9ff9-a09e8b1a2cb6.png)

**Comment by michael-coker** [comment]
@deeleman I added a helper class in this branch - [empty-state-card](https://github.com/michael-coker/syndesis/tree/empty-state-card). Do you want me to create a PR for that or do you want to take a different approach for creating this component?

**Comment by michael-coker** [comment]
@deeleman I created some reusable CSS for that element on this branch: [empty-state-card](https://github.com/michael-coker/syndesis/tree/empty-state-card). Is that what you had in mind or do you want to do something different?

**Comment by deeleman** [comment]
Reusable CSS is a good start, but I would take this effort a bit further and build a reusable and configurable web component.

Configurability of such component can be carried out by means of @Input properties or template transclusion.

Do not hesitate in asking for help if needed.

**Comment by michael-coker** [comment]
> build a reusable and configurable web component

Can you give me a quick example of what you mean? And maybe point me towards something similar in the app that already exists? I'm not sure if this is an angular app component or if you mean a configurable mixin or something else?

**Comment by deeleman** [comment]
I mean an Angular component, so we cater not only with CSS but with HTML content as well, in a reusable fashion.

**Comment by michael-coker** [comment]
@deeleman I took a stab at it and updated the [empty-state-card](https://github.com/michael-coker/syndesis/tree/empty-state-card) branch. Bear in mind this was my first time creating a component in Angular :)

**Comment by gashcrumb** [comment]
Where is this issue at?  I'm guessing @sjcox-rh shouldn't be assigned to this at this stage?

**Comment by michael-coker** [comment]
@gashcrumb from @deeleman's suggestion to create an angular component, I added one on the [empty-state-card](https://github.com/michael-coker/syndesis/tree/empty-state-card) branch. Could someone review it and see if that is a usable solution?

**Comment by gashcrumb** [comment]
So took a quick look, I think it's worth opening a PR though with that branch as then it's easier for folks to give feedback.  Thanks!
