### ISSUE TITLE
Invalid cookie header - message appears when Connection creation fails

### ISSUE THREAD

**Issue by honghuac** [syndesisio/syndesis#1948]
## This is a...

<pre><code>
[ ] Feature request
[X] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
The following error messages appear "Invalid Cookie Header":
https://gist.github.com/honghuac/4f9a6357d5e9f782183642328a288771
upon the authorization of a Twitter app, as part of the Connection creation process.

## Expected behavior

Creation of connection should complete successfully.

## Screenshot

![spinning](https://user-images.githubusercontent.com/8625482/37280164-f50a2db4-2627-11e8-94f2-80752c5c642a.png)

## Tasks involved / Steps to Reproduce

1. Re-create a new Twitter connection on the current code base of Fuse Ingnite.
2. This problem will emerge.

**Comment by zregvart** [comment]
I wonder where those `personalization_id` and `guest_id` Cookies come from, I don't think we set them in Syndesis.

@honghuac any errors/warnings on the development tools console in the browser?

**Comment by honghuac** [comment]
@zregvart Unfortunately, nothing on the Dev Tools console front.

**Comment by tplevko** [comment]
I wasn't able to reproduce this issue, tried insertion of both valid and invalid twitter credentials. Were there maybe some additional steps involved?

**Comment by zregvart** [comment]
This will be fixed by removing the confusing exception stack traces in #2045 and adding robustness to client side state in #1949.
