### ISSUE TITLE
Data Type Mismatch for "Invoke SQL" step

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#1952]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Invoke SQL step has now input data required as json-schema even if you don't use variables in SQL query. Whole intagration works even with this warning so it is misleading for the end user - data type mismatch but it works??

![datatypemissmatch](https://user-images.githubusercontent.com/14313995/37296564-a21830b2-261b-11e8-8570-068bd7b9bf1f.png)

Adding data mapper step looks like this:
![datamappersteperror](https://user-images.githubusercontent.com/14313995/37296669-f2593814-261b-11e8-837d-55c3307fd2c2.png)

## Expected behavior

Invoke SQL step has no input data required if it doesn't use variables in the query

## Screenshot

![invokesql](https://user-images.githubusercontent.com/14313995/37296296-d8e12802-261a-11e8-8425-30183ff0f181.png)

**Comment by KurtStam** [comment]
@mcada Thanks for you bug report. Can you add the Steps to reproduce?

**Comment by mcada** [comment]
Oh sorry I didn't include them, just create new integration, select random start step and as finish or any other step select Database connection and as action select Invoke SQL.

**Comment by KurtStam** [comment]
I can't reproduce this. Maybe it got fixed? @mcade Please reopen if this is still an issue for you.

<img width="537" alt="screen shot 2018-03-14 at 7 51 37 pm" src="https://user-images.githubusercontent.com/35576/37436992-267778da-27c1-11e8-8cdd-c487933436c7.png">
