### ISSUE TITLE
Import/Export: UI: Validation

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis#1957]
## This is a...

<pre><code>
[ x ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
The UI needs to validate imported integrations, on two levels:
1. API. Server errors, invalid file format, etc. #2081
2. UI. Immediate file type detection, size detection, etc.

## Expected behavior
Display the appropriate error to the user in inline notifications.

## Screenshot
[Full Designs](https://github.com/syndesisio/syndesis/blob/master/ux/designs/importexport/importexport.md)

## API Endpoints and Schemas
N/A

## Tasks involved / Steps to Reproduce
1. Navigate to Integrations > Import.
2. Do anything typically considered to be invalid (e.g. select the wrong file type).
3. No proper validation is shown to the user.

**Comment by kahboom** [comment]
@gashcrumb - The epic this corresponds to is assigned to Sprint 35 still--do we want to update both to 36?

**Comment by gashcrumb** [comment]
Yep, I'd move it to a Sprint where we'll implement it.
