### ISSUE TITLE
Syndesis public API access

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#1959]
See also **https://issues.jboss.org/browse/ENTESB-11550**

## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
We would like to have tools integrate with Syndesis. For this we will provide public API access that those tools can use.

Currently targeting:
 - Import/Export API (#967)
 - Extensions API (?)

It seems that using OpenShift OAuth tokens is not a good way to authenticate API access, so we should develop our own API access method independent of it.

## Expected behavior

Tools can use the API securely.

## API Endpoints and Schemas

 - Import/Export API at `/api/v1/integration-support`
 - Extensions API at `/api/v1/extensions`

## Tasks involved / Steps to Reproduce
1. Create project proposal
2. Implement API access
3. Publish the public API documentation

**Comment by apupier** [comment]
cc @lhein

**Comment by zregvart** [comment]
Some background on this: we proposed a change to the `oauth_proxy` to accept OAuth tokens from the user and to authenticate them against the API server not using SubjectAccessReview. This was deemed as a security issue by the OpenShift team.

We currently rely on `oauth_proxy` and it relies on interactively obtained HTTP cookies to check access.

While using HTTP cookies for access is fine, it's probably not a good idea to have the caller of the API use HTTP endpoints intended for humans to gain access to them.

I think we need some way of generating authentication tokens and verifying them. With or without oauth_proxy.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11550**
