### ISSUE TITLE
Avoid returning incomplete data shapes for dynamic action

### ISSUE THREAD

**Issue by igarashitm** [syndesisio/syndesis#1967]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
[x] Technical Debt
</code></pre>

## The problem
Derived from #1961, specifically  https://github.com/syndesisio/syndesis/issues/1961#issuecomment-372763621

Currently if action is not yet configured, `fetchMetadata` API is returning incomplete data shapes which is pre-defined in deployment.json, like `kind=json-schema` but specification is undefined. This data shape doesn't make any sense for dynamic action and confusing when UI handles it. We should clarify this behavior.

## Expected behavior
Not sure. One idea is to return `kind=none` if it's dynamic action but not yet have enough info to get dynamic data shapes.

**Comment by gashcrumb** [comment]
> One idea is to return kind=none if it's dynamic action but not yet have enough info to get dynamic data shapes.

Actually this would probably make the most sense.  If it's always the case that `kind != none` means there's a specification and `kind == none` always doesn't have a specification that'd help out the current UI code :-)

**Comment by igarashitm** [comment]
Oh BTW, we should also keep in mind that there're connectors which have `kind=any` unless user defines custom data type. `kind=any` is also the one which doesn't have specification defined.

Currently no problem with `kind=any` though, as there's no connector which change its kind to/from `any` depending on dynamic action configuration.

**Comment by KurtStam** [comment]
@zregvart This would have to be implemented for every connector. I know the database connector suffers from this and I will address this. Should we open subtasks for each affected connector?

**Comment by zregvart** [comment]
I've created #1981 that I think will sort this out for all connectors. Would like to see if we can make simpler in the long run though.
