### ISSUE TITLE
Icon links are broken for MQTT and HTTPS connectors

### ISSUE THREAD

**Issue by kcbabo** [syndesisio/syndesis#1972]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
Broken link for HTTPS and MQTT icons in the card list when creating a new connection.

**Comment by oscerd** [comment]
![screenshot](https://user-images.githubusercontent.com/5106647/37397423-d71e0fbe-277b-11e8-80d4-b46aaf496172.png)

Looks good now.

**Comment by oscerd** [comment]
Fixed.
