### ISSUE TITLE
HTTP Connector description could use some elaboration

### ISSUE THREAD

**Issue by kcbabo** [syndesisio/syndesis#1974]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
Current description is:
> Http Connector

**Comment by paoloantinori** [comment]
Hey Keith, this really sounds like an enhancement, not really a bug, by definition.

We can mark it as a very important enhancement, but really not a bug.

@TovaCohen  you are probably the best person to help us techie to put this in meaningful words.

**Comment by TovaCohen** [comment]
For the connector description, how about:
Specify URL to call external server

**Comment by kcbabo** [comment]
Point me to where this description is stored and I will submit a pull request.

**Comment by TovaCohen** [comment]
https://github.com/syndesisio/syndesis/blob/master/app/connector/http/src/main/resources/META-INF/syndesis/connector/http4.json

https://github.com/syndesisio/syndesis/blob/master/app/connector/http/src/main/resources/META-INF/syndesis/connector/https4.json

Are there two connectors - one for http4 and one for https4?
What does this look like to the user?

**Comment by oscerd** [comment]
Yes, there are two different connectors. To the user this will look like two different connections to choose. We need to treat them as separated connectors.

**Comment by TovaCohen** [comment]
Thanks @oscerd . Then I think we need two connector descriptions:
HTTP4
Specify URL to call non-encrypted external server
HTTPS4
Specify URL to call encrypted external server

**Comment by oscerd** [comment]
This has been supersesed by #2840
