### ISSUE TITLE
Uptime metric is broken for system and integrations

### ISSUE THREAD

**Issue by kcbabo** [syndesisio/syndesis#1975]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
Uptime metric for system and integrations are both N/A until an integration actually runs.  Once an integration does run, the uptime (for both) only reflects the time since the first run of the integration and now.  Uptime should reflect when the system started (for dashboard system metrics) and when an integration started.

**Comment by KurtStam** [comment]
@dhirajsb want to take a look at this?

**Comment by paoloantinori** [comment]
is this a bug or an enhancement request?

**Comment by kcbabo** [comment]
I generally consider broken things to be bugs. :-)

If the system is up or an integration is deployed, the value should not be N/A.

**Comment by KurtStam** [comment]
@kcbabo Can you define what "when the system started" means? Is calculated from when the server pod was last (re)started? And if so then this means the system uptime could be shorter then an integration uptime (if the integration kept running when the server pod restarted).

**Comment by kcbabo** [comment]
From an end user perspective, I believe "when the system started" means when the UI is available and available to use.  Roughly equivalent to the REST server uptime I expect.

Agree that system uptime could be < than individual integration runtimes.  Makes sense if iPaaS infra was upgraded or had to restart for some reason independent of integration containers.

**Comment by KurtStam** [comment]
@kcbabo so you're saying 'yes' or the latest startTime between all the synthesis-* pods?

**Comment by kcbabo** [comment]
I think system uptime should be tied to syndesis-server.
