### ISSUE TITLE
A few issues with activity viewer data

### ISSUE THREAD

**Issue by kcbabo** [syndesisio/syndesis#1976]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
Check out the attached image for reference.  Activity viewer is looking cool, but there are a few issues:

- Step labels are N/A or empty
- Duration values are incorrect (see associated timestamp entries)
- Should something appear in output?  If so, then it's missing.  If not, I think we should say something like "No output" instead of N/A.

![image](https://user-images.githubusercontent.com/340837/37381515-f2a6be24-2713-11e8-824f-3649c7f2b52e.png)

**Comment by deeleman** [comment]
A few notes here:
- The step labels issue is being actioned at #1983. 
- The text for the output column was addressed in the #1855 discussion thread, given the lack of an original spec for that.
- A fix for the duration values is in the works and will be submitted for review in 3... 2... 1...

**Comment by deeleman** [comment]
As part of the aforementioned fix for the durations, the default `n/a` value for the _output_ column will be replaced by `No output`
