### ISSUE TITLE
Steps data in the integration activity log graph does match the one at the integration overview object

### ISSUE THREAD

**Issue by deeleman** [syndesisio/syndesis#1983]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[✗] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
The Integration activity logs endpoint (`/api/v1/activity/integrations/{id}`) returns a cursor of records related to steps logs that are meant to be rendered at the subviews within the activities listview displayed at the activity tab in the integration detail page.

The information returned by the aforementioned API endpoint does not include the step name, so it must be retrieved straight from the Integration overview graph, by picking the name of the step whose ID matches the one on each step log.

Unfortunately, as we can see by the graphs below, the IDs provided do not match:

#### Integration overview graph (excerpt):

```json
  "steps": [
    {
      "connection": {
        "connectorId": "sql",
        "icon": "fa-database",
        "name": "PostgresDB",
        "id": "5"
      },
      "action": {
        "name": "Periodic SQL invocation"
      },
      "kind": "step",
      "stepKind": "endpoint",
      "id": "-L7PHtACrdmuSqA48niv"
    },
    {
      "action": {},
      "kind": "step",
      "stepKind": "mapper",
      "name": "Data Mapper",
      "id": "-L7PHxnNrdmuSqA48niw"
    },
    {
      "connection": {
        "connectorId": "sql",
        "icon": "fa-database",
        "name": "PostgresDB",
        "id": "5"
      },
      "action": {
        "name": "Invoke stored procedure"
      },
      "kind": "step",
      "stepKind": "endpoint",
      "id": "-L7PHwHXrdmuSqA48niv"
    }
  ],
```

#### Any given activity log entry
```json
  {
    "id": "i-L7ZVynK_OXU13YIGIRwz",
    "logts": "2018-03-14T12:37:28.408534847Z",
    "at": 1521031048405,
    "pod": "i-my-db-to-db-integration-1-fwbqw",
    "ver": "1",
    "status": "done",
    "failed": false,
    "steps": [
      {
        "id": "i-L7ZVynL_OXU13YIGIRxz",
        "at": 1521031048406,
        "duration": 876661
      },
      {
        "id": "i-L7ZVynM_OXU13YIGIRyz",
        "at": 1521031048407,
        "duration": 28664361
      }
    ]
  }
```

## Expected behavior
The step ids in the integration graph should match the ones on each activity log object.
![captura de pantalla 2018-03-14 a las 13 57 18](https://user-images.githubusercontent.com/1104146/37405646-774dedba-2795-11e8-9ace-427031ef83cf.png)

## API Endpoints and Schemas

- Integration overview: `/api/v1/integrations/{INTEGRATION_ID}/overview`
- Integration activity: `/api/v1/activity/integrations/{INTEGRATION_ID}`

## Tasks involved / Steps to Reproduce

1. Create an integration and wait for it to be published
2. Go to the integration detail page and click on the activity tab
3. Unfold any of the listview rows
4. Rows there should display the actual step name instead of `n/a`

**Comment by paoloantinori** [comment]
requires @kcbabo input

**Comment by kcbabo** [comment]
Hey Paolo - can you let me know what specifically requires my input?  I believe this is a follow-up issue that Pablo filed in response to the issue I created last night.

**Comment by chirino** [comment]
Well.. steps are matching up better now.. but we get a few oddball empty ones in the list.
