### ISSUE TITLE
UI, Datamapper tools icons description is invisible.

### ISSUE THREAD

**Issue by Stefan365** [syndesisio/syndesis#1988]
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request

## The problem
while adding / editing datamapper step,
there are 4 links/icons on top right corner of datamapper UI (see picture)

While mouseover event, it looks like some description is shown, but is not visible for the user.
In case of "table" element, description is semi-visible and interfering with the link itself, so that user has problem to click on that link itself (this "table" description is blinking, if the mouse pointer is in interference area).

## Expected behavior
Buttons descriptions are visible and do not interfere with links themselves.

## Screenshot
invisible descrition:
![dm_tools_description_not_visible](https://user-images.githubusercontent.com/2714974/37412421-2861ea16-27a5-11e8-95b9-50e6753e9032.png)

semivisible blinking "table" descrition:
![dm_tools_table_decription](https://user-images.githubusercontent.com/2714974/37412462-40853ef4-27a5-11e8-8b09-178613637c61.png)

## Tasks involved / Steps to Reproduce
1. create/edit integration 
2. add / edit datamapper step, so that you are provided with datamapper UI

**Comment by Stefan365** [comment]
Above mentioned "blinking descriptions" is more general problem.
It occurs also when described element is located at the screen border and 
while mouse-over system tries to adjust elements position to make description visible.

e.g. try to mouse-over this element:
![desctiption_blinking_problem](https://user-images.githubusercontent.com/2714974/37413479-7223fa0c-27a7-11e8-8983-bec6695393f3.png)

**Comment by paoloantinori** [comment]
@igarashitm  are you independent on this? might @michael-coker  help you?

**Comment by igarashitm** [comment]
Ah this might be becuase the border is the boundary between AtlasMap UI and Syndesis UI. I have no idea what to do...

**Comment by michael-coker** [comment]
@igarashitm I'm happy to look into this one if you'd like.

**Comment by igarashitm** [comment]
@michael-coker thanks that helps!

**Comment by michael-coker** [comment]
@igarashitm created PR https://github.com/atlasmap/atlasmap/pull/350

**Comment by igarashitm** [comment]
Yep, let's wait for next atlasmap update, I think it's gonna be after we complete the TP4 release.
