### ISSUE TITLE
AMQ and AMQP connections incorrectly offer RequestResponse as a finish connection action

### ISSUE THREAD

**Issue by TovaCohen** [syndesisio/syndesis#1993]
## This is a...

<pre><code>
[ ] Feature request
[x ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
Dhiraj confirmed for me that AMQ and AMQP connections that are used as the finish connection in an integration should not perform the Request Response action. That was the behavior in TP3. But now, the staging site displays the Request Response action as a choice when you add an AMQ or AMQP connection as a finish connection. 

## Expected behavior

When you add an AMQ or AMQP connection as a finish connection, the only action choice should be Publish Messages. 

## Screenshot
This appears when I am creating a new integration. I selected an AMQ connection as the finish connection, and these are the actions that I can select from. Request Response should NOT appear. 
![image](https://user-images.githubusercontent.com/25067106/37419998-2384254a-278c-11e8-8e06-46a750d2106a.png)

## Tasks involved / Steps to Reproduce

1. Create an AMQ connection.
2. Create a new integration and add the start connection.
3. For the finish connection, select an AMQ connection.
4. Two actions are available here, publish and request/response. Only publish should be available.

**Comment by gashcrumb** [comment]
Currently the UI filters the available actions based on the `pattern` attribute for an action, and that only has `From` and `To`, where `To` can be anywhere and `From` can only appear as a start connection.  Obviously we need a third option or better define this particular attribute.

**Comment by iocanel** [comment]
It might make sense to also use output datashape kind, so that we can distinguish between things that need to be terminal actions (and thus has output datashape kind equal to 'none').

Not sure if this approach is correct. I am experimenting it with it anyways. @rhuss, @lburgazzoli thoughts?

**Comment by gashcrumb** [comment]
Seems legit :-)

Though yeah, I'd maybe caution against being too hasty, it could be that we don't have any actions that have a `none` output data shape...

**Comment by gashcrumb** [comment]
And also the semantics of that increase complexity, it's certainly a lot easier to have one field that we can definitively check vs. 2 fields that require some interpretation.

**Comment by iocanel** [comment]
FWIW, this approach does work. So I removed the WIP and its up for review.

**Comment by gashcrumb** [comment]
K!  Note that if there's a bug raised for xyz action isn't available as a finish step you're gonna get a grumpy cat meme e-mailed to you :-)

**Comment by gashcrumb** [comment]
BTW does that fix this issue then?

**Comment by lburgazzoli** [comment]
@iocanel I agree (sorry for being late) with using the datashapes for filtering action.
imho we should remove `pattern` and rely only on datashapes.

**Comment by gashcrumb** [comment]
This is the danger of that approach -> https://github.com/syndesisio/syndesis/issues/2062#issuecomment-374197278

Maybe `pattern` should be set but driven by the data shapes, that'd be easier to use when doing these checks in the frontend, as currently a data shape has a lot of fields and semantics that have been attached to those fields which are fuzzy and therefore lead to edge cases.

**Comment by iocanel** [comment]
The commit has been reverted. What are we going to do in that front?
Shall we close it as a `won't fix` are we going to introduce a new field?

**Comment by gashcrumb** [comment]
Well, discussion tapered off, I still suggest adding a 3rd option to `pattern` vs using data shapes to calculate where an action can be used as a way of solving this.

**Comment by iocanel** [comment]
@gashcrumb: maybe we can split InOut to InOut (for stricly in-between actions) and InOptionalOut (for in between or edge actions).

**Comment by iocanel** [comment]
pull request with @gashcrumb suggested approach has been merged.
I am closing the issue. Feel free to reopne if anything new comes up.
