### ISSUE TITLE
Move "export" action from kebab to toolbar button in integration details page

### ISSUE THREAD

**Issue by michael-coker** [syndesisio/syndesis#1994]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
"export" action is in a kebab menu

## Expected behavior
it should be a button in the toolbar

## Screenshot
https://github.com/syndesisio/syndesis/blob/master/ux/designs/importexport/importexport.md

## Tasks involved / Steps to Reproduce
1. Go to integrations list
2. Click on integration
3. Look in the toolbar

**Comment by gashcrumb** [comment]
Really?  `cause the last design I saw it was in the kebab...  :-S

**Comment by michael-coker** [comment]
@dongniwang ^^

**Comment by dongniwang** [comment]
@gashcrumb - aha! I'm updating the integration details page design, so it would be in a button format as that's based off the Import/Export design...Do you remember which design you were looking at that has the export in the kebab?

cc: @amysueg @sjcox-rh

**Comment by gashcrumb** [comment]
@dongniwang these ones I think -> https://github.com/syndesisio/syndesis/blob/master/ux/designs/integration_details/integration_details_page.md

You know, maybe we should just bite the bullet and keep the designs all in invision if it's easier for you guys?  Seems like the screenshots in the repo make it harder to keep track of all these pages?

Maybe we need to create a new discuss issue and give it more thought...  @paoloantinori WDYT?

**Comment by amysueg** [comment]
@gashcrumb - @dongniwang  and I were talking about this in a slightly different context yesterday. We started to discuss a way to keep our designs in synch esp as new features are added to the product. The UX team will be working on this and will let everyone know what our thoughts are - this is a pretty common issue across different product areas. Keeping designs and design details in synch becomes more challenging over time.

**Comment by gashcrumb** [comment]
@amysueg @dongniwang created #2033 as a discussion spot so we can keep this issue focused on delicious kebabs.

**Comment by gashcrumb** [comment]
Just to clarify and let this issue move along, @michael-coker you're right, it should be the button :-)

**Comment by dsimansk** [comment]
@mcada fyi
