### ISSUE TITLE
Add build scripts which builds everything

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#2]
Ideally, there should be some flavours, like _full_ builds, or _fast_ builds.

A starting point is e.g. https://github.com/syndesisio/syndesis-project/tree/master/tools/minishift-build which does the fastest possible build over all projects (with a prio upstream pull and creating docker images). 

Ideally there is also a CI job, which can perform this overall build.

**Comment by gashcrumb** [comment]
Don't we have this now?

**Comment by gashcrumb** [comment]
I say that we do :-)
