### ISSUE TITLE
Setting connection id instead of tags in connection

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#2011]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Connection seems to have the connection id set in the `tags` field. Not sure when this is set, it might be when the connection is created.

## Expected behavior

`tags` field should contain only tags, not ids.

## Screenshot

![screenshot-2018-3-15 syndesis](https://user-images.githubusercontent.com/1306050/37458142-5af5e154-2844-11e8-8294-ca4e0b50f58a.png)

## Request and Response Data

```shell
$ jq .tags connection.json 
[
  "i-L7dBtUKe2I2NdegxppNz"
]
```

## API Endpoints and Schemas

 - Create new connection: `POST /api/v1/connections`

## Tasks involved / Steps to Reproduce

1. Create API-based connector
2. Create connection for the new connector

**Comment by gashcrumb** [comment]
Yeah, the UI sets the connector ID as a tag as before we had API Client connections all connectors had human readable strings.  So we can remove setting this tag.

Also as part of fixing this we should actually remove the tag line from the detail page, as it's been decided to remove all tag-related functionality until better defined.
