### ISSUE TITLE
Suggest to the user to set OAuth settings when creating a connection

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#2013]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

If you create a new API-based connector and immediately go and create a connection without setting OAuth settings no OAuth flow will be triggered.

This is because the `/api/v1/connectors/${id}/credentials` endpoint will not return anything if OAuth settings are not set.

## Expected behavior

Guide the user so that the easiest way of creating connections (the OAuth flow) is on the guided path.

## API Endpoints and Schemas

 - Fetching credentials: `GET /api/v1/connectors/{id}/credentials`
 - OAuth settings: `GET /setup/oauth-apps`, `GET|PUT /setup/oauth-apps/{id}`

## Tasks involved / Steps to Reproduce

1. Create new API-based connector
2. Immediately create new connection for that connector

**Comment by zregvart** [comment]
I got some feedback on this and it seems to be confusing for the (first time?) users. If you don't configure OAuth client settings, when creating the connection, the user will be prompted to fill in the OAuth parameters:

![screenshot_2018-08-07 syndesis](https://user-images.githubusercontent.com/1306050/43762473-4ee691c8-9a28-11e8-8e91-2ba7f8aef548.png)

I think accidental miss input for these parameters is quite easy, the user might end up inputting expired tokens, a lot of issues.

For OAuth based connections could we instead of that screen point the users to setup the OAuth settings first? So never prompt the user for all those details.

Something like:

![screenshot_2018-08-07 syndesis 1](https://user-images.githubusercontent.com/1306050/43762691-e9125f3e-9a28-11e8-9ac6-5f76667f8365.png)

That I think would be easy/cheap to do.

We could even be crazy user friendly and put the OAuth settings for the connector in-line here. This would be a bit more involved.

cc @gaughan @kcbabo 

fyi @TovaCohen

**Comment by TovaCohen** [comment]
+1 
For the text:
Authorize access to Twitter from this Fuse Online/Syndesis environment . Then you can create a Twitter connection. 

Button label: 
Authorize access to Twitter

**Comment by zregvart** [comment]
I think we can do better user experience here.

**Comment by dongniwang** [comment]
@zregvart - Yeah, I agreed. We might have some capacity this sprint to look into it. 

@syndesisio/uxd
