### ISSUE TITLE
Update f-m-p to avoid s2i build warnings

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#2014]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

According to https://github.com/fabric8io/fabric8-maven-plugin/issues/1221#issuecomment-370492713 the issue with s2i build and OpenShift 3.7 is fixed. We should upgrade to 3.5.38 of f-m-p

## The problem

Warning and non-fatal error when doing a build

## Tasks involved / Steps to Reproduce

1. Just build the images with `syndesis --images --flash`

**Comment by oscerd** [comment]
I can take care of this, if you're not working on this @rhuss

**Comment by oscerd** [comment]
Actually I don't see failure status anymore

`
[INFO] F8: Using OpenShift build with strategy S2I
[INFO] F8: Running generator spring-boot
[INFO] F8: spring-boot: Using Docker image fabric8/s2i-java:2.1 as base / builder
[INFO] Copying files to /home/oscerd/workspace/jboss-fuse/syndesis/app/server/runtime/target/docker/syndesis/syndesis-server/latest/build/maven
[INFO] Building tar: /home/oscerd/workspace/jboss-fuse/syndesis/app/server/runtime/target/docker/syndesis/syndesis-server/latest/tmp/docker-build.tar
[INFO] F8: [syndesis/syndesis-server:latest] "spring-boot": Created docker source tar /home/oscerd/workspace/jboss-fuse/syndesis/app/server/runtime/target/docker/syndesis/syndesis-server/latest/tmp/docker-build.tar
[INFO] F8: Creating BuildServiceConfig syndesis-server-s2i for Source build
[INFO] F8: Creating ImageStream syndesis-server
[INFO] F8: Starting Build syndesis-server-s2i
[INFO] F8: Waiting for build syndesis-server-s2i-1 to complete...
[INFO] Current reconnect backoff is 1000 milliseconds (T0)
[INFO] Current reconnect backoff is 2000 milliseconds (T1)
[INFO] Current reconnect backoff is 4000 milliseconds (T2)
[INFO] Current reconnect backoff is 8000 milliseconds (T3)
[INFO] Current reconnect backoff is 16000 milliseconds (T4)
[INFO] Current reconnect backoff is 32000 milliseconds (T5)
[INFO] Current reconnect backoff is 32000 milliseconds (T5)
[INFO] Current reconnect backoff is 32000 milliseconds (T5)
[INFO] F8: ==================================================================
[INFO] F8: Starting S2I Java Build .....
[INFO] F8: S2I binary build from fabric8-maven-plugin detected
[INFO] F8: Copying binaries from /tmp/src/maven to /deployments ...
[INFO] F8: Checking for SpringBoot archive...
[INFO] F8: Found runtime.jar...
[INFO] F8: ... done
[INFO] F8: 
[INFO] F8: Pushing image 172.30.1.1:5000/myproject/syndesis-server:latest ...
[INFO] F8: Pushed 0/26 layers, 0% complete
[INFO] F8: Pushed 1/26 layers, 15% complete
[INFO] F8: Pushed 2/26 layers, 15% complete
[INFO] F8: Pushed 3/26 layers, 15% complete
[INFO] F8: Pushed 4/26 layers, 15% complete
[INFO] F8: Pushed 5/26 layers, 19% complete
[INFO] F8: Pushed 6/26 layers, 23% complete
[INFO] F8: Pushed 7/26 layers, 27% complete
[INFO] F8: Pushed 8/26 layers, 31% complete
[INFO] F8: Pushed 9/26 layers, 35% complete
[INFO] F8: Pushed 10/26 layers, 39% complete
[INFO] F8: Pushed 11/26 layers, 43% complete
[INFO] F8: Pushed 12/26 layers, 48% complete
[INFO] F8: Pushed 13/26 layers, 51% complete
[INFO] F8: Pushed 14/26 layers, 55% complete
[INFO] F8: Pushed 15/26 layers, 60% complete
[INFO] F8: Pushed 16/26 layers, 64% complete
[INFO] F8: Pushed 17/26 layers, 68% complete
[INFO] F8: Pushed 18/26 layers, 74% complete
[INFO] F8: Pushed 19/26 layers, 77% complete
[INFO] F8: Pushed 20/26 layers, 80% complete
[INFO] F8: Pushed 21/26 layers, 84% complete
[INFO] F8: Pushed 22/26 layers, 90% complete
[INFO] F8: Pushed 23/26 layers, 92% complete
[INFO] Current reconnect backoff is 32000 milliseconds (T5)
[INFO] F8: Pushed 24/26 layers, 96% complete
[INFO] F8: Pushed 25/26 layers, 98% complete
[INFO] F8: Pushed 26/26 layers, 100% complete
[INFO] F8: Push successful
[INFO] Current reconnect backoff is 32000 milliseconds (T5)
[INFO] F8: Build syndesis-server-s2i-1 Complete
[WARNING] Executor didn't terminate in time after shutdown in close(), killing it in: io.fabric8.kubernetes.client.dsl.internal.WatchHTTPManager@29a9f925
[INFO] F8: Found tag on ImageStream syndesis-server tag: sha256:df90bb569738ae14a3fdfbf4b226605510e73eab5768d38e5c537f465c0ef9ef
[INFO] F8: ImageStream syndesis-server written to /home/oscerd/workspace/jboss-fuse/syndesis/app/server/runtime/target/server-runtime-is.yml
`
But I still see the warning from WatchConnectionManager

**Comment by oscerd** [comment]
By the way with 3.5.38 I see problems in syndesis-meta

`
oscerd@ghost:~/workspace/jboss-fuse/syndesis/tools/bin$ oc logs syndesis-meta-1-7d4wz
Starting the Java application using /opt/run-java/run-java.sh ...
/deployments/run-env.sh: line 8: LOADER_PATH: unbound variable
`

**Comment by rhuss** [comment]
@oscerd thanks for the updates ! Could you report the reconnect issue back to https://github.com/fabric8io/fabric8-maven-plugin/issues/1221 ?

For the script part, that comes probably from an update of the base image. Not sure where this `LOADER_PATH` comes from. Let me check ...

**Comment by rhuss** [comment]
@KurtStam is `LOADER_PATH` something you have introduced ? Note, that the startup scripts runs now with a `set -e` setting which means that undeclared variables must not be used.

So you should use a `${LOADER_PATH:-}` if there is a chance that LOADER_PATH could be empty in https://github.com/syndesisio/syndesis/blob/3734dfc6d186a25fe6dc2306ee1bf4276b7166ed/app/meta/src/main/fabric8-includes/run-env.sh#L8

(btw the run-env.sh script will break when you have files with spaces. should use some kind of xargs magic or loop to make it more robust). Also you should check for ${LOADER_HOME} being set.

**Comment by rhuss** [comment]
@oscerd the loader_path an issue of a broken (or at least not-so-robust) script on ours.

**Comment by rhuss** [comment]
@KurtStam @oscerd If you don't mind I would fix it.

**Comment by oscerd** [comment]
Let me know how do we want to go ahead, from the f-m-p side I believe they didn't notice you were talking about the Warning in WatchHTTPManager. So we may update to 3.5.38 anyway

**Comment by oscerd** [comment]
yeah, no problem. I'll review.

**Comment by rhuss** [comment]
@oscerd @KurtStam --> https://github.com/syndesisio/syndesis/pull/2018

**Comment by oscerd** [comment]
For the f-m-p, do we want to upgrade anyway?

**Comment by nicolaferraro** [comment]
the startup scripts runs now with a set -e setting which means that undeclared variables must not be used.
Thanks @rhuss, my mistake. :+1:

**Comment by nicolaferraro** [comment]
I also didn't care about spaces because it cannot happen since filenames are clean extensionId.

**Comment by rhuss** [comment]
@oscerd yes, lets upgrade.
