### ISSUE TITLE
Consider adding check for cycles

### ISSUE THREAD

**Issue by Stefan365** [syndesisio/syndesis#2017]
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request

## The problem
There is no warning / restriction for user if he selects autoreference with positive feedback route.
i.e. result is added into source, 
so that message volume is doubling every reading period. 

## Expected behavior
autoreference prohibited. Or with warning at least.

## Tasks involved / Steps to Reproduce
1. create DB to DB integrations Create DB to DB(Periodic SQL invocation/Invoke SQL) integration with datamapper step.
use: "SELECT * FROM TODO" for start action Periodic SQL invocation 
and "INSERT INTO TODO(task, completed)  VALUES (:#TASK, 0)" for finish action Invoke SQL
and invocation period 1000ms.

2. Add datamapper step, and map task to TASK. 
3. publish integration
4. Look, what's going to happen.

**Comment by deeleman** [comment]
This issue just won the "Best attention-seeker title" award 😆

**Comment by KurtStam** [comment]
Step 4 should have read: "You won't believe what's going to happen"

**Comment by KurtStam** [comment]
To "save you a click": In 50 steps the number of rows in the database outweighs the earth and a black hole opens up.

**Comment by gashcrumb** [comment]
I'm trying this now just to watch my minishift instance burn.

TBH I think this is a worthwhile feature.

**Comment by gashcrumb** [comment]
See, it's a great disk performance tool:

![capture](https://user-images.githubusercontent.com/351660/37484011-aff82b94-285d-11e8-926d-1230435f0d42.PNG)

weeeeee!

**Comment by KurtStam** [comment]
Goodbye my friend - it was nice working with you

<img width="683" alt="screen shot 2018-03-15 at 4 09 37 pm" src="https://user-images.githubusercontent.com/35576/37488528-5cc6631a-286b-11e8-8afd-19f76a1cdc1c.png">

**Comment by kahboom** [comment]
OMG this thread cracked me the hell up...
