### ISSUE TITLE
Export has secrets in plain text

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis#2021]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[*] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
Export file seems to contain some secrets in plain text. 
## Expected behavior
All secrets should be encrpyted in the export file.

## Screenshot

Robert Baumgartner report this via an email to me:
He said he got an export containing:

![inbox__776__-_hchirino_redhat_com_-_red_hat_mail](https://user-images.githubusercontent.com/103255/37469423-9cdfa68a-283b-11e8-9aa5-14d441377471.jpg)

## API Endpoints and Schemas
export api.

## Tasks involved / Steps to Reproduce
1. Export an integration using the SF connection.
2.
3.
4.

**Comment by chirino** [comment]
@dsimansk could you verify this?  Perhaps create some tests to validate this does not creep in again in the future?

**Comment by iocanel** [comment]
The export provided seems to have encrypted secrets, so I don't see what the issue really is?

**Comment by rbaumgar** [comment]
This is what I found in my export from TP-3

"tags":["salesforce"],"name":"SFDC RBa Connection","configuredProperties":{"clientId":"3MVG9I5...","clientSecret":"1559...",

"tags":["twitter"],"name":"Twitter RBa Connect","configuredProperties":{"accessToken":"»ENC:bddf97...","accessTokenSecret":"»ENC:70dbff...","consumerKey":"»ENC:3377ec...","consumerSecret
":"»ENC:cf6c89..."}

So Twitter is encrypted, SFDC NOT.

**Comment by dsimansk** [comment]
@chirino on `1.3.2` the clientSecret is encrypted as expected. But clientId is not, should it be also exported as encrypted?

**Comment by lburgazzoli** [comment]
@dsimansk `clientId` is not defined as secret, see: thttps://github.com/syndesisio/syndesis/blob/master/app/connector/salesforce/src/main/resources/META-INF/syndesis/connector/salesforce.json#L43

maybe we should ?

**Comment by dsimansk** [comment]
@lburgazzoli it seems that for the sake of consistency `clientId` should be also encrypted similarly to Twitter connector. @chirino @rhuss wdyt?

**Comment by zregvart** [comment]
I don't think the `clientId` should be secret, it's basically a `username`.

**Comment by rbaumgar** [comment]
In SFDC is the clientId more less the same as the accessToken in twitter, so it should be encrypted. It is not the UserName which is well known.
BTW in my opinion the credentials (from twitter, SFDC, and all other) should not be exported at all, from a security perspective...

**Comment by zregvart** [comment]
> In SFDC is the clientId more less the same as the accessToken in twitter, so it should be encrypted. It is not the UserName which is well known.

I'm sorry I think you're confusing OAuth 1.0 and OAuth 2.0. Salesforce OAuth the `clientId` refers to OAuth 2.0 `Client Identifier` [which is not secret](https://tools.ietf.org/html/rfc6749#section-2.2).

**Comment by chirino** [comment]
Closing as not a bug.
