### ISSUE TITLE
Let user to choose root element for XML Schema

### ISSUE THREAD

**Issue by igarashitm** [syndesisio/syndesis#2023]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
When user define a custom data type for shapeless connection, they can upload XML Schema. But since XML Schema itself allows multiple elements to be defined, which of the element is really used for the payload is not declared in itself.

## Expected behavior
 We need to let user to choose which one of those elements is used as a root element of the payload. This would supposed to be happen in "Describe Data Type" page.

Then we need to store that selection as an extra property of DataShape, and provide it into datamapper, so that the datamapper would only show the selected root element as an available field.

**Comment by igarashitm** [comment]
@kcbabo does this mean we need to parse XML Schema in the UI and show a list of elements to choose?

**Comment by gashcrumb** [comment]
@igarashitm we already have https://github.com/syndesisio/syndesis/issues/1878 to track this...
