### ISSUE TITLE
Select element in generated form isn't disabled when the form is read only

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#2024]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

The select element rendered by a read-only form does not have the `disabled` attribute set, and therefore be interacted with. 

## Expected behavior

If a dynamic form is configured to be read-only, the select element should be disabled or replaced with plain text, much like input fields.

## Screenshot

Example screenshot from the connection detail page for an AMQ connection:

![usable-select](https://user-images.githubusercontent.com/351660/37472131-b44d1fae-2841-11e8-9c07-8382e058fb7b.PNG)

## Tasks involved / Steps to Reproduce

1. Create a new AMQ connection, just use whatever for the broker URL
2. Go to the detail page for your AMQ connection
3. Note the 'Skip Certificate Check' field can be changed while all the rest of the controls are disabled

**Comment by gashcrumb** [comment]
@seanforyou23 this would be a good one for you I think...

**Comment by deeleman** [comment]
I've followed the steps described but cannot manage to see the form with all fields disabled, aside from the `Skip Certificate Check` listbox. Am I missing out any step.

I checked the `controlModel` injected object payload and the `disabled` property was set to `false` in all fields defined.

**Comment by gashcrumb** [comment]
Yep, `Skip Certificate Check` is the one.  I think we use a separate config item to disable the entire form vs every control on the form.

**Comment by deeleman** [comment]
> I think we use a separate config item to disable the entire form vs every control on the form.

I've just taken a generic approach for all select controls application-wide. If the injected `controlModel` is configured as `readonly = true`, the select listbox will be rendered as disabled no matter what.

**Comment by gashcrumb** [comment]
Perfect, tx!
