### ISSUE TITLE
Investigate Apparent Memory Leaks on syndesis-server

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis#2027]
## This is a...

<pre><code>
[ ] Feature request
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Syndesis Server pod appear to fail on its own, quite often on long running instances.
There are hints that this might be some kind of memory leak, probably even an evident one, to notice with a profiler.

We need to investigate to better understand what's the root cause of this problem.

## Expected behavior

Not to crash !

## Tasks involved / Steps to Reproduce

1. no better details yet. it seems to occurr even with simple integrations
2.
3.
4.

**Comment by KurtStam** [comment]
Does it crash on minishift as well as on the cluster?

**Comment by paoloantinori** [comment]
no, it's not been reported on `minishift`. indeed that let us believe this is caused by resource limits that are set on `fuse-ignite` but not locally on our dev environment.

investigating in that direction right now

**Comment by KurtStam** [comment]
Y hasn't been crashing for me.. so it's probably not a memory leak then.

**Comment by rhuss** [comment]
@paoloantinori Let me repeat my my mail here for reference:

> * Jolokia is switched off in the dc via AB_JOLOKIA_OFF=true for some reason I don't know. Should we switch it on ?
> * The resource limit is set to 612M which very likely is not large enough. What's about increasing it to 1GB ?
> * The process is started with

```
exec java -Djava.net.preferIPv4Stack=true -Duser.home=/tmp -javaagent:/opt/prometheus/jmx_prometheus_javaagent.jar=9779:/opt/prometheus/prometheus-config.yml 
-Xmx306m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2 -XX:CICompilerCount=2 -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 
-XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:+ExitOnOutOfMemoryError -cp . -jar /deployments/runtime.jar
```

> so there is a heap memory limit set to 306m. We could change the heap/ non-heap ratio to something else than 50%. Since according to Mareks observation a considerable amount is non-heap as the JVM does not run out of HeapMemory (otherwise it wouldn't have been killed by OpenShift wit OOM but stopped itself with an OutOfMemoryError), we might want lower the ratio to 40% (leading to 244M heap)

> * There is no configuration of the HTTP listener threads pools.By default, this is typically based on the number of cores returned by Runtime.getAvailableProcessors() which is not cgroup aware (in Java 9 it will be). That means when you run Syndesis on big machine clusters (AWS) you get considerably more threads eating up considerably more heap. An indication that this might be a problem for us is when Syndesis works on Minishift (2 cores) but not on OSO (64 cores or so). We should and have to configure this threads explicitly for undertow.

So the fact that it runs on Minishift and not on our ignite cluster (btw, with the *very same resources/limits* of course) indicates, that its an issue in setting threading and memory configuration properly.

**Comment by rhuss** [comment]
I just did a comparisation on syndesis-server on Minishift and latest 1.3.2 on fuse-ignite
on a freshly installed pod without any integration (baseline):

* fuse-ignite:
  - Memory:

```
USER        PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
1001360+      1  0.3  1.5 5094664 520048 ?      Ssl  Mar20   2:45 java -Djava.net.preferIPv4Stack=true -Duse
```
     Question here is, why VSZ is over 5Gigs, RSS with 520MB is also already close to our limit of 612 MB   

  - Threads: 50 (so not too much)

* Minishift:
   - Memory
```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
1000060+     1  6.3  8.3 2881476 407068 ?      Ssl  05:20   5:41 java -Djava.net.preferIPv4Stack=true -Duser
```
   - Threads: 54
  
So my theory that is based on an exhausting number of threads does not hold. Actually I'm also not sure the difference between 407MB minishift and 520MB on the cluster, but actually the conditions are not 100% comparable (did the cluster installation yesterday and minishift today). There could be indeed a leak issue. 

However, I think that 612 MB for syndesis-server as limit is too lest. I would like to raise it to 800 MB. Any objections ?

**Comment by paoloantinori** [comment]
Can you externalize the value to become an OpenShift template variable, to
give us the chance to overwrite it at deploy time?

It would be useful also to extend `bin/syndesis` script to support
overridden variables.


paolo

**Comment by rhuss** [comment]
Yes, I can do.

**Comment by rhuss** [comment]
Will do this also for syndesis-meta, the other Java based service.

**Comment by rhuss** [comment]
a super fresh installed minishift has 370MB RSS (2.9 GB VSZ)

**Comment by rhuss** [comment]
@paoloantinori Please review #2096 for the memory limits.

**Comment by rhuss** [comment]
Fyi: Fresh install on fuse-ignite from master, initial memory

--> 

```
USER        PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
1002130+      1 18.8  1.1 4392356 378060 ?      Ssl  08:51   0:56 java -Djava.net.preferIPv4Stack=true -Duse
```

**Comment by paoloantinori** [comment]
I'm downgrading this, since our it's blocker implications have been fixed by this PR: https://github.com/syndesisio/syndesis/pull/2096

**Comment by rhuss** [comment]
#2155 might be related.

Not sure how to proceed here.
