### ISSUE TITLE
Schedule daily release job on Jenkins

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis#2028]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

During the retrospective it's been decided to setup a Jenkins job to release a daily tag of Syndesis Docker images.

Support should be already there at scripts level, it's more a matter of configuring it on Jenkins

## Expected behavior
Have a daily release, useful in case of need to revert to a previous working state, not too far in time.

**Comment by zregvart** [comment]
This was done.
