### ISSUE TITLE
Extend pure bot to autoamitcally tag every new issue with triage label

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis#2030]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Classification on open issue must be approved by the development team. We need a way to mark "new" issues.
GH sends out notifications upon this kind of actions. We can re-use PureBot to implement this.

## Expected behavior

New issues are immediately, or within seconds, labeled with triage label.

**Comment by gashcrumb** [comment]
Should this not be created in the pure bot repo though -> https://github.com/syndesisio/pure-bot/issues

we can always move it...

**Comment by paoloantinori** [comment]
https://github.com/syndesisio/pure-bot/issues/36

**Comment by gashcrumb** [comment]
Let's close this copy...
