### ISSUE TITLE
Salesforce clientId and secret handling in exports

### ISSUE THREAD

**Issue by kcbabo** [syndesisio/syndesis#2036]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
The clientId and secret values for Salesforce OAuth are not encrypted in exported files.  Twitter OAuth information is encrypted, btw.

## Expected behavior
Salesforce OAuth values should be encrypted.

**Comment by zregvart** [comment]
Duplicate of #2021
