### ISSUE TITLE
integration step actions checker/warning-updater is missing

### ISSUE THREAD

**Issue by Stefan365** [syndesisio/syndesis#2041]
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request

## The problem
Example 1.
For integration with 2 input connections with 2 different SQL queries. and output to DB (Steps to reproduce, scenario 1) there is no meaning to add datamapper step in between 1st and 2nd input connections (se picture below), but user has this option.

Example 2.
If user has DB to DB integration with BasicFilter step, and input has been changed (scenario 2)- there should be some immediate notification, that values specified in this filter are no valid anymore.

It would be useful to have some 'integration step actions checker/updater' running in the background.

## Expected behavior
UI environment responses to user action in a way 
that in every moment is inline with logical consequencies of his action.
e.g, user is provided only with reasonable steps. or filters notifications are being updated continuously.

## Screenshot
unreasonable datamapper step:
![unreasonable_step](https://user-images.githubusercontent.com/2714974/37517769-cb3886fa-2912-11e8-8628-2f47c8f7d795.png)

basic filter, no warning:
![basic_filter_no_warning](https://user-images.githubusercontent.com/2714974/37518077-f2f38702-2913-11e8-90c3-bb64e5448aab.png)

## Tasks involved / Steps to Reproduce
Scenario 1
1 . Create DB to DB integration(Periodic SQL invocation/Invoke SQL) integration with datamapper step.
2. add a SQL connection in between start connection and datamapper step, with some other SQL query.
3. Try to add datamapper step in between 1st and 2nd input connections.

Scenario 2
1 . Create DB to DB integration (Periodic SQL invocation/Invoke SQL) integration with 'basic filter' step following with datamapper step.
2. specify basic filter.
3. Change source DB table in 'Periodic SQL invocation'.
  there are no alerts in basic filter operating with old values.

**Comment by gashcrumb** [comment]
Actually #249 is pretty old and stale.  Let's use this issue to track the general problem, which is while we allow the user to go in and muck with connection config and potentially change types we really don't support it.
