### ISSUE TITLE
Java Console cannot be opened on Syndesis pods

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#2054]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ *] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
When going to the Openshift console and trying to open a java-console for either the syndesis-rest or syndesis-meta pod - it's not connecting.

## Expected behavior
Seeing the java console

## Screenshot
<img width="774" alt="screen shot 2018-03-16 at 3 33 30 pm" src="https://user-images.githubusercontent.com/35576/37541066-a28b48ba-292f-11e8-9570-3ddd1848ed5e.png">

**Comment by dsimansk** [comment]
@KurtStam it seems that Jolokia is disabled by env vars https://github.com/syndesisio/syndesis/blob/master/install/generator/04-syndesis-server.yml.mustache#L61-L66

**Comment by KurtStam** [comment]
@dsimansk thx, but even when I set that to `false` I get the same error.

**Comment by rhuss** [comment]
what does the first line in the logs shows a the command executed in the pod ?

**Comment by KurtStam** [comment]
@rhuss 

```
$ oc rsh syndesis-server-2-8qbhr
sh-4.2$ echo $AB_JOLOKIA_OFF
false
sh-4.2$ 
```

`exec java -Djava.net.preferIPv4Stack=true -Duser.home=/tmp -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -Xmx306m -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:+ExitOnOutOfMemoryError -cp . -jar /deployments/runtime.jar`

**Comment by rhuss** [comment]
@KurtStam you should unset it completely. Also you probably should remove `AB_OFF`

From the docs:

> AB_JOLOKIA_OFF : If set disables activation of Jolokia (i.e. echos an empty value). By default, Jolokia is enabled.

So even when you set it to `false` its set. Confusing, agreed and this should be changed.

**Comment by KurtStam** [comment]
@rhuss  That seems to change the error at least. I removed both settings and now I'm getting

<img width="673" alt="screen shot 2018-03-19 at 2 59 03 pm" src="https://user-images.githubusercontent.com/35576/37616383-1bc2086a-2b86-11e8-8179-e7e38f6511c1.png">

**Comment by KurtStam** [comment]
Actually it looks like it's started. This is form the log:

> exec java -Djava.net.preferIPv4Stack=true -Duser.home=/tmp -javaagent:/opt/agent-bond/agent-bond.jar=jolokia{{host=0.0.0.0}},jmx_exporter{{9779:/opt/agent-bond/jmx_exporter_config.yml}} -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -Xmx400m -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:+ExitOnOutOfMemoryError -cp . -jar /deployments/runtime.jar
> I> No access restrictor found, access to any MBean is allowed
> Jolokia: Agent started with URL http://172.17.0.4:8778/jolokia/

However it still shows the handshake timeout error.

**Comment by KurtStam** [comment]
@rhuss Can you comment on this? I think we are running into OSFUSE-700 see above ^. If so how do we pull in that fix?

**Comment by rhuss** [comment]
@KurtStam actually, the issue is more complicated (as its a complex setup involving client certs from openshift for which the startup script has dedicated support when setting "AB_JOLOKIA_AUTH_OPENSHIFT" in the base images. See also https://github.com/fabric8io/agent-bond/tree/master/fish-pepper/jolokia
it's a complex beast, I have to look when I have some hour left to spend.
but we should fix this for sure.

even not sure whether the openshift support for this still exists (we need some help from the openshift side for this to work)

sorry for my inertia, but I'm (again) so overloaded, with the code freeze coming *and* having to create a brand new talk for next week's JAX.

**Comment by KurtStam** [comment]
@rhuss 
1.  is ‘fabric8/java-jboss-openjdk8-jdk:1.3.0’ the default base image?
2. is  https://issues.jboss.org/browse/OSFUSE-700 unrelated?
