### ISSUE TITLE
syndesis-db never comes up again on restart

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#2057]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

When `syndesis-db` is stopped for any reason, OpenShift tries to restart it. But it will fail repeatedly todo so. 
The error from the pod's log

```
pg_ctl: another server might be running; trying to start server anyway
waiting for server to start....LOG:  redirecting log output to logging collector process
HINT:  Future log output will appear in directory "pg_log".
 done
server started
ERROR: tuple already updated by self
```

There is no known way how to recover from this state except a **complete reinstallation**

## Tasks involved / Steps to Reproduce

1. Just kill pod `syndesis-db` manually and see what happens

**Comment by KurtStam** [comment]
Seems like in the postStart.sh file an `  EOF` was added with spaces in front of it. Should be fixes with the above PR
