### ISSUE TITLE
Camel EIPs - introduced as step extensions

### ISSUE THREAD

**Issue by honghuac** [syndesisio/syndesis#2061]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Camel EIPs are not available in Fuse Online.

## Expected behavior

Fuse developers working on Fuse Online projects will appreciate the use of Camel EIPs

**Comment by oscerd** [comment]
You may find some of them as extension here: https://github.com/syndesisio/syndesis-extensions

**Comment by gashcrumb** [comment]
Exactly, currently anything not available as steps should be handled via extensions.  As Syndesis matures we'll introduce more EIP patterns, however those EIP patterns need to be presented in a way that makes sense for the citizen user.

If there are specific EIP patterns that you think would be a good inclusion, please open specific issues for each pattern so we can create a user story around them and prioritize accordingly.  Thanks!
