### ISSUE TITLE
PostgresDB Connection yields no available actions

### ISSUE THREAD

**Issue by honghuac** [syndesisio/syndesis#2062]
## This is a...

<pre><code>
[ ] Feature request
[X] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

PostgresDB Connection used to provide a short list of actions: SQL Statement and Stored Procedure.
It no longer does when set as a Finish Connection.

## Expected behavior

PostgresDB Connection used to provide a short list of actions: SQL Statement and Stored Procedure.

## Screenshot

![empty](https://user-images.githubusercontent.com/8625482/37580975-6f7b6686-2b81-11e8-9fec-eaf377ce82f1.png)
![empty2](https://user-images.githubusercontent.com/8625482/37581066-db97b888-2b81-11e8-809a-3b2a55974f41.png)

## Tasks involved / Steps to Reproduce

1. Setup PostgresDB as the Finish Connection in any integration
2. No actions are shown

**Comment by gashcrumb** [comment]
@iocanel 
![fd3](https://user-images.githubusercontent.com/351660/37595887-b6c86ab0-2b50-11e8-9e39-3d346baad788.jpg)

**Comment by KurtStam** [comment]
Can confirm this (Finish only). Seems to be an UI issue since the REST call looks ok to me.

**Comment by gashcrumb** [comment]
Yeah, the PR out of #1993 introduced this, however I'm strongly suggesting that we revert it the more I think about it.

**Comment by iocanel** [comment]
Let's revert that until we find better cirteria to filter out terminal actions.
