### ISSUE TITLE
Advanced Filter - needs to be more user-friendly

### ISSUE THREAD

**Issue by honghuac** [syndesisio/syndesis#2064]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[] Bug report  
[X] Documentation issue or request
</code></pre>

## The problem

On the Configure Advanced Filter page, a huge text field is provided to the user with no documentation of examples of commands.
Some documentation / tool-tips will be helpful in guiding the user in the use of the Advanced Filter.

## Expected behavior

Tooltips / examples of commands to guide the user.

## Screenshot

![delete](https://user-images.githubusercontent.com/8625482/37583381-2a81ecde-2b8c-11e8-83c0-7a6e265984ef.png)

**Comment by TovaCohen** [comment]
@honghuac , how is this for a hint about what to enter:

> Examples of Simple Language filter expressions:
> ${in.header.type} == 'widget' // Evaluates true when type = widget.
> ${in.body.title}                     // Evaluates true when body contains title.

**Comment by TovaCohen** [comment]
Thanks Hong!
Stan, I updated the doc to have this example. 
Can I assign this issue to you (or someone elese?) to insert the hint into the expression input box?
