### ISSUE TITLE
Combine feature and enhancement labels?

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#2068]
Under https://github.com/syndesisio/syndesis/blob/master/doc/sdh/development/labels.adoc#categories we list `cat/feature` and `cat/enhancement`.  I would argue that the difference is too subtle to be important and we should narrow this to just `cat/feature`.  Then issues are generally a bug or a feature (or of course a discussion like this one :-)

+1 or -1?

**Comment by paoloantinori** [comment]
I'd be happy to converge on a single label, but I'm interested in hearing the possible good reason to distinguish between the 2 of them.

**Comment by deeleman** [comment]
Form me `cat/feature` is a brand new functionality, while `cat/enhancement` just entails an improvement over an already existing functionality. As such, the scope and priority of each category might significantly differ depending on the circumstances.

**Comment by gashcrumb** [comment]
Right but I'm not sure if it's really that important of a distinction in terms of filtering, i.e. any feature or enhancement may have significant scope, that's more of a sizing issue which we also have labels for that don't currently get used as much.

**Comment by gashcrumb** [comment]
If nobody objects today I'm going to combine the `cat/feature` and `cat/enhancement` labels, probably to `cat/feature` since our issue template mentions `feature`.

**Comment by kahboom** [comment]
I agree with @deeleman--I think there is a notable difference between the two, if we're wanting to be really honest here, but with epics it can get a bit confusing, as those may be the indication of new features. Perhaps @paoloantinori can chime in here or have the final say?

**Comment by rhuss** [comment]
@paoloantinori the main reason why we have some kind of overlapping labels comes from the migration from mutiple repos to the mono repo: Each repo had its own set of labels, so the initial approach was to migrate to a unification of all labels of all repos. 

That there should be some sort of consolidation (like this issue ;-) was clear from beginning (also stated in the docs that its something 'living')

btw, this might be true for other labels as well.

**Comment by gashcrumb** [comment]
Done!
