### ISSUE TITLE
Moving from prom/prometheus to a support OpenShift image?

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis#2069]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

We are currently depending on `prom/prometheus` docker image for our metrics feature. Should we moved to a RH suppoorted image? OpenShift is using this image, in other places:

- https://github.com/openshift/openshift-ansible/tree/master/roles/openshift_prometheus#openshift-prometheus
-  https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_prometheus/vars/openshift-enterprise.yml
-  https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_prometheus/templates/prometheus.j2#L83 

@kcbabo  do you have visibility on this? Should we reach out OpenShift team to confirm?

## Expected behavior
Using fully supported sw. We are currently using an external image for postgres, but we know that postgres is a sw supported by RH. Is this true also for Prometheus?

cc: @rhuss  , @chirino

**Comment by kcbabo** [comment]
Tom went down this path for Fuse on OpenShift and is using a productized image for Prometheus.  @cunningt - can you provide some insight into which image you are using?

**Comment by rhuss** [comment]
We should be careful to use for the upstream community templates still prometheus images which can be freely pulled.

**Comment by cunningt** [comment]
@kcbabo The APB that we want to use is this -

https://github.com/ansibleplaybookbundle/prometheus-apb

I think this file lays out the images being used there -

https://github.com/ansibleplaybookbundle/prometheus-apb/blob/master/roles/prometheus-apb/defaults/main.yml

**Comment by aileenc** [comment]
Do we still use upstream prometheus in iPaaS product?

**Comment by cunningt** [comment]
I'm not sure.    The APB I was mentioning uses 

registry.access.redhat.com/openshift3/prometheus

https://github.com/ansibleplaybookbundle/prometheus-apb/blob/master/roles/prometheus-apb/defaults/main.yml#L6

vs

docker.io/prom/prometheus:v2.1.0
https://github.com/syndesisio/syndesis/blob/master/tools/ignite-cluster/migrate-images.pl#L173-L174

**Comment by dhirajsb** [comment]
The `registry.access.redhat.com/openshift3/prometheus` image seems to be version aligned with OCP, and has no information on what underlying Prometheus version is used.

**Comment by paoloantinori** [comment]
In our non linear release process, this information is handled at OpenShift template level.

Today I have released templates for productized `1.3.5` and I'm using the versions you are linking:

https://github.com/syndesisio/fuse-ignite-install/blob/1.3.5/resources/fuse-ignite-image-streams.yml#L63

**Comment by dhirajsb** [comment]
@paoloantinori so it looks like that template references the openshift prometheus image https://github.com/syndesisio/fuse-ignite-install/blob/1.3.5/resources/fuse-ignite-image-streams.yml#L79

**Comment by dsimansk** [comment]
I've run our testsuite with `openshift3/prometheus:v3.9` and worked just fine. 

@dhirajsb the binary versions are reported as same, although RH built binary doesn't specify exact commit id.

openshift3/prometheus:v3.9
```
bash-4.2$ /bin/prometheus --version
prometheus, version 2.1.0 (branch: non-git, revision: non-git)
  build user:       mockbuild@x86-041.build.eng.bos.redhat.com
  build date:       20180221-22:56:27
  go version:       go1.9.2
```


prom/prometheus:v2.1.0
```
/prometheus $ /bin/prometheus --version
prometheus, version 2.1.0 (branch: HEAD, revision: 85f23d82a045d103ea7f3c89a91fba4a93e6367a)
  build user:       root@6e784304d3ff
  build date:       20180119-12:01:23
  go version:       go1.9.2
```

**Comment by dhirajsb** [comment]
@dsimansk that's good to know the versions, since pre 2.1 had a bug we had discovered in testing before. Wonder whether it just pulls the binary from upstream or whether we do a full build from source?

**Comment by dhirajsb** [comment]
Closing this if no one has any objections. We can revisit the APB when we want to pull in other Prometheus bits and Grafana at a future date.
