### ISSUE TITLE
Connector validation error message needs to be more verbose

### ISSUE THREAD

**Issue by honghuac** [syndesisio/syndesis#2076]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Validation error message regarding connector configuration is not helpful, it is devoid of any contents.

## Expected behavior

Display a useful validation message.

## Screenshot

![valid-err](https://user-images.githubusercontent.com/8625482/37643315-0f8a61a2-2c5b-11e8-8dff-8119c45b83b9.png)

## Request and Response Data

Populate the fields for a Salesforce Connector Configuration and attempt to validate.

## Tasks involved / Steps to Reproduce

1. Populate the fields for a Salesforce Connector Configuration and attempt to validate.

**Comment by gashcrumb** [comment]
Error response I got when validating:

```
[
  {
    "status": "ERROR",
    "scope": "PARAMETERS",
    "errors": [
      {
        "code": "ILLEGAL_PARAMETER_GROUP_COMBINATION",
        "parameters": [
          "password",
          "userName"
        ],
        "attributes": {
          "GROUP_NAME": "USERNAME_PASSWORD",
          "GROUP_OPTIONS": "clientId,clientSecret,keystore,password,refreshToken,userName"
        }
      },
      {
        "code": "ILLEGAL_PARAMETER_GROUP_COMBINATION",
        "parameters": [
          "refreshToken"
        ],
        "attributes": {
          "GROUP_NAME": "REFRESH_TOKEN",
          "GROUP_OPTIONS": "clientId,clientSecret,keystore,password,refreshToken"
        }
      },
      {
        "code": "ILLEGAL_PARAMETER_GROUP_COMBINATION",
        "parameters": [
          "keystore",
          "userName"
        ],
        "attributes": {
          "GROUP_NAME": "JWT",
          "GROUP_OPTIONS": "clientId,keystore,password,refreshToken,userName"
        }
      }
    ]
  }
]
```

@zregvart @rhuss I feel like we need to rework the error response for validation here, the error response object isn't something the UI can turn around and show to the user, and to be honest I don't see how I can turn this response into a usable message that the user can understand.

**Comment by gashcrumb** [comment]
Also I kinda recall that you used to be able to just supply the client ID and secret (which gave me the above response when clicking validate) and this would validate just fine, so wonder if there's a couple issues showing up here.  If someone from the backend can confirm then we should raise a second issue for that.

**Comment by gashcrumb** [comment]
@honghuac also normally for salesforce or twitter you'd put your credentials into the oauth client config under `Settings`, but for reasons this method should work too.  We have https://github.com/syndesisio/syndesis/issues/2013 open already for maybe showing a message for this

**Comment by gashcrumb** [comment]
@paoloantinori Actually on the fence if this is a blocker or not, given that normally you'd set your oauth creds on the Settings page.  WDYT?

**Comment by zregvart** [comment]
> @paoloantinori Actually on the fence if this is a blocker or not, given that normally you'd set your oauth creds on the Settings page. WDYT?

yeah :+1: on this, solution for this would change the API, not sure if we wan't to do it, and it has been like this for validation of connection parameters for ages and never got addressed. Though I would like to change that API :smiley:

**Comment by gashcrumb** [comment]
Yeah, we'd have to handle it across the stack for sure.  My feeling is this should be fixed for GA.

Ideally we should start by just making the validation message fit the same error API response as the rest of the app uses, we can improve upon it in subsequent releases as needed.

**Comment by paoloantinori** [comment]
I'm tempted to say it's not really a blocker, since we have alternate paths to get the same result.

**Comment by zregvart** [comment]
With #2492 the Salesforce connector connection creation when not setup with OAuth settings doesn't display refresh token field and all properties are required. This makes the Validate button disabled making illegal parameter combinations a non-issue.
Now if the user fills in values that are not valid a verbatim Salesforce error will appear. This looks like:
![screenshot-2018-4-27 syndesis - development 1](https://user-images.githubusercontent.com/1306050/39363050-2665dff0-4a29-11e8-925a-569a2b8e77f1.png)
I think this makes this issue bearable and removes the need for an API change. I would move this issue to 7.1 and rethink the API and the way we generate errors from the `meta`.
