### ISSUE TITLE
Drill-down into errors - Integration Summary (Metrics tab)

### ISSUE THREAD

**Issue by honghuac** [syndesisio/syndesis#2078]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Documentation issue or request
</code></pre>

## The problem

There is no way to drill down into the root of the errors observed from the metrics tab in the Integration Summary page.

## Expected behavior

A little more drill down will be appreciated. Maybe tracing capabilities too?

## Screenshot

![verbose-err](https://user-images.githubusercontent.com/8625482/37644035-6543ba06-2c5d-11e8-9442-312c4827c233.png)

**Comment by gashcrumb** [comment]
So basically link from the error indicators to the `activity` tab and ideally filter for errors?

Will require implementing https://github.com/syndesisio/syndesis/issues/1912 first

**Comment by honghuac** [comment]
@gashcrumb Yes, and any errror message should be shown (preferably a condensed version of the pod log)

**Comment by deeleman** [comment]
> Will require implementing #1912 first

That is a quickie, but scrolling the user to the first error match is a different kind of beast I'm afraid
