### ISSUE TITLE
[Feature Request] Version switching of Integrations - Integration Summary

### ISSUE THREAD

**Issue by honghuac** [syndesisio/syndesis#2079]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Versions of integration should be switchable. That will be truly add an element of flexibility and control customers need.

## Screenshot

![verbose-err](https://user-images.githubusercontent.com/8625482/37644191-f4e3705c-2c5d-11e8-9574-d8fe7ec98aea.png)

## Tasks involved / Steps to Reproduce

1.
2.
3.
4.

**Comment by gashcrumb** [comment]
This is a duplicate of #1880
