### ISSUE TITLE
Basic Filter UI

### ISSUE THREAD

**Issue by michael-coker** [syndesisio/syndesis#2091]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
* no placeholder text for property name
* condition dropdown has empty options
* field hint/description wraps beside input
* multiple rows wrap weird (floating issues)

## Expected behavior

* placeholder for property name should be "Property name"
* dropdown shouldn't have empty options
* hint should display below input
* rows should wrap properly

## Screenshot
![screen shot 2018-03-20 at 5 22 01 pm](https://user-images.githubusercontent.com/35148959/37685927-59cbb9ac-2c63-11e8-9e61-4c1ed62ed5a8.png)

## Tasks involved / Steps to Reproduce

1. Create/edit integration
2. Add step
3. Choose "Basic Filter"
4. profit!

cc @dongniwang

**Comment by dsimansk** [comment]
@paoloantinori could we increase a priority on this issue to make sure it'll get next 1.3.x tag?
