### ISSUE TITLE
[Solution to problem] Server Pod restart problem - insufficient JVM heap

### ISSUE THREAD

**Issue by honghuac** [syndesisio/syndesis#2092]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Documentation issue or request
[X] Solution
</code></pre>

## The problem

Server Pod restarts numerous times. The problem is due to: the JVM exceeded its heap quota.
The quota / ratio should be set to at least 80%.

The fix is found here:
https://github.com/gpe-mw-training/syndesis/commit/a6f4ab08f1e111f9b5d09c28c775baa67f2add7a
Specifically:
`name: JAVA_MAX_MEM_RATIO`
`value: 80`

## Expected behavior

Server Pod does not reload / restart.

**Comment by rhuss** [comment]
We have to deal with an considerable amount of non-heap memory, so 80% is for sure too larger. The general recommendation is 50% but might get low as 40%. So changing the ratio alone is very likely not sufficient.

**Comment by gashcrumb** [comment]
Thanks for the fix suggestion!  This is still being investigated and as @rhuss has said this may not be a suitable fix.  Let's continue tracking this in #2027
