### ISSUE TITLE
Default for sql query period seems inappropriate

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#2093]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Currently the default suggested as "1000 ms"

![image](https://user-images.githubusercontent.com/99080/37698292-59b7c080-2ce2-11e8-9eb6-57c68b8f6d60.png)

* Instead of "1000 ms" i suggest "1 s" which feels more natural
* But: I would suggest a much higher period as default, maybe 10s or even 1 minute to avoid creating unnecessary load by default. My favorite: 1 minute

**Comment by rhuss** [comment]
Actually I would even remove milliseconds as options alltogether (who want to repeat an sql query every 1 ms or even every 500ms ?)

**Comment by lburgazzoli** [comment]
The sql component only sets the default value but not the unit, see: https://github.com/syndesisio/syndesis/blob/master/app/connector/sql/src/main/resources/META-INF/syndesis/connector/sql.json#L171

Maybe we need an additional property `unit` to be added to the definition.

**Comment by KurtStam** [comment]
@lburgazzoli We can simply change the default value (for example `10`) in the sql.json and have the UI default to seconds?

**Comment by lburgazzoli** [comment]
Of course but as long term solution we should be able to set the unit imho

**Comment by KurtStam** [comment]
Longterm it should also support setting a minimum value. For now we can safeguard connector.

**Comment by KurtStam** [comment]
@gashcrumb I've set the default to 60000 milli-seconds. Maybe you can set the default time unit to seconds in the widget?

**Comment by gashcrumb** [comment]
It should already do that and with the linked PR it'll also use the higher unit, so 1000ms would show up as 1s.
