### ISSUE TITLE
Initial refresh of activities after publishing

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#2094]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

When doing an initial publish and then switch to the activity log after it has been published, the list empty.

The user is forced to press the "Refresh" button to get the list.

![image](https://user-images.githubusercontent.com/99080/37698473-70ca4f44-2ce3-11e8-9be5-baae17017f34.png)

## Expected behavior

Either an initial list should be already fetched when switching to the tab or the button should be called initially "Fetch" and not "Refresh".

**Comment by amysueg** [comment]
UXD has discussed this and we agree that the list should refresh simply by switching to the "Activity" tab. No button press should be required. Removing notif/uxd label.

**Comment by deeleman** [comment]
A quick tweak on the component has been pushed that accommodates the desired functionality and ensures that already fetched records are not wiped out on every new render of the activity component.
