### ISSUE TITLE
Missing log entries

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#2095]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

For an periodic sql query integrations start point with a period of 5 secondes, there seems some entries missing at the start:

![image](https://user-images.githubusercontent.com/99080/37698704-4cd37b78-2ce4-11e8-9cf1-30f5d030124a.png)

Note that 10s distance between the first three entries. After this, period is always 5 seconds as it should be.

**Comment by KurtStam** [comment]
@rhuss it is set to wait 10 seconds before the timer starts. Should I change it to 0 seconds?

**Comment by KurtStam** [comment]
`docker log <your-integration-container-id> -f -t` shows the messages with a timestamp i.e:

> 2018-04-18T21:14:21.440079480Z {"exchange":"i-LAPav_x8Vo-tFZ3k3n7z","step":"-LAJKUU9aO0To1Em-4ir","id":"i-LAPav_y8Vo-tFZ3k3nAz","duration":797732}
> 2018-04-18T21:14:21.440111814Z {"exchange":"i-LAPav_x8Vo-tFZ3k3n7z","status":"done","failed":false}
> 2018-04-18T21:14:22.438620483Z {"exchange":"i-LAPavpa8Vo-tFZ3k3nCz","status":"begin"}
> 2018-04-18T21:14:22.442692899Z {"exchange":"i-LAPavpa8Vo-tFZ3k3nCz","step":"-LAJKSLtaO0To1Em-4ir","id":"i-LAPavpa8Vo-tFZ3k3nDz","duration":3995601}
> 2018-04-18T21:14:22.444198416Z {"exchange":"i-LAPavpa8Vo-tFZ3k3nCz","step":"-LAJKUU9aO0To1Em-4ir","id":"i-LAPavpe8Vo-tFZ3k3nFz","duration":1397562}
> 2018-04-18T21:14:22.444244181Z {"exchange":"i-LAPavpa8Vo-tFZ3k3nCz","status":"done","failed":false}
> 2018-04-18T21:14:23.439539739Z {"exchange":"i-LAPaw4D8Vo-tFZ3k3nHz","status":"begin"}
> 2018-04-18T21:14:23.441009931Z {"exchange":"i-LAPaw4D8Vo-tFZ3k3nHz","step":"-LAJKSLtaO0To1Em-4ir","id":"i-LAPaw4E8Vo-tFZ3k3nIz","duration":1200427}
> 2018-04-18T21:14:23.441282034Z {"exchange":"i-LAPaw4D8Vo-tFZ3k3nHz","step":"-LAJKUU9aO0To1Em-4ir","id":"i-LAPaw4F8Vo-tFZ3k3nKz","duration":705550}
> 2018-04-18T21:14:23.441294654Z {"exchange":"i-LAPaw4D8Vo-tFZ3k3nHz","status":"done","failed":false}
> 2018-04-18T21:14:24.439724961Z {"exchange":"i-LAPawJq8Vo-tFZ3k3nMz","status":"begin"}
> 2018-04-18T21:14:24.441463448Z {"exchange":"i-LAPawJq8Vo-tFZ3k3nMz","step":"-LAJKSLtaO0To1Em-4ir","id":"i-LAPawJq8Vo-tFZ3k3nNz","duration":2095449}
> 2018-04-18T21:14:24.442517585Z {"exchange":"i-LAPawJq8Vo-tFZ3k3nMz","step":"-LAJKUU9aO0To1Em-4ir","id":"i-LAPawJs8Vo-tFZ3k3nPz","duration":1209931}
> 2018-04-18T21:14:24.442548244Z {"exchange":"i-LAPawJq8Vo-tFZ3k3nMz","status":"done","failed":false}

So there /is/ a msg every second. However the Activity logging misses the message at 5:17:22
<img width="807" alt="screen shot 2018-04-18 at 5 26 01 pm" src="https://user-images.githubusercontent.com/35576/38959226-d1080c2e-432d-11e8-9789-30d5fbae6b0f.png">

So it's not just a startup issue.

**Comment by chirino** [comment]
@KurtStam what's the integration that can reproduce this?

**Comment by chirino** [comment]
I just discovered that one of my log parsing assumptions was wrong.  I assumed that all log entries from the API server started with a fix length time prefix that looked like:

    2018-01-12T21:22:02.068338027Z { ..... }

Turns out that that time prefix is actually variable length.

**Comment by rhuss** [comment]
@chirino was it because of this ? --> https://github.com/syndesisio/syndesis/pull/1054#pullrequestreview-90576877 e.g. that you expect "{" at a fixed position ? Couldn't we use some precompiled regexp which could be much more flexibel ?

**Comment by chirino** [comment]
@rhuss exactly.  That's the strategy I'm going with now.
