### ISSUE TITLE
Integration published state is incorrect

### ISSUE THREAD

**Issue by honghuac** [syndesisio/syndesis#2097]
## This is a...

<pre><code>
[ ] Feature request
[X] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Using the master branch code (dated March 21st), the integrations I now create do not reflect the correct publish status. Integration is indicated as not published, when it is actually active and working fine.

## Expected behavior

State of integration needs to be synchronized with its active / dormant state.

## Screenshot

![pub-bug](https://user-images.githubusercontent.com/8625482/37703221-e521b6c4-2d2f-11e8-961c-ab626a8bb7b8.png)

**Comment by gashcrumb** [comment]
Not sure if it's backend or frontend, needs to be verified...

**Comment by iocanel** [comment]
I just merged some related commits, that could possibly fix this issue too. As I haven't been able to reproduce it, can you please check against the latest master?
