### ISSUE TITLE
Cannot create connection if connectors has no options

### ISSUE THREAD

**Issue by nicolaferraro** [syndesisio/syndesis#2103]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

I tried to create a connection from a connector (created from a extension) that has no option. Apart from the fact that connections should be auto-created if the connector has no options (but this has to be discussed), now I cannot create a connection because code in the ui ([here](https://github.com/syndesisio/syndesis/blob/34080b96b7dc8e9d09b6549c85d20e46ed20ed3c/app/ui/src/app/connections/create-page/current-connection.ts#L253)) assumes that `properties` is defined in the connector, but it's not in this case.

## Expected behavior
Connections should be created successfully from connectors without properties to configure.

## Screenshot

N/A

## Request and Response Data

N/A

## API Endpoints and Schemas

N/A

## Tasks involved / Steps to Reproduce

1. Build the syndesis-extension repo (`mvn clean install`)
2. Import the webhook (or timer) extension jar (from the target dir) using syndesis ui
3. Go to connections and create a connection from the webhook (or timer) connector
4. In the review page, write down a name and click on "Create"
5. A "null-reference" error appears in the console

**Comment by gashcrumb** [comment]
@nicolaferraro do you have that extension handy for me to test with btw?

**Comment by nicolaferraro** [comment]
For you: https://www.dropbox.com/s/yu4aute772xggiu/syndesis-connector-webhook-1.0.0.jar?dl=0
