### ISSUE TITLE
Run QE tests on against Alpha releases of OpenShift 3.9

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis#2106]
## This is a...

<pre><code>
[*] Task
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
We should QE test Syndesis against the latest available openshift 3.9 release, like: https://github.com/openshift/origin/releases/tag/v3.9.0-alpha.3 to see if it introduces any regressions for us. And we can report them to openshift community before the 3.9 release is finalized.

**Comment by chirino** [comment]
We should likely figure out how to automate doing continuous integration testing against the next alpha of OpenShift when available.  Like

**Comment by dsimansk** [comment]
I've tried smoke test on our internal instance, that is running `v3.9.4` (should be latest available). So I've spotted any regression infra deployment, s2i build and integration deployment passed smoothly.

**Comment by aileenc** [comment]
Did you mean NOT spotted any regression?

**Comment by dsimansk** [comment]
Sorry, yes I meant NOT spotted.
