### ISSUE TITLE
Integration list page UI

### ISSUE THREAD

**Issue by michael-coker** [syndesisio/syndesis#2118]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
* There is no padding at the top of the list in FF (screenshot)
* CSS can be cleaned up and can utilize the scrollable body helpers

## Expected behavior
* List needs padding in FF
* CSS should utilize helpers

## Screenshot
![screen shot 2018-03-21 at 4 21 18 pm](https://user-images.githubusercontent.com/35148959/37738140-119a75c6-2d24-11e8-886e-3958aba7f223.png)

**Comment by gashcrumb** [comment]
Actually I did raise #521 ages ago but we can track this here, I'll close this old issue.
