### ISSUE TITLE
Page redirection after technical extension creation

### ISSUE THREAD

**Issue by honghuac** [syndesisio/syndesis#2121]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Currently page redirection of the console, after successful import of tech extension, leads to the _Extension Import_ page .

## Expected behavior

 It should be redirecting to the Extensions landing page instead: **https://host.name/customizations/extensions**

**Comment by gashcrumb** [comment]
I'm not seeing this behavior here, when I drag an extension jar onto the page it's uploaded and staged, clicking import then brings me to the extension detail page for the newly imported extension.  Can you maybe clarify by copying the sequence of URLs you're seeing, or a quick screencast?

**Comment by dsimansk** [comment]
> I'm not seeing this behavior here, when I drag an extension jar onto the page it's uploaded and staged, clicking import then brings me to the extension detail page for the newly imported extension. 

Imho the OP refers to the exact behaviour, that it would make a bit more sense to redirect to `Extensions List` page rather newly create extension's detail.

**Comment by gashcrumb** [comment]
Right, so going to the detail page is by design, it's in keeping with creating an integration, and creating a connection is currently really an outlier.
