### ISSUE TITLE
[Api connector] Created connection data missing when related connector deleted 

### ISSUE THREAD

**Issue by mastepan** [syndesisio/syndesis#2123]
## Steps to Reproduce

1. create a new custom connector
2. create a new connection from the connector
3. delete the connector

- the connection detail can't be opened 
- there is also missing icon on the connection card
- the connection can't be used in a new integration - it is not displayed in a list of available connections when creating an integration

It seems that if you delete a connector, then you lose all data of related connections.

The topic discussed in: https://github.com/syndesisio/syndesis/issues/1827
Fix causing the issue (probably): https://github.com/syndesisio/syndesis/pull/1958

**Comment by gashcrumb** [comment]
If you delete a connector then most likely all connections using that connector should be cleaned up too, as a connection with no connector is pretty useless.

**Comment by deeleman** [comment]
> If you delete a connector then most likely all connections using that connector should be cleaned up too, as a connection with no connector is pretty useless.

Exactly.

> Fix causing the issue (probably): #1958

Probably... NOT. That issue just gives visibility from an UI POV to a button that was already there. Such button initiates a delete action which was already available there as well. At that stage, the UI just sends a request to the backend and all the business logic is processed there. 

In a nutshell, whatever logic is needed, it must happen in the backend once you guys agree, for once and for all, on what would happen with the connections that depend on a connection that has been deleted (provided such deletion should be allowed).

That delete button was created according to the original UX provided, then [removed upon your request](https://github.com/syndesisio/syndesis/issues/1442), just to be [reinstated soon after that upon your request too](https://github.com/syndesisio/syndesis/issues/1827). The underlying business logic required was outside the scope of the original request and hence of #1958.

Ultimately, this is not a UI issue I'm afraid, the application does not persist any connection information (so making any particular connection available after deleting it's related connector is outside the scope of the UI capabilities) and should be scalated to the backend team.

**Comment by mastepan** [comment]
> Probably... NOT. That issue just gives visibility from an UI POV to a button that was already there.
I understand but you have added a warning that doesn't correspond with reality now. Therefore I consider this as a bug.

That means we didn't get the solution idea same way. First we need to clearly define required scenario for all of us to understand it in https://github.com/syndesisio/syndesis/issues/1827

**Comment by zregvart** [comment]
If this is still under discussion can we remove `cat/bug` and `prio/p1` labels?

**Comment by paoloantinori** [comment]
I think it makes sense to keep filing this as a bug, since according to current workflow it is one.
Not necessarily something we are going to address if decide to stop supporting this behavior.

**Comment by zregvart** [comment]
IIRC the current behaviour is that if a API connector is deleted any connection related to that connector will be deleted.
