### ISSUE TITLE
[Api connector] Delete connector button disabled when any related connection being used in an integration

### ISSUE THREAD

**Issue by mastepan** [syndesisio/syndesis#2124]
As it was discussed in https://github.com/syndesisio/syndesis/issues/1827 the Delete button should be enabled even if any related connection is being used in an integration.

Current warning displayed when deleting a connector doesn't correspond with current state.
It had been agreed the warning is ok.
It should be only possible to delete connectors anytime without consequences on running integrations.

I think this may be fixed after: [Api connector] Created connection data missing when related connector deleted https://github.com/syndesisio/syndesis/issues/2123

**Comment by gashcrumb** [comment]
From a data integrity point of view I fail to see how this behavior makes any sense, but then I'm coming in halfway through the conversation.  But basically it seems like we're saying it's okay to have a runtime artifact deployed but not have any view of it in the UI.  Huh?

**Comment by deeleman** [comment]
> Current warning displayed when deleting a connector doesn't correspond with current state.
It had been agreed the warning is ok.

Please elaborate on this.

**Comment by mastepan** [comment]
> Please elaborate on this.
It's not meant as my task I suppose. Just making a note to be sure you aren't waiting for me.

> But basically it seems like we're saying it's okay to have a runtime artifact deployed but not have any view of it in the UI
That's halfway solution agreed for it's supposed simplicity.

Then the scenario requires a review.
@gashcrumb @deeleman Could you continue on that with other people ...maybe in https://github.com/syndesisio/syndesis/issues/1827 ?
or maybe somehow follow the new workflow @paoloantinori and others let us know about last week? I'm not sure how to implement the workflow now with this issue.
Thanks

**Comment by paoloantinori** [comment]
Hi @mastepan can you help us understand what do you mean by this sentence:
> Current warning displayed when deleting a connector doesn't correspond with the current state.
It had been agreed the warning is ok.

Also, you'd like to know about details on which new workflow that it's supposed to have happened last week? I'm not sure what you are referring to.

**Comment by mastepan** [comment]
@paoloantinori yes, I meant that what warning says now is not true. If you delete a custom connector it breaks connections created from that and Integrations using this connection probably too.

Workflow I'm referring to:  New workflow for new UX features and enhancements

Solving this issue means decision how things should work. It's not simple clear fix. I suppose that this should decide someone else than I by writing new version of the warning dialog.

I'm not sure that it's all what you needed to know...please tell me if you have any further questions.

**Comment by zregvart** [comment]
If this is still under discussion can we remove `cat/bug` and `prio/p1` labels?

**Comment by mastepan** [comment]
We should definitely solve this. Can anyone have a look at it?

**Comment by zregvart** [comment]
@mastepan I only see the discussion concerning the `Delete` button, and under what circumstances should it be enabled or not. I don't see a conclusion that would make this actionable, so any solution implemented for this would introduce further discussion about the same.
That doesn't mean that the issue does not exist, but from what I understand there is no consensus on this and no solution to be implemented here.

**Comment by mastepan** [comment]
@zregvart We all can find what is wrong and what must be fixed. The only thing is how, because there was probably a miscommunication. And maybe twice, because noone has come with any solution.

@paoloantinori, @deeleman or anyone can you push this to get it finished soon please?

possible solutions:

- A) align the warning text with the reality - integrations and connections can break when api connector deleted

- B) fix the behaviour that breaks integrations and connections when api connector deleted (strongly preferred from user's perspective)

I can only say I am for B, other technical and other details and feasibility are up to the others.

Please discuss warning message with UX team. I only helped to tune it if we thought we knew the right scenario.

Thanks and sorry for an unclear communication recently if there was any.

**Comment by gashcrumb** [comment]
@sjcox-rh @dongniwang FYI

There's been way to much discussion on this button :-)

My take is it shouldn't be possible to delete a connector object from the DB when it's in use, that kind of behavior will run us into data integrity issues, i.e. the connection can't be edited, the integrations can't be edited after doing this etc.

Also I think ultimately we should close all the issues that have been opened on this and when we figure out exactly what the button should do and if it should be enabled/disabled/visible whatever let's open a new issue that spells out what needs to be done.

**Comment by mastepan** [comment]
@gashcrumb closing the current issues will cause nobody will do anything. I feel the problem is there is nobody who would say let's do it this or that way. All of us only say own opinions and that's all...
I can see the user's perspective but honestly I don't know the idea behind connectors, connections and integrations so I can't decide if it makes sense to allow connector removal or if it doesn't.

Could you lead the discussion? Everything is better than leaving it in the current state I think :) And yes, It's way too long already but we need to finish it at least somehow...

**Comment by michael-coker** [comment]
Looks like this was resolved in https://github.com/syndesisio/syndesis/issues/2594
