### ISSUE TITLE
Migrate to Camel 2.21.0

### ISSUE THREAD

**Issue by oscerd** [syndesisio/syndesis#2125]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

Actually on master we are still using camel 2.20.1, we need to migrate.

**Comment by lburgazzoli** [comment]
p0 as fuse build uses 2.21.x already, see: https://github.com/syndesisio/syndesis/blob/syndesis-1.3.3.fuse-000001/app/pom.xml#L71
