### ISSUE TITLE
Activity Log Steps name are invalid for older integration versions.

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis#2130]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
ActivityLog step ids are specific to a given version of an activity.  The Activity log list can have activities from multiple versions of the integration.  Instead of using the current integration's definitions of what the steps are, it should use the integrations at the version specified in the activity to map the step ids. 

The logic that needs updating is here:
https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/integration/integration_detail/integration_activity/integration-activity.component.ts#L60

## Steps to reproduce:

1) Run an integration, have it generate some activity.
2) edit the integration and replace steps with new steps.  Run the new version of the integration, generate some activity.  
3) View integration Activity, new activity will display correctly, old activity will no since it's steps have been removed in the current integration.

**Comment by deeleman** [comment]
AFAIK (and correct me if I'm wrong) the frontend does not persist a history of previous versions of a given integration, so we cannot just simply fetch a given activity, grab its matching integration from a pool of previous integration snapshots and correlate its step names with the activity step ids. That is why, after banging my head against the wall for hours trying to wrap my head around  that convoluted schema definition that integrations feature now, with information scattered across many different models, I've attempted to correlate each activity with its matching integration deployment based on version and then fetch the steps information from each one and extract the name out of each step with a matching id with the activity id.

Result: no ids seem to match, at least in my working environment, so all steps are then rendered as `n/a`.

Please refer to the PR linked above for details.
