### ISSUE TITLE
Support sending optional query params in ApiHttpService's setEndpointUrl method

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis#2132]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
There are APIs which support optional query parameters.  For example all entity listing APIs support pagination control via query parameters.  

We need a way the UI pass these to the APIs when needed.  Keep in mind the query parameters keys and values should be URL encoded and that query keys are allowed to repeat.  Like:

/api/somepath?id=1&id=2&id=3

**Comment by chirino** [comment]
This blocks implementing pagination for #1597

**Comment by gashcrumb** [comment]
It's possible to just pass a direct URL string to the API http service too, but it'd be nice not to have to muck with query params.  I kinda think a nice easy way would be to add any parameters that aren't specified in the URL template as query params in the URL, so for example if I do:

```
apiHttpService.setEndpoint('/foo/{blah}/stuff', { blah: 'hi', id: ['one', 'two', 'three'] }).get();
```

The URL string would be:

```
/foo/hi/stuff?id=one&id=two&id=three
```

**Comment by chirino** [comment]
@gashcrumb, I like that. Hopefully it can also deal with non-array types too like in the 'other' param in this example:

```
apiHttpService.setEndpoint('/foo/{blah}/stuff', { blah: 'hi', id: ['one', 'two', 'three'], other:'test' }).get();
````
The URL string would be:
```
/foo/hi/stuff?id=one&id=two&id=three&other=test
```

**Comment by gashcrumb** [comment]
Yup, attached PR can do that too...
