### ISSUE TITLE
Property name for `Persistent` option on AMQP and ActiveMQ connectors

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis#2140]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

This is in fact a trivial mismatch that has no functionality impact, but it's rather annoying. Property name is reflected in the HTML form as id and therefor may cause problem during automated testing.

Would there be any side-effects of aligning towards `persistent` name only? 

https://github.com/syndesisio/syndesis/blob/55f6777445e6e66cb8912468a551a0d4e2be1b98/app/connector/activemq/src/main/resources/META-INF/syndesis/connector/activemq.json#L209

https://github.com/syndesisio/syndesis/blob/55f6777445e6e66cb8912468a551a0d4e2be1b98/app/connector/amqp/src/main/resources/META-INF/syndesis/connector/amqp.json#L209

**Comment by paoloantinori** [comment]
hi @KurtStam how come the triage label has been added back?
can you add some comment if you are planning activities on this?
