### ISSUE TITLE
Updating an existing connection causes a 404 response

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#2146]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Changing a parameter on an existing connection and saving it causes an HTTP 404 error response.  The changes are still saved at least.

## Expected behavior

Normally this should return HTTP 200.

## Request and Response Data

request URL -> `https://syndesis.192.168.1.127.nip.io/api/v1/connections/i-L8DquY4w78OtY_k1OK-z`

response from the PUT request
```
{
  "errorCode": 404,
  "userMsg": "Please check your request data",
  "developerMsg": "Entity Not Found Exception Integration Optional[i-L8D3Q3rw78OtY_k1OJsz] has been deleted"
}
```

## Tasks involved / Steps to Reproduce

1. Open the browser dev console and go to the network tab.
1. Create a connection, I guess maybe use it in an integration
1. Go to the connection detail page
1. Click 'Edit' and change a parameter
1.  Click 'Save'

If that doesn't do it, try deleting the integration and create a new one using the same connection, then go back and update the connection again.  It could be this occurred because I've used this connection in integrations that I've since deleted.

**Comment by KurtStam** [comment]
@gashcrumb I can not reproduce this. I tried editing the exiting DBConnection.

**Comment by gashcrumb** [comment]
This might have been a development quirk, if you can't reproduce it let's close it.
