### ISSUE TITLE
Implement connection configuration changed indicator for integration list.

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#2148]
## This is a...

<pre><code>
[ x ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

When a connection object is updated, integrations need to be updated accordingly.  While we have the inline notification for the integration detail page, we need to still add the indicator on the integration list page.

Created from #1695

## Screenshot

Relevant design:

![integrationlist](https://user-images.githubusercontent.com/351660/37849790-60fb4c76-2eaf-11e8-8fd3-b7ad4e9ec754.png)

@sjcox-rh dude, this design is ancient :-)

## API Endpoints and Schemas

Currently an integration overview has a `messages` attribute which contains update messages when one or more connections used by an integration is updated.

**Comment by sjcox-rh** [comment]
@gashcrumb oh dear yes it is.  When working on the import/export flow, we accounted for messaging on the integration list page when connections needed to be configured. 

Would that indicator work for this use case as well? Sounds similar.

![importlistalternate](https://user-images.githubusercontent.com/16257540/37921061-870c4264-30dd-11e8-8f1b-5cc5946acac4.png)

I need to update the integration list page design, thanks for the reminder!
