### ISSUE TITLE
Implement alert area on connection card in connection list page

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#2149]
## This is a...

<pre><code>
[ x ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

When a connector is updated it may contain new fields or changes that require the user to reconcile the current connection configuration.  On this list page this is done via an inline notification on the connection card.

Created from #1695 

## Screenshot

![connections](https://user-images.githubusercontent.com/351660/37849964-0085890a-2eb0-11e8-85d7-a0b49727e933.png)

## API Endpoints and Schemas

This is driven by information in the `board` attribute of a connection object now, will fill in the schema better in a few.

**Comment by michael-coker** [comment]
@gashcrumb not that I'm aware. It looks like a standard `.alert-warning` alert with custom positioning inside of the card.

**Comment by gashcrumb** [comment]
This gets challenging when the user opts to have a long description too:

<img width="391" alt="screenshot 2018-03-27 10 00 50" src="https://user-images.githubusercontent.com/351660/37972210-d181a9ba-31a5-11e8-9889-fde1ca156d03.png">

**Comment by gashcrumb** [comment]
@michael-coker think you could figure out a good solution for this on #2160?  I can send you some test extensions to trigger the message though it'll also require doing a rebuild.  Otherwise I can merge the linked PR as a first effort and we can revisit the styling later...

**Comment by michael-coker** [comment]
@gashcrumb yep, I can look at it on Thursday/Friday when I get back. To support the current design for this, it seems like the space for the error message should be reserved in the card even when it isn't shown, so that when it is shown, it doesn't change the current and surrounding card heights, since all of the cards are the same height. Does that sound right @sjcox-rh?

**Comment by gashcrumb** [comment]
@michael-coker awesome, thanks!  I'll merge what's there, then you can just create a new PR for the layout adjustments.

**Comment by sjcox-rh** [comment]
@michael-coker yeah I think that would be the best way to handle the situation to avoid the above issue with longer descriptions. Thanks!
