### ISSUE TITLE
Implement inline notification area for connection detail page if there's messages for a connection

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#2151]
## This is a...

<pre><code>
[ x ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Created from #1695 

When a connection object has messages these need to be displayed to the user via an inline notification, for example if the connection's configuration needs to be updated.

## Screenshot

TBD hopefully @dongniwang @sjcox-rh 

## API Endpoints and Schemas

This is driven by the same `board` attribute on the connection object as the list page

**Comment by sjcox-rh** [comment]
@gashcrumb yup I'll work on this one.

**Comment by gashcrumb** [comment]
@lburgazzoli doesn't seem like if I fetch a connection by id that the `board` attribute comes back, unlike when fetching all connections.  Would it make sense to just inline it for this response also?

**Comment by lburgazzoli** [comment]
@gashcrumb That's ok with me

**Comment by lburgazzoli** [comment]
@gashcrumb with #2165

**Comment by gashcrumb** [comment]
@lburgazzoli thanks!

I'm looking at how the messages are constructed when I add/remove fields from the connection.  I feel like using metadata to indicate fields that have been added/removed is kinda too fine-grained at this stage.  Would it make more sense to kinda stick with a more generic leveled message for now for this?  Kind of like what's there for integrations, currently in the designs it's a pretty generic message, and I'm not sure also when `errors` or `warnings` on a connection would be emitted and what form they'd come in if so.

Ideally for the connection detail page as a first pass I'd kinda like to stick with a similar block to -> https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/integration/integration_detail/integration-detail.component.html#L51-L68

**Comment by lburgazzoli** [comment]
@gashcrumb no problems with me, just tell me what do you want me to set in as messages :)

**Comment by gashcrumb** [comment]
@TovaCohen hey, you'll have opinions on this!  :-)

What would be a good message to display on the connection detail page when the connection definition has been updated and there's changes to the available parameters on the configuration form?  In this case action may or may not need to be taken by the user.

**Comment by gashcrumb** [comment]
@lburgazzoli do we know what would constitute an error or warning in this case?  Or should we just focus on this information message to start with and worry about those other cases in the future?

**Comment by lburgazzoli** [comment]
At the moment the messages level is quite opinionated as I've decided the level :) 
Basically and update of a property is considered as an info, a deletion or an additional of a mandatory field is considered as warning but that can be changed. I can also generate a single warning message and state that something has changed (maybe we can define some error code so the ui is free to set the right text)

**Comment by gashcrumb** [comment]
@lburgazzoli that behavior makes sense to me.  I kinda feel like in general only one message needs to be shown in general based on severity, i.e. if a property was updated but also some mandatory field was added we only really need to warn about the mandatory field as that would cause the user to look at the configuration.  @sjcox-rh @dongniwang thoughts?

**Comment by TovaCohen** [comment]
I hate being vague :-(  But how about this:
There are parameter updates for this connection. Click **Edit** to update parameter settings.

**Comment by lburgazzoli** [comment]
@gashcrumb can we define a code to identify this ? feel free to suggest it :)

**Comment by gashcrumb** [comment]
@lburgazzoli do we have any kind of status codes defined anywhere?  Otherwise we might as well just start at 1 :-)

**Comment by lburgazzoli** [comment]
A generic SYNDESIS-001 ?

**Comment by gashcrumb** [comment]
Might as well!

**Comment by sjcox-rh** [comment]
Sorry for the delay, but here is a screenshot of how the inline notification would appear on the connections details page. I inputted the suggested text from Tova.

![connectordetails](https://user-images.githubusercontent.com/16257540/37996986-6c40186a-31ce-11e8-9184-0d005d0a4272.png)

Should I submit a PR for this or input it into the design tracker?

**Comment by TovaCohen** [comment]
Thanks SJ!
What does "Re-initiate Connection" do?
What does "Deauthenticate Connection" do?

**Comment by TovaCohen** [comment]
@gashcrumb and @lburgazzoli  - in the message that says that OAuth authentication is currently active

If the user clicks "Re-initiate Connection" , what does Syndesis do? Why should the user click this button?
If the user clicks "Deauthenticate Connection", what does Syndesis do? What happens to any running integrations that are using this connection? Why would the user do this?

Thanks!

**Comment by gashcrumb** [comment]
@TovaCohen Those buttons aren't in the app currently I believe, in fact the actual connection detail page is pretty far from this design.

But if they were in there, 're-initiate connection' would really be for retrieving a new authentication token from the oauth provider for that connection.  And 'deauthenticate connection' would be about clearing the current authentication token that was obtained.  TBH the button names aren't really that accurate I don't think.

**Comment by TovaCohen** [comment]
thanks @gashcrumb! Good to know :-)
