### ISSUE TITLE
SQL deadlock detected after a soak test of 2M messages

### ISSUE THREAD

**Issue by maschmid** [syndesisio/syndesis#2155]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Having a soak test run on OCP, using NFS as a persistent volume for the postgres
with 8 running mock integrations in total  (3x timer (1s) -> amq, 2x amq -> log, 3x timer (1s) -> log )

after a weekend run (Uptime 2 days 20 hours 40 minutes), there are 2,171,371 Total Messages

the UI is unresponsive, with most of the API calls taking more than 30 seconds to run (30 seconds is the OpenShift HAProxy default limit)

## Expected behavior

Syndesis should be usable with even after the DB is filled with lots of message logs

## Request and Response Data

(oc rsh to the syndesis-server pod)
time curl -H "X-Forwarded-User: foobar" -H "X-Forwarded-Access-Token: foobar" 127.0.0.1:8080/api/v1/integration-support/overviews
`
{
  "items": [
    {
      "tags": [
        "activemq",
        "ext-io-syndesis-extensions-syndesis-connector-timer"
      ],
      "version": 2,
      "deploymentVersion": 2,
      "steps": [
        {
          "connection": {
            "icon": "extension:icon.png",
            "connectorId": "ext-io-syndesis-extensions-syndesis-connector-timer",
            "name": "timer",
            "id": "i-L8Hz5LixhoStjWXXQZ1z"
          },
          "stepKind": "endpoint",
          "kind": "step",
          "action": {
            "name": "Simple Timer"
          },
          "id": "-L8HznxuOcxje_csrXF9"
        },
        {
          "connection": {
            "icon": "fa-puzzle-piece",
            "connectorId": "activemq",
            "name": "amq",
            "id": "i-L8HzkmIxhoStjWXXQZ2z"
          },
          "stepKind": "endpoint",
          "kind": "step",
          "action": {
            "name": "Publish messages"
          },
          "id": "-L8HzyniOcxje_csrXF9"
        }
      ],
      "targetState": "Published",
      "currentState": "Published",
      "draft": false,
      "name": "timer-amq",
      "id": "i-L8I-AibxhoStjWXXQZ3z"
    },
    {
      "tags": [
        "activemq",
        "ext-io-syndesis-extensions-syndesis-connector-log"
      ],
      "version": 1,
      "deploymentVersion": 1,
      "steps": [
        {
          "connection": {
            "icon": "fa-puzzle-piece",
            "connectorId": "activemq",
            "name": "amq",
            "id": "i-L8HzkmIxhoStjWXXQZ2z"
          },
          "stepKind": "endpoint",
          "kind": "step",
          "action": {
            "name": "Subscribe for messages"
          },
          "id": "-L8IUSKVw1z3o5rWQZiE"
        },
        {
          "connection": {
            "icon": "extension:icon.png",
            "connectorId": "ext-io-syndesis-extensions-syndesis-connector-log",
            "name": "log",
            "id": "i-L8HubiqxhoStjWXXQZ-z"
          },
          "stepKind": "endpoint",
          "kind": "step",
          "action": {
            "name": "Simple Logger"
          },
          "id": "-L8IUUuqw1z3o5rWQZiE"
        }
      ],
      "targetState": "Published",
      "currentState": "Published",
      "draft": false,
      "name": "amq-log",
      "id": "i-L8IUYHF-FH_bC1BYiKCz"
    },
    {
      "tags": [
        "activemq",
        "ext-io-syndesis-extensions-syndesis-connector-timer"
      ],
      "version": 1,
      "deploymentVersion": 1,
      "steps": [
        {
          "connection": {
            "icon": "extension:icon.png",
            "connectorId": "ext-io-syndesis-extensions-syndesis-connector-timer",
            "name": "timer",
            "id": "i-L8Hz5LixhoStjWXXQZ1z"
          },
          "stepKind": "endpoint",
          "kind": "step",
          "action": {
            "name": "Simple Timer"
          },
          "id": "-L8IUcFFw1z3o5rWQZiF"
        },
        {
          "connection": {
            "icon": "fa-puzzle-piece",
            "connectorId": "activemq",
            "name": "amq",
            "id": "i-L8HzkmIxhoStjWXXQZ2z"
          },
          "stepKind": "endpoint",
          "kind": "step",
          "action": {
            "name": "Publish messages"
          },
          "id": "-L8IUdzVw1z3o5rWQZiF"
        }
      ],
      "targetState": "Published",
      "currentState": "Published",
      "draft": false,
      "name": "timer-amq2",
      "id": "i-L8IXmAN-FH_bC1BYiKDz"
    },
    {
      "tags": [
        "activemq",
        "ext-io-syndesis-extensions-syndesis-connector-timer"
      ],
      "version": 1,
      "deploymentVersion": 1,
      "steps": [
        {
          "connection": {
            "icon": "extension:icon.png",
            "connectorId": "ext-io-syndesis-extensions-syndesis-connector-timer",
            "name": "timer",
            "id": "i-L8Hz5LixhoStjWXXQZ1z"
          },
          "stepKind": "endpoint",
          "kind": "step",
          "action": {
            "name": "Simple Timer"
          },
          "id": "-L8IXqwJw1z3o5rWQZiG"
        },
        {
          "connection": {
            "icon": "fa-puzzle-piece",
            "connectorId": "activemq",
            "name": "amq",
            "id": "i-L8HzkmIxhoStjWXXQZ2z"
          },
          "stepKind": "endpoint",
          "kind": "step",
          "action": {
            "name": "Publish messages"
          },
          "id": "-L8IXsWPw1z3o5rWQZiG"
        }
      ],
      "targetState": "Published",
      "currentState": "Published",
      "draft": false,
      "name": "timer-amq3",
      "id": "i-L8IXx8g-FH_bC1BYiKEz"
    },
    {
      "tags": [
        "activemq",
        "ext-io-syndesis-extensions-syndesis-connector-log"
      ],
      "version": 1,
      "deploymentVersion": 1,
      "steps": [
        {
          "connection": {
            "icon": "fa-puzzle-piece",
            "connectorId": "activemq",
            "name": "amq",
            "id": "i-L8HzkmIxhoStjWXXQZ2z"
          },
          "stepKind": "endpoint",
          "kind": "step",
          "action": {
            "name": "Subscribe for messages"
          },
          "id": "-L8IY8MBw1z3o5rWQZiI"
        },
        {
          "connection": {
            "icon": "extension:icon.png",
            "connectorId": "ext-io-syndesis-extensions-syndesis-connector-log",
            "name": "log",
            "id": "i-L8HubiqxhoStjWXXQZ-z"
          },
          "stepKind": "endpoint",
          "kind": "step",
          "action": {
            "name": "Simple Logger"
          },
          "id": "-L8IYB_iw1z3o5rWQZiI"
        }
      ],
      "targetState": "Published",
      "currentState": "Published",
      "draft": false,
      "name": "amq-log2",
      "id": "i-L8IYE1l-FH_bC1BYiKFz"
    },
    {
      "tags": [
        "ext-io-syndesis-extensions-syndesis-connector-log",
        "ext-io-syndesis-extensions-syndesis-connector-timer"
      ],
      "version": 1,
      "deploymentVersion": 1,
      "steps": [
        {
          "connection": {
            "icon": "extension:icon.png",
            "connectorId": "ext-io-syndesis-extensions-syndesis-connector-timer",
            "name": "timer",
            "id": "i-L8Hz5LixhoStjWXXQZ1z"
          },
          "stepKind": "endpoint",
          "kind": "step",
          "action": {
            "name": "Simple Timer"
          },
          "id": "-L8ImSyB7KqrGvzWSSm9"
        },
        {
          "connection": {
            "icon": "extension:icon.png",
            "connectorId": "ext-io-syndesis-extensions-syndesis-connector-log",
            "name": "log",
            "id": "i-L8HubiqxhoStjWXXQZ-z"
          },
          "stepKind": "endpoint",
          "kind": "step",
          "action": {
            "name": "Simple Logger"
          },
          "id": "-L8ImUZ97KqrGvzWSSm9"
        }
      ],
      "targetState": "Published",
      "currentState": "Published",
      "draft": false,
      "name": "timer-log",
      "id": "i-L8ImWoP-FH_bC1BYiKGz"
    },
    {
      "tags": [
        "ext-io-syndesis-extensions-syndesis-connector-log",
        "ext-io-syndesis-extensions-syndesis-connector-timer"
      ],
      "version": 1,
      "deploymentVersion": 1,
      "steps": [
        {
          "connection": {
            "icon": "extension:icon.png",
            "connectorId": "ext-io-syndesis-extensions-syndesis-connector-timer",
            "name": "timer",
            "id": "i-L8Hz5LixhoStjWXXQZ1z"
          },
          "stepKind": "endpoint",
          "kind": "step",
          "action": {
            "name": "Simple Timer"
          },
          "id": "-L8ImYv97KqrGvzWSSmA"
        },
        {
          "connection": {
            "icon": "extension:icon.png",
            "connectorId": "ext-io-syndesis-extensions-syndesis-connector-log",
            "name": "log",
            "id": "i-L8HubiqxhoStjWXXQZ-z"
          },
          "stepKind": "endpoint",
          "kind": "step",
          "action": {
            "name": "Simple Logger"
          },
          "id": "-L8Ima217KqrGvzWSSmA"
        }
      ],
      "targetState": "Published",
      "currentState": "Published",
      "draft": false,
      "name": "timer-log2",
      "id": "i-L8ImcE7-FH_bC1BYiKHz"
    },
    {
      "tags": [
        "ext-io-syndesis-extensions-syndesis-connector-log",
        "ext-io-syndesis-extensions-syndesis-connector-timer"
      ],
      "version": 1,
      "deploymentVersion": 1,
      "steps": [
        {
          "connection": {
            "icon": "extension:icon.png",
            "connectorId": "ext-io-syndesis-extensions-syndesis-connector-timer",
            "name": "timer",
            "id": "i-L8Hz5LixhoStjWXXQZ1z"
          },
          "stepKind": "endpoint",
          "kind": "step",
          "action": {
            "name": "Simple Timer"
          },
          "id": "-L8ImoXu7KqrGvzWSSmB"
        },
        {
          "connection": {
            "icon": "extension:icon.png",
            "connectorId": "ext-io-syndesis-extensions-syndesis-connector-log",
            "name": "log",
            "id": "i-L8HubiqxhoStjWXXQZ-z"
          },
          "stepKind": "endpoint",
          "kind": "step",
          "action": {
            "name": "Simple Logger"
          },
          "id": "-L8ImqCw7KqrGvzWSSmB"
        }
      ],
      "targetState": "Published",
      "currentState": "Published",
      "draft": false,
      "name": "timer-log3",
      "id": "i-L8ImsAR-FH_bC1BYiKIz"
    }
  ],
  "totalCount": 8
}
`
real	12m6.170s

## Tasks involved / Steps to Reproduce

1. Install the timer and log extensions
2. Deploy A-MQ broker
3. Create a few timer (1s) -> amq   and  amq -> log  integrations
4. let it run over a weekend
5. time API requests, responses used by UI need to be faster than millennials' attention span

**Comment by KurtStam** [comment]
@maschmid When you restart the pods are things still slow? I mean if the #of records in the DB is causing this then it should be right?

**Comment by chirino** [comment]
@maschmid please restart the syndesis-server pod.  if that fixes the issue, then that points at a memory pressure issue.

**Comment by chirino** [comment]
@maschmid any updates?

**Comment by maschmid** [comment]
I have deployed the test now, so I will see after it soaks in...

**Comment by maschmid** [comment]
so far, after 50h uptime, the database logs started repeatedly showing

(the "LOG:  incomplete startup packet" are usual, probably caused by the probe)

...
FATAL:  remaining connection slots are reserved for non-replication superuser connections
FATAL:  remaining connection slots are reserved for non-replication superuser connections
FATAL:  remaining connection slots are reserved for non-replication superuser connections
LOG:  incomplete startup packet
FATAL:  remaining connection slots are reserved for non-replication superuser connections
FATAL:  remaining connection slots are reserved for non-replication superuser connections
FATAL:  remaining connection slots are reserved for non-replication superuser connections
LOG:  incomplete startup packet
FATAL:  remaining connection slots are reserved for non-replication superuser connections
FATAL:  remaining connection slots are reserved for non-replication superuser connections
...

in the server pod there occured a "deadlock detected" psql error:

2018-04-12 17:03:15.005  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.i.IntegrationController          : Integration i-L9k2XLKLfP91kVFUdHSz : Setting status to Pending
Exception in thread "Logs Controller" org.skife.jdbi.v2.exceptions.UnableToExecuteStatementException: org.postgresql.util.PSQLException: ERROR: deadlock detected
  Detail: Process 108971 waits for ShareLock on transaction 31343; blocked by process 124477.
Process 124477 waits for ShareLock on transaction 31323; blocked by process 108971.
  Hint: See server log for query details.
  Where: while deleting tuple (43873,18) in relation "jsondb" [statement:"DELETE from jsondb where path LIKE ? OR path in ( ?, ?, ? )", located:"DELETE from jsondb where path LIKE ? OR path in ( ?, ?, ? )", rewritten:"DELETE from jsondb where path LIKE ? OR path in ( ?, ?, ? )", arguments:{ positional:{0:'/activity/exchanges/i-L9pUfQpusTV7fGMA3qLz/i-L9pazCMLj3jFQPG6b3sz/%',1:'/activity/exchanges/i-L9pUfQpusTV7fGMA3qLz/',2:'/activity/exchanges/',3:'/activity/'}, named:{}, finder:[]}]
        at org.skife.jdbi.v2.SQLStatement.internalExecute(SQLStatement.java:1338)
        at org.skife.jdbi.v2.Update.execute(Update.java:56)
        at org.skife.jdbi.v2.BasicHandle.update(BasicHandle.java:305)
        at io.syndesis.server.jsondb.impl.SqlJsonDB.deleteJsonRecords(SqlJsonDB.java:514)
        at io.syndesis.server.jsondb.impl.SqlJsonDB.access$100(SqlJsonDB.java:74)
        at io.syndesis.server.jsondb.impl.SqlJsonDB$BatchManager.deleteRecordsForSet(SqlJsonDB.java:395)
        at io.syndesis.server.jsondb.impl.SqlJsonDB.lambda$update$18(SqlJsonDB.java:474)
        at io.syndesis.server.jsondb.impl.SqlJsonDB.withTransaction(SqlJsonDB.java:550)
        at io.syndesis.server.jsondb.impl.SqlJsonDB.update(SqlJsonDB.java:451)
        at io.syndesis.server.jsondb.JsonDB.update(JsonDB.java:141)
        at io.syndesis.server.logging.jsondb.controller.ActivityTrackingController.processEventQueue(ActivityTrackingController.java:287)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.postgresql.util.PSQLException: ERROR: deadlock detected
  Detail: Process 108971 waits for ShareLock on transaction 31343; blocked by process 124477.
Process 124477 waits for ShareLock on transaction 31323; blocked by process 108971.
  Hint: See server log for query details.
  Where: while deleting tuple (43873,18) in relation "jsondb"
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2103)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1836)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:257)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:512)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:388)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:381)
        at sun.reflect.GeneratedMethodAccessor138.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
        at com.sun.proxy.$Proxy144.execute(Unknown Source)
        at org.skife.jdbi.v2.SQLStatement.internalExecute(SQLStatement.java:1327)
        ... 13 more
2018-04-12 17:03:56.136  INFO [-,,,] 1 --- [Logs Controller] i.s.s.l.j.c.ActivityTrackingController   : deleted 1625 transactions for integration: i-L9pUfQpusTV7fGMA3qLz


and 5 hours later a stream of

2018-04-12 22:13:10.114 ERROR [-,,,] 1 --- [Logs Controller] i.s.s.l.j.c.ActivityTrackingController   : Unexpected Error occurred.

org.skife.jdbi.v2.exceptions.UnableToObtainConnectionException: org.postgresql.util.PSQLException: FATAL: remaining connection slots are reserved for non-replication superuser connections
        at org.skife.jdbi.v2.DBI.open(DBI.java:229) ~[jdbi-2.78.jar!/:2.78]
        at io.syndesis.server.jsondb.impl.SqlJsonDB.getAsStreamingOutput(SqlJsonDB.java:178) ~[server-jsondb-1.3.4.fuse-000001-redhat-2.jar!/:1.3.4.fuse-000001-redhat-2]
        at io.syndesis.server.jsondb.JsonDB.getAsStream(JsonDB.java:160) ~[server-jsondb-1.3.4.fuse-000001-redhat-2.jar!/:1.3.4.fuse-000001-redhat-2]
        at io.syndesis.server.jsondb.JsonDB.getAsByteArray(JsonDB.java:130) ~[server-jsondb-1.3.4.fuse-000001-redhat-2.jar!/:1.3.4.fuse-000001-redhat-2]
        at io.syndesis.server.logging.jsondb.controller.ActivityTrackingController.dbGet(ActivityTrackingController.java:246) ~[server-logging-jsondb-1.3.4.fuse-000001-redhat-2.jar!/:1.3.4.fuse-000001-redhat-2]
        at io.syndesis.server.logging.jsondb.controller.ActivityTrackingController.dbGet(ActivityTrackingController.java:242) ~[server-logging-jsondb-1.3.4.fuse-000001-redhat-2.jar!/:1.3.4.fuse-000001-redhat-2]
        at io.syndesis.server.logging.jsondb.controller.ActivityTrackingController.pollPods(ActivityTrackingController.java:199) ~[server-logging-jsondb-1.3.4.fuse-000001-redhat-2.jar!/:1.3.4.fuse-000001-redhat-2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_161]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_161]
Caused by: org.postgresql.util.PSQLException: FATAL: remaining connection slots are reserved for non-replication superuser connections
        at org.postgresql.core.v3.ConnectionFactoryImpl.readStartupMessages(ConnectionFactoryImpl.java:471) ~[postgresql-9.1-901-1.jdbc4.jar!/:na]
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:112) ~[postgresql-9.1-901-1.jdbc4.jar!/:na]
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) ~[postgresql-9.1-901-1.jdbc4.jar!/:na]
        at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125) ~[postgresql-9.1-901-1.jdbc4.jar!/:na]
        at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30) ~[postgresql-9.1-901-1.jdbc4.jar!/:na]
        at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22) ~[postgresql-9.1-901-1.jdbc4.jar!/:na]
        at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:32) ~[postgresql-9.1-901-1.jdbc4.jar!/:na]
        at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24) ~[postgresql-9.1-901-1.jdbc4.jar!/:na]
        at org.postgresql.Driver.makeConnection(Driver.java:393) ~[postgresql-9.1-901-1.jdbc4.jar!/:na]
        at org.postgresql.Driver.connect(Driver.java:267) ~[postgresql-9.1-901-1.jdbc4.jar!/:na]
        at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:310) ~[tomcat-jdbc-8.5.23.jar!/:na]
        at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:203) ~[tomcat-jdbc-8.5.23.jar!/:na]
        at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:735) ~[tomcat-jdbc-8.5.23.jar!/:na]
        at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:667) ~[tomcat-jdbc-8.5.23.jar!/:na]
        at org.apache.tomcat.jdbc.pool.ConnectionPool.getConnection(ConnectionPool.java:198) ~[tomcat-jdbc-8.5.23.jar!/:na]
        at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:132) ~[tomcat-jdbc-8.5.23.jar!/:na]
        at org.skife.jdbi.v2.DataSourceConnectionFactory.openConnection(DataSourceConnectionFactory.java:34) ~[jdbi-2.78.jar!/:2.78]
        at org.skife.jdbi.v2.DBI.open(DBI.java:211) ~[jdbi-2.78.jar!/:2.78]
        ... 9 common frames omitted

2018-04-12 22:13:15.110 ERROR [-,,,] 1 --- [Logs Controller] i.s.s.l.j.c.ActivityTrackingController   : Unexpected Error occurred.

for several hours


the storage of events doesn't seem to work since, there are no messages shown in "Activity" view of any integration, even though the message counter increases.

I have put the server log here:  http://maven.xtf.cz/50h_uptime_syndesis-server-1-b9kg6.log

**Comment by maschmid** [comment]
$ grep -R -C 20 deadlock *
postgresql-Mon.log-LOG:  incomplete startup packet
postgresql-Mon.log-LOG:  incomplete startup packet
postgresql-Mon.log-LOG:  incomplete startup packet
postgresql-Mon.log-LOG:  incomplete startup packet
postgresql-Mon.log-LOG:  incomplete startup packet
postgresql-Mon.log-LOG:  incomplete startup packet
postgresql-Mon.log-LOG:  incomplete startup packet
postgresql-Mon.log-LOG:  incomplete startup packet
postgresql-Mon.log-LOG:  incomplete startup packet
postgresql-Mon.log-LOG:  incomplete startup packet
postgresql-Mon.log-LOG:  incomplete startup packet
postgresql-Mon.log-LOG:  incomplete startup packet
postgresql-Mon.log-LOG:  incomplete startup packet
postgresql-Mon.log-LOG:  incomplete startup packet
postgresql-Mon.log-LOG:  incomplete startup packet
postgresql-Mon.log-LOG:  incomplete startup packet
postgresql-Mon.log-LOG:  incomplete startup packet
postgresql-Mon.log-LOG:  incomplete startup packet
postgresql-Mon.log-LOG:  incomplete startup packet
postgresql-Mon.log-LOG:  incomplete startup packet
postgresql-Mon.log:ERROR:  deadlock detected
postgresql-Mon.log-DETAIL:  Process 72834 waits for ShareLock on transaction 39630; blocked by process 72838.
postgresql-Mon.log-	Process 72838 waits for ShareLock on transaction 39628; blocked by process 72834.
postgresql-Mon.log-	Process 72834: DELETE from jsondb where path LIKE $1 OR path in ( $2, $3, $4 )
postgresql-Mon.log-	Process 72838: DELETE from jsondb where path LIKE $1 and path < $2
postgresql-Mon.log-HINT:  See server log for query details.
postgresql-Mon.log-CONTEXT:  while deleting tuple (12891,8) in relation "jsondb"
postgresql-Mon.log-STATEMENT:  DELETE from jsondb where path LIKE $1 OR path in ( $2, $3, $4 )
postgresql-Mon.log-LOG:  incomplete startup packet
postgresql-Mon.log-LOG:  incomplete startup packet
postgresql-Mon.log-LOG:  incomplete startup packet
postgresql-Mon.log-LOG:  incomplete startup packet
postgresql-Mon.log-LOG:  incomplete startup packet
postgresql-Mon.log-LOG:  incomplete startup packet
postgresql-Mon.log-LOG:  incomplete startup packet
postgresql-Mon.log-LOG:  incomplete startup packet
postgresql-Mon.log-LOG:  incomplete startup packet
postgresql-Mon.log-LOG:  incomplete startup packet
postgresql-Mon.log-LOG:  incomplete startup packet
postgresql-Mon.log-LOG:  incomplete startup packet
postgresql-Mon.log-LOG:  incomplete startup packet
--
postgresql-Thu.log-LOG:  incomplete startup packet
postgresql-Thu.log-LOG:  incomplete startup packet
postgresql-Thu.log-LOG:  incomplete startup packet
postgresql-Thu.log-LOG:  incomplete startup packet
postgresql-Thu.log-LOG:  incomplete startup packet
postgresql-Thu.log-LOG:  incomplete startup packet
postgresql-Thu.log-LOG:  incomplete startup packet
postgresql-Thu.log-LOG:  incomplete startup packet
postgresql-Thu.log-LOG:  incomplete startup packet
postgresql-Thu.log-LOG:  incomplete startup packet
postgresql-Thu.log-LOG:  incomplete startup packet
postgresql-Thu.log-LOG:  incomplete startup packet
postgresql-Thu.log-LOG:  incomplete startup packet
postgresql-Thu.log-LOG:  incomplete startup packet
postgresql-Thu.log-LOG:  incomplete startup packet
postgresql-Thu.log-LOG:  incomplete startup packet
postgresql-Thu.log-LOG:  incomplete startup packet
postgresql-Thu.log-LOG:  incomplete startup packet
postgresql-Thu.log-LOG:  incomplete startup packet
postgresql-Thu.log-LOG:  incomplete startup packet
postgresql-Thu.log:ERROR:  deadlock detected
postgresql-Thu.log-DETAIL:  Process 108971 waits for ShareLock on transaction 31343; blocked by process 124477.
postgresql-Thu.log-	Process 124477 waits for ShareLock on transaction 31323; blocked by process 108971.
postgresql-Thu.log-	Process 108971: DELETE from jsondb where path LIKE $1 OR path in ( $2, $3, $4 )
postgresql-Thu.log-	Process 124477: DELETE from jsondb where path LIKE $1 and path < $2
postgresql-Thu.log-HINT:  See server log for query details.
postgresql-Thu.log-CONTEXT:  while deleting tuple (43873,18) in relation "jsondb"
postgresql-Thu.log-STATEMENT:  DELETE from jsondb where path LIKE $1 OR path in ( $2, $3, $4 )
postgresql-Thu.log-LOG:  incomplete startup packet
postgresql-Thu.log-LOG:  incomplete startup packet
postgresql-Thu.log-LOG:  incomplete startup packet
postgresql-Thu.log-LOG:  incomplete startup packet
postgresql-Thu.log-LOG:  incomplete startup packet
postgresql-Thu.log-LOG:  incomplete startup packet
postgresql-Thu.log-LOG:  incomplete startup packet
postgresql-Thu.log-LOG:  incomplete startup packet
postgresql-Thu.log-LOG:  incomplete startup packet
postgresql-Thu.log-LOG:  incomplete startup packet
postgresql-Thu.log-LOG:  incomplete startup packet
postgresql-Thu.log-LOG:  incomplete startup packet
postgresql-Thu.log-LOG:  incomplete startup packet

**Comment by chirino** [comment]
@maschmid a change just went into master which I'm hoping eliminates this issue.  Do you need a pipeline build to retest?

**Comment by maschmid** [comment]
Deployed the test with 1.3.5-20180425

**Comment by maschmid** [comment]
22 hour uptime by now, 1,805,991 Total Messages 

So far the performance of the /integrations is noticably slower   (3 - 4 seconds)

time curl -H "X-Forwarded-User: foobar" -H "X-Forwarded-Access-Token: foobar" 127.0.0.1:8080/api/v1/integrations
real	0m3.558s

(as the integration view does not display the activity log directly, I consider this to be slightly suspicous)

**Comment by chirino** [comment]
Have there been any deadlocks?

**Comment by maschmid** [comment]
(i can verify that the pods still produce new logs every second, so the ingrations still run every second just fine)

**Comment by KurtStam** [comment]
@chirino  'DELETE from jsondb where path LIKE ...' can cause a table level lock due to lock escalation. We might want to do this is in two steps so we can delete by ID.

**Comment by maschmid** [comment]
After 4 days of uptime the metrics stopped working,
 
oc describe pod syndesis-prometheus-1-dg9cs 
...
    Last State:		Terminated
      Reason:		OOMKilled
      Exit Code:	137
...

the pod went into CrashLoopBackOff.  Deleting the pod doesn't help. The new pod gets oomkilled just after start.

**Comment by paoloantinori** [comment]
Hi @maschmid do you have evidence of the same deadlock we had before?

**Comment by maschmid** [comment]
http://xtf.cz/2018-04-30-pg_log.tar.gz
http://xtf.cz/2018-04-30-syndesis-server-1-7qmkg.log.gz

while there is no "deadlock" mentioned in the psql logs, there are some
"FATAL:  remaining connection slots are reserved for non-replication superuser connections"

**Comment by rhuss** [comment]
@maschmid @dhirajsb looks like that Prometheus sucks in parts of its timeseries db (or indexes) into memory, so for me it looks that we (a) should configured Prometheus to be more memory conversative and/or tune the openshift resource requests and limits.

**Comment by paoloantinori** [comment]
I'm closing this as moving the discussion to https://github.com/syndesisio/syndesis/issues/2547 , that now reflects more the current state of the issue we are looking at.
