### ISSUE TITLE
UX: Add navigation to the UX Tracker

### ISSUE THREAD

**Issue by amysueg** [syndesisio/syndesis#2158]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Documentation issue or request
</code></pre>

## The problem
The UX work tracker (#2113) should include two items on the nav bar in addition to the landing page showing the actual work being tracked. 

The nav should be "Home | Icons | Style Guide"

The Icons should link to this location: https://github.com/syndesisio/syndesis/tree/master/ux/connections_icons

The Style Guide will be developed. For now, the link should display a blank page with text like "coming soon."

**Comment by michael-coker** [comment]
done! also updated the [README.md](https://github.com/syndesisio/syndesis-ux/blob/master/README.md) to include local build instructions.

For reference, the file that serves the style guide page is [style-guide.md](https://github.com/syndesisio/syndesis-ux/blob/master/style-guide.md)

https://syndesisio.github.io/syndesis-ux/

**Comment by amysueg** [comment]
Thank you!
