### ISSUE TITLE
Integration Editor: Save as Draft should display notification on success 

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis#2163]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
Derived from https://github.com/syndesisio/syndesis/issues/1828 && https://github.com/syndesisio/syndesis/issues/1947.

When button `Save as Draft` currently there's no indication for user to know if everything is saved successfully or not.

## Expected behavior
Toas notification is displayed on successful save or error otherwise.

## Screenshot
See preview gif in https://github.com/syndesisio/syndesis/issues/1947

**Comment by gashcrumb** [comment]
Ideally our save function should consistently work so that the user trusts that clicking save actually saves :-)

Also I dislike gratuitous notifications.  I think notifications should be the exception, not the rule, and we do a big inline notification if there's a save error.

**Comment by dsimansk** [comment]
Hmm a green button maybe :) It feels like that current `Save as Draft` is lacking a visual representation of success. But it might be just me.

@sjcox-rh @dongniwang could you pls review a `Save as Draft` behaviour if you find a bit of spare time?

**Comment by sjcox-rh** [comment]
@dsimansk, @gashcrumb 

Agree with stan that I wouldn't necessarily want to show a toast notification here but it would be nice to show a subtle success state for saving a draft.

How about changing the "Save as Draft" button to show status, like below. 

![dashboard copy](https://user-images.githubusercontent.com/16257540/38204965-e38bc4ca-3672-11e8-8299-42bfdbbfc10f.png)

I visually changed it so it is no longer a button (no outline, gradient, shadow) but simply informs the user that the save was successful. Would retain state until a change was made to the integration, then would return to "Save as draft" button.

@dongniwang, fyi, let me know if you agree with this direction.

**Comment by dongniwang** [comment]
I like the the approach of displaying the dynamic status within the area of the button. It feels more responsive and lightweight. @sjcox-rh 

Just a couple questions for implementation: 
- How long does it take to save an integration? I noticed there's a spinner icon in place currently once user clicks the "Save as Draft" button. 
- I know SJ mentioned that it would remain its state unless a change was made. And I wondered if we want it to just remain its state (the green checkmark) for a couple seconds then return back to "Save as Draft". 
- If a dynamic button is too much, maybe we could go with the old way of just displaying a line of text alongside with the buttons. Something like "Last saved today at 2:20 pm"?

**Comment by amysueg** [comment]
Solving this will need to also include scenarios where save as draft does not work as expected.

**Comment by gashcrumb** [comment]
Autosave makes this issue obsolete really

**Comment by amysueg** [comment]
Should we assume autosave #3048 will happen and thus close this issue @gashcrumb @gaughan?
fyi @dongniwang @sjcox-rh

**Comment by gashcrumb** [comment]
I think so, honestly I don't see this particular issue ever being worked; we're going in a different direction so makes sense to close it.

**Comment by amysueg** [comment]
Per @gashcrumb closing.
