### ISSUE TITLE
Can't build Syndesis, Syndesis-cli is failing.

### ISSUE THREAD

**Issue by oscerd** [syndesisio/syndesis#2164]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
When building the full project, in syndesis-cli we get

```
[INFO] --- duplicate-finder-maven-plugin:1.2.1:check (default) @ syndesis-cli ---
[INFO] Checking compile classpath
[INFO] Checking runtime classpath
[INFO] Checking test classpath
[WARNING] Found duplicate and different resources in [/home/oscerd/workspace/jboss-fuse/syndesis/app/cli/target/classes, io.syndesis.server:server-runtime:1.3-SNAPSHOT]:
[WARNING]   application.yml
[WARNING] Found duplicate classes/resources in compile classpath.
[WARNING] Found duplicate and different resources in [/home/oscerd/workspace/jboss-fuse/syndesis/app/cli/target/classes, io.syndesis.server:server-runtime:1.3-SNAPSHOT]:
[WARNING]   application.yml
[WARNING] Found duplicate classes/resources in runtime classpath.
[WARNING] Found duplicate and different resources in [/home/oscerd/workspace/jboss-fuse/syndesis/app/cli/target/classes, io.syndesis.server:server-runtime:1.3-SNAPSHOT]:
[WARNING]   application.yml
[WARNING] Found duplicate classes/resources in test classpath.
.
.
.
[ERROR] Failed to execute goal org.basepom.maven:duplicate-finder-maven-plugin:1.2.1:check (default) on project syndesis-cli: Found duplicate classes/resources! -> [Help 1]
```

**Comment by zregvart** [comment]
@oscerd are you doing a clean build, i.e. `syndesis build -c`?

**Comment by zregvart** [comment]
Hmm, I wonder if the CI is building the CLI module.

**Comment by oscerd** [comment]
`syndesis build --image-mode openshift --clean --skip-tests`

**Comment by rhuss** [comment]
@zregvart as syndesis-cli is part of the group 'server' syndesis should build it too (if its inclduded in server's pom.xml)

I'm just trying to reproduce it here, too.

**Comment by oscerd** [comment]
It works fine with -f option

**Comment by rhuss** [comment]
yes, `-f` turns of any checks (like the duplicate class check).

**Comment by rhuss** [comment]
I can confirm that is breaks with `syndesis build --image-mode openshift --clean --skip-tests`

@zregvart I wonder, whether the CI test maybe don't run the `duplicate-finder-maven-plugin` ?

Actually the complain is, that there are two `application.yml` in the classpath: One from server-cli and the other one (still) from server-runtime. Maybe use a differently named application.yml for the CLI ?

**Comment by zregvart** [comment]
There are two issues here:
 - CI doesn't build CLI (as it's a top level module)
 - there are duplicate `application.yml` on the classpath (will cause issues at some point)

I need to address both.

**Comment by rhuss** [comment]
@zregvart could we please move cli to server/cli ?

**Comment by rhuss** [comment]
I don't think we need to add a top-level module right now. This is quite expensive:

* Update of "syndesis"
* Update of CI config
* Update of documentation
* Update of GitHub labels
* + all the stuff I just forgot.

And actually, CLI only uses syndesis-server right now. I would just put it as another 'server-cli' module in there, and in the case it grows, would move it top-level. But only then.

We should not inflate the top-level module/group space unnecessarily.
