### ISSUE TITLE
Endless "Unpublishing" state

### ISSUE THREAD

**Issue by tplevko** [syndesisio/syndesis#2167]
## This is a...

<pre><code>
[ ] Feature request
[ x ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

When I try to unpublish any integration, it stays in the "unpublishing" state endlessly. 

## Expected behavior

It should end in "unpublished" state.

## Screenshot

![indefinite_unpublish](https://user-images.githubusercontent.com/4180208/37966802-ced6043a-31c9-11e8-8fce-e418ef53ecfb.gif)

## Tasks involved / Steps to Reproduce

1. Create integration
2. Unpublish the integration
3. The integration stays in "unpublishing" state indefinitely

**Comment by tplevko** [comment]
@paoloantinori hi, could someone please have a look at this? It would be great if it worked as described in our [lifecycle documentation](https://access.qa.redhat.com/documentation/en-us/red_hat_jboss_fuse/7.0-tp/html-single/integrating_applications_with_ignite/#about-integration-lifecycle-handling).

**Comment by paoloantinori** [comment]
Hi @tplevko  can you please attach the logs of the server pod?

**Comment by tplevko** [comment]
@paoloantinori of course, there it is.
[server_pod.log](https://github.com/syndesisio/syndesis/files/1875349/server_pod.log)

**Comment by paoloantinori** [comment]
@tplevko do you have the one spanning 3 hours like you described in your issue definition?

**Comment by tplevko** [comment]
@paoloantinori I don't have one which would span for 3 hours, there is one which spans for 1 hour, I hope it's enough:
[server_pod.log](https://github.com/syndesisio/syndesis/files/1876388/server_pod.log)

**Comment by gashcrumb** [comment]
I've managed to reproduce this now by publishing and then unpublishing the same integration a couple times without making any actual changes to the integration.

**Comment by iocanel** [comment]
Fixes has been merged
