### ISSUE TITLE
LogStepHandler - Context ?

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis#2177]
https://github.com/syndesisio/syndesis/blob/414dff408386c8bf2b41df634b827f0604ccb225/app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/LogStepHandler.java#L52-L57

Hi @iocanel I have just stumbled in the above line, that look wrong since 2 different flags produce the same result.

I would have fixed this myself but I'm not sure what `context` is supposed to mean: `exchange` or just `headers`?

**Comment by iocanel** [comment]
As described by @kcbabo in https://github.com/syndesisio/syndesis/issues/332#issuecomment-368973088: "Message Context" is Headers and Properties.

**Comment by iocanel** [comment]
@paoloantinori: I created a pull request that replaces body with input headers. I don't know if camel provides a way to log ALL properties (as it does with input headers). Didn't find anything in the doc. Same applies to output headers.

So, I am cloding that. Feel free to reopen, if I there is an option that I missed.
