### ISSUE TITLE
Console displays "refresh" icon that does not disappear

### ISSUE THREAD

**Issue by honghuac** [syndesisio/syndesis#2199]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Unpublishing an active integration leads to the following error (seen in the syndesis-rest pod log):
https://gist.github.com/honghuac/3cd80e720cce038a5c16356267475a53

The "refresh" icon does not disappear from the Fuse Ignite console.

## Expected behavior

The errors should not exist.

## Screenshot

![spin](https://user-images.githubusercontent.com/8625482/38091118-2421746e-3397-11e8-906e-a0bd5abcfea8.png)

**Comment by gashcrumb** [comment]
@michael-coker hey, this would be a quick one, this happens when the connections API takes awhile to return...

**Comment by michael-coker** [comment]
How can I reproduce this? I tried unpublishing from the dashboard, didn't get a spinner, and refreshing didn't display a persisting spinner.

And how should this be handled? Should there be some sort of timeout, and if so, when the timeout is met, what should happen in the UI?

**Comment by gashcrumb** [comment]
@honghuac how many connections do you have and what kind?  Wonder if that's related.

It could also just be a matter of creating a bunch of connections/integrations which might start slowing down the API responses.
