### ISSUE TITLE
Nullpointer exception during startup

### ISSUE THREAD

**Issue by honghuac** [syndesisio/syndesis#2200]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

This is observed from the test drive of the code from the current master branch.

Nullpointer exception was detected in a new deployment of **syndesis-rest** pod.
https://gist.github.com/honghuac/76e239bbe7bf51422dc32b4c4ef0d278#file-gistfile1-txt-L11-L66

## Expected behavior

There should not be such exceptions during startup.

**Comment by nicolaferraro** [comment]
I'm getting the same one..
