### ISSUE TITLE
`syndesis build` executed on *fuse ignite 1.3* release fails

### ISSUE THREAD

**Issue by honghuac** [syndesisio/syndesis#2209]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

`syndesis build` executed on *fuse ignite 1.3* release fails:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.8:check (default) on project integration-project-generator: You have 1 PMD violation. For more details see: /hong/syndesis-fuse-ignite-1.3/app/integration/project-generator/target/pmd.xml

Contents on pmd.xml file --
https://gist.github.com/honghuac/eb14dfeb8601311c226323178eae28f6

**Comment by zregvart** [comment]
I just tested this within a docker container building the 1.3.4 tag, so to eliminate any outside interference and could not reproduce. The violation messages and violation rules seem to be mismatched so this might point to incremental/multi-threading issue with PMD.

```shell
$ docker run --rm -it docker.io/java:8-jdk
root@ea08094aeafa:/# git clone https://github.com/syndesisio/syndesis.git
Cloning into 'syndesis'...
remote: Counting objects: 121177, done.
remote: Compressing objects: 100% (54/54), done.
remote: Total 121177 (delta 24), reused 41 (delta 12), pack-reused 121108
Receiving objects: 100% (121177/121177), 59.92 MiB | 6.95 MiB/s, done.
Resolving deltas: 100% (58880/58880), done.
Checking connectivity... done.
root@ea08094aeafa:/# cd syndesis/
root@ea08094aeafa:/syndesis# git checkout tags/1.3.4
Note: checking out 'tags/1.3.4'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at d74d562... [1.3.4]: Update OpenShift templates for Syndesis 1.3.4
root@ea08094aeafa:/syndesis# tools/bin/syndesis build --backend

...

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 06:48 min
[INFO] Finished at: 2018-04-04T09:44:15Z
[INFO] Final Memory: 280M/689M
[INFO] ------------------------------------------------------------------------
```

I would suggest trying a clean build (`syndesis build -c`).

**Comment by zregvart** [comment]
I can reproduce this by running two builds in a row. I think upgrading the plugin might help, seems easy enough to try.
