### ISSUE TITLE
AMQ Connection Wizard - fails to authenticate successfully with AMQ broker despite correct UserId/Password pair

### ISSUE THREAD

**Issue by honghuac** [syndesisio/syndesis#2210]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

In Syndesis 1.3.4,
AMQ Connection Wizard - fails to authenticate successfully with AMQ broker despite correct UserId/  Password pair

Validation will fail with an error message.

**Comment by jbride** [comment]
Apologies:   user error.
This github issue can be closed.

**Comment by gashcrumb** [comment]
Ah, k, thanks!
