### ISSUE TITLE
Creating API client connector, required fields need a required label

### ISSUE THREAD

**Issue by michael-coker** [syndesisio/syndesis#2211]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
There is no visual indication which fields are required until you try to submit the form or focus out of the required field

## Expected behavior
There should be a red asterisk by the "Connector Name" label

## Screenshot
![screen shot 2018-04-02 at 1 04 52 pm](https://user-images.githubusercontent.com/35148959/38208500-e0eea968-3676-11e8-838d-e1c7d2a6e9a9.png)

## Tasks involved / Steps to Reproduce
1. Nav to Customizations
2. Create API Connector
3. Upload a swagger file (I used the todo app's)
4. Next through the steps until you get to the review step

**Comment by KurtStam** [comment]
The `Name` field is prepopulated with with data obtained from the swagger.json. The `Create Connector` button is de-activated when this `Name` field is emptied and the `Name` text box turns red.

<img width="712" alt="screen shot 2018-04-16 at 2 26 28 pm" src="https://user-images.githubusercontent.com/35576/38827857-3c86be80-4182-11e8-9a1e-16006a6b2c69.png">

Do we really need a star next to the `Name` field too?

**Comment by michael-coker** [comment]
@KurtStam The issue with the red outline (or text or whatever) as an indication of a required field is that the most common accessibility issue with websites is around color blindness, and most color blind folks have a hard time seeing red (and green and blue).

The issue with the button being disabled is that there's no clear indication of what's missing in the form. Could be that you need a connector name, or it could be that another field is empty, has an invalid value, etc. 

This is also the first instance I've seen in the app where a required field is not indicated with a red asterisk, and we should be as consistent as we can be. The asterisk is also the [patternfly pattern for required fields](http://www.patternfly.org/pattern-library/forms-and-controls/field-labeling/), which we should follow if possible.

**Comment by KurtStam** [comment]
@michael-coker So everything can stay as it is and we add the star like so:

<img width="519" alt="screen shot 2018-04-16 at 3 33 07 pm" src="https://user-images.githubusercontent.com/35576/38830834-83b417e0-418b-11e8-9b76-df8992941b8f.png">
