### ISSUE TITLE
UX Design: Connection Template

### ISSUE THREAD

**Issue by sjcox-rh** [syndesisio/syndesis#2212]
## This is a...

<pre><code>
[X ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
As new connections are added into iPaaS, would be helpful for UXD to provide a design template for connections that UI team can use going forward.

## Expected behavior
Creation of a design template that can be used as a reference for future new connections as then get added to iPaaS. This will be the first contribution to the styleguide being created.

## Screenshot
Coming soon.

## Tasks involved / Steps to Reproduce

1. Design Template
2. Review with UXD
3. Review with UI
4. Revise based on Feedback and finalize

**Comment by amysueg** [comment]
Awesome! Can't wait, this is going to be really helpful for the UI devs. ![bitmoji](https://render.bitstrips.com/v2/cpanel/469d4aea-0aaa-4b89-919e-0fd853b6f0f0-cc737c0e-145d-4d97-aea9-1fdd38b44e0a-v1.png?transparent=1&palette=1&width=246)

**Comment by amysueg** [comment]
Based on the current planning conversations, this story is important. While planning for additional connectors, it's clear that having a UX guide in place for new connectors will be really helpful. Thanks, @sjcox-rh !

**Comment by sjcox-rh** [comment]
Please view the latest designs for the Connection Template found in our [design tracker](https://syndesisio.github.io/syndesis-ux/)

This template should act as a resource for new connectors being added into iPaaS.

@kcbabo @gashcrumb @kahboom @seanforyou23 @amysueg @paoloantinori @dongniwang @michael-coker @chirino @zregvart

**Comment by zregvart** [comment]
The [Configure connection screen](https://redhat.invisionapp.com/share/BGKJY9XCA6H#/screens/297274667) depicts a non-OAuth connection flow, should there be a template that screen when using OAuth connection flow? See [current designs](https://github.com/syndesisio/syndesis/blob/master/ux/designs/oauth/oauth.md).

The screen of the [connection details](https://redhat.invisionapp.com/share/BGKJY9XCA6H#/screens/297274661) page depicts details of a OAuth based connections, not all connections are OAuth based, should there be a page template for non-OAuth based connections? See the AMQ connection details page [on staging](https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/connections/i-L9aldOzEz22SUzIdZT8z).

**Comment by gashcrumb** [comment]
Added some comments to the design, overall looking good.

**Comment by TovaCohen** [comment]
Thank! I added comments on pages 5, 8, 9, 11.

**Comment by heiko-braun** [comment]
@sjcox-rh what's the status of this?  Does the latest design for the Connection Template satisfy our needs?

**Comment by gaughan** [comment]
Looks great. UX Approved by PM

**Comment by sjcox-rh** [comment]
Sorry for the delay in this but here is V2 of the connection template that hopefully addresses all the comments and feedback received from V1!

https://redhat.invisionapp.com/share/NKMXKRVJG93

Please review when you have time, thank you!

@gashcrumb @gaughan @kcbabo @amysueg @dongniwang @seanforyou23 @michael-coker @paoloantinori @TovaCohen

**Comment by amysueg** [comment]
@sjcox-rh I added a comment and noticed a few others from @zregvart and @gaughan 

Thanks for your work on this!

**Comment by gashcrumb** [comment]
Commented, my comments revolved around button placement.  I feel like after all this talk of button placement we need to get it right :-)

**Comment by sjcox-rh** [comment]
Version 3 of Connection template based off the last round of comments. Thanks everyone for your feedback!

https://redhat.invisionapp.com/share/VZN4L63RS5D

Please review when you have time, thank you!

@gashcrumb @gaughan @kcbabo @amysueg @dongniwang @seanforyou23 @michael-coker @paoloantinori @TovaCohen

**Comment by TovaCohen** [comment]
This LGTM. Thanks SJ!
