### ISSUE TITLE
Improve responsive behavior of the Connections page

### ISSUE THREAD

**Issue by amysueg** [syndesisio/syndesis#2228]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
Resizing the browser results in a poor layout of web interface elements and renders the Connections page unusable in many cases. On a mobile device, it's just as bad or worse. 

## Expected behavior
The page should resize elegantly using modern web design techniques. UXD team will define guidelines for responsive breakpoints and expected layouts and behaviors.

See #2216

**Comment by amysueg** [comment]
@michael-coker @sjcox-rh wanted to tag you here as this one is related to some work you are doing on #2149

**Comment by michael-coker** [comment]
PR https://github.com/syndesisio/syndesis/pull/2222 should fix this once merged.

**Comment by michael-coker** [comment]
Made another change here to address some small issues. Also refactored the CSS for a couple of components on this page.

Issue - https://github.com/syndesisio/syndesis/issues/2742
PR - https://github.com/syndesisio/syndesis/pull/2743

**Comment by amysueg** [comment]
Great! Thanks for following up @michael-coker

**Comment by michael-coker** [comment]
@amysueg you bet! The PR is merged if you want to verify on staging and let me know if you see anything else you think should change.

**Comment by amysueg** [comment]
Looks good. Thanks.
Would the smaller-sized cards be useful either when resizing to a smaller size page or as the default view?

**Comment by michael-coker** [comment]
@amysueg I'm not sure what you mean. Do you mean keeping the cards from growing beyond some sort of width? For reference, here are [cards on patternfly](https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/cards.html) if you can use any of those as a reference point for what you're describing on the connections page.

**Comment by michael-coker** [comment]
Ahh, I don't really have a strong opinion one way or another. I do think the cards are a little big and have a lot of white space, though that's not necessarily a bad thing. Though to fit the icon, title, description, and space for an error message, we would probably have to revisit the UI for the card. One option could be to simply drop the "description" from the card and size the image down a bit.

Here's a quick mockup of smaller cards

![screen shot 2018-06-13 at 11 45 07 am](https://user-images.githubusercontent.com/35148959/41365533-40339fbc-6eff-11e8-86f1-c26e21bfecca.png)

And here's where the error message is currently shown (inside the card)

<img width="760" alt="screen shot 2018-06-13 at 11 46 03 am" src="https://user-images.githubusercontent.com/35148959/41365582-5e622602-6eff-11e8-87f7-6f83820aa436.png">

@sjcox-rh what do you think?

**Comment by amysueg** [comment]
Responsive behavior is fixed and so I'm closing this issue.
Will open a separate issue to think about revisiting the card size for better use of space.
