### ISSUE TITLE
FTP/SFTP middle connections should offer download action

### ISSUE THREAD

**Issue by TovaCohen** [syndesisio/syndesis#2233]
## This is a...

<pre><code>
[x ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
In an integration, as a citizen integrator, I want to connect to an FTP or SFTP server in the middle of the integration to download files. But when I add an FTP or SFTP connection in the middle of an integration, I am offered only the upload action. 

## Expected behavior
When I add an FTP or SFTP connection in the middle of an integration, the Download action should be available for me to choose. 

## Tasks involved / Steps to Reproduce

1. Create an FTP connection.
2. Edit an integration to add a middle connection.
3. Select the FTP connection.
4. Only the Upload action is available.

**Comment by oscerd** [comment]
I don't think so, the download action is only a From pattern. So it can't be used as middle connection. @rhuss what do you think?

**Comment by oscerd** [comment]
Closed as not a problem.

**Comment by TovaCohen** [comment]
Andrea, could help me understand this? Just for my own understanding. What does it mean to say that Download is "only a From pattern"?  I'm wondering if download in the middle of an integration does not make sense because the integration might need to wait for the file/directory of interest. thanks!

**Comment by oscerd** [comment]
Download is a consumer action, it means that you can have a download only when as a starting connection of an integration. Having it as middle connection would mean use that action as a producer action (a To pattern) and it's not like that in Camel.

**Comment by TovaCohen** [comment]
Oh, okay, that makes sense. Thanks!

**Comment by oscerd** [comment]
This can have sense in a pure Camel integration, where you may have the creation of a folder or something like that and a consumer from that folder. Doing something like this in syndesis would mean have two different integrations and trigger the second one only when the first one finished: not something feasible actually.

**Comment by TovaCohen** [comment]
Again, just for my own understanding ...  In a pure Camel integration, are you saying that I could have something like this:
A consumer endpoint starts integration A. 
Somewhere before the producer endpoint that completes integration A, there is another consumer endpoint that feeds additional data into integration A. For example, this might be an FTP endpoint that downloads from a particular folder. 
Thanks for the help in understanding this. I really appreciate it.
