### ISSUE TITLE
FTP/SFTP connection configuration parameters appear in random order

### ISSUE THREAD

**Issue by TovaCohen** [syndesisio/syndesis#2234]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
When I select the FTP or SFTP connector in order to create a connection, the connection configuration parameters appear in a random order. Luca tells me that there is no fixed order for displaying the properties and they may get reordered.  For the FTP connector, only one parameter is required. For the SFTP connector, only 3 parameters are required. The requred parameters should appear first, followed by the other parameters, which all have default values. And they should appear in some kind of logical order. 

## Expected behavior

The order of the parameters should be something like this:

Host
Port
User name
Password
Connect timeout
Reconnect delay
Maximum reconnect attempts
Binary file transfer mode
Passive connection mode
Disconnect from the server after use
Data timeout
## Screenshot
This is what I am seeing in the staging site now:
![image](https://user-images.githubusercontent.com/25067106/38335602-d4fec1c6-382c-11e8-87d0-4d933e7a980b.png)

## Tasks involved / Steps to Reproduce

1. Click "Connections".
2. Click "Create Connection"
3. Click the FTP or SFTP connector.

**Comment by oscerd** [comment]
Actually both FTP and SFTP don't have any order field in their JSON definition

https://github.com/syndesisio/syndesis/blob/master/app/connector/ftp/src/main/resources/META-INF/syndesis/connector/ftp.json

https://github.com/syndesisio/syndesis/blob/master/app/connector/sftp/src/main/resources/META-INF/syndesis/connector/sftp.json
