### ISSUE TITLE
MQTT connector: params alignment with other protocols

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis#2237]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
Currently MQTT requires only one parameter `brokeUrl`. There's e.g. no way to specify `username, password, skipCertificate, ...`.

https://github.com/syndesisio/syndesis/blob/c9760574058f36a8ecd7c8f4d81c39b9f7e32a53/app/connector/mqtt/src/main/resources/META-INF/syndesis/connector/mqtt.json#L19-L31

In contrast with:
https://github.com/syndesisio/syndesis/blob/c9760574058f36a8ecd7c8f4d81c39b9f7e32a53/app/connector/activemq/src/main/resources/META-INF/syndesis/connector/activemq.json#L16-L149

Shouldn't this be aligned with other connectors for different protocols?

## Expected behavior
AMQ(openwire), AMQP and MQTT are more uniform and share common base of parameters.

Cc @dhirajsb @paoloantinori

**Comment by oscerd** [comment]
These are the parameters supported

https://github.com/apache/camel/blob/camel-2.21.x/components/camel-mqtt/src/main/docs/mqtt-component.adoc

**Comment by paoloantinori** [comment]
changed this to a feature request

**Comment by dsimansk** [comment]
@paoloantinori is it still going to be targeted for GA as feature request? I'm scared that we lack a lot of config options in comparison to other JMS connectors.

**Comment by paoloantinori** [comment]
no, it's not targeted for GA

If you have a list of parameters that you need re-exposed and @oscerd can add them quickly, it might get in, otherwise it will come with version 7.1

**Comment by dsimansk** [comment]
@paoloantinori @oscerd ideally I'd like to configure the same params as AMQ and AMQP have. From the `camel-mqtt` list, there are: 

- username
- password
- clientId

In addition:
- skipCertificateCheck
- brokerCertificate
- clientCertificate

**Comment by dsimansk** [comment]
@paoloantinori @oscerd anything we could do about those parameters? The connector is not very usable otherwise.

**Comment by oscerd** [comment]
These are the available parameters https://github.com/apache/camel/blob/camel-2.21.x/components/camel-mqtt/src/main/docs/mqtt-component.adoc

**Comment by dsimansk** [comment]
@oscerd I've stated the list in my [previous comment](https://github.com/syndesisio/syndesis/issues/2237#issuecomment-380709899). Anything else that I could add or describe in more details?

**Comment by oscerd** [comment]
What we can add is clientId,username and password, nothing else, since the component doesn't provide options for that. @paoloantinori do I have to add these options?

**Comment by paoloantinori** [comment]
This looks narrow enough to look like a quickie. Go for it.

**Comment by oscerd** [comment]
just for information, the mqtt connector is currently using camel-paho as @dsimansk correctly found. Maybe we need to document this info somewhere.
