### ISSUE TITLE
Extensions - jdbc driver import doesn't work

### ISSUE THREAD

**Issue by Stefan365** [syndesisio/syndesis#2243]
## This is a...
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request

## The problem
After adding extension with required jdbc driver, this is not loaded properly by SQL connector.

## Expected behavior
After adding extension with required jdbc driver, this driver is available for SQL connector.

## Screenshot
![driver_unavailable](https://user-images.githubusercontent.com/2714974/38362320-a9f3b938-38d0-11e8-8404-0bbddc28af0e.png)

## Request and Response Data
URL: .../api/v1/connectors/sql/verifier

payload:
{url: "jdbc:oracle:thin:@oracle-12cr1.hosts.mwqe.eng.bos.redhat.com:1521:dballo", user: "dballo15",…}
method: POST
response:
[{"status":"ERROR","scope":"PARAMETERS","errors":[{"code":"ILLEGAL_PARAMETER_VALUE","description":"No suitable driver found for jdbc:oracle:thin:@oracle-12cr1.hosts.mwqe.eng.bos.redhat.com:1521:dballo","parameters":["url"]}]}]

syndesis-meta log:
[meta.log](https://github.com/syndesisio/syndesis/files/1880070/meta.log)

## Tasks involved / Steps to Reproduce

1. download oracle driver ojdbc7.jar to: syndesis-extensions/syndesis-library-jdbc-driver/lib, (of the project git@github.com:syndesisio/syndesis-extensions.git)
2. in /syndesis-library-jdbc-driver/pom.xml change jdbc-driver systemPath to:
```
<systemPath>${project.basedir}/lib/ojdbc7.jar</systemPath>
```
2. mvn clean install
3. add target/syndesis-library-jdbc-1.0.0.jar file to Syndesis->Customizations->Extensions->Import Extension
4. wait until syndesis-meta pod has been recreated.
5. validate SQL connection to oracle DB: 
(e.g:        Username: dballo15
               Password: dballo15
      atabase Name: dballo
   Connection URL: jdbc:oracle:thin:@oracle-12cr1.hosts.mwqe.eng.bos.redhat.com:1521:dballo
 )

**Comment by Stefan365** [comment]
@KurtStam is this really bug, or am I doing st. wrong?

**Comment by paoloantinori** [comment]
can you please add server logs?

**Comment by Stefan365** [comment]
@paoloantinori kindly see meta.log above. I don't errors in other pods.

**Comment by KurtStam** [comment]
@Stefan365 So the error suggests that the driver was /not/ added to the verifier/meta classpath. Can you check the meta pods /deployments/opt/ directory to check the extension was uploaded? Can you check it's content too?

**Comment by Stefan365** [comment]
@KurtStam I don't see "/deployments/opt" folder. This is my content of /deployments:
```
config	derby.log  ext	meta-1.3-SNAPSHOT.jar  run-env.sh  run-java.sh
```

**Comment by Stefan365** [comment]
this is content of ...jar:
     0 Thu Apr 05 10:38:46 UTC 2018 META-INF/
   218 Thu Apr 05 10:38:46 UTC 2018 META-INF/MANIFEST.MF
     0 Thu Apr 05 10:38:42 UTC 2018 META-INF/syndesis/
   294 Thu Apr 05 10:38:46 UTC 2018 META-INF/syndesis/syndesis-extension-definition.json
     0 Thu Apr 05 10:38:48 UTC 2018 META-INF/maven/
     0 Thu Apr 05 10:38:48 UTC 2018 META-INF/maven/io.syndesis.extensions/
     0 Thu Apr 05 10:38:48 UTC 2018 META-INF/maven/io.syndesis.extensions/syndesis-library-jdbc/
  4295 Thu Apr 05 10:38:26 UTC 2018 META-INF/maven/io.syndesis.extensions/syndesis-library-jdbc/pom.xml
   129 Thu Apr 05 10:38:46 UTC 2018 META-INF/maven/io.syndesis.extensions/syndesis-library-jdbc/pom.properties
     0 Thu Apr 05 10:38:46 UTC 2018 lib/
3397734 Thu Apr 04 15:15:22 UTC 2013 lib/jdbc-driver-1.0.jar

**Comment by KurtStam** [comment]
@Stefan365 so the `ojdbc7.jar` is missing then right?

**Comment by Stefan365** [comment]
@KurtStam Actually I was trying different ways, as I was not successful. One way was to rename (just rename) "ojdbc7.jar" to "jdbc-driver-1.0.jar" - and since it was my last attempt, o7.jar its not in list. But I've tried it with ojdbc7.jar - as per steps to reproduce, and I wasn't successful as well. I will try it again without renaming and let you know.

**Comment by Stefan365** [comment]
@KurtStam exactly the same results.

**Comment by KurtStam** [comment]
@Stefan365 So we have established then that the extension jar is not build correctly? If so then we can focus on just that.

**Comment by Stefan365** [comment]
@KurtStam imho extension jar was build correctly. the content of above mentioned "jdbc-driver-1.0.jar" and "ojdbc7.jar" are identical

**Comment by KurtStam** [comment]
@Stefan365 and the `META-INF/syndesis/syndesis-extension-definition.json` looks something like this:

```
{
  "schemaVersion" : "v1",
  "name" : "Example JDBC Driver Library",
  "description" : "Syndesis Extension for adding a custom JDBC Driver",
  "extensionId" : "io.syndesis.extensions:syndesis-oracle-jdbc",
  "version" : "8.0.0",
  "tags" : [ "jdbc-driver" ],
  "extensionType" : "Libraries"
}
```

**Comment by KurtStam** [comment]
@Stefan365 I will try to reproduce with the latest code. In the meantime can you check when your meta pod was (re)started? Hopefully after you uploaded the extension and after kill the meta pod so it  restarts, and then try again?

**Comment by Stefan365** [comment]
@KurtStam my metadata pod was restarted two hours ago and yes - immediately after I've uploaded extension. I'm not sure whether I understood correctly second part of your last sentence: should I restart meta pod now by killing it?

**Comment by KurtStam** [comment]
@Stefan365 Yes, just to make sure it's put on the classpath, although the restart you mentioned should have done that.

**Comment by Stefan365** [comment]
@KurtStam I did it, but problem remains. For java startup command - I don't know what exactly you mean.  
[meta2.log](https://github.com/syndesisio/syndesis/files/1880804/meta2.log)

**Comment by KurtStam** [comment]
@nicolaferraro It all looks good to me, but it's definitely not on the classpath. Any ideas what could have broken this?

**Comment by nicolaferraro** [comment]
I see from the startup logs of the meta pod that the lib is listed with the full path, while I remember that the spring-boot loader requires paths relative to the loader home. The script was changed to fix another error. That may be the problem. I'm going to check...

**Comment by nicolaferraro** [comment]
Indeed, that was the problem. I've opened #2263 to fix.

**Comment by Stefan365** [comment]
@KurtStam @nicolaferraro 
it seems this bug is somehow back.
at least has similar behavior (in meta pod/ext folder there is suitable driver, but validation fails)

Here is new meta-pod log:
[meta_reopen.log](https://github.com/syndesisio/syndesis/files/1987917/meta_reopen.log)

**Comment by nicolaferraro** [comment]
I don't see the line with the list of extensions (`Using the following extensions in the spring-boot loader path ...`, printed also for empty list) at the beginning of the log file.

May be a problem in the CR build.

**Comment by nicolaferraro** [comment]
It has to do with the way the GA image is built. The GA image has the following content in `deployments`:

```
[jboss@e5608ddefc61 /]$ cd /deployments/
[jboss@e5608ddefc61 deployments]$ ls
data  runtime.jar
```

While the standard image is like:
```
[jboss@c965757f8c59 ~]$ cd /deployments/
[jboss@c965757f8c59 deployments]$ ls
meta-1.3.6-20180509.jar  run-env.sh  run-java.sh
```

I've just built it using: 
```
# clean build
cd app/meta
mvn clean install -N -DskipTests -P image -Dfabric8.mode=kubernetes
```

The issue is that the `run-env.sh` is what puts the extensions in the classpath and it's missing in the GA image.

Maybe @djcoleman knows more about the build process. It seems to me we're building GA images in a different way.

**Comment by nicolaferraro** [comment]
I checked the image: `brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/fuse7/fuse-ignite-meta:1.0-1`

**Comment by Stefan365** [comment]
after this:
https://issues.jboss.org/browse/ENTESB-8131
it works.
