### ISSUE TITLE
Imported integration has no status

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#2245]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

After importing integration, there is no status of that integration in integration details or list.

## Expected behavior

I would expect unpublished integration status after importing.

## Tasks involved / Steps to Reproduce

1. import integration, I used this one
[Integration_import_export_test-export.zip](https://github.com/syndesisio/syndesis/files/1880333/Integration_import_export_test-export.zip)

2. check integration status - there is none

**Comment by gashcrumb** [comment]
Yep, that looks to be the case, probably given that we broke out 'draft' into a separate flag vs a state.

**Comment by gashcrumb** [comment]
I can add a draft indicator on the list page as well, but also when importing the state flags should get set as part of the process of importing, shouldn't they @chirino?

**Comment by gashcrumb** [comment]
Yeah, the other problem is the status flags on the integration can come back completely unset which is wrong IMO.

**Comment by gashcrumb** [comment]
@lburgazzoli thoughts on this one BTW?

**Comment by lburgazzoli** [comment]
Do we have a json example of what was working before and not anymore ? It may be a side effect of the upgrade epic but I'm not much aware about import/export stuff

**Comment by gashcrumb** [comment]
Just looking at the `model.json` in the exported .zip file and I don't see `currentState` or `desiredState` set in there at all.  So I guess the import just doesn't set those fields to anything, but it should probably set them to `Unpublished` if the fields aren't set at all.
