### ISSUE TITLE
Update URLs for links to customer portal user doc

### ISSUE THREAD

**Issue by TovaCohen** [syndesisio/syndesis#2278]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
The GA URLs for  Ignite user documentation on the Red Hat customer portal will be different than they were for the technology preview releases. The URLs no longer contain "jboss" and no longer contain "-tp". 

## Expected behavior
For GA, these are the correct URLs:

https://access.redhat.com/documentation/en-us/red_hat_fuse/7.0/html-single/integrating_applications_with_ignite/

https://access.redhat.com/documentation/en-us/red_hat_fuse/7.0/html-single/ignite_sample_integration_tutorials/

@fbolton could you please confirm that these URLs will be correct for GA? Thanks!

In the UI, the URLs need to be updated for
- Selecting Help > Sample Integration Tutorials 
- Selecting  Help > User Guide
- Settings  page text ".. See the documentation for help."  This URL will be:

https://access.redhat.com/documentation/en-us/red_hat_fuse/7.0/html-single/integrating_applications_with_ignite/#obtaining-authorization-to-access-applications

**Comment by TovaCohen** [comment]
It looks like the updates are needed in this files:
app/ui/src/app/app.component.ts
app/ui/src/app/customizations/tech-extensions/tech-extensions-list.component.html
app/ui/src/app/settings/oauth-apps/oauth-apps.component.html

Can this be assigned to me and I will update the files and submit a PR?

**Comment by gashcrumb** [comment]
Done!  Actually you should be able to self-assign issues too, afaik you have the power...

**Comment by deeleman** [comment]
The links provided are language-specific so it makes sense to make those depend on the active i18n dictionary in use.

Unless @TovaCohen poses objections, I'd like to reassign this one to myself.

**Comment by TovaCohen** [comment]
Be my guest, Pablo!  Thanks!

**Comment by deeleman** [comment]
> The links provided are language-specific so it makes sense to make those depend on the active i18n dictionary in use.

This will also prevent having the same link replicated across 3 (and probably more) files in the future, which is a code smell.

**Comment by TovaCohen** [comment]
Also, I confirmed that the links I provided in the description are correct.
