### ISSUE TITLE
Uploading an icon when creating an API connector is not working

### ISSUE THREAD

**Issue by TovaCohen** [syndesisio/syndesis#2287]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
I'm working with the staging site: https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/
When I upload the todo app swagger.json file (by specifying the URL) and I upload an icon in the last review step before the connector is created, the icon I uploaded does not  appear.

## Expected behavior
When I upload an icon as part of creating an API connector then I expect the icon to appear in the details for the new API connector. 

## Tasks involved / Steps to Reproduce

1. Click "Create API Connector"
2. Select use a URL and paste https://todo-syndesis-staging.b6ff.rh-idev.openshiftapps.com/swagger.json
3. Next > Next > Next
4. Click Browse and select a dropbox icon, which was just an icon I found for experimenting. 
5. The dropbox icon appears: 
![image](https://user-images.githubusercontent.com/25067106/38500477-813246d0-3bd8-11e8-93ee-2fad723aed19.png)
6. Click "Create Connector". Then click the entry for the new connector to see its details. 
7. The icon does not appear:
![image](https://user-images.githubusercontent.com/25067106/38500640-005aa970-3bd9-11e8-8f5d-7a73041c4912.png)

**Comment by dsimansk** [comment]
@mastepan is it a regression of a similar issue you've seen before?

**Comment by mastepan** [comment]
@dsimansk Depends... Functionally yes. In the code... I can't say because there wasn't an icon generator when I reported this in the past.

**Comment by dsimansk** [comment]
@zregvart in a request sent from wizard submit page to `/connectors/custom`, I can't see image included in a multipart. Might this be an issue? 

@paoloantinori this is another one that impacts user experience and should be rather quick to fix, wdyt?

```
------WebKitFormBoundarymRmu90M6sbthnHTL
Content-Disposition: form-data; name="specification"

false
------WebKitFormBoundarymRmu90M6sbthnHTL
Content-Disposition: form-data; name="connectorSettings"; filename="connectorSettings"
Content-Type: application/json


------WebKitFormBoundarymRmu90M6sbthnHTL--
```

**Comment by zregvart** [comment]
I'll take a look at this one tomorrow.

**Comment by zregvart** [comment]
Just tried to reproduce this again without success, I see that the `POST api/v1/connectors/custom` is getting proper multipart data:

```
-----------------------------4315208671805512933903870609
Content-Disposition: form-data; name="specification"; filename="reverb-swagger.yaml"
Content-Type: application/x-yaml

swagger: '2.0'
info:
...

-----------------------------4315208671805512933903870609
Content-Disposition: form-data; name="icon"; filename="reverb-r-logo-2017_omsytb.png"
Content-Type: image/png

PNG
```

**Comment by dsimansk** [comment]
@zregvart I've managed to narrow it down a bit. The behaviour of "not uploading an icon" only occurs when you provide swagger file via URL reference. When the swagger file is uploaded from fs everything works fine with icon displayed.
