### ISSUE TITLE
Editing an integration does no longer work

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#2291]
## This is a...

<pre><code>
[ ] Feature request
[*] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
When editing an integration the integration becomes invalid. Datamappings no longer work, config is wrong.

## Expected behavior
That it work work

## Tasks involved / Steps to Reproduce

1. Create an integration with data mapping
2. Publish and then try to edit the data mapping
3. The integration won't quite work anymore while editing the user is forced to start over.

**Comment by lburgazzoli** [comment]
Looks similar to #2247

**Comment by KurtStam** [comment]
<img width="1059" alt="screen shot 2018-04-09 at 12 55 33 pm" src="https://user-images.githubusercontent.com/35576/38511193-5bec542a-3bf5-11e8-893b-12c3fbede7bf.png">

**Comment by lburgazzoli** [comment]
@KurtStam can you test it againsta the latest master ?

**Comment by paoloantinori** [comment]
@KurtStam  I'm assigning this to you to have confirmation if it's fixed as expected. If that's not the case, please feel free to re-assign.

Mind that this has blocker priority
