### ISSUE TITLE
Going to "support" breaks the toolbar styling on other pages

### ISSUE THREAD

**Issue by michael-coker** [syndesisio/syndesis#2294]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
If you go to `/support` (from the help link in the toolbar), the toolbar border and box shadow goes away on other pages.

## Expected behavior
Going to `/support` shouldn't impact styles on other pages.

## Tasks involved / Steps to Reproduce
1. Click the help icon in the top/right and choose "support"
2. Click on either "connections," "integrations," or "customizations"
3. Note the lack of a bottom border/shadow on the toolbar.

Possibly related to https://github.com/syndesisio/syndesis/issues/2276

cc @dongniwang

**Comment by michael-coker** [comment]
@gashcrumb @KurtStam looks like this is a problem with any component's CSS that uses `:ng-deep` at the root level of the CSS (not wrapped in `:host` or some class or whatever that is unique to that component). If you just define `:ng-deep .some-element { background: red; }` in a component, after loading that component (and that CSS), if you click around, anywhere else in the app that where `.some-element` exists will have a red background. Is that behavior expected?

Submitted a PR to address this - https://github.com/syndesisio/syndesis/pull/2410

**Comment by KurtStam** [comment]
@michael-coker trying to get my head around this, do you mean '::ng-deep' (two colons?)

**Comment by michael-coker** [comment]
@KurtStam doh! Typo 🙂Yup

**Comment by KurtStam** [comment]
or 
<img width="420" alt="screen shot 2018-04-17 at 12 26 20 pm" src="https://user-images.githubusercontent.com/35576/38883331-93a8dae6-423a-11e8-98c8-a03e1239cd6c.png">
versus
<img width="397" alt="screen shot 2018-04-17 at 12 26 50 pm" src="https://user-images.githubusercontent.com/35576/38883349-a0a22ab8-423a-11e8-9185-ae20439c5823.png">

**Comment by KurtStam** [comment]
@michael-coker to answer your question: I think it is as  `::ng-deep` is meant to cascade down into all child elements. I think we want to content it within the component, which means we need to combine `:host ::ng-deep` as you did in the PR
