### ISSUE TITLE
Fuse Online branding missing in UI

### ISSUE THREAD

**Issue by kcbabo** [syndesisio/syndesis#2296]
## This is a...
<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
Red Hat Fuse Online logo is missing from top navbar on Ignite eval cluster.  I provisioned my account yesterday, so should be using TP4 build.

## Expected behavior
Red Hat Fuse Online logo is present to the left of Ignite text in navbar.

**Comment by dsimansk** [comment]
@kcbabo fixed in the fuse-ignite template. All newly provisioned users should see the icon. If you want to try it out modify ConfigMap `syndesis-ui-config`. I'll create a PR later today to have it properly fixed on master branch also.

```
"iconWhiteBg": "assets/images/FuseOnlineLogo_Black.svg",
"iconDarkBg": "assets/images/FuseOnlineLogo_White.svg",
```
