### ISSUE TITLE
FTP Connection, UX Opportunities

### ISSUE THREAD

**Issue by JimTyrrell** [syndesisio/syndesis#2297]
The Create and Edit page should have the fields in the same order.
The starting order should probably be:
host name
username
password

The Edit page should have a Validate Button always available w/o having to click the edit button.

The validate Button should be in the same place for both pages (create and edit).

Stretch Goal:
The Validate button should be on every Connection in the same place.

Should this editor map to the primitives around editing content or artifacts that exist in (OpenShift.io, Decision Central, something else).

The popup Is, should tell you why I need to do something.  Why binary mode, why or why not do I choose this.
Why or why not do I do passive. etc
<img width="252" alt="screen shot 2018-04-09 at 12 42 50 pm" src="https://user-images.githubusercontent.com/4389749/38516173-9c79bbd8-3bf3-11e8-913c-449f7498543a.png">

**Comment by gashcrumb** [comment]
For the field ordering I believe it was done in this PR -> https://github.com/syndesisio/syndesis/pull/2239 which I think came after the build that @JimTyrrell is looking at.  I'll try and get a screenshot posted to this issue, there's other things in the description that should be tackled as well.

**Comment by dongniwang** [comment]
The validate button on the connection details page

<img width="980" alt="screen shot 2018-04-09 at 3 41 27 pm" src="https://user-images.githubusercontent.com/24943812/38519053-8da3c7ca-3c0c-11e8-9fad-7d5598bea8cc.png">

**Comment by gashcrumb** [comment]
I think the staging instance has the PR in place, so the fields are organized like so:

<img width="551" alt="screenshot 2018-04-09 16 23 07" src="https://user-images.githubusercontent.com/351660/38521071-92d45010-3c12-11e8-9664-97a30a0d25e8.png">

**Comment by JimTyrrell** [comment]
I would argue that the port info should be down at least 1 row.
Host
UserName
Password 

Should probably be the first 3 fields.

Beyond that I am not sure what is required and in what order.

Do we want to have a advanced "button" to show things that are typically not going to be needed to simplify what users have to decide before entering in values?

**Comment by oscerd** [comment]
It's not a problem to change the order, let me know and I'll provide a PR for this.
