### ISSUE TITLE
Activity Tab not showing step details.

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis#2298]
## This is a...

<pre><code>
[ ] Feature request
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
Step details are not shown.

## Expected behavior
Steps activity should be displayed

## Screenshot
![syndesis](https://user-images.githubusercontent.com/103255/38516452-2f921c24-3c05-11e8-8d78-b05d52e0d664.jpg)

**Comment by chirino** [comment]
Runtime integrations are logging messages like:

`
{"exchange":"i-L9fijAW9Jy_fL2cvxWQz","status":"begin"}

{"exchange":"i-L9fijAY9Jy_fL2cvxWSz","step":"-L9fdVqYTmxXt-nl6YXB","id":"i-L9fijAY9Jy_fL2cvxWUz","message":"Body: [{\"count\":215}] before"}

{"exchange":"i-L9fijAW9Jy_fL2cvxWQz","status":"done","failed":false}
`

Notice the 2nd line's exchange is not i-L9fijAW9Jy_fL2cvxWQz.  This is why the step is not part of the shown exchanges in the UI.

**Comment by lburgazzoli** [comment]
What should be the right value ?

**Comment by lburgazzoli** [comment]
@chirino can you add some details about the integration you are using ? a simple db2db integrations reports only begin and end to me:

    i-db2db-1-nbt8n i-db2db {"exchange":"i-L9i19IhPEXGffzly0z-z","status":"begin"}
    i-db2db-1-nbt8n i-db2db {"exchange":"i-L9i19IhPEXGffzly0z-z","status":"done","failed":false}

**Comment by lburgazzoli** [comment]
I do not know all the details of this feature but below is what we get from a simple db2db:

```
i-db2db-2-25fpb i-db2db {"exchange":"i-L9i6paBcTysADYRM2DSz","status":"begin"}
i-db2db-2-25fpb i-db2db {"exchange":"i-L9i6paDcTysADYRM2DUz","step":"-L9i5bChdzAqvhGhZCqS","id":"i-L9i6paDcTysADYRM2DXz","message":"Body: [{\"lead_source\":\"db\"}] "}
i-db2db-2-25fpb i-db2db {"exchange":"i-L9i6paIcTysADYRM2DZz","step":"-L9i5bChdzAqvhGhZCqS","id":"i-L9i6paJcTysADYRM2Dbz","message":"Body: [{\"lead_source\":\"db\"}] "}
i-db2db-2-25fpb i-db2db {"exchange":"i-L9i6paMcTysADYRM2Ddz","step":"-L9i5bChdzAqvhGhZCqS","id":"i-L9i6paMcTysADYRM2Dgz","message":"Body: [{\"lead_source\":\"db\"}] "}
i-db2db-2-25fpb i-db2db {"exchange":"i-L9i6paQcTysADYRM2Diz","step":"-L9i5bChdzAqvhGhZCqS","id":"i-L9i6paRcTysADYRM2Dlz","message":"Body: [{\"lead_source\":\"db\"}] "}
i-db2db-2-25fpb i-db2db {"exchange":"i-L9i6paZcTysADYRM2Dnz","step":"-L9i5bChdzAqvhGhZCqS","id":"i-L9i6pa_cTysADYRM2Dqz","message":"Body: [{\"lead_source\":\"db\"}] "}
i-db2db-2-25fpb i-db2db {"exchange":"i-L9i6paccTysADYRM2Dsz","step":"-L9i5bChdzAqvhGhZCqS","id":"i-L9i6paccTysADYRM2Dvz","message":"Body: [{\"lead_source\":\"db\"}] "}
i-db2db-2-25fpb i-db2db {"exchange":"i-L9i6palcTysADYRM2Dxz","step":"-L9i5bChdzAqvhGhZCqS","id":"i-L9i6pamcTysADYRM2E-z","message":"Body: [{\"lead_source\":\"db\"}] "}
i-db2db-2-25fpb i-db2db {"exchange":"i-L9i6papcTysADYRM2E1z","step":"-L9i5bChdzAqvhGhZCqS","id":"i-L9i6papcTysADYRM2E4z","message":"Body: [{\"lead_source\":\"db\"}] "}
i-db2db-2-25fpb i-db2db {"exchange":"i-L9i6patcTysADYRM2E6z","step":"-L9i5bChdzAqvhGhZCqS","id":"i-L9i6paucTysADYRM2E9z","message":"Body: [{\"lead_source\":\"db\"}] "}
i-db2db-2-25fpb i-db2db {"exchange":"i-L9i6paycTysADYRM2EBz","step":"-L9i5bChdzAqvhGhZCqS","id":"i-L9i6paycTysADYRM2EEz","message":"Body: [{\"lead_source\":\"db\"}] "}
i-db2db-2-25fpb i-db2db {"exchange":"i-L9i6pb2cTysADYRM2EGz","step":"-L9i5bChdzAqvhGhZCqS","id":"i-L9i6pb3cTysADYRM2EJz","message":"Body: [{\"lead_source\":\"db\"}] "}
i-db2db-2-25fpb i-db2db {"exchange":"i-L9i6pbAcTysADYRM2ELz","step":"-L9i5bChdzAqvhGhZCqS","id":"i-L9i6pbFcTysADYRM2EOz","message":"Body: [{\"lead_source\":\"db\"}] "}
i-db2db-2-25fpb i-db2db {"exchange":"i-L9i6pbIcTysADYRM2EQz","step":"-L9i5bChdzAqvhGhZCqS","id":"i-L9i6pbJcTysADYRM2ETz","message":"Body: [{\"lead_source\":\"db\"}] "}
i-db2db-2-25fpb i-db2db {"exchange":"i-L9i6pbUcTysADYRM2EVz","step":"-L9i5bChdzAqvhGhZCqS","id":"i-L9i6pbVcTysADYRM2EYz","message":"Body: [{\"lead_source\":\"db\"}] "}
i-db2db-2-25fpb i-db2db {"exchange":"i-L9i6pbjcTysADYRM2E_z","step":"-L9i5bChdzAqvhGhZCqS","id":"i-L9i6pbkcTysADYRM2Ecz","message":"Body: [{\"lead_source\":\"db\"}] "}
i-db2db-2-25fpb i-db2db {"exchange":"i-L9i6paBcTysADYRM2DSz","status":"done","failed":false}
```
So because the result of a slect is split into multiple records, we have multiple exchnages being generated, how this should be handled ?

**Comment by chirino** [comment]
Need all the steps of an activity execution to report the same activity id

**Comment by chirino** [comment]
Sorry I meant exchange id

**Comment by chirino** [comment]
Also the activity status steps are not being logged.  The log message was occuring when you call done on:
https://github.com/syndesisio/syndesis/blob/master/app/integration/runtime/src/main/java/io/syndesis/integration/runtime/logging/StepDoneTracker.java#L53
