### ISSUE TITLE
Please add an MBean operation to allow users to modify camel log level from jolokia/hawtio

### ISSUE THREAD

**Issue by sjavurek** [syndesisio/syndesis#2299]
## This is a...

<pre><code>
[X ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Debug logging is incredibly handy particularly in Camel for troubleshooting issues. At present there is no way to update the log levels without restarting a pod which may cause the underlying problem to clear. 

This is troubleshooting request. 

## Expected behavior

Users/engineers will be able to change  log levels automatically. Automation of log gather is also being implemented and we can do this under the covers for a few minutes as well. 

Users may update log leve
## Tasks involved / Steps to Reproduce

1.
2.
3.
4.

**Comment by paoloantinori** [comment]
@oscerd @lburgazzoli  is this something already present at Camel level?

**Comment by lburgazzoli** [comment]
spring boot has an endpoint (currently disabled) to change the logging levels
