### ISSUE TITLE
Upgrade to Spring Boot 1.5.13

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#2303]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
[X] Task
</code></pre>

## The problem

We are now using Spring Boot 1.5.8 but the latest release is 1.5.12 which among other things, fixes some CVE.

@paoloantinori @gashcrumb @chirino Should we upgrade before GA ?

**Comment by aileenc** [comment]
We are currently using 1.5.10 in FIS to align with RHOAR

**Comment by oscerd** [comment]
Also Camel 2.21.0 is based on 1.5.10, while 2.21.1 will be based on 1.5.11

**Comment by lburgazzoli** [comment]
because of the CVEs does it make sense to upgrade the whole stack to 1.5.12 ?

**Comment by chirino** [comment]
Yes.  If upstream does not do it, it will occur in the pipeline builds. I think it’s better if get ahead and upgrade your n the upstream.

**Comment by chirino** [comment]
Lets go with latest SB 1.5.x version.

**Comment by oscerd** [comment]
This should be closed, since we are using SB 1.5.13 now. 

https://github.com/syndesisio/syndesis/blob/master/app/pom.xml#L63
