### ISSUE TITLE
Invocation time selection not uniform for connectors in integration

### ISSUE THREAD

**Issue by tplevko** [syndesisio/syndesis#2312]
## This is a...

<pre><code>
[ x ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

I noticed that the improvement in time period selection for DB connector when creating new integration. The same would be really nice to have for other connectors, in my case I noticed this for S3 connector.

## Expected behavior

It would be nice to have all the time period selectors uniform. 

## Screenshot

S3: 
![s3_connector](https://user-images.githubusercontent.com/4180208/38555295-e5a3bea8-3cc5-11e8-8f66-b5889d4308ba.png)
DB:
![db_connector](https://user-images.githubusercontent.com/4180208/38555302-edfaf6de-3cc5-11e8-9065-fd3cfcafbf9b.png)

**Comment by gashcrumb** [comment]
Fix here is to change the control type for that field to `duration`.
