### ISSUE TITLE
"Stop Integration" text on menu item should be "Unpublish" in integration history

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#2318]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

On the active version in the history table the menu reads "Stop Integration", this should probably be "Unpublish" to be consistent with all the other places this menu item shows up.

<img width="640" alt="screenshot 2018-04-10 10 39 04" src="https://user-images.githubusercontent.com/351660/38563768-a4d77ad2-3cab-11e8-905c-904fe1793039.png">

To reproduce you need to publish an integration, then check the integration history table and click on the dotty thing on the line that has the active version.

**Comment by dongniwang** [comment]
Yes, agreed. Decision is to change "Stop Integration" to "Unpublish". Is there a reason we went for "Stop Integration" at the first place...

cc: @TovaCohen @amysueg @sjcox-rh

**Comment by TovaCohen** [comment]
I noticed this also, so thanks Stan for creating the issue. I think "Stop Integration" is just a holdover from before we standardized on Publish and Unpublish. 
So yes, I agree, Stop Integration should be changed to Unpublish.

**Comment by dongniwang** [comment]
Great! Thanks for the quick feedback @TovaCohen. I'll update the design then.
