### ISSUE TITLE
Integration List - "Draft" label and "Configuration Required" notification does not line up properly 

### ISSUE THREAD

**Issue by dongniwang** [syndesisio/syndesis#2333]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

In the Integration List View, when the "Draft" label and Configuration Required notification both appear in a row, the Configuration Required notification is being pushed off the row. 

## Expected behavior

Configuration Required notification should have its own individual column in a row, and align with the rest of the row content. 

Also, with the new design (currently under design review), UX is proposing to remove the "Draft" label. 

## Screenshot

<img width="1434" alt="screen shot 2018-04-10 at 3 10 52 pm" src="https://user-images.githubusercontent.com/24943812/38578731-c5c246c4-3cd2-11e8-8290-ee45c92d29a4.png">

## Tasks involved / Steps to Reproduce

1.
2.
3.
4.

**Comment by dongniwang** [comment]
@gashcrumb - as part of the [Upgrade](https://github.com/syndesisio/syndesis/issues/1128) story, I'm proposing to remove the entire "Draft" column in the list view.

**Comment by dongniwang** [comment]
Not sure the design updates proposed in Upgrade story will be part of GA. Wondered if we should just hide the Draft column right now?

@amysueg @sjcox-rh @gashcrumb

**Comment by gashcrumb** [comment]
Let's do it
