### ISSUE TITLE
Atlasmap transformations use wrong character encoding

### ISSUE THREAD

**Issue by nicolaferraro** [syndesisio/syndesis#2339]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

When transforming text in Atlasmap, e.g. to *prepend* something to a input string, special characters (e.g. characters with accents like `è`) are not properly encoded.

Probably it applies to all transformations and other places where the user can insert text in Atlasmap.

## Expected behavior

Special characters should be encoded correctly.

## Screenshot

https://www.dropbox.com/s/yfc2kzjvzare6w6/Screenshot%20from%202018-04-11%2013-52-06.png?dl=0

https://www.dropbox.com/s/fko5rotjegvynz0/Screenshot%20from%202018-04-11%2012-34-16.png?dl=0

Note: it's a telegram to telegram integration with a `è: ` string prepended using Atlasmap. While the text that is part of the body is encoded correctly, the text added by atlasmap at the beginning of the string is not.

## Request and Response Data

N/A

## API Endpoints and Schemas

N/A

## Tasks involved / Steps to Reproduce

1. Create a integration (telegram-to-telegram in the example)
2. Add a datamapper step
3. In a datamapper mapping, add a "prepend" transformation
4. Use a special character like `è` in the prepended text
5. Look at the result of the transformation in the destination system

**Comment by paoloantinori** [comment]
@igarashitm keep track of this on AtlasMap repo

**Comment by igarashitm** [comment]
This only happens in Syndesis.

One wild guess is that Syndesis might export AtlasMap mapping definition in different encoding than platform default. If so, it needs to specify `encoding` on camel-atlasmap endpoint explicitly.
