### ISSUE TITLE
Create connection wizard progress bar 

### ISSUE THREAD

**Issue by michael-coker** [syndesisio/syndesis#2356]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
1. There is currently no way to know what step you're on by looking at the wizard progress bar.
1. The wizard progress bar is too narrow.
1. Completed steps aren't visually different from non-completed steps

## Expected behavior
1. The active step should be reflected visually in the wizard progress bar.
1. Progress bar should be wider.
1. Completed steps should have a blue circle

See the create custom API client connector wizard progress bar as an example of both of these.

## Screenshot

here's the create connection wizard progress bar
![screen shot 2018-04-11 at 4 40 17 pm](https://user-images.githubusercontent.com/35148959/38644711-13b81104-3da7-11e8-9d3e-39de1f36e827.png)

it should look like the custom API client connector wizard progress bar below
![screen shot 2018-04-11 at 4 40 08 pm](https://user-images.githubusercontent.com/35148959/38644710-139f49c6-3da7-11e8-9f90-d82d3a24ddb8.png)

here's what a completed step should look like
![image](https://user-images.githubusercontent.com/35148959/38744741-37b0ecd6-3f08-11e8-9d4c-476e6151b73e.png)

**Comment by deeleman** [comment]
Beware: the custom api connector wizard progress bar is a reusable component which exposes custom input properties to inform of the steps involved and whAt step is the active one.

I recommend reusing it here too. I passed on this component to Michael Spaxman a few days ago to assess its  inclusion into the patternfly library. Liaise  with him to check whether there'l has been any progress made on that end and whether you should grab the component from the library or not. Thanks!
