### ISSUE TITLE
Activity Log Errors not showing up in the right step.

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis#2365]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
Successful processing flow:
![syndesis](https://user-images.githubusercontent.com/103255/38676274-781e5a00-3e28-11e8-8d58-fe8bea50a071.jpg)

Processing flow where the Random Error step throws an exception:
![syndesis](https://user-images.githubusercontent.com/103255/38676293-8affc47e-3e28-11e8-8a9b-ab1c58d7268d.jpg)

Notice that the Random Error step is not listed and the error is shown in 'Periodic SQL Invocation' step.

## Expected behavior
Random Error step should show up and have the exception on that step entry.

**Comment by dsimansk** [comment]
I can still reproduce the issue, e.g. for the 2 following exchanges - 1st report error in a correct position, 2nd is reporting on both steps. The behaviour seems rather inconsistent.

![screen shot 2018-04-24 at 11 22 29](https://user-images.githubusercontent.com/5637792/39178382-e382b308-47b1-11e8-81e7-7910c4c7f968.png)

![screen shot 2018-04-24 at 11 22 22](https://user-images.githubusercontent.com/5637792/39178383-e39e0cb6-47b1-11e8-8531-44cba1be9bf5.png)

@lburgazzoli ping

**Comment by lburgazzoli** [comment]
@dsimansk do you have the integration logs ?

**Comment by dsimansk** [comment]
@lburgazzoli I've captured the log from the miss-positioned step here: 
https://gist.github.com/dsimansk/3fd5956bbc0149f46f15a3e4d93ba24c

**Comment by lburgazzoli** [comment]
@dsimansk @paoloantinori @chirino 

I think I have a fix for this as well as better management of activity tracking (integration side):

  https://github.com/syndesisio/syndesis/compare/master...lburgazzoli:github-2400-integration-logging

There are quite a few changes so let me know if you want m to PR that work now or not.

Special thanks to @davsclaus for helps on camel internals.

**Comment by dsimansk** [comment]
@lburgazzoli I'd vote to get it. But that's not my decision to make.

**Comment by chirino** [comment]
@lburgazzoli yeah me too.  If it's better lets get it in.

**Comment by chirino** [comment]
98743 ns would less than 1 ms, which is why nano-seconds is a good option for measuring time between small steps.

**Comment by davsclaus** [comment]
Yes but the citizen users wont know that, and dont really care.

Also the JVM nano is not precise, they say that themselves in the docs. Or at least it used to be.

I suggest to use millis seconds like the rest of the world. Or at least display in the UI as seconds or milllis.

**Comment by dsimansk** [comment]
@lburgazzoli for a `Periodic SQL -> Datamapper -> Stored` procedure most of the time I can see 2 logged events, but sometimes there's only datamapper step. Looking into integration's log there are always 2 step logged.

The other thing with the current impl it's not possible to log & display `Periodic SQL` on a first position?

```
{"exchange":"i-LB4tfU7YtNTanACih_dz","status":"begin"}
{"exchange":"i-LB4tfU7YtNTanACih_dz","step":"-LB4kmy-98xgmeFboo4R","id":"i-LB4tfUCYtNTanACih_gz","duration":2235581}
{"exchange":"i-LB4tfU7YtNTanACih_dz","step":"-LB4kiy_98xgmeFboo4Q","id":"i-LB4tfUGYtNTanACih_iz","duration":10961716}
{"exchange":"i-LB4tfU7YtNTanACih_dz","status":"done","failed":false}
{"exchange":"i-LB4tu7dYtNTanACih_kz","status":"begin"}
{"exchange":"i-LB4tu7dYtNTanACih_kz","step":"-LB4kmy-98xgmeFboo4R","id":"i-LB4tu7hYtNTanACih_nz","duration":1081459}
{"exchange":"i-LB4tu7dYtNTanACih_kz","step":"-LB4kiy_98xgmeFboo4Q","id":"i-LB4tu7jYtNTanACih_pz","duration":8649973}
{"exchange":"i-LB4tu7dYtNTanACih_kz","status":"done","failed":false}
```

![screen shot 2018-04-27 at 08 57 09](https://user-images.githubusercontent.com/5637792/39348841-085d79f8-49f9-11e8-989c-f83b537238a6.png)

![screen shot 2018-04-27 at 08 57 23](https://user-images.githubusercontent.com/5637792/39348839-0843dd72-49f9-11e8-9ebb-da6c1c569178.png)

**Comment by dsimansk** [comment]
Here's it is. The missing step is occurring at a rate ~1/ 5. Maybe a race condition during collect?
https://gist.github.com/dsimansk/c9b56466113f4d30b294a1f21989114c

```
{
    "id": "i-LB4yU5pYtNTanACihbwz",
    "logts": "2018-04-27T07:20:56.502385645Z",
    "at": 1524813656501,
    "pod": "i-www-2-t5lb4",
    "ver": "1",
    "status": "done",
    "failed": false,
    "steps": [
      {
        "id": "-LB4kmy-98xgmeFboo4R",
        "at": 1524813656504,
        "duration": 1057626
      }
    ]
  }
```

**Comment by lburgazzoli** [comment]
@dsimansk can we open a new issue for this one ?

**Comment by dsimansk** [comment]
@lburgazzoli sure, I've opened https://github.com/syndesisio/syndesis/issues/2487.
