### ISSUE TITLE
Integration activity is loading from a different integration

### ISSUE THREAD

**Issue by michael-coker** [syndesisio/syndesis#2373]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
Loading the integration activity from an integration on staging shows one thing, then going to another integration's activity, and back to the first integration's activity loads the second integration's activity in the first.

## Expected behavior
An integration's activity should only list the activity of that integration.

## Screenshot
Actual activity
<img width="1397" alt="screen shot 2018-04-12 at 2 05 16 pm" src="https://user-images.githubusercontent.com/35148959/38698422-929502bc-3e5a-11e8-9339-da8c32db9a47.png">

Activity after going to another integration and back to this one
<img width="1397" alt="screen shot 2018-04-12 at 2 05 26 pm" src="https://user-images.githubusercontent.com/35148959/38698421-9280fa06-3e5a-11e8-85d1-088a811a0652.png">

## Tasks involved / Steps to Reproduce

1. Go to [staging](https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/) and click on "Integrations"
1. Click on the "Salesforce to Database April 8" integration
1. Click on the "Activity" tab and note that it's empty
1. Click on the "Integration" link in the breadcrumb
1. Click on the "Sample Integration" integration
1. Click on the "Activity" tab and note that it loads a bunch of activity
1. Click on the "Integration" link in the breadcrumb
1. Click on the "Salesforce to Database April 8" integration
1. Click on the "Activity" tab and note that it loads the "Sample Integration"'s activity

I'm curious if it's related to https://github.com/syndesisio/syndesis/issues/2294

**Comment by dongniwang** [comment]
FYI @gashcrumb @chirino
