### ISSUE TITLE
Going into the Integration Editor and back to home page breaks the Integration Board card 

### ISSUE THREAD

**Issue by dongniwang** [syndesisio/syndesis#2374]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Going into the Integration Editor then coming back out to the Home Page breaks the Integration Board card (with a bottom scroll bar added...) 

## Expected behavior

No scroll bar on the Integration Board card.

## Screenshot

![screen shot 2018-04-12 at 3 00 49 pm](https://user-images.githubusercontent.com/24943812/38700106-fc963d0e-3e67-11e8-8023-78dca75b8af3.png)

## Tasks involved / Steps to Reproduce

1. Click an integration on the Integration List View 
2. Click "Edit Integration" 
3. Click logo area of the top masthead 

Could be related to https://github.com/syndesisio/syndesis/issues/2294

cc: @michael-coker

**Comment by michael-coker** [comment]
I think this is just an issue with how the `pfng-chart-donut` component re-draws when the screen size changes. If you resize the dashboard, you'll notice the horizontal scroll under the integration board donut chart appear, then disappear as the donut chart re-draws. A simple fix to address it would just to be to add `overflow: hidden` to the parent.

I suppose there is likely a more complex fix to address the behavior in this issue that would involve triggering the chart to redraw when the dashboard is loaded or something along those lines?

@seanforyou23 I think you've worked on this component? What do you think?

cc @gashcrumb
