### ISSUE TITLE
Integration UI representation in form of 2D graph

### ISSUE THREAD

**Issue by Stefan365** [syndesisio/syndesis#2377]
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request

## The problem
I think current 1D integration UI representation (kindly see picture 1) is not very intuitive for the user.

In case of the  most simple integration: (START - DataMapper - FINISH) it is ok, since it fits the real message flow structure. 
But in more complicated cases, when there are more finish connections, this 1D chart, is not suitable for representing in fact 2-dimensional flow structure. It is not intuitive and user must have extra additional knowledge to know what exactly is going on.

## Expected behavior
I propose to have 2D graph for representing integrations. 
(kindly see picture 2)

## Screenshot
is:
![1d_representation](https://user-images.githubusercontent.com/2714974/38705123-c7fa5986-3ea8-11e8-8a87-880420f69874.png)

should be:
![2d_representation](https://user-images.githubusercontent.com/2714974/38704886-01f759c8-3ea8-11e8-9973-feb8df8053eb.png)

##Notes:
-There is no need to add "add sink connecton" button in-between each 2 sub-branches,
but just at the end of "header", since it's from functionality point of view equivalent.

-This will probably require some changes in 'message flow' architecture, and some up to date  'features' (like - output of 'non-end-to-connection' is added to input for the following one) wouldn't be available in this new proposal.
On the other hand - is there a real necessity to return down-stream Datamapper message to the 'main flow'? Isn't this little bit bending architecture to 'the needs' of current 1D graph?
WDYT?

**Comment by gashcrumb** [comment]
@kcbabo this might need some input from ya, created a lovely new `product-management` label too for this kind of thing...

**Comment by kcbabo** [comment]
We had a number of discussions and design proposals around nested/child flows.  We can certainly consider this proposal once we go to implement.

**Comment by Stefan365** [comment]
possible design in case of more source connections:
![2d_representation_more_sources](https://user-images.githubusercontent.com/2714974/38808068-1050917c-417f-11e8-9964-4c1ac41750fc.png)
