### ISSUE TITLE
Integration state tracking doesn't seem to be working properly

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#2378]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Trying to get an integration running this morning on a fresh build but finding that the state tracking seems all off.  I basically created an integration, clicked "Publish" and it was working.  Realized that I needed to change the settings for my start connection, so did that from the editor and clicked "Publish" again.  Now I'm in this weird state where there's a pod running with my integration *but* the state coming back isn't right:

![integration](https://user-images.githubusercontent.com/351660/38738829-24e5378a-3f01-11e8-9449-2b798a046918.png)

Actually it looks like the server is trying to deploy it, but it was deployed :-/

Here's the server log:

[syndesis-server-2-ckkn7.log](https://github.com/syndesisio/syndesis/files/1907589/syndesis-server-2-ckkn7.log)

I'm noticing that the state fields aren't as I'd expect, the `currentState` is `Unpublished` and the `targetState` is `Published`.  But `currentState` should be `Pending` at this point if the server is trying to start the integration, at least that's what the UI is expecting it to be at this point since there's a `Pending` state.  Also selecting `Unpublish` from the menu doesn't appear to actually unpublish the integration, at least from the openshift console I still see a pod running.  It seems like the syndesis server has completely lost track of the pod perhaps?

## Expected behavior

Ideally clicking publish should start or restart the integration.  When we're in a state transition, the `currentState` in the integration view object should be `Pending`.  Or we should decide that any discrepencies between the two states means that really the `currentState` should be `Pending` and that the UI should also reset this field as needed.

If the user clicks `Unpublish` then the server should pretty much halt any outstanding builds/deployments and ensure that there's no pod running for that integration.

## Steps to reproduce

1.  Create a valid integration
1.  Publish it via the editor's 'Publish' button
1.  From the integration detail page, go back into the editor
1.  Change something, use the editor's 'Publish' button again to save the changes
1.  Enjoy

At this point I kinda tried using publish/unpublish from various spots on the detail page and integration list page to see if I could get the integration running again, but no joy.

It'd be awesome if someone could verify.

**Comment by gashcrumb** [comment]
Also tried scaling the deployment down, then re-publishing, that scaled it back up, rebuilt but then the integration went back to being `Unpublished`.  Here's the updated server log:

[syndesis-server-2-ckkn7 (1).log](https://github.com/syndesisio/syndesis/files/1907649/syndesis-server-2-ckkn7.1.log)

**Comment by iocanel** [comment]
Most probably!

**Comment by dsimansk** [comment]
Hi @paoloantinori,
FYI I've added p0 priority as there many side-effect after #2338 and we should probably harden the lifecycle handling as much as possible.

**Comment by gashcrumb** [comment]
Fixed by https://github.com/syndesisio/syndesis/pull/2426 thanks @iocanel!
