### ISSUE TITLE
Improve presentation of large amounts of help text on forms

### ISSUE THREAD

**Issue by amysueg** [syndesisio/syndesis#2381]
## This is a...

<pre><code>
[x] Feature request
</code></pre>

## The problem
In the attached screenshot notice that the additional help text under the Host field is somewhat overwhelming. We need an option to allow the user to show or hide large amounts of help text on the page. Some ideas the UXD team are considering area adding a "Show more" and "Hide" button option, or a popover.

See Patternfly approaches here:
http://www.patternfly.org/pattern-library/widgets/#popover
http://www.patternfly.org/pattern-library/forms-and-controls/help-on-forms/#design

## Expected behavior
The user should be presented with enough help to get started and have an option to get to additional help if needed.

## Screenshot
<img width="1371" alt="screen shot 2018-04-13 at 2 45 43 pm" src="https://user-images.githubusercontent.com/31700119/38753591-d9da0e88-3f2c-11e8-831d-8afe7402066b.png">

## Steps to Reproduce
1. Open the staging site and select Connections view: https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/connections
2. Select "Example API" connector to view the details page shown in the screen shot

FYI @dongniwang @sjcox-rh @michael-coker 

Also tagging @TovaCohen for help with editing this help text. Thank you.

**Comment by TovaCohen** [comment]
I don't understand how I can help with the long help text since it comes from the user-defined connector. Do we have any control over that text?
After the first sentence in the help text, I think a  "Show More" and "Show Less" toggle would be great. Is that possible?

**Comment by gashcrumb** [comment]
@zregvart where do the field hints come from, the swagger file?  Or are those added when we generate the connection configuration?

**Comment by zregvart** [comment]
Field hints are stored in the connector template, in the `description` field:

https://github.com/syndesisio/syndesis/blob/f1c494cee54e550e5ddfac74aca8865f0c24e306/app/server/dao/src/main/resources/io/syndesis/server/dao/deployment.json#L62

They were initially imported over from the Camel component documentation.

**Comment by amysueg** [comment]
I think we can close this as I don't believe we've received any customer feedback specifically calling this out as a problem.
