### ISSUE TITLE
Stale cookies prohibited connector creation

### ISSUE THREAD

**Issue by sjavurek** [syndesisio/syndesis#2383]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
Stale cookie impeded ability to create  new sales force connection. (https://github.com/syndesisio/syndesis/issues/2320 - tracks that specific error and will improve bubbling up/reporting issues. 

This issue is to resolve the fact we had as stale cookie. Hiram seems to be aware of the original issue around this.

**Comment by gashcrumb** [comment]
We should see what we can do about those stale cookies (@zregvart?).  There's some [code client-side](https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/store/connector/connector.service.ts#L43) to try and suppress them but I think it's an httpOnly cookie and we can't clear those from javascript.

**Comment by zregvart** [comment]
I think we have addressed this in #1949 and #1948. Client side state should not expire as vigorously: now 30mins is allowed and we can now failover server pods without loosing the encryption keys needed to decrypt it (#2178). Logs for stale cookies look much less foreboding.
