### ISSUE TITLE
please fix version information in the support button so it is accurate

### ISSUE THREAD

**Issue by sjavurek** [syndesisio/syndesis#2384]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

When you click on the support button, the version is hardcoded to 1.0. We need this to be correct for GA. 

## Expected behavior

The correct version is displayed.

**Comment by gashcrumb** [comment]
For reference [this bit](https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/support/support.component.html#L13) also the app name shouldn't be hard-coded either.

It'd be fine to even just bake this into the `config.json` as far as I'm concerned :-)

**Comment by gashcrumb** [comment]
Marking p0, think this should be sorted for GA, @paoloantinori wouldn't you think?

**Comment by dsimansk** [comment]
@zregvart it doesn't very legit :)

<img width="957" alt="screen shot 2018-04-17 at 16 24 32" src="https://user-images.githubusercontent.com/5637792/38876111-218d560e-425c-11e8-92dc-712b2a0b3345.png">

**Comment by gashcrumb** [comment]
I'll tweak that output a bit...

**Comment by zregvart** [comment]
Thanks @gashcrumb I thought this bit:
