### ISSUE TITLE
Please include timestamps in version history

### ISSUE THREAD

**Issue by sjavurek** [syndesisio/syndesis#2388]
## This is a...

<pre><code>
[ x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Please add timestamps to version history. At present, the list only shows a date and if you create multiple versions in one day a timestamp would be helpful, i.e:

![versions](https://user-images.githubusercontent.com/650863/38756156-808936c4-3f36-11e8-9b23-1465fc065802.jpg)
 be handy.

**Comment by gashcrumb** [comment]
@dongniwang is there a recommended timestamp format that includes the time as well?

**Comment by dongniwang** [comment]
@gashcrumb - For now, I would recommend following the OpenShift standard, see screenshot below. 
![screen shot 2018-04-16 at 9 29 54 am](https://user-images.githubusercontent.com/24943812/38811915-d83a9ec0-4158-11e8-84a8-6157bf2736e1.png)

FYI - We have included a timestamp for the expandable row design https://github.com/syndesisio/syndesis/raw/master/ux/designs/integration_details/img/integration_details_page_3.14_expand_scroll_bom.png and a timestamp for the Integration Activity tab https://github.com/syndesisio/syndesis/raw/master/ux/designs/integrationactivity/img/activity.png. Should probably make sure we use a consistent format moving forward. 
cc: @amysueg @sjcox-rh

**Comment by amysueg** [comment]
@dongniwang I agree we should use a consistent format wherever timestamp occurs in the app, and agree that following the OpenShift standard is a good idea.

**Comment by michael-coker** [comment]
@gashcrumb can you assign this one so it's on someone's radar, or do you need more info on the format?
