### ISSUE TITLE
Investigate notification behaviors and button placement for wizard pages 

### ISSUE THREAD

**Issue by dongniwang** [syndesisio/syndesis#2396]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

> From @gashcrumb -  @dongniwang I wonder though, since the 'Create' button is up in the toolbar in the wizard would an inline alert really work for this case? The trouble I see is that the button that actually creates the connection is kinda distant from the form the user has entered the connection name, this would be the area I'd consider putting an inline alert in. Just seems weird though :-)
https://github.com/syndesisio/syndesis/issues/2320#issuecomment-381248147

Need to investigate button placement and interaction feedback (notifications) on wizard workflow. A couple things to think about: 
- When to display inline notification, and when to have toast notification? 
- Do we want to rethink the layout of the wizard so buttons (CTAs) are closer to the actual interaction areas? 

## Expected behavior

Better user experience and better feedback when interacting with the UI. 

## Screenshot

Currently, we only have buttons at the breadcrumb toolbar level. See screenshot below 
<img width="1417" alt="screen shot 2018-04-16 at 10 41 32 am" src="https://user-images.githubusercontent.com/24943812/38815840-d1fe1d8e-4162-11e8-90d2-ca909d027cf9.png">

## References 
https://github.com/syndesisio/syndesis/issues/2320

**Comment by michael-coker** [comment]
@dongniwang I believe the layout of the wizard buttons will be addressed when @sjcox-rh updates the connection template.

Re: when to display inline or toast notifications, do you have something in mind for handling this, or do you want to discuss/review as a group? 

For reference, from patternfly

* [toast notifications](http://www.patternfly.org/pattern-library/communication/toast-notifications/#overview)

> Toast Notifications notify the user of a system occurrence.

* [inline notifications](http://www.patternfly.org/pattern-library/communication/inline-notifications/)

> Inline notifications are used to notify a user of the status of an action during a task flow.

**Comment by sjcox-rh** [comment]
In the connection template, I think we address both of these issues. The action buttons have been moved to form area, along with the notifications. This way the user only needs to stay within this area to configure, move on, cancel, and receive notifications.

<img width="1082" alt="screen shot 2018-06-08 at 10 10 43 am" src="https://user-images.githubusercontent.com/16257540/41171181-7a8fa966-6b04-11e8-9360-f96358b3d734.png">

Does this address the issues? If not happy to meet to discuss. Would love for the connection template to address this issue correctly!

**Comment by michael-coker** [comment]
thanks @sjcox-rh! Looks like it will.

**Comment by sjcox-rh** [comment]
Perfect!

**Comment by dongniwang** [comment]
Closing this issue since the latest [connection template UX work](https://github.com/syndesisio/syndesis/issues/2212) addressed the problem.
