### ISSUE TITLE
Support required field metadata in data shapes

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#2397]
See also **https://issues.jboss.org/browse/ENTESB-11537**

## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Currently we don't take into account any metadata of a field in the data shape. Both JSON Schema and XML Stylesheet provide support for setting if property is required, allowed range of the property and similar metadata.
Supporting this would help the user performing the mapping to know what mappings must be performed (required fields), and we could perform mapping validation based on that metadata.

Requires atlasmap/atlasmap#90 atlasmap/atlasmap#50

## Expected behavior

Help the user by highlighting what fields are required and need values mapped to them.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11537**
