### ISSUE TITLE
Introduce chat bot to #syndesis

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#24]
Notify when 

* When a new PR arrives in the monorepo ? (github integration)
* When a master CI build fails (Jenkins integration)

@paoloantinori you said, there is already something out of the box which you are using ?

**Comment by jimmidyson** [comment]
How would you feel about adding this to syndesisio/pure-bot instead?

**Comment by paoloantinori** [comment]
It can be an interesting activity, with the following notes:
- it's not a "ready to use" solution
- as today I don't know much about golang
- the more complex part, involving finding a way to get webhooks behind a firewall stays there

**Comment by rhuss** [comment]
For the notes, some guys pointed me out to these chat bots, which might be interesting, too:

* https://github.com/probot/probot (and e.g. https://github.com/probot/stale as example for dealing with stale PRs)
* https://geekbot.io/ for Slack, but the idea of async standups (for those who cant attend) might be interesting for us, too

Actually, I'm for reusing existing stuff, but if this doesn't fit our needs, I'm fine with extending purebot (with reasonable efforts).

**Comment by paoloantinori** [comment]
If you want to see how `sopel` behaves, I can set it up.

At the moment we haven't externalized the list of polled repos, so they are not yet an env var. 
An easy task, but needs to be done.

Then I'd need to configure github projects to specify my endpoint for webhooks. Something that my account is not able to do atm

**Comment by gashcrumb** [comment]
Apparently we didn't have time, let's open a new issue if we want to revisit.
