### ISSUE TITLE
Monitoring - Activity: Twitter mention activity is not logged

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis#2406]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
```
Twitter Mention -> Advanced Filter -> Basic Filter -> Salesforce Create or Update
```

Apart from Datamapper warnings
```

{"exchange":"i-LAHvdsdeh6MWSA3gsg6z","status":"begin"}
{"exchange":"i-LAHvdsdeh6MWSA3gsg6z","step":"-LAH_OT3yIroXzXd1V8P","id":"i-LAHvdsfeh6MWSA3gsg8z","duration":1814005}
{"exchange":"i-LAHvdsdeh6MWSA3gsg6z","step":"-LAH_GpoyIroXzXd1V8O","id":"i-LAHvdsheh6MWSA3gsg9z","duration":1103794}
2018-04-17 09:27:56.249  WARN 1 --- [line://MENTIONS] i.a.core.DefaultAtlasConversionService   : Converter between java.util.Date and java.time.ZonedDateTime aleady exists.
2018-04-17 09:27:56.262  WARN 1 --- [line://MENTIONS] i.a.core.DefaultAtlasConversionService   : Converter between java.time.LocalDate and java.time.ZonedDateTime aleady exists.
2018-04-17 09:27:56.264  WARN 1 --- [line://MENTIONS] i.a.core.DefaultAtlasConversionService   : Converter between java.time.LocalDateTime and java.time.ZonedDateTime aleady exists.
2018-04-17 09:27:56.267  WARN 1 --- [line://MENTIONS] i.a.core.DefaultAtlasConversionService   : Converter between java.time.LocalTime and java.time.ZonedDateTime aleady exists.
{"exchange":"i-LAHvdsdeh6MWSA3gsg6z","step":"-LAH_7Y5yIroXzXd1V8N","id":"i-LAHvdsjeh6MWSA3gsgAz","duration":771709951}
{"exchange":"i-LAHvdsdeh6MWSA3gsg6z","step":"-LAH_5InyIroXzXd1V8M","id":"i-LAHve3oeh6MWSA3gsgCz","duration":634184791}
{"exchange":"i-LAHvdsdeh6MWSA3gsg6z","status":"done","failed":false}


```

There seems to be mismatch between actual logging

The first step is logging id `-LAH_OT3yIroXzXd1V8P`, but in my integration 
```
"stepKind": "endpoint",
      "id": "-LAH_4weyIroXzXd1V8M"
```

[Twitter to Salesforce E2E-export (1).zip](https://github.com/syndesisio/syndesis/files/1919081/Twitter.to.Salesforce.E2E-export.1.zip)

## Expected behavior
All steps are logged and visible.

## Screenshot
![screen shot 2018-04-17 at 11 38 26](https://user-images.githubusercontent.com/5637792/38861882-e0298d7c-4233-11e8-876a-23776570d579.png)

## Tasks involved / Steps to Reproduce

1. Create Twitter Mention -> Salesforce or any other endpoint
2. Check Activity

**Comment by dsimansk** [comment]
@lburgazzoli fyi

**Comment by lburgazzoli** [comment]
@dsimansk @chirino what should we log in this case ? 

I mean twitter here is the from endpoint so I guess a failure in the endpoint may not even produce an exchange and how can we track how long the step took ?

**Comment by paoloantinori** [comment]
what's the rationale for having this a blocker priority?

**Comment by chirino** [comment]
@lburgazzoli right, I don't think an exchange is even created until the consumer creates it, so there is no duration there.  It's just the event source.  But the consumer could try to do something when the exchange completes and it could fail there.  Showing an error at the start step might be miss-leading.  

I think in the periodic SQL step, the from step shows up because there is a split step after the from.  So we are basically measuring the start step as the time spent doing the split I guess.  This likely need more looking into.  But I don't see it as a blocker.

**Comment by heiko-braun** [comment]
//cc @syndesisqe We think this is fixed, but requires verification

**Comment by heiko-braun** [comment]
@lburgazzoli Can you verify if this issue is fixed?

**Comment by lburgazzoli** [comment]
@heiko-braun visualization is now consistent

**Comment by heiko-braun** [comment]
Thanks @lburgazzoli . I am going to close this.
