### ISSUE TITLE
AWS connector sticks with US-East-1

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis#2420]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
You can't change AWS zone

## Expected behavior
You can configure the AWS zone.

**Comment by oscerd** [comment]
Didn't notice this one. Do you still see this problem? I'm checking now.

**Comment by oscerd** [comment]
Can you elaborate a bit? You can change the AWS Zone in the connection configuration

**Comment by oscerd** [comment]
Closing this one as we are able to specify any AWS zone we want. Tested with US_WEST_1,US_EAST_1,EU_WEST_1

**Comment by tplevko** [comment]
I think this can be seen, when creating new connection using S3 component:
![out2](https://user-images.githubusercontent.com/4180208/40958688-792065e6-689a-11e8-8963-ce0cde902260.gif)



or when editing existing S3 connection:

![out](https://user-images.githubusercontent.com/4180208/40958676-66476a6e-689a-11e8-8afc-a374e669013f.gif)

**Comment by oscerd** [comment]
I don't think so. If you create a connection with a different region it will be created. This is a matter of ui that doesn't show selected region while editing. I tested yesterday with EU West and it works. So not a problem of the connector.

**Comment by oscerd** [comment]
@gashcrumb can you take a look? I believe it's just a problem of presentation.

**Comment by oscerd** [comment]
My impression is just that the ui shows the default value and it doesn't actualize the choice.

**Comment by oscerd** [comment]
It's a problem in the UI, the connectors are not involved.

**Comment by gashcrumb** [comment]
Pretty confident that this is the same issue that showed up as #2720 the fix for this was merged I think yesterday morning my time, doesn't look like the above screencast included that fix.

**Comment by oscerd** [comment]
I can confirm it works as expected, we can close both the issues :-) @gashcrumb sorry for the noise :-|

**Comment by gashcrumb** [comment]
@oscerd no worries, lookit, we just closed like 2 issues :-)
