### ISSUE TITLE
Not able to start integration from older than current version

### ISSUE THREAD

**Issue by tplevko** [syndesisio/syndesis#2432]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

It is not possible to publish older than current version of integration. There is no integration build from older version in the OS, it simply deploys the current built version of integration.
The UI looks as if the integration was published from the older version, this is however not true, it still runs the current version.

## Expected behavior

When I hit publish on older version - for instance I have "version 1" and "version 2" and I hit "publish" on "version 1", I want the "version 1" to be running

## Screenshot

There is a screenshot of the activity log. The "version 1" I created had no logging. I added this only for the "version 2", which means, there is still "version 2" running.

![version_issue](https://user-images.githubusercontent.com/4180208/38976044-49749ace-43b0-11e8-837a-e9c7abd02482.png)

## Tasks involved / Steps to Reproduce

1. Create integration (and publish) -> this starts as "version 1"
2. Edit the integration (and publish) - e.g. you can simply add logger -> this starts as "version 2"
3. Unpublish the integration using "unpublish" button
4. Publish the "version 1" integration
5. Wait for it to get deployed - in the UI it looks almost as if "version 1" was deployed, but on OS - "version 2" is running, as there was no rebuild

**Comment by gashcrumb** [comment]
@iocanel lemme know if we're passing the right parameters for this, right now the UI posts to `/v1/integrations/{integrationId}/deployments/{deploymentVersion}` like would it make sense to use the `deploymentId` instead of the `version` field?

**Comment by iocanel** [comment]
@gashcrumb: The UI should POST to `/v1/integrations/{integrationId}/deployments/{version}/targetState` the target state, which should be something like:

    {
         targetState: Publised
    }

At list this is what I understand by reading @chirino code.

**Comment by gashcrumb** [comment]
Sorry mistyped the URL yep that's what the UI is currently doing...  If that needs to change let us know, thanks!

**Comment by paoloantinori** [comment]
@iocanel @chirino  guys can you comment on this? Do we need to instruct UI to do things differently or we setting wrong values on the backend?

**Comment by iocanel** [comment]
If the ui uses that url. Then its something erong with the backend. Will check later today

**Comment by paoloantinori** [comment]
@iocanel  hey have you had a chance to check this gremlin yesterday?

**Comment by iocanel** [comment]
Yes. My PR was just merged.

**Comment by tplevko** [comment]
The integration is deployed in older version, it however seems like there is some issue with it, as it get's constantly rebiuld and then redeployed. There is the server pod log:

[lifecycle_older_version.log](https://github.com/syndesisio/syndesis/files/1946243/lifecycle_older_version.log)

The integration got redeployed 13 times so far on my instance: 
![test_integration](https://user-images.githubusercontent.com/4180208/39235753-1065d8bc-4877-11e8-9391-0f6b99fa3628.png)

**Comment by dsimansk** [comment]
@iocanel after https://github.com/syndesisio/syndesis/pull/2471 the invalid character error is gone, but the continuous redeployment of older version that @tplevko is describing still persists. Have you been able to find the root of it?

Cc @paoloantinori

**Comment by zregvart** [comment]
I've managed to reproduce this using steps described by @tplevko in *Steps to Reproduce*. It looks that unpublishing version 2 also removed the config map that's required for version 1 to be published.

From the integration pod:
```
Caused by: java.lang.IllegalArgumentException: PropertiesComponent with name properties must be defined in CamelContext to support property placeholders. Property with key [sql-2.password] not found in properties from text: {{sql-2.password}}
```

**Comment by zregvart** [comment]
It seems that when we generate the Secret we don't account for the steps having different positions over time. I've taken a peek at the application.properties Secret for the test integration. The key `sql-2.password` is not present there, but there are keys for `sql-1.password` and `sql-3.password`, this matches the newer version (v2) of the integration, as I've added a logging step between the two SQL steps, moving the second SQL step from position 2 to position 3.

In PublishHandler we fetch the latest version of the integration from the JSONDB, to generate the application.properties Secret:

https://github.com/syndesisio/syndesis/blob/dc4b74316a0e73e3d1ec79e57a7b4a0de3e36f62/app/server/controller/src/main/java/io/syndesis/server/controller/integration/online/PublishHandler.java#L227-L229

I wonder if we should leave previous version's secrets around for when we need to re-publish non-latest versions, we can keep them:
 - as OpenShift Secret resources (we would need to version them)
 - in JSONDB to reference later

We might need to update values of previously stored secrets (say database password was updated).

I don't think that storing the whole previous version of the Integration would be a good idea.

Any thoughts @iocanel @rhuss @chirino @paoloantinori @lburgazzoli?

**Comment by lburgazzoli** [comment]
Aren't secretes re-generated for each build ?

**Comment by zregvart** [comment]
> Aren't secretes re-generated for each build ?

Yes they are, in this case we don't perform a build, and the Secret is generated from a newer version of the integration and this causes the issue. In nutshell we're scheduling v1 image with v2 secret.

**Comment by lburgazzoli** [comment]
So a workaround would be to re-build the secret for GA

**Comment by zregvart** [comment]
> So a workaround would be to re-build the secret for GA

I don't think we can, we don't store previous integration versions, so any building of the secret can only be done against the latest version (and that's what ends up being done). I love that you're going through the same issues I went debugging this :sweat_smile:
