### ISSUE TITLE
Error when opening support page

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#2433]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

When going to the support page, I get this error -->

![image](https://user-images.githubusercontent.com/99080/38976639-22ba15c4-43b2-11e8-9130-b9693c1f9074.png)

Also not sure, whether the syndesis image version is shown properly even when this error is resolved.

**Comment by rhuss** [comment]
I used 1.3.5-20180419 ....

**Comment by zregvart** [comment]
Seems to be working fine on staging:
![screenshot-2018-4-19 syndesis](https://user-images.githubusercontent.com/1306050/38978573-1e5b5cee-43b8-11e8-8d33-67ed7099d744.png)

**Comment by rhuss** [comment]
Strange, worked now for me, too. sorry for the noise ...
