### ISSUE TITLE
Typo in support page

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#2434]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

Typo

![image](https://user-images.githubusercontent.com/99080/38978854-e1b46f50-43b8-11e8-9f1f-ccb9197f0f6f.png)

**Comment by dsimansk** [comment]
This should have been fixed via https://github.com/syndesisio/syndesis/issues/2300. But maybe it wasn't as I can seen the typo also.
