### ISSUE TITLE
Update API client connector to use the latest integration runtime

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#2436]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

We don't require auto generated Spring (Boot) configuration classes. Let's remove those from the repository and disable their generation.

**Comment by zregvart** [comment]
This is still an issue, we could eliminate code that supports old style connectors and solve build time code generation issues we have.

**Comment by lburgazzoli** [comment]
@zregvart do you have any bandwidth to work on this ? afai only the rest-swagger connector is still based on the old style connectors and unfortunately this connector brings spring boot dependencies into the mix which causes troubles for camel-k integration

**Comment by zregvart** [comment]
Perhaps next week, not really sure.

**Comment by zregvart** [comment]
This is to support the `rest-swagger` connector on Camel-K integration runtime.

**Comment by mmuzikar** [comment]
@zregvart Do you think this could be causing #5250?

**Comment by zregvart** [comment]
Sure looks like it @mmuzikar. @valdar do you think it would be possible to add a migration so that when importing older Connector model it is migrated to the newest?

**Comment by mmuzikar** [comment]
@zregvart @valdar is there any conclusion whether the migration will be happening?

**Comment by zregvart** [comment]
@mmuzikar let's discuss the migration needed for the backward compatibility on #5250
