### ISSUE TITLE
Missing step indicator in connection wizard

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#2439]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

The active step of the connection wizard is not highlighted.

## Expected behavior

The active step of the connection wizard is highlighted.

## Screenshot

![screenshot-2018-4-19 syndesis 1](https://user-images.githubusercontent.com/1306050/38984325-ada6342e-43c6-11e8-8ef2-ad47d96b15a1.png)
![screenshot-2018-4-19 syndesis 2](https://user-images.githubusercontent.com/1306050/38984332-b00ae818-43c6-11e8-8bc8-dcce06ffc09b.png)

## Tasks involved / Steps to Reproduce

1. Try creating a connection (in my case an API connector connection)
2. Go through the steps
3. Notice no active step highlight is present

**Comment by michael-coker** [comment]
Looks OK to me, should be fixed as of https://github.com/syndesisio/syndesis/pull/2392

The API Client Connector active step highlight should have always been there though.

If you're still seeing it, what browser are you using?

**Comment by zregvart** [comment]
I'm using Firefox 59.0.2 on Linux, I see on [staging](https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/) that this is not an issue, so I must have been running an outdated UI version. Sorry for the noise.
