### ISSUE TITLE
Secret configuredProperties of a connector are not encrypted

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#2441]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Connector properties that are marked as `secret=true` are not encrypted. They should be encrypted if present on a Connector or on a Connection.

## Expected behavior

Encrypt all secrets!

## Tasks involved / Steps to Reproduce

1. Create API connector with OAuth declared
2. Setup client id and secret
3. See that the connection's connector has clientSecret set as plain text on the connector's configuredProperties
4. If a connection is created, see that the accessToken is set as plain text on the connector's configuredProperties

**Comment by zregvart** [comment]
Hmm, this is also the case with Connection's `configuredProperties`, I wonder if it's only for the API connector related connections/connectors.

**Comment by zregvart** [comment]
@paoloantinori I'll see if I can get to this one tomorrow morning, otherwise I think this might be an issue that we still need to fix by the end of this sprint.

**Comment by lburgazzoli** [comment]
I did a quick test and for a twitter connector without OAuth declared the properties are encrypted as expected:

```json
"configuredProperties": {
    "accessToken": "»ENC:...",
    "accessTokenSecret": "»ENC:...",
    "consumerKey": "»ENC:...9",
    "consumerSecret": "»ENC:.."
},
```

So maybe the OAuth flow or the custom connectors sets the configured properties without encrypting them.
