### ISSUE TITLE
Upgrade integration runtime (part 2)

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#2442]
See also **https://issues.jboss.org/browse/ENTESB-11536**

## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
[X] Epic
</code></pre>

Follow up for #1118 

## The problem

When an update happens on a connector/connection/extension we are now showing some errors on UI side but we need to support i.e:

- running a previous version of an integration that uses an old runtime
- be able to force dependencies on an integration to use the latest one provided by the platform

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11536**
