### ISSUE TITLE
Inline edit patternfly alignment

### ISSUE THREAD

**Issue by seanforyou23** [syndesisio/syndesis#2452]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

There have been updates to the inline edit design experience in patternfly. Because of this, our implementation in Syndesis has fallen out of sync a bit, and some work is needed to bring this UI element back up to par.

## Expected behavior

Interacting with inline edit in Syndesis reflects the design specs noted in the pattern library.

http://www.patternfly.org/pattern-library/forms-and-controls/inline-edit/#design

**Comment by michael-coker** [comment]
Here are the instances of inline editing that I've found so far. Does anyone know of any more?

cc @dongniwang @sjcox-rh 

## Integration editor - integration name
![screen shot 2018-06-13 at 3 08 31 pm](https://user-images.githubusercontent.com/35148959/41377141-cb68f30e-6f20-11e8-97e7-a0ccc234b079.png)

## API connector details
![screen shot 2018-06-13 at 3 04 54 pm](https://user-images.githubusercontent.com/35148959/41377142-cb7c0ffc-6f20-11e8-9719-703e8f86b1c2.png)

## Integration details - integration name and description 
![screen shot 2018-06-13 at 3 03 57 pm](https://user-images.githubusercontent.com/35148959/41377143-cb91ecc8-6f20-11e8-9116-b5561f8e2652.png)

## Connection details - connection name and description
![screen shot 2018-06-13 at 3 03 32 pm](https://user-images.githubusercontent.com/35148959/41377144-cba151fe-6f20-11e8-9d72-1fc9412887d8.png)

**Comment by michael-coker** [comment]
On hold for the moment until UXD can decide on a good UI for both the editable textarea (integration/connection description) and text (integration/connection name) components.
