### ISSUE TITLE
Syntesis extension dependency validation

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#2457]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

When developing an extension it is quite easy to pull in a dependency that conflicts with the dependency already present in the integration. We should analyze dependencies of the extension and report a error (warning?) that the extension is not compatible with Syndesis.

## Expected behavior

We don't allow extension to override Syndesis's dependency or introduce a dependency that is not version-compatible with Syndesis.

**Comment by lburgazzoli** [comment]
There's a epic for this: https://github.com/syndesisio/syndesis/issues/794
