### ISSUE TITLE
When deleting extension - no redirect to extensions page

### ISSUE THREAD

**Issue by tplevko** [syndesisio/syndesis#2460]
## This is a...

<pre><code>
[ x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[  ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

I deleted an extension, the UI stays on the extension detail page, I would expect some UI action or confirmation.

## Screenshot

![extensions_delete_no_redirect](https://user-images.githubusercontent.com/4180208/39122161-3ef5287e-46f4-11e8-85f0-0c8859c9d13e.gif)

**Comment by dsimansk** [comment]
@paoloantinori I know that we're in blocker only mode, but I wonder if we'd be able to get it some user experience improvements like this one. Redirect to `Extensions list` page would be probably one-line fix.

**Comment by sjcox-rh** [comment]
Thanks for reporting this @tplevko. 

I agree with @dsimansk that a simply directing the user to the Extensions list page would greatly improve this experience upon deletion. To take it a step further, we can even utilize an inline notification on the Extension list page to simply state that Extension was successfully deleted.

Example:
![screen shot 2018-04-24 at 12 53 59 pm](https://user-images.githubusercontent.com/16257540/39210785-9755763e-47be-11e8-80af-60833ca3148a.png)

FYI - @dongniwang

**Comment by gashcrumb** [comment]
Testing now this seems to have been implemented.
