### ISSUE TITLE
Unable to download system diagnostics if there is no integration present

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#2463]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Downloading diagnostics for all integrations from support page works only if you have at least one integration, otherwise downloaded zip is empty.

## Expected behavior

There used to be some diagnostic files even if you had no integration in the system. I am sure that there are logs which are not connected to integrations and are shared amongst all of them so you should be able to get them even without having an integration.

## Tasks involved / Steps to Reproduce

1. Navigate to support page
2. Download diagnostics for all integrations
3. Note that zip has no entries if you have no integration

**Comment by paoloantinori** [comment]
@mcada @dsimansk  Can you please attach `syndesis-server` logs?
I have just tried this on our staging repo and it behaves correctly.

https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/support

**Comment by dsimansk** [comment]
@paoloantinori do you have na integration running? It's only misbehaving on "no-integration" state.

I see the following relevant lines when exporting all.
```
2018-04-24 14:23:17.208  INFO [-,6e2201c746b39d91,6e2201c746b39d91,false] 1 --- [  XNIO-3 task-1] i.s.s.e.v.h.support.SupportHandler       : Received Support file request: {}
--
  | 2018-04-24 14:23:17.265  INFO [-,6e2201c746b39d91,6e2201c746b39d91,false] 1 --- [  XNIO-3 task-1] i.s.s.e.v1.handler.support.SupportUtil   : Created Support file: /tmp/syndesis.6937555058501378548.zip
```
