### ISSUE TITLE
an openshift user with no access to the syndesis namespace can, too, login to syndesis

### ISSUE THREAD

**Issue by maschmid** [syndesisio/syndesis#2465]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

With syndesis 1.3.5-20180424  a user that does not have any access to the namespace of the syndesis application can login to syndesis and do anything there.

deployed on OCP v3.9.14 via 

oc create -f install/support/serviceaccount-as-oauthclient-restricted.yml
oc create -f install/syndesis.yml
oc new-app --template=syndesis \
    -p ROUTE_HOSTNAME=ignite.apps.perf2.xpaas \
    -p OPENSHIFT_MASTER=$(oc whoami --show-server) \
    -p OPENSHIFT_PROJECT=$(oc project -q) \
    -p OPENSHIFT_OAUTH_CLIENT_SECRET=$(oc sa get-token syndesis-oauth-client)

## Expected behavior

User with no access to the syndesis namespace should not be able to view any syndesis state or do any modifications.

## Tasks involved / Steps to Reproduce

1. Create several users on OpenShift
2. Create a project and deploy syndesis 
3. Verify the other users don't have access to the namespace of the syndesis application  (oc login , oc get projects)
3. Try to access the project on a clean browser profile, login as a different openshift user
4. Notice the user that does not have access to the syndesis namespace can still use syndesis and access all its integrations.

**Comment by dsimansk** [comment]
@chirino a while back we talked about different OpenShift users accessing same Syndesis installation. Back then I've tested it on Ignite cluster and user without namespace access was rejected with HTTP 403 by oauth-proxy. Was there any config change of oauth-proxy since then? Or it might be change in latest OpenShift release?

**Comment by dsimansk** [comment]
@chirino @rhuss it this a missing piece?
