### ISSUE TITLE
Custom API connector - endpoint has to produce "application/json"

### ISSUE THREAD

**Issue by tplevko** [syndesisio/syndesis#2468]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

I was playing with the Custom API connector and I noticed a strange behavior. The endpoint seems to need to produce "application/json" content, otherwise there is 406 error returned.
I implemented sample app, the headers of the message sent to the endpoint when it is a part of an integration (in this case it consumes XML payload):

``
{method=POST, path=/v2/pets-xml/newPet, headers={request={Accept=application/json, breadcrumbId=i-LAvT0thb9Yfasp8ZYJzz, User-Agent=Apache-HttpClient/4.5.3 (Java/1.8.0_151), X-Forwarded-Host=swag-syndesis.192.168.99.100.nip.io, X-Forwarded-Proto=http, Forwarded=for=172.17.0.7;host=swag-syndesis.192.168.99.100.nip.io;proto=http, X-Forwarded-For=172.17.0.7, Host=swag-syndesis.192.168.99.100.nip.io, Accept-Encoding=gzip,deflate, Content-Length=86, X-Forwarded-Port=80, Content-Type=application/xml}, response={Access-Control-Allow-Credentials=true, Access-Control-Allow-Methods=*, Access-Control-Max-Age=3600, X-Application-Context=application, Date=Wed, 25 Apr 2018 06:22:56 GMT, Access-Control-Allow-Headers=Content-Type, Accept, X-Requested-With, remember-me, Content-Type=application/json;charset=UTF-8, status=406}}}
``

## Expected behavior

I would expect for endpoints to be able to consume/produce - XML/XML (or possibly some other combination determined by the swagger.json - Json/txt, XML/txt)

## Log Data

This log contains the data with headers, the service receives from the integration:
[XML_payload.log](https://github.com/syndesisio/syndesis/files/1945767/XML_payload.log)

Swagger file: 
[swagger.txt](https://github.com/syndesisio/syndesis/files/1945875/swagger.txt)

## Tasks involved / Steps to Reproduce

1. Have a service that has an endpoint which consumes/produces - XML/XML
2. Create an integration which contains this endpoint - it should use datamapper to map the payload from incoming connection
3. See, that the message produces 406 response

**Comment by zregvart** [comment]
Produces of `*/*` is not supported and doesn't make much sense.

**Comment by zregvart** [comment]
I think this is not an issue as the Swagger specification for `POST` operation at `/v2/pets-xml/newPet` specifies that it produces a content type of `*/*`. That would make the `Accept` header of the request specify `*/*`. If the service implementation has an issue with that then the implementation or the Swagger specification needs to be modified.
