### ISSUE TITLE
On MySQL - Table name pattern can not be NULL or empty

### ISSUE THREAD

**Issue by Stefan365** [syndesisio/syndesis#2482]
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request

## The problem
when I'm trying to create integration with MySQL DB connection (Validation = OK)
during start action if I refer to existing table, there is a warning:
"Table name pattern can not be NULL or empty.. Unable to fetch and process metadata"
With Postgres DB it is ok.

## Expected behavior
No warning.

## Screenshot
![mysql_console](https://user-images.githubusercontent.com/2714974/39317425-d91ef61c-497b-11e8-9539-2e61dd8e7f60.png)

meta pod log:
file:///home/sveres/Documents/18_SYNDESIO/0_ISSUES/DB_mysql/meta.log

## Request and Response Data
Request URL: https://syndesis-project-r.192.168.99.100.nip.io/api/v1/connections/i-LB12Pg6skxtetMNA40Fz/actions/sql-start-connector
Request Method: POST
Status Code: 400 Bad Request
Request Payload: 
```
{query: "SELECT * FROM CONTACT", schedulerExpression: "60000"}
```
Response:
```
{
  "componentScheme": "sql",
  "connectorCustomizers": [
    "io.syndesis.connector.sql.customizer.SqlStartConnectorCustomizer"
  ],
  "inputDataShape": {
    "kind": "none"
  },
  "outputDataShape": {
    "kind": "any"
  },
  "propertyDefinitionSteps": [
    {
      "description": "Enter a SQL statement that starts with SELECT.",
      "name": "SQL statement",
      "properties": {
        "query": {
          "deprecated": false,
          "labelHint": "SQL SELECT statement to be executed.",
          "displayName": "SQL statement",
          "group": "common",
          "javaType": "java.lang.String",
          "kind": "path",
          "required": true,
          "secret": false,
          "type": "string"
        },
        "schedulerExpression": {
          "defaultValue": "60000",
          "deprecated": false,
          "labelHint": "Delay between scheduling (executing).",
          "displayName": "Period",
          "group": "consumer",
          "javaType": "long",
          "kind": "parameter",
          "required": false,
          "secret": false,
          "type": "duration"
        }
      }
    }
  ],
  "split": {},
  "_meta": {
    "message": "Table name pattern can not be NULL or empty.. Unable to fetch and process metadata",
    "type": "DANGER"
  }
}
```

## Tasks involved / Steps to Reproduce
1. In OpenShift create MySQL DB.
2. In the database create some DB tables.
3. In Syndesis create relevant MySQL connection.
4.  In Syndesis try to create integration using MySQL connection.

**Comment by KurtStam** [comment]
@Stefan365 it's probably a mysql specific issue. It's been a while that I tested with MySQL. Can you grab the logs from the meta/verifier pod?

**Comment by Stefan365** [comment]
@KurtStam meta pod log:
[meta.log](https://github.com/syndesisio/syndesis/files/1952366/meta.log)

**Comment by KurtStam** [comment]
Yeah looks like mysql doesn't allow us to send in an empty table name pattern  and wants a "%" instead. JDBC really isn't a very well defined specification.
