### ISSUE TITLE
Monitoring - Activity: intermittently missing step

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis#2487]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
Sometimes the activities listing is missing step, but it's logged properly in the integration. The fail rate is around 1/5 for periodic integration.

## Screenshot
![screen shot 2018-04-27 at 08 57 23](https://user-images.githubusercontent.com/5637792/39353823-2283bbac-4a09-11e8-8606-68fbe86a6eb9.png)

![screen shot 2018-04-27 at 08 57 09](https://user-images.githubusercontent.com/5637792/39353825-229d5134-4a09-11e8-91fc-c6b66dca06e8.png)

## Request and Response Data

https://gist.github.com/dsimansk/c9b56466113f4d30b294a1f21989114c

```
{
    "id": "i-LB4yU5pYtNTanACihbwz",
    "logts": "2018-04-27T07:20:56.502385645Z",
    "at": 1524813656501,
    "pod": "i-www-2-t5lb4",
    "ver": "1",
    "status": "done",
    "failed": false,
    "steps": [
      {
        "id": "-LB4kmy-98xgmeFboo4R",
        "at": 1524813656504,
        "duration": 1057626
      }
    ]
  }
```

## Tasks involved / Steps to Reproduce

1. Create simple DB -> Datamapper -> DB
2. Wath incoming Activity for missing steps

**Comment by heiko-braun** [comment]
@lburgazzoli Could you verify if this still happens?

**Comment by lburgazzoli** [comment]
@heiko-braun I don't see the problem happening again

**Comment by heiko-braun** [comment]
Thanks @lburgazzoli . I am closing this.
