### ISSUE TITLE
Externalize Help and Support texts

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis#2497]
## This is a...

<pre><code>
[ x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Current text for support pages is static.
It would be ideal having this dynamic, possibly tied to `ConfigMaps` or any external source.

## Tasks involved / Steps to Reproduce

1.
2.
3.
4.

See discussion in related issue here: https://github.com/syndesisio/syndesis/issues/2277

**Comment by gashcrumb** [comment]
Any particular text on the support page, or is this for switching the template over to using the i18n dictionary?

**Comment by paoloantinori** [comment]
The rationale here is that GSS procedure might change at their own pace and we'd like to react more easily to them.

There were 2 levels of improvement here:

1. externalized text from the html itself to a dictionary, that will help anyhow if we'll receive a request to support multilanguage
2. find a way to entirely load text from a remote source, so to call ourselves out entirely from owning the data content itself
