### ISSUE TITLE
[Upgrade] After performing a rollback, upgraded (and rolled back) deployments don't start

### ISSUE THREAD

**Issue by avano** [syndesisio/syndesis#2499]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

I'm performing the rollback in upgrade_50_replace_template, where I'm appending `exit 1` after `update_version $tag` in `replace_template::run()`.

After everything is rolled back, the deployments are scaled back to 1, but only those, that are not affected by upgrade (prometheus, oauthproxy, db [i'm not doing db migration for now]) are started back.

This is how it looks like after rollback: 
![uz3h](https://user-images.githubusercontent.com/7081216/39362867-492daf14-4a28-11e8-89b6-63815367170c.png)

The completed deployments in my case can't be scaled up - when I scale them via oc or via web, it goes back to 0 after few seconds.

cc @rhuss @paoloantinori @dsimansk 

## Tasks involved / Steps to Reproduce

1.
2.
3.
4.

**Comment by avano** [comment]
@rhuss I tried it with your changes with my minishift instance and pods are started back, but unfortunately it starts back the upgraded version instead of the original one (notice the deployment #3 in upgraded parts).

I'm doing two changes:
- I'm adding a new ENV variable to syndesis-server in install/syndesis.yml
- Adding a  new label to syndesis-ui config map using my custom script in migration/resource/<upgrade version>

and both changes are still present after rollback

![arjh](https://user-images.githubusercontent.com/7081216/39441325-d6058402-4cad-11e8-9079-78ee38a6cf76.png)

**Comment by avano** [comment]
Hello,

I encountered two problems regarding rollback with the latest changes:

- (I encountered this only once, but it stopped whole rollback) - probably a timing issue only as I never see that again

```
--- * Rolling back 'Update resources'
      - BuildConfig: update (replace)
      - ConfigMap: update (replace)
        * syndesis-meta-config
        * syndesis-prometheus-config
        * syndesis-sampledb-config
        * syndesis-server-config
        * syndesis-ui-config
      - DeploymentConfig: update (replace)
        * syndesis-db
        * syndesis-meta
        * syndesis-oauthproxy
        * syndesis-prometheus
        * syndesis-server
        * syndesis-ui
      - PersistentVolumeClaim: update (replace)
        * syndesis-meta
        * syndesis-prometheus
      - RoleBinding: update (replace)
        * syndesis:viewers
      - Route: force update (delete/create)
        * syndesis
      - Secret: update (replace)
        * syndesis-global-config
        * syndesis-oauth-proxy-cookie-secret
        * syndesis-server-secret
      - Service: force update (delete/create)
        * syndesis-db
        * syndesis-meta
        * syndesis-oauthproxy
        * syndesis-prometheus
        * syndesis-server
        * syndesis-ui
      - ServiceAccount: force update (delete/create)
        * syndesis-integration
        * syndesis-prometheus
serviceaccount "syndesis-prometheus" deleted
Error from server (AlreadyExists): object is being deleted: serviceaccounts "syndesis-prometheus" already exists
====> Rollback Error ==> Exit

```

- Is the upgrade supported with some integration running or should the user stop all integrations before the upgrade?  (According to this #1117 the integration can be running, but I don't know how optimistic is that :-)) The rollback wants to drop the whole DB and recreate it, you can't rollback with an active integration:

```
--- * Rolling back 'Migrate database'
deploymentconfig "syndesis-server" scaled
deploymentconfig "syndesis-meta" scaled
Waiting for syndesis-server to be scaled to 0
Sleeping 10s ...
NAME                                READY     STATUS        RESTARTS   AGE
i-db-to-db-logs-rest-test-1-build   0/1       Completed     0          4m
i-db-to-db-logs-rest-test-2-wlwqk   1/1       Running       0          3m
syndesis-db-1-hjslt                 1/1       Running       0          1m
syndesis-meta-3-4jjqm               1/1       Terminating   0          1m
syndesis-oauthproxy-1-qfjmw         1/1       Running       0          59s
syndesis-prometheus-1-hx2xg         1/1       Running       0          58s
syndesis-server-3-tvxq8             1/1       Terminating   0          57s
syndesis-ui-3-hs8g2                 1/1       Running       0          55s
todo-1-build                        0/1       Completed     0          8m
todo-1-jmfxc                        1/1       Running       0          7m
syndesis-server-3-tvxq8   0/1       Terminating   0         57s
syndesis-meta-3-4jjqm   0/1       Terminating   0         1m
Waiting for syndesis-meta to be scaled to 0
Sleeping 10s ...
syndesis-server-3-tvxq8   0/1       Terminating   0         1m
syndesis-server-3-tvxq8   0/1       Terminating   0         1m
syndesis-meta-3-4jjqm   0/1       Terminating   0         1m
syndesis-meta-3-4jjqm   0/1       Terminating   0         1m
Unable to use a TTY - input is not a terminal or the right kind of file
pg_restore: connecting to database for restore
pg_restore: creating SCHEMA "public"
pg_restore: creating COMMENT "SCHEMA public"
pg_restore: creating EXTENSION "plpgsql"
pg_restore: creating COMMENT "EXTENSION plpgsql"
pg_restore: creating TABLE "public.config"
pg_restore: creating TABLE "public.filestore"
pg_restore: creating TABLE "public.jsondb"
pg_restore: processing data for table "public.config"
pg_restore: processing data for table "public.filestore"
pg_restore: processing data for table "public.jsondb"
pg_restore: creating CONSTRAINT "public.config_pkey"
pg_restore: creating CONSTRAINT "public.filestore_pkey"
pg_restore: creating CONSTRAINT "public.jsondb_pkey"
pg_restore: creating INDEX "public.jsondb_idx"
pg_restore: creating ACL "public"
ALTER DATABASE
Unable to use a TTY - input is not a terminal or the right kind of file
pg_restore: connecting to database for restore
pg_restore: creating SCHEMA "public"
pg_restore: creating COMMENT "SCHEMA public"
pg_restore: creating EXTENSION "plpgsql"
pg_restore: creating COMMENT "EXTENSION plpgsql"
pg_restore: creating FUNCTION "public.add_lead(character varying, character varying, character varying, character varying, character varying, character varying, character varying)"
pg_restore: creating FUNCTION "public.create_lead()"
pg_restore: creating TABLE "public.contact"
pg_restore: creating TABLE "public.todo"
pg_restore: creating SEQUENCE "public.todo_id_seq"
pg_restore: creating SEQUENCE OWNED BY "public.todo_id_seq"
pg_restore: creating DEFAULT "public.id"
pg_restore: processing data for table "public.contact"
pg_restore: processing data for table "public.todo"
pg_restore: executing SEQUENCE SET todo_id_seq
pg_restore: creating CONSTRAINT "public.todo_pkey"
pg_restore: creating ACL "public"
dropdb: database removal failed: ERROR:  database "sampledb" is being accessed by other users
DETAIL:  There are 2 other sessions using the database.
command terminated with exit code 1
====> Rollback Error ==> Exit

```

**Comment by rhuss** [comment]
1. This looks like an internal OpenShift timing issues. I wonder whether we should just ignire this and whether we should stop the rollback in general ?

2. Running integrations should not be affected by an infrastructure upgrade. Since the sampledb can indeed be used by those, I wonder whether we should exclude backup/restore completely for this DB ? I mean, at the end its a "sample" DB anyway. @paoloantinori @zregvart any opinions on this ?

**Comment by zregvart** [comment]
> Running integrations should not be affected by an infrastructure upgrade. Since the sampledb can indeed be used by those, I wonder whether we should exclude backup/restore completely for this DB ? I mean, at the end its a "sample" DB anyway. @paoloantinori @zregvart any opinions on this ?

It's a sample database we could probably remove it from next release and create a sample database template, like we do for AMQ, so not backing it up is perfectly OK with me.

**Comment by avano** [comment]
back to 1)

Ideally there could be a wait for the resource to disappear - the question is if that is an unnecessary overkill because in 99.9% cases you don't need that because the resource disappears (almost) immediately.

When you don't stop the rollback and you don't handle the error, you may end without the resource after rollback (as I assume that it will not create it back, but I can't confirm that since I got the error only once :-) )

**Comment by rhuss** [comment]
@avano in the error you describe we just use a `--force` option, the delete/recreate is an implementation detail of `oc`. So actually I would consider this a bug in `oc`, which we could workaround, but as you said, is quite involved.

stopping or not is a philosophical question. actually I ten to agree with you that we would better stop, but we could do as much rollback as possible, leaving only a few steps to correct afterwards. We should probably collect rollback errors and print them out at the end of the migration to give the user a hint what to fix. Regardless whether we stop or not on the rollback, the system is broken and needs manual fixing. wdyt ?

**Comment by rhuss** [comment]
@avano how does this look like --> https://github.com/syndesisio/syndesis/pull/2508/commits/5e25cbbf485f20ce3421f3510c64a20b780be877 ?

**Comment by avano** [comment]
yup, looks good, probably will be enough :-)

by the way, I assume that this https://github.com/syndesisio/syndesis/blob/master/install/syndesis.yml#L1531-L1533 will go away?

If yes, then it will probably make sense to print the errors to file (in the backup folder?). Wdyt?

**Comment by rhuss** [comment]
good point, will remove it right now.

Also a good idea, I will copy all console output to file in the backup folder, too.

**Comment by rhuss** [comment]
@avano I updated the PR with this changes. Fancy to give a try ? wanted to merge the PR asap (and close this blocker issue)

**Comment by avano** [comment]
I'm on it

**Comment by rhuss** [comment]
cool, thx ;-)

**Comment by avano** [comment]
I already did 2 upgrades and 2 upgrades+rollbacks together with integration deployed, so it took a bit more time, but everything was OK. Let me try without the integration few more times

**Comment by rhuss** [comment]
@avano thanks for testing and the feedback !
