### ISSUE TITLE
Wrong time format in metrics view

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#2500]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

![image](https://user-images.githubusercontent.com/99080/39368012-c19aa44c-4a38-11e8-891e-9884b3b6b9ae.png)

Should be "16:32" or "4:32 pm" ....

**Comment by rhuss** [comment]
The other time (last processed) is in "4:32 pm" format ....

**Comment by rhuss** [comment]
but it's cool that its not shown with the server's timezone but with the one of the user ;)

**Comment by rhuss** [comment]
I still think this is relevant.

**Comment by tplevko** [comment]
Seems to be still issue at least in the integration version history view:  ![screenshot from 2018-10-05 13-07-02](https://user-images.githubusercontent.com/4180208/46532026-a184f280-c89f-11e8-911d-32f82f506d35.png)

**Comment by tplevko** [comment]
Even the Uptime detail in integration is the same, reopening 
![screenshot from 2018-10-05 13-12-52](https://user-images.githubusercontent.com/4180208/46532994-5cfb5600-c8a3-11e8-8003-748fda3ec6d4.png)

**Comment by tplevko** [comment]
Verified, is OK now!
