### ISSUE TITLE
Modern logo

### ISSUE THREAD

**Issue by linadesteem** [syndesisio/syndesis#2507]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Documentation issue or request
</code></pre>

I think this project need a logo to get recognize from people
I made one logo, if you like it i can send a PR

![syndesis](https://user-images.githubusercontent.com/35618068/39416665-e7c8eeac-4c78-11e8-9038-c49c20d2dcf4.png)

**Comment by zregvart** [comment]
Thank you that's really awesome of you :+1: Do you think it makes sense to use the colors of our [current logo](https://github.com/syndesisio/syndesis/blob/master/app/ui/src/assets/images/glasses_logo_square.png) in a colored version?

We can also discuss this here on a PR if that's easier for you.

Thanks :100: 

cc @syndesisio/uxd

**Comment by linadesteem** [comment]
of course, here are some variation with syndesis current logo color palette, let me know the one you prefer, then I will send PR

![syndesis colored](https://user-images.githubusercontent.com/35618068/39425834-5ec1b484-4ca7-11e8-8b59-f89a872646a3.png)

**Comment by chirino** [comment]
I like it. Not sure about all the color variations.  I guess I'm kinda old school plain black kinda guy :)

**Comment by chirino** [comment]
@linadesteem I assume that's in a vector format right?

**Comment by gashcrumb** [comment]
I like it too, most likely white on black would suit the current patternfly-imposed color scheme.

@sjcox-rh @dongniwang thoughts?

**Comment by amysueg** [comment]
Thank you @linadesteem for your ideas. We've been considering updating the Syndesis branding and these are good concepts. The UX Design team at Red Hat can help coordinate this effort and we will start with continuing an exploration of designs we started last year. @sjcox-rh can lead the visual design work and we can use this issue for iterating on that design, with input welcome from the Syndesis community.

**Comment by linadesteem** [comment]
Your welcome @amysueg , I am really happy to contribute to this project. :)

@chirino yes the files will be in vector format and the color is easy to change

**Comment by sjcox-rh** [comment]
@linadesteem Thank you so much for your exploration of a new Syndesis logo, I like it! Also, thanks for bringing the logo back to our attention so we can revisit the design once more. 

For full transparency, here is the logo that was created last May for Syndesis:

<img width="381" alt="screen shot 2018-05-03 at 7 31 12 am" src="https://user-images.githubusercontent.com/16257540/39583094-2db0e41a-4ea4-11e8-9213-254aa0a6db67.png">

Moving forward, I'll continue our exploration of a new logo based on your design and what was done last year. If you're interested, will keep you up to date on the progress!

Thanks again!
