### ISSUE TITLE
Trim spaces when defining connectors

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#2510]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

When entering data for defining a connection, often Copy&Paste data is used which easily can contain leading and trailing whitespace. If this whitespace is considered literally then e.g. a URL is invalid and fails verification as well during the operation itself.

It would be easy to trim trailing and leading whitespace either already on the UI side or within the connector (or both).

## Expected behavior

Invisible whitespace in front of and after connection parameters should be ignored and trimmed.

**Comment by gashcrumb** [comment]
Since it's possible for values to actually start or end in spaces I guess we should really add a `trim` parameter to field config, maybe we just default this to `true` in general and can disable it as needed.

**Comment by gashcrumb** [comment]
I got impatient, the linked PR trims the strings coming back from forms except for fields that have `secret` set to `true`, also trimming can be turned off by setting `trim` to `false` in a property's definition.
