### ISSUE TITLE
redirect to externalized URL when logging out

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#2511]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

https://github.com/syndesisio/syndesis/pull/2461 fixes logging out, but when logging out the user is currently left within the app.  When a user logs out we should redirect to some page, and that page should be defined in the `config.json` file so it can be easily customized per environment.

**Comment by chirino** [comment]
I don't see much value in making the redirect target configurable.  We should just define known redirect target.  With a logout confirmation page, or just skip the confirmation and try to reload the app which should cause the login page to be displayed.

**Comment by gashcrumb** [comment]
By default we can probably redirect to the login page, but I think having a configurable target logout link would be ideal as well for user experience purposes.

**Comment by gashcrumb** [comment]
Also I feel that if we don't at least have a configurable option, we'll be asked to provide a configurable option for this :-)

**Comment by gashcrumb** [comment]
Actually taking a gander at the oauth proxy docs we just need to set the page location to `/oauth/sign_out`, any redirecting to other pages actually ought to be handled via a 302 redirect from the oauth proxy.  Doesn't look like it's currently configurable so right now you just go back to the login page which is what we want at the moment anyways.  Will open a PR with this change shortly.

**Comment by mcada** [comment]
Issue mentioned here https://github.com/syndesisio/syndesis/pull/2461 is still present  when you use firefox browser. @gashcrumb 
![out](https://user-images.githubusercontent.com/14313995/39628503-9775d77e-4fa9-11e8-8190-d218eaab5623.gif)

**Comment by gashcrumb** [comment]
@mcada can you double-check you've cleared your cache?

**Comment by mcada** [comment]
Yes, I did that. I even tried it in private mode - the same result.

**Comment by gashcrumb** [comment]
So it looks like there's a difference between how the oauth proxy is configured for staging vs how we configure it for minishift.  On minishift when I click logout, the GET request to / returns a 302 with a location header redirecting the browser to the login page as I would expect.

On staging when I click logout, the same GET request to / happens but it returns HTTP 200 as I would *not* expect.  All subsequent requests also result in a 302 redirect as well.

I'll have to see what I can do to work around this, the response apparently makes it to our HTTP interceptor so maybe I can force that redirect.

**Comment by gashcrumb** [comment]
Ah, I see what happens now.  We see errors popping out because once the app starts up, our GET requests are getting back 302 redirect responses, but the browser blocks these from getting back to our javascript code.  So what we see is a generic 'request failed' response in our interceptor.

And the problem here is that the response object doesn't contain specific enough information for me to safely consider triggering a window reload via javascript.  I mean, we don't want the app to go totally bananas reloading.

@rhuss @zregvart @paoloantinori we're not requiring github authentication in the real world like we do for staging, are we?  Wonder if we can sort this bit via config:

> On staging when I click logout, the same GET request to / happens but it returns HTTP 200 as I would not expect. All subsequent requests also result in a 302 redirect as well.

as this is what breaks it for firefox.

**Comment by gashcrumb** [comment]
Linked PR attempts to work around this by triggering a reload if we run into this response when fetching the app config, unfortunately I don't have the setup here to verify it properly.  Either the reload will work the same as when you manually click 'refresh', *or* the user will wind up in a horrifying reload loop.

Also on a side note, a new issue should have been created for this vs. re-opening this issue.

**Comment by paoloantinori** [comment]
In my opinion that would add flexibility to perform more complex workflow. @gashcrumb  any opinion?

**Comment by gashcrumb** [comment]
+1

**Comment by gashcrumb** [comment]
We should raise a new issue to implement that and close this one.  I also suggest we close PR #2556 that I opened, as it's a workaround and not a fix, and I fear it may have unintended side-effects.

**Comment by paoloantinori** [comment]
Moving the discussion over #2561
