### ISSUE TITLE
MQTT use-case error

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#2521]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Integration which consists of MQTT - subscribe  >>>>> MQTT - publish does not work.
[integration-logs.txt](https://github.com/syndesisio/syndesis/files/1966548/logs.txt)
While working on test automation of MQTT I did not find any examples of how it should work. I suppose that mqtt-sub --> mqtt-pub is valid customer scenario - just forward the message from one topic to another.
As mqtt is part of release I am using label p0 (@paoloantinori ). 

Can you please check if my scenario is valid and should work (bug) or it is not valid and provide some documentation what should work and how should I set it up from syndesis-user POV? I used amq broker with mqtt ports enabled and when used mosquitto manually my broker works fine when I specify user and password. MQTT connection validated successfully from syndesis, but integration does not work.

## Expected behavior

Integration should work.

## Tasks involved / Steps to Reproduce

1. Create mqtt connection to existing mqtt broker which requires username and password and validate it from syndesis
2. Create integration
3. Start with MQTT - subscribe (any topic)
4. Finish with MQTT - publish (use different topic)
5. Publish the integration and check integration pod logs, there are mentioned errors.

**Comment by oscerd** [comment]
I didn't work on mqtt connector and I don't think is up to anyone to assign issue.

**Comment by oscerd** [comment]
I only added the fields required and checked the validation.

**Comment by lburgazzoli** [comment]
hi @mcada 

I see  "Not authorized to connect" so I guess there is some misconfiguration. I don't see this as as blocker.

**Comment by rhuss** [comment]
I also don't consider that a blocker (yet)

Interesting though that the validation is supposed to be sucessful, whereas during runtime it didn't work. 

But agreed its not a blocker as long as we cant rule out a configuration error.

BTW, there's a NPE during shutdown, too, which comes directly from the Camel component.

**Comment by rhuss** [comment]
According to https://github.com/apache/camel/blob/master/components/camel-mqtt/src/main/docs/mqtt-component.adoc it's `userName`, but the descriptor uses `username` (note the case). 

@lburgazzoli could this be the reason ?

**Comment by oscerd** [comment]
It can be possible. The problem here was the misleading name, since this connector is based on camel-paho.

**https://github.com/apache/camel/blob/master/components/camel-paho/src/main/docs/paho-component.adoc**

**Comment by oscerd** [comment]
I'm building with userName instead of username and I believe is 99.9% the problem.

**Comment by rhuss** [comment]
@oscerd cool, thanks !

btw, good luck tonight in the match (and make it happen again ;-)

**Comment by oscerd** [comment]
I'm already preparing myself :-) With Barcelona was a miracle, tonight we'll need something more than that..

**Comment by oscerd** [comment]
BTW I'll be at the stadium as always :-)

**Comment by oscerd** [comment]
@mcada can you please share how did you create the amq broker and enabled the mqtt protocol? I have the connector fixed with the right name and I'd like to test exactly your scenario

**Comment by rhuss** [comment]
@oscerd btw, dont forget to update the MqttVerifierExtension, too

**Comment by oscerd** [comment]
yeah, I already fixed it :-)

**Comment by mcada** [comment]
@oscerd I used [this template](https://raw.githubusercontent.com/mcada/syndesis-qe/mqtt/utilities/src/main/resources/templates/syndesis-amq.yml) to create pod with broker
I wont be available next ~2 hours.

**Comment by oscerd** [comment]
@mcada I'll need a step-by-step reproducer.

**Comment by mcada** [comment]
PR https://github.com/syndesisio/syndesis/pull/2530 solved the issue, thanks! Closing.
