### ISSUE TITLE
Setting up secrets for imported OAuth based connections is broken

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#2522]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

When importing an integration with a Twitter connection, after the import I get

![image](https://user-images.githubusercontent.com/99080/39515300-fb67b506-4df9-11e8-8f9e-2874d3e0fd2a.png)

That's correct, but editing this connection via

![image](https://user-images.githubusercontent.com/99080/39515332-0c81acfc-4dfa-11e8-90b7-634eeb3153bd.png)

leads to

![image](https://user-images.githubusercontent.com/99080/39515343-19e71102-4dfa-11e8-8f04-239a6d167788.png)

There is no way to instantiate the OAuth dance again (the consumer secret and key has been setup in the global section).

Also, pushing the "Validate" button is a no-op here (no error indicated). IMO the button should be disabled in this case.

**Comment by chirino** [comment]
@zregvart yes we need to be abled edit credentials of a connection when exported into one system and into a different one.  Therefore, we need to be able re-authorize a connection.  Otherwise our integration promotion strategy is kinda dead.

**Comment by gashcrumb** [comment]
If the imported connection didn't have oauth credentials attached to it (or whatever relevant config item indicates that it's an oauth connection) then it could just show the normal form (with the client ID/secret etc) instead of the 'connect' button.  Also I wonder if a potential workaround is to just pre-create the relevant connections first and then do the import?

**Comment by rhuss** [comment]
@zregvart export will export integration and connections. Import will map on the connection name whether to create a new connection or reuse an existing right. Is this correct, @chirino ?

For me not being able to reconfigure a connection's OAuth is a blocker for the import scenario. Actually, combined with #2524 its even worse, because if now someone want to delete this unusable connection, the whole installation is blown up.

**Comment by rhuss** [comment]
> My vote goes for "Not a blocker". It's definitely an important feature, but the user, has other ways to deploy an integration with the same functionality, so this can be considered a way to bypass the issue.

@paoloantinori how ? To recreate everything afresh ? Shouldn't we then disable import/export alltogether ?

What worked for me as workaround:

* Import with then broken connection
* Create a new, similar connection
* Edit the imported integration to use the new connection
* Delete the broken connection

However if you do this slightly differently (like deleting the broken connection first) you run into #2524, which btw I consider even more severe.

**Comment by gashcrumb** [comment]
Can you try creating the named connection *before* importing?

**Comment by chirino** [comment]
@rhuss no, import uses internal ids to identify connections and integrations.  You can't create the named connection before importing.

**Comment by gashcrumb** [comment]
boo

**Comment by zregvart** [comment]
So lets split this, I've created #2531 for the first part.

**Comment by gashcrumb** [comment]
@rhuss wonder, the 'connect' button is shown when you've gone and set your client ID and secret for the service in the 'settings' page.  I think if you clear those out and then go back to the connection detail page you'll get the form instead of just the validate button and should be able to edit the connection.

**Comment by rhuss** [comment]
@gashcrumb true, I filled out the consumer secret/key first. Let me try to erase that and check how it goes.

**Comment by gashcrumb** [comment]
Wonder if you need to have those fields cleared *before* doing the import, might also be worth a test if clearing them after importing doesn't work.

**Comment by rhuss** [comment]
Just checked:

* Clearing the fields *after* import doesn't change the connection behaviour (only 'validate' is available)
* Clearing if *before* import also still leads only to:

![image](https://user-images.githubusercontent.com/99080/39528325-11db7c62-4e24-11e8-9450-1a815683cacc.png)

**Comment by gashcrumb** [comment]
Yeah, interestingly enough even when the credentials have been cleared, on step 2 of the create connection wizard you still get the 'connect twitter' button, so there's some state hanging around even after the oauth client data is deleted @zregvart

**Comment by gashcrumb** [comment]
If we could sort that bit then at least we'd have a workflow even though it's crappy :-)

**Comment by dongniwang** [comment]
Just wanted to say that the UXD would take a look at the workflow as a whole more closely. @amysueg @sjcox-rh 

But for now, if we have a current workflow that we can point the users to, let's do that, even though that may not be the ideal situation. Personally would not suggest just adding a button called "re-authorize" on the connection page for this.

**Comment by gashcrumb** [comment]
Just to ensure it's not lost, I raised -> https://github.com/syndesisio/syndesis/issues/2533 for the above...

**Comment by gashcrumb** [comment]
@rhuss so after merging @zregvart's pr for #2533 we found that instead of using the 'Remove' button if you instead go into the form, highlight the text in each input field, delete it and click 'Save' you can get to the connector config form then.

**Comment by paoloantinori** [comment]
To recap:
recent @zregvart PR allows us to have a workaround that we consider acceptable.
I'm thus demoting this a high priority, but not blocker.
@zregvart has concerns related to how complex it might the workaround be perceived by our target Citizen Dev persona

@chirino @kcbabo  please evaluate this and confirm/reject our decision to demote it to non-blocker

**Comment by heiko-braun** [comment]
@zregvart @rhuss I know there are recent discussions on other issues around oauth settings.  Should we keep this open or mark as stale and close it?

**Comment by rhuss** [comment]
It depends how acceptable the current solution is from a UX POV. I haven't followed the other discussion around oauth settings.

**Comment by zregvart** [comment]
I feel we have the crux of the issue fixed with #2531. We now have a `Reconnect` button in the connection details page.

![screenshot_2018-09-20 syndesis](https://user-images.githubusercontent.com/1306050/45811221-d6544f80-bccc-11e8-9b43-90614ba387ed.png)

If needed we can do another issue to evaluate the usability of this. Also with #3615 reconnecting on import might not be needed.

I would close this.
