### ISSUE TITLE
Inconsistent behaviour for validating existing connections

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#2523]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

On the "View" page of a connection there is a validate button for OAuth based connections, but not for the other connections

![image](https://user-images.githubusercontent.com/99080/39515553-c168dcb2-4dfa-11e8-90b4-2897bb086649.png)

![image](https://user-images.githubusercontent.com/99080/39515562-cb6b15b8-4dfa-11e8-8c05-b44f6acbb3ac.png)

For the "Edit" view, there is always a validate button in both cases

**Comment by dongniwang** [comment]
@rhuss - closing this issue since [there's another one](https://github.com/syndesisio/syndesis/issues/2538) which talks about the same issue.
