### ISSUE TITLE
[Feature] Re-authorize OAuth based connection

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#2531]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

For OAuth based connections there is no way to re-authorize them, i.e. to gain new access token or refresh token from the authorization server of the service provider, the only way is to remove the connection and create a new connection and to update all integrations that used the initial connection.

## Expected behavior

Have the ability to re-authorize an OAuth based connection.

## Screenshot

![screenshot-2018-5-2 syndesis 1](https://user-images.githubusercontent.com/1306050/39526429-00234752-4e1f-11e8-97ce-f5130d7af550.png)

## API Endpoints and Schemas

`POST /v1/connectors/{id}/credentials`
`POST /v1/credentials`
`GET /v1/credentials/callback`
`PUT /v1/connections/{id}`

## Tasks involved / Steps to Reproduce

1. Add re-reauthorize button in the UI 
2. Add logic to the UI to trigger the OAuth flow
3. Update existing connection instead of creating a new connection at the end of the OAuth flow

**Comment by paoloantinori** [comment]
Please note that this is a blocking priority enhancement for next version.
Ideally, something to have in this iteration, but officially not a blocking bug.
