### ISSUE TITLE
Consistent UX - Validate button should appear in a relatively similar location

### ISSUE THREAD

**Issue by dongniwang** [syndesisio/syndesis#2538]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Currently, Validate button is at the top right above the fields on the page when creating a connection, and is at the bottom, below the fields when editing a connection.

## Expected behavior

Validate button should appear in a relatively similar location on the "create" and "edit" Connection pages. 

## Screenshot

Create connection workflow:
<img width="1100" alt="screen shot 2018-05-02 at 5 00 50 pm" src="https://user-images.githubusercontent.com/24943812/39549020-65d606b0-4e2a-11e8-89d8-433db093805b.png">

Connection details page: 
<img width="434" alt="screen shot 2018-05-02 at 5 01 56 pm" src="https://user-images.githubusercontent.com/24943812/39549090-926d8932-4e2a-11e8-918e-a60bc44ae5ab.png">

## Reference 
https://github.com/syndesisio/syndesis/issues/2297

**Comment by michael-coker** [comment]
@dongniwang do you think it's OK to go ahead and close this since we have the improved [connection template](https://redhat.invisionapp.com/share/VZN4L63RS5D#/screens/310392446)?

**Comment by dongniwang** [comment]
Closing this because we have connection template now(see latest design via https://syndesisio.github.io/syndesis-ux/).
