### ISSUE TITLE
When previous version is published, UI showing newest integration detail (also in edit mode)

### ISSUE THREAD

**Issue by tplevko** [syndesisio/syndesis#2539]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

The lifecycle got fixed (https://github.com/syndesisio/syndesis/issues/2432), so the user is now able to publish older version of integration. The integration detail and edit page however is not consistent with the currently deployed integration version.

## Expected behavior

When there are for instance two versions (v1, v2), and the older v1 is published, the integration detail and edit page should provide the user the view and edit possibility of the currently running v1 integration, not the newest v2.

## Screenshot

As you can see, the integration in V1 doesn't contain any log steps:
![tw_db_version1](https://user-images.githubusercontent.com/4180208/39564759-ce7b77dc-4eb5-11e8-8c3c-1f8734ad4112.png)

The log steps are added in V2:
![tw_db_version2](https://user-images.githubusercontent.com/4180208/39564789-e03ba58c-4eb5-11e8-8918-023f98dd0a68.png)

When I return to the previous V1 (you can see, that the curent version is "version 1"), I however still see the V2 detail page. 

![tw_db_back_to_v1](https://user-images.githubusercontent.com/4180208/39564835-0f2fc7c4-4eb6-11e8-9861-8de4b7a877e7.png)

The "Edit" page also provides the possibility to edit not the V1, but the V2 integration:
![tw_db_edit_page_when_v1_deployed](https://user-images.githubusercontent.com/4180208/39564871-2eeaf368-4eb6-11e8-8d93-9d4b2c23ada6.png)

## Tasks involved / Steps to Reproduce

1. Create integration, edit it, so you get at least 2 versions of this integration
2. Revert the integration to the previous version
3. Observe, that the detail page doesn't reflect currently running integration

**Comment by tplevko** [comment]
@gashcrumb @zregvart  am I maybe missing something, why the detail should show the newest available version?

**Comment by zregvart** [comment]
I think this is on purpose there is a "Replace draft" option on an integration version that users need to use to get previous version, though I can't fathom how it functions -- I see no effect. The [UX design](https://github.com/syndesisio/syndesis/blob/master/ux/designs/integration_details/integration_details_page.md) mentions a separate Draft section, I don't see it when I either save draft or replace draft from history.

**Comment by gashcrumb** [comment]
Yeah, so I guess 'replace draft' is supposed to replace whatever the `steps` object is in the integration object with the version in that particular deployment.  I've no idea if that functionality works now, it used to but this view has been hacked up several times.

Anyhoo, the detail view and editor only care about the `steps ` object that comes back in the main integration object and does not index into the deployments at all for this.  IMO the `steps` attribute should always contain whatever was last published/edited, so from this bug report it seems that's not happening.

**Comment by paoloantinori** [comment]
related to https://github.com/syndesisio/syndesis/pull/2546

**Comment by paoloantinori** [comment]
merged
