### ISSUE TITLE
"Replace draft" when hit, it does basically nothing

### ISSUE THREAD

**Issue by tplevko** [syndesisio/syndesis#2540]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

This is a small issue, however I don't know whether it somehow isn't related to this issue https://github.com/syndesisio/syndesis/issues/2539. Basically the "Replace draft" option for various integration versions does nothing. 

## Expected behavior

It could do something?

## Screenshot

![screenshot from 2018-05-03 10-22-08](https://user-images.githubusercontent.com/4180208/39566864-4e630ddc-4ebd-11e8-966e-b189177123d4.png)

## Tasks involved / Steps to Reproduce

1. Create iintegration, edit it so there are at least v1 and v2
2. You can invoke dropdown menu with options "Replace draft" and "Publish" tight next to the integration version. 
3. The "Replace draft" does nothing

**Comment by zregvart** [comment]
Also see https://github.com/syndesisio/syndesis/issues/2539#issuecomment-386226661

**Comment by gashcrumb** [comment]
Linked PR fixes up the UI side, however the `PATCH` request the UI is using doesn't change the `isDraft` status on the integration, so the whole 'Draft' panel doesn't show up after clicking 'Replace Draft' still.  However you can see the steps do get persisted and can edit the old draft.
