### ISSUE TITLE
[UpgradeDB] DB update is lost somewhere during the upgrade process

### ISSUE THREAD

**Issue by avano** [syndesisio/syndesis#2554]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

When doing upgrade procedure with actually upgrading something in the DB, it seems that the upgraded content is lost somewhere during the upgrade process.

I use these two scripts to simulate schema 98 and 99, where both just change the description of a connector:

```
console.log("Starting migration to schema 98");

var path = "/connectors/:activemq/";
console.log("Fetching path: " + path);

var obj=jsondb.get(path);
obj["description"]="UPGRADE AMQ"
jsondb.update(path, obj);

console.log("Migration to schema 98 completed");
```

```
console.log("Starting migration to schema 99");

var path = "/connectors/:http4/";
console.log("Fetching path: " + path);

var obj=jsondb.get(path);
obj["description"]="UPGRADE HTTP"
jsondb.update(path, obj);

console.log("Migration to schema 99 completed");
```

Both these files are bundled inside syndesis-cli.jar and are executing alright (I see the console.logs printed).

I tried 3 scenarios:
- Use upgrade.sh ... without any change
- Use upgrade.sh, but comment out the call to syndesis-cli and use sleep to do it manually during upgrade process
- Manually invoke syndesis-cli outside of upgrade process

When running just upgrade.sh without any change, I noticed that the migration scripts are invoked correctly and there was no problem, but the changes were not present in UI (nor directly in DB) after successful upgrade.

So I tried to start the port forwarding manually during the upgrade process and invoke syndesis-cli manually.. Again no problem, but the changes were not present anywhere after successful upgrade.

When I invoke the syndesis-cli manually anytime outside the upgrade process, changes are present in the DB.

@paoloantinori @rhuss @dsimansk 
## Tasks involved / Steps to Reproduce

1.
2.
3.
4.

**Comment by avano** [comment]
And I forgot to mention, that the schema stays 99 (in the `config` table in the DB) after the changes disappear from JsonDB

**Comment by zregvart** [comment]
I think this might be a feature (cc @chirino), we don't seem to allow the change of built in objects (Connectors). I think the intent of migrations is to make changes to the user-generated objects (Connections, Integrations) and that the upgrades of built objects are in a drop-create/replace mode.

See:
https://github.com/syndesisio/syndesis/blob/20eed89cfa58ff67a81fc6c45efad845998119fa/app/server/runtime/src/main/java/io/syndesis/server/runtime/Migrations.java#L83

**Comment by avano** [comment]
ha! I'll try with something else then :-)
