### ISSUE TITLE
Max integrations per user vs per installation. 

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis#2555]
## This is a...

<pre><code>
[X] Thought Exercise
</code></pre>

## The problem
Right now we can configure a max integrations allowed per user.  Should that be max integrations allowed per installation? Seems per installation would make more sense since that kinda knows how much capacity is available to run integrations.

If multiple users share a single installation, they would be able to exceed the capacity of the install easily.

**Comment by rhuss** [comment]
This is IMO still an important as we don't have a user concept really right now. Also, when user are sharing the same installation, a limit should then apply to the sum of all integrations. So a limit per user makes in no sense in any context.

 I think there is another open issue for that. I would like to consider this change for one of the next releases.

@heiko-braun can we consider this for one of the next sprints ?

**Comment by chirino** [comment]
I think eventually it should be a limit per target namespace. Once we can deploy to multiple namespaces.

**Comment by rhuss** [comment]
@heiko-braun it's per connected user. So, when two users use the same installation they have twice the limit to their avail.

@chirino yes, that what I meant and as we have currently 1 installation = 1 namespace, we should switch that limit to 'per installation' for now as this should be super easy.
