### ISSUE TITLE
[camel] contribute component verifiers upstream

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#2571]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

contribute verifiers upstream

## The problem

We have implemented a number of component verifier that can be contributed upstream. 
Incomplete list:

- https://github.com/syndesisio/syndesis/blob/master/app/connector/dropbox/src/main/java/io/syndesis/connector/dropbox/DropBoxVerifierExtension.java
- https://github.com/syndesisio/syndesis/blob/master/app/connector/aws-s3/src/main/java/io/syndesis/connector/aws/s3/AWSS3VerifierExtension.java
- https://github.com/syndesisio/syndesis/blob/master/app/connector/amqp/src/main/java/io/syndesis/connector/amqp/AMQPVerifierExtension.java
- https://github.com/syndesisio/syndesis/blob/master/app/connector/activemq/src/main/java/io/syndesis/connector/activemq/ActiveMQConnectorVerifierExtension.java
- https://github.com/syndesisio/syndesis/blob/master/app/connector/ftp/src/main/java/io/syndesis/connector/ftp/FtpVerifierExtension.java
- https://github.com/syndesisio/syndesis/blob/master/app/connector/mqtt/src/main/java/io/syndesis/connector/mqtt/MqttVerifierExtension.java

**Comment by oscerd** [comment]
I'll take care of this.

**Comment by oscerd** [comment]
Dropbox is already done too.

**Comment by oscerd** [comment]
Slack done:
https://github.com/apache/camel/commit/024533cf9e684485c2b1d56fada2a2890911ba0b

**Comment by oscerd** [comment]
Paho done:

https://github.com/apache/camel/commit/e95fec66478bee779705ed3c1e23a2b12bfd0f04

**Comment by oscerd** [comment]
Done, for the biggest part.
