### ISSUE TITLE
Templates of fuse-ignite-* flavour should point to GA maven repo

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis#2575]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
Since we're goint toward GA release, Maven artifacts will end up in 
`https://maven.repository.redhat.com/ga/`

https://github.com/syndesisio/fuse-ignite-install/blob/d6a78cc0beb410c93386af2a6b46bdfc271ae8d0/resources/fuse-ignite-ocp.yml#L1094

**Comment by paoloantinori** [comment]
Downgrading this since I have fixed it at ignite install repo level. But we have to find a commond strategy for these.

**Comment by rhuss** [comment]
Fixed with https://github.com/syndesisio/syndesis/pull/3007
