### ISSUE TITLE
Support page version errors

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#2576]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Support page cant load versions.

``
WARN [-,86a67dda110dd561,86a67dda110dd561,false] 1 --- [ XNIO-3 task-10] org.jboss.resteasy.resteasy_jaxrs.i18n   : RESTEASY002142: Multiple resource methods match request "GET /version". Selecting one. Matching methods: [public javax.ws.rs.core.Response io.syndesis.server.endpoint.v1.VersionEndpoint.doGetPlain(), public javax.ws.rs.core.Response io.syndesis.server.endpoint.v1.VersionEndpoint.doGetJson()]
``

## Expected behavior

Versions should load successfully.

## Screenshot

![support_issue](https://user-images.githubusercontent.com/14313995/39816220-eb66b34a-539a-11e8-88a6-9b9864452f88.png)

## Tasks involved / Steps to Reproduce

1. Open support page

![out](https://user-images.githubusercontent.com/14313995/39816647-203edab0-539c-11e8-807f-4b596f3918a6.gif)

**Comment by gashcrumb** [comment]
@paoloantinori seems a blocker.

@mcada Can you grab the HTTP request's response for that URL from the browser's network tab?

**Comment by zregvart** [comment]
Can't see this on staging, I see two requests:

```http
GET /api/v1/version HTTP/1.1
Host: syndesis-staging.b6ff.rh-idev.openshiftapps.com
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/support
SYNDESIS-XSRF-TOKEN: awesome
Cookie: _oauth_proxy=...
DNT: 1
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
```

**Comment by zregvart** [comment]
Sorry, wrong button :)

**Comment by zregvart** [comment]
Would be better that the `Accept` header value is just `application/json`, though I don't see the this causing the request to fail, it just prints a warning line to the stdout.

**Comment by dsimansk** [comment]
@zregvart exactly same issue was reported by Roland a while back and it auto-magically fixed itself https://github.com/syndesisio/syndesis/issues/2433.

**Comment by gashcrumb** [comment]
> Would be better that the Accept header value is just application/json, though I don't see the this causing the request to fail, it just prints a warning line to the stdout.

probably, it should always return JSON, right?

**Comment by zregvart** [comment]
> probably, it should always return JSON, right?

if `text/plain` is never used, yup

**Comment by zregvart** [comment]
Not sure if the tooling (IDE) relies on `text/plain`, though...

**Comment by zregvart** [comment]
Duplicated by #2583
