### ISSUE TITLE
Ignite-upgrade CR container using old 'oc' binary

### ISSUE THREAD

**Issue by avano** [syndesisio/syndesis#2578]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

@paoloantinori @dsimansk for tracking purposes. https://issues.jboss.org/browse/ENTESB-8124

## Tasks involved / Steps to Reproduce

1.
2.
3.
4.

**Comment by paoloantinori** [comment]
what's the rationale for this being a blocker?

**Comment by paoloantinori** [comment]
It looks like the implications are actually on the companion `jq` version that is brought with `oc`

**Comment by aileenc** [comment]
As far as I know this was resolved in latest image build.

**Comment by avano** [comment]
you're right, closing
