### ISSUE TITLE
Error on support page for version 1.3.5

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#2583]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

When going to the support in 1.3.5 the following errors appears:

<img width="637" alt="screen shot 2018-05-09 at 14 27 51" src="https://user-images.githubusercontent.com/99080/39840746-4eb5e9a8-5395-11e8-974c-867dcd69d65f.png">

**Comment by rhuss** [comment]
It looks like that the `https://proj261043.6a63.fuse-ignite.openshiftapps.com/api/v1/version` endpoint just returns "1.3.5", not a JSON object.

**Comment by rhuss** [comment]
@gashcrumb it looks like that the `/api/version/version` returns different kind of data for a GET request, based on the `Accept:` header: A plain string for 'text/plain', the full version for 'application/json'. @zregvart actually I'm not sure whether this is really a good design as the same request GET returns different kind of informations. That looks quite fragile to me (as this issue proves). Couldn't we use different endpoint URL for this like `/api/version/version' and `api/version/info` ?

**Comment by rhuss** [comment]
These days, the UI does not send any `Accept:` header.

**Comment by rhuss** [comment]
<img width="566" alt="image" src="https://user-images.githubusercontent.com/99080/39841917-52d5ea7a-5399-11e8-843a-28f618ce01c1.png">

**Comment by gashcrumb** [comment]
Those are the response headers, can you post the full panel?  Request
headers should be underneath that...

**Comment by gashcrumb** [comment]
Yep, they're sent, but maybe I should change that to just `application/json` then?

![capture](https://user-images.githubusercontent.com/351660/39849765-efb3bd4e-53db-11e8-9ef7-d197318d400d.PNG)

**Comment by dsimansk** [comment]
@gashcrumb are you able to reproduce this behaviour. I've tried both Firefox and Chrome with productized versions deployed to internal cluster. And I can't really reproduce this.

**Comment by gashcrumb** [comment]
No, I've never been able to reproduce it TBH.

**Comment by rhuss** [comment]
I have this with the published 1.3.5 upstream images. The `Accept:` header should be 'application/json', not 'plain/text'. Actually the header sent is

```
Accept: application/json, text/plain, */*
```
@zregvart In the Version Endpoint Handler you introdiced two methods for the `/version` endpoint on GET, one for `application/json` (json object), one for `text/plain` (scalar number). What is the rationale behind this ? And which endpoint would be chosen when you set multiple Accept: headers ? In my case it seems that the scalar endpoint is selected, returning only a plain number. (100% reproducible for me on the ignite cluster and minishift with firefox in private mode).

**Comment by rhuss** [comment]
Same error on Chrome, too.

**Comment by rhuss** [comment]
Happy when it works on the productised images, but its scary not to know, why ;-)

**Comment by gashcrumb** [comment]
The linked PR tightens up that `Accept` header as compared to the default value since we always expect JSON responses for API requests.  This may or may not fix the issue however as I've not reproduced it personally.

**Comment by zregvart** [comment]
> @zregvart In the Version Endpoint Handler you introdiced two methods for the /version endpoint on GET, one for application/json (json object), one for text/plain (scalar number). What is the rationale behind this ? And which endpoint would be chosen when you set multiple Accept: headers ? In my case it seems that the scalar endpoint is selected, returning only a plain number. (100% reproducible for me on the ignite cluster and minishift with firefox in private mode).

#2404 added the `application/json` response to the `/version` endpoint, the `text/plain` endpoint already existed and was not replaced to maintain backward compatibility.

**Comment by zregvart** [comment]
I verified just now #2589 on staging, and I believe this will resolve this issue,

**Comment by zregvart** [comment]
> Happy when it works on the productised images, but its scary not to know, why ;-)

I would double check the version of reasteasy.

**Comment by rhuss** [comment]
Still, I believe we should not have an endpoint which only discriminates on the content type. Would much prefer a `/info` or something instead of `/version` for the json response.

**Comment by zregvart** [comment]
> Still, I believe we should not have an endpoint which only discriminates on the content type. Would much prefer a /info or something instead of /version for the json response.

I disagree, this is very much in line with REST best practices, the endpoint is for a _version_ resource and it returns _version_ information, it just does that in two different formats based on the `Accept` header.

I think the real issue is that the `Accept` header contains both `application/json` and `text/plain` (and `*/*`) and then regardless of the `Content-Type` header the response is interpreted as JSON.

I've created #2604 to address the underlying issue.

**Comment by rhuss** [comment]
@zregvart from a REST purist view, you are absolutely correct. But from a pragmatic POV, if a client can trigger random when providing both `Accept:` options then going a slightly not so pure approach with an extra endpoint. Actually I even disagree a bit with your interpretation because its not only a different format which is returned but also a different amount of information (JSON contains more info, not available in the scalar responsed). That would justify to me a '/version/info' endpoint.

**Comment by rhuss** [comment]
Is it that Spring Boot pickups up by random which response to server or is the order in the `Accept:` header respect (e.g. when `application/json` is first in the accept header, then json is produced ?)

**Comment by zregvart** [comment]
> Is it that Spring Boot pickups up by random which response to server or is the order in the Accept: header respect (e.g. when application/json is first in the accept header, then json is produced ?)

Nope, not a Spring WebMVC issue, it's a JAX-RS implementation that we're using (RESTEasy) and the undefined behaviour of having two mime types with (default) q=1 of HTTP specification.

There are a couple of issues relating to this in the RESTEasy issue tracker linked from https://github.com/syndesisio/syndesis/issues/2423#issuecomment-382298813.
