### ISSUE TITLE
Only one name of connection when importing integrations

### ISSUE THREAD

**Issue by tplevko** [syndesisio/syndesis#2584]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

When I import integration into syndesis, the list of "connections" that this specific imported integration uses is not complete. There is only one connection listed, even though every integration uses at least two connections.

## Expected behavior

The "Connection name" list should contain a complete list of connections, the imported integration uses.

## Screenshot

This integration has two connections, "twitter" and "salesforce" as you can see on second screenshot.
![import_integration](https://user-images.githubusercontent.com/4180208/39858257-471f4ddc-5436-11e8-8f6e-8d10e856805a.png)

![integration_import](https://user-images.githubusercontent.com/4180208/39858261-4b0c81d0-5436-11e8-88e4-8b18b3f408c1.png)

## Tasks involved / Steps to Reproduce

1. Export an integration
2. Import it into syndesis
3. Observe, that the "Connection name" list contains always only one connection name

**Comment by gashcrumb** [comment]
@kahboom can you look into this one when you get a chance?
