### ISSUE TITLE
Custom API connector Delete behavior - new changes in CR1

### ISSUE THREAD

**Issue by mastepan** [syndesisio/syndesis#2586]
## This is a...
<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
There was a discussion about Deleting Custom API connector that haven't lead to any solution.
https://github.com/syndesisio/syndesis/issues/2124, https://github.com/syndesisio/syndesis/issues/1827

Meanwhile, a side effect of an other fix (probably https://github.com/syndesisio/syndesis/issues/2524)  caused change in that behavior, which is:

1. connector can be deleted if there is or isn't a connection created from the connector. THe connection is still editable. It wasn't before.
2. connector can't be deleted (Delete button inactive) if a connection created from the connector is being used in an integration
3. If the connector has been deleted and you want to use a connection created from the connector in a new integration, There is an error when selecting the connection in the integration.
![connectionclicked](https://user-images.githubusercontent.com/8707251/39859067-e443df18-5438-11e8-86c4-300c98dab658.png)
[server_pod.log](https://github.com/syndesisio/syndesis/files/1990798/server_pod.log)

There is also a warning when deleting a connector that says:

>You can no longer edit a connection that was created from this connector. **(not true)**
You can still add connections created from this connector to integrations. **(not true)** Deleting this connector does not affect running integrations. **(true, because you can't Delete it when a connection created from the connector is being used in an integration)**

>Are you sure you want to delete the "Todo App API" connector?

Please do something with that inconsistency. Whichever it is of an easiest way of changing the warning or getting things working properly. Thanks.

**Comment by paoloantinori** [comment]
Hi @mastepan could you be more explicit on which of those 3 listed points is a blocker and why?

**Comment by paoloantinori** [comment]
it's been reported as a blocker at UX level. suggested quickest workaround is to modify the warning messages

**Comment by mastepan** [comment]
@paoloantinori Yes, it is UX level blocker...supposed the scenario is right.

@zregvart 
Decision about the right behavior is up to you. I've never seen/heard what an original scenario intention was so I can't tell.
Your points make sense.

I'd go with the warning dialog text saying something like this:

>No integration uses any connection created from this connector.
All connections created from the connector will be deleted as well.

>Are you sure to delete...

May be styled better... @TovaCohen ? :) if others agree with the solution.

**Comment by paoloantinori** [comment]
Please, notice that for GA we are just performing this:
> workaround is to modify the warning messages

**Comment by paoloantinori** [comment]
No longer a blocker due to this other workaround: https://github.com/syndesisio/syndesis/issues/2594
