### ISSUE TITLE
Import integration, when I press "cancel" integration get's imported

### ISSUE THREAD

**Issue by tplevko** [syndesisio/syndesis#2587]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

There is a "Cancel" button, for integration import. When I press it, the integration get's imported.

## Expected behavior

I think it would be nice, if the integration was not imported when I press the "Cancel" button. For the confirmation of import, there is the "Done" button.

## Screenshot

![out](https://user-images.githubusercontent.com/4180208/39861173-0fe40696-5440-11e8-9b63-17374c99b2e0.gif)

## Tasks involved / Steps to Reproduce

1. Press "import integration"
2. Select integration to import
3. Press "Cancel" button
4.

**Comment by gashcrumb** [comment]
@kahboom can you look into this one when you get a chance?

**Comment by gashcrumb** [comment]
@phantomjinx I'll take this one, actually working on the page now...

**Comment by kahboom** [comment]
Woah, no idea how I didn't realize I had been tagged in this--my apologies @gashcrumb . Next time ping me on IRC if I don't respond right away on here.

**Comment by gashcrumb** [comment]
The integration is imported immediately on selection/file drop, so 'cancel' is meaningless in this context, I'm going to probably get rid of the cancel button in favor of Done for #3101.
