### ISSUE TITLE
Correct message displayed upon connector deletion

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis#2594]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
Upon deletion of a connector the wrong message is displayed

## Expected behavior
Display this message:

```
Deleting this connector does not affect running integrations. 
Are you sure you want to delete the "XXXXXXX" connector?

```

**Comment by TovaCohen** [comment]
Sorry to be so late responding. It's not clear to me whether or not I need to update the user doc.
This is what we have now:

**Deleting API client connectors**
After you delete an API client connector:

- You cannot edit a connection that you created from that connector.
- An integration that is running and that uses a connection created from the deleted connector continues to run.
- You can continue to use connections created from the deleted connector. That is, you can

-- Create and publish
-- Edit and publish
-- Unpublish and republish

an integration that uses a connection that was created from the deleted connector.

To delete an API client connector:

1. In the left panel, click Customizations.
2. In the API Client Connectors tab, to the right of the name of the connector that you want to delete, click Delete.
3. Read the confirmation popup to be sure that you want to click Delete.

Is this correct? 
If not, what needs to change?
Thanks!

**Comment by mastepan** [comment]
@TovaCohen  I've just updated the doc jira.
