### ISSUE TITLE
missing maven repos in settings.xml ?

### ISSUE THREAD

**Issue by petenorth** [syndesisio/syndesis#2610]
## This is a...
<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
I am trying to work through

https://access.redhat.com/documentation/en-us/red_hat_jboss_fuse/7.0-tp/html/ignite_sample_integration_tutorials/amq-to-rest-api

I have setup syndesis (template from master branch) on the latest version of minishift (v3.9.14) and everything worked relatively straightforwardly but the publish step is failing.

Looking at the builds taking place within the syndesis namespace I think that the maven settings.xml that it is using is not pointing to the ea repos, it is only pointing to ga and the artifacts required (2.21.0.fuse-000055-redhat-2) are only present in the ea repos:

https://maven.repository.redhat.com/earlyaccess/all/org/apache/camel/camel-core/
https://maven.repository.redhat.com/ga/org/apache/camel/camel-core/

The settings.xml seems to be set here:

Using custom maven settings from /tmp/src/configuration/settings.xml
Found pom.xml ...
Running 'mvn -Dmaven.repo.local=/tmp/artifacts/m2 -s /tmp/src/configuration/settings.xml package -DskipTests -e -Dfabric8.skip=true -B '

Is there anyway to fix this?

Is this related to #2596

**Comment by zregvart** [comment]
We have Maven repository configuration in `application.yml`:
https://github.com/syndesisio/syndesis/blob/fc6fb35964e17cc02b6837ebcacff71a416b304c/app/server/runtime/src/main/resources/application.yml#L105-L109

And that is mounted via config map named `syndesis-server-config`.

I'm actually confused about this as you mention that you built from master but ended up with Red Hat productized version of Camel. I think you might have somehow mixed the two versions.

If you want to use the version in `master` then you should use the `syndesis` tool we provide to install on minishift. We have steps to do that in the [developer handbook](https://doc.syndesis.io/#_installing_syndesis).

**Comment by petenorth** [comment]
@zregvart I think I have worked out what was going on based on your feedback. The tutorial I used 

https://access.redhat.com/documentation/en-us/red_hat_jboss_fuse/7.0-tp/html/ignite_sample_integration_tutorials/amq-to-rest-api

is for the Ignite hosted application and has a 'Damage Reporter' custom step.

The documentation at access.redhat.com tells you to download the jar from https://github.com/syndesisio/fuse-online-tp3-sample-extension/releases . Both of the releases (TP3 and TP4) use the Red Hat productized version of Camel .

Hence the mixture of camel versions when building an integration (the connectors used are generally SNAPSHOT versions i.e. io.syndesis.connector:connector-activemq:1.3-SNAPSHOT) . 

For other newbies... you can export the integration and then view the model.json file which will indicate the dependencies versions (search for MAVEN).

**Comment by zregvart** [comment]
I think we will make this much better with #794, so closing this in favour of that.
