### ISSUE TITLE
Syndesis lifecycle - issue with renaming of integrations and older versions

### ISSUE THREAD

**Issue by tplevko** [syndesisio/syndesis#2611]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

It seems like there is an issue in current lifecycle design: 
I created an integration with name "test". I then published the integration and then renamed it to "test_updated". Then I edited the integration and deployed the newer version of this integration (this starts the pod with the name "i-test-updated"). Then I revert the integration to the older "version 1" - this will start a pod with name "i-test", the integration name stays however "test_updated".
The issue is now, when I start a new integration "test", this will recreate the running pod "i-test", which is now dedicated to the "test_updated" integration and this will break both my old and new integration, because the "i-test" pod will try to recreate endlessly.

## Expected behavior

There could be some mechanism, which would prevent from creating the integration, which starts the pod with the same name as the running one, or some other solution. 

## Tasks involved / Steps to Reproduce

1. Create integration, run it
2. Rename the integration 
3. Edit the integration - run the new version
4. Revert to older version 1 of the integration
5. Create a new integration, with the original name of the integration, that is already running
6. Observe in OpenShift the incorrect behavior

**Comment by gashcrumb** [comment]
We should really try and decouple the user-supplied name from the actual openshift objects other than a label or tag.

**Comment by dhirajsb** [comment]
The linked PR fixes this issue by ensuring all integration names, including draft and versioned names in deployments, are unique. 
This does mean that integration name may not always match openshift resources due to a different name in deployed version. Hence the new feature request #3247 to display deployment names in versions.
