### ISSUE TITLE
Apicurio - identify not relevant functionalities

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis#2615]
Candidates:
- collaboration?

**Comment by kahboom** [comment]
Closing, as we don't have any strictly identified at the moment. Originally, we thought 'versions' and collaboration, but this looks to be a non-issue. See [here](https://docs.google.com/document/d/165dPV4TsPfvlSIyNMHQ8jXt4PSYmvFTRKLbz8R9HMBU/edit?ts=5b02be8a#heading=h.5surmt3bv9hn) for more discussion, under "Feature Requirement Commonalities & Discrepancies".
