### ISSUE TITLE
Investigate support for OpenAPI 3.0 

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis#2616]

**Comment by paoloantinori** [comment]
@zregvart do you know more about this topic? where we currently stand and what would be the implications to support v3.0?

**Comment by zregvart** [comment]
We use OpenAPI 2.0 for:
 - server API specification at `/api/v1/swagger.(json|yaml)`
 - generating custom API connectors in `app/server/connector-generator`
 - in integration runtime, relying on Apache Camel `camel-rest-swagger` component

To support OpenAPI 3.0 we would need to:
 - add support in Apache Camel `camel-rest-swagger` component
 - add support in `app/server/connector-generator` module
 - update/migrate/configure RESTEasy/JAX-RS in the server

**Comment by paoloantinori** [comment]
thanks @zregvart I think this is enough in terms of investigation activity.

We will refer to this issue if and when asked to support OpenAPI 3.0.

cc @kahboom

**Comment by vinodc** [comment]
OpenAPI 3.0 support would be great. Is there a location you're tracking requests for features such as these in?

**Comment by zregvart** [comment]
@vinodc we have [an open issue](https://github.com/syndesisio/syndesis/issues/467) to support OpenAPI 3.0. You can comment there also.
