### ISSUE TITLE
UI - Give more details on the publishing process

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis#2620]
Implement the UI stuff based on https://github.com/syndesisio/syndesis/pull/2947

**Comment by gashcrumb** [comment]
@dhirajsb Can't seem to fetch the detailed status, I rebuilt/redeployed this morning, when I do a GET to that endpoint I only get back an HTTP 204:

![capture](https://user-images.githubusercontent.com/351660/42461739-36242332-836f-11e8-8a5e-42ac9f2cb100.PNG)

I don't see any errors in the server log.  Anything else I need to set up that I likely missed?

**Comment by gashcrumb** [comment]
@dhirajsb PR is here if you want to give it a test -> https://github.com/syndesisio/syndesis/pull/3010

I opted to just fetch the status detail as part of fetching all the integrations if there's any that are pending, at least hopefully that's what that PR should be doing :-)

TBH having a separate endpoint to fetch this from complicates things for the UI, and this is going to be a performance problem I'd think for folks that have more than a couple integrations running.
