### ISSUE TITLE
Status updates during publish of Ignite integrations

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis#2621]
See subtasks

**Comment by gashcrumb** [comment]
#2751 is the user story I believe and #2343 I think has all the discussion.

**Comment by heiko-braun** [comment]
@gashcrumb @dhirajsb What's the status of this?

**Comment by dhirajsb** [comment]
@heiko-braun I've opened PR #2947 for an initial version of the backend implementation for this. I will work with @gashcrumb for UI changes next.

**Comment by heiko-braun** [comment]
@gashcrumb Is this done? I don't see any pending substasks
