### ISSUE TITLE
Evaluate Operators with CoreOS guys

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis#2623]

**Comment by rhuss** [comment]
A call is scheduled on this Wednesday, let me know if anyone is interested to join.

**Comment by paoloantinori** [comment]
yes please, I'm interested in hearing!

**Comment by lburgazzoli** [comment]
I'm interested too

**Comment by nicolaferraro** [comment]
Please, include me too :smile:

**Comment by zregvart** [comment]
I'm interested

**Comment by rhuss** [comment]
Sorry, forgot to add @lburgazzoli and @nicolaferraro for the initial discussion we had with the CoreOS guys. I'm going to give a presentation / break-out session next week at the F2F, also including the results of this call.

**Comment by rhuss** [comment]
We had the meeting and the guys agreed that the approach layed out in https://docs.google.com/presentation/d/18zkDFkmcuo5mAYxlbfZzP5_Xpn5ncLKEt9pDAzK-Ejc/edit?usp=sharing is doable.

I'm closing this issue for now, but we should be aware that the CoreOS team is happy to help us when it comes to implement the Operator story.
