### ISSUE TITLE
Deliver scoping of the activity for the next sprint

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis#2624]

**Comment by rhuss** [comment]
@paoloantinori could you please elaborate a bit on the topic of this issue as it is not really clear to me ?

**Comment by rhuss** [comment]
I suggest that for the next sprint we should tackle two task:

* Implement the Infrastructure Update Operator around a "Syndesis" custom resource. I would pick that up.
* Possible TOC for the runtime operator support, stage 1 // @nicolaferraro interested ?
