### ISSUE TITLE
Evaluate moving to Ansible based story

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis#2627]

**Comment by paoloantinori** [comment]
@rhuss this is probably entirely outdated? can we close this?

**Comment by paoloantinori** [comment]
The reason why I was suspecting this being outdated was that I thought it might be related to the recent Operator efforts.

Do you confirm that this has no place within the Operators approach we are working on? If so, yes, please detail and plan the activity to support APB for the next version.

**Comment by rhuss** [comment]
APB (what) and Operators (when) are complementary, so APB make for sure sense in an operator's world. My question was, should I take the task for switching from (OpenShift template, homegrown update scripts) -> (APB) to the Operator story or do we want to track it here ?

**Comment by paoloantinori** [comment]
I'd say that they are related but not really depending on the other, so probably it's better to track them as separated stories.
