### ISSUE TITLE
Concur: Supporting multiple environments (DEV/PROD)

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis#2631]

**Comment by paoloantinori** [comment]
@KurtStam hi, is this supported already?

**Comment by zregvart** [comment]
We support multiple environments in OAuth settings, i.e. you can specify different authorization and token URLs.

What we're missing is to specify the `host` parameter when the connection is created.

**Comment by zregvart** [comment]
Superseded by #3197
