### ISSUE TITLE
Other Connectors

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis#2637]
- LinkedIn
- Egencia
- Box
- Twilio
- Azure
- Google Drive

**Comment by nicolaferraro** [comment]
We have here a list of connectors we may add in 7.1.
Gmail (#2636) is one of the first connectors we may start to work on.

Among the others, personally, I like the suggestion made by @oscerd about the Kafka connector. Kafka has a big community and it's used in a wide range of applications, from IoT, to stream processing and machine learning. As Red Hat, we have also released a developer preview of AMQ streams for running Kafka on Openshift. So I'd like to see it in 7.1.

But, I wonder if the list above has some priority from a product point of view, @kcbabo, or we can just pick.

**Comment by oscerd** [comment]
Yeah, it would be great to know the priority of the different optional connectors and user stories for them.

**Comment by heiko-braun** [comment]
I've moved the ones we committed to for 7.1 to separate issues. Anything else is left here

**Comment by heiko-braun** [comment]
Closing in preference of distinct issues for each new connector
