### ISSUE TITLE
Document workflows to import images into Fuser Online clusters

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis#2640]

**Comment by rhuss** [comment]
@paoloantinori if I understand right its about adding a Jenkins Job which does the import after the configuration file https://github.com/syndesisio/fuse-ignite-install/blob/master/fuse_ignite_config.sh has been updated ? 

Actually not sure what the real benefit is except that we would have a history when the import happened (well, actually you *still* can trigger the import manually)

**Comment by paoloantinori** [comment]
well, the benefit would be that at the moment the process involves a person that downloads the project, performs a manual modification and invokes a script.

A job would automate all this. 
It's the same benefit that led us to have a Jenkins job perform a release:
invocable by anyone that has access on the platform and not tied to the engineering team.

**Comment by rhuss** [comment]
> well, the benefit would be that at the moment the process involves a person that downloads the project, performs a manual modification and invokes a script.

To what kind of manual modification to you refer ? The import script has been changed to reuse the release information in https://github.com/syndesisio/fuse-ignite-install/blob/master/fuse_ignite_config.sh which is also used when doing a fuse-ignite release.

So, import_images.pl doesn't need any modification anymore nor does it take any parameter except the target cluster.

All you save is the checkout of the project, that's true. 
I can create a Jenkins Job, which takes the following parameters:

* login credentials (i don't wanna store my personal creds in Jenkins tbh)
* target release (tag in fuse-ignite repository)

So everbody who has write access to the eval cluster then can start the job. Actually, this is you, david, hiram and me (afaik). Personally, I won't be afraid to checkout the project.

**Comment by paoloantinori** [comment]
perfect, creating a jenkins job is exactly the main activity here. the more our operations offloaded to a dedicated server, the easier is to have more people able to use them

thank you

**Comment by heiko-braun** [comment]
@rhuss Do you think there is room for this in 7.1? I.e. should we try to do the 7.1 release in an automated fashion?

**Comment by rhuss** [comment]
Not sure, but I could try after I've done with integrating operators in our build, install and release process (which will still takes some days)

**Comment by rhuss** [comment]
For 7.1 this is very likely not in scope anymore as we run out of time.

**Comment by heiko-braun** [comment]
Right, it's an ongoing effort. Let's turn this into "document ..." for 7.1, than we can close it.
