### ISSUE TITLE
Step/Connection Consolidation - Provide UX designs

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis#2644]

**Comment by amysueg** [comment]
The UX design needs to be reviewed. 

It is located here:
https://redhat.invisionapp.com/share/PWH14PWMCXE

I've added the design link to this issue fyi, @sjcox-rh @dongniwang @gashcrumb

**Comment by amysueg** [comment]
There is already an issue for this work here with many comments, etc: https://github.com/syndesisio/syndesis/issues/1830

Should one of these be closed @gashcrumb @paoloantinori ?

**Comment by gashcrumb** [comment]
+1
