### ISSUE TITLE
Ignite "Contact Us" address is "fuse-online-tech-preview@redhat.com"

### ISSUE THREAD

**Issue by tplevko** [syndesisio/syndesis#2653]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

The "Contact Us" address in the latest GA candidate is pointing to "mailto:fuse-online-tech-preview@redhat.com". 

## Expected behavior

It should be probably some address which would not contain "tech-preview", or get rid of the "Contact Us" altogether. 

## Tasks involved / Steps to Reproduce

1. Click the "Contact Us" 
2. Observe the email address

**Comment by tplevko** [comment]
@paoloantinori it seems like a leftover from https://github.com/syndesisio/syndesis/issues/2277. The support page was updated, but the "Contact Us" mail address stayed the same.

**Comment by dsimansk** [comment]
@paoloantinori per #2277 it was suggested to switch to link pointing to RH Portal. Just beware that Contact Us starts with `mailto:` prefix in UI code. 

https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/app.component.html#L70

**Comment by gashcrumb** [comment]
@paoloantinori linked PR updates that link, merge if you need it...

**Comment by paoloantinori** [comment]
@gashcrumb merged, thanks!
