### ISSUE TITLE
"Sample Integrations Tutorials" and "User guide" documentation pointing to wrong location

### ISSUE THREAD

**Issue by tplevko** [syndesisio/syndesis#2656]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

The URL for "Sample Integrations Tutorials" and "User guide" is probably not correct. It redirects to 404 page.

## Screenshot

When choosing the first two options from these: 
![screenshot from 2018-05-15 10-23-47](https://user-images.githubusercontent.com/4180208/40045276-2546ab5e-582a-11e8-9b41-42a33d7708c8.png)

I get:
![404_user_guide_sample_integrations_tutorial](https://user-images.githubusercontent.com/4180208/40045224-03606700-582a-11e8-876d-135b0af39543.png)

**Comment by dsimansk** [comment]
@tplevko per our conversation those are valid URLs once Docs go live on portal. If you don't mind I'll close this issue.
