### ISSUE TITLE
UI - Enhance API Connector

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis#2672]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
Currently the API connector imports all the operations.
We could see this, from a Camel point of view, as the automated generation of a Component and not really a Syndesis Connector.
The reason for this disctinction is that a Connector allows to pre-configure and simplify/limit the full set of operations exposed by a Component.

Imagining a further step, at UX level, when importing a new API that allows to decide which operation to expose and eventually prefill some required parameter, could improve usability.

**Comment by paoloantinori** [comment]
Inviting @lburgazzoli @zregvart @gashcrumb  to join the discussion.

**Comment by gashcrumb** [comment]
Some of this as well we're thinking could be solved by integrating with apicur.io as well.

**Comment by kahboom** [comment]
Thanks @gashcrumb .

**Comment by amysueg** [comment]
Yes, this makes a lot of sense.

**Comment by dongniwang** [comment]
@zregvart - let's revisit your comments as we're moving forward with the apicurio integration. 

reference: https://github.com/syndesisio/syndesis/issues/2698
