### ISSUE TITLE
UI - Saleseforce - Enhance select widgets

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis#2673]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
In Salesforce component, but this might be shared by most of the one that we have, there are situations where an HTML select shows a huge number of options. The options are sorted,  but manually scrolling to them feels very "old school".

## Expected behavior
It would be handy to have a live filtering on the content of those select.

## Screenshot
![syndesis - mozilla firefox_011](https://user-images.githubusercontent.com/1520602/40189504-e95fac2e-59fc-11e8-8fc1-26fb8eec8f11.png)

**Comment by paoloantinori** [comment]
@gashcrumb @seanforyou23 @kahboom  what do you think about this? Is there a generic enough way to improve the UX for this use case?
Either something when we fully control the UI code, like in a custom connector, or something that can follow generic rules, like when we add metadata to a custom connector?

**Comment by zregvart** [comment]
At a point we had either Patternfly styled Bootstrap Select or Combobox, this proved to be problematic as the data binding failed to work consistently. I think we should stay away from any widgets that substitute native DOM elements and then fail to update them. I'm not sure if we can depend on widgets in Patternfly that are based on Bootstrap widgets and change the DOM element our UI binds to.

**Comment by gashcrumb** [comment]
Yeah, what @zregvart said :-)

We also tried a regular input with a typeahead, but that required you at least have some idea of what to start typing.

Also UXD did have some designs for a better method of picking salesforce objects but that kinda got put on the back burner.  But was basically kinda like a combo filter and listbox kinda deal where all the values are shown and you can either scroll the listbox or put something in the filter and it narrows what's displayed.

@dongniwang @sjcox-rh do you recall that design kinda?

**Comment by paoloantinori** [comment]
>  I think we should stay away from any widgets that substitute native DOM elements and then fail to update them

that implies "we can't use PatternFly", so probably not an option at all.

I think @seanforyou23  mentioned that PatternFly.next won't be based on Bootstrap, so that could ease the limits of current usage.

I was more interested into triggering a discussion about options and I'm finding your comments on bad prev experiences useful. We don't have an official requirement right now, but assisting at presentations at customers, I'm expecting that these kind of request will arrive quite soon, so I wanted to start reasoning on this.

Can you share some more details about data-binding failures? Any chance it's because of genuine bugs at PatternFly level? I remember hearing some comments in past of some sub-optimal implementation related to handling observables and such, and I wonder if this might be a case like that.

**Comment by zregvart** [comment]
We had an issue described in https://github.com/syndesisio/syndesis-rest/issues/733 code that leads to something like this:

https://github.com/syndesisio/syndesis-ui/commit/bd9335ac8e62479724b071d0281a49d2f820af5e#diff-56cdd2b9fdb691d5679fcaf1aea0ee63R11

is problematic, as we bind to values on the original `<select>` and that part of the code replaces the `<select>` (or hides it I don't know exactly) with different markup and then we loose the connection between value user selected.

**Comment by gashcrumb** [comment]
Yeah, it was more an issue trying to mix in a jquery plugin with angular's change detection, the bootstrap select implementation we had pulled in didn't really do a great job of that which lead to a bunch of difficult to solve data binding issues, i.e. the view is wrong, or the data behind the view is wrong etc.

[This](https://github.com/syndesisio/syndesis/blob/master/ux/designs/salesforceobjects/salesforceobjects.md#choose-object) is the desired design, basically we need to come up with a custom type for this particular form field (and ones like it) and then add a custom form widget, much like we have for `duration` type fields.

**Comment by gashcrumb** [comment]
yeah, ideally maybe the select control could be a bit smarter, i.e. be a normal select when there's less than 10 or 15 entries and then be a control similar to the UX design when there's more than that, so the control used is driven by the amount of data vs. the type.

This would mean though potentially this control could pop up in many spots and would not necessarily be consistent across users, so that could complicate things like documentation, screenshots etc.  But I think controls that can adapt better to the data in general would be kinda nice.

**Comment by amysueg** [comment]
+1 to " I think controls that can adapt better to the data in general would be kinda nice."

**Comment by amysueg** [comment]
UXD talked about this just now and we think that a patternfly-ng implementation of the combo box control will take care of this, as it will include a search field to quickly jump to a particular item. Assigned to @seanforyou23 to investigate.

fyi @dongniwang @michael-coker @sjcox-rh

**Comment by paoloantinori** [comment]
Thinking outside of the box.
A Chrome extension that allows you to apply the behavior that we want to ANY select box

https://chrome.google.com/webstore/detail/dropdown-search/kgjaddbcmpmacilgaekjfelhdebfjgib

![screenshot from 2018-05-23 18-44-16](https://user-images.githubusercontent.com/1520602/40438804-536989bc-5eb9-11e8-9bfe-42ba748b094f.png)

**Comment by gashcrumb** [comment]
That wouldn't really help for firefox or edge users though.  I'm sure this component would make at least a good basis, or we could look at directly using -> https://valor-software.com/ng2-select/

**Comment by paoloantinori** [comment]
yeah yeah, this was never any kind of solution I wanted to push =). I've
posted just to add pressure to devs =P
