### ISSUE TITLE
Create a service for dependency resolution of a integration

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#2683]
We're considering removing the S2I build. For the we would have a base image layer with the dependencies or with the dependencies mounted via a shared volume.
The integration itself would not add an additional layer to the pod image. That means that we need to calculate the dependencies of the integration pod.
Dependencies in general include:
 - all connector dependencies
 - all extension dependencies (might be omitted as extensions use their own mechanism)
 - Spring Boot dependencies
 - Atlasmap dependencies

We must take special care with regards to ordering of and versions of computed dependencies.

**Comment by KurtStam** [comment]
When running `mvn dependency:list` the first time it sure downloads the dependencies and the build takes in the order of 12 seconds:

> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD SUCCESS
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 12.656 s
> [INFO] Finished at: 2018-05-18T15:55:10+00:00
> [INFO] Final Memory: 32M/245M

The second time when all dependencies are local it is in the order of 1 second:

> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD SUCCESS
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 1.262 s
> [INFO] Finished at: 2018-05-18T16:07:43+00:00
> [INFO] Final Memory: 32M/417M

So we can at least win 10 seconds if we can build a solution where all dependencies are available in a local .m2 directory for dependency resolution.

Building the fat jar `mvn clean install` take 2.5 seconds:

> [INFO] BUILD SUCCESS
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 2.453 s
> [INFO] Finished at: 2018-05-18T12:09:53-04:00
> [INFO] Final Memory: 48M/560M

**Comment by KurtStam** [comment]
It seems to me that we can simply use the maven build, as along as we can be sure we have a local .m2 cache.

**Comment by lburgazzoli** [comment]
Something that may be useful:
    
    https://github.com/shrinkwrap/resolver#resolving-dependencies

**Comment by lburgazzoli** [comment]
We can also implement our own layout like:

    https://github.com/shrinkwrap/shrinkwrap-springboot

for both extensions and dependencies

**Comment by KurtStam** [comment]
hey stalebot, don't close it please.

**Comment by KurtStam** [comment]
hey stalebot, don't close it please.
