### ISSUE TITLE
Connector developer workflow with no-S2I

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#2686]
We're considering removing the S2I build. For the we would have a base image layer with the dependencies or with the dependencies mounted via a shared volume.
We should find a way to make the developer workflow of a developer working on a connector as easy as possible so that it's possible to update the connector JAR with minimal rebuild of unaffected artifacts.

**Comment by lburgazzoli** [comment]
food for though: should we provide **all** connectors trough extensions ?

**Comment by zregvart** [comment]
> food for though: should we provide all connectors trough extensions ?

That would also offer 3rd party connector support. So I would say yes, that would definitely make sense.
