### ISSUE TITLE
OutputDataShape annotation disregarded by maven plugin

### ISSUE THREAD

**Issue by pszuster** [syndesisio/syndesis#2688]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

I want to create a Step extension with an outputDataShape of kind=json-instance and given specification, but the extension-maven-plugin  generates a syndesis-extension-definition.json with kind="any".

## Expected behavior

I would expect the extension-maven-plugin to honor the DataShape annotation in my java class.

## Screenshot

**SplitAction.java:** 

```
package io.syndesis.extension.split;

import java.util.Map;
import java.util.Optional;

import io.syndesis.extension.api.Step;
import io.syndesis.extension.api.annotations.Action;
import io.syndesis.extension.api.annotations.ConfigurationProperty;
import io.syndesis.extension.api.annotations.DataShape;

import org.apache.camel.CamelContext;
import org.apache.camel.model.ProcessorDefinition;
import org.apache.camel.util.ObjectHelper;
import org.apache.camel.Expression;
import org.apache.camel.builder.Builder;
import org.apache.camel.processor.aggregate.UseOriginalAggregationStrategy;
import org.apache.camel.spi.Language;

@Action(id = "split", name = "Split", description = "Split your exchange", tags = { "split", "extension"}, outputDataShape= @DataShape(name="person",kind="json-instance",specification="{\"name\":\"juan\",\"lastName\":\"perez\"}"))
public class SplitAction implements Step {
    
    @ConfigurationProperty(
        name = "language",
        displayName = "Language",
        description = "The language used for the expression")
    private String language;

    @ConfigurationProperty(
        name = "expression",
        displayName = "Expression",
        description = "The expression used to split the exchange")
    private String expression;

    public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    public String getExpression() {
        return expression;
    }

    public void setExpression(String expression) {
        this.expression = expression;
    }

    @Override
    public Optional<ProcessorDefinition> configure(CamelContext context, ProcessorDefinition route, Map<String, Object> parameters) {
        String languageName = language;
        String expressionDefinition = expression;

        if (ObjectHelper.isEmpty(languageName) && ObjectHelper.isEmpty(expressionDefinition)) {
            route = route.split(Builder.body());
        } else if (ObjectHelper.isNotEmpty(expressionDefinition)) {

            if (ObjectHelper.isEmpty(languageName)) {
                languageName = "simple";
            }

            // A small hack until https://issues.apache.org/jira/browse/CAMEL-12079
            // gets fixed so we can support the 'bean::method' annotation as done by
            // Function step definition
            if ("bean".equals(languageName) && expressionDefinition.contains("::")) {
                expressionDefinition = expressionDefinition.replace("::", "?method=");
            }

            final Language splitLanguage = context.resolveLanguage(languageName);
            final Expression splitExpression = splitLanguage.createExpression(expressionDefinition);

            route = route.split(splitExpression).aggregationStrategy(new UseOriginalAggregationStrategy(null, false));
        }

        return Optional.of(route);
    }
}
```

**syndesis-extension-definition.json**
`{
  "name" : "Split",
  "description" : "Split the Exchange",
  "extensionId" : "io.syndesis.extensions:syndesis-extension-split",
  "version" : "1.0.0",
  "actions" : [ {
    "id" : "split",
    "name" : "Split",
    "description" : "Split your exchange",
    "descriptor" : {
      "kind" : "STEP",
      "entrypoint" : "io.syndesis.extension.split.SplitAction",
      "inputDataShape" : {
        "kind" : "any"
      },
      "outputDataShape" : {
        "name" : "person",
        "kind" : "any",
        "specification" : "{'name':'juan','lastName':'perez'}"
      },
      "propertyDefinitionSteps" : [ {
        "description" : "extension-properties",
        "name" : "extension-properties",
        "properties" : {
          "language" : {
            "componentProperty" : false,
            "deprecated" : false,
            "description" : "The language used for the expression",
            "displayName" : "Language",
            "javaType" : "java.lang.String",
            "kind" : "parameter",
            "required" : false,
            "secret" : false,
            "type" : "string",
            "raw" : false
          },
          "expression" : {
            "componentProperty" : false,
            "deprecated" : false,
            "description" : "The expression used to split the exchange",
            "displayName" : "Expression",
            "javaType" : "java.lang.String",
            "kind" : "parameter",
            "required" : false,
            "secret" : false,
            "type" : "string",
            "raw" : false
          }
        }
      } ]
    },
    "tags" : [ "extension", "split" ],
    "actionType" : "step"
  } ],
  "dependencies" : [ {
    "type" : "MAVEN",
    "id" : "io.syndesis.extension:extension-api:jar:1.3.4.fuse-000002"
  }, {
    "type" : "MAVEN",
    "id" : "org.apache.camel:camel-jsonpath:jar:2.20.1"
  } ],
  "extensionType" : "Steps",
  "schemaVersion" : "v1"
}`

## Tasks involved / Steps to Reproduce

1.Create Step extension in Java
2.Add DataShape annotation with kind=json-instance and a specification
3.Run mvn clean package
4.Verify that syndesis-extension-definition.json describes de step as having an outputDataShape of kind=any

**Comment by zregvart** [comment]
Thanks for reporting this issue! One thing I noticed is that we seem to require a clean build for shape changes to be applied.

@pszuster can you try doing a `mvn clean package` and taking a peek in the `syndesis-extension-definition.json`?

If it contains the correct shape definition I think we need to fix incremental development story in the extensions Maven plugin.

**Comment by pszuster** [comment]
I'm afraid `mvn clean package` is what I've been using, and the result is it doesn't honour kind definiton

**Comment by lburgazzoli** [comment]
Will have a look
