### ISSUE TITLE
[ENH] AWS Component - set CamelAwsS3Key header

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis#2691]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

When AWS is used as a producer the write operation fails unless header `CamelAwsS3Key` is set. A workaround is to set it explicitly via a set header external extension or via a script.
We should provide a way to perform the operation in a way smoother way.

## Expected behavior

Allow this comoponent to be used without additional component required.

**Comment by oscerd** [comment]
Looking at it this week
