### ISSUE TITLE
Zero/negative/not integer value for time interval is allowed

### ISSUE THREAD

**Issue by tplevko** [syndesisio/syndesis#2692]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

User is able to set negative (also not-integer) value for Period. 

## Expected behavior

There could be some sort of validation to prevent this behavior.

## Screenshot

![negative_int_time](https://user-images.githubusercontent.com/4180208/40310309-9e5837b0-5d0c-11e8-9a5c-df6af67f5f55.gif)

## Tasks involved / Steps to Reproduce

1. Create new Integration
2. Select DB connection as input
3. Set the time period to whatever you want
4. Go on with creating integration

**Comment by gashcrumb** [comment]
It's a bug, not a feature :-)
