### ISSUE TITLE
Import and publish of integration with same name is possible

### ISSUE THREAD

**Issue by tplevko** [syndesisio/syndesis#2694]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

It is possible to import integration with the same name as has the already running integration in syndesis.
If the imported integration is published, the running pod in syndesis is rewritten with the newly published integration, both then end up in inconsistent "Published" state.

## Expected behavior

The user should not be allowed to import integration with the same name, or the one integration should be rewritten (the user should be notified about this).

## Screenshot

![out](https://user-images.githubusercontent.com/4180208/40348371-d99baad6-5da3-11e8-9b61-1a25bf61b739.gif)

![same_name_integration](https://user-images.githubusercontent.com/4180208/40348397-eb5e9526-5da3-11e8-8fbd-007a6a08c141.png)

## Tasks involved / Steps to Reproduce

1. Create integration with "name"
2. Import an integration with the same "name" - previously created and exported 
3. Publish the integration with the same name
4. Observe the build and deployment on openshift

**Comment by gashcrumb** [comment]
Ah, this is actually a server-side thing, lemme verify the behavior though.

**Comment by gashcrumb** [comment]
Yeah, this still happens, guess it's really because both integrations have different IDs.

**Comment by heiko-braun** [comment]
//cc @dhirajsb Is this something you could look into?

**Comment by dhirajsb** [comment]
@gashcrumb so this is an insidious use case. When the ids match, it's obvious it's the _same_ integration. 
If the names match, can Syndesis be sure it's the same integration? What if the name is something generic, like 'my-integration', won't it end up overwriting a different intregration.

**Comment by dhirajsb** [comment]
And there is a duplicate name issue with importing connections and extensions with a different id but same name. For e.g. `my-connection` or `my-extension`.

**Comment by gashcrumb** [comment]
Yeah, I mean IDs are unique for sure, I don't think we really have much of a technical reason for unique names do we?

Still, if we have name clashes like this and we care about name uniqueness, we could just append a `(copy)` or `(2)` or something during the import operation and be done with it :-)

**Comment by dhirajsb** [comment]
@gashcrumb yeah, that's the short term solution I've been working on. It'll add a suffix `-imported-nnn` to avoid name conflicts  for integrations and connections when ids don't match. 

This should be resolved by a longer term epic to implement a feature to support an _import integration workflow_ that supports user intervention for ambiguous cases like these.

**Comment by gashcrumb** [comment]
Yeah, importing definitely needs more work :-)
