### ISSUE TITLE
[UX] Investigate integration with Apicur.io 

### ISSUE THREAD

**Issue by dongniwang** [syndesisio/syndesis#2698]
Placehoder issue for apicur.io UX work

**Comment by dongniwang** [comment]
UX design for Apicurio integration is available for review via [UX tracker](https://syndesisio.github.io/syndesis-ux/). Thank you!

**Comment by gashcrumb** [comment]
I've left some comments, I think there's a few tweaks needed.

Also an important point is at the F2F a lot of concern was raised about having a whole new app embedded in the context of a wizard.  As the page flow is, upload/import some file, look at a review, then you click a button and poof you're in a new complicated editor, you make some changes, click 'Done' or 'Save' but then you're not actually done, you still have to finish the wizard.

What if the user needs to go to lunch midway through this?  I don't know what kind of persistence is available at this point, i.e. is the file saved?  When are my changes in apicurio saved?

I feel like we should reconsider how this integration works again, wouldn't it make more sense to only offer editing the API definition *after* it's been imported as an option off of the connection details page or off of the API connector detail page.

Also, I'm kinda questioning embedding apicurio vs having it a separate page.  Embedding it fattens up the UI's dependency tree more, we're adding another app that needs to get downloaded as the app starts up.  Though if it's a separate page, then it *really* doesn't make sense to me to have it as part of a wizard.

@kahboom @kcbabo @gaughan thoughts?  If I'm making crazy talk just ignore me :-)

**Comment by amysueg** [comment]
@gashcrumb  The design was predicated on the decision to embed apicur.io. Further discussion led us to conclude that it would be a natural part of the API connector flow and thus led to including it in the wizard. We added the full-screen mode so that a user wouldn't be confined to that small screen area for editing.

I hear what you're saying about persistence and going to lunch (!) though.  So that is important, and work should not be lost if the user steps away (from anything in Syndesis).

**Comment by kahboom** [comment]
Thank you @dongniwang for the designs, and for ensuring to clarify that error validation and more complex UI enhancements should be reserved for 7.2. Feedback on the existing designs, based on the embedded route:

- For Step 1, I thought we agreed to rename "Swagger Specification" to "OpenAPI Specification"? See discussion [here](https://docs.google.com/presentation/d/1egrXJdO-7M_5NNgyeJev2EChAOw_FJrCwt3nLR5ADXg/edit?ts=5b33428f#slide=id.g3be5e89773_0_9).
- For Step 2, do we still want to show Errors in a negative way to users, implying that they've made a mistake? I listed that as feedback from John Varhaeg @jpav in the doc [here](https://docs.google.com/document/d/165dPV4TsPfvlSIyNMHQ8jXt4PSYmvFTRKLbz8R9HMBU/edit?ts=5b02be8a#heading=h.oe0r2gmmvx21).
- +1 to the change to "Review/Edit API Definition"
- Within the editor, there was some discussion about having two Cancel buttons and the Done button in the same UXD walkthrough above ([link](https://docs.google.com/presentation/d/1egrXJdO-7M_5NNgyeJev2EChAOw_FJrCwt3nLR5ADXg/edit?ts=5b33428f#slide=id.g3be5e89773_0_37)). Are we making any changes about this?

Some additional discussions in the UXD walkthrough slide deck that I think are a bit more up-to-date.

---

@gashcrumb - I'm sure @kcbabo can chime on on the idea of integrating, or even embedding, Apicurio as a whole.

At the F2F, there were a lot of different and conflicting opinions about where/if Apicurio should be a part of the API connector user flow, which I've outlined [here](https://docs.google.com/document/d/165dPV4TsPfvlSIyNMHQ8jXt4PSYmvFTRKLbz8R9HMBU/edit?ts=5b02be8a#heading=h.oe0r2gmmvx21).

Persistence is always done on the Syndesis side, and if the user went to a long lunch, I would think it's kind of the same situation they'd run into if they were creating an integration or connection? We could add the option to save as a draft, of course, for the next release, if that's a major concern.

**Comment by gashcrumb** [comment]
Yep, just had a call and we're on the same page, so +1 with some changes that @dongniwang is working on right now.  @kahboom how is #2886 coming along?

**Comment by gashcrumb** [comment]
We've decided that Syndesis makes folks so efficient, they don't need to stop and have lunch but can instead get their work done quickly in a single session :-)

**Comment by dongniwang** [comment]
V2 of UX design is available [here](https://redhat.invisionapp.com/share/2EM4HUZD4MA). Please review. Thank you!

**Comment by dongniwang** [comment]
See latest UX design via [UX tracker](https://syndesisio.github.io/syndesis-ux/). Closing this issue for now.

I will open a new issue to explore some design options to address the concern about not giving user context and share that with the team later.
