### ISSUE TITLE
Able to veiw avalable/installed headers for component/connection

### ISSUE THREAD

**Issue by dmvolod** [syndesisio/syndesis#2702]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
It's not able to get a list of available headers which is possible to set on the component or connection level. However there are no metadata for headers such as for UriPath or UriParam in Camel. Looks like components need to be extended or store this data inside extension meta, but need to be synconized depends of base Camel version.

**Comment by oscerd** [comment]
To have a feature like this one we should need to harmonize the way header are declared in all the camel components and add them to the catalog. Not super easy.

**Comment by dmvolod** [comment]
@oscerd , yes, I know that this not easy for implement in Camel, but in another way it's possible to store this info inside syndesis component/component meta.

@zregvart not, it's much more related to "citizen developers" rather than technical one. For example, if  we use a pooling consumer connection which receive some metadata in headers (i.e. CamelFileName or other) developers need to know in which headers will come required attribute. It's clear for Camel developers but not clear for otherwise.

**Comment by zregvart** [comment]
@dmvolod our whole premise is that citizen developers would not know anything about headers and frankly they should not care about headers. If there is data for them to operate on it should be in the data shapes. That's one of the reasons we're not using Camel components directly but exposing their functionality via a simplified Syndesis connector contract.

**Comment by zregvart** [comment]
Yeah, I'm still not sold on this. I would like to see a use case for the citizen ~~developer~~ integrator where something like this is needed that the data shapes are not already solving.
