### ISSUE TITLE
syndesis-extension-definition-schema.json is outdated

### ISSUE THREAD

**Issue by apupier** [syndesisio/syndesis#2719]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
some newly added attributes are not available in the schema such as componentProperty and secret

## Tasks involved / Steps to Reproduce

1.
2.
3.
4.

**Comment by zregvart** [comment]
Fixed with #2723
