### ISSUE TITLE
The build generates changed *.json files

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#2721]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

After running a full build (`syndesis build -f -c`) some connector json files are changed:

![capture](https://user-images.githubusercontent.com/351660/40790775-c91c89a6-64c3-11e8-8883-d9c4f3cc3fa9.PNG)

Now I gotta go and uncommit these files.

**Comment by zregvart** [comment]
I think #2436 will fix this.

**Comment by lburgazzoli** [comment]
we need to migrate odata and rest-swagger to the new connector model.

btw, the odata stuff has never been included in our connector list so maybe we should move it to `attic`
