### ISSUE TITLE
consoleUrl handling should add "/console" if missing

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#2730]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

To make provisioning on OSO easier, the consoleUrl used in the UI to point to the runtime pod's log can be provided without the trailing `/console` part (which is the same on every OpenShift instance). The usage in https://github.com/syndesisio/syndesis/blob/d944eebbfe9360eace136d44efe08ba83139dd97/app/ui/src/app/integration/integration_detail/integration_activity/integration-activity.component.ts#L127-L129 should be that smart to deal with both variants (with and without trailing `/console`)

**Comment by gashcrumb** [comment]
I think it's possible to configure the openshift console to be under any context, so `/console` isn't an absolute certainty.

**Comment by rhuss** [comment]
Not really sure, haven't ever seen this in another flavor. But well, not sure either ...

**Comment by astefanutti** [comment]
It seems on OpenShift, a get request on the API server with a Web browser user agent header returns a 302 response with the location of the OpenShift Web console. That can be used to auto-discover the Web console URL from a pod and avoid an additional parameter in the template.

**Comment by gashcrumb** [comment]
That 302 redirect can't be intercepted via javascript as far as I know, the browser transparently follows it even for XHR requests, and I'm not sure that the `Location` header is available when that happens.

**Comment by astefanutti** [comment]
Indeed, that needs to be done server-side. I did something like that in Hawtio online:
https://github.com/hawtio/hawtio-online/blob/45a8274898ca3b1adba173ba5382060fcf223995/docker/nginx.conf#L45-L54

May be hacky, still convenient by the time OpenShift provides a proper way to discover the console URL.

**Comment by gashcrumb** [comment]
@astefanutti that's not hacky, it's problem solving :-)

**Comment by astefanutti** [comment]
> that's not hacky, it's problem solving :-)

@gashcrumb love that statement 😄! I'll quote you conveniently 😉

**Comment by rhuss** [comment]
During startup we could indeeed probe the API server from the backend and extract that information which then is delivered as some part of configuration to the UI. 

This would solve the issue of

* Having infrastructure related configuration in the UI config map
* Avoid to have to use a dedicated console URL during template instantiation

**Comment by rhuss** [comment]
I think this is still an issue, at least the OSO teams uses workarounds to add this "/console" part as they only have the base URL.  Not sure whether and how we should continue on this issue ...
