### ISSUE TITLE
[ENH] UX + IMPL - Detect stale user session

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis#2733]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

I need our UI expert comments here, but I'm not sure if we are currently degrading gracefully in presence of networking issues. I think we currently raise multiple and independent toast notification that shouldn't really matter from a UX perspective.

## Expected behavior

By chance, I had a tab an OpenShift left open for the whole weekend, that has seen multiple local ip address change.
OpenShift seems to solve this the above issue elegantly, from UX pov: a single toast notification with a message saying something like: "Connection to the server was lost. Please click this link to refresh". And clicking the "refresh" button had the same effect of clicking the browser refresh button.
This felt very polished, with no low lever errors leaking.
Can we say we have anything like this? Can we have it?

## Screenshot

I've forgot  to take a screenshot this time. I can try to add it later.

**Comment by paoloantinori** [comment]
@gashcrumb can you comment on this?

**Comment by gashcrumb** [comment]
Yeah, so at the moment all HTTP errors are converted right into toast notifications in a catch-all error handler, so this case is gonna look like a mess :-)

I think we can trim down what that error handler reports first of all, I honestly don't think every HTTP error needs to be surfaced back to the user.  And for HTTP 400 we can show a similar persistent toast notification with the same refresh link.

**Comment by michael-coker** [comment]
There is also a [session timeout](http://www.patternfly.org/pattern-library/communication/session-timeout/#overview) pattern in patternfly that we could tweak to fit our usage, which is similar.

**Comment by gashcrumb** [comment]
Yeah, that'd be good.  We could use that kind of thing when there's a bunch of connectivity issues.

I actually haven't been able to figure out though how to cause a session timeout or loss of access other than just doing stuff like leaving the tab open for days on end which doesn't help me figure out what we need to handle.

Anybody know how to (for example) force the token to expire that oauth proxy uses so the UI gets errors back?  Or does it just not happen?

**Comment by gashcrumb** [comment]
Oh and scaling down the server pod, I can trigger a modal or notification for that easily enough, but it'd be nice if there's other cases we need to handle and how to force those cases in a controlled way.

**Comment by michael-coker** [comment]
You can use the "offline" box under "application -> service workers" in the chrome dev tools

![screen shot 2018-06-05 at 3 11 24 pm](https://user-images.githubusercontent.com/35148959/41000191-cda896c8-68d2-11e8-8114-0bde812c67ae.png)

**Comment by gashcrumb** [comment]
So for HTTP status codes 0, 502, 503 and 504 I have this message popping out:

![capture](https://user-images.githubusercontent.com/351660/41908996-cd4a8e6a-7913-11e8-8d0d-50bb34078fa9.PNG)

Unfortunately I can't add a refresh link with the current way the patternfly-ng notification service is implemented, there's support for Actions in the notification service API but they don't seem to appear or actually have any way of being used, so had to stick with generic instructions for now.  But, at least you don't get a zillion notifications, just 1 and then all the other errors just get logged to the console.  PR in a few...
