### ISSUE TITLE
Add templating to AtlasMap

### ISSUE THREAD

**Issue by nicolaferraro** [syndesisio/syndesis#2735]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Issue #2636 about the Gmail connector highlighted how a templating mechanism is needed in order to do some tasks like writing the text of a email, using input fields as values of the template (@rhuss, @kcbabo ).

A possible solution described in #2636 mentions a "Templating Step", but after brainstorming with @oscerd and @lburgazzoli, it appears that templating can be added to Atlasmap, since **it's not so different from the combine action** already available.

I've hacked the UI to summarize the idea. In the picture I use the fields *name* and *surname* to produce the body of the email I'm going to send.

## Screenshot

![syndesis templating](https://user-images.githubusercontent.com/4151857/40865300-ecbd0068-65f7-11e8-975f-ac82c5300743.png)

I think this should be easy to implement (@igarashitm, @pleacu).
Do you think it's worth to analyze this proposal together with @syndesisio/uxd ?

**Comment by jpav** [comment]
Yes, I'd agree

**Comment by nicolaferraro** [comment]
Very good, can I move this under the "Atlasmap Enhancements" epic #2643?

**Comment by jpav** [comment]
Yes

**Comment by kcbabo** [comment]
I like the idea of having template support in the mapper in general. That said, I don't think it's necessarily a good fit for email templates for the following reasons:

- Email content could get quite large and the right frame text area is unlikely to scale gracefully to handle large content.
- A template is usually going to be a single target for email and not one field among many others, so treating all template substitutions as a single mapping seems a bit odd.
- If an email has many 10+ substitution properties, using token syntax in a field mapping is gonna be rough.

A better solution that involves data mapper would be to have a template step which declares a data shape based on the tokens defined in the template.  A user would add the template step and then a data mapping step before it which then has a set of target fields that correspond to the substitution properties in the template.

Like I said above, I think the template capability is independently useful in the data mapper so we should do it anyway.  I just don't think it's a great fit for the email use case.

@gaughan - FYI

**Comment by rhuss** [comment]
I think templating would be a nice addition for the mapper but I share @kcbabo 's concerns.

Also, I would **not** use positional template parameters, as they are hard to memorize and can change if you reorder field. Template parameters should always be symbolic.

**Comment by igarashitm** [comment]
Removed from AtlasMap enhancement epic for now - atlasmap/atlasmap#46 is going to be implemented independently. Let's keep discussing here to satisfy E-Mail usecase in Syndesis including template step @kcbabo suggested.

**Comment by rhuss** [comment]
@igarashitm just a heads up that this issue has been closed now. Anything we should take over into another issue to not lose the ideas collected here ?

**Comment by zregvart** [comment]
We have a [template step now](https://github.com/syndesisio/syndesis/issues/3047).
