### ISSUE TITLE
Provide a Kafka connector

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/syndesis#2737]
## User Stories

- #2765 
- #2766

**Comment by chirino** [comment]
It would be nice if we could validate the connector can connect to a deployment of https://github.com/strimzi/strimzi which provides Kafka on OpenShift.

**Comment by nicolaferraro** [comment]
I've added this issue to the "other connectors" epic for 7.1.

First step is to provide a connector that is able to send/receive messages from a Kafka broker deployed with Strimzi. We have a connector for AMQP, we can do something similar for Kafka.

Let's address the most basic Strimzi/Kafka configuration first.

**Comment by nicolaferraro** [comment]
@valdar, user story here #2765.
