### ISSUE TITLE
As an expert integrator, create a Gmail connection

### ISSUE THREAD

**Issue by kcbabo** [syndesisio/syndesis#2753]
As an expert integrator, I want the ability to create Gmail connections so that my organization can send and receive emails from a Gmail account.  Each connection should represent a single Gmail account.  There is no connection configuration other than OAuth configuration for authentication.  I expect to configure OAuth client configuration for Gmail through the OAuth Application Management settings in Syndesis and to initiate an OAuth grant when creating the Gmail connection.

**Comment by paoloantinori** [comment]
@oscerd reading this user story, can we archive this as done? or is there anything else we have to implement?

**Comment by oscerd** [comment]
I believe we've done.
