### ISSUE TITLE
As a citizen integrator, send and receive Gmail in integration flows

### ISSUE THREAD

**Issue by kcbabo** [syndesisio/syndesis#2754]
As a citizen integrator, I want to send and receive Gmail from within an integration flow.  Gmail connections should support two actions:
* Receive email : used only in a start connection.  This action should trigger an integration flow for each unread message in my account.  Emails are processed individually - if there are 10 unread emails in my account, the integration flow will be triggered 10 times.  Configuration of this action should allow me to specify one or more labels to perform selective processing of messages in my account.  Processed messages should be flagged in some way (ideally via labels) in Gmail so that they are not reprocessed.
* Send email : used in a step or finish connection.  This action should send an email where the body of the email is based on the most recent data present in an integration flow.  Action configuration should allow me to specify the subject, to (1:*), cc (0:*), and bcc (0:*) for the email message.  Email addresses should be validated for correct syntax.

**Comment by paoloantinori** [comment]
@oscerd have we fully addressed this user story? if not, what's missing?

**Comment by oscerd** [comment]
We should
