### ISSUE TITLE
UX Visuals: Icons for 7.1 Connectors

### ISSUE THREAD

**Issue by sjcox-rh** [syndesisio/syndesis#2756]
## This is a...

<pre><code>
[. ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

There are 5 new connectors for 7.1. Icons will need to be created for each.
- Gmail
- Webhooks
- Service Now
- Concur
- Kafka

## Tasks involved / Steps to Reproduce

1. Create Icons
2. Review with stakeholders
3. Deliver

**Comment by amysueg** [comment]
@sjcox-rh @paoloantinori @heiko-braun Have all the developers who are working on adding the 5 new connectors for 7.1 contacted @sjcox-rh to request icons for their connectors?

**Comment by sjcox-rh** [comment]
@amysueg I haven't heard from anyone yet. @paoloantinori Who should I reach out to for each of the 5 new connectors we're introducing?

**Comment by heiko-braun** [comment]
@sjcox-rh I've emailed the team. Expect them to respond here.

**Comment by oscerd** [comment]
For the gmail connector the icons are already inside syndesis, so we are ok.

**Comment by KurtStam** [comment]
@amysueg I'm working on the concur connector, and will add it in once one becomes available.

**Comment by zregvart** [comment]
Let's just try using Concur icon from their from the press kit. See the discussion at https://github.com/syndesisio/syndesis/issues/1290#issuecomment-362225431

**Comment by zregvart** [comment]
I've created a PR for the Concur icon/description in #2822

**Comment by sjcox-rh** [comment]
@zregvart sounds good. Agreed that we should use the official icon for any connection that already has established branding. Do you have access to Concur's icon or do you want me to grab it?

**Comment by valdar** [comment]
I'm working on Kafka connector, I think we can use the Kafka official icon https://kafka.apache.org/ ?

**Comment by zregvart** [comment]
> @zregvart sounds good. Agreed that we should use the official icon for any connection that already has established branding. Do you have access to Concur's icon or do you want me to grab it?

@sjcox-rh yeah, we could have nabbed it prior to SAP acquisition now the brand/icon download page is behind a registration process and mostly broken anyhow. So I've downloaded the bitmap from the website and retraced so we have a vector version in #2822. It wasn't much work as it's a super simple logo. I didn't include the blue "SAP" flag that seems to be on the left in some variants, just the concur "C" in the square. If I had access to the style guide (registration/broken) I would know if this is the right way to use their branding. So if you can double check on that by somehow getting through to the style guide that would be helpful.

**Comment by nicolaferraro** [comment]
I think there should be a icon for webhooks too. Webhooks icons are similar across websites, but there's not a official one. The one I used in the demo is not so bad...

**Comment by sjcox-rh** [comment]
Just merged a PR with the remaining icons: PR #2856 

Gmail and Concur icons are good to go thanks to @zregvart and @oscerd.

Please go [here](https://github.com/syndesisio/syndesis/tree/master/ux/connections_icons/svg) to grab the svg's for the following icons:

- ServiceNow
- Webhooks
- Kafka

@nicolaferraro and @valdar, I know you both already have the icons but wanted to provide you with the svg just in case you are using a png since vectors are preferred. If you are already using the svg, then ignore this!

**Comment by sjcox-rh** [comment]
@amysueg I think all icons for this sprint are accounted for. Going to close this!
