### ISSUE TITLE
[datamapper] Field search from Mapping Details pane doesn't work

### ISSUE THREAD

**Issue by igarashitm** [syndesisio/syndesis#2759]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
Once you select multiple fields at source or target, the active mapping transitions to Combine/Separate, then you can add more source/target fields from Mapping Details pane by pushing "Add Source" or "Add Target" button.
Then you get the search box immediately, but the search is not somehow working within Syndesis.

## Expected behavior
Show field search results and allow selecting one of them.

**Comment by igarashitm** [comment]
Since it's working as expected in AtlasMap standalone, my guess is that it's coming from dependency mismatch, as AtlasMap updated to Angular6 and rxjs6. Let's see after we finish the version alignment via #2739.

@mcada FYI

**Comment by mcada** [comment]
It looks like after angular update this issue is no longer present, closing.
