### ISSUE TITLE
Data Mapper CSS isn't scoped and affecting other pages in syndesis

### ISSUE THREAD

**Issue by michael-coker** [syndesisio/syndesis#2760]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
Data mapper loads CSS that isn't scoped to the data mapper and is affecting other parts of the syndesis UI.

## Expected behavior
Data mapper CSS should be scoped.

## Screenshot
![screen shot 2018-06-05 at 1 52 58 pm](https://user-images.githubusercontent.com/35148959/40996584-c67bac2e-68c7-11e8-8612-9cf91e0443d3.png)

## Tasks involved / Steps to Reproduce

1. Create or edit an integration and load the data mapper step
2. Create a new integration, choose "twitter" -> "mention" and look at the alert message

**Comment by pleacu** [comment]
This issue has been corrected in the Atlas data mapper with the fix for https://github.com/atlasmap/atlasmap/issues/457
