### ISSUE TITLE
As an expert integrator, create a Kafka connection

### ISSUE THREAD

**Issue by kcbabo** [syndesisio/syndesis#2765]
As an expert integrator, I need to connect my Syndesis environment to our Kafka-based messaging services. The connection configuration page should allow me to enter a broker URL directly, but should also list any Kafka brokers that are currently available within my OpenShift environment.

**Comment by kcbabo** [comment]
@gaughan - FYI
@chirino  - I need to know if there are any other configuration settings we need to consider at the connection level (SSL, clientId, etc.)

**Comment by valdar** [comment]
@kcbabo SSL is definitely something to consider, but right now Strimzi.io does not support deploying SSL enabled kafka brokers; see http://strimzi.io/roadmap/ .

**Comment by kcbabo** [comment]
Okie dokie.  Thanks for the update.

**Comment by valdar** [comment]
@kcbabo at first glance wasn't that easy to "discover" strimzi.io deployed kafka brokers in the same ocp cluster, so I opened an issue https://github.com/strimzi/strimzi-kafka-operator/issues/504 and provided a possible solution https://github.com/strimzi/strimzi-kafka-operator/pull/505 .
