### ISSUE TITLE
As a citizen integrator, I need to send and receive messages using Kafka topics

### ISSUE THREAD

**Issue by kcbabo** [syndesisio/syndesis#2766]
As a citizen integrator, I want to interact with Kafka topics within integration flows.  My initial requirements are similar to other messaging providers supported in Syndesis:
* Receive a message from a Kafka topic (Start connection only)
* Send a message to a Kafka topic (Step and Finish connection only)

Configuration for both topics is limited to specifying the topic name I'm connecting to.  If there is a way to query/discover topic names and present them as a list, that would be ideal.

**Comment by kcbabo** [comment]
@gaughan - FYI

**Comment by paoloantinori** [comment]
@valdar what's our current compliance with this user story?
