### ISSUE TITLE
ui/ux - show activity progress while fetching actions' metadata

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#2777]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

When the UI grab dynamic metadata for a connector like enums, datashapes and so on there's no visual indication that the activity is ongoing so in case the retrieval of dynamic meta-data requires tens of seconds to complete the UI seems not responsive. 

## Expected behavior

If retrieving metadata takes more that a pre-defined  amount of time a visual indication should appear.

**Comment by gashcrumb** [comment]
Which page exactly does this happen on?

**Comment by lburgazzoli** [comment]
It may happen when you have completed the set-up of a step and you click "next" at that point UI queries the backend for some dynamic metadata and i.e. in case of servicenow (which is a connector I'm working on) this query takes quite a few seconds

**Comment by gashcrumb** [comment]
Ah, so after configuring the step but before the UI would maybe show data shapes?
