### ISSUE TITLE
ui/ux : show connector documentation while creating a connection 

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#2783]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Sometime a connector requires some specific configuration or privileges on the target system, so it would be nice to have a way to list requirements when a connection is being created. 

As example, the ServiceNow account used by syndesis in the upcomig ServiceNow connector, needs some privileges to compute data shapes and dynamically retrieve the objects to operate on.

## Expected behavior

A minimal documentation should be displayed on connection creation page.

**Comment by gashcrumb** [comment]
@sjcox-rh @dongniwang FYI

**Comment by dongniwang** [comment]
I'm a little bit confused since we're talking about both connector and connection here. 
- ServiceNow is an out of box connector we provide, right? 
- This link/documentation is something users need to reference during the connection creation flow? 

> so it would be nice to have a way to list requirements when a connection is being created.
what kind of requirements are we talking about here? ^^ 

cc: @sjcox-rh @amysueg - could be something useful to add to the connection template.

**Comment by lburgazzoli** [comment]
@dongniwang 

I'm talking about connection because it is where the user configure a connector so it feels natural to me to show requirements about the connection on that page.

About your question:

1. it will
2. It is something a user need to communicate to the it department when asking for a servicenow account (or do it if the user has the knowledge to do it)

@gashcrumb 

I was thinking about embedding the information because of external developed connector where it may be easier to describe what it is needed directly in the connector descriptor. for connectors we ship, we can just point to the related documentation.

**Comment by sjcox-rh** [comment]
I'm trying to understand the requirement, so you're saying for certain connectors, we would need to show additional information during the creation flow?

<img width="1119" alt="screen shot 2018-06-08 at 10 01 04 am" src="https://user-images.githubusercontent.com/16257540/41170880-3062bc9e-6b03-11e8-80f2-57511575d046.png">

So would it make sense to add a link to the top of the configuration section that would open a new tab when the user can find all of the info OR just list the requirements at the top within the step?

OR, if it's a lot of information that would be shown, would it make sense to add an additional step before the configuration step. If we did that, what would the actions be the user needs to take, or is it just consuming?

**Comment by lburgazzoli** [comment]
I'd say it is more like a README for the connector that tells you how to set up the connections so it may be shown in form of welcome page after selecting the connector (if the connector require so) and before configuring it. 

To be honest I do not k now what is the best way and a link would definitively work for me but it may be a little bit problematic for connectors developed by expert developers or by the community
