### ISSUE TITLE
change wording in extension file uploader from "importing" to "uploading"

### ISSUE THREAD

**Issue by michael-coker** [syndesisio/syndesis#2784]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
The file uploader statuses use the word "import" when they should use "upload".

Addresses the first comment in https://github.com/syndesisio/syndesis/issues/2569

## Tasks involved / Steps to Reproduce
1. Go to customizations and import an extension (you can use [this one](https://drive.google.com/file/d/1bwDvQfkjkJLO4HDbuA6O9sqFds7WxPHY/view?usp=sharing))
2. Note the wording

**Comment by gashcrumb** [comment]
I've already got a fix for this one, opening the PR in a minute...

**Comment by gashcrumb** [comment]
this one -> https://github.com/syndesisio/syndesis/pull/2786
