### ISSUE TITLE
[extension] let user to select which library/technical extension an integration should pick up

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#2808]
See also **https://issues.jboss.org/browse/ENTESB-11535**

## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

It is not possible to choose which library extensions an integration should include a user should be able to include extension that provide error handlers or route policies to an integration.

## Expected behavior

While creating an integration, the user should be able to associate a library extension to an integration.

**Comment by dongniwang** [comment]
@lburgazzoli - 

I'm assuming users first need to upload a library extension, then they can associate the library extension to an integration. In other words, this is an optional feature on the UI? 

Would users be expecting to configure this while they're creating the integration - in the integration editor? Is this some sort of integration properties?

**Comment by dongniwang** [comment]
Hi @lburgazzoli, after talking to @michael-coker, I had another question, can users associate multiple extensions to one integration? Is error handler or route policies consider one extension? Thanks!

**Comment by lburgazzoli** [comment]
Yes the workflow does not change so a user need first to upload an extension then, while setting up the integration it has the option to associate one extension to the integration. As first iteration I'd say thet it is enough to be able to select the extension, using properties need some sork on the extension framework.

Yes a user can associate any number of extensions to the an integration.

**Comment by dongniwang** [comment]
Hi @lburgazzoli - can you explain it to me one more time why the library extension can't be added as a normal step to the integration? 

I think we're treating a library extension as integration properties?

**Comment by lburgazzoli** [comment]
Because a library extension does not have any associated action :)

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11535**
