### ISSUE TITLE
[extension] let user to select which library/technical extension a connection should pick up

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#2809]
See also **https://issues.jboss.org/browse/ENTESB-11534**

## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

It is not possible to choose which library extensions a connection should include i.e. jdbc driver are added using tags which means that an integration using an sql connector does not have only the driver needed for the connection but all the known ones.

## Expected behavior

While creating a connection, the user should be able to associate a library extension to the connection.

**Comment by dongniwang** [comment]
Hey @lburgazzoli, thanks for opening a separate issue here, I have a couple questions regarding the use case: 
- Is this JDBC driver selection only showing up when users are trying to create a SQL connection? 
- What do you mean by "JDBC driver are added using tags"? 
- How many JDBC drivers would users normally see here? 
- Are we able to surface some kind of description for each JDBC driver? How would users be able to tell which one is the one they wanted? 

Thanks! 

cc: @amysueg @gashcrumb

**Comment by lburgazzoli** [comment]
1. yes user should be able to choose the jdbc driver upon connection configuration
2. As today there's no possibility to cherry pick the right jdbc driver for an integration so the runtime pick up all the extension of type library that have a tag `jdbc-driver`
3. what do you mean ?
4. We can show the extension descriptor, name and maybe version or we can add some specific metadata but in general yes, we should be able to show some info.

**Comment by dongniwang** [comment]
@lburgazzoli - do you happen to have a screenshot of the connection configuration for sql connector that you can share with me? Thanks!

**Comment by lburgazzoli** [comment]
![image](https://user-images.githubusercontent.com/1868933/42743831-154e7b4a-88c8-11e8-98a6-3ad9e4b7f16d.png)

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11534**
