### ISSUE TITLE
Importing integration twice causes UI to fail

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#2824]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

From what I understand - importing integration twice should just replace the previous one.

Expected:
![import_success](https://user-images.githubusercontent.com/14313995/41464479-c1b785ca-709a-11e8-8559-e29fbcc0470d.png)

But cancel and done buttons look like this:

![import_fail](https://user-images.githubusercontent.com/14313995/41464300-1a4de8e2-709a-11e8-9f70-7b4ad294e536.png)

Note that those buttons have no functionality as the integration is already imported when those buttons appear. Maybe remove them and just put there OK button?

Also note that information about imported integration is not complete - there is no name of integration and info about salesforce connection is also missing.

I used this integration for reproducing 
[Integration_import_export_test-export.zip](https://github.com/syndesisio/syndesis/files/2105773/Integration_import_export_test-export.zip)

Import the integration. Then import the same integration again.

**Comment by gashcrumb** [comment]
Yep, this was fixed by https://github.com/syndesisio/syndesis/pull/3104
