### ISSUE TITLE
 [connectors]  Add properties to be used by meta service

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#2826]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

When doing meta data retrieval we may need to set action specific options so it would be nice to have a way to define such properties at action configuration

## Expected behavior

We should be able to set meta specific properties such as: 

```json
{
    "configuredProperties": {
        ....
    },
    "metaProperties": {
    },
}
```

**Comment by zregvart** [comment]
Perhaps this needs a bit better explanation, `configuredProperties` are action specific. Are these are properties that would influence the way we deal with metadata? In what way? How does this influence the UI?

**Comment by lburgazzoli** [comment]
`configuredProperties` are supposed to provide 'sttaic' values for endpoint and action implementation so adding additional values here adds some additional work on connector/action side as meta specific properties need to be removed.

But I need some properties specific for the meta service to properly retrieve meta data and I can of course create a switch or if/case base on the action id but I'd would like to avoid this as much as possible.

UI is not affected, this is an information that only the meta-service will receive.
