### ISSUE TITLE
[UX] No cancel button when starting/ending step of integration

### ISSUE THREAD

**Issue by avano** [syndesisio/syndesis#2834]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

This is probably by design it seems, but it is somehow weird.
When you are editing an integration, there is no cancel button when editing starting or ending step, but there is cancel button when editing step that is in between of those two. So if you click for example on ending step, you can't cancel the edit and you need to go through the step's configuration again until you hit "Done" button there

end step, no cancel button

![amq](https://user-images.githubusercontent.com/7081216/41483946-4cb1eb44-70db-11e8-8e10-72aa766fbc95.png)

middle step, cancel button present
![sf](https://user-images.githubusercontent.com/7081216/41483950-4ff48f5a-70db-11e8-98b5-772c27d20073.png)

First I thought it was difference between SF step and AMQ step, but it seems it is not that case

## Expected behavior

Cancel button to cancel the edit of any step

## Tasks involved / Steps to Reproduce

1.
2.
3.
4.

**Comment by michael-coker** [comment]
Agreed, that is a weird UX.

Also noticed that on some connections with multiple steps to configure, there is no "previous" button (to go back), and that the last configuration step on some connections is "done" and on others it's "next"
### Has cancel, previous, and "done" as it's the last step, as I would expect.

![screen shot 2018-06-18 at 10 16 00 am](https://user-images.githubusercontent.com/35148959/41545500-ebf02976-72e0-11e8-86c8-6325752a7dab.png)

### No back or cancel buttons, and "next" finishes configuring the connection

![screen shot 2018-06-18 at 10 16 21 am](https://user-images.githubusercontent.com/35148959/41545502-edcf5ca8-72e0-11e8-91b9-c7f6672a1ad3.png)

+ `notif/uxd`, and cc @dongniwang @sjcox-rh @amysueg

**Comment by dongniwang** [comment]
Feel like there might be two separate issues here...

I think there should always be a "Cancel" button at the breadcrumb level to let users exit the Integration Editor. 

For connections acting as the start or finish connections, there may be different rules applied...Basically, there are integration level controls (buttons) and connection level controls.

Would this be something we want to capture in the connection template? 

adding @gashcrumb @seanforyou23 as well

**Comment by michael-coker** [comment]
> I think there should always be a "Cancel" button at the breadcrumb level to let users exit the Integration Editor.

I updated the screenshots in my previous comment to show the full window (no buttons in the breadcrumbs)

**Comment by gashcrumb** [comment]
At the moment, the start and finish connections in the editor are special in that we force the user to define them up front, and you can't have an integration that doesn't have both of them defined.  

I think we should get rid of that restriction and work towards letting the editor be a bit more flexible, but before trying to tackle that I want to do at least the first part of #2870

**Comment by paoloantinori** [comment]
This will be addressed as part of major UX upgrade tracked here https://github.com/syndesisio/syndesis/issues/1830
