### ISSUE TITLE
Provide a way to identify corresponding step in the integration from Step ID

### ISSUE THREAD

**Issue by igarashitm** [syndesisio/syndesis#2857]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
Step ID is used for a Document ID in Syndesis datamapper step. If mapping gets error, AtlasMap emits Audit with corresponding Document ID. But since Step ID is not human readable, end user cannot identify which data had a problem in Syndesis.
We need a handy way to identify the Step in an integration visually from Step ID.

**Comment by paoloantinori** [comment]
@lburgazzoli are you the right person to give a look at this?

**Comment by lburgazzoli** [comment]
@paoloantinori I need a little bit more context and maybe an example

**Comment by paoloantinori** [comment]
I'll try to get more details but to recap the problem:

the error uses an id to identify the step with an issue, but we have no mapping between ids and high level logical name for the corresponding step, or at least this is what I understand from @igarashitm  comment.

**Comment by igarashitm** [comment]
I just reminded human readable Document Name is already delivered into AtlasMap. We'll show it as a part of Audit log (atlasmap/atlasmap#506). closing
