### ISSUE TITLE
[UX][DataMapper] Remove transformation button help causes page flickering

### ISSUE THREAD

**Issue by avano** [syndesisio/syndesis#2858]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

When hovering mouse on "Remove transformation" button in datamapper step, the whole page will start "flickering", because of the help message is prolonging the page in horizontal direction for a while

## Screenshot
![removetransform](https://user-images.githubusercontent.com/7081216/41657317-42876ee4-7493-11e8-9e69-970d11f1a0a9.gif)

In reality the flicker is much faster, the framerate of the gif is low :-)

Happens to me on chrome on linux, 1920x1080 screen
## Tasks involved / Steps to Reproduce

1. see linked gif
2.
3.
4.

**Comment by gashcrumb** [comment]
@michael-coker didn't you do some work in this area to fix some of the tooltips that were doing this?  Would you mind having a peek?

**Comment by michael-coker** [comment]
I can't seem to link my local atlasmap to syndesis. I'm following [this guide](http://docs.atlasmap.io/#developing-within-syndesis-ui), but there is no `build` target in `package.json` in atlasmap. There are only `build:lib` and `build:app` and neither seem to be building my changes.

@gashcrumb @igarashitm do you know what I might be doing wrong?

FWIW, pretty sure the fix is just to add `placement="left"` to line 6 in [mapping-field-action.component.html](https://github.com/atlasmap/atlasmap/blob/master/ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-action.component.html).

**Comment by pleacu** [comment]
Hey Andrej/Michael/Stan -
   I'll take a look at this toimorrow - Andrej - have you tried this with
the latest Data Mapper??
           --Paul

**Comment by gashcrumb** [comment]
Ah, this might have to wait for #2739 as the data mapper was recently updated to Angular 6, once #2739 is fixed we can pull in the latest and verify that this is sorted, sorry!

**Comment by michael-coker** [comment]
@gashcrumb should we revisit this? #2739 was merged, but the add transformation icon is still flickering.

**Comment by gashcrumb** [comment]
Yep, if it's still overflowing then yeah, we should try and sort this in the next sprint, let's add it.

**Comment by michael-coker** [comment]
I tried making this change again and still can't get my local atlasmap build to link to syndesis. 

The files I modified are:

#### ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-action.component.html (line 6)
```
-        <i class="fa fa-trash link" aria-hidden="true" (click)="removeAction(action)" tooltip="Remove transformation"></i>
+        <i class="fa fa-trash link" aria-hidden="true" (click)="removeAction(action)" tooltip="Remove transformation" placement="left"></i>
```

#### ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-detail.component.html (line 54)
```
-      tooltip="Add transformation"></i>
+      tooltip="Add transformation" placement="left"></i>
```

**Comment by gashcrumb** [comment]
Which directory are you running `yarn link` in within the atlasmap repo?  It should be from the `ui/dist` directory rather than the `ui` directory.

**Comment by michael-coker** [comment]
I'm running it from `ui/dist` per http://docs.atlasmap.io/#developing-within-syndesis-ui

Though it's worth noting `yarn build` in `atlasman/ui` doesn't work. I've run `yarn build:lib`, `yarn build:app`, or both, still not seeing the changes.

And in case we end up updating the atlasmap docs, `cd ${SYNDESIS}/ui` should be `cd ${SYNDESIS}/app/ui`

**Comment by igarashitm** [comment]
@michael-coker sorry for the confusion, yes it should be `${SYNDESIS}/app/ui` and also the atlasmap dist directory has been changed to `${ATLASMAP}/ui/dist/lib` after running `yarn build:lib`. I'll fix the doc.

**Comment by michael-coker** [comment]
@igarashitm thanks!
