### ISSUE TITLE
Add guard to API connector route

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis#2859]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
If you try to refresh or navigate to a URL like `https://syndesis.<url>.nip.io/customizations/api-connector/create/swagger-connector`, you will get an error related to the API Connector Detail component and having a `filter` method that does not exist for `undefined` (or similar). The page will not load properly.

## Expected behavior
This should not be loading anything from the API Connector Detail component. I believe the problem comes down to the routes. Angular thinks you are trying to load an API Connector, and is looking for an `:id` in the path, which it believes it finds and attempts to load nonexistent information about it. There should be a guard for it.

## Screenshot
<img width="1360" alt="screenshot 2018-06-20 12 38 25" src="https://user-images.githubusercontent.com/3844502/41659882-c638e37e-749a-11e8-9bf8-828a42dd5426.png">

**Comment by gashcrumb** [comment]
Perhaps a simple `redirectTo` in the route definition for that module for `/create/{id}` to `/create` might do the trick?
