### ISSUE TITLE
See about having just one action do delete records

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#2860]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

We currently have two actions to delete records Salesforce records. Perhaps it would make sense to have just the one action to make it simpler for the users. This one action can be named "Delete record" and would work exactly like "Delete record by external identifier" currently does.

## Expected behavior

Be a bit simpler on the users.

## Screenshot

![screenshot-2018-6-20 syndesis](https://user-images.githubusercontent.com/1306050/41668160-067b4c1a-74af-11e8-97c5-a2e3e033803e.png)
![screenshot-2018-6-20 syndesis 1](https://user-images.githubusercontent.com/1306050/41668206-1dbaeebc-74af-11e8-8eae-840cf4cea551.png)
![screenshot-2018-6-20 syndesis 2](https://user-images.githubusercontent.com/1306050/41668212-20c94036-74af-11e8-9967-3465cbe8e6ea.png)

cc @gaughan, @kcbabo

**Comment by zregvart** [comment]
Would be trivial to remove _Delete record_ and rename _Delete record by external identifier_ to _Delete record_, but we'd have to create a migration script for integrations that use those. Or find a way to _hide_ (deprecate) an action.

Is this only bothering me? Perhaps we can close this as non issue?

cc @gaughan

**Comment by gaughan** [comment]
@zregvart both operations are exposed by salesforce correct? If so we can probably just leave it. Otherwise, we run the risk of the issue being tackled by salesforce after we take action. Unless one of these are deprecated in the salesforce API?

**Comment by zregvart** [comment]
Yeah, both are distinct non-deprecated Salesforce APIs. I agree with your assessment, let's not complicate without good cause.
