### ISSUE TITLE
Tabs in "Customizations" are easy to miss

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#2862]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

On the *Customizations* page the tabs for *API Client Connectors* and *Extensions* are easy to miss as they're at the top of the page, and this page I think is the only one in the app that behaves like this.

Maybe we should consider moving these two pages to top-level pages in the navigation, alternatively we could consider using the two-level navigation for these two pages I guess

## Screenshot

this bit on the *customizations* page:
![screen shot 2018-06-20 at 15 36 23](https://user-images.githubusercontent.com/351660/41669000-f8eb724e-74b0-11e8-8e10-5c9a9d9a9fd2.png)

**Comment by gashcrumb** [comment]
Just a bit of feedback during the f2f

**Comment by sjcox-rh** [comment]
Adding the Notif/uxd label to this.

My concern with adding API Client Connectors and Extensions as separate sections within the main nav is if any other sections are added that would fall under the categories of "Customization" in the future.

That being said, having only 2 options within a 2nd level nav might not be the best approach either. 

<img width="737" alt="screen shot 2018-06-26 at 10 15 32 am" src="https://user-images.githubusercontent.com/16257540/41918439-578ff590-792a-11e8-8875-ba8d217ecc08.png">

Will discuss with uxd team and provide recommendation!
