### ISSUE TITLE
A maven plugin to upload an extension would be cool

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#2865]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

I mean it's awesome that we have a page to do this, but for extension developers it'd probably be nicer during extension development if there was a maven plugin that would upload/install/update an extension after building.

**Comment by zregvart** [comment]
Requires #1959
