### ISSUE TITLE
Button location refactoring

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#2869]
Let's pair up and start reworking where the buttons are located in a few spots in the app, off the top of my head:

* integration editor save/publish/cancel
* the "Add a step" and "Add a connection" buttons on the save/publish page need to go
* API client connector wizard button locations
* Create connection wizard button locations

There's more too, I can't remember which ones :-)

**Comment by gashcrumb** [comment]
@sjcox-rh @dongniwang be cool if either of you guys could block out some time to pair up and we can go and fix up some of these buttons in realtime maybe?

**Comment by dongniwang** [comment]
Adding @michael-coker for this exercise!

**Comment by gashcrumb** [comment]
So we're going to defer this one until we get a more detailed page flow diagram for #2870

**Comment by amysueg** [comment]
Created state diagrams to address and correct this, more information #2870 & #3356. Closing this.
