### ISSUE TITLE
Delete confirmation dialog

### ISSUE THREAD

**Issue by michael-coker** [syndesisio/syndesis#2879]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
Per the fuse follow-up doc: 

> Are we using PF standard delete dialog… with PF buttons, red button, and standard wording? See https://github.com/patternfly/patternfly-design/issues/632

## Expected behavior
Delete dialogs should be updated. Sample code here - https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/message-dialogs.html

## Screenshots

Here are the delete dialogs I've found:

### Delete OAuth
![screen shot 2018-06-22 at 2 57 37 pm](https://user-images.githubusercontent.com/35148959/41796553-acfbfc82-762c-11e8-80da-fe5cc0855079.png)

### Delete Extension from details
![screen shot 2018-06-22 at 2 57 28 pm](https://user-images.githubusercontent.com/35148959/41796554-ad0eb19c-762c-11e8-8d29-ef628c5642c0.png)

### Delete extension from list
![screen shot 2018-06-22 at 2 57 23 pm](https://user-images.githubusercontent.com/35148959/41796555-ad2198a2-762c-11e8-801a-969c9fcbed89.png)

### Delete API client connector from list
![screen shot 2018-06-22 at 2 57 12 pm](https://user-images.githubusercontent.com/35148959/41796556-ad3807a4-762c-11e8-9833-e48f88d83a2b.png)

### Delete connection from cards/list
![screen shot 2018-06-22 at 2 55 53 pm](https://user-images.githubusercontent.com/35148959/41796557-ad4b26d6-762c-11e8-8c8d-9b6d54c413c8.png)

### Delete step from integration
![screen shot 2018-06-22 at 2 55 39 pm](https://user-images.githubusercontent.com/35148959/41796558-ad5895e6-762c-11e8-8b44-c0f32b5a1b97.png)

### Delete integration from details
![screen shot 2018-06-22 at 2 54 55 pm](https://user-images.githubusercontent.com/35148959/41796559-ad6c07e8-762c-11e8-904b-adeef435270a.png)

### Delete integration from list
![screen shot 2018-06-22 at 2 54 43 pm](https://user-images.githubusercontent.com/35148959/41796560-ad94282c-762c-11e8-8c22-297f99ccac7b.png)

### Delete integration from dashboard
![screen shot 2018-06-22 at 2 51 48 pm](https://user-images.githubusercontent.com/35148959/41796561-ada7058c-762c-11e8-8b75-9c1a0fb4db4e.png)

-------------

cc @amysueg @sjcox-rh @dongniwang - let me know if there are any I may have missed.

Also seems like we should use consistent titles/wording in the modal. Should I ping Tova about that?

**Comment by amysueg** [comment]
@michael-coker I'm sure Tova would have some good thoughts on improving the Titles and wording of these delete modals. Thanks.

**Comment by michael-coker** [comment]
@TovaCohen, I'm updating the UI of our "delete" confirmation modals to match the [design from patternfly](https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/message-dialogs.html). I'll also update the primary button text to say "Delete" instead of "OK".

Would you like to propose changes to the wording in any of these modals? Seems like the title and modal bodies could be more descriptive and consistent in some cases.
