### ISSUE TITLE
Request new image name for Infrastructure Operator

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#2887]

**Comment by rhuss** [comment]
For the new infrastructure operator we will need a new image for sure. I'd suggest to call it something along the lines of "fuse-online-operator" (and then maybe later on for the integration runtimes "integration-operator" ?)

@kcbabo could you please file an RCM request for those new images ? (sorry, no idea how to do this on my own)

**Comment by kcbabo** [comment]
Is this needed for 7.1?  I want to talk to Gary about the naming strategy.  I don't see a big rush to rename our existing image names from ignite-*.  For new image requests, it probably makes sense to start calling them fuse-online-*, but need to consider that a bit more.

@gaughan : FYI

**Comment by rhuss** [comment]
Yes, when we want to switch to an operator approach for installing fuse-online we need that image as operator.

However we might reconsider the operator story for 7.1 as it not only includes development works but also updates to installation documentation for on premise. 

Still there are some unknowns, e.g. whether a user now would need cluster admin perms for installing the operator (as custom resources needs to be defined). This is currently not required.

Tbh, I think from an on premise user's POV the installation experience might be worse (he needs to do more steps to install the operator than instantiating an template as it is now). I expect that for OCP 3.11 (or 4.0) when there will be intrinsic operator support, that this might become easier.

**Comment by rhuss** [comment]
Request has been summited by @gaughan with the information collected at https://docs.google.com/spreadsheets/d/1yw1xpnGb-4h27QHHz-L1PpOKmqSSyhLrflhj4gW_-44/edit#gid=0 via https://docs.google.com/forms/d/e/1FAIpQLSdtqRDV7qG3oPZSXc_ioDyXXjf6UtUa4bPoUB6JwvW8D9lHbA/viewform?usp=mail_form_link

Waiting to confirmation for the request.

**Comment by rhuss** [comment]
@gaughan @djcoleman are there any news about this request ? Are we able to build and push a fuse-online-operator now (so that this issue can be closed) ?

**Comment by gaughan** [comment]
I didn't receive anything Roland but I'm not sure what the normal process is after a request is submitted.
@djcoleman ?

**Comment by rhuss** [comment]
Actually has we have already this image, I suppose that this the request went through :)

**Comment by gaughan** [comment]
Great! :)
