### ISSUE TITLE
Setup and integrate "fuse-online-operator" into regular build

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#2888]

**Comment by rhuss** [comment]
@nicolaferraro if you have some cycles to spend and since you already played around with the Operator SDK, would it be possible for you to help in adding an "fuse-online-operator" skeleton to our mono-repo ?

I would take over the part to include the build into the "syndesis" script.

**Comment by nicolaferraro** [comment]
I've some work to do on Webhooks, but it's definitely something I can start to do right after (this week).

**Comment by rhuss** [comment]
This integration has not been started but is crucial for a coherent productisation process.
For Sprint 32 this should be one of the highest priority and should be started asap.

The idea is to introduce https://github.com/syndesisio/syndesis-operator into https://github.com/syndesisio/syndesis as a submodule, so that the operator and syndesis can be tagged together so that we also publish a new operator version per release.

This story also requires to update `syndesis` to include the building and releasing the operator.
