### ISSUE TITLE
Introduce Syndesis resources in retrospective for already existing installations

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#2892]

**Comment by rhuss** [comment]
For existing Fuse Online installation which has been created with plain templates for GA, there needs to be a way to create the custom resource based on the parameters stored in the projects.

Luckily we already store all the parameters with which a template is instantiated so we can easily extract that information and create a `Syndesis` resource file which then could apply. We need also away to tell a running operator that no action should be performed.

One way to do this is to have a field `noop: true` in the resource. The operator would check this and in this case would not do anything except removing this attribute from the resource.

**Comment by rhuss** [comment]
Not sure whether this work is required if we already going to introduce that kind of resources for 7.1

@kcbabo @gaughan any idea whether we need a generic update for existing 7.0 installations to introduce the new `Syndesis` resources ? If not we could close this issue and consider a manual, handcrafted update of the affected 7.0 installations.

**Comment by kcbabo** [comment]
We don't need to upgrade existing eval installations running in the Ignite cluster, but how would customers handle their own self-managed installations?

**Comment by kcbabo** [comment]
@rhuss : I suggest we take this discussion to email and then update this issue with a summary of any actions planned.

**Comment by rhuss** [comment]
Fixed and included in the operator
