### ISSUE TITLE
Sync with OpenShift Online team for new installation process

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#2893]

**Comment by rhuss** [comment]
The installation process for Fuse Online via subscription has to be changed. Currently this is a script based approach, but needs to be changed to a resource based approach where the subscription script just applies a custom resource to the users project.

It is important that this change needs to be communicated early to the OpenShift Online team.

**Comment by nicolaferraro** [comment]
@rhuss I did some research and it seems it will not be easy to have a true namespaced CRDs soon in Kubernetes https://github.com/kubernetes/kubernetes/issues/65551.

CRDs are cluster-wide objects.
It may be ok for Syndesis installation, but the CRD needs to be created in advance by a cluster-admin.
Also, authorizations to create instances of a specific custom resource definition (`Syndesis` / `FuseOnline`) should be added cluster-wide to the default user roles when creating the CRD.

This means also that if we want to use schema validation in the CRD, any time we want to do a change in the schema, we should update the definition cluster-wide.

Another issue is that Operator SDK, by contrast, does not support cluster-wide operators, but only namespaced ones (they can watch a single namespace at time).
This means that the end-user installation procedure will consist in:
1) Adding the custom resource in the namespace
2) Adding the operator in the namespace

**Comment by rhuss** [comment]
But maybe the Operator Lifecycle Manager can help ? When the OLM is installed in OpenShift / Kubernetes (at the OLM will be part of the OpenShift 3.11 ansible playbook iiur), then you can submitting a ClusterServiceVersion (CSV) with admin right (a one time action), which contains the metadata about your Operator. After the CSV exists, InstallPlans can be generated to say "this namespace is allowed use this operator" and OLM will make it happen (including to register the CRD if not already present).

Some example if've been pointed to by Rob Szumski (thanks btw ! ;) :

[Simple Example](https://github.com/operator-framework/getting-started/blob/master/memcachedoperator.0.0.1.csv.yaml)
[Real Example from Tectonic](https://gist.github.com/robszumski/1bba99407de22f0f393c772b21447215)
[What is a CSV?](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/Documentation/design/architecture.md#what-is-a-clusterserviceversion)

So while you still have to be cluster-admin for (a) installing the OLM and (b) registering a CSV its a well defined handover point between application-admin and cluster-admin on which they can negotiate.

**Comment by rhuss** [comment]
Started a ticket at https://github.com/openshift/online-registration/issues/1360 however haven't heard any feedback yet. 

Going to reask as soon as we a ready to move to OpenShift Online.

**Comment by chirino** [comment]
Do we know if the OLM will be able to cope with multiple versions of the syndesis operator running at the same time in a single cluster?

**Comment by chirino** [comment]
At some point we will need to integrate with OLM, so I created issue #3326 to track.

**Comment by rhuss** [comment]
> Do we know if the OLM will be able to cope with multiple versions of the syndesis operator running at the same time in a single cluster?

@chirino Yes, he can. 

OLM integration is a p0 feature on which we will work in 7.2. There will be an epic for it as soon as we have finished 7.2 planning.

**Comment by rhuss** [comment]
I'm going to close this for now as we have decided to go with templates into the next round. We should still find a way to optimize the subscription process, but for now I think we are good.
