### ISSUE TITLE
Syndesis Infrastructure Operator

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#2894]
Feature Owner: Roland
Subteam: See assignees

 As evaluated in #2625, there are two kinds of possible operators. In the first step, the template based installation process should be moved to an operator based approach where a custom resource is created which then triggers the installation. The same for the update Syndesis itself.

This new operator should be based on the CoreOS Operator SDK and should introduce a `Syndesis` resource, which describes the installation (i.e. the valus of the former templates parameters).

The scope of this Epic within in the current sprint is only about introducing the operator, reusing all the current mechanism we already have (template based instantiation, update pod with shell scripts)

* For an initial installation the operator should just instantiate the template (in the simplest case) with the given parameters.
* For changes of parameters the operator should perform various actions:
  - If some of the parameters changes they should be replaced inline (if possible)
  - For a change of the version, a full update should be performed. Initially this should be done with the update process as already implemented, but an optimization (e.g. by using APBs) should be evaluated and might be considered for a later sprint.

**Comment by heiko-braun** [comment]
@tplevko I don't know to what degree this might impact QE. Can you work with @rhuss to figure out the impact?

**Comment by tplevko** [comment]
All the bits are now available. @heiko-braun after our discussion yesterday, we agreed that this should not have a huge impact on QE. In worst case, the new installation/upgrade procedure using operators would be test manually, as it doesn't require much effort and the automated tests could be delivered after GA. We also await further updates from @rhuss regarding OSO and syndesis install script updates.
