### ISSUE TITLE
Display dynamic form fields in readonly vs normal/editable states

### ISSUE THREAD

**Issue by michael-coker** [syndesisio/syndesis#2895]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

This is just a placeholder so @seanforyou23 and I can discuss how to show "readonly" fields from dynamic forms in a way that works with non-dynamic (static) forms, so that we can toggle between "readonly" and normal/"edit" states consistently.

## Screenshot

For example, showing the connection details (dynamic form) and the API connector details (static form) the same when in "readonly" mode, then showing that same text in a normal/editable form field when in "edit" mode.

![screen shot 2018-06-25 at 4 01 48 pm](https://user-images.githubusercontent.com/35148959/41876611-ff189b7e-7893-11e8-8090-a48e2b8b8b25.png)

![screen shot 2018-06-13 at 3 04 54 pm](https://user-images.githubusercontent.com/35148959/41377142-cb7c0ffc-6f20-11e8-9719-703e8f86b1c2.png)

There is currently a `:read-only` selector in the syndesis form control component's SCSS that displays read only text well, but that doesn't currently work on static forms.

Patternfly has a [static control](https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/forms.html#controls_static-controls) for forms that might work better, but doesn't look like it's designed to be applied to form elements, so using it here would require an additional element to show the value when in "readonly" mode, then hiding it and showing a form element when in "edit" mode.

**Comment by gashcrumb** [comment]
I actually updated the forms not too long ago in #2722 to make the entire form read-only vs individual controls, the latter was a bit broken.  So the connection detail page for example should look more like:

![capture](https://user-images.githubusercontent.com/351660/41896882-cf59ffbc-78f3-11e8-8529-6df9e5e9b737.PNG)

**Comment by michael-coker** [comment]
@gashcrumb thanks! the goal is just to display the read only values as normal text when in a view/details page (not as a disabled input/form element). So in this case (dynamic form), and on the API connector details page (static form), the read only values would look like normal text. Then when the form is in "edit" mode, the values appear in normal form elements so you can edit them.

Do you think it's better to 1) introduce a global CSS class in the app to display inputs that are `readonly/disabled` in an editable form as normal text, then just toggle the `readonly/disabled` state to go between readonly and edit mode. Or 2) update the syndesis-form-control component to display the read only text in a non-form element, utilizing the [static control](https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/forms.html#controls_static-controls) class from patternfly, then toggle between showing the static control element and the form element depending on whether you're in readonly or edit mode? Or something else?

**Comment by gashcrumb** [comment]
I think being able to set the whole form to read-only and have it behave accordingly is a bit nicer vs. doing it on a control by control basis, so I think I like option 1 better :-)

**Comment by michael-coker** [comment]
Cool, I like that option, too, and it won't involve adding a bunch of elements to the page. However, a couple of issues I see with that are:

1. Changing the display of some form elements to look like normal text can be tricky. Textareas, text inputs, and selects are all pretty easy, but I wonder if we will run into issues down the road as a form element that isn't as easy to style is introduced into an editable form.
1. Looking at a `textarea`, as far as I'm aware, getting it to match the height of the content inside requires javascript. By default, it has a min/max height, and the overflow scrolls, which wouldn't really work if we try to style it so that it's contents to look like normal text.

These issues would be easily avoidable if we just display the `value` of the form element in a regular, non-form element when the form isn't in editable mode. What do you think?

**Comment by gashcrumb** [comment]
I think though as a short-term solution it'd be a win, if we decide to eventually pull out ng-dynamic-forms and create our own library of form controls using the native angular APIs then we could also ensure that each type of form element has a readonly variant that fits the patternfly standard.  @seanforyou23 thoughts?

**Comment by michael-coker** [comment]
Here's an example of the `textarea` problem on the API connector details view. 

![screen shot 2018-06-26 at 2 06 26 pm](https://user-images.githubusercontent.com/35148959/41934150-91bf6d56-794b-11e8-8a40-a596c0c8bd89.png)
![screen shot 2018-06-26 at 2 06 28 pm](https://user-images.githubusercontent.com/35148959/41934154-94253e4a-794b-11e8-9115-7de165e288bf.png)
