### ISSUE TITLE
AWS S3 connection configuration not editable

### ISSUE THREAD

**Issue by weimeilin79** [syndesisio/syndesis#2898]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[V ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

After creating a AWS S3 connection,  I wanted to change the regions, but was not able to do it. 
Unable to edit configurations (Region) with AWS S3 connections. 

## Expected behavior
The region should be updated after saving the configuration.

## Screenshot
![screen shot 2018-06-26 at 1 49 36 pm](https://user-images.githubusercontent.com/2534483/41891693-113b9d1a-7948-11e8-9795-2b506142c0d4.png)

**Comment by oscerd** [comment]
What version are you using? This should be fixed in version 1.4 by updating the way default values are managed.

The related issue is: https://github.com/syndesisio/syndesis/issues/2749

**Comment by gashcrumb** [comment]
Wonder if that fix didn't make it into the release, that'd be unfortunate.  The page itself doesn't look right though, on master it's like:

![capture](https://user-images.githubusercontent.com/351660/41896595-ffbc4e68-78f2-11e8-8859-b8f243d9a77c.PNG)

where the select control is also properly set to read-only.

**Comment by weimeilin79** [comment]
Installed it two days ago. Not sure what version it is on. How do I check the version it is running, so I can add it to the issue next time?

**Comment by oscerd** [comment]
I don't know if it may be the problem, but maybe the page is cached.

**Comment by gashcrumb** [comment]
> Installed  it two days ago. Not sure what version it is on. How do I check the  version it is running, so I can add it to the issue next time?

Currently the support page has version information.  Also yeah, it's worth trying to clear your browser's cache (or try in incognito tab) to see if that gets you the updated page.
