### ISSUE TITLE
Allow to specify http headers for datamapper step in Webhooks

### ISSUE THREAD

**Issue by nicolaferraro** [syndesisio/syndesis#2902]
From the user story, when starting a integration from a Webhook, HTTP headers should be available in a datamapper step.

The user may choose which HTTP headers should be available for mapping.

**Comment by nicolaferraro** [comment]
A possible way to add HTTP headers to a datamapper step, when starting from a Webhook connector, is the following:
- The user specifies which HTTP headers he wants to use at the time of defining the Webhook start action (a list of strings)
- The user is then requested to choose a datashape for the body (Webhook is shapeless, so the shapeless connector screen will be shown)
- The Syndesis runtime can then merge the body shape selected by the user with the list of headers

Syndesis can create a single document for the datamapper, with a structure like this:

* document
  * parameters
    * Header1
    * Header2
  * body
    * bodyField1
    * bodyField2

This is the same structure used by the API Connector for outgoing HTTP requests (cc: @zregvart).

A problem is... the Syndesis runtime should enhance the shape chosen by the user for the body (in the screen for shapeless connectors) with parameters selected in the action definition, but the user can choose different formats for the datashape:
- JSON Instance
- JSON Schema
- XML Instance
- XML Schema
- Others in the future

From what I see, they are passed directly to Atlasmap without change. In order for the enhancement mechanism to work, I should write code to wrap all 4 different formats in a body/parameter structure (and more in the future).

To avoid this, is it possible to convert all 4 formats (JSON Instance, JSON Schema, ...) into a single generic format that is known to Atlasmap, so that I do the enhancement once, no matter what is the format selected by the user? @dhirajsb, @igarashitm

**Comment by igarashitm** [comment]
It sounds like an another usecase of #798, so you want to have multiple output datashapes on single action, isn't it?

**Comment by nicolaferraro** [comment]
Yes, there are actually 2 datashapes that I'm trying to merge to be able to map them in a data mapper step.

**Comment by zregvart** [comment]
I'm was thinking about this and perhaps we could make it super simple in the first iteration.
Say we don't define the shape of the Webhook connector's action, but let the user define the shape using the existing screen.
In the post consumer processor we take data we find in the body and headers and combine it in the structure like the one https://github.com/syndesisio/syndesis/issues/2902#issuecomment-401091780.
The trick here would be to document what kind of shape the user needs to specify. And it can be as simple as:

```json
{
  "parameters": {
    "Header1": "",
    "Header2": ""
  },
  "body": {
    "bodyField1": "",
    "bodyField2": "",
  }
```

In the describe data shape screen. Not super user friendly but I think it would be good enough for first iteration.

**Comment by igarashitm** [comment]
For XML/JSON schema, if we document well and also provide a template for both of XML and JSON that would work. Template should pre-define the exchange/(message,property}/{header,body} schema and user would modify body part. But then it requires user to understand how to write XML/JSON schema.

For XML/JSON instance, it's more tricky. Only document would help a bit, but it's going to be user's responsibility to conform to implicit Exchange schema. Then we might want to retire instance support as it's too confusing and ambiguous.

I'm not sure if we can assume `Citizen Integrator` understand how to write XML/JSON schema. @kcbabo WDYT?

**Comment by lburgazzoli** [comment]
I was thinking about a data shape defined like:

```json
"outputDataShape": {
    "schem": "v2",
    "name": "Twitter Mention",
    "description": "Search result for tweets that mention you. The object represents one single status of a user",
    "headers": [
        "CamelTwitterAbc",
        "CamelTwitterXyz"
    ],
    "payload": {
        "kind": "java",
        "type": "twitter4j.Status"
    }
},
```

So for the payload nothing changes but of course it impacts data mapper UI and runtime

**Comment by igarashitm** [comment]
Then it's same as having multiple data shapes. AtlasMap won't distinguish `headers` from `payload`, but they are just a kind of `Document`. So in Syndesis UI we'll need to transform them into some kind of `Document`, one of Java, JSON(schema/instance) and XML(schema/instance).

**Comment by lburgazzoli** [comment]
So because of the following unresolved issues:

- https://github.com/atlasmap/atlasmap/issues/67
- https://github.com/atlasmap/atlasmap/issues/142

using the whole exchange/message as "document" is not possible so we have two options:

1. for this first iteration we'd go for a solution similar that what @zregvart suggested so if the data shape is of type "json-schema" and contains the headers and payload definition, we add a custom processor that wraps  the body and headers in a single message
2. wait for https://github.com/atlasmap/atlasmap/issues/67 :)

@nicolaferraro is that ok ?

**Comment by nicolaferraro** [comment]
Yes, implementing this feature seems not easy without proper support for composite data shapes (or header/payload datashapes) in Atlasmap. In addition, I think we also miss a open multiselect component in the UI/Patternfly in order to comply with the user story (a comma separated text field would have been the alternative option).

So, I think that for this iteration we can add a temporary solution and priorizite work on Atlasmap for next iteration.

The solution outlined by @zregvart and @lburgazzoli has the advantage of being triggered when the user sets a specific datashape, and it should be done on purpose by the user, following our documentation.
This way, the temporary solution can be kept also in next version and deprecated, while users switch to the final solution.

So, for me it's ok. I hope it's ok also for @kcbabo, @gaughan.
