### ISSUE TITLE
As a citizen integrator, I want to be able to manually load a file data source (local file systems or url) in atlas map in order to visualize how the sample data is mapped.

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#2907]
See also **https://issues.jboss.org/browse/ENTESB-11549**

DoD:

- As a citizen integrator, I can manually load a file data source (local file systems or url) in atlas map in order to visualize how the sample data is mapped. An example is when a sample json data file is loaded the sample data that is mapped is correspondingly displayed in the destination output.

- As a field is mapped the data is updated in the target.

- The data file/url is available for ingest as soon as possible (creation of a connector)

- The feature owner has confirmed one of the following:
-- There is an initial draft of the user doc for this feature. 
-- The writer acknowledges receiving enough information from engineering to write the initial draft of the user doc for this feature. 

Epic: atlasmap/atlasmap#451
UX issue: atlasmap/atlasmap#455

**Comment by rhuss** [comment]
@igarashitm @gaughan I guess this story is connected to the atlasmap preview feature we have seen in the last sprint demo ?

**Comment by gaughan** [comment]
@rhuss Yes, we can track in atlas map and close this if you like?

**Comment by gaughan** [comment]
Ah ok, good call!

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11549**
