### ISSUE TITLE
As a citizen integrator, I want to be able to switch views in atlas map to display only the fields that have mappings.

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#2908]
As a citizen integrator, I want to be able to switch views in atlas map to display only the fields that have mappings. 

DoD:

- In this view, unmapped fields do not display. 
- The parent nodes of the field should be visible in order to distinguish the same  “address” field with different parents “billing vs delivery”

- The feature owner has confirmed one of the following:
-- There is an initial draft of the user doc for this feature. 
-- The writer acknowledges receiving enough information from engineering to write the initial draft of the user doc for this feature.

**Comment by igarashitm** [comment]
We already have this option

![screenshot from 2018-06-27 18-08-00](https://user-images.githubusercontent.com/265462/42002403-37ee3cfe-7a35-11e8-85cf-9d2c36e339d4.png)
![screenshot from 2018-06-27 18-08-11](https://user-images.githubusercontent.com/265462/42002404-38073c9a-7a35-11e8-901a-8c9869c82477.png)
![screenshot from 2018-06-27 18-08-17](https://user-images.githubusercontent.com/265462/42002405-38172f1a-7a35-11e8-9f8f-7ba627e26a29.png)

**Comment by gaughan** [comment]
I think the intent is to go further, in this example, not displaying: Properties, Constants, Status...etc
Only mappings should be visible.
