### ISSUE TITLE
Optimize metrics retrieval

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#2912]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

When we present the dashboard (first screen), we have a number of request for `/api/v1/metrics/integrations`. I counted 6 on our staging environment, this uses connections to the database and prevents requests to `/api/v1/integrations` from completing: we get a 504.

This is then perceived as slowness of the UI.

I think we either need to reduce the rate of fetching metrics, prioritize fetching other data or push metrics from the server to the UI.

## Expected behavior

We need to serve the data for the most compelling parts of the UI first and reduce the load on the database.

## Screenshot

![screenshot from 2018-06-27 15-14-31](https://user-images.githubusercontent.com/1306050/41976583-c8ad65e8-7a1d-11e8-80e2-8a091ea69cce.png)
![screenshot from 2018-06-27 15-17-56](https://user-images.githubusercontent.com/1306050/41976595-cf242b1e-7a1d-11e8-8c74-1acb941fa9d1.png)

## API Endpoints and Schemas

`/api/v1/metrics/integrations`
`/api/v1/integrations`

## Tasks involved / Steps to Reproduce

1. Reload the dashboard on staging site
2. Observe the numerous requests to metrics and errors while fetching integrations in the UI and in the network inspector
3.
4.

**Comment by gashcrumb** [comment]
Yeah, maybe first pass we should just scale back the frequency of metrics requests and observe the impact.  I think honestly if there's a bit of a lag between values displayed in the UI and reality it's not the end of the world, except perhaps for demos.  Looks like right now the polling interval is 5 seconds, maybe we should start with 30 seconds and see how that looks.

**Comment by zregvart** [comment]
Oh I don't think I've been that clear, I think that requesting metrics frequently interferes with fetching integrations. My theory is that the each call to metrics is using up a connection to the database and the call to list integration then times out.
Whereas if we were to push the metrics to the client we could always use only one database connection for that.
We could also cache metrics more aggressively on the server so we don't fetch from the database concurrently but from the cache and aggregate the concurrent requests there.

**Comment by zregvart** [comment]
Here are some reports I gathered from staging.

```sh
sh-4.2$ psql -U syndesis
psql (9.5.9)
Type "help" for help.

syndesis=> select count(*) from jsondb;
 count 
-------
 56522
(1 row)
```

I've enabled slow query logging and additional logging. In `/var/lib/pgsql/openshift-custom-postgresql.conf` I've added:
```
log_min_duration_statement = 250
log_line_prefix = '%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h '
log_checkpoints = on
log_connections = on
log_disconnections = on
log_lock_waits = on
log_temp_files = 0
log_autovacuum_min_duration = 0
log_error_verbosity = default
lc_messages='C'
```

And reloaded database via `pg_ctl reload -D /var/lib/pgsql/data/userdata/`.

I've analysed the generated logs in `/var/lib/pgsql/data/userdata/pg_log/` using https://github.com/dalibo/pgbadger.

[pgbadger.zip](https://github.com/syndesisio/syndesis/files/2192350/pgbadger.zip)

**Comment by zregvart** [comment]
After performing `VACUUM FULL jsondb` the staging site is performing much better.
I've lost my measure for before state, now from `syndesis-server` pod:

```
curl -H 'X-Forwarded-User: hello' -H 'X-Forwarded-Access-Token: world' http://localhost:8080/api/v1/integrations

real	0m1.272s
user	0m0.007s
sys	0m0.044s
```

This would suggest that scheduled `VACUUM FULL jsondb` could help the performance.

**Comment by zregvart** [comment]
I think that with regular database maintenance we can remove some of the symptoms we have here. I'll create another issue for the big number of requests I saw.
