### ISSUE TITLE
Update message dialog modals

### ISSUE THREAD

**Issue by michael-coker** [syndesisio/syndesis#2920]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
This is a follow up from [updating the delete modal message dialogs](https://github.com/syndesisio/syndesis/issues/2879) to the new [PatternFly pattern for message dialogs](https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/message-dialogs.html).

It looks like the wording between message dialogs is inconsistent (title, content, button text, etc), and we might be able to take advantage of the new styles for message dialogs for some of our modal actions.

### Delete OAuth
![screen shot 2018-06-27 at 3 49 15 pm](https://user-images.githubusercontent.com/35148959/41998979-bcc73c82-7a21-11e8-980c-1da4af4d7c05.png)

### Delete extension
![screen shot 2018-06-27 at 3 49 08 pm](https://user-images.githubusercontent.com/35148959/41998984-c34978e0-7a21-11e8-87a7-4d6561d6c94b.png)

### Delete extension in use with integration(s)
![screen shot 2018-06-27 at 3 53 16 pm](https://user-images.githubusercontent.com/35148959/41999137-4abdaeea-7a22-11e8-950f-9e5f40340843.png)

### Delete API client connector
![screen shot 2018-06-27 at 3 48 55 pm](https://user-images.githubusercontent.com/35148959/41998999-cc98f1d2-7a21-11e8-81ae-555e5093093c.png)

### Delete connection
![screen shot 2018-06-27 at 3 48 49 pm](https://user-images.githubusercontent.com/35148959/41999006-d3243cb4-7a21-11e8-8c99-69c38653b11b.png)

### Delete step from integration
![screen shot 2018-06-27 at 3 52 05 pm](https://user-images.githubusercontent.com/35148959/41999067-11a13df2-7a22-11e8-85b6-b69e1bf6e6d0.png)

### Delete integration
![screen shot 2018-06-27 at 3 48 42 pm](https://user-images.githubusercontent.com/35148959/41999038-f32b6c1c-7a21-11e8-9ad6-5d56b7ebe622.png)

### Start integration
![screen shot 2018-06-27 at 3 45 22 pm](https://user-images.githubusercontent.com/35148959/41998828-4fa39bfa-7a21-11e8-8abc-515fa51ac33a.png)

### Stop integration
![screen shot 2018-06-27 at 3 45 28 pm](https://user-images.githubusercontent.com/35148959/41998835-5471fa0a-7a21-11e8-911e-ee5df0c3036a.png)

cc @sjcox-rh @dongniwang @amysueg

**Comment by TovaCohen** [comment]
Thanks for the reminder, Michael!  Will you make these changes?
Should I ask anyone else (who?) to review them?

I think that the verb, "Delete" should be used consistently. Don't use "remove" or "clear". 

I think the title for all the delete modals should be 
"Confirm Delete?"

I think the message should consistently be: 
"Are you sure you want to delete ...... "

Here are the specifics:

DELETE OAUTH
----
Confirm Delete?
Are you sure you want to delete the OAuth credentials for "Twitter"?
Cancel  Delete

DELETE EXTENSION
---
Confirm Delete?
Are you sure you want to delete the "Telegram" extension?
Cancel   Delete

DELETE EXTENSION IN USE
---
Confirm Delete?
Each integration that is listed below uses at least one step that is defined in this extension. If you delete this extension, the consequences are unpredictable. 

My Favorite integration

Are you sure you want to delete the "Telegram" extension?
Cancel   Delete

DELETE API CLIENT CONNECTOR
---
Confirm Delete?
Deleting a connector deletes all connections that were created from that connector but does not affect a running integration that uses one of those connections. 

Are you sure you want to delete the "Petstore" connector?
Cancel   Delete

DELETE CONNECTION
---
Confirm Delete?
Are you sure you want to delete the "AMQ 1" connection?
Cancel   Delete

DELETE STEP FROM INTEGRATION
---
Confirm Delete?
Are you sure you want to delete this step from the integration?
Cancel   Delete

DELETE INTEGRATION
---
Confirm Delete?
Are you sure you want to delete the "Twitter to SF" integration?
Cancel   Delete

START INTEGRATION
---
Confirm Start?
Are you sure you want to start the "Twitter to SF" integration?
Cancel   Start (OK is fine too, I don't know the correct convention - when do we use "OK"?)

STOP INTEGRATION
---
Confirm Stop?
Are you sure you want to stop the "Twitter to SF" integration?
Cancel   Stop (or OK)

**Comment by michael-coker** [comment]
Thanks @TovaCohen this looks great to me. Re "start/stop/OK" for the button text, following the non-destructive action dialog pattern (https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/message-dialogs.html), I think the button should be the action, so "start" and "stop" (not "OK").

@amysueg what do you think? Do we need approval from anyone else or can I go ahead and make these updates?

**Comment by amysueg** [comment]
I agree and encourage you to go ahead and make the updates. Thanks so much, @TovaCohen for the terminology.

**Comment by michael-coker** [comment]
@TovaCohen @amysueg do you think any of these modals should utilize the large text as the header of the modal? Or should they all just be normal paragraph sized text? Here I've updated the API Client Connector delete modal with 3 variations.

Per the proposed [design spec](https://docs.google.com/document/d/1mw2zdbkdgIXxpvS2oY5JfsD9j3dLTnmC8769pdKg3e0/edit) from Stacy M, seems like the 2nd variation is what we would use in this instance. But since the "body" is required and the "primary message" (big text) is optional, on a modal like "delete integration/connection" where there is only 1 line of text, those modals would display the modal body in normal sized text.

What do y'all think?

![screen shot 2018-07-03 at 9 54 32 am](https://user-images.githubusercontent.com/35148959/42227498-44a13dd6-7ea7-11e8-8674-1946823d729d.png)
![screen shot 2018-07-03 at 9 54 09 am](https://user-images.githubusercontent.com/35148959/42227499-44b7cc72-7ea7-11e8-8b38-e233a092c72b.png)
![screen shot 2018-07-03 at 9 53 14 am](https://user-images.githubusercontent.com/35148959/42227500-44cf3498-7ea7-11e8-9054-1419d33d113a.png)

**Comment by michael-coker** [comment]
Assuming we go that route, this is how the delete extension modal would look depending on whether you have an integration running that uses the extension or not.

![screen shot 2018-07-03 at 10 13 33 am](https://user-images.githubusercontent.com/35148959/42228569-e704d1ee-7ea9-11e8-930d-4983d491b933.png)
![screen shot 2018-07-03 at 10 13 58 am](https://user-images.githubusercontent.com/35148959/42228575-e8549994-7ea9-11e8-8459-8e7a28c0822a.png)

**Comment by TovaCohen** [comment]
I like option 2. 
My second choice is all normal size text.

**Comment by amysueg** [comment]
I'm with Tova, with a slight preference for using all normal text instead of different sizes.
