### ISSUE TITLE
Add default values for URLs/scopes for oauth apps 

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#2921]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

There's 3 new fields for each oauth app on the Settings page, for authorization and access token URLs but no guidance on what these ought to be or where to get these values.

## Expected behavior

The forms should have default values appropriate to each target app.  We apparently had this hard-coded at one point, ideally the typical user should just need to plug their key and secret into this form.

## Screenshot

![capture](https://user-images.githubusercontent.com/351660/42026105-45af9b08-7a94-11e8-91b0-0e9d573c2ce2.PNG)

**Comment by oscerd** [comment]
For the gmail connector we have them as default properties. What I noticed is that, if you cancel your application after registering it, the fields will be deleted and you won't have them pre-compiled.

**Comment by gashcrumb** [comment]
Ah, I see the values are there from the backend but aren't applied to the form configuration for some reason.  I can look into that.

**Comment by gashcrumb** [comment]
Okay, where they're set in the response, they're set in the form.  I guess though not every oauth app needs all of these settings.  This makes another case for the suggestion in #240 that each of these oauth app entries should have their configuration forms driven by the backend, currently the form is defined client-side where we'd have no idea what settings are relevant for which oauth app.

**Comment by oscerd** [comment]
Talking for the gmail one, it needs all of them

**Comment by gashcrumb** [comment]
I think this can be closed actually, I'll create an issue to consider driving the form configuration from the backend vs the client-side config we're currently using.
