### ISSUE TITLE
URL and scope fields aren't saved when clicking Save

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#2922]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

These three fields were added, however they don't appear to save values properly:

![capture](https://user-images.githubusercontent.com/351660/42026770-080c45ce-7a96-11e8-9111-ef47eaac21c8.PNG)

after a refresh:

![capture](https://user-images.githubusercontent.com/351660/42026853-316a758a-7a96-11e8-9de4-108bd7dd5ad4.PNG)

## Expected behavior

I should be able to populate these fields and save the values.

## Request and Response Data

Data being posted:

```json
{
  "clientId": "",
  "clientSecret": "",
  "icon": "data:image\/svg+xml;base64,PHN2ZyBpZD0iTGF5ZXJfMSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB2aWV3Qm94PSIwIDAgMzAwIDI0My44Ij48c3R5bGU+PC9zdHlsZT48cGF0aCBkPSJNOTQuMyAyNDMuOGMxMTMuMiAwIDE3NS4xLTkzLjggMTc1LjEtMTc1LjEgMC0yLjctLjEtNS4zLS4yLTggMTItOC43IDIyLjUtMTkuNSAzMC43LTMxLjktMTEgNC45LTIyLjkgOC4yLTM1LjMgOS43IDEyLjctNy42IDIyLjUtMTkuNyAyNy4xLTM0LTExLjkgNy4xLTI1LjEgMTIuMi0zOS4xIDE0LjlDMjQxLjQgNy41IDIyNS40IDAgMjA3LjcgMGMtMzQgMC02MS42IDI3LjYtNjEuNiA2MS41IDAgNC44LjUgOS41IDEuNiAxNC01MS4xLTIuNS05Ni41LTI3LTEyNi44LTY0LjItNS4zIDkuMS04LjMgMTkuNy04LjMgMzAuOSAwIDIxLjQgMTAuOSA0MC4yIDI3LjQgNTEuMi0xMC4xLS4zLTE5LjYtMy4xLTI3LjktNy43di44YzAgMjkuOCAyMS4yIDU0LjcgNDkuNCA2MC4zLTUuMiAxLjQtMTAuNiAyLjItMTYuMiAyLjItNCAwLTcuOC0uNC0xMS42LTEuMSA3LjggMjQuNSAzMC42IDQyLjIgNTcuNSA0Mi43QzcwLjEgMjA3LjIgNDMuNSAyMTcgMTQuNyAyMTdjLTUgMC05LjktLjMtMTQuNy0uOSAyNy4yIDE3LjUgNTkuNiAyNy43IDk0LjMgMjcuNyIgZmlsbD0iIzFkYTFmMiIvPjwvc3ZnPg==",
  "id": "twitter",
  "name": "Twitter",
  "authorizationUrl": "asdfasdf",
  "tokenUrl": "asdfasdf"
}

```

**Comment by gashcrumb** [comment]
I should mention it's not being saved at the backend, but this may be more due to the fact that we're using a generic client-side form config for all oauth apps, so not all values would be applicable for all oauth apps.

**Comment by zregvart** [comment]
I think with the rework we did in #2990 this should no longer be an issue.
