### ISSUE TITLE
Can't create a Twitter connection

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#2923]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Nothing happens when clicking the 'Connect Twitter' button.

## Expected behavior

An inline error notification should at least appear when there's a problem initiating an oauth flow.

And also I expect to be able to connect to Twitter if I've put in my credentials into the Settings page.  But maybe because of #2922 I can't properly configure the Twitter connector.

## Request and Response Data

Response back from clicking the button:

```json
{
  "errorCode": 403,
  "userMsg": "403 Forbidden",
  "developerMsg": "403 Forbidden",
  "userMsgDetail": "{\"code\":\"415\",\"\":\"Callback URL not approved for this client application. Approved callback URLs can be adjusted in your application settings\"}"
}
```

apparently the UI isn't expecting this message back for an error response.

**Comment by seanforyou23** [comment]
@gashcrumb  I had a similar issue this morning, and noticed that if the ip address in the twitter callback URL isn't aligned with the minishift ip, it fails, just like with the salesforce connection. I think this didn't used to be required for salesforce connection but maybe now it is? As soon as I updated the callback URL to include the latest ip address is started working for me. I could be off, but maybe that's worth trying on your end?

**Comment by gashcrumb** [comment]
Cool, will check!  Will still leave this open as the error response needs to be reported on the page somehow.
