### ISSUE TITLE
Only 20 connectors are returned at most when creating a connection

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#2925]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

When you install a few extensions that add connectors you'll quickly find that some connectors vanish from the list of available connectors when you go to create a connection.

With a bit of testing by slowly adding connector extensions I found that the API response for /connectors appears to have a maximum limit of 20.

## Expected behavior

All connectors should be returned as the 1st page of the create connection wizard doesn't do pagination.

## Tasks involved / Steps to Reproduce

1. Open up the browser developer console and look at the network tab, check the "Preview" tab for the HTTP request to /connectors
2. Add a connector extension, note how the `totalCount` in the response increases by 1
3. Add more connector extensions so that you have more than 20 connectors
4. Note that `totalCount` stops at 20, and some connectors that were available are now missing.

**Comment by rhuss** [comment]
@zregvart you mentioned that it's not uncommon for connector's meta-data to be >10MB in size when serialized in JSON. Is this a common scenario that will hurt us if we e.g. assemble a list of connectors unbounded in server memory before returning it to the client ?

**Comment by gashcrumb** [comment]
First optimization would be to pull the 'actions' out of the response for fetching connectors, that information isn't needed at all in the create connection flow.  Mainly just the connector properties, name icon and description is all that's needed afaik.

**Comment by gashcrumb** [comment]
I think also this is the only page that fetches connectors, in the editor we need all the connector data but I think that comes back as part of fetching the connection.

**Comment by mcada** [comment]
Adding priority p0 as after moving more extensions into syndesis this is now blocking some of our tests.

**Comment by tplevko** [comment]
This issue quite seriously affects our testing efforts as the "twitter" connector is not displayed in the "create connection" page (it's our one of our favorite connector we use in test scenarios, which means our tests fail quite heavily now that there are more than 20 connectors to choose from).
@gashcrumb could you for the time being please at least increase the limit for displayed connectors, and implement more suitable fix in near future?

**Comment by gashcrumb** [comment]
This needs to be fixed at the backend, the UI currently tries to just fetch everything.

**Comment by gashcrumb** [comment]
I mean if we have to optimize things so that the server returns just id/name/descriptions for the connector request that's fine, I can adapt the 2 other spots where we'd need all the action data.

**Comment by heiko-braun** [comment]
//cc @rhuss Please see @tplevko 's last comment. What can we do to unblock QE?

**Comment by rhuss** [comment]
If I understand the backend code right in https://github.com/syndesisio/syndesis/blob/e4fef26ffc693c3811e5a77804a2a69946d5a6ea/app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/operations/PaginationOptionsFromQueryParams.java#L35-L50
then there is already backend support for paging. Its by far not optimal as the whole list is always build up in the server's memory before its filter out, but at least the UI can influence the page size with the `per_page` query parameter which is set to 20 if not given.

@gashcrumb could you send this parameter for the affected list queries and make it a client side config parameter so we can tune it via the UI configmap ?

**Comment by gashcrumb** [comment]
Yup, can do thanks!

**Comment by gashcrumb** [comment]
Created https://github.com/syndesisio/syndesis/issues/3113 to track improving pagination.
