### ISSUE TITLE
Todo app connection requires empty Base Path but it cannot be set empty

### ISSUE THREAD

**Issue by mastepan** [syndesisio/syndesis#2931]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
If I create custom api connector to TODO app, the app requires BASE PATH attribute to be set empty to work properly.
But this property must be set to be allowed to create a connector (empty value is not accepted when creating the connector).
If I create a connection from this connector then, I can edit BASE PATH property and set it empty.

But an integration using TODO connection doesn't start failing with the following error:

> org.apache.camel.RuntimeCamelException: java.lang.IllegalArgumentException: Could not find a suitable setter for property: basePath as there isn't a setter method with same type: java.lang.String nor type conversion possible: basePath must be specified and not empty

It's blocking some UI tests that use TODO app connection in an integration.

## Expected behavior
TODO app should require non-empty BASE PATH property. There was "/api" required recently and everything worked nicely.

**Comment by zregvart** [comment]
Base path is required and if it's not this could be an issue.

That being said the TODO sample app's basepath is `/api`, and even if it isn't it could be set to `/`, so I don't understand what is the issue here?

**Comment by mastepan** [comment]
The issue is:
If I set **nothing** - extection occurs because the basepath has to be set
If I set **/api** - exception occurs and says that the basepath is http://todo-master.192.168.42.101.nip.io/api/api (/api is there 2 times)

**Comment by zregvart** [comment]
I've created a [custom API connector](https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/customizations/api-connector/i-LNjTyWmEQ-s_ajv4KxJz) for the TODO API OpenAPI [specification](https://todo-syndesis-staging.b6ff.rh-idev.openshiftapps.com/swagger.json) and a [connection](https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/connections/i-LNjU4t9EQ-s_ajv4KxKz). Both have the base path set to `/api` and this seems to be operating correctly in an [integration](https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/integrations/i-LNjUZX9EQ-s_ajv4KxLz?view=activity).

@mastepan can you outline the steps you took to get `/api/api` as the base path?

**Comment by mastepan** [comment]
[screencast.zip](https://github.com/syndesisio/syndesis/files/2437808/screencast.zip)

**Comment by zregvart** [comment]
@mastepan thank you for recoding the screencast, I noticed that you provided a OpenAPI specification served from GitHub (probably [this one](https://github.com/syndesisio/syndesis/blob/master/app/server/api-generator/src/test/resources/swagger/todo.swagger.yaml)), that OpenAPI specification is part of the test suite used to test the Custom API client connectors and was an earlier version of the OpenAPI specification for the TODO app we provide.

The TODO app serves its own OpenAPI specification from /swagger.[json|yaml]. For example [this one](https://todo-syndesis-staging.b6ff.rh-idev.openshiftapps.com/swagger.yaml) on the staging site.

In that specification you can see that the basepath is set to `/api` and the paths start with `/`, whereas in the specification present in the syndesis repository the base path is not specified and the paths start with `/api`, so it is expected that when you prepend the basepath of `/api` you would end up with `/api/api`.

I think we can close this.
