### ISSUE TITLE
Connection creation is broken

### ISSUE THREAD

**Issue by tplevko** [syndesisio/syndesis#2948]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

The fields for filling connection properties are not showing. 

## Screenshot

![out](https://user-images.githubusercontent.com/4180208/42206066-66a34240-7ea6-11e8-9c7b-599c19da2dfe.gif)

## Tasks involved / Steps to Reproduce

1. Start syndesis from master
2. Try to create some of the connections
3. It can't be done

**Comment by gashcrumb** [comment]
Think @seanforyou23 mentioned there might be an issue here, will have a look, thanks!
