### ISSUE TITLE
Empty cancel modal

### ISSUE THREAD

**Issue by tplevko** [syndesisio/syndesis#2949]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

When creating a connection, when I try to switch back to connections overview, empty modal with cancel button appears.

## Screenshot

![out](https://user-images.githubusercontent.com/4180208/42206515-a60f6f66-7ea7-11e8-8c09-a2ce076fc4c6.gif)

## Tasks involved / Steps to Reproduce

1. Syndesis from master running
2. Select some of the connections - start create new connection process
3. Press the Home > Connections option, observe the modal with cancel button

**Comment by gashcrumb** [comment]
The fix for #2948 appears to have sorted this one as well.
