### ISSUE TITLE
Promote some extension to the main repo.

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis#2952]
## This is a...

<pre><code>
[ x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
Syndesis project has delivered some functionality has part of the Extension project: https://github.com/syndesisio/syndesis-extensions

Some of this extension are so commonly used that we should provide them out of the box, without asking our user to install them independently.

## Tasks involved / Steps to Reproduce

1. The activity is mainly a refactoring one: move code from the external repo to the main one, verify that the extension is built and published on the platform
2.
3.
4.

**Comment by paoloantinori** [comment]
This is a continuous activity probably, but to start with something this is the list of extensions that might be the most useful to have:

- `conncector-timer`
- `extension-body`
- `extension-delay`
- `extension-loop`
- `extension-manage-headers`

**Comment by lburgazzoli** [comment]
There's no problem for connectors however for extension there is an issue as they are supposed to  be associate to a jar and so there is a specific work-flow which we need to enhance to support syndesis provided extensions.

**Comment by paoloantinori** [comment]
Critical aspects to keep track of during design and development:

- how multiple imports of the same integration behaves. does this generate any issue?
- how to implement import? over rest? directly invoking business services?
- do we need to mark some extension as "immutable", removing the permission to delete them?
- any work done during this phase should take into account the future possible features of an Online Extension Marketplace

**Comment by oscerd** [comment]
Timer connector imported.

**Comment by oscerd** [comment]
Log connector imported.
Telegram connector imported.
IRC connector imported.
We choose to leave openshift out.

**Comment by oscerd** [comment]
We can close this, there is still work to do on the icons probably.

**Comment by oscerd** [comment]
cc @paolo @heiko-braun
