### ISSUE TITLE
Basic filter step broken

### ISSUE THREAD

**Issue by tplevko** [syndesisio/syndesis#2955]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

The basic filter step can't be used properly. I can't add any rules.

## Screenshot

![out](https://user-images.githubusercontent.com/4180208/42216649-de4fc392-7ec2-11e8-8a8d-eaa94951dea8.gif)

## Tasks involved / Steps to Reproduce

1. Syndesis from master running
2. Add new integration, specify some start/stop end connection
3. Specify the "Basic filter step"
4. Observe, that there is no possibility to specify options for basic filter step

**Comment by gashcrumb** [comment]
Yep, think this was expected with the Angular 6 upgrade, @seanforyou23 I forget, had you raised an issue for this yet?  If not we can use this one :-)
