### ISSUE TITLE
UX Design: Simplify IVP Design

### ISSUE THREAD

**Issue by sjcox-rh** [syndesisio/syndesis#2962]
## This is a...

<pre><code>
[ X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

This is Phase 1 of the revamp of the Integration Visualization Panel.  Goal for this phase is to simplify the design by removing the labels. This is redundant information for the user as the same info is shown within the configuration section.

## Expected behavior

- Removal of labels from IVP
- Way to expand panel to see details
- Way to delete steps

## Tasks involved / Steps to Reproduce

1. Design options reviewed with steakholders
2. Reiterations
3. Final Review and Sign off

**Comment by sjcox-rh** [comment]
Please review the design updates for a simplified Integration Visualization Panel!

https://redhat.invisionapp.com/share/Z7MM774PR8D

Thank you!

@amysueg @dongniwang @michael-coker @seanforyou23 @TovaCohen @paoloantinori @heiko-braun @kcbabo @gaughan @gashcrumb @kahboom

**Comment by gaughan** [comment]
This looks great SJ, thanks!

**Comment by kcbabo** [comment]
+1 LGTM!

**Comment by amysueg** [comment]
Looks great @sjcox-rh, thanks.

@paoloantinori @heiko-braun We need Engineering to sign off and then we will update the tracker to add this item as "Ready for Dev."

Once we have engineering sign off, I would propose that we mark this issue "complete" - as in the UX design is completed.

I will open a separate Github issue to implement these design changes, and assign it to @michael-coker  - Michael will reach out if he needs anything.

Make sense?

**Comment by gashcrumb** [comment]
+1 from me!

**Comment by gashcrumb** [comment]
This is all set...
