### ISSUE TITLE
Bad Integration Summary UI  on firefox after refresh

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#2973]
## This is a...

<pre><code>
[ ] Feature request
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

If I refresh the integration summary page on firefox (linux), the page losts icons, text and so on as per screenshot below. It does not appear to happen with chromium.

## Screenshot

![image](https://user-images.githubusercontent.com/1868933/42280996-968c3050-7fa2-11e8-8827-6a495b7a3d0c.png)

## Tasks involved / Steps to Reproduce

1. Publish n integration
2. Go to the integration's summary page
3. Refresh the page
4.

**Comment by gashcrumb** [comment]
Hmm, I can't seem to reproduce this here.  Wonder is there any big javascript error hitting the browser console perhaps?  Also did you try an incognito window or try clearing your cache maybe?

**Comment by gashcrumb** [comment]
Cool, I think also I probably need to test against the built version vs. a dev instance, that might show the problem here too.

**Comment by lburgazzoli** [comment]
unable to reproduce
