### ISSUE TITLE
step properties not persisted

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#2974]
## This is a...

<pre><code>
[ ] Feature request
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

When switching back and fort between steps, some configuration are lost

## Expected behavior

Configurations should be kept

## Screenshot

![jdbc-issue](https://user-images.githubusercontent.com/1868933/42282440-cd2a183a-7fa6-11e8-95ac-343e29b7f6df.gif)

**Comment by gashcrumb** [comment]
This is actually specific to just the duration control.
