### ISSUE TITLE
Polyfills and shims needed for Angular 6 upgrade

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis#2978]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
After rebasing and using the latest changes with Angular 6.0.4 I started to get the following error coming from the yamljs package when I'd try to rebuild with `yarn ng build --aot=false --vendor-chunk=true --source-map=true` or even just `syndesis build --clean`, which uses the same command.

## Screenshot

```
ERROR in ./node_modules/yamljs/lib/Utils.js
Module not found: Error: Can't resolve 'fs' in '/Users/kahboom/Projects/syndesis/app/ui/node_modules/yamljs/lib'
```

<img width="835" alt="screenshot 2018-07-04 23 19 44" src="https://user-images.githubusercontent.com/3844502/42300994-19fb0568-7fe1-11e8-9460-acb753462dca.png">

 See my comment [here](https://github.com/angular/angular-cli/issues/10681#issuecomment-402594619) for more details.

I also got a few other weird things related to SASS:

```
Module build failed: Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (64)
```

<img width="1673" alt="screenshot 2018-07-04 22 02 51" src="https://user-images.githubusercontent.com/3844502/42300965-ea7fe75e-7fe0-11e8-8685-ef5659c2d859.png">

EDIT: This should be resolved with this PR #2886 .

**Comment by gashcrumb** [comment]
@kahboom run `yarn install --force` before running `yarn start:minishift` to sort the node-saas issue.

**Comment by paoloantinori** [comment]
@kahboom is this still a bug or do @gashcrumb suggestion fixes it?

**Comment by kahboom** [comment]
Well, if this is the same issue I'm thinking of, I was trying to come up with a fix that would work for everyone without having to use the `--force` flag. I think this is related to the version of Node and npm each person uses and dependencies that try to force certain engine versions. Either way, this commit would have sorted out for local env, but not for CD/CI: https://github.com/syndesisio/syndesis/pull/2886/files#diff-4c51b5da64219cce10752e61a6393f5c

I guess either way we can consider this closed and just have people run those commands manually, or that fix above should sort it out.
