### ISSUE TITLE
DataShape extension

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#2980]
See also **https://issues.jboss.org/browse/ENTESB-11548**

## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

For shapeless connectors a citizen developer needs to define the shape of the data the connector produces/consume and it may not be so easy as the citizen developer need to know how to write json schema or other formats. It is also error prone and inside an organization multiple developer may need to define the same data shape i.e. for integration with the company messaging systems.

## Expected behavior

An experienced developer can code an extension that contains one or more data shape definitions an related code that a citizen developer can pick up in data shape selection drop down.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11548**
