### ISSUE TITLE
Update Webhooks UI according to UX design

### ISSUE THREAD

**Issue by nicolaferraro** [syndesisio/syndesis#2981]
For now we just need to replace the current URL string visualization with a "copy button", as explained in: https://github.com/syndesisio/syndesis/issues/2740

**Comment by gashcrumb** [comment]
Is the URL an attribute on the integration then?  Just wondering how we'd know whether or not to show that.

**Comment by nicolaferraro** [comment]
Yes, I've added it as attribute of the integration. There's also a placeholder here: https://github.com/syndesisio/syndesis/blob/d2b9af4759ade65730d29c8bd772a42cf4f7f40e/app/ui/src/app/integration/integration_detail/integration-description.component.html#L28

**Comment by nicolaferraro** [comment]
It appears when creating a integration that starts from a Webhook. Note that in the current implementation the `url` property is not populated immediately but it takes some time for it to be filled in by the backend (less than the time to deploy the integration usually).

**Comment by gashcrumb** [comment]
@nicolaferraro ah perfect, thanks!

**Comment by seanforyou23** [comment]
I have an integration that starts from a webhook, but the url property was never populated for me. Is there anything required beyond starting with a webhook connection for this property to be populated? I will try rebuilding my environment again in case that's to blame.

**Comment by nicolaferraro** [comment]
@seanforyou23, that is strange. Are you using the webhook default connection that is created with syndesis, not the connector in the extensions repo, right?

The route currently is created after the integration is built, so you need to complete s2i Openshift build before the Openshift route is created and the `url` added to the integration.

**Comment by seanforyou23** [comment]
Yes correct, the one that ships with syndesis. I think I just need to rebuild, @michael-coker had some success seeing this work just minutes ago so probably just an issue with my environment on my end. Keep you posted!

**Comment by seanforyou23** [comment]
Closing, feel free to reopen if I've missed anything.
