### ISSUE TITLE
Integration Validation

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#2986]
See also **https://issues.jboss.org/browse/ENTESB-11547**

## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

We do no yet have an integration validation so if for any reason the integration is invalid or one of the step is not properly configured i.e. because of a bug, the integration is be deployed and the runtime may fail or have unpredictable behavior.

## Expected behavior

Integration should be validated and errors have to be reported.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11547**
