### ISSUE TITLE
Validate integration steps

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#2987]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

We should validate steps, i.e. the log step should produce a message or the camel runtime would fail.

**Comment by paoloantinori** [comment]
Can you provide other examples of validation?
Because I'm tempted to say that an empty log entry isn't anything bad.

**Comment by lburgazzoli** [comment]
keep it open

**Comment by lburgazzoli** [comment]
keep it open
