### ISSUE TITLE
Move message dialog text into dictionary file

### ISSUE THREAD

**Issue by michael-coker** [syndesisio/syndesis#2988]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
From PR https://github.com/syndesisio/syndesis/pull/2964. The PR was merged before I finished.

Still need to dialog text from these modals to dictionary file
* delete api connector
* delete extension
* delete step (integration editor)
* delete/stop/start integration (add titles and button text)
* delete OAuth credentials (add title and button text)

**Comment by gashcrumb** [comment]
oh sorry!  I didn't catch that...

**Comment by michael-coker** [comment]
@gashcrumb no worries!
