### ISSUE TITLE
Fetch oauth app form configurations from the backend

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#2990]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Currently all the apps in the oauth settings page use the same form field configuration as it's defined client side, and the UI only fetches values from the backend and then populates those values in the form.  This leads to issues like #2921 and #2922 as not every setting in the generic form config would be relevant to a given oauth client, and also doesn't allow us to provide as nice of a UX, as we can't customize the oauth settings to match the target system's terminology as mentioned in https://github.com/syndesisio/syndesis/issues/240

## Expected behavior

The oauth settings form should really be defined by the connector rather than be hard-coded in the UI.

**Comment by zregvart** [comment]
Also worth noting some tidying up for #2997.
