### ISSUE TITLE
Coding updates for simplified IVP design

### ISSUE THREAD

**Issue by amysueg** [syndesisio/syndesis#2993]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
Implement the code to make the changes outlined in this UX Design: #2962.

## Expected behavior
Simplified, cleaner UI for the Integration Visualization Panel

## Screenshot
![screen shot 2018-07-05 at 4 14 03 pm](https://user-images.githubusercontent.com/31700119/42345780-79ee4ce0-806e-11e8-8940-1fddb1f8aa0b.png)

**Comment by michael-coker** [comment]
@gashcrumb I think I can take care of all of this except for the connection & step details here: 

![screen shot 2018-07-05 at 3 17 45 pm](https://user-images.githubusercontent.com/35148959/42345958-a19f91ca-8066-11e8-8aa4-331e19b2368c.png)

Is that information currently available in the editor pages?

**Comment by michael-coker** [comment]
@gashcrumb ah yes! Perfect, thanks. Though there is no info popup for the non-connection steps (filters, data mapper, log) - do those need any info below them?

**Comment by gashcrumb** [comment]
We'll probably want this for steps too.  Steps don't have an 'action' like connections do, but there's config that we could figure out a way to show.

**Comment by michael-coker** [comment]
@sjcox-rh what do you think about these states in the expanded version of the IVP?

![screen shot 2018-07-09 at 3 14 08 pm](https://user-images.githubusercontent.com/35148959/42473755-176fa008-838b-11e8-8dca-81d5146e06ba.png)
![screen shot 2018-07-09 at 3 14 11 pm](https://user-images.githubusercontent.com/35148959/42473757-18e2f1ec-838b-11e8-894b-46a301235b43.png)
![screen shot 2018-07-09 at 3 14 57 pm](https://user-images.githubusercontent.com/35148959/42473759-1a42290e-838b-11e8-9841-defa6d1270a6.png)

**Comment by amysueg** [comment]
@michael-coker looking good.
I wonder why there is so much horizontal distance between the labels under each expanded section and the values. In other words, why so much white space between the ":" after "Name" for example, and the names? Seems like if that could be made tighter, then the expanded view would not need to take up quite as much horz space. @sjcox-rh WDYT?

**Comment by michael-coker** [comment]
@amysueg ah, that's because I used to have longer labels for the values and didn't change the spacing. The labels in the design are "connection name, connection action, connection action config" and "step name, step action, step action config" - I just made them shorter and put something in there because at some point I'll need to pass off to @gashcrumb to populate the proper data there. I'll update that so it's tighter. That and the overall width of the IVP are easy adjustments, so we can quickly adjust them as needed.

**Comment by gashcrumb** [comment]
Wonder for the 'config' area, we can show the form config values, but I worry that the data in this case is too open-ended, i.e. for some actions there's no config, but then for other actions like the AMQ-based connections there's like 4 or 5 parameters.

Also in the old tooltips we were showing input and output data types, wonder if these would fit in this panel too, here's a quick example:

![capture](https://user-images.githubusercontent.com/351660/42480194-3665e142-83aa-11e8-8f75-01dc97ef3033.PNG)

**Comment by michael-coker** [comment]
@gashcrumb that sounds good to me, whatever info is most meaningful there. Just minor CSS adjustments are needed if we add/remove rows under the connections/steps. I'll update it to show input/output data types.

@sjcox-rh @amysueg I also changed the IVP scrollbar (when the height exceeds the height of the browser) from scrolling the entire IVP (including the integration name) just to scroll the connection/step area. Let me know if you'd like me to handle that differently.

![screen shot 2018-07-10 at 9 20 15 am](https://user-images.githubusercontent.com/35148959/42516133-01bdfadc-8423-11e8-9b39-b59315f6c600.png)
![screen shot 2018-07-10 at 9 20 27 am](https://user-images.githubusercontent.com/35148959/42516140-038b2498-8423-11e8-9494-fb31821e6d38.png)

**Comment by gashcrumb** [comment]
@michael-coker yeah, I think the data type information is the best bit to show in this side panel.

The user can look at the specific step to see/edit the config from that point, so I don't think we should try and squeeze all that information into this panel too.

**Comment by sjcox-rh** [comment]
@michael-coker Sorry late to the party, been heads down in the patternfly world. Thanks for working on this, it all looks great! Also, +1 for the scroll bar you defined.

**Comment by michael-coker** [comment]
@sjcox-rh cool thanks! it's up on staging now, too, if you want to interact with it and let me know if there are any changes you'd like to see.
