### ISSUE TITLE
Remove authorization, token URL and scope OAuth settings for Salesforce, Twitter and GMail connectors

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#2996]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

In #2718 we added three new fields to the OAuth settings:
 - authorization URL
 - token URL
 - scope

It doesn't make sense to change those for Twitter and Salesforce builtin connectors. Only for Concur and custom API connectors.

## Expected behavior

Don't show authorization and token URLs and scope settings for Salesforce and Twitter.

## Screenshot

![screenshot_2018-07-06 syndesis](https://user-images.githubusercontent.com/1306050/42368245-d2750cb2-8106-11e8-8367-5e4acd1005e6.png)

## API Endpoints and Schemas

`/api/v1/setup/oauth-apps`

**Comment by gashcrumb** [comment]
I raised https://github.com/syndesisio/syndesis/issues/2990 yesterday which I think is kinda the same idea.

**Comment by zregvart** [comment]
I think we can work on this in #2990.
