### ISSUE TITLE
As an expert integrator, I need to connect to Concur to create and retrieve.

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#3002]
As an expert integrator, I need to connect to Concur to create and retrieve.
The connector should support the configuration settings for Oauth2. 
Input is required for accessToken, clientId (UUID4 identifier), clientSecret (application’s password) and geolocation (base URI). 
I expect OAuth/Token refresh to work so I don't continually have to login
I should have the option to validate the connector against the instance. Our target implementation is version 3.0 (Concur version doc below)

EPIC:
https://github.com/syndesisio/syndesis/issues/2632
Issues:
https://github.com/syndesisio/syndesis/issues?utf8=%E2%9C%93&q=%3Dconcur+
Concur docs:
https://developer.concur.com/api-reference/
Concur API versions
https://docs.google.com/document/d/10fLUtRld49XXxG6Ya-sRcBGDh9dW91bmBmGcDhmxw78/

**Comment by zregvart** [comment]
This was implemented
