### ISSUE TITLE
Error when downloading specific diagnostics from support page

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#3006]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

Downloading specific integration diagnostics from support page does not work:

![diagnostics_fail](https://user-images.githubusercontent.com/14313995/42443100-d908f116-836c-11e8-9cc8-c0d18b71d0fe.png)

**Comment by paoloantinori** [comment]
Hi, can you add the logs you find on the server pod?

**Comment by heiko-braun** [comment]
Can we retest this with the latest master?

**Comment by mcada** [comment]
It does not fail anymore in our tests :/

**Comment by mcada** [comment]
I mean it is a good thing, it works both manually and in our automation. Good fix :+1: we can probably close the issue.

**Comment by heiko-braun** [comment]
thanks @mcada . I am closing this.
