### ISSUE TITLE
Logout on firefox does not work correctly

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#3016]
I tried new logout endpoint on firefox from anonymous window and it does not work.

After I log out, I am on logout page. Then when I click on Login button, this happens:
![logout_error_firefox](https://user-images.githubusercontent.com/14313995/42498786-6bf51318-842d-11e8-950a-62c475d3d856.png)

Console looked like this:
![logout_error_console](https://user-images.githubusercontent.com/14313995/42498806-76af477e-842d-11e8-80fe-1b8a28213d8e.png)

@zregvart

**Comment by zregvart** [comment]
Weird, I develop on Firefox so I'm pretty sure that it's working (on my machine :)).

Any chance you could try other browsers and see if we can learn something from that?

The error is about establishing WebSocket connection that we use to push updates to the UI from the server. I wonder if the reason behind this could be some race condition. Perhaps we should shutdown that WebSocket before logging out.

**Comment by mcada** [comment]
I tried it with chromium and chrome and it works well. Only with Firefox it does not work on my machine. I tried it on another PC and it worked there.

**Comment by mcada** [comment]
There is another issue but I think it is connected with this one as I can only reproduce it with this one issue:

When I log out on firefox, click login --> receive the error, refresh the page I land on openshift login page. This is ok I guess. But then I login and logout again and then click on login button, I am redirected into syndesis, without error from screenshot above and I am still logged in with access to everything :/ This should not work... Our automated test does more logouts in a row and this is always the case on firefox - first one is with error and second one is redirected into syndesis like no logout ever happened.

**Comment by gashcrumb** [comment]
Just to be on the safe side have you tested this after clearing your history and cache?

**Comment by mcada** [comment]
I am using anonymous window and tests work with firefox webdriver, it should be fresh.

**Comment by gashcrumb** [comment]
Cool, probably a good question for @zregvart as well :-)

**Comment by mcada** [comment]
Issue is present on syndesis version: 1.4.7.fuse-710001-redhat-00001

**Comment by heiko-braun** [comment]
ok, let's move this to next release

**Comment by zregvart** [comment]
@mcada I've created a PR #3624 for this, hopefully this should be fixed. I don't know if it's easy for you to test the PR and see if it works as expected on your side.

**Comment by zregvart** [comment]
@tplevko awesome, thank you for the update!

**Comment by zregvart** [comment]
[gifbot:nuke]

**Comment by tplevko** [comment]
@mcada please verify this fix with first available prodbuild

**Comment by mcada** [comment]
Verified with:

Ignite:
    1.4.10.fuse-711001-redhat-00001
Build ID:
    b64ee2c9-5511-4dc1-85e0-1d4708716d2e
Commit ID:
    42d20ef3dd81245461e60eb759169472cffc021e
