### ISSUE TITLE
Integration doesn't start at all

### ISSUE THREAD

**Issue by mastepan** [syndesisio/syndesis#3017]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
An integration doesn't start, no errors, no exceptions in log. Just nothing happens. The integration is listed in the integrations list but that's pretty much all that happens.

## Expected behavior
An integration starts

## Tasks involved / Steps to Reproduce
1. Create an integration and click Publish
Or click Start on already created integration

**Comment by gashcrumb** [comment]
Any javascript console errors by any chance?

**Comment by mastepan** [comment]
This is only I can see when I start (nothing happens) and stop (404 error) an integration
![integrationstartstop](https://user-images.githubusercontent.com/8707251/42508068-8be0511e-8447-11e8-90f3-b8b274d0c266.png)

**Comment by gashcrumb** [comment]
Well, that `undefined` bit in the URL is definitely a bug, probably the cause.

**Comment by gashcrumb** [comment]
Hmm, I can't seem to reproduce this today, I've just done a fresh build/deploy on master.

Either from the list page or the detail page, I wonder if there's some sequence of pages/actions that led up to this state?

**Comment by mastepan** [comment]
There isn't any special sequence. I'll try this again tomorrow with a fresher build if there is any.

**Comment by mastepan** [comment]
It works today. I have no idea what the problem was...

**Comment by gashcrumb** [comment]
Magically fixed probably by some unrelated change I guess, thanks for reporting though!
