### ISSUE TITLE
Consider disabling text selection

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#3031]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

To make Syndesis feel more desktop-like, we should disable text selection. We should consider doing this globally or just for certain parts of the UI, e.g. navigation.
I'm not sure if this hurts accessibility or hinders functionality in any way.

This can be simply done by setting `user-select: none` in css.

## Expected behavior

Be more desktop like.

## Screenshot

![screenshot_2018-07-11 syndesis - development](https://user-images.githubusercontent.com/1306050/42559207-c7a9f4d2-84f3-11e8-8bfa-7fbbf133110c.png)

**Comment by gashcrumb** [comment]
I'd say yes on navigation elements and controls but other text I think would be best left as is, so am not in favor of globally disabling selection.

**Comment by dongniwang** [comment]
@syndesisio/uxd - Please provide your input here. Thank you!

I agreed with @gashcrumb's comment below. 
> I'd say yes on navigation elements and controls

**Comment by michael-coker** [comment]
I think that's fine. I don't see any issue with a11y. What do you think @seanforyou23?
