### ISSUE TITLE
New Connection wizard shows step 2 instead of 3 for Timer connector

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#3033]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

When creating new Connection for the Timer connector the wizard progress highlights step 2 instead of step 3.

## Expected behavior

For connections without configuration we should either show two steps (Select Connector, Name Connection) or we should skip and mark as disabled the unnecessary middle step (Configure Connection).

## Screenshot

![screenshot_2018-07-11 syndesis 2](https://user-images.githubusercontent.com/1306050/42566630-7236e410-8507-11e8-96ca-e668910269ba.png)

## Tasks involved / Steps to Reproduce

1. Create new Connection for Timer connector
2. Notice the step presented
3.
4.

**Comment by gashcrumb** [comment]
Hmm, we skip it, but yeah, I think there's a counter being used for the numbering, will look.
