### ISSUE TITLE
Step with datashape `any` generates a warning on the next step

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#3034]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

A warning to define the datashape of the previous step is presented even if the previous datashape step has chosen not to define the datashape, i.e. it's set to `any`. This is the case if the integration starts with the Timer connection and the user selects the default _Type specification not required_ for _Select Type_.

## Expected behavior

No warning for `any` and `none` datashapes in the previous step(s).

## Screenshot

![screenshot_2018-07-11 syndesis 3](https://user-images.githubusercontent.com/1306050/42566936-8341abfe-8508-11e8-9662-6957627b6b05.png)

## Tasks involved / Steps to Reproduce

1. Create new integration
2. Select Timer connection as the first step
3. Add the second step (could be any I think)
4. Notice the warning on the second step

**Comment by gashcrumb** [comment]
I think this was by design, @igarashitm wasn't it?  The finish requires a specific input type and can't work with any ol' input data, so you have to define a type for the start connection and then add a mapping step.

**Comment by zregvart** [comment]
Perhaps it's just an issue with the Timer connector and we should then define it's output as `none`?

**Comment by gashcrumb** [comment]
Yeah, if it doesn't produce any kind of type it should definitely be `none`.  Not sure exactly what that would mean still for the end connection if it requires some kind of input.

**Comment by oscerd** [comment]
I believe the citizen integrator won't use the output from a timer as input, it will use the timer just for trigger something. So we can set it as none.

**Comment by oscerd** [comment]
So do we want to add none to timer or others?

**Comment by igarashitm** [comment]
Not all connectors with `any`, e.g. JMS connector actually produce/consume shapeless data, then `Describe Data Type` page allows user to define a data shape on it. `none` is considered as `void` so that it will be completely ignored.

**Comment by oscerd** [comment]
So maybe it makes sense to add none only to the timer connector. At least, if we suppose user won't use datamapping step for that (but I believe they won't).

**Comment by zregvart** [comment]
There is set body extension in case the user needs some data to start with.
Though I kind think when starting with timer then immediately after that will be a step to fetch some data.

**Comment by zregvart** [comment]
Let's set Timer's connector output shape to `none`, I just tried to add shape to the Timer connector and got an exception from Atlasmap:

```
io.atlasmap.api.AtlasException: Errors: [Source document '-LI5pI92Ig2hVW1kFh7G' doesn't exist: docId='-LI5pI92Ig2hVW1kFh7G', path='/test'], 
	at org.apache.camel.component.atlasmap.AtlasEndpoint.onExchange(AtlasEndpoint.java:213) ~[camel-atlasmap-1.35.0.jar:na]
```

As the body at the start of the exchange is `null`.

**Comment by oscerd** [comment]
ok. I'm on it.

**Comment by oscerd** [comment]
you were faster.

**Comment by zregvart** [comment]
@oscerd not as fast as your reviews :robot:

**Comment by oscerd** [comment]
I'm not a bot. Just a reminder.

**Comment by oscerd** [comment]
:-D
