### ISSUE TITLE
Hide labels that don't have a corresponding value in the IVP

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#3036]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

I think we should maybe consider hiding the labels where there's no corresponding value in the new IVP, for example below I have a data mapper and this random error step from an extension.  The 'Name' is redundant as it's already shown in the grey area.  Steps don't necessarily have an action or a data type either.

![capture](https://user-images.githubusercontent.com/351660/42570529-2d054d2a-84e2-11e8-9636-76a54878d4cc.PNG)

@sjcox-rh @dongniwang @amysueg thoughts?

**Comment by gashcrumb** [comment]
@michael-coker btw, awesome work on the new IVP!

**Comment by dongniwang** [comment]
Not sure about hiding action or data type, but my question about hiding the Name field is - what if we have a connection/step name that is super long? It may not be fully displayed in the grey area and having is in the information area could be helpful.

**Comment by gashcrumb** [comment]
Good point!  Yeah, I wasn't sure what the feeling would be towards any of this, so figured it required some discussion.

**Comment by gashcrumb** [comment]
Lemme push a quick fix to add the step name for non-connection steps.

**Comment by michael-coker** [comment]
It's also worth mentioning that there is a ton of white space between the steps if we hide rows of info that don't have data.

![screen shot 2018-07-11 at 8 58 31 am](https://user-images.githubusercontent.com/35148959/42576768-bfc67d4a-84e8-11e8-9945-ffcf9f65d022.png)

**Comment by gashcrumb** [comment]
Yeah, that looks absolutely barren :-)

**Comment by gashcrumb** [comment]
K, that decided it for me, we can revisit this if we start putting more stuff in the sidebar.
