### ISSUE TITLE
Detailed status needs consistent width across stages

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#3045]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Currently the progress bar only matches the width of the text, which changes depending on the state and if there's a link.  Also it looks like the height of the detailed status increases the row height of that particular item in the list of integrations.

## Expected behavior

The overall width of the detailed status should be consistent across stages, and the height of items in the integration list should remain consistent.

**Comment by gashcrumb** [comment]
@michael-coker might need some input on this one too if you get a few -> https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/integration/list/status-detail.component.ts

**Comment by michael-coker** [comment]
@gashcrumb looks like the status message still impacts the height of the row, no? Not sure if you wanted me to follow up on this.

I'm curious what all could potentially be in that area of the toolbar. In the template, looks like there is a possibility of a few things displaying. Would all of these potentially be displayed at once? I'm not sure how to trigger all of these things to appear by setting up an invalid integration, so I just displayed them manually in the template.

![screen shot 2018-07-11 at 4 37 36 pm](https://user-images.githubusercontent.com/35148959/42600727-fd5634b2-8528-11e8-82d6-6c673a0eacdc.png)
