### ISSUE TITLE
Autosave

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#3048]
See also **https://issues.jboss.org/browse/ENTESB-11533**

As a citizen integrator, I want to have my environment autosave. 

DoD

- No save buttons are required/present. 
- I can partially complete a connector or integration and come back to it later to complete.
- Standard names for entries are applied such as ‘Untitled Connector’, ‘Untitled Connector1’ etc 
- The feature owner has confirmed one of the following:
--There is an initial draft of the user doc for this feature. 
--The writer acknowledges receiving enough information from engineering to write the initial draft of the user doc for this feature.

**Comment by amysueg** [comment]
Goal:
The user will not need to manage the saved states of connections/integrations.

Questions:
How soon would "autosave" action kick in during creation of an integration? As soon as the user enters any data.
What is the impact on the idea of having just a single draft (current implementation)?
Autosave would save a draft; the user can leave, come back and continue the same draft. There is just one draft per integration.
User actions (leaving a field, eg) trigger the autosave. Need to determine what those are. 

Split autosave connection and autosave integration into separate issues. There are more considerations for connection (wizard flow); if in a draft state, it probably shouldn't be able to be used in an integration; there is no draft state for connection yet.

**Comment by gashcrumb** [comment]
I would think basically any completed page flow through an integration
would be saved, i.e. whenever wind up at that 'save or add step' page for
starters would be a good point to automatically save the integration.

**Comment by zregvart** [comment]
@gaughan there I fixed it for you

**Comment by gaughan** [comment]
We need to talk about what defines a fix :)

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11533**
