### ISSUE TITLE
Cancel modal dialogs

### ISSUE THREAD

**Issue by michael-coker** [syndesisio/syndesis#3060]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Looks like we need to update the layout and title, body, and button wording of these dialogs

* Cancel during in create API Connector workflow 
* Cancel during integration import

This is potentially part of a larger discussion - should these buttons even have modal dialog confirmations?

The following workflow cancel buttons do not have a confirmation dialog - they just exit the workflow

* extension import
* create integration
* create connection

And assuming any of these workflows (including the first 2 mentioned in the issue) should have cancel confirmation modal dialogs, should the dialog only appear when you click the "cancel" button (current behavior), or should the modal appear when you navigate/cancel out of the workflow some other way? (click a link in the breadcrumbs, navigation, etc)

## Screenshot
![screen shot 2018-07-12 at 3 11 55 pm](https://user-images.githubusercontent.com/35148959/42657096-e3b86dae-85e6-11e8-92b4-f0282281a2db.png)
![screen shot 2018-07-12 at 2 57 01 pm](https://user-images.githubusercontent.com/35148959/42657097-e3ce6b22-85e6-11e8-9c65-3bc4dbddcfcb.png)

thoughts? @TovaCohen @amysueg @sjcox-rh @dongniwang @seanforyou23

**Comment by gashcrumb** [comment]
> It's probably worth noting that we'll have the capbability of autosave in the near future.

Right, true, though I wonder if this is maybe something to consider for 7.1 or as a stopgap until we've implemented proper saving of not finished stuff.

**Comment by dongniwang** [comment]
> Right, true, though I wonder if this is maybe something to consider for 7.1 or as a stopgap until we've implemented proper saving of not finished stuff.

Well, if that's the case, then I vote for having cancel confirmation dialogs once users have actually started a flow - e.g. after user uploaded a file, put in an URL, or any other situations where new changes/data has been introduced, etc.

**Comment by michael-coker** [comment]
@TovaCohen thanks! Updated the API Connector cancel dialog, and the integration import cancel button was removed (https://github.com/syndesisio/syndesis/issues/2587), so we're good there.

@gashcrumb re: adding `CanComponentDeactivate` to the integration workflow, is that something you think I should be able to do, or do you think it would be better to get a UI dev to implement? I looked at it in the create connection workflow and it looks a bit over my head, but maybe it looks more complicated than it is :)

@dongniwang do you think there should be a modal on the "cancel" button on the create connection workflow? Currently you only get a confirmation modal if you try to navigate away from the wizard using anything but the cancel button (clicking in the breadcrumbs, top or left nav, etc). Here's what that modal looks like.

![screen shot 2018-07-19 at 4 42 33 pm](https://user-images.githubusercontent.com/35148959/42971679-c41e09a4-8b72-11e8-9274-7cddffc6cb09.png)

**Comment by michael-coker** [comment]
@gashcrumb created a PR to add a modal when you click "cancel" in the integration editor. https://github.com/syndesisio/syndesis/pull/3143

Does that code look OK? I'm assuming it would be a bad approach to add that to each step in the editor, because we would be repeating a lot of code.

Is there a better way to do that? Or could this be integrated into the `CanDeactivate` guard work?

**Comment by heiko-braun** [comment]
@michael-coker Since you seem to be working on this, I've added it to the current sprint.

**Comment by michael-coker** [comment]
@heiko-braun thanks!

@gashcrumb did you see my [comment above](https://github.com/syndesisio/syndesis/issues/3060#issuecomment-406736621) re: adding a modal to the cancel button in the integration editor?

Also created a PR for the connection wizard - https://github.com/syndesisio/syndesis/pull/3171

**Comment by michael-coker** [comment]
@TovaCohen I added a modal to the create connection workflow cancel button. I mimicked the wording you provided for the API connector cancel modal. Is this OK or want me to update it?

Modal Title:
> Warning!

Modal body header:
> Do you really want to cancel?

Modal body:
> You have not completed the Create Connection process. If you cancel now you will lose data you already entered. Do you still want to cancel?

**Comment by TovaCohen** [comment]
That looks fine to me, Michael!

**Comment by michael-coker** [comment]
@TovaCohen thanks! I'm implementing a modal to appear in the integration creation/edit process if you try to navigate out of the workflow without saving your work. Do you think that the wording for both navigating away from the process (clicking on a link in the breadcrumbs, navigation, etc) and clicking the "cancel" button should have the same wording, or should that wording be different?

This is also a question I have about the create connection process. Currently the modal for "cancel" and just navigating away from the workflow are different....

cancel
<img width="665" alt="screen shot 2018-07-25 at 3 13 58 pm" src="https://user-images.githubusercontent.com/35148959/43224923-69d58a8a-901d-11e8-877a-9f5d87f081df.png">

navigate away
<img width="665" alt="screen shot 2018-07-25 at 3 14 03 pm" src="https://user-images.githubusercontent.com/35148959/43224941-73f282a2-901d-11e8-814a-adb13bed7f53.png">

**Comment by michael-coker** [comment]
@TovaCohen agreed. And for the cancel modal in the integration workflow, what should the body look like? Modeling after the create connection cancel modal, it should say something like "You have not finished the Create Integration process." Can we come up with a single sentence to use there for canceling out of a "create integration" and "edit integration" workflows, or do you think the modal should say "You have not finished the Create Integration process" when creating and "You have not finished the Edit Integration process" when editing?

**Comment by TovaCohen** [comment]
Sorry I didn't think of this before -- could we change to:
You have not finished creating the integration.  and
You have not finished creating the connection. 
Rather than referring to the "Create Integration process" and the Create Connection process? This would make it easier to not capitalize unnecessarily/inconsistently.

Thinking aloud about editing an integration.--- This implies that there was a complete, saved version, right? I'm stumped on how Syndesis would know that I didn't finish editing an integration. Did I enter some parameter or add a step, but then I did not select Save as Draft? Is that when this message would appear? 
I guess we need different messages for creating and editing because you can't save a new integration until it is complete. You have to finish creating the integration. But when you are editing, you just have to save what you added. Does that make sense? So for canceling while editing an integration:

Warning!
Do you really want to cancel?
You have not saved your updates to the integration. If you cancel now you will lose data you entered. Do you still want to cancel?
No  Yes

**Comment by michael-coker** [comment]
Re: the cancel button wording, I think that's a lot better. However, it's worth noting this is the current API Connector cancel button modal wording.

<img width="524" alt="screen shot 2018-07-25 at 4 07 03 pm" src="https://user-images.githubusercontent.com/35148959/43227627-d8dc2da6-9024-11e8-8e71-b85c260b3ae1.png">

That's where the wording from the cancel button in the create connection workflow came from. Should that modal change, too?

**Comment by TovaCohen** [comment]
Yeah, sorry. I keep making more work for you :-(
So the distinct sentence would be:

You have not finished creating the API client connector. 

I'm really glad you are making sure all the messages are consistent!

**Comment by michael-coker** [comment]
> I'm stumped on how Syndesis would know that I didn't finish editing an integration. 

This is a very good point. I've been focused on implementing some of the code and hadn't considered this yet.

@gashcrumb per our discussion in https://github.com/syndesisio/syndesis/pull/3143, I've been implementing the guard on each edit component. How would I know when to activate the guard after someone goes into the edit process and makes a change without saving? And then to disable the guard after saving, until they make another edit?

And since @TovaCohen is suggesting a unique modal for the guard and the cancel button, would that mean I need to implement the guard on each component, and a modal for every cancel button?

**Comment by gashcrumb** [comment]
> @gashcrumb per our discussion in #3143, I've been implementing the guard on each edit component. How would I know when to activate the guard after someone goes into the edit process and makes a change without saving? And then to disable the guard after saving, until they make another edit?

I guess at the moment we don't track when a change on an integration has been performed and so then would be "dirty" and require a save.  We'd want to implement that in the current flow service and will probably need to add a metadata item in the integration object when it's saved, so the route guard can know if the integration has been saved to determine if it should prompt or not.
