### ISSUE TITLE
Incorrect hostname in publishing state monitoring response

### ISSUE THREAD

**Issue by dhirajsb** [syndesisio/syndesis#3063]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Event and logs url from monitoring api contain a generic hostname instead of the actual cluster host name. 
## Expected behavior

Event and logs url should have correct hostname obtained from openshift client API. 
## API Endpoints and Schemas

GET calls to `https://syndesis.192.168.64.36.nip.io/api/v1/monitoring/integrations` returns incorrect logsUrl and eventsURl of the form `"logsUrl":"https://openshift.default.svc/api/v1/namespaces/syndesis/pods/i-amqp-integration-21-build/logs"`
## Tasks involved / Steps to Reproduce

1. Create and Publish an integration
2. Open a browser tab with the URL `https://<cluster-host>/api/v1/monitoring/integrations`
3. Check the logs/events url hostname.

**Comment by gashcrumb** [comment]
In fact as I think about it, if we just return the pod name/namespace we can pretty much completely externalize the URL template to the dictionary which will make it easy to update whenever there's openshift console changes.

**Comment by dhirajsb** [comment]
ok, will add the pod and namespace along with the current API endpoints for getting events and logs.
Depending upon whether the pod has started, you either need to show events or the logs tab, you'll also need a flag to tell the UI the same. Any ideas for a name for that flag?

**Comment by gashcrumb** [comment]
maybe 'linkType' and use a string enum-y kinda deal like 'LOG', 'EVENT' etc.?

**Comment by dhirajsb** [comment]
ok, that works

**Comment by dhirajsb** [comment]
Opened https://github.com/syndesisio/syndesis/pull/3072 to hopefully fix the hostname in the returned API urls. Also added the following fields, which are only present if linkType is present:
```
namespace: <String>
podName: <String>
linkType: <EVENTS|LOGS>
```

**Comment by gashcrumb** [comment]
Cool, if you want to mark that WIP for now I can push updates on the UI side for that too

**Comment by dhirajsb** [comment]
Still having trouble getting hostname from OpenShift client in the backend. Maybe UI has better chance of somehow getting the original browser hostname like `syndesis.192.168.64.36.nip.io`??

**Comment by gashcrumb** [comment]
Ah, so there's a setting in the `config.json` at the moment that's used to send the console URL on to the UI that was set up originally when the activity log stuff was added to the integration details page.  The hack I put in place on the UI side uses that.

There's an open issue (#2730) though about figuring out a better way to get the console URL, it's certainly pretty fragile at the moment I feel.

**Comment by dhirajsb** [comment]
PR has been updated to remove the urls returned from the backend, instead the UI can compute the appropriate URLs based on it's `consoleURL` config property using the backend provided namespace and pod name.
