### ISSUE TITLE
Creating connections with oauth: question mark in comment

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#3066]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

1. set up for example Twitter oauth in settings page (no need for correct values)
2. click on create connection, select Twitter
3. see question mark in this comment: Log into your Twitter account to grant authorization for ? to act on your behalf.

![screenshot_20180713_134615](https://user-images.githubusercontent.com/14313995/42690060-342dc448-86a3-11e8-9f37-7dae01ce0798.png)

**Comment by gashcrumb** [comment]
It's a substitution issue with the dictionary, this particular string references what should be the app name, which is dynamically pulled from the `config.json`, apparently that's not working.
