### ISSUE TITLE
Feature request: Option to select if I want to use oauth settings when creating connection

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#3067]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

User story:
I want to create three Gmail connections. Two of them using oauth and third using Tokens so I can read e-mails from 3 different accounts.

Current status:
I can create 3 different Gmail connections using Tokens. But when oauth is set via settings page, I am not able to create new connection with Tokens. Also there is no option to create 2 different oauth settings for one type of connection.

**Comment by oscerd** [comment]
If you're able to create 3 connections with three different gmail accounts, you should be able to do the same with oauth. You'll use the same application for the three different accounts.

**Comment by mcada** [comment]
Thanks for this information as I wasn't aware of it. There is still the part where there is no option to create connections with tokens when oauth is set up. I guess it is intended? If so, feel free to close this one.

**Comment by zregvart** [comment]
If you setup OAuth clientId/secret then you opt-in to using OAuth flow for OAuth supporting connector. Multiple connections accessing different accounts should be possible, I don't see a way this could not be true, if it is then it's a bug.
Other than with Concur, OAuth based connectors we currently have can access across environments and accounts. With Concur we have an issue as we effectively tie Syndesis to a single environment as the OAuth clientId/secret are valid only for that environment.
I would opt to close this, and think if we need the functionality to define multiple OAuth settings per connector.
