### ISSUE TITLE
Unecessary requests to `/api/v1/integrations`

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#3071]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

It seems that we're hitting the `/api/v1/integrations` endpoint multiple times. This really hurts the backend (~10sec responses).

## Expected behavior

Load only when needed, probably only when update is received via socket?

## Screenshot

On staging:
![peek 2018-07-13 16-54](https://user-images.githubusercontent.com/1306050/42698380-059a3c22-86be-11e8-9059-ab0edf9ee079.gif)

## API Endpoints and Schemas

`GET /api/v1/integrations`

## Tasks involved / Steps to Reproduce

1. Open Syndesis
2. Wait on the dashboard screen doing nothing
3. Notice the requests going to `/api/v1/integrations`

**Comment by gashcrumb** [comment]
yeah, so the UI does this *however* lots of updates show up on that websocket.  I added a debounce() to the code to try and tone it down a bit.

For integrations we get events for integration deployments, integration bulletin board updates and I think now integration deployment status updates, so if you look at the websocket data when starting an integration you'll see probably like 10 events come in for that one action.  Originally that would probably trigger 10 fetches, now at least it should be debounced to hopefully 1 fetch, though I was also conservative in how many events to discard before fetching again.

**Comment by gashcrumb** [comment]
Also double-check that those aren't requests to fetch integration metrics, the URL for that also ends in 'integrations' which can be confusing.

**Comment by gashcrumb** [comment]
Also I considered also adding a debounce for the calls to fetch an individual item as well, but again wanted to be somewhat cautious as of course this effects the perceived responsiveness of the UI with regards to presenting server updates.  But it'd be easy to add and test out also, it'd be a matter of doing [this](https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/store/entity/entity.store.ts#L75) before [this line](https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/store/entity/entity.store.ts#L95) if you want to have a play.

**Comment by gashcrumb** [comment]
One other thing to consider is debouncing calls for fetching the list.  For example on the dashboard there's two individual components that trigger a fetch of integrations, the line of cards at the top and the "top 5 integrations" list.  That means 2 calls to load integrations, with each of those the UI also now triggers 2 calls to fetch any detailed status updates.  And then it seems like 5 or more calls to fetch metrics queue up and then are satisfied.

Also the dashboard makes a call to fetch connections too, which will likely have some impact.

Maybe the homepage should just say 'welcome' :-)
