### ISSUE TITLE
Update button placement for create connection and API connector workflows

### ISSUE THREAD

**Issue by amysueg** [syndesisio/syndesis#3074]
See also **https://issues.jboss.org/browse/ENTESB-11532**

## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
This epic is created to follow through with updates to screens for existing create connection pages as well as API connection to follow the new button placement specified in the Connection Template work #2212 

## Expected behavior
Buttons for embedded wizards should appear on the pages as specified in #2212, that is, navigation buttons should appear as specified by Patternfly in the lower right corner of the card. Form action buttons should appear on a separate row above the navigation buttons, but should be left-aligned to the left edge of form fields, just below the last form field.

## Screenshot
This is a sample screen from the design:
![screen shot 2018-07-13 at 1 51 01 pm](https://user-images.githubusercontent.com/31700119/42707583-aacc146a-86a8-11e8-8a9e-a0296a62ea14.png)

FYI @paoloantinori @heiko-braun @sjcox-rh @dongniwang @michael-coker @seanforyou23 @gaughan

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11532**
