### ISSUE TITLE
Console URL doesn't seem to be correctly set when installed via 'syndesis install'

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#3076]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Seems like the 'open log in openshift' link and the 'logs' link don't work properly out of the box on openshift, with a little digging we found that the `consoleUrl` setting in the UI's `config.json` file seems to be empty or can often be the wrong URL.

## Expected behavior

Ideally this URL should be set correctly when running `syndesis install`

@dhirajsb FYI

As a workaround this can be fixed by editing the `syndesis-ui-config` ConfigMap.  Also with #3072 `yarn start:minishift` will set up the dev instance with the right console URL at least via `minishift`.

**Comment by phantomjinx** [comment]
Current status of this is holding, pending an [upstream](https://github.com/openshift/origin/issues/20447) exposure of the console url via their API. Until then, there is little reliable that can be accomplished. See this [PR](https://github.com/syndesisio/syndesis/pull/3198) for more details.

**Comment by gashcrumb** [comment]
https://github.com/openshift/origin/issues/20447#issuecomment-511042444

In our current architecture this would need to be re-exposed by the server in some fashion.

**Comment by zregvart** [comment]
@paoloantinori why is this a `p0` now the issue has been open for a year  unaddressed?

**Comment by paoloantinori** [comment]
Because it's still present and broken in 7.4.

**Comment by zregvart** [comment]
@paoloantinori I guess I assumed that this is blocking 7.4 release. Did you mean to signal that this is priority work for 7.5?

**Comment by paoloantinori** [comment]
yes, it's for 7.5.

I just wanted to raise it's a priority since the beginning of the dev Sprint to be sure we won't forget to look at this.

I do mistakes often with GH classification and it's **good that you have double checked**, but luckily I didn't this time and I confirm that the 7.5 release target is the correct one.

![Screenshot from 2019-07-30 11-50-38](https://user-images.githubusercontent.com/1520602/62119626-46a20900-b2c0-11e9-9026-29e09d95c695.png)
