### ISSUE TITLE
Allow specifying build nodeselector to pin builds to specific build nodes

### ISSUE THREAD

**Issue by dhirajsb** [syndesisio/syndesis#3080]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

When an integration build starts on a new node, a big docker build image needs to be downloaded to that node, which slows the integration build. 
## Expected behavior

User (Syndesis admin) should be able to specify [node selectors](https://docs.openshift.com/container-platform/3.9/dev_guide/builds/advanced_build_operations.html#dev-guide-assigning-builds-to-nodes) in syndesis server config map, which are satisfied by a small number of specific nodes designated to build integration source. 
This will ensure that nodes without the required s2i docker image are not used to build integrations. And the cost of _priming_ selected nodes is only incurred once per selected node.

**Comment by dhirajsb** [comment]
@kcbabo fyi, this should help take some of the sting off of long build times.

**Comment by kcbabo** [comment]
Nice!
