### ISSUE TITLE
When creating integration, connector icons are not clickable

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#3090]
I think that those icons should be clickable and should show step details like when you expand integration flow and click on the names of those steps.

![screenshot_20180716_183350](https://user-images.githubusercontent.com/14313995/42771283-f8cd5ae0-8926-11e8-92b5-5af36d98fb7e.png)

**Comment by gashcrumb** [comment]
I think it's actually a bug that the icon isn't clickable, as then you *have* to expand the IVP to get around in the editor.
