### ISSUE TITLE
Update the informational text when an oauth app isn't configured

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#3099]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Currently when an oauth application is unconfigured, the list item contains the text "Client ID and secret not configured."  With the changes to the oauth app page where a given app can have more than those two settings or use different terms, this string isn't applicable, for example:

![capture](https://user-images.githubusercontent.com/351660/42823851-97646196-89ac-11e8-9df4-e95d55d357cc.PNG)

So the message says "Client I and client secret not configured" but the SAP concur connector has an ID, secret, URLs etc.  For twitter it uses different terms for the ID/secret:

![capture](https://user-images.githubusercontent.com/351660/42823924-c9ce92f0-89ac-11e8-91fa-9037270bb434.PNG)

We should update this text to be more open-ended/generic.

**Comment by gashcrumb** [comment]
@TovaCohen @dongniwang FYI

**Comment by TovaCohen** [comment]
Possibilities:

 "Access to this application is not configured."  
OR
 "Access from Fuse Online/Syndesis to this application is not configured." 
OR 
"This environment is not authorized to access this application."

**Comment by gashcrumb** [comment]
I like the first one...

**Comment by dongniwang** [comment]
+1 the first one
