### ISSUE TITLE
Better event emitting and handling

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#3105]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Currently we emit events for `integration`, `integration-deployment` and `integration-bulletin-board` but offer only REST resource for `integration` (containing `integration-deployment` and `integration-bulletin-board` data).

Loading the whole integration is expensive operation on the backend. Doing it for (just) a change in deployment/bulletin board data is doubly so.

What we can do in alternative (taken from https://github.com/syndesisio/syndesis/pull/3097#discussion_r203050035 and amended):

 - add a new endpoint (REST resource) for the integration-bulletin-board/integration-deployment and update integration state based on that
 - also trigger integration event on integration-bulletin-board change on the backend
 - send also changed data via events

## Expected behavior

Be less taxing on the backend when it comes to updates.

## Screenshot

Example of loading a lot of data from the backend can be seen in #3071.

## API Endpoints and Schemas

`GET /api/v1/integration`

## Tasks involved / Steps to Reproduce

1. Within Syndesis make changes to extensions or deployment state
2. Notice how the request to load the integration is issued for every event sent based on the state change of deployment/bulletin board

**Comment by lburgazzoli** [comment]
I remember we had different endpoint in the past but UI asked to inline board in the integration object being returned to avoid going back and forth.

**Comment by gashcrumb** [comment]
Yeah, as I recall I would have had to fetch an integration by ID, then separately fetch notifications for it etc.  Was a similar situation with deployments at one point which became problematic with the list.

I mean, we could put these all into separate endpoints, may as well migrate the UI to just mirror the server's state locally and maintain updates via events only.
