### ISSUE TITLE
Switch 'extensions' area of the app to the i18n dictionary

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#3107]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
[x] busywork
</code></pre>

## The problem

All the strings in the HTML templates in `/customizations/tech-extensions` need to be switched over to using the i18n dictionary.  Also it should be renamed to `/customizations/extensions`.

**Comment by paoloantinori** [comment]
what's busywork? :rofl:

**Comment by gashcrumb** [comment]
Going through templates and replacing strings :-)
