### ISSUE TITLE
Apicurio editor - Save button missing

### ISSUE THREAD

**Issue by mastepan** [syndesisio/syndesis#3108]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

I can't find any Save button whatever I change in the swagger specs. The editor can be only cancelled.

## Screenshot

![apicuriosavemissing](https://user-images.githubusercontent.com/8707251/42885159-8ab5ed94-8aa0-11e8-8d04-067d4e70a455.png)
## Tasks involved / Steps to Reproduce

1.
2.
3.
4.

**Comment by dongniwang** [comment]
Looking at the screenshot also noticed that the breadcrumb is not showing that users are actually in the "Edit API Definition" level. 

Is it possible to show something like the following? 
Home > Customizations > API Client Connection > Edit API Definition

**Comment by mastepan** [comment]
As I can see there are more things missing/different from the UI design https://redhat.invisionapp.com/share/UJLWDYZZGCE#/screens/305466950

The question is this is stil on someone's TODO list or if I should report all differencies @kahboom @dongniwang ?

**Comment by kahboom** [comment]
@mastepan - Some things, like the Full Screen mode, will likely not be completed in this sprint, however, there are definitely some things missing. This is definitely on my To Do list! I am trying to sort out some local issues to be able to continue working on this.

@dongniwang - That's because we just got the toolbar in, and I've been having Minishift issues so have not been able to add much functionality to it. In other words, I've not done the work necessary for the toolbar. I can take a look and it should be no problem at all to change the breadcrumb to that, if you'd like, instead of what's on the design.

**Comment by dongniwang** [comment]
@kahboom - If it's possible, then let's update the breadcrumb to the following: 
Home > Customizations > API Client Connection > Edit API Definition

Thank you!

**Comment by kahboom** [comment]
Perfect @dongniwang , thanks, will do!

**Comment by elvisisking** [comment]
I kind of like the first UX design (Version 1) a bit better than the new design (Version 2). The first design had inner Cancel/Done buttons which would allow the user to cancel out of the ApiCurio editor and still leave them in the wizard at the review actions page I'm guessing. With the latest design (without the inner Cancel/Done buttons), clicking Cancel would have the user cancel out of the entire wizard (I think). So if the user didn't want to use the changes made in the editor, or maybe didn't make any changes in the editor, they would have to start the wizard all over again.

The new design has the Save button appearing and disappearing. So kind of like old design again where that didn't happen. I can see where having two Cancel buttons/toolbars on the same page might be confusing also; and maybe that was the motivation for the new design.

**Comment by heiko-braun** [comment]
//cc @dongniwang can you work with @elvisisking to come to a decision which design to use?

**Comment by kahboom** [comment]
If we go with 2, please post the link here as well. Thanks! :)

**Comment by dongniwang** [comment]
Hello everyone - 

@elvisisking, @kahboom, @amysueg and I met earlier today and decided to make some improvements to the Apicruio integration UX design based on the feedback provided in the discussion here. Latest UX design is [here](https://redhat.invisionapp.com/share/V7N923M4N2E). You can also find the latest design via UX tracker. Please review and provide feedback at your earliest convenience as we want to move this forward as soon as possible. Thank you. 

I think @elvisisking and @michael-coker are working on implementing this right now. 

cc: @paoloantinori @heiko-braun @kcbabo @gaughan @michael-coker

**Comment by TovaCohen** [comment]
Why are both the Back button and the Cancel button needed? 
Is there any difference in behavior between them?
I think that the cancel confirmation dialog should be consistent with the other cancel dialogs (integration, connection) so it should be:

Warning!
Do you really want to cancel?
You have not saved your updates to the API definition. If you cancel now you will lose data you entered. Do you still want to cancel?

No   Yes

Will a user always be ready to exit after clicking Save? Is there a chance that a user would want to Save some changes and keep editing? Maybe that's an enhancement for the next release.

**Comment by dongniwang** [comment]
@TovaCohen Thanks for the suggestion! cc: @michael-coker @elvisisking @kahboom 

>Why are both the Back button and the Cancel button needed?
Is there any difference in behavior between them?

The idea is that "< Back" provides context and puts users in the mindset that they're at a sub-step of step 2 Review/Edit API Definition (so one level deeper). 
The Cancel and Save buttons are considered a set of action buttons which normally appear in pairs. 
They do have the same behavior but were included for different reasons.

**Comment by michael-coker** [comment]
@elvisisking I reworked the layout a bit to get the header shown per @dongniwang's designs. We also changed the "back" link from black to blue (normal link color) - [here's the branch](https://github.com/michael-coker/syndesis/tree/3108-updates). Let me know if you have any questions or want me to work on it some more.
