### ISSUE TITLE
Pagination needs work

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#3113]
See also **https://issues.jboss.org/browse/ENTESB-11530**

## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

There's a basic implementation of pagination at the backend but I think we'll need a bit more information on the UI side to implement more on-demand fetching of resources.

Currently there's `page` and `per_page` options that can be sent, the reponse for these requests contain a total, the items but no indication of how many possible pages or items etc.

**Comment by gashcrumb** [comment]
This could be in some relation to #3110 perhaps

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11530**
