### ISSUE TITLE
Prometheus deployment failing

### ISSUE THREAD

**Issue by jcordes73** [syndesisio/syndesis#3116]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

The Prometheus pod is constantly crashing due to not being able to write to /data.

This was solved by adding the following to the DeploymentConfig:

securityContext:
  fsGroup: 2000
  runAsNonRoot: true
  runAsUser: 1000

## Expected behavior

Prometheus starts up fine.

## Tasks involved / Steps to Reproduce

1. Deploy syndesis master
2.
3.
4.

**Comment by zregvart** [comment]
@jcordes73 could you describe your environment where you observe this behaviour?
Our staging is using OpenShift v3.9.31 and we don't see this particular issue. It might make sense to set `runAsNonRoot: true` I'm not sold on using specific UID/GIDs.
I assume you came by GID 2000 and UID 1000 from the [OpenShift](https://docs.openshift.org/latest/admin_guide/manage_scc.html) or [Kubernetes](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/) documentation?

**Comment by paoloantinori** [comment]
Hi @jcordes73 could you also specifying which version of Syndesis you are using?

**Comment by ericw13** [comment]
I think I'm running into the same issue as the OP. The syndesis-prometheus deployment hangs for 10 minutes before timing out. The only message in the log file is "Scaling syndesis-prometheus-X to 1".

$ oc version
oc v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.42.217:8443
openshift v3.9.0+71543b2-33
kubernetes v1.9.1+a0ce1bc657

I tried editing the dc/syndesis-prometheus and adding runAsNonRoot: true as suggested by @zregvart above, but that hasn't resolved the issue.

**Comment by zregvart** [comment]
@ericw13 from the IP address this seems to be a minishift installation, am I correct? Can you provide the steps you used to install Syndesis on minishift?

Were you using the `syndesis` CLI tool to [install on minishift](https://doc.syndesis.io/#_installing_syndesis)?

We have made some changes with the introduction of the operator in the latest version reflected in [this section](https://doc.syndesis.io/#syndesis-install) of the documentation.

**Comment by ericw13** [comment]
@zregvart Yes, this was on minishift. I was able to find an insufficient memory error when I watched the logs of one of the deployment pods. Once I bumped the default memory up to 8GB, I was able to get all deployments to start up successfully.

**Comment by zregvart** [comment]
Odd, we should have some headroom with 4GB RAM.
