### ISSUE TITLE
The View/Edit/Start/Stop dropdown menu of syndesis integration is disappearing on integration start

### ISSUE THREAD

**Issue by tplevko** [syndesisio/syndesis#3121]
## This is a...

<pre><code>
[ ] Feature request
[ x ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

There is a problem with the syndesis integration dropdown menu, which offers the user operations: View/Edit/Start/Stop/Delete/Export. 
When the integration is starting, the menu tends to disappear approx. every 3 seconds.

## Expected behavior

The menu should be in its place until the user selects one of the offered operations or clicks somewhere else on the page.

## Screenshot

![out](https://user-images.githubusercontent.com/4180208/42941633-aa90d648-8b5d-11e8-920d-7dbbee49e1db.gif)

## Tasks involved / Steps to Reproduce

1. Create some integration
2. While the integration is starting - go to the integrations list page
3. Click on the three vertical dots in the right - the menu appears
4. Observe how it disappears without any action after 3 seconds (can be observed only when the integration is starting)

**Comment by gashcrumb** [comment]
This isn't really a regression but has probably been the behavior all along.  Any time there's an update the whole list is redrawn currently, i.e. it's parent element is blanked and filled in again.

**Comment by riccardo-forina** [comment]
I'm looking into this, mostly to learn more about the inner workings of the app but maybe I'll be able to find some way to avoid the problem

**Comment by gashcrumb** [comment]
Sounds good!  I think the dropdown involved here is provided by patternfly, not sure if it can perhaps attach the dropdown element to the page body or some other element other than the parent element.

**Comment by gashcrumb** [comment]
Just as another datapoint this problem also happens on this list:

![capture](https://user-images.githubusercontent.com/351660/43204145-28bc0aa8-8fee-11e8-815c-a02bf5e0f235.PNG)

**Comment by gashcrumb** [comment]
Yep, also on any other list pages as well actually, i.e. go on the connections page, open a dropdown on a connection, then delete a connection from another browser tab, menu goes away on a refresh.  In this case it's probably ideal though unless the menu moved along with it's parent element.
