### ISSUE TITLE
Change breadcrumb level "done" button to "cancel" in integration importer

### ISSUE THREAD

**Issue by michael-coker** [syndesisio/syndesis#3126]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
That button should be labeled "close", since it takes you back to the integration list. And it should be "secondary" (`.btn-default`) style

**Comment by gashcrumb** [comment]
There's a big PR open that overhauls the import page, might want to wait until that gets in -> https://github.com/syndesisio/syndesis/pull/3123

**Comment by gashcrumb** [comment]
In fact if you want I can add this change to that PR, it's no problem...

**Comment by gashcrumb** [comment]
Added a commit to #3123 for ya, lemme know if there's anything else...

**Comment by michael-coker** [comment]
perfect, thanks @gashcrumb!
