### ISSUE TITLE
View Log link not working

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis#3131]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

The "View Logs" link on the publishing page does not work for me. 

## Screenshot

![screenshot from 2018-07-20 10-12-18](https://user-images.githubusercontent.com/1520602/42991882-44d8f2ea-8c07-11e8-93d3-515d07b6e260.png)

## Details
This is where the link point. 
https://syndesis.192.168.42.6.nip.io/project/syndesis/browse/pods/i-paolo-3-build?tab=logs

If I click there, I'm redirected to https://syndesis.192.168.42.6.nip.io/

That doesn't display anything

![screenshot from 2018-07-20 10-27-40](https://user-images.githubusercontent.com/1520602/42991985-8e845c2c-8c07-11e8-8b33-806b427d7cac.png)

If I check with CLI tools I can see this, that might indeed explain the issue, since the log entry is waiting and doesn't have anything to update

```
10:19 $ stern paolo
+ i-paolo-2-build › sti-build
i-paolo-2-build sti-build Image "docker.io/syndesis/syndesis-s2i@sha256:8aed68b4d29..." not available locally, pulling ...
- i-paolo-2-build
+ i-paolo-3-build › sti-build
i-paolo-3-build sti-build Image "docker.io/syndesis/syndesis-s2i@sha256:8aed68b4d29..." not available locally, pulling ...
```

but anyhow, I wonder if we should show something in that log destination page

**Comment by paoloantinori** [comment]
Closing this since my system is unreliable at this moment, so I might just have seen a side effect of that.

**Comment by gashcrumb** [comment]
It would have been a duplicate of #3076 anyways :-)
