### ISSUE TITLE
syndesis install fails on a fresh machine 

### ISSUE THREAD

**Issue by riccardo-forina** [syndesisio/syndesis#3145]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

I'm trying to install the whole stack following the handbook, on a fresh OSX laptop. Requirements are installed and up to date. When running `./tools/bin/syndesis minishift --install --project syndesis` it fails with the following error:

`error: CronJob in version "v1beta1" cannot be handled as a CronJob: no kind "CronJob" is registered for version "batch/v1beta1"`

I end up with all the required containers set up, but the app doesn't work (UI can't talk with the apis).

```
$ oc version
oc v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth

$ minishift version
minishift v1.21.0+a8c8b37

$ yarn --version
1.6.0
```

## Expected behavior

The project should be installed successfully.

## Tasks involved / Steps to Reproduce

1. ./tools/bin/syndesis minishift --install --project syndesis
2. ...
3. 💥

## Workaround

I managed to successfully install the project removing the CronJob section in the `install/syndesis-dev.yml` and then running `./tools/bin/syndesis minishift --install --project syndesis --local --dev`

**Comment by rhuss** [comment]
@riccardo-forina this just has been fixed. The minimal required version for OpenShift is 3.9 now, so the default for minishift has bee just upgraded via #3144 

Could you please verify whether it works for you now out of the box ?

**Comment by riccardo-forina** [comment]
Yes it does, thank you :)
