### ISSUE TITLE
'Recent Updates' displays only first 5 created integrations 

### ISSUE THREAD

**Issue by mmelko** [syndesisio/syndesis#3147]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
'Recent Updates' displays only first 5 created integrations. If any other is updated or new integration is created it doesn't show up in recent upgrades card. 

## Tasks involved / Steps to Reproduce

1.
2.
3.
4.

**Comment by heiko-braun** [comment]
@mmelko Could be a `p2` from my point of view, what do you think?

**Comment by mmelko** [comment]
@heiko-braun sure, this isn't breaking anything it's just not helping overall user experience.

**Comment by heiko-braun** [comment]
cool, thanks for the feedback @mmelko. I've updated the prio

**Comment by gashcrumb** [comment]
One thing to note, there seems to be some discrepencies between when integrations are "changed" and what actually triggers the `updatedAt` field, doesn't seem like updating the description or even stopping/starting an integration changes that field, so I think this will lead to more testing and bugs filed.  Thanks!
