### ISSUE TITLE
Add Integration buttons to Home screen

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#3152]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

We have a `View all Connections`/`Create Connection`, to be consistent we should probably have `View all Integrations`/`Create Integration` link/buttons.
There is also a bit of inconsistency between headings for `Top 5 Integrations` and `Connections`.

## Expected behavior

Have `View all Integrations`/`Create Integration` present on the Home screen.

## Screenshot

![screenshot](https://user-images.githubusercontent.com/1306050/43073307-5bb52b18-8e79-11e8-92ed-5e609fa571f5.png)

**Comment by gashcrumb** [comment]
Is actually a bug -> #3204

There's buttons at the top-right that should appear when there's integrations but they weren't showing up properly.
