### ISSUE TITLE
Create a test suite for the syndesis build/install scripts using bats

### ISSUE THREAD

**Issue by phantomjinx** [syndesisio/syndesis#3161]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

With the complexity of the syndesis script and its high value and visibility in the configuration of the application, it would be beneficial for the creation of a test suite to ensure the functionality is consistently maintained and effective.

The Bash Automation Testing System ([bats](https://github.com/sstephenson/bats)) provides a testing framework for just such a test suite. An example for review is available [here](https://github.com/fabric8io-images/run-java-sh/tree/master/test).

## Expected behavior

Automated test suite unit testing the commands, functions and structure of the syndesis install and build scripts.

**Comment by rhuss** [comment]
Still a valid issue I think.
