### ISSUE TITLE
Cleanup Timer connector's Simple Timer action

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#3164]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Timer connector's `Simple Timer` action should be cleaned up to:
 - have nicer labels: currently `period`, should be `Period`
 - to have default period of 1 min (same as DB connector)
 - no description (same as DB connector)
 - label hint of `Delay between scheduling (executing).` (same as DB connector)
 - period should be required

## Expected behavior

Be in line with what we have done for other connectors, namely the DB connector.

## Tasks involved / Steps to Reproduce

1. edit `app/connector/timer/src/main/resources/META-INF/syndesis/connector/timer.json` to reflect the above

**Comment by zregvart** [comment]
@paoloantinori @heiko-braun I'll add this to this sprint it's a simple task to do only in the JSON descriptor of the Timer connector.

**Comment by heiko-braun** [comment]
sounds good
