### ISSUE TITLE
Cleanup Timer connector's Cron Expression action

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#3165]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Timer connector's Cron Expression action should be cleaned up to:
 - Cron Expression propery description should contain an example of a cron expression
 - Cron Expression should be required
 - Cron Expression should have a default of 1 minute

## Expected behavior

Be in line with what we have done for other connectors.

## Tasks involved / Steps to Reproduce

1. edit `app/connector/timer/src/main/resources/META-INF/syndesis/connector/timer.json` to reflect the above

**Comment by zregvart** [comment]
@paoloantinori @heiko-braun same here as in #3164

**Comment by oscerd** [comment]
I'm on both If you aren't already working on them.
