### ISSUE TITLE
Return the imported resources in the response to the import API

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#3167]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Currently `/integration-support/import` only returns the ID of an imported .zip.  So to display the name and figure out what connections the import added, the UI has to go and fetch all this data in separate requests.  And currently we're only guessing at what connections were imported by looking at the newly imported integration's step array.  Since these embedded connections don't contain the full connection object, the UI has to then fetch connections to show the 'connection required' flag if it's applicable.

## Expected behavior

Seems like it'd be easier if the API response was all of the newly imported objects in a map like:

```
{
  integrations: [],
  connections: [],
  extensions: []
}
```

We don't even show extensions in the import results (@dongniwang @sjcox-rh should probably add that, FYI) and I couldn't easily correlate extensions from integrations anyways, so that'd mean more fetching.

**Comment by gashcrumb** [comment]
Required to fix #3125

**Comment by dongniwang** [comment]
@gashcrumb - I wonder if we should open an epic to capture all the import workflow enhancments? 

FYI also related to 
#2694 
#2603 
#2602

**Comment by gashcrumb** [comment]
I'm not sure if it warrants an epic or not, @paoloantinori WDYT?

**Comment by paoloantinori** [comment]
I've checked  the issues  linked by @dongniwang and some are bugs, some features and some are closed.

I don't see enough material to turn this into an epic.

**Comment by tplevko** [comment]
Verified by QE
