### ISSUE TITLE
Apicurio Editor: URL-fetched specification not supported

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis#3174]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
Specifications should be treated differently based on how they are obtained (e.g. URL fetch or file upload), due to the data structure. See [here](https://gist.github.com/kahboom/9f9e606df271b49973bf7337de3ed0d1) for reference. This is related to #3096.

When a URL is specified, the user can then proceed to Review/Edit from the Review Actions step (2), but the editor is blank, as if a blank specification had been provided.

## Expected behavior
User should be able to either upload a file or specify a URL for the Swagger/OpenAPI spec and see the details of it in the Review/Edit Apicurio editor.

## Screenshot
<img width="1680" alt="screenshot 2018-08-01 12 38 31" src="https://user-images.githubusercontent.com/3844502/43535535-49e0c8f0-9588-11e8-905f-d8057605e591.png">

## Request and Response Data
See [here](https://gist.github.com/kahboom/9f9e606df271b49973bf7337de3ed0d1) for reference.

## Tasks involved / Steps to Reproduce
1. Navigate to Customizations.
2. Proceed as if you were creating a custom API connector, except select the URL option.
3. Test with any valid Swagger/OpenAPI URL.
4. You should see an error.

**Comment by elvisisking** [comment]
When the API spec is fetched via URL, we are running a validation and providing the user errors and warnings for review. We need to pass that spec to the ApiCurioComponent editor if the user wants to modify that spec. Is there a way for the wizard to obtain the URL fetched spec from the backend? Or maybe it could be passed along with the errors and warnings maybe?

**Comment by zregvart** [comment]
Backend is stateles so the UI holds the specification in memory till the end of the wizard.

I think it's here:
https://github.com/syndesisio/syndesis/blob/5358d5fab5da409823019353d35b02387c59b0ac/app/ui/src/app/customizations/api-connector/api-connector.models.ts#L67

We discussed how we exchange errors/warnings with @EricWittmann and agreed that in future we might want to delegate all validations to Apicurio and that Apicurio could provide us with an interface to add custom validations for use cases that would not be supported out of the box.

This would help us as we would have a single model for validations, and the UI would be consistent with the placement and presentation of errors/warnings.

**Comment by EricWittmann** [comment]
Not only am I happy to support custom validations, I'm also willing to implement any Syndesis-specific validations if they can be documented.  I think @zregvart mentioned there are only a handful of them today.

I can also easily document/demo how to perform validation outside the Apicurio editor.  The validation code is contained within an entirely separate NPM module found here:

https://www.npmjs.com/package/oai-ts-core

This module supports reading/writing/validating OpenAPI documents and can be used independently from Apicurio.

**Comment by elvisisking** [comment]
I'm having a hard time tracking this down @zregvart. I think when the UI validates a URL spec, it seems like we get back an `ApiConnectorData` object, which I think is created from the `ConnectorSummary` server-side object. The result includes the actions but not the spec. But maybe I'm not tracking this down right. Any ideas?

**Comment by kahboom** [comment]
@elvisisking - That's why we had the FileReader for uploaded files; we'll need to store it in the browser unfortunately as we don't even get back enough data from the API to tell us parts of the spec we need for the remaining steps in the wizard. So, I think that could be the next enhancement after this release, and there is an issue open for it (https://github.com/syndesisio/syndesis/issues/2717). For now we'll have to store it ourselves, or maybe even create a new object to store the parts of it we want (e.g. auth config settings, warnings/errors, name, description, icon). I'm trying that now to see how/if it works for our purposes.

**Comment by zregvart** [comment]
> I'm having a hard time tracking this down @zregvart. I think when the UI validates a URL spec, it seems like we get back an ApiConnectorData object, which I think is created from the ConnectorSummary server-side object. The result includes the actions but not the spec. But maybe I'm not tracking this down right. Any ideas?

It's a feature™. The backend will not resolve the URL in `specification` until the final step of the wizard. If we need to pass the JSON/YAML content of the OpenAPI specification pointed by the user provided URL to Apicurio -- the UI will need to load it.

There is a bit of documentation about this in the [design proposal](https://github.com/syndesisio/syndesis/blob/master/project/proposals/119-custom-connectors.md).

**Comment by paoloantinori** [comment]
Downgrading this since there is an alternative user flow to obtain the functionality requested.

Still a high priority issue though.

**Comment by gashcrumb** [comment]
> If we need to pass the JSON/YAML content of the OpenAPI specification pointed by the user provided URL to Apicurio -- the UI will need to load it.

The UI would need a backend service to do this, it can't be done from the frontend.

**Comment by EricWittmann** [comment]
Classic "URL Fetch" service to get around CORS.  May have written that once or twice. :)

**Comment by elvisisking** [comment]
Just trying to understand things a bit more ... As I mentioned in an earlier comment, it seems like we have already fetched the URL content in order to run validation the first time (haven't we?). If so, it doesn't seem like we should have to fetch it again each time the user decides to edit the original spec.

**Comment by zregvart** [comment]
Yes that is true, the backend has fetched from the URL, and we could include the fetched specification in the `.../info` response.

**Comment by riccardo-forina** [comment]
Sure! To summarize the problem, the ApiCurioComponent editor requires a spec passed in as a JSON object, but when we the spec is provided as an URL we don't have it causing the bug. 

So I added a check in the post-validation phase in the UI that checks if we are working with a spec URL: if that's the case, the UI will try to fetch the spec, parse it and set it up so that the editor can work with it. 

The limitation is that the browser performs this fetch, so the spec URL must be CORS enabled for us to retrieve it. In case of failure fetching the spec, the "Edit/review" button will be disabled.

> **zregvart commented**
Yes that is true, the backend has fetched from the URL, and we could include the fetched specification in the .../info response.

@zregvart proposal would be the best way to fix the problem; it would give us a way to ignore the fact that the spec could come from multiple sources, simplifying the code.

**Comment by zregvart** [comment]
I would not consider this critical (i.e. needs to be included in release). Adding specification as response of the `.../info` endpoint would be 2-3 line change without much risk.

**Comment by kahboom** [comment]
We should discuss the possibility of adding enhancements to this through another issue, but since this was originally filed as "Bug" this was already fixed for this sprint.
