### ISSUE TITLE
[Create Connection] Wizard step mismatch when returns from OAuth  

### ISSUE THREAD

**Issue by dongniwang** [syndesisio/syndesis#3175]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Noticed this when watching the Concur demo. During the create connection flow step 2 - user selects to connect via OAuth, the page redirects user to Concur and then comes back to syndesis. The screen then shows add connection details with the wizard step indicator is still on step 2. 

## Expected behavior

From the UX design, we suggested to return user to step 2 with a success confirmation message. Then user proceeds to step 3. See design [here](https://github.com/syndesisio/syndesis/blob/master/ux/designs/oauth/oauth.md). 

Alternatively, we could just return user to step 3, but in this case the wizard should indicate user is on step 3. 

## Screenshot

![image](https://user-images.githubusercontent.com/24943812/43163110-132350c2-8f5b-11e8-91d6-19ff84033108.png)

## Tasks involved / Steps to Reproduce

@KurtStam mentioned this is nothing to with concur specifically but could be happening to all OAuth connectors. 

cc:  @michael-coker @gashcrumb @sjcox-rh

**Comment by gashcrumb** [comment]
Yep, can reproduce it here with twitter.
