### ISSUE TITLE
Improved UX/UI for action selection when there's a long list of actions to choose from 

### ISSUE THREAD

**Issue by dongniwang** [syndesisio/syndesis#3176]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Saw this in the Concur demo, and this is perhaps common in some other connectors (e.g. Salesforce) we have as well, that the list of actions is presented as a flat list without any grouping. Interacting with the list is a manual process of scrolling, scanning, and reading all the actions. Users can use the filter but they would need to know what exactly to filter on. 

## Expected behavior

Could we somehow group the actions by resources or action types? 
Can we provide some kind of quick way to filter down the list? 

## Screenshot

![image](https://user-images.githubusercontent.com/24943812/43163687-d4864368-8f5c-11e8-8ba2-3169d7007897.png)

Reference: 
https://github.com/syndesisio/syndesis/issues/2673

**Comment by gaughan** [comment]
+1

**Comment by zregvart** [comment]
Filtering and grouping of actions should be possible via tags. Though for Concur we get only `Resources` (the only tag defined in source OpenAPI specifications), so in that case we need to go through all the actions and edit tags manually.

Filtering by name/description should work in all cases.

cc @KurtStam

**Comment by dongniwang** [comment]
@seanforyou23 - Just FYI, this could be something we look into for the autoform. 

cc: @amysueg
