### ISSUE TITLE
Add `initialDelaySeconds` to prometheus liveness/readyness checks

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#3178]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Prometheus deployment config does not specify `initialDelaySeconds` for liveness/readyness checks, on staging this causes premature termination of prometheus pod and it ends up in a crash loop back off.

## Expected behavior

Let prometheus startup before issuing readyness/liveness probes.

**Comment by zregvart** [comment]
@paoloantinori @heiko-braun this I think we need to fix in this sprint.

**Comment by heiko-braun** [comment]
@zregvart While at it, mind to review #3116 as well?
