### ISSUE TITLE
Implement Backup & Restore for Syndesis Infrastructure Operator

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#3194]
Backup as described in syndesisio/syndesis#1119 could be implemented the same way as backup is implemented for the etcd operator

**Comment by rhuss** [comment]
@heiko-braun is periodic backup / restore for Syndesis still a thing ?

**Comment by heiko-braun** [comment]
Probably a question for @gaughan

**Comment by gaughan** [comment]
Still a good idea imho

**Comment by zregvart** [comment]
Backup/restore is implemented [documentation available downstream](https://access.redhat.com/documentation/en-us/red_hat_fuse/7.9/html/installing_and_operating_fuse_online_on_openshift_container_platform/managing-fuse-online-on-ocp_ocp#backing-up-a-fuse-online-environment_manage).
