### ISSUE TITLE
Ability to change Host property of Concur connector

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#3197]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

We ship the Concur connector with a set of predefined properties. Some of these, like OAuth settings, can be changed on the Settings / OAuth client page. Currently we have no way of changing the `Host` property, a property that is used to determine what environment should the integration be targeted at.
So even if the user changes the Token/Authorization URLs to point to the implementation environment, the request at runtime would go to the production environment and error out as the OAuth token is not valid for it.

## Expected behavior

Have the ability to change the `Host` property of Concur connector.

## Screenshot

![ezgif-3-94b5e009b0](https://user-images.githubusercontent.com/1306050/43264875-84d4558a-90e7-11e8-8959-c412e02bcfc5.gif)

**Comment by dongniwang** [comment]
@zregvart 

Just wanted to make sure I understand this clearly - are we talking about a settings page for Connectors? How often do users need to do connector configurations? Is this something specific to Concur or we know this is desirable for other connectors as well?

**Comment by zregvart** [comment]
Well, to be honest, this should be a Connection property, rather than a Connector property. But the way we have the Concur connector now is that you can only change the OAuth settings at the Connector level. So this makes the `Host` property at a setting at Connector level -- otherwise you might setup OAuth URLs to point to _implementation_ environment and Connection host property to point to _production_ environment. (It's also a quirk of Concur to have OAuth apps that don't span multiple environments, as Salesforce, Google and Twitter do).

With that preamble, we only have this need for the Concur connector, we don't have it for any other connector we currently ship. And it seems that it's super specific to how Concur has things setup. In the long run we might find other systems that work this way, then we need to think about OAuth settings at Connection level I think.

I think users will set these properties mostly once, I think users will mirror the environments they use in Syndesis, meaning production Syndesis instance would target production environment of a system, and test Syndesis instance would target test environment of a system.

**Comment by KurtStam** [comment]
@dongniwang I think it's a 'critical bug'. If you can't set the host parameter, then we can't point it to their 'implementation' site, and it will always point to their production site. My vote is to add it to the OAuth screen for the Concur connector as it needs to be in sync with the OAuth URLs and it would be confusing if we require the user to enter this in two separate places.

**Comment by dongniwang** [comment]
Yeah, seems like this is part of the expert workflow? And @zregvart mentioned usually users only need to configure these properties once. Then OAuth screen seems like a good place to perform all these activities. 

With that being said, is it just adding a Host property field? 

Also wondered if we need to improve the Settings / OAuth app mgmt page to account for any similar issues in the future.

**Comment by heiko-braun** [comment]
@zregvart @KurtStam Do you agree on the classification as `feature`, rather than `bug`? Do we need to change the issues and raise the priority?

**Comment by zregvart** [comment]
Can be a considered a bug, sure.

**Comment by zregvart** [comment]
To implement this on the OAuth screen one would need to add a tag to the `host` property of the Concur connector and add that property to the OAuthApp model here:

https://github.com/syndesisio/syndesis/blob/9d4f9de7b229130b63fd65f247c3d38cc8c93c93/app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/setup/OAuthApp.java#L132-L143

It would probably make sense not to display this as `Host` to the user, perhaps `API Endpoint` might make sense and a nicer description. For example:

```json
    "host": {
      "componentProperty": true,
      "defaultValue": "https://us.api.concursolutions.com",
      "deprecated": false,
      "description": "API Endpoint to use to access Concur instance in the form of https://hostname:port. This value depends on the geolocation received from Concur upon registration.",
      "displayName": "API Endpoint",
      "group": "producer",
      "javaType": "java.lang.String",
      "kind": "property",
      "label": "producer",
      "order": 10,
      "required": true,
      "secret": false,
      "tags": [
        "api-host"
      ],
      "type": "string"
    }
```

needs to be modified in https://github.com/syndesisio/syndesis/blob/9d4f9de7b229130b63fd65f247c3d38cc8c93c93/app/server/dao/src/main/resources/META-INF/syndesis/api-connectors/connector-concur.json

The UI should pick up the change and display the newly found property. The only smart thing to do would be to determine where to place `api-host` tag constant, `Credentials` doesn't seem like a good fit.

**Comment by heiko-braun** [comment]
@KurtStam  Could you look into this?

**Comment by KurtStam** [comment]
<img width="1145" alt="screen shot 2018-08-02 at 2 28 24 pm" src="https://user-images.githubusercontent.com/35576/43603299-8d61950e-9660-11e8-9cb5-98745b3bf592.png">
