### ISSUE TITLE
Remove template syndesis-dev.yml and add functionality to operator

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#3202]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

Currently we have two templates which differ only slightly:

* Add a `JAVA_DEBUG=true` env to all deployments
* Add `allowedOrigins: http://localhost:4200, https://localhost:4200, https://${ROUTE_HOSTNAME}` to the client configmap

This should be done by the operator when a `devMode: true` is present in the Syndesis resource.

**Comment by rhuss** [comment]
I think this is still a valid issue and should be considered for a later sprint. But I won't be able to work on this anymore, unassigning myself for now.

**Comment by zregvart** [comment]
No longer relevant.
