### ISSUE TITLE
 "Create integration" button is not visible all the time

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#3204]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

Create integration button on home page is not visible, when there is no integration. I understand that. But when I created an integration and saved it as draft, the button is still not there so there is no option to go straight to creating integration from home page. Only after refreshing the page with F5 the button suddenly appeared.

**Comment by mcada** [comment]
Ignore this one, the button appears when there is at least one integration, I just missed it. Maybe make it bigger :D

**Comment by mcada** [comment]
Ok, now I understand. I did not miss it, it was not there. Changing it to bug.

**Comment by gashcrumb** [comment]
Ah, the button doesn't react appropriately when you delete the last integration from the home page, or create an integration and go directly from the editor to the home page.
