### ISSUE TITLE
integration activity: step name is not shown for data mapper steps

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#3207]
## This is a...

<pre><code>
[ ] Feature request
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Step name is not shown for data mapper steps.

It appears that the data mapper step does not have an id thus the ui cannot correlate the information from the activity to the right step, below an extract fo the integration jsoin that gets copied over the integration pod:

```json

    {
      "action": {
        "descriptor": {
          "inputDataShape": {
            "name": "All preceding outputs",
            "kind": "any"
          },
          "outputDataShape": {
            "name": "Data Mapper (add_lead Parameter)",
            "description": "Parameters of Stored Procedure 'add_lead'",
            "kind": "json-schema",
            "type": "add_lead_IN",
            "specification": "..."
          }
        },
        "actionType": "step"
      },
      "stepKind": "mapper",
      "name": "Data Mapper",
      "configuredProperties": {
        "atlasmapping": "..."
      }
    },
```

## Expected behavior

Each step should have a proper name

## Screenshot

![image](https://user-images.githubusercontent.com/1868933/43322645-872e9228-91af-11e8-9650-cf0ea1086767.png)

**Comment by gashcrumb** [comment]
Seems like one gets posted:

![capture](https://user-images.githubusercontent.com/351660/43329666-0f12e228-918f-11e8-8031-c2e2c83434f7.PNG)

**Comment by gashcrumb** [comment]
This should be fixed with that PR merged, unless there's something else @lburgazzoli ?

**Comment by lburgazzoli** [comment]
let me retest

**Comment by lburgazzoli** [comment]
@gashcrumb fixed
