### ISSUE TITLE
Add the ability to allow untrusted certificates

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#3230]
See also **https://issues.jboss.org/browse/ENTESB-11529**

## This is a...

<pre><code>
[x ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

https://github.com/syndesisio/syndesis/issues/224

https://github.com/syndesisio/syndesis/issues/3000

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11529**
