### ISSUE TITLE
Top 5 integrations is the same as Recent updates

### ISSUE THREAD

**Issue by mmelko** [syndesisio/syndesis#3241]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
What exactly suppose to show 'Top 5 integrations' tab ? Currently it looks like it shows only last updated integration. 

## Expected behavior

"Top 5 Integrations" should be sorted descending by messages processed and limited to 5 integrations.

**Comment by mmelko** [comment]
@heiko-braun @paoloantinori I know this isn't serious in terms of functionality but i believe it will improve overall UX impression.

**Comment by heiko-braun** [comment]
yes, I understand. but if we keep everything on `p1`, than nothing will have priority at the need of the day.  That said, if you think the change in priority is not justified, feel free to add it again.

**Comment by heiko-braun** [comment]
@syndesisio/uxd I think this is a question for UX

**Comment by dongniwang** [comment]
I think the top 5 integration is supposed to show the 5 integrations that have the most uses (messages). But if you only have 5 integrations in total in your environment, the top 5 would just be all the integrations that you have.

**Comment by gashcrumb** [comment]
Ah of course.  I'm not sure if we have this data or not to properly sort the list.

**Comment by dongniwang** [comment]
@gashcrumb - we have use count for API client connectors, can we do that for integrations as well?

**Comment by gashcrumb** [comment]
Just double-checking what we're getting back from the API calls on the dashboard.  There's no field on an integration object that currently tracks messages processed, and the call to fetch metrics to fill in the top row on the dashboard is only a total.

So yeah, first thing needed to fix this one is to expose (somehow) the messages processed per integration so the UI can sort that list properly.

**Comment by mmelko** [comment]
@gashcrumb under integration / metrics there is total messages for particular integration. Is it possible to use that value ?

**Comment by gashcrumb** [comment]
@mmelko yep see it, there's `/metrics/integrations/<id>`.  But then that means up to 5 additional GET requests when hitting the dashboard page then, and it needs to be done before we can display the integration list as it controls how the list is sorted.

**Comment by gashcrumb** [comment]
I think `/metrics/integrations` should also return a map of integration IDs -> message counts, I could then correlate that client-side.  

Even if it's limited to the top 5 integrations since it's all we need would be fine, I can use that to build the data that drives that list.

I'm definitely *not* going to fire off GET requests for every integration in the system to figure out what the top 5 would be client-side :-)

**Comment by dhirajsb** [comment]
@gashcrumb I think we need a new api operations under `/metrics` to return what you are looking for.

**Comment by gashcrumb** [comment]
@dhirajsb really?  We can't just add this info to `/metrics/integrations`?  Isn't this the only spot where this path is used?
