### ISSUE TITLE
Need IRC connector icon

### ISSUE THREAD

**Issue by amysueg** [syndesisio/syndesis#3243]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
IRC connector currently shows as a broken link on the staging site.

## Expected behavior
See a nice IRC icon on the Connection card.

## Screenshot
![screen shot 2018-07-31 at 1 46 40 pm](https://user-images.githubusercontent.com/31700119/43477080-3f88efe2-94c8-11e8-9284-c1a2fac51cd9.png)

**Comment by sjcox-rh** [comment]
Icon for IRC created. PR #3249 created to add the icon to the icon repository here:
https://github.com/syndesisio/syndesis/tree/master/ux/connections_icons

![connectionicons_irc](https://user-images.githubusercontent.com/16257540/43495366-8aa4ddd2-94ec-11e8-966f-ef97a13c359b.png)

Please let me know if there are strong aversions to this one :]

@amysueg @kcbabo @gashcrumb @michael-coker

**Comment by kcbabo** [comment]
Looks awesome!

**Comment by gaughan** [comment]
+1

**Comment by sjcox-rh** [comment]
Great! New icon added to the list and merged :]

Closing.
