### ISSUE TITLE
Access syndesis server API using curl not working

### ISSUE THREAD

**Issue by phantomjinx** [syndesisio/syndesis#3246]
## This is a...

<pre><code>
[ ] Feature request
[*] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Using either firefox or chrome it is possible to directly enter an url pointing to a function in the server REST API and the correct json is returned. It should be possible to do the same on the command line (cli) using curl, eg.

`curl -vvv -X GET -H "Authorization: Bearer $(oc whoami -t)" https://$(oc get route syndesis  --template={{.spec.host}})/api/v1/connections`

This 'fails' (see [gist](https://gist.github.com/phantomjinx/4b12374f551a09e58b136d7bba746992)) due to a lack of redirecting from the oauth proxy. Is this expected behaviour? Can something be done to make it redirect?

Alternatively, the syndesis script provides a cookie which can be used instead of the bearer token, ie.

`curl -vvv -k --cookie $(syndesis dev --cookie --refresh)  "https://$(oc get route syndesis  --template={{.spec.host}})/api/v1/connections"`

This produces the same result as the previous command. The assumption here is this used to work but no longer works.

## Expected behavior

curl is able to fetch the results of any part of the REST API as long as the correct authentication artifacts are provided to it.

**Comment by phantomjinx** [comment]
Result of First curl Command:

curl -vvv -X GET \
     -H "Authorization: Bearer 7nNqaTp6-AuqJrdFqDOqg2_i0C3yguumJmi3UDhRGrc" \
     https://syndesis.birds-of-prey.phantomjinx.org.uk/api/v1/connections

Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 192.168.88.5...
* TCP_NODELAY set
* Connected to syndesis.birds-of-prey.phantomjinx.org.uk (192.168.88.5) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: none
  CApath: none
* loaded libnssckbi.so
* ALPN/NPN, server did not agree to a protocol
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
*       subject: E=p.g.richardson@phantomjinx.co.uk,CN=peregrine.birds-of-prey.phantomjinx.org.uk,OU=Home Network,O=Falcon Computing,L=Pontypool,ST=Wales,C=UK
*       start date: Oct 17 10:00:32 2017 GMT
*       expire date: Oct 27 10:00:32 2018 GMT
*       common name: peregrine.birds-of-prey.phantomjinx.org.uk
*       issuer: E=p.g.richardson@phantomjinx.co.uk,CN=Birds of Prey Intermediate CA,O=Falcon Computing,ST=Wales,C=GB
> GET /api/v1/connections HTTP/1.1
> Host: syndesis.birds-of-prey.phantomjinx.org.uk
> User-Agent: curl/7.53.1
> Accept: */*
> Authorization: Bearer 7nNqaTp6-AuqJrdFqDOqg2_i0C3yguumJmi3UDhRGrc
> 
< HTTP/1.1 302 Found
< Location: https://peregrine.birds-of-prey.phantomjinx.org.uk:8443/oauth/authorize?approval_prompt=force&client_id=system%3Aserviceaccount%3Asyndesis%3Asyndesis-oauth-client&redirect_uri=https%3A%2F%2Fsyndesis.birds-of-prey.phantomjinx.org.uk%2Foauth%2Fcallback&response_type=code&scope=user%3Ainfo+user%3Acheck-access&state=7538af5943a2c4156c2fb2dc280f6227%3A%2Fapi%2Fv1%2Fconnections
< Set-Cookie: _oauth_proxy_csrf=7538af5943a2c4156c2fb2dc280f6227; Path=/; Domain=syndesis.birds-of-prey.phantomjinx.org.uk; Expires=Tue, 07 Aug 2018 16:22:45 GMT; HttpOnly; Secure
< Date: Tue, 31 Jul 2018 16:22:45 GMT
< Content-Length: 417
< Content-Type: text/html; charset=utf-8
< Set-Cookie: b2a2e2613ad00502bbe3dae4fed6f03a=ffb544407e8538da6491e67584473a43; path=/; HttpOnly; Secure
< 
<a href="https://peregrine.birds-of-prey.phantomjinx.org.uk:8443/oauth/authorize?approval_prompt=force&amp;client_id=system%3Aserviceaccount%3Asyndesis%3Asyndesis-oauth-client&amp;redirect_uri=https%3A%2F%2Fsyndesis.birds-of-prey.phantomjinx.org.uk%2Foauth%2Fcallback&amp;response_type=code&amp;scope=user%3Ainfo+user%3Acheck-access&amp;state=7538af5943a2c4156c2fb2dc280f6227%3A%2Fapi%2Fv1%2Fconnections">Found</a>.

* Connection #0 to host syndesis.birds-of-prey.phantomjinx.org.uk left intact

**Comment by zregvart** [comment]
Also related #1233, openshift/oauth-proxy/pull/59 and #967

**Comment by gaughan** [comment]
This is resolved?

**Comment by riccardo-forina** [comment]
A curl copy-pasted from Chrome Dev Tools works. E.g.:

`curl 'https://syndesis.192.168.64.17.nip.io/api/v1/metrics/integrations' -H 'Pragma: no-cache' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-GB,en-US;q=0.9,en;q=0.8' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36' -H 'Accept: application/json, text/plain, */*' -H 'Referer: https://syndesis.192.168.64.17.nip.io/' -H 'Cookie: b2a2e2613ad00502bbe3dae4fed6f03a=7a0d0f559b83fdcb952ce341cd371275; _oauth_proxy=ZGV2ZWxvcGVyQGNsdXN0ZXIubG9jYWx8b3ppVUxxanB6NFRoWFpOUWpGL1BZaHE2ZHhOUWpRMVhsR3kycXRKZThvUnR3S1ZGcGpldzJiaTJyRFdraU0vTGpBSE4wYk5zNVlXQWxNbz18LTYyMTM1NTk2ODAwfA==|1540994757|tLX5YzkzutczwGJkT0KTW6SAlWQ=' -H 'Connection: keep-alive' -H 'SYNDESIS-XSRF-TOKEN: awesome' -H 'Cache-Control: no-cache' --compressed --insecure`

AFAIK oauth-proxy doesn't support requests with a bearer token, so the first snippet will not work.
The second one should, although it doesn't work on my machine (`syndesis dev --cookie --refresh` returns some weird error that I think it's related to my shell).

**Comment by gaughan** [comment]
ok thanks @riccardo-forina
