### ISSUE TITLE
Integration version list MUST include deployment name

### ISSUE THREAD

**Issue by dhirajsb** [syndesisio/syndesis#3247]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Deployments are allowed to have different names from the current integration draft. Hence, deployment spec names should be listed when showing all versions in the integration details page or wherever deployments are listed. 
## Expected behavior

Include versioned name in list of integration deployments. 
## Tasks involved / Steps to Reproduce

1. Create an integration with a name 'xyz'
2. Publish xyz
3. Rename integration to 'pqr'
4. Publish pqr
5. Publish previous version 'xyz'. Now there is no indication that the current deployed version is actually called 'xyz' and not 'pqr' as shown in the draft. This gets worse if the integration is renamed in further versions.

**Comment by gashcrumb** [comment]
> Publish previous version 'xyz'. Now there is no indication that the current deployed version is actually called 'xyz' and not 'pqr' as shown in the draft. This gets worse if the integration is renamed in further versions.

This behavior seems pretty counter intuitive to me.  Why would we track name changes between versions?  It's just metadata.  As a user I'd be pretty surprised if I started an old deployment and it came up using an old name.

**Comment by dhirajsb** [comment]
I talked to @chirino and it turns out by design, once deployed the name is owned by the version. That name is never exposed to end users per say, it's only used for OpenShift resources right now. 
But if it's exposed as requested here, users can see what the integration was called in that particular version. And it would help when debugging OpenShift resources. 

The integration's _name_ is really the name of the _draft_. Once it's deployed, it's locked into the deployment version. Syndesis is still able to relate the integration as a whole to it's currently deployed version and state in openshift resources through labels. 

It does make _older_ names unavailable as you said, but IMHO it's not a bad thing. Users should _think_ and use semantically meaningful names anyway. :) 
Note that deleted integrations are excluded, so one can _reclaim_ old unused names.

**Comment by gashcrumb** [comment]
I personally don't agree that we use integration names as anything more than a label/identifier, i.e. it shouldn't be used for resource names that have constraints that impose arbitrary restrictions on what the user can use to name their things in the app.  And honestly, versioning the name still doesn't make sense to me.

**Comment by zregvart** [comment]
I think we should treat name as an attribute not an identifier, code that uses name as an identifier (k8s objects, export) should be changed to use something else (random names like docker container names work for me).
