### ISSUE TITLE
Errors in db-maintenance events log

### ISSUE THREAD

**Issue by mmelko** [syndesisio/syndesis#3252]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
I'm running soak test on OSO Pro and I'm seeing following errors in db-maintenance pod events after couple of hours: 
`
Error: Error response from daemon: create 29a8108185585a4b7ce779cf359083624733438f85a9fc634f32966784d64d1f: error while creating volume path '/var/lib/docker/volumes/29a8108185585a4b7ce779cf359083624733438f85a9fc634f32966784d64d1f/_data': mkdir /var/lib/docker/volumes
/29a8108185585a4b7ce779cf359083624733438f85a9fc634f32966784d64d1f: permission denied
`

![screen shot 2018-08-01 at 10 06 09](https://user-images.githubusercontent.com/6814482/43509375-cbb603ec-9572-11e8-9a96-e7036ccfd06a.png)

I believe due to this I cannot see activities after couple of hours (~200 000 total messages):
![screen shot 2018-08-01 at 10 12 04](https://user-images.githubusercontent.com/6814482/43509741-c0636ac4-9573-11e8-8daf-7bc8e4a8a65c.png)

**Comment by zregvart** [comment]
Not sure what we can do here to be honest.

**Comment by rhuss** [comment]
It really looks like an openshift internal error has it has problems to create a Docker volume.

**Comment by mmelko** [comment]
I can't get any meaningful log/messages. It's failing in couple of secons. Here is list of events:

4:01:07 PM | Normal | Scheduled | Successfully assigned syndesis-db-maintenance-1533132060-r5lk7 to ip-172-31-56-79.ec2.internal
-- | -- | -- | --
4:01:07 PM | Normal | Successful Mount Volume | MountVolume.SetUp succeeded for volume "syndesis-db-maintenance-script"
4:01:07 PM | Normal | Successful Mount Volume | MountVolume.SetUp succeeded for volume "default-token-hs7ms"
4:01:10 PM | Normal | Pulling | pulling image "centos/postgresql-95-centos7"
4:01:12 PM | Normal | Pulled | Successfully pulled image "centos/postgresql-95-centos7"
4:01:12 PM | Warning | Failed | Error:  Error response from daemon: create  7fe01eb7482ba72e17c866ba2e21115909517f64385b7d4ecc804fa12b6e077d: error  while creating volume path  '/var/lib/docker/volumes/7fe01eb7482ba72e17c866ba2e21115909517f64385b7d4ecc804fa12b6e077d/_data':  mkdir  /var/lib/docker/volumes/7fe01eb7482ba72e17c866ba2e21115909517f64385b7d4ecc804fa12b6e077d:  permission denied
4:01:53 PM | Normal | Sandbox Changed | Pod sandbox changed, it will be killed and re-created.         12 times in the last minute

I will try to get in touch with openshift team and we will see

**Comment by zregvart** [comment]
This [issue](https://bugzilla.redhat.com/show_bug.cgi?id=1584386) is discussing something about a `VOLUME` in `Dockerfile` that needs to be overridden.

Remembering that in CronJobs we can't use image streams, perhaps this is the root cause?

**Comment by zregvart** [comment]
@mmelko just to double check, this environment has `syndesis-db-maintenance-script` ConfigMap?

**Comment by mmelko** [comment]
@zregvart yep. It's deployed from yesterday's master.

**Comment by rhuss** [comment]
Ah, right. You can't use a Docker image with a volume. That's an openshift restriction on Online.

**Comment by rhuss** [comment]
Which image is it ?

**Comment by zregvart** [comment]
[This one](https://hub.docker.com/r/centos/postgresql-95-centos7/), here is the Dockerfile:

https://github.com/sclorg/postgresql-container/blob/673cd38014d195149d020c633f192e230602b59e/src/Dockerfile#L90

My current idea is to mount an emptydir to `/var/lib/pgsql/data`, would that work?

**Comment by rhuss** [comment]
Nope, that wont work either. You just can't use builds with a `VOLUME` directive on OpenShift Online in the Dockerfile. afaik.

**Comment by zregvart** [comment]
This sucks, let me try to find an image with `psql` CLI in it without any volumes. Any tricks on referencing the image stream image name from the templates?

**Comment by heiko-braun** [comment]
Just to confirm, this is the root cause?

>  You can't use a Docker image with a volume. That's an openshift restriction on Online.

**Comment by rhuss** [comment]
Yes, it is. The problem is, that this image is *not* the official image used by OpenShift in its stock Postgresql image. As we are using a CronJob we cant use an ImageStream as reference as CronJob is a Kubernetes concept that does not know about ImageStream (that's btw one of the reasons why both `Deployment` (image only) and `DeploymentConfig` (also imagestreams) still exist.

**Comment by rhuss** [comment]
For reference: https://docs.openshift.com/online/creating_images/guidelines.html#openshift-specific-guidelines , first section "Privileges and Volume Builds"

**Comment by mmelko** [comment]
Hi @zregvart @rhuss I've tried my soak scenario over the weekend (without #3299) on OSO pro. I have changed image unsed in cronjob and also set cronjob to run more often.  

After ~ 6hours activities stopped being tracked in some integrations. My scenario contains 6 integrations (3 of them have 4-5 steps so activities are bigger) with ~3.4 messages/per second. 

I will also verify tomorrow with this fix. If I should use less messages please let me know, but I believe 3 messages per second isn't that big load.
