### ISSUE TITLE
HTTP Consumer fails to follow redirect.

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis#3254]
## This is a...

<pre><code>
[] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

This is actually borderline between a bug and a feature.
Currently, HTTP Consumer, doesn't follow redirects.
If you define a connection using the default value "www.redhat.com" and path "/", you hit an endpoint that forces a 302 redirect, and this fails this way:

<details>
  <summary><b>Click to expand</b></summary>
<pre><code>
i-paolo-1-dldhn i-paolo org.apache.camel.http.common.HttpOperationFailedException: HTTP operation failed invoking http://www.redhat.com/ with statusCode: 301, redirectLocation: https://www.redhat.com/
i-paolo-1-dldhn i-paolo 	at org.apache.camel.component.http4.HttpProducer.populateHttpOperationFailedException(HttpProducer.java:310) ~[camel-http4-2.21.0.fuse-000112-redhat-3.jar!/:2.21.0.fuse-000112-redhat-3]
i-paolo-1-dldhn i-paolo 	at org.apache.camel.component.http4.HttpProducer.process(HttpProducer.java:207) ~[camel-http4-2.21.0.fuse-000112-redhat-3.jar!/:2.21.0.fuse-000112-redhat-3]
i-paolo-1-dldhn i-paolo 	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61) ~[camel-core-2.21.0.fuse-000112-redhat-3.jar!/:2.21.0.fuse-000112-redhat-3]
i-paolo-1-dldhn i-paolo 	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.21.0.fuse-000112-redhat-3.jar!/:2.21.0.fuse-000112-redhat-3]
i-paolo-1-dldhn i-paolo 	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.21.0.fuse-000112-redhat-3.jar!/:2.21.0.fuse-000112-redhat-3]
i-paolo-1-dldhn i-paolo 	at io.syndesis.integration.component.proxy.ComponentProxyProducer.process(ComponentProxyProducer.java:44) ~[integration-component-proxy-1.3.12.fuse-000001-redhat-2.jar!/:1.3.12.fuse-000001-redhat-2]
i-paolo-1-dldhn i-paolo 	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:148) ~[camel-core-2.21.0.fuse-000112-redhat-3.jar!/:2.21.0.fuse-000112-redhat-3]
i-paolo-1-dldhn i-paolo 	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) [camel-core-2.21.0.fuse-000112-redhat-3.jar!/:2.21.0.fuse-000112-redhat-3]
i-paolo-1-dldhn i-paolo 	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) [camel-core-2.21.0.fuse-000112-redhat-3.jar!/:2.21.0.fuse-000112-redhat-3]
i-paolo-1-dldhn i-paolo 	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-000112-redhat-3.jar!/:2.21.0.fuse-000112-redhat-3]
i-paolo-1-dldhn i-paolo 	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.21.0.fuse-000112-redhat-3.jar!/:2.21.0.fuse-000112-redhat-3]
i-paolo-1-dldhn i-paolo 	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.21.0.fuse-000112-redhat-3.jar!/:2.21.0.fuse-000112-redhat-3]
i-paolo-1-dldhn i-paolo 	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) [camel-core-2.21.0.fuse-000112-redhat-3.jar!/:2.21.0.fuse-000112-redhat-3]
i-paolo-1-dldhn i-paolo 	at io.syndesis.integration.runtime.logging.ActivityTrackingInterceptStrategy$EventProcessor.process(ActivityTrackingInterceptStrategy.java:77) [integration-runtime-1.3.12.fuse-000001-redhat-2.jar!/:1.3.12.fuse-000001-redhat-2]
i-paolo-1-dldhn i-paolo 	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) [camel-core-2.21.0.fuse-000112-redhat-3.jar!/:2.21.0.fuse-000112-redhat-3]
i-paolo-1-dldhn i-paolo 	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) [camel-core-2.21.0.fuse-000112-redhat-3.jar!/:2.21.0.fuse-000112-redhat-3]
i-paolo-1-dldhn i-paolo 	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-000112-redhat-3.jar!/:2.21.0.fuse-000112-redhat-3]
i-paolo-1-dldhn i-paolo 	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.21.0.fuse-000112-redhat-3.jar!/:2.21.0.fuse-000112-redhat-3]
i-paolo-1-dldhn i-paolo 	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.21.0.fuse-000112-redhat-3.jar!/:2.21.0.fuse-000112-redhat-3]
i-paolo-1-dldhn i-paolo 	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-000112-redhat-3.jar!/:2.21.0.fuse-000112-redhat-3]
i-paolo-1-dldhn i-paolo 	at org.apache.camel.component.timer.TimerConsumer.sendTimerExchange(TimerConsumer.java:197) [camel-core-2.21.0.fuse-000112-redhat-3.jar!/:2.21.0.fuse-000112-redhat-3]
i-paolo-1-dldhn i-paolo 	at org.apache.camel.component.timer.TimerConsumer$1.run(TimerConsumer.java:79) [camel-core-2.21.0.fuse-000112-redhat-3.jar!/:2.21.0.fuse-000112-redhat-3]
i-paolo-1-dldhn i-paolo 	at java.util.TimerThread.mainLoop(Timer.java:555) [na:1.8.0_171]
i-paolo-1-dldhn i-paolo 	at java.util.TimerThread.run(Timer.java:505) [na:1.8.0_171]
i-paolo-1-dldhn i-paolo {"exchange":"i-LIlirTmXESPE5W6P_Zpz","step":"-LIlhf8cWV3WrQkyc1aG","id":"i-LIlirt-XESPE5W6P_Zqz","duration":803113459,"failure":"org.apache.camel.http.common.HttpOperationFailedException: HTTP operation failed invoking http://www.redhat.com/ with statusCode: 301, redirectLocation: https://www.redhat.com/\n\tat org.apache.camel.component.http4.HttpProducer.populateHttpOperationFailedException(HttpProducer.java:310)\n\tat org.apache.camel.component.http4.HttpProducer.process(HttpProducer.java:207)\n\tat org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61)\n\tat org.apache.camel.processor.Pipeline.process(Pipeline.java:138)\n\tat org.apache.camel.processor.Pipeline.process(Pipeline.java:101)\n\tat io.syndesis.integration.component.proxy.ComponentProxyProducer.process(ComponentProxyProducer.java:44)\n\tat org.apache.camel.processor.SendProcessor.process(SendProcessor.java:148)\n\tat org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110)\n\tat org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)\n\tat org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)\n\tat org.apache.camel.processor.Pipeline.process(Pipeline.java:138)\n\tat org.apache.camel.processor.Pipeline.process(Pipeline.java:101)\n\tat org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110)\n\tat io.syndesis.integration.runtime.logging.ActivityTrackingInterceptStrategy$EventProcessor.process(ActivityTrackingInterceptStrategy.java:77)\n\tat org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110)\n\tat org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)\n\tat org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)\n\tat org.apache.camel.processor.Pipeline.process(Pipeline.java:138)\n\tat org.apache.camel.processor.Pipeline.process(Pipeline.java:101)\n\tat org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)\n\tat org.apache.camel.component.timer.TimerConsumer.sendTimerExchange(TimerConsumer.java:197)\n\tat org.apache.camel.component.timer.TimerConsumer$1.run(TimerConsumer.java:79)\n\tat java.util.TimerThread.mainLoop(Timer.java:555)\n\tat java.util.TimerThread.run(Timer.java:505)\n"}
i-paolo-1-dldhn i-paolo {"exchange":"i-LIlirTmXESPE5W6P_Zpz","status":"done","failed":true}
i-paolo-1-dldhn i-paolo 2018-07-31 19:05:54.807  WARN 1 --- [r://integration] o.a.camel.component.timer.TimerConsumer  : Error processing exchange. Exchange[i-LIlirTmXESPE5W6P_Zpz]. Caused by: [org.apache.camel.http.common.HttpOperationFailedException - HTTP operation failed invoking http://www.redhat.com/ with statusCode: 301, redirectLocation: https://www.redhat.com/]

</code></pre>
</details>

## Expected behavior
Either to support redirect by default, or to expose the configuration or to change the suggested example.

Tested on iPaaS 7.0.1

**Comment by paoloantinori** [comment]
@oscerd you have some familiarity with this. What's your opinion?

**Comment by oscerd** [comment]
Camel will treat a 300-399 code as

_Response code is in the range 300..399, Camel regards it as a redirection response and will throw a HttpOperationFailedException with the information._

**Comment by oscerd** [comment]
I'll check the code to confirm.

**Comment by oscerd** [comment]
We can enable the follow redirection on the client with the parameter

httpClient.redirectsEnabled=true

**Comment by oscerd** [comment]
tag this for 7.2 and I'll dig into it.

**Comment by oscerd** [comment]
Do we want this as an option, or do we want to set this as always true?

**Comment by paoloantinori** [comment]
I don't have a strong opinion on this. I would say that having the option is probably good, so that advanced users can use it.

On the other side not even `curl` defaults to follow redirects, so I'm not sure what's a reasonable sensible default.

**Comment by oscerd** [comment]
ok

**Comment by oscerd** [comment]
ping @paoloantinori @heiko-braun @gaughan

**Comment by heiko-braun** [comment]
@oscerd It's a bug. I've added it to the current sprint. Feel free to fix it.

**Comment by oscerd** [comment]
Thanks.
