### ISSUE TITLE
Calling syndesis build twice produces duplicate resource error

### ISSUE THREAD

**Issue by phantomjinx** [syndesisio/syndesis#3258]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[*] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Calling `syndesis build` twice in succession without a `-c` or 'mvn clean' inbetween causes a maven error in common-util on the second occasion and build failure.

[INFO] Building jar: /home/phantomjinx/programming/java/syndesis/app/common/util/target/common-util-1.4-SNAPSHOT.jar
<snip> 
[INFO] --- duplicate-finder-maven-plugin:1.2.1:check (default) @ common-util ---
[INFO] Checking compile classpath
[INFO] Checking runtime classpath
[INFO] Checking test classpath
[WARNING] Found duplicate and different classes in [/home/phantomjinx/programming/java/syndesis/app/common/util/target/classes, /home/phantomjinx/programming/java/syndesis/app/common/util/target/test-classes]:
[WARNING]   io.syndesis.common.util.immutable.ImmutableTestValue
[WARNING] Found duplicate classes/resources in test classpath.
[INFO] ------------------------------------------------------------------------
<snip>
[ERROR] Failed to execute goal org.basepom.maven:duplicate-finder-maven-plugin:1.2.1:check (default) on project common-util: Found duplicate classes/resources! -> [Help 1]
[ERROR] 
<snip>

## Expected behavior

Second maven build should run like the first and be quicker since most of the compiling has already been done. A clean should not be required each time a build is executed.

## Tasks involved / Steps to Reproduce

1. syndesis build ...
2. syndesis build ... (no clean switch)

**Comment by zregvart** [comment]
@phantomjinx perhaps you running this with IDE open and set to auto-build, I've seen this issue in that context?

**Comment by phantomjinx** [comment]
@zregvart 
Confirmed. The auto-build in Eclipse interferes with the analysis of the duplicate-finder-maven-plugin. By calling maven with the skip-checks profile, compilation succeeds.
