### ISSUE TITLE
Remove declared types currently not in use in the codebase

### ISSUE THREAD

**Issue by deeleman** [syndesisio/syndesis#326]
One of the major sources of technical debt is the existence of declared type tokens not in use. This generates an undesired additional overhead when bundling the application and an increased filesize of the packaged application.

Also, it invalidates any attempt to automate unused types/variables/tokens detection on the code. The following declared variables/imported tokens can be safely removed from the files enlisted below:

- [ ] /syndesis/ui/src/app/common/modal/modal.service.ts (1,22): 'OnInit'
- [ ] /syndesis/ui/src/app/common/modal/modal.service.ts (1,30): 'ViewChild'
- [ ] /syndesis/ui/src/app/common/modal/modal.service.ts (3,10): 'BsModalRef'
- [ ] /syndesis/ui/src/app/common/user.service.ts (1,22): 'Input'
- [ ] /syndesis/ui/src/app/common/ui-patternfly/notification-service.ts (3,3): 'NotificationType'
- [ ] /syndesis/ui/src/app/common/editable/editable.component.ts (2,3): 'Component'
- [ ] /syndesis/ui/src/app/common/modal/modal.component.ts (7,3): 'Output'
- [ ] /syndesis/ui/src/app/common/common.module.ts (5,10): 'NotificationModule'
- [ ] /syndesis/ui/src/app/store/entity/events.service.ts (3,10): 'Subscription'
- [ ] /syndesis/ui/src/app/store/entity/entity.store.ts (2,10): 'Observer'
- [ ] /syndesis/ui/src/app/store/connector/connector.service.ts (3,10): 'Subscription'
- [ ] /syndesis/ui/src/app/store/connector/connector.service.ts (49,19): 'newCookie'
- [ ] /syndesis/ui/src/app/store/integration-support.service.ts (5,10): 'ErrorObservable'
- [ ] /syndesis/ui/src/app/store/integration-support.service.ts (10,10): 'log'
- [ ] /syndesis/ui/src/app/store/integration-support.service.ts (10,15): 'getCategory'
- [ ] /syndesis/ui/src/app/store/step/step.store.ts (2,10): 'Connection'
- [ ] /syndesis/ui/src/app/store/step/step.store.ts (2,22): 'Action'
- [ ] /syndesis/ui/src/app/store/step/step.store.ts (2,36): 'Steps'
- [ ] /syndesis/ui/src/app/store/step/step.store.ts (2,43): 'TypeFactory'
- [ ] /syndesis/ui/src/app/app.module.ts (4,3): 'NgZone'
- [ ] /syndesis/ui/src/app/app.module.ts (10,10): 'BrowserAnimationsModule'
- [ ] /syndesis/ui/src/app/config.service.spec.ts (3,19): 'async'
- [ ] /syndesis/ui/src/app/common/user.service.spec.ts (3,19): 'async'
- [ ] /syndesis/ui/src/app/common/loading/loading.component.spec.ts (3,10): 'By'
- [ ] /syndesis/ui/src/app/common/loading/loading.component.spec.ts (4,10): 'DebugElement'
- [ ] /syndesis/ui/src/app/common/ui-patternfly/list-toolbar/list-toolbar.component.ts (3,3): 'EventEmitter'
- [ ] /syndesis/ui/src/app/common/ui-patternfly/list-toolbar/list-toolbar.component.ts (5,3): 'Output'
- [ ] /syndesis/ui/src/app/common/ui-patternfly/list-toolbar/list-toolbar.component.ts (16,3): 'ActionConfig'
- [ ] /syndesis/ui/src/app/common/ui-patternfly/list-toolbar/list-toolbar.component.ts (21,3): 'SortField'
- [ ] /syndesis/ui/src/app/connections/create-page/current-connection.ts (7,22): 'Connector'
- [ ] /syndesis/ui/src/app/connections/create-page/current-connection.ts (7,33): 'Connections'
- [ ] /syndesis/ui/src/app/connections/create-page/current-connection.ts (7,46): 'Connectors'
- [ ] /syndesis/ui/src/app/connections/create-page/current-connection.ts (140,11): 'connectorId'
- [ ] /syndesis/ui/src/app/connections/create-page/create-page.component.ts (13,7): 'category'
- [ ] /syndesis/ui/src/app/connections/create-page/create-page.component.ts (47,11): 'connection'
- [ ] /syndesis/ui/src/app/connections/create-page/cancel.component.ts (2,34): 'RouterStateSnapshot'
- [ ] /syndesis/ui/src/app/connections/list-page/list-page.component.ts (2,10): 'ActivatedRoute'
- [ ] /syndesis/ui/src/app/connections/list-page/list-page.component.ts (2,26): 'Params'
- [ ] /syndesis/ui/src/app/connections/list-page/list-page.component.ts (7,10): 'log'
- [ ] /syndesis/ui/src/app/connections/list-page/list-page.component.ts (11,7): 'category'
- [ ] /syndesis/ui/src/app/connections/list/list.component.ts (7,3): 'ViewChild'
- [ ] /syndesis/ui/src/app/connections/detail-page/breadcrumb.component.ts (1,21): 'Input'
- [ ] /syndesis/ui/src/app/connections/detail-page/breadcrumb.component.ts (2,10): 'Connection'
- [ ] /syndesis/ui/src/app/connections/detail-page/info.component.ts (2,10): 'ActivatedRoute'
- [ ] /syndesis/ui/src/app/connections/detail-page/info.component.ts (3,10): 'Observable'
- [ ] /syndesis/ui/src/app/connections/detail-page/info.component.ts (4,10): 'Subscription'
- [ ] /syndesis/ui/src/app/connections/detail-page/info.component.ts (60,13): Property 'configurationService'
- [ ] /syndesis/ui/src/app/connections/create-page/configure-fields/configure-fields.component.spec.ts (5,10): 'ModalService'
- [ ] /syndesis/ui/src/app/connections/list/list.component.spec.ts (3,10): 'By'
- [ ] /syndesis/ui/src/app/connections/list/list.component.spec.ts (5,10): 'DebugElement'
- [ ] /syndesis/ui/src/app/dashboard/connections.component.ts (7,3): 'ViewChild'
- [ ] /syndesis/ui/src/app/dashboard/connections.component.ts (13,10): 'ConnectionStore'
- [ ] /syndesis/ui/src/app/integrations/list/list.component.ts (1,44): 'ViewChild'
- [ ] /syndesis/ui/src/app/integrations/list/list.component.ts (3,10): 'ModalDirective'
- [ ] /syndesis/ui/src/app/integrations/list/list.component.ts (4,10): 'Subscription'
- [ ] /syndesis/ui/src/app/integrations/list/list.component.ts (12,3): 'Notification'
- [ ] /syndesis/ui/src/app/integrations/list/list.component.ts (13,3): 'NotificationType'
- [ ] /syndesis/ui/src/app/integrations/list/list.component.ts (20,10): 'log'
- [ ] /syndesis/ui/src/app/integrations/list/list.component.ts (20,15): 'getCategory'
- [ ] /syndesis/ui/src/app/dashboard/emptystate.component.ts (5,10): 'log'
- [ ] /syndesis/ui/src/app/dashboard/emptystate.component.ts (12,7): 'category'
- [ ] /syndesis/ui/src/app/dashboard/integrations.component.ts (1,28): 'ViewChild'
- [ ] /syndesis/ui/src/app/dashboard/integrations.component.ts (2,10): 'Observable'
- [ ] /syndesis/ui/src/app/dashboard/integrations.component.ts (8,10): 'ConnectionStore'
- [ ] /syndesis/ui/src/app/dashboard/integrations.component.ts (9,10): 'IntegrationStore'
- [ ] /syndesis/ui/src/app/dashboard/integrations.component.ts (11,7): 'category'
- [ ] /syndesis/ui/src/app/integrations/detail-page/detail.component.ts (9,42): 'UrlSegment'
- [ ] /syndesis/ui/src/app/integrations/detail-page/detail.component.ts (14,29): 'Connection'
- [ ] /syndesis/ui/src/app/integrations/detail-page/detail.component.ts (14,41): 'Action'
- [ ] /syndesis/ui/src/app/integrations/edit-page/current-flow.service.ts (6,3): 'Action'
- [ ] /syndesis/ui/src/app/integrations/edit-page/current-flow.service.ts (316,15): 'action'
- [ ] /syndesis/ui/src/app/integrations/edit-page/child-aware-page.ts (1,10): 'Subscription'
- [ ] /syndesis/ui/src/app/integrations/edit-page/child-aware-page.ts (2,26): 'Params'
- [ ] /syndesis/ui/src/app/integrations/edit-page/edit-page.component.ts (10,10): 'log'
- [ ] /syndesis/ui/src/app/integrations/edit-page/edit-page.component.ts (13,7): 'category'
- [ ] /syndesis/ui/src/app/integrations/edit-page/flow-page.ts (3,26): 'Params'
- [ ] /syndesis/ui/src/app/integrations/edit-page/flow-page.ts (5,23): 'Step'
- [ ] /syndesis/ui/src/app/integrations/edit-page/flow-page.ts (5,29): 'TypeFactory'
- [ ] /syndesis/ui/src/app/integrations/edit-page/save-or-add-step/save-or-add-step.component.ts (2,26): 'Params'
- [ ] /syndesis/ui/src/app/integrations/edit-page/save-or-add-step/save-or-add-step.component.ts (3,10): 'Observable'
- [ ] /syndesis/ui/src/app/integrations/edit-page/save-or-add-step/save-or-add-step.component.ts (4,10): 'Subscription'
- [ ] /syndesis/ui/src/app/integrations/edit-page/save-or-add-step/save-or-add-step.component.ts (9,23): 'Step'
- [ ] /syndesis/ui/src/app/integrations/edit-page/save-or-add-step/save-or-add-step.component.ts (9,29): 'TypeFactory'
- [ ] /syndesis/ui/src/app/integrations/edit-page/save-or-add-step/save-or-add-step.component.ts (10,10): 'log'
- [ ] /syndesis/ui/src/app/integrations/edit-page/save-or-add-step/save-or-add-step.component.ts (12,7): 'category'
- [ ] /syndesis/ui/src/app/integrations/edit-page/step-select/step-select.component.ts (5,31): 'StepKinds'
- [ ] /syndesis/ui/src/app/integrations/edit-page/step-select/step-select.component.ts (8,23): 'TypeFactory'
- [ ] /syndesis/ui/src/app/integrations/edit-page/step-select/step-select.component.ts (9,15): 'getCategory'
- [ ] /syndesis/ui/src/app/integrations/edit-page/step-select/step-visible.pipe.ts (1,10): 'Component'
- [ ] /syndesis/ui/src/app/integrations/edit-page/step-select/step-visible.pipe.ts (2,10): 'StepStore'
- [ ] /syndesis/ui/src/app/integrations/edit-page/step-select/step-visible.pipe.ts (2,31): 'StepKinds'
- [ ] /syndesis/ui/src/app/integrations/edit-page/step-select/step-visible.pipe.ts (4,10): 'Step'
- [ ] /syndesis/ui/src/app/integrations/edit-page/step-select/step-visible.pipe.ts (4,16): 'Steps'
- [ ] /syndesis/ui/src/app/integrations/edit-page/step-select/step-visible.pipe.ts (4,23): 'TypeFactory'
- [ ] /syndesis/ui/src/app/integrations/edit-page/step-configure/step-configure.component.ts (3,3): 'Input'
- [ ] /syndesis/ui/src/app/integrations/edit-page/step-configure/step-configure.component.ts (24,10): 'Action'
- [ ] /syndesis/ui/src/app/integrations/edit-page/step-configure/data-mapper/data-mapper-host.component.ts (8,26): 'Params'
- [ ] /syndesis/ui/src/app/integrations/edit-page/step-configure/data-mapper/data-mapper-host.component.ts (15,3): 'MappingModel'
- [ ] /syndesis/ui/src/app/integrations/edit-page/step-configure/data-mapper/data-mapper-host.component.ts (27,23): 'FlowEvent'
- [ ] /syndesis/ui/src/app/integrations/edit-page/step-configure/data-mapper/data-mapper-host.component.ts (30,27): 'TypeFactory'
- [ ] /syndesis/ui/src/app/integrations/edit-page/step-configure/filter-steps/basic-filter.model.ts (12,3): 'Rule'
- [ ] /syndesis/ui/src/app/integrations/edit-page/step-configure/filter-steps/basic-filter.component.ts (18,23): 'FlowEvent'
- [ ] /syndesis/ui/src/app/integrations/edit-page/step-configure/filter-steps/basic-filter.component.ts (23,15): 'getCategory'
- [ ] /syndesis/ui/src/app/integrations/edit-page/list-actions/list-actions.component.ts (2,10): 'Observable'
- [ ] /syndesis/ui/src/app/integrations/edit-page/common/cancel-add-step.component.ts (2,34): 'ParamMap'
- [ ] /syndesis/ui/src/app/integrations/list-page/list-page.component.ts (49,13): Property 'integrationSupportService'
- [ ] /syndesis/ui/src/app/integrations/edit-page/flow-view/flow-view.component.ts (4,3): 'Input'
- [ ] /syndesis/ui/src/app/integrations/edit-page/flow-view/flow-view.component.ts (11,26): 'Params'
- [ ] /syndesis/ui/src/app/integrations/edit-page/flow-view/flow-view.component.ts (12,10): 'Observable'
- [ ] /syndesis/ui/src/app/integrations/edit-page/flow-view/flow-view.component.ts (16,10): 'log'
- [ ] /syndesis/ui/src/app/integrations/edit-page/flow-view/flow-view.component.ts (18,23): 'Step'
- [ ] /syndesis/ui/src/app/integrations/edit-page/flow-view/flow-view.component.ts (18,29): 'TypeFactory'
- [ ] /syndesis/ui/src/app/integrations/edit-page/flow-view/flow-view.component.ts (21,7): 'category'
- [ ] /syndesis/ui/src/app/integrations/edit-page/flow-view/flow-view-step.component.ts (2,26): 'Params'
- [ ] /syndesis/ui/src/app/integrations/edit-page/flow-view/flow-view-step.component.ts (2,42): 'UrlSegment'
- [ ] /syndesis/ui/src/app/integrations/edit-page/flow-view/flow-view-step.component.ts (3,10): 'Observable'
- [ ] /syndesis/ui/src/app/integrations/edit-page/flow-view/flow-view-step.component.ts (4,10): 'Subscription'
- [ ] /syndesis/ui/src/app/integrations/edit-page/flow-view/flow-view-step.component.ts (9,10): 'log'
- [ ] /syndesis/ui/src/app/integrations/edit-page/flow-view/flow-view-step.component.ts (10,23): 'FlowEvent'
- [ ] /syndesis/ui/src/app/integrations/edit-page/flow-view/flow-view-step.component.ts (11,10): 'Integration'
- [ ] /syndesis/ui/src/app/integrations/edit-page/flow-view/flow-view-step.component.ts (14,7): 'category'
- [ ] /syndesis/ui/src/app/integrations/edit-page/current-flow.service.spec.ts (2,19): 'async'
- [ ] /syndesis/ui/src/app/integrations/edit-page/current-flow.service.spec.ts (7,23): 'FlowEvent'
- [ ] /syndesis/ui/src/app/integrations/edit-page/current-flow.service.spec.ts (11,3): 'Connection'
- [ ] /syndesis/ui/src/app/integrations/edit-page/current-flow.service.spec.ts (15,3): 'Action'
- [ ] /syndesis/ui/src/app/integrations/edit-page/common/cancel-add-step.component.spec.ts (2,10): 'ActivatedRoute'
- [ ] /syndesis/ui/src/app/integrations/edit-page/common/cancel-add-step.component.spec.ts (2,26): 'Router'
- [ ] /syndesis/ui/src/app/integrations/edit-page/common/cancel-add-step.component.spec.ts (3,10): 'CurrentFlow'
- [ ] /syndesis/ui/src/app/settings/settings-root.component.ts (10,23): Property 'route'
- [ ] /syndesis/ui/src/app/settings/settings-root.component.ts (10,54): Property 'router'
- [ ] /syndesis/ui/src/app/settings/oauth-apps/oauth-apps.component.ts (1,29): 'ViewChild'
- [ ] /syndesis/ui/src/app/settings/oauth-apps/oauth-app-form.component.ts (4,3): 'EventEmitter'
- [ ] /syndesis/ui/src/app/settings/oauth-apps/oauth-app-form.component.ts (6,3): 'Output'
- [ ] /syndesis/ui/src/app/settings/oauth-apps/oauth-app-form.component.ts (9,10): 'OAuthApp'
- [ ] /syndesis/ui/src/app/settings/oauth-apps/oauth-app-form.component.ts (9,20): 'OAuthApps'
- [ ] /syndesis/ui/src/app/settings/oauth-apps/oauth-app-form.component.ts (16,3): 'DynamicInputModel'
- [ ] /syndesis/ui/src/app/settings/oauth-apps/oauth-app-modal.component.ts (6,10): 'OAuthApp'
- [ ] /syndesis/ui/src/app/settings/oauth-apps/oauth-app-modal.component.ts (6,20): 'OAuthApps'
- [ ] /syndesis/ui/src/app/templates/list-toolbar/list-toolbar.component.spec.ts (3,10): 'By'
- [ ] /syndesis/ui/src/app/templates/list-toolbar/list-toolbar.component.spec.ts (4,10): 'DebugElement'

**Comment by deeleman** [comment]
I do not seem to have privileges to label/tag this issue :_(

**Comment by gashcrumb** [comment]
Unfortunately this has gone stale since all the file paths have been refactored.  I think we need to rely on the boy scout principal for this one vs. someone getting the time to go through and validate this list.
