### ISSUE TITLE
Apicurio Editor: Steps not getting updated with edited changes

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis#3264]
## This is a...
<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
When a specification is updated via the Apicurio editor, the subsequent steps are not getting updated. The final POST request to the API includes the correct, updated version.

## Expected behavior
The Review Actions, Authentication, and Review/Edit Connector Details steps should be using the latest changes for the specification.

## Tasks involved / Steps to Reproduce
1. Customizations > API Client Connector
2. Upload a Swagger/OpenAPI specification file.
3. Click Review/Edit in the Review step.
4. Make changes in the Apicurio editor.
5. Press 'Save'. See that changes are not reflected in the aforementioned steps.

**Comment by zregvart** [comment]
I'm guessing we need to `POST` to `/api/v1/connectors/custom/info` after editing and update the UI state.

**Comment by kahboom** [comment]
Closed with @riccardo-forina 's help on #3278.
