### ISSUE TITLE
Add a card for Create connection

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#3267]
## This is a...

<pre><code>
[ x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

As a citizen integrator, when I click on the Connections page I would like to see a card for Create connection instead on the button we have now.
The background of this card could be a screengrab of all the possible options I have for new connectors.
The card could be similar to the card that exists on the new integration page:
![image](https://user-images.githubusercontent.com/674767/43545381-bd58ffb2-95a3-11e8-9015-d3243e446b59.png)

**Comment by dongniwang** [comment]
Reference: https://github.com/syndesisio/syndesis/issues/1916

**Comment by nding-anges** [comment]
Hi everyone,
I uploaded a design of Connection page which is based on current implementation and
a card for Create connection. Regarding some connection icons and new connection card layout design will continue to be improved and delivery later on relative issues:#3661, #3488 
![connection page](https://user-images.githubusercontent.com/34368385/48693693-3c9a1780-ec15-11e8-8487-89c7d7eda5db.png)
