### ISSUE TITLE
Successfully deleted integration not handled properly

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#3286]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

After fixing https://github.com/syndesisio/syndesis/issues/3151 I noticed that even an integration is successfully deleted on back-end side, it is still shown in status Stopping in summary page

## Expected behavior

Once deleted the integration should disappear/chage status

## Screenshot

![peek 2018-08-03 08-22](https://user-images.githubusercontent.com/1868933/43627542-1deeef9a-96f7-11e8-919b-dfc0861ec34f.gif)

## Tasks involved / Steps to Reproduce

1. create an integration
2. let it start
3. delete the integration

**Comment by heiko-braun** [comment]
//cc @gashcrumb Is this something you could look into? @lburgazzoli assumes it's a UI problem, but we are not sure.
