### ISSUE TITLE
Add new top level section "Community" to Developer Docs

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#3289]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

This should contain links how to reach the syndesis members (i.e. chat, mail, issues).

For chat I would add that we support IRC and Matrix, but for Matrix it's recommended to add the following setup so that direct messages works to IRC user (but its more a  recommendation for Matrix users in general as it does not affect posting to #syndesis

```
* Open a direct chat to @freenode_NickServ:matrix.org (the "Start Chat" action in the lower left action bar in Riot.im)
* Identify yourself with your registered Freenode Nic & password by sending:
identify <nick> <password>
* Group you current nick (typically 'nick[m]') to the registered nick
group

Now your current Matrix IRC nick from the bridge is connected to your registered nick so you can post to channels and other folks which have restrictive spam settings.

In order to make this a permanent thing you have to store your password at the bridge. This can be done by:

* Open a direct chat to @appservice-irc:matrix.org
* Send the message

!storepass nick:password

I'd recommend registering a dedicated user for the proxy at Freenode so that password sharing might not be so harmful.
```

See also: https://github.com/matrix-org/matrix-appservice-irc/wiki/End-user-FAQ#how-do-i-registeridentify-to-nickserv

Alternatively one could also consider to add this to our Website.

**Comment by kahboom** [comment]
We have something similar to this in the community website, but I think it could use improvement. I'll see if I can move this issue over to the website repo.

**Comment by kahboom** [comment]
Issue moved to [syndesisio/syndesis.io #111](https://github.com/syndesisio/syndesis.io/issues/111) via [**ZenHub**](https://www.zenhub.com/)
