### ISSUE TITLE
Warnings are not updated after editing API definition 

### ISSUE THREAD

**Issue by kcbabo** [syndesisio/syndesis#3291]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
The "Warnings" section of the API connector review page does not appear to be updated after editing an API definition.

To reproduce ...
1. Create new API Client Connector
2. Import Todo API definition from file
3. Select Review/Edit
4. Delete the DELETE {id} operation
5. Save the API definition
6. Note that the warning "Operation DELETE /{id} does not provide a response schema for code 204" is still present even though that operation was deleted.

## Expected behavior
Warnings section is updated after editing API definition

**Comment by heiko-braun** [comment]
@kahboom Isn't this fixed already?

**Comment by gashcrumb** [comment]
Think this one did it?  -> https://github.com/syndesisio/syndesis/pull/3282
