### ISSUE TITLE
Create a new home for the Concur connector, and perhaps other API connector based connectors in the future

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#3292]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

We bundle the Concur connector by loading the `concur-connector.json` from `/META-INF/syndesis/api-connectors/` in the DAO module.

The way we build the `concur-connector.json` is to merge several Swagger specifications we download from Concur, patch them to be correct and run a Groovy script to artisanally tune the resulting connector metadata.

Let's create a Maven module in under `app/connector` tree that produces artefact containing the connector descriptor. We could also produce multiple artefacts (I think this is better) or bundle multiple connectors in the same artefact.

## Expected behavior

Make the world a better place.

## Screenshot

![giphy](https://user-images.githubusercontent.com/1306050/43643203-c880b212-972a-11e8-9add-863ff9ea639a.gif)

## Tasks involved / Steps to Reproduce

1. Create a new Maven module under `app/connector`
2. Create Maven build that merges Concur Swaggers, and creates the resulting connector JSON with proper metadata (names/descriptions/icons/tags...)
3. The result should be a JAR file with only the connector JSON
4. Profit

**Comment by rhuss** [comment]
Not sure whether the label "group/connector" is correct as @KurtStam says an api-connector is not a connector. Otherwise we could just create a "connectors/concur" Maven module which holds the patched resource file.

**Comment by KurtStam** [comment]
Yeah I would prefer api-connectors/concur.
