### ISSUE TITLE
Concur oauth settings - no trimming of whitespace characters before credentials are used

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#3293]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

When filling oauth details for SAP Concur, adding whitespace character to the end of the field "Authorization URL" will make it unusable. Creating concur connection will then ends with error:
400 Bad request. URI does not match any available uri-template.

This happens easily with copy-pasting credentials (as it was in my case :) ), maybe we should be more user friendly and trim those types of credentials before using them.

**Comment by zregvart** [comment]
Could be regression, we had this fixed with #2510

**Comment by zregvart** [comment]
One more data point. It seems that when one uses copy widget on Google API Console (https://console.developers.google.com) you might get a leading whitespace (happened to me). I think we might want to trim Client ID and Client Secret fields also.
