### ISSUE TITLE
Concur oauth validation returned error but UI did not recognize it

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#3294]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

TLDR: Oauth validation somehow failed,  syndesis thought that it validated successfully, but all buttons were missing. 

I added oauth credentials via support page. When creating concur connection, I was able to successfully log in to concur, but then something happened when I was redirected back to syndesis. In URL there was an error that something went wrong, but syndesis thought that everything was ok and asked me to fill in connector name. But there were no buttons visible so I could not finish nor cancel the process in standard way.
I am not able to reproduce this issue anymore as the oauth validation now works all the time, but we should probably look into it to avoid such situations?

**Comment by zregvart** [comment]
@mcada can provide the callback with all the parameters as redirected from Concur?

**Comment by mcada** [comment]
I cant provide more information as it happened only once and I thought that I had wrong configuration but I did not and it worked on the second try :/ Can't reproduce it anymore.

**Comment by KurtStam** [comment]
@mcada, both @zregvart and myself have seen some 'flakiness' on the concur implementation site and sometimes we think their load balancer reverts to a working instance or something and trying again fixes it. Keep an eye on it though so we can make sure it's not us.

**Comment by zregvart** [comment]
Keep in mind that if you remain on the Concur site Syndesis did not receive any information on the failure and we have no control over this.

If you end up at Syndesis and the response is negative but we proceed as if it was successful then we have an issue in handling responses from the OAuth flow.

**Comment by mcada** [comment]
@zregvart This is exactly what happened - I was redirected back to syndesis after successfull login into concur and it acted like oauth validation was a success, but in fact it wasn't and I only found out because it was written inside of browser url. And all buttons were missing.

**Comment by zregvart** [comment]
@mcada you might still have the URL we were redirected to in the browser history (long shot), or you might want to fiddle with the parameters of the callback URL.

I see that we're not handling erroneous callbacks properly. For instance I think this reproduces your situation:

 1. With OAuth settings setup for SAP Concur (probably also any other), settings (client id/secret) need not be correct
 1. On Connections tab, select `New Connection`
 1. Pick SAP Concur
 1. Select `Connect SAP Concur`
 1. When on Concur site (either login or error page, doesn't matter) enter the url:
    `https://$SYNDESIS/api/v1/credentials/callback`
 1. Notice that the URL is immediately changed to:
    `https://$SYNDESIS/connections/create/review#{"connectorId":"oauth2","message":"Unable to update the state of authorization","status":"FAILURE"}`

I think this might be the scenario you encountered, the parameters to the `/api/v1/credentials/callback` might be different but we should handle errors in OAuth flow better.

Tagging this with `group/ui`.

**Comment by mcada** [comment]
@zregvart I usually play with syndesis in private mode so I have no history but luckily this time I did not, the URL after callback was probably this one:
``https://syndesis.my-minishift.syndesis.io/connections/create/review#{%22connectorId%22:%22oauth2%22,%22message%22:%22Unable%20to%20finish%20authorization,%20OAuth%20authorization%20timed%20out?%22,%22status%22:%22FAILURE%22}
``

**Comment by zregvart** [comment]
@paoloantinori @gashcrumb I would not call this blocker, if we have some spare cycles perhaps we could take a look at the error handling from OAuth flow and if it's not too much work have it in the release?
