### ISSUE TITLE
Add --route option to `syndesis minishift`

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#3298]
## This is a...

<pre><code>
[*] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
I need a specific route so we can use the same callback url in OAuth. Currently I use:

minishift start
oc login -u system:admin
syndesis install --setup-crd
syndesis install -p myproject --route syndesis.my-minishift.syndesis.io
oc adm policy --as system:admin add-cluster-role-to-user cluster-admin developer cluster role "cluster-admin" added: "developer"
syndesis install --fix-permissions developer

It'd be much easier if the minishift command can take a --route argument so that we maybe able to all all of the above in one command.

@rhuss wdyt?

**Comment by rhuss** [comment]
Yes, we can do that, should be no big issue.

In the meantime you can shorten the list above with the latest syndesis to

```
minishift addons enable admin-user
minishift start --memory 4096
oc login -u system:admin
syndesis install --setup-as-admin developer
oc login -u developer
syndesis install
```

It's all documented [here](https://doc.syndesis.io/#_installing_syndesis_2), btw ;-) (you see, even writing exceptionally well written documentation doesn't help all the time)

**Comment by KurtStam** [comment]
@rhuss I think this was added?

**Comment by rhuss** [comment]
true, just forgot to close that issue.
