### ISSUE TITLE
yarn start:minishift  fails

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis#33]
```
$ yarn start:minishift 
yarn run v1.2.1
warning You are using Node "7.5.0" which is not supported and may encounter bugs or unexpected behavior. Yarn supports the following semver range: "^4.8.0 || ^5.7.0 || ^6.2.2 || ^8.0.0"
$ yarn run prestart
warning You are using Node "7.5.0" which is not supported and may encounter bugs or unexpected behavior. Yarn supports the following semver range: "^4.8.0 || ^5.7.0 || ^6.2.2 || ^8.0.0"
cp: ./.git/hooks: No such file or directory
error Command failed with signal "SIGSEGV".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by gashcrumb** [comment]
That git hook should only be run for stuff under the UI directory really.  Maybe we should take out the `prestart` script as a quick fix for now.  @deeleman thoughts?

**Comment by gashcrumb** [comment]
In fact, if we wind up migrating from angular-cli to just native webpack config, maybe we can get rid of the need to have a git hook.  It's for doing a pre-commit lint check (well, I added formatting too) but if we can bake that into the build task better then it's not needed.

**Comment by gashcrumb** [comment]
Just a test...

**Comment by deeleman** [comment]
Yep, I'm afraid we will have to.

The main issue with monorepos is that background processes evolve into having a global impact. If all the submodules were JavaScript based, we could use Lerna, but i'm afraid we can't here.

Let's remove the `prestart` hook and bind linting to tsconfig. This might break the background compilation enforced by Angular CLI if the code is wrong, but I'll try to prevent this. the upside is that we will get then errors on our IDE no matter what TS version we have installed globally.

A PR is in the works...

> In fact, if we wind up migrating from angular-cli to just native webpack config, maybe we can get rid of the need to have a git hook.

Exactly.

**Comment by gashcrumb** [comment]
@deeleman awesome, thanks for that!  I'll assign this issue to you then...
