### ISSUE TITLE
Remove Branding title "Fuse Ignite"

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#3306]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

Currently the branding header looks and the HTML title looks like

Instead the branding header should only be "Red Hat Fuse Online" (without Ignite) and the HTML title should also be only "Red Hat Fuse Online".

![image](https://user-images.githubusercontent.com/99080/43682978-58b0b266-9883-11e8-9d3c-a10a98e82f9b.png)

I can tweak this by adapting the ui-config and set `branding` to

```json
"branding": {
          "logoWhiteBg": "",
          "logoDarkBg": "",
          "iconWhiteBg": "assets/images/FuseOnlineLogo_Black.svg",
          "iconDarkBg": "assets/images/FuseOnlineLogo_White.svg",
          "appName": "",
          "favicon32": "/favicon-32x32.png",
          "favicon16": "/favicon-16x16.png",
          "touchIcon": "/apple-touch-icon.png",
          "productBuild": true
       }
```
This removes the "Ignite" in the branding but also leaves you with an empty HTML title.

![image](https://user-images.githubusercontent.com/99080/43682933-af248506-9882-11e8-97c3-49e54ff93ae1.png)

**Comment by gashcrumb** [comment]
The `appName` string there is used in several places, better we set it to what it should be (not sure, Fuse Online or Ignite) and just fix the header so it only uses the logotype, I can look at this tomorrow.

**Comment by gashcrumb** [comment]
@rhuss BTW when you get a chance can you attach what the productized `config.json` should look like?  I'd like to be sure I implement this with the right settings.

**Comment by rhuss** [comment]
This is the full section of the config.json from our templates:

https://github.com/syndesisio/syndesis/blob/6ec8341f2a63cb3800e288f3228db5c378b1f603/install/generator/03-syndesis-ui.yml.mustache#L111-L150

with the specific part for branding unsed in productisation: 

https://github.com/syndesisio/syndesis/blob/6ec8341f2a63cb3800e288f3228db5c378b1f603/install/generator/03-syndesis-ui.yml.mustache#L127-L138

**Comment by gashcrumb** [comment]
Cool.  What value should the productized `appName` have then?  `Ignite` still or `Fuse Online`?

**Comment by rhuss** [comment]
"Fuse Online" is it. "Ignite" is not used as part of the product anymore.
