### ISSUE TITLE
Provide a Slack Connector for Fuse Online

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/syndesis#3313]
## Feature Owner: Andrea C.

As a citizen integrator, I want to be able to add a Slack start connector to accept events from my custom slack app that I configure on slack.com(https://api.slack.com/apps/new). I want to monitor a channel for slack messages with by app and consume these via my fuse online integration.
I want to be able to trigger my integration via any/every message.
I would like to use Events API to read messages to a channel:
https://api.slack.com/events-api
https://api.slack.com/events/message

In creating a Slack start connector, I receive my integration url that I can then provide slack.
Slack has specific requirements on the url verification handshake.

DoD

A slack connector can be added to the start of an integration flow
Posting a slack message to a subscribed channel can be processed and output to a log file.

**Comment by oscerd** [comment]
I have a working consumer now. We'll need to address some problem in the Verifier of the connector: from the producer side we use a webhookurl that actually is required. When we'll add the consumer we'll need to use a token and not a webhookurl, so we'll need to remove the required flag and implement some logic in the verifier. Actually the consumer behavior is the following: it will poll a channel on a scheduled base and return a maxResults set of messages in the form of SlackMessage. On each poll the consumer will track the timestamp of the last message consumed and in the next poll it will check from that timestamp.

**Comment by oscerd** [comment]
I still need to push to the Fuse Camel repo.

**Comment by zregvart** [comment]
@oscerd I think it would make sense to have the connector as a part of the syndesis repository, when it stabilises we can donate it to Apache Camel and backport it to Fuse Camel. This way we can iterate on it in sync with Syndesis without the need for a Fuse release.

**Comment by oscerd** [comment]
I'm actually pushing on the Fuse camel side and then I can start a build of Fuse 7.2 and then pin the artifact. In my opinion having the producer on Fuse camel and the consumer on Syndesis don't make sense too much. Once I have it on Fuse I can push upstream too.

**Comment by oscerd** [comment]
So we have a first version of the consumer, I'd like to have some feedback when possible.

**Comment by oscerd** [comment]
I believe we can already mark this as done.

**Comment by oscerd** [comment]
For 7.2

**Comment by heiko-braun** [comment]
@oscerd I saw your PR, is the feature done from your point of view?

**Comment by oscerd** [comment]
Yes, In my opinion it should be done.

**Comment by heiko-braun** [comment]
//cc @syndesisqe This should be ready for review

**Comment by amysueg** [comment]
@heiko-braun Do we need an icon for this new connector? If so, can you create an issue and assign it to @sjcox-rh? Thanks.

**Comment by oscerd** [comment]
We already one because this issue is the second part of an old connector

**Comment by tplevko** [comment]
Automated tests are already in place, provided by @mkralik3: https://github.com/syndesisio/syndesis-qe/pull/579 I think we can close this.
