### ISSUE TITLE
Workday Connector

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/syndesis#3314]
See also **https://issues.jboss.org/browse/ENTESB-11546**

**Comment by amysueg** [comment]
@heiko-braun Does this connector need an icon? If so, would you please create a separate issue related to this epic for @sjcox-rh to create the icon? Thank you.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11546**
