### ISSUE TITLE
API client connector workflow - required fields should be indicated with a red asterisk (*)

### ISSUE THREAD

**Issue by dongniwang** [syndesisio/syndesis#3319]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Required fields are not indicated on step 3 of API Client Connector creation workflow. 

<img width="806" alt="screen shot 2018-08-06 at 11 36 58 am" src="https://user-images.githubusercontent.com/24943812/43727148-2cd10f78-996f-11e8-8f7b-8766d3932a3b.png">

## Expected behavior

Indicate required fields with a red asterisk (*) to the left of the filed label. Should also include the sentence "The fields marked with * are required." 

See PatternFly field labeling for detailed instruction https://www.patternfly.org/pattern-library/forms-and-controls/field-labeling/

(The spacing in the following mock-up is not correct, please reference PF site for correct implmentation - FYI @michael-coker )

![required_fields](https://user-images.githubusercontent.com/24943812/43727743-cd84b3f6-9970-11e8-8144-d3ad1257925c.png)

cc: @amysueg @michael-coker

**Comment by elvisisking** [comment]
Work was done in #3345 and conforms to PatternFly guidelines.
