### ISSUE TITLE
Salesforce Connector throws HTTP error 400

### ISSUE THREAD

**Issue by honghuac** [syndesisio/syndesis#3322]
## This is a...

<pre><code>
[ ] Feature request
[x ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
Attempting to create salesforce connection using valid Salesforce OAuth tokens result in a HTTP Error 400:
https://gist.github.com/honghuac/2f0ea51eb0aabe5164ee933ea82a3526

**Comment by nandanj** [comment]
You have to configure the consumer key/secret in Settings and create the connector for it to work. If you forget the 1st step, it allows you to enter all credentials {userid,pwd, consumer key, secret} in the connector UI, but the error shows up when you add SFDC as a connection in the integration. 
Perhaps there is a way to alert the user to this, so he always configures the security information in settings?

**Comment by zregvart** [comment]
Thank you for reporting this. I agree, this is a pain point for the users, I think we can fix this with #2013. So I'm closing this and redirecting the discussion there.
