### ISSUE TITLE
Provide a ClusterServiceVersion definition to register Syndesis with OLM.

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis#3326]
## This is a...

<pre><code>
[X] Feature request
</code></pre>

## The problem
Provide a ClusterServiceVersion definition to register Syndesis with OLM.

**Comment by chirino** [comment]
Once we do this, we might as well also depend on the [prometheus operator](https://coreos.com/operators/prometheus/docs/latest/user-guides/getting-started.html) and so we can just use the [Prometheus CRD](https://coreos.com/operators/prometheus/docs/latest/api.html#prometheus) to install our prometheus instance.

**Comment by rhuss** [comment]
This is part of our efforts for the 7.2 feature OLM on which we will start shortly. Please negotiate with me or @nicolaferraro in case you are working on this as we take this story over as feature owner.

**Comment by chirino** [comment]
@rhuss you sure we should expand the scope of #2894 with OLM support too?  Since Operator and OLM support land on different versions of OpenShift perhaps keeping these items attached to different epic would be safer.

**Comment by rhuss** [comment]
Yeah, make sense. Let's park this issue until we have the OLM epic up and running (not sure whether @heiko-braun or @paoloantinori already started to put the feature list into epics).

We should close #2894 asap

**Comment by heiko-braun** [comment]
Superseded by https://github.com/syndesisio/syndesis/issues/5350
