### ISSUE TITLE
Can't create concur connector via oauth

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#3329]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

@zregvart 
After successful callback, I am redirected here in syndesis with no way how to finish the connector:
![screenshot_20180807_132539](https://user-images.githubusercontent.com/14313995/43773291-8ce4757c-9a45-11e8-885b-5911211babc6.png)

**Comment by paoloantinori** [comment]
Hi @mcada can you please restore the removed section from the bug template and add the steps to reproduce, in particular, the sample url used?

**Comment by mcada** [comment]
@paoloantinori if you have trouble reproducing it, here are correct steps:

Note that I did not mention concur as connector to reproduce because it is more difficult than all others (you have to set up syndesis route and update /etc/hosts accordingly) but this bug happens with all oauth connectors so if you played with oauth before, you can use the same connector/credentials again. 

1. Authorize syndesis with oauth app which you want to use and set up correct callback url, you can find more information regarding this topic in documentation
2. Fill oauth credentials for desired connector in settings page
3. Create desired connector from connections page
4. During creation, you will be asked to log in to desired application when creating connector via oauth
5. After successful login, you will be redirected back to syndesis and you will end up with the same screen which you can see on mentioned screenshot

I did not attach reproducer as there is just one way how to create connector via oauth but I understand that if someone is not in touch which those things they may not know. I hope it helps.
