### ISSUE TITLE
syndesis release broken

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#3336]
## This is a...

<pre><code>
[ ] Feature request
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

`syndesis install --tag something` currently always installs latest regardless of the tag. 
This bug is fixed in #3334

**Comment by heiko-braun** [comment]
@rhuss Is this addressed already?

**Comment by rhuss** [comment]
fixe in #3334
