### ISSUE TITLE
UI updates to required form fields.

### ISSUE THREAD

**Issue by mcoker** [syndesisio/syndesis#3341]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
When all fields in a form are required
* remove asterisks
* helper text should read "All fields are required."

When some fields are required
* helper text should read "The fields marked with * are required."

When all fields are optional
* helper text should read "All fields are optional."

related - https://github.com/syndesisio/syndesis/issues/3319

PatternFly code for reference - https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/forms.html

#### All fields required
<img width="1410" alt="screen shot 2018-08-07 at 12 19 20 pm" src="https://user-images.githubusercontent.com/35148959/43792623-ded7423a-9a3e-11e8-8193-0188ef0337e1.png">

#### Some fields required
<img width="1410" alt="screen shot 2018-08-07 at 12 29 36 pm" src="https://user-images.githubusercontent.com/35148959/43792617-dccd4c96-9a3e-11e8-86f1-634130db8598.png">

#### All fields optional
<img width="1418" alt="screen shot 2018-08-07 at 12 38 00 pm" src="https://user-images.githubusercontent.com/35148959/43792613-da86f270-9a3e-11e8-9151-1ace6d16fb4e.png">

cc @dongniwang

**Comment by dongniwang** [comment]
cc: @elvisisking since he's working on #3319

**Comment by gashcrumb** [comment]
So all of these pages are ng-dynamic-forms unlike #3319 

So most likely this will need to be implemented in our form service that creates the ng-dynamic-forms objects and probably some work will be needed in our ng-dynamic-forms UI component.  I think it should be fairly straightforward, we should probably move the current text that shows `the fields marked * are required` which is currently in the connection configuration template to the UI component, then we can easily display the correct hint text.

**Comment by dongniwang** [comment]
@gashcrumb @michael-coker - can we close this issue now since PR #3345 is in place?

**Comment by michael-coker** [comment]
@dongniwang the original issue was about the app as a whole. I'm also seeing the original issue still.

<img width="1593" alt="screen shot 2018-10-29 at 4 01 18 pm" src="https://user-images.githubusercontent.com/35148959/47680098-e7c62c80-db93-11e8-91c5-c5ad86f6e974.png">

And here are some others at a quick glance
<img width="1593" alt="screen shot 2018-10-29 at 3 56 45 pm" src="https://user-images.githubusercontent.com/35148959/47680120-f90f3900-db93-11e8-8bf8-e30ff743fda3.png">
<img width="1593" alt="screen shot 2018-10-29 at 3 57 06 pm" src="https://user-images.githubusercontent.com/35148959/47680121-f90f3900-db93-11e8-999d-9b08ac5a4f76.png">
<img width="1593" alt="screen shot 2018-10-29 at 3 58 30 pm" src="https://user-images.githubusercontent.com/35148959/47680122-f90f3900-db93-11e8-98c3-5a08017f92ae.png">
<img width="1593" alt="screen shot 2018-10-29 at 3 58 52 pm" src="https://user-images.githubusercontent.com/35148959/47680123-f90f3900-db93-11e8-9493-f362aad33892.png">
<img width="1593" alt="screen shot 2018-10-29 at 3 59 03 pm" src="https://user-images.githubusercontent.com/35148959/47680124-f90f3900-db93-11e8-92b1-260a37595e33.png">
