### ISSUE TITLE
Activities stopped tracking after couple of hours 

### ISSUE THREAD

**Issue by mmelko** [syndesisio/syndesis#3350]
This topic was discussed in comments of https://github.com/syndesisio/syndesis/issues/2607 so I created new issue because I can still hit this.

I have 6 integrations (>= 3 steps)
- 3 are processing message every second 
- 3 every ~15-20s 

After couple of hours activities stops tracking. Restart of integration or syndesis-server helps for another couple of hours (~8 hours ~100 000 messages).

<img width="1206" alt="screen shot 2018-08-08 at 08 56 37" src="https://user-images.githubusercontent.com/6814482/43821315-2b385baa-9ae9-11e8-9d50-94d5413085e4.png">

I'm trying also simpler scenario with 6 integration:
3 integrations with timer -> amq (message every 5s)
3 integration amq -> log (every 5s)
This is running fine for currently 47 hours with correct activities tracking. However activities are much smaller -- only one step.

**Comment by zregvart** [comment]
I think this will be resolved with #3337. Feel free to reopen if it didn't.
