### ISSUE TITLE
Can't create Twitter connection via OAuth

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#3355]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

I am not able to create twitter connection via OAuth. I end up with this:
![screenshot_20180808_164706](https://user-images.githubusercontent.com/14313995/43845718-e7c8094e-9b2c-11e8-9dce-c634dba1e3d8.png)

I checked my callback URL in twitter app and it is correct. Tested on clean syndesis master.
@zregvart maybe my problem is connected with recent OAuth validation fix? But all other connectors using OAuth work so I am not sure what is wrong here :/

**Comment by zregvart** [comment]
@mcada that message does point to a callback URL issue with twitter OAuth app setup, can you verify that you have a developer account and everything is OK at twitter?
Twitter made it necessary to have a developer account for OAuth apps, could be something related to that.

**Comment by mcada** [comment]
I am quite sure that it worked last week. I am configuring OAuth from developer.twitter.com so I guess it should work.

**Comment by zregvart** [comment]
Yeah, I don't know how recent this change was, you can see a PR #3321 that @TovaCohen did to document this requirement. I think it's a good opportunity to double check that we have documented it properly and to verify that all steps were done on Twitter.

**Comment by mcada** [comment]
I will recheck this, maybe without this account the apps are useless even when set up correctly from their new developers site. For now I will change priority to p2...

**Comment by zregvart** [comment]
I got the exact same error right now. The callback URL was wrong in my case. I also applied for the developer account in parallel. With the changed callback URL I can create a Twitter connection.

**Comment by mcada** [comment]
I had correct callback, I rechecked it many times. I deleted all apps and created one again via their new developer UI and it works, no idea why the old apps did not work, they were visible from the new UI. Closing this one.
