### ISSUE TITLE
OAuth credentials disappearing

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#3386]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Syndesis version 1.4.5
While playing with concur using OAuth credentials from settings page, it already happened 3 times in last 24 hours that those credentials disappeared and connector stopped working (it worked before the credentials loss). I created an integration with concur connection and then edit the integration and publish over and over again, last time the credentials disappeared on fourth edit - publish. 

## Expected behavior

Credentials in settings page must be permanent and not disappear when they want.

**Comment by zregvart** [comment]
@mcada to summarise you set the OAuth settings for Concur, created an integration using the Concur connector and just publish/stop a couple of times, and the settings were reset?

Does it happen with any other connector?

Were there any deployments that might have reset the settings in the meantime?

**Comment by mcada** [comment]
I never experienced this with other connectors using OAuth but to be fair I did not play with them as much as I did with concur. There were no other deployments, no reset, nothing. It was on minishift, syndesis tag 1.4.5 so no image updates and I did not run any tests, it was all done manually.

Exactly what you mentioned - I set the OAuth for concur, created concur connection and integration, it was:
database -> mapper -> concur (create listitem) -> log (body, headers) -> LOG (everything). All I did between republishing was editing the mapper step.

**Comment by zregvart** [comment]
@mcada I've been trying to reproduce this without much luck. I know that there is a small window during which the OAuth settings page is loading and it shows empty values in fields. So, just to be sure if this might be a issue, i.e. that the page is not fully loaded, can you take a look in the database and see if the settings are there when they're not shown in the UI?
Should be something like:

```shell
$ oc exec syndesis-db-1-smh4w -- bash -c 'psql -U syndesis -c "select path, value from jsondb where path like '"'"'/connectors/:concur/configuredProperties/client%'"'"';"'
```

Where `syndesis-db-1-smh4w` is the name of the database pod.

**Comment by mcada** [comment]
@zregvart This is not the case. I created an integration using those OAuth settings. The integration worked as expected. I edited the integration and published it. The integration did not work because it had no credentials because they were empty. Then I checked settings page and those credentials were reset to nothing or default values. Credentials disappeared.

**Comment by zregvart** [comment]
@mcada cool, I've found one case where the OAuth settings are reset: when I delete the server pod. Seems that our database startup/loading mechanism is removing `configuredProperties` from the Connectors. This might be one instance where this issue is manifesting, do you think it's also the case you encountered?

In this instance the URLs (authorization, token, endpoint) were reset to Concur production URLs, did that happen in your case?

**Comment by mcada** [comment]
Yes, my values set by me disappeared and default values were there instead (or nothing nothing in fields where we have no default values).
