### ISSUE TITLE
UX - New Icons Needed

### ISSUE THREAD

**Issue by sjcox-rh** [syndesisio/syndesis#3395]
Need to create 2 generic icons to be used within API provider integration flows:
- API Provider Connector
- Return Path / Stop and Return
- Flow Icon
- Integration Icon

Reference [here](https://thenounproject.com/term/api/137607/) as inspiration.

**Comment by sjcox-rh** [comment]
Added two new icons based off latest API Provider designs:

<img width="979" alt="screen shot 2018-08-27 at 10 31 22 am" src="https://user-images.githubusercontent.com/16257540/44675114-66f88200-a9e4-11e8-94ca-1ed67002c616.png">

**Comment by paoloantinori** [comment]
hi @sjcox-rh  can we consider this done?

**Comment by amysueg** [comment]
@sjcox-rh Once you're back, let's make sure we keep an eye on this one so we can get the new icons for 7.2 Thanks!

**Comment by amysueg** [comment]
@sjcox-rh will add API provider and Return Path icons via #3557
