### ISSUE TITLE
Failed to stop integration Error stopping integration: [object Object] during publishing 

### ISSUE THREAD

**Issue by mmelko** [syndesisio/syndesis#3405]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
Currently it's not possible to stop integration during publishing,  _Failed to stop integration Error stopping integration: [object Object]_ is displayed. I can delete integration though. 

## Expected behavior
I should be able to stop integration during publishing. When I make some mistake I can't edit either so for fixing it I have to delete it and create new one. 

## Tasks involved / Steps to Reproduce

1.
2.
3.
4.

**Comment by heiko-braun** [comment]
@lburgazzoli @nicolaferraro Any thoughts on this?

**Comment by KurtStam** [comment]
When an integration is started/deployed the POST request returns an IntegrationDeployment data structure with the new version that is being started/deployed. When the user clicks on Stop the url that is called is: 

POST: /api/v1/integrations/i-LO2eKU4E1UksX4jFH5Rz/deployments/undefined/targetState

where 'undefined' is supposed to be the version. More over the backend, the backend sends a 404 bc the versionId is defined as an int. So

/api/v1/integrations/i-LO2eKU4E1UksX4jFH5Rz/deployments/{versionId}/targetState

does NOT match the request made.

**Comment by tplevko** [comment]
@mmelko please verify the fix
