### ISSUE TITLE
Expose Fuse Online API projects using kube service annotations

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/syndesis#3407]
## Feature Owner: Kurt

The Fuse Online part of https://issues.jboss.org/browse/ENTESB-9252, i.e. applicable to https://github.com/syndesisio/syndesis/issues/3046 (API Provider)

#3502 SubTask: K8s service annotations - Derive MetaData from Rest DSL conventions
#3503 SubTask: K8s service annotations - Allow User to override default service metadata 
#3504 SubTask: K8s service annotations - Create annotations at deploy time

**Comment by heiko-braun** [comment]
@KurtStam Can you add the subtasks you see fit for this item?

**Comment by zregvart** [comment]
I feel we don't have a common understanding of what annotations (or labels) should we use. There's a discussion on https://github.com/fabric8io/fabric8-maven-plugin/pull/1388 that is relevant to this. I think we need to agree on the annotations (or labels) first in order to proceed here.

**Comment by rhuss** [comment]
@zregvart its also that the discussion involves the 3scale team which also suggests to change the prefix and leave out some of the annotation which e.g. duplicate the information delivered by a response header when fetching the description (e.g. via the mime type). If we add this to the annotation then there is the risk of an inconsistency. So you would have to resolve the conflict and IMO it should be always the HTTP response mimetype which should win as its closer to the servife. So we could just ommit the type (OpenAPI or Rest) from the annotations.
