### ISSUE TITLE
Add an example link to the "Upload OpenAPI Specification" page

### ISSUE THREAD

**Issue by phantomjinx** [syndesisio/syndesis#3410]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

When creating a new API Client Connector, the first wizard page "Upload OpenAPI Specification" describes a 'Custom API' and its conformance to the OpenAPI 2.0 standard. It would be advantageous to include links in this description to:
1. The OpenAPI 2.0 standard so the user will not have to google it;
2. An example REST API that the user can link to as an url or download to try out.

## Expected behavior

User can begin immediate testing/learning of the functionality without cause to hunt around for a REST API as a pre-requisite.

## Tasks involved / Steps to Reproduce

1.
2.
3.
4.

**Comment by zregvart** [comment]
We deploy the [todo-example](https://github.com/syndesisio/todo-example) it has OpenAPI specifications at URL like `http://todo-syndesis.$(minishift ip).nip.io/swagger.(yaml|json)`

**Comment by phantomjinx** [comment]
@zregvart
Given that url is part of the syndesis build, it could be a little tricky adding it as a static link in the description. Given the number of REST API services available on the net, I wouldn't have thought it too tricky to link to one of them. Even a clone (in case it vanishes) of the swagger pet store would suffice (although V2 rather than V3 since the latter is yaml).
