### ISSUE TITLE
Add a filter to the file dialog on the "Upload OpenAPI Specification" page

### ISSUE THREAD

**Issue by phantomjinx** [syndesisio/syndesis#3411]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

* Downloaded the Swagger PetStore V3 Specification to file then selected it in 'Choose File' dialog and clicked Next. This failed with the following error message:

> "Unable to read OpenAPI specification from: openapi: "3.0.0" info: version: 1.0.0 title: Swagger Petstore license: name: MIT server..."

* Error message could be improved to indicate the nature of the problem, which was due to Petstore V3 being in yaml format rather than json;

* Is the file upload not able to manage yaml?

* Using Petstore V2 worked correctly since it was in json;
* Add a filter on the "Choose File" dialog indicating types of files that can be imported;

## Expected behavior

Only supported file extensions should be displayed in file chooser dialog, indicating types of files that can be parsed by the upload.

## Tasks involved / Steps to Reproduce

1.
2.
3.
4.

**Comment by elvisisking** [comment]
The ApiCurio editor currently does not support editing a YAML file. We would have to convert it to either JSON or a JavaScript object in order to get this to work. Is that something we should do @paoloantinori?

**Comment by gashcrumb** [comment]
This should be closed since it was addressed in #3418
