### ISSUE TITLE
Embedded Apicur.io Editor Minor Issues

### ISSUE THREAD

**Issue by phantomjinx** [syndesisio/syndesis#3412]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

These issues are applicable to the apicur.io editor which is embedded in syndesis. Therefore, they will probably be fixed upstream?

- On first display of the editor, the save tooltip is displayed narrowly in a long vertical block with 1-2 words per line (see https://issues.jboss.org/secure/attachment/12439213/apicurio-save-button-tooltip.png);

- There is some odd behaviour with the 'Contact Info' controls:
    - Enter name but leave other inputs blank;
    - Dialog disappears but message 'None Found ..." message is redisplayed even though there is a name. Error is displayed indicating a valid email address must be provided;
    - Fixing Contact Info by reopening and editing does not clear previous errors - only when clicking Save is the error removed;
    - Enter all info so no errors then reopen and remove the email address;
    - Clicking OK gives an error that "The "url" property must be a valid URL." rather than there being no email address;
    - Clicking Save fixes this and displays the correct error, ie. no email address.

- Clicking Save
  - Would be beneficial if errors were flagged up to user prior to returning to the Review Actions page, ie. "You are saving a spec with errors. Would you like to fix them first?" and focus returns to the editor.

## Expected behavior

- Save Tooltip to display in an appropriately wide rectangle;
- Contact Info controls to correctly handle all different combinations of inputs and display appropriate errors messages;
- Save button to flag validation errors prior to exiting the editor. 

## Tasks involved / Steps to Reproduce

1.
2.
3.
4.

**Comment by elvisisking** [comment]
The tooltip placement I have set to "auto" which in this case is being set to the bottom. When I had set the placement to "left" the tooltip did display in a wider rectangle; however, it flickered **really bad** to the point it was quite annoying. With all that said, I agree with @phantomjinx that it currently doesn't look that good, but I thought it not flickering made the "auto" placement a better choice. Has anyone else seen this tooltip flickering issue?

**Comment by gashcrumb** [comment]
Flickering tooltips have been a constant issue with the data mapper as well, I think generally @michael-coker has fixed these by changing the placement, not necessarily to `auto`, but at least to appropriately show the tooltip in a direction that doesn't overflow the parent element.

TBH with such a long tooltip anyways it's fitting into the page exactly how I'd expect.

**Comment by michael-coker** [comment]
@elvisisking if you add `container="body"` to the cancel/save buttons, they're positioning improves. For reference, [ngx-bootstrap tooltip "append to body"](https://valor-software.com/ngx-bootstrap/#/tooltip#append-to-body)

**Comment by elvisisking** [comment]
Thanks @michael-coker. I'll give that a try.

**Comment by elvisisking** [comment]
Currently there is no way to obtain validation errors from the ApiCurio editor component. I've submitted an [enhancement request](https://github.com/Apicurio/apicurio-studio/issues/396) to the [apicurio studio project](https://github.com/Apicurio/apicurio-studio) to add this feature.

**Comment by elvisisking** [comment]
I'm running through the steps @phantomjinx identifies above using the 'Contact Info' control of the ApiCurio editor. There are some differences in the behavior I am seeing.

- When I enter a name and leave the other fields empty and close the dialog, I get 2 errors: (1) The "url"' property must be a valid URL., and (2) The "email" property must be a valid email address. This seems good to me. I think the troubling part to me in addition to the "None Found" message is that when I go and re-edit the contact information the name I entered is lost.
- When I fix the contact information by entering one or both of the URL and email fields the error messages update correctly in the editor for me.
- If I enter all fields (name, email, URL) and close the contact info dialog, the error message count goes to zero (good). If I reopen the contact info dialog, remove the email, then close the dialog, the error count goes to one and is correct in saying a valid email is needed.

Maybe I'm not exactly performing the steps correctly @phantomjinx. And I am also using the "master" code branch to test which might be different than you and could explain some of the behavior differences.

**Comment by EricWittmann** [comment]
For what it's worth, the Contact Info UI has been changed in upstream Apicurio.  So that aspect of this **might** be fixed now.

That said, it sounds like there might be some validation issues where an "empty" email address is being flagged as an invalid one.  So that might need some work.

**Comment by elvisisking** [comment]
I tested the latest contact information UI by using the latest repo code and running a local, dev mode **Apicurio Studio**. As @EricWittmann said, the contact info UI and validation of it has changed. Validation now matches the OpenAPI 2.0 and 3.0 specs where none of the name, email, and URL fields are required are are all independent of each other. Also, when an invalid format for email or URL is entered an appropriate validation message is posted. And when those errors are fixed the appropriate error message is removed.
