### ISSUE TITLE
Change integration import behavior

### ISSUE THREAD

**Issue by mcoker** [syndesisio/syndesis#3420]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
When you import an integration, the integration is automatically imported when you select or drag 'n drop the exported file in the importer.

## Expected behavior
Selecting or dragging/dropping a file in the importer shouldn't automatically import the file. Instead, the file should be staged for import, validated (file type and validity of the exported integration, and whatever else makes sense), and the "Import Results" that are currently shown _after_ importing should be shown at this point.

Instead of a "done" button, we should show "Cancel" and "Import Integration", and clicking "Import Integration" imports the integration and returns you to the integration list with a toast notification indicating that the file has been imported. Cancel would also take you back to the integration list with no notification.

related - https://github.com/syndesisio/syndesis/issues/3402

cc @dongniwang @gashcrumb

**Comment by kahboom** [comment]
I thought this was a feature, not a bug? 😂 I remember discussing with @dongniwang and this was by design.
