### ISSUE TITLE
Update of Syndesis CR should be picked up by the operator

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#3422]
When editing an existing custom resource "Syndesis" and storing it back to OpenShift, then changes (like in `maxIntegrations`) aren't picked up by the operator.

It is expected that, depending on what has changed, the operator will perform the operations needed (like updating a configmap and restarting a pod) to take over the changes.

This might also changes the state model.

And while we are at it, it would be awesome that any change would be recorded in the status section like it happens for other Kubernetes resources.

**Comment by rhuss** [comment]
@heiko-braun this is the other issue I think would be important to include for 7.2

**Comment by claudio4j** [comment]
I think this issue was resolved by #9257 (any updates to configmap may trigger a pod respin). Going to close this one.
