### ISSUE TITLE
Rethink import/export with secrets

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#3423]
See also **https://issues.jboss.org/browse/ENTESB-11458**

## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

We're recurringly stumbling with managing imports/exports of integrations containing secrets (e.g. passwords for database connection). Perhaps we should rethink our approach. Perhaps it would be better to prompt the user for export password and re-encrypt the secret content with that export password that'll also be needed when importing the integration.

## Expected behaviour

No more reports like #3404 #2603 #2602 #2585

## Screenshot

![giphy](https://user-images.githubusercontent.com/1306050/44458936-1827a280-a608-11e8-9615-8893603f147b.gif)

## Tasks involved / Steps to Reproduce

1. On export prompt for a password, decrypt secrets with instance key and re-encrypt with given password
2. On import prompt for a password, decrypt secrets with given password and re-encrypt with instance key

4.

**Comment by gashcrumb** [comment]
+1, it's a mess currently

**Comment by heiko-braun** [comment]
@dhirajsb Is this addressed with your recent work?

**Comment by dhirajsb** [comment]
@heiko-braun the new work is sort of a parallel mechanism that addresses this issue only for the public API. It does not address this issue for the existing import/export UI and related workflow.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11458**
