### ISSUE TITLE
ServiceNow: consider filtering system fields/tables 

### ISSUE THREAD

**Issue by mmelko** [syndesisio/syndesis#3429]
## This is a...

<pre><code>
[x ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
SN connector is currently fetching all available data such as tables, columns etc (system included) which may degrade user experience. For example for selecting table there may be ~1000 tables available which only couple might be useful for for integrator. 

Also during mapping incidents there is generated 90 fields. I believe at least "sys_" fields aren't doable for integrator. 

![screen shot 2018-08-22 at 17 40 44](https://user-images.githubusercontent.com/6814482/44474276-9600a380-a632-11e8-97c5-c232c724208b.png)

## Tasks involved / Steps to Reproduce

1.
2.
3.
4.

**Comment by lburgazzoli** [comment]
This is something the underlying camel component can do but it is not yet exposed to syndesis users as the user experience is not that good as one has to manually list all the needed fields. As this is a common problem when interacting with systems like servicenow or salesforce I think we can do something like:

- allow expert integrators to provide pre-defined data shapes through extensions
- provide a "DataShape Builder" interface to create tailored data shapes so users can filter out fields that are not needed

@gaughan @kcbabo what do you think ?

**Comment by gaughan** [comment]
@lburgazzoli Sounds good!

**Comment by lburgazzoli** [comment]
@gaughan see #3456

**Comment by dongniwang** [comment]
If we have #3456, can we close this one now?  @lburgazzoli

**Comment by lburgazzoli** [comment]
I think so

**Comment by dongniwang** [comment]
Cool, closing now. See #3456 for future updates.
