### ISSUE TITLE
For operator based installation remove image triggers everywhere

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#3432]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Only the operator should carry a redeployment trigger for an image as otherwise updating the streams would update the deployment images, bypassing the upgrade pod. When the operator gets updated via a trigger it will automatically start the update pod. which is a good thing.

**Comment by rhuss** [comment]
That's still important to verify.

**Comment by lgarciaaco** [comment]
This is done since the operator Reconciles and now parses all resources and applies changes. So manually changing any resource (including IS), would do nothing.
