### ISSUE TITLE
Add possibility to create integration sequentionally 

### ISSUE THREAD

**Issue by mmelko** [syndesisio/syndesis#3433]
See also **https://issues.jboss.org/browse/ENTESB-11453**

## This is a...

<pre><code>
[ x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
I feel creating "Start" then "Finish" and then "everything between" isn't very intuitive, especially when creating integrations with 4 and more elements.  Also adding "new finish" (for example some audit, log) during editing integration is complicated. 

## Tasks involved / Steps to Reproduce

1.
2.
3.
4.

**Comment by heiko-braun** [comment]
@gaughan What are your thoughts on this?

**Comment by gaughan** [comment]
+1 for adding flexibility (the default is correct I believe tho)
That being said, I think we have the balance right. @mmelko can you give an example of the first part?
I think I should know the start and finish from step zero.

For the second issue, "new finish" what specifically? Too many clicks etc? Config?

**Comment by mmelko** [comment]
@gaughan I know you know start and finish from beginning, however i believe it feels more natural just adding connection "as message flows" (at least for me:)) in "bigger" integrations like this:
![screen](https://user-images.githubusercontent.com/6814482/44676549-e82b3580-aa33-11e8-803f-bd5315bbf7ca.JPG)

Second part is when you want to add another connection at the end of integration (for example some audit message to broker etc.). it'd be much easier just to have there "+" at the end of integration than delete old finish, add new one and put old before new one.

**Comment by tmielke** [comment]
I think this is a useful feature request (which may require a lot of work). 

When designing Camel routes in Java or XML DSL we also start from the consumer endpoint and then add the next steps and finish with the target endpoint or step. It really feels more natural this way.

**Comment by chirino** [comment]
+1 UXD should be updated to support this.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11453**
