### ISSUE TITLE
Consider adding"number of messages per time period" metric

### ISSUE THREAD

**Issue by mmelko** [syndesisio/syndesis#3434]
See also **https://issues.jboss.org/browse/ENTESB-11457**

## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
Id would be nice if user could see traffic in running integrations and see average throughput. Those informations could be visualised by charts.

## Tasks involved / Steps to Reproduce

1.
2.
3.
4.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11457**
