### ISSUE TITLE
Is telegram connector tech preview?

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#3444]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

Syndesis version: 1.4.5.fuse-710003-redhat-00003

If telegram is tech preview, it has no "Technological preview" label. If it is not tech preview, it has no documentation.

Marking as blocker as it is an easy fix and quite important information which should be visible from UI.

**Comment by heiko-braun** [comment]
Thanks @nicolaferraro
