### ISSUE TITLE
Slack connector - User Story

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#3453]
As a citizen integrator, I want to be able to add a Slack start connector to accept events from my custom slack app that I configure on slack.com(https://api.slack.com/apps/new). I want to monitor a channel for slack messages with by app and consume these via my fuse online integration.
I want to be able to trigger my integration via any/every message.
I would like to use Events API to read messages to a channel:
https://api.slack.com/events-api
https://api.slack.com/events/message

In creating a Slack start connector, I receive my integration url that I can then provide slack.
Slack has specific requirements on the url verification handshake.

DoD

- A slack connector can be added to the start of an integration flow
- Posting a slack message to a subscribed channel can be processed and output to a log file.

**Comment by oscerd** [comment]
Related to #3313

**Comment by heiko-braun** [comment]
I added the user story to the implementation epic. Closing this one
