### ISSUE TITLE
Google Calendar Connector

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#3454]
Google Calendar
As a citizen Integrator I want to be able to use the google calendar Camel component http://camel.apache.org/googlecalendar.html in Fuse Online:

I would like to be able to use the same authentication details if I have already provided for google. 
I would like to be able to configure both:
**start connector** to accept events from my google calendar 
**finish connector** to insert or move event in a calendar

To accept Google Calendar **Poll** events for a start connector, I will configure a google watch url for my calendar https://www.googleapis.com/apiName/apiVersion/resourcePath/watch
I expect  a post message to be sent to my url conforming to google api standard (including the syndesis webhook the event can be sent to) 
I want to monitor a channel (calendar) for new events created and consume these via my fuse online integration.

DoD

- I can create events in google calendar
- I can subscribe to google calendar resources and in turn be notified if an event is created or changed.
- The feature owner has confirmed one of the following:
--There is an initial draft of the user doc for this feature. 
--The writer acknowledges receiving enough information from engineering to write the initial draft of the user doc for this feature.

**Comment by oscerd** [comment]
I believe using Push events is overkilling since we already have a Java API for this https://developers.google.com/calendar/v3/reference/events/watch and we can use the Events Watch 
https://developers.google.com/calendar/quickstart/java

Let me know what do you think, the result should be the same.

**Comment by oscerd** [comment]
Using push notification will be a problem. We'll need to have a domain where we can send the notifications, with a SSL certificate and we'll need to demonstrate we are the owner of that domain, by giving informations or adding html tag in our code (different for each domain). So I don't think is feasible to use push notification at this point, my suggestion is to list the event and filter them by update time. @paoloantinori @gaughan @heiko-braun @kcbabo

**Comment by oscerd** [comment]
More information here: https://developers.google.com/calendar/v3/push

My suggestion is to use a polling approach.

We can think about a general solution, but this would be part of a different issue, google-calendar should avoid using push notifications.

**Comment by oscerd** [comment]
I'll wait for your feedback before I start working on this.

**Comment by heiko-braun** [comment]
I think polling is fine if users have some degree of control how often we poll

**Comment by paoloantinori** [comment]
My suggestion would be to continue with a polling based logic and to start setting up the discussion for an eventually support at Syndesis level per Push based apis.

A quick conversation with engineering pointed out that there are some hard requirements, dictated by the remote service provider, to comply with the service terms.
These go from being able to configure a fixed DNS name and to have your domain available on a valid HTTPS certificate.
Other than that your webpage should include some custom headers in the HEAD section.

This is a broad problem, that we should analyze in details before committing too easily to the delivery of this feature.

**Comment by gaughan** [comment]
Polling is fine with me. I have updated the story accordingly, does not affect DoD

**Comment by oscerd** [comment]
I created the https://issues.apache.org/jira/browse/CAMEL-12784 to track the creation of component for consuming

**Comment by oscerd** [comment]
For the google-connector component we need to be able to specify a date in the ui for start and end date, actually this is not possible and we'll fallback to text.

#3577

**Comment by oscerd** [comment]
About the move operation, do you intend move an event from a calendar to another, or update an event to a different date? In both cases we'll need to get a list of event to show (and this must be limited in some way) or otherwise we need to setup a String field where we can specify the eventId. Get a list of all the incoming events in a calendar is very expensive and we can't list everything in a form field.

**Comment by oscerd** [comment]
Yes, the insert operation will return back the whole event created

**Comment by gaughan** [comment]
Great, string field to specify event id sounds good, thanks Andrea!

**Comment by oscerd** [comment]
ok, just a doubt: did you mean creating the event through Syndesis? Also can you have a  look at the Slack connector issue about splitting in two different connectors? Thanks.

**Comment by gaughan** [comment]
Both, an event created in syndesis or standalone, the event is returned, correct?
We can have a quick call if you like
Slack connector is updated on that thread now.
thanks

**Comment by oscerd** [comment]
#3602

**Comment by oscerd** [comment]
@gaughan Actually the update operation expects an event object as input, and updated version of the event in the calendar, so my suggestion is to add an operation like a get, that will take into account an eventId and calendarId, the use the output of the get as an input for the update and override the content of the event with the stuff coming from the update form action. Is this ok?

**Comment by oscerd** [comment]
Yes get is invokable as a separated operation. If it works I'll go ahead tomorrow

**Comment by oscerd** [comment]
It's a single action like the update one. If we agree on this we can skip the meeting

**Comment by gaughan** [comment]
LGTM!

**Comment by oscerd** [comment]
This can be marked as done.
