### ISSUE TITLE
DataShape providers

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#3456]
See also **https://issues.jboss.org/browse/ENTESB-11545**

## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Connectors such as ServiceNow or Salesforce have the ability to automatically generate data shapes from the source system but this can lead to definitions with a huge list of fields like:

![image](https://user-images.githubusercontent.com/1868933/44644525-bd5dc480-a9d4-11e8-88ad-61124c9be866.png)

For a better user experience we should be able to:

- allow expert integrators to provide pre-defined data shapes through extensions
- provide a "DataShape Builder" interface to create tailored data shapes so users can filter out fields that are not needed

From #3429

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11545**
