### ISSUE TITLE
SAP Concur connector has no technology preview label

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#3457]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Concur is marked as technology preview in documentation and release notes, we should add this label into UI.
Its not really a blocker, but it is very easy to fix and has no regression threats.

**Comment by tplevko** [comment]
Merged docs update: https://github.com/syndesisio/syndesis/pull/3452/files

**Comment by gashcrumb** [comment]
Just needs `tech-preview: "true"` to the metadata map for that connector looks like.

**Comment by tplevko** [comment]
@heiko-braun I don't know how it looks with the images rebuild, but could this be included in 1.4.x?

**Comment by heiko-braun** [comment]
yes

**Comment by rhuss** [comment]
I mean that one #3292. My question actually is whether its save to add this to the json file. Never mind, I'm going to create a PR and it would be super awesome @KurtStam if you could give it a quick review then.

**Comment by rhuss** [comment]
Fixed with #3553 , PR for master is still pending in #3554

**Comment by rhuss** [comment]
As the issue has been reported against 7.1.0 I'm going to close this issue. On master, for 7.2 is also already could be that the concur connector moves out of the tech preview stage.
