### ISSUE TITLE
Use of constants in the datamapper is broken

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#3462]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[*] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
If constants are used in the datamapper step their value always ends up 'null'.

## Expected behavior
To use the value of the defined constant

## Screenshot
<img width="955" alt="screen shot 2018-08-27 at 6 38 19 pm" src="https://user-images.githubusercontent.com/35576/44690343-74cff680-aa28-11e8-8229-6c47d2e28dab.png">
<img width="920" alt="screen shot 2018-08-27 at 6 38 35 pm" src="https://user-images.githubusercontent.com/35576/44690344-74cff680-aa28-11e8-9be1-ff770eaa62ec.png">

Note how 'first_name' is 'null' in the second screenshot.

**Comment by KurtStam** [comment]
[MapTest-export.zip](https://github.com/syndesisio/syndesis/files/2325875/MapTest-export.zip)

**Comment by heiko-braun** [comment]
@igarashitm Can you add your thoughts to this?

**Comment by igarashitm** [comment]
That was a bug atlasmap/atlasmap#544 and we already have it fixed in Syndesis with #3518. Closing.
