### ISSUE TITLE
[Upgrade] Syndesis operator uses hardcoded "latest" for upgrade pod tag

### ISSUE THREAD

**Issue by avano** [syndesisio/syndesis#3463]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Currently, by default, the syndesis specifies upgrade container tag "latest": https://github.com/syndesisio/syndesis/blob/master/install/syndesis.yml#L1635 

But for the community version in the docker hub, there is no such tag: https://hub.docker.com/r/syndesis/syndesis-upgrade/tags/ 

Therefore it causes upgrade to fail because of missing image: 

`Failed to pull image "docker.io/syndesis/syndesis-upgrade:latest": rpc error: code = Unknown desc = Tag latest not found in repository docker.io/syndesis/syndesis-upgrade`

I think the version should be changed from latest to <operator_version> somewhere in the process of building the operator image.

cc @rhuss 

## Tasks involved / Steps to Reproduce

1.
2.
3.
4.

**Comment by rhuss** [comment]
Yes, I agree. I'm just about to add creating the upgrade pod also to the "syndesis" script and add it to our circle build so that it gets build on every commit to master, too.

**Comment by rhuss** [comment]
syndesis-upgrade:latest is now build which each commit on master --> https://hub.docker.com/r/syndesis/syndesis-upgrade/tags/

**Comment by rhuss** [comment]
Still missing: Add a` -m upgrade` to the "syndesis" build script. @avano however, you could already start to check whether this 'latest' image which is pushed now to docker hub fits your bill.

**Comment by mmelko** [comment]
@rhuss if I understand it correctly the preferred way how to upgrade syndesis/fuse-online is to update operator to desired version (e.g from 1.4.8 to 1.4.10) and operator should update syndesis to 1.4.10. However currently "latest" version is hard-code, so it really doesn't matter to what version I upgrade the operator. It will always try to upgrade to "latest".  Wouldn't be better to set version of syndesis-upgrade image to same as operator is ?

**Comment by mmelko** [comment]
@rhuss any thoughts ?

**Comment by rhuss** [comment]
@mmelko you are right, there is an issue in the template we provide. The operator, when processing the upgrade, will fill in a template parameter [SYNDESIS_VERSION](https://github.com/syndesisio/syndesis/blob/1f032d6259751090ab8355b62fb7760c66c3ba7b/install/operator/pkg/syndesis/template/upgrade.go#L40), which is the same as the operator version. This should be used as the tag in the [template](https://github.com/syndesisio/syndesis/blob/1f032d6259751090ab8355b62fb7760c66c3ba7b/install/syndesis.yml#L1671) but it is not. I will send a PR soon to fix that.

But this still doesn't help in upgrading from an older 'latest' to a newer 'latest' as this is not supported (the versions have to differ).

**Comment by rhuss** [comment]
Well, I was a bit too fast. Actually when we release the template, the `{{ Tags.Upgrade }}` will be set to the released version in the template (like [here](https://github.com/syndesisio/syndesis/blob/1.4.10/install/syndesis.yml#L1664)). The operator which uses this template will exactly pick that version. that there is still 'latest' in the released templates, that the issue.

Let me find out why ...

**Comment by avano** [comment]
hi @rhuss , any update on the PR?

**Comment by rhuss** [comment]
Sorry just back from PTO. Have to check back the status and wonder why noone picked up the PR for a review.
