### ISSUE TITLE
[Upgrade] Upgrade s2i image stream tag automatically?

### ISSUE THREAD

**Issue by avano** [syndesisio/syndesis#3464]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Currently the upgrade scripts do not upgrade configmaps by default: https://github.com/syndesisio/syndesis/blob/master/tools/upgrade/steps/upgrade_40_update_resources#L45-L46

Now when I deploy `1.5.4-20180827` for example, the s2i image stream is defined in `syndesis-server-config` configmap:
https://github.com/syndesisio/syndesis/blob/1.5.4-20180827/install/syndesis.yml#L257

When I upgrade to 1.5.4-20180828, this value in the config map is not changed (because the upgrade script does not change config maps by default). In current situation we should provide the migration script for the config map (we do for prod builds now) for each daily release to upgrade this one single value.

It is just my thought to upgrade it automatically using the upgrade script, or get rid of the value in config map and let the default value be the same tag as syndesis server? No idea if that is possible to do :-)

cc @rhuss @zregvart

## Tasks involved / Steps to Reproduce

1.
2.
3.
4.

**Comment by rhuss** [comment]
I completely agree that we either should update this version by default on every update or think about a solution to not reference that image from the configuration (e.g. by using an environment variable in the deployment config of syndesis-server). 

I think the later is the better solution as one could consider the s2i image to use as part of the installation at not something a user should be able to change in a configmap.

@zregvart @avano ok to move the information to an environment variable in the template ?

**Comment by avano** [comment]
thank you @rhuss ! :-)

**Comment by rhuss** [comment]
Sorry no progress yet, and I can't pick it up in the 7.3 time frame.  Happy for any help, I think the comments on https://github.com/syndesisio/syndesis/issues/3464#issuecomment-418264599 are still valid.

**Comment by avano** [comment]
done in https://github.com/syndesisio/syndesis/pull/5161
