### ISSUE TITLE
Refactor connector-generator for using it in API provider

### ISSUE THREAD

**Issue by nicolaferraro** [syndesisio/syndesis#3467]
This includes:
- Making sure API consumer and provider are better integrated in the common api-generator module
- Trying to create a uniform API
- Add tests for the API endpoints

**Comment by zregvart** [comment]
We probably only need tests, but majority of the implementation is here. Right @nicolaferraro?

**Comment by nicolaferraro** [comment]
Right, it's ok closing this.
