### ISSUE TITLE
Update metrics and logs to support multi-flows (no UI)

### ISSUE THREAD

**Issue by nicolaferraro** [syndesisio/syndesis#3470]

**Comment by gashcrumb** [comment]
Yeah, we've no requirement at this stage to separate out activity by flow, and I think this would require some design adjustments to the page.  The user probably would want some way to narrow down all of the activities to the subset of activities related to a given operation.

@dongniwang @sjcox-rh FYI

**Comment by lburgazzoli** [comment]
@nicolaferraro I did comment without refreshing the page so I didn't see your comment. Yes I think this can be safely moved outside the epic
