### ISSUE TITLE
Expose Open API data for discovery through annotation

### ISSUE THREAD

**Issue by nicolaferraro** [syndesisio/syndesis#3471]
We should export the swagger/openapi specification in the integration metadata so that it can be added to the proper annotation as part of #3504. Other metadata (such as paths and protocols) should be already present.

**Comment by heiko-braun** [comment]
Closing as duplicate of #3504. @nicolaferraro please reopen if you think it's a different issues

**Comment by nicolaferraro** [comment]
Yes, stated as is it's a duplicate. I was leaving it because we currently don't publish the swagger doc in a way that can be read by 3scale. So I'm reopening it and changing the description.

**Comment by zregvart** [comment]
Implemented via #3683
