### ISSUE TITLE
Convert old-style integrations into flows (backward compatibility)

### ISSUE THREAD

**Issue by nicolaferraro** [syndesisio/syndesis#3472]

**Comment by lburgazzoli** [comment]
@gashcrumb @nicolaferraro I'm gogin to support backward compatibility by performing a similar thing than the "actualization" of the integrations when the UI retrieve them so that when onld integrations are saved they are converted to the new style. 

Is that enough ?

**Comment by gashcrumb** [comment]
I think that'd be great, ideally I think the UI would probably just switch over to just creating integrations using the new model as part of all of this.

**Comment by nicolaferraro** [comment]
:+1: , that seems also simpler than performing DB migration and DB rollback on Syndesis upgrade.

**Comment by lburgazzoli** [comment]
yes, less work for you :)
