### ISSUE TITLE
Add API provider to Syndesis UI

### ISSUE THREAD

**Issue by nicolaferraro** [syndesisio/syndesis#3473]
Create tasks out of the API provider designs and user story.

**Comment by nicolaferraro** [comment]
@gashcrumb, @riccardo-forina this is a placeholder that needs to be broken down into smaller issues.

**Comment by gashcrumb** [comment]
Cool thanks!  We'll go through the designs there and create some tasks

**Comment by dongniwang** [comment]
@gashcrumb @riccardo-forina - please let me know if you have any questions. Latest design can be found via the ux tracker: https://syndesisio.github.io/syndesis-ux/

**Comment by gashcrumb** [comment]
Defined some tasks based on the designs, think it's a good starting point, so closing this.
