### ISSUE TITLE
Update "save or add step" page to implement "add flow/integration" page based on design

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#3476]
Update [this](https://github.com/syndesisio/syndesis/tree/master/app/ui/src/app/integration/edit-page/save-or-add-step) page to suit [this](https://redhat.invisionapp.com/share/3CNPQLOKAEW#/screens/316356339) design.  This page in general is where you wind up after completing a sequence of pages in the editor.

**Comment by riccardo-forina** [comment]
The updated design is here https://redhat.invisionapp.com/share/CBNWDY58AHG#/screens/318306622

We just need a link back to the Operations page, the inner content is the same as with a normal flow.
