### ISSUE TITLE
Implement "configure return path" page based on designs

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#3477]
[This](https://redhat.invisionapp.com/share/3CNPQLOKAEW#/screens/316356340) design, think it'll be a new page.  This is just for the page, #3487 is more related to adjusting the editor's current work flow to handle having the finish connection instead be the return path indicator.

**Comment by riccardo-forina** [comment]
It looks like this is already handled by Syndesis because of how things have been set up in the integration object. I guess we can close this?

**Comment by gashcrumb** [comment]
I figure this tracks having the return icon in the IVP as well as having the configuration page available to set the return code when you click on the return icon (the ending connection).  But if you don't need this issue to track it or want to create new ones that's fine too and we can close this one.
