### ISSUE TITLE
Connections Page - Icons

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#3488]
## This is a...

<pre><code>
[x ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

On the connections page it is visually confusing which connectors are configured or not. The use of grey and colour is not consistent.
Two issues:
1) The use of grey and colour should no longer be used
2) Distinguish clearly between connections and connectors
3) The card for new webhook in the screenshot should be consistently in the same place,(grouped at the start or end?)

![image](https://user-images.githubusercontent.com/674767/44747067-29762080-aada-11e8-930b-4acf1f045720.png)

**Comment by dongniwang** [comment]
Just wanted to provide a quick check in here: 

~~1. The use of grey and colour should no longer be used~~ - This is done as all OOTB connectiors/connections icon have colors. 
2. Distinguish clearly between connections and connectors - This could be something we can explore if we have time in the upcoming sprints. 
3. The card for new webhook in the screenshot should be consistently in the same place,(grouped at the start or end?) - Goes hand in hand with 2. 

Possibly part of #3661.
