### ISSUE TITLE
Google Drive Connector

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#3490]
See also **https://issues.jboss.org/browse/ENTESB-11528**

Google Drive:
As a citizen Integrator I want to be able to use the google drive Camel component http://camel.apache.org/googledrive.html in Fuse Online:

II would like to be able to use the same authentication details if I have already provided for google. I would like to be able to configure both:
start connector to accept events from my google drive 
finish connector to insert or update a file in a drive

To accept Google Drive Push events for a start connector, I will configure a google watch url for my drive
 https://www.googleapis.com/apiName/apiVersion/resourcePath/watch
I expect  a post message to be sent to my url conforming to google api standard (including the syndesis webhook the event can be sent to) 
I want to monitor a channel (drive) for new events created and consume these via my fuse online integration.

DoD

- I can add documents to google drive.
- I can delete documents in google drive.
- I can edit documents in google drive.
- I can subscribe to google drive resources and in turn be notified if an event is created or changed.
- The feature owner has confirmed one of the following:
--There is an initial draft of the user doc for this feature. 
--The writer acknowledges receiving enough information from engineering to write the initial draft of the user doc for this feature. 

# Related Resources

- https://developers.google.com/drive/api/v3/about-sdk

**Comment by oscerd** [comment]
As we did for google-mail component, we will need to write a new component for google-drive for consuming specific stuff.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11528**
