### ISSUE TITLE
FHIR Connector

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#3491]
See also **https://issues.jboss.org/browse/ENTESB-11527**

FHIR Connector
As an expert healthcare IT Integrator, I want to configure and use  a FHIR connector that can connect and access a FHIR server. In configuring the connector I want to provide my OAuth credentials and server url settings. I also want to choose the the endpoint prefix( in this case read)
I want to be able to search and read records from a FHIR server.

Camel component:
https://github.com/apache/camel/blob/master/components/camel-fhir/camel-fhir-component/src/main/docs/fhir-component.adoc

DoD
I can successfully connect to a FHIR server with FHIR connector.
I can search and read, validate, create and delete FHIR records.
The feature owner has confirmed one of the following:

- There is an initial draft of the user doc for this feature. 
- The writer acknowledges receiving enough information from engineering to write the initial draft of the user doc for this feature. 

Action names:

transaction
update
Validate
capabilities
create
delete
history
Search
Read

**Comment by johnpoth** [comment]
I'll start working on this

**Comment by heiko-braun** [comment]
Thanks @johnpoth !

**Comment by johnpoth** [comment]
blocked by https://github.com/atlasmap/atlasmap/issues/577

**Comment by johnpoth** [comment]
hi @gaughan @heiko-braun, would it be possible to create a new FHIR Connector project and have rights to create new tasks? The issue is larger than anticipated. Thanks!

**Comment by heiko-braun** [comment]
@johnpoth Can you break down the work into more manageable chunks? A simple list of bullets would suffice ...

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11527**
