### ISSUE TITLE
API connector wizzard has no back buttons

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#3495]
## This is a...

<pre><code>
[x ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

User can spend half an hour editing operations in apicurio gui, then saves and go next to specify security just to realize that he/she forgot about security settings and there is no way how to go back to apicurio editor and add it - has to cancel the creation and edit everything again and pray to not forget anything

## Expected behavior

User should be able to go back from any point when creating API connector.

**Comment by elvisisking** [comment]
Agree @mcada! This is something that is really needed.

**Comment by elvisisking** [comment]
Work done in #3569
