### ISSUE TITLE
ApicurIO GUI - context menu disappearing 

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#3496]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Context menu keeps disappearing. I am not sure if it is expected or not, because if I hold right click it stays open. Creating this issue just to be sure to ask anyone who knows better.

## Expected behavior

Menu should be visible when opened until user clicks somewhere else or selects an option.

## Screenshot

![out](https://user-images.githubusercontent.com/14313995/44775328-a6a2a380-ab75-11e8-824e-34649da558e5.gif)

## Tasks involved / Steps to Reproduce

1. Open apicurio studio
2. Right click on any operation
3.
4.

**Comment by paoloantinori** [comment]
@riccardo-forina  am I wrong or this might be familiar to you? at least the pattern of these problems?

**Comment by riccardo-forina** [comment]
Ahah yes, it sounds familiar indeed. I can't reproduce the problem though. Steps I took:
- click on Customization
- click on Create API Connection
- use a URL 
- click on Review/Edit
- right click on an operation on the left

The menu just stays open for me.

**Comment by EricWittmann** [comment]
The menu should **definitely** stay open!  :)  What browser/OS are you using?  Is it reproducible for you?  I can't think of anything that would cause the menu to disappear like that... at least not off the top of my head.

**Comment by mcada** [comment]
@EricWittmann I am on fedora and use firefox, I don't even have to move my mouse, it just disappears unless I hold the mouse button. 100% reproducible.

**Comment by riccardo-forina** [comment]
Ah, gotcha. It's a Firefox specific issue, I have been able to reproduce it using FF 52 and FF Dev Edition (63)

**Comment by riccardo-forina** [comment]
Actually, I'm running macOS. I don't have any other OS handy, but I started downloading [Edge test VM](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/). Once done I can try to reproduce the issue with it too.

**Comment by EricWittmann** [comment]
OK this is interesting.  

Is there an instance of syndesis that I can use to test this myself?  Obviously all of my testing occurs in Apicurio community version.  

I'm using Windows 10 and have tested with Firefox, Chrome, Edge, and IE 11.  All are good for me.

**Comment by EricWittmann** [comment]
OK @riccardo-forina gave me access to syndesis and I've tested using all the browsers I have.  They all work fine for me.

So I asked a colleague to test using Apicurio Studio (live version) + Macos + Firefox and he was able to reproduce the issue.  So it's not limited to Apicurio embedded in Syndesis.  But it is limited by OS and browser.

FYI :)

**Comment by EricWittmann** [comment]
Can I ask what sort of machines you guys are using?  I'm using a workstation and my colleague tested using a macbook pro.  He seems to think it might be related to the latter.  Something about long clicking vs. short clicking?

**Comment by riccardo-forina** [comment]
MBPro here too

**Comment by riccardo-forina** [comment]
According to [this](https://github.com/Apicurio/apicurio-studio/pull/434) It looks like this will be fixed with apicurio v2.16. Am I right @EricWittmann?

**Comment by EricWittmann** [comment]
Actually yes I think so - can you give it a try on studio.apicur.io right now?  Version 0.2.16.Final is up there now.  It might be fixed!  :)  Thanks for keeping an eye on this issue.

**Comment by heiko-braun** [comment]
@riccardo-forina Do you see any risks updating to a newer apicurio version? I wonder if we should do this in 7.3 instead.

**Comment by riccardo-forina** [comment]
It's a minor version, so there should be no breaking changes. Can you confirm @EricWittmann?

By the way, I'm not able to reproduce the issue on my system, nor with Chrome not FF, and this with v2.15 both on a local install and on staging.

@mcada can you still reproduce it?

**Comment by mcada** [comment]
Looks like it was fixed in recent apicurito update, can't reproduce the issue anymore.

**Comment by EricWittmann** [comment]
I can confirm there are no breaking changes.

**Comment by EricWittmann** [comment]
@mcada thanks for confirming.  I'm going to close this issue as fixed as soon as I can track down the commit that fixed it. :)

**Comment by EricWittmann** [comment]
Oh right, nevermind - I forgot this was a Syndesis repository issue.  I'll link to the Apicurio commit but I obviously won't close this issue.  Someone else can do that.

**Comment by riccardo-forina** [comment]
I guess we can close this :)

**Comment by tplevko** [comment]
@mcada please verify

**Comment by mcada** [comment]
Verified with cf0678687fea42c1d506204aed3009b76b05f829
