### ISSUE TITLE
Apicurio GUI - info box not showed properly

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#3497]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Scrolling to the end of the page when editing operation in apicurio studio and opening security tooltip does not show the whole help box.

## Expected behavior

Whole help box should be visible.

## Screenshot

![screenshot_20180829_103107](https://user-images.githubusercontent.com/14313995/44775993-54628200-ab77-11e8-96e1-2109dd0a8c39.png)

## Tasks involved / Steps to Reproduce

1.
2.
3.
4.

**Comment by mcada** [comment]
This screenshot is better :D
![screenshot_20180829_104153](https://user-images.githubusercontent.com/14313995/44776372-39dcd880-ab78-11e8-970b-0fb1bd2745c1.png)

**Comment by elvisisking** [comment]
This has been fixed in the `master` branch of Apicurio Studio. If the info box extends beyond the bottom of the window, the user will now be able to scroll to see it all. See Apicurio/apicurio-studio#446.

**Comment by zregvart** [comment]
Most likely fixed via #3647

**Comment by mmajerni** [comment]
Hi, could you provide more information about the fix? I cannot invoke the help box (there is no "i" icon) 
Is this the fix?

**Comment by tplevko** [comment]
@mcada can we then mark this issue as verified and close it?

**Comment by mcada** [comment]
Yes :)
