### ISSUE TITLE
Figure out the input and output data for the Template Step

### ISSUE THREAD

**Issue by phantomjinx** [syndesisio/syndesis#3498]
The template step needs to integrate with other steps and connections hence it needs to both expect certain parameters/variables as inputs and provide expected data as output. It is not expected that any other steps/connections needs changing in order to allow for this step.

**Comment by phantomjinx** [comment]
The template step using mustache (and eventually freemarker / velocity) can take advantage of these camel modules:
- [mustache](https://camel.apache.org/mustache.html);
- [freemarker](https://camel.apache.org/freemarker.html);
- [velocity](https://camel.apache.org/velocity.html);

If a template and necessary properties/values provided as inputs then this configuration can be delegated to appropriate module above and its output utilised accordingly.

**Comment by phantomjinx** [comment]
@igarashitm 

Hey, are you able to help provide a datamapper json file syntax for use with a [unit test](https://github.com/phantomjinx/syndesis/commit/98a37782f84e0ee98210433760e51c88d198d4c2#diff-2eaa0835c2543b31d8824395c52cf3a4R75)I am writing, please?

Essentially, I want to pass in 'some' simple data map it to what the new template-step expects, ie. all mapped properties added to exchange.in.headers. Already begun writing a [json mapping file](https://github.com/phantomjinx/syndesis/commit/98a37782f84e0ee98210433760e51c88d198d4c2#diff-7a86814a49d7132f8ff3c254d41556c2R1) but really not sure of the syntax.

**Comment by igarashitm** [comment]
Hi @phantomjinx, there're a few here, 3 .json files used for camel-atlasmap test
https://github.com/atlasmap/atlasmap/tree/master/camel/src/test/resources

But your example looks better for your purpose. One thing needs to be fixed would be that the `dataSource/id` must match with `mappings/mapping/*Field/docId`.

**Comment by phantomjinx** [comment]
@igarashitm,
That's got me inching forward!

Can you tell me if it is possible to map from a json payload, eg.
> { time: "10:00", name: "Bob", text: "Hello, how are you?" }

to a java Map and if so how would the mapping syntax look?

In order for the templating step to work I need the input message body to contain a java object something like:
```
Map<String, String> msg = new HashMap<>();
msg.put("time", "10:00");
msg.put("name", "Bob");
msg.put("text", "Hello, how are you?");
```
then a template property of {{body.name}} or {{body.text}} will be correctly populated.

**Comment by igarashitm** [comment]
Unfortunately `java.util.Map` support (atlasmap/atlasmap#142) is not yet implemented. Could it be possible to parse that JSON directly in the template step by using e.g. jackson? Since AtlasMap focuses on field-by-field mapping, it's not really convenient for marshall/unmarshall kind of thing.

**Comment by igarashitm** [comment]
You can expect JSON by specifying `json-schema` as a `inputDataShape.kind` of template step. That's going to be a dynamic data shape as it's determined from tempalte step configuration. Then user can add a datamapper step before template step. Template step then should be able to read that JSON and create a java.util.Map in a pre-processor like stuff Syndesis has. That's other connectors do today IIRC.

**Comment by phantomjinx** [comment]
@igarashitm 
Nice idea! Sorted both the basic and iterative versions of the unit tests now.
Thanks.

**Comment by phantomjinx** [comment]
Input: JSON object, eg.
```
{
  "name" : "Bob",
  "course" : [ {
    "name" : "Mathematics"
  }, {
    "name" : "English"
  }, {
    "name" : "Chemistry"
  } ],
  "text" : "Will be going to the University of Southampton."
}
```

This is converted into a java HashMap using Jackson's ObjectMapper:
```
name="Bob"
course=[{name=Mathematics}, {name=English}, {name=Chemistry}]  // ArrayList of Maps
text="Will be going to the University of Southampton."
```

Template:
```
{{body.name}} passed the following courses:
{{#body.course}}
* {{name}}
{{/body.course}}
{{body.text}}
```

Output:
```
Bob passed the following courses: 
* Mathematics
* English
* Chemistry
Will be going to the University of Southampton.
```

@gaughan

**Comment by gaughan** [comment]
Mawr!
