### ISSUE TITLE
K8s service annotations - Allow User to override default service metadata

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#3503]
SubTask for #3407. After project generation, allow the user to override the metadata. 

I'm not sure when the user is allowed to override (create or post-create) or if we'd have a UI for this, or else the user may need to do this in the maven pom for the project.

**Comment by zregvart** [comment]
From what I understand the metadata here means labels and annotations needed for the API based integration to be exposed.

Are we expecting citizen integrators to know this level of detail? If so wouldn't then this be something that the expert integrator performs, perhaps by modifying the OpenShift objects (Service or such?).

**Comment by heiko-braun** [comment]
This is irrelevant for Fuse Online as their is no manual intervention required and planned.
