### ISSUE TITLE
K8s service annotations - create annotations at deploy time

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#3504]
SubTask for #3407.  When the service is published, add the kubernetes service annotations based on the metadata stored in the project.

**Comment by zregvart** [comment]
@gaughan I need a bit of clarification here.

The current implementation of API provider epic will expose the API-based integration by creating OpenShift Route and Service, much in the same way the WebHook connector is implemented.

If we leave it like this and add labels/annotations then 3scale discovery will pick up the Service and expose it via 3scale as well. So now we'll have the API-based integration exposed via OpenShift Route and via 3scale.

Questions:
 - Do we wish the API-based integration to be exposed via OpenShift Route and via 3scale at the same time? I'm guessing just via 3scale.
 - Do the users have the choice over the mechanism the API-based integration is exposed, so user chooses either OpenShift Route or 3scale based exposure?
 - Does the 3scale integration have any bearing on the WebHook connector?

**Comment by gaughan** [comment]
@kcbabo for integration visibility

Do we wish the API-based integration to be exposed via OpenShift Route and via 3scale at the same time? I'm guessing just via 3scale.
_Just 3scale, I believe._

Do the users have the choice over the mechanism the API-based integration is exposed, so user chooses either OpenShift Route or 3scale based exposure?
_No choice._

Does the 3scale integration have any bearing on the WebHook connector?
_No, doesn't include the discovery of webhooks._

**Comment by kcbabo** [comment]
> Do we wish the API-based integration to be exposed via OpenShift Route and via 3scale at the same time? I'm guessing just via 3scale.
> Just 3scale, I believe.

If possible, I'd like this to be an optional choice for the user in the integration configuration.  We can default to not creating the route, but have a checkbox option the user can select to expose the API directly through a route.  I'm thinking about development and testing phases where you might want to interact with the API directly. 

> Do the users have the choice over the mechanism the API-based integration is exposed, so user chooses either OpenShift Route or 3scale based exposure?
> No choice.

So I'd actually vote for a choice here.  Aside from my reasoning above, we don't have 3scale pre-installed in our eval cluster and a customer may not have it in their environment.  I agree 100% that the default/recommended path is to protect with 3scale, but makes sense to me to have a separate option.

> Does the 3scale integration have any bearing on the WebHook connector?
> No, doesn't include the discovery of webhooks.

Agreed, but if we do go with a checkbox option, then we might want to consider doing something similar for webhook.

**Comment by zregvart** [comment]
@gaughan @kcbabo for 7.2 we'll have a backend configuration option (environment variable) determine if we'll export the integration via 3scale (Service + service discovery annotations/label) or via OpenShift (Route + Service).

There's follow-up work on getting this option in the hands of the users in #3708.
