### ISSUE TITLE
Bug with transformation after a Timer connector

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis#3506]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)[
[x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

The UI fails if you try to apply any operation after a  Timer connector.

## Screenshot
![screenshot from 2018-08-29 16-53-16](https://user-images.githubusercontent.com/1520602/44795904-1895df80-abac-11e8-820d-55124cfc61bd.png)

## Tasks involved / Steps to Reproduce

1.  create a simple integration from timer to log
2. add an intermediate Simple filter step
3.
4.

<details>
  <summary><b>Click to expand</b></summary>
<pre><code>
TypeError: "this.getPreviousStepsWithDataShape(...).reverse(...)[0] is undefined"
getPreviousStepWithDataShapehttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/10.c03fb1e51e50fa5c4409.js:1:15919loadFormhttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/10.c03fb1e51e50fa5c4409.js:1:58130routeSubscriptionhttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/10.c03fb1e51e50fa5c4409.js:1:59262__tryOrUnsubhttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.4b6f2a37458cb8a6e58c.js:1:52947nexthttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.4b6f2a37458cb8a6e58c.js:1:52089_nexthttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.4b6f2a37458cb8a6e58c.js:1:51121nexthttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.4b6f2a37458cb8a6e58c.js:1:50804_nexthttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.4b6f2a37458cb8a6e58c.js:1:43796nexthttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.4b6f2a37458cb8a6e58c.js:1:50804_subscribehttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.77eef8c1bdeef6a93ae7.js:1:390133_trySubscribehttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.4b6f2a37458cb8a6e58c.js:1:45108_trySubscribehttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.77eef8c1bdeef6a93ae7.js:1:875146subscribehttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.4b6f2a37458cb8a6e58c.js:1:44894callhttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.4b6f2a37458cb8a6e58c.js:1:43477subscribehttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.4b6f2a37458cb8a6e58c.js:1:44812ngOnInithttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/10.c03fb1e51e50fa5c4409.js:1:59032ahttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.77eef8c1bdeef6a93ae7.js:1:639733ahttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.77eef8c1bdeef6a93ae7.js:1:639133ahttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.77eef8c1bdeef6a93ae7.js:1:638031Slhttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.77eef8c1bdeef6a93ae7.js:1:649126buhttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/10.c03fb1e51e50fa5c4409.js:1:300551updateDirectiveshttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.77eef8c1bdeef6a93ae7.js:1:645907Xahttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.77eef8c1bdeef6a93ae7.js:1:637679ilhttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.77eef8c1bdeef6a93ae7.js:1:644626rlhttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.77eef8c1bdeef6a93ae7.js:1:644289Xahttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.77eef8c1bdeef6a93ae7.js:1:637704ilhttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.77eef8c1bdeef6a93ae7.js:1:644626nlhttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.77eef8c1bdeef6a93ae7.js:1:644024Xahttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.77eef8c1bdeef6a93ae7.js:1:637826ilhttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.77eef8c1bdeef6a93ae7.js:1:644626rlhttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.77eef8c1bdeef6a93ae7.js:1:644289Xahttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.77eef8c1bdeef6a93ae7.js:1:637704ilhttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.77eef8c1bdeef6a93ae7.js:1:644626rlhttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.77eef8c1bdeef6a93ae7.js:1:644289Xahttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.77eef8c1bdeef6a93ae7.js:1:637704ilhttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.77eef8c1bdeef6a93ae7.js:1:644626nlhttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.77eef8c1bdeef6a93ae7.js:1:644024Xahttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.77eef8c1bdeef6a93ae7.js:1:637826detectChangeshttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.77eef8c1bdeef6a93ae7.js:1:619201tickhttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.77eef8c1bdeef6a93ae7.js:1:574630tickhttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.77eef8c1bdeef6a93ae7.js:1:574591nexthttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.77eef8c1bdeef6a93ae7.js:1:572965invokehttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.4b6f2a37458cb8a6e58c.js:1:9337onInvokehttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.77eef8c1bdeef6a93ae7.js:1:564145invokehttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.4b6f2a37458cb8a6e58c.js:1:9264runhttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.4b6f2a37458cb8a6e58c.js:1:4497runhttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.77eef8c1bdeef6a93ae7.js:1:564852nexthttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.77eef8c1bdeef6a93ae7.js:1:572942ohttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.77eef8c1bdeef6a93ae7.js:1:562669__tryOrUnsubhttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.4b6f2a37458cb8a6e58c.js:1:52947nexthttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.4b6f2a37458cb8a6e58c.js:1:52089_nexthttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.4b6f2a37458cb8a6e58c.js:1:51121nexthttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.4b6f2a37458cb8a6e58c.js:1:50804nexthttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.77eef8c1bdeef6a93ae7.js:1:874577emithttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.77eef8c1bdeef6a93ae7.js:1:562435ynhttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.77eef8c1bdeef6a93ae7.js:1:565301onHasTaskhttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.77eef8c1bdeef6a93ae7.js:1:564290hasTaskhttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.4b6f2a37458cb8a6e58c.js:1:10331_updateTaskCounthttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.4b6f2a37458cb8a6e58c.js:1:10598_updateTaskCounthttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.4b6f2a37458cb8a6e58c.js:1:6780runTaskhttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.4b6f2a37458cb8a6e58c.js:1:5400vhttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.4b6f2a37458cb8a6e58c.js:1:12241invokeTaskhttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.4b6f2a37458cb8a6e58c.js:1:11142ghttps://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.4b6f2a37458cb8a6e58c.js:1:22032_https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.4b6f2a37458cb8a6e58c.js:1:22264 main.77eef8c1bdeef6a93ae7.js:1:2603073
zUnb/At</t.prototype.log
https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.77eef8c1bdeef6a93ae7.js:1:2603073
zUnb/At</t.prototype.handleError
https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.77eef8c1bdeef6a93ae7.js:1:2602971
next
https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.77eef8c1bdeef6a93ae7.js:1:570878
CcnG/fn</t.prototype.subscribe/o<
https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.77eef8c1bdeef6a93ae7.js:1:562669
FFOo/l</e.prototype.__tryOrUnsub
https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.4b6f2a37458cb8a6e58c.js:1:52947
FFOo/l</e.prototype.next
https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.4b6f2a37458cb8a6e58c.js:1:52089
FFOo/f</e.prototype._next
https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.4b6f2a37458cb8a6e58c.js:1:51121
FFOo/f</e.prototype.next
https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.4b6f2a37458cb8a6e58c.js:1:50804
K9Ia/d</t.prototype.next
https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.77eef8c1bdeef6a93ae7.js:1:874577
CcnG/fn</t.prototype.emit
https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.77eef8c1bdeef6a93ae7.js:1:562435
onHandleError/<
https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.77eef8c1bdeef6a93ae7.js:1:564455
0TWp/</</u</t.prototype.invoke
https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.4b6f2a37458cb8a6e58c.js:1:9337
0TWp/</</i</e.prototype.run
https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.4b6f2a37458cb8a6e58c.js:1:4497
CcnG/hn</e.prototype.runOutsideAngular
https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.77eef8c1bdeef6a93ae7.js:1:565164
onHandleError
https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/main.77eef8c1bdeef6a93ae7.js:1:564417
0TWp/</</u</t.prototype.handleError
https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.4b6f2a37458cb8a6e58c.js:1:9417
0TWp/</</i</e.prototype.runTask
https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.4b6f2a37458cb8a6e58c.js:1:5242
0TWp/</</c</e.invokeTask
https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.4b6f2a37458cb8a6e58c.js:1:11106
e/this.invoke<
https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.4b6f2a37458cb8a6e58c.js:1:10991
u/n.args[0]
https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/polyfills.4b6f2a37458cb8a6e58c.js:1:26294

</code></pre>
</details>

```json
{"componentScheme":"timer","inputDataShape":{"kind":"none"},"outputDataShape":{"kind":"none"},"propertyDefinitionSteps":[{"description":"Period","name":"Period","properties":{"period":{"componentProperty":false,"defaultValue":"60000","deprecated":false,"description":"Period","labelHint":"Delay between scheduling (executing).","displayName":"Period","javaType":"long","kind":"parameter","required":true,"secret":false,"type":"duration"}}}],"configuredProperties":{"timerName":"syndesis-timer"},"_meta":{}}
```

**Comment by gashcrumb** [comment]
I guess the basic filter step probably shouldn't be available since timer doesn't have a data shape?
