### ISSUE TITLE
[Operator] -registry seems to be ignored, upgrade image always pulled from docker.io

### ISSUE THREAD

**Issue by avano** [syndesisio/syndesis#3515]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

When `-registry` argument is used in the operator image, it seems to be ignored. We have currently `fuse-online-operator:1.1-4` image that specifies our docker registry:

```
"Entrypoint": [
                "/usr/local/bin/syndesis-operator",
                "-template",
                "/conf/syndesis-template.yml",
                "-registry",
                "registry.access.redhat.com"
            ]
```

but when the operator tries to upgrade 7.0.1 to 7.1, it tries to pull the image from docker hub:

```
Failed to pull image "docker.io/fuse7/fuse-ignite-upgrade:1.1-8": rpc error: code = Unknown desc = Error: image fuse7/fuse-ignite-upgrade:1.1-8 not found
```

I tried to modify the upstream 1.4.7 operator image to specify my own registry:

```
FROM syndesis/syndesis-operator:1.4.7

ENTRYPOINT [ "/usr/local/bin/syndesis-operator", "-template", "/conf/syndesis-template.yml", "-registry", "myregistry" ]
```

and after deploying that image, it still pulls docker.io.

## Expected behavior

To pull from repository that is specified in `-registry`

## Tasks involved / Steps to Reproduce

1.
2.
3.
4.

**Comment by heiko-braun** [comment]
Sorry @nicolaferraro, but while @rhuss is absent I do need to rely on your on help again.

**Comment by nicolaferraro** [comment]
No problem @heiko-braun, it should be a easy-fix.

**Comment by nicolaferraro** [comment]
I see the command is overridden in the Operator DeploymentConfig. Have you tried using args in the operator deployment config (pod spec)? Like:

```
spec:
  containers:
    - command:
        - syndesis-operator
      args:
        - "-registry"
        - "anotherone"
```

**Comment by avano** [comment]
@nicolaferraro damn, who would expect that. You are probably right, I'll retry asap and will let you know.

@heiko-braun this was actually the 7.0.1 -> 7.1.0 with operator, as the registry is only used for getting the upgrade image afaik

**Comment by nicolaferraro** [comment]
I've fixed it in https://github.com/syndesisio/fuse-online-install (branch `master` and `1.4.x`) by removing the command, in order to use the entrypoint of the productized image. If this works (@avano, cc: @djcoleman), we can close this.

We need also to update the yaml file in this repo (not relevant for Fuse installation, but they better stay in sync).

**Comment by heiko-braun** [comment]
@nicolaferraro Which yaml file do you refer to?

**Comment by heiko-braun** [comment]
@avano Once you've verified the latest changes, please close this issue with a comment.

**Comment by avano** [comment]
looks good to me :-)
