### ISSUE TITLE
Introduce String converter for Gmail connector

### ISSUE THREAD

**Issue by kcbabo** [syndesisio/syndesis#3517]
See also **https://issues.jboss.org/browse/ENTESB-11569**

## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
It would be nice if the Gmail connector included a type converter for String -> GmailMessageModel.  This would allow non-Gmail-aware components/processors to work with Gmail connector OOTB by just setting a String as the message body.  The converter should set the String body value to GmailSendEmailCustomizer.text.

## Expected behavior

Pass a string to the Gmail connector and have it used as the email text.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11569**
