### ISSUE TITLE
EDI Transformations with Fuse Ignite and Trace Transformer

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#3520]
See also **https://issues.jboss.org/browse/ENTESB-11526**

As a citizen integrator, I want to be able to use a Trace Transformer step natively within fuse online.

I want the ability to write, maintain, and operate complex EDI transformations. I want to use a step extension to transform a flat-formatted file into XML using Trace Transformer. The existing step extension gives me the ability to add their own custom steps, which citizen integrators can include in their integrations. 
https://developers.redhat.com/blog/2018/06/12/edi-transformations-with-fuse-ignite-and-trace-transformer/

https://github.com/sigreen/trace-transformer-syndesis-extension

DoD
I trace transformer step is available to me OOTB in fuse online
I can transform a flat file into xml via trace transformer
The feature owner has confirmed one of the following:

- There is an initial draft of the user doc for this feature. 
- The writer acknowledges receiving enough information from engineering to write the initial draft of the user doc for this feature. 

## Related material

- https://developers.redhat.com/blog/2017/07/18/edi-transformations-with-fuse-integration-services-fis/

**Comment by sigreen** [comment]
I can pickup this one.  I'm working with the Trace dev team to determine scope and effort.

**Comment by heiko-braun** [comment]
@sigreen Thanks, that's great. If need help or have questions, feel to reach out to @zregvart and @christophd

**Comment by sigreen** [comment]
Thanks @heiko-braun !  At the moment I'm working through tidying-up my previous attempt at this functionality, which is located here: https://github.com/sigreen/trace-transformer-syndesis-extension .  I plan to download the latest/greatest syndesis step extension code and get it working with the latest build. I'll be sure to reach out to @zregvart and @christophd once I've figured out my plan.

**Comment by sigreen** [comment]
I have updated my example code here: https://github.com/sigreen/syndesis-extension-trace-transformer.  We can work together to figure out how best to merge this into the repo

**Comment by sigreen** [comment]
Trace have added a new Exposed Service drop-down (see below image) to their Transformer tool.  Their product version (Transformer 3.6.9, SyndesisServiceBuilder-1.0) aligns with Syndesis version 1.3.12.fuse-000001-redhat-2.

![image](https://user-images.githubusercontent.com/13749692/55578328-a22e0280-56e3-11e9-92bd-3eb7c3125a69.png)

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11526**
