### ISSUE TITLE
Change references "fuse-ignite" to "fuse-online"

### ISSUE THREAD

**Issue by avano** [syndesisio/syndesis#3523]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

```
<avano> hbraun, do you know by any chance, why we have fuse-IGNITE-{s2i, server, ui, meta, upgrade} images, but we have fuse-ONLINE-operator image?
<hbraun> operator is new and uses the new terms already
<hbraun> the other ones should follow
<hbraun> but we didn't have the time to fix it in 7.1
<hbraun> mid term we want fuse-ignite to be replaced with fuse-online in all cases
<hbraun> this applies to image names as well well as image stream names, tags, etc
```

## Expected behavior

For releases >=7.1.1 release we should reference "fuse-online" everywhere and not "fuse-ignite"

## Tasks involved / Steps to Reproduce

1.
2.
3.
4.

**Comment by michael-coker** [comment]
related https://github.com/syndesisio/syndesis/issues/3431

**Comment by avano** [comment]
thank you @michael-coker ! I'll close this one and I'll start watching #3431
