### ISSUE TITLE
Create a Camel endpoint to use as end of API integrations

### ISSUE THREAD

**Issue by nicolaferraro** [syndesisio/syndesis#3524]
@lburgazzoli .

API integration should be something like `from("direct:operationId").to("thisnewendpoint:dummy?returnCode=200)`.

**Comment by lburgazzoli** [comment]
can we use a setHeader like endpoint ?

**Comment by nicolaferraro** [comment]
For the current requirements it should be ok.

I foresee we may want to set multiple headers in the future, but we've never talked about it...

**Comment by lburgazzoli** [comment]
We can set every property configured as an header value so it is an UI think to properly show it.
