### ISSUE TITLE
Spike: OLM Support 

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/syndesis#3538]
Investigate benefits, scope and complexity of OLM support in Fuse Online and  provide a draft roadmap  that outlines the connection to other teams and their schedules.

**Comment by rhuss** [comment]
I'm afraid I won't come to this story until the end of the sprint.

**Comment by heiko-braun** [comment]
Moving to next sprint

**Comment by heiko-braun** [comment]
@rhuss Can you summarise the findings of this investigation in a google doc? It would be valuable input to the 7.3 planning.

**Comment by rhuss** [comment]
Yes, will do.
