### ISSUE TITLE
Editor choose connection page broken

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#3539]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

![image](https://user-images.githubusercontent.com/351660/45032577-29b57500-b020-11e8-861a-890c917f5d75.png)

Most likely from the addition of the API provider connection which doesn't have any actions, page just needs to be updated to handle this case anyways as part of the API provider epic.

## Expected behavior

The page works.

## Steps to reproduce

1. Create a new connection using the "API Provider" connection
2.  Create a new integration and you'll hit the above.

**Comment by gashcrumb** [comment]
Basically 'actions' can possibly be undefined I guess, so [this line](https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/integration/edit-page/current-flow.service.ts#L75) and [this line](https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/integration/edit-page/current-flow.service.ts#L85) need to be updated.

**Comment by riccardo-forina** [comment]
This was an issue with the API not providing the `actions` property for this new kind of integrations, which has been fixed already.
