### ISSUE TITLE
After upgrading the integration can't be edited

### ISSUE THREAD

**Issue by avano** [syndesisio/syndesis#3540]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

I'm upgrading the syndesis infrastructure with 1 integration (timer -> log) running. After the upgrade, the UI shows that the integration should be republished:
![upgrade1](https://user-images.githubusercontent.com/7081216/45032798-f6d8a480-b052-11e8-90fe-3d0eaee44c4f.png)

However, when I click on "edit integration", all things from the integration are gone:
![upgrade2](https://user-images.githubusercontent.com/7081216/45032818-03f59380-b053-11e8-9838-a18a3cf86bd6.png)

When I try to stop and start the integration, the camel xml is empty:

```
2018-09-04 12:54:33.380 DEBUG 1 --- [           main] .i.r.IntegrationRuntimeAutoConfiguration : Routes:
--
  | <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
  | <routes xmlns="http://camel.apache.org/schema/spring"/>
```

Steps to reproduce:
1. deploy syndesis version 1
2. create integration
3. upgrade syndesis to version 2
4. edit s2i imagestream tag in syndesis-server-config to use s2i from version 2 and restart server to pick up the changes
5. try to edit the integration to pick up newer artifacts

**Comment by heiko-braun** [comment]
@avano Is this reported against 7.1?

**Comment by heiko-braun** [comment]
@rhuss Can we get your feedback on this?

**Comment by rhuss** [comment]
@lburgazzoli any idea about this integration update issue ?

**Comment by lburgazzoli** [comment]
no, is there any log on syndesis server ?

**Comment by rhuss** [comment]
> #3514
> #3460

I don't think they are related (these issues are for upgrading the infra, not the integrations)

**Comment by heiko-braun** [comment]
@rhuss Right, they are not technically related, but with respect to decision if it can be postponed until 7.1.1. Which is the main point of interest right now – similar to #3514 and #3460 which both blocked but have been rescheduled for 7.1.1

**Comment by avano** [comment]
@rhuss @heiko-braun with 7.0.1 upgraded to 7.1 CR2 I can't see that issue (however I used different integration db->db, as the timer and log are not in 7.0.1 by default, but that should not matter).

Sorry for poluting the issues list with p0 issue unrelated to CR1, lowering to p1 for now

**Comment by heiko-braun** [comment]
Thanks @avano. We look into it for 7.1.1

**Comment by lburgazzoli** [comment]
Issue migrating to 1.5.x has been fixed by #3566

**Comment by heiko-braun** [comment]
@avano Looking at @lburgazzoli last comment and the confusion around the test scenario, is issue still valid? If so please update the issue description with a new reproducer

**Comment by heiko-braun** [comment]
@avano Please verify the issue for 7.1.1

**Comment by heiko-braun** [comment]
@syndesisqe We need to know if this problem still exists.

**Comment by tplevko** [comment]
@heiko-braun if I understand this correctly by the description provided by Andrej, the issue described by him was really related to upgrading from 7.1. tag (1.4.7) to 7.2. tag (1.5.4), and didn't really appear when upgrading 7.0.1 upgraded to 7.1 CR2. This I think means, this isn't really relevant for 7.1.1. and as even the fix wasn't merged to 1.4.x branch, this shouldn't be a part of 7.1.1. release. Please correct me if I'm wrong.

**Comment by heiko-braun** [comment]
Thats my understanding as well. I just needed some confirmation from QE before closing this.

**Comment by rhuss** [comment]
@heiko-braun guess that's the same gotcha, so I'm free to close it again.

**Comment by heiko-braun** [comment]
right

**Comment by mastepan** [comment]
What the fix exactly does @lburgazzoli ? The following steps result in unavailable Edit Integration button.

![editintegrationafterimport](https://user-images.githubusercontent.com/8707251/46731898-34e96980-cc8c-11e8-8e3a-020db5d1bea7.png)

1. create an integration on 1.5.4-20181006 version
2. export this integration
3. reinstall syndesis to 1.5.4-20181009 version
4. import the integration

**Comment by lburgazzoli** [comment]
What I see is that the integration is being assembled thus it is not possible to edit it. I think the steps are:

- import the integrations
- edit the integration
- publish it

**Comment by mastepan** [comment]
Ah, I missed this. So the integration is editable now. Thanks.
