### ISSUE TITLE
Provide the upgrade procedures to lift integrations from 1.4.x to 1.5.x

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/syndesis#3541]
With the changes introduced to the domain model in `1.5.x` (concept of flows), we need to make sure users can upgrade integrations running on `1.4.x` to `1.5.x`

**Comment by lburgazzoli** [comment]
it shod be already in place but it there may be some cases not taken into account.

**Comment by lburgazzoli** [comment]
Fixed by #3566
