### ISSUE TITLE
Document how to use Data Shapes in extensions.

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis#3542]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Documentation issue or request
</code></pre>

## Description
We should add a section to the [The Developing Extensions Guide](https://github.com/syndesisio/syndesis/blob/master/doc/developing_extensions/topics/developing_extensions.adoc) the focuses on the different ways you can configure data shapes and the impacts that has on the UI and Runtime processing of steps.

**Comment by TovaCohen** [comment]
I'm happy to help with this. Will one of you write something up? Or should I schedule a BJ meeting and you can explain it and then I can write it? Let me know how you want to do this. thanks!

**Comment by oscerd** [comment]
From a runtime perspective nothing really changes. The more impacted part is the UI, since the Data mapper steps will show you different stuff based on the datashape you choose for your extension

**Comment by igarashitm** [comment]
FYI - `Data Mapper and DataShape`
https://github.com/syndesisio/syndesis/blob/master/app/server/docs/design/datamapper.md#data-mapper-and-datashape

**Comment by TovaCohen** [comment]
Thanks Tomo!
@chirino - If I add the content that Tomo pointed to, starting with the "Data Mapper and Data Shape" header, through the content just before the "Message Map" header, does that provide all the information that needs to be provided?
Also, I am planning to add this information here:
https://access.redhat.com/documentation/en-us/red_hat_fuse/7.1/html-single/integrating_applications_with_fuse_online/#developing-extensions
Is that the right place?
If not, where should this information go?

**Comment by lburgazzoli** [comment]
@TovaCohen do you need something more from my side ?

**Comment by chirino** [comment]
Yes I think that's a good start.  @igarashitm can you improve the explanation for kind none.  I thought  kind none on the output means the step does not change the input body.  None on the input body means, it does not read the input body so it is allowed to by any shape.

**Comment by igarashitm** [comment]
OK done

**Comment by TovaCohen** [comment]
thanks all. I'm good for now. When I bring this content into the user doc, I'll ask for a review.

**Comment by TovaCohen** [comment]
Draft content is here:
https://docs.google.com/document/d/1VzuQ0uC223rNTu6anioYNA6agL_4fZbTYP8QekHYceg/edit?usp=sharing

**Comment by lburgazzoli** [comment]
@igarashitm @TovaCohen is this done ?

**Comment by TovaCohen** [comment]
@lburgazzoli, yes:
https://access.redhat.com/documentation/en-us/red_hat_fuse/7.2/html/integrating_applications_with_fuse_online/customizing_ug#how-to-specify-data-shapes_extensions 
I have an added on task to add examples. Zoran suggested that. But this task is done and can be closed.
