### ISSUE TITLE
Hide technical connector/connections

### ISSUE THREAD

**Issue by nicolaferraro** [syndesisio/syndesis#3546]
Currently there are a number of connector/connections that are included in Syndesis for technical reasons, but not useful from a user perspective.
The list includes:
- Timer
- Log
- Webhook
- API Provider (new)

Syndesis backend needs a connector/connection pair in order to display actions in the UI. E.g. I cannot start from a webhook action if I don't create a webhook connection first. But the webhook connection has no parameters and has no meaning for the user. That's why we create default (empty) connections for those connectors at server startup.

I'm wondering why we're keeping them visible in the syndesis UI in the connection list and we don't just hide them.

I think we can mark them as "technical-connector" and hide them from the list of available connections and connection create page. Wdyt @gaughan, @kcbabo.

We can also plan a refactoring of the syndesis model to eliminate the need for always having a underlying connection, but it will be a major one.

**Comment by nicolaferraro** [comment]
As part of this, API provider actions (start from endpoint, endpoint return code customization) should also be hidden when creating a integration flow. They should be only available in the API provider context.

**Comment by nicolaferraro** [comment]
@riccardo-forina let's address this.
Aside from the task of hiding the "technical connections", there's a simple thing that we need to remove and it's that when a user starts a integration from something else (e.g. Dropbox in the picture), the API connector is shown as possible end action, because the "return path" action is a possible "To" action according to current rules. But it should not be shown (especially, if you click on it, the API provider wizard starts).

How can we remove it? I can mark that action with a special tag backend side if you think it's useful for the UI to reason about it.

![screenshot from 2018-10-17 12-23-17](https://user-images.githubusercontent.com/4151857/47080184-98811300-d207-11e8-9773-4edbd235af45.png)

**Comment by gaughan** [comment]
Agree we should remove API Provider as a finish connector.

**Comment by nicolaferraro** [comment]
The issue with displaying the "API provider" end action has been fixed by #3882.

Additional discussions here: #3889
