### ISSUE TITLE
todo app should be productised when shipped as part of Fuse Online

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#3548]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Our `todo` app is currently build afresh via s2i from GitHub on every Fuse Ignite installation. This will not only fail when no internet connection is present, but can cause also security concerns.

IMO if we ship the sample app with Fuse Online we shoudld productise this image as any other image and fetch it from the redhat registry.

**Comment by rhuss** [comment]
@heiko-braun @gaughan any thoughts on this ? Is this an issue or should it be closed ?

**Comment by heiko-braun** [comment]
Added the triage label so we can discuss it next week.

**Comment by heiko-braun** [comment]
It's an example and will not be productised
