### ISSUE TITLE
todo app api does no authentication, but swagger definition says so

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#3549]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

Todo apps swagger declares in https://github.com/syndesisio/todo-example/blob/master/swagger.yaml.php#L121-L123 that it require basic auth but it does not check the authentication. This should be either implemented (and documented what to use here) or this section should be removed.

**Comment by rhuss** [comment]
I think this is still a quick fix for a details which we should tackle // @heiko-braun @gaughan

**Comment by gaughan** [comment]
+1
