### ISSUE TITLE
Salesforce on-create,on-update not triggered (part 2)

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/syndesis#3550]
We need to cleanup and properly fix https://github.com/syndesisio/syndesis/issues/3533

**Comment by dhirajsb** [comment]
@heiko-braun the fix was on 1.4.x branch, so it's just a matter of reverting/removing the workaround changes at the appropriate time. Can I make those changes on that branch now or is there still release work ongoing on that branch?

**Comment by heiko-braun** [comment]
@dhirajsb No, `1.4.x` is free for `7.1.1`. But can we maybe revert the changes and the update to the camel version in one sweep ?

**Comment by dhirajsb** [comment]
This has been addressed in [ENTESB-9452](https://issues.jboss.org/browse/ENTESB-9452) for the prod branches and also mentions the fix in upstream Camel for [CAMEL-12780](https://issues.apache.org/jira/browse/CAMEL-12780). 
The temporary fix on 1.4.x has to be reverted, and I'll open a PR for the same. 
Upstream Syndesis Camel version also has to be updated to use the latest pinned RedHat fuse build of Camel to include the change from prod branch for 7.1.x.

**Comment by oscerd** [comment]
Upstream on master we are already using 7.2.0 pinned RedHat Fuse build

**Comment by jmartisk** [comment]
Verified with 7.1.1 dev build
