### ISSUE TITLE
Spike: Changing config of a used connection is not picked up

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#3551]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

As it looks like that changing a connection which is used in an integration, is not picked up by integration which are using it. Every integration has a copy of a connection, so when a connection changes all integration's copies need to be updated too. the curse of a document based NoSQL Db.

Specifically when updating an imported Todo API connector connection, and changing the host name, this change gets not reflected in the integration. // @heiko-braun

**Comment by lburgazzoli** [comment]
Did you edit the integration ?

**Comment by gashcrumb** [comment]
What should happen when a connection is changed that's associated with an integration is that the integration should then show that a connection has been edited and that the integration needs to be republished.  So I'd expect on the integration details page to see an inline notification after editing one of the connections that are used by that integration.
