### ISSUE TITLE
UX Design: 7.2 Connector Icons

### ISSUE THREAD

**Issue by sjcox-rh** [syndesisio/syndesis#3557]
Icons needs for new connectors being added as part of the 7.2 release. 

- Slack
- Workday
- Google Drive
- Google Calendar
- FHIR

@paoloantinori @heiko-braun Could you tag the feature owners for these 5 connectors so I can see if help is needed for me to provide the icons?

**Comment by amysueg** [comment]
Thanks @sjcox-rh  

According to @oscerd  on #3313, we don't need a Slack icon.

**Comment by amysueg** [comment]
@sjcox-rh will add the API Connector icon and Return path icon via this issue as well (#3395)

**Comment by sjcox-rh** [comment]
Svg's and png's uploaded for the FHRI, google drive, and workday. You can find them here:

https://github.com/syndesisio/syndesis/tree/master/ux/connections_icons

Icons for APi provider and return path still missing.

@dongniwang @amysueg @michael-coker @paoloantinori @gaughan

**Comment by gaughan** [comment]
Thanks @sjcox-rh

**Comment by zregvart** [comment]
I see that we don't have SVG icons for:
- Dropbox (we use PNG)
- Slack (we use PNG)
- Telegram (we use PNG)
- API Provider (we use PNG, not final version?)

I think having SVG versions of those would be nice, though the only pressing need is to have icon(s) for API Provider.

**Comment by zregvart** [comment]
@dongniwang are there any icons we still need to update for 7.2?

**Comment by dongniwang** [comment]
> I see that we don't have SVG icons for:
> 
> * Dropbox (we use PNG)
> * Slack (we use PNG)
> * Telegram (we use PNG)
> * API Provider (we use PNG, not final version?)
> 
> I think having SVG versions of those would be nice, though the only pressing need is to have icon(s) for API Provider.

Do we still need .svg for Dropbox, Slack and Telegram? @zregvart

**Comment by zregvart** [comment]
I've added those in https://github.com/syndesisio/syndesis/commit/30ca7f488fadf5f71311fd72284e26ebea7dfd86#diff-13632c97439beb0cf3239688a15254e4

Took them straight out of the branding pages and in some cases just cropped.

I think we can close this.
