### ISSUE TITLE
Unable to edit imported integrations

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#3561]
## This is a...

<pre><code>
[ ] Feature request
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

When importing the integrations attached to https://github.com/syndesisio/syndesis/issues/3531, the integration summary properly shows the integration steps but when to integration is edited, the shown pages is the one for an empty integration.

## Expected behavior

We should be able to edit imported integrations.

## Screenshot

* **Integration Summary**

![image](https://user-images.githubusercontent.com/1868933/45149201-493bd180-b1c9-11e8-8d5c-e67635285195.png)

* **Integration Editor**

![image](https://user-images.githubusercontent.com/1868933/45149225-58228400-b1c9-11e8-8e80-a455d72e637c.png)

## Tasks involved / Steps to Reproduce

1. Import  db_custom_api_db.zip
2. Edit the integration

**Comment by lburgazzoli** [comment]
@riccardo-forina can you have a look ?

**Comment by gashcrumb** [comment]
Looks like the flow ID doesn't match.  In the URL:

![image](https://user-images.githubusercontent.com/351660/45156890-72e6ff80-b1ad-11e8-9adc-b66a40f47dad.png)

And in the fetched integration:

![image](https://user-images.githubusercontent.com/351660/45156931-8d20dd80-b1ad-11e8-8d36-41534638de06.png)

Likely I just fudged properly detecting if the integration being edited has a matching flow ID when it's being loaded, the difficulty here is it's being done kind of out of band with the integration being loaded, i.e.:

* it's set here -> https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/integration/edit-page/edit-page.component.ts#L125 actually before we even load
* This I think is probably dubious -> https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/integration/edit-page/current-flow.service.ts#L667-L669

It worked at least when creating integrations, not sure what circumstance with this imported integration would make this not work though :-)

**Comment by lburgazzoli** [comment]
Do we need an additional endpoint now  ? integrations/{integrationId}/{flowId}/{stepId}

**Comment by gashcrumb** [comment]
We found that the flowId changes each time the integration gets fetched:

1 -> 
![image](https://user-images.githubusercontent.com/351660/45160523-adee3080-b1b7-11e8-9ac4-7299dfd25aab.png)

2 -> 
![image](https://user-images.githubusercontent.com/351660/45160552-c5c5b480-b1b7-11e8-8235-7993ae3c1e33.png)

The page loads the integration, syncs the flowId it spots to the URL, loads it again and on that second load the flowId in the newly loaded integration is different.

**Comment by gashcrumb** [comment]
> Do we need an additional endpoint now  ? integrations/{integrationId}/{flowId}/{stepId}

I don't think so.

**Comment by lburgazzoli** [comment]
mh I see what the problem could be, let me work on that

**Comment by lburgazzoli** [comment]
@gashcrumb @riccardo-forina does the change of the flowId explain also the failure loading the step ?

**Comment by lburgazzoli** [comment]
yeah it seems so, sending apr
