### ISSUE TITLE
Query parameters are not set in the API-Connector

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#3564]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[*] Bug report  
[ ] Documentation issue or request
</code></pre>

Found by @mcada 

## Description
The DELETE action for listitems has a path of /common/listitems/{id}, 

https://developer.concur.com/api-explorer/v3-0/ListItems.html#/

however it also has a required query parameter called listId. The id and the listId are both available as parameters. The id is set in the RestProducer by substituting the {id} with the value of the id, however the listId query parameters is never set on the request as listId is never identified as a queryParameter.

This makes the request to concur fail. I'mn still trying to figure out what code is supposed to identify it as a queryParameter so that it can be set. Maybe it's a bug in camel-core altogether.

So to be clear; this happens with all type of HTTP requests GET/UPDATE/DELETE with query parameters like

/common/listitems/{id}?listId={listId}

**Comment by mcada** [comment]
@KurtStam it still does not work for concur delete :/

**Comment by KurtStam** [comment]
@mcada you tried on master?

**Comment by mcada** [comment]
Yes I tried it on up-to-date master.

**Comment by KurtStam** [comment]
ok will double check, and a GET + query params worked?

**Comment by KurtStam** [comment]
@mcada - I think the fix is working but I think there was a bad merge. Here is a screenshot of the proof that the params are in fact set on a DELETE request

<img width="894" alt="screen shot 2018-09-13 at 12 53 02 pm" src="https://user-images.githubusercontent.com/35576/45503339-92a19900-b754-11e8-81b2-2dda268eef96.png">

The concur swagger is loaded in into the DB though. So if it's not a fresh install then you will need to run "delete from jsondb" in the syndesis db and then kill the server pod, so it repopulates the db. You will have to rebuild your concur connection and integrations.

**Comment by KurtStam** [comment]
@mcada I reopened until you can verify this is working now.

**Comment by mcada** [comment]
@KurtStam I did test it with fresh master as I always do, but I forgot to update my test to also set listId when deleting the item :( After I fixed that it works. My bad, thanks for your screen shot, I immediately knew what was my mistake after seeing it. Closing.

**Comment by KurtStam** [comment]
Great! Thx Michael.

On Sep 14, 2018, at 04:40, mcada <notifications@github.com> wrote:

Closed #3564 <https://github.com/syndesisio/syndesis/issues/3564>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/syndesisio/syndesis/issues/3564#event-1845519196>, or mute
the thread

**Comment by zregvart** [comment]
Good work here thanks @KurtStam and @mcada :100:
