### ISSUE TITLE
Migrate from nginx to some simple go static asset server

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#3568]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

![image](https://user-images.githubusercontent.com/351660/45226539-13f8b780-b28d-11e8-81f0-717db40feba4.png)

**Comment by rhuss** [comment]
Wasn't [caddy](https://caddyserver.com/) @jimmidyson 's pet server but we had to replace it with nginx because of productisation constraints ?

**Comment by heiko-braun** [comment]
@gashcrumb Why would we do that? Can you provide some arguments that explain your motivation?

**Comment by chirino** [comment]
There are a few benefits: reduced CVE surface area, smaller image layer, easier redistribution of static assets to other platforms or image containers.

**Comment by chirino** [comment]
Btw, caddy seems more like a traditional http server.

**Comment by rhuss** [comment]
Again, we as on caddy before were *forced* to move to nginx as this was the most lighweight productised HTTP server. It was not for technical reason that we moved away from caddy, it was of productisation issues.

Before switching the HTTP server we should be 100% sure that this is possible productionwise.

Personally I would also love to switch to caddy but I also love to pass the buck on in case of CVE issue in the HTTP serving layer which, tbh, is not our bussiness to maintain.

**Comment by rhuss** [comment]
This was the original issue and motivation: https://github.com/syndesisio/syndesis-ui/issues/622

**Comment by chirino** [comment]
So, I'm not sure about Caddy, but the http engine I'm planning to use is the one provided by the go standard libs.  I bet that's the same http server that k8s uses.  I'm having Darren check to see how easy it would be to productize one of these types of images.

**Comment by rhuss** [comment]
> There are a few benefits: reduced CVE surface area, 

Not sure if I buy this argument as it is now ourselves who have to watch for CVEs affecting in the golang  HTTP libraries, whereas for an officially supported Red Hat base images its a team which is specialized on this. Of course, nginx should be trimmed down configurationwise as much as possible, and although I'm not sure, I think it should be possible to switch off all dynamic behaviour.

> smaller image layer

Don't think that's an issue as Red Hat's nginx's base image is available locally, and nginx won't add much more than an home grown  HTTP server

>  easier redistribution of static assets to other platforms or image containers

could you please elaborate what you mean with redistribution and where you would wont to redistribute or share static assets files from images ?

As for drawbacks of an HTTP server developed and maintained on our own I see:

* The image build has to be integrated into our build process
* The base image needs to be productised with all the overhead (except when you compile the HTTP server each time you create a UI image, but then it can't be reused in other projects like apicurito)
* It's not our business to maintain an HTTP server

**Comment by zregvart** [comment]
Caddy is really nice, it can serve git repositories, render markdown and has Let's Encrypt support out of the box. I would prefer Caddy just for the Let's Encrypt support as Let's Encrypt is now trusted root CA in all platforms. Git support might be helpful for serving docs for example. It's also a single binary (Caddy is golang based), so `FROM scratch` is possible with it also.

**Comment by rhuss** [comment]
I like caddy, too, but more for that its maintained outside our team.

wrt the feature I don't see much value for our concrete use case, though: We won't serve from git repos, we don't dynamically render markdown and our certs should come from openshift with any need to renewal (so let's encrypt is not really of value here, too).

And we still have the productisation issue with caddy.
