### ISSUE TITLE
Api connector swagger supported format

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#3578]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
I was not able to find if and why did we stop supporting .yaml format when creating api connectors.
It worked on 7.1 but now on master there is this note that we only support .json:

![screenshot_20180912_103836](https://user-images.githubusercontent.com/14313995/45412849-091c9900-b678-11e8-9248-65db1fdf588f.png)

If we wanted to do this change, can you please point me to the correct issue with discussion/decision regarding this topic?

**Comment by mcada** [comment]
I did some more digging and found out that it may be due to apicurio only supporting json. Is it still valid? It does not make sense to me to disable yaml just because user can not edit it from syndesis. Maybe if yaml is used we should disable apicurio?

**Comment by zregvart** [comment]
We can surely convert from YAML to JSON if needed for Apicurio, though I was pretty sure that I saw YAML support in Apicurio also (there was a yaml dependency in package.json).

**Comment by tplevko** [comment]
@paoloantinori @heiko-braun, QE considers this to be a serious limitation of Syndesis functionality. Could you please explain to us, why the .yaml format was decided to be not supported? How do the plans look like with supporting / not supporting this format in 7.2.?

**Comment by heiko-braun** [comment]
@chirino Do you know anything about this?

**Comment by paoloantinori** [comment]
```
✔ /data/repositories/work/syndesis/syndesis [master|…3⚑ 13] 
14:48 $ ag "Accepted file type: .json"
app/ui/src/assets/dictionary/en-GB.json
59:        "api-upload-helper-text": "Accepted file type: .json",
✔ /data/repositories/work/syndesis/syndesis [master|…3⚑ 13] 
14:51 $ git show 92cc6c3fb
commit 92cc6c3fb6e687fc14ce1bdc4b7c3c841ed7974a
Author: Daniel Florian <dflorian@redhat.com>
Date:   Tue Aug 21 13:18:14 2018 -0500

    Fix for Issue 3411 Add a filter to the file dialog on the "Upload OpenAPI Specification" page
    - when using file chooser dialog, now only *.json files are enabled and selectable
    - this change does not affect how DND works, so any file with any extension still can be dropped

diff --git a/app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-swagger-upload/api-connector-swagger-upload.component.html b/app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-swagger-upload/api-connector-swagger-upload.component.html
index 03241545b..eda57898f 100644
--- a/app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-swagger-upload/api-connector-swagger-upload.component.html
+++ b/app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-swagger-upload/api-connector-swagger-upload.component.html
@@ -49,6 +49,7 @@
                     <input #fileSelect
                       class="api-file-chooser"
                       type="file"
+                      accept="application/json"
                       ng2FileSelect
                       [uploader]="uploader">
                   </p>

```

https://github.com/syndesisio/syndesis/issues/3411

**Comment by chirino** [comment]
Yeah. So I’d rather disable editing via Apicurio if it is in Yaml format. Instead of removing the ability to use Yaml.

**Comment by gashcrumb** [comment]
Yeah, also since we don't support round-tripping the swagger file at all we could just convert on the fly.  We could use `yaml.js` and do it on the frontend side, but that assumes the YAML structure will properly convert to a JSON format.  Or do it on the backend side.  It looks like it's a straightforward enough conversion but I'm sure there's probably edge cases where the conversion would be imperfect and lead to some usability bugs, i.e. "my YAML validates just fine but I get blah blah JSON error, what's that about?"

Though I imagine most actual real-world swagger is gonna be non-trivial, so asking the user's browser to do it on their laptop may not be the best UX.

I haven't found anything on the site that says that Apicurio *doesn't* support YAML; so this could be due more to a limitation with how we're handing the data over to Apicurio, I think the wrapper component expects a javascript object which ultimately would mean a conversion would have to happen regardless, @kahboom @elvisisking can you confirm?

**Comment by zregvart** [comment]
This is weird to me, I know that I've seen YAML dependency in package.json of Apicurio. And to test I've just imported https://todo-syndesis-staging.b6ff.rh-idev.openshiftapps.com/swagger.yaml to hosted version of Apicurio at https://studio.apicur.io/.

I wonder how did we come to the conclusion that OpenAPI 2.0 in YAML format is not supported in Apicurio?

**Comment by elvisisking** [comment]
Regardless if the upload is a file or a URL, we are currently passing a "stringified" JSON object to the Apicurio editor component. The Apicurio editor also accepts JSON JavaScript objects **AND** YAML JavaScript objects. However, when passing a string to the editor it **must** be in JSON format.

One issue in the UI the file chooser component we are using is that it's file filters use MIME types and YAML currently does not have one (JSON does). So there would not be a way to create a filter for the file chooser component that allows only JSON and YAML files to be selected.

**Comment by gashcrumb** [comment]
I vote get rid of the file filter and just validate the extension of the filename after the fact if that's the case.

**Comment by tplevko** [comment]
@mcada please verify the yaml format is supported for api connectors
