### ISSUE TITLE
Edit Slack connection - replacing token by webhook doesn't work

### ISSUE THREAD

**Issue by mastepan** [syndesisio/syndesis#3582]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

I created a Slack connection with TOKEN. If I want to remove TOKEN and set WEBHOOK URL instead (on Connection Details page), both fields stay filled after clicking **Save** button.

I have no idea if this can cause any problem but it is confusing. At least.

**Comment by gashcrumb** [comment]
I can't reproduce this on master unless I'm missing something.

**Comment by oscerd** [comment]
It may be the fix you did a while ago @gashcrumb ? I'll give it a try with master too.

**Comment by oscerd** [comment]
I cannot reproduce this on master.

**Comment by oscerd** [comment]
Can you please try on a fresh incognito tab? @mastepan

**Comment by mastepan** [comment]
@oscerd If you save the changed values, go back to Connections page and then to the Slack connection detail again, then it can be reproduced. I'm not sure if it was even reproducible by the shorter way I described first...

**Comment by gashcrumb** [comment]
Ah, I see it now.  So when you clear out a field and save it puts:

![image](https://user-images.githubusercontent.com/351660/45552251-5296f080-b7fe-11e8-8333-ef8182f7c1d9.png)

And then when you go out and back into the details page we get back:

![image](https://user-images.githubusercontent.com/351660/45552294-70fcec00-b7fe-11e8-9d19-7ed84ae763ed.png)

which could probably be the empty string, but it's a password field so it shows up as filled in even with the empty string.  Lemme see if that page can omit the empty string instead, should fix this.
