### ISSUE TITLE
[UI] syndesis-loading children is evaluated regardless of its loading state

### ISSUE THREAD

**Issue by riccardo-forina** [syndesisio/syndesis#3587]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Children elements of the `syndesis-loading` component are parsed regardless of the loading state of the component.

A simple example to try it out is the following:

```
// example.component.ts
export class Example {
   alert = alert;
}

// examle.component.html
<syndesis-loading [loading]="true">
  {{ alert("sorry, still evaluated!") }}
</syndesis-loading>
```

## Workaround

The following code does what you'd expect it to do.

```
// example.component.ts
export class Example {
   alert = alert;
}

// examle.component.html
<ng-container *ngIf="true; else content">
  <syndesis-loading loading="true"></syndesis-loading>
</ng-container>

<ng-template #content>
  {{ alert("this will not be called!") }}
</ng-template>
```

**Comment by gashcrumb** [comment]
I think without wrapping the HTML in a template it gets evaluated.  

I'm thinking though I'd enhance the loading component so you could do:
```
<syndesis-loading [loading]="stuffLoading" [content]="content">
  <ng-template #content>
    <div>Hello</div>
    <div>
      {{ alert("Hi!") }}
    </div>
  </ng-template>
</syndesis-loading>
```

**Comment by riccardo-forina** [comment]
Ah, I like that 👍

Il giorno gio 13 set 2018 alle 19:08 Stan Lewis <notifications@github.com>
ha scritto:
