### ISSUE TITLE
Support for more advanced pragmas in Template Step

### ISSUE THREAD

**Issue by phantomjinx** [syndesisio/syndesis#3598]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
[Mustache](https://mustache.github.io/mustache.5.html) has support for more advanced types of syntax. Some of them are probably never going to be appropriate to implement, eg. calling functions. However, syntax such as lists/sections may be useful:
```
{{#person}}
  {{name}}
{{/person}}
```
However, this is actually an array of 'person' objects containing the attribute 'name'. Although both the template can support it and the mustache-camel component execute it, the problem is the mapping of data to it. The DataMapper does display object-type arrays, eg. geometryCoordinates in twitter connection. However, this does not support an association link; only its children can.

- Should this kind of advanced syntax be supported?
- Should this syntax be supported initially for 7.2 (or just go with simple {{name}} substitution)?
- Should the DataMapper be updated to support this type of mapping?

**UPDATE**
With implementation of both velocity and freemarker, it is evident that these engines also support more advanced pragmas/directives that would require careful implementation in both datamapper and the TemplateStepHandler. Therefore, it would be necessary to define exactly which are likely be required and feasible before embarking on further advanced implementation.

**Comment by phantomjinx** [comment]
@heiko-braun @gaughan

Can I have your take on this as to whether it is worth pursuing and therefore needs an upstream issue generated in atlas-mapper?

**Comment by gaughan** [comment]
I think we are ok to exclude from 7.2, adding @igarashitm @pleacu to see if we can work into current or future atlasmap plans.

**Comment by igarashitm** [comment]
If template step has an array in its JSON schema definition, you can map to it in datamapper step today. Then it's just a matter of extracting that value from JSON payload in the template step code, isn't it?

**Comment by phantomjinx** [comment]
@igarashitm 
Might need to discuss this with you further to understand better. For the moment, to provide an example:
Mustache allows the following pragma:
```
{{#geoLocation}}
  Coordinates: ({{lattitude}}, {{longitude}})
{{/geoLocation}}
```
With json data, this would generate the following list type output:
```
DATA
{
  geoLocation [
    { latitude: x1, longitude: y1 },
    { latitude: x2, longitude: y2 },
    { latitude: x3, longitude: y3 }
  ]
}

OUTPUT
Coordinates: (x1, y1)
Coordinates: (x2, y2)
Coordinates: (x3, y3)
...
```
The important differences here are that it is the geoLocation enclosing object that is the object to be mapped and the it is in fact an array of objects rather than just values.
 
The Twitter object that would map to it is described as follows:
```
 * Twitter Object
   * ...
   * geoLocation >
     * latitude
     * longitude
   * ...
```

The unfortunate difficulty is that this Twitter object can only be expanded in the DataMapper and not itself associated. Both latitude and longitude can be associated but that, in this case, is not what would be required.

HTH

**Comment by igarashitm** [comment]
@phantomjinx 
Maybe I don't yet understand the issue. With your example datamapper can map
`twitter4j.Status/geoLocation/latitude` > `DATA/geoLocation/latitude`
`twitter4j.Status/geoLocation/longitude` > `DATA/geoLocation/longitude`
where `Data/geoLocation` is a JSON array. I don't think it's an array in Twitter4j.Status object though. So it would just create one item in the array in target JSON object.

**Comment by phantomjinx** [comment]
@igarashitm 
Sorry! I've confused the object in question.

In the Twitter4j.Status, it is place > geometryCoordinates rather than geoLocation.

Anyway, have done a quick video to try and demonstrate the issue:
https://drive.google.com/file/d/113uITebNFU54DqMyH8tejewhcoNO6je4/view?usp=sharing

**Comment by igarashitm** [comment]
@phantomjinx 
It looks like `geo` at target side is recognized as a primitive array but not an object array. How the JSON schema look like?

**Comment by phantomjinx** [comment]
@igarashitm 

Yes, the JSON schema for the template step just details geo as array rather than array of objects. I would imagine that is why I can select geo on the target side. Otherwise, I am guessing it would look like geometryCoordinates on the source side?

**Comment by igarashitm** [comment]
@phantomjinx isn't it what that usecase expect? primitive array only contains primitive value like string or integer, but you want to have both of latitude and longtitude under `geo` right? Then you need object array in JSON schema.

**Comment by igarashitm** [comment]
So without array, `geo` is object right? it's not a single primitive value, but has two properties `latitude` and `longtitude`. This is object in JSON schema. Then if you want to have an array of it, it must be an object array.

**Comment by phantomjinx** [comment]
@igarashitm 
Unpack a couple of things here:
1. In order to satisfy the requirements of the template syntax (and mustache's java implementation), geo must be an **array of objects** (each object containing 2 properties latitude and longitude);

1.  The current implementation of the JSON schema as I have dynamically written it is *wrong* and needs to be fixed;

1. Fixing it at this stage depends on atlasmapper support the selection and association of object arrays, rather than just there children.

So I can sort out the first 2 but is atlasmapper able to support number 3?

**Comment by igarashitm** [comment]
That's not possible by design. AtlasMap is field-by-field mapping solution and only terminal fields are mappable. parents are all container but not a field, this can't be participate in mapping.

**Comment by phantomjinx** [comment]
@igarashitm 

In that case this will have to be revisited from the view of the json -> java map processor that kicks in prior to the actual mustache route. It might be possible to associate the terminal fields of both the source and target then re-arrange them into a form that the mustache library understands to be an array-of-maps.

@gaughan

**Comment by rhuss** [comment]
Where do we stand with this feature ? Is it something we should consider for 7.3 ?

**Comment by gaughan** [comment]
I think we are probably oversubscribed to 7.3 features as is, correct? Maybe 7.4?
