### ISSUE TITLE
UX Design Improvements for API Provider 

### ISSUE THREAD

**Issue by dongniwang** [syndesisio/syndesis#3601]
Related to https://github.com/syndesisio/syndesis/issues/3140

Question! In this [design](https://redhat.invisionapp.com/share/4JNR7J5DMNY#/screens/316053627) we show a badge with a number. I implemented it as the count of operations coming from the swagger file, but talking with @dongniwang I found that it should have been the number of _integrated_ operations.

But iterating on that, wouldn't both info be useful at the same time? Something like 5/20 for example, to indicate that 5 out of 20 operations have an integration defined.

Somewhat linked to this, I think it would be interesting to show the same thing [here](https://redhat.invisionapp.com/share/CBNWDY58AHG#/screens/318306620) instead of the Santa Hat, it would be a sort of progress indicator for the user while working.

WDYT?

_Originally posted by @riccardo-forina in https://github.com/syndesisio/syndesis/issues/3140#issuecomment-421352496_

cc: @amysueg @sjcox-rh @heiko-braun @paoloantinori @gashcrumb

**Comment by michael-coker** [comment]
@dongniwang how should we handle the badge size? I imagine the badge size should remain constant regardless the count inside it? If so, how many numbers should be able to fit inside, and how many should it be optimized for? (for example, it looks great with 2 numbers in it and spacious if there is only 1 and tight if there are 3)

Or should the circle get bigger/smaller depending on the # inside it?

Or should we consider something like the design @jameslau included when we were talking about it originally? 
![unread-mail-number-iphone](https://user-images.githubusercontent.com/35148959/46636717-c9ce5480-cb1e-11e8-9bc4-366d15494b9d.jpg)

**Comment by michael-coker** [comment]
here's what I have so far.

<img width="319" alt="screen shot 2018-10-08 at 5 27 12 pm" src="https://user-images.githubusercontent.com/35148959/46636877-6ee92d00-cb1f-11e8-97de-31f3cbe92f45.png">
