### ISSUE TITLE
Create an icon for google-calendar connector

### ISSUE THREAD

**Issue by oscerd** [syndesisio/syndesis#3602]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Create an icon for google-calendar connector.

**Comment by dongniwang** [comment]
Hi @oscerd, @sjcox-rh has issue https://github.com/syndesisio/syndesis/issues/3557 opened for this request, think we can close this one? 

cc: @amysueg

**Comment by oscerd** [comment]
Yes, sure.
