### ISSUE TITLE
Full Investigation and Design Plan for Updating Cached Artifacts

### ISSUE THREAD

**Issue by phantomjinx** [syndesisio/syndesis#3606]
See also **https://issues.jboss.org/browse/ENTESB-11524**

When a connection and an integration are created, there can exist at least 3 copies of the connection in the system:
- The connection stored in the data store and accessible via the DataManager;
- The connection cached in the draft integration (assumed saved-as-draft);
- The connection cached in the copy of the deployed integration

The problem with the multiple copies is that it is possible for 1 component to be updated with new metadata whilst the other elements remain using the old data. For example:
1. Create a gmail connection, specifying the OAuth Client credentials in the settings;
2. Create an integration based on the gmail connection;
3. Publish the integration;
4. Change the gmail connection settings;

At this point, it is possible that the connection can be edited to update its cached metadata. However, this is not certain and observations have shown this does not always occur. Likewise, editing the integration is supposed to update its cached connection metadata yet this does not always occur either. A tell-tale sign is the warning that now gets flagged on the integration:

```A connection associated with this integration has been modified. To incorporate the changes, please edit the integration.```

A systematic investigation should be conducted to find all the points where updates occur then events should be fired to signal all cached copies, where applicable, should be synchronized.

**Comment by phantomjinx** [comment]
@rhuss 

I made it an epic since I had already created related sub-tasks previously and it seems a more complex issue than just a bug or feature request. Happy to change it if preferred.

**Comment by phantomjinx** [comment]
@lburgazzoli 

Agreed. So this would probably require a design document outlining the changes prior to implementation.

**Comment by rhuss** [comment]
@phantomjinx no problem wrt Epic, just wanted to be sure that's not by accident as I haven't seen the subtasks (remember, you have to create the Epic via ZenHub, just adding the label is not good enough).

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11524**
