### ISSUE TITLE
LinkedIn Connector

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#3607]
See also **https://issues.jboss.org/browse/ENTESB-11523**

## This is a...

<pre><code>
[ x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
LinkedIn
As a citizen integrator in the Human Resources LoB, I want to be able to add a LinkedIn start connector to an integration. I want to be able to retrieve job candidates profile data.  https://developer.linkedin.com/docs/guide/v2/people/profile-api 

I also want to be able to publish job descriptions to LinkedIn Recruiter via a finish connector and receive inMail via a start connector. I have an internal job record database (ATS - Applicant tracking system) that I want to query and then publish new jobs to LinkedIn.

HRM LoB Scenario
A position requisition and associates job description is created in an internal system of record. I want to publish to multiple sources, linkedIn, indeed.com dice.com monster.com etc
I want to track applications from the beginning to the end of my talent acquisition pipeline. At the end of the process, the profile data from LinkedIn, for example, should feed into my “employee engagement” system.

DoD
A LinkedIn connector can be added to the start of an integration flow.
A LinkedIn connector can be added to the finish of an integration flow
I can successfully post a job description to LinkedIn
I can retrieve one or many candidates linkedin profile/s 

The feature owner has confirmed one of the following:
- There is an initial draft of the user doc for this feature. 
- The writer acknowledges receiving enough information from engineering to write the initial draft of the user doc for this feature.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11523**
