### ISSUE TITLE
Logging is broken in the UI

### ISSUE THREAD

**Issue by riccardo-forina** [syndesisio/syndesis#3617]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

The UI app uses [`typescript-logging`](https://github.com/mreuvers/typescript-logging/) to log on the console, but nothing actually gets logged to the console.

**Comment by RHodzelmans** [comment]
I have the same issue, when I open my URL:
https://syndesis-fuseonline.apps.jfall2.rhtesting.nl/project/fuseonline/browse/pods/i-jfall-integration-1-build?tab=logs

I tested it in 2 OCP 4.2 AWS clusters:

![ScreenshotOf404](https://user-images.githubusercontent.com/2842380/67848522-2410cd80-fb05-11e9-8782-2c03184ed9ca.png)
![ScreenshotOfLink](https://user-images.githubusercontent.com/2842380/67848523-24a96400-fb05-11e9-8d12-a3c04d2f2a01.png)

I have the diagnostics, but I'm a little hesitant to attach them to this bug
