### ISSUE TITLE
Add support for apiKey for API Connector

### ISSUE THREAD

**Issue by jcordes73** [syndesisio/syndesis#3629]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When creating an API Connector and Swagger definition contains authentication via API-Keys there is warning that apiKey authentication is not supported.
It would be good to have the feature of authentification via API-Keys as well.

Tested with https://petstore.swagger.io/v2/swagger.json and Fuse Online 1.4.8.

**Comment by zregvart** [comment]
@gaughan we could tackle this for 7.3 I think.

**Comment by mmuzikar** [comment]
With #5490 resolved, this is pretty much done :)
