### ISSUE TITLE
Template Step UI implementation UX review 

### ISSUE THREAD

**Issue by dongniwang** [syndesisio/syndesis#3630]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

1. Upload Template screen: there are two grey lines right beneath the intro text. 
2. Add a step screen: notification icon is inside the step icon. 

## Expected behavior

1. Upload Template screen: do not show the grey lines. UX design is [here](https://redhat.invisionapp.com/share/UYNXZ30MQ34#/screens/318752827). 
2. Maybe show the notification icon at the top right edge of the step icon. UX design for this screen is [here](https://redhat.invisionapp.com/share/UYNXZ30MQ34#/screens/318752832). 

## Screenshot

1. Grey lines
<img width="1015" alt="screen shot 2018-09-19 at 3 40 52 pm" src="https://user-images.githubusercontent.com/24943812/45778356-67242000-bc26-11e8-8c51-5e39051dbb9c.png">

2. Notification icon
<img width="829" alt="screen shot 2018-09-19 at 4 10 36 pm" src="https://user-images.githubusercontent.com/24943812/45778497-bb2f0480-bc26-11e8-9f44-5c1aa9f94751.png">

cc: @phantomjinx

**Comment by dongniwang** [comment]
Adding comments from @kcbabo:

> We seem to have a regression in the IVP where there's a massive amount of space between the icons again.  It looks like they are being sized based on the details text - when the details panel is opened then the spacing seems right.  Can we just squash the steps together when the details pane is not open?
Why don't our steps have individual icons?  There's really no way to tell what's going on in a flow without expanding the details pane.  Also, the smaller step icons don't decorate well.  Case in point, the missing mapping warning in the video completely overlays the step icon.

We may need to create seperate issues based on the comments above. 

@michael-coker - would you be able to help investigate what's causing the massive amount of space between icons in the collapsed IVP view? 

In terms of step icons, @syndesisio/uxd please voice your opnions here as well.

**Comment by amysueg** [comment]
@kcbabo @gaughan Regarding step icons, I think it's an interesting idea. The way the steps are presented now in the IVP they are smaller than the connections and if we keep that size distinction (which I think we should), icons will be quite small. UXD team can explore this idea if you think it's worthwhile to do so. 

In the meanwhile @dongniwang, I agree that the warning icon should appear as a badge (upper right corner) on the step icon, as depicted in the design. Is that also something you could check @michael-coker?

**Comment by kcbabo** [comment]
Out of curiosity, why do you feel there should be a size difference between connections and steps?  I see those as being of equal significance to the user when editing an integration flow.

**Comment by amysueg** [comment]
@kcbabo thinking toward a future where there is less distinction between connections and steps --#1830 -- you're 100% right. The icons should be the same size.
