### ISSUE TITLE
Integration - Add a Step: loading wheel stuck turning

### ISSUE THREAD

**Issue by mastepan** [syndesisio/syndesis#3632]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
1. go to Create Integration
2. select Timer and Log as start and finish connections
3. Add a Step between these 2 connections (Log and Advanced filter are available)

It doesn't matter what step you choose. The loading wheel is turning and turning...infinitely. 

The problem may be when there are no attributes that could be filtered, logged or mapped. There should be accessible only those integration steps that make sense.

I suppose this is not limited only to these 2 connections.

![loadingwheelstuck](https://user-images.githubusercontent.com/8707251/45807682-532efb80-bcc4-11e8-9c12-9662fd2edaa7.png)

**Comment by heiko-braun** [comment]
@mastepan which version are you testing?

**Comment by mastepan** [comment]
@heiko-braun the yesterday's one. Can be an exact version found anywhere?

**Comment by gashcrumb** [comment]
Yep, this is totally my bad, PR in a few...
