### ISSUE TITLE
Use base path from the OpenAPI specification

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#3636]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

I think it's a bug that we have fixed base path of `/api` for API provider generated integrations. The OpenAPI specification mandates the base path, and we should abide by that.

The url mapping here:

https://github.com/syndesisio/syndesis/blob/faeaa61ef038f62cbcf64e23d422c8cc864d564e/app/connector/api-provider/src/main/java/io/syndesis/connector/apiprovider/ApiProviderServletAutoConfiguration.java#L34

Should be parameterized from the base path of the specification.

**Comment by mcada** [comment]
Verified.
