### ISSUE TITLE
(Backport) Query parameters are not set in the API-Connector 

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/syndesis#3638]
Backport of https://github.com/syndesisio/syndesis/issues/3564 to 1.4.x

**Comment by zregvart** [comment]
Done via #3633

**Comment by mcada** [comment]
Verified with:

Ignite:
1.4.10.fuse-711001-redhat-00001
Build ID:
b64ee2c9-5511-4dc1-85e0-1d4708716d2e
Commit ID:
42d20ef3dd81245461e60eb759169472cffc021e
