### ISSUE TITLE
WMQ Connector

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#3643]
See also **https://issues.jboss.org/browse/ENTESB-11522**

WMQ Connector
As a citizen user I want to be able to connect to Websphere MQ. I will provide my own jar file via library extensions for use with my connector. Other message queue details such as broker url and credentials should be provided in a similar to the AMQ connector. 

DoD

- I can send WMQ messages
- I can receive WMQ messages.

The feature owner has confirmed one of the following:
--There is an initial draft of the user doc for this feature.
--The writer acknowledges receiving enough information from engineering to write the initial draft of the user doc for this feature.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11522**
