### ISSUE TITLE
Can create a flow without ID through REST API

### ISSUE THREAD

**Issue by jstastny-cz** [syndesisio/syndesis#3646]
This is a bug.

User (through REST API) can create an Integration with Flow which doesn't have id specified. The Integration is created, and works well.
But when trying to edit the Integration through web interface, the flow is not visible after clicking 'Edit integration' and all the screen seems broken (no buttons or links).

Either the Flow id needs to be enforced via REST API, or web interface need to overcome this deficiency.

**Comment by heiko-braun** [comment]
@gashcrumb What are your thoughts on this?

**Comment by zregvart** [comment]
#techdebt we should validate all parameters we receive via the REST API. A bunch of this we get with Immutables if we turn on JSR 303 validations.

**Comment by heiko-braun** [comment]
ok, thanks for the feedback. We leave it open for further consideration but will not (yet) act on it.

**Comment by heiko-braun** [comment]
@jstastny-cz I think this one of the areas where we would love to see contributions. If you can think about adding further constraints to the API parameters, I guess @zregvart can point you in the right direction.
