### ISSUE TITLE
UX Design - explore ways to handle multiple notifications on integration details page 

### ISSUE THREAD

**Issue by dongniwang** [syndesisio/syndesis#3648]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

When there are multiple inline notifications (>5) appearing on the integration details page, the main content got pushed down below the fold. 

## Expected behavior

A better way to display these inline notifications on the page. 
- Some kind of way to group the notifications so it's not being displayed in a flat list 
- Let users know there are more than one notifications 
- Have a control to expand/collapse the notification group 
- Catch user attention that something needs to be done 

## Screenshot

![image](https://user-images.githubusercontent.com/24943812/45890009-e3864280-bd8f-11e8-8664-cab9060b974a.png)

## Reference 
See comments in https://github.com/syndesisio/syndesis/issues/3637

**Comment by dongniwang** [comment]
PF4 has a pattern for handling multiple notifications herehttps://github.com/patternfly/patternfly-next/issues/654

FYI @nding-anges @mcoker

**Comment by nding-anges** [comment]
@dongniwang @mcoker Thanks Dongni. I just have a concern about whether the Toast notification is suitable for this use case? I suppose that Toast notification is in charge of display message of global system on the overall situation. Inline notification points out an issue of a specific use case on one UI. Here, as the error message is addressed to an integration, it is better to display by Inline notification and be close to the relative item.

I just made a draft solution to have a discussion with you, see image below: 
1. Adding a 'close' button on notification( there should be display maxium one notification on UI)  ; 2. After user close the notification, an Alert icon will display on the header while a constant occurrence of an error (same error should be display by the same message if it is technically possible)
<img width="716" alt="2018-11-16 4 52 23" src="https://user-images.githubusercontent.com/34368385/48610612-f26c2880-e9bf-11e8-8367-acf8d490b866.png">

3. onMouse over on Alert icon, a dropdown will show the detail messages. It could be display a list of message on dropdown. Refer to Openshift:
<img width="973" alt="2018-11-16 4 31 18" src="https://user-images.githubusercontent.com/34368385/48611651-afab5000-e9c1-11e8-8d8a-8f641aa58147.png">

If the direction is right, I will continue to design more detail situation, please feel free to brainstorming ;-)

**Comment by dongniwang** [comment]
@nding-anges - Thanks for posting. Here are my thoughts: 
- I agreed that it's not a use case for Toast Notification, and I'm not suggesting we should use toast notification here. I was referring to the concept of having a "two more unread" and "dismiss all" message. 
- I like the idea of the close button. But not sure if limiting to only displaying one notification at all time is a good idea. 
- I do like the idea of having a consistent error message (alert/warning icon) shown somewhere on the page, but not sure if the icon itself is enough or we need more help text. Also, since the "stopped" label there is also some kind of status indicator, maybe we can explore another location for displaying the alert/warning?

**Comment by nding-anges** [comment]
@dongniwang Thanks for the suggestions. It's a draft design and I will continue to do an iteration design in this direction.

**Comment by nding-anges** [comment]
@dongniwang @mcoker Hello everyone, I updated the design solution and I'd like to have a discussion with you, see images below:
![default status](https://user-images.githubusercontent.com/34368385/48832737-d2b87400-edb4-11e8-9881-8a0a620ea9ba.png)
![expanding status](https://user-images.githubusercontent.com/34368385/48832754-dea43600-edb4-11e8-94e5-7aa33be15d2b.png)
![alert icon](https://user-images.githubusercontent.com/34368385/48832775-e9f76180-edb4-11e8-8272-8cb887867eec.png)
![mouse over icon](https://user-images.githubusercontent.com/34368385/48832798-fa0f4100-edb4-11e8-8205-aacd9ee1c534.png)

Another regarding the notification massage: I notice that most of these massages have the same content since a confuguration required status. Is that possible to display only one notifictaion message if the confuguration required status is continued? That will be solve the problem fundamentally.  Thanks~

**Comment by phantomjinx** [comment]
@nding-anges 

> I notice that most of these massages have the same content since a configuration required status. Is that possible to display only one notification message if the configuration required status is continued?

Each message is actually checking a different connection in the integration then returning the more generic message. Therefore, although the message is the same the underlying reason for it being flagged will be different. I have merged in an API change to the backend that actually delivers a more detailed message the references the specific differences. However, no UI picks this up yet. Maybe, that is something that could be factored in, eg. details button + slide-out panel.

On the other hand, knowing that some part of the integration is stale and editing the integration would solve it is probably sufficient for the user to be told only once. Therefore, maybe at the UI-level despite receiving several notifications, a de-duplication function could be added so only one is displayed (maybe even with a number in brackets to suggest there are (n) number of these messages)?

**Comment by dongniwang** [comment]
@nding-anges - Thanks for the update! Is it possible to move the designs into InVision? It would be easier to review and provide feedback that way. Thank you.

**Comment by nding-anges** [comment]
@phantomjinx Thanks for explaining the context of notification. That is really helpful and now I understand very well where the problem is. Could you please give me an example of a phrase that will show on the notification message after you changed API and delivered more detail? I will integrate into the UI design. 

Another question: The new design can handle multiple notifications without quota, and the current strategy is to display message one by one.  Do you think that will have a huge quantity of the message, like 50，100 or even more? If so, we will consider the acceptability on UI level and also from the user standpoint. Thus, I think that 'a number in brackets to suggest there are (n) number of these messages' is a good idea for a de-duplication function.

**Comment by nding-anges** [comment]
@dongniwang I uploaded the design on Invision please have a look: https://redhat.invisionapp.com/share/J3P909MXTHQ#/332778522_Default_Status

**Comment by phantomjinx** [comment]
@nding-anges 

So this is an example of a detail message that is produced for a SYNDESIS011, ie. 'A connection associated...' message:

> PostgresDB:Connection$configured-properties
> 	=> '{password=»ENC:3f7a6a025bb0e953d8cbe0cba59328fc55f58732e9a037a13f4651ca ...'
> 	=> '{schema=sampledb2, password=»ENC:3f7a6a025bb0e953d8cbe0cba59328fc55f587 ...'

1. The syntax starts with the connection that has the difference and its specific property;
2. What follows is 2 bullet points representing the 2 differing values. In this case, configured-properties has an extra 'schema' property with a value of 'sampledb2'. These bullets are truncated to about 70 characters for the sake of brevity and communication.

To reiterate previous conversations, it was felt that showing this detail was something to be avoided in preference to the more generic messages. Therefore, the placement of this detail as detail hidden behind a button.

The detail property is only used currently for SYNDESIS011 & SYNDESIS012. However, that doesn't mean more messages could take advantage of it in the future. Obviously, their syntax may vary.

**Comment by dongniwang** [comment]
@gashcrumb @phantomjinx - do you know if we would have error messages (instead of warning messages) on this integration details page? e.g. what kind of message do we display when users are not able to publish an integration (and let's say they stay on this details page when the publishing is in progress)?

**Comment by gashcrumb** [comment]
I think there's two possibilities, one is if the API request errors out.
That'd be reported via toast notification.  The second case would be a
problem in the publishing process, that's reported eventually via an error
field on the integration object.  I think we may not surface that error on
the detail page at all as I think about it, it used to be the field that
would drive a red x on the integration list page.

**Comment by nding-anges** [comment]
@dongniwang @phantomjinx @gashcrumb 
> So this is an example of a detail message that is produced for a SYNDESIS011, ie. 'A connection associated...' message:
> PostgresDB:Connection$configured-properties
=> '{password=»ENC:3f7a6a025bb0e953d8cbe0cba59328fc55f58732e9a037a13f4651ca ...'
=> '{schema=sampledb2, password=»ENC:3f7a6a025bb0e953d8cbe0cba59328fc55f587 ...'

> The syntax starts with the connection that has the difference and its specific property;
What follows is 2 bullet points representing the 2 differing values. In this case, configured-properties has an extra 'schema' property with a value of 'sampledb2'. These bullets are truncated to about 70 characters for the sake of brevity and communication.

Regarding the example above, it is clear that provding more detail info on the Notification is more helpful and make more sense to the user than a general message.Therefore, Inline Notification has a limitation of characters  and  truncated policy. Maybe, it is not suitable for display more detailed information. It will be annoying on the header with too much characters. I think that we could explore another design solution for that .

**Comment by dongniwang** [comment]
Re the detail message in the above comment, I don't think we want to expose any of the password or sensitive information. 

And from a user point of view, what's the most important information from this message? I'm assuming "PostgresDB" is the most important part of the information. 

> So this is an example of a detail message that is produced for a SYNDESIS011, ie. 'A connection associated...' message:
PostgresDB:Connection$configured-properties
=> '{password=»ENC:3f7a6a025bb0e953d8cbe0cba59328fc55f58732e9a037a13f4651ca ...'
=> '{schema=sampledb2, password=»ENC:3f7a6a025bb0e953d8cbe0cba59328fc55f587 ...'

And what would be the immediate action they need to perform? Wondering if we can somehow aggregate this type of information into one message (maybe try the [n] number of message method), but allow users to see more. And we list out the connection names (based on the detailed message @phantomjinx mentioned above).

**Comment by nding-anges** [comment]
@dongniwang 
I agreed that we will not expose any of the password or sensitive information on the massage, and I'm not suggesting we will show an original massage directly from the backend.The message should be definitely re-wrote from the user stand point and make more readable.

From the example adove, we saw clearly that the message will content  two or more aspects: 
 1)  indicated which connection has problem ; 
 2)  indicated some specific property  of the connection.
 3)  this properties maybe has an extra 'schema' property with a value..ect 
The syntax may vary...

Showing all these detail info will be more helpful to the user than a single massage. I was wondering if we just show a type of information into one massage ( with different connection names + the[n] number of massage) , we will still need to display the detail somewhere on the UI and alllow user to check. 

So I suggest to make enhancement design or explore another design solution.


I was referring to the concept of having a "two more unread" and "dismiss all" message.
