### ISSUE TITLE
Extending the capabilities of the Template Step

### ISSUE THREAD

**Issue by phantomjinx** [syndesisio/syndesis#3649]
Building on the features produced in [#3047](https://github.com/syndesisio/syndesis/issues/3047), enhance the Template Step to:
- Include the use of alternative template libraries, ie. FreeMarker and Velocity;
- Follow the UI modifications as laid out in [UX Design v3](https://redhat.invisionapp.com/share/MKNX2N6SVE6) (as opposed to v3.1 which only provided for mustache);
- Dynamic runtime dependencies whereby the choice of library dictates which camel library the runtime integrations are build against, ie. camel-mustache, camel-velocity, camel-freemarker (currently camel-mustache is always included).

**Comment by mmuzikar** [comment]
Currently verifying this feature, I believe this might be part of #3598 but I'd like to explicitly state that comments are included in the output of the template step.

**Comment by tplevko** [comment]
Verified https://issues.jboss.org/browse/FUSEQE-2943
