### ISSUE TITLE
Add 5 icons for existing steps

### ISSUE THREAD

**Issue by amysueg** [syndesisio/syndesis#3650]
## This is a...

<pre><code>
[x ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
Per comments on #3630 we should increase the size of the representation of steps in the IVP to match that of Connections. This also conforms with the designs for #1830 to combine adding step and connection into one action.

## Expected behavior
The larger size circle will require an icon so that the user can tell what steps are included in the integration. This issue is for tracking the creation and review of icons to represent the 5 steps.  

1. Advanced Filter
2. Basic Filter
3. Data Mapper
4. Log Step
5. Template Step

Assigning to @sjcox-rh. FYI @michael-coker @dongniwang @seanforyou23 @jameslau

**Comment by sjcox-rh** [comment]
Svg's and png's uploaded for the 5 step icons. You can find there here:

https://github.com/syndesisio/syndesis/tree/master/ux/connections_icons

@dongniwang @amysueg @michael-coker @paoloantinori @gaughan

**Comment by amysueg** [comment]
Reassigning to @michael-coker to implement. Thanks.

**Comment by amysueg** [comment]
and @jameslau

**Comment by zregvart** [comment]
I'm not sure, I can't find them in the database, I can see icons for Connections and Connectors but none for the steps listed above. I can see for the integration details page that they all have the same icon drawn via CSS class `not-connection`:

https://github.com/syndesisio/syndesis/blob/c0b40c49e16409bf46d1dd90a3b985037fe06c5c/app/ui/src/app/integration/integration_detail/integration-description.component.html#L68-L70

And on the integration view pane it seems to be also drawn via CSS class `not-connection`:

https://github.com/syndesisio/syndesis/blob/ad0ef92a4938f5d16e04a0ed11c26c5d648dfec0/app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.ts#L171-L176

https://github.com/syndesisio/syndesis/blob/ad0ef92a4938f5d16e04a0ed11c26c5d648dfec0/app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html#L23

I would expect the `synIconPath` to be used if they were loaded from the backend.

@kahboom @gashcrumb do you have any pointers for us?

**Comment by michael-coker** [comment]
@zregvart oh yeah, these icons don't exist yet. I was referring to the icons we display for connections in the IVP being stored in the database. I'm assuming we would store these icons for steps in a similar manner?

**Comment by zregvart** [comment]
I've updated connection icons with #3735 (PR #3758), that is:

1. ActiveMQ
2. AMQP
3. AWS-S3
4. FTP
5. GMail
6. HTTP
7. HTTPS
8. IRC
9. LOG (connection)
10. MQTT
11. Salesforce
12. ServiceNow
13. SFTP
14. SQL (database)
15. Timer (connection)
16. Twitter

And the out of box connections to:

1. Sample Postgresql
2. Timer Connection
3. Log Connection

Those are stored in the backend database, (we're missing some in SVG but that's [another issue](https://github.com/syndesisio/syndesis/issues/3557#issuecomment-427667140)).

From what I understand the issue here is with the icons for the steps (Advanced Filter, Basic Filter, Data Mapper, Log Step, Template Step) and I don't think we have the ability to store those on the backend (yet/currently), i.e. there is no REST endpoint to fetch the Steps.

It seems to me that the Steps are entirely UI driven so we need to start there.

// cc @paoloantinori

**Comment by gashcrumb** [comment]
Yep, the built in steps are defined in
app/ui/src/app/store/step/step.store.ts only, you'd have to also update to
the step model and figure out how this works for extensions.

**Comment by zregvart** [comment]
@paoloantinori can we find someone to help with this?

**Comment by gashcrumb** [comment]
I can get it next week probably...

**Comment by michael-coker** [comment]
thanks @gashcrumb!!

**Comment by tplevko** [comment]
I noticed "log step" and "log connector" have the same icons. It could possibly cause some problems when using several log steps/connectors in integration, @sjcox-rh wdyt? 
![logger_icons](https://user-images.githubusercontent.com/4180208/47005283-b4b38000-d133-11e8-85ee-8396241c3e4f.png)
![logger_icon](https://user-images.githubusercontent.com/4180208/47005285-b715da00-d133-11e8-8a84-b35258995e62.png)

**Comment by gashcrumb** [comment]
@sjcox-rh can probably answer that question regarding the assets.

My question on this is why do we have a log step vs a log connector, and maybe one of them should go away.  @tplevko it might be better to raise this as a separate issue for discussion, as the work regarding this particular issue (create some icons) has been done.

**Comment by gaughan** [comment]
Yea is there a legacy reason why it is set this way? The step should go away I believe... if we define a step as having input and output in a flow. The functionality is different between the two as it stands today (no header available in the step)

**Comment by kcbabo** [comment]
There’s a big difference between log step and log connection.  The former’s
output shows up in the activity log.

**Comment by zregvart** [comment]
> There’s a big difference between log step and log connection. The former’s output shows up in the activity log.

@kcbabo don't get @KurtStam started on that (#3880)

**Comment by gashcrumb** [comment]
> The former’s output shows up in the activity log.

So the "log" connection doesn't actually log in a way the app can see...  Um.

**Comment by sjcox-rh** [comment]
@jameslau  of course, here is where all the icons are stored:

https://github.com/syndesisio/syndesis/tree/master/ux/connections_icons

They are two folders, one with all the svgs and the other with all the pngs.

**Comment by jameslau** [comment]
Thanks @sjcox-rh!

**Comment by kcbabo** [comment]
> So the "log" connection doesn't actually log in a way the app can see... Um.

Yes, that's pretty much what I said. :-)

**Comment by tplevko** [comment]
@dongniwang as this was moved to "7.3" release, should I move it from "done" state to "backlog"?

**Comment by amysueg** [comment]
The new icons are ready and @mcoker is adding them now.

**Comment by mastepan** [comment]
fix verified on 1.6.1-20190115
