### ISSUE TITLE
Fuse Parameters

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#3652]
See also **https://issues.jboss.org/browse/ENTESB-11521**

As an expert integrator, I want to be able to provide parameters to be stored and retrieved in my Fuse environment. I want to be able to store a connection string for different environments, for example, $dev for development or $stg for staging. I want to be able to use these variables when I go to configure a connector. A user can view, search and add parameters in the Settings tab. 
I want the ability to assign a variable the scope of: 
environment
integration (by selecting an existing integration) or 
connector (by selecting an existing integration) 
I want the ability to assign a label (existing or create a new label) to one or many variables. The purpose of the label is to be able to group a set of parameters for search. Multiple labels per variable can be applied.

DoD for first version:
I can declare a variable name and content.
I can use these variables when configuring a connector in Fuse Online.

The feature owner has confirmed one of the following:
--There is an initial draft of the user doc for this feature.
--The writer acknowledges receiving enough information from engineering to write the initial draft of the user doc for this feature.

### SubTasks:

- UX Design to view, search and add parameters in the Settings tab #4175
- API to View, search and add parameters #4177
- UI Implementation View, search and add parameters in the Settings tab #4176
- Backend implementation to serve the API to View, search and add parameters #4178
- Backend Implementation to use the parameters #4179

**Comment by KurtStam** [comment]
@gaughan is `environment` the same as a Kubernetes `namespace`?

**Comment by gaughan** [comment]
Hey Kurt, answers inline:
is environment the same as a Kubernetes namespace?
_An environment in this context is the fuse online instance_

Is there some kind of defined list of environments?
_No, not suggesting we maintain a list of environments_

I think you want a different value for $myDBconnection depending on the the environment you are in like dev, staging? I'm a bit confused by: $dev for development or $stg for staging.
can we assume that the type is always a string?
_Yes just a sting, dev could be any string_

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11521**
