### ISSUE TITLE
IRC connector related issues

### ISSUE THREAD

**Issue by tplevko** [syndesisio/syndesis#3655]
## This is a...

<pre><code>
[ x ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

IRC connector related issues, as discussed in previous email communication, and which was the reason for marking this as TP:
 * there are no properties on the connector itself - all the configuration is done in action properties. This means every time you want to use IRC connector, you need to fill in the configuration. This is not aligned with the user experience of using other connectors (screenshot 1)
  * this also means that you can't validate the connection as there is no button for that, the "step 2" when creating new connection is skipped for this connector (screenshot 2)
  * there is just one action ("React to privmsg") - that is in conflict with the IRC connector description that states: "Send and receive messages to/from an IRC chat" (screenshot 3 and 4)
  - minor one - there are no meaningful hints for the fields when trying to configure

screenshot 1:
![irc_configuration](https://user-images.githubusercontent.com/4180208/45943677-969ca900-bfe7-11e8-9d50-5b6b393baa4c.png)
screenshot 2:
![irc_step_2_skipped_no_validation](https://user-images.githubusercontent.com/4180208/45943762-eda27e00-bfe7-11e8-8d27-7c338f03f08f.png)
screenshot 3:
![irc_privmsg](https://user-images.githubusercontent.com/4180208/45943789-1165c400-bfe8-11e8-9792-4b0edba33a14.png)
screenshot 4:
![irc_privmsg](https://user-images.githubusercontent.com/4180208/45943802-1d518600-bfe8-11e8-9c60-b1c2c248f0fb.png)

**Comment by heiko-braun** [comment]
//cc @gaughan What are your thoughts on this?

**Comment by gaughan** [comment]
Agree we need to clean up. After this mornings call, can we feed this into some guidelines doc? Choose an action when there is only one action should not be something we force on the user, right?
