### ISSUE TITLE
Should `/apis/generator/save` API be available by default

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#3658]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

We expose `/apis/generator/save` API by default, the API documentation states that it's a test method, should we have it exposed by default?

https://github.com/syndesisio/syndesis/blob/6c84953b817675783d5613324dd610fc04670f06/app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/api/ApiHandler.java#L94-L112

Options are that it's available behind a feature flag `endpoints.test_support.enabled` and/or moved to `TestSupportHandler`.

I'm guessing this was something requested by the @syndesisio/qe?

**Comment by tplevko** [comment]
@zregvart I'm not aware of using this endpoint in our testsuite, for generating Integrations using rest, we use standard /integrations endpoint. I think this endpoint doesn't need to be available by default (at least for QE), so it can be behind the ```test_support.enabled``` flag.

**Comment by zregvart** [comment]
@nicolaferraro I guess that API can be removed or moved to test support (to be behind the `test_support.enabled` flag?)

**Comment by nicolaferraro** [comment]
The `/generator/save` API was necessary to be able to develop the different parts of the API provider story without the need to have the UI upload feature first.

Now the UI upload part is being developed by @riccardo-forina. After it is merged (and I think it will use the `/generator` - without `/save` - path), the save endpoint can be completely removed, as not needed anymore.

**Comment by riccardo-forina** [comment]
Actually, we are gonna use the `/generator/save` endpoint while creating the integration, since doing the whole creation with a volatile state is not doable without a huge refactoring effort.

So please keep it! :D

**Comment by zregvart** [comment]
@riccardo-forina you can use `POST /api/v1/integrations` with the result from `POST /api/v1/apis/generator`, only logic I see is that `POST /api/v1/generator/save` has an really ugly `name` set on the integration.

**Comment by tplevko** [comment]
Verified by QE, closing
