### ISSUE TITLE
Refactor out /deep/ selector from scss files

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#366]
_From @gashcrumb on November 17, 2017 14:46_

As [already noted](https://angular.io/guide/component-styles#deprecated-deep--and-ng-deep) by the Angular team, the shadow-piercing descendant combinator `/deep/` (plus its equivalent `>>>`) is [deprecated and support is being removed from major browsers and tools](https://www.chromestatus.com/features/6750456638341120). 

We currently use the `/deep/` combinator in the following files:

* [ ] /ui/src/app/settings/oauth-apps/oauth-apps.component.scss
* [ ] /ui/src/app/integrations/list/list.component.scss
* [ ] /ui/src/app/integrations/edit-page/step-configure/step-configure.component.scss#L42
* [ ] /ui/src/app/integrations/edit-page/flow-view/flow-view.component.scss#L120
* [ ] /ui/src/app/integrations/edit-page/connection-select/connection-select.component.scss#L49
* [ ] /ui/src/app/integrations/edit-page/action-configure/action-configure.component.scss#L45
* [ ] /ui/src/app/integrations/detail-page/detail.component.scss#L22
* [ ] /ui/src/app/dashboard/integrations.component.scss#L172
* [ ] /ui/src/app/customizations/api-connectors/api-connector-list.component.scss#L21
* [ ] /ui/src/app/connections/create-page/create-page.component.scss#L29
* [ ] /ui/src/app/common/ui-patternfly/syndesis-form-control.scss#L1
* [ ] /ui/src/app/common/ui-patternfly/list-toolbar/list-toolbar.component.scss#L1
* [ ] /ui/src/app/app.component.scss#L13

### How to proceed?

First, refrain from replacing `/deep/` by Angular's very own `::ng-deep` since it will be phased out soo too. The best approach is to accomodate the styles affecting the re-styled component in the component's CSS definition itself, with a specific meta selector pointing to those cases which that particular CSS should be applied depending on the element located in the parent tree. eg: For a given template:

```html
<section class="foo">
  <div>
    <my-custom-element></my-custom-element>
  </div>
</section>
```

Instead of defining the following:

```css
.foo /deep/ my-custom-element {
  color: blue;
}
```

Go straight to the CSS definition for `<my-custom-element>`, which will be probably located in a file named `custom-element.component.scss`, and do the following:

```css
:host-context(.foo) {
  color: blue;
}
```

By doing this we do not break component encapsulation and ensure that it is the component itself which takes care of its UI layout at all times.

_Copied from original issue: syndesisio/syndesis-ui#1231_

**Comment by kahboom** [comment]
Not sure if I'm using the 'Process' label properly here, but it seemed apt. 😂
