### ISSUE TITLE
Twitter connector as "End connection"

### ISSUE THREAD

**Issue by mmajerni** [syndesisio/syndesis#3664]
See also **https://issues.jboss.org/browse/ENTESB-11456**

## This is a...

<pre><code>
[ x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
A Twitter connector cannot be used as "End connection" in integration.
Screenshot: there is just actions pattern "From" in twitter connector definition.
i.e. Postgres connector has both patterns(From, To) 

## Expected behavior
A Twitter connector can be used as "Start connection"(working now) and "End connection".

![to-twitter](https://user-images.githubusercontent.com/22192892/46010378-b0f78500-c0c2-11e8-8078-3f925c48041d.png)

**Comment by oscerd** [comment]
This require discussion with @kcbabo and @gaughan. By the way the twitter-timeline component offers also specific producer side endpoints, same story for the twitter-search.

**Comment by gaughan** [comment]
added to 7.3 backlog for discussion

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11456**
