### ISSUE TITLE
Extract reason for equivalence failure when comparing 2 integration connections

### ISSUE THREAD

**Issue by phantomjinx** [syndesisio/syndesis#3667]
When a connection or integration is modified, a check is made on the integration connection's equivalence to the original connection stored in the server data store. The equivalence is recursive and therefore efficiently returns a status of equivalent or not. However, the actual element or property that does not match is not highlighted and a generic message is presented to users. This can leave the user in a state of confusion as to what exactly caused a lack of equivalence.

Fix the equivalence checks to provide enough detail to pinpoint what is causing a lack of equivalence.

**Comment by phantomjinx** [comment]
Reference - https://github.com/syndesisio/syndesis/issues/3637

**Comment by lburgazzoli** [comment]
@phantomjinx at the beginning it was done as you suggested but then a generic message was required by UI, maybe @gashcrumb remember what the issue was.

**Comment by phantomjinx** [comment]
@lburgazzoli 
That's fine. I think it's right to stick with the generic error message but am thinking of adding a second message or detail attribute that allows the user to discover more information if they prefer. This would tie in with the new component being explored in #3637, ie. an 'i' button maybe that displays 'detail' maybe.

@gashcrumb @dongniwang

**Comment by heiko-braun** [comment]
@phantomjinx Can elaborate in the use case or issue?

**Comment by phantomjinx** [comment]
@heiko-braun 

This is meant to tie in with #3637, which displays a number of generic notifications. These notifications provide no context as to what exactly has changed. This issue's purpose is the return of additional information from the server that would allow a UI notification component to be populated and answer the question "so what exactly is different between my integration's connection and the connection in the DataManager?".

**Comment by gashcrumb** [comment]
I think as a first step even having this debug information in the browser tools is a good first step so we can better understand what kind of notification or other information we can provide to the user, generally my issue with the behavior seen in #3637 is that the integration board is spammed by n messages that are the same where n seems to be the number of flows * the number of connections, I don't think that's the right approach :-)

**Comment by phantomjinx** [comment]
@gashcrumb 
I think that goes to a broader issue with the IntegrationUpdateHandler and ConnectionUpdateHandler. This PR doesn't change that. It actually moves lots of similar methods into a single validator-type class so as to try and glean some useful messages. Whether the ...UpdateHandler classes should be improved to maybe group/deduplicate messages is a further issue that should probably be looked at.

cc/ @lburgazzoli

**Comment by gashcrumb** [comment]
Yep, sounds good to me.  I got this branch running here now and did note that after rebuilding I got 2 notifications on an existing integration that was present before the rebuild.

![image](https://user-images.githubusercontent.com/351660/46491092-bf872000-c7d7-11e8-90ed-8ceff11a3a10.png)

Nothing's changed as far as I'm aware, but I wonder, is the difference here because the fields in the connection object have a different order when the comparison is performed?  This would be a concern as this feels like a false positive.

**Comment by phantomjinx** [comment]
@gashcrumb
Actually no. The equals method does check maps based on their key/values not their order. Unfortunately, converting the map to a string means the contents is ordered differently and the ... I added in to reduce noise has missed password v password.

Am willing to bet that the passwords are different since each new server build in OS creates new encrypted hashes.

**Comment by gashcrumb** [comment]
Ah, of course, in which case the message is totally warranted.  Perfect!
