### ISSUE TITLE
gmail and google calender oauth form config missing defaultValue parameters

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#3674]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Both the gmail and google calendar connectors have oauth form config JSON that have "hidden" fields but don't provide values for those fields, for example [see here](https://github.com/syndesisio/syndesis/issues/3672#issuecomment-424743192).

Ideally it should look like this:

![image](https://user-images.githubusercontent.com/351660/46088414-5e799f80-c17a-11e8-98d0-db14e450e3e4.png)

when `type` is set to `hidden`, the UI will post these values then when saving the oauth config.

Otherwise I'd say just remove these form fields and set them at the backend if there's no reason to expose them to the user.

**Comment by oscerd** [comment]
As far as I remember this fields are populated with predefined values on top of the json

**Comment by gashcrumb** [comment]
Do they really need to be in the form config then?  If the user can't change 'em anyways...

**Comment by oscerd** [comment]
As far as I see other connectors use the same approach for the oauth. I can make them visible. But set them in the back end is not feasible because these parameters are part of the syndesis oauth flow and they can be changed at component level. @zregvart wdyt?

**Comment by oscerd** [comment]
Maybe I'm missing the point here

**Comment by zregvart** [comment]
Oh, here you are @oscerd :smile: 

Perhaps we should filter out `hidden` properties on the server side, that would fix it no?

**Comment by zregvart** [comment]
And stay down.
