### ISSUE TITLE
Refactor the Customization section to us the new openapi components

### ISSUE THREAD

**Issue by riccardo-forina** [syndesisio/syndesis#3677]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

In PR #3676 I created a new module named `openapi` that expose 3 new components:

* a custom form field to upload a specification from the local filesystem / a remote url / create a new one from scratch
* a review component to render the validation response results
* an editor component, that embeds Apicurio

These components are based on the ones used by the Customization section but reworked to be reusable and Redux-compatible.

We should refactor the Customizations section as done in #3676.

**Comment by gashcrumb** [comment]
@heiko-braun I think it's worth having QE go through the API client connector flow with this one as well as it's a bit of refactoring, I guess probably that was going to happen thanks to the apicurio update but wanted to raise this just to be certain.
