### ISSUE TITLE
parameter SAR_PROJECT is required and must be specified

### ISSUE THREAD

**Issue by mronus** [syndesisio/syndesis#3687]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
I get the following exception when I run the command given in the quickstart doc.

`error: error processing template "myproject/syndesis": Template.template.openshift.io "syndesis" is invalid: template.parameters[4]: Required value: template.parameters[4]: parameter SAR_PROJECT is required and must be specified`

"oc new-app syndesis \
    -p ROUTE_HOSTNAME=syndesis.$(minishift ip).nip.io \
    -p OPENSHIFT_MASTER=$(oc whoami --show-server) \
    -p OPENSHIFT_PROJECT=$(oc project -q) \
    -p OPENSHIFT_OAUTH_CLIENT_SECRET=$(oc sa get-token syndesis-oauth-client)"

Doc: https://syndesis.io/quickstart/#template-selection

**Comment by rhuss** [comment]
Fixed with https://github.com/syndesisio/syndesis.io/pull/83. Thanks @zregvart !
