### ISSUE TITLE
Adding flow step to API provider based integration yields error

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#3694]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

I can't seem to edit a flow to add a step to it. The browser console emits an error:

```
main.bd08e7b5ad2ce0b417ba.js:1 TypeError: Cannot read property 'action' of undefined
    at n.ngOnChanges (11.bb2047dff352bcbffb47.js:1)
    at main.bd08e7b5ad2ce0b417ba.js:1
    at main.bd08e7b5ad2ce0b417ba.js:1
    at $a (main.bd08e7b5ad2ce0b417ba.js:1)
    at Sl (main.bd08e7b5ad2ce0b417ba.js:1)
    at Object.updateDirectives (11.bb2047dff352bcbffb47.js:1)
    at Object.updateDirectives (main.bd08e7b5ad2ce0b417ba.js:1)
    at Xa (main.bd08e7b5ad2ce0b417ba.js:1)
    at il (main.bd08e7b5ad2ce0b417ba.js:1)
    at rl (main.bd08e7b5ad2ce0b417ba.js:1)
```

## Expected behavior

I should be able to edit and add steps as needed to the flow.

## Screenshot

![peek 2018-09-28 12-34](https://user-images.githubusercontent.com/1306050/46203905-8a805680-c31b-11e8-83a2-47418f416a90.gif)

## API Endpoints and Schemas

I only see `GET` requests to `/api/v1/integrations/i-LNUix7uR6BhTm3sXS83z` and `/api/v1/monitoring/integrations/i-LNUix7uR6BhTm3sXS83z`, probably unrelated.

## Tasks involved / Steps to Reproduce

1. Create API provider based integration
2. Try to edit one of the flows to add a step

[console-log.txt](https://github.com/syndesisio/syndesis/files/2427874/console-log.txt)

**Comment by oscerd** [comment]
I believe the set-body extension currently don't work if you don't work with 1.5-SNAPSHOT syndesis dependencies.

**Comment by zregvart** [comment]
Perhaps it's an issue with Set Body extension, I can add the mapper to the POST request (one that has datashape on the start and end shapes)

**Comment by oscerd** [comment]
yes, the problem with setBody it's documented here: https://github.com/syndesisio/syndesis-extensions/issues/69 

Also we need to align the extensions to what we have in Syndesis.

**Comment by gashcrumb** [comment]
Page shouldn't be throwing that error anyways, will definitely fix that.

**Comment by gashcrumb** [comment]
Hmm, actually has nothing to do with the API provider or the set body extension, it occurs when the start connection doesn't have a data shape like the timer connection, so just a UI bug.

**Comment by mmajerni** [comment]
Verified
