### ISSUE TITLE
API provided flow visualisation, a bit wonky

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#3695]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

The number of flows in the API provider based integration is presented in an ellipse and its in dark orange colour. Perhaps it would be better if it was a circle in non error indicating colour?

## Expected behavior

Look nicer and less stressful.

## Screenshot

![screenshot_2018-09-28 syndesis](https://user-images.githubusercontent.com/1306050/46204537-d7652c80-c31d-11e8-87a7-3358c95a6012.png)

**Comment by gashcrumb** [comment]
Yeah, looks like the circle needs to be padded out for single digits.  Wonder, should we also cater for 3 digits in the circle as well?  I mean, it's possible to have a 100+ operation swagger file, isn't it?

Agreed, orange probably isn't the best color.  I think the idea is the number should be noticeable to convey that the integration is a different thing, but you're right, maybe a better color combination.

What about a blue kinda like the surrounding circle and white text still?

@dongniwang thoughts?

**Comment by riccardo-forina** [comment]
This is also discussed in #3601

**Comment by gashcrumb** [comment]
Ah cool, let's leave the discussion in there then :-)

**Comment by zregvart** [comment]
Let's close in favour of #3601
