### ISSUE TITLE
Copying to clipboard of exposed integration isn't on Firefox

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#3696]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Copy to clipboard of the URL in the integration details page is working in Chrome but not in Firefox.

## Expected behavior

Should copy the URL to clipboard in Firefox.

## Screenshot

![peek 2018-09-28 12-59](https://user-images.githubusercontent.com/1306050/46204792-b7823880-c31e-11e8-9984-7517aabfd8d6.gif)

## Tasks involved / Steps to Reproduce

1. Create an integration that will be exposed (WebHook or API provider)
2. Publish
3. Try to copy the URL from integration details page

**Comment by zregvart** [comment]
Perhaps something for you @seanforyou23

**Comment by elvisisking** [comment]
I could not duplicate this @zregvart. I am using Firefox Quantum v62.0.2 on OS X (Mojave). I used syndesis-staging and the same Test API integration to test.

**Comment by zregvart** [comment]
I'm fine with this being only on my computer :) Thanks for looking into it @elvisisking!

**Comment by mmuzikar** [comment]
Hey @zregvart the same thing is happening to me... is it working for you or could we perhaps determine what is causing this issue?
I am using firefox 66.0.2 on fedora 29.

**Comment by zregvart** [comment]
I think clipboard access in Firefox is prohibited by default, see http://kb.mozillazine.org/Granting_JavaScript_access_to_the_clipboard

**Comment by zregvart** [comment]
Though it's interesting that this works for me on the same Firefox on github.com. They're using https://github.com/github/clipboard-copy-element

I'm going to reopen this, perhaps there is something we can fix on our end.

**Comment by mmuzikar** [comment]
@zregvart copying works for me in the new react frontend... can you try this as well and perhaps we could consider this issue solved?

**Comment by zregvart** [comment]
I've tried this on Linux in Chromium (73.0.3683.86) and in Firefox (67.0) in the React frontend. Let's close this.
