### ISSUE TITLE
Twitter-Connector: Add support for twitter-directmessage endpoint

### ISSUE THREAD

**Issue by oscerd** [syndesisio/syndesis#3697]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

In the last days, I worked on fixing a bug upstream https://issues.apache.org/jira/browse/CAMEL-12838 and I believe it could be nice to have the support for directmessage endpoint. This could work as consumer and as producer and maybe this can be an occasion to revisit the support for "to" action also for the existent actions that we have.

**Comment by oscerd** [comment]
If needed I'm able to work on this.

**Comment by oscerd** [comment]
@paoloantinori @heiko-braun @gaughan

**Comment by heiko-braun** [comment]
+1 from me.

**Comment by gaughan** [comment]
+1 great!

**Comment by claudio4j** [comment]
I think this a duplicate of #3521

**Comment by oscerd** [comment]
Yes, thanks. You're right
