### ISSUE TITLE
Workday connector - Internal

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#3700]
See also **https://issues.jboss.org/browse/ENTESB-11518**

As a citizen integrator and HR recruiting representative I want to be able to connect my legacy Database to my workday environment in order to:
Create a position
Add applicants for consideration
Update a job posting
Remove a job posting
Transition from an applicant to hired status

https://community.workday.com/sites/default/files/file-hosting/productionapi/index.html

https://community.workday.com/sites/default/files/file-hosting/productionapi/Recruiting/v31.0/Recruiting.html

DoD for first version:
I can add a new position to my workday instance.

No documentation required for this story

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11518**
