### ISSUE TITLE
Determine URL of integration exposed via 3scale

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#3707]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

When we expose the integration via 3scale we need to determine the URL of the exposed integration. For non-3scale exposure we get this URL from the OpenShift Route. Should use 3scale API or is there a convention the URLs follow so we can generate the URL without involving 3scale?

Any pointers/ideas @guicassolato?

**Comment by guicassolato** [comment]
@zregvart, there is a pattern to generate the public staging and production endpoints based on templates set in the 3scale configs. It's is a bit complex though, I have to say. You can find the defaults at https://github.com/3scale/porta/blob/220911b1fd01a59ee7394f7cb56566ba3b137268/openshift/system/config/sandbox_proxy.yml#L10-L11.

```ruby
apicast_staging_endpoint: 'https://%{system_name}-%{tenant_name}-apicast-staging.<%=ENV.fetch('THREESCALE_SUPERDOMAIN', '3scale.net')%>:%{port}'
apicast_production_endpoint: 'https://%{system_name}-%{tenant_name}-apicast-production.<%=ENV.fetch('THREESCALE_SUPERDOMAIN', '3scale.net')%>:%{port}'
```

- `THREESCALE_SUPERDOMAIN` is an environment variable and it usually equals to the required parameter `WILDCARD_DOMAIN` provided in the 3scale deployment [\[1\]](https://github.com/3scale/3scale-amp-openshift-templates/blob/6ac1c4c3d136da1f2494319bdfa0742aed13029c/amp/amp.yml#L8-L9). Of course, it can be changed in the deployment for the 3scale `system-app` pod.
- `{system_name}` is the system name of the API in 3scale. It can be chosen by the user (i.e. the API provider's admin user). In the case where the service is "discovered" by 3scale within the same cluster [\[2\]](https://github.com/3scale/porta/pull/35), `{system_name}` is fixed and equals to `{k8s-svc-namespace}-{k8s-svc-name}`, respectively to the K8S/OCP namespace of the Service and the K8S/OCP Service name itself. Underscore characters (`_`) are always replaced with dashes (`-`) [\[3\]](https://github.com/3scale/porta/blob/220911b1fd01a59ee7394f7cb56566ba3b137268/app/models/service.rb#L425). 
- `{tenant_name}` is what 3scale calls the "provider subdomain" [\[4\]](https://github.com/3scale/porta/blob/220911b1fd01a59ee7394f7cb56566ba3b137268/app/models/proxy.rb#L169). It is extracted from the `domain` attribute of the API provider account in 3scale [\[5\]](https://github.com/3scale/porta/blob/220911b1fd01a59ee7394f7cb56566ba3b137268/app/models/account/domains.rb#L150) – basically whatever the API provider's domain contains preceding again the `THREESCALE_SUPERDOMAIN.
- `{port}` is usually fixed `443`, although it can be changed by tweaking with the sandbox proxy configs

Other parameters of the template, not used in the examples I shared are:
- `{env}`: usually an empty string, but it can resolve to `pre.` in special deployments of 3scale preview environment
- `{account_id}`: API provider's 3scale account ID

----

Of course, you can also fetch those endpoints after the API is created in 3scale. Please check the "Proxy Read" endpoint of 3scale API Docs: https://github.com/3scale/porta/blob/220911b1fd01a59ee7394f7cb56566ba3b137268/doc/active_docs/Account%20Management%20API.json#L5680

Keep in mind though that for service discovery, API creation happens asynchronously. The user request it in the UI, but it is actually performed by a background job.


cc/ @mikz

**Comment by mikz** [comment]
Users can change that host to something else any time. Why do you need it?

**Comment by zregvart** [comment]
@mikz when we expose via OpenShift route, we provide within Syndesis UI the URL for the exposed API. I’d like to provide the same functionality when we expose via 3scale.

**Comment by mikz** [comment]
@zregvart I thought it is going to be the User's action to expose the API. 3scale already exposes all published APIs through a wildcard route (using the superdomain). Also, the action is not just exposing route, but also setting up the usage rules, plans, metrics, ...

We plan to have OpenShift integration in the future and create a Route instead of using the wildcard router, but it is not going to be there in the next release. But still, it would be the User's action to go to 3scale, discover a service and create an API from it.

**Comment by zregvart** [comment]
Since the users will use 3scale to manage APIs exposed via 3scale it makes no sense to replicate the URL of the exposed API in Syndesis. The users can fully manage the URL in 3scale and that is the best place for this functionality.
