### ISSUE TITLE
Allow the citizen integrator to choose how the integration is exposed

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#3708]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

With #3504 we expose the integration via 3scale if the backend is configured to do so. So every integration that ends up being exposed (API provider, webhook) will be exposed either via 3scale API gateway or via OpenShift Route.

We should allow the user to choose how to expose integrations on a per-integration basis (from this evil comment https://github.com/syndesisio/syndesis/issues/3504#issuecomment-424816704).

**Comment by zregvart** [comment]
I need some help from @syndesisio/uxd on this (cc @dongniwang).

We're working towards having two methods of exposing API based integrations (API Provider based first, WebHook after that). This means that the citizen integrator will have the option to choose to expose either via mechanism that we have already (using OpenShift Route) or a new mechanism via 3scale API gateway.

This is something the citizen integrator can choose based on the functionality the required for a particular integration (3scale offers more functionality). Citizen integrator might opt to change this exposure mechanism and then re-publish the integration if needed. The chosen method will be in effect only after publishing the integration.

One idea would be to group the existing "Exposed URL" widget and the new "Expose via" (work in progress name) on the Integration details page.

Something like:
![screenshot from 2018-10-01 22-09-00](https://user-images.githubusercontent.com/1306050/46312921-cb4fc800-c5c6-11e8-95f5-7b07c070a574.png)

And that _might_ work. I think the drawback of this would be that the citizen integrator will arrive at integration details only on **Publish** or **Save Draft**. So to change the mechanism (we might choose default) this might be few clicks too far.

So we might want to present this choice in the API provider wizard also.

Something like:
![screenshot from 2018-10-01 22-33-08](https://user-images.githubusercontent.com/1306050/46314168-161f0f00-c5ca-11e8-96ea-dfe398cd26c8.png)

**Comment by dongniwang** [comment]
A quick recap of some thoughts and ideas based on a few conversations around this topic: 
- Possibly, we need to move the configuration of exposing API based integrations to the integration details page instead of part of the create integration flow
- Need to provide more explanation regarding the two methods, as well as what's going to happen if users choose one or another 
> This means that the citizen integrator will have the option to choose to expose either via mechanism that we have already (using OpenShift Route) or a new mechanism via 3scale API gateway.
- We need a way to direct users to 3scale if that's the selected method, still pending if we need a way from 3scale to get back to syndesis 
- May need to review the termiology used here and in 3scale to ensure consistency  

cc: @amysueg @zregvart @riccardo-forina @guicassolato

**Comment by heiko-braun** [comment]
//cc @gaughan

**Comment by chirino** [comment]
Would be cool, if we could provide the right link to 3scale.
For example,  if api is not created in 3scale yet, a provide link that says "Expose API via 3Scale".
Once it is created in 3 scale, then have a link that says: "Manage API in 3Scale", and we should also list the public API URL.

**Comment by zregvart** [comment]
The logic to choose the type of exposure on the backend is in the [ExposureDeploymentDataCustomizer.java](https://github.com/syndesisio/syndesis/blob/139caa7a2c784a7ee370d7b03661e1489ebe66a9/app/server/controller/src/main/java/io/syndesis/server/controller/integration/online/customizer/ExposureDeploymentDataCustomizer.java), where we depend on environment variable `CONTROLLERS_EXPOSE_VIA3SCALE` having the value `true`.

**Comment by rareddy** [comment]
UX wise Data Integration also needs the same options presented to the user as the Integration.

**Comment by rkorytkowski** [comment]
@zregvart, shall I get rid of the global switch entirely or apply it, if default/nothing is chosen?

**Comment by zregvart** [comment]
Ideally we would know what's applicable, for instance if there's no 3scale available we wouldn't offer such option. With that in mind I think we need a global variable indicating that 3scale is available. So perhaps we can remove the existing switch and introduce a new one signalling that the exposure via 3scale is possible, say an URL to the 3scale instance. Not sure what the default should be, I think it makes sense to default to 3scale, we should make it obvious to the user that when exposing via 3scale there's an additional step required: configuring the API in 3scale. We can then use the configured URL and link to 3scale admin console.

Hope this makes some sense...

**Comment by gaughan** [comment]
An admin page for global settings like this in Syndesis would be nice. That way you could set it for your environment and be done.

**Comment by rareddy** [comment]
May be some 3scale based service discovery would be nice.

**Comment by zregvart** [comment]
> May be some 3scale based service discovery would be nice.

@rareddy do you mean discovering 3scale from Syndesis? I think a first step might be providing the URL to 3scale at installation (or an admin page as @gaughan mentions). With 3scale's natural multi-tenacy it's difficult even if we do know how to discover 3scale which tenant to choose.

**Comment by rareddy** [comment]
Yes, for example, 3scale admin user creates the API admin user in 3scale, which should be the same user or share the same role that user logged into Syndesis.

**Comment by zregvart** [comment]
Heads up @TovaCohen we need this documented.

**Comment by TovaCohen** [comment]
I created https://issues.jboss.org/browse/FUSEDOC-3425 to do the doc work.

**Comment by rkorytkowski** [comment]
Thanks @TovaCohen! Some screenshots for the implemented feature (copied from PR):

![image](https://user-images.githubusercontent.com/1163157/64020281-86634700-cb31-11e9-9393-2c5f364e202e.png)
![image](https://user-images.githubusercontent.com/1163157/64020290-8bc09180-cb31-11e9-950f-6da9397dca71.png)
