### ISSUE TITLE
Syndesis Server running at 75% CPU

### ISSUE THREAD

**Issue by phantomjinx** [syndesisio/syndesis#3717]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
The syndesis-server pod takes a lot of CPU! If left untamed it has a tendency to swipe 3 CPUs. If limited by Openshift to 1 CPU then it runs smoothly with 75% (while its couple of subordinate threads reside on 50%+). See htop screenshot.

By profiling the server, it is possible to get an idea of what is taking up the CPU time. The IntegrationUpdateHandler validates all integrations (including deleted integrations!) by calling validators on each integrations fetched from the DataManager. The trouble is the NoDuplicateValidator then fetches all the integrations from the DataManager in order to test for duplicates:

IntegrationUpdateHandler:
```
List<Integration> integrations = DataManager.fetchAll(Integration.class ...)
for (Integration integration : integrations) {
  ...
  messages.addAll(computeValidatorMessages(supplier, integration));
  ...
}
```

NoDuplicateIntegrationValidator:
```
...
final Set<String> names = dataManager.fetchAll(Integration.class).getItems().stream()
...
```

Fetching integrations from the DataManager is expensive and slow in this case since there is no caching of the integrations (or at least caching is not used since a DataAccessObject is available for the Integration [class](https://github.com/phantomjinx/syndesis/blob/master/app/server/dao/src/main/java/io/syndesis/server/dao/manager/DataManager.java#L216)).

**Comment by phantomjinx** [comment]
![htop-status](https://user-images.githubusercontent.com/1634180/46352013-ad2eaa00-c650-11e8-830c-5bc63dcf9b5b.png)

HTop display showing syndesis server running at 75% CPU

**Comment by phantomjinx** [comment]
![snapshot-visualvm](https://user-images.githubusercontent.com/1634180/46352241-3219c380-c651-11e8-8d3f-67b0f9e5ebe9.png)


VisualVM snapshot of the CPU threads of the syndesis server
Note:
- The ResourceUpdateController thread is active for 583ms of the 693ms recorded;
- computeValidatorMessages() is taking 99.4% of the CPU time of the ResourceUpdateController thread;
- (Not Shown) DataManager.fetchAll() is responsible for 580ms of the 583ms used by computeValidatorMessages().

**Comment by phantomjinx** [comment]
Commenting out the computerValidatorMessages() function entirely reduces the CPU usage of the server to below 20% (with occasional spikes up to 25%).

**Comment by zregvart** [comment]
Good catch and a great analysis!
