### ISSUE TITLE
Default Connection Values aren't passed to MetaDataExtensions 

### ISSUE THREAD

**Issue by johnpoth** [syndesisio/syndesis#3719]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

When creating a Connection based on default values, connection properties aren't passed to MetadaExtensions. Re-entering default values in the Connection solves the problem.

Thanks!

**Comment by gashcrumb** [comment]
Related conversation:

![image](https://user-images.githubusercontent.com/351660/46359461-55d01000-c637-11e8-9321-e88f5c59e2dc.png)

I'm having a peek at the request made when the connection is created to verify.

**Comment by gashcrumb** [comment]
Which connector was this for BTW?

I had a look through the existing connectors while trying to reproduce this and settled on the TODO connector, as that was the first one I found that had some default values.  The connection configuration posted is as I'd expect, the `basePath` and the `authenticationType` and `specification` field are all values that come from the `properties` object in the connector:

![image](https://user-images.githubusercontent.com/351660/46364455-d7c63600-c643-11e8-821c-9f694f57ea0c.png)

I was however forced to enter in a username/password, so I'm concerned that I'm not quite making the same test.  Can you provide more detailed steps to reproduce this please?  Thanks!

**Comment by johnpoth** [comment]
Hi @gashcrumb , thanks for looking into this!

I'm developing a new [connector](https://github.com/johnpoth/syndesis/tree/fhir-connector/app/connector/fhir), which isn't in Syndesis yet.

Here's the concerned property configuration:

        "serverUrl": {
            "kind": "parameter",
            "displayName": "FHIR server URL",
            "group": "common",
            "required": false,
            "type": "string",
            "javaType": "java.lang.String",
            "deprecated": false,
            "secret": false,
            "order": "1",
            "raw": true,
            "defaultValue": "http://fhirtest.uhn.ca/baseDstu3",
            "labelHint": "The base URL of your FHIR server"
        }

Note that the Camel Component is instantiated correctly so the values seem to be passed to the component. However they aren't passed to the [FhirMetadaExtension](https://github.com/johnpoth/syndesis/blob/fhir-connector/app/connector/fhir/src/main/java/io/syndesis/connector/fhir/FhirMetaDataExtension.java#L14).

I'll see if setting the "required" field to true changes the behavior. Thanks!

**Comment by zregvart** [comment]
From what @johnpoth is typing, it seems that we're missing `serverUrl` value in `sanitized` here:

https://github.com/syndesisio/syndesis/blob/2d2a899a1b8ab8c12c1c58a0fe12ff2e68996b55/app/ui/src/app/connections/common/configuration/validation.component.ts#L39

**Comment by gashcrumb** [comment]
I can double-check that.  It should be set on that formGroup object at that point as the dynamic form service should copy the default value over to the `configuredProperties` object.

Also @johnpoth if you could maybe verify via the browser developer console in the Network tab what is posted when going through the create connection wizard that'd be super helpful.

**Comment by johnpoth** [comment]
sure! When I manually enter the values, I get a request to `/api/v1/connections` which contains the payload:

configuredProperties:{serverUrl: "http://fhirtest.uhn.ca/baseDstu3", fhirVersion: "DSTU3"}

When I don't enter any values when creating FHIR connections no 'configuredProperties' field appear in the request payload.

HTH

**Comment by gashcrumb** [comment]
Yep, perfect, I think I can see where it's going wrong...

**Comment by johnpoth** [comment]
awesome thanks @gashcrumb !
