### ISSUE TITLE
Data mapper step isn't available for 

### ISSUE THREAD

**Issue by mastepan** [syndesisio/syndesis#3725]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[  x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

If I want to create an integration **Whatever -> DB** I can't use (is not available) **Datamapper step** (e.g. if I want to insert any data into DB from a previous connection)
![todbintegration](https://user-images.githubusercontent.com/8707251/46415068-c99c1680-c724-11e8-88bc-330c28b2fa1f.png)

**Comment by gashcrumb** [comment]
Can you list out exactly what steps you're following for this?

If I do DB periodic SQL invocation -> log there's no data mapper step available, but the log step doesn't have a data shape.

But if I do DB SQL -> stored procedure (create lead) I can add a data mapper step as I would expect.

**Comment by mastepan** [comment]
hm...I used Periodic SQL invocation -> Periodic SQL invocation which might not make much sense...
So the only way how to insert data into DB is creating a stored procedure?
Your scenario works as expected.

**Comment by zregvart** [comment]
> So the only way how to insert data into DB is creating a stored procedure?

Should not be the only way, regular `INSERT` statements should work. Could be an issue with the dynamic data shape not being generated under certain conditions/for certain statements.

@mastepan Perhaps you can share the exact database step configuration (SQL statements and all).

**Comment by zregvart** [comment]
Re-reading this, perhaps the issue is here that we offered periodic SQL actions at the end of the integration, that doesn't make much sense as @mastepan noted.

**Comment by gashcrumb** [comment]
I think *INSERT* used to work, didn't it?  What statement did you use?

I can check and see what data shapes are available in this case, I think your statement needs to have a parameter, otherwise there's no data shape I think, which would mean the data mapper would be hidden.

**Comment by mastepan** [comment]
@zregvart It isn't periodic action...I misread it. It's just SQL action.
@gashcrumb If I use parametrized INSERT statement DataMapper is available. 
INSERT INTO my_table VALUES (1,:#param)
