### ISSUE TITLE
Provide copy/paste callback URL for Syndesis on OAuth Settings page

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#373]
@kcbabo commented on [Sun Nov 19 2017](https://github.com/syndesisio/syndesis-project/issues/184)

We force users to manufacture the callback URL now - would be much easier if we simply provided a copy/paste callback URL on the OAuth Settings page.  Having users manually create the URL from an example URL in the docs and their specific account URL is just asking for trouble.

**Comment by dongniwang** [comment]
Reference: 
https://github.com/syndesisio/syndesis-ui/issues/870
https://github.com/syndesisio/syndesis/issues/279

**Comment by kcbabo** [comment]
@gashcrumb @rhuss : any chance we can get this in for TP4?  Seems like a minor change that would help our users quite a bit.

**Comment by gashcrumb** [comment]
+1

**Comment by dongniwang** [comment]
PR #3023 merged so closing this issue.
