### ISSUE TITLE
WebHook and 3scale integration

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#3731]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

With #3504 and follow-up in #3636 we exposed API provider based integrations, using labels/annotations and 3scale service discovery, via 3scale.

We should look into doing the same for WebHooks or disabling 3scale integration for Webhooks all together.

We probably need to think about what can we do for 7.2 and what we do beyond that.

What I propose: for 7.2 we don't enable 3scale service discovery for WebHooks (expose them via OpenShift Route, don't add label/annotations). The argument for that would be that the WebHook already has the random token that serves as authorization and in general WebHooks are public.

In next release we might offer the choice to the citizen integrator, and then we might opt not to generate the random token, but leave that to 3scale and manage API keys there. For this we would also need to provide OpenAPI spec for the WebHook (based on the DataShape provided by the user).

cc @gaughan @kcbabo

**Comment by tplevko** [comment]
@heiko-braun @zregvart Michael verified that the webhook is not exposed using 3scale for this version (7.2). Do you want to keep this issue open and assigned to one of the future releases, as the description addresses different issue as the one solved in the commit, or can we close this one and new one for 7.3. will be (is) created?
