### ISSUE TITLE
Update to grayscale icons

### ISSUE THREAD

**Issue by sjcox-rh** [syndesisio/syndesis#3735]
There was feedback that the grayscale connector icons look disabled. I've updated the 3 in question so they have color.

- SQL
- Timer
- HTTP

https://github.com/syndesisio/syndesis/tree/master/ux/connections_icons

This isn't a priority but wanted to update the icons for when there is time to replace them.

@gashcrumb @gaughan @amysueg @michael-coker @dongniwang @paoloantinori

**Comment by amysueg** [comment]
Thanks @sjcox-rh !

**Comment by amysueg** [comment]
@gashcrumb   - @gaughan  had pointed out that they seemed to indicate "disabled" state so @sjcox-rh updated the grayscale icons to include color.  Could you or another UI dev replace the old with the new icons? Thanks!

**Comment by tplevko** [comment]
Verified by QE
