### ISSUE TITLE
tooltip/popover overlap in IVP

### ISSUE THREAD

**Issue by michael-coker** [syndesisio/syndesis#3745]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
* The connection icon has a tooltip, and the warning icon has a popover, and they have an overlap issue when both are visible.
* There is no right padding on tooltips with long text.

## Expected behavior
* The popover should display on top of the tooltip?
* There should be padding.

## Screenshot
<img width="866" alt="screen shot 2018-10-04 at 9 55 28 am" src="https://user-images.githubusercontent.com/35148959/46485341-1af9e380-c7c1-11e8-8dcc-0aac9077eb91.png">
<img width="333" alt="screen shot 2018-10-04 at 4 47 15 pm" src="https://user-images.githubusercontent.com/1402829/46502175-86f63f00-c7f5-11e8-86be-e0c2240637dc.png">

## Tasks involved / Steps to Reproduce
1. Create an integration with a data type warning.
2. Hover over the connection in the IVP and click the warning icon.

**Comment by michael-coker** [comment]
cc @dongniwang do you agree with the expected behavior?

> The popover should display on top of the tooltip

**Comment by dongniwang** [comment]
> The popover should display on top of the tooltip

Yes, I agreed. 

Just curious - does the tooltip have a fixed location, which means it always shows up at the same place? Or it depends on where the mouse is? If that's the case, I don't have a strong preference of always have to show the popover on top of the tooltip. As long as they're not overlapping is fine.
