### ISSUE TITLE
API provider exposure/discovery consistency

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#3746]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
I'm labelling this as a bug as lack of consistency usually is.

We need to align how we do exposure/discovery in Apicurito generated project using fabric8-maven-plugin and in Syndesis.

From Syndesis point of view:

1. `basePath` handling

`basePath` should be taken from the uploaded OpenAPI 2.0 specification, if present, and it should determine the servlet mapping (contextPath) for the Camel Servlet. If not present it should default to `/` and the servlet mapping should be `/*`.

2. remove `discovery.3scale.net/path` annotation

We specify `basePath` in the generated REST DSL and set the CamelServlet mapping, it's also set as `basePath` in the generated Swagger document. So we don't need to specify `discovery.3scale.net/path` annotation as it would calculate the path to the API with duplicate base path.

3. OpenAPI 2.0 specification serving

We should serve the OpenAPI 2.0 specification from `/openapi.json`, this should be the provided OpenAPI 2.0 specification not the auto-generated one from REST DSL.

@KurtStam @chirino please review and add additional changes we need to be consistent across all projects

## Related, additional report from Kurt

In the swagger for https://github.com/KurtStam/syndesis-quickstarts/tree/master/api-provider, no contextPath is specific. So as far as the user is concerned the URL at which the API runs is
{$externalURL}/todo

however it is

{$externalURL}/api/todo

There is another issue opened on this why we are doing this, but if we keep doing it then we should include the /api part in the externalURL. It's complete guess work for the enduser right now.

**Comment by KurtStam** [comment]
Yes at the moment we seem to be defaulting this basePath to /api which is not clear at all to the enduser.

**Comment by zregvart** [comment]
Another data point is that for the [TODO swagger](http://todo-syndesis-staging.b6ff.rh-idev.openshiftapps.com/swagger.json) the `baseBath` is set to `/api` and with the path for `GET` (fetch all) and `POST` (create new) is set to `/`, but the resulting integration ends up having `/api/api` URL for those two operations (and presumably `/api/api/{id}`) for the other two operations.

//cc @dongniwang
