### ISSUE TITLE
Integration Import: note && validation of file format

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis#375]
Could we add note about desired file format is `zip` only and not e.g. `model.json`. And also validation that zip file is being uploaded to prevent further user-errors.
@chirino wdyt?

**Comment by chirino** [comment]
Could you clarify what this means?  You want UI text saying they should pick a '.zip' file?  You should get an error message if you try uploading a bad file now.

**Comment by amysueg** [comment]
Will be included as part of UX Design issue #333 
Closing this ticket.
