### ISSUE TITLE
Slack connection - Delay time doesn't work

### ISSUE THREAD

**Issue by mkralik3** [syndesisio/syndesis#3761]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
I have integration Slack -> PostgreSQL. For Read Messages, I have set Delay to 8 minutes and Maximum Messages to Retrieve to 2.
Maximum Messages work but Delay field doesn't work for me. Every time when I post message to the channel, immediately I see message in the integration metrics and saved in the DB.

**Comment by oscerd** [comment]
This is fixed in Camel. Need to release a dev build and pin it, then I'll upgrade in Syndesis.
