### ISSUE TITLE
Mark API Provider as tech preview

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#3764]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

API Provider is technology preview and should be marked as.

**Comment by rhuss** [comment]
@heiko-braun looks like pure-bot was confused as it labels two `progress/` like labels.

**Comment by heiko-braun** [comment]
could also be a remote call that failed to reset the labels. thanks for the notice.

**Comment by tplevko** [comment]
It's marked as TP, verified
