### ISSUE TITLE
Invalid Cert error on minishift stop/start

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#3766]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[*] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

....
You are logged in as:
    User:     developer
    Password: <any value>

To login as administrator:
    oc login -u system:admin

error: The server uses a certificate signed by unknown authority. You may need to use the --certificate-authority flag to provide the path to a certificate file for the certificate authority, or --insecure-skip-tls-verify to bypass the certificate check and use insecure connections.
Could not set oc CLI context for 'minishift' profile: Error during setting 'minishift' as active profile: Unable to login to cluster

To Reproduce:

Install Syndesis using

sy minishift --full-reset --install

then 

minishift stop

and on 

minishift start

I get the error above.

**Comment by KurtStam** [comment]
Workaround is to login using the '--insecure-skip-tls-verify' flag. Can't we auto-trust our own self signed certs?

**Comment by zregvart** [comment]
> Workaround is to login using the '--insecure-skip-tls-verify' flag. Can't we auto-trust our own self signed certs?

That's probably a question for `minishift`, I saw in #3799 that you have an older version, does upgrading to a newer one help?

I'm running:

```
$ minishift version
minishift v1.22.0+7163416
```

And I don't get that error.

**Comment by KurtStam** [comment]
minishift version
minishift v1.25.0+90fb23e

Maybe I should downgrade :)

**Comment by KurtStam** [comment]
Can no longer reproduce
