### ISSUE TITLE
UI incorrectly indicates Telegram connector is Technology Preview 

### ISSUE THREAD

**Issue by TovaCohen** [syndesisio/syndesis#3769]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
For 7.2, the Telegram connector is fully supported. It is no longer Technology Preview as it was in 7.1. However, the UI still shows that it is Technology Preview:

![image](https://user-images.githubusercontent.com/25067106/46625524-4e5eaa00-cb02-11e8-90aa-5c4ca04d2dde.png)

The "Technology Preview" indicator needs to be removed.

**Comment by tplevko** [comment]
Verified
