### ISSUE TITLE
Upgrade Angular CLI to v1.5.x

### ISSUE THREAD

**Issue by deeleman** [syndesisio/syndesis#377]

**Comment by jimmidyson** [comment]
Getting warnings in build:

> [WARNING] npm WARN deprecated angular-cli@1.0.0-beta.28.3: angular-cli has been renamed to @angular/cli. Please update your dependencies.

**Comment by deeleman** [comment]
This issue has not been actioned yet, so that warning is unrelated. In any event `angular-cli@1.0.0-beta.28.3` is quite too outdated and I recall someone (perhaps it was you @seanforyou23?) reported this a few days ago. Apparently it turns out it was caused by an outdated image fetched from the cluster.

Perhaps @seanforyou23 might provide a workaround :)
