### ISSUE TITLE
Cannot create API Provider integration from YAML

### ISSUE THREAD

**Issue by asmigala** [syndesisio/syndesis#3774]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

The API Provider starting step only allows JSON, URL or manual way of defining APIs, no YAML. This is similar to #3578, so the solution should probably be the same

**Comment by tplevko** [comment]
@asmigala please verify the fix

**Comment by asmigala** [comment]
Verified with latest master.
