### ISSUE TITLE
 API Provider: Ability to edit OpenAPI definition after provider is created

### ISSUE THREAD

**Issue by asmigala** [syndesisio/syndesis#3775]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
It is currently impossible to edit an API provided by API Provider integration once it's been created (either from uploading swagger.json or from scratch). This is particularly limiting when creating from scratch, where a certain amount of back-and-forth is expected.

**Comment by zregvart** [comment]
Something to ponder about for the next release when we add more functionality to API provider.

//cc @gaughan

**Comment by gaughan** [comment]
Yes, we need edit functionality before GA

**Comment by zregvart** [comment]
Yeah I thought it was out of scope for 7.2. Lets see what we would need to do to get this done:
 - endpoint on the backend to fetch the original OpenAPI specification
 - endpoint on the backend to update the flows of current integration based on given OpenAPI specification, that would:
    - delete all flows that are no longer present in OpenAPI specification, matched by operation id (if present) and HTTP method and path (if not)
    - add all flows that do not exist in the integration to update, matched by operation id (if present), HTTP method and path (if not)
    - change shapes of all start/end steps of a flow that have changed, matched by operation id (if present), HTTP method and path (if not)
 - mark changed flows needing update on the backend, so the UI can show that the flow needs updating
 - update notification/mark on the UI based oh the former
 - action to edit the OpenAPI specification of an integration on the UI that:
    - loads the original OpenAPI specification from the backend
    - displays Apicurio UI
 - action to update the integration based on the edits in Apicurio UI that would:
    - send the updated OpenAPI specification to the backend
    - reload/update the integration UI state from the backend

// cc @paoloantinori @heiko-braun @riccardo-forina

**Comment by gaughan** [comment]
@zregvart 7.2 is Tech Preview (this was the goal in the beginning) 
7.3 is the target for GA 
Sorry, I should have mentioned above.

**Comment by zregvart** [comment]
I think this can be an epic in itself.

**Comment by zregvart** [comment]
Implemented.
