### ISSUE TITLE
Clicking 'Go to Operation List' button discards all work in progress

### ISSUE THREAD

**Issue by asmigala** [syndesisio/syndesis#3776]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

When editing and API Provider integration and defining the steps for a particular operation, clicking the 'Go to Operation List' button returns to the operation list immediately, without saving the work on the currently open flow or warning the user. This makes this button work effectively the same as the Cancel button.

## Expected behavior

Two possibilities:
1. save on-the fly or when the Go to Operations List button is clicked
2. warn the user (using a pop-up or something) that going back to the operation list will discard their changes and they need to save a draft if they want to retain them.

## Screenshot

![image](https://user-images.githubusercontent.com/9480152/46659586-7fe47d80-cbb5-11e8-8c62-4b0b53f1f4d3.png)

## Tasks involved / Steps to Reproduce

1. Create an API provider integration with multiple operations
2. Edit one of the operations, add some steps
3. Click the 'Go to Operations List' button
4. Open the same operation again, the steps are gone

**Comment by asmigala** [comment]
Probably duplicates / is part of autosave #3048

**Comment by heiko-braun** [comment]
@dongniwang Can you share your thoughts on this?

**Comment by dongniwang** [comment]
Thanks @heiko-braun for tagging me. 

> 1. save on-the fly or when the Go to Operations List button is clicked

We don't support autosave right now, so we definitely need users to explicitly click "Save as Draft" to save any progress they've made on the integration. Unless it's possible to save on the fly? @riccardo-forina @gashcrumb @zregvart 

> 2. warn the user (using a pop-up or something) that going back to the operation list will discard their changes and they need to save a draft if they want to retain them.

Yeah, I agreed that we should warn users if they will lose all the changes upon clicking "Go to Operations". However, I think it would be annoying if users get a modal dialogue everytime they click the button. What if they just want to quickly check something on the list page? 

Is there a way to check and see if users have saved a draft for that integration when they click the button? In other words, only when users have _NOT_ perform any "save" activites, then we display the modal dialogue? Does this make sense?

**Comment by zregvart** [comment]
> We don't support autosave right now, so we definitely need users to explicitly click "Save as Draft" to save any progress they've made on the integration. Unless it's possible to save on the fly? @riccardo-forina @gashcrumb @zregvart

We can certainly send all the data about the integration to the backend (it would be same as the user clicked save draft, but navigated to the operations list instead of integration details page), but perhaps it would be better to see if we're reloading from the backend on navigation to operations list and prevent that to work with what we have in browser memory. Similar to how we navigate between steps of a flow without loosing what was edited in the step/action configuration.

**Comment by amysueg** [comment]
I agree this is important to address - @dongniwang should we discuss at our UXD meeting this afternoon?

**Comment by gaughan** [comment]
@heiko-braun can we add a warning or modal?

**Comment by heiko-braun** [comment]
@riccardo-forina @gashcrumb See @gaughan question above. Is there a quick fix for remedy the situation in 7.2?

**Comment by dongniwang** [comment]
@syndesisio/uxd met and discussed this and we agreed with Zoran's statment below. We think this is the most natrual behavior and least interrupting approach. 
> Similar to how we navigate between steps of a flow without loosing what was edited in the step/action configuration.

**Comment by gashcrumb** [comment]
I think this comment -> https://github.com/syndesisio/syndesis/issues/3798#issuecomment-429943246

**Comment by tplevko** [comment]
@asmigala please verify the fix

**Comment by asmigala** [comment]
Verified on latest master that returning to operation list now saves the work in progress.
