### ISSUE TITLE
Google Calendar Connector: Set a String input Datashape for the get Event action

### ISSUE THREAD

**Issue by oscerd** [syndesisio/syndesis#3778]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
This is related to #3740 
I think we can improve this action: we can define the input Data Shape as a String and pass this value to get Event Customizer and use that as an input for the get operation.

Since this is an enhancement I'm not sure this will go in 7.2

**Comment by oscerd** [comment]
Can you give your feedback @gaughan @heiko-braun @paoloantinori ?

**Comment by gaughan** [comment]
LGTM!

**Comment by jstastny-cz** [comment]
How can a user find event id? I couldn't find it in other way than listing events via API.
My concern is, that without ability of dynamically setting the event id to the 'Get a specific Event' action, there's no practical usage for the action.

I don't think that getting the id via calendar API + writing it to the 'Get a specific Event' step manually is a satisfying option.

This should be considered as a severe issue for the 'Get a specific Event' action.

**Comment by oscerd** [comment]
You don't have a different way to get a specific event. You need an Id.

This issue let you be able to map the event Id from the event you're getting through the receive events action, to a string as input (as eventId) for the get Event action. In that case you don't have to insert it.

For and end user find an eventId is as follow:

You can append this string to you Google Calendar URL

?gsessionid=OK&eventdeb=1

Then when you select an event, in the options dropdown list, you should see a Troubleshooting Info option, when you click there you should see a json, the event Id for that event is the eid parameter.

eid=0s1dsu77h5nte9p1cf9b6u03p3

for example.

I completely disagree to the fact this is a severe issue. I can't change how Google Calendar API works. I can make it easier configure the eventId through the datashape, nothing more than that.

**Comment by jstastny-cz** [comment]
@oscerd I do understand, that we actually need the id to be able to retrieve specific event. What I am saying is, that the current state (before this feature request gets into project) is impractical.

**Comment by oscerd** [comment]
@heiko-braun can this be part of 7.2?

**Comment by oscerd** [comment]
Sure, It was because I believe this may be considered something limiting the feature. But it's ok. No problem.
