### ISSUE TITLE
Lost my 'from scratch' openapi document

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#3784]
## This is a...

<pre><code>
[*] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[*] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When working on a 'from scratch' api, I assumed it would be saved. But when I accidentally moved away from the page, there was no way to navigate back to it: My work was lost..

1. Work needs to be saved.
2. I need to be able to navigate back to it.
3. I need to be able to export the api document. 
4. Also there we some quirks in the version of apicurio that is currently integrated that are fixed in the latest version (2.15).
5. Not having tooltips where the "I" errors appear in the UI is bad. I need to guess and match from the list of errors. This point is probably apicurio specific.
6. I think content should be saved when it looses focus. It's cumbersome to click the blue checkmark buttons.
7. I like how a dataType is created from providing some example data in the new apicurio version, it's tedious in the older version. 
8. When I name example data structures I expect that I can reuse them later on other request definitions.

@EricWittmann some of it is to do with the integration, but you might be interested in reading my experience feedback ^

**Comment by EricWittmann** [comment]
Yes I'm definitely always interested in this sort of experience!  I have some thoughts and a request for clarification (see below):

Points 1-4 are specific to syndesis and the use-cases there.

5) You can click on the (!) icons to see the list of errors for that context.  You were expecting a hover-tooltip, did you try clicking?
6) What blue checkmark are you referring to here?  Is this something specific to syndesis?
7) Thanks!  We're slowly making progress on time-saving features like this. :)
8) I agree, however the OpenAPI spec supports re-usable examples only in version 3.0 of the specification.  Syndesis/Fuse **only** support version 2.0 (swagger).

**Comment by riccardo-forina** [comment]
> 1 . Work needs to be saved.
> 2. I need to be able to navigate back to it.
> 3. I need to be able to export the api document.

Syndesis UI is rich with escape path from any given point. One solution could be to have a service that can be used to flag the working session as dirty, and have a side-wide route guard that checks for that dirty status and asks for confirmation before allowing the route to change.

> 4. Also there we some quirks in the version of apicurio that is currently integrated that are fixed in the latest version (2.15).

Actually, [we are on v2.15](https://github.com/syndesisio/syndesis/blob/aeecdaee2a1a008915974322beaabeb0ca75d15b/app/ui/package.json#L52). Are you running the UI locally perhaps?

**Comment by zregvart** [comment]
Also of interest for autosave #3048.

**Comment by dongniwang** [comment]
@KurtStam - Do you have screenshots for some of the points you mentioned above. That would be helpful! 

FYI @seanforyou23

**Comment by KurtStam** [comment]
@dongniwang Sure, so we currently have 2 screens:

<img width="1086" alt="screen shot 2018-10-25 at 9 15 10 pm" src="https://user-images.githubusercontent.com/35576/47524636-72104700-d89b-11e8-97f5-185f1f45a064.png">

Shows the externalURL, and 

<img width="1112" alt="screen shot 2018-10-25 at 9 15 25 pm" src="https://user-images.githubusercontent.com/35576/47524637-72104700-d89b-11e8-95b8-f2e5d1e240e4.png">

shows the three actions

When I need to invoke these endpoints it's nice to be able to see how I invoke each action and what the in and output data is. Something like the swagger-ui does this, you upload the task-api.json to it and on the right panel it brings up a little UI that shows the three endpoints
<img width="1150" alt="screen shot 2018-10-25 at 9 16 27 pm" src="https://user-images.githubusercontent.com/35576/47524638-72104700-d89b-11e8-96e9-e6659bfee6cb.png">

When clicking on an endpoint (like POST) I even get an example request I can execute.

<img width="561" alt="screen shot 2018-10-25 at 9 16 38 pm" src="https://user-images.githubusercontent.com/35576/47524639-72104700-d89b-11e8-83d4-fcd0bab3679b.png">

I'm looking for similar functionality in Syndesis. Does this help?

**Comment by KurtStam** [comment]
@dongniwang Can you specify which items you'd like screenshots of? It's mostly to do with how the apicurio-ui is embedded in ours. It works fine for the happy path but when you want to use it for a real use case it made me angry :( . I actually stopped using it and fired up a standalone apicurio on JBossEAP.

**Comment by Mgranfie** [comment]
@EricWittmann these are good use cases. We had not addressed navigating away from a tab with the back button or a session that unexpectedly ends. These are important use cases that we should consider.

@KurtStam  I am working with Eric on the Apicurio UX and would like to help by understanding better.
WRT "#6. I think content should be saved when it looses focus. It's cumbersome to click the blue checkmark buttons." 

Which attribute were you editing and what action did you take to move away from the content being edited, causing it to lose focus?

**Comment by KurtStam** [comment]
@Mgranfie I was working to create the methods

<img width="1144" alt="screen shot 2018-10-25 at 10 08 16 pm" src="https://user-images.githubusercontent.com/35576/47527305-8b68c180-d8a2-11e8-995d-983b6f5a7f6f.png">

It seems to already have been improved a lot. On most I can simply hit the enter button now and move on.

**Comment by EricWittmann** [comment]
Ah now I understand number (6) above.  It's certainly possible to save the field when focus is lost.  Not sure if that's the right UX - @Mgranfie can weigh in on that.  However, it's worth noting that you can always use the Enter key when editing a field (as you noted, Kurt).  But in the cases where you're editing a multi-line field (such as descriptions or examples) you can use Ctrl-Enter.  Pro-tip.  :)

**Comment by EricWittmann** [comment]
I'd also like to add that navigating away from the editor is not an issue in the full Apicurio solution, since all edits are saved on the server in "real-time" - so you're free to close the tab or navigate away and your work will be saved.  Improvements in this area (ie "offline" mode for when you're on a plane) still need to be made - but as long as you have a reasonable connection to the server, work will be saved.

So the "I've lost my work!" problem is specific to the syndesis integration (and also Apicurito).  I think in both cases we should save work to browser local storage.  It's easy enough to do and allows the user to recover their work.  I've suggested that for Apicurito but it's not yet on the required feature list.  I'd be happy to add it.

**Comment by chirino** [comment]
@EricWittmann +1 on using local browser storage.  Should we open a new issue for that in Apicurio?

**Comment by EricWittmann** [comment]
I already have an issue open for that in **Apicurito**:  https://github.com/Apicurio/apicurito/issues/2

Any other use-cases should probably have separate issues filed since the solution would be specific to them.  So e.g. if one or both of the syndesis+apicurio integration use-cases need it, then I think we should open issues for that in the syndesis repo.

IMO :)
