### ISSUE TITLE
Cannot implement API Provider operation returning collection

### ISSUE THREAD

**Issue by asmigala** [syndesisio/syndesis#3788]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

When an operation in API Provider returns a collection, there is no way to set that up in the actual flow. It is possible to map whatever the items are in the returned array, but only the first element is ever returned when accessing the resulting API.

e.g. using the TODO API specification, which contains the following for GET / : 

```
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Task"
              }
            }
```

I get the following:
![screenshot_2018-10-10_12-30-23](https://user-images.githubusercontent.com/9480152/46730782-36656280-cc89-11e8-80db-006df48e8a5f.png)
![screenshot_2018-10-10_12-30-55](https://user-images.githubusercontent.com/9480152/46730780-36656280-cc89-11e8-92d3-0e88f418c134.png)
![screenshot_2018-10-10_12-36-40](https://user-images.githubusercontent.com/9480152/46730779-36656280-cc89-11e8-911a-0d3d204a9e4e.png)

**Comment by heiko-braun** [comment]
@igarashitm Can you take a look if this is a limitation or a bug?

**Comment by zregvart** [comment]
This is a limitation, we have it since forever.

https://github.com/atlasmap/atlasmap/issues/435
https://github.com/atlasmap/atlasmap/issues/162
https://github.com/atlasmap/atlasmap/issues/75
https://github.com/atlasmap/atlasmap/issues/63

**Comment by igarashitm** [comment]
Right, this is exactly atlasmap/atlasmap#63. topmost array/list is not supported. You need to wrap it with single object.

**Comment by zregvart** [comment]
@igarashitm and myself had a discussion on IRC, this can be considered a bug in the API connector. Well a lack of (critical) functionality. We have established a wrapper for collections that should look something like this (in JSON, for this specific case):

```json
{
  "parameters": {
  },
  "body": [
    {
      "id": 1,
      "completed": 0,
      "task": "t1"
    }
  ]
}
```

The reason why it isn't is because the data shape generation from OpenAPI spec is shared between custom API client connector and API provider implementation. And I guess we don't generate this wrapper for the responses in the API client and thus we don't provide it for the responses in the API provider.

If I'm correct on this I think we should provide such wrapper for both custom API client connector and API provider.

**Comment by heiko-braun** [comment]
@zregvart Can you tackle this?

**Comment by zregvart** [comment]
> @zregvart Can you tackle this?

Rhetorical? Sure, I need to confirm if my theory holds :smiling_imp:

**Comment by tplevko** [comment]
@asmigala please verify the fix

**Comment by asmigala** [comment]
I can now map the fields properly (I see a "body" property in data mapper which indicates that the result is an array).

However, when actually implementing the integration as in the first comment (with a postgres connection and  select * ), requesting the api endpoint returns nothing (Content-Length: 0).

**Comment by zregvart** [comment]
@asmigala is this a simple API provider-based integration implementing the TODO API swagger with `GET /` flow with DB connector with `SELECT * FROM TODO` and mapping step? Can you provide an export of the integration?

I suspect there are rows in the `TODO` table? Be wary of the know limitation we have (#3856, #3896)

**Comment by asmigala** [comment]
@zregvart yes, exactly like that. Export attached 

[TODO-export.zip](https://github.com/syndesisio/syndesis/files/2529484/TODO-export.zip)

**Comment by asmigala** [comment]
Spoke with @zregvart on irc, here's a summary:

The API Provider can currently return a collection, however, no other step can _provide_ more than one value at a time to it, so the resulting collection will always have just one element (so, effectively the same result as was originally reported, except wrapped in an array). This is reported as #3856 and #3896 .

Therefore, QE does not consider this issue to be resolved (it's resolved in its letter, not in the spirit).

This is a blocker for 7.2, but the other two issues are not.

@heiko-braun @gaughan @tplevko how should we proceed?

**Comment by gashcrumb** [comment]
Seems a bit late in the release cycle to introduce an aggregate step type, but if someone maybe made an extension that added an aggregate step which a user could install as a workaround...  hmm...

**Comment by heiko-braun** [comment]
According to the summary above, it‘s a limitation, rather than a blocker from my point of view. If no steps can return collections, my suggestion would be to enhance it in the next release (create a followup issue) and close this one for now.

**Comment by zregvart** [comment]
I also can live with this as is and have it nicely done for the next release.

(but)

To be fully open and honest, we could add an aggregation step (only) in the API provider response processing. Not sure how risky could that be. We do have two weeks to find out.

**Comment by gaughan** [comment]
I think we have zero appetite for introducing (small?) risk into 7.2 ship date. We can work alongside perhaps and fix in 7.3?

**Comment by asmigala** [comment]
Ok, in that case, would it be possible to include a warning in the syndesis ui in case the user tries to implement a route returning array? Right now the behaviour is very confusing.

The 'Review Actions' page in the API Provider wizard seems like a logical place to include such a warning, though I'm not sure it's possible to put it there (as the same page is used in the API Connector wizard).

![image](https://user-images.githubusercontent.com/9480152/47861780-db400f00-ddf3-11e8-8fe2-81fcd378910a.png)

**Comment by tplevko** [comment]
From QE perspective, the p0 priority can be decreased to p1 as the API provider feature is only TP for 7.2. This issue however should be a part of the release notes as a known limitation. We however leave the decision on decrease of priority up to PM.

**Comment by asmigala** [comment]
Also, please consider raising back to p0 for 7.3 (or whatever release API Provider will be promoted from tech preview)

**Comment by tplevko** [comment]
Also as this is still an issue, even though not a blocker from QE perspective, I'm moving this back to backlog.

**Comment by gaughan** [comment]
I agree on moving to 7.3

**Comment by asmigala** [comment]
From QE's standpoint this issue is resolved, but it is marked as blocked here. @heiko-braun can I still close as verified?

**Comment by heiko-braun** [comment]
Yes, please close it
