### ISSUE TITLE
Switching between multiple Data Mapper steps in an integration does not update the view

### ISSUE THREAD

**Issue by asmigala** [syndesisio/syndesis#3789]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When there are two (or more) Data Mapper steps in an integration, opening one of them and then selecting the other one in the sidebar, it appears to get selected in the sidebar, but the main view is not updated (i.e. it's still showing the old data mapper's content).

Switching to some other step first or closing the Data Mapper and opening it for the other steps works as a workaround.

![dm](https://user-images.githubusercontent.com/9480152/46731849-1d11e580-cc8c-11e8-874f-45447f78bfdd.gif)

**Comment by igarashitm** [comment]
Hi @heiko-braun, this is Syndesis bug, it's completely out of AtlasMap control.

**Comment by tplevko** [comment]
@asmigala please verify

**Comment by asmigala** [comment]
Verified in latest master
