### ISSUE TITLE
Google Calendar Connector: confusing option to alter polling behaviour

### ISSUE THREAD

**Issue by jstastny-cz** [syndesisio/syndesis#3790]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Receive events action option 'Consume from the last event update date on the next poll' is source of confusion for the user.

It assures, that in consecutive poll it returns only events that take place after the 'last update date' of current poll.

The thing is that it compares two unrelated values - based on last update of events it returns only events that take place after it.

Side effect of this is that user can't get past events that were updated recently (added link with recording or similar).

It would make much more sense for the action to return events updated after the 'previous poll last update date' to have only a diff between the two polls.

We should aspire to sanitize this filtering option.

**Comment by oscerd** [comment]
We can also take into account the end date and time of the last event consumed, instead that the updated date.

**Comment by jstastny-cz** [comment]
@oscerd I'd start with the question of what we want to have. Is there a user story or something? About when and why would user use this?

**Comment by oscerd** [comment]
_I want to monitor a channel (calendar) for new events created and consume these via my fuse online integration._

https://github.com/syndesisio/syndesis/issues/3454

So ideally you should be able to get only new events created on each poll or updated. The only information we have to distinguish are the dates (start, end, updated)

**Comment by jstastny-cz** [comment]
@oscerd so we want the events where event.update_date is after the updates of events received earlier, right?
Effectively we should do following comparison:
event.update_date >= max(event_from_previous_poll.update_date)

Right?

**Comment by oscerd** [comment]
Yes, but this will need some changes on the camel side.

**Comment by heiko-braun** [comment]
@oscerd Is there a solution without touching camel?

**Comment by oscerd** [comment]
No. But it would be easy to do

**Comment by heiko-braun** [comment]
Ok lets do it. If we are quick and manage to get this in place before @janstey kicks off a camel build, that would great.

**Comment by oscerd** [comment]
I fixed this on the camel side with CAMEL-12874

We now need a dev build to pin and I can merge. Actually we have some provisioning problem on CI

**Comment by heiko-braun** [comment]
@oscerd Please leave the issue in the `Done` column and open, if they have been re-opened and moved after a PR was merged. The QE workflow depends on it.

**Comment by oscerd** [comment]
Yes, sorry @heiko-braun

**Comment by jstastny-cz** [comment]
Verified.
