### ISSUE TITLE
UI - Google Calendar Connector: Receive Events 'Query for events' description

### ISSUE THREAD

**Issue by jstastny-cz** [syndesisio/syndesis#3791]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

The purpose of the form field labeled 'Query for events' is not clear. I miss the information that/how it actually filters the events retrieved for the calendar.

What it appears to do is a full-word search in events' fields, checked summary and description so far, Behaves in following manner:
 1. events e1 with description 'An old event' and e2 with description 'An old event2'
 2. 'Query for events' set to 'An old event' retrieves only e1, not e2.

It might be desired behavior, but it's hard to tell, due to insufficient description of the field purpose.

**Comment by oscerd** [comment]
This has been already specify here:

https://github.com/syndesisio/syndesis/blob/master/app/connector/google-calendar/src/main/resources/META-INF/syndesis/connector/calendar.json#L646

it's a free text search so it's the desired behavior. Also it's an internal feature of Calendar Api.

**Comment by rhuss** [comment]
@jstastny-cz @oscerd could it be that the search only matches the whole words and not substrings? So it wouldn't be surprising that "event" doesn't match "event2" in the example. 

I think it would be fine if the search semantics would be documented in the User documentation (and not in the UI).

**Comment by oscerd** [comment]
Yes, it works like that. But I still have to find a good reference about this for the docs.

**Comment by oscerd** [comment]
I'll change the description to something more UI oriented and this will be for docs team, after merging the update to description I'll close this one.
