### ISSUE TITLE
Google Calendar Connector: 'Get a specific Event' not failing gracefully

### ISSUE THREAD

**Issue by jstastny-cz** [syndesisio/syndesis#3793]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

User is presented with a stack trace without any description of an error.

## Expected behavior

Ideally an error message, plus optionally with an error code/stacktrace.

## Screenshot

![screenshot from 2018-10-10 16-15-20](https://user-images.githubusercontent.com/11939909/46743414-4a20c100-cca9-11e8-972b-9deb660bd61f.png)

## Tasks involved / Steps to Reproduce

1. Use a Google calendar action 'Get a specific Event'
2. Specify non-existent event id
3. Publish such integration

**Comment by oscerd** [comment]
404 not found is clear. The event doesn't exists. We can't think of mapping any possible error of an API. So for me this rejected. But let me ask to @paoloantinori @heiko-braun @gaughan

**Comment by jstastny-cz** [comment]
@oscerd imho 404 doesn't say, that this is an issue of invalid event id. I deduced this only from the stacktrace + cross-checking what could have gone wrong.

**Comment by oscerd** [comment]
If we map a 404 to a specific exception, then we'll need to map any other possible error to something else. I personally disagree, but I'm not the one who decide.

**Comment by heiko-braun** [comment]
After considering this in the triage call, we decide to close it as won't fix.
