### ISSUE TITLE
API Provider tooltip text

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#3796]
## This is a...

<pre><code>
[ x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Text displays as Provided API in a flow. 

## Expected behavior

It should read in the example below: "Add a new pet to the store"

## Screenshot

![image](https://user-images.githubusercontent.com/674767/46763318-763b4280-cca7-11e8-88ce-62a64e651dce.png)

**Comment by dongniwang** [comment]
@gashcrumb @riccardo-forina - Is the information "Add a new pet to the store" available as part of the page data or in the IVP already? I'm assuming this is the same as the info that we're showing in the breadcrumb. 

Wondering if @michael-coker may be able to help with this? This issue https://github.com/syndesisio/syndesis/issues/3848 could be related...

**Comment by riccardo-forina** [comment]
Yes, we do. Actually, I already addressed in this in the PR I'll open soon to fix #3848.

**Comment by dongniwang** [comment]
I think this is fixed now? Please verify. @michael-coker @riccardo-forina

**Comment by michael-coker** [comment]
Yep, looks like it's fixed.
