### ISSUE TITLE
API Provider Operation list navigation

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#3797]
## This is a...

<pre><code>
[ x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Navigation to the operation list should be possible via the left hand panel.
Maybe a parent above the flow?

![image](https://user-images.githubusercontent.com/674767/46763554-20b36580-cca8-11e8-92ef-420ff6c8db53.png)

**Comment by riccardo-forina** [comment]
CC @dongniwang

**Comment by dongniwang** [comment]
@riccardo-forina - thanks for tagging. Maybe we can take care of this issue first https://github.com/syndesisio/syndesis/issues/3848 and I'll explore options as to how and where to provide the way to navigate to the Operation List page.

**Comment by heiko-braun** [comment]
I think this is adressed with the new UX designs, closing
