### ISSUE TITLE
Quick Install stopped working

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#3799]
bash <(curl -sL https://syndes.is/start)
=====================================================================
SYNDESIS 1.3 QUICKSTART

Hybrid integration on OpenShift made easy
=====================================================================

---------------------------------------------------------------------
Starting minishift ....

-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.7.1' is valid ... OK
-- Checking if requested OpenShift version 'v3.7.1' is supported ... FAIL
   Minishift does not support OpenShift version v3.7.1. You need to use a version >= v3.9.0

**Comment by zregvart** [comment]
I think it's a prerequisite that you have `minishift` pre-installed, looks like you have a older version that can't run OpenShift version we require.

**Comment by KurtStam** [comment]
I'm on version 1.25 of minishift. It works ok when minishift is running already but when it's not I get the FAIL mentioned above.

**Comment by KurtStam** [comment]
Moving this to syndesis.io https://github.com/syndesisio/syndesis.io/issues/84
