### ISSUE TITLE
Icon change request

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#3809]
The latest icon for a Database connector is yellow, can we change it to a different color? Perhaps blue?

**Comment by amysueg** [comment]
@gaughan Sounds good to me Gary. Yellow conveys "caution" and so I think going with blue is a good idea. @sjcox wdyt?

Going forward I would like to suggest that we develop a color scheme or theme for new "homemade" icons and revisit the current set for cohesion. @dongniwang fyi.

**Comment by gaughan** [comment]
@sjcox-rh thanks!

**Comment by dongniwang** [comment]
Closing this issue as we have this now https://github.com/syndesisio/syndesis/blob/master/ux/connections_icons/png/sql.png.
