### ISSUE TITLE
bug(IVP): Step Icon Line Jutting Out

### ISSUE THREAD

**Issue by jameslau** [syndesisio/syndesis#3811]
<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The Problem
Multistep child step icon line extends beyond step icon

**Multistep Setup**
<img width="130" alt="screen shot 2018-10-11 at 5 59 51 pm" src="https://user-images.githubusercontent.com/1402829/46837148-2c735a80-cd82-11e8-83b0-2176332ba448.png">

**Step Icon Line Jutting Out**
<img width="43" alt="screen shot 2018-10-11 at 6 17 25 pm" src="https://user-images.githubusercontent.com/1402829/46837162-36955900-cd82-11e8-8c1d-45267435bfa1.png">

## Expected Design
Multistep child step icon line should not extend beyond step icon

## Reproduce Issue
1. Create integration with API Provider
2. Choose `Upload an OpenAPI file`
3. Add a random JSON file and click `Next`
4. Click `Next` from `Review Action` step

**Comment by jameslau** [comment]
cc @dongniwang / @michael-coker

**Comment by tplevko** [comment]
Verified by QE, seems better now :+1:
