### ISSUE TITLE
Steps icons overlaid in Apicurio UI during API Provider creation

### ISSUE THREAD

**Issue by asmigala** [syndesisio/syndesis#3816]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Opening Apicurio during creation of API Provider integration (either editing provided swagger.json or creating from scratch) causes the step icons from the left side panel to remain visible, on top of the Apicurio UI. See screenshot:

![screenshot_2018-10-12_14-51-03](https://user-images.githubusercontent.com/9480152/46870424-d9a3ac80-ce2e-11e8-82bb-e5fd6d99785c.png)

**Comment by asmigala** [comment]
Probably caused by #3810 , disabling the z-index in dev console makes the icons go away.

**Comment by jameslau** [comment]
Hey @asmigala, I quickly discovered this after I pushed it up to master. Going to find a work around this. Thanks! cc @michael-coker
