### ISSUE TITLE
#3712 is inconsistent in 1.4.9 build

### ISSUE THREAD

**Issue by mmelko** [syndesisio/syndesis#3817]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
https://github.com/syndesisio/syndesis/commit/ef0589de9fc293502466bfb79abaf6de02f47525 reverted changes in templates from https://github.com/syndesisio/syndesis/pull/3712/commits PR. Due to that https://github.com/syndesisio/syndesis/issues/3460 is still present. Marking as blocker as it should be fided in 7.1.1

**Comment by heiko-braun** [comment]
@mmelko 1.4.10 has been released to address this.
