### ISSUE TITLE
Support for vanilla Kubernetes 

### ISSUE THREAD

**Issue by kevinbayes** [syndesisio/syndesis#3826]
## This is a...

<pre><code>
[ x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Is it possible to get a deployment for on vanilla Kubernetes? So, in the same way, there are openshift deployments have a section for kubernetes scripts.

**Comment by KurtStam** [comment]
To grow community support running on k8s is a must in my opinion, and any healthy project needs a community. It's disappointing we let go of k8s support to easily. I'm def interested to help out on this effort.

**Comment by kevinbayes** [comment]
Sure it should be fine to give some support on this.

**Comment by heiko-braun** [comment]
@kevinbayes Can you elaborate on what you mean with "vanilla" Kubernetes?

**Comment by rhuss** [comment]
I think Kubernetes support would be good to have. However, I think we have a lot of subtle dependencies on OpenShift. Maybe it's a good start to collect the differences before we can break that down in smaller tasks? 

Out of my head, I see the following areas which would need to be updated:

* Building integration runtimes when publishing. Uses S2I on OpenShift, would need to use (Knative ?) or implement similar build service for Kubernetes
* Installation uses OpenShift templates. We are currently moving the installation into an operator where the template becomes an internal implementation detail which could be changed to something which can be used on both, OpenShift and Kubernetes
* Using OpenShift SSO via OAuth proxy.
* Using Imagestreams in DeploymentConfigs for updates. This concept doesn't exist on Kubernetes
* Not 100% sure how the API Provider and Webhook exposes their routes, but if its via an OpenShift Routes this would have to be changed to Ingress objects.

Anything else ?

**Comment by nicolaferraro** [comment]
By switching to Camel K as Camel runtime, we can support build on vanilla Kubernetes. It uses Kaniko (it probably will use Knative build when Knative is available). The only thing to decide is the Docker registry where to publish images (on Minikube, Camel K uses the "addon registry").

Also last point about exposing routes is covered (Route / Ingress).
