### ISSUE TITLE
salesforce : have the possibility to listen for create/update/delete events in a single action

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#3829]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

When listen from events emitted by SalesForce, one has to choose to start from a specific actions as shown by the image below:

![image](https://user-images.githubusercontent.com/1868933/46941351-35f31000-d06b-11e8-8d94-b40f4a0901a7.png)

This means that to handle create/update/delete cases one has to spawn multiple integration that may lead to inconsistency as the actions may be handled in parallel so you can have i.e. that an update is handle after a delete or that multiple action compete to be executed to the target system.

We should have a generic action in which I can select which events I want to receive.

**Comment by mastepan** [comment]
@lburgazzoli  just checking. Is there anything that should be checked by QE?

**Comment by lburgazzoli** [comment]
Don't think so
