### ISSUE TITLE
Modals in Apicurio inaccessible when creating API Provider from scratch

### ISSUE THREAD

**Issue by asmigala** [syndesisio/syndesis#3830]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Opening a modal dialog (e.g. by clicking Add a path) in Apicurio when creating an API Provider from scratch causes the whole page to become greyed out, including the modal itself. Nothing on the page is clickable, the only way to get out is to refresh the page (or use dev console).

Probably result of #3824 

## Screenshot
![modals](https://user-images.githubusercontent.com/9480152/46942768-4ce73180-d06e-11e8-9bb2-498d77700781.gif)

**Comment by heiko-braun** [comment]
@michael-coker Is it related to #3824?

**Comment by asmigala** [comment]
Verified in latest master
