### ISSUE TITLE
Missing icons for intermediate steps

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#3831]
## This is a...

<pre><code>
[ ] Feature request
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Missing icons for intermediate steps

## Screenshot

![image](https://user-images.githubusercontent.com/1868933/46943778-b10af500-d070-11e8-9220-b1128d3cba8e.png)

**Comment by gashcrumb** [comment]
Are these built-in steps?  It's probably just because I haven't yet gotten https://github.com/syndesisio/syndesis/issues/3650 sorted...

**Comment by lburgazzoli** [comment]
yes they are, so mark this as fixed once you get that one sorted

**Comment by tplevko** [comment]
Verified by QE
