### ISSUE TITLE
Clicking back button when creating API Provider from scratch enters "hidden" wizard

### ISSUE THREAD

**Issue by asmigala** [syndesisio/syndesis#3832]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Clicking the browser back button when Apicurio is open during API Provider creation, the UI enters a 'API Provider - Choose Action' wizard. I'm not sure this is intentional, but since I found no way to enter this wizard any other way, I'm assuming it is not.

## Screenshots
Creating API Provider from scratch...
![screenshot_2018-10-15_11-52-04](https://user-images.githubusercontent.com/9480152/46943898-fcbd9e80-d070-11e8-9189-7325202eaab9.png)

Opens Apicurio
![screenshot_2018-10-15_11-52-14](https://user-images.githubusercontent.com/9480152/46943897-fc250800-d070-11e8-992f-ba47f9bd40e1.png)

After clicking the browser back button, this screen appears:
![screenshot_2018-10-15_11-52-30](https://user-images.githubusercontent.com/9480152/46943896-fc250800-d070-11e8-8463-5df81734f118.png)

I'm able to finish the wizard:
![screenshot_2018-10-15_11-52-38](https://user-images.githubusercontent.com/9480152/46943895-fc250800-d070-11e8-97c8-ba9f128b032a.png)
![screenshot_2018-10-15_11-53-05](https://user-images.githubusercontent.com/9480152/46943894-fc250800-d070-11e8-8127-6d7493feafba.png)
![screenshot_2018-10-15_11-53-18](https://user-images.githubusercontent.com/9480152/46943893-fc250800-d070-11e8-964a-89949c2b2b96.png)

If I then select API Provider again as the Finish Connection, similar thing happens, I'm still able to finish the wizard, but it's impossible to map the Finish Connection fields.

**Comment by tplevko** [comment]
@asmigala please verify the fix

**Comment by asmigala** [comment]
Verified with latest master.
