### ISSUE TITLE
Empty first column in the integration flow view

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#3844]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

When an API provider-based integration is created using a specification that for operations doesn't specify summary or description the first column in the integration flow list is empty.

## Expected behavior

We should generate a name for the connector action similar to how we generate one for the custom API clients. Something like `Receives POST request to /my/operation`.

## Screenshot

![screenshot_2018-10-15 syndesis](https://user-images.githubusercontent.com/1306050/46968860-af632080-d0b4-11e8-9813-5a66d717399c.png)

## Tasks involved / Steps to Reproduce

1. Create an API-provider based integration using the attached specification
2. Notice that the flow list has blank first column

[spec.json.txt](https://github.com/syndesisio/syndesis/files/2479959/spec.json.txt)

**Comment by zregvart** [comment]
//cc @dongniwang

**Comment by tplevko** [comment]
@mkralik3 please verify the fix
