### ISSUE TITLE
[API Provider] Operation name is missing from IVP when editing a flow 

### ISSUE THREAD

**Issue by dongniwang** [syndesisio/syndesis#3848]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

When editing a flow for API provider integraiton, users can only rely on the page breadcrumb to tell which operation they're building the flow for. Operation name is not available in IVP. 

## Expected behavior

Operation name should appear beneath the integration name area in the IVP. See UX design [here](https://redhat.invisionapp.com/share/CBNWDY58AHG#/screens/318306622) for operation name location. 

<img width="479" alt="screen shot 2018-10-15 at 3 37 05 pm" src="https://user-images.githubusercontent.com/24943812/46973759-33ef7800-d090-11e8-8b62-b53c92dc17dc.png">

## Screenshot

Current implementation:

<img width="1432" alt="screen shot 2018-10-15 at 3 31 57 pm" src="https://user-images.githubusercontent.com/24943812/46973537-88debe80-d08f-11e8-8d24-4c0d3fd78b01.png">

**Comment by tplevko** [comment]
@asmigala please verify the fix

**Comment by asmigala** [comment]
@dongniwang I think the element showing the Operation Name and the info icon should be hidden on the Start integration with an API call, the way it currently is is confusing:
![screenshot_2018-10-17_08-53-03](https://user-images.githubusercontent.com/9480152/47067668-6e6d2800-d1ea-11e8-8aaf-28565dbb440b.png)

**Comment by riccardo-forina** [comment]
Ops, I missed that...

**Comment by riccardo-forina** [comment]
@asmigala do you mind checking this again? That element should now be hidden when creating a new integration.

**Comment by asmigala** [comment]
Verified with latest master
