### ISSUE TITLE
'No data type specification was found for subsequent step' error in data mapper

### ISSUE THREAD

**Issue by asmigala** [syndesisio/syndesis#3859]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Having multiple data mapper steps can sometimes lead to the above error when editing one of them. See steps to reproduce and screenshots for one such scenario

## Steps to Reproduce

1. Create a API Provider integration from the Todo API
1. Start implementing the 'Fetch Task' operation
1. Add a Postgres connection, invoking SELECT * FROM todo (yes, this does not make much sense IRL, but still is possible)
1. Add a Data Mapper step between the start connection and the Postgres connection
1. Notice this Data Mapper has the response fields in the Target colum (as the Postgres step does not take any input)
1. Connect 'id' from the Source to the Target, leave other fields unconnected, close the Data Mapper
1. Add a new Data Mapper step, this time between the Postgres step and the finish connection
1. Connect 'completed' and 'task' fields from the Source to the Target, close the Data Mapper
1. Open the first Data Mapper step again, an error is shown instead of the Data Mapper UI

## Screenshots

![screenshot_2018-10-16_13-46-12](https://user-images.githubusercontent.com/9480152/47014691-4b3f6b80-d14b-11e8-9c23-b73eb8fda13f.png)
![screenshot_2018-10-16_13-46-45](https://user-images.githubusercontent.com/9480152/47014690-4b3f6b80-d14b-11e8-9a2a-83e555a63f61.png)
![screenshot_2018-10-16_13-47-06](https://user-images.githubusercontent.com/9480152/47014689-4b3f6b80-d14b-11e8-8621-fc9ed5055d18.png)
![screenshot_2018-10-16_13-47-23](https://user-images.githubusercontent.com/9480152/47014688-4b3f6b80-d14b-11e8-89d3-327b7b3a4df7.png)

**Comment by heiko-braun** [comment]
@igarashitm Can you take a look and tell where this belongs? Backend, frontend, atlasmap? We can than re-assign if needed.

**Comment by gashcrumb** [comment]
It's definitely a Syndesis UI thing.  I think it might have to do with the data mapper host component discovering the subsequent data mapper step when you go back and look at that step, which would have an input data shape of `any`.

One thing I also noticed is that when I create an integration with a middle connection (say to the sample DB) and add a data mapper step between the start and the middle connection, the mapper doesn't seem to detect the data shape in the middle connection (used the SQL create_lead stored procedure) but I think it has one.  Instead the mapper shows the finish connection's data shape as the target.

**Comment by igarashitm** [comment]
That sounds interesting, I think that's what I implemented for Data Buckets - maybe datamapper host component is not catching up with current Syndesis UI?

**Comment by asmigala** [comment]
@gashcrumb interesting, this is not my experience at all, I can map to middle connection just fine. What are your steps?

**Comment by gashcrumb** [comment]
Ah, well lookit that, the create_lead action doesn't have an input data shape at least when used as a middle connection, so the behavior would be expected.  I still think the issue might be caused by the data mapper discovering the second data mapper step instead of the finish connection, but I'm not sure if that's expected or not.

**Comment by gashcrumb** [comment]
The current semantics for when the data mapper step is available are to check if any steps before or after the spot where you're adding the data mapper have input/output data shapes.  

I don't know, should this be changed to only look at the previous/next step in the flow?  That would then make the data mapper step unavailable between the start connection and the SQL connection.

**Comment by igarashitm** [comment]
I think for Data Buckets, all preceding datashape aware steps needs to be taken into account, but only right next step which exactly consumes datamapper output.

**Comment by asmigala** [comment]
I don't really have an opinion on this (too little experience with syndesis and fuse in general)

**Comment by gashcrumb** [comment]
> I don't really have an opinion on this (too little experience with syndesis and fuse in general)

No worries, that question was more for @igarashitm sorry!

> I think for Data Buckets, all preceding datashape aware steps needs to be taken into account, but only right next step which exactly consumes datamapper output.

Sounds good, I can update the criteria used by the step select page, right now it takes all subsequent steps into account, which sounds wrong.

**Comment by tplevko** [comment]
@asmigala please verify the fix

**Comment by asmigala** [comment]
@gashcrumb I'm still able to trigger the error, using a slightly different set of steps:

1. Create a API Provider integration from the Todo API
2. Start implementing the 'Fetch Task' operation
3. **Add a Postgres connection, invoking `SELECT * FROM todo WHERE id = :#in_id`**
3. Add a  second Postgres connection after the first, invoking `SELECT * FROM todo`
4. Add a Data Mapper step between the start connection and the first Postgres connection **(this works, since the first Postgres connection has input)**
5. **Do not map anything, close the Data Mapper**
7. **Delete the first Postgres connection**
1. **Open the Data Mapper again**, notice it now has the response fields in the Target colum (as the **remaining** Postgres step does not take any input)
1. Connect 'id' from the Source to the Target, leave other fields unconnected, close the Data Mapper
7. Add a new Data Mapper step, this time between the Postgres step and the finish connection
1. Connect 'completed' and 'task' fields from the Source to the Target, close the Data Mapper
1. Open the first Data Mapper step again, an error is shown instead of the Data Mapper UI

I think step 7 is what's important here, as it breaks the assumption that a Data Mapper step should immediately precede a step with input.

**Comment by gashcrumb** [comment]
So yeah, you've changed the test, that's kinda bad form :-)

But seriously that behavior is mostly because we haven't decided what should happen to existing mappings when the user makes big changes to a flow like that.  See https://github.com/syndesisio/syndesis/issues/3864#issuecomment-430293313 which was raised for this kind of scenario,

**Comment by igarashitm** [comment]
@asmigala can you verify the original scenario in the top description now works and close this, and continue on #3864 about the refactoring scenario? also please file a new issue if you find something else.

**Comment by asmigala** [comment]
I still believe the new scenario is just a slight variation on the old one, but I'll see once #3864 is resolved if it fixes it.

Anyway, in the old scenario, it is now impossible to add a data mapper before a step that does not take input. Verified.

**Comment by igarashitm** [comment]
Please avoid any variation in the same ticket, it makes us to track individual bugs significantly harder.
