### ISSUE TITLE
Renaming Postgres step parameter causes Data Mapper issues

### ISSUE THREAD

**Issue by asmigala** [syndesisio/syndesis#3864]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
If the SQL query in a Postgres step is changed so that an existing :# parameter is renamed, and when that particular parameter was already mapped in a previous Data Mapper step, a data type mismatch warning is shown on the Postgres step (understandably, since the input data changed). Opening the Data Mapper step shows an error about missing field (again, understandable).  However, changing the mapping from the old to the new field name does not make the mismatch warning go away. In fact, the only way to make it go away is to rename the parameter back to its old name (a nuance here is that after renaming to the old name, no warning is shown, even though the mapping now references a non-existent parameter, with the new name).

Not sure this is only happening with the Postgres step, haven't tried any other.

## Steps to Reproduce
1. Create a new API Provider from the Todo API, start implementing the Fetch Task operation
2. Add a Postgres step, set the SQL to `SELECT * FROM todo WHERE id = :#id`
3. Add a Data Mapper step between the start and Postgres steps, map id to id
4. Open the Postgres step again, change the `:#id` to something else
5. Observe the data type mismatch warning
6. Try to fix the mapping

## Screenshots

![screenshot_2018-10-16_15-44-25](https://user-images.githubusercontent.com/9480152/47022354-95c9e380-d15d-11e8-893d-2502f03dbb81.png)
![screenshot_2018-10-16_15-44-44](https://user-images.githubusercontent.com/9480152/47022363-9c585b00-d15d-11e8-97cc-ef19bce00972.png)
![screenshot_2018-10-16_15-45-04](https://user-images.githubusercontent.com/9480152/47022366-a11d0f00-d15d-11e8-810c-a74638078d48.png)

![screenshot_2018-10-16_15-45-17](https://user-images.githubusercontent.com/9480152/47022382-a712f000-d15d-11e8-8f72-e752e43d700e.png)
![screenshot_2018-10-16_15-45-54](https://user-images.githubusercontent.com/9480152/47022390-ae39fe00-d15d-11e8-8d83-b314f94adaf5.png)
![screenshot_2018-10-16_15-46-13](https://user-images.githubusercontent.com/9480152/47022405-b3974880-d15d-11e8-803d-cb6c8dfdd32a.png)

![screenshot_2018-10-16_15-46-29](https://user-images.githubusercontent.com/9480152/47022411-b8f49300-d15d-11e8-9a38-6da98f6b86d9.png)

**Comment by igarashitm** [comment]
So this is a scenario that DataShape is changed after datamapper step is configured. I think we haven't actually consider deeper enough at implementation level yet. One option was to just blow out all existing datamapper step, but IIRC we haven't decided to do that.

**Comment by igarashitm** [comment]
@gashcrumb I barely remember we talked this a bit while back...

**Comment by gashcrumb** [comment]
@igarashitm yep, and it's still a problem as you say, we've no real strategy/guidance how to handle when the data shape changes and there's existing mappings.

**Comment by heiko-braun** [comment]
@gashcrumb @igarashitm Would you agree to the `p0` classification? Is there a workaround?

**Comment by gashcrumb** [comment]
Yep, in this case you just need to delete the data mapper step after changing the type, then add a new data mapper step.  So I wouldn't call it a blocker.

**Comment by gashcrumb** [comment]
I mean the safest approach would be to wipe any involved data mapper steps when a related connection is deleted or changed but that seems kinda draconian.

**Comment by heiko-braun** [comment]
@asmigala According to Stan's comment in https://github.com/syndesisio/syndesis/issues/3864#issuecomment-430293313 I am changing the priority to p1.

**Comment by heiko-braun** [comment]
@dongniwang Can we get your feedback as well?

**Comment by dongniwang** [comment]
@heiko-braun @gashcrumb @igarashitm - Sorry for the late reply. 

Are we trying to include this for 7.2? I think we need some time to explore the UX solutions for the "not so happy paths". 

For now, I agreed that the safest thing to do is to advise users to delete the existing data mapper step and add a new mapping step. Wondering though if we can detect data shape changes and display notification (similar to data shape mismatch) and let users know they need to delete the existing step and add a new step. 

cc: @syndesisio/uxd

**Comment by heiko-braun** [comment]
Not for 7.2, but we can explore the UX approaches in the 7.2 time frame and aim for implementation changes in 7.3

**Comment by dongniwang** [comment]
Sounds good re https://github.com/syndesisio/syndesis/issues/3864#issuecomment-433151599! thank you!
