### ISSUE TITLE
Wrong warning on Twitter > Salesforce integration

### ISSUE THREAD

**Issue by igarashitm** [syndesisio/syndesis#3871]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
As Twitter output DataShape (java) and Salesforce input DataShape (json) are both datamapper aware shapes, the warning on the Salesforce finish connector should encourage user to add Data Mapper step. This `Define the data type` link doesn't do anything.

## Expected behavior
Have a link to add a Data Mapper step in between Twitter and Salesforce there

## Screenshot
![screenshot from 2018-10-16 16-13-00](https://user-images.githubusercontent.com/265462/47044818-310f8880-d15f-11e8-82c4-e21cf8b7ebac.png)

**Comment by tplevko** [comment]
Verified
