### ISSUE TITLE
The Add a Step or Add a Connection items dissappear from the popup menu after clicking the corresponding button

### ISSUE THREAD

**Issue by asmigala** [syndesisio/syndesis#3875]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
In some cases, the popup menu in the left sidebar in Integration editor only shows one of the menu items (either Add a Connection or Add a Step). This happens when the user clicks e.g. Add a Connection in the main view, goes through with adding the connection, then tries to add a Step using the sidebar.

## Steps to Reproduce
1. Create a new integration, any start and end connection, plus one intermediate step (of any type)
2. In the main view, click the Add a Connection button, the tooltips in the sidebar appear with just the Add Connection item (this is expected, we are adding a connection)
3. Select any type of connection and finish its wizard
4. Back in the integration editor, the popup menus in the sidebar now only have Add a connection option, no Add a step

## Workaround
When the popup menu only has one item, the respective button in the main view can be clicked to reveal the other item.

## Screenshot
![screenshot_2018-10-17_09-57-56](https://user-images.githubusercontent.com/9480152/47071173-2bfc1900-d1f3-11e8-94c9-cb08d920529a.png)

**Comment by gashcrumb** [comment]
Honestly @dongniwang maybe we should just get rid of those buttons :-)

**Comment by dongniwang** [comment]
@asmigala  - I'm assuming this is happening when you're trying to create just a normal integration (not an API provider integration). 

@gashcrumb - consolidating step and connection could potentially happen in the near future. Hopefully, that will solve this problem. 

@michael-coker @jameslau - In the meantime, is this something you can take a look at?

**Comment by gashcrumb** [comment]
It's actually the opposite BTW, you click "add a step" and it pops out the tooltips over each possible spot where a step can be added and hides the "add a connection" link.

It's because once you have more than just a start and finish, the buttons really contextually don't make sense.  If you click one, where exactly in the flow are you adding this step/connection?  :-)

That's why I vote to get rid of the buttons.  Or maybe hide 'em once there's more than just the start/finish connections.

**Comment by jameslau** [comment]
@dongniwang I'll take a look at this.
