### ISSUE TITLE
The Step Delete functionality wins a prize for the most hidden feature..

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#3881]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[*] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Expand the sidebar and discover the trashcan!
<img width="430" alt="screen shot 2018-10-17 at 1 41 04 pm" src="https://user-images.githubusercontent.com/35576/47083900-54dfd680-d212-11e8-9a26-d6840b2e4df8.png">

But I guess after you publish it's gone for good.
<img width="1037" alt="screen shot 2018-10-17 at 1 38 03 pm" src="https://user-images.githubusercontent.com/35576/47083786-ff0b2e80-d211-11e8-924e-bac1a73e04f7.png">

Though I'd never noticed the trashcan till now!

**Comment by asmigala** [comment]
Had the same problem with the disappearing trash can, turns out it disappears when a step is "open", i.e. the trash can is only shown in the main integration editor page.

**Comment by gashcrumb** [comment]
Yeah, the trash icon is currently only visible when the IVP is expanded *and* when you're on the save/add step page with the two buttons there.

**Comment by gashcrumb** [comment]
@dongniwang wonder maybe we need to revisit how a step can be deleted, the trash icon is pretty hard to get to now with the expandable IVP.  Maybe once a step is configured we could offer a delete button also in the main area somewhere around the area of the cancel/done buttons?

**Comment by dongniwang** [comment]
> Had the same problem with the disappearing trash can, turns out it disappears when a step is "open", i.e. the trash can is only shown in the main integration editor page.

@asmigala - When a step is "open", do you mean that it's in an "edit" mode? Would you expect to be able to delete when editing a step? 

@gashcrumb - I feel like there's reason why we don't display the trash can? Is it because the steps/connections before or after could be dependent on it? e.g. a data mapping step

**Comment by gashcrumb** [comment]
Yeah, so we don't display the trash cans while "in" a step to avoid screwing up the flow state.  The main thing is there's a relationship between steps that have data shapes.  If you delete a connection before a data mapper step, that has an impact on what data shape the data mapper has as an input.  [This issue](https://github.com/syndesisio/syndesis/issues/3864) is a concrete example.  The basic filter also cares about data shapes, so it's another example of what should happen to it should you delete the previous step that has a data shape it's using to drive it's configuration.

I also originally had some real reservations about data integrity and screwing up the editor state allowing folks to arbitrarily delete steps at any point in the editor, but maybe those reservations are unfounded.

I think having a delete button when a step is "open" like you say would kinda make sense, for example you can delete an integration from the detail view (i.e. when you've "opened" an integration) and I think the same for a connection now, so it's at least consistent with a pattern we use elsewhere in the app.
