### ISSUE TITLE
Log Connection should allow logging a custom message

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#3884]
## This is a...

<pre><code>
[*] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
See https://github.com/syndesisio/syndesis-quickstarts/tree/master/hello-world

The Step Logger allows for a Custom Message, the LogConnector does not allow for this. It should offer the same functionality so we don't have to add a Log Step. 

In addition - I /think/ it should have logged and empty body instead of null, which is probably related to https://github.com/syndesisio/syndesis/issues/3880

**Comment by tplevko** [comment]
Still a relevant new feature - also for QE.
