### ISSUE TITLE
Google Calendar connector: Update Event form values not overriding the values coming in through flow

### ISSUE THREAD

**Issue by jstastny-cz** [syndesisio/syndesis#3887]
See also **https://issues.jboss.org/browse/ENTESB-11441**

## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When using an Update Event step in combination with an incoming Event instance (resulting from Get by id, or Get events actions) the values from the Update Event form are not being set.

The only way to achieve that is placing a Data Mapper before the Update Event step and map fields only partially (those that I don't want to update) and then in 'Update Event' form I can specify the values to update. (Or set the values as constants in data mapper, which I think is even worse option.)

To rephrase a bit, if I specify both mapping and form value, then form value is ignored. When considering the following simple scenario this can be surprising to user. (As they have explicitly set the values to the form.)

Scenario:
I'd like to be also able to send the event through the flow with/without a data mapper, just chaining actions 'Get a specific Event' -> 'Update Event', where the form of update step would have the overriding values specified.

In more complex scenarios, where I want to dynamically set all the values of event, this is not an issue, as data mapper works as expected.

**Comment by oscerd** [comment]
Don't you think this is a feature request?

**Comment by jstastny-cz** [comment]
I hesitated for a while, deciding between bug and feature request. Only the level of surprise caused by this limitation made me call this a bug.

**Comment by oscerd** [comment]
In my opinion this can be documented to be sure to avoid surprising reaction. But this is up to to triage call. I'll work on the PATCH action for 7.3, so we can use that to override existing field, without mapping or with mapping.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11441**
