### ISSUE TITLE
Hide the API provider connection from the connections page?

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#3889]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
The API connector shows up on the connection page as a regular connection.  It also shows up as a connector in the first step of the create connection wizard, but it shouldn't be available here either.

![image](https://user-images.githubusercontent.com/351660/47098767-da0ebf80-d201-11e8-8134-3e709c3b887c.png)

@nicolaferraro @riccardo-forina @dongniwang

**Comment by dongniwang** [comment]
I don't think it should. It's not really a connection and not a connector as well. 

cc: @amysueg @gaughan

**Comment by gashcrumb** [comment]
Good point!  Just checked and yes, it shows up in the first step of the create connection wizard, which it should not:

![image](https://user-images.githubusercontent.com/351660/47109853-5662cc00-d21d-11e8-9a63-b55db399abf4.png)

**Comment by gashcrumb** [comment]
Updated the description accordingly.

**Comment by nicolaferraro** [comment]
@gashcrumb issue #3546 was expressing some of the concerns you're mentioning.

Now paths that lead to wrong actions have been removed from the UI, but connections remain visible.

It's not only the "API provider" connection that should be removed from the list of connections and connectors, but also "Webhooks", "Timer" and "Log" (they are of the same kind).

**Comment by gaughan** [comment]
So API Provider starts an integration so it should only appear on the 'Intergrations' page I believe.

**Comment by gashcrumb** [comment]
@nicolaferraro also I think you're issue probably lays the case out better as to why this connection/connector and the other ones should be hidden, it kinda feels like it'd make more sense to track all of this under that issue and close this one as a duplicate, I honestly didn't realize that all those other connections should be hidden to but makes perfect sense.

**Comment by heiko-braun** [comment]
@nicolaferraro Can you work with stan on this?

**Comment by gashcrumb** [comment]
Looks like @zregvart is on it in #3907

**Comment by gashcrumb** [comment]
Nope I'm maybe lyin'.  :-)

**Comment by tplevko** [comment]
Verified.
