### ISSUE TITLE
Kudu Connector

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#3898]
As a citizen user I want to be able to connect to Kudu datastore. I will provide my own connection configuration strings such as:
Url
username 
password
Internal/External flag

DoD
I can send MQTT messages to Kudu.
I can retrieve Kudu data and send to a JDBC connection.

The feature owner has confirmed one of the following:
--There is an initial draft of the user doc for this feature.
--The writer acknowledges receiving enough information from engineering to write the initial draft of the user doc for this feature.

**Comment by heiko-braun** [comment]
@lgarciaaco Let's leave it on done for @syndesisio/qe to close when they've verified it.

**Comment by mcada** [comment]
Verified
