### ISSUE TITLE
Document template generation in the SDH

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#3901]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

The documentation should contain a section which explains:

* Which templates we have
* How productised templates are created
* How to regenerate the template
* How to a git pre-commit hook to check that the template has been regenerated (we had already several issues because that is has been forgotten)

**Comment by rhuss** [comment]
No time to work on that, but left open as a reference for future improvements (also to bring the SDH back to attention). BTW, is anyone still using it ?

**Comment by zregvart** [comment]
No longer relevant.
