### ISSUE TITLE
Check that templates have been recreated when doing a release

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#3902]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

During a release with `syndesis release` it should be verified that the generated templates are in sync with checked in the templates.

Although they are re-created, it's very likely if the generated template differs that someone just has forgotten to recreate the template or, worse, edited the syndesis.yml directly which now gets overwritten.

The release should stop here and only proceed when the regenerated templates are the same.

**Comment by heiko-braun** [comment]
Would be good to have for 7.2. Do you think it's feasible?

**Comment by zregvart** [comment]
Perhaps this could be _as easy_:tm: as running `run.sh` to generate templates and checking `git diff --exit-code`.
