### ISSUE TITLE
Odd paddings lead to off-center icons

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#3903]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
The icons in the integration details screen (perhaps in other places) are off-center.

![screenshot_2018-10-18 syndesis 2](https://user-images.githubusercontent.com/1306050/47160921-3c92b900-d2f1-11e8-8148-389283612f4e.png)

I got it nicely centered when I changed this CSS:

```diff
--- old.css	2018-10-18 16:18:20.246386177 +0200
+++ new.css	2018-10-18 16:18:00.807432404 +0200
@@ -1,12 +1,12 @@
 .step-block .icon {
     border-radius: 100px;
     border-style: solid;
     border-width: 3px;
     border-color: #0088ce;
-    padding: 11px;
-    width: 55px;
-    height: 55px;
+    padding: 13px;
+    width: 56px;
+    height: 56px;
     margin: 0 auto 5px;
     background-color: #fff;
     position: relative;
 }
```

Now it looks like:
![screenshot_2018-10-18 syndesis 3](https://user-images.githubusercontent.com/1306050/47161220-e7a37280-d2f1-11e8-94be-d1ce97e0f373.png)

And my OCD induced eye twitch has stopped.

**Comment by gashcrumb** [comment]
@michael-coker Have time for this?

**Comment by michael-coker** [comment]
@gashcrumb on it!
