### ISSUE TITLE
Connection step goes poof if I cancel the action the second time

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#3904]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

I create/edit an integration and add a connection/action as a step. If I go and click on it again to edit the action settings and click on cancel, the connection/action disappears from the integration view pane.

## Expected behavior

Shouldn't disappear just like that it's rude.

## Screenshot

![peek 2018-10-18 16-24](https://user-images.githubusercontent.com/1306050/47161635-baa38f80-d2f2-11e8-9480-60c028b93144.gif)

## Tasks involved / Steps to Reproduce

1. Create/edit an integration
2. Add a connection step (in my case custom API provider)
3. Set desired action settings, click done
4. Click again on the new connection step to edit
5. Click cancel
6. Poof

**Comment by gashcrumb** [comment]
It seems to be just when the action doesn't have any configuration, as I can't get the same behavior to occur with say the Log or PostgresDB connection.  @zregvart can you attach the swagger file you used to create your API client so I can reproduce it here?

**Comment by zregvart** [comment]
@gashcrumb this one:
[test_xml.json.txt](https://github.com/syndesisio/syndesis/files/2492950/test_xml.json.txt)

And I used the `deleteJson` action.

**Comment by mastepan** [comment]
fix verified on version 1.5
