### ISSUE TITLE
Label color improvements

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#3906]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

Actually, the label colours have been consolidated to less colours, which is a good thing imo.

However, I think it goes a bit over the top for label groups which are supposed to be allowed multiple times (like `group/` or `notif/`)

So my suggestion is:

* To use a single background colour for label groups where is only one element is supposed to be present (`prio/`, `size/`, ...). Not sure why `cat/feature` is different from the scheme.
* For others, where are several possibilities allowed (`cat/`, `group/`, especially `notif/` which targets different teams and its hard to depict from the colour to which team it belongs). For those I suggest to use different but similar colours (e.g. shades of green) and for `notif/` totally separate colours.

**Comment by gashcrumb** [comment]
I've been feeling the initial grouping qualifier on our labels a bit over-engineered to be honest.  So consistent label colors and pulling the grouping out of the text of the label might be much better.

**Comment by gashcrumb** [comment]
And see, lookit, this issue has `cat/discussion` and `cat/feature` and they're different colors :-)

I rest my case.

**Comment by gashcrumb** [comment]
One other thought, the `notif` category is meaningless as an actual notification of any kind.  Using `triage` as a flag to indicate an issue needs triaging is fair enough though.

**Comment by rhuss** [comment]
@gashcrumb `cat/feature` is the only exception of the rule. not sure why though.

**Comment by rhuss** [comment]
wrt regarding stripping the prefix: I'm using some tooling which is not colour aware so it would be super awesome if we could keep that.

**Comment by gashcrumb** [comment]
Yep, that's cool, I'm fine with that.

**Comment by dongniwang** [comment]
One related question - 

Is it possible to have the bot automatically tag syndesisio/uxd when a label group/uxd or notif/uxd is applied?

**Comment by gashcrumb** [comment]
That'd be a good case for any of the `notif` labels there if it caused a bot to add a comment with the relevant group like @syndesisio/uxd

**Comment by dongniwang** [comment]
What's the difference between pure-bot and syndesis-bot? 

Also, would it be possible to have a bot automatically add an issue to a project based on a certain label? e.g. with the label notif/uxd, add the issue to https://github.com/syndesisio/syndesis/projects/2

**Comment by rhuss** [comment]
I think we should remove `group/uxd` (as it is not a functional group as the other members of this category) and just stick with notif/uxd so there would be no need for an extra label to filer on for the UXD team.

**Comment by rhuss** [comment]
> Also, would it be possible to have a bot automatically add an issue to a project based on a certain label? e.g. with the label notif/uxd, add the issue to

Yes, that should be possible. Please feel free to open an issue over there at https://github.com/syndesisio/pure-bot

**Comment by heiko-braun** [comment]
I wanted features to be green and bugs red. Along these color changes my proposal would be to call it ‘feature’ and ‘bug’ and leave the remaining ‘cat/*’ as is.

**Comment by heiko-braun** [comment]
I agree with stans comment about notif

**Comment by heiko-braun** [comment]
To add some background info, this is what inspired that changes:
![screen shot 2018-10-19 at 08 40 58](https://user-images.githubusercontent.com/369380/47201632-d488b500-d37a-11e8-8535-28e56e54db8d.png)

(Taken from https://robinpowered.com/blog/best-practice-system-for-organizing-and-tagging-github-issues/)

**Comment by rhuss** [comment]
@heiko-braun But why has every `group/` and `cat/` the same color when there can be multiple of these labels applied at the same time ? Your colour scheme above implies a single selection per label, then the same colour makes sense.

For the case of multiple possible labels I'd like a differentiation in the colour (and if its only a shade)  so that ideally every label attached to an issue has different colours (also a good litmus test to check whether labelling was applied correctly: If two labels with the same colours are applied, then a supposed to be single selection was applied twice, like adding `prio/p0` and `prio/p1` at the same time).

**Comment by dongniwang** [comment]
> I think we should remove group/uxd (as it is not a functional group as the other members of this category) and just stick with notif/uxd so there would be no need for an extra label to filer on for the UXD team.

What do you all think about Roland's proposal ^^? @syndesisio/uxd 

Also, just open [this issue ](https://github.com/syndesisio/pure-bot/issues/59) for the bot to automatically notify uxd. @rhuss @heiko-braun

**Comment by amysueg** [comment]
@dongniwang As long as we triage the "notify/uxd"-labeled items and treat them the way we've been treating group/uxd items, I agree that we don't need the nuanced differentiation and potential confusion of keeping both.

**Comment by rhuss** [comment]
To put the label "group/uxd" in a historical context, that label was meant at the time to be applied to issues and PRs which result in a UXD document stored within the syndesis repo. AFAIK, UXD artefacts are not stored anymore in the syndesis mono repo, so it would make sense to remove the "group/uxd" label.

**Comment by dongniwang** [comment]
@rhuss - this is probably really nit-picky, but I was wondering if we can increase the color contrast of the notif label set. The current color combination of purple background and black text makes it really hard to scan...

**Comment by gashcrumb** [comment]
@dongniwang if it helps you should also have permissions to update 'em -> https://github.com/syndesisio/syndesis/labels

I agree, the purple is a bit dark.

**Comment by heiko-braun** [comment]
@dongniwang let's iterate on this. I have changed it to use a white font colour - better?

**Comment by heiko-braun** [comment]
I was thinking about making bug and feature top level items, i.e turning them into `Bug` and `Feature`. Any objections?
