### ISSUE TITLE
Add metadata to Connections that determines if the Connection should be shown in the UI

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#3907]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Raised in https://github.com/syndesisio/syndesis/issues/3889#issuecomment-431073550, the Connection object should include metadata that UI can use to determine if the Connection doesn't need to be displayed in the Connection list.

**Comment by gashcrumb** [comment]
Key bit is for connections/connectors that should only show up in the integration editor vs the connection management pages.

**Comment by nicolaferraro** [comment]
@zregvart are you already working on it? (just to make sure we don't do it twice :D)

**Comment by zregvart** [comment]
> @zregvart are you already working on it? (just to make sure we don't do it twice :D)

nope, feel free to take this one; thanks :+1:
