### ISSUE TITLE
Getting quotes in responses with the unified responses

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#3909]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

From https://github.com/syndesisio/syndesis/issues/3851#issuecomment-430986258 when the body of the response is defined as a simple type (string, numeric, ...) the request contains that value quoted.

For example, given the unified response of:

```json
{
  "body": "hello"
}
```

The HTTP response body is literally `"hello"` (with quotes).

**Comment by heiko-braun** [comment]
@zregvart Is this still open?

**Comment by zregvart** [comment]
I think the bot fiddled with it. I think this only needs verification from QE.

**Comment by asmigala** [comment]
Verified with latest master
