### ISSUE TITLE
Discussion: Dependencies on pipeline artefacts in upstream

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#3916]
Besides the more political arguments we exchanged over the mailing list, I'd like to raise some technical and organizational concerns around having dependencies on `-fuse` artefacts in upstream Syndesis:

* The pipeline build of fabric8-maven-plugin (with -fuse extension) uses base images for the builds which are not freely available on Docker Hub. See #3872 where this bites us.
* Who is responsible with an issue in these dependencies (e.g. d-m-p, f-m-p, kubernetes-client) ? Where can an issue be raised to fix this ? The source code for these pipeline builds are not freely available, so how could I fix this and can send a PR ? (asking for a non Red Hat friend).
* Are the referenced pipelines builds guaranteed to be available forever (to make syndesis release reproducible even when done in 5 years) ? Sure, stuff on Maven central can disappear, too, but then I can still recreate the upstream dependencies on my own from source.

Wdyt, could we resolve these issues ?

I would be happy to track fuse specific branches (as we already do in other projects), I just think its not appropriate on upstream branches (master, bug fix branches)

// cc @cunningt @chirino @heiko-braun

**Comment by KurtStam** [comment]
+1 on using project artifacts only on the Syndesis project.

**Comment by oscerd** [comment]
Where we are unable to avoid using -fuse, like Camel, I'm ok on using these artifacts. Where we able to choose I'd go with upstream.

**Comment by KurtStam** [comment]
@oscerd  - so I understand - are we not contributing all changes to Camel back upstream? Or is it simply so that we can release Camel in a more timely manner?

**Comment by oscerd** [comment]
For example, for new components implemented (where we have to do that), like google-calendar-stream and google-mail-stream, but also for the Slack component, where I added a consumer that was missing before, I pushed the on upstream master. Since this stuff is new stuff, I couldn't backport to 2.21.x upstream and I had to backport on Fuse Camel 2.21.x. The main problem actually is that from 2.22.x upstream ahead, we are using Spring-Boot 2, so even if we would like to use Camel 2.22.0 or 2.22.1, or the next release, 2.23.0, in Syndesis, we actually can't. So we are bound to use Fuse Camel 2.21.x

**Comment by oscerd** [comment]
While, in case of bugs, we can backport on 2.21.x even upstream, as it's normal to do. By the way we won't be aligned in that case... This situation will be like now for time being, for example if you'd like to contribute a new component in Camel and then use it Syndesis, you'll first PR on upstream master, then backport to Fuse Camel 2.21.x, then release a Camel dev build, pin the camel dev stuff on Nexus and update dependency in Syndesis.

**Comment by chirino** [comment]
I think a better fix might be to ensure the git source to the fuse releases are available  and that we only use pinned builds.

**Comment by KurtStam** [comment]
@oscerd sounds like we should move to the same spring-boot version Camel master is on.

**Comment by lburgazzoli** [comment]
> @oscerd sounds like we should move to the same spring-boot version Camel master is on.

I think moving to sb2 is something for a major release. 

Maybe we could also think to remove the sb bits from integration runtime. I know @chirino disagree :) but as the runtime used is an "implementation detail" and not directly impacting users it may be an option.

**Comment by oscerd** [comment]
> > @oscerd sounds like we should move to the same spring-boot version Camel master is on.
> 
> I think moving to sb2 is something for a major release.
> 
> Maybe we could also think to remove the sb bits from integration runtime. I know @chirino disagree :) but as the runtime used is an "implementation detail" and not directly impacting users it may be an option.

I agree, but maybe experimenting on an a dev branch could be a good choice to be already able to switch

**Comment by cunningt** [comment]
I guess my question is if we're not testing these on master, where will be testing these?   We need to do it somewhere.     I can configure the PR generation to go to any branch we want to, but not testing the camel bits burned us on 7.1 and we should do it somewhere before producting the CR.

**Comment by rhuss** [comment]
> The tags will be available forever. The artifacts will go away in two weeks.

Does this mean that if we e.g. release Syndesis 1.4.11 which references such a `-fuse` kubernetes-client can't be rebuilt after two weeks without also rebuilding the kubernetes-client locally, too ? (and the same for f-m-p).

> I don't have a good answer for this one, but this is a substitution we are making in the pipeline build that we handover to production. We should be testing those images somewhere.

Actually, we are relying on auto-detection of f-m-p for the image (which in turn evaluates the version number). However, we could always pin that with a property to the fabric8 community images in upstream. In master and for upstream release we really should refer to upstream images available on Docker Hub for building (like fabric8 base images). Please note also, even when we would use pipeline base images, our community images are pushed with every commit to Docker Hub, which eventually has the effect, that the Pipeline images will also end up on Docker Hub (although probably not very visible).

**Comment by cunningt** [comment]
> Does this mean that if we e.g. release Syndesis 1.4.11 which references such a `-fuse` kubernetes-client can't be rebuilt after two weeks without also rebuilding the kubernetes-client locally, too ? (and the same for f-m-p).

We're promoting ("stickying") the Fuse builds that go into the candidate releases.   So if 1.4.11 uses candidate-release Fuse, then there's no issue.
