### ISSUE TITLE
Upgrade Spring Boot due to vulnerabilities found

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#3917]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[*] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
> 8 org.springframework:spring-core vulnerabilities found in app/pom.xml 3 days ago
> Remediation
> 
> Upgrade org.springframework:spring-core to version 4.3.18 or later.

We also need to coordinate versions with Camel, so this is a little more complex then changing the version number in the pom. On a quick try @zregvart reported some tests started failing. We prob want to do this sooner rather then later.

![yummy](https://user-images.githubusercontent.com/35576/47214139-4d006d80-d39d-11e8-827f-23b552787c21.jpg)

https://github.com/syndesisio/syndesis/network/alert/app/pom.xml/org.springframework:spring-core/open

**Comment by zregvart** [comment]
This was done in #3878. Here's [the failed](https://circleci.com/gh/syndesisio/syndesis/46899) CI build.

Just for posterity the root cause seems to be:
```
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is java.lang.NoSuchMethodError: io.undertow.servlet.api.DeploymentInfo.addServletContainerInitializer(Lio/undertow/servlet/api/ServletContainerInitializerInfo;)Lio/undertow/servlet/api/DeploymentInfo;
Caused by: java.lang.NoSuchMethodError: io.undertow.servlet.api.DeploymentInfo.addServletContainerInitializer(Lio/undertow/servlet/api/ServletContainerInitializerInfo;)Lio/undertow/servlet/api/DeploymentInfo;
```

**Comment by KurtStam** [comment]
@zregvart says: This was done in #3878. Here's the [failed CI build](https://circleci.com/gh/syndesisio/syndesis/46899).

Just for posterity the root cause seems to be:

java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is java.lang.NoSuchMethodError: io.undertow.servlet.api.DeploymentInfo.addServletContainerInitializer(Lio/undertow/servlet/api/ServletContainerInitializerInfo;)Lio/undertow/servlet/api/DeploymentInfo;
Caused by: java.lang.NoSuchMethodError: io.undertow.servlet.api.DeploymentInfo.addServletContainerInitializer(Lio/undertow/servlet/api/ServletContainerInitializerInfo;)Lio/undertow/servlet/api/DeploymentInfo;

**Comment by aileenc** [comment]
What version do we use?

**Comment by zregvart** [comment]
> What version do we use?

1.5.13.RELEASE

**Comment by aileenc** [comment]
We should be on SpringBoot 1.5.16

https://issues.jboss.org/browse/ENTESB-9322

Does taht have vulnerable version of spring-core

**Comment by KurtStam** [comment]
Upgraded to SpringBoot 1.5.16.

**Comment by tplevko** [comment]
shouldn't this be addressed also in 1.5.x. branch?

**Comment by oscerd** [comment]
No, because in 7.2.x we need to be in sync in all the Fuse part, so also on standalone and Fuse on Openshift. We'll align in 7.3

**Comment by tplevko** [comment]
@oscerd thank you for the clarification. In that case however, shouldn't the target release for this be 7.3 instead of 7.2. @heiko-braun wdyt?

**Comment by oscerd** [comment]
@tplevko there was some confusion about the version alignment. I think we need to backport this also on 1.5.x, because actually we are using the same version also on 7.2 standalone and Openshift. Sorry for the confusion.

**Comment by oscerd** [comment]
The problem is the pipeline version alignment.

**Comment by heiko-braun** [comment]
@oscerd I am confused. What target release to you have in mind?

**Comment by heiko-braun** [comment]
//cc @janstey Whatever the outcome, I think we need your teams feedback on this.

**Comment by oscerd** [comment]
> @oscerd I am confused. What target release to you have in mind?

I was talking about 7.2. The pipeline upgrade the dependency correctly to 1.5.16, but the codebase in Camel is still based on 1.5.13, that's why I was saying there was confusion. 7.2 will use 1.5.16 btw. So we are fine.

**Comment by heiko-braun** [comment]
Thanks for the clarification. Does this mean we can close this issue?

**Comment by oscerd** [comment]
Yes, this should be fine. Sorry again for the confusion @tplevko @KurtStam @heiko-braun
