### ISSUE TITLE
Application dashboards

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#3918]
As an expert user of Fuse Online I want to be able to browse to my Grafana instance and view metrics pre configured fro my Fuse environment.
I want my Grafana instance to be display metric per integration deployed.
Metrics we would like to see (per intergration)
	CPU usage
	Memory usage
	Average time to execute
	Min time to execute
	Max time to execute
	Average payload size	
	Min payload size
	Max payload size

Sample dashboard:

![image](https://user-images.githubusercontent.com/674767/47219372-a3a97f80-d37c-11e8-98a3-5014fc727fd0.png)

DoD
	Grafana should be installed and preconfigured for prometheus
	Grafana should be automatically connected to prometheus
	A single Fuse datasource is preconfigured in Grafana
	A single Fuse Dashboard is available exposing all prometheus fuse metrics and loads on navigating to the instance
	Documentation of how to create a custom dashboard is created

The feature owner has confirmed one of the following:
--There is an initial draft of the user doc for this feature.
--The writer acknowledges receiving enough information from engineering to write the initial draft of the user doc for this feature.

**Comment by alexkieling** [comment]
Merged into https://github.com/syndesisio/syndesis/issues/4146

**Comment by alexkieling** [comment]
I'm assuming we want to show JVM metrics (memory, threads, etc.) and Camel metrics (messages processed, processing time, etc.).

**Comment by gaughan** [comment]
Are JVM metrics handled in the infrastructure?

**Comment by alexkieling** [comment]
There is a infrastructure dashboard that shows the JVM metrics exposed by the Syndesis Server and Syndesis Meta applications.
The application dashboard will show the JVM and Camel metrics of each integration. We plan to add a drop-down to the top of the dashboard to select what integration we want to see the metrics.

**Comment by gaughan** [comment]
Sounds good, thanks alex

**Comment by zregvart** [comment]
@mmelko has soak tests running on staging (in `syndesis-test` project), would be good to have these tested there also.

**Comment by alexkieling** [comment]
@heiko-braun If this feature is targeted at expert Fuse Online user, shouldn't it be available in the Integration Metrics page?

**Comment by mkralik3** [comment]
Verified. The issue contains only dashboard (might be used in the future for external monitoring as the other dashboards in the addons folder). I verified it with _syndesis-prometheus_ instance which exposed all Camel metrics (relaxed [metric_relabel_configs](https://github.com/syndesisio/syndesis/blob/3736a21944dacd254663f493010f2122aa7b7593/install/generator/06-syndesis-prometheus.yml.mustache#L86) from the ConfigMap ) and installed own Grafana from a [template](https://raw.githubusercontent.com/openshift/origin/master/examples/grafana/grafana.yaml).

![Screenshot from 2019-06-03 14-56-29](https://user-images.githubusercontent.com/16251792/58805081-9e4f2b80-8613-11e9-90a4-8c4a64203637.png)
