### ISSUE TITLE
Indicate "auto generated" connections in the UI

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#3926]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

For auto-generating connections as discussed in #3692 there should be an indication in the UI that a connection is auto-generated. This could be as easy as a flag in the connection domain model which is set by an external API access (but not when we create the connection from within the UI)

**Comment by gashcrumb** [comment]
>  This could be as easy as a flag in the connection domain model

There's already the metadata map in the connection object that could be used to drive this

**Comment by gashcrumb** [comment]
We should also gather some UXD input as well so as not to conflict with the tech preview indicator and other potential indicators on connections, @dongniwang FYI

**Comment by dongniwang** [comment]
Are you @rhuss @gashcrumb referring to the OOTB connectors/connections? e.g. Timer, Log?

**Comment by rhuss** [comment]
@dongniwang no, its about connections which are created by external systems and which should show up in Syndesis. The concrete example are ActiveMQ connections which are created in an external system (EnMasse) and which should automatically available in Syndesis as connections for integrations.

**Comment by dongniwang** [comment]
@rhuss - OK. I think I need some more information about this to fully understand the request and use case. 

@heiko-braun @gaughan - Is this something we're hoping to deliver for 7.3? 

cc: @amysueg @syndesisio/uxd

**Comment by gaughan** [comment]
It could be a 7.3 item if we have space, probably a 7.4

**Comment by johnfriz** [comment]
@dongniwang - I'm part of the team requesting this feature - happy to set up a call to discuss.

**Comment by dongniwang** [comment]
@johnfriz - That would be great! Happy to discuss and learn more about it. Thank you!

**Comment by amysueg** [comment]
I'll set up a call @dongniwang @johnfriz  and we'll get this sorted out!
