### ISSUE TITLE
Missing Connection/Extension Property Change Event When Integrations Are Created Or Deleted

### ISSUE THREAD

**Issue by elvisisking** [syndesisio/syndesis#3931]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Connections and extensions have a `uses` integer property that identifies how many integrations are using it. When an integration is created that uses a connection or extension, a change event for that connection and/or extension should be fired. I don't believe that event is fired as the UI object cache/store does not get refreshed.

See #391 and #3930.

**Comment by chirino** [comment]
as a workaround we can force a full refresh on when those entities are created or refreshed.

**Comment by gashcrumb** [comment]
I don't think this is a p0/blocking item.

**Comment by heiko-braun** [comment]
must have been by accident

**Comment by mmuzikar** [comment]
Before closing this as verified I would suggest adding this information to extension detail. 
As now it can be quite confusing for some users, this is the preview and detail for the same extension in same application state and although you can't delete it, there is also written that no integrations are **currently** using it. 
So I would suggest adding line above this message saying how many integrations it is used by and then how many it is used by currently.
![image](https://user-images.githubusercontent.com/46345469/53870597-d639d900-3ffa-11e9-9754-ce5d153aa18a.png)
![image](https://user-images.githubusercontent.com/46345469/53870666-f7022e80-3ffa-11e9-9edf-e757149157c6.png)

**Comment by zregvart** [comment]
@mmuzikar I agree, let's move it to backlog so it gets addressed.

**Comment by mmuzikar** [comment]
Just looking at it in the new react UI, the number is now synchronized between those two pages and there is a table of all integrations currently using that extension.
I'd say we can consider this closed & verified. Feel free to reopen this if you think otherwise :)
