### ISSUE TITLE
Update icons for OOTB connections - Log, PostgresDB, and Timer 

### ISSUE THREAD

**Issue by dongniwang** [syndesisio/syndesis#3945]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Update the existing Log, PostgresDB, and Timer icons to the latest version. 

## Expected behavior

Here are the new set of icons: 

Log https://github.com/syndesisio/syndesis/blob/master/ux/connections_icons/svg/connectionicons_logstep.svg
![image](https://user-images.githubusercontent.com/24943812/47391523-0043cc00-d6e8-11e8-9e90-74e9fdc455e7.png)

PostgresDB https://github.com/syndesisio/syndesis/blob/master/ux/connections_icons/svg/SQL.svg
![image](https://user-images.githubusercontent.com/24943812/47391478-ea360b80-d6e7-11e8-8db8-2efe392733f1.png)

Timer https://github.com/syndesisio/syndesis/blob/master/ux/connections_icons/svg/connectionicons_timer.svg
![image](https://user-images.githubusercontent.com/24943812/47391546-12256f00-d6e8-11e8-9341-7d1ee557db3f.png)

@gaughan - Please advice if you feel we need to hold off on changing any of these icons. They currently are yellow. 

@gashcrumb @zregvart - If we get the green light, I think this is a task that needs your help. Thanks! 

Reference: https://github.com/syndesisio/syndesis/issues/3809
cc: @amysueg @michael-coker @jameslau

**Comment by gaughan** [comment]
LGTM! thanks

**Comment by gashcrumb** [comment]
@zregvart think this is actually purely a UI task, I'll get to it today.

**Comment by gashcrumb** [comment]
Nope, I'm lying, these get put in the DB :-)
