### ISSUE TITLE
API Provider overview screen should help the user invoke the endpoint

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#3948]
## This is a...

<pre><code>
[*] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
The overview screen of the API Provider overview screen should have a link to expand one endpoint showing a curl command that can be used to invoke the endpoint. Or a section that's like the SwaggerUI that describes the request and allows you to fire the request right there.

**Comment by zregvart** [comment]
It would be really cool if we could do this via Apicurio. Other than that we could always embed Swagger UI in the integration pod.

@EricWittmann does Apicurio have the ambition to also provide a API client functionality?

**Comment by EricWittmann** [comment]
We have discussed a (related but separate) effort to build something that would be a replacement for swagger-ui, but have no concrete plans yet.  It's been discussed/considered for more than a year now, so I wouldn't say it's likely at this point.  I'd probably recommend swagger-ui or ReDoc (although ReDoc might not yet have API client features).

**Comment by zregvart** [comment]
Let me channel @chirino here also, a link to the OpenAPI specification would also be nice. I even think we can show the link to the specification instead of _External URL_ on the integration details page.

Rationale is that the OpenAPI specification contains all the paths and the hostname.

Doh, that reminds me (#3972).

**Comment by atkawa7** [comment]
@zregvart @EricWittmann Checkout https://github.com/atkawa7/httpsnippet for generating code snippets with springfox and redoc

**Comment by zregvart** [comment]
Thanks @atkawa7 the cURL snipped generation could be something could use. Not sure where would that fit though on the backend (implemented in Java) or in the UI (via https://github.com/Kong/httpsnippet).

**Comment by atkawa7** [comment]
@zregvart You could use the client directly https://github.com/atkawa7/httpsnippet/blob/master/httpsnippet/src/main/java/io/github/atkawa7/httpsnippet/generators/shell/Curl.java

**Comment by EricWittmann** [comment]
> It would be really cool if we could do this via Apicurio. Other than that we could always embed Swagger UI in the integration pod.
> 
> @EricWittmann does Apicurio have the ambition to also provide a API client functionality?

No, this is outside the scope of Apicurio.  I'm actually using ReDoc to display documentation to the user (with plans to add swagger-ui as well).  Client functionality is not something that's very useful during the design phase, so it's not something that's really on the radar.  That's much more useful for e.g. API Implementations and API Management, where there is a real endpoint that someone can hit.
