### ISSUE TITLE
IVP expand button tooltip is behind the connection cards 

### ISSUE THREAD

**Issue by dongniwang** [syndesisio/syndesis#3954]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

The tooltip of the exapand IVP button is covered by the connection cards in the create integration flow. 

## Expected behavior

The tooltip should appear above the connection cards so users can see what's on the tooltip. 

## Screenshot

![screen shot 2018-10-24 at 1 11 45 pm](https://user-images.githubusercontent.com/24943812/47448839-0d67c600-d78f-11e8-9eb5-e878762eeacc.png)

## Tasks involved / Steps to Reproduce

1. Go to staging site 
2. Click "Create Integration" 
3. Hover over the expand button

**Comment by dongniwang** [comment]
@jameslau @michael-coker - Is this something either of you can take a look at? Thanks!

**Comment by jameslau** [comment]
I can take a look at this issue. It's similar to [#3806](https://github.com/syndesisio/syndesis/issues/3806)

**Comment by heiko-braun** [comment]
@jameslau Can we get this in by tomorrow (code freeze)?

**Comment by jameslau** [comment]
@heiko-braun sure thing, I'll jump on it today.
