### ISSUE TITLE
OData client connection 

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#3956]
As a citizen user of fuse online, I want to be able to connect to an OData V4 Producer 
I want to be able to provide my connection url, authentication details and any additional details such as cache settings.
DoD
I can create an integration with a standard timer writing to an OData service.
I can connect to an OData VDB resource exposed on Openshift

--There is an initial draft of the user doc for this feature.
--The writer acknowledges receiving enough information from engineering to write the initial draft of the user doc for this feature.

**Comment by gaughan** [comment]
Adding @dhirajsb @zregvart @cunningt as I'm not sure who worked on OData originally

**Comment by heiko-braun** [comment]
@phantomjinx I guess @dhirajsb can answer these questions

**Comment by phantomjinx** [comment]
> @phantomjinx I guess @dhirajsb can answer these questions

> The existing odata connector is indeed an older version and uses the olingo2 component. You should start anew with the olingo4 component.

Answer kindly provided by @dhirajsb via email.

**Comment by phantomjinx** [comment]
Teiid's [implementation](https://teiid.github.io/teiid-documents/10.2.x/content/client-dev/OData4_Support.html) of the odata protocol is secured via BASIC authentication. Parameters supporting this will need to be incorporated.

- [Link for odata 4 component specification](https://github.com/apache/camel/blob/master/components/camel-olingo4/camel-olingo4-component/src/main/docs/olingo4-component.adoc)
- [Link to old odata 2 component](https://camel.apache.org/olingo2.html)
- [Example odata service](https://services.odata.org/TripPinRESTierService/)
- [OData 4 Documentation](https://www.odata.org/documentation/)
- [OData 4 OASIS URL Spec](http://docs.oasis-open.org/odata/odata/v4.01/cs01/part2-url-conventions/odata-v4.01-cs01-part2-url-conventions.html)

**Comment by phantomjinx** [comment]
**olingo4-connector bugs logged for issues ^**
- [serviceUri as query property](https://issues.apache.org/jira/projects/CAMEL/issues/CAMEL-13005)
- [edm & responseHandler missing properties](https://issues.apache.org/jira/projects/CAMEL/issues/CAMEL-13006)

**Comment by phantomjinx** [comment]
As regards the issues in the camel-olingo4 component [listed](https://github.com/syndesisio/syndesis/issues/3956#issuecomment-447409978), some have now been fixed while some are being investigated. At some point, upstream should contain fixes for all of them. At the moment, current syndesis source would pick up original versions of this library, so any integrations built and deployed using the odata connector lead to failures. Therefore, could the process be described here to outline how:

a) a new version of the component would be made available as part of the forked fuse collection (those build dependencies labelled name.version.fuse-xxxxxx);
b) to include a fixed version of the component in syndesis whilst waiting on the forking of the new upstream release, ie. how to package/build a custom version within syndesis. (Seems google-sheets connector might do this?)

Thanks.

@heiko-braun @zregvart @lburgazzoli

**Comment by zregvart** [comment]
We usually backport this to Fuse Camel fork and do a release that is then pinned in the early access JBoss repository. You an do it like that if you think we're done with the changes to the Camel component; or you can vendor the component in Syndesis source tree until we're confidant enough that we won't make (many) changes.

**Comment by phantomjinx** [comment]
Thanks @zregvart 
Would you mind outlining how these processes are achieved. Probably at the moment, the latter is more pertinent due to the remaining outstanding upstream issues?

**Comment by zregvart** [comment]
To vendor you simply copy over the source from the Camel component into the connector and make sure that the connector descriptor JSON doesn't reference the Camel component artifact. I think you'd want to remove the dependency on the component from Maven POM also.

Similar to how we have it for the kudu connector:

https://github.com/syndesisio/syndesis/tree/master/app/connector/kudu/src/main/java

I think that's a good start and quickest way to iterate, once we have the component in a place upstream we can backport the related commits to Fuse Camel fork.

**Comment by phantomjinx** [comment]
Great progress made! Have successfully published an odata integration consuming data from a odata/teiid/wildfly server. All 50 US states appear in the pod's log!
Slight wrinkle is that the odata component [polls](https://camel.apache.org/polling-consumer.html#PollingConsumer-ScheduledPollConsumerOptions) the same data multiple times. I notice other connectors include the 'initial delay' and 'delay' properties to slow down the polling. However, I can see that the twitter connector has a 'filterOld' property and the gmail connector has a 'markRead' property. No such properties are available for odata. Therefore, is it 'ok' to have data repeated upon each polling or should I look for a way to filter results?

Pointers and suggestions appreciated!

@gaughan @heiko-braun @lburgazzoli @zregvart

**Comment by heiko-braun** [comment]
//cc @syndesisio/backend Can anyone assist @phantomjinx ? (See questions above)

**Comment by lburgazzoli** [comment]
We do not have such filter as syndesis level and this functionality is usually provided by the camel component so I think the connector is fine. 

If you have time and can investigate how to implement such filter at camel level, that would eb awesome.
