### ISSUE TITLE
Most connection disappeared

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#3957]
## This is a...

<pre><code>
[ ] Feature request
[*] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
I think we are a little too aggressive with hiding things

<img width="1024" alt="screen shot 2018-10-25 at 10 11 14 am" src="https://user-images.githubusercontent.com/35576/47491623-83316780-d84b-11e8-9103-610b605d015e.png">

It's probably a regression from: #3889

**Comment by nicolaferraro** [comment]
I though I did this test... There's a "list" and a "listVisible" method on the connection provider.. maybe I used the wrong one in the integration selection page..

**Comment by heiko-braun** [comment]
@nicolaferraro Can you help @gashcrumb to get this sorted out?

**Comment by nicolaferraro** [comment]
Sure, I think @gashcrumb is already doing a full reinstall. If he confirms the problem, I can help to fix it.

**Comment by gashcrumb** [comment]
Yeah, so same deal with the full install, so I can't reproduce here and the code changes were kinda along the lines of what I was expecting when I approved the PR.

Kurt, can you try pulling/rebuilding just to check on your end?  Also you might try explicitly clearing your browser cache.

And if it still happens can you check the browser developer tools to see if any errors pop up?

**Comment by KurtStam** [comment]
@nicolaferraro @gashcrumb 
Turns out it's only reproducible when installing with "bash <(curl -sL https://syndes.is/start)"

**Comment by heiko-braun** [comment]
Based on @KurtStam comment I am lowering the priority.

**Comment by nicolaferraro** [comment]
I suspect it's because https://syndes.is/start has the following statement at the beginning of the script:

```
# Latest tagged versions
SYNDESIS_DEFAULT_VERSION=1.3
```

It's using a old version without those connectors..

**Comment by KurtStam** [comment]
@nicolaferraro I will update the version.
