### ISSUE TITLE
Improving the docs on creating custom steps

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#3959]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Documentation issue or request
</code></pre>

## Description
"The documentation of creating custom steps in Fuse Online does not include guidance on how to register beans in the Camel Registry

The extension examples are very thin and do not include all necessary dependencies to interact with SpringBoot. A developer willing to create an extension will find it hard to do it well and correctly.

I suggest we also document the different GUI fields that can be mapped to the Java inputs in a custom step/connector"

**Comment by TovaCohen** [comment]
I'm going to close this. We track doc work for Syndesis in the FUSEDOC Jira project.
I copied the content in this issue to:
https://issues.jboss.org/browse/FUSEDOC-2916
