### ISSUE TITLE
Automate the deployment of Fuse (Staging to Production)

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#3960]
As a developer of Fuse applications, I want to be able to automate the deployment of my applications to my staging environment on Open Shift and subsequently to my production environment. Out of the box, I want to have a sample fuse application, that I can deploy via playbook or Jenkins? to my staging and production environments running Fuse, 3Scale and AMQ

I want to be able to push my integrations from one environment to the other. I want the ability to see view the version of the integration in the environment.
I want to be able to roll back a version push.

In the future, I want canary deployment and blue/green deployment.

Questions
How are permissions handled between environments, how do I provide/request authorization?
How do I get state/publish
 DoD A sample fuse application for Fuse on Open Shift is available. A playbook is available to deploy on staging and production environments.
--There is an initial draft of the user doc for this feature. --The writer acknowledges receiving enough information from engineering to write the initial draft of the user doc for this feature.

**Comment by oscerd** [comment]
Can you please explain much more details about this?

**Comment by mkralik3** [comment]
What is a result of this issue? (How to verify it?)
I don't see any linked resolved issues and the similar Epic with Import/Export REST API #3701 exist.

**Comment by heiko-braun** [comment]
We can close this. All work was tracked under  #3701
