### ISSUE TITLE
Clean up unused png icons in app/ui/src/assets/icons

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#3962]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
[*] Chore
</code></pre>

## Description
Might as well free up some space and clear out some unused png files for connection icons that are kept in the frontend image.

**Comment by tplevko** [comment]
Just removal of unused icons. Closing
