### ISSUE TITLE
Remove the circle border from the settings page icons?

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#3963]
## This is a...

<pre><code>
[*] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
The settings page still have the circles ->
![image](https://user-images.githubusercontent.com/351660/47509423-123a8180-d844-11e8-82a7-be62609eff2e.png)

At this stage the only place they're used is in the IVP and integration detail page as far as I can see, and given that the sizing is a bit tight they kinda mess with the icon they're encircling.  Should these circles be removed?

@dongniwang @michael-coker thoughts?

**Comment by michael-coker** [comment]
@gashcrumb +1. this would match the integration list view.

**Comment by dongniwang** [comment]
Yeah, no strong feelings about the blue circle on this page as they don't mean anything - unless we can style it:
- When it's _NOT_ configured, it has the grey circle.
- Then when it's configured, it has the blue circle. 

Also, what about the integration details page?

**Comment by michael-coker** [comment]
Right now I think it looks OK on the integration details page and in the IVP because the background of the page is grey, so there is a white circle behind the icons to make it standout against the background, and the border helps define the white circle. Plus there is a good amount of spacing between the icon and the grey/blue borders, unlike in this view.

**Comment by michael-coker** [comment]
oops! I hit tab too many times before hitting enter to submit the comment and accidentally closed the issue 😄

**Comment by michael-coker** [comment]
Here's what it would look like

<img width="1232" alt="screen shot 2018-10-25 at 1 12 46 pm" src="https://user-images.githubusercontent.com/35148959/47521117-b7ab2080-d857-11e8-8d26-f0e590eb9742.png">

**Comment by dongniwang** [comment]
Nice! So much cleaner! @michael-coker 

For some reason, I keep thinking there's a version of the integration details page with the white background. We need to revisit that page at some point for sure... along with https://github.com/syndesisio/syndesis/issues/3648
