### ISSUE TITLE
API Provider - return path icon is not being displayed in the IVP when configuring a flow

### ISSUE THREAD

**Issue by dongniwang** [syndesisio/syndesis#3974]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

When configuring a flow in API Provider integration, the return path icon is not being displayed in the IVP. Instead, the API Provider is being shown for the return path. 

## Expected behavior

Display return path icon for return path configuration. 

## Screenshot

Current behavior: 
<img width="347" alt="screen shot 2018-10-26 at 11 49 39 am" src="https://user-images.githubusercontent.com/24943812/47578154-a2e19200-d916-11e8-96df-919e9538beda.png">

Correct behavior:
<img width="147" alt="screen shot 2018-10-26 at 12 00 45 pm" src="https://user-images.githubusercontent.com/24943812/47578213-cf95a980-d916-11e8-9f52-2f7949028c93.png">

## Tasks involved / Steps to Reproduce

1. Go to staging site
2. Create integration with API provider 
3. Select a flow 
4. Now you can see two API provider icons...

**Comment by dongniwang** [comment]
Assigning this to @michael-coker for now. But wanted to cc @gashcrumb @riccardo-forina @zregvart in case @michael-coker can't fix this.

**Comment by zregvart** [comment]
I think the icons might get set on the backend when the integration flows are generated.

**Comment by dongniwang** [comment]
Fix is provided here https://github.com/syndesisio/syndesis/pull/3979. Closing now.
