### ISSUE TITLE
Connection icons in IVP don't appear immediately

### ISSUE THREAD

**Issue by mcoker** [syndesisio/syndesis#3988]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
The start/finish connection icons in the IVP don't show up when you choose the connection type.

## Expected behavior
When you click a connection to use, it's icon should appear in the selected white circle (icon placeholder) in the IVP.

## Log as finish connection
<img width="1593" alt="screen shot 2018-10-29 at 4 09 25 pm" src="https://user-images.githubusercontent.com/35148959/47680585-39bb8200-db95-11e8-9bd3-a31c276de5d6.png">

## API integration
<img width="1593" alt="screen shot 2018-10-29 at 4 06 02 pm" src="https://user-images.githubusercontent.com/35148959/47680587-39bb8200-db95-11e8-9290-e93d3061af05.png">

## DB as start connection
<img width="1593" alt="screen shot 2018-10-29 at 4 05 46 pm" src="https://user-images.githubusercontent.com/35148959/47680588-39bb8200-db95-11e8-89b8-35f86a4db813.png">

## Tasks involved / Steps to Reproduce

1. Create an integration
2. See icon brokenness

cc @dongniwang

**Comment by dongniwang** [comment]
@michael-coker - What version of the app were you using?

**Comment by gashcrumb** [comment]
Any JS console errors?

@riccardo-forina can you have a look into this when you get a chance?

**Comment by gashcrumb** [comment]
I wonder if this has anything to do with the icon rework, I hadn't seen any issues since merging it locally.

@michael-coker did you rebuild the backend btw?  I think all the icons now come from the syndesis server, and there were changes that involved the initial connector/connection json that's installed out of the box, so you might need to do a full rebuild.

**Comment by gashcrumb** [comment]
Yep, this is probably the cause, whatever bug is causing this error to be thrown:

![image](https://user-images.githubusercontent.com/351660/47688033-b19ba380-dbb9-11e8-940b-22b2eb61fc84.png)

**Comment by gashcrumb** [comment]
Yep, issue was actually in the template, attached PR should sort it.

**Comment by gashcrumb** [comment]
@riccardo-forina nothing to do, sorry!  :-)

**Comment by tplevko** [comment]
Works perfectly now!
