### ISSUE TITLE
Warning dialog in API provider is blank

### ISSUE THREAD

**Issue by mkralik3** [syndesisio/syndesis#3996]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

When I want to cancel API provider, the shown dialog is blank. Buttons works.

## Screenshot

![image](https://user-images.githubusercontent.com/16251792/47706075-9ddb5600-dc28-11e8-9535-7a75b61b67da.png)

## Tasks involved / Steps to Reproduce
1. Click on Create Integration
2. Select API Provider
3. Click on Cancel button

**Comment by riccardo-forina** [comment]
This should be a side-effect of #3988, which has been fixed by #3994. Can you check this again against master?

**Comment by mkralik3** [comment]
Yes, the issue is gone in the latest version.
