### ISSUE TITLE
No way to specify alternative response for API Provider based on request and previous steps outcome

### ISSUE THREAD

**Issue by asmigala** [syndesisio/syndesis#3999]
See also **https://issues.jboss.org/browse/ENTESB-11452**

## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When implementing API Provider operations, there is no way to gracefully handle situations when e.g. a requested item does not exist or a POSTed item already exists. These situations end up returning the stack trace in the body and 500 as the response status.

## Steps to reproduce
(note this is just an example, there are other situations where we would want to change the response based on the outcome of previous steps)
1. Create an API Provider integration from the TODO API spec
2. Implement the Fetch task operation
3. Add a postgres connection with `select * from todo where id = :#id`
4. Add the appropriate mappings from the request to postgres and from postgres to response
5. Publish the integration
6. Go to {integration-url}/api/42 (or some other non-existent id) in the browser, the full stacktrace is returned with http status 500

**Comment by heiko-braun** [comment]
@asmigala To me this is another limitation, rather than a blocking issue. 

@gaughan What do you think?

**Comment by gaughan** [comment]
Yes agree, we had planned to tackle error handling in 7.3

**Comment by mmuzikar** [comment]
@heiko-braun Just letting you know that now the same steps that @asmigala described result in status code 200 and returns `{"id": null, "completed": null, "task": null}`

**Comment by zregvart** [comment]
I think the `null` values come from the mapper, it will generate the output document in the shape of the definition and as it can't find any values to fill in (empty or null message body) it fills with `null`. This is as expected under the functionality we have right now.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11452**
