### ISSUE TITLE
Re-enable checks on connectors project

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#400]
See comments in https://github.com/syndesisio/syndesis/pull/365, we should enable checks done by Maven plugins that are currently disabled by setting the `phase` to `none` or `skip` set to `true`. That means cleaning up the code to meet the standards of those checks also.

**Comment by gashcrumb** [comment]
This seems stale, re-open if this needs to be a thing, maybe outline better what needs to be done.

**Comment by zregvart** [comment]
We need to go through `pom.xml`s in `app/connector` and enable checks. Currently most of the maven plugins performing the checks are disabled.

https://github.com/syndesisio/syndesis/blob/3734dfc6d186a25fe6dc2306ee1bf4276b7166ed/app/connector/pom.xml#L140-L189
