### ISSUE TITLE
character encoding issue when integrating twitter2gmail

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#4000]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[*] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Use search term 'Syndesis'. and send from twitter to gmail.

Email comes in looking like

<img width="1114" alt="screen shot 2018-10-30 at 3 49 17 pm" src="https://user-images.githubusercontent.com/35576/47726901-b1ec7b00-dc5b-11e8-8f28-fe7ea07dbdb6.png">

I'm using Paul's scenario.

https://youtu.be/Pfysm8W8sco

![utf-8-encoding-issues-better-drink-my-own-pee](https://user-images.githubusercontent.com/35576/47727239-5a024400-dc5c-11e8-9108-65e5b883c13f.jpg)

**Comment by KurtStam** [comment]
[Twitter2Gmail-export.zip](https://github.com/syndesisio/syndesis/files/2530224/Twitter2Gmail-export.zip)

**Comment by KurtStam** [comment]
<img width="725" alt="screen shot 2018-10-30 at 4 16 27 pm" src="https://user-images.githubusercontent.com/35576/47728703-2a087000-dc5f-11e8-93e3-c8d69507b3b9.png">

**Comment by KurtStam** [comment]
Looks like it may be coming from Twitter

<img width="721" alt="screen shot 2018-10-30 at 4 32 42 pm" src="https://user-images.githubusercontent.com/35576/47730017-8cfb0680-dc61-11e8-8b24-21b9785c5f49.png">

**Comment by oscerd** [comment]
Ok, I'll have look there too

**Comment by oscerd** [comment]
Yes, your token expired. You need to use the ClientId and ClientSecret to get authorized through the oauth workflow, only one first time. So you'll need fresh clientId and clientSecret never used, do the workflow and you'll get back your refresh token.

**Comment by aileenc** [comment]
Is this low risk fix for 7.2?

**Comment by oscerd** [comment]
This is not something easy to do, it's probably something at component level. I don't think it's feasible for this sprint.

**Comment by oscerd** [comment]
It doesn't seem to be a problem at component level. I'm able to log correctly the output of Japanese tweets.

**Comment by oscerd** [comment]
Also searching for magnesianews.gr I was able to log the following tweet 

```
(2018-11-02 10:13:20,759 [main           ] INFO  DefaultCamelContext            - Apache Camel 2.23.0-SNAPSHOT (CamelContext: camel-1) is starting
2018-11-02 10:13:20,760 [main           ] INFO  DefaultManagementStrategy      - JMX is disabled
2018-11-02 10:13:20,797 [main           ] INFO  DefaultTypeConverter           - Type converters loaded (core: 195, classpath: 5)
2018-11-02 10:13:20,853 [main           ] INFO  DefaultCamelContext            - StreamCaching is not in use. If using streams then its recommended to enable stream caching. See more details at http://camel.apache.org/stream-caching.html
2018-11-02 10:13:20,870 [main           ] INFO  DefaultCamelContext            - Route: route1 started and consuming from: twitter-search://magnesianews.gr?accessToken=26693234-W0YjxL9cMJrC0VZZ4xdgFMymxIQ10LeL1K8YlbBY&accessTokenSecret=BZD51BgzbOdFstWZYsqB5p5dbuuDV12vrOdatzhY4E&consumerKey=NMqaca1bzXsOcZhP2XlwA&consumerSecret=VxNQiRLwwKVD0K9mmfxlTTbVdgRpriORypnUbHhxeQw&delay=5000&type=polling
2018-11-02 10:13:20,870 [main           ] INFO  DefaultCamelContext            - Total 1 routes, of which 1 are started
2018-11-02 10:13:20,871 [main           ] INFO  DefaultCamelContext            - Apache Camel 2.23.0-SNAPSHOT (CamelContext: camel-1) started in 0.112 seconds
2018-11-02 10:13:20,871 [main           ] INFO  MockEndpoint                   - Asserting: mock://result is satisfied
2018-11-02 10:13:22,790 [main           ] INFO  SearchPollingTest              - Tweet: Fri Nov 02 08:51:25 CET 2018 (magnesianews) Στο «μικροσκόπιο» οι συναλλαγές για τη χρυσή βίζα https://t.co/p7DSDXICdA)
```

By using the SearchPollingTest in Camel

**Comment by oscerd** [comment]
If you use the log connector without log step

`
{"exchange":"i-LQJ6EPiBZPXmWRJonf4z","step":"-LQJ5_o3G2ejjzN4O3X1","id":"i-LQJ6EPiBZPXmWRJonf6z","duration":1320427}
--
  | {"exchange":"i-LQJ6EPiBZPXmWRJonf4z","status":"done","failed":false}
  | {"exchange":"i-LQJ6ux3BZPXmWRJonf7z","status":"begin"}
  | {"exchange":"i-LQJ6ux3BZPXmWRJonf7z","step":"null","id":"i-LQJ6ux4BZPXmWRJonf9z","message":"Exchange[ExchangePattern: InOnly, BodyType: twitter4j.StatusJSONImpl, Body: Fri Nov 02 11:12:01 UTC 2018 (magnesianews) Bloomberg: ??????? ? ?????? ??? ??? ??? ???????? ???????? ??? ??????? https://t.co/txauqMLDpm  https://t.co/WfRjJ9Dekt ]"}
  | 2018-11-02 11:12:18.248  INFO 1 --- [magnesianews.gr] syndesis-log                             : **Exchange[ExchangePattern: InOnly, BodyType: twitter4j.StatusJSONImpl, Body: Fri Nov 02 11:12:01 UTC 2018 (magnesianews) Bloomberg: Ανοίγει ο δρόμος για μια νέα εμπορική συμφωνία ΗΠΑ – Κίνας https://t.co/txauqMLDpm  https://t.co/WfRjJ9Dekt ]**
`

It logs the stuff fine. so it seems to be the log step.

**Comment by oscerd** [comment]
I can confirm it's the log step. Not sure about this but it looks like it doesn't care about the charset you set. I'll have a look.

**Comment by oscerd** [comment]
@igarashitm do you think this is something related to datamapping?

**Comment by igarashitm** [comment]
Hmm as it's starting from Twitter which has Java DataShape, it must be always UTF-8 while AtlasMap is processing a payload.
* AtlasMap is extracting Camel body here
  * https://github.com/atlasmap/atlasmap/blob/master/camel/src/main/java/org/apache/camel/component/atlasmap/AtlasEndpoint.java#L291
  * https://github.com/atlasmap/atlasmap/blob/master/camel/src/main/java/org/apache/camel/component/atlasmap/AtlasEndpoint.java#L330
  * https://github.com/atlasmap/atlasmap/blob/master/camel/src/main/java/org/apache/camel/component/atlasmap/AtlasEndpoint.java#L332

Also AtlasMap mapping definition is assumed as UTF-8 here in Syndesis.
https://github.com/syndesisio/syndesis/pull/3124

And this reminded me that Syndesis integration runtime pod doesn't have platform default encoding to be UTF-8 IIRC. Log connector might need to specify encoding explicitly if it depends on platform default.

**Comment by oscerd** [comment]
The log connector seems to work fine if you look at the output above. The problem seems to be in the log step.

**Comment by igarashitm** [comment]
Oops, sorry for the confusion

**Comment by heiko-braun** [comment]
@gaughan if its just the log step, and considering the low impact I would suggest to make this p2

**Comment by gaughan** [comment]
@heiko-braun agreed

**Comment by oscerd** [comment]
Maybe it could be also the dump of the exchange. Need to investigate more
