### ISSUE TITLE
Gmail OAuth does not support RefreshTokens so only works for 60 min

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#4002]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[*] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When using the Gmail connector OAuth:
<img width="772" alt="screen shot 2018-10-30 at 4 40 27 pm" src="https://user-images.githubusercontent.com/35576/47730625-d861e480-dc62-11e8-907d-db3e8918a5e7.png">

The token expires after an hour. 
<img width="771" alt="screen shot 2018-10-30 at 4 46 48 pm" src="https://user-images.githubusercontent.com/35576/47730904-6b9b1a00-dc63-11e8-972d-dd7d8a3e33d0.png">

**Comment by oscerd** [comment]
This is how Google works. You need to provide clientId and clientSecret never used before if you want to have a refreshToken. I told you in the other issue. We can't do anything here.

**Comment by oscerd** [comment]
This will work and you should get a refreshToken in the connection. This was verified by QE and tested by myself and @zregvart. And it's reported in docs too I guess.

**Comment by oscerd** [comment]
Definitely not a bug

**Comment by KurtStam** [comment]
OK I will refresh my MiniShift as I guess I may not have that fix, however just want to state that it was a brand new OAuth token/clientId and it worked for an hour. Anyway I will report back.

**Comment by oscerd** [comment]
You need to check if you have access offline defined in your oauth settings on DB. If not you won't have a refresh token and the token will expire

**Comment by KurtStam** [comment]
Seems to be working ok using the latest code. Thanks!
