### ISSUE TITLE
Smartsheet Connector

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#4009]
See also **https://issues.jboss.org/browse/ENTESB-11517**

Smartsheets
As a citizen Integrator, I want to be able to use smartsheets in my integration

I would like to be able to provide my authentication details to my smart sheet instance and authenticate my connection in smartsheets.
I would like to be able to configure both:
start connector to accept subscribed to webhook callbacks from my smartsheets instance
finish connector to write data, apply formulas, create charts in my smartsheets instance

DoD

I can read and write data to smartsheets
I can subscribe to smartsheets resources and in turn be notified if a cell is changed.
I can build pivot tables
I can create charts
The feature owner has confirmed one of the following:
--There is an initial draft of the user doc for this feature.
--The writer acknowledges receiving enough information from engineering to write the initial draft of the user doc for this feature.

**Comment by heiko-braun** [comment]
@gaughan smartsheets or googlesheets? The description mentions both.

**Comment by gaughan** [comment]
@heiko-braun smartsheets. c&p error

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11517**
