### ISSUE TITLE
Unable to upgrade using operator - upgrade pod - pod has unbound PersistentVolumeClaims

### ISSUE THREAD

**Issue by avano** [syndesisio/syndesis#4010]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
I tried to upgrade from "1.4.9" to "latest" (because currently there is still hardcoded "latest" upgrade pod in operator image #3924).
Then I tried from "1.5.5" to "latest" with the same result - upgrade pod won't start because of this:
![up1](https://user-images.githubusercontent.com/7081216/47850659-4aa70600-ddd6-11e8-84a6-ca2160f5c462.png)

There is also this error in the operator log:
```
time="2018-11-01T11:58:12Z" level=error msg="error syncing key (myproject/app): object is being deleted: persistentvolumeclaims \"syndesis-upgrade\" already exists"
```

steps to reproduce:
./syndesis install -s
./syndesis install --project myproject --tag 1.4.9
wait for syndesis to install
deploy new operator image, for example 1.5.6 version

minishift v1.26.1+1e20f27
openshift 3.10

**Comment by heiko-braun** [comment]
@nicolaferraro @rhuss Can you two take a look at this?

**Comment by nicolaferraro** [comment]
@avano I'm not able to reproduce it.

Here's the list of steps I'm doing:
```
syndesis install --project myproject --tag 1.4.9
# wait for everything to install
syndesis install --operator-only --tag 1.5.6
```

The result is what expected. The error about the persistent volume claim already existing is not a real issue. It will not appear anymore after #3861.

Operator logs:
```
  | time="2018-11-06T00:04:51Z" level=info msg="Go Version: go1.10.3"
  | time="2018-11-06T00:04:51Z" level=info msg="Go OS/Arch: linux/amd64"
  | time="2018-11-06T00:04:51Z" level=info msg="operator-sdk Version: 0.0.5+git"
  | time="2018-11-06T00:04:51Z" level=info msg="Using template /conf/syndesis-template.yml"
  | time="2018-11-06T00:04:51Z" level=info msg="Watching syndesis.io/v1alpha1, Syndesis, myproject, 5"
  | time="2018-11-06T00:04:51Z" level=info msg="No legacy Syndesis installations detected in the myproject namespace"
  | time="2018-11-06T00:04:51Z" level=info msg="Syndesis legacy installations check completed"
  | time="2018-11-06T00:04:51Z" level=info msg="Starting upgrade of Syndesis resource app from version 1.4.9 to version 1.5.6"
  | time="2018-11-06T00:04:51Z" level=info msg="Upgrading syndesis resource app from version 1.4.9 to 1.5.6"
  | time="2018-11-06T00:04:51Z" level=error msg="error syncing key (myproject/app): object is being deleted: persistentvolumeclaims \"syndesis-upgrade\" already exists"
  | time="2018-11-06T00:04:52Z" level=info msg="Upgrading syndesis resource app from version 1.4.9 to 1.5.6"
  | time="2018-11-06T00:04:56Z" level=info msg="Syndesis resource app is currently being upgraded to version 1.5.6"
  | time="2018-11-06T00:05:01Z" level=info msg="Syndesis resource app is currently being upgraded to version 1.5.6"
  | time="2018-11-06T00:05:06Z" level=info msg="Syndesis resource app is currently being upgraded to version 1.5.6"
  | time="2018-11-06T00:05:11Z" level=info msg="Syndesis resource app is currently being upgraded to version 1.5.6"
```

The upgrade pod **is bound and completes successfully**.

The redeployment does not stop because #3924 is not merged and tag is hardcoded to latest, but I don't see the error you're reporting here.

Are you doing something different?

**Comment by avano** [comment]
@nicolaferraro strange, I tried again with the same steps as you and still can see the same outcome. I'll ask around if I'm the only one with that problem and will let you know

**Comment by tplevko** [comment]
@nicolaferraro I was also able to reproduce the issue @avano describes. Which openshift version do you use please? We both hit this issue on 3.10.

**Comment by nicolaferraro** [comment]
This is my env:
```
minishift v1.25.0+90fb23e
openshift v3.10.0+349c70c-73
kubernetes v1.10.0+b81c8f8
```

Can you share the yaml of the upgrade pod to understand why it's not mounting the volume?

**Comment by nicolaferraro** [comment]
There are a number of issues on OpenShift related to subpath mounting:

```
...
volumeMounts:
- mountPath: /opt/backup
  subPath: backup
  name: backup-dir
```

It may be a OpenShift issue.

**Comment by heiko-braun** [comment]
@avano @nicolaferraro What `oc` version are you using? Could it be related?

**Comment by nicolaferraro** [comment]
No, I don't think the `oc` version is related because the resources that are having the problem are not created by `oc` directly, they are created by the operator.

The issue in the event monitor seems related to the subPath mounting, that is a feature that we don't actually need to use since we have a dedicated volume for the upgrade now.

**Comment by avano** [comment]
btw I tried to upgrade from 1.4.9 to "master" (latest with your changes) and it works well now.

**Comment by heiko-braun** [comment]
@avano if it works well, can you close the issue?

**Comment by avano** [comment]
@heiko-braun I would prefer to leave this open until it gets to a prod build, because the CR1 is affected as well at the moment

**Comment by heiko-braun** [comment]
@avano Yes, makes sense.

**Comment by avano** [comment]
fixed in CR2 prod build
