### ISSUE TITLE
Jaeger based storage for activity monitoring

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#4011]
See also **https://issues.jboss.org/browse/ENTESB-11516**

## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

As discussed in #3922 (and #3337, #3252, #2598, #1780, ...) we need a new mechanism for storing activity entries.

**Comment by heiko-braun** [comment]
@chirino Do you still plan to work on this?

**Comment by chirino** [comment]
Current status
The following PRs have been merged to master:
#5280  Add jaeger-spring-boot-starter and enabled it in the syndesis server so it can participate in opentracing requests.
#5283 Add optional jaeger tracing for activity monitoring for the SB runtime.
#5285 Add a jaeger based ActivityTrackingService.

Still Pending:
Being able to optionally enable via syndesis CRD option the jaeger based activity tracing.  I started a branch to do that at: https://github.com/chirino/syndesis/tree/jaeger-4
But it does not yet optionally install it.

**Comment by chirino** [comment]
It might be worth waiting until openshift template based installed don't need to be supported anymore so that we can have a more dynamic operator.

**Comment by chirino** [comment]
This is now completed: 
1. Install syndesis as usual. 
1. Install the Jaeger operator as described at: https://www.jaegertracing.io/docs/1.13/operator/#installing-the-operator-on-okd-openshift
2. As a cluster admin, grant the sydnesis operator access to create a jaeger instance: 
```
NAMESPACE=`oc project -q`
oc create  rolebinding syndesis-jaeger-operator --clusterrole=jaeger-operator --serviceaccount $NAMESPACE:syndesis-operator
```
3. Update the sydnesis custom resource to enable the jaeger addon:
`oc patch syndesis app --type merge -p '{"spec":{"addons":{"jaeger":{"enabled":"true"}}}}'`

**Comment by heiko-braun** [comment]
Do we fallback to the current activity logging when jaeger is not enabled?

**Comment by chirino** [comment]
No.  If you enable the jaeger addon, the system will be configured for jaeger

**Comment by chirino** [comment]
We also need to do some work to also enable this feature to work when camel-k mode is enabled.

**Comment by heiko-braun** [comment]
Yes, but what if jaeger is not enabled?

**Comment by chirino** [comment]
if you don't enable the jaeger addon, then syndesis continues to use db based activity logging.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11516**
