### ISSUE TITLE
Problem with create integration after clicking on breadcrumb

### ISSUE THREAD

**Issue by shawkins** [syndesisio/syndesis#4014]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
Clicking on the integration name breadcrumb before the integration is saved gets things in a bad state.

## Screenshot

![screenshot_20181101_155615](https://user-images.githubusercontent.com/2475669/47876079-b8f7c280-ddee-11e8-8136-69ac504dcf58.png)

## Tasks involved / Steps to Reproduce

1. attempted to create an integration.
2. added a name, xyz, in the text field on the left nav
3. clicked on the name in the top breadcrumbs "Home > Integrations > xyz > Choose a Start Connection"
4. I'm taken back to the main/create integration screen, but any attempt to create another integration leads to a blank screen.  Logging back in returns things to normal.

**Comment by aileenc** [comment]
Is this easy fix for CR2?

**Comment by gashcrumb** [comment]
There's two bits exposed here, the editor state gets messed up and can't be recovered, and we create an invalid link when the user changes the name.  I think the latter should be simple enough to suppress, I'm not sure on the former.

The main question is, does this bug block the release?  You can work around it by refreshing the app.

**Comment by mastepan** [comment]
1.6.1-20181206
