### ISSUE TITLE
PF4 page mockups -Mapping Details Page

### ISSUE THREAD

**Issue by dongniwang** [syndesisio/syndesis#4015]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Create page mockups using PF4 elements. 
1. Integration details page (start with this page first) 
2. Create connection workflow (future sprint) 

See UX design for integration details page. 
- [Details tab](https://github.com/syndesisio/syndesis/blob/master/ux/designs/integration_details/integration_details_page.md)
- [Activity tab](https://github.com/syndesisio/syndesis/blob/master/ux/designs/integrationactivity/integrationactivity.md)

## Screenshot

Integration details page
<img width="1436" alt="screen shot 2018-11-01 at 4 54 31 pm" src="https://user-images.githubusercontent.com/24943812/47879392-d92b7f80-ddf6-11e8-941a-3c1c8b3bddd5.png">

Integration details page - Activity tab 
<img width="1439" alt="screen shot 2018-11-01 at 4 55 53 pm" src="https://user-images.githubusercontent.com/24943812/47879459-0841f100-ddf7-11e8-8955-e6eb3cc89611.png">

<img width="1436" alt="screen shot 2018-11-01 at 4 56 21 pm" src="https://user-images.githubusercontent.com/24943812/47879486-15f77680-ddf7-11e8-918f-8923d8150f5a.png">

Integration details page - Metrics tab 

<img width="1435" alt="screen shot 2018-11-01 at 4 56 46 pm" src="https://user-images.githubusercontent.com/24943812/47879532-37586280-ddf7-11e8-9d89-6e9cccfa7270.png">

@deernano @nding-anges - Please let me know if you need any other information. Thanks!

**Comment by deernano** [comment]
@dongniwang @amysueg 
Here is the integration details page mockup
https://redhat.invisionapp.com/share/4MP3ULPN9DG#/331249197_Integration-Details

Please review it, thank you~

**Comment by amysueg** [comment]
Closing for now. Will open new issues when we are ready.
