### ISSUE TITLE
Settings page - input fields not updated on change

### ISSUE THREAD

**Issue by jstastny-cz** [syndesisio/syndesis#4017]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

The Forms in Settings page (OAuth Application Management) don't reflect the changes made. The contents of the changed fields of a form are not reflected immediately in the form itself. There are two scenarios:
1. When an empty form is filled, and saved, after collapsing and reopening the entry the values are gone. When user navigates Home and back to Settings, then values are there showed properly.
2. When a filled in form is removed, after confirming the Delete warning dialog, and expanding the deleted entry again, the values are still in the input fields. Again when I after removing navigate to Home and back to Settings the fields are in sync.

## Expected behavior

The changes submitted should be immediately reflected in the form's contents.

**Comment by zregvart** [comment]
We had a user recently report this in #4046, perhaps we should increase the priority on this. Any thoughts @gashcrumb @paoloantinori?

**Comment by christophd** [comment]
#4096 is slightly different though as it addresses an empty form submit where this issue here claims the saved registration values to disappear from the form fields after submit. I ran into both scenarios recently so I can see the difference.

I think we can keep #4096 as duplicate but keep an eye on fixing all mentioned scenarios with this issue.

**Comment by gashcrumb** [comment]
I'm sure we'll have to get another 1.5.x built, so this would be a good candidate to take care of, though I wouldn't consider this an issue that should block the release either.

**Comment by gashcrumb** [comment]
Lemme see if I can get this and #4046 taken care of today.

**Comment by mastepan** [comment]
Fix verified on 1.6.1-20181206
