### ISSUE TITLE
Reduce memory footprint for integrations

### ISSUE THREAD

**Issue by jcordes73** [syndesisio/syndesis#4019]
## This is a...

<pre><code>
[ X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
I have observed that even simple integrations lead to pods that consume around 350 mb of memory, which IMO is too much. In my case I have created a timer with a log step and nothing else.

**Comment by heiko-braun** [comment]
If we talk a about page sizes, rather than heap, this seems to be normal for pods running JVM‘s
