### ISSUE TITLE
Re-enable release of Docker images to Dockerhub

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis#402]
After switch to monorepo there wasn't any `latest` release from master. The version published to Dockerhub is 6 days old.

This is a tracking issue to indicate when the related CI issues are fixed.

Cc @iocanel should we re-enable Circle CI deploy meanwhile?

**Comment by iocanel** [comment]
Sure

**Comment by dsimansk** [comment]
This was done a while back, closing the issue.
