### ISSUE TITLE
Connection Details - disabled Validate button for OAuth connections

### ISSUE THREAD

**Issue by jstastny-cz** [syndesisio/syndesis#4021]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

After creating a OAuth based connection (Gmail, Google Calendar, Twitter,...) and opening the connection details page, the 'Validate' button is not clickable.

## Expected behavior

The button should be enabled.

## Screenshot

![screenshot from 2018-11-05 11-32-12](https://user-images.githubusercontent.com/11939909/47992974-a206e800-e0ee-11e8-9eab-26754ee7e356.png)

**Comment by asmigala** [comment]
This issue is still present in 1.6.4, reopening

**Comment by TovaCohen** [comment]
I'm working on a doc update that is related to this. See [https://github.com/syndesisio/syndesis/issues/5325](5325) and [https://issues.jboss.org/browse/FUSEDOC-3172](FUSEDOC-3172). 
I'm adding this note to the doc for connecting to Google applications: 

> You must create a new Google client application for Fuse Online. The credentials that Google provides for a new client application contain a token for refreshing expired access tokens. This refresh token is available only the first time that a client application uses the credentials. In Fuse Online, connections to Gmail, Google Calendar, and Google Sheets can all use the same Google client ID and Google client secret. If they do, the refresh token is available to all connections to Google applications. When you view connection details in the Fuse Online user interface, do not click the Validate button. Validation is a second use of the credentials and the refresh token is no longer part of the client credentials. You can, however, re-connect to Google applications.

In this situation, the inactive Validate button is a good thing. It prevents the user from losing connectivity to Google. So for connections to Google applications, perhaps it would be better to keep the button inactive, or not show it at all, or if the button becomes active, add text that warns "Don't Do This!".

**Comment by zregvart** [comment]
I'm not sure about loosing connectivity to Google applications, that should not happen when using validation extension, it's the same code that's invoked when connection is initially created and validated on the new connection wizard, am I right @oscerd and @christophd?

@syndesisio/ui-api, @paoloantinori any chance we can fix this for the next release?

**Comment by riccardo-forina** [comment]
This is fixed in the React UI.

**Comment by tplevko** [comment]
Verified, this is no longer an issue - closing.
