### ISSUE TITLE
PF4 navigation mockups

### ISSUE THREAD

**Issue by amysueg** [syndesisio/syndesis#4027]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
Related to #4015, this is a request for a mockup of the major Navigation elements of the interface, using Patternfly4.

## Expected behavior
The navigation for products that are part of the Integration Product should be familiar to the users of any of the products and they should use consistent PF4 UI elements. The focus should be Masthead, Vertical Nav, Tabs within Vertical Nav, and Breadcrumbs. 

## Screenshot
Sample screen shot here:

![image](https://user-images.githubusercontent.com/31700119/48013955-9669f000-e0f3-11e8-9f8c-722fc698366e.png)

**Comment by deernano** [comment]
Hi, @amysueg @dongniwang  
This is Navigation look in PF4
![syndesis-nav 2x](https://user-images.githubusercontent.com/5396309/48191093-38e9d380-e37f-11e8-9c18-34fe7ebed6a2.png)

**Comment by amysueg** [comment]
Thank you @deernano - this looks good.

@dongniwang Do you think that @deernano should take the IVP navigation next as part of this exploration? I realize that IVP is a custom component, but I would be curious to see how it stands along-side other PF4 page elements.

**Comment by zregvart** [comment]
I wish we'd explore other options than IVP. I feel that IVP introduces the need for modes: by which I mean it forces the user to switch between editing configuration of a step/connection and modifying the integration flow. Also to provide more information or to access more options the user needs to expand the IVP on occasions.

I think a better approach would be to have a single flow with all the information and all the configuration options present. Similar to how [OSX Automator](https://macosxautomation.com/automator/) has it.

This approach, I think, would clear up room for other interaction areas on the screen: OSX Automator has a pallet of available actions, we might have the need to add more inline context information -- such as last activity information for a particular action.

**Comment by amysueg** [comment]
Closing for now. Will open a new issue for PF4 designs as we move forward.

@dongniwang
