### ISSUE TITLE
Incorrect credentials during connector creation lets you create an active connection

### ISSUE THREAD

**Issue by snandakumar87** [syndesisio/syndesis#4030]
When creating a connector, lets say for gmail/ftp/amazon s3, validate does allow for validating if the creds can establish the connection succesfully, wouldnt it make more sense to prompt that the connection string isnt right even if the validate was not explicitly tested. Even an informational string at this stage could avoid a breaking integration.

![image](https://user-images.githubusercontent.com/39506194/48024813-924bcb80-e10f-11e8-8f4b-c42ba0e4ab40.png)
I probably understand the intent behind this, that we allow for cases when the external system is actually offline/down. But, accounting for it during creation can help in the creation of a broken integration.

**Comment by gaughan** [comment]
Discuss fefature vs bug

**Comment by gashcrumb** [comment]
I believe this was a conscious decision *not* to require validation in order to create the connection.

**Comment by gashcrumb** [comment]
That being said a warning would be a good feature, it would probably require us to spend more time building out the form validation capabilities in the app in general.

**Comment by gaughan** [comment]
Yea a feature enhancement to warn the user would be great.

**Comment by dongniwang** [comment]
Checking in again to see if this is required for 7.3? 

cc: @gaughan @heiko-braun @gashcrumb @amysueg

**Comment by heiko-braun** [comment]
@dongniwang Too late in the cycle, but worth exploring when move to react. @gashcrumb What do you think?

**Comment by gashcrumb** [comment]
@heiko-braun yeah, too late for 7.3 but totally a candidate to improve in the react impl.
