### ISSUE TITLE
Clicking on the padding of a list item won't be processed

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#4036]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

If I don't click on padding gutter of a list item (say in the integration list), then it won't be registered as a click on that list item (say open integration details page). And that's a bit confusing since on hover it does activate.

## Expected behavior

When there is a hover effect the click should also be registered.

## Screenshot

![peek 2018-11-06 13-17](https://user-images.githubusercontent.com/1306050/48063956-cb934280-e1c6-11e8-8ad7-cc1c3543efcd.gif)

## Tasks involved / Steps to Reproduce

1. Try clicking on a list item around the edge of the item

**Comment by riccardo-forina** [comment]
I think we inherit the behavior from pf-ng. We don’t specify how the list
item should be rendered, just what should happen when clicking on the list
item [1].

I guess the click assumption was that since a list item can (should?) have
action buttons, clicking on the item itself wasn’t expected to happen very
often.

Perhaps we should add a button for the primary action, that would be “Show
details” or something like that.

Else we have to sync with the PF guys to see if this can be changed
upstream.

Il giorno mar 6 nov 2018 alle 18:28 James Lau <notifications@github.com> ha
scritto:

**Comment by jameslau** [comment]
Thanks for the feedback @riccardo-forina. This maybe a simple js issue where something is bubbling up the event.

**Comment by jameslau** [comment]
Based on the Syndesis/Fuse Online UX discussion this morning...

- @seanforyou23 suggested to "spot patch" this issue for Syndesis and then open up a ticketed issue for PF-NG. 
- @mcoker states that this might be a larger change that isn't probably worth time as of right now.
- @dongniwang suggested an evaluation on the level of effort needed for this ticket and see if we can actually do this ticket right now or if it requires a bit of overhaul within PF-NG team.

**Comment by mastepan** [comment]
@jameslau what the fix has changed please? I can't see any difference as a user. Thanks.

**Comment by jameslau** [comment]
Hi @mastepan, naturally, you can't click on padding because that's not actually the main div container field. There is away if you us JavaScript, but this would be considered a hack.

**Comment by mastepan** [comment]
@jameslau can you push this to be fixed in patternfly or elsewhere the bug is please? Is there a way?
I've verified the current fix but It is not enough from user's perspective. It's still unexpected that only small part in the middle of the bar is clickable.

**Comment by jameslau** [comment]
Hi @dongniwang and @mcoker, can we get some direction on this issue for @mastepan? Thanks!

**Comment by mastepan** [comment]
@dongniwang, @mcoker is there any feasible way how to make the whole list row clickable?

**Comment by mcoker** [comment]
We decided it isn't something we can change the behavior of upstream, so changing the pointer to indicate the clickable area is best solution for the moment. This should be resolved when we move to PF4.

**Comment by mastepan** [comment]
fix verified on 1.6.1-20190111
