### ISSUE TITLE
API Provider ignores 204 as default status code

### ISSUE THREAD

**Issue by asmigala** [syndesisio/syndesis#4040]
See also **https://issues.jboss.org/browse/ENTESB-11455**

## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When implementing an API Provider operation that has status code set to 204 (such as the Delete task operation in the todo API), the Provided API Return Path defaults to 200. This does not seem to happen with other status codes (e.g. the Create task operation correctly sets the status code to 201).

A simple workaround is to open the finish step and select 204 as the status code.

**Comment by zregvart** [comment]
Relates to #3780

**Comment by dongniwang** [comment]
Just wanted to add a quick comment here since I have a participant from the feedback gathering session ran into this issue as well. 

cc: @zregvart @gaughan

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11455**
