### ISSUE TITLE
Google Calendar finish connection should not offer Get Specific Event action

### ISSUE THREAD

**Issue by TovaCohen** [syndesisio/syndesis#4041]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When I add a Google Calendar connection as the finish connection in an integration, I can select the "Get a Specific Event" action. However, there is no use case, no benefit, for obtaining a specific event at the end of the integration.  Gary tells me: "Obtaining an event makes no sense at the end ..."

When adding a Google Calendar connection as the finish connection, the "Get a Specific Event" action should not be displayed.

**Comment by oscerd** [comment]
This is wrong. The get event action is a to pattern in Camel and there are situation in which it makes sense as I explained in the email.

**Comment by oscerd** [comment]
For me this is not a bug and it can be closed

**Comment by TovaCohen** [comment]
@gaughan ?
Technically, it might make sense. But from a citizen integrator POV, why would they do this?

**Comment by oscerd** [comment]
I can remove the action, it's not a problem. But suppose that one day someone wants to run an integration just one time (this is something missing, but in the timer connector we may add a count option to be able to fire just one time), for example because he needs to modify just one event in the calendar: to be able to do that, he cannot use the get events action, because he doesn't know when the event he needs to modify will be consumed (and the query won't assure you'll get exactly one event).. So the only way for him to update or modify a specific event is throuh the getEvent action and by specifying a single eventId

**Comment by TovaCohen** [comment]
Adding @gaughan since I think this is his decision. 
Suppose I get a specific event as the finish connection in an integration.
What do I have to do to obtain the details for that event so that I can then do something with it?

**Comment by oscerd** [comment]
You can map the details to an event in a subsequent update event action.
you may have timer->get specific event-> datamapping -> update event -> datamapping -> slack
The to pattern doesn't mean you can't create a chain of to action.

**Comment by TovaCohen** [comment]
Sorry, I must be misunderstanding or I'm not being clear. I'm only considering an integration that gets a specific event in the finish connection, which is a connection to Google Calendar. If an integration gets a specific event from a Google Calendar in its finish connection, how can I map the details of that event in order to update that event?

**Comment by oscerd** [comment]
If you finish an integration with a get specific event action, you can't update the event. The aim of the get specific event action is to get an event, map what you need and update it through a update event action: if you want to update a single and specific event, this is the only way (if we consider only google calendar connector). This was explained and there was an agreement here: https://github.com/syndesisio/syndesis/issues/3454#issuecomment-422408892

**Comment by gaughan** [comment]
@TovaCohen I totally understand where you are coming from, having functionality exposed in a context that doesnt immediatly make sense is hard to explain. @oscerd we could remove this when the connector is only in the finish position correct?
The danger in doing so is that in the future we want to allow the user to describe and partial unfinished intergration. This would be messy as the finish connection would (for only a moment)be a finish connector. Removing functionality would defeat this inititive (potentially)

**Comment by oscerd** [comment]
To me changing to a from pattern it's not needed. But if you want I can do it

**Comment by TovaCohen** [comment]
Let's leave the connector as it is. Can I add this to the user doc:
NOTE: In this release, while obtaining a specific event in integration's finish connection is supported, it is not particularly useful. This is expected to change in a future release. 

If we don't have something like that in the doc, I would expect someone is going to ask the same questions that I am.

**Comment by gaughan** [comment]
sounds good

**Comment by TovaCohen** [comment]
While this feature is not useful now, it might be useful in the future. So it stays and the note in the previous comment gets added to the user doc.
