### ISSUE TITLE
OAuth Application Management shows successful registration message even if nothing is entered

### ISSUE THREAD

**Issue by snandakumar87** [syndesisio/syndesis#4046]
## The problem
when Ok is clicked without entering the Client Id/Secret, we still see the registration successful message, when in effect we havent done anything at all.

## Screenshot
![image](https://user-images.githubusercontent.com/39506194/48136762-76ab0700-e26e-11e8-9f41-fc603566fc4f.png)

**Comment by zregvart** [comment]
Thanks for reporting this @snandakumar87. I think this is a duplicate of #4017.

**Comment by gashcrumb** [comment]
Really when the form is empty the "Save" button should probably be disabled to prevent submitting empty values.

**Comment by mastepan** [comment]
The fix verified on 1.6.1-20181210
