### ISSUE TITLE
Import tech extension text on updating

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#405]
Just implementing this page -> https://github.com/syndesisio/syndesis/blob/master/ux/designs/technical_extensions/tech_ext.md#choose-file

and of course noticed the text in better detail.  Do we need to go into such detail about what should be an edge case, i.e. updating a technical extension?  Would it be better to handle this case either by just allowing the update or deferring this text:

> To update a technical extension in the breadcrumbs above, click Technical Extensions and in the list of technical extensions, click Update for the appropriate technical extension.

as a response message if we don't support using this particular page flow to update?  Personally I think we should just allow updating, as I suspect we'd have the metadata available to do so rather than make the user manually navigate back to the list and pick the extension they want to update.

@lburgazzoli thoughts?

Gonna stick with the current text for now but wanted to raise the above.

**Comment by lburgazzoli** [comment]
@gashcrumb 

on upload the backend checks if there is any active extension with the given id and in case there is one, it raise an error. I think the UI can react to such error by going to the extension update page.

Make sense ?

**Comment by gashcrumb** [comment]
But what's the difference between updating and importing really?  I guess I don't understand why we have this distinction really.  From the user's perspective they're just uploading a file.  There's no difference in the flow between either.  And when you update a tech extension that doesn't have an impact on *running* integrations, does it?  Other than we should be flagging them as needing a re-deploy.  It just feels needlessly clunky to me :-)

**Comment by gashcrumb** [comment]
Also an option is that at the review step we notify the user that the file they've uploaded will *update* an existing technical extension.  I honestly see no reason to have a totally separate update page flow the more I think about it.  And it's not just because I don't want to implement it either, honest!  :-)

**Comment by lburgazzoli** [comment]
I agree, however I want to keep the error on backend side (you can use it to warn the user)

@dongniwang can we update the design with Stan's suggestion ?

**Comment by dongniwang** [comment]
@gashcrumb @lburgazzoli 

Thanks for raising the issue! Just wanted to make sure I understand the problem and what's been suggested here:

![image](https://user-images.githubusercontent.com/24943812/33278361-4fdbe816-d369-11e7-979d-fe414e6ad81c.png)

So for the above page, we're saying that we **_DO NOT_** need the "Update" action buttons anymore. If users want to update an existing tech extension, they just need to use the primary blue action button for importing. 

![image](https://user-images.githubusercontent.com/24943812/33281307-bbe9bf8e-d372-11e7-8baf-a7765a767e77.png)
What about the "update" button on the tech extension details page? If we want to remove that, the only way to import would be from the list view? Or we can change "update" to "Import" on this page. 

Is the backend able to recognize the user action - updating an existing tech extension? If yes, we can display an inline notification at the review step like what @gashcrumb suggested below. 
> Also an option is that at the review step we notify the user that the file they've uploaded will update an existing technical extension.

**Comment by gashcrumb** [comment]
Yeah, I'd have the `Update` button on the detail view just go to the existing import page.  I can pass along some context too so the import page can be a bit smarter and update the text accordingly.

**Comment by dongniwang** [comment]
Awesome! I'll update the design accordingly. Thank you! @gashcrumb

**Comment by dongniwang** [comment]
Now I'm working on updating the design, I feel like we need to either keep both update buttons or just remove them both. Having the update button on the detail view only would probably confuse users. 

I'm thinking we can just keep both update buttons and make them go to the same import process. Just need to make sure the text/page title/instruction on the import page reflect the user selection. What do you think? @gashcrumb @lburgazzoli

**Comment by dongniwang** [comment]
Here's a solution for making the same import process usable for both Import and Update. Users need to make a selection upfront to let us know what they want to do. 

![screen shot 2017-11-27 at 2 47 34 pm](https://user-images.githubusercontent.com/24943812/33285986-0622021e-d382-11e7-9f84-d476f3e9cd64.png)

**Comment by gashcrumb** [comment]
No, I don't think that'd work :-)

Maybe we should just keep the update flow as-is, I'll change the current import page so it can handle updating too, and we'll keep the update buttons on the list.  Sound better?

**Comment by dongniwang** [comment]
@gashcrumb yeah, maybe keeping the update flow and the buttons is the better option for now. I think the page layouts and the flows are pretty much the same for import and update. As long as the page can handle both situations then we should be good. Do we still need any updates on the design?

**Comment by gashcrumb** [comment]
With that I don't think so :-)

**Comment by dongniwang** [comment]
Closing the issue for now. We can open another issue if needed. Thank you!
