### ISSUE TITLE
Missing images after integration creation

### ISSUE THREAD

**Issue by honghuac** [syndesisio/syndesis#4054]
## This is a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
</code></pre>

## The problem
The console of Fuse Online appears as such, without images, after an integration was created.

![huh](https://user-images.githubusercontent.com/8625482/48188169-12746a00-e378-11e8-9469-9b27f2276bc9.png)

![online](https://user-images.githubusercontent.com/8625482/48188309-75fe9780-e378-11e8-9295-1b571d11dad1.png)

![qn](https://user-images.githubusercontent.com/8625482/48189605-8cf2b900-e37b-11e8-95dd-637bdee1e043.png)

## Expected behavior
Images should be present on the console.

## Request and Response Data
An integration involving a webhook and a log connector was created, that led to this error.

Seems to be a repeat of this issue: https://github.com/syndesisio/syndesis/issues/2973

**Comment by zregvart** [comment]
I don't think this is the images looks to me like some labels are missing. @honghuac can you provide `/assets/dictionary/en-GB.json` from your environment and double check with browser cache cleared or [force-reload](https://en.wikipedia.org/wiki/Wikipedia:Bypass_your_cache#Bypassing_cache).

@paoloantinori @gashcrumb this could be a `p0/bug` if it's not local.

**Comment by honghuac** [comment]
@zregvart Sure, here is the [en-GB.json](https://gist.github.com/honghuac/1fb4e10130a9e8c05f78aec8f31d5666) from my browser. I am using Firefox 60.1.0esr (64 bit)

**Comment by honghuac** [comment]
![pbr](https://user-images.githubusercontent.com/8625482/48190407-94b35d00-e37d-11e8-8456-c9bbd9c0bbaa.png)

Works with private browsing on Firefox.

**Comment by zregvart** [comment]
Looks like that `en-GB.json` is missing a number of entries. Just to make sure, and it's somewhat easier to do it this way than to track down the image containing `en-GB.json` can you open the `https://$SYNDESIS_HOST/assets/dictionary/en-GB.json` in the private browsing or force-reload (hit <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>R</kbd>). it from the non-private browser session.

From what I can see `Etag` header is being served and that should prevent the resource from being cached by the browser in case of resource change/

**Comment by gashcrumb** [comment]
Yeah, this seems like a matter of clearing your browser cache after updating.

This is a common gotcha and I think something we need to solve,

**Comment by zregvart** [comment]
I'm not sure how we can, seems like a browser/client configuration issue to me, we're generating `Etag` header and it should change when the underlying resource changes.

This is what I see:

```http
HTTP/1.1 200 OK
Content-Encoding: gzip
Content-Type: application/json
Date: Thu, 08 Nov 2018 10:11:02 GMT
Etag: W/"5be1a0cf-6a2b"
Gap-Auth: zregvart@cluster.local
Gap-Upstream-Address: syndesis-ui
Last-Modified: Tue, 06 Nov 2018 14:10:23 GMT
Server: nginx/1.13.4
Vary: Accept-Encoding
Transfer-Encoding: chunked
```

**Comment by gashcrumb** [comment]
Hmm, it's a weak tag, wonder if Firefox ignores it, feels like Firefox in particular caches pretty aggressively.  Do we know how this is generated, i.e. hashing the file perhaps?

**Comment by zregvart** [comment]
Looks to me like a combination of last modified timestamp and length of the file:

https://github.com/nginx/nginx/blob/774d69cf4a0ab2526422c77c0210f1f4d75f2900/src/http/ngx_http_core_module.c#L1608-L1609

https://github.com/nginx/nginx/blob/4bf4650f2f10f7bbacfe7a33da744f18951d416d/src/http/modules/ngx_http_static_module.c#L218-L219
