### ISSUE TITLE
Stop/Start integration should not result in new container

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#4056]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[*] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When I Stop and Start the same integration w/o editing it, it should not build a new container. Instead it should be able to simply spin up a new pod using the old container, same integration version, but I guess a new deployment version.

Maybe it's simply because we call the `update` and not `updateTargetState` on a Start. I think we should only call `update` if the integration was updated.

**Comment by heiko-braun** [comment]
Will be fixed with Camel-K
