### ISSUE TITLE
Update to latest Operator SDK version

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#4063]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

The operator SDK switched to controller-runtime as the backing library which substantially changed the internal structure. We should update our operator to use 0.1.1 of the operator SDK to allow further updates.

The migration path is described in https://github.com/operator-framework/operator-sdk/blob/master/doc/migration/v0.1.0-migration-guide.md

**Comment by rhuss** [comment]
There is currently a discussion to which version of the Operator SDK we can upgrade as the operator SDK switched their dependency on the kubernetes client to 1.12 (but OpenShift 3.11 uses K8s 1.11).

See https://groups.google.com/d/msg/operator-framework/1CFIsYwrgj0/imwDSaKeDAAJ for the discussion thread just started.

**Comment by heiko-braun** [comment]
@rhuss Can this be closed?

**Comment by rhuss** [comment]
Yes.
