### ISSUE TITLE
Upgrade: Missing migration script for s2i image

### ISSUE THREAD

**Issue by avano** [syndesisio/syndesis#4064]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Since #3464 is not done for 7.2, we need a migration script to bump the s2i imagestream tag to "1.5" like it was done here for 7.1: https://github.com/syndesisio/syndesis/blob/master/tools/upgrade/migration/resource/1.1/03_server_config_map_upgrade.sh#L22

It should be in "1.2" folder

**Comment by heiko-braun** [comment]
@rhuss this needs to happen early next week (12.11) and be coordinated with @janstey 's team.

**Comment by rhuss** [comment]
@zregvart as you did the previous migration, could you please take this over for 7.2, too ? would be awesome.
