### ISSUE TITLE
As an expert integrator, create a messaging connection

### ISSUE THREAD

**Issue by kcbabo** [syndesisio/syndesis#407]
As an expert integrator, I need to create connections to messaging services to support message-oriented interactions in integration flows.

When creating a connection, I will provide the following configuration parameters:
- Broker URL
- Username (optional)
- Password (optional)

Once a connection is created, I should be able to validate connection configuration by verifying the connection.

**Comment by mmelko** [comment]
What JMS providers are we planning to support? Or we will support only usage with amq openshift image?

**Comment by kcbabo** [comment]
AMQ initially, but other providers supported by Fuse eventually.  That will require specific connectors, so will follow up with a separate user story.

**Comment by mmelko** [comment]
Thanks. So I guess is ok if we use broker (no SSL) from amq 6.3 openshift template.At least for TP3.

**Comment by kcbabo** [comment]
I would prefer to use no SSL and SSL broker if possible.

**Comment by dsimansk** [comment]
@kcbabo my main concern here is that for SSL broker to be used. We would require from users to provide keystore and truststore as a Secret. See [the docs](https://access.redhat.com/documentation/en-us/red_hat_jboss_a-mq/6.3/html/red_hat_jboss_a-mq_for_openshift/get_started#configuring_ssl) about SSL configuration. 
To achieve correct SSL config user needs to generate those and then configure them for the SSL-flavoured template. And finally we need to either provide another field to specify secret name of fetch the default one. 
Is it something we want to tackle for TP3? Imho if we would stick with non-SSL template broker URL is simplified to `failover://tcp://{SERVICE_NAME}:{SERVICE_PORT}` + username & password with any additional fiddling with keystores and Secrets. Wdyt?

**Comment by kcbabo** [comment]
@dsimansk - the secret config is for the broker and not the client connection, right?

**Comment by dhirajsb** [comment]
@kcbabo can we close this user story now that we have A-MQ and AMQP connectors?

**Comment by kcbabo** [comment]
Yessir
