### ISSUE TITLE
Settings page: OAuth app rows collapse when you click "Remove". Review button/modal wording.

### ISSUE THREAD

**Issue by mcoker** [syndesisio/syndesis#4070]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
@nding-anges from https://docs.google.com/document/d/1EfIZtY4gc6b3S41unIQLuwGd4oD5V1qlkAoI9zACuFM/edit#heading=h.jfmx74dcupnb

#### Settings Page - remove behavior
When OAuth list rows are expanded, if you click "remove" to remove the credentials for an app, that list row collapses and the others are left open. The row should probably be left open. What should happen after you click "delete" in the modal? Should the row collapse then? Should it be left open and the input fields are emptied?

Also, the words "Remove" in the button and "Delete" in the modal don't match, and are kind of confusing since those words imply that you are removing/deleting the row instead of just clearing the credentials.

cc @syndesisio/uxd @TovaCohen

**Comment by TovaCohen** [comment]
Sorry to be so late checking in with you about this. Do you need any input from me?
