### ISSUE TITLE
Use Patternfly for inline, toast, and other notifications

### ISSUE THREAD

**Issue by amysueg** [syndesisio/syndesis#408]
For Reference:
http://www.patternfly.org/pattern-library/communication/inline-notifications/
http://www.patternfly.org/pattern-library/communication/toast-notifications/

@seanforyou23 - Adding this as a place to track and update work, please update with relevant details as you like.

**Comment by seanforyou23** [comment]
After speaking more with Stan, it seems we're already in step with the PF way of launching/handling notifications in syndesis (win!) - I did find one enhancement we've made that probably makes sense to contribute back to PF.

> would be cool if that the getNotificationsObservable() that we added in https://github.com/syndesisio/syndesis-ui/blob/master/src/app/common/ui-patternfly/notification-service.ts was part of patternfly-ng/notification-service

I will work with the PF team to incorporate this enhancement back into patternfly-ng, making any generalizations that become necessary.

**Comment by amysueg** [comment]
Can we close this issue then @seanforyou23 ?

**Comment by seanforyou23** [comment]
Yes we can!
