### ISSUE TITLE
Integration Summary Page - External URL Copy feature does not work

### ISSUE THREAD

**Issue by honghuac** [syndesisio/syndesis#4080]
## This is a...

<pre><code>
[ ] Feature request
[x ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
On the *Integration Summary Page* - the *External URL Copy* feature does not work. The URL does not get copied into the clipboard, as it should.

## Screenshot
![webhook-int-summary-url](https://user-images.githubusercontent.com/8625482/48356927-5944c580-e6d2-11e8-90bf-f75492b577e8.png)

## Tasks involved / Steps to Reproduce

1. Open any integration previously created
2. Attempt to copy the external URL of the integration

**Comment by zregvart** [comment]
@honghuac can you specify your browser/version I had this happen on Firefox (#3696) and we determined it was only on my end (still doesn't work for me though). Works fine on Chrome.

**Comment by dongniwang** [comment]
FYI @seanforyou23 - Can you take a look at this as well if you have time? Thank you!
