### ISSUE TITLE
Activity log is confusing

### ISSUE THREAD

**Issue by mkralik3** [syndesisio/syndesis#4087]
<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
I have an integration SLACK to DB,
![image](https://user-images.githubusercontent.com/16251792/48484935-cdd54c80-e817-11e8-9b31-9c70b5e13884.png)
When I send a message which goes through basic filter and advance filter, these steps do not appear in the activity log.
![image](https://user-images.githubusercontent.com/16251792/48485881-4c32ee00-e81a-11e8-98fd-16ea1f40593e.png)
But When I have a message which does not meet the condition in the Basic filter or Advance filter, this step appears in the activity log with **no output**
Message doesn't meet the condition in the Basic filter:
![image](https://user-images.githubusercontent.com/16251792/48485571-86e85680-e819-11e8-9a33-921cb3ee8ebe.png)
Message doesn't meet the condition in the Advance filter:
![image](https://user-images.githubusercontent.com/16251792/48485998-91efb680-e81a-11e8-84f7-534e7dfb30bd.png)

I know that when the message meets the condition, then is not necessary shows anything in the activity log.
However, In my point of view, this is very confusing for the basic user. I would expect that this step (Advanced filter and Basic filter) will be in the log always and shows whether it was true or not.

In my point of view, showing three times Invoke SQL with No output is really confusing for the user too.
![image](https://user-images.githubusercontent.com/16251792/48485881-4c32ee00-e81a-11e8-98fd-16ea1f40593e.png)

And I don't know what means the name of the activity. E.g. for the image above it is **212ort3pmt2** 
I noticed that the month ago, there was a date.
e.g.
![image](https://user-images.githubusercontent.com/35576/47083564-4513c280-d211-11e8-94a8-5cc1f813b14e.png)

Maybe this is similar issue https://github.com/syndesisio/syndesis/issues/3880

**Comment by KurtStam** [comment]
IMHO it's more then confusing 3880

**Comment by heiko-braun** [comment]
@dongniwang making this a UX task for now.

**Comment by dongniwang** [comment]
Checking again if this is something we want for 7.3? If yes, per [my comment above](https://github.com/syndesisio/syndesis/issues/4087#issuecomment-439196654), can someone from Engineering please work with me to help me understand what information is available to show? Thanks! 

cc: @heiko-braun @paoloantinori @gaughan @amysueg

**Comment by heiko-braun** [comment]
@dongniwang I think this is out of scope for 7.3. I'll move it to 7.x for now.

**Comment by mkralik3** [comment]
Now, the log contains all steps ( https://github.com/syndesisio/syndesis/issues/4181 )
For integration similar as in the first comment
![image](https://user-images.githubusercontent.com/16251792/58430223-cafdc300-80a8-11e9-9575-bc18f34258ff.png)
the log is correct:
![image](https://user-images.githubusercontent.com/16251792/58430184-a0ac0580-80a8-11e9-8d75-8582552b88fa.png)
However, still, when Basic Filter or Advanced Filter doesn't pass, the output is "No output". 
From the user point of view, it will be nice to see what data doesn't meet the filter.
![image](https://user-images.githubusercontent.com/16251792/58430298-131ce580-80a9-11e9-9465-0729e4631aeb.png)

**Comment by christophd** [comment]
> From the user point of view, it will be nice to see what data doesn't meet the filter.

I agree with that. Can we open another issue for that particular feature? The code freeze for features in 7.4 is already gone and I would like to see this issue fixed with 7.4

So if the log is correct at the moment I would like to close this one and open another issue for subsequent feature requests.

**Comment by mkralik3** [comment]
Agree. I have created an enhancement request: https://github.com/syndesisio/syndesis/issues/5479
