### ISSUE TITLE
UXD Research: Use Patternfly for form elements

### ISSUE THREAD

**Issue by amysueg** [syndesisio/syndesis#409]
Reference: See Forms and Controls section: http://www.patternfly.org/pattern-library/

@seanforyou23 Added this issue to document and track your work, update as needed. Thanks.

**Comment by amysueg** [comment]
@rhuss I was mistaken about this work. After talking with Michael, I moved this out of Sprint 21 to the backlog. There is going to have to be some research and analysis as to what needs to be done to use PatternflyNG for all the elements of our forms, and that will take some time and is overall a lower priority than the existing new UX work. I'm removing the "target/tp3" tag as well until we know more.

**Comment by seanforyou23** [comment]
After speaking with @gashcrumb it seems that we are already using PF form elements and best practices. Of course there are the forms which are driven by ng-dynamic-forms, which have some intrinsic limitations of the markup that's generated, but I don't believe these go against any of the PF style guides.

I believe this issue can be closed, feel free to reopen if I've missed anything.
