### ISSUE TITLE
Tooltips are off-center

### ISSUE THREAD

**Issue by mcoker** [syndesisio/syndesis#4094]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
Our tooltip arrow is off center relative to the thing it points to.

## Expected behavior
The arrow should be centered vertically or horizontally depending on the tooltip position.

## Screenshot
<img width="530" alt="screen shot 2018-11-15 at 8 35 52 am" src="https://user-images.githubusercontent.com/35148959/48559644-9ca95a80-e8b1-11e8-8f3e-10cc28f5f1e8.png">
<img width="341" alt="screen shot 2018-11-15 at 8 38 20 am" src="https://user-images.githubusercontent.com/35148959/48559777-e2662300-e8b1-11e8-8272-4e32bc6d7cf6.png">

## Tasks involved / Steps to Reproduce

1. You can see the first screenshot when creating an integration, or anywhere you see the info icon beside a form field label.
2. The second is on the Settings page, but you might be able to find other places with top/bottom tooltip placement.

**Comment by mastepan** [comment]
fix verified on 1.6.1-20190111
