### ISSUE TITLE
Some Tooltips on Setting page are missing

### ISSUE THREAD

**Issue by nding-anges** [syndesisio/syndesis#4096]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
On Setting page, the tooltips of 'Client ID' and 'Client Secret, etc...'on Salesforce and SAP Concur  are missing.  

<img width="1278" alt="2018-11-16 3 04 20" src="https://user-images.githubusercontent.com/34368385/48603375-2724b380-e9b1-11e8-9bcf-dc8e0a22e791.png">

<img width="1297" alt="2018-11-16 3 09 07" src="https://user-images.githubusercontent.com/34368385/48603489-8b477780-e9b1-11e8-8f6d-923fd4cb9303.png">

**Comment by nding-anges** [comment]
@TovaCohen Please help us to review the tooltips. Thanks~

**Comment by dongniwang** [comment]
@zregvart @gashcrumb - Do you have any idea as to why some of the form fields have the "i" icon right next to the field labels while some of them have help text below the form fields?

**Comment by gashcrumb** [comment]
Yeah, some of these forms are configured to use `labelHint` (which makes the 'i' icon show up) vs `description` in the properties object, which drives the text *under* the input field.  We could probably stand to align all of these to one, though the `labelHint` means that you get a hover tooltip which works terribly when there's lots of text, like some of those fields under the Salesforce oauth connector etc.

**Comment by TovaCohen** [comment]
Apologies for not responding. I've been out sick the last week, and will be out this week. But I will look at this as soon as I can after Thanksgiving.  Can someone point me to a file that contains the tooltips that need editing?

**Comment by TovaCohen** [comment]
And I forgot to specify this issue number in these pull requests: 
Twitter: https://github.com/syndesisio/syndesis/pull/4358 
Salesforce: https://github.com/syndesisio/syndesis/pull/4357
