### ISSUE TITLE
Remove action should be hide in collapse row and wording of 'Remove' button need to be improved 

### ISSUE THREAD

**Issue by nding-anges** [syndesisio/syndesis#4097]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

In the list view of Setting page, it seems that ‘Remove’ button is used to delete the current row at the first glance. However, clicking ‘Remove’ button will only clear all input and refresh to null in detail page. Remove button is looked quite simlar with other buttons, it might have a misoperation.
<img width="1303" alt="2018-10-24 2 07 52" src="https://user-images.githubusercontent.com/34368385/48604409-c39c8500-e9b4-11e8-9f41-dea0900f7985.png">

## Expected behavior

- 'Remove’ button is better to hide in collapse row  and then show only in extended row. 
-  Change to another wording (TBD) and redesign ‘Remove button, ex: icon+text link style.
 

## Screenshot

<img width="1312" alt="2018-10-24 2 03 18" src="https://user-images.githubusercontent.com/34368385/48604639-694ff400-e9b5-11e8-96aa-30253fdddf17.png">

**Comment by junezhang** [comment]
Duplicated with this issue: https://github.com/syndesisio/syndesis/issues/4070
so close it, if anything needs to update, please re-open it.
