### ISSUE TITLE
Suggest to improve 'Validate' button and make the process more smoothly

### ISSUE THREAD

**Issue by nding-anges** [syndesisio/syndesis#4098]
## This is a...

<pre><code>
[x ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

from Fuse Evaluation doc https://docs.google.com/document/d/1EfIZtY4gc6b3S41unIQLuwGd4oD5V1qlkAoI9zACuFM/edit#heading=h.jfmx74dcupnb
In Connection Detail Page
<img width="1309" alt="2018-10-23 4 33 22" src="https://user-images.githubusercontent.com/34368385/48605624-43781e80-e9b8-11e8-8825-7df13c13be29.png">

When the user clicks “edit” button to edit the form,the ‘Validate’ ,‘Cancel’ and ‘Save’ button show as below:

<img width="1316" alt="2018-10-23 4 34 14" src="https://user-images.githubusercontent.com/34368385/48605632-48d56900-e9b8-11e8-917f-468d2ec399b2.png">

Since the ‘Save’ button is the Primary button style (in blue) and the ‘Validate’ button is Secondary button style, the user will probably ignore Validate step, which is more important behavior than ‘Save’ .
 

## Expected behavior

Provide different design treatment to the “Validate” button in order to distinguish from other actions and make the process more smoothly.

**Comment by nding-anges** [comment]
Hello everyone, @dongniwang @amysueg @deernano 
I uploaded the improvement design on Invision, please have a look and feel free to leave your comments. https://redhat.invisionapp.com/share/J3P909MXTHQ#/335151221_Validate-Intro

**Comment by dongniwang** [comment]
@nding-anges - thanks for posting the design! I left some comments and please let me know if you have any questions.

**Comment by dongniwang** [comment]
@zregvart @gashcrumb - Hoping to get your feedback on the latest design for the issue. Please use the link in this [comment](https://github.com/syndesisio/syndesis/issues/4098#issuecomment-444382848). 

Do you know if we can combine the Validate and Save here? What are we validating on when the user clicks the button?
