### ISSUE TITLE
Can we inline the integrations used by an extension rather than requiring a separate call

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#410]
Otherwise implementing this page is going to be chatty between the UI and the rest API:

https://github.com/syndesisio/syndesis/blob/master/ux/designs/technical_extensions/tech_ext.md#tech-extension-list

It also complicates implementing the detail page as we have to make a second API call to fetch what integrations are used by an extension.

**Comment by gashcrumb** [comment]
Would like this to finish up #262 and #263

**Comment by lburgazzoli** [comment]
@nicolaferraro can we have additional endpoints to retrieve something like an "ExtensionDetail" which include both the extension and the list of integrations (as ResourceIdentifier) ?

**Comment by nicolaferraro** [comment]
Sure. Yes, this is needed.

**Comment by gashcrumb** [comment]
So what was the endpoint BTW?  For the detail page I wound up just fetching the integration list separately.

For the list page really all I need is the integration usage count to be part of each extension object that's returned in the array to support [this third column](https://github.com/syndesisio/syndesis-ux/blob/master/designs/technical_extensions/tech_ext.md#tech-extension-list)

**Comment by gashcrumb** [comment]
Created #474 to track this for the list view.
