### ISSUE TITLE
 API Provider: We need a Camel message header firewall

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#4102]
See also **https://issues.jboss.org/browse/ENTESB-11520**

## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
We should make Camel message headers part of the connector contract, right now we have only definitions of endpoint/component parameters. Most Camel components are influenced by Camel message headers and potentially we could leak sensitive information if we pass Camel message headers bound via incoming payload by the consumer to an outgoing message payload via producer binding.

We need to:
 1. add a white list of Camel message headers that are passed from the one connector to the following connector
 2. filter out all but white listed Camel message headers before invoking the following connector
 3. restore message headers after invoking the following connector (I think this is needed to restore activity tracking)

I guess we don't need to do this for step connectors?

cc @syndesisio/backend 

See #3865 #1915

**Comment by KurtStam** [comment]
@zregvart I see this more as a bug than a feature request. Seems like a pretty big security risk.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11520**
