### ISSUE TITLE
Add install maven mirror script

### ISSUE THREAD

**Issue by rkorytkowski** [syndesisio/syndesis#4112]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Add `syndesis minishift --maven-mirror`/`syndesis install --maven-mirror`, which will provision a nexus instance in OpenShift so that you can make use of #4109 in a very straightforward way.

**Comment by rkorytkowski** [comment]
Hi @heiko-braun, not worth doing in your opinion?

**Comment by heiko-braun** [comment]
definitely worth, but is has been fixed already in https://github.com/syndesisio/syndesis/pull/4110, no?

**Comment by rkorytkowski** [comment]
#4110 added a way to use a manually installed nexus repo. This one is about adding a way to provision a nexus repo automatically for you. It lowers the effort for devs to use #4110.

**Comment by heiko-braun** [comment]
ok, I've misread the description

**Comment by rkorytkowski** [comment]
I'm planning to work on that.

**Comment by rkorytkowski** [comment]
PR at https://github.com/syndesisio/syndesis/pull/5801
