### ISSUE TITLE
running "syndesis install" yeilds: openshift_funcs: line 102: 1: unbound variable 

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#4114]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Running `./tools/bin/syndesis install --local --dev --project syndesis` to install syndesis onto a local cluster, the tool fails with:

```
Creating project syndesis
Already on project "syndesis" on server "https://127.0.0.1:8443".
Deploying Syndesis operator
/home/gashcrumb/Source/syndesis/tools/bin/commands/util/openshift_funcs: line 102: 1: unbound variable
ERROR: Last command exited with 1
```

Changing the mentioned line to:

```
    local project="${1:-}"
```

sorts it

**Comment by gashcrumb** [comment]
Lol, that was the wrong change :-)

**Comment by avano** [comment]
looks ok now
