### ISSUE TITLE
Docker image size of s2i increases over time

### ISSUE THREAD

**Issue by christophd** [syndesisio/syndesis#4118]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

While rebuilding the syndesis-s2i Docker image during development the image size increases from build to build. 1st build gives me an image size of 1.29 GB, 2nd build 1.8 GB and so on. 

Saw that behavior both in s2i-s2i build within Minishift and locally with --docker flag.

Increasing image size is a threat to the disk space of the Minishift VM so reset of Minishift becomes mandatory at some time.

**Comment by avano** [comment]
@christophd the issue is that the maven build of s2i module produces a zip file with all the artifacts in the local repository under io/syndesis/s2i/s2i.. and when doing the s2i build again, it collects all io/syndesis/* artifacts to create the s2i zip so effectively duplicating all the artifacts :dancer: 

In my image I had:

```
[jboss@bb2ed34a3573 1.6-SNAPSHOT]$ ls -la
total 8373480
drwxrwxr-x 2 root root       4096 Jan  7 09:29 .
drwxrwxr-x 4 root root       4096 Jan  7 09:28 ..
-rw-rw-r-- 1 root root        189 Jan  7 07:41 _remote.repositories
-rw-rw-r-- 1 root root        734 Jan  7 07:41 maven-metadata-local.xml
-rw-rw-r-- 1 root root 8574409413 Jan  7 07:31 s2i-1.6-SNAPSHOT-m2.zip
-rw-rw-r-- 1 root root       8266 Dec 21 16:02 s2i-1.6-SNAPSHOT.pom
[jboss@bb2ed34a3573 1.6-SNAPSHOT]$ pwd
/tmp/artifacts/m2/io/syndesis/s2i/s2i/1.6-SNAPSHOT
```

**Comment by rhuss** [comment]
@avano good point. I think the fix should be easy, let gimme a try later.
