### ISSUE TITLE
UXD - API Provider UX design update based on feedback 

### ISSUE THREAD

**Issue by dongniwang** [syndesisio/syndesis#4120]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
[x] UX Design
</code></pre>

## Description
Update existing UX design based on API Provider usability testing #3768.

**Comment by gaughan** [comment]
This looks great, thanks @dongniwang

**Comment by gaughan** [comment]
@asmigala I added some comments to the design. 
1. I see the loop too, maybe we can iterate once dongni is back, but we should proceed based on what we have and the comments.
2. A warning icon (already in place for data shape mismatch) plus a dialog on save should be enough for saving breaking changes. @amysueg for clarity.

**Comment by paoloantinori** [comment]
Hi @dongniwang what's the status of this?

We are about to enter the second last development sprint and without the final UX defined we are risking to not be able to implement the requested functionality.

Can you give us an update?

**Comment by dongniwang** [comment]
The design was done back in December. If @gaughan @zregvart and @riccardo-forina are all fine with it. Please sign off. Design link is available in the[ tracker here.](https://syndesisio.github.io/syndesis-ux/). 

Also, we have an epic opened for implementation https://github.com/syndesisio/syndesis/issues/4260

**Comment by amysueg** [comment]
Please refer to Syndesis design tracker for final designs: https://syndesisio.github.io/syndesis-ux/ 
Closing this item.
