### ISSUE TITLE
Add guidelines to the templates about which version should be used where

### ISSUE THREAD

**Issue by avano** [syndesisio/syndesis#4136]
See also **https://issues.jboss.org/browse/ENTESB-11485**

## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Based on the email conversation, here is the summary I did about which version should be used where:

```
For 7.2 we have:
SYNDESIS_UPSTREAM=1.5
SYNDESIS_PROD=1.2

I took the templates from both images and substituted correct variables, here are the lines:

OPERATOR:
https://gist.github.com/avano/f250e4fa49833689e4af659032059ef7#file-operator-versions-L8
https://gist.github.com/avano/f250e4fa49833689e4af659032059ef7#file-operator-versions-L200
https://gist.github.com/avano/f250e4fa49833689e4af659032059ef7#file-operator-versions-L316
https://gist.github.com/avano/f250e4fa49833689e4af659032059ef7#file-operator-versions-L813
https://gist.github.com/avano/f250e4fa49833689e4af659032059ef7#file-operator-versions-L1144
https://gist.github.com/avano/f250e4fa49833689e4af659032059ef7#file-operator-versions-L1209

UPGRADE:
https://gist.github.com/avano/b6c7f8f2ea7faae7a0de148206135279#file-upgrade-versions-L7
https://gist.github.com/avano/b6c7f8f2ea7faae7a0de148206135279#file-upgrade-versions-L199
https://gist.github.com/avano/b6c7f8f2ea7faae7a0de148206135279#file-upgrade-versions-L315
https://gist.github.com/avano/b6c7f8f2ea7faae7a0de148206135279#file-upgrade-versions-L812
https://gist.github.com/avano/b6c7f8f2ea7faae7a0de148206135279#file-upgrade-versions-L1143
https://gist.github.com/avano/b6c7f8f2ea7faae7a0de148206135279#file-upgrade-versions-L1208
+ syndesis upgrade container should have system property SYNDESIS_VERSION property defined that resolves to <SYNDESIS_PROD>
```

**Comment by rhuss** [comment]
I still think this is valid to document the relationship between Syndesis versions (1.6.x) and Fuse Online image version (1.3.x or so). 

Tbh I think its better than someone other than me documents this (with the help from @avano and me) to get to understand the relationship better, also for future versions. For me, it would take a considerable amount of time again to go through everything and write it down, not sure whether I can find that. But I'm happy to help and answer every question.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11485**
