### ISSUE TITLE
Syndesis dev --cookie and syndesis dev --cookie --refresh doesn't work as expected

### ISSUE THREAD

**Issue by oscerd** [syndesisio/syndesis#4137]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Generating cookie with these command doesn't allow to access API from outside. Probably something changed in Openshift too.

**Comment by oscerd** [comment]
I think this must be fixed in some way for the next sprint, but in the next months we must have an agreement about:
- how to expose a public API in a secure manner
- what to expose

**Comment by heiko-braun** [comment]
Adding @chirino . I think he had some ideas to separate the automation API from the UI API and using another form of authentication, decoupled from the actual users of the UI (i.e. simple shared secret, aka API tokens)

**Comment by lburgazzoli** [comment]
integr8ly need to access our api too so having a common solution would help (I think)
