### ISSUE TITLE
Creating API Connector fails but no error displayed on UI

### ISSUE THREAD

**Issue by phantomjinx** [syndesisio/syndesis#4140]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

- Downloaded [this](https://github.com/open-banking/model-config) open-banking specification to use as an example;
- In Syndesis:
  - clicked on 'customizations' and, when prompted, selected the .yaml file;
  - clicked Next. 

## Expected behavior

OpenAPI specification should be imported correctly.

## Screenshot

The progress spinner just keeps spinning and never returns:
![never-ending-wheel](https://user-images.githubusercontent.com/1634180/48941992-8f294b80-ef15-11e8-8f68-91686d79ccaa.png)

Poking into the console, its clear something has gone wrong:
![never-ending-console-errors](https://user-images.githubusercontent.com/1634180/48942003-94869600-ef15-11e8-9b37-ae4eeadf74bf.png)
Looking at the source, it would appear that the request is created without due regard for errors generated. In this case:
- action.payload is valid but contains an error, specifically "Unable to read OpenAPI specification from: openapi: "3.0.1"↵info:↵  version: "1.0.0-alpha1"↵  title: "pg-ledger API"↵  description: "API to ..." so maybe not a recognised format??
- action.payload.configuredproperties is undefined;
- action.payload.configuredproperties.specification is also undefined;
- action.payload.name is undefined hence attempts to read action.payload.specification.info fail and cause the exception

![never-ending-source](https://user-images.githubusercontent.com/1634180/48941994-918ba580-ef15-11e8-8cca-9fb68126faf0.png)

Now, it may be the case that this OpenAPI specification is not valid. In which case it would be good to know why. However, more importantly error handling for non-valid files would be an advantage.

To escape the infinite spinner requires a page refresh of the browser.

## Tasks involved / Steps to Reproduce

See above.

**Comment by heiko-braun** [comment]
@phantomjinx if it's openapi 3, it's not supported. Still, the UI should handle these cases gracefully.

**Comment by phantomjinx** [comment]
@heiko-braun 
That was my suspicion. Should there be a UX wording change on the 1st step page as well, eg.
_Upload OpenAPI **(1.0-2.0)** Specification_ ??

@gashcrumb @dongniwang

**Comment by dongniwang** [comment]
1. We can add a line of instruction text to explain what is currently suppoted (see screenshot below). 
2. Can we catch that before user perform the upload action? If not, we should display an error message saying the openapi 3 is not supported. 

I believe @zregvart  worked on this feature initially, so tag him as well. 

@TovaCohen - do you know if we mention what kind of open api specification we support in the user doc? 

cc: @syndesisio/uxd 

![screen shot 2018-11-27 at 11 02 36 am](https://user-images.githubusercontent.com/24943812/49094312-f9066580-f233-11e8-838d-86d37b2b1d92.png)

**Comment by TovaCohen** [comment]
The user doc says:
Fuse Online requires a valid OpenAPI 2.0 schema that describes a REST API.

So perhaps change the UI prompt from:
Upload an OpenAPI file
to
Upload an OpenAPI 2.0 schema that describes a REST API.

**Comment by dongniwang** [comment]
@TovaCohen - Yeah. Assuming you're referring to the first radio button text? We can certainly change it to _Upload an OpenAPI 2.0 schema that describes a REST API_. But I wonder if that makes it too long of a description for a radio button. 

@syndesisio/uxd - WDYT?

**Comment by amysueg** [comment]
@dongniwang @TovaCohen what about something more like "Upload an OpenAPI file (Version 1.0-2.0)"

that's similar to what @phantomjinx suggested earlier...

**Comment by zregvart** [comment]
> "Upload an OpenAPI file (Version 1.0-2.0)"

We only support 2.0 at the moment, there is no 1.0 support.
