### ISSUE TITLE
Camel K Image Builder as internal implementation detail to speed up Fuse deployments

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/syndesis#4143]
As a user, I want to be able to use Camel-K to stand up integrations on Openshift, to be able to benefit from the quick turnaround times.

**Comment by KurtStam** [comment]
@lburgazzoli can you point me to the code in Camel-K. I'm wondering if we can package this logic for any maven based build, so that we can speed up the Syndesis build even for this release.

**Comment by heiko-braun** [comment]
@KurtStam I think it doesn't make sense to backport any of this to Syndesis. I think it's safe to assume that Camel-K will replace the current means to standup integrations soon. Outside Syndesis however, more generally looking at Java/Maven builds on Openshift this might be interesting.

**Comment by lburgazzoli** [comment]
It would be quite a big task to implement the same logic in syndesis as it is not just the maven build that is affected but also the way we do package the application would need to be completely rewritten.

**Comment by mastepan** [comment]
QE ignore
