### ISSUE TITLE
Infrastructure Monitoring

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/syndesis#4145]
As a user I want to be able to monitor all main Syndesis components to be able to tell when a component becomes unresponsive or errorneous.

Acceptance Criteria

- All main components can be instrumented (i.e. data retrieved from them)
- We have documentation that explains how to configure prometheus to scrape these components

**Comment by mkralik3** [comment]
@heiko-braun  In the Acceptance Criteria is a mention about documentation. Is any documentation which describes the following items?:

- how to set up Grafana and Prometheus (I used [Application Monitoring Stack](https://github.com/integr8ly/application-monitoring-operator))

- how to add [dashboards and servicemonitors ](https://github.com/syndesisio/syndesis/tree/master/install/addons)

**Comment by tplevko** [comment]
@heiko-braun we have a difficulty with verification of this epic. The acceptance criteria clearly states "We have documentation that explains how to configure prometheus to scrape these components" 
However the documentation was moved to 7.4.: [FUSEDOC-3049](https://issues.jboss.org/browse/FUSEDOC-3049), [FUSEDOC-3000](https://issues.jboss.org/browse/FUSEDOC-3000), [FUSEDOC-2996](https://issues.jboss.org/browse/FUSEDOC-2996), [FUSEDOC-2997](https://issues.jboss.org/browse/FUSEDOC-2997)

Just want to ask, how should we proceed in this case. Should it be left open and moved to 7.4., or can there be a new follow-up task created and we can close this?

**Comment by alexkieling** [comment]
@tplevko Yes, the documentation tasks have been moved to 7.4 and the epic won't be fully done until they are completed. I suggest leaving it open and moving it to 7.4 as well.

**Comment by heiko-braun** [comment]
I think what @tplevko is asking for is slightly different. QE wants to test the infra monitoring, but without any docs they cannot achieve this. Is there a way we enable QE, without having full fledged product docs? Anything upstream that explain how to setup monitoring they would allow @tplevko s team to make progress?

**Comment by alexkieling** [comment]
OK. James wrote a document explaining how to install the monitoring stack but haven't sent a PR to syndesis yet. I think it still needs some work.
https://github.com/jamesnetherton/syndesis/blob/monitoring-docs/doc/managing_environments/topics/monitoring_operator_installation.adoc

**Comment by tplevko** [comment]
@heiko-braun thanks, this was actually as @alexkieling mentioned more a problem with this epic - whether we should leave it open and move to 7.4. or create a follow up issue and close it. The explanation of how the monitoring should be set up was delivered to QE earlier.

**Comment by heiko-braun** [comment]
Ok, sorry for the confusion. In  this case i think we should create a subtask for docs and move the epic to 7.4

**Comment by alexkieling** [comment]
@heiko-braun , I believe this epic can be closed.

**Comment by mkralik3** [comment]
@heiko-braun @tplevko @alexkieling I have close this issue due to the fact that the upstream contains the needed documentation https://github.com/syndesisio/syndesis/blob/1.7.x/doc/managing_environments/topics/monitoring_operator_installation.adoc .
