### ISSUE TITLE
Infrastructure Dashboard

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/syndesis#4147]
As an administrator of Fuse on Openshift and/or Fuse Online, I want to be able to use some OOTB dashboards. These OOTB dashboards allow me to monitor my Prometheus infrastructure metrics for my Fuse infrastructure. This allows me to quickly check on the health of my Fuse install.

**Comment by alexkieling** [comment]
Merged into https://github.com/syndesisio/syndesis/issues/4145
