### ISSUE TITLE
As a citizen integrator, use a messaging connection in an integration

### ISSUE THREAD

**Issue by kcbabo** [syndesisio/syndesis#415]
As a citizen integrator, I would like to use messaging connections to perform message-oriented interactions from an integration flow.  Specifically, I need the following capabilities:
- Receive : used exclusively as a Start connection to kick off an integration flow based on an inbound message.  Supported configuration options should include:
    - Destination name (required)
    - Destination type (required; default Queue)
    - Selector (optional)
    - Subscription ID (optional)
- Send and receive : used exclusively as a "step" between a start and finish connection in an integration flow.  Supported configuration options should include:
    - Destination name (required)
    - Destination type (required; default Queue)
    - Reply timeout (optional)
    - Persistent message (true/false)
- Send : used exclusively as a Finish connection to send a message and the end of an integration flow.  Supported configuration options should include:
    - Destination name (required)
    - Destination type (required; default Queue)
    - Persistent message (true/false)

**Comment by mmelko** [comment]
Hi Kieth, 
So citizen integrator basically know nothing about JMS, brokers etc .. he will only use messaging connection as sort of buffer (queues) or notification service (topics)? Is my understanding correct ?

**Comment by kcbabo** [comment]
I think that's a fair way to put it.  IOW, the citizen cares about messaging as input/output in an integration flow.  The expert cares about configuring the connectivity to a specific messaging provider.

**Comment by dhirajsb** [comment]
@kcbabo closing this as A-MQ connector is done.
