### ISSUE TITLE
Leverage registry.redhat.io for product builds

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/syndesis#4165]
We need to move from `registry.access.redhat.com` to `registry.redhat.io` in all cases where the product registry is referenced. I think this is first and foremost an issues for the scripts in https://github.com/syndesisio/fuse-online-install, but may also impact other places (i.e. syndesis). 

The new registry requires authentication.

**Comment by heiko-braun** [comment]
@rhuss Do you have this on your radar? It is planned for 7.3

**Comment by rhuss** [comment]
No, and I don't have an idea what this issue is about.

**Comment by heiko-braun** [comment]
@rhuss I have updated the description. Does it make sense now?

**Comment by rhuss** [comment]
How does the authentication looks like ? Is it when the imagestreams are installed ? Any pointers for more information ? 

I also guess that the documentation needs to be updated.

**Comment by heiko-braun** [comment]
@lgarciaaco Do you have bandwidth to look into this? This mostly revolves around changes to the bash scripts in https://github.com/syndesisio/fuse-online-install.

**Comment by heiko-braun** [comment]
@rhuss Do you think we also need to touch any Syndesis build scripts?

**Comment by rhuss** [comment]
@heiko-braun As long as I don't know anything about how the authentication against the registry works when deploying Fuse Online, I can't comment on this. it could be even that that authentication is a cluster configuration so we don't have to do anything.

**Comment by heiko-braun** [comment]
I think it requires a cluster config change:

- https://docs.okd.io/latest/install_config/configuring_red_hat_registry.html
- https://access.redhat.com/articles/3560571

**Comment by heiko-braun** [comment]
Let's verifythe changes on 7.2, with the setup instructions provided here: https://access.redhat.com/documentation/en-us/red_hat_fuse/7.2/html/fuse_on_openshift_guide/get-started-admin#configure-container-registry

**Comment by heiko-braun** [comment]
Let's keep this in progress for verification with CR1

**Comment by tplevko** [comment]
It won't be possible to test this with CR1, as the images won't be available in registry.redhat.io, just in brew repo. 7.2. images however should be already available in this registry, so we can utilize these for testing. 
For 7.3. we can perform this as a postGA task. 
Assigned to @avano.

**Comment by avano** [comment]
I tried it with 7.2, here is what I did:

- get fuse online install, replace registry.access.redhat.com with registry.redhat.io
- change the install_ocp.sh to get local files instead of files from github
- create namespace, create the secret that is generated on the redhat page in my namespace
- bash install_ocp.sh
- operator pod won't start because it can't pull the images, so I needed to add my secret to syndesis-operator SA: `oc secrets link syndesis-operator <my-secret> --for=pull`
- then the operator image is pulled and it spawns the syndesis infra, however, all pods fail because they can pull the images, so I needed to add the `imagePullSecret` to all deployment configs: `oc patch dc/<all-syndesis-dc> -p '{"spec": {"template": {"spec": {"imagePullSecrets": [{"name": "<my-secret>"}]}}}}'`
- then syndesis is spawned successfully
- only problem left is that **I can't create an integration**, as it is not able to pull the s2i image. I tried to add my secret to all SAs I had in the project: `builder`, `default`, `deployer`, `syndesis-integration`, `syndesis-server` (I left out syndesis-oauthproxy and syndesis-prometheus, but those two shouldn't matter). The build pod always fails with:

```
      Reason:   Error
      Message:  Image "registry.redhat.io/fuse7/fuse-ignite-s2i@sha256:bc0dfc7b29b..." not available locally, pulling ...
pulling image error : Get https://registry.redhat.io/v2/fuse7/fuse-ignite-s2i/manifests/sha256:bc0dfc7b29bc005673bfdc5a8d3ffdeea41f28d1922d5f71dee3e0503b9255ca: unauthorized: Please login to the Red Hat Registry using your Customer Portal credentials. Further instructions can be found here: https://access.redhat.com/articles/3399531
error: build error: unable to get registry.redhat.io/fuse7/fuse-ignite-s2i@sha256:bc0dfc7b29bc005673bfdc5a8d3ffdeea41f28d1922d5f71dee3e0503b9255ca

```

Maybe it is possible to add the imagePullSecret to the ImageStream directly, but I didn't find a way to do so. Any ideas? :grin:

**Comment by heiko-braun** [comment]
@rhuss Can you take a look at this?

**Comment by heiko-braun** [comment]
@avano Did you also try the steps outlined in https://access.redhat.com/documentation/en-us/red_hat_fuse/7.2/html/fuse_on_openshift_guide/get-started-admin#configure-container-registry?

**Comment by rhuss** [comment]
The S2I images are pulled for the build of the integration runtime image. The corresponding resources are created from the Syndesis server on the fly, so depending what needs to be done for the authentication, it might require some code changes, too.

**Comment by rhuss** [comment]
@heiko-braun I guess the docs you reference describe how to setup the secret, and assume that all the fis imagestreams reference the secret. This is the secret sauce which we are probably missing as our resources nowhere reference the created secrets. Who did the registry Auth part for the fis images ? He could probably help us here, too

**Comment by rhuss** [comment]
@avano in https://github.com/syndesisio/syndesis/blob/master/app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftServiceImpl.java (line 243 or so) the reference to the imagepull secret need to be added afais (sorry, on mobile can't do proper linking). This means we would need a new configuration option (also as part of the Syndesis CR), which switches on authentication and specifies the name of the secret to us for authentication (which then would need to be added as described in the docs)

For the regular images, this information can be used by the operator to add the pullsecrets when creating the deployments. (Need to be added to the operator though).

The question remains how to add this to a template based install. I guess we need to introduce a second template with this pull secrets enabled. And cc affair the install script accordingly to pick this up.

**Comment by heiko-braun** [comment]
@rhuss @avano I have created a separate issues (bug,p0) over here: https://github.com/syndesisio/syndesis/issues/4799

**Comment by heiko-braun** [comment]
I don;t know if we need new service accounts (i.e. for ui pod), apparently we can use the `default` account:

```
oc secrets link default <pull_secret_name> --for=pull
```

(Taken from https://access.redhat.com/RegistryAuthentication#using-authentication-3 )

**Comment by heiko-braun** [comment]
@avano If we put the changes on `1.6.x`, do you means to verify it against some registry that requires auth and with  community images?

**Comment by avano** [comment]
@heiko-braun the changes will be in operator only afaik (and install scripts in fuse-online-install) - the operator only references the image stream tag, so it doesn't know where the other images are located, so I can re-use the community operator to deploy syndesis from registry.redhat.io

**Comment by heiko-braun** [comment]
@avano I see what you mean. Thta's interesting – and yes, it might actually work ...

**Comment by heiko-braun** [comment]
@avano I think we have everything on master (in the operator), except for two things that have to happen outside that: a) setting up the pull secret and b) linking it to the syndesis-operator SA to be able to pull the initial operator image. 

Would it be possible to verify what we have based on this?

**Comment by avano** [comment]
@heiko-braun I'll check tomorrow

**Comment by avano** [comment]
@heiko-braun @astefanutti @lgarciaaco 

Two issues:
1) I assume we will use some productized oauth proxy for productized syndesis - the community currently uses https://github.com/syndesisio/syndesis/blob/145b34812e82db31328a956101fd454d24522caa/install/syndesis.yml#L236

So we will need the pull secret in the `syndesis-oauth-client` SA as well, as that is the one specified in the syndesis-oauthproxy dc:

```
oc describe dc/syndesis-oauthproxy | grep "Service Account"
  Service Account:	syndesis-oauth-client
```

```
Name:                syndesis-oauth-client
Namespace:           syndesis
Labels:              app=syndesis
Annotations:         serviceaccounts.openshift.io/oauth-redirectreference.route={"kind": "OAuthRedirectReference", "apiVersion": "v1", "reference": {"kind": "Route","name": "syndesis"}}
                     serviceaccounts.openshift.io/oauth-redirecturi.local=https://localhost:4200
                     serviceaccounts.openshift.io/oauth-redirecturi.route=https://
Image pull secrets:  syndesis-oauth-client-dockercfg-8vgj6
Mountable secrets:   syndesis-oauth-client-dockercfg-8vgj6
                     syndesis-oauth-client-token-qwrfg
Tokens:              syndesis-oauth-client-token-dpn2k
                     syndesis-oauth-client-token-qwrfg
Events:              <none>
```

That pod is the only one that didn't start:

```
NAME                           READY     STATUS             RESTARTS   AGE
syndesis-db-1-6tf5q            2/2       Running            0          4m
syndesis-meta-1-5kf2q          1/1       Running            0          4m
syndesis-oauthproxy-1-deploy   1/1       Running            0          4m
syndesis-oauthproxy-1-sbs94    0/1       ImagePullBackOff   0          4m
syndesis-operator-1-q4vnq      1/1       Running            0          4m
syndesis-prometheus-1-2ztw4    1/1       Running            0          4m
syndesis-server-1-ckmn7        1/1       Running            0          4m
syndesis-ui-1-kg6pn            1/1       Running            0          4m
todo-1-4n8fl                   1/1       Running            0          3m
todo-1-build                   0/1       Completed          0          4m
```

2) Operator adds the `syndesis-pull-secret` to `builder` SA, but the image can't be pulled:

```
oc logs -f i-qq-1-build
Image "registry.redhat.io/fuse7/fuse-ignite-s2i@sha256:bc0dfc7b29b..." not available locally, pulling ...
pulling image error : Get https://registry.redhat.io/v2/fuse7/fuse-ignite-s2i/manifests/sha256:bc0dfc7b29bc005673bfdc5a8d3ffdeea41f28d1922d5f71dee3e0503b9255ca: unauthorized: Please login to the Red Hat Registry using your Customer Portal credentials. Further instructions can be found here: https://access.redhat.com/articles/3399531
error: build error: unable to get registry.redhat.io/fuse7/fuse-ignite-s2i@sha256:bc0dfc7b29bc005673bfdc5a8d3ffdeea41f28d1922d5f71dee3e0503b9255ca
```

```
oc describe sa builder
Name:                builder
Namespace:           syndesis
Labels:              <none>
Annotations:         <none>
Image pull secrets:  builder-dockercfg-jbnmb
                     syndesis-pull-secret
Mountable secrets:   builder-token-ctrdv
                     builder-dockercfg-jbnmb
Tokens:              builder-token-76zqz
                     builder-token-ctrdv
Events:              <none>
```

It seems that operator did the same as linking the secret with `--for=pull`, because when I do `oc secrets link syndesis-oauth-client syndesis-pull-secret` manually, the secret is added to `Mountable secrets`, as opposite to `Image pull secrets` where it is added by the operator

```
oc describe sa builder
Name:                builder
Namespace:           syndesis
Labels:              <none>
Annotations:         <none>
Image pull secrets:  builder-dockercfg-jbnmb
                     syndesis-pull-secret
Mountable secrets:   builder-token-ctrdv
                     builder-dockercfg-jbnmb
                     syndesis-pull-secret
Tokens:              builder-token-76zqz
                     builder-token-ctrdv
Events:              <none>

```

The problem lies here probably:

https://github.com/syndesisio/syndesis/blob/145b34812e82db31328a956101fd454d24522caa/install/operator/pkg/syndesis/action/install.go#L107-L108

where the `linkImagePullSecret` returns true so in the next line the `linkSecret` isn't called

**Comment by astefanutti** [comment]
@avano Thanks a lot for the detailed feedback. Let me fix these two issues.

**Comment by astefanutti** [comment]
The two issues should be fixed with #4988. I thought the `syndesis-oauth-client` service account was only meant to be used as OAuth client but it turns out it's also used as real pod service account.

**Comment by heiko-braun** [comment]
@astefanutti I was looking at recent 1.6.x and it seems the `builder` is still linked with `--for-pull`. I believe @avano is right, when he says that the builder should show the secret under `Mountable secrets`, like this one:

```
Name:                test
Namespace:           syndesis
Labels:              <none>
Annotations:         <none>
Image pull secrets:  test-dockercfg-zfvgr
Mountable secrets:   test-token-8nl6b
                     test-dockercfg-zfvgr
                     syndesis-pull-secret
Tokens:              test-token-5dxcj
                     test-token-8nl6b
Events:              <none>
```

**Comment by astefanutti** [comment]
@heiko-braun are you sure you tested with #5003?

**Comment by heiko-braun** [comment]
No, sorry, my bad. let me do another test

**Comment by astefanutti** [comment]
no worries. Let me know how that goes.

**Comment by heiko-braun** [comment]
@astefanutti works like charm: 

```
oc describe sa builder
Name:                builder
Namespace:           syndesis
Labels:              <none>
Annotations:         <none>
Image pull secrets:  builder-dockercfg-7c92k
                     syndesis-pull-secret
Mountable secrets:   builder-token-mclbk
                     builder-dockercfg-7c92k
                     syndesis-pull-secret
Tokens:              builder-token-92c56
                     builder-token-mclbk
Events:              <none>

```

**Comment by astefanutti** [comment]
@heiko-braun I think this replicates the behaviour of `oc link` without `--for-pull`, that is the secret is both referenced in the pull and mountable secrets.

**Comment by avano** [comment]
@astefanutti @heiko-braun looks ok with master now. since it didn't get to the 1.6.2 build, is it ok to wait with verification to 1.6.3?

I built my own operator image from 1.6.x branch (`./syndesis build -m operator --flash --docker`) but it seems it has some problems even without any modification, so I don't know if the release script is doing something differently:

```
level=error msg="error syncing key (syndesis/example): Template.template.openshift.io \"syndesis\" is invalid: template.parameters[4]: Required value: template.parameters[4]: parameter SAR_PROJECT is required and must be specified"
```

**Comment by astefanutti** [comment]
@avano the operator is supposed to source the `SAR_PROJECT` env variable passed to the template processing from the `SarNamespace` syndesis CR spec field or the syndesis CR namespace:

https://github.com/syndesisio/syndesis/blob/4690f60457205094d45082eb3b99bd083a413f3f/install/operator/pkg/syndesis/configuration/configuration.go#L192-L202

I would expect the namespace to be always evaluated.

**Comment by heiko-braun** [comment]
>  since it didn't get to the 1.6.2 build, is it ok to wait with verification to 1.6.3?

@avano yes, sure. In the meantime we work on the bash scripts in `fuse-online-install`. Thanks for your help!

**Comment by rhuss** [comment]
Looks like the issue with the integration runtimes has been sorted out (i.e. where to add the secret to the SA). Awesome work, guys!

Is there anything which needs to be done in this story and which is not assigned ?

**Comment by lgarciaaco** [comment]
@rhuss I think the `fuse-online-install` `install_ocp.sh` and `update_ocp.sh` are the tho missing bits, and we(heiko+myself) are taking care of it already

**Comment by heiko-braun** [comment]
@rhuss I foyu could look at https://github.com/syndesisio/syndesis/issues/4903 that would be a great help.

**Comment by rhuss** [comment]
ok

**Comment by avano** [comment]
I closed all the issues I verified with `1.6.3`

**Comment by TovaCohen** [comment]
Is there user doc required for this issue? 
I still have this doc Jira open and I don't know what, if anything, I need to do:
https://issues.jboss.org/browse/FUSEDOC-3045

I did update the doc for installing and upgrading Fuse Online on OCP on premise to indicate that a prerequisite is a redhat.developers.com account, and that the installation/upgrade script will prompt you for your user name and password. 

Please let me know if additional updates to the user doc are needed. And if yes, what those updates are.  Thanks!

**Comment by TovaCohen** [comment]
Just want to note here that I am all set with the doc. It is being updated as part of 
https://issues.jboss.org/browse/FUSEDOC-3109
and a draft of the updated doc is here: 
https://docs.google.com/document/d/1Q8SYbxZpFqzSi2Io-z_YreoD4GKPVqGgqhxOpzHvQPY/edit?usp=sharing

**Comment by avano** [comment]
@TovaCohen I can review it tomorrow, does that work for you?

**Comment by TovaCohen** [comment]
@avano That would be great! Thanks!

**Comment by mastepan** [comment]
Closing this epic. Contained issues will be/have been verified.
