### ISSUE TITLE
Monitoring - export JDBC metrics in Syndesis Server

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/syndesis#4171]
As a system administrator, I want to expose metrics about JDBC connections in Syndesis Server, so I can monitor its health.

**Comment by alexkieling** [comment]
As a system administrator, I want to expose metrics about Tomcat in Syndesis Server, so I can monitor its health.

**Comment by mkralik3** [comment]
Verified. Prometheus contains those parameters.
