### ISSUE TITLE
Step which is after basic or advanced filter is in the activity log twice

### ISSUE THREAD

**Issue by mkralik3** [syndesisio/syndesis#4181]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When I have some step after the advanced filter or basic filter, this step appears in the activity log twice.
e.g.
**1. Integration:**
![image](https://user-images.githubusercontent.com/16251792/49217560-31da4200-f3ce-11e8-8682-cdb50848483f.png)

![image](https://user-images.githubusercontent.com/16251792/49219408-74eae400-f3d3-11e8-95d3-fda4246dd09d.png)
You can see that DataMaper is there **after** Invoke SQL **again**.
[Webhook to DB before-export.zip](https://github.com/syndesisio/syndesis/files/2628810/Webhook.to.DB.before-export.zip)

**2. Integration:**
![image](https://user-images.githubusercontent.com/16251792/49217316-87fab580-f3cd-11e8-813d-85e70db0a267.png)
In the activity log, you can see that another **unknown** Log step with No output is after Invoke SQL but this step is not **defined**.
![image](https://user-images.githubusercontent.com/16251792/49219453-9ba91a80-f3d3-11e8-95dc-4346a097b499.png)
)
[Webhook to DB advanced after-export.zip](https://github.com/syndesisio/syndesis/files/2628894/Webhook.to.DB.advanced.after-export.zip)

**3. Integration:**
Same situation with Basic filter:
![image](https://user-images.githubusercontent.com/16251792/49219286-16256a80-f3d3-11e8-8126-05c3b07b75c2.png)
![image](https://user-images.githubusercontent.com/16251792/49219486-c1362400-f3d3-11e8-815b-8e3d72606b4e.png)
In the activity log, you can see that another **unknown** Log step with No output is after Invoke SQL but this step is not **defined**.
[Webhook to DB basic after-export.zip](https://github.com/syndesisio/syndesis/files/2628908/Webhook.to.DB.basic.after-export.zip)

**4. Integration:**
 For integration without the advance of the basic filter, **no** extra steps appear after the finish step:
![image](https://user-images.githubusercontent.com/16251792/49219588-09eddd00-f3d4-11e8-93d6-8bf0ce8d1408.png)
![image](https://user-images.githubusercontent.com/16251792/49219610-12deae80-f3d4-11e8-94a5-4c7182ab4458.png)
[Webhook to DB with connection-export.zip](https://github.com/syndesisio/syndesis/files/2628927/Webhook.to.DB.with.connection-export.zip)

**Step to reproduce:**
1. import integration:
2. publish it
3. in the command line, update endpoint for webhook and run
```
curl -k -v https://i-webhook-to-db-syndesis.192.168.42.27.nip.io/webhook/test-webhook -d '{"first_name":"John","company":"Red Hat"}' -X POST -H "Content-Type: application/json"
```

**Comment by KurtStam** [comment]
The pod log already contains the problem:

{"exchange":"i-LaFjKh608Qvv3mvTp8qz","status":"begin"}
{"exchange":"i-LaFjKh608Qvv3mvTp8qz","step":"-LSU64LJHz7Zte_e1fMQ","id":"i-LaFjKh608Qvv3mvTp8sz","message":"anotherLog"}
{"exchange":"i-LaFjKh608Qvv3mvTp8qz","step":"-LSU64LJHz7Zte_e1fMQ","id":"i-LaFjKh608Qvv3mvTp8sz","duration":1271163}
{"exchange":"i-LaFjKh608Qvv3mvTp8qz","step":"**-LSTzCWy2Ax_18exj37d**","id":"i-LaFjKip08Qvv3mvTp8uz","duration":10502061}
{"exchange":"i-LaFjKh608Qvv3mvTp8qz","step":"-LSTz7Pv2Ax_18exj37Y","id":"i-LaFjKj-08Qvv3mvTp8wz","duration":6712176}
{"exchange":"i-LaFjKh608Qvv3mvTp8qz","step":"**-LSTzCWy2Ax_18exj37d**","id":"i-LaFjKh808Qvv3mvTp8tz","duration":125807557}
{"exchange":"i-LaFjKh608Qvv3mvTp8qz","status":"done","failed":false}

**Comment by KurtStam** [comment]
Looks like something in the AdvancedFilter is messing with the logic in the Camel Pipeline 

https://github.com/syndesisio/syndesis/blob/master/app/integration/runtime/src/main/java/io/syndesis/integration/runtime/logging/ActivityTrackingInterceptStrategy.java#L79

**Comment by christophd** [comment]
@KurtStam also worth taking a look at IntegrationRouteBuilder logic as this had some changes in this release. Possible mess up with step ids or something

https://github.com/syndesisio/syndesis/blob/master/app/integration/runtime/src/main/java/io/syndesis/integration/runtime/IntegrationRouteBuilder.java

I will also take a look this afternoon

**Comment by christophd** [comment]
I had a look at the IntegrationRouteBuilder and the generated Camel route looks exactly the same as before all the changes related to start/end block. 

I think the problem is in the generated route itself. This is a sample route generated from integration following steps

`direct => filter => mock`

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<routes xmlns="http://camel.apache.org/schema/spring">
    <route customId="true" id="flow">
        <from customId="true" id="direct" uri="direct:start"/>
        <setHeader headerName="Syndesis.FLOW_ID" id="setHeader1">
            <constant>flow</constant>
        </setHeader>
        <setHeader headerName="Syndesis.STEP_ID" id="setHeader2">
            <constant>direct</constant>
        </setHeader>
        <process id="process1"/>
        <pipeline customId="true" id="step:filter">
            <setHeader headerName="Syndesis.STEP_ID" id="setHeader3">
                <constant>filter</constant>
            </setHeader>
            <filter id="filter1">
                <expressionDefinition>io.syndesis.integration.runtime.util.JsonSimplePredicate@69cac930</expressionDefinition>
                <process id="process2"/>
                <pipeline customId="true" id="step:mock">
                    <setHeader headerName="Syndesis.STEP_ID" id="setHeader4">
                        <constant>mock</constant>
                    </setHeader>
                    <to id="to1" uri="mock:result"/>
                    <process id="process3"/>
                </pipeline>
            </filter>
        </pipeline>
    </route>
</routes>
```

When I execute the route and filter evaluates to `match` I get the following activity logs:

```
{"exchange":"i-LaPGprB9hUTgjoDxVGpz","status":"begin"}
{"exchange":"i-LaPGprB9hUTgjoDxVGpz","step":"mock","id":"i-LaPGprZ9hUTgjoDxVGsz","duration":888913}
{"exchange":"i-LaPGprB9hUTgjoDxVGpz","step":"mock","id":"i-LaPGprN9hUTgjoDxVGrz","duration":14366042}
{"exchange":"i-LaPGprB9hUTgjoDxVGpz","status":"done","failed":false}
```

When filter evaluates to `no match` and the subsequent mock step is not executed I get:

```
{"exchange":"i-LaPGprb9hUTgjoDxVGtz","status":"begin"}
{"exchange":"i-LaPGprb9hUTgjoDxVGtz","step":"filter","id":"i-LaPGprb9hUTgjoDxVGvz","duration":346734}
{"exchange":"i-LaPGprb9hUTgjoDxVGtz","status":"done","failed":false}
```

I think the problem is that the `stepId` header is overwritten by nested pipelines (here the `mock` step) living inside the filter block. So the log activity for the filter is done after the nested pipeline is done and therefore logs the stepId of the nested mock step once again instead of the actual filter stepId.

I think is is also possible that it has been this way since always.

**Comment by christophd** [comment]
I think it should look like:

```
{"exchange":"i-LaPGprB9hUTgjoDxVGpz","status":"begin"}
{"exchange":"i-LaPGprB9hUTgjoDxVGpz","step":"mock","id":"i-LaPGprZ9hUTgjoDxVGsz","duration":888913}
{"exchange":"i-LaPGprB9hUTgjoDxVGpz","step":"filter","id":"i-LaPGprN9hUTgjoDxVGrz","duration":14366042}
{"exchange":"i-LaPGprB9hUTgjoDxVGpz","status":"done","failed":false}
```

Another option would be to not log filter steps at all. Just like we do not log split/aggregate steps at the moment.

**Comment by KurtStam** [comment]
@lburgazzoli I think I need some pipeline expertise to help me out here..

**Comment by KurtStam** [comment]
The filter defines the pipeline as 

  ```
      <pipeline customId="true" id="step:-LbNDJpPC460DUibX7N1">
            <setHeader headerName="Syndesis.STEP_ID" id="setHeader4">
                <constant>-LbNDJpPC460DUibX7N1</constant>
            </setHeader>
            <filter id="filter1">
                <expressionDefinition>io.syndesis.integration.runtime.util.JsonSimplePredicate@7a2a7492</expressionDefinition>
                <process id="process5"/>
                <pipeline customId="true" id="step:-LbNCWdpC460DUibX7Mz">
                    <setHeader headerName="Syndesis.STEP_ID" id="setHeader5">
                        <constant>-LbNCWdpC460DUibX7Mz</constant>
                    </setHeader>
                    <to id="to3" uri="sql-0-3"/>
                    <process id="process6"/>
                </pipeline>
            </filter>
        </pipeline>
```
Note that header of the SQL connector is nested bc the process is conditional.
