### ISSUE TITLE
Name of AMQ connector is misleading

### ISSUE THREAD

**Issue by finp** [syndesisio/syndesis#4183]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

When choosing between connectors, I'm confused between AMQ and AMQP.
Suggestion: change label to ActiveMQ as per https://developers.redhat.com/products/fuse/connectors/ 

![image](https://user-images.githubusercontent.com/5154224/49225531-373e8900-f3dc-11e8-97e9-39dcf4347353.png)

**Comment by catrobson** [comment]
@dongniwang FYI, this was identified as we saw many users choose the wrong connector during the Integreatly walkthrough sessions.

**Comment by dongniwang** [comment]
Thanks for opening the issue @finp @catrobson! 

Are we using ActiveMQ across all projects and products? I noticed from the above link that the connector has a different icon/logo. Is that something we need to align as well? 

cc: @amysueg @gaughan @kcbabo @TovaCohen

**Comment by kcbabo** [comment]
AMQ is a connector for a specific product - Red Hat AMQ.
AMQP is a vendor-neutral protocol that talks to any message broker that supports it.

**Comment by zregvart** [comment]
Perhaps "AMQ Message Broker" should be "Red Hat AMQ"?

**Comment by dongniwang** [comment]
Do we have a consensus on this? Is the decision to change from "AMQ Message Broker" to "Red Hat AMQ"?

**Comment by gaughan** [comment]
I'm good with that

**Comment by dongniwang** [comment]
@zregvart @gashcrumb @TovaCohen - We now have a green light for the change (see above comments). What do we need to do to move this forward? Thanks! 

cc: @heiko-braun

**Comment by zregvart** [comment]
This needs to change:

https://github.com/syndesisio/syndesis/blob/ab09481970490f4419a627239466e5e5b91ce824/app/connector/activemq/src/main/resources/META-INF/syndesis/connector/activemq.json#L307

Might be worth going through that file and checking for other ambiguities.

**Comment by TovaCohen** [comment]
I created this Fuse documentation Jira to update the user doc:
https://issues.jboss.org/browse/FUSEDOC-2950

**Comment by dongniwang** [comment]
Thanks @zregvart @TovaCohen !

@zregvart - are you doing the update or you're just pointing out how to do the update?

**Comment by zregvart** [comment]
> @zregvart - are you doing the update or you're just pointing out how to do the update?

The latter

**Comment by TovaCohen** [comment]
I'm updating the user doc to have "Red Hat AMQ", so I thought I would also update the activemq.json file as Zoran described. 
In the image that I am pasting below, will the title automatically become ""Red Hat AMQ Configuration" with the update to the .json file?
Should the text under the last two fields in this image should be prefixed with "Red Hat"?

![image](https://user-images.githubusercontent.com/25067106/51180893-ab06f900-1897-11e9-9548-098bd6814beb.png)

**Comment by gaughan** [comment]
@zregvart ont he first question, if the title automatically gets updated or not,
On question 2, yes prefixing Redhat would be nice

**Comment by zregvart** [comment]
I believe so, because of:

https://github.com/syndesisio/syndesis/blob/070d6cc57da59da7f2efa05fd0bd2469c69e62d7/app/ui/src/app/connections/create-page/configure-fields/configure-fields.component.html#L9

https://github.com/syndesisio/syndesis/blob/23327e151774797f54d734a921e9a96bbe80fa94/app/ui/src/assets/dictionary/en-GB.json#L381

**Comment by TovaCohen** [comment]
Excellent. Thanks. I updated the json file. The PR is here:
https://github.com/syndesisio/syndesis/pull/4329

**Comment by TovaCohen** [comment]
I'm closing this:
- The updated "Red Hat AMQ" name now appears in the staging site per  https://github.com/syndesisio/syndesis/pull/4329 
- The doc has been updated and is visible here: https://access.qa.redhat.com/documentation/en-us/red_hat_fuse/7.3/html-single/connecting_fuse_online_to_applications_and_services/#connecting-to-amq_connectors
