### ISSUE TITLE
Update 1.5.x dictionary to state `7.2`

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/syndesis#4191]
See https://github.com/syndesisio/syndesis/blob/1.5.x/app/ui/src/assets/dictionary/en-GB.json#L319

**Comment by heiko-braun** [comment]
@TovaCohen Where and how is this version being shown?

**Comment by heiko-braun** [comment]
@gashcrumb Where does the version taken from dictionary show up?

**Comment by gashcrumb** [comment]
I'd have to look in more detail, but for sure that really shouldn't be in
there, or should have an override in the config.json like the
shared.project.name key.

**Comment by gashcrumb** [comment]
Ah, of course, the links here -> https://github.com/syndesisio/syndesis/blob/1.5.x/app/ui/src/assets/dictionary/en-GB.json#L231-L234 and I see no others spots where this shows up.

**Comment by heiko-braun** [comment]
Just in case, can you fix the reference and cut another release? I will talk to Darren ...

**Comment by heiko-braun** [comment]
@gaughan without this, the UI links to 7.1 docs. What do you think, should we try to squeeze it in? IMO I wouldn’t take the risk of rebuilding anything at this stage.

**Comment by gashcrumb** [comment]
Having incorrect links that take you to the previous version's docs is
pretty bad.  We should merge this and rebuild the UI image IMO.

**Comment by gaughan** [comment]
Discussed on 7.2 checkpoint call, proceeding with 7.2 release, UI image rebuild to take place next week

**Comment by heiko-braun** [comment]
@gashcrumb Created a followup to improve the situation: https://github.com/syndesisio/syndesis/issues/4195

**Comment by TovaCohen** [comment]
In my Fuse Online 7.2 evaluation, which I just got, when I click the Help icon in the upper right, the user doc links display the 7.1 versions of the doc. At this point, can anything be done to point to the 7.2 user doc versions instead?

**Comment by heiko-braun** [comment]
@TovaCohen I am looking at the staging env and it seems to pick up the right version: https://access.redhat.com/documentation/en-us/red_hat_fuse/7.2/html-single/integrating_applications_with_fuse_online
