### ISSUE TITLE
Final step doesn't show error in the activity log

### ISSUE THREAD

**Issue by mkralik3** [syndesisio/syndesis#4192]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
I have this integration.
![image](https://user-images.githubusercontent.com/16251792/49283126-2c91fb80-f491-11e8-8967-ccde9a581b97.png)

The final SQL insert contains a mistake (insert string data about company to the column which has date datatype). 
```
INSERT INTO contact (create_date) VALUES (:#company)
```

When I send data to webhook, the data maper add company string to the company input parameters and the last steps throws an exception. In the activity log is shown 'Errors found' but in the log is not the final step which contains this error.:
![screenshot from 2018-11-30 11-15-13](https://user-images.githubusercontent.com/16251792/49283320-b9d55000-f491-11e8-9aff-f07eb5459754.png)

When I delete data maper and I add incorrect value to the SQL as a constant
```
INSERT INTO contact (create_date) VALUES ('RedHat')
```
the error is shown in the log.
![image](https://user-images.githubusercontent.com/16251792/49283998-9ca18100-f493-11e8-90ec-d66e0d2ca9e1.png)
![image](https://user-images.githubusercontent.com/16251792/49284018-a925d980-f493-11e8-89fa-7dc3010cf6fc.png)

Integration: 
[hook-to-db-with-db-export.zip](https://github.com/syndesisio/syndesis/files/2632837/hook-to-db-with-db-export.zip)

**Step to reproduce:**

1. Import and publish integration
2. Run command: (update webhook url according to integration)
```
curl -k -v https://i-webhook-to-db-with-mistake-syndesis.192.168.42.27.nip.io/webhook/test-webhook -d '{"first_name":"John","company":"Red Hat"}' -X POST -H "Content-Type: application/json"
```

3. Look to the activity log

**Comment by heiko-braun** [comment]
@mkralik3 Is it a UX problem or does it help the QE workflow?

**Comment by mkralik3** [comment]
In my point of view, it is a UX problem because it is really confusing for the users when UI shows _Errors found_ but doesn't show any error log as in the other situations.

**Comment by mkralik3** [comment]
I have reopened this issue. In my POV, it should be fixed because it can be very confusing for the users when they see _Errors found_ title; however, no error is in the activity tab.

**Comment by mkralik3** [comment]
Now, it doesn't work without data mapper either. When I use the same integration as in the original description which showed error without data mapper:
![image](https://user-images.githubusercontent.com/16251792/49283998-9ca18100-f493-11e8-90ec-d66e0d2ca9e1.png)
Now, the error log missing in the activity log too:
![image](https://user-images.githubusercontent.com/16251792/58415486-eb188c80-807e-11e9-90d5-f8f812ef6a13.png)

**Comment by mkralik3** [comment]
I change the priority because the error is not shown when it is thrown in the final step.

**Comment by claudio4j** [comment]
@mkralik3 can you review the fix ? it is already merged in master.
