### ISSUE TITLE
Automate the version (link) changes in dict en-GB

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/syndesis#4195]
https://github.com/syndesisio/syndesis/blob/1.6.x/app/ui/src/assets/dictionary/en-GB.json#L332 needs to be automated

**Comment by TovaCohen** [comment]
Will do!

**Comment by gashcrumb** [comment]
Yeah, was thinking about it more and I think driving the version from the config.json could be a bit brittle for this, as with that setting in there someone could think it needs to be updated for minor/patch versions.

**Comment by gashcrumb** [comment]
@TovaCohen No worries BTW!  :-)

**Comment by TovaCohen** [comment]
Okay, so I will take the responsibility to update the version number in the dictionary file as soon as there is a branch for a release. Then I will also take the responsibility to update the version number in the dictionary file on master as soon as the user doc for that release is available on the customer portal. If that's the best solution, then you can close this issue. 

Thanks Stan!
