### ISSUE TITLE
Data Virtualisation in Syndesis

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/syndesis#4203]
The bulk of the work (Teiid part) is tracked in `DINT`: https://red.ht/2G26b1q 

Use this issue to track all syndesis local changes needed to integrate data virt.

**Comment by rareddy** [comment]
@zregvart I have the changes related to bringing in the Data Integration engine into syndesis build are here on this branch [1]. Can you help further refine to suit syndesis if needs any? otherwise, I can also submit a PR then go from there?

[1] https://github.com/rareddy/syndesis/tree/teiid-syndesis

**Comment by zregvart** [comment]
@rareddy the bits in on that branch look good to me, open a PR so we can get it merged, one thing I think would make sense is to have those bits behind a feature toggle, so we users can decide if they wish to deploy them or not...

**Comment by rareddy** [comment]
@zregvart I wanted to add Data Integration to include with a --include an option, but I failed to figure out, as I think this needs to be done in the Operator code, any suggestions?

The next question is, where the target image for the Data Integration needs to be hosted, right now I have it Teiid docker hub, is that good? or should we consider something under "syndesis" in your opinion?

**Comment by gaughan** [comment]
We need the image in the product. Ill start a thread. Once I get image details I can kick off and image request.

**Comment by zregvart** [comment]
> @zregvart I wanted to add Data Integration to include with a --include an option, but I failed to figure out, as I think this needs to be done in the Operator code, any suggestions?

`--include` option in the `tools/bin/syndesis` script or in the template generation stuff in `syndesis/install/generator`?

I think it would be best if we used some sort of service discovery mechanism, I'm assuming that the Komodo server will be running as a separate pod, then from Syndesis operator we can discover that it exists (by reacting on a label for example) and include the necessary configuration.

Let me rope in @astefanutti, @nicolaferraro and @lgarciaaco as our resident Operator gurus.

In the template based installation we can add more code to the template generator to include/exclude it (via a flag I think would be the easiest).

We need to rope in @djcoleman, @cunningt and @orpiske to refine this for the product builds.

> The next question is, where the target image for the Data Integration needs to be hosted, right now I have it Teiid docker hub, is that good? or should we consider something under "syndesis" in your opinion?

I think hosting it on Docker Hub is OK for upstream, as @gaughan noted we need another image build in the product, that will have it's own coordinates.

**Comment by zregvart** [comment]
Well, actually the operator will be installing Komodo, so it would be a feature toggle on the Syndesis custom resource.

**Comment by rareddy** [comment]
@zregvart I submitted the PR at https://github.com/syndesisio/syndesis/pull/5358 for review and approval

Improved little bit by adding a flag in the templates, such that when "--include-data-integration=false" to "run.sh" will not generate the templates in the `syndesis.yml` file. The flag by default is set to true. What I could not figure out is who initiates the `run.sh` to generate `syndesis.yml` in the scripts, that may be some help I need if this is not invoked manually.

**Comment by zregvart** [comment]
We run `run.sh` manually and via the `pre-commit` script for those that have [pre-commit](http://pre-commit.com/) installed.

**Comment by phantomjinx** [comment]
@zregvart 
So that implies that whatever is in syndesis.yml is always unnconditionally going to be created. 'Tis interesting since it is similar to a problem I'm trying to solve in #5330 where the todo components are to be made optional & disabled if required. Would be good to have a steer on a uniform methodology of making components in syndesis.yml optional (or in fact making syndesis.yml dynamically generated dependent upon switches provided).
All comments gratefully received.

**Comment by rareddy** [comment]
@zregvart @phantomjinx  Looks like release build runs that way by script, I have seen references in the code. Since the build is run through a script couldn't same be followed here? The issue could be it will bring in lot more command line options, but these could be for expert view IMO.

**Comment by vhalbert** [comment]
Since DV is TP, i believe the default for --include-data-integration should be false, so that the default installation would be what they would put into production

**Comment by heiko-braun** [comment]
Making it an optional installation component sounds right to me.

**Comment by phantomjinx** [comment]
@rareddy @zregvart 
What I have understood so far:
1. The syndesis [tool](https://github.com/syndesisio/syndesis/tree/master/tools/bin) is a set of shell scripts that take various switches & parameters
2. On executing `syndesis install -p syndesis` the scripts
 - Download & deploy the syndesis-operator -> ` oc create -f $SYNDESIS/install/operator/deploy/syndesis-operator.yml`
 - Execute the syndesis operator by running:
```
syndesis=$(cat << EOT
apiVersion: "syndesis.io/v1alpha1"
kind: "Syndesis"
metadata:
  name: "app"
spec:
EOT
)
echo "${syndesis}" | cat | oc create -f -
```
3. The syndesis-operator then takes over the work of installing the various images and deploying their instances. The syndesis-operator is a go application that takes a single argument: `-template /conf/syndesis-template.yml` where the template is a copied-in version of [syndesis.yml](https://github.com/syndesisio/syndesis/blob/master/install/syndesis.yml).

I have been trying to understand how to get a parameter/flag into syndesis-operator that would control disabling installation of the todo app & looks like DataVirt has the same problem. At the moment, my current investigation is around the [addons](https://github.com/syndesisio/syndesis/tree/master/install/addons) directory. It maybe the case that putting the necessary templating syntax from syndesis.yml into the addons directory would allow the more optional approach. However, mileage only small at this stage.

@rhuss

**Comment by zregvart** [comment]
> Looks like release build runs that way by script

Yes it does, though [our quickstart](http://syndesis.io/quickstart/) references the `syndesis.yml` directly, so keeping it in sync would be a good idea. That is, at least until we remove all templates and go all in on the operator.

**Comment by zregvart** [comment]
@phantomjinx I like the idea of taking out bits of the template and placing them in the `addons` directory, we need to make all tooling aware of this: the `syndesis` script, operator, syndesis-install and any bits that perform productization.

**Comment by rareddy** [comment]
@zregvart @phantomjinx One difference with Data Integration is since it is TP, I want to have a way to exclude in extreme situations from build (like we can't deliver and not to hold up the 7.4 release ) vs a truly an optional module like todo.

**Comment by zregvart** [comment]
Way back when we generated two templates `syndesis.yml` and `syndesis-privileged.yml ` using that run.sh (trivial hack to do):

https://github.com/syndesisio/syndesis/blob/571f33d782e6b2d397f33f7b64087663fabbc401/install/generator/run.sh#L23-L24

Perhaps we can do the same in this case as a first and easiest step?

**Comment by rareddy** [comment]
See in future when we move off of templates then it can be completely driven by Operator and CRD definitions perhaps until then we need to resort to these add-ons or flags during the template code generation

**Comment by heiko-braun** [comment]
@rareddy I need to talk to @gaughan, but I think we can skip templates for datavirt right from the beginning and solely base the install on operators

**Comment by phantomjinx** [comment]
@rareddy 
I think the [addons](https://github.com/syndesisio/syndesis/tree/master/install/addons) directory is CRD defintiions rather than templates. They are [loaded](https://github.com/syndesisio/syndesis/blob/master/install/operator/pkg/syndesis/addons/install.go#L13) into the syndesis-operator app programatically & each one [installed](https://github.com/syndesisio/syndesis/blob/master/install/operator/pkg/syndesis/action/install.go#L128).

**Comment by rareddy** [comment]
@zregvart, since you worked on this, can I assign this to you, so that you can mark resolved?

**Comment by zregvart** [comment]
You can, though we have still outstanding bits to finish this epic in #5475 that @rkorytkowski has a PR open. So it's not technically done :smirk:

**Comment by chirino** [comment]
Please peek at https://github.com/syndesisio/syndesis/issues/5433#issuecomment-515579533, the komodo addon has been converted into an operator template and is enabled via the syndesis CR.

**Comment by mastepan** [comment]
closing as all underlying issues have been already closed
