### ISSUE TITLE
Connector data shape inspections not generated in clean build

### ISSUE THREAD

**Issue by christophd** [syndesisio/syndesis#4206]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

When doing a clean build the connector inspections for Java typed input/output data shapes are not generated. 

This is leads to data mapper steps not being able to determine source and target data shapes at runtime. You will get `No source data type was found. Data Mapper requires at least one data type aware step prior to itself` errors when adding data mapper steps to your integrations.

**Comment by christophd** [comment]
I think this is caused by the `generate-connector-inspections` mojo in `connector-support-maven-plugin` Maven plugin. The plugin execution has been linked to the `generate-resources` phase where the required connector `*.json` has not been copied to the classes folder yet.

Before the plugin execution has been bound to the `prepare-package` phase.

**Comment by christophd** [comment]
@zregvart any idea why we have changed the default phase for this plugin execution?

**Comment by christophd** [comment]
I think we should bind the plugin execution to `copy-resources` phase to make sure that the connector meta `.json` has been copied to the classes output directory before the plugin executes. Or go back to `prepare-package` phase.

**Comment by zregvart** [comment]
> I think we should bind the plugin execution to `process-resources` phase to make sure that the connector meta `.json` has been copied to the classes output directory before the plugin executes. Or go back to `prepare-package` phase.

Sounds like an easy fix.

**Comment by christophd** [comment]
Fixed with #4210
