### ISSUE TITLE
Adding data mapper when no previous output shape is provided

### ISSUE THREAD

**Issue by christophd** [syndesisio/syndesis#4207]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Documentation issue or request
</code></pre>

## Description

It seems to me that a data mapper step is only selectable when a previous step in the integration provides some supported output data shape? Why is that? I can imagine a data mapper to be required also when no previous step provides an output shape.

Users may need to map from constant values or properties only, too. When no output data shape has been found in previous steps the data mapping is not displayed even though a mapping is mandatory for the integration to work.

Example Integration: `Timer -> SQL invoke -> Log`

Even in case the SQL invocation specifies placeholders that should be mapped (`insert into todo (task, completed) values (:#task, 0)`) the data mapper is not offered to the user.

I think data mapping step should be available all the time.

**Comment by heiko-braun** [comment]
@syndesisio/backend Any ideas?

**Comment by igarashitm** [comment]
FYI that decision is made in UI code, if we show Data Mapper step to be put with looking at the all previous data shapes.

**Comment by igarashitm** [comment]
Also AtlasMap should not error out when there's no `Source Document`, which is going to be addressed as a part of - https://github.com/atlasmap/atlasmap/issues/604#issuecomment-443002502

**Comment by gashcrumb** [comment]
Nothing will happen on this without some clarification that a decision has been made or an issue raised to actually make the change :-)

**Comment by igarashitm** [comment]
I think now AtlasMap UI opens even if there's no source document. Once Syndesis UI relax the check it would just work.

**Comment by christophd** [comment]
So I think we all agree that it should be possible to use data mapper even if no previous step provides an output shape (also see #4588). So lets turn this into a bug describing that scenario.

**Comment by christophd** [comment]
Same thing came up recently when doing the summit sessions as described in #5408

**Comment by gashcrumb** [comment]
Since I'm in the code now on the react side, I'll add that change to https://github.com/syndesisio/syndesis-react/pull/368

**Comment by gashcrumb** [comment]
When I tried the data mapper with a timer 2 log kinda integration, it didn't initialize properly, so I think it needs a subsequent step to have an input data shape at the moment.  I've gone and taken out the requirement that previous steps have an output data shape.  I wasn't sure about collection support, so I didn't change anything there, but that's easy enough to adjust.

**Comment by zregvart** [comment]
I've tried this on a [Timer to SQL](https://syndesis-legacy.b6ff.rh-idev.openshiftapps.com/integrations/i-LggcXA_e4c8TFQl2NSLz) integration, I can't add the mapper in between those. I can see that the SQL connector has an `inputDataShape`. Was this case covered/considered with this issue?

**Comment by gashcrumb** [comment]
@zregvart I actually only changed this in the react impl as it so happened the discussion was happening right when we were bringing some of this code over, [here's](https://github.com/syndesisio/syndesis-react/commit/0892891c74c94c4841bb2e62015a04d6639683e6) the commit.
