### ISSUE TITLE
Remove 1GB attachment limit on Help -> Support page

### ISSUE THREAD

**Issue by tmielke** [syndesisio/syndesis#4208]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

The Syndesis Help->Support page currently says:

"To obtain support, download diagnostic information through this page and open a request on the Red Hat Customer portal. If the downloaded zip file is less than 1 GB, attach it to the case. For a larger zip file, tell the support team that the zip file is larger than 1 GB and ask for instructions."

This restriction is gone with the announcement of https://access.redhat.com/solutions/3616871.
I guess we can remove the 1GB limit note, the limit is now 250GB and should probably never get reached when collecting this support information.

**Comment by tplevko** [comment]
Verified by QE. Closing
