### ISSUE TITLE
Integration with Operatorhub (within OCP4) 

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/syndesis#4214]
As a user I want to have all Fuse operator integrated with the Openshift 4 Operatorhub, so that I can install Fuse components through these means.

**Comment by heiko-braun** [comment]
@gaughan After talking to @kcbabo we decided to move this into the 7.4 timeframe. Any objections?

**Comment by gaughan** [comment]
sounds good

**Comment by mastepan** [comment]
@heiko-braun anything here for QE?

**Comment by heiko-braun** [comment]
Yes, at least the product operators (APICurito, Fuse Online and Camel K) would need to be verified. Here the task is to use CR1 and try to install any of the three from the embedded operatorhub in OCP4. @tplevko should have more information on the QE requirements
