### ISSUE TITLE
Authentication type basic is currently not supported

### ISSUE THREAD

**Issue by RafiZz** [syndesisio/syndesis#4218]
## This is a problem is related to the BasicAuth type in swagger.json file.

<pre><code>
[ ] Feature request
[X] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
There is such a part in my swagger specification file.
<pre><code>
"securityDefinitions": {
    "basicAuth": {
        "type": "basic"
    }
},
"security": [
    {
        "basicAuth": []
    }
],
</code></pre>

My actions:
1. Click "Create new integration" button on "Integrations" page.
2. Choose "API provider" type.
3. Click 'Choose File", then choose "swagger.json" file. Click "Next" button.
Then in "WARNINGS" I see an unexpected line:
"Authentication type basic is currently not supported"

There is a pull request where this feature has been added.
https://github.com/syndesisio/syndesis/pull/840

What could be the problem?

This is my zipped specification file.
[swagger.json.zip](https://github.com/syndesisio/syndesis/files/2667581/swagger.json.zip)

**Comment by zregvart** [comment]
Hi @RafiZz, there is no support for any kind of authentication in the API provider based integrations in the current release. The PR you linked to we added support for the custom API clients.

In the current version we're relying on 3scale to perform all authentication.

How would use basic authentication? How would you specify the username/password combinations that are allowed to invoke the exposed API?

**Comment by yelizariev** [comment]
@zregvart 
> How would use basic authentication? How would you specify the username/password combinations that are allowed to invoke the exposed API?

I do not quite understand your concerns. There are username\password fields from  [db-2-api-connector example](https://github.com/syndesisio/syndesis-quickstarts/tree/master/db-2-api-connector)

![screenshot-syndesis 192 168 42 211 nip io-2019 07 27-17-24-00](https://user-images.githubusercontent.com/186131/61994417-6c969600-b093-11e9-988b-85634c45d99c.png)

Following question might be related: https://github.com/syndesisio/syndesis-quickstarts/issues/31

**Comment by zregvart** [comment]
@yelizariev this question is about the API provider functionality, this is the functionality of providing API, i.e. implementing API services by designing integration flows in Syndesis. The issue you referenced is with using custom API connectors that act as clients, i.e. can be used to invoke 3rd party APIs from integration flows.

The state of API provider functionality is the same, we do not have any support for security that can be specified or implemented via Syndesis for API providers. For this we rely on the integration with [3scale](https://3scale.github.io/).

**Comment by yelizariev** [comment]
I'm a bit confused with those two types of API. I'll try to dive deeply into the subject then and come back. I have a feeling that my concerns are just from misunderstanding. I'll let you know. Thanks.
