### ISSUE TITLE
bash update_ocp.sh --version not working

### ISSUE THREAD

**Issue by tmielke** [syndesisio/syndesis#4227]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Following the [10.6. Upgrade Fuse Online on OCP](https://access.redhat.com/documentation/en-us/red_hat_fuse/7.2/html/integrating_applications_with_fuse_online/how-to-install-on-ocp_ug#upgrade-on-ocp_ocp) documentation 

in step 4 I am told to run
<code>
$ bash update_ocp.sh --version
</code>
but the script fails with 
<code>
update_ocp.sh: line 385: /Users/tmielke/Downloads/fuse_online_config.sh: No such file or directory
</code>

**Comment by heiko-braun** [comment]
Issue moved to [syndesisio/fuse-online-install #66](https://github.com/syndesisio/fuse-online-install/issues/66) via [**ZenHub**](https://www.zenhub.com/)
