### ISSUE TITLE
SPIKE: Investigate the removal of Springboot for integrations (runtime)

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/syndesis#4232]
In order to simplify the usage of Camel-K, the removal of SpringBoot from integrations runtimes could help a lot. This would allow us to prevent version mismatches and the potential need to support different SpringBoot versions. 

This task is about investigating the feasibility and effort to make it happen in order to take a decision for 7.3.

**Comment by lburgazzoli** [comment]
We may think to split the integration runtime bits related to spring in a "starter" artifact so we can include the bits that are needed according to the environment.

**Comment by lburgazzoli** [comment]
@KurtStam as follow up of our conversation I would expect that we end up with the following modules: (naming is just an indication)

- integration/runtime
- integration/runtime-adapter-spring-boot
- integration/runtime-adapter-camel-k

The syndesis runtime bits should be part of integration/runtime and it should have no dependencies on spring-boot or camel-k whereas the runtime-adapter-* have the dependencies on the target runtime.

This would allow us to:
- deploy "classic" integration by including runtime-adapter-spring-boot
- deploy camel-k integration including  runtime-adapter-camel-k

**Comment by KurtStam** [comment]
@lburgazzoli makes sense to me. As a first step, and before splitting things out, I'm looking into removing spring-boot from the current integration/runtime first or at least from the RouteBuilder.

**Comment by KurtStam** [comment]
![springboot-runtime](https://user-images.githubusercontent.com/35576/51752287-267d5d00-2085-11e9-8d62-4142ce9a2e3b.png)

**Comment by tplevko** [comment]
As this is was a refactoring task, QE work is probably not necessary on this. Closing.
