### ISSUE TITLE
Unable to validate Salesforce connection after importing an existing integration

### ISSUE THREAD

**Issue by weimeilin79** [syndesisio/syndesis#4248]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

I tried to import an [existing Integration](https://github.com/weimeilin79/fuseonlinewine/blob/master/fuse-online-exports/account-export.zip) I built earlier, and of the integration is showing I need to re-configure the Salesforce connection by updating it's secrets, 

![image](https://user-images.githubusercontent.com/2534483/50731730-e720b800-1139-11e9-9261-3b5f6fac9f52.png)

So I went ahead and update the OAuth in the setting, and then use the reconnect in the "Connection". The problem is that, after reconnecting, I was not able to VALIDATE the connection (the button is always disabled), so my integration keeps saying my resource needs configuration. The entire import is not usable. 
![image](https://user-images.githubusercontent.com/2534483/50731741-2bac5380-113a-11e9-91d6-fd98d73c2b3c.png)
 
I am sure my OAuth setting is correct, because I was able to create a new Salesforce connection with the same setting. 

![image](https://user-images.githubusercontent.com/2534483/50731752-8ba2fa00-113a-11e9-84fc-2cbb90c53843.png)

**Comment by weimeilin79** [comment]
Same thing happens to Gmail Connector as well.

**Comment by zregvart** [comment]
Encryption of properties is done with a site-specific secret key. This can caused by either re-installing Syndesis and having a new key generated or importing an exported integration between environments that have different keys.

Until this is addressed with something like #3423 you need to update all secret properties (Client Secret in the case of Salesforce and Gmail) and Reconnect the connection.

**Comment by weimeilin79** [comment]
@zregvart I was trying to demo how to hand off an integration from Testing to PROD, the Fuse online environment is definitely different.  And I indeed update the Client Secret for both Salesforce and Gmail, that make sense. My problem is that even when I updated and Reconnect successfully on the two connections, it still shows "THE SECRETE NEEDS TO BE UPDATED".

**Comment by heiko-braun** [comment]
@dhirajsb Can you verify this in the context of the new import / export facilities?

**Comment by dhirajsb** [comment]
@heiko-braun the new import/export public API supports directly setting connection properties by using the target environment's encryption key. But it doesn't address the existing integration export/import API and UI. Doing so would require reworking either the current import/export UI or providing other mechanisms for somehow configuring source/target environment encryption key.

**Comment by heiko-braun** [comment]
@dhirajsb I was wondering if this issues goes away when using the import/export API's. I know that the current  means toi manually export and import are a different story, but if the new facilities don't show this problem, we could recommend using it instead and lower the priority of this issue.

**Comment by dhirajsb** [comment]
@heiko-braun there is no automated workaround for circumventing the manual login OAuth flow that a user must do create login tokens for connectors like Salesforce. 
When we address creating environments with fuse environment variables, this issue could kinda be solved when users could share variables for credentials, perhaps they could then share generated secrets and user won't have to login again after importing. 
@zregvart what do you think?

**Comment by heiko-braun** [comment]
@dhirajsb I think that's not the issue. If I under the comment correctly (see https://github.com/syndesisio/syndesis/issues/4248#issuecomment-451966847) the problem is that even when you update/reconfigure the login tokens the message `"THE SECRETE NEEDS TO BE UPDATED"` remains and a user cannot use the imported integration.

**Comment by dhirajsb** [comment]
Thanks @heiko-braun. So it's a connection update issue after import. I'll dig more tomorrow.

**Comment by dhirajsb** [comment]
@weimeilin79 there are some gremlins when using the export/import mechanism with individual integrations. It retains auto-generated `refreshToken` property, which is simply passed back and forth between the ui and the backend without being updated when the user re-authenticates in new Syndesis environment. 

Ideally, when the user edits the connection in the UI and validates/re-authenticates, it should only retain values entered in the configuration page, and set all other properties like `refreshToken` to null. This could either be done in the UI or the backend. I have opened an issue for the UI side of this in #5762  

The public import API allows users to provide connection properties for the target environment, which takes care of specifying user provided secrets like `password` and `clientSecret`. However, the auto-generated `refreshToken` secret will still run into the issue I described above. 

I'm also looking at possibly avoiding this issue in the backend by dropping properties like `refreshToken` during export/import. But I do not have a good generic solution yet.

**Comment by dhirajsb** [comment]
@weimeilin79 when you were testing this particular issue, were you using the OAuth flow method where you login into Salesforce from Syndesis console or were you directly specifying username and password properties in connection configuration? 

Also, after updating the connections, did you also edit the integration, save it and then try publishing it? This is required due to the way connections are stored as shallow copies in integrations.

**Comment by dhirajsb** [comment]
There are a couple of other issues that are contributing to this one #5582 and #5763 

I also created a PR #5765 to remove auto generated secrets from external environment, to avoid importing stale tokens like `refreshToken'. This will make sure we don't import properties to get rid of later, even if the present UI is not working to refresh OAuth connections.
