### ISSUE TITLE
Apply PF4 markup to Masthead and Vertical Navigation

### ISSUE THREAD

**Issue by amysueg** [syndesisio/syndesis#4249]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
The consoles that are part of the Agile Integration product should share a common look and feel. We'd like to start by applying a common visual theme to the masthead and vertical navigation of the consoles, using underlying PF4 markup and PF3 CSS.

## Expected behavior
Use PF4 markup for the masthead and vertical navigation of Syndesis; apply PF3 CSS styling until all consoles in the Integration product are ready to unveil PF4 styling.

FYI @gaughan @mcoker @jameslau @dongniwang

**Comment by amysueg** [comment]
1. This year we have a goal to move our Integration consoles (Fuse, AMQ, 3scale) to Patternfly4. This will be a gradual adoption and one that we propose to coordinate between the console teams and developers. 
2. To begin the move, we propose an initial milestone to move to a PF4 look and feel for the masthead and vertical navigation of the console UI. And probably the login page as well.
3. Because it is possible for PF4 and PF3 to live together harmoniously in the same application, the recommended approach is to use a PF3 compatibility mode (CSS) but to change the underlying mark-up (HTML) to use PF4.  
4.  When all consoles are ready to adopt the PF4 look and feel, then we can drop the PF3 CSS, and PF4 styling will be applied.

In the case of 3scale, they had *no* Patternfly at all. In that case,  the approach was that Michael assisted Thomas to adopt PF3 HTML and CSS styles to produce a PF3 look and feel that more or less matches the existing PF3 UI in Fuse Online and in OpenShift. They had initially considered that 3scale would write the PF4 HTML and then apply a PF3 CSS to it; I believe that was abandoned when Thomas decided it wouldn't be that onerous to re-write the code for PF4.

**Comment by jameslau** [comment]
Thank you for the clarification @amysueg!

**Comment by gashcrumb** [comment]
> And probably the login page as well.

Note the login page comes from openshift and is out of our control.

**Comment by jameslau** [comment]
Based on recent meetings, we've come to a consensus that the masthead will go forward for 7.3 release with PF4 styling while sitting on top of a PF3 markup (HTML) infrastructure. The vertical navigation will be released at a much later time in 2019. Please ping @amysueg and @dongniwang for further questions and/or comments on the progress for this issue.

**Comment by amysueg** [comment]
Related PR #4578 is merged, closing this one.
Only adding PF4 for Masthead for now, will open a separate issue to address vertical navigation.
