### ISSUE TITLE
Make OpenAPI operation ID mandatory

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#4252]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When we enable editing of OpenAPI specification in the API provider we need to make the `operationId` property mandatory. This will enable us to track what operation was changed/added/removed.

From what I understand Apicurio already validates the uniqueness of [operation ids](https://github.com/Apicurio/oai-ts-core/blob/566fbf6fd607b202d6d9790f46511c480b6daa19/src/validation/2.0/uniqueness.rule.ts#L43-L56). We need to add `operationId` as required by [overriding support for checking mandatory properties](https://github.com/Apicurio/oai-ts-core/blob/566fbf6fd607b202d6d9790f46511c480b6daa19/src/validation/2.0/required-property.rule.ts#L94-L96) or by [adding our own rule to the list of existing rules](https://github.com/Apicurio/oai-ts-core/blob/fbca15d01fb1b8f75453867d6630af42871f1288/src/visitors/visitor.base.ts#L214-L218).

When a new operation (path in Apicurio terminology) is added we need to assign a unique `operationId` to it. Most likely we need to override `createNewPathCommand` flow.

Related to #3459, cc @EricWittmann

**Comment by EricWittmann** [comment]
A feature that is on the Apicurio roadmap is the ability to do the following with respect to validation:

1) Set the severity of the various validation rules (i.e. info, warning, error, ignore)
2) Include custom validation rules

Once that feature is available, the validation piece of this should be easy.

As for customizing the editor to generate an `operationId` whenever an operation is created, that's trickier and will require some consideration.

Note that it's not when creating paths (e.g. /resources/{resourceId}), but rather when creating operations for a path (e.g. GET, PUT, POST).  The latter is what can have a unique `operationId`.

**Comment by zregvart** [comment]
The best we can do currently is to maintain the warning currently issued when an operation doesn't have an `operationId` and generate the `operationId` when processing on the backend.

@TovaCohen I think we should document the need for `operationId` being specified and unique in an OpenAPI document as it allows round tripping between the embedded Apicurio editor and the integration flows.

**Comment by EricWittmann** [comment]
@zregvart I still think we should implement the Syndesis rules in `oai-ts-core` so that we can show appropriate errors/warnings in the Apicurio embedded editor.

Note that the latest version of Apicurio editor supports customizing the severity levels of all validation rules, which would be very useful for Syndesis I think.

**Comment by EricWittmann** [comment]
Also note: if someone were to simply **document** the rules, I'd be happy to actually implement them in `oai-ts-core`.

**Comment by zregvart** [comment]
@EricWittmann should I open an issue for this in `oai-ts-core`?

**Comment by TovaCohen** [comment]
How's this for the user doc. 

Ensure that each operation has a unique `operationId` property within the OpenAPI document. This allows the Apicurio editor and the integration flows to remain synchronized. 

In 7.2, we told the user that the only time they could edit the OpenAPI document was when they created the API provider integration. Does this change for 7.3?

**Comment by zregvart** [comment]
@TovaCohen the proposed text looks good. In 7.3 we're adding the ability to edit the specification and the changes there will be reflected in the integration.

The epic for this is in #3775 the design document is [here](https://redhat.invisionapp.com/share/BHPQXBH6W8Y) and there are few more issues you can follow for UXD changes (#4260) and other enhancements in the API provider (#4018).

There's a demo recording for the specification edit functionality [here](https://drive.google.com/open?id=1uLA8zsn9TUdVzZHWepR-9Hx43xKsK5ZF).

**Comment by TovaCohen** [comment]
thanks @zregvart - I'll update the doc accordingly. I'll be working on the API Provider user doc in the next sprint and make it available for review.

**Comment by TovaCohen** [comment]
If someone can capture the validation rules, please let me know and I'll be glad to document them in the user doc.
