### ISSUE TITLE
Support data shape change

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#4253]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

When the user modifies the OpenAPI specification of a API provide based integration in a way that will modify the data shapes, a mapping step might need to be updated. 

Currently we get an error when opening the mapping step (`Could not find field from document for mapped field ...`).

We need the ability to let the user know that the data shape was changed in a incompatible way. If the data shape was changed but in a compatible way I don't think we need to notify the user for that.

I think this is functionality needs some support in Atlasmap.

Overall it it could work like this:
 - given an integration,
    - go through all the flows of an integration
      - go through all mapping steps of a flow
         - check if the existing mapping is still valid given the updated data shapes

I think we need to notify the user both in the operation (flow) list (perhaps a exclamation icon with a tooltip saying that mapping steps need updating) and within the integration editor (perhaps a exclamation icon next to the mapping step icon in the integration view pane).

This functionality is also beneficial to other use cases, for instance when user defines the data shape (e.g. when using message queue connection) and later, after mapping, changes that data shape.

cc @igarashitm, @syndesisio/uxd

**Comment by igarashitm** [comment]
An option would be:
1. Check Document ID and its schema which is already used in mappings
   1. If any of already in use Document is missing, discard related mapping entries
   1. Show warnings about discarded mapping entries
1. Check all the fields participating in mappings
   1. If any of field path doesn't exist or field type is different, discard that specific mapping entry
   1. Show warnings about discarded mapping entries

This would be a bigger enhancement, basically need to walk through all the schemas just like inspection but for another purpose. Then it ends up with the same problem with on-demand inspection, that we need some metadata registry for Java Documents (classes) via syndesis-meta. Note that currently we rely on offline inspection to avoid all the connector/extension classes loaded in syndesis-server classpath.
