### ISSUE TITLE
Support deleting operations

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#4255]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

When editing OpenAPI specification of a API provider based integration, user can opt to delete an operation. Deleting the operation should result in the removal of a flow from the integration.

We need a new endpoint on the backend to receive the updated OpenAPI specification of the integration and update the integration.

The frontend needs to invoke that endpoint when the user is done editing the OpenAPI specification in Apicurio and reload the integration.

**Comment by asmigala** [comment]
Verified with CR3
