### ISSUE TITLE
UX design for Data Virtualization in Syndesis

### ISSUE THREAD

**Issue by amysueg** [syndesisio/syndesis#4261]
## This is a...
<pre><code>
[x] Feature request
</code></pre>

## The problem
Data Virtualization will be integrated into Syndesis to allow the citizen integrator to create and manage virtual databases (VDBs) and data views. Functionality from the existing Beetle Studio will be reconsidered as part of this design.

## Expected behavior
The integration of this functionality within Syndesis should feel native and seamless, and should present a consistent interaction design with other parts of the Syndesis project.

@junezhang @deernano @nding-anges @dongniwang - created this after the Syndesis sprint planning meeting in order to track the design work for DV integration.

**Comment by deernano** [comment]
Data Virtualization Low-fi mockups Version 1:
https://redhat.invisionapp.com/share/J3Q13OSDBSR#/341533929_dv

**Comment by dongniwang** [comment]
Closing this issue now since we're tracking things in JIRA.
