### ISSUE TITLE
SPIKE: Investigate how to install camel-k operator 

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#4262]

**Comment by rhuss** [comment]
A first implementation for a fixed version of Camel-K (0.2.0) is implemented via #4347.

It's implemented by downloading the "kamel" binary which does then the hard work.

Still todo:

* Make Camel-K version configurable.
* On Camel-K side: Create daily images/builds with a 'latest' tag. Allow the "kamel" to specify the tag to use for the operators.
* Add "--camel-k" to "syndesis build". This should build the operators only like its done for Syndesis. It is expected that Camel-k is checkout within GOPATH.

**Comment by rhuss** [comment]
@lburgazzoli I think the first point I can still add for this sprint, but "syndesis build" and daily camel-k builds need to be moved to the next sprint.

**Comment by lburgazzoli** [comment]
fine with me, can you open the related issues ?

**Comment by rhuss** [comment]
Opened #4380 

Not sure where to open the issue for daily camel-k builds. This should be probably on the Camel-K side ?

**Comment by lburgazzoli** [comment]
Open it on camel-k and add a link to the issue here so we can track it as part of the epic

**Comment by rhuss** [comment]
btw, what do I have to do to become a committer for Camel-K ? (except for submitting some more code ;-)

**Comment by oscerd** [comment]
> btw, what do I have to do to become a committer for Camel-K ? (except for submitting some more code ;-)

You need to submit more code on Camel and Camel-K :-)

**Comment by rhuss** [comment]
Everythins done so far and committed.
