### ISSUE TITLE
Hit github rate limit

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis#4271]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Documentation issue or request
</code></pre>

## Description

@oscerd has it this one earlier today:

```
-- Checking if requested OpenShift version 'v3.10.0' is valid ...
Hit github rate limit: GET https://api.github.com/repos/openshift/origin/releases/tags/v3.10.0: 403 API rate limit exceeded for 79.xxx.xxx.xxx. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) [rate reset in 8m32s]
FAIL
```

The error is clearly all up to GitHub and might pop up depending on the user/developer traffic but also, something that can depend of specific network topologies ( a shop with a single outgoing ip can hit this)

This is the workaround I'm aware of. 
```minishift config set skip-check-openshift-release true```

I think we should document this or entirely bring this into our defaults.

**Comment by gashcrumb** [comment]
You can also set an auth key that minishift will use which ups the accepted rate limit -> https://docs.okd.io/latest/minishift/troubleshooting/troubleshooting-getting-started.html#github-api-rate-limit-exceeded
