### ISSUE TITLE
Validate OAuth access using OpenShift ServiceAccounts for public APIs such as import/export

### ISSUE THREAD

**Issue by dhirajsb** [syndesisio/syndesis#4273]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

OpenShift serviceaccounts should be able to access backend public APIs. This should provide the cookie that OpenShift needs using the serviceaccount itself. 
Might need to filter access to the Server pod from within OAuth proxy, to ensure that only public facing APIs can be accessed from the Server pod.

**Comment by rhuss** [comment]
If I understand the mechanics of oauth-proxy right, there are [two ways](https://github.com/openshift/oauth-proxy/#delegate-authentication-and-authorization-to-openshift-for-infrastructure) how the proxy can be operated:

* [Limiting access to really users](https://github.com/openshift/oauth-proxy/#limiting-access-to-users) which delegates to OpenShift SSO for authentication, verifies the SSO token send in the cookie and authenticates by checking whether the user is allowed to perform a certain API call (like listing all pods in a certain namespace). This is how we currently operate the oauth-proxy.

* [Verifying an SA token](https://github.com/openshift/oauth-proxy/#delegate-authentication-and-authorization-to-openshift-for-infrastructure) which takes the bearer token, verifies it and checks whether a certain API call is performed. This mode can be enabled via `--openshift-delegate-urls`. With this mode, we can just use an SA token, extracted from the cluster, for the import/export.

If I understand correctly, both options are mutually exclusive. So the only solution for us would be to run two oauth-proxy instances, one for doing the SSO authentication for regular users, and one for allowing access with an SA.

Considering that the oauth-proxy does not each up many resources, I think this could be a reasonable solution.

Any thoughts?

**Comment by oscerd** [comment]
I don't know if we may have a better solution.. so I think it's fine.

**Comment by oscerd** [comment]
@dhirajsb what do you think?

**Comment by oscerd** [comment]
Can I have a feedback about this?

**Comment by paoloantinori** [comment]
As long as we don't have any real alternative to consider, I think that the only next step is trying to validate Roland proposal and see if it works.
I don't think that the impacts of having a second instance of oauth running is that impacting, but other than that, I haven't heard any alternative option.

My suggestion is to start exploring this setup while still checking if anyone can come up with a better solution.

Adding @zregvart and @chirino to this conversation, to hear their pov.

**Comment by chirino** [comment]
This looks like a good approach to me.

**Comment by dhirajsb** [comment]
@oscerd yeah, this approach works for us for now. It's highly likely that our security requirements become more complex in the future, when we want to support RBAC. But this should be good for now.

**Comment by oscerd** [comment]
I didn't have the time to look at this during this week. I hope to have the time next week.

**Comment by dhirajsb** [comment]
@oscerd did you get a chance to try this configuration yet?

**Comment by oscerd** [comment]
I didn't find the time yet

**Comment by heiko-braun** [comment]
@syndesisio/backend Anybody able to help out with this?

**Comment by dhirajsb** [comment]
@heiko-braun I'll be testing this configuration today since I have the backend work done for the initial version

**Comment by heiko-braun** [comment]
@dhirajsb ok, great.

**Comment by dhirajsb** [comment]
@rhuss I edited the local oauth-proxy in my enviroment to run in the SA token mode by changing the args to the following:
```
      - args:
        - --provider=openshift
        - --client-id=syndesis-syndesis
        - --client-secret=U8jwrxkTAyWVGO0TUJO7O0EOIjJ0KYEwuIuPIkjDLMKLvDfb12CuxG8WAr311OoN
        - --upstream=http://syndesis-server/api/v1/public/
        - --tls-cert=/etc/tls/private/tls.crt
        - --tls-key=/etc/tls/private/tls.key
        - --cookie-secret=$(OAUTH_COOKIE_SECRET)
        - --pass-access-token
        - --skip-provider-button
        - --skip-auth-regex=/logout
        - --skip-auth-regex=/[^/]+\.(png|jpg|eot|svg|ttf|woff|woff2)
        - --skip-auth-regex=/api/v1/swagger.*
        - --skip-auth-regex=/api/v1/index.html
        - --skip-auth-regex=/api/v1/credentials/callback
        - --skip-auth-regex=/api/v1/version
        - --skip-auth-preflight
        - --openshift-ca=/etc/pki/tls/certs/ca-bundle.crt
        - --openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        - --openshift-delegate-urls={"/api/public":{"namespace":"syndesis","resource":"pods","verb":"get"}}
```

I also had to add a new serviceaccount to run the proxy deploymentconfig:
```
      serviceAccount: syndesis-public-oauthproxy
      serviceAccountName: syndesis-public-oauthproxy
      volumes:
...
```
This serviceaccount had to be granted the following role:
```
oc adm policy add-cluster-role-to-user system:auth-delegator system:serviceaccount:syndesis:syndesis-public-oauthproxy
```

But, I'm still getting a login screen as a response (which is obviously wrong) when trying to connect using a curl command like below, where the bearer token is a token secret from the sa:
```
curl -k -L -H "Authorization: Bearer <super-long-token>" https://syndesis-syndesis.192.168.64.41.nip.io/api/v1/public/releasetags/fake-tag
```

Any idea what's going on? Did we ever bypass the login screen for regular oauth-proxy flow?

**Comment by dhirajsb** [comment]
Made some progress, the `openshift_delegate_urls` had a typo, needed to add `--approval_prompt=auto` and had to give edit permission to my test sa. 
Now it's hitting the server, but throwing the following error:
```
{"timestamp":1548408064049,"status":401,"error":"Unauthorized","message":"Authentication Failed: No AuthenticationProvider found for org.springframework.security.web.authentication.preauth.PreAuthenticatedAuthenticationToken","path":"/api/v1/public/releasetags/fake-tag"}
```
Will continue to investigate tomorrow.

**Comment by dhirajsb** [comment]
Aha, tried one last thing before going to bed and it's working now, had to set `--pass-user-bearer-token`. 
Will continue testing tomorrow. @rhuss I'll need help to get this configuration into a syndesis-public-oauthproxy container. I tried editing the mustache templates, but the operators seem to be independent of those, or more likely I'm missing some intermediate step.

**Comment by zregvart** [comment]
Careful, `--pass-user-bearer-token` is not part of the productised `oauth-proxy`.

**Comment by dhirajsb** [comment]
@zregvart can you point me to the source of that information?

**Comment by zregvart** [comment]
http://post-office.corp.redhat.com/archives/openshift-sme/2018-August/msg00213.html

**Comment by dhirajsb** [comment]
https://imgflip.com/i/2sfwbx

**Comment by dhirajsb** [comment]
@rhuss can you review the oauth proxy template I've added to https://github.com/syndesisio/syndesis/pull/4344 ?

**Comment by rhuss** [comment]
@dhirajsb sorry for being late to the party again, but I will PR #4344 soonish.

**Comment by heiko-braun** [comment]
@dhirajsb Moving this to the `Done` column, is it correct?

**Comment by dhirajsb** [comment]
Yes
