### ISSUE TITLE
Add producer elements to the odata connector

### ISSUE THREAD

**Issue by phantomjinx** [syndesisio/syndesis#4281]
Adds functionality to the odata connector to create, update and delete data from an odata service.

**Comment by gaughan** [comment]
Plan to work on this in 7.3?

**Comment by phantomjinx** [comment]
@gaughan 
Now that the consuming odata is finally finished, I am moving over to this now. Should be straight forward since I know my way around the olingo components so shouldn't be too long. Might manage to get it in before the end of Feb but see how I go.

**Comment by gaughan** [comment]
Awesome thanks, plan it to have odata as TP in 7.3

**Comment by phantomjinx** [comment]
Hey @christophd, can you advise on the following. 
re. Collection Support

Have built an integration to test OData Create-Entity.
- SQL Invoke -> SampleDB
- Split
- Data Mapper -> maps first_name/last_name to Person.name
- OData Create -> Person resource selected and thus DataShape is json-schema for Person entity type

Starting this in OS, it fails because the result of the split provides a message.in.body of an ArrayList. This ArrayList happens to contain a single result from the SQL invoked query. At the moment, I have not modified the body using a Customizer so the ArrayList passes through all the way to the camel.Olingo4Producer. Unfortunately, the producer expects an object of either an olingo4.ClientEntity or a json String, but not an ArrayList, hence throws exception.

Therefore, would you mind any insights into:
1. Is the integration flow correct in that once split, potentially there are a number of results, ie. user wants to create several Persons using odata-create and not just one, so therefore odata-create should handle a list of results and not just expect one?
2. Alternatively, if an ArrayList comes in, should the OData Customizer simply handle it and replace the body with the first element of the list (only expects single value)?

**Comment by christophd** [comment]
I doubt that the split provides a body of type ArrayList. What makes you think that it is doing that? 

The data mapper might create a single element list in case the target is typed as a collection. This would be then the input shape of the odata create connector. Is that shape a json-schema of type array?

**Comment by christophd** [comment]
> 1. Is the integration flow correct in that once split, potentially there are a number of results, ie. user wants to create several Persons using odata-create and not just one, so therefore odata-create should handle a list of results and not just expect one?

From your previous descriptions I assume that the odata camel component does not support multiple Persons in a single create operation. So connector customizer is not able to pass in the collection of Persons. So you need to create one record after another using the split.

**Comment by christophd** [comment]
> 2\. Alternatively, if an ArrayList comes in, should the OData Customizer simply handle it and replace the body with the first element of the list (only expects single value)?

I think with the odata create connection input shape defining a proper single element shape you are pretty save to not get any collection form a data mapper. So if you want to double check you can add some auto conversion of Lists in the customizer but I would only support single element collections and in case multiple elements are provided throw some exception. WDYT?

**Comment by phantomjinx** [comment]
> I doubt that the split provides a body of type ArrayList. What makes you think that it is doing that?
> 
> The data mapper might create a single element list in case the target is typed as a collection. This would be then the input shape of the odata create connector. Is that shape a json-schema of type array?

Yeah, I agree. The first single element of an ArrayList<String> is the json instance
`[{"Name":"Joe Jackson","Description":"Red Hat"}]`

So it is the data mapper that inserts the results into the ArrayList. At the moment, the json-schema is typed as a [collection schema](https://github.com/phantomjinx/syndesis/blob/odata-connector-wip/app/connector/odata/src/main/java/io/syndesis/connector/odata/meta/ODataMetaDataRetrieval.java#L114). This might be the issue at hand?

@christophd

**Comment by christophd** [comment]
@phantomjinx yes, that's it! if you set this to the single element schema it should work as expected

**Comment by christophd** [comment]
Just a side note: The Log step is adding `[]` around the message body. So do not get confused with those brackets in the activity log output as they are not coming from the actual message body.

**Comment by phantomjinx** [comment]
> Just a side note: The Log step is adding `[]` around the message body. So do not get confused with those brackets in the activity log output as they are not coming from the actual message body.

No worries. I got the body from debugging via Eclipse rather than the log.

**Comment by phantomjinx** [comment]
@christophd 
Up n running and workflow working as expected, ie. expects 1 entity as json-schema and creates 1 entity in odata service. Thanks!
