### ISSUE TITLE
Extensions tab displays "Ignite Help" and links to 7.1 doc

### ISSUE THREAD

**Issue by TovaCohen** [syndesisio/syndesis#4283]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

In my Fuse Online 7.2 evaluation, the Extensions tab displays "Ignite Help" as a label for a link to doc for developing extensions. The target of the link is 7.1 doc. 
In the Syndesis staging site, the label is "Syndesis Help" and the link target is correctly to the 7.2 doc. 

## Expected behavior

For the downstream product, this label should be "Fuse Online Help". 
The target link should be to the 7.2 doc:
https://access.redhat.com/documentation/en-us/red_hat_fuse/7.2/html-single/integrating_applications_with_fuse_online/index#developing-extensions_custom

## Screenshot

![image](https://user-images.githubusercontent.com/25067106/51186620-07721480-18a8-11e9-98de-b067a8ed10e7.png)

Also, the Customizations > API Client Connectors tab displays "Ignite" in the description in the Fuse Online 7.2 evaluation environment. In the Syndesis staging site, this description has "Syndesis" as the product name. 

![image](https://user-images.githubusercontent.com/25067106/51186961-d0503300-18a8-11e9-9809-8746cb1f77b4.png)

## Tasks involved / Steps to Reproduce

1. Open a Fuse Online 7.2 evaluation environment.
2. Click Customizations to see "Ignite" in the description. 
3. Click the Extensions tab to see "Ignite" in the link.

**Comment by gashcrumb** [comment]
This will ultimately be fixed via the fix for https://github.com/syndesisio/syndesis/issues/4284

**Comment by gashcrumb** [comment]
Well, at least the "ignite" bit, the doc links I think were already patched on the 1.5.x branch but correct me if I'm wrong, thanks!

**Comment by TovaCohen** [comment]
In my Fuse Online 7.2 evaluation, which I just obtained last week, all the links to doc are still to 7.1 versions. I remember that we updated this very late.

**Comment by TovaCohen** [comment]
Thanks for fixing the product name, Stan!

**Comment by gashcrumb** [comment]
Yeah, maybe we just haven't actually patched it yet.  I'll keep an eye out for it, am releasing 1.5.10 which will have all of your updates as well.
