### ISSUE TITLE
Update product name in config map template

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#4284]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
The UI config map still has `Ignite` for the app name as the product name, it should be `Fuse Online`.

**Comment by tplevko** [comment]
Verified by QE - the template is updated. QE will verify the presence of correct product name with the first productized build.
