### ISSUE TITLE
[camel-k] expose metrics to Prometheus

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#4290]
see https://github.com/apache/camel-k/issues/82

**Comment by rhuss** [comment]
@astefanutti you moved that to review, is there already a PR which we can review ?

**Comment by astefanutti** [comment]
Ready for review at https://github.com/apache/camel-k/blob/3c3e2502808c8b93f728c1d3ae5e94b8ad110741/pkg/trait/prometheus.go

**Comment by mastepan** [comment]
QE ignore. Not testable in Syndesis.
