### ISSUE TITLE
Refactor integration editor's current flow service

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#4294]
As part of supporting the API provider enhancements we need to refactor the current flow service.  Currently any changes done to the integration are *mostly* handled by this guy in one event handler function.

Planning on pulling out each block of code in the event handler into separate static functions so it's easier to reuse that logic elsewhere.

Also as part of this I'll verify that there aren't other controllers in the editor that make changes to the integration object directly outside of the current flow service, cases like that should really be refactored out, and that logic should also follow the same pattern as above.

@riccardo-forina FYI, and feel free to add any other concerns that I should be aware of.

**Comment by gashcrumb** [comment]
@riccardo-forina wonder, think it'd be helpful to also extract out functions like `getSubsequentConnections` or `getSubsequentSteps` etc?

**Comment by riccardo-forina** [comment]
yeah, I think so! if it's easy to do I mean

**Comment by gashcrumb** [comment]
Almost done, I want to get the current flow functions I mentioned previously and I also spotted some code in some of the controllers that I think would be good to extract out as well.
