### ISSUE TITLE
[camel-k] [syndesis-extensions] SPIKE : investigate how to share extensions between syndesis and camel-k

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#4297]
We could leverage

- s3 compatible object storage
- ~~a persistent volume~~
- a nexus and upload extensions as standard artefacts
- ~~a maven like interface on top of our filestore~~
- etc

**Comment by lburgazzoli** [comment]
See also: https://github.com/apache/camel-k/issues/1227

**Comment by Delawen** [comment]
I'm going to close this as "won't fix" by now.

Extensions will not be considered as part of Syndesis 2.x until we find a good way of including them. We want to use Camel-K and drop spring-boot, so adding external dependencies would be out of scope by now.
