### ISSUE TITLE
[camel k] [syndesis-extensions] include information about extension packaged dependencies

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#4298]
We do include information about what dependencies are required by the extension but not what dependencies the extension brings in.

**Comment by Delawen** [comment]
I'm going to close this as "won't fix" by now.

Extensions will not be considered as part of Syndesis 2.x until we find a good way of including them. We want to use Camel-K and drop spring-boot, so adding external dependencies would be out of scope by now.
