### ISSUE TITLE
[camel k] support for dependencies archive 

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#4299]
see:
- https://github.com/apache/camel-k/issues/334
- https://github.com/apache/camel-k/issues/1227

**Comment by Delawen** [comment]
I'm going to close this as "won't fix" by now.

Extensions will not be considered as part of Syndesis 2.x until we find a good way of including them. We want to use Camel-K and drop spring-boot, so adding external dependencies would be out of scope by now.
