### ISSUE TITLE
Since Time in the metrics tab sometimes shows actual time

### ISSUE THREAD

**Issue by mkralik3** [syndesisio/syndesis#4303]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
The metrics tab shows a date since the integration is active in the uptime section. But when I refresh the page (press F5) more times, sometimes the date is the same as the actual date which is incorrect because uptime is more than 0 minutes (e.g. 4minutes).

Integration: 
[Webhook to DB-export.zip](https://github.com/syndesisio/syndesis/files/2768786/Webhook.to.DB-export.zip)

![output](https://user-images.githubusercontent.com/16251792/51321437-0b966180-1a63-11e9-8f86-df9e7bda2abe.gif)

In video:
e.g.
Actual time 14:17 , uptime 4 minutes, Since 14:12
refresh ->
Actual time 14:17 , uptime 4 minutes, Since 14:12
refresh ->
Actual time 14:17 , uptime 4 minutes, Since **14:17**   (Which is invalid)

**Comment by gashcrumb** [comment]
I've not been able to reproduce this here locally.  It'd be good to see the network responses from the backend if possible from the metrics endpoint to help narrow it down, as mentioned in #4304

**Comment by mkralik3** [comment]
All responses are the same. It looks like an issue with UI.

**Comment by gashcrumb** [comment]
Cool thanks!  Last question, after reproducing does the value eventually reset itself after like 10 to 20 seconds?  Same question for #4304 actually.

**Comment by gashcrumb** [comment]
This might be worth checking with the fix applied in #4384 if you don't mind.

**Comment by mkralik3** [comment]
No, it will remain to the next refresh.
Yes, I am still able to reproduce it but much fewer times as you can see:
![output](https://user-images.githubusercontent.com/16251792/51998196-7a8aa600-24b8-11e9-8dd5-02abdba34b16.gif)
on the 9th attempt. 
(after 4th attempt, I was pressing F5 twice at that moment)

**Comment by mastepan** [comment]
@mkralik3 @gashcrumb has this issue been resolved?

**Comment by mkralik3** [comment]
@mastepan It was hard to reproduce it. However, now I am not able to reproduce it anymore. Maybe the React UI resolved this problem.
