### ISSUE TITLE
[runtime] reduce integration definition size 

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#4309]
The integration definition json is quite huge and contains lot of duplicated information well as bits that are not used by the runtime. 

We should remove the garbage before generating a prject/crd

**Comment by rhuss** [comment]
Isn't it just that we pick only those parts from the integration definition which are relevant for a Camel-K resource ?

**Comment by KurtStam** [comment]
I've removed all actions from the connectors as the action in use is already attached to the Step. Now the connection > connector adds very little to the size of the integration anymore. It'd be interesting to know if there are other scenarios where it still makes the integration large in size. Is there a way we can monitor the size in our QE tests?

**Comment by tplevko** [comment]
@KurtStam I asked @avano to look into it. There are some possibilities we discussed, he'll let you know once we have some results.

**Comment by avano** [comment]
@kurtstam if I got it right, it is about the size of the final integration.json file in the integration pod, is that correct?

we can implement such checks in our testsuite, but do you know where such big payloads can occur? we tried to brainstorm with @tplevko but we couldn't find any other place.

btw it is everything for the issue or will more commits follow?

**Comment by KurtStam** [comment]
@avano - correct, I added a pruning step which runs just before it get's packaged up for the runtime. Big payloads used to occur for in particular for api-connectors such as the concur connector, where there are tons of actions per connector. Now we only send over the action in use.

all commits are in.

**Comment by avano** [comment]
Hi Kurt, everything looks ok to me. Do you think this is worth automating? The only (naive) thing that came to our minds was to set a threshold for each step and then compare the integration size with (countOfSteps * threshold).

Does something better come to your mind?
