### ISSUE TITLE
Monitoring - Instrument Syndesis DB

### ISSUE THREAD

**Issue by jamesnetherton** [syndesisio/syndesis#4316]

**Comment by tplevko** [comment]
@jamesnetherton as this was reverted, can QE close this issue, or move to backlog for tracking purposes?

**Comment by jamesnetherton** [comment]
@tplevko It wasn't reverted. The task is complete (thought I had closed this actually).

**Comment by tplevko** [comment]
@jamesnetherton sorry, my bad. Closing this as verified.
