### ISSUE TITLE
Implement API provider toolbar section

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#4317]
Each page of the API provider editor features this toolbar:

![image.png](https://images.zenhubusercontent.com/592d862b51aa2c30577fdbb4/707826d6-7b44-4d12-9da7-8195c939dae9)

Save/publish buttons are always available.  Inline editable integration name, new "view api definition" link.  I don't see a design that includes what menu should be available with the dots next to the "Publish" button.

Full page here -> https://redhat.invisionapp.com/share/BHPQXBH6W8Y#/screens/338299137

**Comment by gashcrumb** [comment]
Let's try and make this a bit standalone so it could also be used in the regular editor to support #4320 also.

**Comment by riccardo-forina** [comment]
Implemented in #4467
