### ISSUE TITLE
Implement API provider operation list side-panel

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#4319]
New side panel appears to embed the same API provider operation list but is visible on all editor pages:

![image.png](https://images.zenhubusercontent.com/592d862b51aa2c30577fdbb4/2c2a5242-b621-40b0-a963-78cdaabdf60d)

Note the "Create" buttons should probably save whatever the user is doing or prompt/notify the user what's going to happen when clicked.

Screenshot snippet is from this page for reference -> https://redhat.invisionapp.com/share/BHPQXBH6W8Y#/screens/338299138

The user can click on the "Operations" header whenever to access the full operation list again -> https://redhat.invisionapp.com/share/BHPQXBH6W8Y#/screens/338299155

**Comment by gashcrumb** [comment]
Closely related to #4318

**Comment by gashcrumb** [comment]
Current side panel as implemented in #4415 shares the same list as used in the full page view, and it uses the patternfly-ng list and toolbar for filtering.  I don't know if we should just style the list as-is to match the design more or should we just implement our own list that supports grouping and a simple search filter?

**Comment by riccardo-forina** [comment]
Pane has been pushed back for the moment because of horizontal space constraints.
