### ISSUE TITLE
Implement API provider editor page header

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#4320]
There's general editor changes to where the buttons and breadcrumbs are located.  Let's use this issue to track what happens to 'em.

With the design changes for #4317 the breadcrumb, integration name and buttons from the editor all move into the toolbar.  I think we should adapt the toolbar design to the non-api provider version of the editor as well and provide the same buttons etc and clean up each individual page header.

**Comment by gashcrumb** [comment]
With #4415 the bit is there that shows the method, path and flow name but will need styling improvements.

**Comment by riccardo-forina** [comment]
Closed by #4467
