### ISSUE TITLE
Implement API provider IVP

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#4321]
The API provider editor has a slightly different IVP:

Collapsed:
![image.png](https://images.zenhubusercontent.com/592d862b51aa2c30577fdbb4/8559b640-2036-46d6-bc72-ffcdfefeb45a)

Full page -> https://redhat.invisionapp.com/share/BHPQXBH6W8Y#/screens/338299143

Expanded:
![image.png](https://images.zenhubusercontent.com/592d862b51aa2c30577fdbb4/7c1cf4e3-d7b3-491d-afd4-32713b9932b7)

Full page -> https://redhat.invisionapp.com/share/BHPQXBH6W8Y#/screens/338299140

Looks like steps/connections in the middle are the same as the original IVP, just the start/finish connections are now boxes with the return path arrow.

Expander method is totally different.  Not sure how steps/connections in between the boxes should really look as compared to the old IVP.

**Comment by gashcrumb** [comment]
@mcoker For this one, do you think it'd be a big hassle to change the current editor's expander to use the one here from the api provider enhancements design?

**Comment by gashcrumb** [comment]
Yeah, the divider below.  Though now that I look at the API provider IVP, how's that expand/collapse link going to work once the integration gets longer and needs scrolling :-/

![image](https://user-images.githubusercontent.com/351660/51946759-8d39a800-23f0-11e9-8669-c21826c7a2de.png)

**Comment by mcoker** [comment]
Good point! @dongniwang what do you think? It might be weird, but the link could just stay at the top of the viewport in the panel it closes, like https://codepen.io/mcoker/pen/qgqWam

**Comment by gashcrumb** [comment]
When #4415 gets merged the IVP will be in the right spot but all the rest of the styling needs to be done still.  Also I feel like perhaps we have enough space most of the time to default the IVP to expanded, except obviously for the data mapper page.  At least for the non-api provider editor maybe?

**Comment by dongniwang** [comment]
If we have the space to expand the IVP at all time, I'll +1 on keeping it expanded. 

But if not, the method the @mcoker mentioned above, the sticky expand control looks fine to me.
