### ISSUE TITLE
Implement combined add step/connection page

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#4322]
The API provider editor doesn't have separate pages for adding a step or connection, instead it's just one page:

![image.png](https://images.zenhubusercontent.com/592d862b51aa2c30577fdbb4/d9ca8b87-6cb0-48e6-86be-eda427e76e37)

Full page -> https://redhat.invisionapp.com/share/BHPQXBH6W8Y#/screens/338299142

Not clear if this wireframe should incorporate elements of [this most recent design](https://redhat.invisionapp.com/share/X6K0SKUWZFG#/screens).  It probably should at least have some kind of filter/search.

This also means the popups in the IVP can be removed.

**Comment by gashcrumb** [comment]
@paoloantinori I think we might just have to let this particular change leak over to the regular editor too.

**Comment by asmigala** [comment]
Verified with latest master
