### ISSUE TITLE
Implement view/edit API defintion link

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#4323]
![image.png](https://images.zenhubusercontent.com/592d862b51aa2c30577fdbb4/7bed51a4-fa2a-461f-b861-091e8d0b6db8)

From -> https://redhat.invisionapp.com/share/BHPQXBH6W8Y#/screens/338299146

When the link is clicked we need to prompt the user to save so:

https://redhat.invisionapp.com/share/BHPQXBH6W8Y#/screens/338299147

So that the backend can then give us the swagger json for this new tab -> https://redhat.invisionapp.com/share/BHPQXBH6W8Y#/screens/338299148

There's also view/edit, which can bring back the apicurio editor:

![image.png](https://images.zenhubusercontent.com/592d862b51aa2c30577fdbb4/69e95c9a-10f3-4fa9-971d-146137f637dd)

From -> https://redhat.invisionapp.com/share/BHPQXBH6W8Y#/screens/338299150

Still prompts for save -> https://redhat.invisionapp.com/share/BHPQXBH6W8Y#/screens/338299151

And then the user is back in apicurio -> https://redhat.invisionapp.com/share/BHPQXBH6W8Y#/screens/338299153

**Comment by zregvart** [comment]
I'll try to pin this to #4270 to make it demo better. It will need to be revisited in the new design though.

**Comment by zregvart** [comment]
First pass of this was added to #4270, it's far from production ready though it kinda works.
