### ISSUE TITLE
Implement API provider editor page layout

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#4324]
The API provider editor has a different layout than the previous editor, with a top panel, operation side panel, IVP and the functional config/selecty area, for example:

![image.png](https://images.zenhubusercontent.com/592d862b51aa2c30577fdbb4/cf3ce42e-f65a-4ddc-b106-900a92d3fafb)

From -> https://redhat.invisionapp.com/share/BHPQXBH6W8Y#/screens/338299143

Also note the simplified breadcrumb that brings the user back to the integration list.

**Comment by riccardo-forina** [comment]
Closed by #4467

**Comment by riccardo-forina** [comment]
Closed by #4467
