### ISSUE TITLE
Implicit split step not saved to DB

### ISSUE THREAD

**Issue by christophd** [syndesisio/syndesis#4331]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Some connectors (sql, aws-s3, servicenow) use an implicit split step for automatically iterating over a collection of results. The implicit split is added to the connector descriptor as an empty Json node (e.g. [sql-connector](https://github.com/syndesisio/syndesis/blob/master/app/connector/sql/src/main/resources/META-INF/syndesis/connector/sql.json#L90)). 

This empty split node never makes it to the jsondb. So when the syndesis server is reading an integration definition from the DB the implicit split step is gone.

## How to reproduce

- Create an integration with one of the start connections (sql, aws-s3, servicenow) 
- Stop the integration
- Rebuild syndesis-server or kill the server pod (to clear the cached integration definitions on the server)
- Start the integration

Result: Implicit split is not performed and the integration runs on the initial collection

**Comment by christophd** [comment]
A quick fix for newly created integrations would be to add default properties to the empty split node in the connector descriptors for sql, aws-s3 and servicenow

```json
    "split": {
          "language": "simple",
          "expression": "${body}"
    }
```

The split definition will then be saved to the jsondb.

Though this will not fix existing integrations that already have been saved to the db (without the empty split node).

**Comment by lburgazzoli** [comment]
We do need to add an update step to fix this.

@rhuss do we have some docs about this ?

**Comment by christophd** [comment]
Funny thing is that the ui is always provided with the correct empty split node as these integration definitions seem to be built directly from the connector descriptor json files in META-INF read from classpath.

**Comment by lburgazzoli** [comment]
I guess we do not need to expose the split step but instead we need to work on the new foreach https://github.com/syndesisio/syndesis/issues/4312. 

This bug impacts the current version but it should not require any UI work

**Comment by gashcrumb** [comment]
Sure!  You may though want the UI to at least be able to properly render *something*.  If there's no data in a step it probably just shows some empty node or something.

**Comment by christophd** [comment]
The split node is only a marker for the backend to automatically add a step at integration runtime. The implicit split is not visible to the user. The implicit split marker is also not part of the steps provided to the ui so we will not have to render that.

**Comment by christophd** [comment]
We can close that issue as the implicit split has been removed completely. No need to save to DB anymore.
