### ISSUE TITLE
[api provider - collections] Data Shape definition for collections

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#4337]
We should add a tag to actions' shapes that tell data mapper that the specification is about an element of a collection. If such tag is found DataMapper should use a collection as document root.

@igarashitm

**Comment by igarashitm** [comment]
The conclusion from the discussion was that syndesis-meta will provide a tweaked JSON schema to express topmost JSON array IIRC? I haven't looked into that path to tweak the JSON schema at AtlasMap side, will need to look into.

BTW that would only work for online inspection i.e. JSON, while Syndesis depends on offline inspection for Java.

**Comment by christophd** [comment]
Done with work on collection-support in v7.3

**Comment by mastepan** [comment]
Reopening for the QE to verify this if needed
