### ISSUE TITLE
[camel k] Add a trait to configure/enable jolokia

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#4338]
See https://github.com/apache/camel-k/issues/369

@astefanutti willing to take this too ?

**Comment by astefanutti** [comment]
@lburgazzoli happy to take it!

**Comment by lburgazzoli** [comment]
It has been added to this sprint but don't worry if you do not have enough time, we can move it to next sprint

**Comment by astefanutti** [comment]
Sounds good!

**Comment by mastepan** [comment]
@rhuss @astefanutti  Why is this in progress again? Isn't that a mistake? This issue was Done and ready to be verified by QE several days ago...

**Comment by astefanutti** [comment]
@mastepan some changes have been decided following the review. I may have moved it to done mistakenly, while it should have remained in review. Sorry for the noise.

**Comment by astefanutti** [comment]
Ready for review at https://github.com/apache/camel-k/blob/3c3e2502808c8b93f728c1d3ae5e94b8ad110741/pkg/trait/jolokia.go.

**Comment by mastepan** [comment]
QE ignore. Not testable in Syndesis.
