### ISSUE TITLE
[api provider - collections] integration migration

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#4346]
We should convert the implicit step to the new foreach block.

Auto translate implicit split that is used by connectors (sql, asw-s3, servicenow) to new split/aggregate steps.Either do this via DB migration script or auto translate when providing old integrations from DB to UI

User might be provided with a warning/info that the integration has been migrated/auto translated

We do have two options:

- while doing the database migration
- by actualizing an integration before it is sent to the UI

We should decide based on the complexity.

@christophd do you mind exploring the two options and give your feedback about the feasibility ?

**Comment by christophd** [comment]
When this issue is resolved https://github.com/syndesisio/syndesis/issues/4331 becomes obsolete

**Comment by mastepan** [comment]
Reopening for the QE to verify this if needed. It was in Done state previously so we have a task for this.
