### ISSUE TITLE
[api provider - collections] Implement UX 

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#4349]
Implement UX as per #4312

@gashcrumb @riccardo-forina @paoloantinori

**Comment by mmuzikar** [comment]
Hey I was just verifying this issue and most of what @christophd wrote is true except for:

>     * Users can add aggregate step as finishing step of an integration
>     * Users can add aggregate step after an existing finishing step

Also you can add as many aggregate steps as you like if a split step is present (not sure if that's an issue though... but maybe worth pointing it out)

**Comment by christophd** [comment]
thanks @mmuzikar for verifying!

Those last two points with aggregate being added as finish step or after an existing finish step are obsolete as we have decided to not do this. I think users should just not add the aggregate at all when the integration is supposed to operate with the split to the very end.

Multiple aggregate steps do not really make sense so I would consider this as a bug. Will open a separate issue for that thanks!

**Comment by christophd** [comment]
Here is the issue regarding multiple aggregate steps: https://github.com/syndesisio/syndesis/issues/4710

**Comment by mmuzikar** [comment]
With closing of #4710 I'd say that this can be considered verified as well.
