### ISSUE TITLE
Implement Swagger 2.0 specification validator

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#435]
We need to validate if the Swagger specification provided for the custom connector is valid. Valid means that it conforms to the Swagger 2.0 specification, we should do a JSON Schema validation of it. Next we should check for specific items Syndesis mandates:
 - request/response JSON schemas (as warning)
 - supported authentication types

**Comment by nicolaferraro** [comment]
@zregvart I can help with this. Ok?

**Comment by zregvart** [comment]
@nicolaferraro  That would awesome, ideally it would be part of the `SwaggerConnectorGenerator::info` ([SwaggerConnectorGenerator.java#L83](https://github.com/zregvart/syndesis/blob/6d8719d8b328b632e349fdffea94c2e9a09b130d/rest/connector-generator/src/main/java/io/syndesis/connector/generator/swagger/SwaggerConnectorGenerator.java#L83)) and would set errors/warnings on `ConnectorSummary`. And once more to see if any errors occur in `SwaggerConnectorGenerator::generate`.

Thanks!
