### ISSUE TITLE
Update Syndesis logo + title

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#4353]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

Please update the Syndesis logo and title to the now official version found at http://design.jboss.org/syndesis/

**Comment by jameslau** [comment]
@gashcrumb notified me about this ticketed issue. Thank you @rhuss for the link to the Syndesis assets.

Because there are several variations to the branding, I will need to touch base with @dongniwang and ask for a design direction before I move forward.
