### ISSUE TITLE
[api provider - collections] Out message capturing in/after foreach steps

### ISSUE THREAD

**Issue by christophd** [syndesisio/syndesis#4355]
DataMapper steps inside of a foreach block should be provided with all out messages from previous steps.

DataMapper steps placed after an endForeach step should not have access to the foreach internal out messages but only to the endForeach overall out message.

**Comment by mmuzikar** [comment]
@christophd Hey just to make sure by 
> DataMapper steps inside of a foreach block should be provided with all out messages from previous steps.

You meant steps inside foreach (split) block should be provided with all out messages from previous steps **inside** the block?

If that's true I would say we can consider this verified.

**Comment by christophd** [comment]
@mmuzikar yes, that is true
