### ISSUE TITLE
Change to step/connection icons and max-width/height in UI

### ISSUE THREAD

**Issue by mcoker** [syndesisio/syndesis#4356]
## The problem
Our step/connection icons have a max-height/width of 24px, meaning the long edge will never be more than 24px and the short edge will change to keep the image in the original aspect ratio.

We have some icons that look too small at 24px and the image size needs to increase to match the visual style of other icons around it. An example of this is our API connector icon. We have custom CSS in the integration editor to increase the size of that single icon to max-width/height of 35px. At 35px, the 4 corners of the icon will touch the inner part of the circle around the icon in the IVP and integration details page.

<img width="390" alt="screen shot 2019-01-26 at 9 14 57 am" src="https://user-images.githubusercontent.com/35148959/51789086-1039d480-214b-11e9-9c51-584eeed45639.png">

Here is the icon beside (at the normally 24px max-width/height) it for comparison

<img width="386" alt="screen shot 2019-01-26 at 9 15 13 am" src="https://user-images.githubusercontent.com/35148959/51789093-20ea4a80-214b-11e9-9956-ef74cad3c196.png">

Now we have new icons (Apache Kudu, for example) that need to be increased in size, too. Instead of adding a custom class per icon to increase the icon size to a custom size that makes it visually match the icons around it in the integration list page and editor, I think we could increase the size of all of our icons to a max-width/height of 35px, then scale down the drawn icon part of the icon in the image canvas for most of our existing images, while allowing us to draw some icons larger than others in the 35x35px canvas, without having to use custom CSS per icon to manipulate a custom size.

Here is an example.

Before the change with the max-width/height at 24px as it is currently:

<img width="270" alt="screen shot 2019-01-26 at 9 22 53 am" src="https://user-images.githubusercontent.com/35148959/51789222-31e78b80-214c-11e9-9e72-17597f10984c.png">
<img width="291" alt="screen shot 2019-01-26 at 9 22 56 am" src="https://user-images.githubusercontent.com/35148959/51789223-31e78b80-214c-11e9-821b-28e9e603cc4d.png">

After the change, increasing the max-width/height to 35px and simply increasing the canvas area of the database icon while increasing the overall size of the kudu icon in the canvas to make it larger

<img width="252" alt="screen shot 2019-01-26 at 9 23 49 am" src="https://user-images.githubusercontent.com/35148959/51789232-4cba0000-214c-11e9-9c5e-283a53e46ea1.png">
<img width="255" alt="screen shot 2019-01-26 at 9 23 45 am" src="https://user-images.githubusercontent.com/35148959/51789233-4cba0000-214c-11e9-9df0-18b9c5464fe3.png">

cc @syndesisio/uxd @gashcrumb

**Comment by gashcrumb** [comment]
@mcoker I'm +1 certainly.
