### ISSUE TITLE
Some UI instances of "OpenAPI Specification" should be "OpenAPI Document"

### ISSUE THREAD

**Issue by TovaCohen** [syndesisio/syndesis#4361]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
In the UI for creating an API Client Connector, instances of "OpenAPI Specification" should be "OpenAPI Document". The user does not upload the OpenAPI 2.0 Specification. The user uploads an OpenAPI document or file that conforms to the OpenAPI 2.0 Specification. 
## Screenshot

![image](https://user-images.githubusercontent.com/25067106/51802682-60cc3300-221a-11e9-9d9f-ef69eddec0f4.png)

This needs to change in strings in 
app/ui/src/assets/dictionary/en-GB.json

I can make this change. Let me know if I should go ahead and do this. 
Does any other file have instances that appear in the UI?

**Comment by zregvart** [comment]
Quickly checking with `grep` I found also this:

https://github.com/syndesisio/syndesis/blob/a9687a1345c5a71570c0028c3166eb160601b46f/app/ui/src/app/customizations/api-connector/api-connector-list/api-connector-list.component.html#L4-L5

https://github.com/syndesisio/syndesis/blob/a9687a1345c5a71570c0028c3166eb160601b46f/app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/SyndesisSwaggerValidationRules.java#L201-L202

https://github.com/syndesisio/syndesis/blob/a9687a1345c5a71570c0028c3166eb160601b46f/app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/SyndesisSwaggerValidationRules.java#L213

https://github.com/syndesisio/syndesis/blob/a9687a1345c5a71570c0028c3166eb160601b46f/app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/SwaggerModelInfo.java#L57

https://github.com/syndesisio/syndesis/blob/a9687a1345c5a71570c0028c3166eb160601b46f/app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/util/SwaggerHelper.java#L184

https://github.com/syndesisio/syndesis/blob/a9687a1345c5a71570c0028c3166eb160601b46f/app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/util/SwaggerHelper.java#L217

https://github.com/syndesisio/syndesis/blob/a9687a1345c5a71570c0028c3166eb160601b46f/app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/util/SwaggerHelper.java#L227

https://github.com/syndesisio/syndesis/blob/a9687a1345c5a71570c0028c3166eb160601b46f/app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/util/SwaggerHelper.java#L243

https://github.com/syndesisio/syndesis/blob/a9687a1345c5a71570c0028c3166eb160601b46f/app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/util/SwaggerHelper.java#L325

https://github.com/syndesisio/syndesis/blob/a9687a1345c5a71570c0028c3166eb160601b46f/app/server/dao/src/main/resources/io/syndesis/server/dao/deployment.json#L165

https://github.com/syndesisio/syndesis/blob/a9687a1345c5a71570c0028c3166eb160601b46f/app/server/dao/src/main/resources/io/syndesis/server/dao/deployment.json#L290

https://github.com/syndesisio/syndesis/blob/a9687a1345c5a71570c0028c3166eb160601b46f/app/server/dao/src/main/resources/io/syndesis/server/dao/deployment.json#L391

https://github.com/syndesisio/syndesis/blob/a9687a1345c5a71570c0028c3166eb160601b46f/app/server/dao/src/main/resources/io/syndesis/server/dao/deployment.json#L435

Changing bunch of these will probably result in test failures, best we set the correct wording and then fix the tests.

The ones in `api-provider.actions.ts` and `api-connector.actions.ts` don't need to change IMO.

**Comment by heiko-braun** [comment]
@gashcrumb A low hanging fruit?

**Comment by heiko-braun** [comment]
@gashcrumb nm, is was merged already. moving to done.

**Comment by tplevko** [comment]
Verified
