### ISSUE TITLE
Monitoring - Show JVM metrics in a Grafana dashboard

### ISSUE THREAD

**Issue by alexkieling** [syndesisio/syndesis#4364]
As a system administrator, I want a Grafana dashboard exposing JVM metrics about Syndesis Meta and Syndesis Server, so I can monitor things like CPU usage, memory usage, garbage collection, and threads.

Consider adapting this dashboard instead of creating one from scratch:
https://grafana.com/dashboards/4701

**Comment by mkralik3** [comment]
Verified.
![image](https://user-images.githubusercontent.com/16251792/52481946-367e5c00-2bb0-11e9-9295-3bd60eaaea8e.png)
