### ISSUE TITLE
Monitoring - Show Syndesis Server JVM metrics in a Grafana dashboard

### ISSUE THREAD

**Issue by alexkieling** [syndesisio/syndesis#4365]
As a system administrator, I want a Grafana dashboard exposing JVM metrics about Syndesis Server, so I can monitor things like CPU usage, memory usage, garbage collection, and threads.

Consider adapting this dashboard instead of creating one from scratch:
https://grafana.com/dashboards/4701

**Comment by jamesnetherton** [comment]
Closing as we'll have a single dashboard and issue (#4364) to cover both Syndesis Meta & Syndesis Server.

**Comment by mkralik3** [comment]
Verified. When I change the Application in the Dashboard from **syndesis-meta** to **syndesis-server**, information about JVM is refreshed.
![image](https://user-images.githubusercontent.com/16251792/52482313-3a5eae00-2bb1-11e9-92ac-c47b21059e25.png)
