### ISSUE TITLE
Unexpected behavior when pressing back during Integration creation

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#4370]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When creating an integration, the browser back button can be pressed at any time and most of the time leaves the user with not valid integration, but the integration can still be published.

For example when adding a step in between two other steps, you can press back instead of choosing an operation... but the step is still present but is empty. Which then causes the integration to fail when publishing and can be quite confusing when the integration is quite large.

The same behavior happens even when creating filters for example... you cannot create a filter with an empty expression, or you shouldn't be able to but if you press back nothing is stopping you and you probably can see the issue :smile: 

## How to reproduce
Go back in browser history any time you can choose some operation, or also for example when creating advanced filter, press back twice and you have a filter with an empty expression which also causes the integrations to fail, but a failure is never reported, so they are stuck in like a starting loop.

**Comment by gashcrumb** [comment]
I think this one is worth deferring until the React implementation of the console, where @riccardo-forina has history working properly.
