### ISSUE TITLE
syndesis-db fails to pull during 'syndesis install', so the installation never completes

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#4375]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
I had a working environment last Friday, pulled and realized my minishift instance was kinda sick, ran my usual command to restart, ran into some issues, opted to update to the latest minishift (`minishift-1.30.0-linux-amd64`) and give it a try.  I've tried both:

`tools/bin/syndesis minishift --full-reset --install --dev --local -p syndesis`

And also:

`tools/bin/syndesis minishift --full-reset && tools/bin/syndesis --install --dev --local -p syndesis`

In either case the install just spins waiting for Syndesis to start up as the syndesis-db image apparently cannot be pulled:

```
Failed to pull image "172.30.1.1:5000/openshift/postgresql@sha256:4ab2cbdae8af04eb2cddd32bb97ef249d9c592353b70b4ac7188dc0601fe980a": rpc error: code = Unknown desc = Get http://172.30.1.1:5000/v2/: dial tcp 172.30.1.1:5000: getsockopt: connection refused
```

I've actually been hitting this kind of behavior since minishift 1.26.1 or so, but have been working around it previously by downgrading to a version of minishift that supports `--openshift-version 3.9.0` but that also doesn't seem to work for me now either.

**Comment by gashcrumb** [comment]
@seanforyou23 have you been seeing this kinda stuff too?

**Comment by gashcrumb** [comment]
I'm trying a second machine too.  The main problem is while I wait for the installation I wind up buying used studio gear on Reverb.

**Comment by zregvart** [comment]
I have intermittent issues if I run BlueJeans at the same time as `syndesis minishift --install`. I find it that the install exerts the CPU and network connections, so if I do `syndesis minishift --install` I find it good to go do the laundry also.

**Comment by SvenC56** [comment]
I'd like to reopen this issue. I get mostly the same issue at the moment.

```
Failed to pull image "172.30.1.1:5000/openshift/postgresql@sha256:d459c9bb18ec7de443fbe4dd31cff26bdc6fdc681363922e97ae2f40e64a93c1": rpc error: code = Unknown desc = Error response from daemon: unknown: unable to pull manifest from docker.io/centos/postgresql-95-centos7:latest: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 172.30.0.2:53: read udp 172.17.0.5:57543->172.30.0.2:53: i/o timeout
```

I tried to change the DNS to the Google nameservers but this did not resolve the issue.
