### ISSUE TITLE
Support for "addon" resources in syndesis-operator

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#4381]
For integrating with external systems (e.g. Prometheus, Grafana) it would be very valuable when the Syndesis operator would install arbitrary resources stored in a directory within the operator image.

A sample workflow would look like this:

* Within the Operator image, there is a directory `/addons` which can contain any possible Kubernetes resource in YAML foramt. This can also be also custom resources like a `ServiceMonitor` for the Prometheus Operator. The syndesis-operator build process should be modified to pick up those file from _somewhere_ and put it into this directory.
* When the syndesis-operator is running and someone deploys a `Syndesis` resource, after the operator has installed syndesis, it checks this directory and for every resource found in this directory:
  - Adds an `ownerReference` to the `Syndesis` resource
  - Adds a label/annotation indicating that it has been installed on behalf of the operator (e.g. `syndesis.io/addon-resource`)
  - Applies this resource to the current namespace

This ensures, that when the Syndesis resources are deleted, also the addon resources are deleted.

The Installation of an Operator would do the following steps;

* The new operator gets started. During startup, and when it detects an upgrade situation (e.g. a Syndesis resource is already installed) it checks for all resources with a label `syndesis.io/addon-resource' and then for each delete the resource.
* When an existing installation needs to be updated, just install the addon resources from the new operator image after the update process has finished.

@jamesnetherton @alexkieling @lgarciaaco I hope this summarizes our discussion accurately. 

@heiko-braun this feature is requested by Integreatly so that Syndesis could be monitored by an external, integreatly provided Prometheus instance. Is there a way that we can schedule this work into one of our next releases ?

**Comment by zregvart** [comment]
Is't this the functionality of the [operator lifecycle manager](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/Documentation/design/dependency-resolution.md)?

**Comment by alexkieling** [comment]
@rhuss The Grafana dashboards will be done before this task is completed, therefore I'll create the `/addons` directory and start adding them there.

**Comment by gaughan** [comment]
this looks to me to be in 7.3 then not 7.4?

**Comment by jamesnetherton** [comment]
@heiko-braun We'll need this for 7.3 for deploying the Grafana dashboards, Prometheus service monitors and alert rules.

**Comment by heiko-braun** [comment]
@rhuss How would you estimate this effort? Any dependencies that we need to be aware of?

**Comment by heiko-braun** [comment]
@jamesnetherton If we don't have this feature, what other options do we have for getting Grafana dashboards, Prometheus service monitors and alert rules set up? Is there also a manual way to achieve this?

**Comment by jamesnetherton** [comment]
@heiko-braun shell script could do the job, or the resources could be applied manually.

**Comment by rhuss** [comment]
@heiko-braun should be possible within one day.

**Comment by heiko-braun** [comment]
@rhuss Does it require addtional permissions for the operator?

**Comment by heiko-braun** [comment]
@rhuss based on your comments I would pull it into 7.3, wdyt?

**Comment by rhuss** [comment]
@heiko-braun if there is someone to pick that up, then I agree that it definitely makes sense. I can pick this up, but would have to trade it for some other stories (e.g. #4263 and #4287). #4063 is harder than expected, so my current assignments are a tough call anyway. As I'm on operator development, it would make sense though to combine that.

**Comment by heiko-braun** [comment]
@rhuss, @astefanutti has volunteered to work on it next week. He might approach you with questions.

**Comment by rhuss** [comment]
@astefanutti please be aware of #4460  as this will changes the operator structure completely. Any change of the operator should go on top of that.

**Comment by astefanutti** [comment]
@rhuss ah great, thx for the heads-up.

**Comment by astefanutti** [comment]
PR #4517 is available for review.

**Comment by astefanutti** [comment]
> @rhuss Does it require addtional permissions for the operator?

@heiko-braun I've created #4522 that adds the permissions for the current monitoring addons.

**Comment by heiko-braun** [comment]
@rhuss @astefanutti We need to discuss the dependencies introduced by this change. The monitoring operator is not present in all environments. Whiat should happen when it's not, or the permission to install CRD's are not present? 

@astefanutti suggested:

> * Add an option to deactivate add-on by default
* Or do not fail-fast on add-on resource creation error, at least for missing permission or missing CRDs.

I think making the whole setup from addon-ons dir configurable is a good approach. WDYT?

**Comment by astefanutti** [comment]
I've rebased the PR on top of #4460.

@heiko-braun I've changed the activation behaviour so that the `--addons` option must be explicitly set for the addons to be applied.

**Comment by heiko-braun** [comment]
Very good, thanks @astefanutti !

**Comment by chirino** [comment]
https://github.com/syndesisio/syndesis/pull/6256 Sydnesis 1.7 now changes how these addons are activated.  You have to update the CR like this:

```
apiVersion: "syndesis.io/v1alpha1"
kind: "Syndesis"
metadata:
  name: app
spec:
  addons:
    ops:
      enabled: "true"
```
