### ISSUE TITLE
Tech preview popover is hidden behind toolbar

### ISSUE THREAD

**Issue by mcoker** [syndesisio/syndesis#4385]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
When you click on the tech preview icon for a connection, the popover is hidden behind the toolbar.

## Expected behavior
The popover should be full visible when it's clicked. We should also make sure it looks fine at different viewports when the preview is shown on the left and right-most cards, too.

## Screenshot
<img width="1641" alt="screen shot 2019-01-29 at 2 30 02 pm" src="https://user-images.githubusercontent.com/35148959/51938735-76388d00-23d3-11e9-8f5c-9a4c6c5f986c.png">

## Tasks involved / Steps to Reproduce

1. Go to connections and create/find a connection that is a tech preview and click the icon that triggers the popover. I found this on staging.

cc @dongniwang

**Comment by tplevko** [comment]
Seems like now the tech-preview icon is not visible at all. 
![screenshot from 2019-03-05 10-23-10](https://user-images.githubusercontent.com/4180208/53794678-c2c23b80-3f30-11e9-9c8d-9d1f0e591fc5.png)

**Comment by mcoker** [comment]
@tplevko I noticed the same thing and made note of it in the PR https://github.com/syndesisio/syndesis/pull/4694

@gashcrumb do you know why the tech preview icon is gone?

**Comment by gashcrumb** [comment]
Is that connector still marked tech preview?  Looking at the response data in my own instance I don't see it flagged as such.

**Comment by tplevko** [comment]
@gashcrumb yes, we agreed with @gaughan that the FHIR and also OData connector is at least for the productized - Fuse Online 7.3. in TP.

**Comment by gaughan** [comment]
yes, should be TP

**Comment by gashcrumb** [comment]
@heiko-braun think we need someone to verify if the connector definitions for these dropped the tech preview flag.  I didn't spot it when I checked out the response data yesterday but perhaps I missed it.

**Comment by heiko-braun** [comment]
@rkorytkowski, @phantomjinx Can you make sure the FHIR and OData connector's have the tech preview flag set in their meta data?

**Comment by rkorytkowski** [comment]
@heiko-braun, sure PR for both at https://github.com/syndesisio/syndesis/pull/4779

**Comment by heiko-braun** [comment]
Thanks @rkorytkowski !

**Comment by mcoker** [comment]
This look OK to me on staging now. @tplevko can you verify?

<img width="702" alt="Screen Shot 2019-04-01 at 12 43 16 PM" src="https://user-images.githubusercontent.com/35148959/55347998-c4bde280-547b-11e9-81f0-67a10fb28930.png">

**Comment by tplevko** [comment]
@gashcrumb it seems to be working OK. I think we can close this one as verified.
