### ISSUE TITLE
OutMessageCaptureProcessorTest is flaky

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#4389]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
I wonder if OutMessageCaptureProcessorTest is beyond help. It fails intermittently see:

https://circleci.com/gh/syndesisio/syndesis/53985

See also #3328 and #2658

**Comment by christophd** [comment]
I think this one has been fixed with https://github.com/syndesisio/syndesis/pull/4438
