### ISSUE TITLE
Error messages not formatted correctly

### ISSUE THREAD

**Issue by phantomjinx** [syndesisio/syndesis#4392]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

On occasion, error toast messages in the UI are not formatted correctly, in that the message is displayed followed by [object Object]. Obviously, some json object is not be converted to a string.

An encountered example follows:
`Failed to stop integration Error stopping integration: [object Object]`
(This has been occurring after shutting down Openshift with an integration published then restarting it)

## Expected behavior

Error messages should be properly formatted with objects.

## Screenshot

![error-message-object](https://user-images.githubusercontent.com/1634180/51983029-a04f8500-248f-11e9-813f-df9588d6af12.png)

**Comment by mmuzikar** [comment]
@heiko-braun This behavior is quite easily reproducible with #5250 because when the integration is in the starting state and user presses stop that causes the message to be formatted like this... could this be  happening because no pod of the integration is present?

**Comment by mastepan** [comment]
@mmuzikar can you please check if this issue is still reproducible? Thanks

**Comment by mmuzikar** [comment]
This issue is probably reproducible in some way, not in the one I mentioned in the original issue. But I will try to come up with some way to reproduce this.
