### ISSUE TITLE
Provide an example pipeline

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/syndesis#4393]
As a user I want to see an example pipeline that leverages the API's to get get an idea how to leverage the API's.

Jenkins pipelines are preferred.

(Please also take a look at https://github.com/RHsyseng/IntegrationApp-Automation)

**Comment by tplevko** [comment]
@heiko-braun to have this at hand would be of great help for QE, as we struggle a bit with the setup of testing pipeline.

**Comment by tplevko** [comment]
There is also question regarding the "draft of user doc" mentioned in the parent epic's DoD section https://github.com/syndesisio/syndesis/issues/3701. This would be also of great help for us.
@dhirajsb where can we please find this draft?

**Comment by mkralik3** [comment]
In my POV, the issue https://github.com/syndesisio/syndesis/issues/4740 can be resolved as part of this issue too.

**Comment by heiko-braun** [comment]
@dhirajsb Can this be resolved?

**Comment by dhirajsb** [comment]
@heiko-braun it's just waiting on a fixed link for the video I made for this. I'll sort it out with @KurtStam and create a PR for this issue. Shouldn't be more than a day or two.

**Comment by dhirajsb** [comment]
Created PR https://github.com/syndesisio/syndesis-quickstarts/pull/25 for the quickstart. 

The fixes comment in the PR closed this issue automatically before the PR was merged. Reopening, to be closed when that PR is reviewed and merged.
