### ISSUE TITLE
Empty integration can be created after refreshing

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#4394]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Refreshing a page during integration creation process removes all defined steps but when you were at a point where you can publish an integration it is still possible to do so.
When you try to publish or save the integration as a draft you are then stuck... and any other attempts to create another Integrations leave you hanging... effectively you are stuck (You can still access the integration editor by modifying the URL validate to false).

**Comment by gashcrumb** [comment]
I think this one is worth deferring until we cut over to the React implementation of the console.
