### ISSUE TITLE
View log in Openshift link seems to be wrong

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#4395]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
In the Integration activity tab, there is a link saying View log in Openshift, but it won't take you to the log. 
Note: I am running syndesis on Minishift but AFAIK that shouldn't change much because Openshift and Syndesis should both serve different ports so linking to /project/syndesis/browse/pods/pod-id won't take you to the Openshift console.

Also when changing the resulting URL to lead to Openshift you get a response 403, but changing it to /console//project/syndesis/browse/pods/pod-id seems to fix the issue and takes you to the desired log.

**Comment by gashcrumb** [comment]
Couple related issues to this -> #3076 and #2730 

Especially on minishift you may need to edit the UI's config map after installation as there's no reliable way of knowing the openshift console's endpoint until an API is exposed.

**Comment by mmuzikar** [comment]
So should the /console part be also in the config?

**Comment by gashcrumb** [comment]
yeah, should be.

**Comment by heiko-braun** [comment]
@mmuzikar Did the comment from @gashcrumb solve the issue for you?

**Comment by mmuzikar** [comment]
Yes, it worked fine.
