### ISSUE TITLE
Errors when going from the integration detail page into the editor

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#4396]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

When you're in the integration detail page and then click on the "Edit Integration" button a bunch of javascript errors surface on the console, for example:

![image](https://user-images.githubusercontent.com/351660/51987308-2fe53b80-2470-11e9-8f91-91729e41c56d.png)

**Comment by mastepan** [comment]
Verified on 1.6.1-20190204
