### ISSUE TITLE
OData output results needs separating to allow for mapping and transmission to producers

### ISSUE THREAD

**Issue by phantomjinx** [syndesisio/syndesis#4397]
The consumer odata connector produces results as json. However, in line with the underlying olingo4 component it has been implemented to provide all results in a single message. Unfortunately, this means that the data cannot be mapped to services such as gmail or slack. Therefore, need to split the results (consumer actually contains a consume.splitResults property) to facilitate correct mapping and communication.

**Comment by zregvart** [comment]
Related to #4291
