### ISSUE TITLE
[api provider - collections] Introduce data shapes for split and aggregate steps

### ISSUE THREAD

**Issue by christophd** [syndesisio/syndesis#4405]
New split and aggregate steps should provide a data shape with meta data retrieval.

The split step should provide a single element data shape representation of the step output sitting right before the split.

The aggregate step should provide a collection of the last step output data shape sitting in the split/aggregate.

The data shapes for these steps will be retrieved by meta data dynamic lookup.

**Comment by mastepan** [comment]
Reopening for the QE to verify this if needed. It was in Done state previously so we have a task for this.
