### ISSUE TITLE
UI provides data shape for split and aggregate steps

### ISSUE THREAD

**Issue by christophd** [syndesisio/syndesis#4406]
As part of https://github.com/syndesisio/syndesis/issues/4405 we need the UI to call syndesis-meta when split and aggregate steps are added to the integration in order to receive dynamic output data shapes for these steps.

For split step the UI should provide the output data shape of the step sitting right before the split. Meta server will evaluate and return a proper output data shape for the split step representing a single element in the collection.

For aggregate step the UI should provide the output data shape of the last step in the split/aggregate to the server. Meta server will evaluate and return a proper output data shape for the aggregate step.

**Comment by lburgazzoli** [comment]
@paoloantinori @gashcrumb FYI

**Comment by gashcrumb** [comment]
Do we have an issue also for creating the split/aggregate step entries in UI's step store by any chance, or is this issue covering that too?  If the latter, what should the split and aggregate step definitions look like?  Or should I just [rename these](https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/store/step/step.store.ts#L135-L154)?

**Comment by christophd** [comment]
The rename to split/aggregate is pending with PR https://github.com/syndesisio/syndesis/pull/4455 (commit https://github.com/syndesisio/syndesis/pull/4455/commits/3aa8b013d633683cc6da90c92158bb319f1a3e1e)

The step definitions will be very simple as in a first iteration the user will not have any options available on those.

**Comment by christophd** [comment]
@gashcrumb renamed steps are now available on master

**Comment by gashcrumb** [comment]
Do we have endpoints for this in place?

**Comment by christophd** [comment]
There is a new server endpoint `/steps/{kind}/descriptor` where `{kind}` path parameter is the step kind (one of: endpoint, connector, expressionFilter, ruleFilter, extension, mapper, split, aggregate, log, headers, template)

The endpoint receives a POST request with a json payload representing the current step meta data. The step meta data should provide input and output data shapes:

For instance:
```
{
  "inputShape" : {
    "kind" : "json-schema",
    "type" : "type",
    "name" : "name",
    "description" : "description",
    "specification" : "{ ... }"
  },
  "outputShape" : {
    "kind" : "none",
    "type" : "type"
  }
}
```

For `split` step the input and output shapes of the preceding connection should be provided as is.
For `aggregate` step the input and output shapes of the preceding step should be provided as is.

The endpoint responds with an adjusted json object representing the input and output data shapes that should be set to the respective step (split/aggregate) that the request has been called for.

**Comment by christophd** [comment]
At the moment the server endpoint provides meta lookup logic for split and aggregate only. Requests with step kinds other than that just get a response with the exact same json object as requested.

**Comment by gashcrumb** [comment]
Some clarification on these:

> For `split` step the input and output shapes of the preceding connection should be provided as is.

Connections only or should it be whatever step has a data shape?  I think this would be the data mapper and maybe the template step?

> For `aggregate` step the input and output shapes of the preceding step should be provided as is.

A lot of steps *don't* have any data shape or don't change it in any appreciable way, should I assume here that it should be whatever preceding step has a data shape, be it a connection or otherwise?  This would mean also potentially a split step.

**Comment by christophd** [comment]
> Connections only or should it be whatever step has a data shape? I think this would be the data mapper and maybe the template step?

Good point! Yes, whatever provides an output data shape. Same for aggregate step.

**Comment by mastepan** [comment]
Reopening for the QE to verify this if needed. It was in Done state previously so we have a task for this.
