### ISSUE TITLE
The Log step doesn't show body properly

### ISSUE THREAD

**Issue by mkralik3** [syndesisio/syndesis#4407]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
The Log step doesn't show body from webhook correctly.
![image](https://user-images.githubusercontent.com/16251792/52064074-21804800-2574-11e9-9889-ff5ae69fb359.png)

actual version:
```
Body: [[org.apache.camel.converter.stream.InputStreamCache@704f438]] before basic filter
```
previous version:
```
Body: [{"first_name":"John","company":"incorrect company"}] before basic filter
```

Step to reproduce:
1. import project 
[Webhook.to.DB-export.zip](https://github.com/syndesisio/syndesis/files/2817834/Webhook.to.DB-export.zip)
2. Publish it
3. Post 
```
{"first_name":"John","company":"incorrect company"}
```
to the webhook
4. Look to the activity tab.

**Comment by christophd** [comment]
This is my bad as I introduced a new body logger implementation. I will fix that as soon as possible

**Comment by christophd** [comment]
By the way how do you call the web hook POST request in your test scenario? The web hook is using SSL so I have been using a little Citrus test in order to call that web hook once it is published.

See https://gist.github.com/christophd/6101f20875738f4213cc5faeb5845fb4

Which tool do you use?

**Comment by mkralik3** [comment]
@christophd I use [Advanced REST client](https://chrome.google.com/webstore/detail/advanced-rest-client/hgmloofddffdnphfgcellkdfbfbjeloo) with [ARC cookie exchange extension.](https://chrome.google.com/webstore/detail/arc-cookie-exchange/apcedakaoficjlofohhcmkkljehnmebp) Very helpful for debugging https rest points.

Now the log contains one more array as before. Is it necessary?
```
Body: [[{"first_name":"John","company":"incorrect company"}]] before basic filter
```
Before:
```
Body: [{"first_name":"John","company":"incorrect company"}] before basic filter
```

**Comment by mkralik3** [comment]
Ok,
Verified, so I have closed this issue.
