### ISSUE TITLE
[Rollback] Pretty-print failed steps doesn't print newlines

### ISSUE THREAD

**Issue by avano** [syndesisio/syndesis#4412]
See also **https://issues.jboss.org/browse/ENTESB-11439**

## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When some step fails during rollback, it will be printed after the execution, I fixed the misspelled variable name in https://github.com/syndesisio/syndesis/pull/4411 , but then the new lines are not printed:

```
==========================================
!!!!!!!!! Errors during Rollback !!!!!!!!!

The following rollback compensation steps
caused an error


  * migrate_db\n

The setup is very likely broken now and you
have to manually fix it.
Please check the log output above for any
detailed error messages.
==========================================
```

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11439**
