### ISSUE TITLE
Cancel/Done button location for data mapper

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#4416]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
With the changes in #4415 the done/cancel buttons for the data mapper are redundant with the toolbar buttons in the new element for the API provider.  I propose moving that done and cancel button into the toolbar.

@dongniwang

**Comment by gashcrumb** [comment]
I could probably move other 'done' and 'cancel' buttons that show up in the UI up to that toolbar as well if it'd be a better location.

**Comment by gashcrumb** [comment]
Here's a rough example of things now:

![image](https://user-images.githubusercontent.com/351660/52136874-21855400-2617-11e9-83de-3b10855d0571.png)

**Comment by dongniwang** [comment]
@gashcrumb - you mean moving the "Done" and "Cancel" of the data mapper UI to the toolbar above?

**Comment by gashcrumb** [comment]
@dongniwang yep

once #4414 is merged you'll be able to test it all out on staging too, so no need to answer right now :-)

**Comment by dongniwang** [comment]
@gashcrumb OK. I wanted to say the rule of thumb on this is to make sure we have a clear control for the Save and Cancel action... And it would be great to try things out on staging! Thanks!
