### ISSUE TITLE
Monitoring - Show Syndesis DB metrics in a Grafana dashboard

### ISSUE THREAD

**Issue by jamesnetherton** [syndesisio/syndesis#4419]
As a system administrator, I want a Grafana dashboard exposing metrics about Syndesis DB, so I can monitor aspects of the Postgres DBMS and individual databases.

**Comment by mkralik3** [comment]
verified.
![image](https://user-images.githubusercontent.com/16251792/52482088-9bd24d00-2bb0-11e9-9e99-377ff2976d55.png)
