### ISSUE TITLE
Monitoring - Create Prometheus ServiceMonitor resources for Syndesis infrastructure components

### ISSUE THREAD

**Issue by jamesnetherton** [syndesisio/syndesis#4421]
In environments where the Prometheus operator is installed, we need to use the ServiceMonitor CRD to ensure metrics are scraped for our Syndesis infrastructure components.

- Syndesis Meta
- Syndesis Server
- Syndesis DB

**Comment by mkralik3** [comment]
Verified.
![image](https://user-images.githubusercontent.com/16251792/52483150-7b57c200-2bb3-11e9-92f8-b1efac7aa3f8.png)
