### ISSUE TITLE
Eliminate log connection in favor of the log step

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#4425]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
There's a log step and a log connection.  We can get rid of the log connection if we make it possible to use steps in the last spot in a flow.

1)  Remove this stuff -> https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/integration/edit-page/flow-functions.ts#L170-L177
2)  Test it, revisit #1 if broken and repeat until working
3)  Ask someone nicely to remove the log connection

**Comment by gashcrumb** [comment]
With #4448 merged any 'ol step can be added at the end.

**Comment by TovaCohen** [comment]
I'll document this for the Log step. Is there any reason to document it for any other step?

**Comment by gashcrumb** [comment]
So the implication here is that an integration can end with the basic or advanced filter, log step, or any extension.  The data mapper can't be put at the end of an integration still, as it needs a target data shape.

When we had a separate "add step" and "add connection" page, we actually had two separate definitions for the "log" step, which is still the case until we remove the log connection.  

@lburgazzoli @christophd I'm hoping that we'd migrate integrations that use the old log connection once we remove the definition for it.  Or should I perhaps just hide the log connection for now from the selection page?  Then we could worry about migrating old integrations later...

**Comment by TovaCohen** [comment]
Can you give me an example of when a filter step (basic or advanced) would be useful as the last step in an integration?
I assume that a Template step cannot be the last step in an integration, right?

**Comment by tplevko** [comment]
@gashcrumb same question as @TovaCohen raised. Is there a justification for this approach? It's not clear, why would anyone want to set this as finish step, as there is no output to the user. 
This could cause problems to the user, as this would make sense only if user could provide some step following the filter/advanced filter, which is ATM not possible.

**Comment by tplevko** [comment]
Created an issue for this: https://github.com/syndesisio/syndesis/issues/4527

**Comment by heiko-braun** [comment]
@gashcrumb Moving to 7.x?

**Comment by gashcrumb** [comment]
@heiko-braun Yeah, there's a remaining item on this for someone from the backend team, the log connection needs to be removed.  Ideally though it should really happen for 7.3, otherwise folks have 2 logs to choose from.

**Comment by heiko-braun** [comment]
@gashcrumb I think the twp have different purposes: One logs to the pod, the other goes back to the activity logging. @KurtStam Can you shed some light on this?

**Comment by jsafarik** [comment]
Wouldn't it be better to merge those two into one connection and let the user choose from the "Log - Choose an Action" page (page that occurs after selecting Log with description "Log the exchange with different options")?

**Comment by TovaCohen** [comment]
In the staging site, today, when the user wants to add a step to a flow, these two cards are right next to each other": 
![image](https://user-images.githubusercontent.com/25067106/54297391-241b8780-458d-11e9-828b-1206e88a56fe.png)

Is this going to be what the user sees in the 7.3 release?

**Comment by TovaCohen** [comment]
@heiko-braun , @gashcrumb , **We cannot document this the way it is.** Something has to change for 7.3. At the very least, can we change the labels to "Log Step" and "Log Connection"? Or maybe to "Log Activity" and "Log to Pod". Depending on how you change the labels, I can suggest the description that appears below the label. 

Here's a link to a Google document that has the user doc for logging. The user has no way to know which Log card is a step and which Log card is a connection. While the user doc consistently compares and refers to Log steps and Log connections. I highlighted the text that will be confusing to users. As you can see, there's a lot of yellow highlights in this document: 

https://docs.google.com/document/d/1_1yoVEWO8aStaw0CIdldI-JfKHQEIA3SaEl6zyX2eY8/edit?usp=sharing

Please let me know what the plan is.

**Comment by gashcrumb** [comment]
This was done btw.
