### ISSUE TITLE
Inability to create data mapping until first publish

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#4427]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
It seems that it is not possible to create data mappings when first creating integrations, at least when working with templates. Either the data mapping reports an error that the data type of step below should be specified (step below was always template).
![screenshot from 2019-02-04 16-04-31](https://user-images.githubusercontent.com/46345469/52216633-ff016e00-2896-11e9-9dac-5fb2edb08886.png)
Or it seemed like somehow was storing errors from previous mappings and trying to apply those (will provide a screenshot and steps to reproduce when I manage to reproduce it).
You can get to data mapping configuration only after publishing it and later editing, only then is the data mapping accessible without any errors.

After publishing: 
![screenshot from 2019-02-04 16-14-52](https://user-images.githubusercontent.com/46345469/52217092-0aa16480-2898-11e9-9481-69f6a3c83425.png)

**Comment by heiko-braun** [comment]
@igarashitm Any idea?

**Comment by gashcrumb** [comment]
We probably need to implement the roundtrip described in #4406 to also fix this one, most likely once the integration is published the right data shape is put into the flow.

Still tricky though, you have to actually finish your template step first before you can put a data mapper in front of it, otherwise if you go and change the template you potentially change the data shape, and then you're back here again I suspect.

**Comment by mmuzikar** [comment]
I managed to reproduce the issue with trying to apply different mappings. It causes these errors: 
![screenshot from 2019-02-05 13-56-31](https://user-images.githubusercontent.com/46345469/52274863-3121d700-294e-11e9-86b7-c97da6ac0333.png)
As you can see it's only data mapping I have in that integration and also I didn't have any prior to creating this one **in this integration**.
It happens when you create a data mapping before (for example I created data mapping from create_lead to add_lead) then delete it and don't publish. What seems weird is that it persists between different integrations.

**Comment by gashcrumb** [comment]
I'm sorry, can you narrow this down to the sequence of steps you're doing to reproduce this?  It definitely sounds like something's broken but it's not clear exactly where to start from that description.  A clear list of steps to reproduce the problem would be very helpful :-)

**Comment by mmuzikar** [comment]
I hope this should be the minimal setup required
This one should work:
Create integration from db (create_lead) to db (add_lead)
Map the data between those two connections however you like
Add template step above data mapper
And try to map data to the template 

This one should work out... if not give me a few minutes as it persists across all integrations and I have to restart minishift

**Comment by gashcrumb** [comment]
Hmm, I couldn't reproduce it here, but also I've heavily refactored quite a few things in the editor since then, so it's worth a re-test if you get a chance.

What kind of template did you use on the template step BTW if it persists?

**Comment by mmuzikar** [comment]
Yeah I can't reproduce it either on the latest version of Syndesis.

**Comment by mmuzikar** [comment]
Hey maybe there was a misunderstanding here, just to clarify I can't reproduce this issue:

> I managed to reproduce the issue with trying to apply different mappings. It causes these errors:
> ![screenshot from 2019-02-05 13-56-31](https://user-images.githubusercontent.com/46345469/52274863-3121d700-294e-11e9-86b7-c97da6ac0333.png)
> As you can see it's only data mapping I have in that integration and also I didn't have any prior to creating this one **in this integration**.
> It happens when you create a data mapping before (for example I created data mapping from create_lead to add_lead) then delete it and don't publish. What seems weird is that it persists between different integrations.

But the original one is still a problem, the integration has to be published first in order to be able to add the data mapping step.

**Comment by mmuzikar** [comment]
@gashcrumb I run into the same when those errors show, but to be honest I can't imagine on which occasion user would do these steps and expect everything to work, but if you are interested you can reproduce it by:
- start: sql periodic invocation "select * from contact"
- end: log with template or whatever you have to use datamapper for
- add datamapper
- remove the starting step
- add the same step and you get
![image](https://user-images.githubusercontent.com/46345469/54033041-8f431380-41b3-11e9-8757-37ffb68ccb0d.png)
But these errors don't persist and if you click on the "saved" datamapping it gets cleared with the next opening with datamapper.

**Comment by gashcrumb** [comment]
Yeah, in this case it's a stale mapping.  The data mapper refers to the old step ID in it's mapping, but that's invalid since the start step was removed and replaced, even though it's the same type, the replaced step will have a new ID.  We have a few issues that capture this behavior and haven't figured out yet exactly what should happen, like [this](https://github.com/syndesisio/syndesis/issues/3864).
