### ISSUE TITLE
Suppport multi-selection for form fields

### ISSUE THREAD

**Issue by rkorytkowski** [syndesisio/syndesis#4429]
## This is a...

<pre><code>
[x ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

In FHIR connector we need the user to be able to specify a list of contained resource types in a form of a multiselect field on a configure action step.

A multiselect field is supported by the underlying ng-dynamic-forms library, but not by our UI and backend. 
The change in UI is straightforward and backwards compatible.

In the backend we need to modify https://github.com/syndesisio/syndesis/blob/master/app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandler.java#L95 to accept Map<String, Object> properties since multiple choices will be deserialized as String[] and not String.

It will result in us having to refactor a number of public methods e.g. EncryptionComponent.encryptPropertyValues/.decrypt, WithConfigurationProperties.* and possibly a few more, which I missed at first glance. It's a rather straightforward refactoring, but not sure what's our policy on refactoring public methods in a backwards incompatible way. Are these part of our API contract e.g. when implementing extensions?

Alternately we could just modify ConnectionActionHandler.enrichWithMetadata to accept Map<String, Object> and convert it to Map<String, String> by converting any String[] value to a String using some custom separator like '|#|'. It's far from ideal, but does not require any refactoring and I did use this method initially as a workaround.

Which way to go? @paoloantinori, @zregvart, others?

**Comment by zregvart** [comment]
I think we have the notion of a property having a single value through Syndesis. I think perhaps the easiest way would be to keep the property as single value String, and introduce a separator for multiple values. Even more so if in end this is likely to be used in a Camel endpoint URI where we usually place multiple values joined by a separator character (IIRC typically comma).

**Comment by valdar** [comment]
@zregvart +1

**Comment by rkorytkowski** [comment]
@zregvart, would you support using a comma in such a case or some more unique separator?

**Comment by zregvart** [comment]
> @zregvart, would you support using a comma in such a case or some more unique separator?

Mostly depends on the data being given and if it can contain a comma. In general I would prefer the comma or semicolon. If the data can contain the separator character but not in a great percentage of cases I would opt to escape or encode the separator when part of the data.

**Comment by rkorytkowski** [comment]
I went ahead and used a comma as a separator.

**Comment by rkorytkowski** [comment]
There's an issue with this change, which I haven't noticed earlier. If you attempt to use a simple select (single selection), the component sends a json array with one element and not a simple string. It's strange, because it only happens, if you happen to change the initial value. If you do not touch the initial value it will be correctly sent as string.

To reproduce:
1) Create a fhir connector and create a new integration
2) Choose timer as initial step
3) Choose FHIR as final step with read as action
4) Change the resource type
Observe the data sent by the component to the server.

@riccardo-forina, I'd appreciate your help.

**Comment by rkorytkowski** [comment]
I ended up with https://github.com/syndesisio/syndesis/pull/4478 as I couldn't make [multiple]="model.multiple". It always displayed properly, but produced wrong data for some reason.

**Comment by mastepan** [comment]
@rkorytkowski how can I verify the changes work please?

**Comment by rkorytkowski** [comment]
@mastepan, you can find multi-selection being used in the FHIR connector e.g. in the Transaction action when you select multiple resources to be included in a transaction and see them listed in the Data Mapper step added before the Transaction action.

**Comment by mastepan** [comment]
@rkorytkowski The resources are included as items of the Transaction. They aren't before the Transaction in the datamapper. Is that correct?
![transaction_items](https://user-images.githubusercontent.com/8707251/56141351-f2874900-5f9c-11e9-8289-626233dfe019.png)

**Comment by rkorytkowski** [comment]
Yes, it's correct. They are part of the transaction. It proves multiselect works as expected.

**Comment by mastepan** [comment]
verified
