### ISSUE TITLE
Syndesis Logout Page Design

### ISSUE THREAD

**Issue by jameslau** [syndesisio/syndesis#4434]
## This is a...
<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Documentation issue or request
</code></pre>

## The problem
Once a user logs out of the Syndesis application, there is a simple logout page that still uses old PF3 styling. 

![screen shot 2019-02-04 at 3 59 37 pm](https://user-images.githubusercontent.com/1402829/52237164-d5e0dd80-2896-11e9-9869-8f95e0990661.png)

![logout](https://user-images.githubusercontent.com/1402829/52237109-aaf68980-2896-11e9-81e9-7fd44d830e79.gif)

## Expected behavior
What can we do to improve on the design and user experience? Perhaps a possible PF4 styling upgrade is needed?

**Comment by jameslau** [comment]
Hi @amysueg and @dongniwang, can we make a plan for this portion of the application?

**Comment by dongniwang** [comment]
Wondering if we can just redirect users to the login page and display an inline message or something similar saying that they've successfully logged out. 

@mcoker - Do you know if there's anything in PF4 that may provide a direction?

**Comment by gashcrumb** [comment]
Keep in mind that we don't control the login page, that comes from openshift.

**Comment by mcoker** [comment]
@dongniwang looks like that pattern is used for session timeouts https://www.patternfly.org/pattern-library/communication/session-timeout/#overview

<img src="https://www.patternfly.org/pattern-library/communication/session-timeout/img/PF-SEW-02.png">
