### ISSUE TITLE
OpenAPI v3.0 customization freezes Syndesis frontend

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#4441]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Trying to create an API client connector with OpenAPI v3.0 to freezes the frontend of Syndesis.
Note that nowhere in the page is specified which version should be used.
As an example I used [https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore.yaml](https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore.yaml).
No link can be clicked, only way to get out of that situation is to enter a new URL or refresh.
OpenAPI v2.0 work just fine.

**Comment by zregvart** [comment]
Requirement to use OpenAPI 2.0 is documented in [7.1. Develop REST API client connectors](https://access.redhat.com/documentation/en-us/red_hat_fuse/7.2/html-single/integrating_applications_with_fuse_online/#developing-rest-api-client-connectors_custom) and in [5.3. Create a REST API connector](https://access.redhat.com/documentation/en-us/red_hat_fuse/7.2/html-single/fuse_online_sample_integration_tutorials/#amq2api-create-rest-api-connector_amq2api).

**Comment by amysueg** [comment]
This seems straightforward to me. The UI shouldn't "freeze" if a file type is not recognized. We should instead raise an error message or warning that that API version of the selected file is not supported. 
@zregvart is that possible to do from the backend?
@gashcrumb to see how feasible it would be to bring up an error message in the UI once the user has tried to add a file that uses an unsupported API version
@TovaCohen for the actual wording to use in an error message

**Comment by TovaCohen** [comment]
For the error message, maybe: 
This document cannot be uploaded. Provide an OpenAPI 2.0 document.

**Comment by zregvart** [comment]
The provided file is validated against the OpenAPI 2.0 schema. So right now this generates errors:

![Screenshot_2019-04-01 Syndesis](https://user-images.githubusercontent.com/1306050/55352705-c7432b00-54c1-11e9-9ec8-b250372cd048.png)

I think this was improvement that we made via #4542.

**Comment by zregvart** [comment]
(And) We can add additional validation that the user provided file is an OpenAPI 2.0 (not OpenAPI 3.0) on the backend and create a more meaningful error for the user.

**Comment by amysueg** [comment]
@zregvart may i reassign this to you then so you can do that additional validation?

**Comment by zregvart** [comment]
With #5587 the error will look like:
![Screenshot_2019-06-04 Syndesis(2)](https://user-images.githubusercontent.com/1306050/58887300-aaa3b900-86e5-11e9-9273-a0b51060be58.png)
![Screenshot_2019-06-04 Syndesis(1)](https://user-images.githubusercontent.com/1306050/58887307-ac6d7c80-86e5-11e9-83a9-c3f722e5347b.png)

**Comment by dongniwang** [comment]
Looks great to me! Thanks @zregvart!

**Comment by mmuzikar** [comment]
Works even on react, great work @zregvart !
