### ISSUE TITLE
Workflow forgets I was creating an integration when I add a new connector

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#4449]
See also **https://issues.jboss.org/browse/ENTESB-11567**

## This is a...

<pre><code>
[x ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When I create an integration of API provider flow, I can choose to add configure a new connection. If I do this I never get returned to my integration. The workflow is broken and I must manually navigate back to where I began.

Expected behavior:
After configuration of the connection is complete I returned back to the integration from where I came.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11567**
