### ISSUE TITLE
Integration Health Check

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#445]
|<img src="https://avatars1.githubusercontent.com/u/1868933?v=4" valign="middle" width="22px"></img> @lburgazzoli | [2017-10-16](https://github.com/syndesisio/syndesis-project/issues/131) | Epic  |
|-|-|-|

From camel 2.20 we have some native support for health checks:

- ability to restart a failing route (see #56)
- an initial and experimental implementation of context Health Checks so we can monitor routes health and add custom checks when needed as well as integrating external checks (i.e. from consul)

We should discuss what it is missing from syndesis pov.

**Comment by gashcrumb** [comment]
This appears to be stale, if it needs to be a thing create an epic and flesh out what needs to be done
