### ISSUE TITLE
Contribute kudu component to Apache Camel

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#4457]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Once ready, we should contribute the kudu component to Apache Camel and remove the one in Syndesis.

**Comment by oscerd** [comment]
I think this can be done for 7.5. It's important to contribute back stuff.

**Comment by lgarciaaco** [comment]
Yes please, I will come back to it then

**Comment by Delawen** [comment]
@lgarciaaco do you have time? Should I do it instead?
