### ISSUE TITLE
Next button instead of Done

### ISSUE THREAD

**Issue by mkralik3** [syndesisio/syndesis#4458]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Why is in the Invoke SQL Next button when after clicking on the button the step is configured. In the previous versions was there Done button. It is confusing to click on the Next button when no next configure page exists for this step.

For the final step, I choose PostgresDB and Invoke SQL and I insert SQL statement.
![image](https://user-images.githubusercontent.com/16251792/52346029-f76cd100-2a1e-11e9-8263-4980f9cb39b6.png)

**Comment by heiko-braun** [comment]
@gashcrumb Is this still open?

**Comment by thomasryan4578** [comment]
No it’s closed

Ryan Buckley
8433041998

**Comment by mkralik3** [comment]
I am still able to reproduce it on the master (22beae32f32fe42f3bb696f85ae5ef5acf938267)
