### ISSUE TITLE
Connection usage reports incorrect integration usage count

### ISSUE THREAD

**Issue by avano** [syndesisio/syndesis#4464]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
When inspecting connection details in the UI, it reports in how many integration the connection is used.

I have only one integration: `AMQ -> HTTP -> AMQ`, where both AMQ are from the same connection and when I navigate to AMQ connection details, I get `Usage: Used by 2 integrations`, so it counts one integration two times because it is used twice

## Tasks involved / Steps to Reproduce

1. create amq -> amq integration with the same connection
2. inspect amq connection details

**Comment by KurtStam** [comment]
@avano I think this got fixed in a recent refactoring. I can no longer reproduce it.

**Comment by avano** [comment]
@KurtStam yes, looks OK now
