### ISSUE TITLE
SQL Connector: Return generated keys for INSERT statement

### ISSUE THREAD

**Issue by jcordes73** [syndesisio/syndesis#4466]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
The SQL connector should return generated keys for INSERT statements, so that these can also be mapped during integration.

Example:

RESTFul PUT statement where an ID is expected as a return parameter and data is actually stored in a PostgreSQL instance.

**Comment by zregvart** [comment]
Currently the only way of doing that is to wrap the `INSERT` statement in a stored procedure.
A while back we had the idea of replacing the SQL parser logic we have in the SQL connector with the use of [`PreparedStatement::getMetadata`](https://docs.oracle.com/javase/7/docs/api/java/sql/PreparedStatement.html#getMetaData()) for generating output data shape and [`PreparedStatement::getParameterMetaData`](https://docs.oracle.com/javase/7/docs/api/java/sql/PreparedStatement.html#getParameterMetaData()) for generating input data shape.

This would allow statements such as:
`INSERT INTO TODO (TASK) VALUES (?) RETURNING ID`

To generate data shapes with the data type of `TASK` as input and `ID` as output.

**Comment by KurtStam** [comment]
Code complete but I can't test end2end b/c stuff is broken at the moment

https://github.com/KurtStam/syndesis/commit/6e0d7895cc5028f2ccba6b8ab27a07803587f715

**Comment by zregvart** [comment]
@KurtStam thanks, though I really think we should replace the SQL parser we have with `getMetadata` and `getParameterMetaData`, i.e. do no parsing on our own. With parsing we'll always be one step behind or we won't support some use cases. With `getMetadata` and `getParameterMetaData` we put all that logic to the one place it is maintained - to the driver and the database's own SQL parser.

The code in https://github.com/KurtStam/syndesis/commit/6e0d7895cc5028f2ccba6b8ab27a07803587f715 relies on a specific/subset database implementation, some databases have a `SERIAL` type, `IDENTITY` or `AUTO_INCREMENT` attributes, some schemas may a `SEQUENCE` for generating keys or triggers. (see http://troels.arvin.dk/db/rdbms/#mix-identity).

**Comment by KurtStam** [comment]
@zregvart 

1. The query isn't actually parsable by the database if the query contains camel paramaters. We're already trying to use the db metadata as much as possible. 

2. Your second point is well taken. I do some tests with MySQL, Postgres and Oracle, to see what metadata is set in that case.

**Comment by KurtStam** [comment]
@zregvart I thought I had it all working, but then I tested with Mysql and found out that ParameterMetaData is not accurate until it is set: 

https://github.com/KurtStam/syndesis/blob/autoincrement/app/connector/sql/src/main/java/io/syndesis/connector/sql/common/SqlStatementParser.java#L118

I've tried a few things but so far this is a show stopper. Seems to work ok in Derby, Postgresql and Oracle.

**Comment by zregvart** [comment]
@KurtStam you don't need to `execute` the `PreparedStatement` here:

https://github.com/KurtStam/syndesis/blob/a53a63c539e189b623bdcc3887ebdc32935afad6/app/connector/sql/src/main/java/io/syndesis/connector/sql/common/SqlStatementParser.java#L109

Let me checkout your branch and try a few things...

**Comment by KurtStam** [comment]
>you don't need to `execute` the `PreparedStatement` here:
@zregvart y that was a desperate attempt to get the mysql driver to give me something..

**Comment by zregvart** [comment]
Trying to create an integration test with testcontainers, not having much luck atm...

**Comment by KurtStam** [comment]
@zregvart ah just use unit tests like this one:

https://github.com/KurtStam/syndesis/blob/autoincrement/app/connector/sql/src/test/java/io/syndesis/connector/sql/SqlConnectorTest.java

changing the connection settings here:
https://github.com/KurtStam/syndesis/blob/autoincrement/app/connector/sql/src/test/resources/test-options.properties
