### ISSUE TITLE
base path in API spec

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#4471]
## This is a...

<pre><code>
[x ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When I upload my openapi file that includes a basepath:
Basepath: /api/43

The url displayed in syndesis once Im finished doesnt include the base path.
This causes confusion when a curl doesn't work, the expectation (user feedback) is that the url displayed is the full path

**Comment by heiko-braun** [comment]
@zregvart Do you think this can be done in 7.3?

**Comment by zregvart** [comment]
@gaughan is this for custom API client connectors or for API provider functionality? Do you mean the URL shown on the integration details?

Also of interest #3948.

**Comment by gaughan** [comment]
APi Provider, silimar to #3948 
![image](https://user-images.githubusercontent.com/674767/52478416-47f54300-2b73-11e9-8b69-f101fe2918e3.png)
