### ISSUE TITLE
Once I publish an integration I want to access the logs

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#4473]
## This is a...

<pre><code>
[ x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Currently, when I publish I briefly get the opportunity to access the logs as the build and deploy process executes. I would like to access these logs easily form other views of my integration

Can we link to the openshift console and or grafana maybe?

**Comment by dongniwang** [comment]
There's a way to view log in OpenShift on the Activity tab of the integration details page. Is this what you're looking for? 

![image](https://user-images.githubusercontent.com/24943812/52442940-6ebf6500-2af2-11e9-8d27-f126adc41d31.png)

**Comment by gaughan** [comment]
That link is not always there tho:
![image](https://user-images.githubusercontent.com/674767/52444767-50a83380-2af7-11e9-9a5f-78f54002f2e0.png)

During the build process, the log link is front and center if the publish fails the log link disappears.
In the activity tab that link may not be there.

**Comment by dongniwang** [comment]
The screenshot you shared is interesting since you have a successfully published integration but nothing in the activity tab. 

I'm not so sure the logic behind when does the View Log link show up. 

Maybe @KurtStam or @zregvart knows?

**Comment by zregvart** [comment]
The link `View Log in OpenShift` appears if there is at least one activity captured:

https://github.com/syndesisio/syndesis/blob/839cda6b00a719b8a712d957e7868f74ed18bd40/app/ui/src/app/integration/integration_detail/integration_activity/integration-activity.component.ts#L164-L170

**Comment by gaughan** [comment]
That makes sense, but can we point to other logs if something goes wrong, like builds logs? Or @dongniwang do you think we add all available logs options at all times?

**Comment by dongniwang** [comment]
@gaughan What do you mean by "all available logs options"...How many log options do we have? And how are they different? 

Assuming users want to see logs because they want to troubleshoot, what are some other scenarios that they want to see or have access to logs?

Wondering if this is a functionality that relates to the application level notification system?

**Comment by gaughan** [comment]
Build, deployment or pipeline logs.
Scenarios are that it deployed successfully but for some reason is not reachable or working as expected. Or it failed to deploy due to an issue like resource constraints or a config issue or permissions.
Some could be application level for sure.

**Comment by dongniwang** [comment]
If this is something we wanted to include for 7.4, can @heiko-braun help find a backend engineer to help me understand things more?

**Comment by gaughan** [comment]
I think we can address this in 7.4 
There are two issues that caused this the published url didn't amend the base path from the api defn uploaded. The log file of the integration is always available. 
One option we could take is: display the build log and replace once the integration pod is up. @heiko-braun  this option may be the least invasive, wdyt?

**Comment by heiko-braun** [comment]
@gaughan  I have moved it to 7.4. We need to bring it up again once we start looking the scope for that release.
