### ISSUE TITLE
API Client location in UI

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#4474]
See also **https://issues.jboss.org/browse/ENTESB-11566**

## This is a...

<pre><code>
[ x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

With the addition of API provider, the location of API client connection is now difficult to navigate.
We should look to standardize the two options and place a card next to API Provider?

**Comment by dongniwang** [comment]
@gaughan Can you provide some context about the request? 

What do you mean by "a card next to API Provider"?

**Comment by gaughan** [comment]
Currently, you go to integration and can provide an API but not create an API. Create an API is under customizations.
The issue is that our two option for API interaction are in very separate parts of the application
wdyt?

**Comment by zregvart** [comment]
Perhaps we could envision an UI that has everything available on the same screen:
 - creating API client - via the same wizard we currently have
 - adding extensions - could look much the same as creating a connection
 - connecting to an OAuth enabled service - first few screens of the create new connection wizard could be entering the values users now enter on the OAuth settings page

Not sure what trade-offs would emerge but perhaps we could consider something like this.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11566**
