### ISSUE TITLE
Display prompt if you really want to leave when leaving integration creation

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#4475]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
If you are about to leave when creating connection, you get a prompt asking whether you really want to leave. It would also make sense if this prompt was displayed when leaving integrations. As most of the time you don't really want to loose the integration you have been working on and loosing that progress by clicking somewhere can be frustrating.

**Comment by zregvart** [comment]
cc @syndesisio/uxd

**Comment by dongniwang** [comment]
I think at some point we had a discussion about having a confirmation modal for the create integration workflow. And we started the work on[ integration editor diagram ](https://github.com/syndesisio/syndesis/issues/2870). 

I do agree we need confirmation for leaving the workflow, unless autosave is happening in the near future. 

And I think we have confirmation for the API Provider flow, so maybe it's not too complicated to have that for regular integration flow? WDYT?  @riccardo-forina @gashcrumb
