### ISSUE TITLE
swagger-core adding superflous `responseSchema` property

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#4477]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Seems that the Swagger API we use (`swagger-core`) is adding `responseSchema` elements to responses. This triggers schema violation in Apicurio.

**Comment by mmajerni** [comment]
Is this resolved? Because I still can set responseSchema elements to responses.
![rts](https://user-images.githubusercontent.com/22192892/53341062-d7884900-390a-11e9-8945-ba2bf36c489d.png)

**Comment by zregvart** [comment]
@mmajerni superfluous JSON property caused an error to be reported in Apicurio, in the _Source_ OpenAPI JSON/YAML you would see a property named `responseSchema` that is not part of the OpenAPI specification; `schema` is and that's what you're seeing in the UI (screenshot).

For example this is valid:

```yaml
        get:
            summary: 'List All Tests'
            description: 'Gets a list of all `Test` entities.'
            operationId: getTests
            responses:
                '200':
                    description: 'Successful response - returns an array of `Test` entities.'
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/Test'
```

This is not valid:
```yaml
        get:
            summary: 'List All Tests'
            description: 'Gets a list of all `Test` entities.'
            operationId: getTests
            responses:
                '200':
                    description: 'Successful response - returns an array of `Test` entities.'
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/Test'
                    responseSchema:
                        type: array
                        items:
                            $ref: '#/definitions/Test'
```

**Comment by mmajerni** [comment]
@zregvart OK great thanks. In that case: Verified by QE.
