### ISSUE TITLE
Resource discovery

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#448]
Resources are loaded from deployment.json which is quite limited so we should have a sort of resource service (that can be a separated pod) that grab resource from a pluggable list of back-ends like:

- jsondb
- classpath
- configmap
- distributed cache
- external key/val store
- filesystem

**Comment by rhuss** [comment]
@lburgazzoli what do you actually mean with 'resources' ? The connector definitions ?

**Comment by lburgazzoli** [comment]
basically any static definition that as today ends up in the jsondb

**Comment by lburgazzoli** [comment]
it is linked to https://github.com/syndesisio/syndesis/issues/449 as we should be able to trim the model as much as possible so it can be safely included in the integration runtime so i.e, we can just store the steps and the resources needed to set-up the camel runtime (i.e. we need to exclude connection secrets)

**Comment by rhuss** [comment]
Ok, got it. Can we make a larger story as epic and link these two stories to this Epic then (converting these to plain issues).

**Comment by lburgazzoli** [comment]
sorry I did comment on the wrong issue before :)
