### ISSUE TITLE
Changes to the OpenAPI specification that do not modify flows are not saved

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#4480]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

When editing OpenAPI details that do not affect any flows the updated OpenAPI specification is not stored.

For instance when changing the version property of the OpenAPI document.

**Comment by mmajerni** [comment]
Verified by QE.
