### ISSUE TITLE
[Datamapper] No supported source data type was found. Data type needs to be configured before Data Mapper step is added.

### ISSUE THREAD

**Issue by avano** [syndesisio/syndesis#4483]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Trying to use datamapper in AMQ->IRC integration:

1) start with AMQ subscribe step
2) specify output datashape as json instance with the specification `{"messageOut":"test"}`
3) add IRC publish message to channel step
4) specify input datashape as json instance with the specification `{"messageIn":"hello"}`
5) put datamapper in between the steps

![wd3e](https://user-images.githubusercontent.com/7081216/52480027-d6d18200-2baa-11e9-913f-1cd8b18418a8.png)

**Comment by avano** [comment]
this is probably related to amq connector, as in our test suite there was always amq involved in failed test

**Comment by heiko-braun** [comment]
@KurtStam Do you have bandwidth to look into this?

**Comment by KurtStam** [comment]
@avano can you attach an export of the scenario?

**Comment by avano** [comment]
@KurtStam it looks like the issue got resolved in the meantime, as with latest version of syndesis I'm not able to reproduce it anymore. I'll wait for the results of our jobs and will close the issue eventually.

**Comment by avano** [comment]
looks ok now
