### ISSUE TITLE
Creating API provider based integration - cancel/save/publish buttons behavior broken

### ISSUE THREAD

**Issue by tplevko** [syndesisio/syndesis#4487]
## This is a...

<pre><code>
[ ] Feature request
[ x ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

I was trying to create new API based integration - the buttons cancel/save/publish seem to be broken in the API provider definition phase. 

## Screenshot

![out](https://user-images.githubusercontent.com/4180208/52487125-2751db00-2bbd-11e9-9635-e937dbb64069.gif)

**Comment by gashcrumb** [comment]
Ah, think on some of those pages we probably just need to hide those buttons.

**Comment by tplevko** [comment]
OK now
