### ISSUE TITLE
API provider integration definition seems to be broken

### ISSUE THREAD

**Issue by tplevko** [syndesisio/syndesis#4488]
## This is a...

<pre><code>
[ ] Feature request
[ x ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

When trying to create an API provider based integration - it's not really working ATM

## Screenshot

![out](https://user-images.githubusercontent.com/4180208/52487528-240b1f00-2bbe-11e9-9978-b49d0e4c534a.gif)

## Tasks involved / Steps to Reproduce

1. Create a new integration
2. Select URL for API definition - e.g. http://petstore.swagger.io/v2/swagger.json
3. select option e.g. GET /pet/{petId}
4. the view does not work right

**Comment by heiko-braun** [comment]
@syndesisio/ui-api A low hanging fruit somebody wants to tackle?

**Comment by riccardo-forina** [comment]
We are working on that here #4467

**Comment by gashcrumb** [comment]
Yeah, this is already being tracked in the issue Riccardo linked to, so this is a duplicate.
