### ISSUE TITLE
Simplify integration definition

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#449]
The integration structure contains some boilerplate bits like
- 'copy and paste' info such has Actions, Connectors, Extension & so on that can be retrieved by the back-end when needed
- connections related data (i.e. oauth tockens) that are already available on the backend-side

We should simplify it and let it contains only the bits that are not available on back-end

**Comment by rhuss** [comment]
With 'back-end' do you mean the _runtime_ ?

Any suggestion (or example) how to simplify ?

**Comment by lburgazzoli** [comment]
Yeah I mean on syndesis-rest, let's think about an endpoint step, in the model it is defined like:

```java
class Step {
    Optional<Action> getAction();
    Optional<Connection> getConenction();
    Optional<Extension> getExtension();
}
```

Then `Connection` is defined like:

```java
class Connection {
    Optional<Connector> getConnector();
    Optional<String> getConnectorId();
}
```

But on `syndesis-rest` we do already have all the info so the ui does not need to send them back so we can have a step defined like:

```java
class Step {
    Set<ResourceIdentifier> getResources();
}
```
Or if we want to go with a typed model:

```java
class EndpointStep {
    ResourceIdentifier getAction();
    ResourceIdentifier getConenction();
    Optional<ResourceIdentifier> getExtension();
}
```

So on `syndesis-rest` we can look-up bits from the storage. When the UI need to grab an integration we can create something like:

```java
class IntegrationDefinition {
    Integration getIntegration();
    List<T extends ResourceIdentifier> getResources();
}
```

So i.e. we can also avoid to send back to the ui duplicated info (i.e. same extension definition used multiple time).
