### ISSUE TITLE
Error when defining a simple Timer

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#4490]
![grafik](https://user-images.githubusercontent.com/99080/52498316-c33d1000-2bd8-11e9-98ab-20fd65067dd9.png)

What does 'check your sorting arguments' mean ?

**Comment by rhuss** [comment]
It's from the latest pushed image (installed via "syndesis minishift")

**Comment by rhuss** [comment]
```


Syndesis:
    1.6-SNAPSHOT

Build ID:
    0bb6746b-6bec-490d-a1dc-5ac83a0565e9

Commit ID:
    7f432df13f879cebd701e1876974a585003525d6
```

**Comment by zregvart** [comment]
Duplicate of #4486?

**Comment by rhuss** [comment]
yep, think so.
