### ISSUE TITLE
Implement UXD design for add to CI/CD dialog

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#4494]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Implement this design -> https://redhat.invisionapp.com/share/E9QCV528WVN#/screens/345130937

Using this info -> https://github.com/syndesisio/syndesis/issues/4326

backend API -> https://github.com/syndesisio/syndesis/blob/f178db73b5124913ffeaf84456b92b0e4cb2b78b/app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/continuousdelivery/ContinuousDeliveryHandler.java

Object definition -> https://github.com/syndesisio/syndesis/blob/f178db73b5124913ffeaf84456b92b0e4cb2b78b/app/common/model/src/main/java/io/syndesis/common/model/integration/ContinuousDeliveryEnvironment.java

**Comment by mkralik3** [comment]
Missing "Last tagged" from design https://redhat.invisionapp.com/share/E9QCV528WVN#/screens/345130941
![image](https://user-images.githubusercontent.com/16251792/52949215-f3747380-337b-11e9-846e-e14abffc2438.png)


Probably the bug:
When I click on edit and change the name, it works properly. However, when I click on edit but I don't change the name and click on Save, the Tag is deleted.
![output](https://user-images.githubusercontent.com/16251792/52949084-9973ae00-337b-11e9-92ad-24a6ae250ce8.gif)

**Comment by gashcrumb** [comment]
@mkralik3 can you raise these as separate issues, thanks!

**Comment by mkralik3** [comment]
@gashcrumb 
Yes, https://github.com/syndesisio/syndesis/issues/4617
What about "Last tagged" label? Is it missing or it wasn't include it to the UI from design?

**Comment by mkralik3** [comment]
For it, I created another issue https://github.com/syndesisio/syndesis/issues/4716. 
This can be closed as verified.
