### ISSUE TITLE
Google sheets connector pivot table properties can be specified only via datamapper

### ISSUE THREAD

**Issue by mmelko** [syndesisio/syndesis#4500]
See also **https://issues.jboss.org/browse/ENTESB-11484**

## This is a...

<pre><code>
[x ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
I might be missing some context to pivot tables but I believe it's not the best option to setting up the pivot table only via data-mapper custom properties (see demo ([here](https://drive.google.com/file/d/1M9rrbo9mXdH6AfNIRsio_-NV3pXDX72m/view)). From my pov it's mainly pivot table configuration and the best would be to configure it during connection settings via some form. This would be probably better from UX perceptive too. 

On the other hand ability to overwrite privot table properties via DM is also nice.  

Here is basically only pivot table configuration with no real mapping(except spreadsheetId):
![screenshot_20190213_105321](https://user-images.githubusercontent.com/6814482/52703021-b4aa7c00-2f7d-11e9-891e-082763bc6d42.png)

**Comment by amysueg** [comment]
@dongniwang Can you take a look at this one? thanks.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11484**
