### ISSUE TITLE
Syndesis crashes when creating any integration

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#4509]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When creating any integration, Syndesis stops working properly when building said integration, after that it alerts you that it can't connect to the server and in a few moments crashes completely.

I have attached log from syndesis-server pod, and even when syndesis-ui starts again and the status is running in openshift console, the ui does not work.

[log.txt](https://github.com/syndesisio/syndesis/files/2851495/log.txt)

**Comment by tplevko** [comment]
It seems to work fine with the latest syndesis build.

**Comment by heiko-braun** [comment]
Closing according to @tplevko comments
