### ISSUE TITLE
[UI] Don't show aggregate as the last step of integration in the integrations list?

### ISSUE THREAD

**Issue by avano** [syndesisio/syndesis#4516]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
@christophd If I understood it correctly, the `forEach` and `endForEach` were replaced by `split` and `aggregate`, but their meaning is still the same, am I correct? So you always should do `split -> something -> aggregate`? 

When I was trying the scenario https://github.com/syndesisio/syndesis/issues/4515 , my integration in the integration list looked like this:

![before_1](https://user-images.githubusercontent.com/7081216/52580711-3937b600-2e29-11e9-8ac6-9b557945b9f2.png)
![before_2](https://user-images.githubusercontent.com/7081216/52580714-3b017980-2e29-11e9-8fc1-a80d79358d02.png)

After the upgrade, it was changed to this (I'm assuming it is correct :grin:):
![after_1](https://user-images.githubusercontent.com/7081216/52580731-43f24b00-2e29-11e9-9232-7c50d5d19034.png)
![after_2](https://user-images.githubusercontent.com/7081216/52580740-45bc0e80-2e29-11e9-9ee6-8efdc185cb4d.png)

I lost the information, what the actual finish step of the integration is, as the `aggregate` is just a "meta" step.

What first came to my mind was to not show such step in the integration list if it is the last step of the integration. When examining the actual integration, then the aggregation step should be visible.

**Comment by heiko-braun** [comment]
@christophd It's good to have a discussion, but keep in mind that we are past feature freeze. I'd say changes are ok, if they are low hanging fruits without side effects. Anything bigger needs to be considered in 7.4

**Comment by avano** [comment]
looks better now
