### ISSUE TITLE
Twitter search "ignore previously found" is off center

### ISSUE THREAD

**Issue by tplevko** [syndesisio/syndesis#4520]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

When I select the search operation in twitter component, the "ignore previously found" text is off center with the checkbox and the popup help.

## Screenshot

![tw_off_center](https://user-images.githubusercontent.com/4180208/52621243-12b86000-2ea7-11e9-98cf-9349df8a4913.png)

**Comment by avano** [comment]
the same with amq and probably others
![azfz](https://user-images.githubusercontent.com/7081216/52634663-114b5f80-2ec8-11e9-8059-a954066631d3.png)

**Comment by tplevko** [comment]
Looks much better now, thanks!
