### ISSUE TITLE
NullPointerException - DataManager - server pod

### ISSUE THREAD

**Issue by mastepan** [syndesisio/syndesis#4523]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
NPE, more in the attached log. 
I can't create an integration, syndesis freezes in an integration editor (might be only one of the symptoms)

[syndesis-server-1 (1).log](https://github.com/syndesisio/syndesis/files/2855196/syndesis-server-1.1.log)

**Comment by christophd** [comment]
I had a quick look and I suppose that the resource update controller has received first change events on the vent bus (coming from auto DB migration) while not having yet received the application ready event.

This leads to the NPE as the schedulers are not initialized yet. Initialization is done when the application ready event is received.

I see two options: Either ignore all change events that are fired before the application ready event or do initialization as soon as subscription to the change event bus is done.

**Comment by zregvart** [comment]
Would making this:

https://github.com/syndesisio/syndesis/blob/ab824c669422289322b2fe1f0b0cc8200414ea6f/app/server/update-controller/src/main/java/io/syndesis/server/update/controller/ResourceUpdateController.java#L135

a `@PostConstruct` work?

**Comment by heiko-braun** [comment]
@zregvart  Are you able to look at it?

**Comment by zregvart** [comment]
> @zregvart Are you able to look at it?

Being mighty rhetorical here

**Comment by tplevko** [comment]
Verified
