### ISSUE TITLE
Documentation for back-up / restore procedure

### ISSUE THREAD

**Issue by sedroche** [syndesisio/syndesis#4525]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ x ] Documentation issue or request
</code></pre>

## Description

I see issues https://github.com/syndesisio/syndesis/issues/1119 and https://github.com/syndesisio/syndesis/issues/3194 have been created around backup and restore functionality.

[One of the comments](https://github.com/syndesisio/syndesis/issues/1119#issuecomment-403802358) suggests there is a way to do backup and restore currently.

Is there existing documentation for the current backup/restore procedure? or can documentation be created for this?

**Comment by sedroche** [comment]
@rhuss Might you have some info on this?

**Comment by heiko-braun** [comment]
@TovaCohen Would you prefer a fusedoc issue for this?

**Comment by TovaCohen** [comment]
@heiko-braun  I created this FUSEDOC Jira for this: 
https://issues.jboss.org/browse/FUSEDOC-3051

I see that this engineering issue is assigned to 7.3, but I don't know if we can commit to providing the doc for 7.3. I need a better understanding of the doc requirements.  So the FUSEDOC Jira is in the **Fuse Online doc backlog** for now. 

I think it would be best to close this issue, and use the FUSEDOC Jira to track the work. Having the engineering issues in one place and the doc issues in another place is not optimum, but it is what we have,
