### ISSUE TITLE
Basic filter, advanced filter, split, template steps as "Finish connection"

### ISSUE THREAD

**Issue by tplevko** [syndesisio/syndesis#4527]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

It's possible now to set the basic filter, advanced filter, split, template steps as finish connections, which is however not right from user POV.

## Screenshot
![end_step](https://user-images.githubusercontent.com/4180208/52631286-b3664a00-2ebe-11e9-8bd7-b7cc841f417e.png)

**Comment by gashcrumb** [comment]
Actually there could be valid reasons for any of these to be a final step.

**Comment by gashcrumb** [comment]
Yeah, I figure eventually someone would give me a list of what should be available at the end :-)

**Comment by tplevko** [comment]
There is still the question regarding Log step and Log connector - this will be sorted out in: https://github.com/syndesisio/syndesis/issues/4425 This one is verified.
