### ISSUE TITLE
Create services for the integration pods

### ISSUE THREAD

**Issue by alexkieling** [syndesisio/syndesis#4528]
Prometheus discovers what applications need to be scraped with the help of the ServiceMonitor. This object requires that each pod is exposed via a service, therefore we need to change syndesis to create a service to each integration pod.

**Comment by jamesnetherton** [comment]
I think we can close this given how I reconfigured the ServiceMonitor(s) for #4967.

**Comment by jamesnetherton** [comment]
Think I closed this in error. If we are to use a `ServiceMonitor`, then it needs to reference a service. Not all integrations will expose a service by default (the majority). So this task is still valid for the Spring Boot integration runtime at least.

**Comment by alexkieling** [comment]
Done in https://github.com/syndesisio/syndesis/pull/5908
