### ISSUE TITLE
Embedded apicurio has height of 0

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#4535]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

We're not showing the embedded Apicurio editor, the `<div class="editor-outline">` has a computed height of `0`. This is on `Review/Edit` of Custom API connectors feature.

## Expected behavior

See the whole editor.

## Screenshot

![screenshot from 2019-02-12 15-53-29](https://user-images.githubusercontent.com/1306050/52644141-90e42900-2ede-11e9-9729-fee2a4c0f419.png)

## Tasks involved / Steps to Reproduce

1. Go to Customizations / API Client Connector
2. Provide any OpenAPI 2.0 document
3. Click on Review/Edit

**Comment by dongniwang** [comment]
I can see the Apicurio editor in the API Provider workflow, wondering if the changes we introduced (the card layout) for the API Provider affected the API Client Connector view. 

@gashcrumb @riccardo-forina What do you think?

**Comment by riccardo-forina** [comment]
Ah yes, my bad! I can fix that tomorrow 😞

Il giorno mar 12 feb 2019 alle 19:17 Dongni (Iris) Wang <
notifications@github.com> ha scritto:

**Comment by zregvart** [comment]
Works as a charm, thanks!
