### ISSUE TITLE
High-fi design of DV List and DV Details page for Data Virtualization in Syndesis

### ISSUE THREAD

**Issue by deernano** [syndesisio/syndesis#4539]
## This is a...

<pre><code>
[ x ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
This issue is to track the high-fi design pages for Data Virtualization in Syndesis

1.  Data Virtualization page 
Data Virtualization List with status tracking

2. Data virtualization Details page
Manage a single virtual databases (VDBs)

## Expected behavior

1. Based on the low-fi design
Refine the page and improve the design based on the comments
2. Confirm with uxd, dev & pm, sign off the High-fi mockup.

## Related Issue
#4261

**Comment by deernano** [comment]
@rareddy @gaughan @kcbabo 
Hi team, we would like to sign off the design for Data Virtualization DV list & DV details page high-fi : https://redhat.invisionapp.com/share/AHQ773XQJ6V#/343366967_dv
Please help to reivew it, there are some comments from other devs that might need you to answer or review.
Thank you!

**Comment by gaughan** [comment]
LGTM, assuming comments discussed are part of the final

**Comment by rareddy** [comment]
When we consider some the changes we are talking with the new user stories document, I strongly feel there are going to be some modifications to the Virtualization Details page. So, sign off on all the screens here is still maybe a little premature.

**Comment by deernano** [comment]
@rareddy Will review the docment of [User Steps for Data Integration](https://docs.google.com/document/d/1PZsSjx-PCt3OC84rBJR-zM2XFIiveldL4ya4Gj89w_U/edit?ts=5c617e89#heading=h.q0k00oa7s766) and reconsider if we need to add more things

**Comment by deernano** [comment]
@rareddy @gaughan @kcbabo 
We still need to confirm or add funtions about 

- Add filter/search in dv-details page)
- Add relationship between views
-Whether we need to remain the function of importing a view in the dv-details page

**Comment by dongniwang** [comment]
Closing this issue now since we're tracking things in JIRA.
