### ISSUE TITLE
Low-fi design of View Page (Tabular Format) for Data Virtualization 

### ISSUE THREAD

**Issue by deernano** [syndesisio/syndesis#4540]
## This is a...

<pre><code>
[ x ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
This issue is to track the low-fi design pages of view page （Tabular Format) for Data Virtualization in Syndesis

We already have a canvas format design concept showing in 

The canvas format is a bit complicated to implement from development aspects.
The tabular format is an alternative solution.

## Expected behavior

1. Provide the tabular format view page mockup
2. Gathering feedback, combine with [User Steps for Data Integration
](https://docs.google.com/document/d/1PZsSjx-PCt3OC84rBJR-zM2XFIiveldL4ya4Gj89w_U/edit?ts=5c617e89#heading=h.q0k00oa7s766) document to improve the mockup
3. Confirm with uxd, dev & pm, sign off the low-fi and ready for view page high-fi mockup design. 

## Related Issue
#4261

**Comment by deernano** [comment]
Fuse DV View Page (Tabular Format) low-fi mockup:
https://redhat.invisionapp.com/share/KFQALXC8Z6E#/344386722_dv

**Comment by dongniwang** [comment]
Closing this issue now since we're tracking things in JIRA.
