### ISSUE TITLE
Support FHIR patch, search and transaction actions

### ISSUE THREAD

**Issue by rkorytkowski** [syndesisio/syndesis#4552]
## This is a...

<pre><code>
[x ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
The FHIR connector needs to expose support for patch, search and transaction actions.

**Comment by rkorytkowski** [comment]
PR at https://github.com/syndesisio/syndesis/pull/4553

I still need to resolve an issue with the inability to use a data mapper to map a number of resources in a transaction, but wanted to merge the current state as soon as possible for testing.

**Comment by mastepan** [comment]
not yet verified by the QE
