### ISSUE TITLE
[Google Sheets] squeezed icon on settings page

### ISSUE THREAD

**Issue by christophd** [syndesisio/syndesis#4557]
Google Sheets icon looks squeezed on settings page. Perhaps because PNG icon source is used instead of SVG?

![Bildschirmfoto 2019-02-13 um 21.30.56.png](https://images.zenhubusercontent.com/5be31e5e6d41381168d0a8e7/3798c128-d0da-4f70-954f-c1866293dd60)

**Comment by dongniwang** [comment]
I have a feeling that this is somewhat related to https://github.com/syndesisio/syndesis/issues/4612 and https://github.com/syndesisio/syndesis/issues/4608 (basically part of the masthead changes we introduced)

@mcoker @seanforyou23 What do you think? 

cc: @gashcrumb

**Comment by mcoker** [comment]
Doesn't look like that's related to the masthead update. This has likely always been an issue, we just didn't see it before because so far the icons have been fairly similar dimensions. The icons on the left of a list row are expected to be a square, and have a hard width of 30px x 30px from PF3:

```
.list-pf-icon-small {
    font-size: 1.4em;
    height: 30px;
    line-height: 30px;
    width: 30px;
}
```

But as a couple of examples, Salesforce is 36x27 and Google Sheets is 28x36. So making both of those 30x30 messes up the dimensions. The problem with showing the images with different widths and heights is that if the images are variable widths, the title text won't align, and if the images are variable heights, the row heights will be different.

As an example, I made the width of all of the images 28px here, then changed the width of the Salesforce icon 36px. 
<img width="158" alt="screen shot 2019-02-19 at 8 47 01 am" src="https://user-images.githubusercontent.com/35148959/53023882-a9df6380-3423-11e9-995a-73acb9753549.png">




In a perfect world, all of these images would be on a 30x30px canvas, and the icon would be sized on the canvas appropriately, using the technique mentioned in https://github.com/syndesisio/syndesis/issues/4356

**Comment by dongniwang** [comment]
@mcoker - Thanks for looking into this! 

Yeah, it makes perfect sense. Unless we can find a temporary fix for this for 7.3. I'd suggest tackling #4356 (which will fix this issue as well) once and for all in 7.4. 

cc: @amysueg @heiko-braun @paoloantinori

**Comment by mcoker** [comment]
A temporary fix would be to do the same thing we're doing for the API connection icon in the integration editor and use custom CSS to resize the images that aren't displaying properly.

**Comment by dongniwang** [comment]
OK. Thanks for clarifying. 

So the question becomes - Is Google Sheet and Salesforce the only ones we need to apply special treatment? Or for every icon on this page, we need to do this? 

And I think the Swagger Petstore one was brought in through user generation.

**Comment by christophd** [comment]
Just wanted to bring in that the Google Sheets icon has been added by me without any optimizations done. Maybe we can find a SVG icon source and optimize it for Syndesis as we did with other Google related icons. 

Also add @zregvart as he might know about icon optimizations that we have done before.

**Comment by amysueg** [comment]
Adding @lboehling - FYI, icon discussion

**Comment by mcoker** [comment]
@dongniwang 

> So the question becomes - Is Google Sheet and Salesforce the only ones we need to apply special treatment? Or for every icon on this page, we need to do this?

Currently all of the icons are different dimensions except for the SAP Concur and Swagger Petstore icons (and Google Calendar is probably close enough). So technically, they should all have custom sizing if we want them to display in their native aspect ratio. Here's the current width x height of them all, assuming a common 30px width.

* gmail - 30x25
* calendar - 30x29
* sheets - 30x38
* salesforce - 30x23
* SAP concur & swagger petstore - 30x30
* twitter - 30x26

**Comment by dongniwang** [comment]
Based on @mcoker 's last [comment](https://github.com/syndesisio/syndesis/issues/4557#issuecomment-465228098). I think it makes sense to just fix the Google Sheets icon for this release. Then we work on https://github.com/syndesisio/syndesis/issues/4356 in 7.4.

**Comment by mcoker** [comment]
@christophd can you replace the current sheets image with this one?

![sheets](https://user-images.githubusercontent.com/35148959/53192517-45173b00-35d4-11e9-9668-fbe018af556c.png)

**Comment by zregvart** [comment]
Can we get a SVG version place it in https://github.com/syndesisio/syndesis/tree/master/ux/connections_icons/svg with the name `connectionicons_googlesheets.svg` and update https://github.com/syndesisio/syndesis/blob/744ba2f806b5d8cb6c1a5609201c1592021a00a9/ux/connections_icons/svg/mapping.json to contain:

```json
  {
    "connectorId": "sheets",
    "icon": "connectionicons_googlesheets.svg"
},
```

And then run `yarn icons` from the same directory.

Perhaps we should also set the `id` of Google Sheets connector to `google-sheets`, seems that it's `sheets` at the moment and that might be a conflict in the future.

**Comment by mcoker** [comment]
@zregvart @christophd I added the SVG, updated the mappings file, ran `yarn icon`, but I'm still not seeing it updated in the UI. I put up a PR with that work if you want to update it or let me know if there are more steps involved. https://github.com/syndesisio/syndesis/pull/4667

**Comment by zregvart** [comment]
@mcoker to see the updated icon you'd need to rebuild syndesis backend and reset the database. I'll verify on my end, the PR looks good.

**Comment by christophd** [comment]
@mcoker @zregvart 

PR looks good but when I test this on master the Google Sheets icon is not displayed. The `img` `src` is having the new svg base64 encoded string but I can not see the icon:

![bildschirmfoto 2019-02-25 um 11 23 47](https://user-images.githubusercontent.com/195264/53331031-3c827580-38f0-11e9-82b1-badeedd65f39.png)

I am using Chrome browser on MacOS

**Comment by christophd** [comment]
turns out that it is related to Chrome browser

**Comment by tplevko** [comment]
No more squeezed
