### ISSUE TITLE
Low-fi design of create new DV for Data Virtualization

### ISSUE THREAD

**Issue by deernano** [syndesisio/syndesis#4559]
## This is a...

<pre><code>
[ x ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
This issue is to track the low-fi design pages of create new DV process for Data Virtualization in Syndesis

## Expected behavior

1.  According to [User Steps for Data Integration
](https://docs.google.com/document/d/1PZsSjx-PCt3OC84rBJR-zM2XFIiveldL4ya4Gj89w_U/edit?ts=5c617e89#heading=h.q0k00oa7s766) document, provide create new dv design mockups
2. Gathering feedback from uxd, dev & pm, improve the design
3. Confirm with uxd, dev & pm, sign off the low-fi and ready for view page high-fi mockup design. 

## Related Issue
#4261

**Comment by dongniwang** [comment]
Closing this issue now since we're tracking things in JIRA.
