### ISSUE TITLE
[collection support] provide a migration path for old integrations

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#4560]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Integrations made before the introduction of collection support may need to be updated and/or the user informed that some manual changes are needed

**Comment by avano** [comment]
verified
