### ISSUE TITLE
Flaky OData connector unit test on CircleCi

### ISSUE THREAD

**Issue by christophd** [syndesisio/syndesis#4562]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

ODataReadRouteSplitResultsTest seems to fail from time to time on CircleCi.

See https://circleci.com/gh/syndesisio/syndesis/56953?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

Simple build rerun has fixed the test.

**Comment by zregvart** [comment]
Looks like it still causes problems:

https://circleci.com/gh/syndesisio/syndesis/80101

**Comment by phantomjinx** [comment]
On it.

**Comment by mastepan** [comment]
@phantomjinx is there anything to verify by the QE? If no please add ignore/qe label. Thanks

**Comment by phantomjinx** [comment]
@mastepan 
Sure. Nothing for qe. Tests should just pass repeatedly.

**Comment by zregvart** [comment]
Sounds like we can close this.
