### ISSUE TITLE
Update split/aggregate step icons

### ISSUE THREAD

**Issue by christophd** [syndesisio/syndesis#4563]
Update icons to official step icons for split and aggregate

**Comment by zregvart** [comment]
The icons should be placed here:

https://github.com/syndesisio/syndesis/tree/master/ux/connections_icons/svg

Since these are step icons (not connector icons), the script to optimize/manage the SVGs probably needs to be updated also.

**Comment by christophd** [comment]
@zregvart do you have time to look at this?

**Comment by zregvart** [comment]
Can do, sometime next week I think.

**Comment by tplevko** [comment]
Verified, closing.
