### ISSUE TITLE
google-sheets connector: make Add charts step configurable from step definiton form 

### ISSUE THREAD

**Issue by mmelko** [syndesisio/syndesis#4564]
See also **https://issues.jboss.org/browse/ENTESB-11483**

## This is a...

<pre><code>
[x ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Basicaly same as #4500. When we want to add chart in spreadsheet datamapper has to be always involved, which make some scenarios more complicated as it could be (i.e periodic chart update based on timer)

**Comment by amysueg** [comment]
@dongniwang Please take a look and follow up. Thanks.

**Comment by dongniwang** [comment]
@christophd - are you working on this along with #4500 ? Let me know if you want to discuss how UX can help or if you want me to review anything. Thanks!

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11483**
