### ISSUE TITLE
Cancel button does not work when prompted to name integration

### ISSUE THREAD

**Issue by tplevko** [syndesisio/syndesis#4582]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

When creating new integration - I want to get back to editing integration from the integration naming screen. I expected this would be possible using the "cancel"button, but it doesn't seem to work.

## Expected behavior

When pressing the cancel, I expected I would get back to the integration editor.

## Screenshot

![out2](https://user-images.githubusercontent.com/4180208/52849667-dc324d80-3111-11e9-89fc-d928ae4bc378.gif)

## Tasks involved / Steps to Reproduce

1. Select create integration
2. Select start connection
3. Select end connection
4. Press "Publish" button
5. Press cancel button - nothing happens

**Comment by gashcrumb** [comment]
I took out this cancel button as an experiment in the linked PR.

You wind up on this page if you haven't named the integration, you get to it when you click save, and you can't save until you've named your integration.  So I don't know that having a cancel button on this page really is a benefit.

The other option is to make it just go back to the save/add step page, but that creates the above loop in the flow.

**Comment by tplevko** [comment]
Verified
