### ISSUE TITLE
No way to add datamapper before OpenAPI connection

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#4588]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
I am using [https://petstore.swagger.io/v2/swagger.json](https://petstore.swagger.io/v2/swagger.json) file to create an OpenAPI connection. When I want to perform GET /pet/{petId}, there is no prompt to add data mapping (even if it would be constant). 

But when I put some connection before the API connection, data mapper becomes available and the parameters show up correctly and as far as I know they also work correctly. 
I used PostgreSQL to get the data mapper to show up with SQL invocation SELECT * FROM contact, stored procedures don't let the data mapper step to show up.

**Comment by zregvart** [comment]
Relates to #4207
