### ISSUE TITLE
[Action configuration page] Checkboxes and labels are not aligned  

### ISSUE THREAD

**Issue by dongniwang** [syndesisio/syndesis#4594]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

I saw this from @phantomjinx's demo this morning. It seems like the checkboxes for "Filter Old Results" and "Split Results" are not aligned with the text. 

It seems like patternfly has a known issue with check/radio vertical alignment on linux distros, see https://github.com/patternfly/patternfly/issues/1122. 

## Expected behavior

Checkboxes and text should align. 

## Screenshot

<img width="535" alt="screen shot 2019-02-15 at 9 54 23 am" src="https://user-images.githubusercontent.com/24943812/52866733-4e546380-310d-11e9-95c4-88109ab53ae7.png">

## Tasks involved / Steps to Reproduce

1.
2.
3.
4.

cc: @seanforyou23 @mcoker @syndesisio/uxd

**Comment by dongniwang** [comment]
Linking the similar issue here https://github.com/syndesisio/syndesis/issues/4520

**Comment by tplevko** [comment]
Verified in https://github.com/syndesisio/syndesis/issues/4520
