### ISSUE TITLE
fix license headers

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#460]
We seem to be a bit fuzzy about license headers in connectors, perhaps we should revisit license headers enforcement througout the (Java) codebase and fix existing discrepancies.

**Comment by rhuss** [comment]
It's easy todo with Intellij's "Update Copyright" support for the connectors directory and the result looks ok. This has also the benefit that all license headers look the same (which the basepom license check does not enforce).

I agree, that we probably should switch off the license checks in the build, as it causes more friction than benefit IMO. As the tooling is pretty decent to update all headers in one step, I'm happy todo this from time to time (e.g. before a release) with a dedicated PR (and then switch on the licencse check for release builds only).

@syndesisio/backend wdyt ?

**Comment by zregvart** [comment]
I've modified [license pull request check](https://ci.fabric8.io/view/syndesis/job/syndesis-pullreq-license-check/) to run against syndesisio/syndesis.

**Comment by zregvart** [comment]
Done ✔️
