### ISSUE TITLE
Add a label to the Operations drop-down for API Provider

### ISSUE THREAD

**Issue by amysueg** [syndesisio/syndesis#4600]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
The drop-down on the header for API Provider needs a label to identify the dropdown. The label should be "Operations:"

**Comment by amysueg** [comment]
![image](https://user-images.githubusercontent.com/31700119/52879485-3e4c7c00-312d-11e9-8cba-ef7b90e61b7b.png)
 Screenshot for reference, the request is to add a label to the left of the "Delete user" drop-down in this example.

**Comment by tplevko** [comment]
Verified
