### ISSUE TITLE
[Deploy] Unable to deploy from master

### ISSUE THREAD

**Issue by avano** [syndesisio/syndesis#4606]
## This is a...

<pre><code>
[ ] Feature request
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
With clean minishift:

```
./tools/bin/syndesis install --setup
Installing Syndesis CRD

./tools/bin/syndesis install --project syndesis -y --test-support
Creating project syndesis
Already on project "syndesis" on server "https://192.168.99.100:8443".
ERROR: No CRD Syndesis installed or not enough permissions to read them. Please run --setup and/or --grant as cluster-admin. See 'syndesis install --help' for more information.

oc get crd
NAME                                                                     AGE
openshiftwebconsoleconfigs.webconsole.operator.openshift.io              21m
servicecertsigneroperatorconfigs.servicecertsigner.config.openshift.io   24m
syndeses.syndesis.io                                                     1m
```

**Comment by heiko-braun** [comment]
@syndesisio/all Any thoughts on this?

**Comment by heiko-braun** [comment]
@rhuss Could you take a look at this?

**Comment by heiko-braun** [comment]
@avano Seem to work fine with 79c630c9cf8b95f406a3ace31a8ea5fa303f1b41

**Comment by rhuss** [comment]
Yes, there was an issue with the scripts as the crds name has been aligned with the operator SDK update's suggestion (syndesisis -> syndeses plural form).

Everything should work fine again. @avano can you confirm this ?

**Comment by avano** [comment]
@rhuss ha, I found it. I was using oc 3.10 version and openshift 3.11 and it had some problem with the new plural form of syndesis.

**Comment by heiko-braun** [comment]
@avano So can we close this?

**Comment by avano** [comment]
@heiko-braun will we support 3.10 with 7.3? If yes, then the install from `fuse-online-install` repository will most likely fail in the same way when using 3.10 oc client.

cc @tplevko

**Comment by heiko-braun** [comment]
@rhuss What would you suggest? Can leverage the new SDK without breaking 3.10 support?

**Comment by gashcrumb** [comment]
I nuked my minishift env from last friday and I can't seem to get it running today, I can't tell if it's related to this issue or not but just to be sure -> https://gist.github.com/gashcrumb/80a13603c5d3a72243bceecce132f34c

**Comment by gashcrumb** [comment]
@seanforyou23 I think showed me a screenshot with the same error as I've linked.

**Comment by heiko-braun** [comment]
@avano Since we reverted the plural I think we can close this, right?

**Comment by rhuss** [comment]
This can be fixed I think. But there is still an issue with ther operator and updates.
