### ISSUE TITLE
consolidate font sizes in syndesis 

### ISSUE THREAD

**Issue by mmelko** [syndesisio/syndesis#4608]
Introducing new font brought some inconsistency in font sizes and visibility of connection names:
![screenshot_20190218_094516](https://user-images.githubusercontent.com/6814482/52938782-d5e6e000-3362-11e9-94d6-e3188d0e2985.png)
![screenshot_20190218_095532](https://user-images.githubusercontent.com/6814482/52939010-5dccea00-3363-11e9-8e44-38f962d3c286.png)

**Comment by gashcrumb** [comment]
So I've seen quite a lot impacted by introducing patternfly 4 with the masthead PR:

1)  font-awesome icons are broken
2)  Fonts in general are all over the place
3)  Extra padding here and there where there wasn't padding
4)  Misalignment of elements here and there where this wasn't happening

I'm starting to wonder if we shouldn't consider backing out that change, or are we going to wind up with a lot of extra custom CSS to suppress the above?

**Comment by seanforyou23** [comment]
Don't give up just yet! 😀

Had some delays getting going on these follow up issues, but I think we can get them all resolved and in a way that's properly supported on the PF side and without it taking forever. I know they went through this exact exercise recently over in OSIO so I plan to team up with the wiz that made that happen tomorrow. I'll see if we can expose some overrides or something like that as an include from the PF dist. That way the overrides are out of our hair. We may have to denote certain html containers with some extra classes, but that's a much better solution I think. 

Either way we'll shoot for as little touch points as possible. Keep you posted!

**Comment by seanforyou23** [comment]
Just an update - we're making good progress on this and looks like the general approach has the thumbs up from the PF team. I'm ironing out a final detail on that side and thinking it will be merged in the next day. Then, we'll just need to update the corresponding PR in syndesis and give it a final test run. Thanks for being patient!

**Comment by seanforyou23** [comment]
@mmelko this should be fixed now, let me know if you see any issues!

**Comment by mmelko** [comment]
It looks good now. Thanks!
