### ISSUE TITLE
No way how to cancel additional step wizard

### ISSUE THREAD

**Issue by mkralik3** [syndesisio/syndesis#4610]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When I click on add step button but I will realize that I don't want to any additional step, I don't have any option how to cancel step wizard. The page contains only Cancel button which cancels all integration wizard. The user can click on it thinking that that cancel button cancels just step wizard not whole integration wizard. After that, the complete configured integration is gone. So, in the worst case, the user can lose configuration which **models hours**. For that case, I have also already created a feature request https://github.com/syndesisio/syndesis/issues/4611

![output](https://user-images.githubusercontent.com/16251792/52940288-738fde80-3366-11e9-879d-3f086f5150f4.gif)

On the video, you can see that I have complex integration but when I click on cancel, because I mistakenly thought that the button cancel only step wizard,the whole work is gone.

On the other hand, another misunderstanding for the user can be that when they click on cancel button during edit existing integration, the cancel button only cancels the actual wizard, not whole integration wizard as in the previous example. So the same Cancel button does two different things which can be really confusing for the users.

![output](https://user-images.githubusercontent.com/16251792/52940593-35df8580-3367-11e9-97d8-a3e9a1d2abbd.gif)

**Comment by gashcrumb** [comment]
Yeah, cancel up there is a work in progress button.  Ultimately I want the button to "do the right thing" depending on context, so these issues are helpful.

That being said, the cancel button is there because we have a toolbar for buttons and they're in the design.  The other option is to selectively hide the cancel button when it isn't appropriate, basically on all the step/connection configuration pages etc.  We still have a cancel button in the form areas on pages *except* with the data mapper page, that one needs to be in the toolbar at the moment.

@dongniwang opinion?

**Comment by dongniwang** [comment]
Thanks for capturing these issues. 

@gashcrumb I agreed that we want the button to do that right thing when it comes the right time. How much effort would it involve to hide the cancel button when in step/connection configuration pages? I think I can certainly open an issue to continue the work of the[ integration state diagram](https://github.com/syndesisio/syndesis/issues/2870).

**Comment by gashcrumb** [comment]
I don't think it'd be too difficult, probably as difficult as it would be to make it do the right thing on a given page :-)  So really either way, if we prefer to minimize the available buttons on a given page it's probably better to hide the button.

**Comment by dongniwang** [comment]
I think hiding the buttons would be good for now. @gashcrumb

**Comment by gashcrumb** [comment]
So I started looking at this, and the thing is, on the "Add a step" page there's no place for a cancel button in the design.  Except in the toolbar where it is.  

I can't seem to reproduce this though on master, when I click cancel in the editor the step to add is removed and I'm back at the save or add step page as expected.  I wonder if perhaps you had some cached code running?

My thought is to implement #4611 before touching this one.

**Comment by dongniwang** [comment]
+1 to have the cancel confirmation modal. 

And for the cancel button, can users click anywhere else in the integration editor (IVP)?

It seems like the Cancel is working as expected on staging site.

**Comment by gashcrumb** [comment]
Whoops, linked the wrong issue, tracking the cancel dialog in #4475

**Comment by gashcrumb** [comment]
The cancel button at this stage should be working as designed, i.e. it contextually cancels out of a page flow when needed or out of the integration with a prompt.  If there's specific spots where this doesn't happen, let's create specific issues for those cases.
