### ISSUE TITLE
The prompt whether the user really wants to cancel integration.

### ISSUE THREAD

**Issue by mkralik3** [syndesisio/syndesis#4611]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

![output](https://user-images.githubusercontent.com/16251792/52940288-738fde80-3366-11e9-879d-3f086f5150f4.gif)

On the video, you can see that I have complex integration but when I click on the cancel button, because I mistakenly thought that the button cancels only step wizard (issue https://github.com/syndesisio/syndesis/issues/4610 ),the whole work is gone. In my point of view, there should be some prompt which asks whether the user really want to cancel the whole integration wizard.

**Comment by avano** [comment]
#4475

**Comment by gashcrumb** [comment]
Yeah, we have an issue open for this already.
