### ISSUE TITLE
Invalid character

### ISSUE THREAD

**Issue by mkralik3** [syndesisio/syndesis#4612]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Everywhere when is a button for editing is an invalid character.

E.g.

Edit name of integration (  )
![image](https://user-images.githubusercontent.com/16251792/52941860-0f6f1980-336a-11e9-8f48-30c34dcaaeb3.png)

Edit name and description of integration.
![image](https://user-images.githubusercontent.com/16251792/52941938-2e6dab80-336a-11e9-971c-cd804be7e115.png)

Edit name and description of Connection
![image](https://user-images.githubusercontent.com/16251792/52941988-49d8b680-336a-11e9-84cc-3ce77c346ed0.png)

![image](https://user-images.githubusercontent.com/16251792/52942090-93c19c80-336a-11e9-98a6-25ba4ab22463.png)

![image](https://user-images.githubusercontent.com/16251792/52942102-9ae8aa80-336a-11e9-8f63-c67b727941bb.png)

![image](https://user-images.githubusercontent.com/16251792/52942242-ea2edb00-336a-11e9-970c-3103c15388fb.png)

**Comment by heiko-braun** [comment]
@mkralik3  `p0` means blocking. Is this what you had in mind?

**Comment by mkralik3** [comment]
@heiko-braun  Sorry I didn't noticed , missclick, I meant  P1

**Comment by heiko-braun** [comment]
@mkralik3 thanks for the clarification

**Comment by dlabaj** [comment]
I'll take a look at this @seanforyou23

**Comment by seanforyou23** [comment]
@dlabaj just a heads up, the latest push to https://github.com/patternfly/patternfly-next/pull/1467 allows us to resolve this by simply not including the styles that cause this problem. It's all coming full circle right about now :) I will lump this fix in with https://github.com/syndesisio/syndesis/pull/4669
