### ISSUE TITLE
Error in logging into Java Console of Integration Pod

### ISSUE THREAD

**Issue by honghuac** [syndesisio/syndesis#4613]
## This is a...

<pre><code>
[ ] Feature request
[x ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

In earlier releases of Syndesis, it was possible to access the Java Console/Hawtio console of each Integration Pod. 

![http-log](https://user-images.githubusercontent.com/8625482/52942254-9beafd80-33a5-11e9-8a4a-ffb8175fce56.png)

With release 1.5, the Console is no longer accessible, this error is encountered.

![js](https://user-images.githubusercontent.com/8625482/52942302-b45b1800-33a5-11e9-8141-6fd5ba3a7dc0.png)

**Comment by heiko-braun** [comment]
@rhuss Any idea?

**Comment by honghuac** [comment]
There is a solution described on the Forums - https://issues.jboss.org/browse/ENTESB-8297. But that means the **Java Console** link on the AMQ pod console page has to updated to use the Bearer Token, instead of plain text userID and password.
