### ISSUE TITLE
Editing CI/CD tag without changes causes that the tag is removed

### ISSUE THREAD

**Issue by mkralik3** [syndesisio/syndesis#4617]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When I click on edit and change the name, it works properly. However, when I click on edit but I don't change the name and click on Save, the Tag is deleted.
![output](https://user-images.githubusercontent.com/16251792/52949084-9973ae00-337b-11e9-92ad-24a6ae250ce8.gif)

**Comment by gashcrumb** [comment]
@dhirajsb In this case the UI does a PUT request to the rename endpoint with the same string, the backend seems to delete the tag in this case.

I'll add some code to the UI for this though to disable the save button and maybe not make the request while the old and new names match.

**Comment by dhirajsb** [comment]
@gashcrumb I'll add a check to ignore such requests in the service
