### ISSUE TITLE
[API provider] Edit integration page is empty

### ISSUE THREAD

**Issue by christophd** [syndesisio/syndesis#4619]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

After create and publish of an integration with API provider start connection the edit page of that integration is empty.

![bildschirmfoto 2019-02-18 um 15 37 31](https://user-images.githubusercontent.com/195264/52958300-1c086780-3394-11e9-9d8e-086e29a6a4a5.png)

![bildschirmfoto 2019-02-18 um 15 37 47](https://user-images.githubusercontent.com/195264/52958310-232f7580-3394-11e9-8467-70770a462fc8.png)

Using Chrome on MacOS. No JS errors visible.

The API provider connection has been created from scratch with one single operation. Here is an export of the integration
[TodoApi-export.zip](https://github.com/syndesisio/syndesis/files/2876114/TodoApi-export.zip)

**Comment by gashcrumb** [comment]
I've seen this raised a couple times, did you try clearing your browser cache out of curiosity?

**Comment by christophd** [comment]
Yes but it did not help. It seems to be related to the API only having one single operation. When I have an API with 2 or more operations everything just works fine.

**Comment by tplevko** [comment]
Verified. It's working as expected now.
