### ISSUE TITLE
Commit ID no longer present on support page

### ISSUE THREAD

**Issue by asmigala** [syndesisio/syndesis#4628]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
The support page no longer shows the commit ID of the currently deployed syndesis. The reason for this seems to be that the manifest in runtime.jar now has `Git-Commit-Id: null`, though I was unable to find any recent change that would cause this (it was still there about a week ago).

**Comment by zregvart** [comment]
Could be the basepom upgrade done in #4586. It should be there based on https://github.com/basepom/basepom/blob/811f00a70885cd1e6b1365e4e0fb3dbd3bfb2d86/foundation/pom.xml#L426 perhaps we disabled the git-id Maven plugin.

**Comment by asmigala** [comment]
Verified with latest master
