### ISSUE TITLE
Provide the way to set env variable to deployment config of integration pod

### ISSUE THREAD

**Issue by abouchama** [syndesisio/syndesis#4634]
See also **https://issues.jboss.org/browse/ENTESB-11509**

(Placeholder for https://issues.jboss.org/browse/ENTESB-10194)

When we set a new environment variable, by default the deployment config starts new deployment,
After that, when we edit the integration flow in Syndesis Dashboard -> No Action will be performed and the Status will be reflected as "?" near the Integration name.

**Comment by heiko-braun** [comment]
@dhirajsb Can you look at this? I am not sure if it's a bug or a feature.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11509**
