### ISSUE TITLE
Initial version of Camel OData connectors

### ISSUE THREAD

**Issue by dhirajsb** [syndesisio/syndesis#464]
Create Olingo4 based OData connectors for the following actions:
- Create
- Retrieve
- Update
- Replace
- Delete

**Comment by dhirajsb** [comment]
@kcbabo need user story for this connector. Also need to sort out what provider(s) we will support initially.

**Comment by dhirajsb** [comment]
Initial implementation is done, need to create a PR for review. There are still some issues, but can be worked on in the next Sprint.

**Comment by zregvart** [comment]
This is done via #526
