### ISSUE TITLE
The Cancel Prompt shows up when creating an API Provider integration, preventing its completion

### ISSUE THREAD

**Issue by asmigala** [syndesisio/syndesis#4650]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When creating an API Provider integration, the cancel prompt (#4475) appears after clicking "Save and continue" button. Furthermore, after clicking "Cancel" in the dialog, a spinner is shown and there is no way to continue editing the integration.

![save-cancel](https://user-images.githubusercontent.com/9480152/53161117-a259bf00-35c9-11e9-9428-dbcce35482a7.gif)

**Comment by heiko-braun** [comment]
A job for @gashcrumb ?

**Comment by asmigala** [comment]
Verified with lates master
