### ISSUE TITLE
Added empty string as CI/CD tag causes StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by mkralik3** [syndesisio/syndesis#4654]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When I add empty string as a tag in the CI/CD dialog, on the server shows StringIndexOutOfBoundsException. After that, syndesis doesn't work.
Log:
[syndesis-server-1-5njvb.log](https://github.com/syndesisio/syndesis/files/2889377/syndesis-server-1-5njvb.log)

After redeploying only syndesis-server, the exception is still there.
Redeploy log:
[syndesis-server-2-f7b9n.log](https://github.com/syndesisio/syndesis/files/2889409/syndesis-server-2-f7b9n.log)

**Comment by heiko-braun** [comment]
@dhirajsb Can you take a look at this?

**Comment by dhirajsb** [comment]
@mkralik3 yeah, looks like an empty string was inserted in the DB and it's borked. I'll add a validation check for empty strings as not supported.
