### ISSUE TITLE
Help menu stays visible after selecting an item

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#4655]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Help menu stays open after selection of an item and we have to click on the icon again to close it. I have never seen such behavior for similar features - do we want it like this or should we make the menu disappear when we select an item?

## Expected behavior

When I open help menu and select an item, the menu should disappear.

## Screenshot

![out](https://user-images.githubusercontent.com/14313995/53172401-85cb8000-35e5-11e9-8785-f42c49968d64.gif)

**Comment by amysueg** [comment]
Can we close this item since #4675 has been merged? @mcada @heiko-braun @dlabaj

**Comment by heiko-braun** [comment]
Moving to `Done`

**Comment by amysueg** [comment]
Closing.

**Comment by amysueg** [comment]
Closing.
