### ISSUE TITLE
google-sheets: add chart step: unable to specify target sheet,  new is always created

### ISSUE THREAD

**Issue by mmelko** [syndesisio/syndesis#4664]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description 

"Add chart" step in google sheets connector is always creating new sheet. If sheetID is specified in datamapper then following exception is thrown:

`
org.apache.camel.RuntimeCamelException: com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request {   "code" : 400,   "errors" : [ {     "domain" : "global",     "message" : "Invalid requests[0].addChart: Cannot add chart to new sheet with ID: 545637411, a sheet with that ID already exists.",     "reason" : "badRequest"   } ],   "message" : "Invalid requests[0].addChart: Cannot add chart to new sheet with ID: 545637411, a sheet with that ID already exists.",   "status" : "INVALID_ARGUMENT" } 	at org.apache.camel.component.google.sheets.GoogleSheetsProducer.doInvokeMethod(GoogleSheetsProducer.java:49) 	at org.apache.camel.util.component.AbstractApiProducer$1.run(AbstractApiProducer.java:86) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 	at java.lang.Thread.run(Thread.java:748) Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request {   "code" : 400,   "errors" : [ {     "domain" : "global",     "message" : "Invalid requests[0].addChart: Cannot add chart to new sheet with ID: 545637411, a sheet with that ID already exists.",     "reason" : "badRequest"   } ],   "message" : "Invalid requests[0].addChart: Cannot add chart to new sheet with ID: 545637411, a sheet with that ID already exists.",   "status" : "INVALID_ARGUMENT" } 	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146) 	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113) 	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40) 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321) 	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1065) 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419) 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352) 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469) 	at org.apache.camel.component.google.sheets.GoogleSheetsProducer.doInvokeMethod(GoogleSheetsProducer.java:47) 	... 8 more
`

**Comment by christophd** [comment]
I had a look into this and it turns out that `sheetId` and `sheetIndex` are two different things in terms of identifying a target sheet. Google Sheet API requires a `sheetId` to be set. This id is a random number generated when the sheet is added to the spreadsheet.

The funny thing is that the very first sheet in a spreadsheet has `sheetId=0` and `sheetIndex=0`. All other sheets get a random 8 digit number as `sheetId`.

Users need to get and set the `sheetId` when using a different target sheet for the chart.

**Comment by christophd** [comment]
All Google Sheets reference samples and guide use `sheetId=0` which is quite misleading to get this confused with `index` of that sheet.

https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/other#GridRange

**Comment by christophd** [comment]
I had a look at how we could support the user in getting the `sheetId` value. I am afraid we can not provide a meta lookup at the moment (would be an enhancement for upcoming releases).

What we can do right now is get the spreadsheet properties. Since #4672 we will get all sheets and their properties back and can map those `sheetId` values to the chart target `sheetId`.

**Comment by christophd** [comment]
@mmelko can you please put this to a test once again and see if we can live with that for this release?

**Comment by mmelko** [comment]
@christophd Hi .. the problem is not about getting sheetId (you can get it from spreadsheet url). problem is when you will specify sheetId you get exception that sheet already exists. When you don't  chart is always created in new sheet so you can end up with 50 chart sheets as I did :)

**Comment by christophd** [comment]
@mmelko thank you, now I get it!

**Comment by christophd** [comment]
So after having another look it seems that Google Sheets API is not able to overwrite a chart sheet which is a sheet that only contains the chart itself. 

We have to use an overlay position when specifying a target sheet. With the overlay position set the chart can be placed in another sheet and the overwrite is successful as expected. 

So the default behavior is to always create a new sheet unless an overlay position is set. When an overlay position is set the chart is placed at this position within the source sheet by default. In case a target sheet is set in addition to the overlay position the chart is placed at this position in the target sheet.

@mmelko are you fine with that?

**Comment by mmelko** [comment]
Hi @christophd. So I've tested this and it looks like even if you will use overlay position, it **will** create a chart in  specified sheet, but it is still creating new one. So you will end up with many charts placed on the same place. This might not be necessary a problem, but I'd expect it will update existing chart but it's probably problem of google-api, isn't?

**Comment by mmelko** [comment]
Closing after discussion with @christophd
