### ISSUE TITLE
Support OpenAPI 3.0

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#467]
See also **https://issues.jboss.org/browse/ENTESB-11541**

We currently have support for Swagger 2.0 in the API connector, we should also support OpenAPI 3.0

**Comment by zregvart** [comment]
@kcbabo I seem to recall that we needed OpenAPI 3.0 support as P1, and I think this issue came about in order to support OAuth1 which is not supported in Swagger 2.0.
Is this still required (supporting OAuth1 and OpenAPI 3.0)? I feel it might be better to wait for feedback and see if there is a need for it, I haven't seen any OpenAPI 3.0 or OAuth1 APIs while searching for demo APIs to use.

**Comment by zregvart** [comment]
We'll add support for OpenAPI 3.0 and OAuth1 outside of API Client connector epic

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11541**
