### ISSUE TITLE
google-sheets: spreadsheet properties data shape should contain collection of sheets instead of single sheet object

### ISSUE THREAD

**Issue by mmelko** [syndesisio/syndesis#4672]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Currently I can't get properties of all sheets of spreadsheet, only the first one. I believe Spreadsheet properties data shape should contain collection of sheets instead of single sheet: 
![screenshot_20190225_124751](https://user-images.githubusercontent.com/6814482/53335464-d7348180-38fb-11e9-8daa-677511bd3c92.png)

This spreadsheet has 5 sheets but in messasge body is only one: 
```
Body: [[GoogleSpreadsheet [spreadsheetId=1_OLTcj_y8NwST9KHhg8etB10xr6t3TrzaFXwW2dhpXw, title=Test-Data, url=https://docs.google.com/spreadsheets/d/1_OLTcj_y8NwST9KHhg8etB10xr6t3TrzaFXwW2dhpXw/edit, sheet=GoogleSheet [sheet=0, index=0, title=Sheet1]]]]
```

**Comment by christophd** [comment]
I see this more as an enhancement for upcoming releases. At the moment the update spreadsheet properties action is designed to update a single sheet at a time. You have to specify the target sheet to update using the index property.

In case we want to display all available sheets in a spreadsheet we have to do a meta data lookup on the Google API first so we get all available sheets info for the mapper.

@gaughan what do you think?

**Comment by gaughan** [comment]
agreed, we can consider it an enhancement

**Comment by christophd** [comment]
I had another look and I realized that for some reason I had the update spreadsheet properties use case in mind. But this issue here refers to get spreadsheet properties use case. Is that right @mmelko? 

In that case we do not need a meta data lookup and the fetched results should reflect the collection of sheets rather than just the first sheet. So I will fix that as suggested

**Comment by christophd** [comment]
@gaughan sorry for the confusion I may have caused

**Comment by mmelko** [comment]
@christophd sorry for late response. Yes that's right, I was referring to get properties. Thanks for fixing that:)

**Comment by gaughan** [comment]
great thanks!
