### ISSUE TITLE
Move postgres exporter to syndesis-db pod

### ISSUE THREAD

**Issue by lgarciaaco** [syndesisio/syndesis#4674]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Having the postgres prometheus exporter as a sidecar is a good practice. As part of the move, change the `readinessProve` and `livenessProbe` to tcp. This will solve https://github.com/syndesisio/syndesis/issues/4652 and https://github.com/syndesisio/syndesis/issues/4410.

**Comment by heiko-braun** [comment]
@lgarciaaco  I assume you plan to tackle it this sprint?

**Comment by lgarciaaco** [comment]
I am working on it ...
