### ISSUE TITLE
ActiveMQ Connector - UX Design

### ISSUE THREAD

**Issue by dhirajsb** [syndesisio/syndesis#468]
Need collateral for ActiveMQ connection images, etc. 
Also need to sort UI ordering of connection properties, filter out 'to' actions for first step.

**Comment by amysueg** [comment]
@dhirajsb - need a bit more information on this one to determine what you need. thanks. 
@sjcox-rh @dongniwang fyi

**Comment by amysueg** [comment]
UX PR issue #638 is merged.
Closing this issue.
