### ISSUE TITLE
bad text positioning in customizations main screen

### ISSUE THREAD

**Issue by lhein** [syndesisio/syndesis#4680]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
When opening the "Customizations" screen of Syndesis I experience a bad text positioning. (see attached screenshot)

## Expected behavior
The text is positioned without any spacing atm. There should be some spacing between the text and the upper and left.

## Screenshot
![bildschirmfoto von 2019-02-26 12-42-06](https://user-images.githubusercontent.com/435853/53410501-4aa1c600-39c4-11e9-86ce-ff7526edd79a.png)

**Comment by dongniwang** [comment]
I think the PR https://github.com/syndesisio/syndesis/pull/4669 that @seanforyou23 is working on will fix this. 

cc: @dlabaj @mcoker
