### ISSUE TITLE
Upgrade CRD version for 7.4

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#4686]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

The CRD itself needs to be upgraded for 7.4 with the following changes:

* The plural form should be "syndeses"
* A 'status' subresource needs to be added
* The `resource:` properties' structure should be adapted to a format that is used in the OLM's UI descriptors (don't know that by heart, just that we use it differently wrt to nesting).

I suggest moving from the current `syndesis.io/v1alpha1` version to `syndesis.io/v1alpha2` (or even `syndesis.io/v1beta1`).

The interesting part will be how to perform this update since our current update mechanism doesn't really take this use case in consideration.

I suggest:

* When updating the operator for 7.4, add the new CRD *in addition* to the old CRD.
* The operator itself needs to be able to deal with both version. So both version's CRD needs to be scaffolded in `pkgs/apis/v1alpha1` and `pkgs/apis/v1alpha2` (in the respective go packages).
* Then the operator needs a new phase for upgrading CRDs. This can come right after the phase when we check for a legacy application (that without any CRD). In this phase/action, the Operator should convert the v1alpha1 CR to a v1alpha2 version.
* After this, the regular update mechanism can continue.

So adding this feature requires changes in the update shell script which updates the operator and within the operator itself for doing the migration of the CR from one CRD version to the next one.

// @heiko-braun please consider this to schedule this for 7.4

**Comment by rhuss** [comment]
Created based on the findings of #4659

**Comment by zregvart** [comment]
No longer relevant.
