### ISSUE TITLE
Remove auto-splitting from connectors

### ISSUE THREAD

**Issue by avano** [syndesisio/syndesis#4687]
See also **https://issues.jboss.org/browse/ENTESB-11482**

## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Since we have the explicit split step, it would be nice not to do it automatically in the connector.

For example in the SQL->AMQ integration, when there are more elements in the array from SQL connector, I receive it as separate messages in the AMQ even when I didn't use the split

**Comment by heiko-braun** [comment]
@christophd What do you think about this?

**Comment by christophd** [comment]
I need to have a closer look to find out if this split is happening in the connector or in the AMQ Camel component. I agree that the connector should not do the split but use the complete collection as single message payload.

**Comment by avano** [comment]
@christophd it would be good to check other connectors as well, as I'm not sure if the amq is the only one that does the splitting by itself

**Comment by phantomjinx** [comment]
Hey @christophd,

If you'll recall, I configured the odata connector (consumer part) with an option to split. It does now feel a little weird to set this but then add a split step after connector-sql. If you now want me to remove the odata-split-option then let me know.

**Comment by christophd** [comment]
Hey @phantomjinx,

the split functionality in odata connector that you have mentioned is fine to me. This is a split when having the connector as start connection in an integration. The auto split in this issue here refers to the AMQ connector having auto split on the finish connection of an integration. Finish connections should not split but handle the whole collection as payload then.

So the split in AMQ connector is a little bit different to that in the odata connector.

**Comment by christophd** [comment]
I had a closer look and the split is done in the AMQ Camel component itself. While looking at that I realized that JMS standard does not define a message type for a collection (JMS message types: text, binary, object, map)

I do not see how to map the list payload to a proper JMS message type. I guess this is why the Camel component just sends each element of that list as a separate message by default.

I come to the conclusion that this split in AMQ component is a well designed feature that Syndesis is not able to influence. So when providing a list to the AMQ component these will always get sent out element by element resulting in multiple messages on the JMS destination.

**Comment by avano** [comment]
@christophd 

> the split functionality in odata connector that you have mentioned is fine to me

Can you please elaborate on this? Why it makes sense to have a split option on the starting connector when we have the split step?

**Comment by christophd** [comment]
@avano to my understanding this is not on the start connection but on the finish or intermediate connection in an integration

**Comment by tplevko** [comment]
@christophd the OData connector seems to provide this functionality for the start connection
![odata_split_results](https://user-images.githubusercontent.com/4180208/53796781-1cc50000-3f35-11e9-942c-1c7a46a571a3.png)

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11482**
