### ISSUE TITLE
OData Connector OAuth Connections

### ISSUE THREAD

**Issue by dhirajsb** [syndesisio/syndesis#469]
See also **https://issues.jboss.org/browse/ENTESB-11540**

OData services like [Microsoft Dynamics](https://msdn.microsoft.com/en-us/library/mt634540(v=nav.90).aspx) require OAuth tokens to connect. 
iPaaS Oauth feature will need to add support for OData Service Connections.

**Comment by dhirajsb** [comment]
@kcbabo just creating for now. Need PM guidance on supported OData providers, after TP3.

**Comment by amysueg** [comment]
Created UX issue #726 for this and removed the notif/uxd label.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11540**
