### ISSUE TITLE
Tidy up and remove old-odata modules

### ISSUE THREAD

**Issue by phantomjinx** [syndesisio/syndesis#4692]

**Comment by phantomjinx** [comment]
@dhirajsb
Having implemented the new olingo4 odata connector, what's your opinion on retaining the original olingo2 odata connector (currently renamed to old-odata and not being included in builds)?

cc @zregvart @heiko-braun

**Comment by dhirajsb** [comment]
@phantomjinx we should remove it, there is no need to keep the old connector around.
