### ISSUE TITLE
Adding multiple aggregate steps after split

### ISSUE THREAD

**Issue by christophd** [syndesisio/syndesis#4710]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Users can add multiple aggregate steps after a single split step which should not be allowed. But we can have multiple split steps in an integration each of them should be allowed to have a corresponding aggregate.

The rule should be that each split is just having a single aggregate.

**Comment by heiko-braun** [comment]
Does ia have side effects? What happrns in such a case?

**Comment by christophd** [comment]
It could have negative side effects on the integration runtime

**Comment by heiko-braun** [comment]
@gashcrumb Can you take a look at this?

**Comment by lburgazzoli** [comment]
I guess this is for the current implementation only right ? in the future you can potentially aggregate some aggregations :)

**Comment by christophd** [comment]
@lburgazzoli you are right. at the moment aggregate does not have any options for the user to set so multiple aggregate steps will not bring any functionality.

With the current implementation we are limited to that. Also I think nested split of split should be tested and may not work with current implementation.

**Comment by christophd** [comment]
I put this to a test and multiple aggregate steps seem to not break the integration runtime.
![bildschirmfoto 2019-03-01 um 11 18 16](https://user-images.githubusercontent.com/195264/53631949-0278e280-3c14-11e9-8439-792c57cea2f3.png)
![bildschirmfoto 2019-03-01 um 11 19 03](https://user-images.githubusercontent.com/195264/53631968-0dcc0e00-3c14-11e9-93c4-5afb3c993c64.png)

**Comment by tplevko** [comment]
It's not possible anymore to add multiple aggregation steps after single split. Verified.
