### ISSUE TITLE
FHIR connector fixes for field ordering, collections and transaction output

### ISSUE THREAD

**Issue by rkorytkowski** [syndesisio/syndesis#4711]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Address 3 issues:
1. Upstream changes introduced different ordering of fields for action forms, which need to be reordered in json.
2. Atlasmap does not support collections within collections so schemas need to be adjusted to use maxOccurs="1" for fields in collections.
3. Transaction action output was set to NONE, whereas it is helpful to be able to access e.g. ids of newly created objects.

**Comment by mastepan** [comment]
@rkorytkowski how can I verify the fixes please?

**Comment by rkorytkowski** [comment]
1. Verify that required fields for actions are at the top.
2. Verify that in data mapping step for FHIR actions that Patient - name[] - given instead of Patient - name[] - given[] and Patient - address[] - line instead of line[] i.e. there's no collection within a collection.
3. A data mapper step after Transaction should let you access ids of newly created resources

**Comment by mastepan** [comment]
> Verify that required fields for actions are at the top.
Do you mean fields for actions are: 
There are Create, Delete, Patch, Read, Search, Transaction, Update?
Which fields are required to be on top (on top of the list on fhir - Choose an Action page?)? 

Or do you mean something else?

**Comment by mastepan** [comment]
2. - verified
3. there is tns:id - I suppose that's what we want @rkorytkowski

**Comment by rkorytkowski** [comment]
After you select an action e.g. "Create" you are presented with a list of fields. Required fields are marked with '*' and for most cases should be at the top before none required fields.

Correct, it's tns:id.

**Comment by mastepan** [comment]
Verified. Thanks @rkorytkowski
