### ISSUE TITLE
Cannot edit mappings if source and target are xml-schema type

### ISSUE THREAD

**Issue by rkorytkowski** [syndesisio/syndesis#4713]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Whenever I try to return to a data mapper step (newly added or previously saved) in order to edit it I get "Could not find document for mapped field 'value' at URI atlas:xml:undefined". Any previously created mappings are also gone at that point and I need to do them again. It happens for me only if both target and source are xml-schema data shapes. I don't see any server side errors, just the UI error.

It used to work a week or so ago. I cannot say when precisely, because I did not use that feature for a while.

Please see the browser logs and the screenshot.

[syndesis.192.168.42.229.nip.io-1551438966195.log](https://github.com/syndesisio/syndesis/files/2919194/syndesis.192.168.42.229.nip.io-1551438966195.log)

![screenshot from 2019-03-01 12-09-22](https://user-images.githubusercontent.com/1163157/53635084-51c31100-3c1c-11e9-883d-62170d826fea.png)

@igarashitm, @pleacu, any clues?

**Comment by igarashitm** [comment]
The URI `atlas:xml:undefined` means that it's looking for a Step ID `undefined` which is obviously wrong. It sounds like there's something wrong in Step ID <=> DataShape mapping in Syndesis.

**Comment by rkorytkowski** [comment]
Thanks @igarashitm. I don't think I have enough knowledge of how things are wired together to continue digging based on your comment. Do you know who might help finding the issue? I'm looking for some pointers what/where to check.

**Comment by igarashitm** [comment]
@heiko-braun ? would need a first diagnose and see if it's UI or backend.

**Comment by heiko-braun** [comment]
@rkorytkowski Can you add a reproducer?

**Comment by heiko-braun** [comment]
@rkorytkowski nm, i should have read your description more carefully.

**Comment by rkorytkowski** [comment]
FWIW I've just updated to the latest master do no longer observe the issue. Closing.
