### ISSUE TITLE
Integration pod still being deployed after deleting it in UI

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#4736]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
This has happened to me a few times before, but usually it sorted itself out after a while or after deleting other integrations. But now I am not able to make it work (apart from redeploying syndesis again)

From the server logs I discovered there's integration called i-simple-test still trying to be deployed although I have deleted it in the UI.

I am attaching server log (it's going to be quite a lot to go through but I am not sure, what caused it really just can tell you that i-simple-test is misbehaving):
[syndesis-server-1-5qvhk(1).log](https://github.com/syndesisio/syndesis/files/2926975/syndesis-server-1-5qvhk.1.log)

**Comment by dhirajsb** [comment]
@mmuzikar I haven't been able to recreate this condition on my end. I've been able to delete integration in s2i build stage, deployment stage and running stage. 
I did notice that it takes a very long time to delete sometimes, but it eventually always deleted OpenShift resources and the integration. 
Is it possible, that there's a race condition on your machine somehow, where the OpenShift delete calls are really slow, and the publish thread doesn't see an exception, which causes it to stop. That's the behavior I see on my machine, where the publish thread quits with an exception on delete.

**Comment by mmuzikar** [comment]
@dhirajsb This hasn't happened to me quite for quite a long time, and I wasn't able to recreate it in any way as well. Maybe it got fixed or never was an issue and was maybe my minishift not having enough resources at that time?

If you agree I think we can close this and if I ever encounter it again I will let you know :)

**Comment by dhirajsb** [comment]
@mmuzikar cool, closing it for now. Reopen if it surfaces again.
