### ISSUE TITLE
Add 'uses' column to tech extension list

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#474]
Currently this column can't be shown as it requires fetching the usage count for each extension as a separate call, ideally we'd inline this attribute in the extension object.

**Comment by lburgazzoli** [comment]
@gashcrumb the endpoints to get details are:

https://github.com/syndesisio/syndesis/blob/master/rest/rest/src/main/java/io/syndesis/rest/v1beta1/handler/extension/ExtensionHandler.java#L216-L251
https://github.com/syndesisio/syndesis/blob/master/rest/rest/src/main/java/io/syndesis/rest/v1beta1/handler/extension/ExtensionHandler.java#L216-L251

**Comment by gashcrumb** [comment]
@lburgazzoli the problem with this messes up the URL structure for the UI and the returned array of objects is more information than the UI needs for the list view.  We can't just add an integration count attribute to the extension object?  That's all I'm asking for :-)

**Comment by lburgazzoli** [comment]
Not at the extension object level as the extension is "immutable" whereas the number of integration is dynamic. 

@nicolaferraro can you have a look ?

**Comment by gashcrumb** [comment]
Right, that may be the case in the backend object model, but we should
avoid that constraint in the API the frontend is using so we can avoid
having to make more than one call ideally.
