### ISSUE TITLE
Documentation of Public API

### ISSUE THREAD

**Issue by mkralik3** [syndesisio/syndesis#4740]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
A user can use Public API for exporting and importing an integration across more Syndesis instances https://github.com/syndesisio/syndesis/issues/3701. This API should be documented in case the users want to use it, they have to know which endpoints call with which parameters etc.

- How to expose public API https://github.com/syndesisio/syndesis/tree/master/install#create-template-for-public-api-endpoint
- What needs for communication (Token from Service Account)
- Description of the Public API endpoints (possible parameters, how looks data for POST/PUT etc.)
POST ​/public​/connections​/{id}​/properties
GET ​/public​/environments
PUT /public​/environments​/{env}
DELETE /public​/environments​/{env}
POST ​/public​/integrations
GET ​/public​/integrations​/{env}​/export.zip
POST /public​/integrations​/{id}​/deployments
PUT​ /public​/integrations​/{id}​/deployments​/stop
GET /public​/integrations​/{id}​/state
GET /public​/integrations​/{id}​/tags
PATCH ​/public​/integrations​/{id}​/tags
POST ​/public​/integrations​/{id}​/tags
DELETE ​/public​/integrations​/{id}​/tags​/{env}

**Comment by mkralik3** [comment]
QE notes (doc) from testing Public API: https://docs.google.com/document/d/1nPfOc0baL4aP-QNbwGeRqXFiJhE64SVOWtfJAJuHaXU/edit?usp=sharing

**Comment by heiko-braun** [comment]
Thanks for sharing @mkralik3, that's really useful

**Comment by dhirajsb** [comment]
Closing this issue as API has been documented in product along with a quickstart showing usage in Jenkins.
