### ISSUE TITLE
[collection-support] Fix data type mismatch overlay icon

### ISSUE THREAD

**Issue by christophd** [syndesisio/syndesis#4741]
Steps that require some data mapping are provided with a warning sign as overlay icon. When using split/aggregate steps the data type mismatch icon is displayed multiple times on aggregate and subsequent step. It should only appear on aggregate step.

![bildschirmfoto 2019-03-04 um 20 21 28](https://user-images.githubusercontent.com/195264/53757263-886a8700-3ebb-11e9-9aef-063e44d56c5a.png)

Also when mapper has beed added the overlay icon on the aggregate step disappears but the one on the subsequent step is still displayed and never goes away.

![bildschirmfoto 2019-03-04 um 20 21 52](https://user-images.githubusercontent.com/195264/53757304-a1733800-3ebb-11e9-9529-81f43a568599.png)
 
[TodoApiProvider-export.zip](https://github.com/syndesisio/syndesis/files/2931311/TodoApiProvider-export.zip)

**Comment by christophd** [comment]
@dongniwang @gashcrumb FYI

**Comment by gashcrumb** [comment]
Doesn't invoke SQL here only want 1 thing vs an array?

**Comment by christophd** [comment]
@gashcrumb that's right the sample should use a Google Sheets connector or an API provider where the finish connection is able to use some collection shape

**Comment by gashcrumb** [comment]
So in that case when using the sheets connector does the warning icon still show up?  

As with the given example, the warning icon makes sense as aggregate would have an array output data shape.

**Comment by christophd** [comment]
Yes, also tested this with Google Sheets connection - same result

**Comment by gashcrumb** [comment]
This is worth a retest with the code for #4742 merged.

**Comment by christophd** [comment]
@gashcrumb I put this to another test and with changes in #4742 the issue is solved from my point of view

**Comment by gashcrumb** [comment]
Cool, if it pops up again we can always reopen or create a new issue.
