### ISSUE TITLE
Keep split/aggregate consistent when removing steps

### ISSUE THREAD

**Issue by christophd** [syndesisio/syndesis#4742]
When removing a split step from an integration we might force/guide the user to also remove the corresponding aggregate step. Otherwise the integration might have an inconsistent state on aggregate without a split.

**Comment by christophd** [comment]
@dongniwang FYI

**Comment by gashcrumb** [comment]
Would make sense to just remove the subsequent aggregate step if it's there.  I vote for just doing it vs. asking the user to do it, saves explaining why.

**Comment by gashcrumb** [comment]
Eventually the aggregate step could be it's own standalone thing that doesn't require a split, correct?

While investigating the feasibility of this I wonder if we should punt on this one.  The simple use-cases are pretty easy, i.e. one split/aggregate, or more than one in a flow etc.  Nested split/aggregate though is more difficult and what I have right now will still leave orphaned aggregate steps.

**Comment by gashcrumb** [comment]
Opted to go with it, if we don't like this behavior it's easy enough to roll back.

**Comment by christophd** [comment]
PR https://github.com/syndesisio/syndesis/pull/4759 also makes sure that orphaned aggregate steps (if any should survive the UI checks) are ignored when the integration runtime is built

**Comment by avano** [comment]
verified
