### ISSUE TITLE
Auto update data shapes on split/aggregate

### ISSUE THREAD

**Issue by christophd** [syndesisio/syndesis#4743]
Split and aggregate steps lookup their shapes according to previous and subsequent steps. That lookup is a once in a lifetime shot at the moment. We might need to update those shapes when integration has changed (e.g. the step before the split has changed, the step after the aggregate has changed).

At the moment the changes are not reflected to split/aggregate and user has to remove and add those steps in order to get new lookup fo the shapes.

**Comment by christophd** [comment]
@gashcrumb something we can tackle?

**Comment by gashcrumb** [comment]
We can certainly try :-)

**Comment by gashcrumb** [comment]
This is being done.

**Comment by mastepan** [comment]
not yet verified by the QE

**Comment by mmelko** [comment]
verified by QE.
