### ISSUE TITLE
bug: Public API does not return any state details for un-deployed integrations

### ISSUE THREAD

**Issue by dhirajsb** [syndesisio/syndesis#4747]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

The public API for integration state MUST return the current integration state in addition to any available state details.

**Comment by dhirajsb** [comment]
@mkralik3 I added this issue to provide state details for unpublished integrations.

**Comment by mkralik3** [comment]
Is it already done? On the master the Public API still returns only Assembling, Building, Deploying state.

**Comment by mkralik3** [comment]
When integration is in the state: Assembling, Building, Deploying, the rest point returns state info:
e.g.:
```
{"id":"i-L_DMKBDkyDxWGNIj2dLz:1","integrationId":"i-L_DMKBDkyDxWGNIj2dLz","deploymentVersion":1,"detailedState":{"value":"BUILDING","currentStep":2,"totalSteps":4},"namespace":"syndesis","podName":"i-timer-to-log-1-build","linkType":"LOGS"}
```
However, for Running, Stopping, Stopped states it returns still `204 No Content`

**Comment by dhirajsb** [comment]
I just tested it locally again and for unpublished integration I get this:
```
rh-wfh-dbokde:app dbokde$ curl -k -L -H "Content-Type: application/json" -H "SYNDESIS-XSRF-TOKEN: awesome" -H 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJzeW5kZXNpcyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJzeW5kZXNpcy1jZC1jbGllbnQtdG9rZW4tMnZjNmwiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoic3luZGVzaXMtY2QtY2xpZW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiNjUxMjYxNGMtMmYwMS0xMWU5LTk3OWEtNDI1YWNlMzY3MTcyIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OnN5bmRlc2lzOnN5bmRlc2lzLWNkLWNsaWVudCJ9.uKsri0JSKJDbgHoQwAhBJSNuWKwJgjegf2QlrCkhxVssSK1zIMZQaF9P5a4R7ZcWRnrZ_345UTqxYVeRlfHWVH0PqBkD-n7PAS9dcKJIFdS1jUHOmL1FTGgc3YW-bz1SlWT93tvK1EhorZ4_-EBfXhSAP4Uumi5qAg3_QUTMDstq233NSwBKYtFOw3Pp1ys3p3y0hcaiLMimeCH60vR4iWvptqqzc5QDigHiPySZNWxs_5awZlwdoIDvR-nSj690aC-49UKFgyEEdzdFU4bI2W4hOyDyhN9fVaIAZQKeJUrJBU-lnFTHI_NAd2OwzOEBpWZuj31Za5w9fU4kf4UDGA' https://public-syndesis.192.168.64.42.nip.io/api/v1/public/integrations/timer-to-log/state
{"currentState":"Unpublished"}
```

**Comment by mkralik3** [comment]
My Syndesis has Commit ID: `29bcd8560d1cd0064b22999a1eb882f2245dc5be` so I don't know why it is not working on my machine. I will try to install it again.

**Comment by mkralik3** [comment]
Ah, my bad, it works, I have closed the issue.
