### ISSUE TITLE
Filter in split/aggregate not working

### ISSUE THREAD

**Issue by christophd** [syndesisio/syndesis#4752]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Adding a basic filter step in a split/aggregate leads to weird behavior where the aggregate is not working as expected.

Expected behavior is to only aggregate those elements that matched the filter.

Example Integration:
[FilterInSplit-export.zip](https://github.com/syndesisio/syndesis/files/2930406/FilterInSplit-export.zip)

![filter-in-split](https://user-images.githubusercontent.com/195264/53798570-cb1e7480-3f38-11e9-8186-469cdd2ed03d.png)

Activity Log:

![filter-in-split-activity](https://user-images.githubusercontent.com/195264/53798580-d376af80-3f38-11e9-9728-042c115ac420.png)

**Comment by mastepan** [comment]
Verified by QE
