### ISSUE TITLE
Monitoring - Syndesis DB Grafana dashboard should be resilient to pod restarts

### ISSUE THREAD

**Issue by jamesnetherton** [syndesisio/syndesis#4753]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

The syndesis-db Grafana dashboard is not very resilient to restarts of the syndesis-db pod. Some of the 'singlestat' metrics at the top of the dashboard fail because it cannot handle multiple time series being returned. Hence they appear like:

![dashboard-error](https://user-images.githubusercontent.com/4721408/53805623-99aaa680-3f42-11e9-85fa-7b6e7c6d4ed0.png)

Other rows such as 'Active Connections' start to report on multiple time series, thus it's not obvious to the user what's being graphed. See below example, there are multiple series for the syndesis database. One for the old dead pod and another for the new one. Which is confusing.

![dashboard-error-1](https://user-images.githubusercontent.com/4721408/53805717-d9718e00-3f42-11e9-9cdb-ef49c3a9dfb7.png)

**Comment by mkralik3** [comment]
Verified. 
When the syndesis-db pod was scaled down to 0, the dashboard shows correct data in graphs.

![image](https://user-images.githubusercontent.com/16251792/54134923-1e9d3080-4419-11e9-994b-c5c16e8d6ad0.png)

During the interval where the pod was scaled down to 0,
![image](https://user-images.githubusercontent.com/16251792/54134999-468c9400-4419-11e9-8351-f554acc44216.png)
