### ISSUE TITLE
Connection checkbox default values not being honoured

### ISSUE THREAD

**Issue by phantomjinx** [syndesisio/syndesis#4756]
When configuring an integration's connection, default values for checkboxes are being passed to the UI's form model but the latter is ignoring them, eg.

![odata-connector-default-values](https://user-images.githubusercontent.com/1634180/53811543-8fdc6f80-3f51-11e9-9774-b8da83fcb32e.png)
_Checkboxes have default values of 'true'_

The reason this occurs is located in [form-factory-provider.service.ts](https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/core/providers/form-factory-provider.service.ts).
- [createFormModel()](https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/core/providers/form-factory-provider.service.ts#L26) is called;
- For each [key](https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/core/providers/form-factory-provider.service.ts#L37) in the properties received from the server, a create..() method is determined - for boolean/checkboxes -> createCheckbox();
- In most cases, _value_ is passed to create methods as _undefined_. However, for checkboxes, this is converted into a [boolean](https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/core/providers/form-factory-provider.service.ts#L69) <- **_(problem!)_**;
- In [createCheckbox()](https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/core/providers/form-factory-provider.service.ts#L313), _value_ is evaluated and either _it_, _field.value_ or _field.defaultValue_ should be used. However, _value_ is always chosen due to it having already been [assigned](https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/core/providers/form-factory-provider.service.ts#L69).

**Comment by heiko-braun** [comment]
@phantomjinx Is this still in progress?

**Comment by phantomjinx** [comment]
Done.
