### ISSUE TITLE
OData connector with https url needs client certificate 

### ISSUE THREAD

**Issue by jsafarik** [syndesisio/syndesis#4758]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

When setting up OData connector with TripPin sample service (https://services.odata.org/TripPinRESTierService/) and trying to validate it, there's message saying "An https / ssl OData connection requires an ssl client certificate.". Why does it need that? Simple HTTPS connector is able to validate this url and use it properly.

## Tasks involved / Steps to Reproduce

1. Create OData connector
2. As Service Root URL add https://services.odata.org/TripPinRESTierService/
3. Try to Validate

**Comment by phantomjinx** [comment]
Hi @jsafarik,
You're right that the reference odata service doesn't require a certificate, even though its SSL. However, some odata services behind SSL can be configured to deny access unless a certificate is provided. Consequently, the 'Check Certificate' option -> Enable/Disable has been added to reflect this possibility.

While testing this I have found that the certificate textbox cannot be empty (still get the ssl message you mentioned) so I'll look at rectifying that. In the meantime, you can workaround it by:
- Select 'Check Certificate' -> disable;
- Enter '.' in 'Client Certificate'.
This will allow the reference odata service to become a connection and should allow an integration to be created.

**Comment by jsafarik** [comment]
@phantomjinx the verification with the firstly mentioned workaround works (so I'm able to create the connector), but then using the connector fails because of (as you wrote) the disabled Check Certificate not being used in the ODataComponent.

**Comment by jsafarik** [comment]
@phantomjinx even with the last commit I still can't create OData connector with disabled "Check certificate", having it both on disabled or enabled still results in error saying the connector needs ssl client certificate. Am I using it the wrong way?

**Comment by phantomjinx** [comment]
@jsafarik
Hmm ... the last commit took away the "Check certificate" option and the "needs ssl client ..." message so maybe your UI needs refreshing?

**Comment by jsafarik** [comment]
@phantomjinx yes, that was exactly what it needed, thank you
