### ISSUE TITLE
rest module fails when try to build it against the 1.2-SNAPSHOT connectors

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis#476]
```
Adding component: sql-stored-connector
Adding connector: SqlStoredConnector with scheme: sql-stored-connector
[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.194 s <<< FAILURE! - in io.syndesis.dao.DeploymentDescriptorIT
[ERROR] deploymentDescriptorTakeCueFromConnectorDescriptor(io.syndesis.dao.DeploymentDescriptorIT)  Time elapsed: 1.399 s  <<< FAILURE!
java.lang.AssertionError: 
[Definition of `sql-stored-connector` connector has a property `url` that is not defined in the Camel connector] 
Expecting actual not to be null
	at io.syndesis.dao.DeploymentDescriptorIT.lambda$assertConnectorProperties$11(DeploymentDescriptorIT.java:292)
	at io.syndesis.dao.DeploymentDescriptorIT.assertConnectorProperties(DeploymentDescriptorIT.java:283)
	at io.syndesis.dao.DeploymentDescriptorIT.lambda$deploymentDescriptorTakeCueFromConnectorDescriptor$0(DeploymentDescriptorIT.java:121)
	at io.syndesis.dao.DeploymentDescriptorIT.deploymentDescriptorTakeCueFromConnectorDescriptor(DeploymentDescriptorIT.java:79)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   DeploymentDescriptorIT.deploymentDescriptorTakeCueFromConnectorDescriptor:79->lambda$deploymentDescriptorTakeCueFromConnectorDescriptor$0:121->assertConnectorProperties:283->lambda$assertConnectorProperties$11:292 [Definition of `sql-stored-connector` connector has a property `url` that is not defined in the Camel connector] 
Expecting actual not to be null
[INFO] 
[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by zregvart** [comment]
The `DeploymentDescriptorIT` integration test checks to see if `deployment.json` is in line with the JSON descriptors in the connector JAR.

I can see that both `deployment.json`:

https://github.com/syndesisio/syndesis/blob/b73366edd3431a9a091cc86c3f217455f236e8f9/rest/dao/src/main/resources/io/syndesis/dao/deployment.json#L701-L715

and `camel-connector-schema.json` should be compatible:

https://github.com/syndesisio/syndesis/blob/b73366edd3431a9a091cc86c3f217455f236e8f9/connectors/connectors/sql/sql-stored-connector/src/main/resources/camel-connector-schema.json#L70-L81

**Comment by rhuss** [comment]
> "componentProperty": true,

is in deployment.json which is missing in camel-connector-schema.json. Does this harm ?

**Comment by zregvart** [comment]
>> "componentProperty": true,
> 
> is in deployment.json which is missing in camel-connector-schema.json. Does this harm ?

I think you're on the right track, I think the test fails to notice that the `url` property is defined within `connectorProperties` (looks within `componentProperties`), could be a change in 2.20.1 of Camel.
