### ISSUE TITLE
Integration details page with two shades of grey 

### ISSUE THREAD

**Issue by dongniwang** [syndesisio/syndesis#4765]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

With the latest masthead changes, the integration details page now has two sets of grey in the background areas. 

## Expected behavior

We should use only one type of grey for integration details page. 

## Screenshot

<img width="1438" alt="screen shot 2019-03-05 at 1 52 42 pm" src="https://user-images.githubusercontent.com/24943812/53829762-dd0b1200-3f4e-11e9-92d7-900c6648d15f.png">

## Tasks involved / Steps to Reproduce

1.
2.
3.
4.

cc: @seanforyou23 @mcoker

**Comment by mcoker** [comment]
I think you can just change this line to the value below https://github.com/syndesisio/syndesis/blob/master/app/ui/src/scss/utils/_overrides.scss#L39

`--pf-c-page__main-section--BackgroundColor: #e1e1e1;`

**Comment by tplevko** [comment]
Verified by QE
