### ISSUE TITLE
Tooltip for filter toolbar is partially hidden

### ISSUE THREAD

**Issue by dongniwang** [syndesisio/syndesis#4766]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Tooltip for the dropdown on the filter toolbar is partially hidden behind another page element. See screenshots below. This happens on both Create a Connection step 1 and the integration list page. 

Possibly relates to https://github.com/syndesisio/syndesis/issues/4385

## Expected behavior

The tooltip should be fully visible when hover.

## Screenshot

<img width="455" alt="screen shot 2019-03-05 at 2 57 25 pm" src="https://user-images.githubusercontent.com/24943812/53834535-4859e180-3f59-11e9-8cb8-f024b536ab53.png">

<img width="960" alt="screen shot 2019-03-05 at 3 17 14 pm" src="https://user-images.githubusercontent.com/24943812/53834758-df269e00-3f59-11e9-89d9-56ea22627092.png">

## Tasks involved / Steps to Reproduce

1.
2.
3.
4.

cc: @mcoker @seanforyou23

**Comment by mastepan** [comment]
@dongniwang has this issue been resolved?

**Comment by dongniwang** [comment]
@mastepan - I think the issue is no longer relevant since we've moved to react.
