### ISSUE TITLE
Cannot select start connection when creating integration

### ISSUE THREAD

**Issue by asmigala** [syndesisio/syndesis#4768]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When creating a new integration, selecting a start connection does nothing. 

## Steps to reproduce
1. Go to Create Integration
2. Select any connection as Start Connection
3. Nothing happens

![no-start](https://user-images.githubusercontent.com/9480152/53862967-3f185580-3fe9-11e9-8bec-435774b72002.gif)

**Comment by heiko-braun** [comment]
@riccardo-forina @gashcrumb FYI

**Comment by tplevko** [comment]
QE is blocked by this

**Comment by christophd** [comment]
@asmigala @tplevko just merged a quick fix so you can continue with your work 

@gashcrumb needs to review after 1st coffee in the morning though 😄

**Comment by gashcrumb** [comment]
@christophd rofl, think it looks good, thanks for jumping on it!

This is what I get for not at least adding comments during previous work to remind myself of some of the reasoning :-)

**Comment by asmigala** [comment]
Verified with latest master.
