### ISSUE TITLE
Data Mapper UI partially hidden when in API Provider integration

### ISSUE THREAD

**Issue by asmigala** [syndesisio/syndesis#4771]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When editing a data mapping in an API Provder integration, the Data Mapper UI is partially hidden by the API Provider toolbar.

![screenshot_2019-03-06_11-30-26](https://user-images.githubusercontent.com/9480152/53874937-c96db300-4003-11e9-81c8-54f4ce7f1a5f.png)

This breaks most of our automated tests, since they expect the buttons in the toolbar to be visible and clickable.

**Comment by heiko-braun** [comment]
@gashcrumb Can you look at this?

**Comment by gashcrumb** [comment]
I'm not seeing this behavior here on either Chrome or Firefox at least on master but let me try one more test with a freshly built UI image and update.

**Comment by gashcrumb** [comment]
Yeah, here I don't see this behavior on master, either when the code served out from the pod or in development mode.  I've checked on Firefox and Chrome.  Also tried making the window more narrow and also shorter but I can't get those toolbar buttons for the data mapper to do that.

**Comment by asmigala** [comment]
@gashcrumb  ok, did some more investigation and I think the main problem here is that in Chrome, this particular page is not scrollable. Our tests use scrollIntoView on the mapping field element, which causes just the .card-pf-body section to scroll under the header.

Here are the screenshot from Firefox and Chrome, notice the Firefox one has a scrollbar, Chrome has no scrollbar, plus a weird grey rectangle at the bottom.
(both of these screenshots were taken manually, not through the automated tests, also both are at commit fc2e36619deffa767408617147a2888092dc8e70)
![dm-firefox](https://user-images.githubusercontent.com/9480152/53942027-04cab900-40ba-11e9-932a-8edbdd7ea563.png)

![dm-chrome](https://user-images.githubusercontent.com/9480152/53942033-085e4000-40ba-11e9-9535-96f76fd3f848.png)

**Comment by asmigala** [comment]
@gashcrumb also note that this is exclusive to the API Provider integration editor, when editing a regular integration, the scrollbar is visible in Chrome:
![dm-chrome-non-api](https://user-images.githubusercontent.com/9480152/53942469-22e4e900-40bb-11e9-8b8d-ec01d1bfb88d.png)

**Comment by asmigala** [comment]
One last thing, I believe this is really a layout problem, there is no reason the scroll should be necessary, the only thing under the fold is the number of fields, which should be visible without scrolling.

**Comment by heiko-braun** [comment]
I can confirm that the page doesn't scroll (on Mac OS / Chrome):

![screenshot 2019-03-07 at 10 32 21](https://user-images.githubusercontent.com/369380/53946580-62fc9980-40c4-11e9-872f-3fc3508459f0.png)

**Comment by gashcrumb** [comment]
@mcoker @seanforyou23 do either of you have a mac to verify this on?

Also on a side-node, do we want that thin padding on either side of the page and the bottom?  It bugs me personally :-)

**Comment by asmigala** [comment]
@gashcrumb this is not exclusive to mac, my screenshots are from linux

**Comment by seanforyou23** [comment]
I don't seem to be able to replicate the overlap as shown in the initial screenshot. However, I also can't seem to scroll and this should be possible when the content is too large to fit. Looks like it's coming from the styles applied to `.pf-c-page__main .pf-c-page__main-section` (overflow), which came from introducing the PF4 masthead. Should be a simple fix, will take a look. The padding @gashcrumb mentioned also seems to be coming from there so can fix both of these in the same go. Thx for bringing this to our attention!

**Comment by asmigala** [comment]
@seanforyou23 the overlap in the initial screenshot is actually due to the automated tests forcefully scrolling an element into view - I was also unable to do that manually.

However, I'd like to reiterate that I think there should not be no scrolling necessary on this page, unless the actual content is too tall - which it isn't in this case (my [first comment](https://github.com/syndesisio/syndesis/issues/4771#issuecomment-470431211)), it's just the footer that's off-screen.

**Comment by heiko-braun** [comment]
@seanforyou23 @gashcrumb is this being taken care of?

**Comment by gashcrumb** [comment]
I'll take another look at this today.

@seanforyou23 ideally the data mapper area should just occupy the full height of the page without overflowing, as it has individual panels that can scroll.  

There's a footer that's out of view in the above screenshots, seems like the height calcuation maybe doesn't take the extra space used by the api provider toolbar into account, perhaps that's what I missed when I first looked at this.

**Comment by gashcrumb** [comment]
Aha, [this todo](https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts#L64-L65) says it all, doesn't it :-)

**Comment by heiko-braun** [comment]
haha, good catch!

**Comment by asmigala** [comment]
Verified with 1.6.1
