### ISSUE TITLE
service-now: processing connection step in integration editor takes too long 

### ISSUE THREAD

**Issue by mmelko** [syndesisio/syndesis#4788]
See also **https://issues.jboss.org/browse/ENTESB-11437**

## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Processing connection step (i.e Add record, confirm after select import-set) in integration editor takes too long when service-now is involved. Confirmation connection after for example selecting import-set may take longer than 15s. 
![screenshot_20190307_114648](https://user-images.githubusercontent.com/6814482/53951818-9a247800-40cf-11e9-97b7-dfa1d290db6f.png)

**Comment by heiko-braun** [comment]
Could it be an issue with the remote system?

**Comment by mmelko** [comment]
I'd say it's quite possible .. but I woudln't expect it when you are confirming connection.

**Comment by heiko-braun** [comment]
@zregvart do we validate connections upon creation?

**Comment by zregvart** [comment]
> @zregvart do we validate connections upon creation?

I don't think this issue is about creating connections, but using ServiceNow connection actions within an integration, am I right @mmelko?

For that we interact with the ServiceNow dynamically to fetch data and validate choices.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11437**
