### ISSUE TITLE
Centrally Monitor any Fuse application in a managed console

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#4793]
See also **https://issues.jboss.org/browse/ENTESB-11508**

## This is a...

<pre><code>
[ x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
As a Fuse administrator, I want to be able to view my metrics of all my Fuse applications in one central managed console.

Minimum DoD:

- A fuse online console can display a representation of an integration running in a different namespace
- A fuse online console can display a representation of an integration running in Fuse on OpenShift
- A fuse online console can display a representation of an integration running in Fuse Online
- A fuse online console can display a representation of an integration running in Fuse Standalone
- The number of messages processed displays in the dashboard.

Metrics:
- Number of messages processed
- Number of messages failed

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11508**
