### ISSUE TITLE
Debug Console - stepwise

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#4795]
See also **https://issues.jboss.org/browse/ENTESB-11506**

## This is a...

<pre><code>
[x ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
As a citizen integrator, when my environment is running camel-k, as soon as I add a connection to my integration I want the integration to be already running. (pre-built integration)

I want to be able to see the data output from my integration, in the console as I build the integration. The integration can have a toggle on/off button to stop the integration.
You can add the step multiple times in an integration.

Minimum DoD:
- A new finish connector is available called "console"
- The console connector is automatically added as the final step.
- The console connector can be removed and added at any point in the future.
- Selecting the console displays a textarea with the latest data shape output.

Questions
Publish and stop still relevant?

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11506**
