### ISSUE TITLE
Conditional Flows

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#4796]
## This is a...

<pre><code>
[x ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
As a citizen integrator, I want to be able to create Integrations using the content-based routing EIP.

Acceptance Criteria:
- I can create multi-flow integrations 
- Based on the message content I can route the message to different flows
- I can add a Content router step and add it to my integration
- In the content router step, I can provide two or more content types (rules I can create similar to filter) that will then correspond to flows

**Comment by dongniwang** [comment]
@gaughan - can you please provide more info on "In the content router I can provide two or more content types that correspond to flows"? 

At what point would users want to add a "Content Router Step"? Is it like API Provider, as the first step of building an integration or users can add this step at any point?

**Comment by gaughan** [comment]
Updated now, on the second point, the step could be at any point.
