### ISSUE TITLE
Cannot use registry.redhat.io

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/syndesis#4799]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

**Comment by heiko-braun** [comment]
@avano reported:

I tried it with 7.2, here is what I did:

- get fuse online install, replace registry.access.redhat.com with registry.redhat.io
- change the install_ocp.sh to get local files instead of files from github
- create namespace, create the secret that is generated on the redhat page in my namespace
- bash install_ocp.sh
- operator pod won't start because it can't pull the images, so I needed to add my secret to syndesis-operator SA: `oc secrets link syndesis-operator <my-secret> --for=pull`
- then the operator image is pulled and it spawns the syndesis infra, however, all pods fail because they can pull the images, so I needed to add the `imagePullSecret` to all deployment configs: `oc patch dc/<all-syndesis-dc> -p '{"spec": {"template": {"spec": {"imagePullSecrets": [{"name": "<my-secret>"}]}}}}'`
- then syndesis is spawned successfully
- only problem left is that **I can't create an integration**, as it is not able to pull the s2i image. I tried to add my secret to all SAs I had in the project: `builder`, `default`, `deployer`, `syndesis-integration`, `syndesis-server` (I left out syndesis-oauthproxy and syndesis-prometheus, but those two shouldn't matter). The build pod always fails with:

```
      Reason:   Error
      Message:  Image "registry.redhat.io/fuse7/fuse-ignite-s2i@sha256:bc0dfc7b29b..." not available locally, pulling ...
pulling image error : Get https://registry.redhat.io/v2/fuse7/fuse-ignite-s2i/manifests/sha256:bc0dfc7b29bc005673bfdc5a8d3ffdeea41f28d1922d5f71dee3e0503b9255ca: unauthorized: Please login to the Red Hat Registry using your Customer Portal credentials. Further instructions can be found here: https://access.redhat.com/articles/3399531
error: build error: unable to get registry.redhat.io/fuse7/fuse-ignite-s2i@sha256:bc0dfc7b29bc005673bfdc5a8d3ffdeea41f28d1922d5f71dee3e0503b9255ca

```

Maybe it is possible to add the imagePullSecret to the ImageStream directly, but I didn't find a way to do so. Any ideas? :grin:

**Comment by heiko-braun** [comment]
@rhuss said:

@avano in https://github.com/syndesisio/syndesis/blob/master/app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftServiceImpl.java (line 243 or so) the reference to the imagepull secret need to be added afais (sorry, on mobile can't do proper linking). This means we would need a new configuration option (also as part of the Syndesis CR), which switches on authentication and specifies the name of the secret to us for authentication (which then would need to be added as described in the docs)

For the regular images, this information can be used by the operator to add the pullsecrets when creating the deployments. (Need to be added to the operator though).

The question remains how to add this to a template based install. I guess we need to introduce a second template with this pull secrets enabled. And cc affair the install script accordingly to pick this up.

**Comment by rhuss** [comment]
I can start working on this on Thursday, but happy to help to assist if someone could already work on it. The solution includes several parts:

* Update the installation script to add the fixes that @avano found in the comments above. There should be an option like `--pull-secrets <secret-name>` to enable this functionality. 

* Update syndesis-server to add the imagePullSecret to the generated DC for the integration runtime. This should come from the syndesis-server config map.

* Same for 'update_ocp.sh' which needs to switch from non-authorized to an authorized mode

* Add a new variant for the templates with 'imagePullSecrets' enabled and with a template parameter for specifying the secret name. Alternatively check whether an empty 'imagePullSecrets' in a Pod spec would work, which would make things much easier as we would only have to add an extra parameter `IMAGE_PULL_SECRET` which could be empty in the default case. The template also needs to add the reference to the pull secret to the syndesis-server config map

* Update the Operator and add a field 'imagePullSecret:' to the Syndesis CR, which is evaluated in the operator to either just fill in the IMAGE_PULL_SECRET template parameter for the single template, or, if we have to use two templates also select the proper template with pullSecrets enabled.

* Update the update scripts to add the secret name to the syndesis-server config-map + modify all deployment etc to add the missing field. This is a tricky task, as the secret name is an external parameter to the update script, so the whole way how we are doing updates must be adapted (i.e. the update script might require an extra parameter which then is also provided within the operator when it calls the update script).

-----------------

@avano @heiko-braun this is a lot to cover. I suggest working on the first item first to allow to test, whether adding imagePullSecrets to the integration runtime DCs fixes the remaining issue. 

@avano you could also create an image runtime and then adapt the created DC afterwards by adding the imagePullSecret with 'oc edit' and kill the pod. This would verify that we need to add it during the creation of the integration runtime pods.

A totally other question will be, how the `kamel` can use pull secrets to fetch its images for the Camel-K mode.

**Comment by avano** [comment]
@rhuss I built my own server image, where I added my pull secret into integration's **build**config:

```
Name:		i-q
Namespace:	syndesis
Created:	8 minutes ago
Labels:		syndesis.io/app=syndesis
		syndesis.io/deployment-version=1
		syndesis.io/integration-id=i-L_fs0Dm_NVxaGBXa6UOz
		syndesis.io/type=integration
		syndesis.io/username=developer
Annotations:	syndesis.io/deployment-version=1
		syndesis.io/integration-id=i-L_fs0Dm_NVxaGBXa6UOz
		syndesis.io/integration-name=q
Latest Version:	1

Strategy:		Source
From Image:		ImageStreamTag syndesis/fuse-ignite-s2i:1.5
Pull Secret Name:	<my secret>
Output to:		ImageStreamTag i-q:1
Binary:			provided on build

Build Run Policy:	SerialLatestOnly
Triggered by:		<none>
Builds History Limit:
	Successful:	5
	Failed:		5

Build	Status		Duration	Creation Time
i-q-1 	complete 	3m59s 		2019-03-11 09:30:47 +0100 CET

Events:	<none>
```

I just added `withNewPullSecret("secret name")` inside this block: https://github.com/syndesisio/syndesis/blob/ba937b8043a18a90019b5b354f19ff3b10ae033b/app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftServiceImpl.java#L314-L325 and it worked well

**Comment by rhuss** [comment]
>     * then the operator image is pulled and it spawns the syndesis infra, however, all pods fail because they can pull the images, so I needed to add the `imagePullSecret` to all deployment configs: `oc patch dc/<all-syndesis-dc> -p '{"spec": {"template": {"spec": {"imagePullSecrets": [{"name": "<my-secret>"}]}}}}'`

@avano I don't understand why this is needed. Wouldn't it be enough to link the secrets to the SA under which these deployments are running ? If this would be possible, that would be much easier and would make many of the above steps obsolete (as we don't have to touch the templates then)

**Comment by rhuss** [comment]
> I just added `withNewPullSecret("secret name")` inside this block:

@avano maybe instead of adding the pull secret directly, we could add a (new) service accoung, e.g. "syndesis-build" here and then link this to the secret. The benefit of this approach would be, that we don't have to introduce a config variable in syndesis-server which conditionally adds this `withNewPullSecret()` part, but always adds the SA which can be manipulated from the outside to have the proper creds. Could you please try this, too ?

**Comment by rhuss** [comment]
Ideally, we can avoid `withPullSecret:` alltogether and do everything over the service accounts. In this case we only would have to update the install scripts (and the update process to add service accounts where missing). But no template change or, worst, introduce a new template (one for authentication and one without).

**Comment by avano** [comment]
> > then the operator image is pulled and it spawns the syndesis infra, however, all pods fail because they can pull the images, so I needed to add the `imagePullSecret` to all deployment configs: `oc patch dc/<all-syndesis-dc> -p '{"spec": {"template": {"spec": {"imagePullSecrets": [{"name": "<my-secret>"}]}}}}'`
> 
> @avano I don't understand why this is needed. Wouldn't it be enough to link the secrets to the SA under which these deployments are running ? If this would be possible, that would be much easier and would make many of the above steps obsolete (as we don't have to touch the templates then)

I probably messed something up when I tried that initially, after adding the pull secret to all syndesis-* SAs, it pulled all images, **except ui** (that one doesn't use any service account) without any problem:

```
NAME                          READY     STATUS             RESTARTS   AGE
syndesis-db-1-sjbfz           1/1       Running            0          6m
syndesis-meta-1-krhxc         1/1       Running            0          3m
syndesis-oauthproxy-1-nl4hd   1/1       Running            0          2m
syndesis-operator-1-vkp87     1/1       Running            0          6m
syndesis-prometheus-1-7w9sw   1/1       Running            0          1m
syndesis-server-1-6qfhs       1/1       Running            0          3m
syndesis-ui-1-deploy          1/1       Running            0          4m
syndesis-ui-1-mbk7n           0/1       ImagePullBackOff   0          3m
todo-1-build                  0/1       Completed          0          6m
todo-1-nsh52                  1/1       Running            0          6m

```

**Comment by avano** [comment]
> Ideally, we can avoid `withPullSecret:` alltogether and do everything over the service accounts. In this case we only would have to update the install scripts (and the update process to add service accounts where missing). But no template change or, worst, introduce a new template (one for authentication and one without).

I tried with the new service account:

```
Name:                syndesis-builder
Namespace:           syndesis
Labels:              app=syndesis
                     syndesis.io/app=syndesis
                     syndesis.io/component=syndesis-builder
                     syndesis.io/type=infrastructure
Annotations:         <none>
Image pull secrets:  syndesis-builder-dockercfg-4lvcz
                     <my secret>
Mountable secrets:   syndesis-builder-token-kjr52
                     syndesis-builder-dockercfg-4lvcz
Tokens:              syndesis-builder-token-45lqk
                     syndesis-builder-token-kjr52
Events:              <none>
```

Then I added `.withServiceAccount("syndesis-builder")` in ensureBuildConfig and it was added:

```
apiVersion: build.openshift.io/v1
kind: BuildConfig
...
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: {}
  output:
    to:
      kind: ImageStreamTag
      name: i-integration:1
  postCommit: {}
  resources: {}
  runPolicy: SerialLatestOnly
  serviceAccount: syndesis-builder
...
```

But it doesn't work for me:

```
oc logs -f i-integration-1-build
Image "registry.redhat.io/fuse7/fuse-ignite-s2i@sha256:bc0dfc7b29b..." not available locally, pulling ...
pulling image error : Get https://registry.redhat.io/v2/fuse7/fuse-ignite-s2i/manifests/sha256:bc0dfc7b29bc005673bfdc5a8d3ffdeea41f28d1922d5f71dee3e0503b9255ca: unauthorized: Please login to the Red Hat Registry using your Customer Portal credentials. Further instructions can be found here: https://access.redhat.com/articles/3399531
error: Unable to update build status: resource name may not be empty
error: Unable to update build status: resource name may not be empty
error: build error: unable to get registry.redhat.io/fuse7/fuse-ignite-s2i@sha256:bc0dfc7b29bc005673bfdc5a8d3ffdeea41f28d1922d5f71dee3e0503b9255ca
```

Did I miss something here @rhuss ?

**Comment by rhuss** [comment]
@avano thanks for confirming that deployments work with the SAs properly prepared. So we should add a SA to the syndesis-ui as well.

For the other problems, I don't really have a clue. Could be that the S2I build system doesn't honor the BuildConfig's SA for pulling the images (but that I would consider to be a bug). Can we ask on the OpenShift channels how a S2I base image can be pulled with authentication when configuring a BuildConfig (and without 'imagePullSecrets') ? I guess this is  a very common setup/sitation so I hope that there might be an answer for us. Unfortunately I have to jump on the train soonish, so don't have time to ask myself.

**Comment by heiko-braun** [comment]
It looks like replacing the registry in `fuse_online_config.sh` and `resources/*.yml` doesn't lead to images being pulled from registry.redhat.io. After running `bash install_ocp.sh` I still see references to the old registry:

```
oc describe is fuse-ignite-server
Name:			fuse-ignite-server
Namespace:		syndesis
Created:		3 minutes ago
Labels:			syndesis.io/app=syndesis
			syndesis.io/component=syndesis-server
			syndesis.io/type=infrastructure
Annotations:		openshift.io/image.dockerRepositoryCheck=2019-03-12T09:44:34Z
			openshift.io/image.insecureRepository=false
Docker Pull Spec:	172.30.1.1:5000/syndesis/fuse-ignite-server
Image Lookup:		local=false
Unique Images:		1
Tags:			1

1.5
  updates automatically from registry registry.access.redhat.com/fuse7/fuse-ignite-server:1.2-5

  * registry.access.redhat.com/fuse7/fuse-ignite-server@sha256:03bc567c7ff37d5520599fdfe0b9d81245a7223f9c6491f0c370e6b1ee546fc2
      3 minutes ago

```

**Comment by avano** [comment]
@heiko-braun you also need to change this line in `install_ocp.sh`: https://github.com/syndesisio/fuse-online-install/blob/master/install_ocp.sh#L387 

to:

```
local url="./${resource}"
```

**Comment by heiko-braun** [comment]
Thanks @avano!

**Comment by rhuss** [comment]
@avano @heiko-braun what is the current status ? Is it still that the S2I build which doesn't work ?

what do I need to rebuild this issue ? I guess I would need a red-hat subscription, right ? What is the easiest way to get this subscription ?

**Comment by heiko-braun** [comment]
It's documented here: https://access.redhat.com/RegistryAuthentication

**Comment by avano** [comment]
@heiko-braun btw I tried to add the pull secret to `default SA` as mentioned by you here: https://github.com/syndesisio/syndesis/issues/4165#issuecomment-472100228 and it doesn't work for me :/

```
oc describe sa default                                                                                                                                             ⌚ 8:52:49
Name:                default
Namespace:           syndesis2
Labels:              <none>
Annotations:         <none>
Image pull secrets:  default-dockercfg-lmggg
                     <my secret>
Mountable secrets:   default-token-vmqwb
                     default-dockercfg-lmggg
Tokens:              default-token-qt8nw
                     default-token-vmqwb
Events:              <none>
```

```
oc get pods                                                                                                                                                                      Thu Mar 14 08:54:23 2019

NAME                           READY     STATUS             RESTARTS   AGE
syndesis-db-1-m86hj            1/1       Running            0          2m
syndesis-meta-1-4gg8g          0/1       ImagePullBackOff   0          1m
syndesis-meta-1-deploy         1/1       Running            0          2m
syndesis-oauthproxy-1-deploy   1/1       Running            0          2m
syndesis-oauthproxy-1-f8blm    0/1       ImagePullBackOff   0          2m
syndesis-operator-1-x8nnc      1/1       Running            0          2m
syndesis-prometheus-1-deploy   1/1       Running            0          2m
syndesis-prometheus-1-fsn56    0/1       ImagePullBackOff   0          1m
syndesis-server-1-deploy       1/1       Running            0          2m
syndesis-server-1-n78wq        0/1       ImagePullBackOff   0          2m
syndesis-ui-1-2gdv7            1/1       Running            0          2m
todo-1-9dp6m                   1/1       Running            0          1m
todo-1-build                   0/1       Completed          0          2m
```

**Comment by avano** [comment]
@rhuss for me the work to do is:

- find out how to use the pull secret in s2i (SA method didn't work for me, .withPullSecret("my secret") worked)
- use the pull secret in syndesis SAs + use syndesis SA in UI dc

**Comment by heiko-braun** [comment]
yes, I have tried the default SA as well, but it doesn't work. I guess our best bet is to move ahead as Roland suggested: 

a) add service accounts for all pods
b) link service accounts to pull secrets
c) update  `OpenShiftServiceImpl.java` to either levergae service accounts or pull secrets as well.
d) update install scripts to allow setting credentials

**Comment by rhuss** [comment]
> find out how to use the pull secret in s2i (SA method didn't work for me, .withPullSecret("my secret") worked)

As mentioned we should try hard to get this running by using an authenticated SA only. Otherwise we would have much more work in the installation scripts and operator to distinguish the authenticated and non-authenticated case.

**Comment by rhuss** [comment]
@heiko-braun @avano I back Heikos list, and I'm going to open dedicated issues for each step required so that we can discuss this later on the call.

**Comment by avano** [comment]
> > find out how to use the pull secret in s2i (SA method didn't work for me, .withPullSecret("my secret") worked)
> 
> As mentioned we should try hard to get this running by using an authenticated SA only. Otherwise we would have much more work in the installation scripts and operator to distinguish the authenticated and non-authenticated case.

I'm not against that, I just shared my experience :-)

**Comment by astefanutti** [comment]
For s2i build, the secret is used for pushing and pulling build images, and has to be linked by running `oc secrets link builder <pull_secret_name>`, without `--for=pull`. By default, the `builder` service account is used.

Another lead is to use `referencePolicy: local` for built images, otherwise clients fetch the image directly from the external repository and not the integrated one.

**Comment by rhuss** [comment]
@astefanutti @avano Is there anything left to do with this issue ? Or can it be closed ?
