### ISSUE TITLE
Templating step syntax highlighting broken in compiled image

### ISSUE THREAD

**Issue by phantomjinx** [syndesisio/syndesis#4802]
## This is a...

<pre><code>
[ ] Feature request
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Running the UI with yarn start:minishift, the template-step Codemirror editor highlights syntax correctly. However, using a compiled/deployed UI image, the syntax highlighting no longer works.

**Comment by phantomjinx** [comment]
@gashcrumb 
Well this is really odd ...
My [sidenote](https://github.com/syndesisio/syndesis/issues/4777#issuecomment-470623572) mentioned an extra node_modules directory in ui/node_modules/ng2-codemirror. Well turns out this was created not by me accidentally running yarn in the wrong directory but comes from _yarn install_ run by the maven compile procedure. In fact executing _yarn install_ with no node_modules directory at all brings the same result.
ng2-codemirror has a dependency of 5.22.0 but the version coming down to its local node_modules is 5.40.0. This is not aligned with syndesis' versioning which has upgrade to codemirror 5.42.0. Therefore, exactly where it is getting it from is an interesting question.

Removal of this extra node_modules directory fixed the CodeMirror editor issues yesterday.

2 possibilites:
- Try and remove the extra node_modules directory as a post-process during _yarn install_. This would require the least changes since no code changes are required and the current CodeMirror install has a patch applied;
- Go with the extra node_modules version of CodeMirror and remove the 'general' dependency from syndesis's package.json. This would require code changes and modifications to the patch. Also, and more importantly this might affect any further uses of CodeMirror by other use-cases in the future.

**Comment by phantomjinx** [comment]
Consensus is opting for first possibility.

**Comment by tplevko** [comment]
Verified by QE
