### ISSUE TITLE
DB -> S3 integration with collection support

### ISSUE THREAD

**Issue by tplevko** [syndesisio/syndesis#4808]
See also **https://issues.jboss.org/browse/ENTESB-11481**

## This is a...

<pre><code>
[ x ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

I was trying to create simple integration from DB -> S3. The intention was to continuously "backup" the DB results into S3. However it seems that there is a conversion problem between datatypes.

```Caused by: No type converter available to convert from type: java.util.ArrayList to the required type: java.io.InputStream```

The integration zip file attached.
[DB_to_s3-export.zip](https://github.com/syndesisio/syndesis/files/2946349/DB_to_s3-export.zip)

## Steps to reproduce
1. create S3 connection
2. create integration - DB ->  S3
3. specify the S3 input datatype as collection
4. add mapping between these two connections
5. observe the error in integration log

**Comment by oscerd** [comment]
S3 expects an input stream, a file or a wrappedFile in an single operation (not multipart).

https://github.com/jboss-fuse/camel/blob/2.21.x.redhat-7-x/components/camel-aws/src/main/java/org/apache/camel/component/aws/s3/S3Producer.java#L218-#L229

No collection are supported.

**Comment by oscerd** [comment]
Definitely not a bug.

**Comment by tplevko** [comment]
@oscerd from your POV, can this be updated to feature request - to provide internally data conversion?

**Comment by oscerd** [comment]
I think it may be a possible new feature, yes.

**Comment by tplevko** [comment]
Thanks for clarification @oscerd. Changed to feature request.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11481**
