### ISSUE TITLE
Integration flow doesn't continue after DB DELETE and INSERT 

### ISSUE THREAD

**Issue by mastepan** [syndesisio/syndesis#4811]
See also **https://issues.jboss.org/browse/ENTESB-11436**

## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Let's have an integration:
DB Insert -> whatever
or
DB Delete -> whatever

Each integration run performs only Insert and Delete and doesn't continue to the following defined steps.

Note:
DB Select doesn't interrupt an integration run even if the result is nothing.

**Comment by heiko-braun** [comment]
Do you have a split before insert/delete? Can you provide an example integration? 

@christophd Does it ring a bell?

**Comment by christophd** [comment]
yes, an example integration would be good

**Comment by mastepan** [comment]
[aaa-export (2).zip](https://github.com/syndesisio/syndesis/files/2946814/aaa-export.2.zip)
Just 
**DB Delete from todo -> DB insert into contact...**
Delete is first step.

**Comment by christophd** [comment]
has that been working before? is that a regression? seems a bit strange to start an integration with a delete

**Comment by christophd** [comment]
@KurtStam any thoughts on this? has that ever been supported to have a SQL delete as a starting connection?

**Comment by mastepan** [comment]
@christophd This integration doesn't make sense probably. But SQL Delete/Insert can be used in any part of any integration and everything after that is dead I think. I can check it once more on Monday to be sure.
If this is a regression? I don't know.

**Comment by christophd** [comment]
I had a look and it seems to fail directly in the start connector because there is some unexpected exchange body auto converted to a list. This causes a class cast exception in further processing.

I guess this has never been working but that does not matter of course.

Provided a PR fixing this issue

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11436**
