### ISSUE TITLE
Cyclic reference handling for API connector/provider

### ISSUE THREAD

**Issue by tplevko** [syndesisio/syndesis#4826]
See also **https://issues.jboss.org/browse/ENTESB-11480**

## This is a...

<pre><code>
[ x ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
ATM the API connector and provider can't handle cyclic references in OpenApi definitions. This limitation can be seen when trying to use e.g. [openhabApi definition](http://demo.openhab.org:8080/rest/swagger.json)

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11480**
