### ISSUE TITLE
Setup monitoring stack on staging cluster

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/syndesis#4830]
See also **https://issues.jboss.org/browse/ENTESB-11512**

**Comment by alexkieling** [comment]
I'm working on it.

**Comment by zregvart** [comment]
Staging cluster is created manually, we should perhaps think about how we update so it keeps in sync with the codebase.

I see two ways of doing that:
 - requesting permissions needed to run the operator and supporting upgrades in the operator (#5117)
 - adding code to the CI to check for changes in the template and modifying the objects directly from CI (would require OAuth token to be configured on CI)

**Comment by alexkieling** [comment]
My plan is to install the integr8ly monitoring stack in a separate OpenShift project using their [application-monitoring-operator](https://github.com/integr8ly/application-monitoring-operator) and it shouldn't be affected by updates to syndesis.

**Comment by alexkieling** [comment]
@heiko-braun I think we'll need to keep this task on hold until the managed cluster is upgraded to a version that supports the management of operators.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11512**
