### ISSUE TITLE
Fix kubeclient version

### ISSUE THREAD

**Issue by nicolaferraro** [syndesisio/syndesis#4836]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

`kubernetes-client 3.1.12.fuse-730020` used in branch 1.6.x and master is not pinned and will disappear shortly. We should use `kubernetes-client 3.1.12.fuse-730022` which is pinned.

**Comment by heiko-braun** [comment]
@nicolaferraro Are you going to take care of this?

**Comment by nicolaferraro** [comment]
Yes, just need some time to test it.
