### ISSUE TITLE
AWS-SQS Connector

### ISSUE THREAD

**Issue by oscerd** [syndesisio/syndesis#4843]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Create a connector for AWS-SQS

As a citizen integrator, I want to be able to consume and submit messages in my AWS-SMS

1. I want to be able to specify my queue type: Simple or FIFO
2. I want to be able to provide a filter
3. I want to be able to delete messages
4. I want to be able to Send, receive, or delete messages in batches.
(5. I want to be able to send payloads larger than 256KB via S3)
6. I want to be able to enable long polling.

**Comment by heiko-braun** [comment]
@gaughan Can you supply a user story and acceptance criteria for this one? @oscerd Volunteered to look into it.

**Comment by gaughan** [comment]
@heiko-braun updated above

**Comment by oscerd** [comment]
At the moment:

1. you're able to distinguish through the queue name (ended with .fifo), as you may read here: https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/FIFO-queues.html

2. Not supported as option, you can use a normal camel filter.

3. Not supported as producer operation

4. Not supported as producer operation, you can only consume as batch.

5. Not supported.

6. supported as option when you create the queue

**Comment by oscerd** [comment]
About S3 for big message, not sure if this is really feasible, this would need use an extended client library and we may break camel users. So I don't think it can be done, for the other points I'm working on that

**Comment by gaughan** [comment]
For 2, not supported by AWS?
3,4 supported as a consumer?
5, 6 ok

**Comment by oscerd** [comment]
As far as I see you cannot filter directly through AWS, you can use camel for this.

you can delete messages after your consumed them or after they've been filtered (so as consumer you can delete multiple messages) and receive as batch, but you can't delete messages as batch as a producer operation and you can't send messages batch as producer.

**Comment by oscerd** [comment]
For send Batch messages I completed:  https://issues.apache.org/jira/browse/CAMEL-13317
For deleting a single message I completed: https://issues.apache.org/jira/browse/CAMEL-13318

We need to backport this stuff.

**Comment by oscerd** [comment]
For deleting messages I think it's enough to delete them while consuming. Otherwise we can use the deleteMessage operation, but this requires a receipt handle header, that can be obtained only after consuming the message. So as a producer operation, in syndesis, it doesn't really make sense.

**Comment by gaughan** [comment]
Sounds good to me to delete while consuming. thanks

**Comment by avano** [comment]
@oscerd can this one be closed?

**Comment by oscerd** [comment]
yes, I think so, maybe there is space for improvements, but the base features are in. Thanks @avano

**Comment by avano** [comment]
thanks!
