### ISSUE TITLE
AtlasMap is unable to find mapping

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#4846]
This is because we do sanitize the resource name like: https://github.com/syndesisio/syndesis/blob/1.6.x/app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/CamelKPublishHandler.java#L344

**Comment by heiko-braun** [comment]
How is this different from #4840?

**Comment by lburgazzoli** [comment]
The difference is that in  #4840 the mapping is not attached to the mapping step whereas in this one, even when the mapping is present, atlasmap does not find it because the name is mangled

**Comment by heiko-braun** [comment]
@lburgazzoli Can you backport this to 1.6.x?

**Comment by lburgazzoli** [comment]
It is already on 1.6 61065adb9395bfcf467f54e8b6a9c78558894cd7

**Comment by tplevko** [comment]
Camel-K TP related, QE ignore for now.
