### ISSUE TITLE
New exception with OData's read operation

### ISSUE THREAD

**Issue by phantomjinx** [syndesisio/syndesis#4848]
I got new exception with OData's read operation:
`o.a.c.component.olingo4.Olingo4Consumer  : Consumer Consumer[olingo4-olingo4-0-0://read] failed polling endpoint: olingo4-olingo4-0-0://read. Will try again at next poll. Caused by: [org.apache.camel.RuntimeCamelException - org.apache.olingo.client.api.communication.ODataClientErrorException: Path segment not supported: City) [HTTP/1.1 501 Not Implemented]]
org.apache.camel.RuntimeCamelException: org.apache.olingo.client.api.communication.ODataClientErrorException: Path segment not supported: City) [HTTP/1.1 501 Not Implemented]`

Not sure if this is caused by the exception reported in this GH issue or not, either way the read operation is not working properly for me (I am able to get the whole collection and single entity, but not individual property of entity).

### Steps to reproduce:
 1. Create integration with OData connector as start step
 2. Choose read action
 3. Choose "Airports" as Resource collection
 4. Enter `('KLAX')/Location` in the Entity Key Predicate

It would be useful if the connector logged to pod what Request URL it's trying to send.

_Originally posted by @jsafarik in https://github.com/syndesisio/syndesis/issues/4791#issuecomment-471488857_

**Comment by phantomjinx** [comment]
@jsafarik 
The problem is caused not just by the splitting (that is an extra problem I've found while doing a fix) but also in the lack of handling of the key predicate. Up until this point, the ODataComponent assumed only integer predicates of the form _(1)_ so did not take into account the addition of quotes or indeed sub-predicates, ie. (1)/Location. I have a PR in the works that addresses both of these omissions.

**Comment by jsafarik** [comment]
@phantomjinx ok, thanks for clearing it up :)

**Comment by jsafarik** [comment]
Testing this today, I found out that reading a simple property is ok (ie. https://services.odata.org/V4/TripPinServiceRW/People('russellwhyte')/LastName) but reading a complex one (ie. https://services.odata.org/V4/TripPinServiceRW/People('russellwhyte')/AddressInfo) results in `Consumer Consumer[olingo4-olingo4-0-0://read] failed polling endpoint: olingo4-olingo4-0-0://read. Will try again at next poll. Caused by: [org.apache.camel.RuntimeCamelException - org.apache.olingo.commons.api.ex.ODataException: Unsupported property: AddressInfo]` again.

**Comment by phantomjinx** [comment]
@jsafarik
Yeah, this is a limitation with the underlying camel-olingo4 component and will require more work to implement.

@heiko-braun

**Comment by jsafarik** [comment]
@phantomjinx @heiko-braun 
is this feature (support of reading complex property) going to be in 7.3?

**Comment by phantomjinx** [comment]
@jsafarik
Created #5067 to track this but not going to be in 7.3 since it is going to need looking at upstream and understanding why it wasn't included in the first place (might not be hard but don't know at this stage).

@heiko-braun

**Comment by phantomjinx** [comment]
As created #5067 from [comment](https://github.com/syndesisio/syndesis/issues/4848#issuecomment-474896328), I'll close this one.

**Comment by jsafarik** [comment]
thanks
