### ISSUE TITLE
OCP 4: syndesis-server exception: Caused by: java.net.UnknownHostException: openshift.default.svc: Name or service not known

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis#4854]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
On openshift 4, I see this error in the sydnesis-server logs:
`Caused by: java.net.UnknownHostException: openshift.default.svc: Name or service not known`

Using a terminal against the server pod:
```
sh-4.2$ ping openshift.default.svc
ping: openshift.default.svc: Name or service not known
sh-4.2$ ping kubernetes.default.svc
PING kubernetes.default.svc.cluster.local (172.30.0.1) 56(84) bytes of data.
From ip-10-131-0-1.ec2.internal (10.131.0.1) icmp_seq=1 Destination Host Unreachable
From ip-10-131-0-1.ec2.internal (10.131.0.1) icmp_seq=2 Destination Host Unreachable
From ip-10-131-0-1.ec2.internal (10.131.0.1) icmp_seq=3 Destination Host Unreachable```
```

**Comment by avano** [comment]
works ok now on openshift 4 preview from rhpds

**Comment by heiko-braun** [comment]
Thanks for verifying this @avano
