### ISSUE TITLE
OCP 4: Can't login: 500 Internal Error

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis#4857]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
Part of #4614.
When you try to log into Syndesis via OCP 4: you get a 500 Internal Error screen.

## Expected behavior
Syndesis UI

## Screenshot

![500_Internal_Error](https://user-images.githubusercontent.com/103255/54227242-e1e33f00-44d5-11e9-8b66-3f1b99e64719.jpg)

## Oauth Proxy Log:

[syndesis-oauthproxy-1-f7xrk-syndesis-oauthproxy.log](https://github.com/syndesisio/syndesis/files/2958308/syndesis-oauthproxy-1-f7xrk-syndesis-oauthproxy.log)

**Comment by zregvart** [comment]
@chirino mentioned that switching the oauth-proxy image to `quay.io/openshift/origin-oauth-proxy:latest` helped fix this.

**Comment by heiko-braun** [comment]
@nicolaferraro I think you managed ot get it running on OCP4, right? Can we close this one?

**Comment by janstey** [comment]
@chirino @zregvart where exactly do we need to change this oauth proxy image? @djcoleman or @orpiske can take a look next week after we get CR1 complete.

**Comment by zregvart** [comment]
@janstey here:

https://github.com/syndesisio/syndesis/blob/21fde8d51182af4fef72edc96aea32f4466a5639/install/syndesis.yml#L236

and here:

https://github.com/syndesisio/syndesis/blob/21fde8d51182af4fef72edc96aea32f4466a5639/install/syndesis.yml#L1080

And I guess we need to make this change here also.

**Comment by zregvart** [comment]
A bit risky to depend on `:latest`, would be good if we would have a fixed tag to target, I see `v4.0.0` but it seems to move with `:latest`.

**Comment by nicolaferraro** [comment]
> @nicolaferraro I think you managed ot get it running on OCP4, right? Can we close this one?

We got it working on the OCP4 cluster by switching to the `quay.io/openshift/origin-oauth-proxy:latest` image. Yeah, a tagged version would be better.

**Comment by heiko-braun** [comment]
@nicolaferraro Can you try 4.0.0 and provide feedback?

**Comment by nicolaferraro** [comment]
Tag `v4.0.0` works. Tested on demo cluster.

**Comment by heiko-braun** [comment]
@nicolaferraro Can you backport the update to 4.0.0 to master and 1.6.x?

**Comment by nicolaferraro** [comment]
Does this need to be in 1.6.x too? Not that the image is overridden in https://github.com/syndesisio/fuse-online-install/blob/63a7ae7b36bd9dc9a9f348c76c0c983626d833d0/import_images.pl#L69 with a productized one. The one we're setting here is named `origin-`, so I assume it is valid for upstream..

**Comment by heiko-braun** [comment]
Yes, it needs to be in 1.6.x. I can talk to Jon about the 4.0.0 prod one.
