### ISSUE TITLE
Templating step not working in Camel K mode

### ISSUE THREAD

**Issue by nicolaferraro** [syndesisio/syndesis#4863]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

`mustache` component not found. It is not added in Camel K mode when used.

**Comment by zregvart** [comment]
I see that the proper dependencies (template step has mustache, velocity and freemarker components as dependenceis) are added:

https://github.com/syndesisio/syndesis/blob/ba937b8043a18a90019b5b354f19ff3b10ae033b/app/integration/api/src/main/java/io/syndesis/integration/api/IntegrationResourceManager.java#L168

https://github.com/syndesisio/syndesis/blob/21fde8d51182af4fef72edc96aea32f4466a5639/app/common/model/src/main/java/io/syndesis/common/model/integration/step/template/TemplateStepLanguage.java#L195-L198

And from what I can see this is invoked:

https://github.com/syndesisio/syndesis/blob/21fde8d51182af4fef72edc96aea32f4466a5639/app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/CamelKPublishHandler.java#L279-L286

So how come that the component is missing in the end, do we need to register components for use within Camel-K runtime somehow?

**Comment by valdar** [comment]
@nicolaferraro could I be of any help?

**Comment by nicolaferraro** [comment]
Thanks, I've already implemented a fix in a private branch and need to backport it. Will do it soon.

The fix is adding dependencies as Zoran mentioned.

**Comment by heiko-braun** [comment]
Lowering the priority after talking to Gary.
