### ISSUE TITLE
Inconsistent Maven repositories configuration

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#4864]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

It seems that we're inconsistently configuring Maven repositories, this leads to hard to debug issues (artefacts not found, builds fail). From what QE reports is that it fails integration S2I builds.

What we do know is that we should not be using `origin-repository.jboss.org`.

This could also be a `prio/p0`, marking it as `prio/p1` for now.

cc @asmigala

**Comment by zregvart** [comment]
Some things we need to do:
 - not use `origin-repository.jboss.org`
 - use consistent repository IDs, these get set to `_remote.repository` and for same artifact if the repositori ID differs the artifact will be re-downloaded
 - use consistent repository URLs
 - remove no longer needed repositories - any additional repositories slow down the build
 - use the canonical Maven Central repository (https://repo.maven.apache.org/maven2/)
 - make sure that we're consistent in the generated projects and configuration

**Comment by zregvart** [comment]
@asmigala can you please repeat your test with current `master`. Also, can you comment on if you consider this a blocking (p0) issue and we need to backport it to `1.6.x`?

**Comment by tplevko** [comment]
@asmigala can this be closed?

**Comment by asmigala** [comment]
Yes, haven't run into this again and apparently the main cause was something entirely different (#4867), so I will close this
