### ISSUE TITLE
Publish button disabled when editing deployed API Provider integration

### ISSUE THREAD

**Issue by asmigala** [syndesisio/syndesis#4865]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When editing an already deployed API Provider integration, the Publish button is disabled (it's greyed out and shows the in-progress spinner). This only happens with API provider integration, not with regular integration. 

## Steps to reproduce
1. create an API Provider integration, implement at least one operation
2. publish the integration, wait until it's running
3. edit the integration, the publish button is disabled

![int-running](https://user-images.githubusercontent.com/9480152/54271651-3d6b0680-4582-11e9-9208-d1f32e1d9cc7.png)
![cannot-publish](https://user-images.githubusercontent.com/9480152/54271654-3f34ca00-4582-11e9-95e9-25a4318a31e7.png)

**Comment by asmigala** [comment]
There is a potential workaround, you can click any of the operations in the integration editor and the Publish button becomes active. However, this is hard to discover, especially when the user edits the integration to only delete an operation using the View/Edit API Definition, as coming back from the Apicurio editor does not reenable the Publish button.

**Comment by gashcrumb** [comment]
One other thing to check, if you change something in the integration, does the publish button become enabled?  Well, I can check that here, I think I have an idea of what's going on.

**Comment by asmigala** [comment]
Yes, it's enough to just open any operation flow and the button gets enabled, you don't even need to change anything. But my point is that there are situations where the user would legitimately want to redeploy the integration and the publish button would be disabled.

**Comment by gashcrumb** [comment]
@heiko-braun assuming we'd want this fixed for 7.3 I created #4872 also.

**Comment by asmigala** [comment]
Verified with 1.6.1
