### ISSUE TITLE
Aggregate step does not update its data shape 

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#4866]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
The aggregate step does not update its datashape when subsequent steps change, split steps handles changes correctly. 
![image](https://user-images.githubusercontent.com/46345469/54270424-af8e1c00-457f-11e9-8465-534b2e4624b8.png)
It can be fixed by removing the aggregate step and adding it again. 
## Steps to reproduce
- Start: db "select * from todo"
- End: db add_lead
- add split and aggregate steps between start and end
- add template after aggregate (template used by example, use whatever comes in handy)
- aggregate step still says it outputs SQL or SQL procedure parameters
- delete and place aggregate again
- aggregate outputs json-schema for template

**Comment by gashcrumb** [comment]
Yep, looked into it.  Fixing this may not be trivial.  Currently when the editor refreshes data shapes for split/aggregate it sends each step individually to the backend, I don't think there's enough context for the backend to figure out that there needs to be a data shape change with the provided parameters, for example if the integration hadn't been saved after adding the template step the backend wouldn't then know about the template step.

So currently the backend returns the finish step for the descriptor request:

![image](https://user-images.githubusercontent.com/351660/54284715-d3992f80-4576-11e9-96db-1095990130a2.png)

@christophd thoughts?  The only way I could see fixing this properly is for the UI to provide the whole array of steps whenever there's changes like this to the integration, but this kinda seems like a big change to try and force in now.

@heiko-braun might need to release note this one for 7.3.

**Comment by christophd** [comment]
I think there is not need to save the integration first because UI provides the data shapes to the backend based on the up-to-date integration flow. I think we have to search for the answer by having a look at the template step data shapes and why these are not sent to the backend.

Maybe the data shape lookup has to be triggered once more by clicking on the aggregate step?

**Comment by christophd** [comment]
The data shape descriptor lookup on the backend is only using the provided input and output shape in that request. there is not reference to the whole integration and its saved state at the moment

**Comment by gashcrumb** [comment]
Yeah, I'm wondering if I'm misinterpreting the behaviour here, let me poke at the relevant areas with a stick for awhile, it occurred to me that the aggregate step should be discovering the template step's data shape before requesting.

**Comment by mmuzikar** [comment]
Aggregate correctly updates it's datashape now, verified.

**Comment by tplevko** [comment]
Was already verified. Closing.
