### ISSUE TITLE
Starting an integration fails occasionally with SIGSEGV due to missing prometheus config

### ISSUE THREAD

**Issue by asmigala** [syndesisio/syndesis#4867]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When publishing an integration, it sometimes fails to start after successful build with the following error:
```
Starting the Java application using /opt/run-java/run-java.sh ...
exec java -javaagent:/opt/jolokia/jolokia.jar=config=/opt/jolokia/etc/jolokia.properties -javaagent:/opt/prometheus/jmx_prometheus_javaagent.jar=9779:/tmp/src/prometheus-config.yml -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:+ExitOnOutOfMemoryError -cp . -jar /deployments/project-0.1-SNAPSHOT.jar
OpenJDK 64-Bit Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of parallel GC threads appropriately using -XX:ParallelGCThreads=N
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.io.FileNotFoundException: /tmp/src/prometheus-config.yml (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileReader.<init>(FileReader.java:72)
	at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxCollector.<init>(JmxCollector.java:74)
	at io.prometheus.jmx.shaded.io.prometheus.jmx.JavaAgent.premain(JavaAgent.java:47)
	... 6 more
FATAL ERROR in native method: processing of -javaagent failed
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fbb5b0e4a47, pid=1, tid=0x00007fbb5bed5700
#
# JRE version: OpenJDK Runtime Environment (8.0_191-b12) (build 1.8.0_191-b12)
# Java VM: OpenJDK 64-Bit Server VM (25.191-b12 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libc.so.6+0x37a47]  abort+0x297
#
# Core dump written. Default location: /deployments/core or core.1
#
# An error report file with more information is saved as:
# /deployments/hs_err_pid1.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp 
#
[error occurred during error reporting , id 0xb]
```

**Comment by heiko-braun** [comment]
@asmigala Any idea how to reproduce it? Can you describe: the environment, integration, etc ?

**Comment by heiko-braun** [comment]
@syndesisio/backend Is anyone volunteerting?

**Comment by asmigala** [comment]
@heiko-braun the integration is just a super simple API Provider integration with a single implemented flow, running in my local minishift. Will keep an eye on it, but I got it once yesterday and now twice today, no idea right now what could trigger it.

**Comment by tmielke** [comment]
I seem to see this consistently as well with one integration but not with another.
My integration also starts with an API provider and then tries to produce to Kudu server and fails to start with this error.
I created another integration that only uses an API provider but that runs fine...

**Comment by heiko-braun** [comment]
@lburgazzoli @zregvart Does this ring a bell?

**Comment by lburgazzoli** [comment]
Only that I did experienced it in the past

**Comment by christophd** [comment]
I had a look at this and I suppose that there is an error while the integration project is built. This error leads to a corrupted/incomplete integration tar binary sent to the s2i image. The s2i starts and files are missing because of the incomplete integration runtime.

@tmielke @asmigala you should see errors in the server pod when this happens. Most likely the integration json could not be read for some reason. It would be good to have this information in order to find out what exactly caused the integration runtime build to fail.

Do we have an integration export that reproduces this error?

@syndesisio/backend we should find a way to not just log the errors while building the integration project tar in https://github.com/syndesisio/syndesis/blob/master/app/integration/project-generator/src/main/java/io/syndesis/integration/project/generator/ProjectGenerator.java#L275

Any ideas how we could notify the UI about errors here and how to abort the integration publishing in that case?

**Comment by zregvart** [comment]
We could convert that `Runnable` to `Callable` to propagate the exception.

For notifying the UI we should set the `IntegrationDeployment`s state to `IntegrationDeploymentState.Error`.

Either way we should not submit the build if we can't generate all required files for it.

**Comment by asmigala** [comment]
So I think I finally managed to unwrap what is going on (thanks @zregvart and @mkralik3 ):

As @christophd said, the main cause is that a file does not get included when building the integration tar.
This happens because of #4840 , leading to https://github.com/syndesisio/syndesis/blob/master/app/integration/project-generator/src/main/java/io/syndesis/integration/project/generator/ProjectGenerator.java#L289 to throw an exception and not adding the rest of the necessary files.

This would normally fail during the integration build, as it would not be able to find the required artifacts without settings.xml. This was originally reported as #4864 , because we believed there was something wrong with the repositories.

However, in my attempts to workaround #4864, I overrode the default maven repo to point to our nexus, leading to the build passing and then the integration failing because of the missing prometheus-config.yml file, which in turn lead to the SIGSEGV as originally reported.

**Comment by asmigala** [comment]
@christophd for an integration that reproduces the issue most of the time, see https://github.com/syndesisio/syndesis/issues/4840#issuecomment-473251219

**Comment by asmigala** [comment]
Cannot reproduce this anymore, seems the underlying issue was fixed, closing as verified
