### ISSUE TITLE
[Datamapper] Delimiter is aligned to the right

### ISSUE THREAD

**Issue by avano** [syndesisio/syndesis#4868]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
First time using transformation in the datamapper I used "," as delimiter and I was wondering why it didn't pick up the comma, then I noticed it was aligned to the right and I didn't expect that :-)

![bM4u](https://user-images.githubusercontent.com/7081216/54279541-9d1edd00-4595-11e9-8f78-418958bab984.png)

**Comment by mcoker** [comment]
@avano I've opened an issue in the atlasmap repo to investigate further

https://github.com/atlasmap/atlasmap/issues/831
