### ISSUE TITLE
Apicurito operator is not working

### ISSUE THREAD

**Issue by mmajerni** [syndesisio/syndesis#4871]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Operator from: [https://github.com/Apicurio/apicurito/tree/master/operator](https://github.com/Apicurio/apicurito/tree/master/operator)

After all the steps I have this in operator pod logs:

`
2019/03/13 13:12:51 uninstall: Failed deletion of "apicurito-9jau31jxxt0pw0rw5ap8ijd2l": deploymentconfigs.apps.openshift.io "apicurito-ui" is forbidden: User "system:serviceaccount:tmp-operator:default" cannot delete deploymentconfigs.apps.openshift.io in the namespace "tmp-operator": no RBAC policy matched

2019/03/13 13:12:51 uninstall: Failed deletion of "apicurito-9jau31jxxt0pw0rw5ap8ijd2l": imagestreams.image.openshift.io "apicurito-ui" is forbidden: User "system:serviceaccount:tmp-operator:default" cannot delete imagestreams.image.openshift.io in the namespace "tmp-operator": no RBAC policy matched
   ####
2019/03/13 13:12:51 uninstall: Failed deletion of "apicurito-9jau31jxxt0pw0rw5ap8ijd2l": routes.route.openshift.io "apicurito" is forbidden: User "system:serviceaccount:tmp-operator:default" cannot delete routes.route.openshift.io in the namespace "tmp-operator": no RBAC policy matched
time="2019-03-13T13:12:51Z" level=error msg="failed to reconcile release for apiVersion=apicur.io/v1alpha1 kind=Apicurito name=tmp-operator/apicurito: install error: release apicurito-9jau31jxxt0pw0rw5ap8ijd2l failed: deploymentconfigs.apps.openshift.io is forbidden: User \"system:serviceaccount:tmp-operator:default\" cannot create deploymentconfigs.apps.openshift.io in the namespace \"tmp-operator\": no RBAC policy matched"
`

**Comment by mmajerni** [comment]
#4154

**Comment by lgarciaaco** [comment]
[Help app operator ](https://github.com/operator-framework/helm-app-operator-kit/tree/master/helm-app-operator)used for this operator is now deprecated. I will refactor using the operator-sdk. I wonder if for next spring we decide to do this using go? A basic operator with install / delete functionalities in go should be rather easy to implement

**Comment by heiko-braun** [comment]
Mid term moving to go is a good idea, but are there other ways to make the current impl. work in short term?

**Comment by heiko-braun** [comment]
What's causing this? Is the operator missing the right priviliges?

```
 User "system:serviceaccount:tmp-operator:default" cannot delete deploymentconfigs.apps.openshift.io in the namespace "tmp-operator": no RBAC policy matched
```

**Comment by lgarciaaco** [comment]
By using the [operator-sdk for helm](https://github.com/operator-framework/operator-sdk/blob/master/doc/helm/user-guide.md) we move away from non supported helm app operator, and keep the same principles. The issue mentioned in this ticket isn't related with this though, the rbac is not being applied to the system user used but the operator

**Comment by lgarciaaco** [comment]
I should be able to fix the issue using the the the old sdk, creating a new ticket sounds good to me

**Comment by lgarciaaco** [comment]
@mmajerni the fix is merged into https://github.com/lgarciaaco/apicurito/tree/master/operator, can you please? I also moved #4154

**Comment by mmajerni** [comment]
It works now.
