### ISSUE TITLE
Show step details when clicking on it in the integration details

### ISSUE THREAD

**Issue by avano** [syndesisio/syndesis#4873]
See also **https://issues.jboss.org/browse/ENTESB-11454**

## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
I want to check how I named the queue in my integration's AMQ step, so I would like to see the details of the configured step in the integration details without going into the integration editor.
![IxQk](https://user-images.githubusercontent.com/7081216/54280718-6a2a1880-4598-11e9-85e3-d7e9ebfbc3c1.png)

When I click here on the "amq" step, it would be nice to display the configuration. Currently it takes me to the configuration of the `amq connection`

**Comment by dongniwang** [comment]
@avano - just wanted to understand a little bit more about the request, what do you mean by " the details of the configured step", what kind of information are you looking for?

**Comment by avano** [comment]
@dongniwang , here is how my integration is configured:

![fswg](https://user-images.githubusercontent.com/7081216/54429028-b0f64a80-471f-11e9-8c94-c23df32f4c48.png)
![GEZ0](https://user-images.githubusercontent.com/7081216/54429036-b6539500-471f-11e9-8a8b-1ddd1346bc63.png)
![eQxn](https://user-images.githubusercontent.com/7081216/54429041-bce20c80-471f-11e9-8152-9fd0417526ab.png)
![bMS8](https://user-images.githubusercontent.com/7081216/54429044-beabd000-471f-11e9-98e3-87777bee25e2.png)

When I'm on the integration summary page (screenshot in my initial comment), when I click on the "AMQ" for example, I'm presented with the **connection** details:

![rYVl](https://user-images.githubusercontent.com/7081216/54429046-c10e2a00-471f-11e9-8a3c-1776732870a1.png)

Where I would expect (since I'm in the context of the integration) the details how the AMQ step is configured in the current integration, in other words this information:

```
Publish messages:
destination: myqueue
destination type: Queue
persistent: no
datashape: specified datashape
```

The same could be for the SQL connector

```
Periodic invocation:
SQL Statement: Select * FROM Contact
Period: 10 seconds
datashape: default datashape of the SQL connector
```

Optionally it could also display some condensed mapping specified, something like:

```
Mapping:
[].last_name -> message
```

One option would be when I click the "AMQ" it would bring me to the integration editor with the AMQ step where I can review the details.
Better option would be to review this information without going into the editor.

Would that make sense? If not, feel free to close it :-)

**Comment by dongniwang** [comment]
Yes, it makes sense. And we're always interested in gathering feedback and improving the experience. Thanks for sharing @avano  

@lboehling is working on this https://github.com/syndesisio/syndesis/issues/4767 right now, she can certainly explore some design options with the feedback. 

@heiko-braun - I see you marked it for 7.4, I'm not positive that this will go in for 7.4. Let's discuss further. Thanks! 

cc: @syndesisio/uxd

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11454**
