### ISSUE TITLE
Inconsistent descriptions for SQL connector

### ISSUE THREAD

**Issue by avano** [syndesisio/syndesis#4878]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When selecting SQL connector action, it states:

```
Periodically invoke SQL to obtain, store, update, or delete data.
```

When I click on it, it brings me to the query configuration where the description is:

```
Enter a SQL statement that starts with SELECT.
```

This doesn't match the previous screen.

Also the validator states more methods when entering some invalid query:

```
Your statement is invalid and should start with INSERT, UPDATE, SELECT or DELETE.
```

**Comment by zregvart** [comment]
I think @TovaCohen might help us with this one.

**Comment by TovaCohen** [comment]
I think I corrected this: 
https://github.com/syndesisio/syndesis/pull/5684

**Comment by zregvart** [comment]
Thanks @TovaCohen, let's mark this as done.

**Comment by avano** [comment]
@TovaCohen @zregvart it seems that I failed to explain the point in the description :-) my main point was the bit that says `Enter a SQL statement that starts with SELECT.` - in the current react ui there is a tooltip that says something similar:

![sql](https://user-images.githubusercontent.com/7081216/59328415-a29ed700-8cec-11e9-8e89-209aaa8c2d3d.png)

The `SELECT` statement isn't the only one that can return something, for example you can have: `DELETE FROM CONTACT WHERE first_name = 'Joe' RETURNING last_name` that results in:

```
{"exchange":"i-Lh9N5TBJdqOxOYWs6Yqz","status":"begin"}
{"exchange":"i-Lh9N5TBJdqOxOYWs6Yqz","step":"-Lh9MltHLTBhZJpO-N2G","id":"i-Lh9N5UFJdqOxOYWs6Yrz","duration":11632212}
{"exchange":"i-Lh9N5TBJdqOxOYWs6Yqz","step":"-Lh9Lu1HLTBhZJpO-N2F","id":"i-Lh9N5hFJdqOxOYWs6Ytz","message":"Body: [[{\"last_name\":\"Jackson\"}]] "}
2019-06-12 06:29:21.678  INFO 1 --- [r://integration] -Lh9LaxnLTBhZJpO-N2F                     : Body: [[{"last_name":"Jackson"}]] 
{"exchange":"i-Lh9N5TBJdqOxOYWs6Yqz","step":"-Lh9Lu1HLTBhZJpO-N2F","id":"i-Lh9N5hFJdqOxOYWs6Ytz","duration":319050255}
{"exchange":"i-Lh9N5TBJdqOxOYWs6Yqz","status":"done","failed":false}

```

**Comment by zregvart** [comment]
@avano ah, I get it, so this is about the label description here:

https://github.com/syndesisio/syndesis/blob/25f4d4759b7828682752f9f6774d25f57033bbd9/app/connector/sql/src/main/resources/META-INF/syndesis/connector/sql.json#L70

Would something simply removing the `SELECT` from that help in your view?

Something like: "SQL statement to be executed."

**Comment by avano** [comment]
@zregvart there was another label in the old ui that disappeared in the react one, so yeah, currently the issue is with the hint. Removing `select` looks ok to me

**Comment by zregvart** [comment]
I think we need a new issue for displaying the `description` property in the React UI (I've created #5689)

**Comment by tplevko** [comment]
Verified
