### ISSUE TITLE
HTTP 404 being returned for /api/v1beta1/extensions

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#489]
After cleaning up my minishift instance and reinstalling via a local build I'm getting a 404 response for `/api/v1beta1/extensions` as well as `/api/v1beta1/swagger.json`.  The `Extension` definition shows up in `/api/v1/swagger.json` as well as some of the new API connector APIs so I'm fairly confident I'm running against my local build.

No error in the rest pod log, am wondering if the oauth proxy config changed to cause this perhaps?

**Comment by gashcrumb** [comment]
nothing interesting in the oauth proxy pod log either...

**Comment by dsimansk** [comment]
@gashcrumb can you check with these two [env vars](https://github.com/syndesisio/syndesis/issues/416#issuecomment-346313366).

**Comment by gashcrumb** [comment]
Ah, of course.  So I vote these should be enabled by default at this point
:-)

**Comment by lburgazzoli** [comment]
@rhuss 

should we make tech extension enabled by default and move the api to standard v1 path instead of v1beta1 ?

**Comment by gashcrumb** [comment]
There's no toggle in the UI so I don't see the point at this stage in hiding it.

**Comment by gashcrumb** [comment]
@lburgazzoli BTW if you happen to change the API path in a PR would you mind updating this path -> https://github.com/syndesisio/syndesis/blob/master/ui/src/app/store/extension/extension.service.ts#L12, it should be a matter of removing the `../v1/beta1/` bit in the first argument.

**Comment by rhuss** [comment]
> should we make tech extension enabled by default and move the api to standard v1 path instead of v1beta1 ?

@lburgazzoli yes, I think we should move them to v1 as the will be enabled for sure in the next release.

**Comment by lburgazzoli** [comment]
@nicolaferraro can you take care of removing feature toggles and v1beta1 ?

**Comment by nicolaferraro** [comment]
Sure, I think it's time to do it.
