### ISSUE TITLE
Unable to resolve REST service endpoints - /oauth/sign_in and /oauth/callback

### ISSUE THREAD

**Issue by honghuac** [syndesisio/syndesis#490]
I am managed to install syndesis using OpenShift App template [`syndesis-dev-restricted.yml`](https://raw.githubusercontent.com/syndesisio/syndesis-openshift-templates/master/syndesis-dev-restricted.yml) 

Attempting to sign into the [OpenShift OAuth Proxy](https://rhhong.apps.dev.openshift.opentlc.com/oauth/sign_in) of  Syndesis fails for me, resulting in this [page](https://rhhong.apps.dev.openshift.opentlc.com/oauth/callback).

Clearly, the REST service endpoints for the /oauth/sign_in URI is not defined, how should this service be defined?
 
What is the specific OAuth2 authorization code flow that is used?

**Comment by zregvart** [comment]
@honghuac there is a great comment by @paoloantinori on this in https://github.com/syndesisio/syndesis/issues/99#issuecomment-348017381 perhaps it would help

**Comment by honghuac** [comment]
@zregvart Thank you!!
