### ISSUE TITLE
Add SA to syndesis-ui and a build SA.

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#4901]
A dedicated SA should be attached to syndesis-ui. This should be either an already existing SA or a specific SA for syndesis-ui. This is required for attaching pull secrets later on.

**Comment by rhuss** [comment]
Also in the template a SA for the build should be added.

**Comment by rhuss** [comment]
Adding SA are two steps:

* Add the ServiceAccount in a template-template file in `install/gen`
* Add a `serviceAccount:` filed to the syndesis-ui DeploymentConfig in the templates

**Comment by lgarciaaco** [comment]
Shared service account, create a default with minimal permissions except for syndesis-server

**Comment by avano** [comment]
works ok with 1.6.3
