### ISSUE TITLE
Allow for authenticated S2I builds of the integration runtimes

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#4902]
If pull authentication is enabled, the S2I build for the runtimes need to be able to pull the s2i builder image with authentication.

This is supposed to work with these alternative solutions:

* Add a SA to the "Build" or "BuildConfig" object, which is linked to the secret used for authentication. However it seems that this doesn't work right now.
* Add pull secret to the BuildConfig created in https://github.com/syndesisio/syndesis/blob/ba937b8043a18a90019b5b354f19ff3b10ae033b/app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftServiceImpl.java#L314-L325

The later approach seems to work (as @avano tested this), but it would require massive changes in the operator and installation scripts. We should strive to get the first solution running, as this allows to switch on authentication on the outside. The SA configured there should be also empowered by install_ocp.sh as described in #4900 .

**Comment by heiko-braun** [comment]
@astefanutti If In understand the comments in https://github.com/syndesisio/syndesis/issues/4900#issuecomment-473936723 correctly, the `builder` can be linked and it works?

**Comment by astefanutti** [comment]
@heiko-braun your understanding is correct. Note that the operator will require write permission on service account resources but that is alright IMO.

**Comment by astefanutti** [comment]
It should be fixed with #4951. I've tested the fix by checking the `builder` service account do have the image pull secret linked and mounted. It should ideally be tested against a registry requiring authentication.

**Comment by heiko-braun** [comment]
Thanks for the quick turn around @astefanutti

**Comment by avano** [comment]
works ok with 1.6.3
