### ISSUE TITLE
Add update steps to add ServiceAccounts

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#4903]
Related to #4901 , the update scripts need to add the missing SAs and the serviceAccount: fields during the update from 7.2 to 7.3 if authentication enabled.
The update should check whether a secret "syndesis-pull-secret" exists, and if so, link it to a list of SAs via 'oc' in the shell script. This step needs to be idempotent and should be a no-op if the link already exists.

# Changes made to 1.6
I don't exactly know how the update works, but in 1.6 we added theses changes, across a number of components (install scripts, operator, templates)

- a pull secret has been added, called `syndesis-pull-secret`
- a new `syndesis-default` SA has been introduced in 7.3
- `syndesis-operator` and others need to link to `syndesis-pull-secret` with `--for-pull`
- the default `builder` SA needs to to link to `syndesis-pull-secret` *without* `--for-pull`

**Comment by avano** [comment]
looks ok
