### ISSUE TITLE
Clicking a split step defined in the integration causes flickers

### ISSUE THREAD

**Issue by avano** [syndesisio/syndesis#4908]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Clicking a split step already defined in the integration causes flickers as it probably tries to open the configuration, but obviously it doesn't have any.

![out](https://user-images.githubusercontent.com/7081216/54430184-097b1700-4723-11e9-8f5f-626b750fd071.gif)

the same happens with aggregate

**Comment by gashcrumb** [comment]
That's exactly it.  I guess I could add a metadata item to these kinds of steps that they don't have configuration which could then avoid this.

**Comment by tplevko** [comment]
not present in the new UI
