### ISSUE TITLE
API Connector does not save any change with warnings

### ISSUE THREAD

**Issue by mmajerni** [syndesisio/syndesis#4910]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Upload an OpenAPI file, click to edit it. Make some "good" changes and one with some warning. E.g. create one operation with a response but do not fill description -> warning shows. Click on Save button. The current step is previous (Upload OpenAPI Document ) with an error similar to:
![warnn](https://user-images.githubusercontent.com/22192892/54428621-53adc980-471e-11e9-8f33-cb7cb205268a.png)

Now you cannot click on the Next button. 
Problem is when I make a lot of changes but one has a warning, not an error in apicurito I will lose all changes.

**Comment by asmigala** [comment]
Still happening on 1.7.9:

![apicurio-save-with-error](https://user-images.githubusercontent.com/9480152/60955640-8dc05e00-a301-11e9-921a-37c78e7f9ecd.gif)

I'd consider this a blocker, since it loses all user progress in the apicurito editor, @heiko-braun  @gaughan what do you think?

**Comment by zregvart** [comment]
@asmigala can you provide the OpenAPI document, from the screenshot it seems that there are 59 warnings in Apicurio, I'm guessing Apicurio is a bit lenient on errors than Syndesis is. The error displayed looks like the OpenAPI document violates the JSON schema for OpenAPI 2.0.

**Comment by asmigala** [comment]
@zregvart it's this file: https://github.com/syndesisio/syndesis-qe/blob/master/ui-tests/src/test/resources/swagger/connectors/invalid/kie-server-swagger.json

After uploading this, I do the following steps: 
1. click the Review/Edit button
2. add a new path using the plus button
3. add a new operation for the path by clicking the Add Operation button
4. add a response to the operation by clicking the Add a response link and Add in the modal
5. Click save in apicurito (without filling any response details)

**Comment by zregvart** [comment]
I'm getting:

![Screenshot_2019-07-10 Review Actions - Syndesis](https://user-images.githubusercontent.com/1306050/60963884-4e4e3d80-a312-11e9-9b01-4b4e2faef0d5.png)

Sounds like this will be fixed with #6101

**Comment by riccardo-forina** [comment]
Yup, tested it with #6115 and you can't click next doing the same steps @asmigala 	described.

**Comment by asmigala** [comment]
@zregvart @riccardo-forina that's awesome. Just to make sure we are on the same page, this issue is regarding API Connector, while the other one is about API Provider. Is that same fix going to work for both?

**Comment by zregvart** [comment]
Right, good that you've checked @asmigala , both me and @riccardo-forina thought it was about API provider :smile:

**Comment by riccardo-forina** [comment]
oops! I'll check it there too :D

**Comment by riccardo-forina** [comment]
Ok, now it's fixed also for the API Connectors

**Comment by asmigala** [comment]
Still needs QE verification, reopened
