### ISSUE TITLE
Filters/Sorts have dropdowns with only one option

### ISSUE THREAD

**Issue by avano** [syndesisio/syndesis#4911]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Filters/Sorts have dropdowns with only one option, so it probably doesn't make sense to have the dropdowns, wdyt?

In the integration for example:
- in "Choose a step" page
- in for example SQL connector, where I can filter the actions I can use

![U91n](https://user-images.githubusercontent.com/7081216/54430752-d3d72d80-4724-11e9-97db-257da24a3970.png)

**Comment by gashcrumb** [comment]
We probably need issues/direction to say what other fields can be used for filtering/sorting on a given page I guess.
