### ISSUE TITLE
Invoking metadata endpoints for non dynamic actions

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#4914]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

In API provider integrations I noticed that we invoke `/api/v1/connections/api-provider/actions/io.syndesis:api-provider-start` and `/api/v1/connections/api-provider/actions/io.syndesis:api-provider-end` endpoints -- the action metadata. For actions that are not tagged with `dynamic`. The generated integration already contains the shapes based on the OpenAPI specification and invoking the action metadata endpoint for them will yield `any` data shape as that's what the connector descriptor defines.

## Expected behavior

Invoking action metadata endpoint only for actions tagged with `dynamic`.

## Tasks involved / Steps to Reproduce

1. Create API provider integration based on the [TODO OpenAPI](https://todo-syndesis-staging.b6ff.rh-idev.openshiftapps.com/swagger.json)
2. While implementing one of the flows notice the invocations of `/api/v1/connections/api-provider/actions/io.syndesis:api-provider-start` and `/api/v1/connections/api-provider/actions/io.syndesis:api-provider-end` endpoints

**Comment by gashcrumb** [comment]
Should be easy enough to fix, those are done [here](https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/integration/edit-page/current-flow.service.ts#L658-L667).

**Comment by mastepan** [comment]
@gashcrumb please keep this open for the QE be able to track and verify. Thanks

**Comment by mastepan** [comment]
@gashcrumb I got back to this. Is there anything that QE should check? Or can we add ignore/QE label?

**Comment by tplevko** [comment]
This is related to the old UI, so not really relevant anymore. Closing with QE_ignore
