### ISSUE TITLE
Cancel button cancels the whole integration when adding a middle step

### ISSUE THREAD

**Issue by avano** [syndesisio/syndesis#4924]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
@gashcrumb on latest master I can see the exact issue as described in #4610, the cancel button exits the integration editor where I would expect to cancel only the add step page. When I want to cancel adding a middle step, I need to first select some step and then hit the cancel button

**Comment by gashcrumb** [comment]
Can you screenshot which page(s)?

**Comment by avano** [comment]
sorry, forgot to include the gif :-)
![out](https://user-images.githubusercontent.com/7081216/54523147-19873680-496f-11e9-8b17-14079e1e4492.gif)

**Comment by gashcrumb** [comment]
Yeah, I tried it here too, this is on staging right now (firefox) I get the same with chrome too:

![Peek 2019-03-18 12-12](https://user-images.githubusercontent.com/351660/54545135-74249080-4977-11e9-9938-4eceebf7efcc.gif)

Browser cache maybe?

**Comment by avano** [comment]
@gashcrumb I still can see it in both chrome and firefox with cleared caches, I'll try to ask around if I'm the problem :-)

**Comment by gashcrumb** [comment]
Hopefully the UI image is building ok etc, these kinds of things make me nervous ;-)

**Comment by tplevko** [comment]
@gashcrumb works the same way as in the  @avano's case also for me on the newest master

**Comment by riccardo-forina** [comment]
This is not relevant anymore with the React UI. Shall we close it?

**Comment by tplevko** [comment]
It works as expected in the new UI, closing this.
