### ISSUE TITLE
Add AMQ connection causes error in UI

### ISSUE THREAD

**Issue by christophd** [syndesisio/syndesis#4933]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
![Bildschirmfoto 2019-03-18 um 14 31 56](https://user-images.githubusercontent.com/195264/54533580-d2a73a00-498a-11e9-9a3b-80360f6a09c9.png)

Steps to reproduce: Add AMQ connection as finish connection

Most likely related to https://github.com/syndesisio/syndesis/issues/4914 when step action has no tags defined. AMQ connector provides no tags and is just an example.

**Comment by gashcrumb** [comment]
Just for the record, these are the kind of inconsistencies that make me go crazy :-)

**Comment by zregvart** [comment]
Though ActiveMQ connector does not support dynamic metadata and doesn't advertise its support for it (not tagged with dynamic), as far as I can see.

**Comment by gashcrumb** [comment]
Yeah, no, it's because the `tags` property isn't sent then altogether.

**Comment by gashcrumb** [comment]
@christophd see you have a commit fixing this, I'll assign it to you, thanks for that!

**Comment by zregvart** [comment]
One good thing is that we have [connector-schema.json](https://github.com/syndesisio/syndesis/blob/e0270ae1de9c84cd48032663a94d62e86a625a7d/app/connector/support/maven-plugin/src/main/resources/connector-schema.json) and tooling (thanks to @phantomjinx), and we can refine the schema to be even more exact, and we can develop further tooling to check for discrepancies between connector schema, backend model (= swagger spec) and UI model.

**Comment by zregvart** [comment]
Created #4941 so chime in with ideas there...

**Comment by avano** [comment]
works ok now
