### ISSUE TITLE
Two "Log" cards appear when the user has to choose a step

### ISSUE THREAD

**Issue by TovaCohen** [syndesisio/syndesis#4935]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

For 7.3, the user now sees two Log cards but has no way to know which card to click. Something must change for 7.3.  See related issue: 
https://github.com/syndesisio/syndesis/issues/4425

**Comment by gashcrumb** [comment]
Yeah, I've kinda been hoping somebody could provide some direction on this, originally I was told the log step could be removed, then I learned that in fact it does something different to the log connection and so here we are :-)

**Comment by christophd** [comment]
AFAIU separation between log step and log connection was done because we had a limitation that only connections can be used as a finishing step in an integration.

We do not have this limitation anymore that is why both step and connection are offered to the user.

I see the log step doing a logging in a format that enables the activity logging so UI can display the log events as activity. I see log connection just doing a log to the integration runtime console without any connection to the activity logging.

Log connection is subject to be removed in upcoming release so I guess we can now hide the log connection from list of available connections/steps so the user can only choose log step from now on.

**Comment by heiko-braun** [comment]
Why don't we remove the log connection right away? It seems to create more confusion than it helps. @gaughan Any objections if we remove log connection in this release?

@christophd What would it take to remove the log connection? Any side efects?

**Comment by gaughan** [comment]
I think keep as is for 7.3 (blockers only) right?

**Comment by TovaCohen** [comment]
This is what the user sees in 7.3. I'm sure we can do better in the time remaining. 
![image](https://user-images.githubusercontent.com/25067106/54539614-d88e2280-496c-11e9-9ea0-e89ba6fe6aff.png)

**Comment by christophd** [comment]
@heiko-braun in case we remove the log connection we need to provide a db migration for all existing or imported integrations to use the log step instead.

**Comment by gashcrumb** [comment]
Maybe the log connection could be the `stdout` connection, or the `System.out.println` or `printf` or I dunno, you know?

**Comment by gashcrumb** [comment]
Actually, I *could* kinda hide it on the frontend side so the user can no longer choose it as a connection, however it'd still be there for any integration that has it already configured, then we can figure out the migration and removal for the next release.

**Comment by gashcrumb** [comment]
@heiko-braun ^^^^^^

**Comment by heiko-braun** [comment]
@gashcrumb THat's what I had in mind as well. Some kind of blacklisting, so that it cannot be added to newly designed integrations

**Comment by gashcrumb** [comment]
Cool, I'll add in support so that we can just mark a connection as hidden via it's connector definition for future cases, much like we have already for the connections list page, and explicitly ensure the log connection isn't shown just to be sure.

**Comment by TovaCohen** [comment]
For integrations that were published before 7.3 and that contain a log connection, I assume that such integrations continue to run after an infrastructure upgrade to 7.3 and after I republish an integration without editing it. I just want my integration to use the newer libraries and resources. In these two situations, integrations continue to run, right?

Suppose I upgrade to 7.3 and I want to edit one of these integrations, do I have to remove the log connection? 

Should we recommend removal of the log connection and replacement with the log step?

For the release notes, how's this:

In this release, you can add a log step as an integration's finish connection, as well as in the middle of an execution flow. Log connections are no longer available to be added to integrations.

Is that enough information for the release notes?

**Comment by christophd** [comment]
@TovaCohen afaik we only removed the log connection form the list of available steps/connections that a user can add to the integration. Running/importing old integrations that make use of the log connection should just work. You should also be able to edit log connections and republish. So no need to remove/replace the log connections manually from a user perspective.

> Should we recommend removal of the log connection and replacement with the log step?

Not needed in my opinion

I think the release notes are fine the way you suggested and I think we can remove the log connection chapter then from the docs saying you should be using Log step instead.

**Comment by tplevko** [comment]
There is only one Log now. Verified by QE.
