### ISSUE TITLE
Dict points to wrong version in 1.6.x

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/syndesis#4937]
https://github.com/syndesisio/syndesis/blob/1.6.x/app/ui/src/assets/dictionary/en-GB.json#L332 refers to 7.2, but it should use 7.3 instead

**Comment by heiko-braun** [comment]
@gashcrumb Can you tackle this and verify the change?

**Comment by zregvart** [comment]
My bad, I've marked #4922 as backported and it wasn't.

**Comment by zregvart** [comment]
I'll backport it then...

**Comment by zregvart** [comment]
Fixed via #4942

**Comment by gashcrumb** [comment]
Thanks @zregvart!
