### ISSUE TITLE
Remove masthead background image 

### ISSUE THREAD

**Issue by dongniwang** [syndesisio/syndesis#4953]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
[x] UI update
</code></pre>

## Description
Need to remove the masthead background image per latest conversation. Please make sure there's no background image for both the upstream version and the productized version. 

<img width="1435" alt="Screen Shot 2019-03-18 at 1 17 05 PM" src="https://user-images.githubusercontent.com/24943812/54549363-4b54c900-4980-11e9-9023-b827730779fb.png">
 
cc: @amysueg @mcoker @seanforyou23 @gashcrumb

**Comment by gashcrumb** [comment]
Does this need to get into 7.3?  @heiko-braun FYI

**Comment by dongniwang** [comment]
I want to say yes. @amysueg @catrobson - can you please verify?

**Comment by dongniwang** [comment]
OK. Just confirmed, yes it needs to get into 7.3. 

cc: @amysueg @catrobson

**Comment by heiko-braun** [comment]
@gashcrumb Can you backport the change when we get the PR?

**Comment by gashcrumb** [comment]
Yup!

**Comment by tplevko** [comment]
@gashcrumb the image was removed, however the top of the page now has two shades of gray
![colour_of_header](https://user-images.githubusercontent.com/4180208/54990448-0ef61e00-4fbb-11e9-8f2d-22f21c002992.png)

This is how it looked with Fuse Onlien 7.2.:
![top_fuse_online](https://user-images.githubusercontent.com/4180208/54990477-203f2a80-4fbb-11e9-81d4-1622054a263a.png)

Just want to ask, whether the lighter gray is there on purpose, or it's just an accident.

**Comment by gashcrumb** [comment]
I'm not sure tbh, @dongniwang @seanforyou23 should it be the two shades like that or a single color at the top?

**Comment by dongniwang** [comment]
Adding @mcoker here to help clarify. 

cc: @syndesisio/uxd

**Comment by seanforyou23** [comment]
Ah, shouldn't be two shades of grey. We fixed this in master yesterday, does it also need to go into `1.6.x` branch?

**Comment by mcoker** [comment]
Looks OK to me on master. This was merged yesterday https://github.com/syndesisio/syndesis/pull/5049

<img width="512" alt="Screen Shot 2019-03-26 at 9 31 57 AM" src="https://user-images.githubusercontent.com/35148959/55005550-31337000-4faa-11e9-96f1-090065222d2e.png">
<img width="1602" alt="Screen Shot 2019-03-26 at 9 31 51 AM" src="https://user-images.githubusercontent.com/35148959/55005552-31cc0680-4faa-11e9-9c60-2490407be885.png">

**Comment by gashcrumb** [comment]
Okay cool, that PR was backported to 1.6.x as well.  I wonder if staging hasn't been rebuilt since this PR was merged, as it shows up with two tones on there:

![image](https://user-images.githubusercontent.com/351660/55006182-b8d1ac80-4fb3-11e9-87b5-a191d48484e8.png)

That's on firefox in case that makes a difference.

**Comment by tplevko** [comment]
Verified by QE
