### ISSUE TITLE
flag --create-lock should just create the lock and exit.

### ISSUE THREAD

**Issue by iocanel** [syndesisio/syndesis#496]

**Comment by zregvart** [comment]
Unless I'm mistaken we decided on not using locking in the end, so this can be closed.

**Comment by iocanel** [comment]
The `not use locking` thing was something that could only work using Jenkins. Since we now use circleci we have and we do use locking.

**Comment by iocanel** [comment]
@zregvart: fyi ^

Still not sure if this issue is still relevant so let's leave it as is for now.

**Comment by zregvart** [comment]
@iocanel I suggest that we reopen once we know that locking is needed, as far as I understand right now we're not locking on CircleCI, that is: for system tests we use `system-test-{build-no}` namespace.
