### ISSUE TITLE
datamapper editor does not appear

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#4960]
## This is a...

<pre><code>
[ ] Feature request
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

After updating to latest master UI, I'm experiencing the following issue when doing an integration from Telegram to Telegram:

![telegram2telegram](https://user-images.githubusercontent.com/1868933/54582828-7687f880-4a12-11e9-8e0d-459544985b1b.gif)

This does not happen when doing other integrations such as DB to DB. 
The same behaviour can be observed on staging.

I do not know if this applies to 1.6 too.

**Comment by heiko-braun** [comment]
@gashcrumb Would you mind to take a look and see if you can reproduce it?

**Comment by asmigala** [comment]
I can also reproduce in latest master (any integration)

**Comment by gashcrumb** [comment]
Yup, can see it as well here, looking into it!

**Comment by gashcrumb** [comment]
Hmm, no errors and it appears to get through all the initialization code correctly according to the debugger.  Great!  :-)

**Comment by gashcrumb** [comment]
@igarashitm if you've some time today I might need a second pair of eyes on this one, reproducer I'm using: [test4-export.zip](https://github.com/syndesisio/syndesis/files/2982865/test4-export.zip)

**Comment by christophd** [comment]
@gashcrumb @igarashitm I occasionally see this error in browser. Maybe this rings a bell?

![Bildschirmfoto 2019-03-19 um 14 42 06](https://user-images.githubusercontent.com/195264/54610405-3f870680-4a55-11e9-99d6-07a73d281dc7.png)

**Comment by gashcrumb** [comment]
@igarashitm When test4-export.zip works, this one breaks -> [test1-export (1).zip](https://github.com/syndesisio/syndesis/files/2984756/test1-export.1.zip)

**Comment by tplevko** [comment]
Verified by QE
