### ISSUE TITLE
fuse-online-install scripts need to link pull-secrets for initial pull of operator image

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/syndesis#4965]
For the initial pull (operator image), the scripts in fuse-online-install need to link the operator SA to the pull secret.  This requires the pull secret to be created in the first place .

All of the following should be driven from `install_ocp.sh`:

1) Creation of pull secret

```
oc create secret docker-registry syndesis-pull-secret \
        --docker-server=registry.redhat.io \
        --docker-username=<user> \
        --docker-password=<pass> \
        --docker-email=<email>
```

2) Linkage to service account 

```
oc secrets link syndesis-operator syndesis-pull-secret --for=pull
```

**Comment by heiko-braun** [comment]
@lgarciaaco FYI https://github.com/syndesisio/fuse-online-install/pull/70

**Comment by avano** [comment]
@heiko-braun I tried it and looks ok, can I close this one or is there anything else needed?

**Comment by heiko-braun** [comment]
@lgarciaaco can you move it to done when the work on the scripts is finished?

**Comment by heiko-braun** [comment]
@lgarciaaco the scripts in fuse-online-install carry flags for installing the camel k operator  (optional) can you make sure that the same pull secret is linked for the camel k operator? I think with this in place we can close this issue.

**Comment by lgarciaaco** [comment]
@heiko-braun is it possible to update to 1.6 AND include camel k?

**Comment by lgarciaaco** [comment]
Ok I am assuming it is possible, if not script wont break. Can someone review + merge?

**Comment by heiko-braun** [comment]
I am not surebwhat you mean. The flag to install camel k should be in fuse-online-install already. @rhuss added it

**Comment by lgarciaaco** [comment]
Fixes https://github.com/syndesisio/syndesis/issues/4945

**Comment by avano** [comment]
@heiko-braun this seems to be missing in `1.6.x` branch in fuse-online-install, it is in master only
