### ISSUE TITLE
Can't add any step/connection to the integration after trying to add the Aggregate step

### ISSUE THREAD

**Issue by mastepan** [syndesisio/syndesis#4969]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Steps to reproduce
1. start creating a new integration
2. select start and finish connections
3. add Split step between them
4. if you try to select the Aggregate step, it fails and any other step/connection can't be selected

Only refreshing the browser tab brings back the possibility of selecting the steps but the Aggregate step still can't be clicked otherwise it causes the same problem again.

![syndesis](https://user-images.githubusercontent.com/8707251/54598635-38ea9600-4a39-11e9-8ca4-51a73aa7dd19.gif)

**Comment by gashcrumb** [comment]
I guess this is mostly because log there doesn't have a data shape.  Perhaps the aggregate step shouldn't be available then.

**Comment by mastepan** [comment]
@gashcrumb you're probably right. If I try that with **DB->Split->Aggregate->GoogleSheets** integration, everything works.

**Comment by christophd** [comment]
@gashcrumb @mastepan I have found the issue providing a PR soonish. 

This happens when no step subsequent to aggregate provides a proper input shape. This has been handled before but was lost on the road of latest changes. I think we should handle that and provide the aggregate step as just logging the aggregated collection makes sense to me.

**Comment by tplevko** [comment]
@christophd @heiko-braun is it possible to sneak this fix also in 1.6. branch?

**Comment by heiko-braun** [comment]
@tplevko All blocking issues need to be backported

**Comment by mastepan** [comment]
verified
