### ISSUE TITLE
Imported integration with extension does not import the extension

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#4981]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
I created a simple integration 
Timer -> OpenAPI connector -> Script Extension -> Log
Exported it, manually deleted all connections, OpenAPI specifications and extensions. The OpenAPI connector gets imported while importing the integration, but the integration gets imported with empty step instead of the Script extension, although the .jar file is present in the exported file ZIP.

**Comment by heiko-braun** [comment]
@gaughan Do you think this classifies for `p0`?

**Comment by gaughan** [comment]
yes

**Comment by dhirajsb** [comment]
@mmuzikar can you attach the test export zip you created? It will be help easily recreate this issue.

**Comment by mmuzikar** [comment]
Sure, here you are :smile: 

[todo-test-export.zip](https://github.com/syndesisio/syndesis/files/2989090/todo-test-export.zip)

**Comment by dhirajsb** [comment]
I tried importing it the first time and it imported the script correctly:
![image](https://user-images.githubusercontent.com/181691/54713507-0362ad00-4b0c-11e9-9048-76deb0e5b859.png)

**Comment by dhirajsb** [comment]
When I tried re-importing the same integration after deleting the integration, connection, API spec and extension, I am able to reproduce the missing step issue:
![image](https://user-images.githubusercontent.com/181691/54713816-c2b76380-4b0c-11e9-911a-267104624b72.png)

**Comment by dhirajsb** [comment]
@mmuzikar PR #5012 should fix this issue. You can test it off the PR branch if you like. 
@heiko-braun I've added the `backport 1.6.x` label as well.

**Comment by dhirajsb** [comment]
@mmuzikar please close this issue after verifying.

**Comment by mmuzikar** [comment]
Extension are now imported, thanks @dhirajsb
