### ISSUE TITLE
Understand the camel-mail component

### ISSUE THREAD

**Issue by phantomjinx** [syndesisio/syndesis#4989]
The camel-mail component is available at instructions on its settings are [here](https://camel.apache.org/mail.html) (old version) and [here](https://github.com/apache/camel/blob/master/docs/components/modules/ROOT/pages/mail-component.adoc) (github master).

**Comment by phantomjinx** [comment]
The camel-mail component combines 6 different email protocols: imap(s), pop3(s), smtp(s). The latter protocol, smtp(s), is for sending, while the others are receiving. This presents an interesting usecase:

When creating a connection, one typically enters a hostname, a port, some credentials then clicks validate. Behind the scenes, a connection is made to the server testing connectivity and confirming the settings are correct. For most of the syndesis connectors this is straightforward since only a single hostname:port are required. However, in the case of email, it depends on the protocol concerned, ie. an imap server is a different beast to an smtp server and they are offered on different port numbers. Therefore if offering an email connection, part of the validation process requires the user to choose the protocol so that the server can be validated correctly.

Unfortunately, this breaks a tradition of connections being universal to either Start or Finish points in integrations, since an imap connector cannot be a Finish connection any more than an smtp connector be a Start connection. However, there is no filtering offered in the UI (and no metadata specified in the connectors) to indicate a connector is only a Start connection or Finish connection. A workaround has been identified to place validation checks in the MetadataRetrieval code, where if a connector is placed in the wrong location then (a couple of steps on in the wizard) an error is thrown back to the UI, eg. _"the connector chosen has the wrong protocol for this step."_ This works but is less satisfactory than disallowing the user from selecting the 'wrong' connector in the first place.

The connector can certainly be broken into 3 different connectors, ie. imap, pop3, smtp. However, this just means it becomes more obvious that the user is selecting the wrong connector without denying them the ability. Therefore,
- should a change be made to offer metadata stating a connector's preferred position?
- specify a callback offering the same metadata allowing code to determine same?
- filtering should occur either in the UI or in the backend that observes the metadata and filters the connections that appear in the integration step wizard?

@heiko-braun
@oscerd
@lburgazzoli
@gashcrumb 
@anyonelse-who-feels-they-could-offer-a-useful-viewpoint

**Comment by oscerd** [comment]
I believe it's just a matter of from/to pattern. If someone select the wrong connector, it won't be possible to use it as from if it doesn't contain a from action and same for the others. It's always better to have a 1-to-1 relation with camel components, than having custom mechanisms to achieve an all-in-one connector. But this is just my PoV

**Comment by phantomjinx** [comment]
@oscerd 
Sure thing. I think 3 separate connectors is the way to go rather than all-in-one. However, the from/to pattern just moves the logical dead end forward a step (currently at the metadata receiving point). Still think it better to not allow selection of connector at all.
