### ISSUE TITLE
Documentation links lead to 404 page

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#5000]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
All the documentation links at least in release 1.6.2 lead to 404 page. I feel like on master the same thing happened but can't switch versions right now.

**Comment by heiko-braun** [comment]
Does it take you to fuse 7.3? That isn't published yet.

**Comment by mmuzikar** [comment]
Yes it does, so are we just waiting for it to be published?

**Comment by mmuzikar** [comment]
Docs have been up for a while closing this issue.
