### ISSUE TITLE
Error creating new API connector: Please check your sorting arguments

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis#5002]
## This is a...

<pre><code>
[X] Bug report  
</code></pre>

## Expected behavior
That the api imports.

## Screenshot
![Syndesis](https://user-images.githubusercontent.com/103255/54694229-49187900-4afe-11e9-9757-266489ee6833.jpg)

## Request and Response Data
Tried to import this API:

[Machine History.json.txt](https://github.com/syndesisio/syndesis/files/2988758/Machine.History.json.txt)

**Comment by zregvart** [comment]
@chirino can you check if your version includes the fix for #4486

**Comment by heiko-braun** [comment]
Closing as duplicate of  #4486
