### ISSUE TITLE
Add ui commands to `syndesis` wrapper scripts

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#5006]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Be good to finally bake in the various UI tasks we currently run directly with `yarn` into the `syndesis` script.  Especially if we can get a standard set of commands that would also be applicable for the react port.

@zregvart @christophd any good examples I could work from you could point me to would be appreciated :-)

**Comment by zregvart** [comment]
It's all shell script, so brace yourself.

Adding a new command is adding a script to `tools/bin/commands`.

They should have `$cmd::description`, `$cmd::usage` and `$cmd::run` functions.

For example `tools/bin/commands/ui`

```shell
#!/bin/bash

ui::description() {
    echo "Syndesis UI developer tools"
}

ui::usage() {
    cat <<"EOT"
    --serve       Serve the UI on localhost:9090
EOT
}

ui::run() {
    if [ $(hasflag --serve) ]; then
        echo Serving UI on...
    fi
}
```

You can include a bunch of stuff from `tools/bin/commands/util`, most useful are things in `common_funcs` already included from `syndesis` script (`hasflag`, `check_error`). You can include other script with `source "$(basedir)/commands/util/other script"` (I think).

The idea is that the utility functions return value via `stdout` like:

```shell
utility_fn() {
    if [ "$x" -gt "$y"]; then
        echo "ERROR: x is greater than y"
    fi
    echo "result"
}
```

The convention is to return `ERROR: message` for errors so they can be checked via:

```shell
local result=$(utility_fn)
check_error $result
```

**Comment by gashcrumb** [comment]
Awesome, thanks!
