### ISSUE TITLE
Cannot use predicates other than '=' in Invoke SQL step's WHERE clause

### ISSUE THREAD

**Issue by asmigala** [syndesisio/syndesis#5016]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When creating a PostgresDB - Invoke SQL step, the following statements work:
```
select * from todo where id = :#id
select * from todo where id between 1 and 100
select * from todo where id is null
```
but these cause an error:
```
select * from todo where id < :#id
select * from todo where id > :#id
select * from todo where id != :#id
select * from todo where id between :#id and 100
```
The error in the UI is `Invalid SQL, the number of columns (0) should match the number of number of input parameters (1). Unable to fetch and process metadata `. 

There's also an error in the developer console, but that might be due to #5015:
```"Http failure response for https://syndesis.my-minishift.syndesis.io/api/v1/connections/5/actions/sql-connector: 400 Bad Request"```

![image](https://user-images.githubusercontent.com/9480152/54740767-965b2000-4bbc-11e9-9524-a840b7592b17.png)

**Comment by gashcrumb** [comment]
Naw, the dev console error is expected as we're getting back an HTTP 400 response, nothing to do with #5015

**Comment by asmigala** [comment]
It is now possible to use predicates in the forms I mentioned above, however, the following (and similar) still cause the same issue:
```
select * from todo where :#id < id
```

**Comment by christophd** [comment]
@asmigala is that a valid SQL query? I doubt that you can switch predicate operands that way in SQL

I think you just have to use

`select * from todo where id > :#id`

This works perfectly fine

**Comment by asmigala** [comment]
@christophd that is indeed a perfectly valid SQL. 

Here's a couple more examples of valid queries that do not validate in Syndesis:
```
select * from todo where (id+1) < :#id
select * from todo where id in (0, :#id)
select * from todo where id = floor(:#id)
```

**Comment by christophd** [comment]
@asmigala thanks, nice examples.

not sure if this in particular is a p0 though and should go into this release. I suppose to open another issue with lower prio and tackle this for next releases.

**Comment by asmigala** [comment]
@christophd 
also 
```
select * from todo where id = (:#param1 + :#param2)
```

I expect there to be many others as well. I think that the best course of action would be using a proper SQL parser, but understand there's no way we could do that for the current release.

**Comment by heiko-braun** [comment]
@asmigala can we create an enhancement request and close this one (or lower the prio).

**Comment by KurtStam** [comment]
@asmigala please open a new issue and assign it to me please. I'm currently refactoring this code anyway.

**Comment by tplevko** [comment]
@christophd @heiko-braun There was a feature request created https://github.com/syndesisio/syndesis/issues/5084. Do you think this particular issue should be closed and we can follow up on the feature request?

**Comment by heiko-braun** [comment]
Yes, i dont think it should be blocking the release

**Comment by asmigala** [comment]
Setting to verified with CR1 as the original issue was resolved and the newly found problems are not considered blocking.

**Comment by asmigala** [comment]
And stay closed :D

**Comment by heiko-braun** [comment]
sorry @asmigala the bot seems to have issues, but I didn't find the time to look into it yet
