### ISSUE TITLE
Unable to process a collection POSTed to an API Provider

### ISSUE THREAD

**Issue by asmigala** [syndesisio/syndesis#5017]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When implementing an API which accepts an array of a particular type, it's impossible to process that data in a meaningful way in the API Provider integration, because a split step splits the collection items themselves into (key: value) pairs. 

This is caused by #4862 (and you can find more details there), reporting as a separate issue because it makes it impossible to implement some APIs in API Provider.

**Comment by heiko-braun** [comment]
>  it's impossible to process that data in a meaningful way in the API Provider integration

@asmigala Can you outline possible scenarios how you wold like to process collections? One or two example would help others to understand what you try to achieve.

**Comment by asmigala** [comment]
@heiko-braun the simplest example using our todo API is being able to post a bunch of tasks and have them inserted into a database. The idea is that you would create an operation that accepts Array of Task (this is possible in apicurito), then in the flow, add a split step to get each of the Tasks. After that, an Invoke SQL with `insert into todo (id, task, complete) values (:#id, :#task, :#completed)`.

The problem is that after the split, what I'm getting is not e.g. `{"id": 1, "task": "task1", "completed": 0}`, but rather `{"id": 1}` and then (a separate invocation of the SQL step) `{"task":"task1"}` etc.

**Comment by heiko-braun** [comment]
@asmigala Thanks for the explanation, I now see what you mean.

**Comment by asmigala** [comment]
The issue is still present in 1.6.4.

I'm now getting 
```
org.apache.camel.RuntimeExchangeException: Cannot find key [id] in message body or headers to use when setting named parameter in query [INSERT INTO todo (id, completed, task) VALUES (:?id, :?completed, :?task)] on the exchange: Exchange[i-Lb3ggNjv4h_QK4HUhkFz]
```

even though I have the mapping set up.

Attaching a sample integration.

[TODO Integration-export.zip](https://github.com/syndesisio/syndesis/files/3018427/TODO.Integration-export.zip)

**Comment by christophd** [comment]
@asmigala can you please double check the mapping by going back to the mapper and open the mapping in the editor? I have had this error the other day and it turned out that my mapping was incomplete (I also was sure to have had done the mapping before but it was incomplete)

**Comment by asmigala** [comment]
@christophd 
![image](https://user-images.githubusercontent.com/9480152/55174848-81fbc200-517e-11e9-946d-fda1491a8bac.png)

**Comment by christophd** [comment]
@asmigala ok, thanks for the double check

**Comment by christophd** [comment]
I see some errors in the server log:
```
com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `com.fasterxml.jackson.databind.jsonFormatVisitors.JsonValueFormat` from String "int64": value not one of declared Enum instance names: [color, regex, date-time, utc-millisec, date, host-name, style, email, ipv6, uri, ip-address, phone, time]
--
  | at [Source: (String)"{"$schema":"http://json-schema.org/schema#","type":"object","$id":"io:syndesis:wrapped","properties":{"body":{"type":"array","items":{"type":"object","properties":{"id":{"format":"int64","title":"Task  ID","description":"Unique task identifier","type":"integer"},"task":{"title":"The task","description":"Task line","type":"string"},"completed":{"title":"Task completition status","description":"0 - ongoing, 1 - completed","maximum":1,"minimum":0,"type":"integer"}}}}}}"; line: 1, column: 252] (through reference chain: com.fasterxml.jackson.module.jsonSchema.types.ObjectSchema["properties"]->java.util.LinkedHashMap["body"]->com.fasterxml.jackson.module.jsonSchema.types.ArraySchema["items"]->com.fasterxml.jackson.module.jsonSchema.types.ObjectSchema["properties"]->java.util.LinkedHashMap["id"]->com.fasterxml.jackson.module.jsonSchema.types.IntegerSchema["format"])
```

Seems like the syndesis server can not handle this specification:

```
{"id":{"format":"int64","title":"Task  ID","description":"Unique task identifier","type":"integer"}
```

This is because of the `int64` format. 

@zregvart any ideas why this is?

**Comment by christophd** [comment]
If I go back and revisit the type definitions to not use `int64` but plain integer it starts to work out. I had to redo all the mappings, too.

![Bildschirmfoto 2019-03-28 um 20 07 25](https://user-images.githubusercontent.com/195264/55185972-ccd50400-5195-11e9-9785-23b7056f7426.png)

**Comment by christophd** [comment]
I did some further investigations and it seems that OpenAPI and JSON Schema diverge in functionality. That causes the Json schema parser to fail when the Open API spec uses incompatible bits.

@zregvart I think this is something we need to take care of in API provider when json schema is created from Open API specification. Any thoughts?

**Comment by christophd** [comment]
I came up with a solution for the unsupported data formats in #5087 @zregvart can you please have a look

**Comment by christophd** [comment]
FYI I found this article that describes the divergence in OpenAPI and Json schema: https://philsturgeon.uk/api/2018/03/30/openapi-and-json-schema-divergence/

**Comment by zregvart** [comment]
Good work on this everyone :+1:

**Comment by asmigala** [comment]
Verified with 1.6.6
