### ISSUE TITLE
No indication a flow needs to be updated when editing API definition

### ISSUE THREAD

**Issue by asmigala** [syndesisio/syndesis#5018]
See also **https://issues.jboss.org/browse/ENTESB-11451**

## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
After editing an operation that's already implemented in an API Provider integration, there's no indication on the Operation List page that the flow needs to be updated.

## Steps to reproduce
1. create an API Provider integration with a flow that requires a data mapping
2. edit the operation so that the data mapping would not be valid (e.g. change the return type)
3. save the API definition
4. no indication that the mapping is no longer valid

**Comment by asmigala** [comment]
We cannot determine whether this is still an issue due to #6099, removing the stale label

**Comment by dongniwang** [comment]
Just following up on the latest of this issue. Seems like #6099 is closed now, anything we need from UX to move this forward? 

cc: @asmigala @heiko-braun

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11451**
