### ISSUE TITLE
Error in data mapper when editing an API Provider flow which changed due to API definition change

### ISSUE THREAD

**Issue by asmigala** [syndesisio/syndesis#5019]
See also **https://issues.jboss.org/browse/ENTESB-11434**

## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
In an API Provider integration, after changing the return type of an operation that's already implemented, trying to update the data mapping causes the following error:
```
Data Mapper UI Initialization Error: Could not load document 'i-LaUfMv856-V-nkQhsB7z': undefined undefined 
```
![image](https://user-images.githubusercontent.com/9480152/54748810-ffe62900-4bd2-11e9-9779-ac2f9bd549fe.png)

## Steps to reproduce:
1. create an API Provider integration with a flow that requires a data mapping
1. edit the operation so that the data mapping would not be valid (e.g. change the return type)
1. save the API definition
1. open the appropriate flow, notice a warning badge on the result
1. open the data mapper to change the mapping, the above error is shown

**Comment by heiko-braun** [comment]
> edit the operation so that the data mapping would not be valid (e.g. change the return type)

@asmigala Do you mean changing the OpenAPI defintion?

**Comment by heiko-braun** [comment]
Is there a workaround?

**Comment by asmigala** [comment]
@heiko-braun yes, changing the OpenAPI definition.

As a workaround, the user can delete the data mapper step and add a new one in its place.

**Comment by heiko-braun** [comment]
@gaughan Considering the workaround (see https://github.com/syndesisio/syndesis/issues/5019#issuecomment-475196561), I am tempted to make this a `p1`. What do you think?

**Comment by asmigala** [comment]
@heiko-braun I'd be perfectly ok with leaving this as-is for 7.3 if API Provider was still Tech Preview.

**Comment by gashcrumb** [comment]
It's really the same situation as when you go and change a connection on either side of the data mapper and render it's existing mappings invalid.  Maybe what we should do in these cases is just change the messaging from what's shown to something like "Invalid mappings have been detected and removed" :-)

**Comment by gaughan** [comment]
+1 on the messaging change

**Comment by asmigala** [comment]
@gashcrumb do you mean that only the message would change and the user would still need to delete the step and create a new one, or that the data mapper ui would load without any mappings and show an error message that the existing mappings had to be removed?

Both options are much better than the current state, but the second one is of course preferable.

**Comment by gashcrumb** [comment]
Yeah, I think the latter option is more ideal as well for really any case like there where the the integration has changed such that the mapper has a stale reference to a removed step, as is the case here.

@igarashitm what do you think?

**Comment by igarashitm** [comment]
+1

It requires some enhancement in AtlasMap though, instead of error out, remove the mappings which refers to no-longer-exist fields, and then show documents those are available. It should hapeen as a part of initialization process.

**Comment by gashcrumb** [comment]
I think that'd be the most pragmatic approach at this stage if it's low risk.

**Comment by igarashitm** [comment]
If we do this in this sprint, I feel it's a bit risky, as my 6th sense says that it's big change enough to introduce some regressions. But I think @pleacu's sense is more accurate in this area.

**Comment by heiko-braun** [comment]
Can we introduce an improved message (handling the situation gracefully)?

**Comment by igarashitm** [comment]
While Paul is looking at the code, I'm thinking about the better error message...
`Invalid document '<name> (<id>)' is detected`, where `<name>` is going to be like `5 - SQL Result`, and id is still Step ID. Or we shouldn't show Document ID(= Step ID in Syndesis) at all? it's required for debugging though.

**Comment by gashcrumb** [comment]
I think that'd be fine, @TovaCohen what do you think?

If you have more technical info that'd help debugging you could always output that to the js console as a last resort.  But I think your suggestion is the right direction for sure.

**Comment by asmigala** [comment]
I'd definitely include a message for the user explaining that this happened because they changed something and is not just a random error, and also that they should delete the mapper step and create it again.

**Comment by igarashitm** [comment]
@asmigala problem is that the `Step` is Syndesis term and It's only a `Document` in AtlasMap.

**Comment by igarashitm** [comment]
It turned out the Document name like `5 - SQL Result` is no longer available at that time, since it's coming from DataShape. If original DataShape is not provided, then only avaiable info here is Document ID = Step ID.
So all we can do is
`Invalid document has been detected [<docID>]`

**Comment by pleacu** [comment]
@igarashitm and I have worked though the issues here and we both believe that the UI can get to a point that a warning is correctly issued and the AtlasMap UI continues but we are not convinced the generated atlasmap mappings XML is correct (looks suspicious).  Since we don't want a runtime failure with potential garbage in the mappings XML - it's better that we make the user redo their AtlasMap step - that's the safest at this point.  We can address this in 7.4.

**Comment by igarashitm** [comment]
@pleacu you forgot to mention your idea, so it's better describing in user doc or release note about this error message, and say "remove Data Mapper step and add it again for now, we're gonna improve it in next release".

**Comment by TovaCohen** [comment]
In the 7.3 user doc, is this what I need to add:

While you are editing an operation flow, you might edit the OpenAPI document that defines that operation and then return to editing the operation's flow. In the unlikely event that your edit causes a data mapping error, Syndesis/Fuse Online displays an `Invalid document has been detected` message. If you see this message, delete the data mapper step that has the message, and add a new data mapper step.

**Comment by asmigala** [comment]
@TovaCohen I would not say the event is unlikely, you'll get this error any time you change the reponse type.

**Comment by pleacu** [comment]
Hey @TovaCohen - I guess I'd make it a little less specific.  The error will occur if the user modifies the data shape that contains a mapped field as well as the OpenAPi document scenario you describe.  Maybe some like:

If you see the following error message diagnostics coming from the Data Mapper step:
'Could not load document ...` or 'Could not find document for mapped field` it indicates that you have changed the data shape where you have specified a mapping.  You should remove and reimplement the data mapper step.

**Comment by pleacu** [comment]
Hey Tova -
        Seems fine - I added the second error text because that's what I
would search for if I ran into this issue.

ref: Could not find document for mapped field 'last_name' at URI
atlas:json:-LaX4LMC1CfVJYp3JXM6

Thanks!
        --Paul

**Comment by TovaCohen** [comment]
Thanks Paul! @asmigala let me know what you think.

**Comment by pleacu** [comment]
+1   looks good - thanks Tova.

**Comment by asmigala** [comment]
Cannot determine whether still present due to #5697, unmarking as stale

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11434**
