### ISSUE TITLE
Integrations - Basic filter step: allow to remove 1st contition

### ISSUE THREAD

**Issue by mastepan** [syndesisio/syndesis#502]
Allow to remove 1st condition if there is more than 1.
A User can fill many conditions and then he realizes that the 1st one is not needed. He can't simply remove it now.
![basicfilterdeletefirstrow](https://user-images.githubusercontent.com/8707251/33381223-aac8f90c-d51d-11e7-82d5-914877978b36.png)

**Comment by gashcrumb** [comment]
@seanforyou23 @michael-coker this'd be a good one...

**Comment by michael-coker** [comment]
The UI for the page is pretty bad in Chrome, and could be improved (vertical align row) in Firefox

![screen shot 2018-03-20 at 9 27 56 am](https://user-images.githubusercontent.com/35148959/37660816-4bd502aa-2c21-11e8-991c-4618fdf22b99.png)
![screen shot 2018-03-20 at 9 29 31 am](https://user-images.githubusercontent.com/35148959/37660817-4bf02eae-2c21-11e8-9ba2-d1a4b07f4e22.png)

**Comment by gashcrumb** [comment]
That's strange, it hasn't looked like that for me here :-/ unless something's crept in that's changed things...

In any case @michael-coker you should raise a new issue for it rather than lumping a new issue on top of this existing one.
