### ISSUE TITLE
Unable to use fetches a record from Salesforce by external id

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#5022]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

I created a simple integration that does:

    db -> split -> datamapper -> salesforce -> log

with the aim of retrieving an object from Salesforce using a contact from the contact table (sampledb) but the integration fails for a number of reasons:

- atlasmap is not able to istantiate the object that the salesforce connector expects (SalesforceIdentifier)
- salesforce connector does not check for the message body for being of the expected type and tries to convert it to the expected type as it were a string

**Comment by gaughan** [comment]
Does occur without split?
Is it a regression?
Does it block your demo?

**Comment by lburgazzoli** [comment]
Yes it appears to happen with or without the split and it seems a regression but I haven't used the component for a while
