### ISSUE TITLE
Twitter search action can't have multiple keywords

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#5029]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
The keywords tooltip (and keyword on its own being plural) hints at keywords taking a comma separated list of keywords, but if you specify keywords like that, the Twitter connection does not produce any outputs. 
I have created a simple integration which searches twitter for keyword test, and then modified it to be looking for a list of keywords like this: 
![image](https://user-images.githubusercontent.com/46345469/54823075-034ae480-4ca7-11e9-875b-d04b655a7da0.png)
The first version produced output every 5 seconds but the second version does not produce any output as you can see here: 
![image](https://user-images.githubusercontent.com/46345469/54823128-28d7ee00-4ca7-11e9-8985-97af8474b15b.png)

**Comment by claudio4j** [comment]
The comma is not a valid character separator for multiple keywords, the camel-twitter component and syndesis documentation should be fixed to say the multiple keyword search should use the [twitter search standard operators](https://developer.twitter.com/en/docs/tweets/search/guides/standard-operators).

Examples of valid queries:
* `investiments AND cryptocurrency`
* `investiments -bitcoin`
* `(fuse online) AND salesforce`

For syndesis I could locate only (doc/connecting/topics/p_adding-twitter-connections.adoc) to update  and link to twitter search operators.

**Comment by TovaCohen** [comment]
I have this Jira to update the doc: https://issues.jboss.org/browse/FUSEDOC-3238

**Comment by mmuzikar** [comment]
@claudio4j I don't see the new tooltip on my end (see screenshot), is this intentional? Also would a link for more information be possible? [https://developer.twitter.com/en/docs/tweets/rules-and-filtering/overview/standard-operators.html](https://developer.twitter.com/en/docs/tweets/rules-and-filtering/overview/standard-operators.html) this one leads straight to the table overview of all operators possible (which I assume we support all). 
![image](https://user-images.githubusercontent.com/46345469/59826381-7f040e00-9336-11e9-9b1f-d16321d0ba49.png)

**Comment by claudio4j** [comment]
@mmuzikar Tova changed the tooltip as requested in https://github.com/syndesisio/syndesis/pull/5759#issuecomment-502665711

**Comment by mmuzikar** [comment]
Oh, OK I see, anyway I am satisfied with it being in the documentation, because describing all the search operators would make the tooltip not a tooltip anymore but a whole new page.
Considering just functionality this can be closed and with examples in the documentation, I can be happy to close it.
