### ISSUE TITLE
[UX] Visualize steps in disabled state

### ISSUE THREAD

**Issue by christophd** [syndesisio/syndesis#5031]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Based on the position in an integration and due to some other conditions some steps are temporarily not valid to be added by the user. For instance this can be an aggregate or filter step that is not valid at the moment.

These steps are removed from the list of available steps when the user wants to add a step.

I wonder if we generally should mark those steps as disabled instead of removing completely from the list (e.g. with light-greyed icons and a disabled pointer when hovering over such a disabled step). I personally find it confusing when well known steps totally disappear and appear from time to time. Maybe we could also give a reason tool tip saying why the step is disabled at this specific position in the integration.

**Comment by christophd** [comment]
@dongniwang FYI

**Comment by dongniwang** [comment]
Thanks @christophd. Adding @gashcrumb to this thread as I think we had talked about this at some point. 

cc: @gaughan @syndesisio/uxd
