### ISSUE TITLE
OData connector Done/Next buttons

### ISSUE THREAD

**Issue by jsafarik** [syndesisio/syndesis#5057]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Is there any reason why there should be "Done" button in OData connection Create action and "Next" button in Update/Delete action? Would be nice if this was unified.

**Comment by phantomjinx** [comment]
Hey @jsafarik, have never noticed that. Would you mind attaching a couple of screenshots as cannot exactly see where you are referring?
Am sure you know:
- 'Done' normally means end of the wizard / last step;
- 'Next' normally means there is another step.

So maybe an extra black step is being picked up from somewhere.

**Comment by jsafarik** [comment]
@phantomjinx 
Create action:
![Create_OData](https://user-images.githubusercontent.com/46523434/55076755-8351bf80-5096-11e9-92f6-b47f8bf05df0.png)
Update action (same as Delete action):
![Update_OData](https://user-images.githubusercontent.com/46523434/55076764-88167380-5096-11e9-8a1e-ccb6ab0ef6f4.png)
As you can see, Create has Done button, Update (and Delete) has Next button, all of them acts the same - it's the last step of the connection.

**Comment by gashcrumb** [comment]
TBH this is probably the same issue as reported in https://github.com/syndesisio/syndesis/issues/4458

**Comment by phantomjinx** [comment]
@gashcrumb 
Can you answer a couple of questions about this please?
1. Looking at the code, commit [0ba0c9a8](https://github.com/syndesisio/syndesis/commit/0ba0c9a85d21aa4dc816bf70f730b4a61de15934) is responsible for changing the *ngIf logic for display of either 'Next' or 'Done'. The concept of whether the action is shapeless determines which button is displayed. Can you explain why this is relevant?

2. 
- To show _Done_: shapeless == false && (page >= lastPage || !this.hasConfiguration)
- To show _Next_: shapeless == true || page < lastPage
Does _shapeless_ being true imply some kind of next step should occur after the action? Assume the shape editor page? However, this does not take into account the location of the action in the flow. For a start action with an output-shape of 'any' then makes sense but for a finish action with an output-shape of 'any' it makes no sense.

@gashcrumb 
Any recommendations?

**Comment by gashcrumb** [comment]
Yep, so shapeless actions that have a data shape of ANY will lead the user
to the "describe data" page after the action configuration screen, so the
button should show 'next'.  Otherwise if there's a type then no data shape
customization is needed, so the button shoud show 'done'.

**Comment by phantomjinx** [comment]
@gashcrumb
Thx. WDYT about the bit about location of the step. If its a finish step then surely the shape is irrelevant?

**Comment by gashcrumb** [comment]
No, the `InputDataShape` in the descriptor would be relevant.

**Comment by phantomjinx** [comment]
@gashcrumb
That's true but in this issue's case, the finish connection step is an odata producer. It has json-schema as input-shape & any as output-shape. Due to the lack of output-shape it is showing 'next' even though it is at finish. Upshot - in this configuration 'next'  is not required & clicking it gives blank screen.
