### ISSUE TITLE
Enhance OData create/update function to include ETags/headers where necessary to allow for successful operation

### ISSUE THREAD

**Issue by phantomjinx** [syndesisio/syndesis#5068]
It has been found that there are services that require ETag for data modification (this ETag can be read from headers when doing GET request for entity) and without that ETag specified it is not possible to modify the data (update or delete).

_Originally posted by @jsafarik in https://github.com/syndesisio/syndesis/issues/4889#issuecomment-476564030_

Need to retrieve ETags during metadata retrieval and add where necessary. The ODataTestServer (as implemented from odata.org's tutorials) does not have this capability so want to add option to implement this, enabling creation of unit tests that don't depend on external service.

**Comment by phantomjinx** [comment]
Reference [this comment](https://github.com/syndesisio/syndesis/issues/4889#issuecomment-475240662) too.

**Comment by phantomjinx** [comment]
The Trippin reference service does make use of ETags, especially with its Writable version (only limited use of ETags in read version) - https://services.odata.org/V4/TripPinServiceRW.

See further explanation of ETags here ->
https://www.odata.org/getting-started/basic-tutorial/#etag

**Comment by phantomjinx** [comment]
ETags are [optional](http://docs.oasis-open.org/odata/odata/v4.0/errata03/os/complete/part1-protocol/odata-v4.0-errata03-os-part1-protocol-complete.html#_Toc453752230) to client requests for edition/deletion. If the client uses an ETag in its header then it is requiring the response to honour concurrency modification checking. Should the ETag not be present in the client request headers then there is no reason for such checking to occur.

The sample odata services are not constrained by ETags although they implement them to demonstrate their optional operation. To edit the data in these services, the [unique key](https://www.odata.org/odata-services/service-usages/request-key-tutorial/) provided in the redirect of the url IS required. Therefore, if a syndesis connection should be using these reference services then the unique key should be adhered to.

**Comment by jsafarik** [comment]
@phantomjinx 
Well even though I request the key and use it in syndesis OData connection, the service still returns ETag in header - that means that it has to be included in if-match header to successfully modify data on this service.

Modifying data on service that doesn't support ETag works fine, even though I just found out that there is problem with passing string as key predicate to update (and possibly delete) action. I was testing with service taking integers as key predicate (which works ok) so found out there is problem with string just now. Issue here: [#5241](https://github.com/syndesisio/syndesis/issues/5241#issue-433969144).

**Comment by jsafarik** [comment]
[feature request](https://issues.apache.org/jira/browse/CAMEL-13598) that has to be done prior to any syndesis change so syndesis supports ETags was submitted.

**Comment by phantomjinx** [comment]
[PR](https://github.com/apache/camel/pull/3118) for upstream submitted.

**Comment by phantomjinx** [comment]
~PR for [backport](https://github.com/jboss-fuse/camel/pull/985)~

**Comment by phantomjinx** [comment]
Requires new camel build snapshot to be built and syndesis to have dependency upgraded.

**Comment by phantomjinx** [comment]
PR for camel upstream upgrade:
https://github.com/syndesisio/syndesis/pull/6735

**Comment by phantomjinx** [comment]
Upgrade complete & feature included.
