### ISSUE TITLE
Optimize daily meetings

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#507]
As a result of our retrospective, we have the feeling that our daily meetings are not feature focused and that they are not also not really suite we are more and more people.

Idea:

* Focus on features by looking at the current tasks in GitHub
* Keep daily cadence at a fixed time
* Create labels:
   - daily/monday
   - daily/tuesday
   - ...
* Attach one or more of such labels to each feature Epics.
* Each feature's task is reviewed quickly in the respective daily meeting.
* Create an IRC bot which shortly before the meeting post the features which are a talked about.
* For the daily, everyone is invited, but only the members of the 'feature team' are mandatory,

That way we are flexible in distributing features over daily standup, can easily query for which feature is spoken about on what day. And not everyone needs to attend everyday.

@syndesisio/all wdyt ? Other suggestions ?

**Comment by chirino** [comment]
I like it.

**Comment by rhuss** [comment]
I just introduced labels d/mon, d/tue, ... (d for daily and want to keep it short to not further clutter sceen estate) and going to ask all Feature owners to attach (at least 2 ;-) such labels to their Epics.

**Comment by zregvart** [comment]
Any suggestions on how to sync this with calendar? I know this will lead to some confusion initially as it requires that we keep an eye on for IRC notifications, labels and meeting link.

**Comment by rhuss** [comment]
Wouldn't this be an awesome use case for Syndesis ? A GitHub to Google Calendar integration ?

Sorry, no idea yet. Maybe we can trigger mails short before the meeting (which in turn contains an .ics) or we are talking directly to the Google Calendar API. Not sure whether this is worth the effort.

I would like to start small, just to find out whether it really works. Then we can automate.

**Comment by rhuss** [comment]
What I can do though is to add URLs to the meetings invite which directly filter on the date: E.g.
https://github.com/syndesisio/syndesis/issues/507#boards?labels=d%2Ftue&repos=106613119,105563335 for Tuesdays.

Then I would schedule 5 series of Standup Meeting containing the appropriate link to the board.

Would this help ?

**Comment by zregvart** [comment]
I think that a link might help, not 100% sure that I'll be able to remember if I was on Monday or Wednesday. Best, give it a go and see how we do.

**Comment by gashcrumb** [comment]
This was done, let's close this issue
