### ISSUE TITLE
When creating a connection, default the connection name to be the connector name.

### ISSUE THREAD

**Issue by chirino-test** [syndesisio/syndesis#5077]
## This is a...

<pre><code>
[ X] Feature request
</code></pre>

## The problem
When creating a connection, default the connection name to be the connector name.

## Screenshot
![Syndesis](https://user-images.githubusercontent.com/26656637/55152829-72b24f80-5151-11e9-8f64-68188997cb27.jpg)

**Comment by riccardo-forina** [comment]
Fixed by https://github.com/syndesisio/syndesis-react/pull/474
