### ISSUE TITLE
CI/CD tag is set for all integrations

### ISSUE THREAD

**Issue by mkralik3** [syndesisio/syndesis#5078]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
This issue exists in the last CR1 (1.6.2.fuse-730001-redhat-00001). In the master, it works.
When I add a tag in the CI/CD dialog, the tag is added to all integration. I am not able to uncheck it, only delete it from all integration. The issue looks similar (not same) as #4683 . However, all fixes from that issue look back-ported in 1.6.x .

-----------------------------------
**CR1:**
```
curl .../timer-to-log-1/tags --request PUT -d '["tag100"]'
```
The _timer-to-log-1_ contains it
```
curl .../timer-to-log-1/tags --request GET
{"tag100":{"name":"tag100","releaseTag":"i-Lb2oX1en02206AHqYm6z","lastTaggedAt":1553768521898}}
```
The _timer-to-log-2_ contains it too (but it shouldn't) however inconsistent with null
```
curl ... /timer-to-log-2/tags --request GET
{"tag100":null}
```
-----------------------------------
On the **master,** it works correctly:
```
curl .../timer-to-log-1/tags --request PUT -d '["tag100"]'
```
The _timer-to-log-1_ contains it
```
curl .../timer-to-log-1/tags --request GET
{"tag100":{"name":"tag100","releaseTag":"i-Lb2oX1en02206AHqYm6z","lastTaggedAt":1553768521898}}
```
The _timer-to-log-2_ doesn't contains it 
```
curl ... /timer-to-log-2/tags --request GET
{}
```

On the video below, on the right site is master, on the left site is 1.6.2.fuse-730001-redhat-00001.
![output](https://user-images.githubusercontent.com/16251792/55150606-c53d3d00-514c-11e9-97bd-4ec9637abe70.gif)

Lets say, that the user have three integrations (timer1, timer2, timer3) in the _environment1_.
So in case, when the user want to export some integrations (e.g. _timer1_, _timer2_) according to the particular tag, the all integrations are exported (_timer3_ too). As a workaround, the user can delete the unnecessary integrations after import .zip file in the _environment2_.
However, when they have integration with the same name on both environment (_timer3_ is in the _environment2_ before import Ing zip file, _timer1_ and _timer2_ not), and they want to export only _timer1_ and _timer2_, _timer3_ will be exported too (because a tag is set accross all integrations) and after import zip file original _timer3_ in the _environment2_ will be replace by imported _timer3_. Because of that, I marked this issue as Blocker.

**Comment by heiko-braun** [comment]
@dhirajsb would it be possible to test it against 1.6.x ?

**Comment by heiko-braun** [comment]
@mkralik3 can you test it against 1.6.4? https://github.com/syndesisio/syndesis/releases/tag/1.6.4

**Comment by mkralik3** [comment]
yes.
It works and I am not able to reproduce this issue on:
Syndesis: 1.6.4
Commit ID:  b63d10b986c34340a5332d6551800ccafb127d5c

**Comment by heiko-braun** [comment]
Thanks @mkralik3 , that’s good to know. Afaik cr1 was/is rebuild and this change should be included there

**Comment by dhirajsb** [comment]
I'll check this in an hour or so.
What does the export do? Does it actually include the untagged integration
timer3?

>
>

**Comment by mkralik3** [comment]
yes, because it is tagged. All integrations are tagged with the new tag, not only the integration which the dialog is open on. However, I am not able to reproduce it on 1.6.4, so we will see after rebuild whether this issue will be still there or not.

**Comment by dhirajsb** [comment]
Part of the confusion might have to do with the HTTP method being used for creating tags. For the UI we added support in the create tags endpoint for HTTP method PUT to completely replace all tags and PATCH to add new tags. Basically the UI uses PUT to avoid having to call DELETE on unchecked tag names. 
If you just want to add new tags, use PATCH on the endpoint, and it won't remove any existing tags that are not in the list of tag names in the body.

**Comment by dhirajsb** [comment]
The null value is also a helper feature for the UI. When the UI calls the endpoint to get tags, it gets a map with ALL names as keys, and only values for tags present on the integration in question. 
This avoids having to do two calls to get all available names, then another call to get tags on an integration and having to merge them in the UI.

**Comment by dhirajsb** [comment]
I built the latest 1.6.x branch and tested tagging with a couple of integrations. It's working as expected. Only the integration being tagged is affected when using the CI/CD menu.

**Comment by mkralik3** [comment]
When I unchecked the tag and saved the UI dialog, the PUT method was called (according to web console in a browser), so I used the same method in the command line.
However, as I described in the first comment, the same calls on the _1.6.2.fuse-730001-redhat-00001_ version behave differently as in the master. Same problem in the UI.

Anyway, on the 1.6.4 tag, they behave correctly (the same as in the master). So I expect that the issue will be gone with CR2. When I test API with that build, I will be back with a feedback.

**Comment by dhirajsb** [comment]
@mkralik3 the behavior has changed in 1.6.x branch and master. The server implementation does return a null for tag names without values in the return map, but for some reason they are not being serialized. I am looking at changes to figure out the change that caused this. 

It's not an issue right now, since it seems the UI was indeed changed to make two calls and combine list of all names with the output of GET tags map.

**Comment by heiko-braun** [comment]
@mkralik3 based on wthe information above, can we close this issue?

**Comment by mkralik3** [comment]
@dhirajsb Yes, that what you described (that UI calls only one endpoint and gets tags which are associated with the integration and others(with null), instead of calls two endpoints) are not an issue now because on the **master** and on the tag **1.6.4**, UI still calls two endpoints:
```
/integrations/<integration>/tags
/environments
```

@dhirajsb Which commit changed the behavior? Because on the latest **master** and on the tag **1.6.4**, the api ` /integrations/<integraton>/tags` returns only tags which are associated to the particular integration and the response doesn't contain another tag (with null) which are not associated to that integration.

However, this issue is about something different. On the CR1 build, I am not able to create a tag only for particular integration because the tag is added to all integrations. I am not able to remove the tag from integration which I don't want to tag. Simplified, I can only tag all integration with the tag or none.

Because of that, @heiko-braun no, we can't. 
As a user, when I tag _integration1_ with the _tag1_, the _integration2_, _integration3_, _integration4_ ... are tagged too which is not correct. And I am not able to untagged the _tag1_ from this all integration. 

However, as was mentioned before, it works correctly on **1.6.4** tag, so we need to wait for the CR2 build.

**Comment by dhirajsb** [comment]
@mkralik3 I've been looking at the service code and there isn't a way to add a tag to multiple integrations at once. 
@gashcrumb is it possible that there was a UI error in CR1 that shows all tags checked for all integrations?

**Comment by mkralik3** [comment]
@dhirajsb Maybe the UI is not able to work with the tag which has `null` value 
As I describe above, on the **master** and the **1.6.4** tag, the endpoint  `/integrations/<integration>/tags` returns only tags which are associated with the particular integration. However, on the **1.6.2.fuse-730001-redhat-00001**, the endpoint `/integrations/<integration>/tags` returns all tags (tags which are associated with the particular integration and the other tags with `null` value). 

I am just thinking what happening on **1.6.2.fuse-730001-redhat-00001** :
After open CI/CD dialog, the endpoint returns all tags, the tags which are associated with the integration on which the dialog is opened and the tags with `null` value. However, the UI cannot work with the tags with `null` value, so UI shows all tags as checked. (and when the user click on save, the other tags are added to the integration).

Still, I don't know how it is possible that rest point `/integrations/<integration>/tags` behaves differently on **1.6.2.fuse-730001-redhat-00001** in comparison with **master** and **1.6.4** tag

**Comment by dhirajsb** [comment]
@mkralik3 yeah, that's what I thought was happening too. I still haven't found the reason for it, but it's working as user expects it to. So, I guess that makes this a feature. :)

**Comment by mkralik3** [comment]
I don't think that UI works as users expect on _1.6.2.fuse-730001-redhat-00001_. 
When they tag _integration1_ with the _tag1_, I think that they don't expect that _integration2_ will be tagged too when they open CI/CD dialog on _integration2_.
In my POV, the UI works as users expect on master and 1.6.4 tag.

**Comment by heiko-braun** [comment]
If it works on 1.6.4, can we close this one?

**Comment by mkralik3** [comment]
I suggest waiting for CR2 build, just for sure that issue is gone. I will have to test it anyway, so, at the same time, I can verify and close this issue.

**Comment by mkralik3** [comment]
I am still able to reproduce it on CR2 build:

**CR2 build**,  (1.6.9.fuse-730001-redhat-00001,     87a34a54-cd2c-4c28-9de0-d2c12d2d3dfc, c6b5fbd7aaa4a00d4d8e8463edafe84c9073037a )

![output](https://user-images.githubusercontent.com/16251792/55879494-144c8e80-5b9f-11e9-9562-50afe273c018.gif)

**tag 1.6.9** ( Syndesis: 1.6.9 ;  53d6c25296df51454e12e2803fb1a4a20b82c3dc )

![output](https://user-images.githubusercontent.com/16251792/55879519-22021400-5b9f-11e9-8f7c-9bcd09cf665e.gif)

**Comment by dhirajsb** [comment]
There must be something happening in productization, perhaps a different version of jackson binding library being imported or something, which is affecting json generation and causing this issue. 

I'll need to change the backend to ensure it behaves the way we expect under all conditions. 
@heiko-braun is there a CR3 build planned?

**Comment by heiko-braun** [comment]
Yes, CR3 is planned for end of this week.

**Comment by zregvart** [comment]
Moving this to `Done`.

**Comment by mkralik3** [comment]
Verified at CR3.
