### ISSUE TITLE
Fuse Online logo is a little small

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#5079]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

From https://issues.jboss.org/browse/ENTESB-10420 the productized logo doesn't look right, or at least it's much smaller than before:

## Description
![image](https://user-images.githubusercontent.com/351660/55157703-759e4780-5133-11e9-8d4a-399633e262cf.png)

@dongniwang @mcoker @seanforyou23 Do you guys recall what size the logo was previously?

**Comment by gashcrumb** [comment]
I measured it at 310px on a screenshot and it looks alright, will run with it:

![image](https://user-images.githubusercontent.com/351660/55158877-4937fa80-5136-11e9-8584-d985c25e2c20.png)

**Comment by dongniwang** [comment]
@lboehling thought you're working on the productized logo? 

cc: @syndesisio/uxd

**Comment by lboehling** [comment]
@dongniwang I was working on the products that don't have this styling yet for pre-summit releases. https://docs.google.com/presentation/d/1nhOx4SheKFKRejtg7yHbANboeBywL7KCSvkc74UegzA/edit#slide=id.g545c8126ca_1_0 (slide 8). https://drive.google.com/drive/folders/1Cgp9mw1F4DJZsmagmUViHs5pn-TkIqYw
