### ISSUE TITLE
Fully support SQL statements in SQL Connector

### ISSUE THREAD

**Issue by asmigala** [syndesisio/syndesis#5084]
See also **https://issues.jboss.org/browse/ENTESB-11487**

## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
The SQL validator in SQL connnection currently supports a somewhat limited subset of SQL (see #5016 for examples). I suggest using a full featured SQL parser rather than trying to address each of these ad-hoc.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11487**
