### ISSUE TITLE
Can't start any integrations

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#5086]
Upgrade of spring-boot to 1.5.17 broke things

java.lang.IllegalStateException: Could not evaluate condition on org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration$EndpointWebMvcConfiguration due to org/apache/camel/spring/boot/CamelContextConfiguration not found. Make sure your own configuration does not rely on that class. This can also happen if you are @ComponentScanning a springframework package (e.g. if you put a @ComponentScan in the default package by mistake)
Caused by: java.lang.ClassNotFoundException: org.apache.camel.spring.boot.CamelContextConfiguration'

**Comment by heiko-braun** [comment]
Can you check if this also happens on 1.6.x?

**Comment by KurtStam** [comment]
Sure will do!

On Mar 29, 2019, at 14:24, Heiko Braun <notifications@github.com> wrote:

Can you check if this also happens on 1.6.x?

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/syndesisio/syndesis/issues/5086#issuecomment-477996270>,
or mute the thread

**Comment by heiko-braun** [comment]
That would be bad and require another CR. I hope its not the case

**Comment by KurtStam** [comment]
The 1.6.x branch runs ok with spring-boot 1.5.17.

**Comment by heiko-braun** [comment]
Great, thanks Kurt!

-- 
Heiko Braun

**Comment by heiko-braun** [comment]
Yhe version chnage has been rolled back
