### ISSUE TITLE
Feature design documents

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#509]
When creating a feature Epic a default issue should be created for creating the design document. For the next feature, let’s try to prototype an ‘executable’ design document.

@zregvart you mentioned "contract" (?) as a tool for this. Could you add some links, please ? Actually, I'm not even sure whether I recorded that action item properly ;-)

**Comment by zregvart** [comment]
Yeah the idea is to have a [consumer driven contract](https://martinfowler.com/articles/consumerDrivenContracts.html) and one implementation of this principle that I have experience with is [Spring Cloud Contract](https://cloud.spring.io/spring-cloud-contract/)

**Comment by gashcrumb** [comment]
this seems to have gone stale
