### ISSUE TITLE
Split step not able to handle input stream bodies

### ISSUE THREAD

**Issue by christophd** [syndesisio/syndesis#5093]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Some connectors provide input stream as message body (e.g. Http connector). Split step is not able to handle the input stream. Split step should read input stream content and try to perform split on the String content (e.g. Json array).

**Comment by christophd** [comment]
@heiko-braun I labeled that issue with p1. Can somebody maybe from @syndesisio/qe confirm this prio or if we need it to be a p0 instead?

**Comment by zregvart** [comment]
Fix in #5094 looks straightforward and there is a test for this case. Not sure if it needs to be a `p0` but I think it's safe to include it in `1.6.x`. (2c)

**Comment by christophd** [comment]
@heiko-braun should we push this to `1.6.x`? I think it is worth it.
