### ISSUE TITLE
"n/a" when uptime of integration is less than 1 minute

### ISSUE THREAD

**Issue by mkralik3** [syndesisio/syndesis#5100]
See also **https://issues.jboss.org/browse/ENTESB-11432**

## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When uptime of the integration is less than 1 minute, the UI shows n/a. That can be confusing for the users and they can think that integration is not running.
![image](https://user-images.githubusercontent.com/16251792/55345006-34999080-54af-11e9-84c0-425b55288fd8.png)

**Comment by mkralik3** [comment]
In the version 1.7.9, it shows "No Data Available"

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11432**
