### ISSUE TITLE
Exported API Connectors reference icon by db id

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#5104]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Exported API Connectors reference icon by db id but target system may not contains it, example:

```json
"connectorGroupId": "swagger-connector-template",
"description": "A damage service api used to work with damage events.",
"icon": "db:i-LbI5KTzgrJnaWjUyQ_7z",
"id": "i-LbI3csggrJnaWjUyQ_5z",
"name": "Damage Service",
```

**Comment by mastepan** [comment]
@lburgazzoli  just checking. Is there anything that should be checked by QE?
