### ISSUE TITLE
Malformed integration can be published

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#5107]
See also **https://issues.jboss.org/browse/ENTESB-11450**

## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
I am able to publish an integration which is malformed and will have errors in log and won't work. Small warning icon about data type mismatch is present but it is not enough to stop me from deploying the integration. 

We should not allow malformed integration to be published.

## Reproducer

![screenshot_20190402_124915](https://user-images.githubusercontent.com/14313995/55397143-d23f9f00-5545-11e9-9fda-6a2eb66fbc02.png)
![screenshot_20190402_124856](https://user-images.githubusercontent.com/14313995/55397144-d23f9f00-5545-11e9-9111-1dd3f03b9424.png)
![screenshot_20190402_124938](https://user-images.githubusercontent.com/14313995/55397142-d23f9f00-5545-11e9-935e-a73bb3ace110.png)
![screenshot_20190402_124948](https://user-images.githubusercontent.com/14313995/55397141-d23f9f00-5545-11e9-80a1-b6c8dcf4e916.png)

**Comment by gashcrumb** [comment]
I feel like this issue is kinda too broad and vauge to be acted upon.

Also I think we specifically decided to allow publishing even with mapping warnings as we can't definitively say that it's wrong, but I'd think the warning icon is a good indicator the integration won't work.

**Comment by mcada** [comment]
If this is accepted behavior I would expect explicit warning before publishing if we are sure to publish the integration with warnings. Because those small warning icons are easy to overlook when I have 6+ connections and add a new one in between them which breaks the integration on some other place which is exactly what happened to me and why I decided to create this issue.

**Comment by KurtStam** [comment]
I don't think we should prevent publishing because of a warning. It can be feature too.. see .i.e. https://github.com/syndesisio/syndesis-quickstarts/tree/master/kafka-2-db: the DB connector takes in 2 different datashapes (collection and single message) but atm we only support one datashape which is set to the collection but you can ignore this mismatch and publish anyway and it will work. This is why it a warning and not an error..

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11450**
