### ISSUE TITLE
Too much output and too many errors in the JavaScript console

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#511]
There are too many errors in the JavaScript console which should be probably addressed. Also, it would be awesome if could cut down the debug noise in the console, too.

**Comment by gashcrumb** [comment]
So when javascript errors creep into the console we all need to be better about raising them as actual bugs, otherwise they will never be addressed.

Same goes for debug noise, though am hoping we'll get our logging sorted soon enough that it won't be a problem too much longer.

**Comment by gashcrumb** [comment]
While working today I noticed these a *lot* in the editor -> https://github.com/syndesisio/syndesis/issues/515

**Comment by gashcrumb** [comment]
This isn't specific enough...
