### ISSUE TITLE
Discovery of 3scale APIs

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/syndesis#5112]
See also **https://issues.jboss.org/browse/ENTESB-11504**

(See also https://issues.jboss.org/browse/ENTESB-11338)

As a citizen integrator when I create an API client connector, I want to be able to access my APIs already managed by 3scale in the same namespace. 
DoD
I want to be able to browse all 'applicable' APIs (where applicable means the API is set to discoverable in 3scale)
I want to seamlessly add my API (no authentication steps required)

Stretch:
I want to be able to navigate to the API descriptions in 3scale

Discussion details shared by Andrew:

- Discover APIs managed by 3scale in the same cluster
Use k8s labels? - 3scale or customer labels them
Query 3scale via it's API (need to get a secret from the cluster...)
Search for resources in the clusters? (for CRD created ones)

- Discover (any) API in the same k8s cluster 
Use routes or labeled routes? (Need to think about wild-card routes maybe?)

- Discover 3scale managed services "anywhere"
local cluster (as above) 
other clusters? need a registry, or to know the cluster(s) to look in
3scale SaaS - query via it's API (limited to your provider via provider key)

- Discover any APIs elsewhere 
Need the central Registry of APIs and be able to query it via API...

**Comment by heiko-braun** [comment]
@gaughan Can you flesh out the details above? (i.e. acceptance criteria, more details to the user story, etc)

**Comment by gaughan** [comment]
@heiko-braun updated above

**Comment by zregvart** [comment]
We discussed with 3scale folk, the discover mechanism will be based on the citizen integrator pointing to the 3scale developer portal. There's a well known location of an OpenAPI specification there which Syndesis can use to create an API client.

**Comment by heiko-braun** [comment]
@zregvart You mean it will remain a manul step, rather than auto-discovery/wiring?

**Comment by amysueg** [comment]
@heiko-braun @gaughan In the "feature groups" doc this item has a check for UX/UI impact. Can we discuss the expectation for this in the UI? I've assumed it would be similar to API discovery in 3scale and that we would provide an "import" choice but I'm not sure where this would appear in the UI. Thoughts?

**Comment by zregvart** [comment]
> @zregvart You mean it will remain a manul step, rather than auto-discovery/wiring?

Yes, the argument being that in a multi-tenanted 3scale environment showing all tenants is not what the user expects. And that the user should be aware of the development portal, as it is the place where the user registers Syndesis as a client of the API.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11504**
