### ISSUE TITLE
Support for upgrades in APICurito operator

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/syndesis#5114]

**Comment by lgarciaaco** [comment]
@heiko-braun given the stateless nature of apicurito, do you think it is enough if the image Spec in the [CR](https://github.com/lgarciaaco/apicurio-operators/blob/master/apicurito/deploy/crds/apicur_v1alpha1_apicurito_cr.yaml#L8) is updated to a new image? Right now the operator would pick this change and trigger a deployment, I would consider this an application upgrade.

If this is not enough I need more scope on how an update for apicurito looks like

@EricWittmann mb you can shed some light

**Comment by EricWittmann** [comment]
I think you are right, @lgarciaaco in your assessment of an Apicurito upgrade.  There is no state, so an upgrade is simply deploying a more recent version of the image.  Nothing else needs to be done.

**Comment by lgarciaaco** [comment]
Alright @EricWittmann thx ...

**Comment by mmajerni** [comment]
Upgrading works fine -> closed
