### ISSUE TITLE
Operator support for upgrades

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/syndesis#5117]
See also **https://issues.jboss.org/browse/ENTESB-11503**

As a user I want to see upgrade support across all operators, so that I can install newer versions of the underlying software using an operator.

**Comment by heiko-braun** [comment]
@astefanutti Is this something you have onyour radar?

**Comment by astefanutti** [comment]
@heiko-braun yes, I'm planning to cover upgrade for the Fuse console operator first. I can help on the other operators as well.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11503**
