### ISSUE TITLE
OData connection read action as middle step

### ISSUE THREAD

**Issue by jsafarik** [syndesisio/syndesis#5129]
See also **https://issues.jboss.org/browse/ENTESB-11486**

## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Why isn't there a read action in odata connection used as middle step? Might be useful, for example reading IDs from DB -> read entities with those IDs from OData service -> ...

**Comment by phantomjinx** [comment]
@heiko-braun 
With this being a feature, do you want it held over until 7.5?

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11486**
