### ISSUE TITLE
Avoid the Camel Catalog from being used by the rest module.

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis#514]
Using the camel catalog causes downloading online artifacts via groovy grape.  This is slow and also error prone since sometimes you need to clear that grape cache.

The catalog is only used by the project generator to encode the action properties into and endpoint URI.  We should defer that so that it's done at runtime when the route is created.  This change means that the syndesis.yml format will change a bit so that it will now carry a json property map of all the action config.

**Comment by lburgazzoli** [comment]
camel-catalog is not more there
