### ISSUE TITLE
Maven POM generation doesn't take into account dependency's version

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#5140]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

When generating the Maven POM for the S2I build we're not including the specified version of a dependency, say one that has been added as a dependency to the extension descriptor.

This prevents adding a dependency not present in one of the imported BOMs and fails the integration build

This seems to be on purpose, relying on the fact that any dependency we use currently is present in one of the BOMs we import. Perhaps as a way of prohibiting version clashes.

Not sure what would be the best way of dealing with these, seems that we need to take into account all dependencies imported from the BOM and for any dependency not present in the BOM specify its version when generating the POM for the integration build.

**Comment by lburgazzoli** [comment]
As far as I remember dependencies that are not part of one of our boms should be added by the extension plugin as embedded dependency and not listed among direct dependencies of the extension

**Comment by zregvart** [comment]
@lburgazzoli that makes sense. We should probably document this better in the [Develop Fuse Online extensions](https://access.redhat.com/documentation/en-us/red_hat_fuse/7.2/html/integrating_applications_with_fuse_online/customizing_ug#developing-extensions_custom).

@TovaCohen can we add something to the documentation, I propose:

> As integration pods run in Java process with a flat classpath, to avoid version clashes make sure that the dependencies an extension uses is aligned with the imported bill of material (BOM)<sup>*</sup> from `org.springframework.boot:spring-boot-dependencies:$SPRING_BOOT_VERSION`, `org.apache.camel:camel-spring-boot-dependencies:$CAMEL_VERSION` and `io.syndesis.integration:integration-bom:$SYNDESIS_VERSION`.
> 
> Any additional dependencies that are not part of the imported BOMs need to be packaged within the extension JAR file in the `lib` directory and omitted from the `dependencies` property of the extension JSON descriptor.


<sup>*</sup> There is a difference between upstream BOMs and Red Hat BOMs that are imported, could be my mistake, our boosters are not using `fabric8-project-bom-camel-spring-boot`.

**Comment by TovaCohen** [comment]
Where in the doc do you think we need to add the note?
This is a link to the 7.2 doc for developing extensions:
https://access.redhat.com/documentation/en-us/red_hat_fuse/7.2/html/integrating_applications_with_fuse_online/customizing_ug#procedure-for-developing-extensions_extensions

In that section, step 6 says to add dependencies to the project's pom.xml file. Should this note go with that step?  If not there, where?
Thanks!
