### ISSUE TITLE
Move additional oauth proxy template to fuse-online-install

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/syndesis#5141]
Move the template [1] into the install repo and reference the produtized oauth proxy version

[1] https://github.com/syndesisio/syndesis/blob/master/install/support/syndesis-public-oauth-proxy.yml

(An interim solution until we sorted out https://issues.jboss.org/browse/ENTESB-10183)

**Comment by heiko-braun** [comment]
@TovaCohen We are moving the template and with the link in the docs need to change. @dhirajsb can supply you with the new URL.

**Comment by dhirajsb** [comment]
PRs in syndesis and fuse-online-install projects merged. Closing.
