### ISSUE TITLE
Javascript errors from ng-tour annotated elements

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#515]
I see these a lot in the editor mostly while creating an integration:

```
anchorId integrations.step already registered!
```

@kahboom is there something we can do about this?

**Comment by kahboom** [comment]
Oh... uh oh. Sorry about that.

**Comment by kahboom** [comment]
This must be because the tourAnchor is within the iterator for some reason and should not be, rather, it should be in the enclosing division or whatever its equivalent is. We don't need a tour step for every item, but I thought @deeleman had removed this already? If not, I can do that soon.

**Comment by kahboom** [comment]
Remove or possibly move it, depending on whether or not we need a tour step in that part of the app. I'll have to check again.

**Comment by gashcrumb** [comment]
Ah could be...  Also we've nested ngIfs and `syndesis-loading` stuff, dunno if that'd complicate things for the tour stuff?

**Comment by kahboom** [comment]
Should be fine, just need to check whether or not we still need a step there. If you'd like, remove it for now and I'll re-add it since I'm missing several steps anyway and need to work on that for TP3-4. The important thing is that it works and is set up properly 😂 .

**Comment by gashcrumb** [comment]
This is not applicable now...
