### ISSUE TITLE
Extra scrollbar appears when hovering on the IVP expansion bar  

### ISSUE THREAD

**Issue by dongniwang** [syndesisio/syndesis#5153]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

When creating an integration, an extra scrollbar appears when hovering on the IVP expansion bar. This behavior happens when using the staging site. 

## Expected behavior

No extra scrollbar when hovering on the expansion bar. 

## Screenshot

![wOeiD8II38](https://user-images.githubusercontent.com/24943812/55650722-82b2da80-57b4-11e9-9b64-c15b21040720.gif)

## Tasks involved / Steps to Reproduce

1. Create Integration
2. Hover on the Integration IVP expansion bar

**Comment by dongniwang** [comment]
@gashcrumb @mcoker - hey there, I'm not sure if this is the intended behavior or what's the purpose of the extra scrollbar...but it's pretty distracting when trying to use the IVP. Maybe we can think of a way to improve it?

**Comment by gashcrumb** [comment]
Yeah that's a bug for sure.  I'm not sure why the content area where it's supposed to scroll is inset so much, this is happening in a few spots that I've noticed since the masthead update, like it also happens in the integration list and the connection list pages as well.

**Comment by mcoker** [comment]
That's a weird bug. It has to do with the tooltip being positioned way off screen. This is what happens to the page when you hover the IVP and the tooltip appears.

<img width="1662" alt="Screen Shot 2019-04-05 at 5 15 16 PM" src="https://user-images.githubusercontent.com/35148959/55659262-79326e00-57c6-11e9-9bf8-224afe9ef08e.png">

The padding issues did happen with the masthead updates. Here are the connection list and integration list pages.

<img width="1662" alt="Screen Shot 2019-04-05 at 5 10 48 PM" src="https://user-images.githubusercontent.com/35148959/55659150-fdd0bc80-57c5-11e9-8a58-ffc7f635876d.png">
<img width="1662" alt="Screen Shot 2019-04-05 at 5 10 42 PM" src="https://user-images.githubusercontent.com/35148959/55659153-00331680-57c6-11e9-93b8-52f6291f6173.png">

Also note how the toolbar doesn't extend to the edges. That happens with borders that should extend to the edges, too.

<img width="1662" alt="Screen Shot 2019-04-05 at 5 10 56 PM" src="https://user-images.githubusercontent.com/35148959/55659173-222c9900-57c6-11e9-8863-906176ce65dc.png">
<img width="1662" alt="Screen Shot 2019-04-05 at 5 11 04 PM" src="https://user-images.githubusercontent.com/35148959/55659174-222c9900-57c6-11e9-8d23-67b95c0c554f.png">

**Comment by dongniwang** [comment]
Thanks for the screenshots! And that tooltip is really bizarre... @mcoker - Is this something you can help with?
