### ISSUE TITLE
Modal stays when integration no longer exists

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#5155]
See also **https://issues.jboss.org/browse/ENTESB-11431**

## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
This happens due to the delay between user calling delete on integration and the integration no longer existing in the UI. The delay is sometimes too long and it seems that nothing is happening so the user decides to press delete again; the modal shows up and in that time the integration can be already deleted.

The part of this behavior I'd call bug is that the modal stays up and the cancel and the X button don't close the window, so you have to refresh the page.
When you click on any of those button you get these errors in the console
![image](https://user-images.githubusercontent.com/46345469/55710017-f1c54480-59e9-11e9-8ba4-95157a532743.png)

**Comment by heiko-braun** [comment]
@riccardo-forina Another one we have to verify on react. Please close this issue when it's no longer relevant with the new user interface.

**Comment by gashcrumb** [comment]
I tested this on the react side against staging.  What I found is both times I deleted an integration the backend would crash.  In the react codebase this causes the error handler page to be rendered, which effectively removes the dialog that I left open from the page.

So kinda inconclusive, I think it's gonna work better but I can't say for sure.

**Comment by riccardo-forina** [comment]
It works as it should on the React UI.

**Comment by mmuzikar** [comment]
Reopening for verification

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11431**
