### ISSUE TITLE
Support insert/update of multiple rows in SQL connector

### ISSUE THREAD

**Issue by christophd** [syndesisio/syndesis#5158]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
SQL connector only supports insert and update of single rows in DB. With the new topmost collection support in data mapper we could also support prepared statements for insert/update of multiple rows with one operation.

At the moment a split step is required in front of a SQL connector in order to insert/update multiple rows.

**Comment by mmuzikar** [comment]
Verified by QE
