### ISSUE TITLE
syndesis-server: gc under pressure when UI requests integration details

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#5167]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

When UI shows an integration summary, it [fetches](https://github.com/syndesisio/syndesis/blob/master/app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationOverviewHelper.java#L89-L90) all the `IntegrationDeployment` for the given integration and because each deployment contains a snapshot of the integration for the revision, such operation is quite memory intensive and:
- can put the GC under pressure so in some case this result in a long phase so that the liveness proves reports the the application not more healthy thus openshift restarts it
- can trigger OOM

This problem is exacerbate using camle-k as back-end as deployment are quick and people may end-up amending  integrations more often.

**Comment by lburgazzoli** [comment]
It appears that this creates also pressure to `syndesis-oauthproxy` that gets killed by `OOMKiller`

**Comment by gashcrumb** [comment]
fwiw the UI only uses a couple fields from those integration deployments, so if pulling out the step/flows in the response helps go for it.

**Comment by lburgazzoli** [comment]
Yes the problem is not the UI, it is it the back-end that loads everything and then throw almost everything away

**Comment by heiko-braun** [comment]
@lburgazzoli Can we close this with the recent improvements @nicolaferraro made?

**Comment by mastepan** [comment]
@lburgazzoli anything there to be checked by QE? Or should I add ignore/QE label instead? Thanks

**Comment by lburgazzoli** [comment]
Think we can close it for now
