### ISSUE TITLE
Create a new video for API provider quickstart

### ISSUE THREAD

**Issue by TovaCohen** [syndesisio/syndesis#5172]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Documentation issue or request
</code></pre>

## Description

The video of the API Provider integration quickstart that we provided in 7.2 needs to be updated for 7.3.  Kurt says he can do this and here's the issue so it's not forgotten

**Comment by MelissaFlinn** [comment]
ne thing that I have noticed with the Task API example is that, when I import it into Fuse Online (both on my local minishift and in Integreatly), the "fix" for the Delete operator (change the response code to 200) does not work (as documented here: https://access.redhat.com/documentation/en-us/red_hat_fuse/7.2/html/integrating_applications_with_fuse_online/trigger-integrations-with-api-calls_ug#configure-publish-api-provider-quickstart_api-provider). Fuse Online wants me to add a data mapper step and when I try to do that, I get another error.

**Comment by MelissaFlinn** [comment]
Also - it would be terrific if we could provide a zip file that a user can import and just publish, without having to first edit the response codes...

**Comment by MelissaFlinn** [comment]
Please test the availability of an API's external URL in OpenShift when the CONTROLLERS_EXPOSE_VIA3SCALE=true environment variable has been set, and then changed to false. The following did not work for me and needs further testing:
1. Set CONTROLLERS_EXPOSE_VIA3SCALE=false
2. stop the openshift synsesis-server pod and then start a new pod with the config change.
3. In Fuse Online, stop and republish the API. 
I still  could not see the external URL in Fuse Online on the summary page.
I also tried deleting the CONTROLLERS_EXPOSE_VIA3SCALE variable and then #2 and 3 - still did not work.
I do not know how accurate my test environment is - so maybe it will work for you...

**Comment by MelissaFlinn** [comment]
FYI: I deleted my previous comment. Today, in my latest Integreatly workshop environment, I was able to successfully see an API's external URL in Fuse Online after changing the OpenShift CONTROLLERS_EXPOSE_VIA3SCALE environment variable from true to false. So it is working as expected there... :)

**Comment by KurtStam** [comment]
The Quickstart has been updated and includes ErrorHandling
