### ISSUE TITLE
Not able to get JSON out of JSON template

### ISSUE THREAD

**Issue by mhockelberg** [syndesisio/syndesis#5173]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Created API Provider with simple Slack integration. Posts a message to Slack user and returns the Slack message in the API response as JSON. 

Mapped the Slack message to JSON template to convert the message string to JSON. Tried to map that JSON to API response body and it returns the message string and not the message string in JSON format. 

Ping me if you need more details.

**Comment by mastepan** [comment]
@mhockelberg just checking. Is there anything that should be checked by QE?
