### ISSUE TITLE
Unable to start integration from box connector

### ISSUE THREAD

**Issue by avano** [syndesisio/syndesis#5174]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
There are currently no actions to start the integration in box connector and 2 actions to finish (upload, download).

This should be "From" I assume:
https://github.com/syndesisio/syndesis/blob/28cb62a0c74be5c58792d8aca83a2a194fdfb22a/app/connector/box/src/main/resources/META-INF/syndesis/connector/box.json#L87-L88

**Comment by heiko-braun** [comment]
//cc @tadayosi

**Comment by avano** [comment]
@oscerd mentioned that the download action should be a "To" pattern, so I'm closing this

**Comment by tadayosi** [comment]
Yes, actually this is intentionally set to `To` as unlike camel-dropbox, camel-box doesn't support consumer endpoint for downloading at this moment.
