### ISSUE TITLE
Bulk operation(s) for updating descriptors and metadata for steps

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#5181]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Currently when changes are made to the flow in the editor it fetches metadata and descriptors for steps *per step* that needs it individually.  I think a bulk operation that the editor could submit the entire step array would certainly perform better, with the single requests the editor can get more laggy the larger the integration is.

For reference these are the spots where these calls are made currently when changes to the flow are made:

The invocations
https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/integration/edit-page/current-flow.service.ts#L740

https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/integration/edit-page/current-flow.service.ts#L763

And these are triggered from [here](https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/integration/edit-page/current-flow.service.ts#L646) and [here](https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/integration/edit-page/current-flow.service.ts#L696).  It's also complicates the code a bit to have all these requests made while scanning through the step array.

@christophd FYI this'd be *really* nice for 7.4 I think.

**Comment by christophd** [comment]
@gashcrumb yes I think this is a good idea. added my name to it

**Comment by gashcrumb** [comment]
Think this is all set, isn't it?  We can close this.

**Comment by mastepan** [comment]
@gashcrumb please let the issues open for the QE to be able to track them and verify. Thanks
