### ISSUE TITLE
OData Connector Enhancements

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/syndesis#5182]

**Comment by tplevko** [comment]
@phantomjinx QE needs the issues to be in "done" state for us to get the information, it's ready for the verification and that we can start working on automated test coverage. @jsafarik could you please extend the test suite to have the new functionality covered? Once you have verified these new features, please close this issue.

**Comment by jsafarik** [comment]
Is this epic targeted for 7.4? If yes, then https://github.com/syndesisio/syndesis/issues/5068 should be removed from this list as it is blocked by [this feature request](https://issues.apache.org/jira/browse/CAMEL-13598). It seems noone is working on this, so it wont be working in 7.4 I guess.
