### ISSUE TITLE
[camel-k] AtlasMap's multi document vs InputStream

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#5184]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

I've been working on an application that requires to map the same document multiple time in the integration flow and I run into an issue because the document that I wanted to map was stored in the exchnage's message body as InputStream and the stream was consumed by a previous step.

This happens because we do copy the message a map stored as exchange property but as the body is an InputStream the first processor that consumes it, will break all the subsequent mapping.

NOTE: with camel-k backend

**Comment by lburgazzoli** [comment]
We may need to enable stream caching

**Comment by lburgazzoli** [comment]
Ok so we may have been missed porting the default config for spring-boot, see https://github.com/syndesisio/syndesis/blob/master/app/integration/project-generator/src/main/resources/io/syndesis/integration/project/generator/templates/application.properties.mustache

**Comment by valdar** [comment]
So the plan is to generally address that in `camel-k-runtime` and then enable it through configuration in CamelkPublishHandler
