### ISSUE TITLE
KNative connector for Syndesis

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/syndesis#5186]
See also **https://issues.jboss.org/browse/ENTESB-11501**

User Story:

This feature will add a Syndesis connector for Knative, to allow Syndesis to interact with Knative resources. The feature will not be enabled by default, but will be available if configured in the general syndesis configuration configmap.
It can be enabled only when syndesis is installed in a OpenShift cluster with Knative installed and only when Camel K is set as integration runtime (this should be documented).
The connector will allow to expose a integration as service or subscribe to an existing knative channel to receive cloud events. In both cases, the integration will scale down to 0 if not used and scale up automatically under huge load.
The connector can also be used to send events to other services or channels.

Acceptace Criteria:
* minimum knative version required >= 0.4

TODO

**Comment by lburgazzoli** [comment]
We should define the minimum knative version required, ideally >= 0.4

**Comment by heiko-braun** [comment]
@lburgazzoli please add it to the acceptance criteria above

**Comment by tplevko** [comment]
Just noticed there is the initial implementation of Knative connector delivered - https://github.com/syndesisio/syndesis/pull/5345
We didn't find any information regarding this connector in this topic description, or in engineering document. Would it be possible to provide a bit more information, so QE could dive into this new feature?

**Comment by nicolaferraro** [comment]
Yeah, it's something expected for 7.3+ that has landed in 7.4. I've updated the engineering document: https://docs.google.com/document/d/1xJAVaK8zXDlepPPhJZa-u0-CG9WWa39Tx8_Aj2XHyX0/edit#

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11501**
