### ISSUE TITLE
[camel-k] SyndesisHeaderStrategy not loaded into the registry

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#5189]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Some connectors requires an HeaderStrategy named syndesisHeaderStrategy to be present in the registry and it was done using spring boot before but that does not work any more in camel-k so we need to implement a similar strategy in camel-k otherwhise integration using such connector won't even start

We missed to replicate what https://github.com/syndesisio/syndesis/blob/master/app/connector/support/processor/src/main/java/io/syndesis/connector/support/processor/SyndesisHttpConfiguration.java does so we could hit `No bean could be found in the registry for: syndesisHeaderStrategy of type: org.apache.camel.spi.HeaderFilterStrategy` in case we use i.e. the http component.

**Comment by heiko-braun** [comment]
@lburgazzoli What the impact of this problem? Can you add a brief description?

**Comment by lburgazzoli** [comment]
some connectors [requires](https://github.com/syndesisio/syndesis/blob/master/app/connector/http/src/main/resources/META-INF/syndesis/connector/http4.json#L184) an HeaderStrategy named syndesisHeaderStrategy to be present in the registry and it was done using spring boot before but that does not work any more in camel-k so we need to implement a similar strategy in camel-k otherwhise integration using such connector won't even start

**Comment by heiko-braun** [comment]
which connectors are impacted?

**Comment by lburgazzoli** [comment]
http and webhook for what I can see (webhook is not supported in this release in any case)
