### ISSUE TITLE
Create an icon for AWS-SQS

### ISSUE THREAD

**Issue by oscerd** [syndesisio/syndesis#5204]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Just the icon needed for the connector

**Comment by avano** [comment]
@oscerd and this one?

**Comment by oscerd** [comment]
The icon is already in place. I created it, but I don't know if I have to put the svg or png somewhere. @zregvart can you shed some light on this?

**Comment by zregvart** [comment]
@oscerd sure, put the SVG of the icon in `ux/connections_icons/svg` modify `mapping.json` in that directory to include a block like this:

https://github.com/syndesisio/syndesis/blob/c73cc80b872cc63d0a5f15cc2ea44c89ea6aecc1/ux/connections_icons/svg/mapping.json#L166-L169

And run `yarn icons` from the same directory. This should optimize the SVG and replace the embedded version in Syndesis connector JSON descriptor.

**Comment by oscerd** [comment]
I'll do. @avano please leave this one open then

**Comment by oscerd** [comment]
This should be done @avano
