### ISSUE TITLE
No padding between toolbar and list

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#521]
@dongniwang Isn't there supposed to be some blank space above the list, not sure what happened to it:

![screen shot 2017-11-29 at 16 03 19](https://user-images.githubusercontent.com/351660/33399011-ecfbc9fc-d51e-11e7-9ecd-f54d3ca077c2.png)

**Comment by dongniwang** [comment]
Yes, that's correct. Are you using a different browser or system?

**Comment by gashcrumb** [comment]
Aha, you're right it looks normal on Chrome.  So in the above screenshot I'm using the new Firefox release there on Fedora.

**Comment by dongniwang** [comment]
Yeah, we need a plan to test the implementation against different browsers and systems...I thought we had an issue open for this?

**Comment by gashcrumb** [comment]
let's track in #2118
