### ISSUE TITLE
[conditional-flows] CBR specific activity logging

### ISSUE THREAD

**Issue by christophd** [syndesisio/syndesis#5213]
Content based router step should provide activity logging that gives some information on the matched condition and its sub-flow outcome.

Would be good to use the same activity logging in the CBR sub-flows so we have parent flow and sub-flow in one single activity log.

**Comment by mcada** [comment]
How do I know which condition passed from activity log?

![screenshot_20190627_153941](https://user-images.githubusercontent.com/14313995/60271115-0bdc3800-98f2-11e9-95f8-2f209470ce54.png)

**Comment by christophd** [comment]
@mcada is that an integration with multiple conditional flows steps that you are using?

**Comment by mcada** [comment]
Yes it is. The logging is good and it works. We just can't determine which condition was used just from activity logs.

**Comment by christophd** [comment]
@mcada agreed, the activity logs should be enhanced to reflect the matching condition (maybe as activity log output) if possible. I would like to track this in a separate issue if this is OK with you

**Comment by mcada** [comment]
Sure. In that case I am closing this one as verified.

**Comment by christophd** [comment]
thanks!
