### ISSUE TITLE
OAuth proxy image stream tag mismatch between community and prod version

### ISSUE THREAD

**Issue by avano** [syndesisio/syndesis#5225]
See also **https://issues.jboss.org/browse/ENTESB-11429**

## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
The template generator defines tags for both prod and community templates, but for the community the expected tag for oauth proxy is `v4.0.0`:

https://github.com/syndesisio/syndesis/blob/cda907377a9c6181770f895ec7d5d720117e0854/install/generator/syndesis-template.go#L112-L117

whereas for prod image the expected tag is `v1.1.0:

https://github.com/syndesisio/syndesis/blob/cda907377a9c6181770f895ec7d5d720117e0854/install/generator/syndesis-template.go#L142-L147

Probably not a big deal but it would be good to have it unified

# Related

- https://issues.jboss.org/browse/ENTESB-10377

**Comment by heiko-braun** [comment]
It will be unified once the productised 4.0 version becomes available. Please also note that 1.1.0 is misleading: The actual proxy version in prod is 3.10.45: https://github.com/syndesisio/fuse-online-install/blob/1.6.11/import_images.pl#L69

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11429**
