### ISSUE TITLE
Box - allow to map something to the fileId in box connector

### ISSUE THREAD

**Issue by avano** [syndesisio/syndesis#5226]
See also **https://issues.jboss.org/browse/ENTESB-11479**

## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
It would be nice if it was possible to map (for example the output of SQL select) to the `fileId` property in box connector's download action

Currently you can download one file over and over again and it isn't very practical

**Comment by claudio4j** [comment]
> It would be nice if it was possible to map (for example the output of SQL select) to the `fileId` 
> property in box connector's download action

Do you mean to upload instead to download ? To get the output of an SQL invocation and upload as text to box/dropbox/ftp/sftp ?

**Comment by avano** [comment]
@claudio4j currently you can use the box download action in a way, that you need hard-code the `fileId` property - so the integration will download one file from box over and over again, which makes it kinda limited. So I think we will need a way how we can use some "dynamic" `fileId` in the download action. 

This doesn't apply just to box connector, but other connectors like ftp or dropbox, but those can download the whole directories AFAIK, so its not a big problem with those connectors, but box seems to only work with individual files - is that right?

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11479**
