### ISSUE TITLE
Title and Icon in browser tab need to be updated - Integrately

### ISSUE THREAD

**Issue by amysueg** [syndesisio/syndesis#5231]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
In the Red Hat Solution Explorer, under Applications, select "Red Hat Fuse Online (Shared)".
Fuse comes up in a separate tab which uses the old, out of date Syndesis icon and the title "Ignite".

I used this running instance of RHMI: https://tutorial-web-app-webapp.apps.uxddev-42b3.openshiftworkshop.com/

## Expected behavior
The tab should include the customer-facing Fuse icon and the label "Red Hat Fuse Online".
I will add the customer-facing Fuse icon when I find it. :-)

## Screenshot

![Screenshot 2019-04-15 16 34 29](https://user-images.githubusercontent.com/31700119/56163862-72151800-5f9d-11e9-920c-fea507f52759.png)

![Screenshot 2019-04-15 16 48 11](https://user-images.githubusercontent.com/31700119/56165017-ec469c00-5f9f-11e9-8213-f7f499a7b9b5.png)

**Comment by seanforyou23** [comment]
I've searched through https://github.com/integr8ly/tutorial-web-app and don't seem to find the glasses logo or a reference to the text "Ignite " anywhere. Here's a list of image assets I found in this repo. 

```./public/favicon.ico
./src/img/favicon.ico
./src/img/landing-page-bck-img.jpg
./src/img/pfbg_992.jpg
./src/img/StartingServices_Final.svg
./src/img/brand-alt-solutions-explorer.svg
./src/img/logo-alt.svg
./src/img/StartingServicesStill.svg
./src/img/brand-alt.svg
./src/img/login-reversed.svg
./src/img/Logo_RH_SolutionExplorer_White.png
./src/img/bg-login-2.png
./src/img/congratulations_bg.png
./src/img/Logo_RH_RGB_Reverse.png
./src/img/bg-login.png
./src/img/provisioning-bg.png
./src/img/HomePageDefault.png
./src/logo.svg

./public/assets/images/pfbg_576.jpg
./public/assets/images/loading_576@2x.jpg
./public/assets/images/pfbg_992.jpg
./public/assets/images/congrats_768.jpg
./public/assets/images/pfbg_576@2x.jpg
./public/assets/images/pfbg_2000.jpg
./public/assets/images/congrats_768@2x.jpg
./public/assets/images/loading_768.jpg
./public/assets/images/loading_2000.jpg
./public/assets/images/loading_576.jpg
./public/assets/images/congrats_2000.jpg
./public/assets/images/loading_768@2x.jpg
./public/assets/images/pfbg_768.jpg
./public/assets/images/congrats_576@2x.jpg
./public/assets/images/pfbg_992@2x.jpg
./public/assets/images/congrats_576.jpg
./public/assets/images/pfbg_1200.jpg
./public/assets/images/pfbg_768@2x.jpg
./public/assets/images/background-filter.svg
./public/assets/images/StartingServices_Final.svg
./public/assets/images/RedHatLogo_white.svg
./public/assets/images/Icon_RH_Software_App.svg
./public/assets/images/congratulations.svg
./public/assets/fonts/webfonts/fa-regular-400.svg
./public/assets/fonts/webfonts/fa-solid-900.svg
./public/assets/images/Web_RH_Banner.png
./public/assets/images/RedHatLogo.png


./src/components/provisioning/StartingServices_Final.svg
./src/components/errorScreen/resources/StartingServices_Error.svg
./src/components/errorScreen/resources/backdrop.png
./src/components/errorScreen/resources/RedHatLogo.png```

Is there another codebase I can search through for this information?

**Comment by seanforyou23** [comment]
@amysueg ^
