### ISSUE TITLE
Box - OutputDataShape java.io.OutputStream not needed as it can't be mapped to anything

### ISSUE THREAD

**Issue by avano** [syndesisio/syndesis#5234]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
`Download file` action specifies the datashape as `java.io.OutputStream` and that is not needed, as it can't be mapped to anything.

![dm](https://user-images.githubusercontent.com/7081216/56188693-75081b00-6026-11e9-95d9-9d40afa2d1e7.png)

It would be better if the connector was returning some custom structure (if it is possible) with properties like `fileName` `content` `size` `...` that could be mapped to something

**Comment by heiko-braun** [comment]
@tadayosi Do you have room to look at it this sprint?

**Comment by tadayosi** [comment]
@heiko-braun Sure, let me take.
