### ISSUE TITLE
Icon of a step extension not visible

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#5255]
## This is a...

 - [ ] Feature request
 - [ ] Regression (a behavior that used to work and stopped working in a new release)
 - [x] Bug report  
 - [ ] Documentation issue or request

## Description

Icon placed in `src/main/resources/META-INF/syndesis/icon.[svg|png]` is bundled but not presented in the UI. The `icon` property points to `extension:icon.[svg|png]` which is directly rendered for `src` attribute of an `<img>`.

**Comment by nicolaferraro** [comment]
I've seen the same issue with connector extensions. It happens in the react UI with every connector having a custom scheme like 'db:' or 'extension:'. It seems the [`getConnectionConnector`](https://github.com/syndesisio/syndesis/blob/3736a21944dacd254663f493010f2122aa7b7593/app/ui-react/packages/api/src/helpers/connectionFunctions.ts#L28) function doesn't get called in all pages.

![Screenshot from 2019-06-03 12-37-02](https://user-images.githubusercontent.com/4151857/58796086-933cd100-85fc-11e9-8ac5-c74e8d316943.png)

cc: @riccardo-forina

**Comment by mastepan** [comment]
@nicolaferraro @gashcrumb @paoloantinori  just checking. Is there anything that should be checked by QE?
