### ISSUE TITLE
Internal API to fetch environments with usage counts

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#5267]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
The updated CI/CD design has counts of the number of integrations tagged with a given environment, however the public environments endpoint only returns an array of environment names.  It'd be cool if there was maybe an internal endpoint the UI could use that returned an array of `{ "name": "foo", "uses": 3 }` kinda objects, otherwise the rows on the UI look a bit plain.

**Comment by mkralik3** [comment]
Verified that the endpoint returns the number of uses for tags. `GET .../public/environments?withUses=true` returns 
```
[{"name":"tag1","uses":1},{"name":"tag2","uses":0}]
```
@gashcrumb Is the UI already prepared for the response and are we able to deliver it for 7.4 or the counter in UI (according to linked storybook) will be moved to 7.5?
https://user-images.githubusercontent.com/351660/56456742-9aef3180-633e-11e9-8fb5-f51a2b152584.png

**Comment by gashcrumb** [comment]
Shouldn't be a big change, but probably it'll be a 7.5 thing I guess.
