### ISSUE TITLE
Template code editor starts counting lines at 0

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#5273]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
The CodeMirror template editor reports errors with line numbers in them and this line number starts at 0, which can be quite confusing if you see an error on the 3rd line reporting that something's wrong on the second line.
Also there are no line numbers displayed so this error message could be more useful if you could see the line number from the start.
@syndesisio/uxd Could you please provide an opinion on this? I am not really sure if this is supposed to be filed as bug or if it is how things are meant to be.
Because I'd either suggest dropping the location information completely (as the errors are displayed only for one line) or making the line numbers visible and perhaps allowing the users to see all errors at the time without hovering over all the error indicators?

**Comment by mmuzikar** [comment]
I will also provide an example:
I get these errors:
```
     Expected open symbol at line: 1, column: 6
     Illegal close symbol at line: 1, column: 13
     '{{wrongid1}}' does not conform to the format {{xyz}} at line: 2, column: 12
```
When using this template:
```
{{test}} Valid line
    {invalid} 
{{wrongid1}}
```
You probably can see how confusing that gets if the only valid line in your template is the first and you get two errors reported there :D

**Comment by phantomjinx** [comment]
@mmuzikar 
Can certainly look into tightening up the line numbers and iron out any confusion.
The codemirror editor uses an array with first index of 0 for its line numbers, hence the assumption of starting at 0. Will need to fix the label messages to display (index + 1).

**Comment by dongniwang** [comment]
@mmuzikar - Thanks for the issue. Would you be able to supply a screenshot with this issue as well? 

From what I understand, the UX suggestion would be to display the right line number. As for whether or not to drop the line location information completely, that would be a question to get some more feedback from users.

**Comment by mmuzikar** [comment]
@dongniwang I figured it'd be better for me to provide a gif of the behavior since on a single screenshot the error message overlaps other lines in the editor
![Peek 2019-04-26 07-43](https://user-images.githubusercontent.com/46345469/56785836-1cd7d280-67f7-11e9-9434-fa54ff23a384.gif)

**Comment by dongniwang** [comment]
@mmuzikar thank you for the screenshots. I think what @phantomjinx suggested here makes sense. https://github.com/syndesisio/syndesis/issues/5273#issuecomment-486243634

**Comment by mmuzikar** [comment]
@dongniwang Yes I 100 % agree that is the best possible solution :)

**Comment by phantomjinx** [comment]
PRs to be merged
- angular: https://github.com/syndesisio/syndesis/pull/5655
- react: https://github.com/syndesisio/syndesis-react/pull/445

**Comment by mmuzikar** [comment]
Verified by QE
