### ISSUE TITLE
[SQS] Can the queue be moved to action instead of connection?

### ISSUE THREAD

**Issue by avano** [syndesisio/syndesis#5278]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
@oscerd can the queue name be moved from the definition on the connection level directly to the action? For example, when I want to use two queues from the same region, I need to create two connections where I need to put the same AWS credentials twice and the only difference is the queue name I want to use. IMO it would be better to have one connection for one AWS region and re-use it for multiple queues if that would be possible

**Comment by oscerd** [comment]
Not sure. I'll check tomorrow :-)

**Comment by oscerd** [comment]
It should be done.
