### ISSUE TITLE
Utilize available PF4 patterns to improve UX

### ISSUE THREAD

**Issue by seanforyou23** [syndesisio/syndesis#5293]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Since we've added the new PF4 Chrome, any short-comings in our existing IA are further highlighted. 

- Duplicate heading text in Customizations tab can be improved by transitioning the tabs into expandable nav items in the main sidebar menu. See example link below.
- Introduce subheader section to house breadcrumbs, view title and description. See example link below.
- Some pages like Connections and Integrations do not have a title or description, let's create content for these so the main pages across the app have a consistent place to help orient the user.
- Some areas of the application need to remove the main content area padding to take advantage of all available real estate (integration editor for example). Let's make a convenient hook for managing this.

http://patternfly-react.surge.sh/patternfly-4/demos/pagelayout/pagelayoutexpandablenav/

## Expected behavior

The app takes advantage of available PF4 patterns given the milestones outlined for the integration product suite. For now, this means any aspect of PF4 chrome (nav, masthead, subheader, about modal, typography).

## Screenshot

This example closely resembles the general structure we're going for: http://patternfly-react.surge.sh/patternfly-4/demos/pagelayout/pagelayoutexpandablenav/

**Comment by mastepan** [comment]
@seanforyou23  just checking. Is there anything that should be checked by QE?
