### ISSUE TITLE
Artifact for integration-bom-camel-k not released

### ISSUE THREAD

**Issue by nicolaferraro** [syndesisio/syndesis#5298]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Looking at a released tag, that artifact is still present with a snapshot version: https://github.com/syndesisio/syndesis/blob/6654c7a703338f4c2ee2a102e65d32af9c674999/app/integration/bom-camel-k/pom.xml#L23

It happens because it is not a descendant of the root project (and it should not be).

But this in turns mean that it's not published in the maven repo when we do the release.
 
cc: @heiko-braun, @lburgazzoli, @valdar 
Seems a CI / Prod issue. Affects 7.3.

**Comment by heiko-braun** [comment]
Here's the link to 1.6.x: https://github.com/syndesisio/syndesis/blob/1.6.x/app/integration/bom-camel-k/pom.xml#L23

**Comment by janstey** [comment]
FYI it got released here https://maven.repository.redhat.com/ga/io/syndesis/integration/integration-bom-camel-k/1.7.0.redhat-00007/integration-bom-camel-k-1.7.0.redhat-00007.pom but obviously that won't work as all connector references in that pom are to a non-existent 1.7 version of syndesis :-(

**Comment by heiko-braun** [comment]
The file is available now at the right location: https://maven.repository.redhat.com/ga/io/syndesis/integration/integration-bom-camel-k/1.6.11.fuse-730003-redhat-00001/
