### ISSUE TITLE
Create an AWS-SNS connector

### ISSUE THREAD

**Issue by oscerd** [syndesisio/syndesis#5299]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
As a citizen user of fuse online, I want to be able to connect to an AWS-SNS connector
I want to be able to provide my connection url, authentication details and any additional details such as cache settings.
DoD
I can create an integration with a standard timer writing to an SNS.
I can connect to an AWS-SNS and consume messages
I want to be able to provide a filter policy to restrict the notifications I receive.
I want to be able to use AWS-KMS for encrypt/decrypt

--There is an initial draft of the user doc for this feature.
--The writer acknowledges receiving enough information from engineering to write the initial draft of the user doc for this feature.

**Comment by heiko-braun** [comment]
@gaughan Can you provide a user story and acceptance criteria for this one?

**Comment by oscerd** [comment]
Please, note that there is no consumer on the aws-sns component. This is because of this discussion https://issues.apache.org/jira/browse/CAMEL-3476

**Comment by oscerd** [comment]
In introduced the bridge between aws-sns topic and aws-sqs to be able to consume from sns in Camel. I think we can try to use that, but it won't be completely free (we need to backport the functionality on 2.21.x)

**Comment by gaughan** [comment]
@heiko-braun updated above

**Comment by oscerd** [comment]
To consume you'll need to pass through an SQS connection. This will only need to be set on the aws console. There is no consumer in the component.. because the Java sdk provides the feature of bridging SQS to SNS. It makes sense to provide docs on how to do this on the console and consuming from an SQS endpoint. For KMS I have to check.

**Comment by oscerd** [comment]
For KMS, you need to enable it when you create the topic, so it makes sense to leave this out. If you need to use KMS, you can do that through the AWS console, as for consuming through the SQS queue. For a citizen integrator, creating the bridge, or setup the KMS master key to use on the topic created, seems to be too much. I will show how to do this on a demo and we can document everything.

**Comment by oscerd** [comment]
For the filter policy, you can use the a camel filter as we do for SQS, since you'll use an SQS queue to consume.

**Comment by oscerd** [comment]
I think I have enough material to create the connector which will have only a to action.

**Comment by oscerd** [comment]
Ok, I tested the situation. The connector will have only the possibility to send something to topic.
The encryption can be enabled during the topic creation on the aws console.
To consume, the only thing you need is creating an SQS queue and subscribe the queue to your topic, then you can create a normal consumer on that SQS queue and the messages coming from the sns will be consumed from there.
This is because from a pure java perspective the SNS Client doesn't have any methods to consume messages: it only provides a way to subscribe to a topic, through different approach http/https/SQS/lambda. 
I'll add to the component the parameters needed for enabling encryption, but anyway they will be applied only during the creation of the topic (it means, they will be take into account, only if the topic we specified doesn't exists at the moment of the invocation). So, IMO, this is something to leave out of the Syndesis connector and set up everything on the AWS Console.
I'll help with the documentation on this.

**Comment by oscerd** [comment]
ping @heiko-braun @gaughan

**Comment by heiko-braun** [comment]
@syndesisio/qe FYI
