### ISSUE TITLE
Polish UI with keyboard input

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#5301]
See also **https://issues.jboss.org/browse/ENTESB-11477**

## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
Most tasks in Syndesis (ie. adding a new connector, creating a new integration) require the user to move their focus from clicking in the UI to the keyboard. It would be really nice if the UI was streamlined enough to for example fill in a new connector details and move to naming connector and creating it without the need to move my hands from the keyboard.

What I would propose is make at least the basic keyboard shortcuts the users are used to readily available, ESC for canceling works in some cases (canceling a modal), but I as a user also expect ENTER to be a key for confirming, so in most cases i instinctively press ENTER.

Sometimes there is more than one button on the page at the same time (will provide screenshots bellow) so this feature might not be that simple to implement in all cases (we have to think about what the user expects to be confirming).

Also the best case scenario would be if using tab to move in forms would first focus on the elements in the currently edited form and after that other links etc. 

@syndesisio/uxd Do you think this can be valuable feature? 

## Screenshots
![image](https://user-images.githubusercontent.com/46345469/57123694-fb409300-6d82-11e9-9b75-43a319cf60de.png)
Here is screenshot of a page having two buttons a user can see as pressing enter would trigger them. My opinion is the ENTER should always trigger next/confirm/done but some users could also believe it might be linked to validate.

![Peek 2019-05-03 09-49](https://user-images.githubusercontent.com/46345469/57125233-ec5cdf00-6d88-11e9-93b4-846ca416b00e.gif)
Here I captured the behavior we have now, as you can see you can cancel out a modal window but can't confirm it by keyboard.

**Comment by gashcrumb** [comment]
+1 plus proper accessibility support kinda requires keyboard navigation.

**Comment by mmuzikar** [comment]
Also adding to this suggestion it think it would be nice to be able to start typing and what I am typing being send to the filter inputs... that could really speed up creating new connectors for example.

**Comment by asmigala** [comment]
> Also the best case scenario would be if using tab to move in forms would first focus on the elements in the currently edited form and after that other links etc.

I'd like to expand this a bit, currently in the react UI, in the Create Connection form for instance, hitting Tab moves focus from a text input to the next input's `i` button, so you need to pres Tab twice to move between text inputs.

**Comment by dongniwang** [comment]
Having basic keyboard shortcuts is definitely a good enhancement, that will depend on how we structure the page (i.e. placement of the primary buttons, cancel button) based on our understanding of the user behaviors. 

Adding @seanforyou23 for accessibility input.

**Comment by mmuzikar** [comment]
@seanforyou23 This is still an issue that you are tackling with the accessibility input right? I should have asked you on the F2F.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11477**
