### ISSUE TITLE
[conditional flow] Create UX design for conditional flow

### ISSUE THREAD

**Issue by dongniwang** [syndesisio/syndesis#5307]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

See user story in https://github.com/syndesisio/syndesis/issues/4796. 

- [x] receive UX request / identify priority
- [x] verify user story and requirements
- [x] initial design
- [x] design review
- [x] design iteration
- [ ] design sign-off
- [ ] plan of action for implementation

**Comment by dongniwang** [comment]
Latest design can be found here https://redhat.invisionapp.com/share/2ARQTCSHBWF.

**Comment by dongniwang** [comment]
@gaughan @christophd and @gashcrumb, can you please review the latest design 4/26 [here](https://redhat.invisionapp.com/share/2ARQTCSHBWF.). 

If everything looks alright and now further UX changes needed, please sign off in this issue. 

cc: @paoloantinori @TovaCohen

**Comment by gashcrumb** [comment]
@dongniwang can you update the link?  I get a page not found.

**Comment by gashcrumb** [comment]
@dongniwang So for the angular codebase sure thing, that design will work.  I think however we need to also consider this layout/card view usage in the context of the layout of the react implementation, as I'm not 100% how this design is going to translate.  I definitely think it warrants a look before I fully sign off.

**Comment by dongniwang** [comment]
Updated the link. @gashcrumb 

And good point about the react version, I can work on it.

**Comment by dongniwang** [comment]
Per @gashcrumb 's [request](https://github.com/syndesisio/syndesis/issues/5307#issuecomment-490119377), here are some possibilities for the conditional flow design in React UI.

https://redhat.invisionapp.com/share/5NRZPGAVP2F

I've included 2 options for the conditional flow. In the InVision, you can also find some early PF4 exploration for the integration editor. Feedback is always welcomed. Thank you! 

@syndesisio/uxd @gaughan @christophd

**Comment by gaughan** [comment]
looks great! thanks

**Comment by mcada** [comment]
@dongniwang is this issue up-to-date?

**Comment by dongniwang** [comment]
The link I shared above probably doesn't work now. Here's the updated [link](https://marvelapp.com/c34fch0) to the design.

**Comment by mcada** [comment]
I mean the feature is already implemented - what are following steps? What needs to happen so we can close this task?

**Comment by dongniwang** [comment]
I think we can close this one, I'll open another issue if we need to update the existing design and implementation. Thanks!

**Comment by tsykora** [comment]
Hello @dongniwang, just a quick question please, I noticed the checkbox for design sign-off "task" in this issue in not checked. Who is supposed to provide such sign-off? (You? Developers? QE? Gary? Everyone together?)

Regarding the plan of actions for implementation - I believe, logically, that it has been already made somehow since the implementation is done and functionality is in the product - hence I am not asking for that. Just wondering about the sign-off itself. Thanks so much! Tomas

**Comment by dongniwang** [comment]
Thanks for checking in @tsykora - I forgot to check the boxes and I think Gary and Engineering had reviewed the design already. 

Let's discuss how we can include QE earlier in the process to make sure there's clear communication in the future. Thanks!

**Comment by tsykora** [comment]
Thanks @dongniwang for the explanation. There is no intention to give you any hard times. As you said - the general intention is to include QE input earlier in the process. I think we are in a better position for 7.5 release, QE will work more closely on cases. Michael is working on that together with Bruno Alejos from Engineering team ;)
