### ISSUE TITLE
Flows mismatched when editing OpenAPI definition of API provider itegration

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#5310]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

If I create an OpenAPI definition without specifying `operationId` a `operationId` will be generated as `operation-#` (say `operation-0`). If I edit the OpenAPI definition to remove an operation and add another operation without specifying the `operationId` the new operation will use the same `operationId` (the same `operation-0`).

The result of this is that the flow designed for the first, now removed, operation will be assigned to the flow of the newly added operation.

I think it would make sense to generate unique `operationId`s as the numbered ones can lead to clashes like this.

**Comment by mmuzikar** [comment]
@zregvart While this fixes the problem of mismatching flows, it highlights another problem when the user is able to edit the operationId with existing flow and inevitably losing that flow (with operation-xx there was still some chance of being able to guess that id).

I don't think that the user should be able to edit the operationId when a flow tied to that operationId exists.

What do you think @syndesisio/uxd

**Comment by zregvart** [comment]
We're explaining this in the [documentation](https://access.redhat.com/documentation/en-us/red_hat_fuse/7.3/html/integrating_applications_with_fuse_online/trigger-integrations-with-api-calls_ug#requirements-for-api-provider-integrations_api-provider), search for "Considerations while editing the OpenAPI document"

**Comment by mmuzikar** [comment]
Even though it is in documentation, I think it would be the best if there was at least a conformation dialog if user really wants to change the operationId... or perhaps if there is already a flow tied to that operationId use the new operationId.

It might not be apparent to users that renaming something can lead to losing an entire flow.

**Comment by zregvart** [comment]
Might be so, lets then open an feature request for that, and verify this issue as I think it should be resolved.

**Comment by mmuzikar** [comment]
Opened #5513 and closing this issue as verified.
