### ISSUE TITLE
Unable to find adapter for google calendar

### ISSUE THREAD

**Issue by asmigala** [syndesisio/syndesis#5311]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Trying to add any google calendar step results in the following message:

![image](https://user-images.githubusercontent.com/9480152/57293542-51843d80-70c5-11e9-890c-60ac259ce724.png)

**Comment by christophd** [comment]
I had a look into this and it seems to be related to recent the removal of Spring framework from the connectors.

Before there has been a Spring Boot auto configuration that loaded the meta data retrieval beans with a special bean name pattern `{connector-id}-adapter`. 

In [ConnectorEndpoint](https://github.com/syndesisio/syndesis/blob/313186a1bbe9a8aeefbaa607099a4f7c207669b9/app/meta/src/main/java/io/syndesis/connector/meta/v1/ConnectorEndpoint.java#L59) the meta data retrieval beans got loaded using this bean name pattern with the `-adapter` suffix.

This got somehow lost when removing the Spring Boot bits from the connectors. Instead we could use the Camel factory finder mechanism as fallback but we need to make sure that the `-adapter` suffix is handled with this mechanism. At the moment the adapter is not found and this leads to the described error. This is not only for google-calendar connector but for others, too.

@rkorytkowski @zregvart @lburgazzoli any thoughts?

**Comment by christophd** [comment]
A 2nd look revealed that is is more the connector id than the `-adapter` suffix. The google calendar connector id is `google-calendar` but the factory lookup file is named `calendar`. That is why the adapter is not found using the factory finder mechanism.

**Comment by asmigala** [comment]
Verified with latest master
