### ISSUE TITLE
Create integration - disable Save and Publish buttons until an integration name set

### ISSUE THREAD

**Issue by mastepan** [syndesisio/syndesis#5312]
See also **https://issues.jboss.org/browse/ENTESB-11428**

## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Save and Publish buttons are enabled even if the integration name hasn't been set yet. If they are clicked, the integration setting is lost because the buttons are set disabled forever then.
The only way how to reset them is going back to Integrations page and set the all new integration settings again.
 
## Expected behavior

Keep Save and Publish buttons disabled while the integration name is not set.

## Screenshot

![save1](https://user-images.githubusercontent.com/8707251/57298979-ce1e1880-70d3-11e9-954c-9849e13a87d3.png)
![save2](https://user-images.githubusercontent.com/8707251/57298990-d24a3600-70d3-11e9-8dfb-fc91c9c6be85.png)

**Comment by heiko-braun** [comment]
@riccardo-forina Can you verify the behaviour in the react UI?

**Comment by riccardo-forina** [comment]
In the React UI those buttons are links pointing to the page where a name and description must be set to continue saving. I think we should be ok.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11428**
