### ISSUE TITLE
[SQS] Use nullDeduplicationStrategy by default

### ISSUE THREAD

**Issue by avano** [syndesisio/syndesis#5313]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
It makes more sense to have `nullDeduplicationStrategy` selected by default, rather than `ExchangeIdDeduplicationStrategy` and then wondering why I don't get all the messages I should :-)

**Comment by oscerd** [comment]
One thing to have in mind is that in case of FIFO queue, we need to enable the content-based deduplication during the queue creation

**Comment by heiko-braun** [comment]
Can we make it configurable?

**Comment by oscerd** [comment]
It's already configurable. @avano means to set the default as nullDeduplicationStrategy
