### ISSUE TITLE
Inputs stay open in API provider when clicking between operations

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#5314]
See also **https://issues.jboss.org/browse/ENTESB-11476**

## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When editing some property of operation in the API Provider definition, you can click between different operations and when you have an edit widget "open" and click on different operation it stays active with the same input, which can cause accidental overriding of the properties if user clicks on confirm in wrong operation.

Gif showing the current behavior:
![Peek 2019-05-07 16-33](https://user-images.githubusercontent.com/46345469/57308219-3ece3080-70e6-11e9-9381-3d55d0c19f33.gif)

What I would expect is closing the widget (simulating pressing the X key) so any not confirmed changes are dropped (which I believe a lot of users do click somewhere else to discard any changes). Maybe and that's up for the debate applying those changes (but I think that might cause more trouble than just discarding the changes)

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11476**
