### ISSUE TITLE
Clean up integration data when integration gets deleted

### ISSUE THREAD

**Issue by christophd** [syndesisio/syndesis#5321]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

When an integration is deleted we should remove all related data from the database. At the moment the database still holds integration related data (e.g. integration definition, integration-deployments, integration-activity, open-api specs, integration-bulletin-board). 

We should clean up those entries when the integration is deleted.

**Comment by phantomjinx** [comment]
@zregvart 
Is this not quite a big change?
When integrations and integration-deployments, they are updated to make their deleted flag 'true' so nothing ever really actually disappears. Are we happy to change the common-model to remove the deleted flags and actually have the integration etc.... properly disappear entirely?

**Comment by zregvart** [comment]
I think it's not a lot of work to do this, and it would lead to better performance. I can't remember why we don't delete the integrations fully from the database. I think @chirino has some arguments on why we do that?
I'm not aware of anything that will break, but there might be some surprises.
The only thing I'm not completely sure about is if the deleted flag has some weight in the integration controller and openshift integration I don't see it mentioned in the [design proposal](https://github.com/syndesisio/syndesis/blob/master/project/proposals/044-integration-model.md).
So I'm not sure what to advise here, perhaps try to time box the effort and see how many dragons you fight?

**Comment by phantomjinx** [comment]
@zregvart 

> I think it's not a lot of work to do this, and it would lead to better performance. I can't remember why we don't delete the integrations fully from the database. I think @chirino has some arguments on why we do that?

Yeah, so started with removal of the deletion flag and that is used fairly extensively, hence my comments about "big change". However, looking at is further I think we can leave that flag for now and simply deprecate the `isDeleted()` since existing releases will still have deleted flagged integrations resident in the datamanager.

> I'm not aware of anything that will break, but there might be some surprises.
Running through it now ... 

> The only thing I'm not completely sure about is if the deleted flag has some weight in the integration controller and openshift integration I don't see it mentioned in the [design proposal](https://github.com/syndesisio/syndesis/blob/master/project/proposals/044-integration-model.md).
Will take it out for a few spins before running up a PR.

> So I'm not sure what to advise here, perhaps try to time box the effort and see how many dragons you fight?
Sure thing!

**Comment by KurtStam** [comment]
Are we sure we want to do this? Initially this was done by design. Did the design change?

**Comment by phantomjinx** [comment]
see https://github.com/syndesisio/syndesis/pull/5755#issuecomment-502394954

**Comment by mastepan** [comment]
@phantomjinx Is there anything that QE should verify?

**Comment by phantomjinx** [comment]
Create integration
Connect to json-db pod from OS directly using psql & confirm presence of integration
Update integration name or description in syndesis
Connect to json-db ... & confirm presence of integration update bulletin board records
Delete integration in syndesis
Connect to json-db ... & confirm all integration records have gone.

**Comment by mmuzikar** [comment]
Verified by QE.
