### ISSUE TITLE
Documentation for Actions in a Google Sheet connection are truncated and cannot be read fully. 

### ISSUE THREAD

**Issue by tmielke** [syndesisio/syndesis#5323]
## This is a...

<pre><code>
[ x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
Documentation for Actions in a Google Sheet connection are truncated and cannot be read fully. 

## Expected behavior
There is plenty of space on the screen to move the text into multiple lines rather than truncating the longer single line.

## Screenshot

<img width="1438" alt="screenshot" src="https://user-images.githubusercontent.com/1889892/57368570-b7d39380-718b-11e9-8309-97570dfdf832.png">

## Tasks involved / Steps to Reproduce
1. Create a new Google Sheets connection
2. Create a new Integration with the Google Sheets connection at the start. 
3. Review the screen that requests you to choose an Action

**Comment by tplevko** [comment]
This seems no longer to be an issue 
![Screenshot from 2019-08-22 10-52-30](https://user-images.githubusercontent.com/4180208/63500875-f71fb900-c4ca-11e9-865b-4a6bd4ca578b.png)
