### ISSUE TITLE
Customize Option For Syndesis-UI User Interface

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/syndesis#5327]
See also **https://issues.jboss.org/browse/ENTESB-11510**

See https://issues.jboss.org/browse/ENTESB-10117 for further details

**Comment by paoloantinori** [comment]
Hi, we cannot fully commit to this activity but we acknowledge its importance and for this Sprint we have decided that we'll offer a solution based on documenting how to override part of the UI with OpenShift level interactions (mounting filesystem folders to overwrite the original source, at deploy time).

This should not consider a complete solution but a first step to show people that they have options even without any engineering intervention.

/cc @gashcrumb @riccardo-forina @kahboom @seanforyou23

**Comment by aileenc** [comment]
Does this seem feasible for 7.5?

**Comment by paoloantinori** [comment]
We have discussed this with the team and the solution to this for the 7.5 timeframe is gonna be the same.

@rkorytkowski how do you feel working on this?

**Comment by rkorytkowski** [comment]
Cool. I'll give it a shot.

**Comment by rkorytkowski** [comment]
Not sure where to put the docs so let me leave them in a comment below.

**Comment by rkorytkowski** [comment]
### Customize Syndesis UI Branding
It is currently possible to customize branding (logos, app name) for Syndesis UI using OC by manipulating static resources directly in the Syndesis UI pod.

You can start from fetching customizable resources by running:

`oc rsync syndesis-ui-REPLACE_POD_ID:/opt/app-root/src/static/media ~/`

(replace REPLACE_POD_ID with the actual pod ID determined by running `oc get pods`)

It will put Syndesis resources under `~/media/`.

You can manipulate any files you want to customize e.g. `~/media/syndesis_logo_full_darkbkg.*.svg` is used for the header logo.

Once you have made all necessary customizations you can upload modified resources back to the pod with:

`oc rsync ~/media syndesis-ui-REPLACE_POD_ID:/opt/app-root/src/static`

Similarly you can modify the application title by running:

```
mkdir ~/syndesis-custom/src
oc rsync syndesis-ui-REPLACE_POD_ID:/opt/app-root/src/index.html ~/syndesis-custom/src
sed -i 's/\(<title>\).*\(<\/title>\)/<title>REPLACE_WITH_NEW_TITLE<\/title>/g' ~/syndesis-custom/src/index.html
oc rsync ~/syndesis-custom/src syndesis-ui-REPLACE_POD_ID:/opt/app-root

```
Please note that the customizations will be reverted, if the Syndesis UI pod is ever redeployed.

**Comment by rkorytkowski** [comment]
Regarding using sed. I've tried oc exec POD sed -i ... but it didn't modify the file for some unknown to me reason thus using rsync.

Also I'm not sure if there's a way to make the changes persistent across redeploys. Please advise.

**Comment by riccardo-forina** [comment]
> Not sure where to put the docs so let me leave them in a comment below.

I think it can go in a "Customization" section in the [README](https://github.com/syndesisio/syndesis/blob/master/app/ui-react/README.md)

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11510**
