### ISSUE TITLE
Add liveness check to Spring Boot integrations

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/syndesis#5328]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Expose a health endpoint in Spring Boot integration runtime pods and configure OpenShift to use it for its liveness probe.
Note: In support of SLI-4.2

**Comment by alexkieling** [comment]
@heiko-braun Integration pods already expose a Prometheus endpoint and Prometheus automatically creates an `up` metric with value 1 when the last scrape was successful and value 0 when it failed.
I think we don't need to add a different liveness check. What do you think?

**Comment by heiko-braun** [comment]
The intent was to enable Openshift self-healing capabilities. Without the liveness check, failed pods will not be restarted I think.

**Comment by alexkieling** [comment]
OK, got it. I thought you were referring to an availability check done by integr8ly.
I'll contact the backend team.

**Comment by zregvart** [comment]
> That said, maybe there was reason to not add liveness checks in the first place? Something to ask @syndesisio/backend ...

I can't remember any discussion on that, my guess is that we simply forgot to add them. The design for this [was done](https://github.com/syndesisio/syndesis/blob/master/project/proposals/042-health-checks.adoc).

That being said we probably need to consider this in the Camel-K runtime also by enabling the `probes` trait if we don't do it already.

**Comment by lburgazzoli** [comment]
some work has been done about health check but because we were rushing to get the first release done, health checks have not been tested and I think the implementation is still partial (does not cover all the aspects of camel).

**Comment by alexkieling** [comment]
Shall we focus on both Spring Boot and Camel-K? I think we need to review that design document and add a section for Camel-K, right?

**Comment by lburgazzoli** [comment]
Yes we also need to define what we really wants to check. The first design was quite advanced like as you can find reading through the docs there were the option to start the integration and deal with connectivity errors i.e. later on.

**Comment by alexkieling** [comment]
@heiko-braun I'm reducing the scope of this task to Spring Boot and creating another one to focus on Knative. It's currently not clear how health checks should be done in Knative.

**Comment by heiko-braun** [comment]
Why worry about KNative?

**Comment by alexkieling** [comment]
Good question, @heiko-braun . Maybe it's too early to worry about that.
