### ISSUE TITLE
datamapper separate feature

### ISSUE THREAD

**Issue by Stefan365** [syndesisio/syndesis#533]
When "separate" action selected, 
second "target" has to be created manually.
I suppose this should be done automatically by UI.

**Comment by zregvart** [comment]
@igarashitm doesn't Atlasmap do this if you drag the same source to two or more targets?

**Comment by igarashitm** [comment]
I think this is a separate version of atlasmap/atlasmap#95, atlasmap/ui is not handling well around combine/separate.

**Comment by igarashitm** [comment]
This issue was moved to atlasmap/atlasmap#140
