### ISSUE TITLE
Changes to OpenAPI not reflected in API Provider

### ISSUE THREAD

**Issue by asmigala** [syndesisio/syndesis#5332]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
After editing an OpenAPI definition in an APi Provider integration (such as deleting an operation or adding a new one), the list of available operation remains unchaged.

## Steps to reproduce
1. create an API Provider Integration from an existing swagger json
2. click View/Edit OpenAPI definition
3. delete one of the operations
4. click save
5. the list of operations still contains the deleted operation

**Comment by heiko-braun** [comment]
@asmigala  Is it in 1.6.x or current master?

**Comment by asmigala** [comment]
Current master

**Comment by mmuzikar** [comment]
@heiko-braun there hasn't been much news on this issue, I actually wanted to report new one and recorded this gif capturing what @asmigala is talking about.

Could someone take a look at this please?

![Peek 2019-05-29 14-37](https://user-images.githubusercontent.com/46345469/58558592-86e1fe00-8221-11e9-89ae-9e6769ac3f59.gif)

**Comment by heiko-braun** [comment]
@zregvart Can you take a look at this?

**Comment by mmuzikar** [comment]
I am closing this issue and continuing all conversations in #5697 to avoid having multiple conversations in many issues regarding the same problem.
