### ISSUE TITLE
FHIR actions - increase multiselect field height

### ISSUE THREAD

**Issue by mastepan** [syndesisio/syndesis#5333]
See also **https://issues.jboss.org/browse/ENTESB-11475**

## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Multiselect field has too small height. Scrolling there is really cumbersome.

This should be fixed on the following FHIR action pages:
- create
- read
- transaction
- update

![small_multiselect](https://user-images.githubusercontent.com/8707251/57462419-1c205100-7279-11e9-8497-4c3cd233e10e.png)

## Expected behavior

I'd preffer to have it at least as high as the selectbox on the following image
![larger_one](https://user-images.githubusercontent.com/8707251/57462608-71f4f900-7279-11e9-99b3-d1d7e5b7ea92.png)

**Comment by claudio4j** [comment]
This is fixed in master branch. Can this issue be moved to Done, if there is no objection.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11475**
