### ISSUE TITLE
Update Camel K in community operatorhub (OpenShift / OKD)

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/syndesis#5348]

**Comment by heiko-braun** [comment]
@astefanutti I think this is done, isn't it?

**Comment by astefanutti** [comment]
@astefanutti the update for operatorhub.io / kubernetes is done. I'm still working on the update for OpenShift / OKD.

**Comment by oscerd** [comment]
> @astefanutti the update for operatorhub.io / Kubernetes is done. I'm still working on the update for OpenShift / OKD.

Self-quotation one time in my life? Done!

**Comment by astefanutti** [comment]
@oscerd I have no idea how this happened 🥇!

**Comment by oscerd** [comment]
you need to frame this!

**Comment by heiko-braun** [comment]
I see, looks like I got confused my the title.

**Comment by heiko-braun** [comment]
https://operatorhub.io/operator/camel-k

**Comment by mastepan** [comment]
@heiko-braun anything here for QE?

**Comment by heiko-braun** [comment]
no, closing this. it deals with community bits in the community channel of the operatorhub
