### ISSUE TITLE
Apicurito in community operatorhub (OpenShift / OKD)

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/syndesis#5351]

**Comment by mastepan** [comment]
Are QE supposed to check anything here here?

**Comment by heiko-braun** [comment]
Yes, as part of the OCP 4 certification we need to do for 7.4 QE can help verify the operatopr is served from the embedded operatorhub in OCP 4.

**Comment by tplevko** [comment]
The apicurito operator is not available in the community operator hub. https://operatorhub.io/

**Comment by lgarciaaco** [comment]
Here is the PR https://github.com/operator-framework/community-operators/pull/373. I am poking in their channel to have it merged

**Comment by lgarciaaco** [comment]
@tplevko apicurito is available now in the embedded operatorhub

**Comment by mmajerni** [comment]
Apicurito operator in operatorhub works fine
