### ISSUE TITLE
UI: Allow mapping of standard errors to HTTP response codes

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/syndesis#5360]
An integration flow can declare a set of possible standard errors (set of all standard errors in declared by connectors used). Users need to have a way to map all possible standard errors to specific response codes. 

- 500 should be the default mapping.
- Possible response codes should be within the range defined by the OpenAPI spec
- If an OpenAPI operation does not define a specific set of codes, the full range of common HTTP codes should be available for mapping

**Comment by heiko-braun** [comment]
![Screenshot 2019-05-15 at 09 14 27](https://user-images.githubusercontent.com/369380/57755756-f5876d80-76f1-11e9-869d-2eb8f5a4a75e.png)

**Comment by heiko-braun** [comment]
@KurtStam @christophd Does this match your expectations for the minimal UI to begin with?

**Comment by christophd** [comment]
@heiko-braun yeah that's what I had in mind, too.

**Comment by heiko-braun** [comment]
@dongniwang We plan to add this screen for 7.4. Any chance we can get a mockup from your team?

**Comment by heiko-braun** [comment]
@christophd Are you comfortable developing the UI part?

**Comment by christophd** [comment]
@heiko-braun yes, I can work on that once I have finished all things for conditional flows epic. Most likely can begin with it tomorrow in the afternoon.

**Comment by dongniwang** [comment]
@heiko-braun - I should be able to do that. 

I'm assuming we need that for the react UI? And what's the context for this screen?  And what's the timeline we're looking at?

**Comment by gashcrumb** [comment]
> I'm assuming we need that for the react UI?

yup!

@heiko-braun I would not plan to start doing this in the angular codebase if this is going to take longer than the end of this sprint, at that point it really only makes sense to focus developing new things in the react codebase once it's been merged in.

**Comment by gashcrumb** [comment]
@riccardo-forina is planning on starting the API provider bits pretty soon, so worst case if no design is ready yet we'd probably start with porting the existing page over and then can iterate on this.  I'm actually currently working on array support in the react codebase's auto-form component that should make this easier to implement.

**Comment by dongniwang** [comment]
I need more information to understand the problem and provide a design solution. 

- How many standard errors are there? "all possible standard errors" what are these? Are we planning to show all? Is it dynamic? 
- Is it just adding one screen or modifying an existing screen? Does it need more than one screen to complete the task?

**Comment by dongniwang** [comment]
![API-error-handling-0522](https://user-images.githubusercontent.com/24943812/58200440-ca2bf200-7ca0-11e9-8ca4-62fb168d850b.png)

Met with @christophd and @KurtStam this morning. Attaching the design here. Please let me know if you need anything else. Thanks!

**Comment by heiko-braun** [comment]
Thanks @dongniwang !

**Comment by KurtStam** [comment]
The final design looks like:

<img width="592" alt="Screen Shot 2019-08-12 at 10 14 30 AM" src="https://user-images.githubusercontent.com/35576/62852566-055f1f80-bcea-11e9-823e-ef8ba27b42db.png">

**Comment by gashcrumb** [comment]
Are you certain it's not this one @KurtStam:

![image](https://user-images.githubusercontent.com/351660/62878695-98528680-bcf7-11e9-8fd9-815961d1c8d0.png)

@dongniwang can you clarify?  I wonder if we should leave out old designs by default when we're iterating so folks don't confuse which design is the latest.

**Comment by KurtStam** [comment]
Maybe. but we can't group by connector..

**Comment by dongniwang** [comment]
Hey @gashcrumb and @KurtStam - yes, the screenshot from Stan's comment is the latest one https://github.com/syndesisio/syndesis/issues/5360#issuecomment-520483987. 

And Marvel is new to me, so still figuring out the best way to group things. 

@gaughan suggested the group by connector, if that's not possible, we'll just have a flat list then?

**Comment by KurtStam** [comment]
Yes flat list. We can order alphabetically.

**Comment by gashcrumb** [comment]
ah, gotcha, that works for me, thanks!

**Comment by gaughan** [comment]
Do we have the meta data to order by the integration order? This, in my opinion, is the most logical default order to present.

**Comment by christophd** [comment]
@KurtStam can I assign this issue to you? You may know better what's the actual status of this one and what needs to be done.

**Comment by KurtStam** [comment]
This work is done
