### ISSUE TITLE
[UI] Don't trim the description of the connector

### ISSUE THREAD

**Issue by avano** [syndesisio/syndesis#5371]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
There is plenty of space for second row to be displayed in the description of the connector:

![connector](https://user-images.githubusercontent.com/7081216/57779239-ff2ac880-7725-11e9-842e-acebb59751e9.png)

**Comment by heiko-braun** [comment]
Are these react UI issues?

**Comment by riccardo-forina** [comment]
Don't think so, AFAIK we don't have any trim in place.

**Comment by mmelko** [comment]
Looks ok in react ui.
