### ISSUE TITLE
Remove host and base URL configuration from the custom API clients

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#5373]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

I think we should remove host and base URL configuration from the custom API clients.

![Screenshot_2019-05-15 Syndesis](https://user-images.githubusercontent.com/1306050/57783786-0acebd00-772f-11e9-9da4-0570257d1b79.png)

That configuration is repeated when connection is created:

![Screenshot_2019-05-15 Syndesis(1)](https://user-images.githubusercontent.com/1306050/57783889-3e114c00-772f-11e9-864f-38d7b317757b.png)

Also, settings on the connection have lower precedence over settings on the connector (which might be a bug), and to, for example, change the hostname one needs to perform the change on the Custom API settings page and not on the connection.

Any objections @gaughan @syndesisio/uxd?

**Comment by dongniwang** [comment]
I don't have enough information to make a decision here. 

But I think in general, if hostname and base URL varies per connection, then let's only have the configuration on the connection level. Unless there's a use case where we don't want users to change the hostname or base URL (user role related? ) and want to control it at the connector level.

**Comment by gaughan** [comment]
Agreed. 
Separately: Adding a checkbox int he future to automatically create  the connection would be cool

**Comment by dongniwang** [comment]
> Separately: Adding a checkbox int he future to automatically create the connection would be cool

@gaughan - a checkbox as part of the flow of creating API client connector?

**Comment by gaughan** [comment]
Yes, but all connectors

**Comment by zregvart** [comment]
Nice feature creep @gaughan, you sly product manager you.

**Comment by gaughan** [comment]
I wasn't intentional, but that probably makes it worse!

**Comment by zregvart** [comment]
On second thought, we can't do this without enhancing the OAuth connection creation flow (which only has the `Connect to...` button). So defining host/base path on the connector is the only way.

I'm inclined to close this issue, so feel free to reopen if you think this needs to be done.
