### ISSUE TITLE
Could you guide how to developed  apache-camel project on syndesiso 

### ISSUE THREAD

**Issue by pankaj358** [syndesisio/syndesis#5382]
I need to deployed all my microservices to syndesisio, for that I need help or walkthrough 
Please needed...!!

**Comment by heiko-braun** [comment]
Hi @pankaj358, I am not sure I fully understand what you are trying to achieve. Can you you elaborate?

**Comment by pankaj358** [comment]
Hi Heiko,

Thanks for your reply,

I just need to know to deployed microservice which is already build using technology like apache-camel, osgi, frabic8, I have all the code I just want to use this code syndesis.

**Comment by heiko-braun** [comment]
I see what you, but reusing existing services and managing those from Syndesis is currently not possible. What you can do however, is to keep these services on Openshift as they are and interface with them through OpenAPI's, for instance. This way you could leverage existing services within Syndesis, but it's more a sort of delegation. The outermost intergation flow would still need to be designed within Syndesis from scratch.

**Comment by pankaj358** [comment]
Heiko Many thanks to you...

Could you please guide how to create sample apache camel example in syndesis  or docs that I can follow.

Thanks in advanced.

**Comment by heiko-braun** [comment]
Take a look here: https://github.com/syndesisio/syndesis-quickstarts

**Comment by pankaj358** [comment]
Thank you.
