### ISSUE TITLE
Rename Apicurito

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#5390]
See also **https://issues.jboss.org/browse/ENTESB-11565**

## This is a...

<pre><code>
[ x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Rename UI elements exposing Apicurtio to API Designer
and 
Standalone API Designer

**Comment by heiko-braun** [comment]
@TovaCohen This also impacts docs.

**Comment by TovaCohen** [comment]
Thanks for letting me know about this. This has a small impact on Fuse Online doc, but a bigger impact on the doc for the Red Hat Integration product. So I'm glad to see this moved to 7.5.

**Comment by TovaCohen** [comment]
Fuse Online Jira for updating the doc: 
https://issues.jboss.org/browse/FUSEDOC-3248

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11565**
