### ISSUE TITLE
Swagger dataShape's kind enum is different from the one used in the app

### ISSUE THREAD

**Issue by riccardo-forina** [syndesisio/syndesis#5391]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
[x] Tech debt
</code></pre>

## Description

This is the `stepKind` definition from the Swagger file:
```json
"DataShape": {
      "type": "object",
      "properties": {
        ...cut..
        "kind": {
          "type": "string",
          "enum": [
            "ANY",
            "JAVA",
            "JSON_SCHEMA",
            "JSON_INSTANCE",
            "XML_SCHEMA",
            "XML_SCHEMA_INSPECTED",
            "XML_INSTANCE",
            "NONE"
          ]
        }   ...cut...
```

In the React codebase, it gets properly translated to this:
```ts
export interface DataShape {
    ...
    kind?: "ANY" | "JAVA" | "JSON_SCHEMA" | "JSON_INSTANCE" | "XML_SCHEMA" | "XML_SCHEMA_INSPECTED" | "XML_INSTANCE" | "NONE";
}
```

Unfortunately tho, the Angular app [uses this enum](https://github.com/syndesisio/syndesis/blob/08fbc208cc369c3b8dded0b452e8356640ac66fe/app/ui/src/app/platform/types/platform.models.ts#L155-L164) which has the values as lower case strings:
```ts
export enum DataShapeKinds {
  ANY = 'any',
  JAVA = 'java',
  JSON_SCHEMA = 'json-schema',
  JSON_INSTANCE = 'json-instance',
  XML_SCHEMA = 'xml-schema',
  XML_SCHEMA_INSPECTED = 'xml-schema-inspected',
  XML_INSTANCE = 'xml-instance',
  NONE = 'none'
}
```

This same interface has been ported over to the React codebase together with a number of helper functions we use to work with the models.

The problem is that since the React codebase uses the models as defined by the swagger file, we have type mismatch issues like this one:
![image](https://user-images.githubusercontent.com/966316/57906612-dc5df880-787a-11e9-821c-e7f594863944.png)

For the moment we have bypassed the problem converting both sides to lower case strings when doing the comparison, and shutting down the type check in the assignments, but this isn't really maintainable. 

Normally I'd simply update the enum to be in sync with the swagger definition (or get rid of the enum completely, since hardcoded strings as values of a union type field are type checked), but I'm wary of doing so without guidance. The app has been using the lower case version so far, and things just work™️, so maybe the lower case version is the right one?

What do you suggest doing here @zregvart @igarashitm? Can we update the enum to be in sync with the definition from the swagger? Or should we do the opposite, so update the swagger to be in sync with what the UI has been using in the last year?

CC @gashcrumb

**Comment by zregvart** [comment]
I think the enum in OpenAPI document should reflect the actual use of the value. We'd need some Swagger magic to get that in sync.

**Comment by gashcrumb** [comment]
Yeah, I ran into this in a big way with the describe data shape stuff as well, it's been a real thorn in the side, thanks for opening this!

I'd rather the swagger be updated to reflect the actual values, otherwise we'll introduce migration issues.

**Comment by gashcrumb** [comment]
[this](https://github.com/syndesisio/syndesis-react/pull/292/commits/e87505ece090597228b4af1b31fccb458ae1d331) is the reality of the situation :face_with_head_bandage:
