### ISSUE TITLE
Summit Fuse Feedback 

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#5398]
See also **https://issues.jboss.org/browse/ENTESB-11498**

## This is a...

<pre><code>
[x ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Epic to capture all the Fuse feedback from summit.

**Comment by tsykora** [comment]
Hello Gary @gaughan, will this epic become our priority for Fuse 7.5? I very like the luxury of having such customer/user feedback to work on.

**Comment by gaughan** [comment]
@tsykora Yes, well I hope so, the scope discussions have not begun.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11498**
