### ISSUE TITLE
SQL connector syntax validation

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#5400]
See also **https://issues.jboss.org/browse/ENTESB-11564**

## This is a...

<pre><code>
[ x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Limitations in the SQL connector are not giving enough detail on what subset of SQL is valid. 
SQL connector does not provide immediate SQL statement validation. (I don't mean the table schema, but simple SQL grammar validations)
We may need to expand our syntax for DV.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11564**
