### ISSUE TITLE
Split Step unclear that it relates to data

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#5402]
See also **https://issues.jboss.org/browse/ENTESB-11563**

## This is a...

<pre><code>
[x ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Split step, what am I splitting? (user response: ahhhh, Im splitting my DATA???) (Some users thought split means splitting the route instead of splitting data. Should be made clear in the UI)

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11563**
