### ISSUE TITLE
Data-shape validation needs to have a bigger scope (full integration)

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#5403]
See also **https://issues.jboss.org/browse/ENTESB-11562**

## This is a...

<pre><code>
[x ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
After introducing a new step (API) the shape changed. Users expected to be informed that it might be a good idea to split or map (they only see map)

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11562**
