### ISSUE TITLE
Indicate optional fields in mapping google sheets

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#5404]
See also **https://issues.jboss.org/browse/ENTESB-11561**

## This is a...

<pre><code>
[ x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Indicate optional variables in mapping, during the Google sheet mapping, there is variably called sheet id, this is optional would be nice to indicate that

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11561**
