### ISSUE TITLE
Combine step and mapping warnings

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#5405]
See also **https://issues.jboss.org/browse/ENTESB-11560**

## This is a...

<pre><code>
[ x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Aggregation was confusing, the data mapping was not clear that it needs to be setup before not after.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11560**
