### ISSUE TITLE
Adding new steps before mappings hides errors

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#5406]
See also **https://issues.jboss.org/browse/ENTESB-11559**

## This is a...

<pre><code>
[ x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Introducing new steps before mappings hides errors, only removing the mapping and add a new mapping fixes it.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11559**
