### ISSUE TITLE
Connector and connection ambiguity

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#5407]
See also **https://issues.jboss.org/browse/ENTESB-11558**

## This is a...

<pre><code>
[ x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Users do not immediately understand that they have to create a connection after they've imported a rest API definition. 
Adding an auto create checkbox, default to true may help.

**Comment by zregvart** [comment]
Also of note #5373, which if implemented would necessitate the connection creation.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11558**
