### ISSUE TITLE
Releasing 1.6.x fails

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#5417]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

We seem to be having issues [building the upgrade container](https://ci.fabric8.io/view/syndesis/job/syndesis-release-1.6.x/29/console).

**Comment by tplevko** [comment]
Verified
