### ISSUE TITLE
Duplicate extensions can be achieved when importing integrations

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#5420]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Relates to #5163 
Multiple extensions of the same extensionId shouldn't be present in Syndesis at the same time, but the importing process ignores this restriction and the user usually ends up with duplicates of the same extension, which can be only resolved by deleting *both* integrations and related extension (you have to delete both integrations to be able to delete the duplicate extension).

Steps to reproduce:
1. import set body extension
2. import integration using set body extension 

What is also interesting is if you remove both extensions and then import the integration you end up with having two integrations in Syndesis.

Another way to achieve this is by having two *different* integrations (importing the same integration twice only overwrites the original integration) which also causes this behavior.

**Comment by mmuzikar** [comment]
Adding link to sample integrations to reproduce: [https://drive.google.com/open?id=1rx8xAZXAHlA2Ng0lPy2q_JXPGZ7FZkXV](https://drive.google.com/open?id=1rx8xAZXAHlA2Ng0lPy2q_JXPGZ7FZkXV)

**Comment by dhirajsb** [comment]
This was a tricky issue and extensions import in integrations had to be rewritten to ignore ids altogether and use extensionIds and versions. 
I've added logic to compare extension maven versions to take the most recent version, either updating the syndesis instance or the imported integration appropriately. 
@mmuzikar please test PR #5735 with this use case and any other use cases you can think of?

**Comment by mmuzikar** [comment]
@dhirajsb can't think of other use cases when this might be a problem. I checked with multiple integrations and everything works as it should, you just saved me a lot of headaches when preparing tests using extensions, thanks :)
