### ISSUE TITLE
Datamapper - source/target values hidden under expandable "noname" item

### ISSUE THREAD

**Issue by mastepan** [syndesisio/syndesis#5425]
See also **https://issues.jboss.org/browse/ENTESB-11427**

## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
The elements in the Source mapping area (only this case) are hidden under an expandable element without any name. The "noname" element should not be there - it's confusing.

Other complication is the element doesn't have an id attribute value which makes automated testing difficult. All other named elements have their id values.

I suggest removing this element and make the underlying list visible by default.
![datamapperNoId](https://user-images.githubusercontent.com/8707251/58029182-5e208100-7b1c-11e9-9dac-c317eb54074e.png)

**Comment by mastepan** [comment]
still present on 1.7.8

**Comment by igarashitm** [comment]
Now `<div class="DocumentFieldDetailComponent" id="document-root" should be shown

**Comment by mastepan** [comment]
Yes that's great for testing, thanks. 
From a user's perspective it's still confusing to have seemingly empty list of attributes

**Comment by igarashitm** [comment]
Ah right, I forgot about that. Filed atlasmap/atlasmap#1084

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11427**
