### ISSUE TITLE
Integrate the React UI codebase into Syndesis 

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis#5426]
## This is a...

<pre><code>
[x ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

We need to move the code from https://github.com/syndesisio/syndesis-react to this repo.
The plan is to:
1. rename `ui` to `ui-angular`
1. making all fail and keep track of all the intervention point
1. fix all the pointers to go to `ui-react`
1. migrate all the issues from the `syndesis-react` repo

**Comment by riccardo-forina** [comment]
* update the proxy settings as by the latest findings (CC @zregvart who did the changes in the last few weeks)

**Comment by zregvart** [comment]
Are we're having the two side by side for a while? I'm not afraid of just straight replacing the `ui` with `ui-react`.
If we're going to have the two side by side, we should consider having a feature toggle to enable switching between the two.

**Comment by heiko-braun** [comment]
It would be good to have both running side by side, maybe even including two openshift routes.

**Comment by zregvart** [comment]
I think this should be an epic with a number of subtasks:
- Implement changes to `syndesis` tool build and CI
- Build syndesis-ui image with both Angular and React UIs
- Configure oauth-proxy for both Angular and React UIs
- Implement ability to switch between Angular and React UIs at runtime

**Comment by gashcrumb** [comment]
> Implement ability to switch between Angular and React UIs at runtime

It's better to be able to run them alongside each other if possible, I'm constantly comparing 'em, and I'm sure I won't be the only one.

**Comment by gashcrumb** [comment]
but yeah, :+1: on an epic, it's not exactly a small task :smile:

**Comment by heiko-braun** [comment]
@paoloantinori had some concerns about `Implement ability to switch between Angular and React UIs at runtime`, but otherwise I agree – we should turn this into an Epic. I'd say we leave it to the UI team to decide if the want to keep both UI's in the same final image or just carry on with React.

**Comment by paoloantinori** [comment]
So the current status of this is:
- code have been merged on syndesis main repo
- new updates still happening on syndesis-react and manually synched (simple rebase)

- I'm in the process of configuring staging 2 to support both the old and the new frontend and I need @zregvart help for this.

**Comment by gashcrumb** [comment]
I think this is done, no?

**Comment by mastepan** [comment]
@gashcrumb anything to check on this by the QE? If no, add ignore/qe label, reopen otherwise please. Thanks.

**Comment by riccardo-forina** [comment]
Sorry! Label added. Nothing to check in particular about this, I mean, there are already plenty of related issues anyway 😅
