### ISSUE TITLE
Provide instructions about the authentication type in the new API client wizard

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#5429]
See also **https://issues.jboss.org/browse/ENTESB-11474**

## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When I create API client connector with lets say basic security authentication, creating this connector does not show the authentication type anymore. 

Old screenshot:
![screenshot_20190521_131105](https://user-images.githubusercontent.com/14313995/58091481-f3c61a00-7bc9-11e9-8a76-824819df3fcd.png)

Current version:
![screenshot_20190521_131115](https://user-images.githubusercontent.com/14313995/58091496-faed2800-7bc9-11e9-80d4-d1049c5f9da6.png)

**Comment by heiko-braun** [comment]
@zregvart Is this related to your recent changes?

**Comment by zregvart** [comment]
Yes, and intentionally. The type of authentication determines what kind of connection is to be created, this is a user choice when creating the API client connector, so supporting multiple authentications when creating a connection doesn't make much sense to me, since it was the user that has chosen the authentication type in the API client connector wizard in the first place.

**Comment by mcada** [comment]
@zregvart I agree with you but can we add a note about selected authentication type when creating the connection?

**Comment by zregvart** [comment]
I am very familiar with the flow and what's needed from me in when defining the API connector, so I'm most likely blind to the fact that it might not be too clear.

We can add some text when defining the API connector, for example on this screen here:

![Screenshot_2019-05-23 Syndesis](https://user-images.githubusercontent.com/1306050/58239686-ca33fc80-7d49-11e9-8f5e-e3ca014dd5e9.png)

Do you think that would work?

**Comment by mcada** [comment]
Yes, sure!

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11474**
