### ISSUE TITLE
Remove examples from connectors

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#543]
They just make the build longer (objectively not by much), and we don't use them at runtime. Not sure if there is any other use for them.

**Comment by KurtStam** [comment]
It helped me understanding how the connectors work. My vote is to keep them.

**Comment by oscerd** [comment]
Maybe it would be a good idea to maintain the examples somewhere else. I believe they are useful to understand how the connectors work.

**Comment by zregvart** [comment]
@oscerd yeah I've created #828 and I'll move the removed examples there (at some point), also they need updating: Salesforce connector that creates/updates specifically Salesforce Contact object was removed.
