### ISSUE TITLE
Unable to find adapter for servicenow

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#5430]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Same as https://github.com/syndesisio/syndesis/issues/5311
Trying to add any servicenow step results in the following message:
![screenshot_20190521_133459](https://user-images.githubusercontent.com/14313995/58092912-8caa6480-7bcd-11e9-989e-6b56898a9b45.png)

**Comment by heiko-braun** [comment]
@christophd Can you take care of this one as well?

**Comment by christophd** [comment]
Sure! Should not be a big issue

**Comment by mcada** [comment]
Verified with:

Syndesis:
    1.7-SNAPSHOT
Build ID:
    458c1ddc-b735-4668-8462-a8177ece2ab6
Commit ID:
    dc379e809595980889e1c8358f123735fa25bad3
