### ISSUE TITLE
Scale Komodo to 0 by default

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#5432]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Once we merge Komodo changes to Syndesis template (#5358) we should scale it to 0 by default.

Also we need to document how to scale it to 1 to enable Data virtualization feature.

**Comment by tplevko** [comment]
Verified
