### ISSUE TITLE
Backport Google Sheets Camel component to Fuse repo

### ISSUE THREAD

**Issue by christophd** [syndesisio/syndesis#5444]
Google Sheets connector has its Camel component inline and that is maintained in Syndesis repo. We need to move this to Camel fuse repository.

**Comment by christophd** [comment]
References https://issues.jboss.org/browse/ENTESB-10672

**Comment by christophd** [comment]
Should be moved to Camel repository https://github.com/jboss-fuse/camel/tree/2.21.x.redhat-7-x/components

**Comment by mastepan** [comment]
@christophd anything here for QE to check? Add ignore/QE label otherwise please. Thanks.

**Comment by tplevko** [comment]
The move to camel repository already took place, I think we can consider this to be verified. Closing.

**Comment by christophd** [comment]
@mastepan sorry just returning from PTO. Agreed this should be verified along the way by now.
