### ISSUE TITLE
Tech extension: extension definition json schema

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#545]
we should have a json schema to validate the extension definition

**Comment by nicolaferraro** [comment]
Do we need to add a json schema to the proposal doc or we need to generate a json schema and ship it with the model?
(and in case the response is 2, why don't we just use bean validation?)

**Comment by lburgazzoli** [comment]
@lhein is it ok to provide a jar with bean validation stuffs so you can use it to validate the extension definition or you need a json schema ?

**Comment by apupier** [comment]
Having a json schema will allow to have auto-completion and validation of the json file.

But I noticed that it is possible to define everything in pom.xml, is it still planned to allow/recommend users to use the json file? 

> (and in case the response is 2, why don't we just use bean validation?)

what is the link of a "bean validation" with the extension definition?

**Comment by lhein** [comment]
You cannot define everything in the pom.xml. It is just used for the extension details, not the extension definition itself like steps, actions, etc.

**Comment by apupier** [comment]
> You cannot define everything in the pom.xml. It is just used for the extension details, not the extension definition itself like steps, actions, etc.

**Comment by nicolaferraro** [comment]
So, I though you needed the json schema to validate the object, not to define it.
How will we share the json schema object? Should we put it in the tech-extension documentation or we can bundle it in a specific jar file, so that it will be versioned together with syndesis?

**Comment by lburgazzoli** [comment]
maybe we can put it into the rest/model artifact as resource with the same "path" as the Extension object ?

**Comment by apupier** [comment]
I know that schemas are usually available through internet.
Having it also in an artifact would be great as it allows to have access to it offline

**Comment by apupier** [comment]
another question on the subject which was asked during one call was: how to specify the schema to use? Is it possible to do it in the file itself? Or do we need to provide a specific filename? (extension-definition.json might be collide to other tools, no? What about extension-definition.syndesis.json for instance?)

**Comment by nicolaferraro** [comment]
Yes, we can agree on a specific file name, so that it can be loaded at runtime.
I'd go for including it in the `io.syndesis:model` jar with a name of `syndesis-extension-definition-schema.json` in the root of the jar.

**Comment by apupier** [comment]
the specific file name that I was mentioning is for model json file which is described by the json schema that you are proposing to name syndesis-extension-definition-schema.json
(and the name for the json schema is fine)

**Comment by nicolaferraro** [comment]
Ok, what you mean by "model json" file? I thought we were talking about only one file (the schema) that can be used to both validate and define a object.

**Comment by apupier** [comment]
During last call with Luca and Lars, we said that we don't know if we can put the schema reference directly inside the json mode file. As far as we know, it seems that it is not possible. It seems that usually, the matching between a json file and its schema is done by looking for the complete name of the json file.
If it is really case, we will need to have a very specific name for the json model file to be able to map the schema.

**Comment by nicolaferraro** [comment]
Yes, there's no standard way to specify the schema of a json file inside the json file itself, so matching should be done in some other ways.
What do you suggest as name for the schema, so that the tooling can find it easily in the syndesis model jar?

**Comment by apupier** [comment]
> What do you suggest as name for the schema, so that the tooling can find it easily in the syndesis model jar?
for the schema, the name that you proposed is fine: syndesis-extension-definition-schema.json
