### ISSUE TITLE
[Conditional-Flow] User defined output data shape

### ISSUE THREAD

**Issue by christophd** [syndesisio/syndesis#5456]
Conditional flows step should be handled as "shapeless connection" so the user is prompted to provide a shape when the step is added to the flow.

When the user provides an output shape for the conditional flow step all flows added to this step must produce this very same output.

In case a subsequent step already exists, the UI should offers also an option to adopt the input shape of that subsequent step.

When a shape is given all conditional flows have this as fixed finish step shape. This ensures that all conditional flows produce the same output and we can continue with the integration flow after the conditional flows step accessing this output.

**Comment by gashcrumb** [comment]
Sorry I had the above comment open but not posted for like an hour :-)
