### ISSUE TITLE
Test Syndesis with Camel 3

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#5460]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Given that there are a number of Camel 3 milestones and a release coming this year we should test with Camel 3 milestones to provide feedback to have any issues resolved before Camel 3 release.

We can do this at several levels:
 - just building with a Camel 3 milestone or snapshot version
 - running end to end tests against a version using Camel 3
 - having a CI job to test (nightly) a version of Syndesis against Camel 3 snapshot

**Comment by lburgazzoli** [comment]
Some effort have already been done here: https://github.com/syndesisio/syndesis/issues/4769

**Comment by zregvart** [comment]
I thought there was an issue, could not find it at the time, closing this as a duplicate of #4769
