### ISSUE TITLE
Support metadata suggestions in AWS SQS/SNS

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#5464]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

When I use a AWS SQS/SNS connector I need to type in names of topics, I'd like to pick from a list of existing topics, if there are any topics that are already defined. This can be done by extending the metadata for the SQS/SNS connectors to fetch topics from from AWS and populate the `enum` property with the suggested values.

**Comment by avano** [comment]
works as expected
