### ISSUE TITLE
Daily release builds take a long time

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#5468]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

I was able to narrow this down to this command taking a lot of CPU:
```
/mnt/hudson_workspace/workspace/syndesis-release-daily/app/ui-react/node/node --max-old-space-size=2048 /mnt/hudson_workspace/workspace/syndesis-release-daily/app/ui-react/node_modules/fork-ts-checker-webpack-plugin/lib/service.js
```

And with @riccardo-forina's help narrowed it down to this issue https://github.com/facebook/create-react-app/issues/6792.

**Comment by zregvart** [comment]
Seems we're running out of memory and this results in the build waiting to finish indefinitely. More details here: https://gist.github.com/zregvart/c9d2ff894f1de9d3bf7a278cd4412c6e

**Comment by heiko-braun** [comment]
Is it related to the react build steps?

**Comment by zregvart** [comment]
@heiko-braun yes this was introduced with React UI.

**Comment by zregvart** [comment]
Main culprit seems to be craco, these two processes use 2GB of RSS:
```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
slave    15630  101 29.5 3315912 1145388 pts/0 Rl+  09:22   2:12 /mnt/hudson_workspace/workspace/syndesis-release-daily/app/ui-react/node/node /mnt/hudson_workspace/workspace/syndesis-release-daily/app/ui-react/node_modules/@craco/craco/scripts/build.js --verbose
slave    15654 66.1 30.4 1715108 1181092 pts/0 Sl+  09:22   1:23 /mnt/hudson_workspace/workspace/syndesis-release-daily/app/ui-react/node/node --max-old-space-size=2048 /mnt/hudson_workspace/workspace/syndesis-release-daily/app/ui-react/node_modules/fork-ts-checker-webpack-plugin/lib/service.js
```

**Comment by tplevko** [comment]
This is also causing problems on QE side - we use daily builds for execution of our nightly jobs, any help with solving this would be highly appreciated.

**Comment by paoloantinori** [comment]
We are currently investigating in this. Although I've been able to build `ui-react` locally with less of 300MiB dedicate to the process, so I'm really not sure what's going on.

I've also noticed on Zoran output the `--verbose` flag, wondering if that has any role in this.

**Comment by zregvart** [comment]
> I've also noticed on Zoran output the `--verbose` flag, wondering if that has any role in this.

That was to try to get more messages out of logging to have it easier to debug. This issue happens regardless of the `--verbose` flag [on the CI](https://ci.fabric8.io/view/syndesis/job/syndesis-release-daily/).

**Comment by zregvart** [comment]
@paoloantinori I can't reproduce this issue using [your instructions](https://gist.github.com/paoloantinori/3e1ed14f75c1e3e332bce8b11b34706c), I can reproduce a memory issue, not the same memory issue, of getting killed by the OOM killer when running with 2GB of RAM and without any swap.

This is how I tried to reproduce the issue locally:

Ran a Docker container specified Dockerfile, to create the `build` image:
```Dockerfile
FROM docker.io/adoptopenjdk:8-hotspot

RUN apt-get update -y \
    && apt-get install -y git \
    && rm -rf /var/lib/apt/lists/*
```

Like this:
```shell
$ docker run -it -m 2G --memory-swappiness 0 --privileged -u $(id -u):$(id -g) --ulimit nofile=122880:122880 -v `pwd`:/work -e HOME=/tmp build /bin/bash`
```

And in the container I ran;
```shell
$ cd /work; ./mvnw -f ui-react clean verify
```

That leads me to believe that in your case the 300MB of memory was not the total amount of memory used, but also (probably a large) amount of swap was used.

**Comment by paoloantinori** [comment]
I've missed this message. Good to know, I'll try to tweak the setup just to
learn something new

**Comment by zregvart** [comment]
I managed to get a daily build (1.7.1-20190605), closing this.
