### ISSUE TITLE
Update productised Camel K version to include recent changes

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/syndesis#5469]

**Comment by heiko-braun** [comment]
@nicolaferraro @valdar Do we have eveything in place for another Camel K release? Do we have any upstream dependencies or will we release from an internal repo?

**Comment by valdar** [comment]
@heiko-braun Upstream camel-k release?

**Comment by heiko-braun** [comment]
Yes, I wonder if we depen on another Apache release for inclusion in 7.4

**Comment by valdar** [comment]
We also have downstream builds already in use: https://github.com/syndesisio/syndesis/blob/master/app/pom.xml#L79 although for the camel-k operator itself there are not yet downstream stored artifacts outside of the final released one.

So we are not strictly dependent on upstream release, it would be good to have one though.

@nicolaferraro wdyt?

**Comment by valdar** [comment]
So to summarise before closing:
- *jboss-fuse/camel-k:* `master` branch has been aligned to upstream and from now on will target camel 3 (so will be used for Fuse 8). The product branch `0.3.x.redhat-7-x` has been created form `0.3.4` tag and some useful commits have been backported from @nicolaferraro. From now on this is the branch to be productized for Fuse 7
- *jboss-fuse/camel-k-runtime:* `master` branch has been aligned to upstream and from now on will target camel 3 (so will be used for Fuse 8). The product branch for Fuse 7 will be `0.3.x.redhat-7-x` has been created as a copy of `camel-2.x` branch which is upstream effort to support camel 2 up until the first stable release of camel 3. From there on it is just downstream maintenance to support camel 2 in `camel-k-runtime`

I have also updated Jenkins pipeline to reflect this and double checked with @orpiske and @cunningt if everything was ok. @orpiske and @cunningt, please say if I misunderstood/forgot something thanks.

**Comment by orpiske** [comment]
@valdar thanks, this looks OK to me.

**Comment by mastepan** [comment]
@valdar please add ignore/qe label if there's nothing to check by the QE. Reopen otherwise. Thanks.
