### ISSUE TITLE
No output when Basic Filter or Advanced Filter doesn't pass

### ISSUE THREAD

**Issue by mkralik3** [syndesisio/syndesis#5479]
See also **https://issues.jboss.org/browse/ENTESB-11473**

## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When Basic Filter or Advanced Filter doesn't pass, the output is "No output". 
From the user point of view, it will be nice to see what data doesn't meet the filter.
The activity log when the filters pass:
![image](https://user-images.githubusercontent.com/16251792/58430184-a0ac0580-80a8-11e9-8d75-8582552b88fa.png)
The activity log when the basic filter doesn't pass:
![image](https://user-images.githubusercontent.com/16251792/58430298-131ce580-80a9-11e9-9465-0729e4631aeb.png)

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11473**
