### ISSUE TITLE
[React-ui] unable to create connections using oauth-flow 

### ISSUE THREAD

**Issue by mmelko** [syndesisio/syndesis#5482]
## This is a...

<pre><code>
[ ] Feature request
[x ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
This feature isn't implemented yet in react-ui.  Using this issue as placeholder for: https://github.com/syndesisio/syndesis-react/issues/136

**Comment by paoloantinori** [comment]
https://trello.com/c/0kWnLlpj/42-s-oauth-support

**Comment by mmuzikar** [comment]
@paoloantinori any update regarding this issue? QE uses OAuth in many tests.

**Comment by riccardo-forina** [comment]
Working on this, I'd say it's almost done but the oauth connection flow with its cookie setting dance doesn't want to behave...

**Comment by riccardo-forina** [comment]
So [PR 426](https://github.com/syndesisio/syndesis-react/pull/426) added support for creating oauth based connections. We still have to do the details page, but you should have enough to start your testing now.

The only thing, it's not on the main syndesis repo yet. Would that be a problem?

**Comment by riccardo-forina** [comment]
Right, this has been merged.

**Comment by mastepan** [comment]
@mmuzikar has this issue been verified?

**Comment by mmuzikar** [comment]
@mastepan definitely
