### ISSUE TITLE
[Conditional Flow] First condition can not be deleted

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#5484]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
First condition can not be removed - there is no delete icon:

![screenshot_20190528_102131](https://user-images.githubusercontent.com/14313995/58462635-90d90380-8132-11e9-865d-ff54d3a59121.png)

**Comment by gashcrumb** [comment]
We actually have the same kinda of problem with the basic filter step, where it's an array and it should contain at least 1 value in it.

We could have the trash icon on the 1st row too and then just ensure in the click handler for that trash icon just adds an empty new row if that array is empty.

**Comment by gashcrumb** [comment]
Actually, don't we always want at least 1 condition?  I guess the idea is the user just changes whatever value is there.

**Comment by dongniwang** [comment]
Yeah, I think we always want at least one condition for the conditional flow. And if we want no conditions, users should be able to just delete the conditional flow step.

**Comment by gashcrumb** [comment]
Makes sense to me.  I also think for consistency's sake we should follow the same pattern as the basic filter then which has a similar layout and behavior, so I don't think this is a bug but an enhancement.

**Comment by mcada** [comment]
No. I am sorry, but this is a bug. When I want to keep second condition by deleting the first one, I can not do it - I have to push first condition to second place and then delete it - this is just stupid.

**Comment by christophd** [comment]
I guess we could auto adjust the visibility of that 1st remove button. as long as we have more than one condition available the button is visible. When there is only one single last condition left the remove button is not displayed.

**Comment by gashcrumb** [comment]
Yup, that'd work fine, good call!  That's also an approach I can apply to the react codebase pretty easily.

**Comment by mcada** [comment]
@christophd perfect idea, I like that!
