### ISSUE TITLE
[Conditional Flow] There is no syntax example for conditions

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#5485]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Syndesis should be intuitive. Conditions are simple topic, but in our case user will be probably forced to browse documentation to find out what is the correct syntax and which keywords to use in conditions. We should add a help button which shows a window with syntax and examples of different conditions and available keywords. Or a link which opens a page with such information in a new tab.

**Comment by mastepan** [comment]
@mcada @christophd just checking. Is there anything that should be checked by QE?

**Comment by mcada** [comment]
@mastepan please open conditional flow step and check if the example present is sufficient
