### ISSUE TITLE
[Conditional Flow] make conditions drag'n'drop for rearranging their position

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#5486]
See also **https://issues.jboss.org/browse/ENTESB-11472**

## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
It's 2019 and our UX design is outdated and does not take advantage of comfortable features for users - what about drag'n'drop functionality with conditions instead of buttons to rearrange their position?

**Comment by zregvart** [comment]
cc @chirino :rofl:

**Comment by christophd** [comment]
@gaughan I think drag'n'drop will not make it into this release. I guess this is not keeping conditional flows away from GA state though.

**Comment by gaughan** [comment]
Thanks, I agree. I'm not sure if there are other items preventing GA?

**Comment by christophd** [comment]
@gaughan I think we have tackled all other things. I will show the status in the sprint demo.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11472**
