### ISSUE TITLE
[Conditional Flow] conditional flow inside of conditional flow

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#5487]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Do we support conditional flow inside of conditional flow? If so, we have to rework UI because it is not usable in such situation - basically it is not scalable with multiple conditional flows inside one. There is no button to go to parent condition, only primary flow. And if I add conditional flow into multiple conditions, it gets even more messy and navigation between them has to be done from primary flow or user has to remember names of the conditions.

**Comment by christophd** [comment]
> And if I add conditional flow into multiple conditions, it gets even more messy and navigation between them has to be done from primary flow

@mcada Can you please elaborate on this scenario? I do not know what you mean by `if I add conditional flow into multiple conditions`

Would it help to add user defined names to conditions? Display those in navigation drop down and in conditional flows configuration page?

**Comment by christophd** [comment]
Maybe we allow the user to provide a name to the conditional flow step itself, too? So we have a combination of conditional flow step name and condition name.

`MyConditionalFlows -> My1stCondition -> When ${body.task} contains 'foo'`

**Comment by mcada** [comment]
What I ment was adding new conditional flow step inside of one condition in existing conditional flow step. So it would look something like this:

webhook -> conditional flow 1 -> log

conditional flow 1: condition1, condition2, condition3

condition1: flow start -> conditional flow 2 -> flow end
.
.
.

conditional flow 2: condition 4, condition 5 condition 6


In current UI implementation you would get lost pretty quickly and navigation between those conditions would be really hard. I agree that some special selection/columns for conditions needs to exist and your suggested solution with simple UI changes may solve the issue.

**Comment by heiko-braun** [comment]
I think we should prevent nested conditional flows in the first release

**Comment by christophd** [comment]
@heiko-braun I think we would have the same situation when adding multiple conditional flows steps (in sequence) to the primary flow. So it is not exclusively bound to nesting conditional flows inside conditional flows.

Things get complex when you write complex integrations. I guess this is a quite common rule. The best solution is to teach the user to break things down to less complex integrations.

Of course we should make things as comfortable as possible but at the end the user is always able to do very complex things.

**Comment by heiko-braun** [comment]
@christophd yes, you are right. How would you suggested to proceed with this issue?

**Comment by christophd** [comment]
I think we should add some more clear separations between the different conditional flow steps in the top level drop down navigation. So we can group the conditions for each step and have a clear separation. In addition to that user defined naming of flows and steps would help here.
