### ISSUE TITLE
[Conditional Flow] multiple conditional steps share flows

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#5488]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When I want to use multiple conditional flow steps, they all share flows between each other:
![screenshot_20190528_104350](https://user-images.githubusercontent.com/14313995/58464173-80765800-8135-11e9-9d3b-3b84c8eb4b82.png)

I would expect that when I am inside of a conditional flow step, I can only navigate between its flows and UI does not offer all existing flows which have nothing incommon with the step I am currently editing.

**Comment by mcada** [comment]
I got it wrong - it is expected to show all the flows. But still - when I add multiple conditional flow steps, could we at least sort the flows in groups so we can easily distinguish between flows from different steps?

**Comment by christophd** [comment]
The top level navigation bar is for the whole integration. It is not linked to the current step being edited.

We could think of another navigation drop down within the step configuration page that is related to the conditional flow step being edited.

@dongniwang any thoughts?

**Comment by christophd** [comment]
@mcada I agree, some sort of separation lines in the top level navigation drop down will help I guess

**Comment by dongniwang** [comment]
A few ideas - 

1. Add a divider line or use indentation to indicate groups. 
2. When users are on the main integration, would it make more sense to let them navigate to the different flows via the actual conditional flow step? In other words, use the IVP to navigate to different sub-flows instead of the toolbar.

**Comment by riccardo-forina** [comment]
I'll just drop this: the IVP on "mobile" devices is hidden by default, and can't be shown in any way. The only safe areas are the header and the "body" of the editor.

I'm not saying we shouldn't add stuff to the IVP, but there should be alternate navigation available. Actually, I'd make the IVP the alternate navigation, but that's just my 2c :)

**Comment by christophd** [comment]
@dongniwang @riccardo-forina Sorry I have to ask this because it is not clear to me: What exactly is the IVP?

**Comment by riccardo-forina** [comment]
Oh right, it's the sidebar on the left, the one with all the steps.

**Comment by dongniwang** [comment]
I think the IVP (integration visualization panel) should not be hidden by default. That panel contains important information like data shape, can we investigate and find a way to surface that on "mobile" devices?

**Comment by mmuzikar** [comment]
In the new react UI there is only one set of flows displayed at a time and that's of the most recent conditional step. It looks like regression to me.

![image](https://user-images.githubusercontent.com/46345469/58963516-9a571100-87ad-11e9-8c0d-75998668da2d.png)
