### ISSUE TITLE
[Conditional Flow] manage new flow starts as a new integration

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#5491]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
This one is quite a blocker - for some reason new flow starts as an empty integration:
![out](https://user-images.githubusercontent.com/14313995/58470837-d69dc800-8142-11e9-8d36-8970a15238da.gif)

After that I am lost - cancel button does nothing and all I can do is cancel the whole create integration process and start over.

**Comment by mcada** [comment]
Just happened to me again and it broke the whole syndesis - I was not able to perform any action and had to close the browser tab.

**Comment by christophd** [comment]
Most likely there is some JavaScript error that causes the application to crash. We have to review the JavaScript console for errors to find out

**Comment by paoloantinori** [comment]
We have just switched to the React implementation for Conditional Flows.
Could you verify this?

**Comment by mcada** [comment]
Now every flow starts and looks as new integration - probably intended change. If so, we can close this one.

**Comment by gashcrumb** [comment]
Yeah, the handling of configuration vs linking is done a bit differently.  I think separating out the configuration of the conditions from actually linking to the flows saves us from some potentially tricky issues.  Thanks for verifying!
