### ISSUE TITLE
[Conditional Flow] add a button to get back to parent conditional flow

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#5492]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
There is no button to go back to parent conditional flow step when I am finished with implementation of one flow. I have to go to the primary flow and then select conditional flow step every time I want to edit/add new condition. This is very inconvenient. There should be a button which saves the condition implementation and gets you back to the step with conditions - next to the button which returns you to the primary flow:

![screenshot_20190528_130806](https://user-images.githubusercontent.com/14313995/58473730-a86fb680-8149-11e9-8438-0af6e6a9ca9a.png)

**Comment by heiko-braun** [comment]
> There is no button to go back to parent conditional flow step when I am finished with implementation of one flow

What is the button in the top right corner doing? It says `Back to primary flow`

**Comment by mcada** [comment]
@heiko-braun Primary flow here is the main integration flow:

![out](https://user-images.githubusercontent.com/14313995/58476362-d9071e80-8150-11e9-95c5-1293c8942633.gif)

**Comment by heiko-braun** [comment]
I see, do you want to get back to the list of conditions?

**Comment by mcada** [comment]
I think it would be much better if such option existed.

**Comment by gashcrumb** [comment]
I wonder if it'd make the most sense for that button to *always* go back to the conditional flow step.

**Comment by paoloantinori** [comment]
@dongniwang this requires your comment.

**Comment by dongniwang** [comment]
I understand the request. We need three kinds of navigation here:
1. Go back to the conditional flow step. That's for taking care of if users need to add/update/delete any conditions. 
2. Go back to the main integration. This is for when configuring additional steps and connections for the integration. 
3. Navigate between different conditions. This is for jumping between conditions. And we already have a dropdown for this. 
![Screen Shot 2019-05-29 at 10 13 08 AM](https://user-images.githubusercontent.com/24943812/58564436-eaa50080-81fa-11e9-9c7a-109c70b82d85.png)

So I think for addressing 1 & 2 above, we can set the back to go back to the conditional flow step.

**Comment by paoloantinori** [comment]
We have just switched to the React implementation for Conditional Flows.
Could you verify this?

**Comment by mcada** [comment]
This one is a tricky issue as it was partially fixed by the new design where you can only edit flows from the main integration view. But with more sophisticated scenario the whole integration breaks: add another conditional flow step inside existing flow - there is where a button "back to the parent flow step" is required, but it breaks the whole integration.

**Comment by dongniwang** [comment]
@mcada - thanks for the comment. Can you provide more information about what do you mean by 
> the whole integration breaks: add another conditional flow step inside existing flow

I'd be happy to set up a quick meeting so we can go through the use case you mentioned. Please let me know.

**Comment by gashcrumb** [comment]
So in the react impl we separated the list of links off to flows from the management of those conditions.  When you go back to the primary flow, you'd see all of the conditional steps available then, so then there's no need to go back to the actual conditional flow step.

Also I suspect we probably don't hide the conditional flow step yet when you're editing a sub-flow, so while it may be possible to nest the conditional flow step I don't think we're planning on supporting that.  Do I have that understanding right @christophd ?

**Comment by christophd** [comment]
From a technical perspective nesting conditional flow steps would be possible. If it is too much effort to make this comfortable to use from a usability perspective we can just hide it in a 1st version and add this some other release.

**Comment by christophd** [comment]
@mcada I assume we do not have these issues when multiple conditional flow steps are added to the primary flow, right?

**Comment by christophd** [comment]
I just reviewed the solution doc and it says nesting cbr steps is not in scope

**Comment by gashcrumb** [comment]
Yeah, I thought so, and I think it's worth preventing that in this first go simply because I think the navigation will become too complicated using the current approaches so far.  Given that we do have more real estate in that kinda root page of the editor we could definitely do some interesting things but I think it'd be safer to iterate on this.

**Comment by dongniwang** [comment]
Agreed on keeping it simple for now so we have more time to iterate on this - now that we have API provider, conditional flow as well as split/merge (collection), we have a strong interest in UX to evaluate and improve the experience of using these features. 

cc: @gaughan @syndesisio/uxd

**Comment by mcada** [comment]
@christophd multiple conditional flows in the primary flow break the whole integration:

![out](https://user-images.githubusercontent.com/14313995/59097970-42401c00-891f-11e9-9e29-541625ebb6d3.gif)

**Comment by gashcrumb** [comment]
Lemme check that, I made one on my minishift instance yesterday and I don't recall it behaving like that.

**Comment by gashcrumb** [comment]
@mcada can you raise a separate issue for that behavior?  I do see that I can create what looks like orphaned flows when editing a conditional flow, I think probably we'll tackle a lot of this while fixing #5608

**Comment by mcada** [comment]
Sure, here it is https://github.com/syndesisio/syndesis/issues/5636
