### ISSUE TITLE
SQL connector doesn't return generated IDs when added as start step

### ISSUE THREAD

**Issue by jsafarik** [syndesisio/syndesis#5493]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
follow-up to [#4466](https://github.com/syndesisio/syndesis/issues/4466), when performing the INSERT statement as a start step it doesn't return the generated IDs. that means:
 - Timer -> SQL (insert) -> Log works just fine, the log shows the generated ID
 - periodic SQL (insert) -> Log doesn't return anything

**Comment by zregvart** [comment]
cc @KurtStam

**Comment by heiko-braun** [comment]
@KurtStam Does this ring a bell?

**Comment by KurtStam** [comment]
Yeah - this is by (bad?) design. It is assumed that INSERT is not used as the start connection as you'd think you'd need an input param. This explains why it works ok when the timer is the first connection. Let me see if it makes sense to get rid of this difference in behavior.

**Comment by jsafarik** [comment]
Just tried to verify that this functionality was added in 1.7.6 (and just to be safe, with 1.8-SNAPSHOT as well), but it still doesn't return the keys. from the commit I understand that this feature should be added, am I trying it with the wrong version?

**Comment by jsafarik** [comment]
@KurtStam ^^

**Comment by KurtStam** [comment]
I think this is the scenario, which is working now.

<img width="822" alt="Screen Shot 2019-08-13 at 10 12 31 AM" src="https://user-images.githubusercontent.com/35576/62925591-f8f2c980-bdb2-11e9-899c-ebdae780c0d6.png">
<img width="1134" alt="Screen Shot 2019-08-13 at 10 12 44 AM" src="https://user-images.githubusercontent.com/35576/62925592-f8f2c980-bdb2-11e9-9042-80fb97715647.png">

**Comment by jsafarik** [comment]
Just verified this, in 1.8-SNAPSHOT this is working as supposed. @KurtStam thanks for the info that it is working now :)
