### ISSUE TITLE
[Conditional Flow] Conditions form layout is not great

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#5496]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When I have more conditions, the form with them does not look great:

![screenshot_20190528_152603](https://user-images.githubusercontent.com/14313995/58481647-1671a900-815d-11e9-8da8-0a81ae6b6613.png)

We are in the age of 4k monitors yet even on my FullHD monitor the rows and the text are small. I suggest a few things: Make it bigger, make every row clickable so I do not have to click small button to edit the condition flow, add an animation on mouse hover so the row under mouse is more visible and it is clear which will be selected on click. Also the table indentation feels wrong, maybe some smart borders or less white space would make wonders.

This is a deeper problem in syndesis design and I will try to push things forward in react-ui to make everything look better because at least from my pov syndesis design does not look professional and feels outdated. But in the mean time the least we can do is to make this form look better (the final react version of it), wdyt?

**Comment by gashcrumb** [comment]
Keep in mind that 4k monitors are not our only resolution to target :-)

The app also needs to work at lower resolutions to support web casts, old projectors at customer sites, look nice on blue jeans, and so on.

I think the overall plan is that migrating to PF4 is gonna help this situation.

**Comment by mcada** [comment]
Sure, modern web UI counts with different resolutions and devices - that is why responsive design exists and we should use it.

**Comment by paoloantinori** [comment]
"is not great" sounds to me as a definition of an enhancement.

Re-labelling

**Comment by mcada** [comment]
@paoloantinori It does not look great - yes, 80% of this screen is white space. I am not happy with new features which look like that - are you?

**Comment by mcada** [comment]
The issue is obsolete, react-ui solved the problem :)
