### ISSUE TITLE
[react-ui] Datamapper step is missing

### ISSUE THREAD

**Issue by mmelko** [syndesisio/syndesis#5498]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
No datamapper step in integration where DM is required: 
![screenshot_20190528_155744](https://user-images.githubusercontent.com/6814482/58484618-b4b43d80-8162-11e9-8994-4d2303687959.png)

**Comment by tplevko** [comment]
@paoloantinori QE test migration is blocked by this.

**Comment by riccardo-forina** [comment]
Thanks. As an alternative option, the warning icon and link to create the data mapping step should be visible in the previous page, the "Add to integration" one

**Comment by paoloantinori** [comment]
![Screenshot from 2019-05-28 18-21-35](https://user-images.githubusercontent.com/1520602/58494557-a3c0f780-8175-11e9-9a7b-5cfb74a70f02.png)

Far from ideal, but as an interim solution the mapping screen can be accessed via this link.

**Comment by gashcrumb** [comment]
No "Advanced Filter" either, that should be available as well.

**Comment by paoloantinori** [comment]
Just tried this, from db to db and I cannot see it:

![Screenshot from 2019-05-30 09-48-05](https://user-images.githubusercontent.com/1520602/58617296-0e7e4a00-82c0-11e9-93be-f2d55577a2a1.png)

**Comment by riccardo-forina** [comment]
Ok verified this with Paolo, the thing is working it's just staging that's not in sync with the latest changes.
