### ISSUE TITLE
[react-ui] Unnecessary step page in actions when configuration isn't needed

### ISSUE THREAD

**Issue by mmelko** [syndesisio/syndesis#5499]
See also **https://issues.jboss.org/browse/ENTESB-11426**

## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
I believe showing this page isn't necessary at all. 
![screenshot_20190528_155719](https://user-images.githubusercontent.com/6814482/58484859-373cfd00-8163-11e9-8613-48fbd6dfa6fe.png)

**Comment by gashcrumb** [comment]
I have https://github.com/syndesisio/syndesis-react/issues/319 for this already.

**Comment by heiko-braun** [comment]
@gashcrumb That's good, please keep it redundant. We agreed with QE to use this issue tracker for any QE filed issue regarding React, knowing that the other repository is a temporary solution.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11426**
