### ISSUE TITLE
[react-ui] blank panel at bottom

### ISSUE THREAD

**Issue by mmelko** [syndesisio/syndesis#5500]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
I'm not a designer but big white panel feels like there there is missing something or something is hidden behind that panel. I'd suggest add some footer. 
![screenshot_20190528_120357](https://user-images.githubusercontent.com/6814482/58484941-5cca0680-8163-11e9-87c6-ee5283be28f5.png)

**Comment by riccardo-forina** [comment]
It's an app-wide glitch that has been fixed in the API Provider PR.
