### ISSUE TITLE
[Angular] [Conditional Flow] done/cancel buttons are not aligned correctly

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#5502]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
`Cancel` button is slightly higher than `Done` button:

![screenshot_20190528_165604](https://user-images.githubusercontent.com/14313995/58488448-a7e71800-8169-11e9-9720-f4f0d0514ae7.png)

**Comment by paoloantinori** [comment]
We have just switched to the React implementation for Conditional Flows.
Could you verify this?

**Comment by mcada** [comment]
Cancel button was removed - not sure if intended - if so, we can close this issue.
