### ISSUE TITLE
[React-ui] Unable to publish integration

### ISSUE THREAD

**Issue by mmelko** [syndesisio/syndesis#5507]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
`Unhandled rejection` after setting the name and publishing simple integration

![screenshot_20190529_085222](https://user-images.githubusercontent.com/6814482/58535909-571a0280-81ef-11e9-9b8f-b9ba68422956.png)

**Comment by riccardo-forina** [comment]
https://github.com/syndesisio/syndesis-react/pull/363

This should fix it
