### ISSUE TITLE
Require confirmation when changing operationId in API provider

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#5513]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
There is no warning that changing operationId leads to the flow tied to that Id will be lost, a conformation window should be displayed and tell the user that this can lead to losing part of their integration. OR the flow should be remapped to use the new operationId.

Current behavior:
![Peek 2019-05-29 13-44](https://user-images.githubusercontent.com/46345469/58555165-159e4d00-8219-11e9-9f6e-45010adde68a.gif)

**Comment by dongniwang** [comment]
Agreed we should display a confirmation modal or better yet we should capture a change log in the modal or some sort so users are aware of the changes that they're bringing back to the integration. Is that something we can provide?
