### ISSUE TITLE
Ambiguity of Cancel in API provider

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#5514]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
User is able to review the API specification but the save button is enabled only if the specification was changed, because of how the cancel button works in different fashion across Syndesis I personally associate it with canceling the whole operation i.e. API provider case cancel would mean "I don't want to create this integration, I changed my mind". I believe the Save button should be enabled even when no changes were made.

@syndesisio/uxd Can someone please leave their opinion about this issue? 
I am also attaching a link of this behavior in action (it's mainly for other issue that this but it showcases it quite well I think):
![Peek 2019-05-29 14-00](https://user-images.githubusercontent.com/46345469/58556001-3f587380-821b-11e9-8b04-96c708652aa2.gif)

**Comment by dongniwang** [comment]
This set of Cancel and Save is for editing API definition only as they're placed within the API editor screen. So the Cancel should safely get you back to the Review Action step. 

You can also use the Back link on the far left (next to the API definition link) to get back to the previous screen.

**Comment by mmuzikar** [comment]
Oh, didn't even see that Back link, because every other button is placed on the right hand side. So it didn't even occur to me that some navigation could be placed on left. And I think that might be a problem for more people as well.
