### ISSUE TITLE
[Conditional Flow] conditional flow step is broken when used inside of API provider

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#5515]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Using conditional step breaks API provider - there may be more issues but I will leave it as one as this may be a complex problem.

![out](https://user-images.githubusercontent.com/14313995/58557791-8ba5b280-821f-11e9-8d61-86e516ea9ee4.gif)

When I click on the cancel button at the end of the gif and edit the integration again, there is one more operation in operation count (it probably thinks that the condition == API provider operation), but all the operations are gone:

![screenshot_20190529_144234](https://user-images.githubusercontent.com/14313995/58558063-23a39c00-8220-11e9-8d0f-0aff417c5305.png)

**Comment by paoloantinori** [comment]
We have just switched to the React implementation for Conditional Flows.
Could you verify this?

**Comment by mcada** [comment]
Still broken.

**Comment by mastepan** [comment]
@gashcrumb @heiko-braun why pure-bot closed this issue and what we can do with that? It's repetitive problem for the QE. It's even more critical for P0 issues when we lose track of them.

**Comment by christophd** [comment]
@mastepan so is this then being verified once more by QE? If so we should move it to done state. At the moment it is in inbox and I am not sure if there is any action required.

**Comment by tplevko** [comment]
The fix seems to be in place, so @christophd you are right - it should be in the done state.
