### ISSUE TITLE
[Conditional Flow] misaligned label when editing name of the flow

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#5519]
See also **https://issues.jboss.org/browse/ENTESB-11425**

## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
The `Flow` label jumps down when editing name of the flow. Also the dividers in the same row have different sizes, it would be nice to fix it in react UI.

![screenshot_20190530_110945](https://user-images.githubusercontent.com/14313995/58622245-78502100-82cb-11e9-907c-ef66e4495b8b.png)

**Comment by christophd** [comment]
I do not see this on my machine (Mac OS, Safari or Chrome) @mcada what browser are you using?

**Comment by mcada** [comment]
@christophd True, when I tried chrome it is good. Looks like it is only broken on up-to-date Firefox.

**Comment by paoloantinori** [comment]
We have just switched to the React implementation for Conditional Flows.
Could you verify this?

**Comment by mcada** [comment]
I can not even assign a name to a flow, not sure if it is what we wanted.

**Comment by christophd** [comment]
@riccardo-forina @gashcrumb is editing of the flow name still possible in react code base? Maybe we also should review the issue in general in order to see if this became obsolete.

**Comment by gashcrumb** [comment]
I think not, I don't recall that they were intended to be edit-able, but should that be the case then we should get an issue going and add it.

**Comment by christophd** [comment]
@gaughan is renaming of flows an intended feature that we should add to the react code base? It has been there in Angular but we are not sure if this has ever been intended to have editable flow names

**Comment by gaughan** [comment]
Its a nice to have for me, if it causes an issue let me know cc @dongniwang

**Comment by dongniwang** [comment]
Let me know if we need a design recommendation for rename a flow. @christophd @gashcrumb

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11425**

**Comment by mcada** [comment]
No product priority, reopening upstream issue. Nice to have.
