### ISSUE TITLE
API Client not working if multiple http compatible components are found in the camel registry or classpath

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#5521]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

The rest-swagger connector registers its own component in the camel context but does not enforce the underlying camel component to use it and this could lead to unexpected behaviours when multiple http compatible components are found in the Camel Registry. In case of multiple API Client connection used inside the same integration it could be even worse because each connection could pick up a different http compatible component.

**Comment by mmuzikar** [comment]
@lburgazzoli Any pointers to how QE should test this issue? This seems like internal thing to me.

**Comment by lburgazzoli** [comment]
yes it is more internal thing, but to test it you can do test something like 
- api-provider -> http
- webhook -> http-client

**Comment by mmuzikar** [comment]
Thanks @lburgazzoli tried both today and didn't encounter any issues.
