### ISSUE TITLE
Template Step Fails to update the input specification when changed

### ISSUE THREAD

**Issue by phantomjinx** [syndesisio/syndesis#5526]
## This is a...

<pre><code>
[ ] Feature request
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
1. Create a new integration, eg. between odata & log
1. Add a template step between the 2 connections
1. Enter text in the template such as Candidate: {{LastName}} {{FirstName}}
1. Click Done
1. Create a new mapping step between odata & template. Only 'LastName' appears in the target mapping.

**Comment by phantomjinx** [comment]
This was an odd one since the code (angular-ui) generating the input specification of the template step has not changed. However, this is what is happening:
1. The input datashape is re-created as a key event change, meaning after {{LastName}} is successfully typed by the user, that symbol is passed out as part of the action.descriptor.inputDataShape. This is the first time that the action is created.
1. As more of the text is typed into the editor, the event is fired and new versions of the inputDataShape are sent out as part of the action. The handling of this event is done by the [current-flow.service](https://github.com/syndesisio/syndesis/blob/master/app/ui-angular/src/app/integration/edit-page/current-flow.service.ts#L538), which sets the new step into the flow of the integration.
1. Before assigning the flow, the _setActionOnStep_ function is [called](https://github.com/syndesisio/syndesis/blob/master/app/ui-angular/src/app/integration/edit-page/current-flow.service.ts#L541). This is where the problem [lies](https://github.com/syndesisio/syndesis/blob/master/app/ui-angular/src/app/integration/edit-page/flow-functions.ts#L346). Since the generated action has now id then both the original and newly generated actions are undefined hence this function always returns the original step not including the new input datashape.

Questions:
- Should the templater code include an action id? If so, how should that be generated (based on datashapes & other parts of the action)?
- Should the setActionOnStep function be fixed to check whether an id exists and not end up comparing 'undefined' with 'undefined'?

@gashcrumb

**Comment by gashcrumb** [comment]
Yeah, the difficulty here is that setting the data shape is done in a kind of out-of-band way, the data mapper host component also has to do this.  Ideally that data shape could be pass back to the step-configure component, so it could be set on the step at the same time as the configuration for the template step is set.

But I dunno, it might not be worth that level of refactoring.  Barring that:

> Should the templater code include an action id? If so, how should that be generated (based on datashapes & other parts of the action)?

Yeah, it should set the `id` property on the action.  There's a `key()` function [you can import](https://github.com/syndesisio/syndesis/blob/master/app/ui-angular/src/app/integration/edit-page/flow-functions.ts#L9) that just generates a unique ID, it's used everywhere.

> Should the setActionOnStep function be fixed to check whether an id exists and not end up comparing 'undefined' with 'undefined'?

I think if we just ensure the id is set that should be enough, this will even ensure existing template steps in existing integrations would eventually be updated properly.

**Comment by paoloantinori** [comment]
is this error on angular, react or both?

**Comment by phantomjinx** [comment]
@paoloantinori 
Yes it is. Both code sources are identical in the _setActionOnStep()_ function.

**Comment by phantomjinx** [comment]
Fixed by @gashcrumb.
https://github.com/syndesisio/syndesis/commit/52d47428863796037ffa8af26632bb9500e281f5#diff-50bac496ca1b20cc62dd08e516cf3353R183
Thx!

**Comment by mmuzikar** [comment]
Verified
