### ISSUE TITLE
Wrong schema in the default postgres connection

### ISSUE THREAD

**Issue by asmigala** [syndesisio/syndesis#5528]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
The `PostgresDB` connection defined in syndesis by default has the wrong schema set - should be `public` instead of `sampledb` (which is the name of the database, not schema). As far as I can tell, it's not used anywhere in syndesis, since the database steps work with either value - the only problem is that Data Virtualization cannot import the sample db out of the box, because it actually uses the schema.

**Comment by paoloantinori** [comment]
We should not hardcode `null` here:

https://github.com/syndesisio/syndesis/blob/1d1a37099de230b6e0de1a391cb6229d52d10832/app/connector/sql/src/main/java/io/syndesis/connector/sql/customizer/SqlConnectorCustomizer.java#L116

**Comment by paoloantinori** [comment]
https://issues.jboss.org/browse/ENTESB-9996

**Comment by KurtStam** [comment]
@asmigala Can you provide a bit more information. With what credentials and JDBC connection information are you trying to access the sampledb? It currently is grabbing the schema from the connection.

**Comment by asmigala** [comment]
@KurtStam everything works fine in syndesis, the problem is when trying to import the default connection into DV on the Data tab. In fact, the problem appears even just by starting the komodo-server pod, which will try to deploy a vdb internally an fail, since it tries to access the non-existent `sampledb` schema.

@rareddy can probably provide more details on how it gets the schema from syndesis

**Comment by rareddy** [comment]
DV reads the configuration of the data source from syndesis, and uses it create connection and read metadata, issue queries etc. The reason it also happens during the startup of komodo-server pod is, at startup Komodo tries to synchronize the connection configuration between two systems.

@asmigala apart from failing to proceed further, if you see other issues with wrong configuration those we need to capture for DV

**Comment by KurtStam** [comment]
@rareddy can you provide me the JDBC connection info you are using?

**Comment by rareddy** [comment]
we just make rest call to `http://syndesis-server/connection` and read the configuration from it.  This issue saying is on "PostgreDB" connection by default created has default "schema" value is defined as "sampledb". Whereas in Postgres the default schema value is "public". So, this value can be changed to "public" or where ever we are creating the schema in PosgreSQL, create the sampledb schema on it.

**Comment by KurtStam** [comment]
Ah I think I found it, the sampledb is NOT using the sampledb schema, but the public schema instead. So the issue is how the DB is setup. iirc this was changed to be this way so we didn't have to create a schema which needed admin rights.

**Comment by asmigala** [comment]
Verified with 1.7.8
