### ISSUE TITLE
[React-ui] Unable to select Split step

### ISSUE THREAD

**Issue by mmelko** [syndesisio/syndesis#5530]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

![screenshot_20190531_102043](https://user-images.githubusercontent.com/6814482/58692019-fa088300-838d-11e9-87ea-0818128ad037.png)

**Comment by riccardo-forina** [comment]
Thank you, unfortunately it's a regression we introduced this week. Relative issue here https://github.com/syndesisio/syndesis-react/issues/377

**Comment by gashcrumb** [comment]
I've a fix for this I like in [this pr](https://github.com/syndesisio/syndesis-react/pull/379) I can probably extract it out into a separate PR so we can get this sorted.
