### ISSUE TITLE
OpenAPI client is displayed without any connections

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#5532]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
The OpenAPI client in settings is displayed on clean installation of Syndesis. Not sure if more API clients get added because all connection types require the info provided by API client during creation.

State on fresh installation of Syndesis:
![image](https://user-images.githubusercontent.com/46345469/58694223-ce3bcc00-8392-11e9-9835-2a277fb6999a.png)

**Comment by paoloantinori** [comment]
hi @mmuzikar are you testing angular or react front end?

**Comment by mmuzikar** [comment]
@paoloantinori angular

**Comment by paoloantinori** [comment]
mmm. okay. we are not releasing Angular frontend for 7.4.

The only testing expected here is for  CBR routing.

Have you stumbled upon this one or are you systematically testing the Angular frontend. Because if it's the second situation, I think there is some confusion on the release plan.

**Comment by mmuzikar** [comment]
No systematic testing :D we were just confused because it appeared out of nowhere

**Comment by paoloantinori** [comment]
Okay, thanks then I will also file this under react so that we can verify it!

**Comment by zregvart** [comment]
I think that whole list is driven by the data from the server, so there must be a bug we introduced that made the OpenAPI connector to appear without there being a custom API connector created for it beforehand.

**Comment by zregvart** [comment]
Server should not be returning that from the `/api/v1/setup/oauth-apps` endpoint:

![Screenshot from 2019-06-07 09-55-02](https://user-images.githubusercontent.com/1306050/59089448-68a78c80-890a-11e9-9f5d-cb3b302d3924.png)

**Comment by zregvart** [comment]
One note though is that the database needs to be reset, this will not fix an issue when the connector is already defined in the database with tags. We introduced tags in #2436 so we haven't done a release containing that, and that's why I don't think we need a migration script.

**Comment by mmuzikar** [comment]
Agree with you on not needing to provide a migration script, especially if it was to just fix this minor issue. Verified
