### ISSUE TITLE
React UI is using Red Hat logo for favicon

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#5535]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Syndesis has a logo we should be using it as favicon.

## Expected behavior

Syndesis logo as favicon.

## Screenshot

![Screenshot from 2019-05-31 12-48-08](https://user-images.githubusercontent.com/1306050/58701113-5e354200-83a2-11e9-839a-e751003e7425.png)

**Comment by riccardo-forina** [comment]
cc @seanforyou23 git points the change to you :)

**Comment by seanforyou23** [comment]
So I did this intentionally, and I _believe_ it was the right move :) @amysueg can verify, but I think the idea was that all the integration products will adopt this same favicon to further embrace a collective user experience. It's no problem to revert if I goofed it up though.

**Comment by amysueg** [comment]
Syndesis (upstream) should use its own favicon.
The Red Hat favicon should be the one we use for all RH Integration components/products.
Sorry for any confusion on that one @seanforyou23
