### ISSUE TITLE
Add health check to Knative integrations

### ISSUE THREAD

**Issue by alexkieling** [syndesisio/syndesis#5537]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Find out how health checks work in Knative and configure it for Camel K apps running in Syndesis.

**Comment by heiko-braun** [comment]
@alexkieling KNative?

**Comment by alexkieling** [comment]
@lburgazzoli Can you confirm the need of a health check for Knative apps?

**Comment by lburgazzoli** [comment]
Knative health checks do not behave exactly the same as standard k8s probes as you cannot use a different host/port than the one that accept knative request

**Comment by alexkieling** [comment]
@heiko-braun I've updated the description. Luca and I thought that it would make sense to have a separate issue to research how health checks work in Knative. We can close it if it's too low priority at the moment.
