### ISSUE TITLE
Integration revision enhancements

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#5540]
See also **https://issues.jboss.org/browse/ENTESB-11497**

## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

We should be able to:
- limit the number of revisions we store for each integrations
- allow user to delete old revisions
- allow user to compare revisions
- allow user to tag revisions

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11497**
