### ISSUE TITLE
React-ui building/testing performance

### ISSUE THREAD

**Issue by phantomjinx** [syndesisio/syndesis#5545]
Obviously, the react-ui is still being heavily developed so this is merely a signpost in the ground as it were.

1. When building dev images for testing in minishift, I like to do a flash build of everything first. This ensures all modules have been recompiled & I'm not wasting time with old code. I then build the relevant images & deploy accordingly. While doing the first compile, the angular-ui used to take quite a short period of time. However, the react-ui seems to take a noticeably longer period of time & appears to run tests too (not sure angular-ui did??). Is there a way the build time could be curtailed?

2. When pushing to a branch ready to generate a PR, I've come across a git hook that seems to re-execute testing for the react-ui. No code in my PR relates to the react-ui so not sure why it should have activated (see screenshot). As can be seen, it unfortunately, failed hence the only way to push to my branch is to disable the git hook. Thus, can this git hook be limited, please?

![git-hook-react.png](https://images.zenhubusercontent.com/5b4745687c849143424ec0f5/8f78f94c-590b-4ec5-a0bd-bb830a1c7dc4)

**Comment by paoloantinori** [comment]
Hi @phantomjinx . Hooks dependency should be gone, but I think you still need to manually run this command once:

```

**Comment by phantomjinx** [comment]
@paoloantinori @zregvart 
Just tried to push from a branch and still have a hook being fired that did a UI build (happily succeeded and quicker than the last!). Does the hooks directory need updating please?

![git-hook-react-2](https://user-images.githubusercontent.com/1634180/58899012-d2018280-86f3-11e9-99a0-fe71d197710d.png)

**Comment by riccardo-forina** [comment]
That’s local to your system, you can remove the hooks folder in `.git/hooks`

**Comment by phantomjinx** [comment]
@riccardo-forina 
Sure. So was their a script that got executed that generated the hooks in the first place?

**Comment by riccardo-forina** [comment]
We had a dependency over [husky](https://www.npmjs.com/package/husky) which we temporarily removed. By default as soon as it gets installed, hooks are added to the git repo.

**Comment by phantomjinx** [comment]
Got it. Removed. Thx!
