### ISSUE TITLE
[Connectors] Ansible Tower Connector

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#5547]
See also **https://issues.jboss.org/browse/ENTESB-11557**

## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
As a Fuse Online user I want to be able to invoke my Ansible Tower playbook via Fuse Online. I want to be able to check on job status. I want to be able to create and update users, teams and projects, credentials, hosts and jobs. 
I want to be able to do this via a Fuse webhook and API Provider.

**Comment by zregvart** [comment]
Of note is the [OpenAPI document for AWX](https://s3.amazonaws.com/awx-public-ci-files/schema.json) the documentation of the REST API is [here](https://docs.ansible.com/ansible-tower/latest/html/towerapi/api_ref.html).

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11557**
