### ISSUE TITLE
Names of buttons have been changed

### ISSUE THREAD

**Issue by mmelko** [syndesisio/syndesis#5548]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
During connection create last button was "Create" but now it's Next, which might be a bit confusing. 

Also on "validation" page was changed from "Next" to "Save".

**Comment by paoloantinori** [comment]
@riccardo-forina @gashcrumb your comment is required on this.

**Comment by riccardo-forina** [comment]
Opened a PR to fix it here https://github.com/syndesisio/syndesis-react/pull/390
