### ISSUE TITLE
Raise/throw error step

### ISSUE THREAD

**Issue by christophd** [syndesisio/syndesis#5551]
With conditional flows and basic error handling in place we need to add a step that is able to raise a user defined error. So the user can (based on a condition evaluation) raise a (standardized) error at some point in the integration.

For instance when a db query returns many results where only one result is expected user could raise an error based on condition evaluation. Or when a 3rd party service returns with empty results where results would have been expected.

The error step aborts the integration processing and triggers the error handling process of that integration.

Properties of the raise error step could be:
- condition to evaluate (when matching the error is raised)
- error category/type (a standard error category defined by Syndesis)
- error message
- Http status code

**Comment by paoloantinori** [comment]
@riccardo-forina @lburgazzoli I think you have started reasoning on this already.

Keep an eye on this discussion.

**Comment by lburgazzoli** [comment]
beside user defined errors, I guess if we need a sort of "data shape" result validation
