### ISSUE TITLE
Operatorhub productisation changes

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/syndesis#5552]

**Comment by heiko-braun** [comment]
Placeholder for https://issues.jboss.org/browse/ENTESB-10707

**Comment by mastepan** [comment]
@heiko-braun anything here for QE?

**Comment by heiko-braun** [comment]
Yes, at least the product operators (APICurito, Fuse Online and Camel K) would need to be verified. Here the task is to use CR1 and try to install any of the three from the embedded operatorhub in OCP4. @tplevko should have more information on the QE requirements

**Comment by tplevko** [comment]
@heiko-braun can we close this one? I think it's just a placeholder issue, and the verification of installation of productized images using operatorhub will be a part of CR1/CR2 testing: [FUSEQE-5201](https://issues.jboss.org/browse/FUSEQE-5201) [FUSEQE-5016](https://issues.jboss.org/browse/FUSEQE-5016) [FUSEQE-4963](https://issues.jboss.org/browse/FUSEQE-4963)
