### ISSUE TITLE
Integration name  is not unique

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis#5553]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Staging 2 is currently in a state where there are 2 integrations with the same name:

`Integration name 'timer_to_log' is not unique`

This is reported as an error by the UI, which is already a positive thing.

But do we have any checks to prevent this, server side?
Can we protect against this outcome, or there is no way of doing this and we should think of a clean up job or a job that reports logical errors?

![Screenshot from 2019-06-03 10-35-12](https://user-images.githubusercontent.com/1520602/58788026-4c92ab00-85eb-11e9-8bc4-5337e8998d22.png)

**Comment by zregvart** [comment]
> But do we have any checks to prevent this, server side?

Yes, though not at the persistence layer, i.e. unique constraint in the database, this is not easily done with JSONDB, so there is a possibility of duplicate names when things get racy.

> Can we protect against this outcome, or there is no way of doing this and we should think of a clean up job or a job that reports logical errors?

Not sure, best way would be to restrict this at the database layer, might be difficult with JSONDB.

**Comment by lburgazzoli** [comment]
AFAIK we do already have a way to intercept this (even if not the bes solution) so maybe the question is how to deal with such a case ? i.e. should we transfer the integration in a draft state ?

**Comment by riccardo-forina** [comment]
Abort saving and return an error?

**Comment by zregvart** [comment]
Due to the architecture of JSONDB we cannot have any guarantees on uniqueness of two concurrent integration creations. The unique name validation operates on the currently committed rows in the database, not on the database uniqueness constraint. There can be two in-flight transactions saving two integrations with the same name and the validation cannot be aware of this.
