### ISSUE TITLE
Some integrations might not have `tags`

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#5556]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Encountered this on the Angular app:

```
TypeError: "e.tags is undefined"
    c main.92dfe73cca4a82a65801.js:32609
    list main.92dfe73cca4a82a65801.js:83792
    _next polyfills.cd1c6ed959cbc1c630d4.js:1
    next polyfills.cd1c6ed959cbc1c630d4.js:1
    _next polyfills.cd1c6ed959cbc1c630d4.js:1
    next polyfills.cd1c6ed959cbc1c630d4.js:1
    _next polyfills.cd1c6ed959cbc1c630d4.js:1
    next polyfills.cd1c6ed959cbc1c630d4.js:1
    _next polyfills.cd1c6ed959cbc1c630d4.js:1
    next polyfills.cd1c6ed959cbc1c630d4.js:1
    notifyNext main.92dfe73cca4a82a65801.js:120633
    _next main.92dfe73cca4a82a65801.js:121824
    next polyfills.cd1c6ed959cbc1c630d4.js:1
    _next polyfills.cd1c6ed959cbc1c630d4.js:1
    next polyfills.cd1c6ed959cbc1c630d4.js:1
    _next main.92dfe73cca4a82a65801.js:130013
    next polyfills.cd1c6ed959cbc1c630d4.js:1
    u main.92dfe73cca4a82a65801.js:123825
    invokeTask polyfills.cd1c6ed959cbc1c630d4.js:1
    onInvokeTask main.92dfe73cca4a82a65801.js:21984
    invokeTask polyfills.cd1c6ed959cbc1c630d4.js:1
    runTask polyfills.cd1c6ed959cbc1c630d4.js:1
    invokeTask polyfills.cd1c6ed959cbc1c630d4.js:1
    b polyfills.cd1c6ed959cbc1c630d4.js:1
    _ polyfills.cd1c6ed959cbc1c630d4.js:1
main.92dfe73cca4a82a65801.js:formatted:141141
```

I think here we need to check if `integration.tags` is not `null`:

https://github.com/syndesisio/syndesis/blob/8fad0602f5f968861a5ed292f956f53d6e65b296/app/ui-angular/src/app/store/integration/integration.service.ts#L33

**Comment by paoloantinori** [comment]
I've:
- removed all the integrations
- create a new integration on the Angular UI
- verified that this way both angular and react render it fine.

I'd say that the quickest fix to keep it going would be to make React code base to add an empty list for tags in case the preprerty is null/undefined

**Comment by riccardo-forina** [comment]
[We're already doing that](https://github.com/syndesisio/syndesis/blob/3736a21944dacd254663f493010f2122aa7b7593/app/ui-react/packages/api/src/helpers/integrationFunctions.ts#L690), in theory.

**Comment by riccardo-forina** [comment]
Right, it looks like it's not working, or that code isn't called by all code paths. 
It needs to be checked out.

**Comment by zregvart** [comment]
I think we can fix this also on the backend, I think we might omit `tags` if it's empty. Super easy fix, would that be better?

**Comment by riccardo-forina** [comment]
I'd rather have the new UI behave as much as possible as the old one in this phase. I mean, I'd rather have all the business logic handled by the BE all the time, mind, but since that's not the way it's done now better not diverge too much I guess?

**Comment by zregvart** [comment]
Would be cool if this was handled at the model level, we do it on the backend, the default value is always an empty set/list so when a `null` value is passed for a collection property we don't get hit by this.

I was suggesting as I was investigating #4977 which has a similar root cause (accessing `.length` of `null`) and instead of looking at all the places I need to check for this in the UI I can handle this on the backend and make sure that `[]` is returned even for empty/null values.

I'll try not to make this change on the backend, and try to see if a model change in the UI would be better.

**Comment by riccardo-forina** [comment]
Well, ultimately I think [this](https://github.com/syndesisio/syndesis/issues/4085) is the real problem, but that didn't go anywhere.

**Comment by gashcrumb** [comment]
The angular app [builds an array of tags](https://github.com/syndesisio/syndesis/blob/master/app/ui-angular/src/app/integration/edit-page/flow-functions.ts#L442) containing the involved connector IDs when saving, but maybe it's possible to create an integration nowadays that only uses extensions and steps I wonder.  

Anyhoo, `tags` was originally for grouping but now we've overloaded it for determining the integration type unfortunately.  So it's only usage in either app at this point should simply be for this API provider check.

**Comment by riccardo-forina** [comment]
By the way, [this](https://github.com/syndesisio/syndesis-react/pull/407) will make sure that the tags array is properly set in the integration object before saving.

**Comment by riccardo-forina** [comment]
This should be fixed now.
