### ISSUE TITLE
FHIR - datamapper: UPDATE action - missing resource id field

### ISSUE THREAD

**Issue by mastepan** [syndesisio/syndesis#5558]
See also **https://issues.jboss.org/browse/ENTESB-11471**

## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Let's have an integration 
... -> FHIR Create -> datamapper -> FHIR - Update -> ...

I want to update the resorce I've just created. How can I tell what resource I want to update?
Analogically, if I want to **Read** a resource I can map a resource id via datamapper from the previous steps. But I can't do the same using **Update** action because there is not resource id field.
![FHIR_read_resourceId](https://user-images.githubusercontent.com/8707251/58798952-4e1c9d00-8604-11e9-9f20-20a4e70f17e8.png)
![FHIR_update_resourceId](https://user-images.githubusercontent.com/8707251/58798958-5248ba80-8604-11e9-8d4f-9914c90db639.png)

**Comment by rkorytkowski** [comment]
@mastepan, please map "id.idPart" instead of "id.value". The "value" contains the full url, whereas idPart just the logical id. I'll request that info to be added to the documentation.

**Comment by rkorytkowski** [comment]
@mastepan, you can specify a resource id to update in a data mapper step.

**Comment by mastepan** [comment]
@rkorytkowski well, I can't see how. Can you help me please?
If I map it to the resource that is being updated (target), it should change (unless it's unmutable) as any other value I map to the target.

**Comment by rkorytkowski** [comment]
![image](https://user-images.githubusercontent.com/1163157/58948018-826d9600-8789-11e9-93ec-472b63849291.png)
See the mapping. The target is for the update action. If you set id to an existing value, then an existing object with that id will be updated. If you set id to a new value, then a new object will be created. It is not possible to update an id alone (well you could copy all fields to a new object with a manually assigned id).

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11471**
