### ISSUE TITLE
OData connector details displays a password that hasn't been set

### ISSUE THREAD

**Issue by jsafarik** [syndesisio/syndesis#5563]
See also **https://issues.jboss.org/browse/ENTESB-11422**

## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

When I create and OData connector (basic, using https://services.odata.org/TripPinRESTierService/ as always, not setting any username, password or server certificate) and then go to connectors details, there is a pretty long password fetched from the backend. When I try to edit the connector, delete the password, save it and re-edit again, the passowrd appears again. (not sure if this can be somehow connected to the validation error reported in [#5559](https://github.com/syndesisio/syndesis/issues/5559), but tried not to validate the service at all and the issue is still present). Can't figure out where this password comes from.

**Comment by paoloantinori** [comment]
>  there is a pretty long password fetched from the backend

**Comment by jsafarik** [comment]
@paoloantinori if counting right, it's 69 characters long (tried a few different service root URLs to see if it is not just copied, but it doesn't match with the length of the URL and password seems to be the same length no matter how long the URL is)

**Comment by riccardo-forina** [comment]
Aint that password a dummy one, just to show that it was previously
configured? Passing back the original and right password values wouldn't be
a wise thing to do anyway...

**Comment by phantomjinx** [comment]
Your right. No password required for Tripin service.

On 3 June 2019 15:15:21 BST, jsafarik <notifications@github.com> wrote:
>@riccardo-forina  Well the thing is that this happens when there is no
>password specified when creating the connector, so there shouldn't be
>any dummy password, or am I wrong?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/syndesisio/syndesis/issues/5563#issuecomment-498274929

-- 
P. G. Richardson
* Ty-Carreg Barn, Penyrheol, Pontypool, Torfaen. UK
* 01495 762483
* p.g.richardson@phantomjinx.co.uk

**Comment by riccardo-forina** [comment]
Not showing a dummy password would give away that there is no password. I don't know this feature in particular, but from a user standpoint, the current behavior doesn't seem wrong to me.

**Comment by jsafarik** [comment]
Well, there is no username specified, just password, and I think that for a public service that doesn't require any username or password is misleading to show a dummy password. it's public, no need to hide the fact that there is no password.

**Comment by phantomjinx** [comment]
This is a generic issue with the password control (happens with ftp connector as well). Whether to change it is TBD.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11422**
