### ISSUE TITLE
Integration Editor does not propagate ids correctly - Missing names of some steps in the Activity log

### ISSUE THREAD

**Issue by mkralik3** [syndesisio/syndesis#5565]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
In the activity log, the name of the log step and data mapper is **n/a**. What is worse, the log step also doesn't show any output in the activity log.
E.g. I have this integration with steps DB->LOG->DATA MAPPER->LOG->DB
![image](https://user-images.githubusercontent.com/16251792/58874812-137d3800-86ca-11e9-991e-33e299ca62d4.png)
The activity log:
![image](https://user-images.githubusercontent.com/16251792/58874999-a027f600-86ca-11e9-9eac-9a982c834bdb.png)

**Comment by paoloantinori** [comment]
@gashcrumb data is there. Full payload here:
https://paste.fedoraproject.org/paste/LboIkjhTC2AGlQuBt3p-Og

**Comment by gashcrumb** [comment]
Looks like it could be on those ones the `id` field isn't set on the step, so we can't correlate the activity message to the step properly, for example here's the `timer_to_log_30s` integration on staging 2:

![image](https://user-images.githubusercontent.com/351660/58883183-e6219180-86ab-11e9-9e09-30bcc72d9e17.png)

**Comment by paoloantinori** [comment]
@gashcrumb @riccardo-forina , sorry but I need to bring worse news.
Inspired by @gashcrumb comment I have tried to create the same exact integration via the Angular editor, and, in that way, the Activity steps are correct on both Angular and React,

So I call a bug in the editor that doesn't propagate the correct `ids`.

See

https://syndesis-legacy.b6ff.rh-idev.openshiftapps.com/integrations/i-LgXnz2vMEJGX20oiVIqz?view=activity

https://syndesis-staging-2.b6ff.rh-idev.openshiftapps.com/integrations/i-LgXnz2vMEJGX20oiVIqz/activity

If link do not work, the integration name is ` timer_to_log_paolo`

**Comment by riccardo-forina** [comment]
Fix here https://github.com/syndesisio/syndesis-react/pull/407
