### ISSUE TITLE
Validate button is disabled in API connector

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#5566]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
The `validate` button is disabled no matter what field I change. And the next button is disabled as well, I figured that it probably gets enabled when the connector is validated. 

Steps to reproduce:
1. import API client specification ([https://petstore.swagger.io/v2/swagger.json](https://petstore.swagger.io/v2/swagger.json))
2. go into connections and try to create that connector
3. 
![image](https://user-images.githubusercontent.com/46345469/58807775-05231380-8619-11e9-9e4c-12ca5557c098.png)

**Comment by paoloantinori** [comment]
Linked to this? https://github.com/syndesisio/syndesis/issues/5560

**Comment by gashcrumb** [comment]
Probably.  The angular code obviously has a band-aid in place to prevent this.  I guess if there's enough we may have to adopt the same band-aid :-(

**Comment by zregvart** [comment]
API client connectors don't offer validation, none of the HTTP client connectors do. Not sure if we signal this correctly for the UI though.

**Comment by gashcrumb** [comment]
Ah, I didn't realize that there was a limitation, there's no check made in the UI whether or not the validate button should be offered.

**Comment by paoloantinori** [comment]
This still seems to be broken in my test,

**Comment by riccardo-forina** [comment]
If you tested this on staging-2, it's on commit `86cd2ac0f568dacb55d57b941d9103924116fc75` which doesn't include the fix.

**Comment by paoloantinori** [comment]
Thank. I swear I have just forced a docker image update and I was expecting
to pick up the latest one

**Comment by paoloantinori** [comment]
For what I can tell, this commit is in:

https://github.com/syndesisio/syndesis/pull/5581/commits/fb4f843d69b4106f2830e12bb7c7b189a5fe4dfb

**Comment by riccardo-forina** [comment]
![image](https://user-images.githubusercontent.com/966316/58887108-4bde3f80-86e5-11e9-85d7-157967c5332f.png)

Commit is [this one](https://github.com/syndesisio/syndesis/commit/86cd2ac0f568dacb55d57b941d9103924116fc75)

**Comment by mmuzikar** [comment]
@paoloantinori From what I've gathered from the conversation regarding this issue, it is not possible to validate such connection. In this case I believe the `validate` button shouldn't be displayed and shouldn't tell the user that the connection was successfully validated, when it wasn't possible to validate it.

**Comment by riccardo-forina** [comment]
I don't think we have any way to know that something can't be validated against the BE right now.

**Comment by mmuzikar** [comment]
Verified by QE
