### ISSUE TITLE
Unnecessary parameters prevent creating google connections 

### ISSUE THREAD

**Issue by mmelko** [syndesisio/syndesis#5572]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
In google connectors appeared parameters like Authorization URL (2x!) and Token URL that are marked as required and block creating connetions: 
![screenshot_20190604_085236](https://user-images.githubusercontent.com/6814482/58857949-b754ec80-86a6-11e9-8c02-a3aa651e5ad9.png)

Old UI: 
![screenshot_20190604_085421](https://user-images.githubusercontent.com/6814482/58857952-b91eb000-86a6-11e9-92d2-0395bb277839.png)

I'd like to meniton that this is blocking our smoke tests, because we are validating all of our credentials there.

**Comment by mmelko** [comment]
@paoloantinori FYI

**Comment by paoloantinori** [comment]
@gashcrumb @riccardo-forina @zregvart 

There is definitely some non-intuitive logic with the semantics of the connector description metadata that we haven't ported right to React, just like @gashcrumb was assuming.

See the oddity of this portion:

https://github.com/syndesisio/syndesis/blob/master/app/connector/google-calendar/src/main/resources/META-INF/syndesis/connector/calendar.json#L555-L586

**Comment by paoloantinori** [comment]
https://github.com/syndesisio/syndesis/blob/master/app/connector/google-calendar/src/main/resources/META-INF/syndesis/connector/calendar.json#L555-L586

**Comment by riccardo-forina** [comment]
In this particular case the problem [is this bit](https://github.com/syndesisio/syndesis-react/blob/2cc61c060786c581b24294e10b7e4624f13e75b9/app/ui-react/packages/auto-form/src/utils.ts#L81), which basically means that we don't consider the `hidden` type when there is some specific business logic going on with the type.

I'll fix this now but I wonder, why sending hidden fields to the UI in the first place?
