### ISSUE TITLE
WebHook doesn't contain route url

### ISSUE THREAD

**Issue by mkralik3** [syndesisio/syndesis#5575]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
In ReactUI, the WebHook doesn't contain external url as before. In this case, the users are not able to see (in UI) a route where the webhook is. They have to go to the OpenShift console -> project -> routes.

![image](https://user-images.githubusercontent.com/16251792/58862348-cb9de700-86b0-11e9-8151-ce25cf5a98ec.png)

**Comment by asmigala** [comment]
Same for API Provider
