### ISSUE TITLE
Data Mapper conditional mapping alert showing behind source table

### ISSUE THREAD

**Issue by jsafarik** [syndesisio/syndesis#5579]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

When I create an integration including data mapper and try to click on the `enable/disable conditional mapping expression` with no previously created mappings, there appears an alert with message `Please select a mapping first`. BUT this alert is hiding behind the `source` table.

![data_mapper_warning](https://user-images.githubusercontent.com/46523434/58870167-f2afe500-86bf-11e9-9243-63bb1f8b6f78.png)

**Comment by paoloantinori** [comment]
@igarashitm @pleacu Can you give a quick view to this to undersand if the issue is on AtlasMap or on SYndesis?

**Comment by igarashitm** [comment]
It seems to be a Syndesis only problem, but we might have to put something in AtlasMap CSS...

**Comment by igarashitm** [comment]
@riccardo-forina do you have any pointer to the Syndesis CSS which could affect AtlasMap UI?

**Comment by riccardo-forina** [comment]
[This](https://github.com/syndesisio/syndesis/blob/4783174dccd2f58e152ebbf1024c37456a46c645/app/ui-react/packages/atlasmap-assembly/src/app/app.component.css#L1-L0) and [this](https://github.com/syndesisio/syndesis/blob/7050313bd3ed7ce188c27aa62feddbd2e941768b/app/ui-react/packages/atlasmap-assembly/src/styles.scss#L1). The latter should have been copied over [from Atlasmap's](https://github.com/atlasmap/atlasmap/blob/master/ui/src/styles.scss) repo, and maybe it's not needed.

**Comment by riccardo-forina** [comment]
By the way those files are specific to the iframe where Atlasmap is being loaded. Syndesis's own styling can't clash with Atlasmap's, because the iframe.

**Comment by igarashitm** [comment]
atlasmap/atlasmap#1057
