### ISSUE TITLE
Received `processedtemplates "syndesis-ci" is forbidden:` error while installing

### ISSUE THREAD

**Issue by honghuac** [syndesisio/syndesis#558]
Installing syndesis using the build.sh file, on top of a local OCP cluster failed, with the following error: 

**error: error processing the template "syndesis-ci": processedtemplates "syndesis-ci" is forbidden: unable to create new content in namespace itest-9356bca9 because it is being terminated.
No resources found**
_[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 605.919 s <<< FAILURE! - in io.syndesis.systests.DeploymentTest_

The rest of the relevant trace in the log can be found here:
https://gist.github.com/honghuac/4303bb0338b4c3179797d5710784602c

Why is the project *itest-9356bca9* deleted while installation is taking place? This is likely the reason for the error. What can be done to resolve this project deletion issue?

**Comment by zregvart** [comment]
We went back and forth with namespace handling in system tests. I see that the current setup works OK on our CI (for instance https://circleci.com/gh/syndesisio/syndesis/4462), so I'm closing this as I believe it's no longer an issue, please reopen if you still experience it.
