### ISSUE TITLE
Configuring a connection in integration causes white screen

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#5583]
See also **https://issues.jboss.org/browse/ENTESB-11420**

## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When editing an integration and clicking on configure button of some used connection usually displays just white screen to user:

GIF:
![Peek 2019-06-04 14-38](https://user-images.githubusercontent.com/46345469/58879696-84c2e800-86d6-11e9-806e-76154ec8d577.gif)

**Comment by riccardo-forina** [comment]
Anything in the console?

**Comment by mmuzikar** [comment]
```
TypeError: "c.action is undefined"
    di WithConfigurationForm.tsx:101
    React 8
react-dom.production.min.js:4408
    React 7
    unstable_runWithPriority scheduler.production.min.js:274
    React 5
```

**Comment by riccardo-forina** [comment]
What's the commit id in the Support > About dialog?

**Comment by mmuzikar** [comment]
b30162865f3cb8d797199c2b06b053b02f0bddf4

**Comment by riccardo-forina** [comment]
Ok I can reproduce it, it happens when clicking what once we used to call "steps" (eg. Split, Aggregate).

I'll work on a fix, thanks for reporting the issue!

**Comment by riccardo-forina** [comment]
Fix here https://github.com/syndesisio/syndesis-react/pull/406

**Comment by mmuzikar** [comment]
Reopen for verification

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11420**
