### ISSUE TITLE
[react-ui-id] Add element id to about page elements

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#5584]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Please add element id to strings in about page for easier testing and flexibility in case of any change on that page. Any change will break our tests.

![screenshot_20190604_145733](https://user-images.githubusercontent.com/14313995/58880852-3236fb00-86d9-11e9-999f-e6f118ef1848.png)

**Comment by zregvart** [comment]
I can see we have `data-testid` for all of these:

```html
<dl class="" data-pf-content="true">
	<dt class="" data-testid="about-modal-content-product-name-list-item" data-pf-content="true">Syndesis:</dt>
	<dd class="" data-testid="about-modal-content-version-list-item" data-pf-content="true">1.8-SNAPSHOT</dd>
	<dt class="" data-pf-content="true">Build ID:</dt>
	<dd class="" data-testid="about-modal-content-build-id-list-item" data-pf-content="true">cb2cdc61-8e83-4d58-83cc-a8f50c795819</dd>
	<dt class="" data-pf-content="true">Commit ID:</dt>
	<dd class="" data-testid="about-modal-content-commit-id-list-item" data-pf-content="true">9d6403a6b16ddc4ee8655838a8027fda35fd88e2</dd>
</dl>
```
