### ISSUE TITLE
[react-ui-id] Add element id to logout dropdown

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#5585]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Please add element id to logout dropdown as current implementation has auto generated ID which we can not use in tests.

![screenshot_20190604_151148](https://user-images.githubusercontent.com/14313995/58881770-1f252a80-86db-11e9-9860-3901ace740f1.png)

**Comment by elvisisking** [comment]
This should be fixed @mcada
