### ISSUE TITLE
If multiple OAuth flows are given, filter out only authorization code flow

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#5592]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

From https://github.com/syndesisio/syndesis-react/issues/411, we need to filter out OAuth flows that we support presented in an OpenAPI document. I think in 99% cases this will only lead to a single OAuth flow, in other cases I'm not sure that that OpenAPI document (i.e. one specifying multiple authorization code OAuth flows) follows the spirit/semantics of the OpenAPI specification.

**Comment by mastepan** [comment]
@zregvart what should QE verify here please?

**Comment by zregvart** [comment]
There are four OAuth flows that can be specified in the [security definition within the OpenAPI document](https://swagger.io/specification/v2/#security-scheme-object): implicit, password, application or accessCode, we only support `accessCode`. The change we made was to filter out any OAuth security defintions that use any of the three unsupported OAuth flows.
You can test by creating a OpenAPI document with various OAuth flows and only the the one that has the `flow` set to `accessCode` should be presented as a choice to the user.
Does that make sense?

**Comment by tplevko** [comment]
Thanks @zregvart, sure it does. I tried all the combinations you described, the only one supported ATM is in deed the `accessCode`, the others are not available. Should this be mentioned in the docs? Any other option, how we could let the user know we don't support the other security definitions?

**Comment by zregvart** [comment]
I'm pretty certain that was mentioned in the docs at some point, @TovaCohen can you help us out? Do we specifically mention in the documentation that we support only _authorization code_[1] OAuth flow?

[1] https://tools.ietf.org/html/rfc6749#section-1.3.1

**Comment by tplevko** [comment]
@zregvart I looked at [the docs](https://access.redhat.com/documentation/en-us/red_hat_fuse/7.4/html-single/integrating_applications_with_fuse_online/index#providing-client-credentials_dev-client-connector) and the `accessCode` is the only mentioned oauth flow, but it isn't mentioned that it's the only supported.  
@TovaCohen I created a [Doc Jira|https://issues.jboss.org/browse/FUSEDOC-3411] so we won't loose track of this. I think this issue can be closed.
