### ISSUE TITLE
In Safari the connector grid page keeps jumping upwards when trying to scroll down

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#5593]
## This is a...

<pre><code>
[ ] Feature request
[*] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
In Safari the connector grid page keeps jumping upwards when trying to scroll down. Works ok in Chrome.

**Comment by riccardo-forina** [comment]
Interesting, I can't reproduce this on my Safari (Version 12.1.1)

**Comment by seanforyou23** [comment]
Hmm I don't seem to have this on my end either. This is for the `/connections/create/connection-basics` route, right? It's smooth for me, I'm on version 12.1.1. Is there something else I can try or do you have an idea as to where the issue is coming from?

**Comment by seanforyou23** [comment]
I did notice something similar to this when trying to scroll as the connectors are loading and the skeleton cards are displayed. Does this accurately depict the issue @KurtStam?

**Comment by seanforyou23** [comment]
This may be related to 

https://github.com/patternfly/patternfly-next/issues/1688

https://bugs.webkit.org/show_bug.cgi?id=196619
