### ISSUE TITLE
Make DeploymentDescriptorIT test great again

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#560]
https://github.com/syndesisio/syndesis/blob/d6df69488f8e0b6885b1ea82218e3bb88dd22979/rest/dao/src/test/java/io/syndesis/dao/DeploymentDescriptorIT.java#L68

**Comment by KurtStam** [comment]
The test seems to download the snapshots from maven, not the local tree. So even though I think I fixed the data to make the test pass, I won't pass till the snapshots are deployed. @zregvart does that sound right? If so that is kinda a side effect of moving to the mono repo.

**Comment by zregvart** [comment]
Seemed to work OK for me when the connectors are installed in the local Maven repository (it would get them from there), could be just a build order issue? Perhaps we could also troll the source tree and take Camel schema JSONs from there? Part of them are code generated so that would only fail if the code generation was not done.

**Comment by KurtStam** [comment]
@zregvart my connectors have the SQL URL param set to 'required'. My local .m2 directory has a sql-connector-1.2-SNAPSHOT.jar with the sql-connector.json reflecting this. Grabe seems to ignore this and proceeds to download the artifact from maven central (or another listed repo) and gets an older snapshot, with the param required set to false. Test fails. 

I would expect to fix the failure without having to push a release to central.

**Comment by zregvart** [comment]
Perhaps we could take JSON schemas straight from filesystem, now that we're in a single repository that should work.

**Comment by KurtStam** [comment]
@zregvart y, though I would expect it to work with the local .m2 as well.

**Comment by zregvart** [comment]
Yeah, though looking at the JSON files directly could be also good for development experience:
 - change connector JSON
 - run the test (no need to package/install)
 - fix deployment.json...

Though the connector simplifications by @lburgazzoli will remove some of the need for this.

**Comment by KurtStam** [comment]
y. though what happens if I dive directly into the `rest` directory without building the `connectors`. It would fail right? That's bad.

**Comment by zregvart** [comment]
I'm thinking of going directly to filesystem for the Connector JSON files, we would have to try not to use `camel-connector-schema.json` if possible (it's generated/updated by connectors maven plugin), and go straight to `camel-connector.json`. If we end up needing (and we might) perhaps we can invoke the logic from the connector mojo to generate `camel-connector.json`. Could end up being a largish task in the end...
