### ISSUE TITLE
Confusing flow when editing OpenAPI definition of API provider integration

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#5600]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When trying cancelling view/edit API definition UI asks to upload the OpenAPI specification when cancelling that UI asks for a start connection.

I should return to the screen from which I clicked on view/edit API definition directly without these two additional screens.

![Peek 2019-06-05 12-50](https://user-images.githubusercontent.com/1306050/58951258-e9db1400-8790-11e9-9f83-34698b063fdf.gif)

**Comment by riccardo-forina** [comment]
Right, that's because I cheated and reused the editor from the creation flow. Which in hindsight was a mistake.

Can you tell me what should happen after the spec gets edited? Should we call the same API we call when creating an API Provider based integration to get the integration object back? If yes, does it mean that the previous integration will effectively be discarded, with all its changes?

**Comment by zregvart** [comment]
> Can you tell me what should happen after the spec gets edited? Should we call the same API we call when creating an API Provider based integration to get the integration object back? If yes, does it mean that the previous integration will effectively be discarded, with all its changes?

The same thing Angular UI does :)

Which is to update the specification of the integration and reload the integration (WSS event will be triggered):

https://github.com/syndesisio/syndesis/blob/8fad0602f5f968861a5ed292f956f53d6e65b296/app/ui-angular/src/app/integration/api-provider/operations-page/specification/specification-editor-page.component.ts#L54-L58

https://github.com/syndesisio/syndesis/blob/0d8863cf9bdf0226b8083e50e7a5ba4983dd392f/app/ui-angular/src/app/store/integration/integration.service.ts#L124-L131
