### ISSUE TITLE
Trouble logging into a redeployed syndesis

### ISSUE THREAD

**Issue by asmigala** [syndesisio/syndesis#5602]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When I have a syndesis instance deployed in minishift, log in to it, then delete the whole project and create a new one, I get a bunch of different errors when trying to log into syndesis. Not sure what exactly fixes it, some combination of ctrl+f5, clearing the site data and opening a new tab.

## Steps to reproduce
1. create a new project in minishift
2. deploy syndesis into it
3. log into syndesis
4. delete the project
5. create the project again
6. deploy syndesis
7. try logging in again

Please note that I'm NOT clicking on the `Report the issue` button in the following video, I just happen to move my mouse there when hitting ctrl+f5.

![syndesis-login](https://user-images.githubusercontent.com/9480152/58958400-1dbf3500-87a3-11e9-8f84-39d1b76bf722.gif)

**Comment by asmigala** [comment]
Opening syndesis in a private browsing window works straight away, with no voodoo steps required.

**Comment by zregvart** [comment]
I'm guessing it's a mix of cached stuff, I troubleshooted something similar and ended up removing all local storage and service worker stuff from my browser.

I think this might have a potential to influence users going from Angular to the React versions on the same hostname.

**Comment by zregvart** [comment]
Let's get some attention on this, I don't think this is random or local, we'll probably have an issue migrating from Angular to React because of this. So cc @paoloantinori :smiling_imp:

**Comment by asmigala** [comment]
Definitely not random, happens every time I redeploy syndesis, also happens to @wyvie  and @mkralik3

**Comment by paoloantinori** [comment]
@asmigala can you confirm if unregistering the corresponding Service Worker would allow you to succeed?

**Comment by asmigala** [comment]
@paoloantinori how do I do that?

**Comment by heiko-braun** [comment]
@paoloantinori If this blocks QE (see https://github.com/syndesisio/syndesis/issues/5602#issuecomment-499124327) I would consider it blocking. Do you have someone in your team to investigate this?

**Comment by heiko-braun** [comment]
@riccardo-forina Any idea what might be causing this?

**Comment by asmigala** [comment]
@heiko-braun we are not really blocked, _we_ can get it to work eventually. However, I would still consider this to be p0, as being unable to login into the app without considerable effort seems like a pretty serious issue to me.

**Comment by paoloantinori** [comment]
> @paoloantinori If this prevents QE form making progress (see [#5602 (comment)](https://github.com/syndesisio/syndesis/issues/5602#issuecomment-499124327)) I would consider it blocking. Do you have someone in your team to investigate this?

Yes, so this per se is not a blocker. But it is in conjunction with the other bug with `logout`, I've just hit this.

The problem is that the logout operation is at the moment not implemented correctly. It's not clearing cookies correctly and it's not even redirecting correctly.

What happens is that you hit logout:
- some but not all is cleared on client side. Enough for the app to stop allowing you to access endpoints but not enough to be detected as a new user.

My local workaround was to manually clear cookies and local storage AND to unregister the service worker.

**Comment by riccardo-forina** [comment]
> ![syndesis-login](https://user-images.githubusercontent.com/9480152/58958400-1dbf3500-87a3-11e9-8f84-39d1b76bf722.gif)

Anything in the browser console when the error page appears? That screen is about some error trying to fetch the `config.json`. When I see it, it's because of the SSL certificate that's self-signed.

**Comment by wyvie** [comment]
i've been trying to do anything to my firefox (on mac) to get past the cors error, and it seems nothing is helping 😞 (linux firefox is working fine)
mod-shift-r (full reload), clearing all the cookies, deleting all the firefox folders, redeploying syndesis, restarting computer, even private browser window, and nothing helps
chrome seems to work just fine though

**Comment by gashcrumb** [comment]
I don't know if it's related but since pointing my dev instance to staging-2 I find that I *always* need to remove `.puppeteer_data` and log in whenever I restart the dev server (via `syndesis ui --serve`).  I wonder if it's something to do with the oauth proxy changes that were made when trying to get both consoles working perhaps?  TBH I don't think it's really anything wrong with the console itself, there's no actual oauth or login code, or really any code that deals with your authenticated state, either the console has a cookie or it doesn't, and if it does, it's either stale, or it isn't.  And that cookie is set server-side.

**Comment by gashcrumb** [comment]
Other data point is that when I try and access [staging 2](https://syndesis-staging-2.b6ff.rh-idev.openshiftapps.com/) directly from firefox I *only* see an error page.  I've gone into the 'storage' tab and cleared everything.  I do see that we only appear to get a 302 redirect when fetching an icon and then the `config.json`, firefox blocks that request due to CORS so the console would in this case just get an error back when fetching this:

![image](https://user-images.githubusercontent.com/351660/59114548-61d24700-8915-11e9-9198-b79f5707a911.png)

**Comment by gashcrumb** [comment]
VS staging, the first request gets a redirect.  I'll stop adding screen captures now and move along :-)

![image](https://user-images.githubusercontent.com/351660/59114742-d3aa9080-8915-11e9-98e8-2b0914c07ff9.png)

**Comment by paoloantinori** [comment]
We are about to deploy this one:

https://github.com/syndesisio/syndesis/issues/5573

And we should all revisit if that fixes this one too.

**Comment by paoloantinori** [comment]
this is still not fixed.
The main workaround, for anyone that has to cope with this is to unregister the service worker.

It can be done either accessing the corresponding browser page or with a short snippet to paste in the web browser console.

see

https://love2dev.com/blog/how-to-uninstall-a-service-worker/

**Comment by riccardo-forina** [comment]
Wonder, is the browser on Jenkins running from a clean slate? Like in private mode or something equivalent? As Stan stated, the UI doesn't have anything to do with the authentication process. We are suspecting the web worker that does some asset caching; if that's the culprit, running in private mode or equivalent should definitely work.

**Comment by avano** [comment]
@riccardo-forina I finally managed to get to what is going on on jenkins - it seems it is the same problem that Stan described in https://github.com/syndesisio/syndesis/issues/5602#issuecomment-499924963 - The firefox console has:


Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://master.fuse-online-3-10.dos.fuse-qe.eng.rdu2.redhat.com:8443/oauth/authorize?approval_prompt=force&client_id=system%3Aserviceaccount%3Asyndesis2%3Asyndesis-oauth-client&redirect_uri=https%3A%2F%2Fsyndesis-syndesis2.apps.fuse-online-3-10.dos.fuse-qe.eng.rdu2.redhat.com%2Foauth%2Fcallback&response_type=code&scope=user%3Ainfo+user%3Acheck-access&state=cdda9bd61e26062bd732a061c4de39b1%3A%2Fconfig.json. (Reason: CORS header \u2018Access-Control-Allow-Origin\u2019 missing).


I also tried private window, but it is still the same.

Also tried to delete all from storage, service workers seemed to be disabled

The version of firefox is `60.7.0esr` and it seems to be the latest one that is available in the image.

**Comment by avano** [comment]
@heiko-braun I sent it back to `inbox` according my last comment

if somebody has an idea what else should I try, send it to me

**Comment by heiko-braun** [comment]
@riccardo-forina @gashcrumb Can you take another look?

**Comment by mastepan** [comment]
@zregvart if this's been fixed please change the pipeline to **Done**. I'm just checking. If **In Progress** state is right, than ignore this comment. Thanks.

**Comment by zregvart** [comment]
Sorry, I should have noted that I can't reproduce this. I've tried on minishift and with Firefox 67.0.2 in a new profile (with defaults).

I did get an issue with timeouts from the service worker:

```
Terminating ServiceWorker for scope ‘https://syndesis.192.168.42.195.nip.io/’ with pending waitUntil/respondWith promises because of grace timeout.
```

That does not occur if I configure the syndesis route as to allow non-encrypted HTTP traffic and access over plain text HTTP; or if I try in Chromium. The issue manifested itself as long loading when trying to switch between Connection and Integration menu items, i.e. the animated loading placeholder was shown and the network tab did not show a request to the backend.

I linked this from #5893 to fix the issue @paoloantinori mentioned in https://github.com/syndesisio/syndesis/issues/5602#issuecomment-500792883.

The resources on `logout.html` were hitting oauth-proxy's access control and might have interfered somehow, or this could be a separate issue.

**Comment by avano** [comment]
I tried it on freshly installed openstack vm without any luck - the problem still persists. The system is rhel 7.6 and firefox 60.7.2.esr.

I can provide both ssh and vnc access to the machine if you want to try

**Comment by avano** [comment]
also by default the service workers were disabled in firefox, I tried to enable them in about:config, but still the same

**Comment by zregvart** [comment]
I've VNC-ed to the machine, seems that the request for `/config.json` requires authentication and results in a 302 redirect to oauth-proxy authentication HTML page. Which is odd as in another tab I can load `/config.json` without any issues. Could be something to do with cookies over secure and XHR requests to untrusted certificates or something like that -- not sure how to check.

I would propose that we skip authentication for `/config.json` via `--skip-auth-regex` command line option to oauth-proxy. That seemed to have helped with logging in on that machine.

**Comment by paoloantinori** [comment]
@zregvart are you proposing to add that entry to whitelist for our whole configuration or just as a workaround on QE systems?

If it's globally, can we do that without any risk?

**Comment by paoloantinori** [comment]
I've just checked the current content on staging and looks safe to me.
As long as we don't have secret stuff present there only in specific cases, I think we can try this:

```json
{
  "apiBase": "https://syndesis-staging.b6ff.rh-idev.openshiftapps.com",
  "apiEndpoint": "/api/v1",
  "title": "Syndesis",
  "consoleUrl": "",
  "project": "syndesis-staging",
  "datamapper": {
    "baseMappingServiceUrl": "https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/api/v1/atlas/",
    "baseJavaInspectionServiceUrl": "https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/api/v1/atlas/java/",
    "baseXMLInspectionServiceUrl": "https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/api/v1/atlas/xml/",
    "baseJSONInspectionServiceUrl": "https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/api/v1/atlas/json/",
    "disableMappingPreviewMode": false
  },
  "datavirt": {
    "dvUrl": "/vdb-builder/v1/"
  },
  "features" : {
    "logging": false
  },
  "branding": {
    "appName": "Syndesis",
    "favicon32": "/favicon-32x32.png",
    "favicon16": "/favicon-16x16.png",
    "touchIcon": "/apple-touch-icon.png",
    "productBuild": false
 }
}
```

**Comment by avano** [comment]
looks ok now, thanks everyone!
