### ISSUE TITLE
SQL connector cannot access the sampledb tables

### ISSUE THREAD

**Issue by asmigala** [syndesisio/syndesis#5603]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Trying a simple `SELECT * FROM todo` in the SQL step fails with `Table 'TODO' does not exist. Unable to fetch and process metadata`. This is most likely a result of #5591 , though changing the query to `SELECT * FROM sampledb.todo` does not work either.

The table in the database is indeed in the `sampledb` schema:

```
postgres=# \c sampledb
You are now connected to database "sampledb" as user "postgres".
sampledb=# \dt                         
No relations found.
sampledb=# set search_path to sampledb;
SET
sampledb=# \dt
           List of relations
  Schema  |   Name   | Type  |  Owner   
----------+----------+-------+----------
 sampledb | contact  | table | sampledb
 sampledb | todo     | table | sampledb
 sampledb | winelist | table | sampledb
(3 rows)
```

**Comment by paoloantinori** [comment]
this is related, or possibly the same bug as this one: #5603

**Comment by asmigala** [comment]
@paoloantinori you linked linked this very issue

**Comment by KurtStam** [comment]
Might be a side effect of moving it into the new sampledb schema. Will look into it.

**Comment by asmigala** [comment]
Verified with 1.7.8. The same issue occurs in 1.8, see #6014
