### ISSUE TITLE
Advanced filter expression is not saving

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#5604]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
The advanced filter step is not saving the expression, or every time the user clicks on configure of that step, the expression is cleared.

Steps to reproduce:
1. start creating an integration
2. start step can be timer
3. finish step can be log
4. add advanced filter between timer and log
5. write some expression in the textarea and click on done
6. click on the configure button of advanced filter

If this is caused because the user inputs nonsense, it should be handled by error messages. Also I am curious if it's intended behavior to have advanced filter available even though there is no data in the integration I am using to describe the bug.

**Comment by gashcrumb** [comment]
yeah, the advanced filter can work on headers etc. so it doesn't really need a data shape.

I can definitely reproduce this here also.

**Comment by gashcrumb** [comment]
Actually it looks like forms stopped loading data for steps, so that's a way more serious regression.

**Comment by mmuzikar** [comment]
ah, didn't consider headers... good to know, thanks :)

**Comment by mmuzikar** [comment]
@gashcrumb this happened to me only with the filter step, template for example was fine

**Comment by gashcrumb** [comment]
yeah, those are more specific pages, it's the generic step config page that seems to be missing grabbing the configuration.  So 'log' and the advanced filter and probably any step extension as well, I'll check 'em all and make sure those all work as I'd expect.

**Comment by mmuzikar** [comment]
Reopening for verification

**Comment by heiko-braun** [comment]
Migrated to https://issues.jboss.org/browse/ENTESB-11419
