### ISSUE TITLE
page not loading - edit an integration 

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#5612]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Documentation issue or request
</code></pre>

Editing an integration to add a step: brings you to a page that flickers but doesn't load

![flickering adding step](https://user-images.githubusercontent.com/674767/58967580-729e8380-8782-11e9-9b42-5d2900d96b89.gif)
 load

**Comment by gashcrumb** [comment]
yep syndesisio/syndesis-react#422 should sort this
