### ISSUE TITLE
API key option of security does not enable next button

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#5615]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When using an API client with API key option, it is not possible to create such customization because the next button is not enabled in `Specify security`.

![image](https://user-images.githubusercontent.com/46345469/58966514-b7daa980-87b2-11e9-85b4-ed4b8adadf3c.png)

## Steps to reproduce
1. import API client [petstore-test.txt](https://github.com/syndesisio/syndesis/files/3260376/petstore-test.txt) (change the file extension to json, github doesn't allow to upload json files)
2. click on the next button and try to choose API key option

**Comment by mmuzikar** [comment]
@kahboom I believe there has been a regression and the Next button is not enabled i no situations.

**Comment by riccardo-forina** [comment]
I think https://github.com/syndesisio/syndesis/pull/5793 should fix this too.

**Comment by mmuzikar** [comment]
I deployed Syndesis in the morning, so I will redeploy and get back to this.

**Comment by heiko-braun** [comment]
@mmelko Moving into your ballpark (`Done`).

**Comment by mmuzikar** [comment]
@riccardo-forina yup you were right, it's fixed :)
