### ISSUE TITLE
No confirmation dialog shows up when leaving the integration

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#5619]
See also **https://issues.jboss.org/browse/ENTESB-11418**

## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When leaving the integration creation process, there was a confirmation dialog displayed if user really wants to leave the process. Now it just allows them to leave without any second confirmation, which can lead to losing WIP integrations.

**Comment by paoloantinori** [comment]
I've just tried this on staging and I see this working.

Could you attach a video?

**Comment by mmuzikar** [comment]
Sure, I noticed in my recording that this does indeed work when using the integration editor. But links outside this editor work without any conformation. IIRC clicking on the logo also displayed the dialog on the angular frontend and it would be good if it is possible to keep it that way.

![Peek 2019-06-10 08-59](https://user-images.githubusercontent.com/46345469/59178129-6178bc80-8b5e-11e9-9fd7-cb9b90f654cd.gif)

**Comment by riccardo-forina** [comment]
Fixed by https://github.com/syndesisio/syndesis-react/pull/466

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11418**
