### ISSUE TITLE
404 when click on "Define the data type" warning link

### ISSUE THREAD

**Issue by claudio4j** [syndesisio/syndesis#5626]
<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

Steps to reproduce:
1. create a twitter connection
2. create a ftp connection
3. create an integration
3.1 add the ftp connection / Download. Finish with the twitter connection / Send a direct message (type any value in the form) 

The integration steps are displayed, the twitter step shows a warning icon, click on it to open the data mapping window

![1_actions](https://user-images.githubusercontent.com/836543/59053919-e74bed80-8868-11e9-981c-d4b0442f9c39.png)

It shows this error page

![2_fail_404](https://user-images.githubusercontent.com/836543/59053918-e74bed80-8868-11e9-99aa-4b451b011037.png)

**Comment by mastepan** [comment]
@gashcrumb @claudio4j  just checking. Is there anything that should be checked by QE? The issue has been closed by pure-bot

**Comment by gashcrumb** [comment]
Yep, if there isn't an automated test that checks the type mismatch icon this will need verification.  I usually use an AMQ connection when I need a connection that requires defining the data type if you don't want to set up an FTP connection, you can probably use an SQL connection for the finish step.

**Comment by tplevko** [comment]
verified
