### ISSUE TITLE
💄 API Provider operation list alignment

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#5627]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Documentation issue or request
</code></pre>

When you implement a flow in API provide the alignment on that operation is off

![image](https://user-images.githubusercontent.com/674767/59057858-5c1f2780-8869-11e9-9345-79a9fbb532c9.png)

**Comment by dongniwang** [comment]
@mcoker - Is this something you can help take a look at when you get a chance? I think it has something to do with the action button column width?

**Comment by mastepan** [comment]
@mcoker  just checking. Is there anything that should be checked by QE?

**Comment by mcoker** [comment]
@mastepan if you have different sized/amount of actions in the rows, the rest of the column alignment in the list view should remain aligned. You could test it by showing a list view with actions, and removing actions from one or more of the rows and ensuring the alignment of the other columns is still correct.

**Comment by tplevko** [comment]
Verified on master.
