### ISSUE TITLE
Metrics tag shows Invalid Date

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#5628]
See also **https://issues.jboss.org/browse/ENTESB-11570**

## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Documentation issue or request
</code></pre>

![image](https://user-images.githubusercontent.com/674767/59058391-87eedd00-886a-11e9-8b29-4e177e7935fd.png)

**Comment by gashcrumb** [comment]
Does it even make sense to have the Metrics tab available if the integration hasn't been run yet, or in this case it's being created the first time, so there's no data for this view.

Same goes for "Activity" really.

**Comment by dongniwang** [comment]
Yeah, there should be an empty state for both Activity and Metrics. Is this something we hope to get in for this release?

**Comment by gashcrumb** [comment]
What would the empty state for metrics look like?

**Comment by dongniwang** [comment]
Basically pretty similar to what we have for other empty states, except that will be no "+" sign probably. Something like this maybe? 

![empty-state-metrics](https://user-images.githubusercontent.com/24943812/59060112-60017880-886e-11e9-817d-0b3612de4f77.png)

**Comment by dongniwang** [comment]
@elvisisking, I think what you initially had "n/a" for the invalid date is good for now. 

I'll open another issue to investigate what we can show there for these use cases 
>  if the integration hasn't been run yet, or in this case it's being created the first time

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11570**
