### ISSUE TITLE
Incremental builds on CircleCI

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#5632]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

The builds on CircleCI are getting longer and this prevents the UI folk from switching over to the upstream (syndesis) git repository.

We recently introduced the `--incremental` switch to `syndesis build` and enabled it on CI. This caused [some](https://circleci.com/gh/syndesisio/syndesis/75107) [issues](https://circleci.com/gh/syndesisio/syndesis/75097) that need to be refined before it's enabled again.

This is what I think needs to be done:
 - For builds on `master` the Maven artifacts in `io.syndesis` group installed in the local Maven repository need to be saved in a separate cache not tied to the hash of the `pom.xml`. This will act as a makeshift Maven repository, so when a build of a module that another module depends on is skipped the previously built version of the module (from `master`) will be used.
 - CircleCI configuration needs to be a bit more robust taking into account that some jobs can be skipped and not produce any artifacts which need to be cached/archived.

As an option, it would be good if there were a way to trigger a full build i.e. disable incremental build via some convention or parameter so if an incremental build causes issues a build can be retried as a full build. Not sure how that can be done, need to investigate it.

**Comment by riccardo-forina** [comment]
To run a full build on demand maybe we can leverage [conditional builds](https://circleci.com/docs/2.0/reusing-config/#defining-conditional-steps) based on some commit convention. A bit like `[ci skip]` skips the build, we could have a `[syn full-build]` or something along those lines.

**Comment by zregvart** [comment]
This might be of interest to help with #7197

**Comment by zregvart** [comment]
We're using GitHub Actions, so this is stale now. Incremental builds have been implemented for local development, for CI we need a place to store artifacts resulting from skipped modules so we can use them when building dependent modules incrementally.
