### ISSUE TITLE
[Connector] Guidelines documentation

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/syndesis#5633]
Provide a document to describe a typical connector development. Later publish the document to syndesis.io.

**Comment by squakez** [comment]
First draft: https://docs.google.com/document/d/18HjIqCgIeechPmEiRW_RkH4-Ky3E9__88v5KdeO4c3E/edit

**Comment by squakez** [comment]
Going to talk to Lars Heinemann in order to help with a tool he's planning to work on. Can be based on the result of this documentation.
