### ISSUE TITLE
[Conditional Flow] Multiple conditional flow steps in the primary flow break the integration

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#5636]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Multiple conditional flows in the primary flow break the whole integration:

![out](https://user-images.githubusercontent.com/14313995/59100433-563b4c00-8926-11e9-94ce-9ccab72eeb3b.gif)

**Comment by mcada** [comment]
As of today the issue is still present:

![out](https://user-images.githubusercontent.com/14313995/59271419-0f19c780-8c54-11e9-832b-f798d2a5a1b0.gif)

**Comment by gashcrumb** [comment]
np, will have a look, thanks!

**Comment by gashcrumb** [comment]
@mcada also can you slow down a little bit when you record these gifs?  My aging brain apparently is needing more time to absorb what's going on :rofl:

**Comment by mcada** [comment]
It works with webhook + 2 flows but cannot use the reproducer from gif due to https://github.com/syndesisio/syndesis/issues/5716 so I will verify the issue when it gets fixed.
