### ISSUE TITLE
[MongoDB connector] Unit test

### ISSUE THREAD

**Issue by squakez** [syndesisio/syndesis#5639]

**Comment by mastepan** [comment]
@squakez what is this issue for? A planning or...? I'm asking because it;s in Done state.

**Comment by squakez** [comment]
> @squakez what is this issue for? A planning or...? I'm asking because it;s in Done state.

Hi @mastepan, it's a task of a bigger epic and I've completed that.

**Comment by mastepan** [comment]
@squakez can you please close this if it's finished and if there is nothing that prevents that? Thanks
