### ISSUE TITLE
Datamapper to Template step leads to blank screen

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#5652]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Whenever I try to create a mapping to template step the whole page goes white and reports this error in console: 

```
Error: "output document shape kind not supported"
    m utils.ts:184
    pr utils.ts:160
    render utils.js:753
    React 8
    
    render
    
    La
    
    qi
    
    Yi
    
    jc
    
    zc
    
    Ac
    
    En
react-dom.production.min.js:4408
Error: "output document shape kind not supported"
    m utils.ts:184
    pr utils.ts:160
    render utils.js:753
    React 8
react-dom.production.min.js:4408
Error: output document shape kind not supported utils.ts:184:10
    m utils.ts:184
    pr utils.ts:160
    render utils.js:753
    React 8
    En (index):1019
```

**Comment by riccardo-forina** [comment]
Fix here https://github.com/syndesisio/syndesis-react/pull/443

**Comment by gashcrumb** [comment]
Seems like the template step is supposed to have an input data shape matching the identifiers in the template, and maybe that's not happening, am I right there @phantomjinx?

**Comment by phantomjinx** [comment]
@gashcrumb 

Yes, the template step does expect a json-schema data shape. With the error posted from _getOutputDocument()_ (DataMapperPage.tsx), it would suggest that the DataMapper has thrown the error and the template editor going blank is maybe the UI now in a failed state?

**Comment by riccardo-forina** [comment]
No, it's the opposite: the UI gets the input document(s) before the step, and it searches for the output document (singular) after the step. An output document is mandatory, and that's an exception that's raised when we can't find it.

This is how to reproduce it:

> Try to create this integration:
> Start: timer
> End: log
> Add Template between those two with any text "{{test}}" will suffice
> And then try to place datamapper in front of template

The problem I think is that the template step doesn't provide an input data shape for us to properly set up data mapper.

**Comment by phantomjinx** [comment]
@riccardo-forina 
If this is the case then its surely an invalid use-case as there is no reason to put template-step between a timer and a log.

Note. this is not possible in the angular-ui, ie. the template-step just doesn't appear as an option.
![no-template-step](https://user-images.githubusercontent.com/1634180/59193069-6c424a00-8b7c-11e9-9c21-ad74718746c5.png)

**Comment by riccardo-forina** [comment]
That's what I did, restore the Angular behavior. But @gashcrumb [commented that that change might have been done on purpose?](https://github.com/syndesisio/syndesis-react/pull/443#issuecomment-500375204)

**Comment by phantomjinx** [comment]
@riccardo-forina 
Cool. Made a [comment](https://github.com/syndesisio/syndesis-react/pull/443#issuecomment-500392037) on the PR as well.

**Comment by gashcrumb** [comment]
@mmuzikar Can you try this scenario using the PorstgresDB connection instead of the timer and see if that works ok?

**Comment by mmuzikar** [comment]
@gashcrumb Yup the same thing happens when using the DB connection with the same error in console

**Comment by gashcrumb** [comment]
@igarashitm data mapper still needs to have a thing with an input data shape after it I guess?  I can unrelax that restriction I relaxed already :-)

**Comment by igarashitm** [comment]
Data Mapper UI can open without even a target document, but I think it doesn't make sense in Syndesis, rather it's better to hide data mapper step in that case.

**Comment by gashcrumb** [comment]
ok, will do, thanks!

**Comment by mmuzikar** [comment]
Verified.
