### ISSUE TITLE
Remove Tech Preview banner from OData and FHIR connector cards

### ISSUE THREAD

**Issue by TovaCohen** [syndesisio/syndesis#5657]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
In 7.4, the FHIR and OData connectors are supported. But in the staging and staging-2 sites, the cards for these connectors still display a Technology Preview banner: 

![image](https://user-images.githubusercontent.com/25067106/59203414-8b38e000-8b6c-11e9-8b46-07b96aa5d67b.png)

**Comment by paoloantinori** [comment]
Thank you @TovaCohen !

**Comment by mastepan** [comment]
@paoloantinori reopening as this hasn't been verified by QE yet.

**Comment by paoloantinori** [comment]
My bad. I might have done this on mulitple issues. I will pay more
attention to avoid this.

Sorry about that!

**Comment by tplevko** [comment]
Verified
