### ISSUE TITLE
❓ Look & Feel with very long strings

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis#5658]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Not a bug. But I've stumbled on an instance of a very long name for an Integration, that forces the layout to re-arrange a little and it's probably a good excuse to confirm if we like it this way or if we should truncate or hide.

![Screenshot from 2019-06-10 16-54-36](https://user-images.githubusercontent.com/1520602/59204346-b6d5bd80-8ba0-11e9-92a4-bd9670540a10.png)

**Comment by gaughan** [comment]
Not a blocker for 7.4. CAn we line break on the word in the future?

**Comment by dongniwang** [comment]
Agreed that this is not a blocker. Although I think line break on the word should be an easy fix, let's hear from @mcoker to be sure on this. 

Having two lines for integration name is acceptable, but anything longer than two lines should be truncated and accompany with a tooltip that shows the full name. 

Maybe the visual imbalance comes from the narrow space between the name column and the label column? @lboehling - what do you think?

**Comment by lboehling** [comment]
Yeah, I think it would look more balanced if we had a line break so the space between the name column and label column is larger. I agree that the names shouldn't show more than 2 lines. 

In the Recent Updates list, there seems to be more spacing btwn the name column and label column, making the text wrap look more balanced (though it does add uneven spacing below the timestamp/label).

**Comment by mcoker** [comment]
FWIW, the default from PF is to truncate the name with `...` and keep it on one line.

**Comment by dongniwang** [comment]
@mcoker - Good to know. Is this for both PF3 and PF4? 

I feel like we may need the second line because we're only displaying about 5 words per line and that's probably not enough for users to describe the integration...

**Comment by mcoker** [comment]
Just PF3. PF4 doesn't truncate any content.
