### ISSUE TITLE
Integration List needs more sorting options

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#5660]
See also **https://issues.jboss.org/browse/ENTESB-11556**

## This is a...

<pre><code>
[x ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

We should add the ability to sort by: 

- last created 
- last edited

![image](https://user-images.githubusercontent.com/674767/59205640-4a8f9580-8b71-11e9-8d35-23b7b13223a5.png)

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11556**
