### ISSUE TITLE
Pause icon can't be "played"

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#5661]
## This is a...

<pre><code>
[ x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

We have a cool pause icon, but you cant start the integration by clicking "play"

![image](https://user-images.githubusercontent.com/674767/59206043-17013b00-8b72-11e9-9fe0-8243c7e6b4a5.png)

**Comment by gashcrumb** [comment]
Seems a bit redundant to have a "pause" icon next to the "Stopped" text.  Plus, when the integration is running it's a green check.  So I dunno seems a bit out of place :smile:.

**Comment by dongniwang** [comment]
Let's remove the "pause" icon as it's not adding value here and could be misleading.

**Comment by mcoker** [comment]
Are we just trying to remove the icon and leave the functionality in place to revisit later, or do we want to remove the feature all together? I can remove the icon from the page, but I would likely need to pass this to someone else to remove the underlying functionality.

**Comment by gashcrumb** [comment]
I think the icon just sits alongside the detailed status component there, so it's just a matter of removing that element and leaving the detailed status component.  And the "stopped" badge thingy.  Basically the way it was in the angular app.

**Comment by mcoker** [comment]
Looks like this was fixed by @seanforyou23 in https://github.com/syndesisio/syndesis-react/commit/88f5d5e133d08791d36f8b4446ce9df3b1ba9695
