### ISSUE TITLE
Conditional Flow Alignment is off on the first condition

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#5662]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Documentation issue or request
</code></pre>

![image](https://user-images.githubusercontent.com/674767/59207128-69dbf200-8b74-11e9-855c-19052aa1ec36.png)

**Comment by gashcrumb** [comment]
Which control?  The "up" arrow is hidden in the first row and the "down" arrow is hidden in the last row.  The arrows are aligned based on their direction.

I'm calling the arrows an MVP thing anyways, ultimately we should do drag/drop for this, maybe with the arrows as a fallback.

**Comment by gaughan** [comment]
Ah I see it now, my bad. We can close this.
