### ISSUE TITLE
View/edit API definition is not accessible from the operation list

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#5665]
## This is a...

<pre><code>
[x] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
On the angular UI it was possible to change the API definition from the operations list (the first page that you see after you click edit). Now on the react UI it is possible only when editing some flow of that operation... which is quite cumbersome, naturally I would think that edit API definition would be present when I try to edit the integration tied to that API.

Here you can see no link to edit the definition:
![image](https://user-images.githubusercontent.com/46345469/59256607-97887000-8c34-11e9-914e-bde64762673a.png)

You have to edit a flow to edit the integration:
![image](https://user-images.githubusercontent.com/46345469/59256650-a96a1300-8c34-11e9-894b-83df5adf06cc.png)

It was accessible on the angular UI right away:
![image](https://user-images.githubusercontent.com/46345469/59256693-c1419700-8c34-11e9-8fdd-58b216c03c22.png)

**Comment by gaughan** [comment]
Just bumped into this also today

**Comment by riccardo-forina** [comment]
Should be fixed by https://github.com/syndesisio/syndesis-react/pull/456

**Comment by mmuzikar** [comment]
> Should be fixed by [syndesisio/syndesis-react#456](https://github.com/syndesisio/syndesis-react/pull/456)

[syndesisio/syndesis-react#456](https://github.com/syndesisio/syndesis-react/pull/456) was merged and the link is present, this issue is verified
