### ISSUE TITLE
[api client connector] basic authentication does not work

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#5669]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Basic authentication is selected by default but `Next` button is disabled:

![screenshot_20190611_132057](https://user-images.githubusercontent.com/14313995/59267952-d544c300-8c4b-11e9-9071-b4ff0fe823c1.png)

Adding two Basic authentication options is broken - it has the same name, selecting them does not work - the same bug as above:

![screenshot_20190611_132220](https://user-images.githubusercontent.com/14313995/59268021-11782380-8c4c-11e9-83ab-9695ea61f2c6.png)

**Comment by riccardo-forina** [comment]
Can you share the document you're using for both scenario?

**Comment by riccardo-forina** [comment]
The second case is an edge one, we don't get other info from the API to enrich the authentication type description. Nor we can really work with two types of the same. @zregvart suggestions?

**Comment by zregvart** [comment]
> The second case is an edge one, we don't get other info from the API to enrich the authentication type description. Nor we can really work with two types of the same. @zregvart suggestions?

Yeah, not sure if it makes sense to have multiple basic authentication security definitions in an OpenAPI document (it is allowed by specification/schema), they would only differ by description. I don't think we would see much of this in the wild.

We can add description to the label if that would help.

**Comment by riccardo-forina** [comment]
I guess it would, but the definition for the authorization field would require some tweak too so that the types of the same type (lol) actually have different values. Else the radio would not work.

**Comment by riccardo-forina** [comment]
https://github.com/syndesisio/syndesis-react/pull/461 should fix the first case (next button disabled with a single option available)

**Comment by mcada** [comment]
@riccardo-forina the next button is still disabled, tried on syndesis dde62844cc7c9cedf63074e73323608a1449ca1d

![screenshot_20190618_094441](https://user-images.githubusercontent.com/14313995/59662673-b5fae800-91ad-11e9-9129-652b7e21a4c3.png)

**Comment by riccardo-forina** [comment]
Thank you. Apparently, the recent change in the BE to give us a better description wasn't coping well with the "is valid" logic we had in the FE. I pushed a PR to address that.
