### ISSUE TITLE
[api client connector] specify security block is not centered correctly

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#5670]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
![screenshot_20190611_132057](https://user-images.githubusercontent.com/14313995/59268097-471d0c80-8c4c-11e9-8f75-95c95a1e5196.png)

Edit: Also the radio element is not aligned with the label.

**Comment by riccardo-forina** [comment]
https://github.com/syndesisio/syndesis-react/pull/461 fixes this

**Comment by mcoker** [comment]
> Edit: Also the radio element is not aligned with the label.

To fix that, I think we should change the `body`'s `line-height` to either 1.6 (PF3 default) or `--pf-global--LineHeight--md` (PF4 default, which is 1.5). That has some far reaching implications, and might require some other updates as it would impact the line-height on most/all pages. I'm down for giving it a try. WDYT @dongniwang? Should I try and do that today?

**Comment by dongniwang** [comment]
@mcoker - Is there a way to do some investigative work for this? Would it be a quick fix which means they it's something you can wrap up today?  My main concern is whether or not changing the line height affect the display of other UI elements, like checkboxes, text input field, or icons (info icons)?

**Comment by riccardo-forina** [comment]
I'd classify that as an enhancement and do it for 7.5, with all the required time to evaluate the fallback.

**Comment by heiko-braun** [comment]
Migrated to https://issues.jboss.org/browse/ENTESB-11416
