### ISSUE TITLE
[Conditional flow] icons to manipulate conditions are too small

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#5671]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
The icons with arrows and delete icon are too small:

![screenshot_20190611_133234](https://user-images.githubusercontent.com/14313995/59268708-9d3e7f80-8c4d-11e9-95b7-5e037a183b48.png)

**Comment by gashcrumb** [comment]
Yeah, I have some CSS in auto-form that' supposed to make those bigger but it's not getting picked up, thanks for raising this as it's been bugging me but I keep forgetting to raise it :-)
