### ISSUE TITLE
[Conditional Flow] moving a condition changes layout based on help message under it

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#5672]
See also **https://issues.jboss.org/browse/ENTESB-11470**

## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
The second condition position is changing when moved to first place:

![out](https://user-images.githubusercontent.com/14313995/59269217-d9beab00-8c4e-11e9-8b90-7e2931f63134.gif)

**Comment by riccardo-forina** [comment]
Well, that's because the second condition's description is on 2 lines. I don't think there is much that can be done here.

**Comment by mcada** [comment]
That is why it is in the title of this issue - my point is that this "feature" does not look good. It is just p2 issue, probably an enhancement. We can add more space between conditions so it does not jump even with two lines of comment.

**Comment by christophd** [comment]
Layout of form fields has changed significantly. Moving this one to `Done` in order to trigger reevaluation.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11470**
