### ISSUE TITLE
[Conditional Flow] back to the primary flow button is missing

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#5673]
See also **https://issues.jboss.org/browse/ENTESB-11469**

## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
There was a button `back to primary flow` in angular UI. Now the button is hidden in flow dropdown, which is not intuitive. Maybe we can add the button back so it is visible on the first view? Current state will be confusing for first time users.

![screenshot_20190611_135625](https://user-images.githubusercontent.com/14313995/59270016-be549f80-8c50-11e9-8827-50e690481b07.png)

![screenshot_20190611_135633](https://user-images.githubusercontent.com/14313995/59270014-bdbc0900-8c50-11e9-88c5-56fc3e2d3d6e.png)

**Comment by gashcrumb** [comment]
+1

@dongniwang I guess put it with the other buttons?  And should we keep the button in the dropdown or not?

**Comment by dongniwang** [comment]
Yup, we can add a button with other buttons, and can we label it as "back to primary flow" or something similar. 

I think it's fine to keep the button in the dropdown.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11469**
