### ISSUE TITLE
[API provider] 15+ operations in API provider cause black design

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#5675]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
![out](https://user-images.githubusercontent.com/14313995/59272973-79803700-8c57-11e9-93ce-f4f416d49fa6.gif)

**Comment by gashcrumb** [comment]
Darn, you found where we hide all the band-aids and tape.

**Comment by mcada** [comment]
The issue is still present.

**Comment by riccardo-forina** [comment]
Are you sure you're running against the latest version of all? I personally fixed this, it was a bit late but I'm quite sure this was fixed.

**Comment by riccardo-forina** [comment]
I mean, this is what I get from a long list of operations:

![scrollable-operations](https://user-images.githubusercontent.com/966316/59416935-9dae5600-8dc6-11e9-8bcf-c1c40d9946a2.gif)

**Comment by mcada** [comment]
I am using latest image so it is possible that its not there yet. The commit of my syndesis is 7226de41a84b7ed37e9717fa7e0bd75eec6cdaf0

**Comment by riccardo-forina** [comment]
Right, it's not there yet then. The latest sync should eventually build a new image containing the fix.

**Comment by mcada** [comment]
Verified.
