### ISSUE TITLE
[Conditional flow] Condition manipulation icons are broken

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#5676]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
The behavior is unpredictable:

![out](https://user-images.githubusercontent.com/14313995/59273508-aa14a080-8c58-11e9-8e13-1b33fe695203.gif)

![out](https://user-images.githubusercontent.com/14313995/59273562-c87a9c00-8c58-11e9-828a-4b52e80d7e0a.gif)

![out](https://user-images.githubusercontent.com/14313995/59273619-ecd67880-8c58-11e9-8c9a-e6611bace2b9.gif)

**Comment by gashcrumb** [comment]
Um, no there's actually some thought in there.  The form requires at least 1 condition, so when you remove all the other ones the trash icon is removed.  Also you can't obviously move the first condition up or the last condition down, so those arrows are hidden.  The icon placement stays consistent with the arrow direction so that they're arranged in columns.

**Comment by gashcrumb** [comment]
@dongniwang I could probably be convinced to set these buttons to disabled vs hiding 'em, think that'd be a better option?

**Comment by dongniwang** [comment]
Yeah, I was going to suggest that we just disabled those icons.

**Comment by mcada** [comment]
> Um, no there's actually some thought in there. The form requires at least 1 condition, so when you remove all the other ones the trash icon is removed. Also you can't obviously move the first condition up or the last condition down, so those arrows are hidden. The icon placement stays consistent with the arrow direction so that they're arranged in columns.

@gashcrumb I do not know what you are talking about, the issue is not about the icons but the functionality:

First gif: I can not move second condition up.
Second gif: deleting the first condition deletes the second one.
Third gif: moving the condition copies the value to another condition.

**Comment by gashcrumb** [comment]
Ah, I see.  A caption on the gifs would have been helpful to understand what I'm looking at :laughing:

**Comment by mcada** [comment]
My bad, will do next time :)

**Comment by gashcrumb** [comment]
hmm, yeah I think the main problem is that this occurs when you use the buttons before actually entering things into the field.  So probably I just need to revisit what's going on when a new entry is added to the array.

**Comment by gashcrumb** [comment]
Assuming the p0 label was taken off in error :smile:

**Comment by mcada** [comment]
All 3 scenarios are still broken, tested on syndesis 7226de41a84b7ed37e9717fa7e0bd75eec6cdaf0

**Comment by mastepan** [comment]
@mcada @gashcrumb just checking. Is there anything that should be checked by QE?

**Comment by mcada** [comment]
@mastepan there is automated test for this use-case, please run it against current syndesis master just to be sure that it works
