### ISSUE TITLE
Atlasmap doesn't save configured mappings 

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#5678]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
I am able to create a mapping inside atlasmap but it doesn't save. Trying to get more information if it's only camel-k behavior or happens even on "normal" version.

This GIF describes the issue better then I could: 
![Peek 2019-06-11 15-36](https://user-images.githubusercontent.com/46345469/59277448-86edef00-8c60-11e9-9873-07f348f055a9.gif)

No traceable logs found in server neither in browser console.

**Comment by lburgazzoli** [comment]
I saw this in the past and there was some syncing issue, maybe @gashcrumb knows more

**Comment by mmuzikar** [comment]
I would swear that it worked in the morning today... but you are correct @lburgazzoli it was just my first instinct to blame it on the most obvious change :D

**Comment by lburgazzoli** [comment]
I remember that the `done` button was disable till something happen in the background to indicate the mapping is ready to be saved. I think that if you slows down a bit your test and leave some time between the mapping and hitting the save button, then you could get your desired behaviour.

**Comment by mmuzikar** [comment]
Waiting even for 10 seconds doesn't help. What solves this issue is clicking on other property inside the atlas map

**Comment by christophd** [comment]
I saw this on the Angular code base today, too. So it seems to be related to Atlasmap itself

**Comment by igarashitm** [comment]
It sounds like this one https://github.com/syndesisio/syndesis/issues/4874
User action is required to trigger save mapping event at this moment.

**Comment by igarashitm** [comment]
Maybe it started to happen now because I just bumped up AtlasMap version to 1.40.0-beta1 for syndesis-react repo. It used to be 1.39.6 till yesterday.

**Comment by igarashitm** [comment]
ah wait, this looks even worse, if it establish a mapping then save mapping event should be triggered.

**Comment by igarashitm** [comment]
Hmm tested with AtlasMap upstream master by adding event listener for debugging and verified mappingUpdated event is emitted for sure. It might have been already fixed as a part of another bug. Let's have AtlasMap beta2 release and bring into Syndesis.

**Comment by igarashitm** [comment]
OK I found a root issue in AtlasMap UI, atlasmap/atlasmap#992

**Comment by KurtStam** [comment]
@igarashitm when will this fix make it into Syndesis?

**Comment by igarashitm** [comment]
@KurtStam the plan is to have a release tomorrow morning and then bump in Syndesis

**Comment by mmuzikar** [comment]
Verified by QE
