### ISSUE TITLE
[camel-k] All integrations create a route for themselves 

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#5679]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
All integrations created in Syndesis using camel-k create a route for themselves and display this route in integration details. The route leads nowhere and is quite confusing as to what I as a user should be using that route for.

![image](https://user-images.githubusercontent.com/46345469/59278000-7c802500-8c61-11e9-8737-9a1a8be6d6c0.png)

The route is created in Openshift as well, with Openshift informing the user that the target pod is http but the route has no port with that name.

**Comment by nicolaferraro** [comment]
Cannot reproduce. This code should have fixed it: https://github.com/syndesisio/syndesis/blob/master/app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/customizer/ExposureCustomizer.java

**Comment by nicolaferraro** [comment]
Found the issue in camel k that creates a route on top of the prometheus service.

**Comment by nicolaferraro** [comment]
Opened https://github.com/apache/camel-k/issues/749

**Comment by nicolaferraro** [comment]
This has been already fixed in the prod version: https://github.com/jboss-fuse/camel-k/commit/1307bd10bdb6574f9fe06139080dc4be8fc6c9ad

**Comment by mmuzikar** [comment]
Verified by QE
