### ISSUE TITLE
SQL statement contains text from the previous step

### ISSUE THREAD

**Issue by mkralik3** [syndesisio/syndesis#5686]
See also **https://issues.jboss.org/browse/ENTESB-11415**

## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Every time when I add Database step before another Database step, the Invoke SQL is predefined according to the existing Database step.

When I want to create DB step for Invoke SQL, and I have already defined another Invoke SQL step which is before that step, the SQL statement is automatically predefined and it is same as SQL statement in the step which was defined before.
![output](https://user-images.githubusercontent.com/16251792/59333247-3de97980-8cf8-11e9-96b1-5196bcdc0db2.gif)
When I add another step between them, e.g. log step, the SQL statement is empty.
![output](https://user-images.githubusercontent.com/16251792/59333272-49d53b80-8cf8-11e9-9d15-4212065484e7.gif)

**Comment by riccardo-forina** [comment]
This should fix it https://github.com/syndesisio/syndesis-react/pull/463

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11415**
