### ISSUE TITLE
Property descriptions missing

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#5689]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

From #4878, we seem to be missing property descriptions in the React UI, i.e. it seems that this:

https://github.com/syndesisio/syndesis/blob/25f4d4759b7828682752f9f6774d25f57033bbd9/app/connector/sql/src/main/resources/META-INF/syndesis/connector/sql.json#L61

is not shown in the UI.

**Comment by riccardo-forina** [comment]
Fixed by https://github.com/syndesisio/syndesis-react/pull/464

**Comment by claudio4j** [comment]
This is fixed in master branch. If there is no objection, this can be closed.
