### ISSUE TITLE
Errors in integrations cause the activity page to be misaligned

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#5693]
See also **https://issues.jboss.org/browse/ENTESB-11413**

## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
The image speaks for itself: 
![image](https://user-images.githubusercontent.com/46345469/59346064-bf013a80-8d11-11e9-83e4-0881078eb93e.png)

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11413**
