### ISSUE TITLE
API provider definition can't be edited after creating the integration

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#5697]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
After creating an API provider integration, the definition cannot be changed. Any changes made are just ignored. This blocks me to verify #5332 because nothing can be reflected in the UI since nothing can be changed.

![Peek 2019-06-12 14-31](https://user-images.githubusercontent.com/46345469/59351570-fcb89000-8d1e-11e9-8b51-0432ddebddc9.gif)

**Comment by mmuzikar** [comment]
@riccardo-forina There are still problems with editing the definition, as it is shown in this GIF:

![Peek 2019-06-18 13-58](https://user-images.githubusercontent.com/46345469/59680297-426ad200-91d1-11e9-8f0f-2ac567309996.gif)

**Comment by riccardo-forina** [comment]
Right, so this is an edge case that I didn't consider. 

Before showing Apicurio we call an API- `/v1/api/integrations/[integration id]/specification`-to get its specification back; the problem is that in this case the integration has not been saved yet, so the call to the API fails because we pass an ID which isn't a valid one.

Without the specification, we can't show the editor. In addition to that, we are missing the UI part of this PR here https://github.com/syndesisio/syndesis/pull/5724; so what happens right now is that if you change the specification for an existing integration, any customization done on that integration-eg, adding steps or configuring return codes-is effectively lost.

@zregvart any chance we can have a version of `/v1/api/integrations/[integration id]/specification` that instead of asking for an id asks for the actual integration object?

**Comment by mmuzikar** [comment]
It is now possible to edit the definition, but it would probably be easier and more convenient to write it by hand right now.
Integration has to be saved everytime user changes the definition, which shows the save dialog on each save, meaning each save the user has to input an integration name.
On each save of the definition user is navigate to an operation flow, not list of all operations.

Attaching GIF of what it currently behaves like:
![Peek 2019-06-25 09-32](https://user-images.githubusercontent.com/46345469/60079196-b6efc480-972d-11e9-8cee-9699b3b6a97c.gif)

I have zero clues about what each of the buttons **actually** do, but shouldn't the save in API provider definition save the definition, not after the integration is saved? Or is it that the definition gets saved but the integration implementing the definition has to be saved in order for the definition to get saved?

**Comment by paoloantinori** [comment]
@zregvart can you comment on this? 

@zregvart any chance we can have a version of /v1/api/integrations/[integration id]/specification that instead of asking for an id asks for the actual integration object?

Is this something that we can do, that seems the UI needs?

**Comment by zregvart** [comment]
From the last chat communication, there are two issues that need to be resolved on the server for this to be implemented: #5924 and #5936.

**Comment by paoloantinori** [comment]
Are the two additional issues linked required to have this fixed? Because if it's so, we need to raise them to blocker status.

**Comment by riccardo-forina** [comment]
Think so, there is no workaround without those but going back to force saving the integration when working with an OpenAPI definition, which is a very big change and definitely not the direction we want to follow in the new UI.

**Comment by heiko-braun** [comment]
I am raising #5924 and #5936 to blocking to make it more visible

**Comment by zregvart** [comment]
@heiko-braun I think you want to make #5963 blocking as well

**Comment by mmuzikar** [comment]
Just a heads up, I am currently trying to fix API provider tests and before it wasn't possible to create any flows before the integration was saved... wouldn't that save a lot of your problems? @gashcrumb @riccardo-forina

**Comment by gashcrumb** [comment]
Honestly it didn't help that much in the angular app :smile:

**Comment by heiko-braun** [comment]
@riccardo-forina @gashcrumb It seems the dependent changes are done. Is this in your ballpark now?

**Comment by riccardo-forina** [comment]
PR is ready, it just needs to be merged and this should be fixed.

**Comment by heiko-braun** [comment]
Thanks @riccardo-forina !

**Comment by tplevko** [comment]
Moving to "Done" for verification. @mmuzikar can you please have a look?

**Comment by mmuzikar** [comment]
The definition can be changed even on unsaved API Provider, great job. Verified.
