### ISSUE TITLE
Post install Addon

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis#5698]
## This is a...

<pre><code>
[ x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Today we have just redeployed syndesis and we have forgot to apply at least one manual step:
- to modify the limit of the integration number per users.

I'd suggest to collect this manual edit + any eventual other we normally perform directly under an `addon/` with either OpenShift resource definition or eventually `oc` commands.

@zregvart wdyt?

**Comment by zregvart** [comment]
Or we make the default unlimited and the limit is applied where it needs to be applied...
