### ISSUE TITLE
No way to delete mapping on smaller window

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#5699]
See also **https://issues.jboss.org/browse/ENTESB-11468**

## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
The `mapping details` window of data mapper doesn't show up on smaller width (around 1000 px) and it is quite necessary in order to be able to use atlas mapper. AFAIK there's no way how to remove mappings other than from the details. I did a bit of a mess in the end part of the GIF trying to find a way to remove it.

![Peek 2019-06-12 14-53](https://user-images.githubusercontent.com/46345469/59353050-68502c80-8d22-11e9-9662-bd012cac8e21.gif)

**Comment by riccardo-forina** [comment]
Fixed by https://github.com/syndesisio/syndesis-react/pull/469

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11468**
