### ISSUE TITLE
Basic Filter cannot continue with a predefined condition

### ISSUE THREAD

**Issue by mkralik3** [syndesisio/syndesis#5701]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Basic Filter has predefined `equals` condition. When I fill in values to the Basic Filter step, the Done button is still disabled. I have to choose another condition and set equals back.
![output](https://user-images.githubusercontent.com/16251792/59355818-fda1ef80-8d27-11e9-8f5e-75ecccedee67.gif)

**Comment by riccardo-forina** [comment]
I can't reproduce this on the latest master.

**Comment by mkralik3** [comment]
me neither (in Chrome). It looks that issue is gone.
