### ISSUE TITLE
Add Technology Preview label for Amazon SQS, SNS, BOX, KNative connectors

### ISSUE THREAD

**Issue by tplevko** [syndesisio/syndesis#5704]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Add Technology Preview label for Amazon SQS, SNS, BOX, KNative connectors - these should be marked as TP for this release.

**Comment by oscerd** [comment]
I don't think SQS and SNS are TP. There is no more work to do on them, except enhancement. So I think for these two connectors there is no need for TP.

**Comment by paoloantinori** [comment]
@gaughan could help us to clarify this? are all these connectors in TP?

**Comment by tplevko** [comment]
@gaughan @oscerd I was informed by @avano that from QE perspective - the SQS can be considered GA for this release and the same is true for SNS. In case the decision is made to not release this as TP - I believe this should be communicated with the docs team too.

Also the KNative connector apparently already contains the "Technology preview" label.
In case the SQS and SNS get's GA'ed - the only connector needing the TP label is the Box connector, which still needs some additional work to be GA from our POV.

**Comment by oscerd** [comment]
Ok, I'll add the TP only for Box connector.
