### ISSUE TITLE
View/Edit API

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#5707]
See also **https://issues.jboss.org/browse/ENTESB-11555**

## This is a...

<pre><code>
[x ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

Currently, we always display View/Edit link but don't always support edit (after publish)
We should use edit only when available and not allow when not supported.
Or add the ability to edit after publish.
![image](https://user-images.githubusercontent.com/674767/59373863-916bbf80-8d18-11e9-85d5-c35a0f64ce9e.png)

**Comment by riccardo-forina** [comment]
So right now there is no such logic, the link is always visible regardless of the integration being published or not. Is that a problem?

Also, I'm not sure how reliably we can check for the integration status while in the editor. Why is that important that the integration shouldn't be published already?

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11555**
