### ISSUE TITLE
Check S2I Module

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#571]
The s2i module currently depends on the rest module. This must not be the case. Also it generates / copies code under src/ which also needs an updated in the dmp configuration.

**Comment by gashcrumb** [comment]
Seems stale?

**Comment by rhuss** [comment]
Let me still have a look, as I still believe there are gremlins.

**Comment by rhuss** [comment]
Not sure that I can work on this issue. Still a thing I believe, but going to unassign myself.
