### ISSUE TITLE
NaN duration in the activity log

### ISSUE THREAD

**Issue by mkralik3** [syndesisio/syndesis#5715]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
The Advanced Filter and Basic Filter have _NaN_ Duration in the activity log.
![image](https://user-images.githubusercontent.com/16251792/59415116-27f4bb00-8dc3-11e9-94fb-1f8c649de33c.png)
The back-end returns _0_ as a duration:
![image](https://user-images.githubusercontent.com/16251792/59415344-933e8d00-8dc3-11e9-88b0-964ae678d3a3.png)

**Comment by mcoker** [comment]
@gashcrumb or @seanforyou23 I'm not sure how to address this. Would one of you mind taking this on or reassigning?

**Comment by gashcrumb** [comment]
@mcoker sure thing!

@mkralik3 I mean, it could be argued that's kinda accurate, I dunno :-)

@elvisisking I guess maybe if it's `0` here like the backend says we just avoid passing the value to moment.js and just hard-code it to show `0 ms`?

**Comment by mkralik3** [comment]
@elvisisking Is this already fixed or just partially? Now I see the correct duration in the activity log for a basic filter step on the 1.7.x branch. However, the basic filter is there twice:
![image](https://user-images.githubusercontent.com/16251792/60096990-ae5db500-9752-11e9-995d-b68b27f7836e.png)
The backend returns it twice too:
![image](https://user-images.githubusercontent.com/16251792/60097033-c6cdcf80-9752-11e9-9a4c-d4249d3e517d.png)
The integration which I used:
![image](https://user-images.githubusercontent.com/16251792/60097062-d9e09f80-9752-11e9-853b-549e9487feff.png)

**Comment by mkralik3** [comment]
^Sorry, my bad, the Basic Filter is shown twice because the db contains two items and a split step runs the basic filter twice (only one passed and got to the log)
