### ISSUE TITLE
[Conditional flow] It is not possible to add conditional flow step after split step

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#5716]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Adding conditional flow step after split step results in `Done` button doing nothing and an error in console: `Error: Cannot create conditional flow for a step with no ID set`. 

![screenshot_20190613_101918](https://user-images.githubusercontent.com/14313995/59415918-bb7abb80-8dc4-11e9-9798-476bc4152bb8.png)

**Comment by mcada** [comment]
On newer image I can not even add conditional flow after webhook step, but it may be the same issue so I will not create new one.

**Comment by gashcrumb** [comment]
On master:

![image](https://user-images.githubusercontent.com/351660/59433367-5d93a700-8db7-11e9-9385-29959b9e6284.png)

Was also able to do the same against the staging instance.  Maybe this was tested too early?

**Comment by mcada** [comment]
@gashcrumb does not work on 63e4ed69c1c4135242adfcfd51d1a9719c873200

**Comment by mcada** [comment]
@gashcrumb ok this is weird, after deleting cookies it started to work again...

**Comment by mcada** [comment]
What bothers me is that when I run my automated tests it does not work - but it runs fresh browser... Investigating...

**Comment by gashcrumb** [comment]
We also disabled the service worker that prompts you to refresh when there's changes, so you'll want to ensure you clear your cache, cookies etc. probably before starting a fresh run, hopefully that should do the trick!

**Comment by mcada** [comment]
It still does not work, even when I cleared everything. Yesterday it worked well so i am a bit confused now... Lets wipe minishift...

**Comment by gashcrumb** [comment]
Weird, I tried staging this morning (like the deployed one) and it worked there too.

**Comment by gashcrumb** [comment]
Maybe the feature just needs a Friday to work properly.  Or a weekend of rest.  We've probably tired it out.

**Comment by mcada** [comment]
Ok so what I found out is that there is a bug. I do not know where yet, but in the same browser session I am sometimes able to add the conditional flow step and sometimes it throws mentioned error. It has something to do with the default condition flow.

**Comment by riccardo-forina** [comment]
(sorry miss-clicked the close button)

Can you check the network panel when that happens? I have noticed some flappines of the API we use to retrieve the updated steps while developing, sometimes it errors out. I assumed it was something to do with our dev proxy, but maybe it isn't.

**Comment by mcada** [comment]
![out](https://user-images.githubusercontent.com/14313995/59438257-74f08580-8df3-11e9-9aa2-9dc93a0f8be0.gif)

I did not manage to record the whole console but I do not know what may be wrong there. The error in console is present.

**Comment by gashcrumb** [comment]
ah, well that would do it.  The exception there is totally on purpose to protect against those other bugs, as they're due to a broken relationship between the step and the flows it points to.  But that gives me something to watch out for, thanks!

**Comment by mcada** [comment]
Here you have the whole console, it does not allow to create default flow at first, but configuring it again you can add it. That is... Not intuitive? :)

![out](https://user-images.githubusercontent.com/14313995/59438613-2394c600-8df4-11e9-9e0c-13262305a75c.gif)

**Comment by gashcrumb** [comment]
Yeah, so I think really what's needed is some error handling here for that backend call which is definitely not happening at the moment.  As part of working on [this issue](https://github.com/syndesisio/syndesis/issues/5215) I'll add this in and do what I can to kinda preserve the state should the backend come back with an error and also add an error alert to the page.  Thankfully this state is built up when "Done" is clicked so there's no data lost.

Also there could be a thing here where the backend isn't liking the step configuration I'm creating, maybe that's causing some problem with the response.  Again, all good to know and stuff I can try and test here locally, so thanks!

**Comment by gashcrumb** [comment]
I still can't get it to happen against the staging instance at all.  Can you open [this link](https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/integrations/i-LhGP9p9PVLglhrDYincz/details) alright and reproduce at your end?

**Comment by mcada** [comment]
I do not have permissions to log in.

**Comment by zregvart** [comment]
@mcada I've added you to the `syndesis` group on staging, you should have the permissions now

**Comment by mcada** [comment]
Thanks, I was able to reproduce it - the same way as on the gif. I also tried webhook -> conditional flow step and the behavior is the same - when default flow is selected, the error happens and done button does nothing.

**Comment by riccardo-forina** [comment]
Anything in the console or the network panel?

**Comment by mcada** [comment]
It is all the same as on the gif so I do not know what I should look for.

**Comment by riccardo-forina** [comment]
Ok thanks

**Comment by gashcrumb** [comment]
Oh, so I did catch a dumb mistake I was making that could lead to this, not sure why I haven't hit it locally yet.  Anyways, the work on syndesisio/syndesis-react#470 I think didn't land onto staging until after you've tested it, I can't tell.

**Comment by gashcrumb** [comment]
Hey, I just got it to happen!  Yay!

**Comment by gashcrumb** [comment]
Ah, so checked staging's about dialog, it's still at e8815dba21b89ddd1c30e56e9326d0d54984e062 which doesn't have that mentioned PR.  And I can't reproduce this on master.  I did notice however that the page is adding a bunch of extra junk to the step it's creating, so I'll have a little more work to attach to this one.

**Comment by gashcrumb** [comment]
Nope, I lied, it's exactly one case where this happens, just figured it out.  Phew!
