### ISSUE TITLE
[UI][SQS] Disable group/deduplication id enums when not working with fifo queue

### ISSUE THREAD

**Issue by avano** [syndesisio/syndesis#5718]
See also **https://issues.jboss.org/browse/ENTESB-11467**

## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When publishing message to SQS queue, the user can specify group id and deduplication id for the messages - these are valid only for fifo queues. Fifo queues in SQS needs to end with ".fifo" suffix, so it would be nice, if the queue doesn't end with ".fifo" suffix, disable the mentioned enums as they will not have any effect anyway

**Comment by paoloantinori** [comment]
This is interesting and it's actually just an instance of a larger pattern:

- figure out a maintainable way to offer customization for the configuration pages, both on the layout and on the validation/local dependencies between widgets

**Comment by paoloantinori** [comment]
We will try to fit this in 7.5 features list

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11467**
