### ISSUE TITLE
API generator update endpoint

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#5719]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
From the discussion on https://github.com/syndesisio/syndesis-react/pull/456. We need a `PUT /api/v1/apis/generator` endpoint that receives the Integration JSON and the OpenAPI document, updates the Integration JSON according to the OpenAPI document and stores/replaces the OpenAPI document stored on the backend.

**Comment by mastepan** [comment]
@zregvart can you please provide steps to verify this issue? Or add ignore/QE label if verification not needed. Thanks.

**Comment by tplevko** [comment]
The PUT endpoint is present and doing exactly what it's supposed to do. Closing as verified.
