### ISSUE TITLE
IllegalArgument Exception thrown

### ISSUE THREAD

**Issue by honghuac** [syndesisio/syndesis#572]
The following errors appear in the installation trace of Syndesis on OCP 3.6

```
[ XNIO-2 task-24] s.r.v.h.e.IllegalArgumentExceptionMapper : Illegal Argument on Call Cannot find field invalid_field in io.syndesis.model.integration.Integration as int or String field
java.lang.IllegalArgumentException: Cannot find field invalid_field in io.syndesis.model.integration
```

Full error trace : https://gist.github.com/honghuac/d2883e9c3f1740b3f29a272839f95700

**Comment by zregvart** [comment]
It's a part of the test that checks that sorting by unknown field results in an error:

https://github.com/syndesisio/syndesis/blob/857988c72ee4dc537de1843d4f012fd1da7fd91a/app/rest/runtime/src/test/java/io/syndesis/runtime/IntegrationsITCase.java#L53-L58
