### ISSUE TITLE
[About page] Accessing about page when creating integration breaks syndesis

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#5720]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Accessing about page when creating integration breaks syndesis:

![out](https://user-images.githubusercontent.com/14313995/59419466-4bbbff00-8dcb-11e9-83fe-be1e7a7ee011.gif)

**Comment by riccardo-forina** [comment]
https://github.com/syndesisio/syndesis-react/pull/462 should fix this
