### ISSUE TITLE
Support total customization for configuration pages

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis#5722]
See also **https://issues.jboss.org/browse/ENTESB-11496**

## This is a...

<pre><code>
[x ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

We currently have a generic logic to render forms. This has implicit limits on the expressivity to support complex UX.

For example:
widget A should be enabled only if a specific set of values on widget B has been selected.

We should organize a strategy to allow deviation from standard behavior.

**Comment by gashcrumb** [comment]
I think what you really mean to say is we should [implement this issue](https://github.com/syndesisio/syndesis-react/issues/192) as we already have this concept in the form definition.

Trouble is it never worked quite right in the angular app, and could only be used to disable fields, not hide them altogether.  So yep, definitely something we want to get going.

**Comment by gashcrumb** [comment]
Of course, now I can't for the life of me find an example connector definition that was using the `relation` property :smile:

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11496**
