### ISSUE TITLE
Streamlining Maven group and artifact ids

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#573]
This is currently a wild mix.

Suggestions:

* group-id: io.syndesis.rest, io.syndesis.runtime, ...
* artifact-id: rest-model, rest-runtime, .... (so that artifact ids are also unique among all maven modules)

Also, remove unneeded intermediate parent pom.xml which only add to the build time,

However, wait for changing until @lburgazzoli has done its connectors refactoring.

**Comment by jimmidyson** [comment]
@syndesisio/backend Is this necessary for TP3 or can we push this out to TP4?

**Comment by zregvart** [comment]
I think this would complicate ongoing PRs and on basis of that I would push this beyond TP3.

**Comment by rhuss** [comment]
Argeed, lets target tp4 for this ....
