### ISSUE TITLE
Split not able to work with FTP connector

### ISSUE THREAD

**Issue by christophd** [syndesisio/syndesis#5737]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Split step is not able to handle data coming from FTP connector. The FTP connector's outcome is a RemoteFile object and split step is not able to handle this in order to split the data.

Expected behavior:
When FTP connector defines a collection JSON data shape the split should be able to handle that.

**Comment by zregvart** [comment]
Don't the Camel converters kick in and convert the `RemoteFile` to `InputStream`, odd.

**Comment by mastepan** [comment]
@christophd  just checking. Is there anything that should be checked by QE? The issue has been closed by pure-bot...maybe unintentionally.

**Comment by christophd** [comment]
@mastepan yep, pure-bot failed to reopen after fix. This should be verified by QE.
