### ISSUE TITLE
Mismatch in port labels in monitoring resources addons

### ISSUE THREAD

**Issue by davidkirwan** [syndesisio/syndesis#5746]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When importing the monitoring addon resources in ``install/addons``, the dashboards show up empty. This appears to be because there is a mismatch in the lables in monitoring addon resources.``metrics`` vs ``prometheus``

see: https://github.com/syndesisio/syndesis/blob/master/install/addons/syndesis-db-servicemonitor.yml#L14
and: https://github.com/syndesisio/fuse-online-install/blob/1.6.20/resources/fuse-online-template.yml#L718

As examples.

**Comment by zregvart** [comment]
cc @alexkieling

**Comment by alexkieling** [comment]
cc @lgarciaaco

**Comment by lgarciaaco** [comment]
I could not reproduce this issue. @davidkirwan is testing again, this time installing fuse NOT from template, but using the operator. We are on hold waiting for him

**Comment by davidkirwan** [comment]
@alexkieling @lgarciaaco hi folks, I've retested from the master of https://github.com/syndesisio/fuse-online-install/blob/master/resources/fuse-online-operator.yml and I've patched and added the following to take in the addons as suggested:

```
--- fuse-online-operator.yml	2019-06-20 10:38:47.854505525 +0100
+++ fuse-online-operator.yml.new	2019-06-20 10:40:04.436240223 +0100
@@ -227,6 +227,9 @@
         - name: syndesis-operator
           image: ' '
           imagePullPolicy: IfNotPresent
+          args:
+            - '-a'
+            - '/conf/addons'
           ports:
             - containerPort: 60000
               name: metrics
```

**Comment by davidkirwan** [comment]
Spoke with @lgarciaaco this afternoon on bluejeans, and he explained how I can test this right now from master, however as I'll need to target a productised release tag in RHMI, we'll happily wait until the new release is out in the next week or two, and then have another go importing via passing the addons to the fuse operator.

cheers folks!
