### ISSUE TITLE
Bake the UI's commit ID into the about dialog as well at build time

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#5753]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Currently the UI displays a commit ID, but it comes back as a response from the backend, so effectively it's really the backend's current version.  Which can be different from the UI especially on staging where things track master.  So ideally we should add the commit ID at build time to the about dialog as well, and display the two commit IDs to give a more accurate representation of what versions are being used.

**Comment by zregvart** [comment]
Perhaps display both only when they differ?
