### ISSUE TITLE
Choose a Connection title incorrectly appears: should be Choose a Step

### ISSUE THREAD

**Issue by TovaCohen** [syndesisio/syndesis#5766]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

On the staging site, I added the start and finish connections to a simple integration. So far I have this: 
![image](https://user-images.githubusercontent.com/25067106/59556686-a81e4a80-8f94-11e9-9d95-9775f1f88adf.png)

When I click the plus sign, I expect to get a page that prompts me to Choose a Step. But instead I get: 

![image](https://user-images.githubusercontent.com/25067106/59556693-d734bc00-8f94-11e9-888d-f6dcdb9a9969.png)

As you can see, it is prompting me to add the finish connection. But the finish connection is already in place.  This is the behavior no matter how many steps I already have in the simple integration. 

## Expected behavior

There should be a "Choose a Step" page. 

## Tasks involved / Steps to Reproduce

1.
2.
3.
4.

**Comment by tplevko** [comment]
Verified

**Comment by TovaCohen** [comment]
I'm working in staging. I'm creating the Twitter to Salesforce sample integration. I added the Twitter start connection and Salesforce finish connection. In the UI, I see the visualization and I click the plus sign between the two connections. I expect to see the "Choose a step" page, but I'm getting: 

![image](https://user-images.githubusercontent.com/25067106/61539017-89362c80-aa08-11e9-9bcb-05f5a6d7483e.png)

As you can see, the page title is "Choose a connection" when it should be "Choose a step".

**Comment by gashcrumb** [comment]
@heiko-braun dunno if it's too late to get this fixed in 7.4?

**Comment by heiko-braun** [comment]
@gashcrumb @TovaCohen I don't fully understand what you try to point out. What is wrong from your point of view? Is it just the page title?

**Comment by gashcrumb** [comment]
yep, it's the page title.

**Comment by heiko-braun** [comment]
Lowering to `p1`, since it's just the page title that might be misleading.

**Comment by TovaCohen** [comment]
With my  new-user-who-is-not-a-programmer hat on, I must point out that every time a user clicks the plus sign in a flow in order to add a step to a flow, the page that then appears has the title "Choose a connection".   From the POV of a user, especially a new user, this is confusing, misleading, and wrong. 

While we all know that all connections are steps, but not all steps are connections, that concept might not be known to the user, especially the new user. 

If there is any way to get this into 7.4, we will be glad we did.

**Comment by heiko-braun** [comment]
@gaughan What do you think about this?

**Comment by gaughan** [comment]
Too late for 7.4 imho. I agree with p1 status.
