### ISSUE TITLE
No connections are displayed on master

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#5771]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
It is currently not possible to create any integrations nor any new connections on the master branch.

This is what's displayed:
![image](https://user-images.githubusercontent.com/46345469/59585846-b5951b00-90e1-11e9-80b1-762b32528883.png)

I get this exception on the server pod:
[syndesis-server-1.log](https://github.com/syndesisio/syndesis/files/3295651/syndesis-server-1.log)

**Comment by riccardo-forina** [comment]
I couldn’t reproduce this morning on my local env nor on staging. I can’t say about the be log tho.

**Comment by christophd** [comment]
Having a quick look at the server log I see something like:

```
Caused by: org.apache.http.conn.ConnectTimeoutException: Connect to syndesis-prometheus:80
```

So I guess the prometheus pod was not available at that time and maybe that also caused the server pod to fail. So when no server pod is there the UI can not fetch the connections from the database

**Comment by christophd** [comment]
So we need to find out why the syndesis-prometheus pod has had a problem I guess

**Comment by mmuzikar** [comment]
Adding the Prometheus log if that's of any help to you.

[syndesis-prometheus-1-pfptj.log](https://github.com/syndesisio/syndesis/files/3297571/syndesis-prometheus-1-pfptj.log)

**Comment by riccardo-forina** [comment]
I just got this running the UI against the latest BE deployed on minishift. Working on a fix.

**Comment by riccardo-forina** [comment]
The error was being logged in the browser's dev tools console. In the future, it would help if you could check the console and attach any log you can find there.

**Comment by mmuzikar** [comment]
Sorry, I was probably jumping to conclusions when I saw that exception in the server log, will make sure to check all the consoles next time :)

**Comment by mmuzikar** [comment]
Works on my side, thanks @riccardo-forina  :)
