### ISSUE TITLE
Operator image is not being pushed to dockerhub

### ISSUE THREAD

**Issue by rkorytkowski** [syndesisio/syndesis#5777]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Fix for https://github.com/syndesisio/syndesis/pull/5621 to explicitly list docker images to push and include operator and upgrade images.

**Comment by rkorytkowski** [comment]
PR at https://github.com/syndesisio/syndesis/pull/5778

**Comment by rkorytkowski** [comment]
IMAGES variable can be removed from build config in Circle CI once it is merged.

**Comment by rkorytkowski** [comment]
So it turned out that the operator image is named differently i.e. syndesis/syndesis-operator and not just syndesis-operator as configured here: https://github.com/syndesisio/syndesis/blob/master/tools/bin/commands/util/operator_funcs#L7. I'll fix that in a follow-up and create an issue to eventually align the name with other images be removing 'syndesis/'.

**Comment by rkorytkowski** [comment]
3rd attempt... PR at https://github.com/syndesisio/syndesis/pull/5784

**Comment by rkorytkowski** [comment]
I got rid of the list of images in favor of using DOCKER_IMAGES variable declared by individual jobs. I left the check in place to make sure that the declared DOCKER_IMAGES have been actually built before pushing.

**Comment by heiko-braun** [comment]
Anything with `ignore/qe` can be closed without further verification (`done` column)

**Comment by rkorytkowski** [comment]
PR hasn't been yet merged, see https://github.com/syndesisio/syndesis/pull/5786
