### ISSUE TITLE
EMail Send Connector generates unknown protocol error

### ISSUE THREAD

**Issue by phantomjinx** [syndesisio/syndesis#5780]
## This is a...

<pre><code>
[ ] Feature request
[X] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When creating an integration using a send-email connector, the metadata retrieval checks for the email protocol. However, since the protocol property is not yet available for send (as it is a configuredProperty only), an error is thrown: _'Email connector protocol cannot be identified. Unable to fetch and process metadata'_.

The EmailMetadata class does not provide any help to the integrations other than doing checks on the protocol. These checks, in turn, are no longer necessary since it is impossible to mix up the protocols due to there being separate connector for _send_ and _receive_.

**Comment by mastepan** [comment]
@phantomjinx how can QE check this fix please? It's gmail connector I suppose

**Comment by oscerd** [comment]
No, it the mail connector based on camel-mail.

**Comment by phantomjinx** [comment]
@mastepan 
QE don't need to check it since the MetadataRetrieval Class has been removed. Should be enough to create a mail-send connection and verify. For testing failure modes, try changing port number since an smtp client connection will fail on say an imap server.

**Comment by jsafarik** [comment]
Verified that the `send email` connector can be used in an integration and doesn't show error before showing the text fields to configure the action. Won't create reproducer test as this is already covered by one of the tests in the syndesis-qe.
