### ISSUE TITLE
Allow for updates to DeploymentConfig

### ISSUE THREAD

**Issue by edeandrea** [syndesisio/syndesis#5787]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
We need the ability to modify and persist changes to a `DeploymentConfig` created by Fuse online. The `DeploymentConfig` contains configuration of things such as (but not at all limited to)
- number of replicas
- Deployment strategy (i.e. recreate vs rolling)
- Autoscaling

These could be things that get tweaked by an Ops person for a given integration. Currently if they are tweaked, if a new version of the integration is published, the entire `DeploymentConfig` is re-created from scratch, thereby wiping out any previous changes to it.

**Comment by edeandrea** [comment]
ping to keep active

**Comment by heiko-braun** [comment]
@edeandrea Looks like a duplicate of https://issues.jboss.org/browse/ENTESB-10194

**Comment by edeandrea** [comment]
It seems that ticket (at least by it's title) is only for environment variables. If that ticket is worded in such a way that the DeploymentConfig isn't re-created on each deployment then sure it could be a duplicate. If that ticket though is implemented just so environment variables aren't blown away, then that doesn't encompass everything I'm describing here.

**Comment by heiko-braun** [comment]
I think it bopils down to the same problem: Modiffication to the Deplyment config and ENV var changes lead to redeplyment and Fuse Online cannot handle this well atm.

**Comment by heiko-braun** [comment]
I will create a second ticket in ENTESB an link it.

**Comment by heiko-braun** [comment]
tracked in https://issues.jboss.org/browse/ENTESB-11640
