### ISSUE TITLE
Connectors are labeled by type instead of name

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#5796]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When creating new integration all the connectors in the list are labeled by their type instead of name. This issue blocks all QE tests. Also creating two connectors of the same type results in this:

![screenshot_20190618_104059](https://user-images.githubusercontent.com/14313995/59666927-1aba4080-91b6-11e9-97e5-82b6c7d60dbb.png)

**Comment by riccardo-forina** [comment]
This has been fixed by https://github.com/syndesisio/syndesis/pull/5781, I find it odd that you're still seeing it.

**Comment by mcada** [comment]
I am on syndesis dde62844cc7c9cedf63074e73323608a1449ca1d
Also I just noticed that there is `Choose a connection` under the finish step but `Choose a step` under start step :/

**Comment by mcada** [comment]
Oh that explains why its not fixed - I am on latest tag but it was not updated. I will install 1.7
