### ISSUE TITLE
Checking the tag causes that tag is duplicated

### ISSUE THREAD

**Issue by mkralik3** [syndesisio/syndesis#5828]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
I have created a tag in the Manage CI/CD view. When I want to check this tag on the particular integration, the duplicated tag is created. 
![output](https://user-images.githubusercontent.com/16251792/59783060-8fc56d00-92bf-11e9-96a0-aa392dfebeca.gif)

The PUT endpoint (and PATCH too) `...public/integrations/<ID>/tags` calls [tagForRelease](https://github.com/syndesisio/syndesis/blob/8cd2a418256c0b6b18144a940f2a217d398576cd/app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/external/PublicApiHandler.java#L338) function which creates the tag in the backend.
When the endpoint for returns all tags is called `...public/environments`, it returns both tags, which is in the queue and in the backend.

So the tag should be deleted from in-memory cached when it is assigned to the integration (and returns there when no integration contains it) or the endpoint `/environments` should ignore the tags which have the same name and return they only once.

**Comment by heiko-braun** [comment]
@dhirajsb Looking at the recent commits, I assume this work in progress?

**Comment by dhirajsb** [comment]
@heiko-braun this was resolved with PR #5829
