### ISSUE TITLE
"Foreign" characters aren't logged correctly

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#5832]
See also **https://issues.jboss.org/browse/ENTESB-11412**

## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Encountered this behavior using Twitter connector, so it might be an issue of just that connector. I found that japanese characters are rendered as "?", but in the Openshift log they can be rendered correctly.

## Screenshots
![image](https://user-images.githubusercontent.com/46345469/59827013-e2db0680-9337-11e9-93ad-eaf4e594af74.png)
![image](https://user-images.githubusercontent.com/46345469/59827053-f9815d80-9337-11e9-9b90-b5de83613ec3.png)

## Steps to reproduce
1. Create a twitter connector
2. Start with search with query "from:nintendo"
3. End with log step

**Comment by gashcrumb** [comment]
Looks like we're maybe not using UTF conversion somewhere in the response back from the activity monitoring:

![image](https://user-images.githubusercontent.com/351660/60098161-e6e59a80-9722-11e9-8a8f-f2ee0ee1e696.png)

In this case it should be showing:

![image](https://user-images.githubusercontent.com/351660/60098247-0ed4fe00-9723-11e9-8f7a-cef7170b052b.png)

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11412**
