### ISSUE TITLE
Route for API Provider integration not created

### ISSUE THREAD

**Issue by asmigala** [syndesisio/syndesis#5833]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
After deploying an API Provider integration, a route is not created and the following is logged in syndesis-server log:

```
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://kubernetes.default.svc/apis/route.openshift.io/v1/namespaces/syndesis/routes/i-qwer. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. routes.route.openshift.io "i-qwer" is forbidden: User "system:serviceaccount:syndesis:syndesis-server" cannot get routes.route.openshift.io in the namespace "syndesis": no RBAC policy matched.
```

Happens on 1.7.1 and master

**Comment by heiko-braun** [comment]
@lgarciaaco Is this related to your recent changes?

**Comment by heiko-braun** [comment]
Related to #5892

**Comment by lgarciaaco** [comment]
> @lgarciaaco Is this related to your recent changes?

yes

**Comment by heiko-braun** [comment]
@lgarciaaco Are the commits supposed to fix the issue? In this case please move the issue to `Done`

**Comment by heiko-braun** [comment]
@nicolaferraro Can you verify if it's fixed?

**Comment by nicolaferraro** [comment]
Sure

**Comment by nicolaferraro** [comment]
I confirm it works on 1.7.7.

**Comment by asmigala** [comment]
Verified with 1.7.8
