### ISSUE TITLE
Import extension: "Something is wrong" dialog appears, extension not imported

### ISSUE THREAD

**Issue by mastepan** [syndesisio/syndesis#5835]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Customizations - Extensions - Import Extension
Select an extension and this happens:
![importextension](https://user-images.githubusercontent.com/8707251/59842699-580a0400-9357-11e9-95b9-628489bda233.png)

No extension is imported when I check it on Extensions page.

**Comment by heiko-braun** [comment]
@lburgazzoli , @riccardo-forina Is it a UI or backend problem?

**Comment by gashcrumb** [comment]
Hmm, worked against staging.  Can you grab the logs from the server and ideally have a look and see if there's any errors in the javascript console or network tab?

**Comment by lburgazzoli** [comment]
@mastepan could you attach the extension ? could be a problem with the format of the extension itself

**Comment by mastepan** [comment]
[extension.zip](https://github.com/syndesisio/syndesis/files/3310841/extension.zip)

console output:
<code><pre>
VM13:1 Uncaught (in promise) DOMException
react-dom.production.min.js:4408 TypeError: Cannot read property 'map' of undefined
    at ExtensionImportPage.tsx:243
    at S (Translation.js:16)
    at Zo (react-dom.production.min.js:3274)
    at Sa (react-dom.production.min.js:3745)
    at La (react-dom.production.min.js:3957)
    at qc (react-dom.production.min.js:5514)
    at Yc (react-dom.production.min.js:5536)
    at ki (react-dom.production.min.js:5958)
    at Si (react-dom.production.min.js:5925)
    at xi (react-dom.production.min.js:5860)
dc @ react-dom.production.min.js:4408
</pre></code>

no server pod log errors

**Comment by zregvart** [comment]
There seems to be an issue with this still on staging, via https://github.com/syndesisio/syndesis/pull/5862#issuecomment-505440965

**Comment by gashcrumb** [comment]
There's a JDBC driver extension that I just installed using staging.  However it uploaded fine, this occurs when clicking the "Install" button:

**Comment by gashcrumb** [comment]
That HTTP 500 error is new and wasn't happening when I merged that PR.
