### ISSUE TITLE
Collect all dev related documentation into a single place

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#585]
I suggest creating a 'Syndesis Developer Handbook' (SDH) which collects all documentation which is sprinkled over all places.

This would look like e.g. https://dmp.fabric8.io/ (asciidoc) and would also contain the diagrams / docs that have been contributed by Andrea and Paolo.

The handbool will be reachable as e.g. `sdh.syndes.is` or `docs.syndes.is` or whatever you prefer. (docs.syndesis.io is also available)

Lets first collect all the location which contains docs.

**Comment by gashcrumb** [comment]
There's a lot in the UI readme, at least not all of it is outdated -> https://github.com/syndesisio/syndesis/blob/master/app/ui/README.md

When consolidated I would expect that any existing READMEs in the sub-projects get cleaned up and just be a short file that links back to the developer handbook, make sense?

**Comment by rhuss** [comment]
Yes, absolutely. Ideally, we should be able to only maintain a single document, even when it is one click further away.

**Comment by gashcrumb** [comment]
hey, we've a handbook now!
