### ISSUE TITLE
No way to specify security values when creating API connection

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#5855]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Currently the API client requires only input for Host and Base path, but there is no way to specify what username & password or api key to use. I don't remember clearly if there was another page in this process or everything was in the same form.

![image](https://user-images.githubusercontent.com/46345469/59904523-0d929100-9404-11e9-82b0-c2d9ebbf1988.png)

Sample API specifications to try this out: 
[todo.txt](https://github.com/syndesisio/syndesis/files/3313358/todo.txt) (basic http auth)
[petstore-test.txt](https://github.com/syndesisio/syndesis/files/3313359/petstore-test.txt) (api key)

**Comment by heiko-braun** [comment]
Is a UI issue?

**Comment by mmuzikar** [comment]
I didn't find any logs in the dev console and no obvious exception linked to this in the server pod

**Comment by zregvart** [comment]
Reproduced it locally on minishift, the response from `POST /api/v1/connectors/custom` is missing the `username` and `password` in `properties` of the generated Connector.

**Comment by mmuzikar** [comment]
Thanks @zregvart I hope this was the last obstacle in my verifying the api key security option :)
