### ISSUE TITLE
[UI] Rename Settings to OAuth Settings?

### ISSUE THREAD

**Issue by avano** [syndesisio/syndesis#5857]
See also **https://issues.jboss.org/browse/ENTESB-11466**

## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Currently there is `Settings` link in the navigation that points to the `OAuth Application Management` page - I would not expect to configure oauth there and I would expect the settings for the syndesis ui
![screenshot-2019-06-21_10:10:36](https://user-images.githubusercontent.com/7081216/59908059-ce1c7280-940c-11e9-97e8-eee606cd3cf2.png)

Woudln't it make sense to rename the link to `OAuth Settings`?

**Comment by gashcrumb** [comment]
I'd even go so far to say it should be kinda bundled under connections.  Or lump it under "Customizations" since it also has to do with connections.

**Comment by gashcrumb** [comment]
@dongniwang FYI

**Comment by dongniwang** [comment]
Agreed that we should probably group it under connections.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11466**
