### ISSUE TITLE
Provide a description for the integration page

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#5869]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Currently on the Integration page the heading has "This description has not yet been actually defined, please send help."

![Screenshot_2019-06-21 Integrations - Syndesis](https://user-images.githubusercontent.com/1306050/59932984-bcf15700-9448-11e9-9d4e-e964629b2585.png)

I would mark this as `p0` as it is in a very prominent place and it's super embarrassing. What do you think @paoloantinori?

@TovaCohen @dongniwang can you advise on the text here, we can leave it blank if needed.

**Comment by TovaCohen** [comment]
I already provided text for the placeholder descriptions. 
https://github.com/syndesisio/syndesis/pull/5764

**Comment by gashcrumb** [comment]
Yeah, looks like the one on this page is one of the leftovers after that PR in `integrations-translations.en.json`.  There's actually 4 instances on that file that correspond to 4 different pages:

1) https://github.com/syndesisio/syndesis/blob/master/app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json#L2
![image](https://user-images.githubusercontent.com/351660/59937742-4725c500-9421-11e9-8524-1b52c1fd5d0e.png)


2) https://github.com/syndesisio/syndesis/blob/master/app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json#L26
![image](https://user-images.githubusercontent.com/351660/59937773-54db4a80-9421-11e9-94d7-20462e13c19e.png)

3) https://github.com/syndesisio/syndesis/blob/master/app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json#L120
![image](https://user-images.githubusercontent.com/351660/59937951-c4513a00-9421-11e9-864e-95ca75d0575c.png)

4) https://github.com/syndesisio/syndesis/blob/master/app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json#L124

I just hit a bug trying to fetch the screenshot for it, but it's in the API provider wizard after you upload a swagger file.

**Comment by TovaCohen** [comment]
Sorry, but it is not clear to me how, if at all, I can help at this point. If there is aparticular file that you would like me to update, please tell me explicitly what is needed.

**Comment by gashcrumb** [comment]
Oh right, so just pointing out which pages still have this placeholder text, these are the ones we need to update still.

**Comment by TovaCohen** [comment]
Thanks. I'll update those pages now and submit a PR.

**Comment by gashcrumb** [comment]
There's a couple more, want me to gather up screenshots and links for 'em?  I don't mind.

**Comment by TovaCohen** [comment]
Links would be great. 
If I can't figure out the context, I'll ask.

**Comment by gashcrumb** [comment]
ok perfect!

**Comment by gashcrumb** [comment]
Ah, no I'm wrong, the other two are indeed cases where there's entries but they're not shown.  I propose we leave them as-is, that way if they do somehow make it to the UI we'll find out quickly enough :smile:

**Comment by TovaCohen** [comment]
Fixed by https://github.com/syndesisio/syndesis/pull/5874
