### ISSUE TITLE
Adding a "Import Extension" is not working

### ISSUE THREAD

**Issue by rareddy** [syndesisio/syndesis#5870]
## This is a bug

<pre><code>
[ ] Feature request
[x ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

When a user using the UI tries to add an extension based "import library" the operation always fails to upload the file.

**Comment by gashcrumb** [comment]
Just pushed a fix for this earlier today -> https://github.com/syndesisio/syndesis/pull/5862

**Comment by rareddy** [comment]
Duplicate of https://github.com/syndesisio/syndesis/pull/5862
