### ISSUE TITLE
Replace of start/finish connection in integration - the old connection still showing up

### ISSUE THREAD

**Issue by tplevko** [syndesisio/syndesis#5883]
See also **https://issues.jboss.org/browse/ENTESB-11411**

## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

When editing the start or finish connection in integration - the old connection, which is being updated is still showing, as you can see in the recording. The "clean" start/stop icon there would be much more intuitive (image attached).

## Screenshot

![out](https://user-images.githubusercontent.com/4180208/59997420-5729e880-965d-11e9-8a77-3820c25f0e50.gif)

![Screenshot from 2019-06-24 08-51-00](https://user-images.githubusercontent.com/4180208/59997480-7aed2e80-965d-11e9-95e4-03c592c4e50f.png)

## Tasks involved / Steps to Reproduce

1. Create integration with start and stop connection
2. Select delete one of these connections
3. See that the old connection is still showing on the place of connection which is updated

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11411**
