### ISSUE TITLE
[UI] Some connector icon sizes are too small

### ISSUE THREAD

**Issue by avano** [syndesisio/syndesis#5884]
See also **https://issues.jboss.org/browse/ENTESB-11465**

## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
SQS, SNS, Box and Kudu (maybe salesforce as well) icons are a little too small comparing to the other icons

![screenshot-2019-06-24_09:30:55](https://user-images.githubusercontent.com/7081216/59999691-e2f24380-9662-11e9-97bf-bfaabcee339f.png)

For example compare `DB vs SNS` or `S3 vs Kudu` size

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11465**
