### ISSUE TITLE
[UI] Tooltip close button selection overlaps with text + button not aligned

### ISSUE THREAD

**Issue by avano** [syndesisio/syndesis#5885]
See also **https://issues.jboss.org/browse/ENTESB-11410**

## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When I click on some tooltip to get some help about the field, it comes with the "X" button selected and it overlaps with the text:
![screenshot-2019-06-24_09:41:41](https://user-images.githubusercontent.com/7081216/60000415-7710da80-9664-11e9-990b-9790ce60cb63.png)

Also the button is not aligned with the text
![screenshot-2019-06-24_09:44:09](https://user-images.githubusercontent.com/7081216/60000467-97409980-9664-11e9-860c-f3bc941cfcb2.png)

**Comment by gashcrumb** [comment]
@seanforyou23 FYI

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11410**
