### ISSUE TITLE
Operator unable to start

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#5888]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Seems like the changes merged in #5712 (on master) are causing issues with operator starting.

```
$ docker run -it docker.io/syndesis/syndesis-operator
...
Status: Downloaded newer image for syndesis/syndesis-operator:latest
panic: could not find the root module directory

goroutine 1 [running]:
github.com/syndesisio/syndesis/install/operator/pkg/build.init.0()
	/home/circleci/project/install/operator/pkg/build/pkg.go:45 +0x24d
```

@chirino can you take a look?

**Comment by chirino** [comment]
looking into it...

**Comment by chirino** [comment]
#5907 should fix it.

**Comment by chirino** [comment]
@zregvart I assume we can close this?

**Comment by heiko-braun** [comment]
@chirino If think this doesn't require QE review (which I believe) then it's safe to close. But in that case add the `ignore/qe` label. However if you want QE to look at it, leave it in the Zenhub `Done` column.
