### ISSUE TITLE
[Box] "id" mapped from response is empty

### ISSUE THREAD

**Issue by avano** [syndesisio/syndesis#5889]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
After https://github.com/syndesisio/syndesis/pull/5723 there is a possibility to map `content`, `id`, `size` - however, the `id` is always empty.

Integration: `timer -> box download -> datamapper (combine content-id-size -> task) -> sql (insert into todo(task) values (:#task)`

The resulting record in todo app is `Hello integration!--18` - the id is empty

**Comment by claudio4j** [comment]
@avano this bug was fixed by #5933
