### ISSUE TITLE
Add support for units to form service

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#589]
For some of the upcoming designs we have time periods in the generated form.  We'll need to add support for a numeric type that has a unit field along with it.  Ideally we should support the possibility to have upper and lower bounds per unit.  So for example a field that could be in milliseconds, seconds, minutes, hours, the input should be type `number` with a select next to it to specify the unit.  

Changing the unit should update any potential min/max bounds on the input field.

@KurtStam FYI

**Comment by gashcrumb** [comment]
@seanforyou23 this one :-)

**Comment by gashcrumb** [comment]
@KurtStam should this be included in whatever epic tracks the SQL connector?

**Comment by kahboom** [comment]
Closing as we have carried the conversation onto a separate issue without realizing it was a duplicate #717. Will copy over initial description of this issue onto there.
