### ISSUE TITLE
The published integration has become obsolete - details aren't very helpful

### ISSUE THREAD

**Issue by avano** [syndesisio/syndesis#5890]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
I edited my integration where I changed the `fileId` property in the box connector and during the republishing there is this message `The published integration has become obsolete` - I clicked on `View details` but the details weren't really helpful:

```
myint:Integration > :Flow > :Step > Simple:ConnectorAction > :ConnectorDescriptor$property-defn-steps 
  => '[ActionDes ... null}]' 
  => '[ActionDes ... Period}]'
```

**Comment by gashcrumb** [comment]
Yeah, I dunno what the strings are really trying to relay, it's probably only useful to Syndesis developers.  Also the UI concatenates many of these same messages that appear on the integration `board` attribute but in some cases it's a message per connection per flow, so that string gets truncated to keep the page from blowing up.  But at least some of the information that's driving this message is being surfaced now, you'd have to go and look at the API response in the network tab previously.

**Comment by phantomjinx** [comment]
@gashcrumb 

[This](https://github.com/syndesisio/syndesis/pull/3709#discussion_r222750235) should provide you with an explanation of what the details are trying to show.

So, the error message is the result of a comparison that's been done between a cached version of the published integration and the new-modified integration. A recursive diff is performed on all major properties of both and if there is a difference then the error is tripped, reported and detail of the exact difference provided. Yes, not much help for users, I agree, much more a developer thing.

**Comment by gashcrumb** [comment]
Gotcha!  Yeah, that information probably needs to be in a more readily available place :smile: 

This isn't anything a user is gonna care about, *however* it is something that they can copy/paste into an issue.  

I think we probably could also stand to loosen our equivalency checking a bit, I feel like it really creates a lot of false positives.  For example, I probably shouldn't see any messages along these lines if I go and create an integration and immediately save/publish it, theoretically the published integration should be up to date with whatever connections/steps/extensions it's been linked to.

One other suggestion is that we could make those equivalency messages a bit more verbose and more self-explaining.  I had to read your explanation a couple times, but if the messages were a bit more self-describing then folks probably could get by without supporting documentation.

**Comment by avano** [comment]
looks slightly better now
