### ISSUE TITLE
A route for WebHook is not created automatically

### ISSUE THREAD

**Issue by mkralik3** [syndesisio/syndesis#5892]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
After deployed the integration with WebHook, the route is not created automatically as before. Because of that, the UI doesn't contain the URL either.

Version: (`syndesis minishift --install --tag 1.7`)
Syndesis: 1.7.3
Commit ID: ef7b10dfca7246c95ab685eeddc16d61f73e6d34

**Comment by heiko-braun** [comment]
@lgarciaaco Are the commits supposed to fix the issue? In this case please move the issue to `Done`
