### ISSUE TITLE
DB-2-DB with mssql jdbc connector - No enum constant io.syndesis.connector.sql.common.DbEnum.MICROSOFT_SQL_SERVER

### ISSUE THREAD

**Issue by iledarn** [syndesisio/syndesis#5895]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Documentation issue or request
</code></pre>

## Description

Syndesys version: ae2ad3ef8952f706353c11d051a649f0bbcc20fe

I've deployed mssql JDBC library extension with the help of the https://github.com/syndesisio/syndesis-extensions/tree/master/syndesis-library-jdbc-driver and this instruction
https://access.redhat.com/documentation/en-us/red_hat_fuse/7.2/html/connecting_fuse_online_to_applications_and_services/connecting-to-databases_connectors
By the way, I've encountered with the https://github.com/syndesisio/syndesis/issues/2999.
In the end, I'm able to build and deploy (https://gist.github.com/iledarn/038085951541ef165b70b29642a15184). Also I've created a connection (DB-2-DB) to it and have it validated. Now I'm trying to make my Integration with this Connection. The problem is now when I'm trying to define simple SQL statement in it (select top 1 * from Workplace) and click `next` button I got this error: `No enum constant io.syndesis.connector.sql.common.DbEnum.MICROSOFT_SQL_SERVER. Unable to fetch and process metadata`

![Screenshot from 2019-06-24 16-42-26](https://user-images.githubusercontent.com/14071718/60023823-4601cb80-969f-11e9-93ce-ffe30080cd2d.png)

**Comment by zregvart** [comment]
@KurtStam this one looks like it's right up your alley.

**Comment by KurtStam** [comment]
This has been fixed
