### ISSUE TITLE
Twitter connection creation fails

### ISSUE THREAD

**Issue by claudio4j** [syndesisio/syndesis#5910]
## This is a...
<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
After adding the twitter consumer api and secret key in the Settings page, try to add a twitter connection. Upon clicking the "Connect Twitter" there is a Error popup message: "Errors trying to connect: c is undefined", this happens in the react-ui, there are no error in browser console.

syndesis-server prints

```
<error code="417">Desktop applications only support the oauth_callback value 'oob'</error>
```

![twitter_conn_fail](https://user-images.githubusercontent.com/836543/60067196-0ad3bc80-96e0-11e9-8a5c-6165232dfd1a.png)

The error also occurs in angular-ui: "code: 417. Desktop applications only support the oauth_callback value 'oob'"

![twitter_conn_error_legacy](https://user-images.githubusercontent.com/836543/60067195-0ad3bc80-96e0-11e9-8d57-fb69df327b1a.png)

**Comment by claudio4j** [comment]
Investigating this issue, the twitter app on twitter should set:
* Sign in with Twitter: Enabled
* Callback URL: some url

Now the error message is: Callback URL not approved for this client application. Approved callback URLs can be adjusted in your application settings

**Comment by zregvart** [comment]
This is relevant #3355 also checkout the documentation [on creating connections](https://access.redhat.com/documentation/en-us/red_hat_fuse/7.3/html/connecting_fuse_online_to_applications_and_services/connecting-to-twitter_connectors) to Twitter.

**Comment by claudio4j** [comment]
Thanks Zoran, it works. I was using the wrong callback url.
