### ISSUE TITLE
Nothing gets loaded on freshly deployed Syndesis

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#5912]
See also **https://issues.jboss.org/browse/ENTESB-11409**

## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
After deploying Syndesis, everything I get are placeholders. Simple refresh fixes these problems but all of QE tests expect that the UI will get loaded. Refreshing in every test becomes cumbersome and it's not a good UX having to refresh to load the UI.

![Peek 2019-06-25 12-34](https://user-images.githubusercontent.com/46345469/60092254-dd6e2980-9746-11e9-8173-69f432cbcfae.gif)

## Steps to reproduce
1. deploy Syndesis
2. click on connections/settings/integrations
3. to fix it click on refresh

**Comment by riccardo-forina** [comment]
Anything on the browser's console?

**Comment by mmuzikar** [comment]
No logs in the browser console neither in the syndesis-server pod

**Comment by zregvart** [comment]
I've narrowed this down to Firefox and Service worker, I did get a timeout relating to Service Worker something like in the Console:
`Terminating ServiceWorker for scope ‘https://syndesis.192.168.42.195.nip.io/’ with pending waitUntil/respondWith promises because of grace timeout.`
To fix this I've allowed HTTP (unencrypted) traffic on the syndesis route and accessed over plain text HTTP. Same minishift over http has no issues and over https shows similar symptoms. No issues in Chromium.

**Comment by gashcrumb** [comment]
@mmuzikar that looks like firefox in the gif, am I right?  Does the test suite also use Chrome or Chromium and does it show up there?

**Comment by zregvart** [comment]
Reading up on service workers [here](https://wiki.mozilla.org/MDN/Get_involved/Events/HackOnMDN/Project:_Service_Workers) and [here](https://github.com/w3c/ServiceWorker/issues/274) it appears that TLS (`https`) is required for service workers to be enabled.
With Create React App we have a different implementation for the Service Worker we use, I wonder if there are issues with that implementation regardless and we just don't notice it as we're developing over plain text (http on port 3000).

**Comment by mmuzikar** [comment]
@gashcrumb the same behavior on Chromium 
![image](https://user-images.githubusercontent.com/46345469/60101421-064ce980-975c-11e9-9b5a-7f96889ff2b4.png)

**Comment by riccardo-forina** [comment]
> Reading up on service workers [here](https://wiki.mozilla.org/MDN/Get_involved/Events/HackOnMDN/Project:_Service_Workers) and [here](https://github.com/w3c/ServiceWorker/issues/274) it appears that TLS (`https`) is required for service workers to be enabled.
> With Create React App we have a different implementation for the Service Worker we use, I wonder if there are issues with that implementation regardless and we just don't notice it as we're developing over plain text (http on port 3000).

Workers don't run in localhost, are effectively ever deployed only in production. That said, the worker [has been disabled for a while now](https://github.com/syndesisio/syndesis/commit/8e4c53df2de2a3cf93be4307587eaeb9852f8d7f).

Maybe you still have a worker installed from before. They're quite hard to remove programmatically, maybe try running this snippet:

```
navigator.serviceWorker.getRegistrations().then( 
 
    function(registrations) { 
 
        for(let registration of registrations) {   
            registration.unregister(); 
 
        } 
 
}).then(() => console.log('done'));
```

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11409**
