### ISSUE TITLE
Delete integration causes that associated tag is deleted too

### ISSUE THREAD

**Issue by mkralik3** [syndesisio/syndesis#5917]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When I have a tag which is associated only to the one integration and I delete that integration, the tag is automatically deleted too. Shouldn't the tag stay in the Syndesis when the tag lifecycle is managed in the Manage CI/CD view?  A similar case as with https://github.com/syndesisio/syndesis/issues/5266 In my POV, for consistency, the deletion of the tag should be able only in the Manage CI/CD view.

**Comment by dhirajsb** [comment]
@mkralik3 this is because of the model being as it is right now, i.e. it happens due to the tag being part of the deleted integration object. 
For 7.5 when we refactor environments out this won't be an issue anymore.

**Comment by dhirajsb** [comment]
PR #5952 fixes this by removing environment tags from integration before deleting it and moving them to unassigned status if not being used.
