### ISSUE TITLE
SQL Connector can have 2 different input shapes (isBatch)

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#5922]
## This is a...

<pre><code>
[ ] Feature request
[*] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
On INSERTS and UPDATES, the data shape changed recently from single element, to collection. This to support batch inserts/updates. Though this is nice it breaks the use case where we only have single elements. For an example of this see: https://github.com/syndesisio/syndesis-quickstarts/tree/master/webhook-2-db

where the user is now presented with a DataMapper warning.

If we introduce an option called isBatch, then we can change the inputShape. 
isBatchInput -> collection, and single elements otherwise.

'isBatchInput' - allow batch processing (applies only to INSERT or UPDATE)

When we start using the `relation` feature (https://github.com/syndesisio/syndesis/issues/5722) in react we can only present this option when the user types a SQL with INSERT or UPDATE

**Comment by KurtStam** [comment]
BTW the same issue might hold true for other Connectors like google sheets?

**Comment by gashcrumb** [comment]
So what's shown is based on the text that the user types into the SQL field?

Having other fields show up or go away as a result of actual typing is gonna look weird.  And probably also be hard to implement.  Why not present this as a second page after the user enters in the SQL, we already have the ability to have multiple pages of connection configuration?

**Comment by KurtStam** [comment]
yeah - and then NOT have a second page sometimes?

**Comment by gashcrumb** [comment]
I think yeah or just don't return a second page, the UI checks the size of the property definition steps array against the current index it's on.  Probably it won't "just work" like I'd want it to, but I think we can make it work if there's some hiccups.  I'd rather avoid an empty second page or one with disable controls.

**Comment by christophd** [comment]
The meta data lookup for those properties on the server can only return property value suggestions. Even if we return no suggestions still the property definition step has that property defined.

I guess we would have to change the meta lookup API to the server here to mark that the property definition is obsolete.

**Comment by christophd** [comment]
@KurtStam I started to fix this but I still get the data mapper warning sign every time even when I use the batch property to force a single element data shape. 

This is because the logic to hide that warning is based on a total equality of data shape specifications (see https://github.com/syndesisio/syndesis/blob/fa75b576eda29849a21cdbed74c10d8ac1c15c90/app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts#L151).

So the data mapper warning only disappears when shapes are exactly the same with equal kind and specification. For webhook and other connectors that define their shapes by given user input I can not imagine that the user hits exactly the same specification as required by SQL connector for instance. So the warning will be there almost all the time.

So I do not understand how this has been working before the batch support in SQL connector.

**Comment by christophd** [comment]
BTW in the webhook-2-db quickstart the user is also presented with a DataMapper warning and the quickstart instructions add a DatamMapper from `task -> task` to solve it.

**Comment by KurtStam** [comment]
Hmm - I guess we need to upgrade the comparison :)

On Jun 26, 2019, at 05:59, Christoph Deppisch <notifications@github.com>
wrote:

BTW in the webhook-2-db quickstart the user is also presented with a
DataMapper warning and the quickstart instructions add a DatamMapper from task
-> task to solve it.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/syndesisio/syndesis/issues/5922?email_source=notifications&email_token=AAAIV6A75TBDZC3BKPHOWGTP4M4ZXA5CNFSM4H3JUCA2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYTAJMI#issuecomment-505808049>,
or mute the thread

**Comment by christophd** [comment]
I think when we enhance the data shape comparison we can also add the logic that applies to element and collection shape differences. So when two shapes share the same properties but only differ in collection and element type we can hide the data mapping warning.

So we do not need multiple SQL connector shapes and the batch property setting then. 

@KurtStam WDYT

**Comment by christophd** [comment]
We agreed that this is more a matter of enhanced data shape comparison than supporting SQL connector to handle multiple shapes. 

Let me close this issue and open another one related to some enhanced data shape comparison feature
