### ISSUE TITLE
Number of usages a tag is incorrect in some cases

### ISSUE THREAD

**Issue by mkralik3** [syndesisio/syndesis#5923]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
I have a tag "tag12" and three integration (_integration1_, _integration2_ and _integration3_). Only _integration1_ and _integration2_ are tagged by the tag _tag12_. 
`GET .../public/integrations/integration1/tags` returns `{"tag12":..}`
`GET .../public/integrations/integration2/tags` returns `{"tag12":..}`
`GET .../public/environments?withUses=true` returns `{"name":"tag12","uses":2}`
The integration3 is not tagged by any tag.
`GET .../public/integrations/integration3/tags` returns `{}`

After that, I call the endpoint for exporting all integration, 
`GET .../public​/public​/integrations​/staging/export.zip?all=true -o export.zip`
so the tag is added to the integration3 too.
`GET .../public/integrations/integration1/tags` returns `{"tag12":...}`
`GET .../public/integrations/integration2/tags` returns `{"tag12":...}`
`GET .../public/integrations/integration3/tags` returns `{"tag12":...}`
However, the number of usages is wrong, should be 3 but is 2:
`GET .../public/environments?withUses=true` returns `{"name":"tag12","uses":2}`

I am able to reproduce it on the tag 1.7.4.

![output](https://user-images.githubusercontent.com/16251792/60114842-f1308480-9774-11e9-8afd-7177f1726f9a.gif)

Step to **reproduce:**

- Create tag _tag12_
- Create simple integration Timer-to-log with name integration1
- Create simple integration Timer-to-log with name integration2
- Create simple integration Timer-to-log with name integration3
- Check _tag12_ in the integration1
- Check _tag12_ in the integration2
- Verify that _tag12_ is not checked in the CI/CD dialog in the integration3
- Verify that _tag12_ is used only twice `GET .../api/v1/public/environments?withUses=true` -> `[{"name":"tag12","uses":2}]`
- Export all integrations `GET .../public​/public​/integrations​/tag12/export.zip?all=true -o export.zip`
- Verify that _tag12_ is now checked in the CI/CD dialog in the integration3
- The endpoint `GET .../api/v1/public/environments?withUses=true` still returns twice `[{"name":"tag12","uses":2}]`

**Comment by mkralik3** [comment]
Today I noticed that the problem is simpler. If the tag is in the three or more integration, the endpoint .../environments?withUses=true every time returns 2 uses for the tag.

For reproducing it, just create e.g. 4 integrations and one tag. Check that tag in the all integrations and call the .../environments?withUses=true endpoint.

**Comment by heiko-braun** [comment]
@dhirajsb can you take a look at this?

**Comment by dhirajsb** [comment]
PR #5948 will take care of this.

**Comment by dhirajsb** [comment]
Backport PR #5949
