### ISSUE TITLE
Server OpenAPI document contains different values for Kind

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#5924]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Seems that the OpenAPI document generate by the server runtime lists values of `Kind` as camel case, whereas we store as dash-ed snake case in JSONDB.

Seems like the most correct approach would be to try to customize the OpenAPI document generation so it uses `name` for enum values instead of `value` of the Kind enum.

**Comment by heiko-braun** [comment]
Does this inherit the priority of #5697 ?

**Comment by zregvart** [comment]
> Does this inherit the priority of #5697 ?

It's open for debate, this is a bug but hardly a `p0` it does help with implementing #5697 but in a very indirect way.

**Comment by zregvart** [comment]
Relates to #5697

**Comment by tplevko** [comment]
Verified
