### ISSUE TITLE
Create Prometheus alerts for integration apps

### ISSUE THREAD

**Issue by alexkieling** [syndesisio/syndesis#5929]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

As a Site Reliability Engineer, I want to have predefined Prometheus alerts so that I can get warned when integration apps experience health issues.

#### Definition

Alert for any integration with a high rate of failed exchanges

#### Standard operating procedure (SOP)

Check the logs and the Grafana dashboards. When the issue is related to resource usage, such as memory or disk, restart the pod. When the issue is related to connectivity to another monitored application, check that application's logs and Grafana dashboard.

**Comment by alexkieling** [comment]
@zregvart @KurtStam @chirino @christophd  
Do you have any suggestions on integration issues that should trigger alerts to ops teams?
Note that when the integrations become unhealthy, the liveness probe fails and the pods are restarted. 
Are there any issues that don't necessarily make the health endpoint return a failure but could still affect the correct processing of messages?
There are some Camel metrics about failures and blocked messages that we could potentially use.
Also, in case you have a suggested metric we could alert on, what should the ops team do in that case?

**Comment by KurtStam** [comment]
@alexkieling, I would think the integration log would be my first suggestion, but that's not metrics; you specifically are asking about metrics right?

**Comment by alexkieling** [comment]
@KurtStam, yes, I'm talking about Prometheus metrics. I don't think we currently expose a counter for log messages but it would be useful if we were interested in the rate of log messages with level Error. Camel has a metric counter for failed exchanges.

**Comment by mkralik3** [comment]
Verified. 
![image](https://user-images.githubusercontent.com/16251792/63021571-2b7af000-bea1-11e9-845b-ac9d591583d0.png)
