### ISSUE TITLE
Implement endpoint to fetch the OpenAPI resource by id

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#5936]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

The React UI needs to access the OpenAPI document resource by id. This is because until the user opts to save the integration the integration will not be stored on the server and the `GET /apis/v1/integrations/{id}/specification` endpoint is not applicable.

When generator API is invoked either via `POST /apis/v1/apis/generator` or via `PUT /apis/v1/apis/generator` the server stores the OpenAPI resource.

The id of the stored OpenAPI resource is set in the `resources` property of the Integration, and can be identified by searching for the resource with `kind` that equals `open-api`.

The new endpoint should be at `GET /apis/v1/resources/{kind}/{id}`.

**Comment by zregvart** [comment]
Relates to #5697

**Comment by tplevko** [comment]
Verified
