### ISSUE TITLE
OAuth settings sometimes not saved with firefox

### ISSUE THREAD

**Issue by wyvie** [syndesisio/syndesis#5953]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

When entering OAuth settings into syndesis using firefox, sometimes (doesn't happen every time) success alert is not shown, and form is visibly stuck, with `Save` button still active, fields and `Remove` greyed out. Upon page refresh settings is still empty, not saved. This doesn't happen on Chrome.

## Expected behavior

OAuth settings saved correctly while using firefox and chrome.

## Screenshot

![image](https://user-images.githubusercontent.com/3992240/60256566-15ee3e80-98d2-11e9-933d-1c5c9e138df8.png)

**Comment by gashcrumb** [comment]
Any javascript console errors?  Also is there any activity in the network tab in the browser's developer tools?

**Comment by wyvie** [comment]
@gashcrumb 

after some waiting there appears this in console, nothing on network tab:
```
The connection to wss://syndesis.my-minishift.syndesis.io/api/v1/event/streams.ws/717204c8-0abf-4db0-b389-fb6bc5cd39c9 was interrupted while the page was loading.
```
