### ISSUE TITLE
git hooks assumes `syndesis` binary on PATH

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis#5957]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Git hooks assume to find `syndesis` binary on path, which is not a strict requirement.
Hooks should not make this assumption or degrade gracefully otherwise.

**Comment by mastepan** [comment]
closing as ignore/qe added
