### ISSUE TITLE
Release script no longer working

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#5959]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Seems that the last operator refactoring broke the release script:

```
/mnt/hudson_workspace/workspace/syndesis-release-daily/tools/bin/commands/release: line 58: /mnt/hudson_workspace/workspace/syndesis-release-daily/tools/bin/commands/util/operator_funcs: No such file or directory
```

@chirino what would be the new way of building/releasing the operator?

**Comment by phantomjinx** [comment]
FYI
operator_funcs has moved to ${syndesis}/install/operator/.lib.sh

**Comment by chirino** [comment]
I’ll look into this today.

**Comment by chirino** [comment]
@zregvart what command were you running?
