### ISSUE TITLE
Add classes to elements in API provider setup

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#5961]
See also **https://issues.jboss.org/browse/ENTESB-11464**

## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
In the review actions there are elements without any classes which makes them difficult to locate in tests, please add classes at least to these marked elements:

![image](https://user-images.githubusercontent.com/46345469/60272300-2c0cf680-98f4-11e9-8925-f6cbc876d8e5.png)

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11464**
