### ISSUE TITLE
Drop integration id and operation id from the flow id

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#5963]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Currently we're creating flow id of the API provider generated flows by concatenating `integration id`, `:flows:` and `operation id` (of the OpenAPI operation).

We should store the operation id in the flow metadata, and modify the logic to match the operation with the flow based on the metadata.

The existing flows need to be migrated such that flow ids are regenerated and the operation id from the flow id is placed into the metadata of the flow.

**Comment by gashcrumb** [comment]
This also matches the pattern we've adopted for conditional flows, where a flow's metadata is used to provide the linking between flows.  It also ensures the ID format stays opaque and neutral and can therefore be fairly safely generated by the backend or frontend, which is kinda crucial given that either side is responsible for creating objects in an integration during various use cases.

**Comment by zregvart** [comment]
Relates to #5697

**Comment by mmuzikar** [comment]
@zregvart is there anything you need to get validated on this issue? Seems to me like an internal thing that QE doesn't realistically get chance to validate properly

**Comment by zregvart** [comment]
Yeah, let me slap a `ignore/qe` on this and close.
