### ISSUE TITLE
Rebuilding the operator and installing ...

### ISSUE THREAD

**Issue by phantomjinx** [syndesisio/syndesis#5967]
After deleting syndesis project, spent time trying to reinstall. Made some progress but now stuck.

Observations & Potential Issues
1. Building the operator:
```
export GOPATH=~/programming/java/syndesis
syndesis build --local -m operator -f
```
- The build requires go & the operator-sdk. Once both are installed and correctly configured, ie. GOPATH is correct, the following error occurs and aborts the build:
```
INFO[0004] Running deepcopy code-generation for Custom Resource group versions: [syndesis:[v1alpha1], ] 
INFO[0009] Code-generation complete.                    
INFO[0002] Running OpenAPI code-generation for Custom Resource group versions: [syndesis:[v1alpha1], ] 
API rule violation: names_match,github.com/syndesisio/syndesis/install/operator/pkg/apis/syndesis/v1alpha1,SyndesisSpec,RouteHostName
2019/06/27 16:00:04 OpenAPI code generation error: Failed executing generator: some packages had errors:
API rule violations exist
Error: failed to perform openapi code-generation: failed to exec []string{"/home/phantomjinx/programming/go/src/github.com/syndesisio/syndesis/install/operator/build/_output/bin/openapi-gen", "--input-dirs", "github.com/syndesisio/syndesis/install/operator/pkg/apis/syndesis/v1alpha1", "--output-package", "github.com/syndesisio/syndesis/install/operator/pkg/apis/syndesis/v1alpha1", "--output-file-base", "zz_generated.openapi", "--go-header-file", "/tmp/685499015"}: exit status 1
Usage:
  operator-sdk generate openapi [flags]
```
- By changing the GOPATH (with use of softlinks) it is possible to bypass this error and move on to building the operator. The error doesn't seem to hinder the operator being built.
- Until recently, the _-i_ switch was used to cause the creation of an image, eg. _syndesis build -m meta -f -i_. If this switch is used with the operator then local docker building is chosen. This works correctly except it builds the image literally on my installed local docker instance. When using minishift, this is the wrong docker instance and hence the new image is not available to openshift. There is no clue that this is the case unless really hunted for.
- Without using _-i_, the s2i version is used which does require openshift. However, this currently errors out [here](https://github.com/syndesisio/syndesis/blob/master/install/operator/.lib.sh#L157). On Fedora, _mktemp_ complains about lacking 'XXX' [symbols](https://github.com/rtomayko/shocco/issues/5) in its command. This causes the tar archive to be named '.tar' and the s2i build immediately errors out. The line can be changed to the following and the build works correctly:
```
local arch="$(mktemp -t ${S2I_STREAM_NAME}-dockerXXX).tar"
``` 
2. Running syndesis
All pods have been deployed and all running correctly:
```
NAME                          READY     STATUS      RESTARTS   AGE
syndesis-db-1-8p5vr           2/2       Running     0          26m
syndesis-meta-2-gw6n4         1/1       Running     0          17m
syndesis-oauthproxy-1-2hnqt   1/1       Running     0          26m
syndesis-operator-1-tm45d     1/1       Running     0          28m
syndesis-operator-5-build     0/1       Completed   0          33m
syndesis-prometheus-1-jmjgb   1/1       Running     0          26m
syndesis-server-2-6b567       1/1       Running     0          2m
syndesis-ui-1-4r6sf           1/1       Running     0          26m
```
However, the syndesis home page fails to appear. Rather, I have 
![Screenshot_20190627_170803](https://user-images.githubusercontent.com/1634180/60282151-2c11f400-98fe-11e9-818c-56617e14d491.png)
- Unfortunately, I have no errors in the console, pods logs or events to determine the problem.

**Comment by phantomjinx** [comment]
@lgarciaaco @chirino 
Any chance you can have a read and consider possible avenues of things to try?
Thx!

**Comment by phantomjinx** [comment]
Note. in order to get the operator working https://github.com/syndesisio/syndesis/pull/5954 has been applied to my local branch.

**Comment by lgarciaaco** [comment]
@phantomjinx try `go 1.12.6`, that took care of the `operator-sdk ...` issues for me

**Comment by phantomjinx** [comment]
Upgraded to go 1.12.6 & found following issues:

- Tried to execute `dep init` & it failed with a bunch of "could not solves"
- Followed [this](https://darkowlzz.github.io/post/dep-solve-errors/) & created a _Gopkg.toml_ file with following:
```
[[constraint]]
  name = "github.com/syndesisio/syndesis"
  branch = "master"
```
- Then could execute `dep ensure` which failed with 'unable to find k8s.io/gengo/boilerplate'
- Then called `go get k8s.io/gengo`
- Then could execute `install/operator/build.sh` which fails with following:
```
API rule violation: names_match,github.com/syndesisio/syndesis/install/operator/pkg/apis/syndesis/v1alpha1,SyndesisSpec,RouteHostName
```
- [Looking](https://github.com/kubernetes/kube-openapi/blob/master/pkg/generators/rules/names_match.go) this up, this indicated a disparity between the go name and the json name for 'RouteHostName'. Sure enough there is a difference in the second 'n' with the json name using a little 'n'.
- Modified the go name to 'RouteHostname' and recompiled. This executed but then encounters a further error in _zz_generated.openapi_:
```
unable to format file "/home/phantomjinx/programming/go/src/github.com/syndesisio/syndesis/install/operator/pkg/apis/syndesis/v1alpha1/zz_generated.openapi.go" (150:2: missing ',' before newline in composite literal (and 6 more errors)).
```
- The generation is not including any tabs making comparing with the original harder so trying to understand the reason why a) no tabs & b) comma is missing.
- ... ... ... more progress to follow.

**Comment by phantomjinx** [comment]
... ... ...
- Generation is failing due to Addons type in SyndesisSpec. If it is removed then the generation works correctly including tabs.

**Comment by lgarciaaco** [comment]
@phantomjinx master is not using `dep` anymore for dependencies resolution, but `mod`. Something like `go mod vendor` is what you are looking for, however, that step is included when you run `./install/operator/build.sh`

**Comment by phantomjinx** [comment]
@lgarciaaco 
Cool ... although have been running `./install/operator/build.sh` all along (either directly or through build_operator in tools/bin/build) and didn't seem to get past the `go get k8s.io/gengo`. So that may still be a problem. Will kill off changes at the end and redo to check. Wanna understand this AddonsSpec problem first.

**Comment by phantomjinx** [comment]
Part 2 of issue should be fixed by #5987.

**Comment by phantomjinx** [comment]
So I think there is a bug in the k8s code generator used for creating [zz_generated.openapi.go](https://github.com/syndesisio/syndesis/blob/master/install/operator/pkg/apis/syndesis/v1alpha1/zz_generated.openapi.go) from [syndesis_types.go](https://github.com/syndesisio/syndesis/blob/master/install/operator/pkg/apis/syndesis/v1alpha1/syndesis_types.go).

Since the _Addons_ type has been added to _SyndesisSpec_, the generator seems to get confused with the number of braces required to complete the type. It correctly creates a well-formed json object:
```
"addons": {
  SchemaProps: spec.SchemaProps{
    Type: []string{"object"},
    AdditionalProperties: &spec.SchemaOrBool{
      Schema: &spec.Schema{
        SchemaProps: spec.SchemaProps{
          Type: []string{"array"},
          Items: &spec.SchemaOrArray{
            Schema: &spec.Schema{
              SchemaProps: spec.SchemaProps{
              },
            },
          },
        },
      },
    },
  },
},
```
However, it then immediately inserts the [Dependencies](https://github.com/syndesisio/syndesis/blob/master/install/operator/pkg/apis/syndesis/v1alpha1/zz_generated.openapi.go#L133) line directly underneath rather than adding a couple more braces. This causes the error:
```
errors in package "github.com/syndesisio/syndesis/install/operator/pkg/apis/syndesis/v1alpha1":
unable to format file "/home/phantomjinx/programming/go/src/github.com/syndesisio/syndesis/install/operator/pkg/apis/syndesis/v1alpha1/zz_generated.openapi.go" (150:2: missing ',' before newline in composite literal (and 6 more errors)).
```

As a workaround would it make sense to turn off generation of this particular part of the openapi by removing ``// +k8s:openapi-gen=true`` at [line 12](https://github.com/syndesisio/syndesis/blob/master/install/operator/pkg/apis/syndesis/v1alpha1/syndesis_types.go#L12)?

@lgarciaaco @chirino

**Comment by phantomjinx** [comment]
Building with changes is successful. However, still receive the following error(?):
```
W0628 16:52:41.868119   27033 parse.go:239] Ignoring child directory github.com/syndesisio/syndesis/install/operator/pkg/apis/syndesis: unable to import "github.com/syndesisio/syndesis/install/operator/pkg/apis/syndesis": go/build: importGo github.com/syndesisio/syndesis/install/operator/pkg/apis/syndesis: exit status 1
go: finding github.com/syndesisio/syndesis/install/operator/pkg/apis/syndesis latest
go: finding github.com/syndesisio/syndesis/install/operator/pkg/apis latest
go: finding github.com/syndesisio/syndesis/install/operator/pkg latest
go: finding github.com/syndesisio/syndesis/install latest
go: finding github.com/syndesisio/syndesis v0.3.6
go: downloading github.com/syndesisio/syndesis v0.3.6
go: extracting github.com/syndesisio/syndesis v0.3.6
can't load package: package github.com/syndesisio/syndesis/install/operator/pkg/apis/syndesis: unknown import path "github.com/syndesisio/syndesis/install/operator/pkg/apis/syndesis": cannot find module providing package github.com/syndesisio/syndesis/install/operator/pkg/apis/syndesis
```
Don't understand at the moment why or what is failing?

**Comment by heiko-braun** [comment]
@nicolaferraro @lburgazzoli Can you help resolve this?

**Comment by chirino** [comment]
Get fresh checkout from master and try again. A few related issues have been fixed there.

**Comment by phantomjinx** [comment]
> Building with changes is successful. However, still receive the following error(?):
> 
> ```
> W0628 16:52:41.868119   27033 parse.go:239] Ignoring child directory github.com/syndesisio/syndesis/install/operator/pkg/apis/syndesis: unable to import "github.com/syndesisio/syndesis/install/operator/pkg/apis/syndesis": go/build: importGo github.com/syndesisio/syndesis/install/operator/pkg/apis/syndesis: exit status 1
> go: finding github.com/syndesisio/syndesis/install/operator/pkg/apis/syndesis latest
> go: finding github.com/syndesisio/syndesis/install/operator/pkg/apis latest
> go: finding github.com/syndesisio/syndesis/install/operator/pkg latest
> go: finding github.com/syndesisio/syndesis/install latest
> go: finding github.com/syndesisio/syndesis v0.3.6
> go: downloading github.com/syndesisio/syndesis v0.3.6
> go: extracting github.com/syndesisio/syndesis v0.3.6
> can't load package: package github.com/syndesisio/syndesis/install/operator/pkg/apis/syndesis: unknown import path "github.com/syndesisio/syndesis/install/operator/pkg/apis/syndesis": cannot find module providing package github.com/syndesisio/syndesis/install/operator/pkg/apis/syndesis
> ```
> 
> Don't understand at the moment why or what is failing?

This has now been fixed. Thx @chirino 

PR with changes problems encountered above/fixes submitted.

**Comment by lburgazzoli** [comment]
I did try to run the build (although I'm not a super expert on the syndesis operator) and the only thing I had to apply was the trick on `mktemp`

```
$ syndesis build --local -m operator -f
==============================================================================
Building syndesis-operator
==============================================================================
~/work/redhat/dev/syndesis-go/src/github.com/syndesisio/syndesis/install/operator ~/work/redhat/dev/syndesis-go/src/github.com/syndesisio/syndesis/install/operator
======================================================
Building executable with go tooling
======================================================
INFO[0000] Running deepcopy code-generation for Custom Resource group versions: [syndesis:[v1alpha1], ]
INFO[0004] Code-generation complete.
writing assets_vfsdata.go
building executable
?   	github.com/syndesisio/syndesis/install/operator/cmd/manager	[no test files]
?   	github.com/syndesisio/syndesis/install/operator/pkg/apis	[no test files]
?   	github.com/syndesisio/syndesis/install/operator/pkg/apis/syndesis/v1alpha1	[no test files]
?   	github.com/syndesisio/syndesis/install/operator/pkg/build	[no test files]
?   	github.com/syndesisio/syndesis/install/operator/pkg/controller	[no test files]
?   	github.com/syndesisio/syndesis/install/operator/pkg/controller/syndesis	[no test files]
ok  	github.com/syndesisio/syndesis/install/operator/pkg/generator	(cached)
?   	github.com/syndesisio/syndesis/install/operator/pkg/generator/assets	[no test files]
?   	github.com/syndesisio/syndesis/install/operator/pkg/generator/dev	[no test files]
?   	github.com/syndesisio/syndesis/install/operator/pkg/openshift	[no test files]
?   	github.com/syndesisio/syndesis/install/operator/pkg/openshift/serviceaccount	[no test files]
?   	github.com/syndesisio/syndesis/install/operator/pkg/openshift/template	[no test files]
?   	github.com/syndesisio/syndesis/install/operator/pkg/syndesis/action	[no test files]
?   	github.com/syndesisio/syndesis/install/operator/pkg/syndesis/addons	[no test files]
ok  	github.com/syndesisio/syndesis/install/operator/pkg/syndesis/configuration	(cached)
?   	github.com/syndesisio/syndesis/install/operator/pkg/syndesis/legacy	[no test files]
?   	github.com/syndesisio/syndesis/install/operator/pkg/syndesis/operation	[no test files]
?   	github.com/syndesisio/syndesis/install/operator/pkg/syndesis/template	[no test files]
ok  	github.com/syndesisio/syndesis/install/operator/pkg/util	(cached)
building executable
======================================================
Building image with S2I
======================================================
/tmp/syndesis-operator-dockerHxf.tar
build/
build/bin/
build/bin/entrypoint
build/bin/user_setup
build/conf/
build/conf/addons/
build/conf/addons/syndesis-db-dashboard.yml
build/conf/addons/syndesis-db-prometheus-rule.yml
build/conf/addons/syndesis-infrastructure-servicemonitor.yml
build/conf/addons/syndesis-integration-dashboard.yml
build/conf/addons/syndesis-integrations-service.yml
build/conf/addons/syndesis-integrations-servicemonitor.yml
build/conf/addons/syndesis-jvm-dashboard.yml
build/conf/addons/syndesis-legacy-ui-serviceaccount.yml
build/conf/addons/syndesis-legacy-ui.yml
build/conf/addons/syndesis-rest-api-dashboard.yml
build/conf/addons/syndesis-rest-api-prometheus-rule.yml
build/conf/template-config.yaml
build/_output/
build/_output/bin/
build/_output/bin/client-gen
build/_output/bin/lister-gen
build/_output/bin/informer-gen
build/_output/bin/deepcopy-gen
build/_output/bin/operator
build/Dockerfile
Dockerfile
Uploading archive file "/tmp/syndesis-operator-dockerHxf.tar" as binary input for the build ...

Uploading finished
build.build.openshift.io/syndesis-operator-2 started
```

**Comment by mastepan** [comment]
@phantomjinx anything here for QE? Or can you please add ignore/qe and close otherwise?

**Comment by phantomjinx** [comment]
@mastepan 
Was going to mark it qe/ignored but did wonder how much qe test the `syndesis build ...` functions of the syndesis command tool?

**Comment by mastepan** [comment]
> @mastepan
> Was going to mark it qe/ignored but did wonder how much qe test the `syndesis build ...` functions of the syndesis command tool?

@avano can you provide any info?

**Comment by heiko-braun** [comment]
The syndesis build functions should work for QE (everyone should be able to build and install syndesis), but they don't belong to the product and hence don't need to be tested by QE. It's the responsiblity of the  upstream community (including @phantomjinx ) to maintain these I would think.

**Comment by heiko-braun** [comment]
@phantomjinx If you think this issue has been resolved, feel free to close it. I've added `ignore/qe` on your behalf.
