### ISSUE TITLE
Fetching integrations that use a specific extension always returns an empty array

### ISSUE THREAD

**Issue by elvisisking** [syndesisio/syndesis#5974]
## This is a...

<pre><code>
[ ] Feature request
[x ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
I remember this working some time ago when I first implemented the React code for extensions. Here is the fetch (dev server) URL I am using to return the integrations used by an extension with an ID of `i-Lhot0JO0d0Su26sEoVBz`:
```
http://localhost:3000/api/v1/extensions/i-Lhot0JO0d0Su26sEoVBz/integrations
```
Does that URL look right?

**Comment by riccardo-forina** [comment]
Stupid question, was that extension actually being used by an integration?

**Comment by elvisisking** [comment]
Yes it was @riccardo-forina

**Comment by riccardo-forina** [comment]
It sounds like a BE issue then. CC @syndesisio/backend
