### ISSUE TITLE
Integrations - allow going back when a wrong connection selected

### ISSUE THREAD

**Issue by mastepan** [syndesisio/syndesis#598]
1. Click Integrations
2. Click Create Integration
3. Select a connection
4. Choose an Action - whoops I have clicked a wrong connection a step before and I can't go back. I only can finish the wrong connection configuration and then delete it and choose another one.

**Comment by rhuss** [comment]
Thanks for reporting!

We have this discussion here, too: https://github.com/syndesisio/syndesis/issues/317 , let's follow up on this.
