### ISSUE TITLE
Operator generates invalid config.json (on `master`)

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#5987]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Operator seems to be using single quotes in JSON, which doesn't parse on the UI.

**Comment by riccardo-forina** [comment]
Yeah, single quotes can't be used in JSON documents...

**Comment by zregvart** [comment]
I'll close this, it's only on `master` and the cause is recent refactor of the operator. When we get to QE this will be validated regardless.
