### ISSUE TITLE
Gateway timeouts on staging when requesting integrations

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#5989]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
It's time we talk about this :smile: 

On staging there's probably 10 or so integrations.  And currently we've a 30 second (apparently) proxy timeout set up for oauth proxy.  It appears that periodically the request handling for the `/api/v1/integrations` takes longer than the timeout, and in fact what I'm seeing is that other endpoints also can take 10-12 seconds while I'm seeing gateway timeouts.

I did however notice that sometimes the request to `/api/v1/integrations` can complete in a lot less time.  Until I decided to start an integration and then guess what, moar timeout responses.  One thing to note is that the UI currently ensures it debounces incoming change events, and the UI also really tries to avoid sending multiple requests when fetching integrations.  For example, here's while I'm typing this:

![image](https://user-images.githubusercontent.com/351660/60350421-7bedcb00-9991-11e9-894a-d6ba7f9b3ac2.png)

The successful requests are to the monitoring endpoint for the detailed status data, the two red items there are timed out requests to fetch integrations.

**Comment by heiko-braun** [comment]
@gashcrumb What priority would give to this? How does it impact people?

**Comment by gashcrumb** [comment]
Hard to say, if it's something that'll show up after 2-3 weeks of usage it seems like it could be a p0.  Could be related to the same kinda thing that QE reported.

The result of the timeout is that the UI displays a big error instead of integrations.

**Comment by zregvart** [comment]
Did anyone experience this recently? @syndesisio/ui do you still use staging as backend? Any issues?

**Comment by riccardo-forina** [comment]
Yep. Today at 6PM it was _very_ slow at losing integrations or connections. I never waited for a timeout, but I did wait ~10s or so.

**Comment by zregvart** [comment]
I've run:

```sql
postgres=# ALTER DATABASE syndesis SET log_min_duration_statement = 5000;
ALTER DATABASE
```

On PostgreSQL in `syndesis-staging` project, this should log slow queries (over 5sec) this way we can notice if there are any especially slow queries and try to optimize them.

**Comment by zregvart** [comment]
Also:

```sql
postgres=# LOAD 'auto_explain';
LOAD
postgres=# SET auto_explain.log_min_duration = '10s';
SET
postgres=# SET auto_explain.log_analyze = true;
SET
```

**Comment by zregvart** [comment]
With those settings the syndesis-db log (postgresql container) should log statements and run the analysis. It looks something like this:

```
2019-07-10 19:53:12 UTC psql SELECT 00000 5d264125.4497 LOG: duration: 11011.046 ms plan:
	Query Text: SELECT pg_sleep(11);
	Result (cost=0.00..0.01 rows=1 width=0) (actual time=11011.026..11011.027 rows=1 loops=1)
2019-07-10 19:53:12 UTC psql SELECT 00000 5d264125.4497 LOG: duration: 11011.247 ms statement: SELECT pg_sleep(11);
```

**Comment by zregvart** [comment]
This [logs search](https://logs.rh-idev.openshift.com/goto/de75cbe8e4da86c6059d6fca3a8a402e) should surface any slow queries (executing longer than 10sec).

I think what we're most likely seeing is the server pod being restarted and not being ready to serve requests. We currently use recreate deployment strategy which doesn't afford high availability.

**Comment by zregvart** [comment]
We have a number of slow queries logged, here's an example:
```
2019-07-16 07:59:23 UTC [unknown] SELECT 00000 5d2cf0a7.726 LOG:  duration: 348570.216 ms  execute S_2: select path,value,ovalue from jsondb where path LIKE $1 order by path ASC
2019-07-16 07:59:23 UTC [unknown] SELECT 00000 5d2cf0a7.726 DETAIL:  parameters: $1 = '/integration-deployments/%'
```

There's a total of 547 slow queries (over 10 sec) from July 16th 2019, 04:59:24.338 till July 16th 2019, 10:21:29.621 (4h 21min).

Database is using 753MiB:
```
sh-4.2$ df -kh
Filesystem                              Size  Used Avail Use% Mounted on
overlay                                 5.0G   28K  5.0G   1% /
tmpfs                                   7.6G     0  7.6G   0% /dev
tmpfs                                   7.6G     0  7.6G   0% /sys/fs/cgroup
/dev/mapper/rootvg-var                   45G  2.8G   43G   7% /etc/hosts
shm                                      64M  4.0K   64M   1% /dev/shm
/dev/mapper/docker_vg-docker--root--lv  200G   24G  177G  12% /run/secrets
/dev/nvme4n1                            976M  753M  208M  79% /var/lib/pgsql/data
tmpfs                                   7.6G   24K  7.6G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs                                   7.6G     0  7.6G   0% /proc/acpi
tmpfs                                   7.6G     0  7.6G   0% /proc/scsi
tmpfs                                   7.6G     0  7.6G   0% /sys/firmware
```

There are 44732 rows in the jsondb table:

```
syndesis=> select count(*) from jsondb;
 count 
-------
 44732
(1 row)
```

Seems that auto-vacuuming of the jsondb table is failing with a great number of tuples remaining in the data files:

```
2019-07-16 08:29:56 UTC   00000 5d2d89fe.551a LOG:  automatic vacuum of table "syndesis.public.jsondb": index scans: 0
	pages: 0 removed, 19845 remain, 8 skipped due to pins
	tuples: 0 removed, 800813 remain, 755946 are dead but not yet removable
	buffer usage: 28855 hits, 64398 misses, 54 dirtied
	avg read rate: 1.916 MB/s, avg write rate: 0.002 MB/s
	system usage: CPU 0.63s/0.29u sec elapsed 262.58 sec
```

**Comment by gashcrumb** [comment]
Yeah, staging is kinda unusable today it's looking like...

![image](https://user-images.githubusercontent.com/351660/61308010-52200b00-a7bd-11e9-8c5a-b8b40638822d.png)

:disappointed:

**Comment by zregvart** [comment]
We can "fix" this on staging by truncating the `jsondb` table. The issue in #6052 is about activity logging, this seems to be about persistence of Integration/IntegrationDeployment to `jsondb` perhaps finding a way to reproduce this so we can validate any fix we make beforehand would be a good idea.

**Comment by zregvart** [comment]
I've truncated the `jsondb` table on staging.

**Comment by chirino** [comment]
Can someone attach a database export of the system when it hangs like this?  That ways it's easier to reproduce on local development systems?

**Comment by zregvart** [comment]
> Can someone attach a database export of the system when it hangs like this? That ways it's easier to reproduce on local development systems?

I think you need the whole volume, the data file from 500-800MB and there are only 45000-50000 rows at this point.

**Comment by gashcrumb** [comment]
So, staging is misbehaving a lot this week, even for connections:

![image](https://user-images.githubusercontent.com/351660/62656067-66c17000-b931-11e9-8a8e-a1e9392eb098.png)

**Comment by zregvart** [comment]
Today I performed a `VACUUM ANALYSE FULL jsondb` to get rid of dead tuples and update table statistics.

The current breakdown of rows by type:

```sql
syndesis=> select distinct(substring(path, '\/[^/]+\/')), count(*) from jsondb group by 1;
           substring           | count
-------------------------------+-------
 /activity/                    |   417
 /connection-bulletin-boards/  |    90
 /connections/                 |  2297
 /connector-templates/         |   318
 /connectors/                  | 10062
 /extensions/                  |    72
 /integration-bulletin-boards/ |  1184
 /integration-deployments/     | 37203
 /integration-endpoints/       |    31
 /integrations/                | 27787
 /open-apis/                   |    49
(11 rows)
```
