### ISSUE TITLE
Reduce number of OpenShift templates

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#599]
Actually, we have different flavours of templates:

```
syndesis-ci.yml
syndesis-dev-restricted.yml
syndesis-dev.yml
syndesis-ephemeral-restricted.yml
syndesis-restricted.yml
syndesis.yml
```

For maintenance, documentation and simplicity, I'd like to reduce this number based on the following observations:

* syndesis-ci.yml removes healthchecks. @iocanel do we need this anymore?
* _Non restricted_ templates are not used anywhere, so we could safely remove them?
* What is `syndesis-ephemeral-restricted.yml` for ?
* The dev templates uses plain images instead of image-streams. Actually, I don't see a benefit of this approach, as using imagestream will automatically trigger a redeployment (this is currently broken, but I'm confident that this can be fixed). In addition, it adds the JAVA_DEBUG variable, but I think this should not be there (but temporarily switched on when debugging). See #593 for additional information. Opinions on this ?

Ideally, we would only have `syndesis.yml`, that way we would also dev and test against the very same template.

@syndesisio/backend any opinions on this ?

**Comment by zregvart** [comment]
👍 on reducing the number of templates

**Comment by paoloantinori** [comment]
discovering what we can safely remove sounds like a documentation and system design activity.
definitely a +1 from me =P

**Comment by jimmidyson** [comment]
> What is syndesis-ephemeral-restricted.yml for ?
This was for when we had problems mounting PVs IIRC. Not needed any more.

**Comment by jimmidyson** [comment]
> Non restricted templates are not used anywhere, so we could safely remove them?

I wanted to make a start on playing with a multitenant Syndesis so I would prefer not to remove them if possible. Thinking about is, the main difference is the use of a global oauthclient, which I'm not sure if we would need for multitenancy actually.

So... :+1: for removing, we can resurrect later if we need it.

**Comment by zregvart** [comment]
We reduced to one and increased to two with the #3576, I'd say we're done here.
