### ISSUE TITLE
komodo-server is missing ENV variable CONTROLLERS_EXPOSE_VIA3SCALE

### ISSUE THREAD

**Issue by rareddy** [syndesisio/syndesis#5999]
## This is a bug

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
The exposure of the odata routes are controlled through CONTROLLERS_EXPOSE_VIA3SCALE env property. It is not defined with default value in the template/operator

**Comment by heiko-braun** [comment]
@rareddy Wasn't there a PR already to address this?

**Comment by rareddy** [comment]
Yes, I believe that is already pulled in. This can be closed
