### ISSUE TITLE
Find optimal time slots for team meetings

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#6]
Currently, we have the following team meetings:

* Daily Standup (15 mins)
* Retrospective (1 hour every 3 weeks)
* Planning Meeting (1 hour every 3 weeks)
* Sprint Demo (1 hour every 3 weeks)

Each of these meetings is supposed to be mandatory to attend (except for reasons).

However, the scheduled dates are not optimal, so that there is a systematic problem to attend certain meetings. Let's try a bit harder and find a common base.

I'm going to open Doodles for these meetings, especially the standup meeting is critical.

**Comment by rhuss** [comment]
Doodle started

**Comment by gashcrumb** [comment]
I think this is all set.
