### ISSUE TITLE
Integrations - unify "Add a Step"/"Choose a Step" labels

### ISSUE THREAD

**Issue by mastepan** [syndesisio/syndesis#600]
I would use **Choose a Step** as there already is **Choose a Connection**
This can also cause naming issues in our testsuite.
![choosestep](https://user-images.githubusercontent.com/8707251/33597830-df4d8666-d9a0-11e7-9c4e-35a4afdcc784.png)
![chooseconnection](https://user-images.githubusercontent.com/8707251/33597871-02fc16f4-d9a1-11e7-8ed0-226b3a9cb9c2.png)

**Comment by dongniwang** [comment]
PR https://github.com/syndesisio/syndesis/pull/604 is merged. Closing this issue.
