### ISSUE TITLE
Connection Edit Issues

### ISSUE THREAD

**Issue by rareddy** [syndesisio/syndesis#6001]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
After the first time connection is created in syndesis, then click edit the connection, and then modify couple fields then hit cancel. The modified fields are kept as new values

## Expected behavior
Revert the properties to original values

**Comment by zregvart** [comment]
Sounds like a blocker to me woudn't you agree @paoloantinori?

**Comment by heiko-braun** [comment]
@riccardo-forina Mind taking a look?
