### ISSUE TITLE
The title isn't updated

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#6004]
See also **https://issues.jboss.org/browse/ENTESB-11408**

## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
In some cases, the title isn't properly updated when navigating between various pages. Most notably it probably doesn't update ever when user clicks on the Syndesis logo in the top left. Steps to reproduce are captured in the GIF attached.
![Peek 2019-07-01 07-47](https://user-images.githubusercontent.com/46345469/60413517-7f719400-9bd5-11e9-8278-f8a08a5502ba.gif)

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11408**
