### ISSUE TITLE
Cannot create any oauth connections

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#6005]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
The `connect *connector type*` button doesn't show up when creating new connections which require oauth, instead a message that user needs to input oauth settings is displayed, although it's already set up.
![Peek 2019-07-01 08-36](https://user-images.githubusercontent.com/46345469/60415466-83a0b000-9bdb-11e9-9e66-2d594966477e.gif)

**Comment by tplevko** [comment]
@heiko-braun @paoloantinori QE is blocked by this

**Comment by heiko-braun** [comment]
@christophd @zregvart Can you work  with @mmuzikar to resolve this? I guess we need another  release once its fixed.

**Comment by heiko-braun** [comment]
@riccardo-forina your feedback might be useful as well

**Comment by zregvart** [comment]
Relates to #5924

**Comment by tplevko** [comment]
@zregvart would it be possible to get a set of images with this fix included?

**Comment by christophd** [comment]
@tplevko 1.7.8 release build is running already

**Comment by tplevko** [comment]
@christophd perfect, thanks!

**Comment by heiko-braun** [comment]
Thanks for quick turnariund @zregvart !

**Comment by mmuzikar** [comment]
Verified by QE, thanks @zregvart
