### ISSUE TITLE
SQL connector cannot access the sampledb tables in 1.8-SNAPSHOT

### ISSUE THREAD

**Issue by jsafarik** [syndesisio/syndesis#6014]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Same issue as https://github.com/syndesisio/syndesis/issues/5603, the tables are in public schema and syndesis can't find them. When I tried to do `SELECT * FROM todo` and click the next button, it says `Table 'TODO' does not exist in schema 'sampledb'. Unable to fetch and process metadata`.

The database shows this
```
sampledb=> \dt
          List of relations
 Schema |  Name   | Type  |  Owner
--------+---------+-------+----------
 public | contact | table | sampledb
 public | todo    | table | sampledb
(2 rows)
```

after changing the schema to `sampledb`, it works as supposed.

Reporting this again because it only occurs in 1.8-SNAPSHOT,

**Comment by KurtStam** [comment]
Weird.. they should be in the sampled schema. Can you verify that `syndesis-sampledb-config` configmap has the line:

https://github.com/syndesisio/syndesis/blob/master/install/syndesis.yml#L565

**Comment by KurtStam** [comment]
I seems to be using

operator/pkg/generator/assets/install/04-syndesis-db.yml.mustache 

now, which is an older version, hence the regression.

**Comment by jsafarik** [comment]
@KurtStam I just looked to the `syndesis-sampledb-config` configmap and see no line `CREATE SCHEMA AUTHORIZATION sampledb;` there. The config goes as
```
...
psql -d sampledb -U sampledb <<'EOF'
  CREATE TABLE IF NOT EXISTS contact (first_name VARCHAR, last_name VARCHAR, company VARCHAR, lead_source VARCHAR, create_date DATE);
...
```
the other file you posted looks like the one it uses.
