### ISSUE TITLE
[#Error report] Data Virtualizations - Error: Bad Gateway

### ISSUE THREAD

**Issue by fhornaintest** [syndesisio/syndesis#6015]
## Description
I just ran the command : bash <(curl -sL https://syndes.is/start)
As soon as the installation was done, I went to the Syndesis GUI and click on Data tabulation.
I got the 
"Something is wrong
An error occurred while talking with the server.
Please check your internet connection."
error message.

Regards
Frederic

**Comment by heiko-braun** [comment]
@KurtStam @rareddy Mind taking a look?

**Comment by rareddy** [comment]
Maybe backend Komodo-Server is no started?

**Comment by fhornaintest** [comment]
Hi Ramesh,

Into Openshift GUI -see attached sceenshot -  and container process list, I do not see any Komodo reference ?
How can I check Komodo is running and how can I start it ?

![Screenshot from 2019-07-03 09-48-08](https://user-images.githubusercontent.com/35542169/60573313-bb445f00-9d77-11e9-9c27-c0fb6cc25641.png)

Thanks in advance for your collaboration

**Comment by heiko-braun** [comment]
@rareddy This seems to be related to https://github.com/syndesisio/syndesis/issues/5475. I don't think the changes in https://github.com/syndesisio/syndesis/issues/5475 are effective.

**Comment by heiko-braun** [comment]
@rkorytkowski Any idea why we see an error opposed to handling the absence of Komodo in a graceful manner?

![Screenshot 2019-07-03 at 09 53 54](https://user-images.githubusercontent.com/369380/60574090-2cd0dd00-9d79-11e9-8404-7da4895cbb06.png)

**Comment by fhornaintest** [comment]
Thank you.

**Comment by rkorytkowski** [comment]
Someone broke the feature in operator install. I'll fix that.

**Comment by rkorytkowski** [comment]
Also installing Komodo is broken.

**Comment by rkorytkowski** [comment]
I get an error trying to build the operator:
{code}
[rafal@elusive-rh operator]$ ./build.sh
======================================================
Building executable with go tooling
======================================================
go: finding github.com/emicklei/go-restful-swagger12 latest
go: finding github.com/openshift/api/build latest
go: finding github.com/openshift/api/image latest
go: finding github.com/openshift/api/servicecertsigner latest
go: finding github.com/openshift/api/security latest
go: finding github.com/openshift/api/apps latest
go: finding github.com/openshift/api/user latest
go: finding github.com/openshift/api/route latest
go: finding github.com/operator-framework/operator-sdk/commands/operator-sdk/cmd/cmdutil latest
go: finding github.com/operator-framework/operator-sdk/pkg/util/k8sutil latest
go: finding github.com/operator-framework/operator-sdk/commands/operator-sdk/cmd latest
go: finding github.com/operator-framework/operator-sdk/commands/operator-sdk latest
go: finding github.com/operator-framework/operator-sdk/pkg/util latest
go: finding github.com/operator-framework/operator-sdk/commands latest
go: finding github.com/operator-framework/operator-sdk/pkg latest
go: finding bitbucket.org/ww/goautoneg latest
go: finding github.com/openshift/api/operator/v1alpha1 latest
go: finding github.com/openshift/api/network latest
go: finding github.com/openshift/api/config latest
go: finding github.com/openshift/api/operator latest
go: finding github.com/operator-framework/operator-sdk/commands/operator-sdk/cmd/generate latest
go: finding github.com/openshift/api/kubecontrolplane latest
go: finding github.com/openshift/api/legacyconfig latest
go: finding github.com/openshift/api/osin latest
go: finding github.com/operator-framework/operator-sdk/pkg/scaffold latest
go: finding github.com/operator-framework/operator-sdk/pkg/scaffold/input latest
go: finding github.com/operator-framework/operator-sdk/commands/operator-sdk/cmd/test latest
go: finding github.com/openshift/api/project latest
go: finding github.com/operator-framework/operator-sdk/commands/operator-sdk/cmd/completion latest
go: finding github.com/openshift/api/authorization latest
go: finding github.com/openshift/api/template latest
go: finding github.com/openshift/api/openshiftcontrolplane latest
go: finding github.com/operator-framework/operator-sdk/commands/operator-sdk/cmd/add latest
go: finding github.com/openshift/api/webconsole latest
go: finding github.com/mxk/go-flowrate/flowrate latest
go: finding github.com/mxk/go-flowrate latest
go: finding github.com/openshift/api/quota latest
go: finding github.com/bradfitz/gomemcache/memcache latest
go: finding github.com/bradfitz/gomemcache latest
go: finding github.com/sergi/go-diff/diffmatchpatch latest
go: finding github.com/pquerna/ffjson/fflib latest
go: finding github.com/pquerna/ffjson latest
go: finding golang.org/x/build/autocertcache latest
go: finding golang.org/x/build latest
go: finding k8s.io/kube-openapi/pkg/schemaconv latest
go: finding github.com/openshift/api/servicecertsigner/v1alpha1 latest
go: finding github.com/openshift/api/oauth latest
go: finding github.com/pquerna/ffjson/ffjson latest
go: finding github.com/operator-framework/operator-sdk/pkg/scaffold/ansible latest
go: finding github.com/docopt/docopt-go latest
go: finding github.com/petar/GoLLRB/llrb latest
go: finding github.com/operator-framework/operator-sdk/pkg/tlsutil latest
go: finding github.com/operator-framework/operator-sdk/commands/operator-sdk/cmd/up latest
go: finding github.com/petar/GoLLRB latest
go: finding k8s.io/kube-openapi/pkg latest
go: finding github.com/garyburd/redigo/redis latest
go: finding k8s.io/kube-openapi latest
go: finding k8s.io/apimachinery/pkg/api/testing/fuzzer latest
go: finding k8s.io/apimachinery/pkg/api/testing/roundtrip latest
go: finding github.com/openshift/origin/pkg/cmd/server/apis/config latest
go: finding github.com/openshift/origin/pkg/cmd/server/apis latest
go: finding github.com/openshift/origin/pkg/cmd/server latest
go: finding github.com/openshift/origin/pkg/cmd latest
go: finding github.com/openshift/origin/pkg latest
go: finding k8s.io/apimachinery/pkg/api/testing latest
go: finding github.com/operator-framework/operator-sdk/test/e2e/e2eutil latest
go: finding github.com/operator-framework/operator-sdk/test/e2e latest
go: finding github.com/operator-framework/operator-sdk/test latest
go: finding github.com/operator-framework/operator-sdk/test/e2e/framework latest
go: finding github.com/mjibson/appstats latest
go: finding github.com/docker/spdystream latest
go: finding k8s.io/apimachinery/pkg/api latest
go: finding k8s.io/apimachinery/pkg latest
go: finding go4.org/syncutil/singleflight latest
go: finding k8s.io/apimachinery latest
go: finding sigs.k8s.io/structured-merge-diff/schema latest
go: finding github.com/coreos/prometheus-operator/pkg/client/monitoring latest
go: finding github.com/coreos/prometheus-operator/pkg/client latest
go: finding github.com/coreos/prometheus-operator/pkg latest
go: finding github.com/syndtr/goleveldb/leveldb latest
go: finding go4.org/syncutil latest
go: finding github.com/elazarl/goproxy latest
go: finding sigs.k8s.io/structured-merge-diff latest
go: finding go4.org latest
go: finding k8s.io/kubernetes/pkg/kubectl/util latest
go: finding k8s.io/kubernetes/pkg/kubectl latest
go: finding k8s.io/kubernetes/pkg latest
go: finding k8s.io/component-base v0.0.0
go: finding k8s.io/cluster-bootstrap v0.0.0
go: finding k8s.io/sample-apiserver v0.0.0
go: finding k8s.io/kube-controller-manager v0.0.0
go: finding k8s.io/csi-translation-lib v0.0.0
go: finding k8s.io/cli-runtime v0.0.0
go: finding k8s.io/cloud-provider v0.0.0
go: finding k8s.io/legacy-cloud-providers v0.0.0
go: finding k8s.io/kubelet v0.0.0
go: finding k8s.io/metrics v0.0.0
go: k8s.io/component-base@v0.0.0: unknown revision v0.0.0
go: k8s.io/legacy-cloud-providers@v0.0.0: unknown revision v0.0.0
go: k8s.io/cluster-bootstrap@v0.0.0: unknown revision v0.0.0
go: k8s.io/cli-runtime@v0.0.0: unknown revision v0.0.0
go: k8s.io/kube-controller-manager@v0.0.0: unknown revision v0.0.0
go: k8s.io/csi-translation-lib@v0.0.0: unknown revision v0.0.0
go: k8s.io/cloud-provider@v0.0.0: unknown revision v0.0.0
go: k8s.io/sample-apiserver@v0.0.0: unknown revision v0.0.0
go: k8s.io/kubelet@v0.0.0: unknown revision v0.0.0
go: k8s.io/metrics@v0.0.0: unknown revision v0.0.0
go: finding k8s.io/cri-api v0.0.0
go: finding k8s.io/apiserver v0.0.0
go: finding k8s.io/kube-proxy v0.0.0
go: finding k8s.io/kube-aggregator v0.0.0
go: finding k8s.io/kube-scheduler v0.0.0
go: k8s.io/cri-api@v0.0.0: unknown revision v0.0.0
go: k8s.io/kube-scheduler@v0.0.0: unknown revision v0.0.0
go: k8s.io/kube-proxy@v0.0.0: unknown revision v0.0.0
go: k8s.io/apiserver@v0.0.0: unknown revision v0.0.0
go: k8s.io/kube-aggregator@v0.0.0: unknown revision v0.0.0
go: error loading module requirements
{code}
I get the same error when running with docker: ` ./build.sh --operator-build docker --image-build s2i` or through syndesis script `syndesis build -m operator -f -c -i` 

@zregvart, @chirino, any idea why it happens for me, but not on CI?

**Comment by heiko-braun** [comment]
@rkorytkowski Please coordinate any operator changes with @nicolaferraro

**Comment by zregvart** [comment]
@rkorytkowski there was an issue when using older version of go that didn't support go modules, perhaps check that. Also I'm guessing this is only an issue on `master`, not on `1.7.x`, operator changed a lot on `master`.

**Comment by heiko-braun** [comment]
go `1.12.6` is supposed to work I think

**Comment by rkorytkowski** [comment]
Upgrading to go 1.12.6 didn't help. Also running `./build.sh --image-build docker --operator-build docker` fails as well. Strangely the error `go: error loading module requirements` happens at different point in time for each build I try.

Also looking at some recent builds on CI e.g. https://circleci.com/gh/syndesisio/syndesis/85715 I see a completely different list of modules being fetched... I'm completely new to go and not sure how this all works. I'd expect the same list unless our CI setup does not start from scratch, but uses some caching.

**Comment by rkorytkowski** [comment]
It's related to https://github.com/kubernetes/kubernetes/issues/79384

I need to figure out the list of all kubernetes submodules now...

**Comment by rkorytkowski** [comment]
Hmmm, it was reported for master, wasn't it? (https://syndes.is/start fetches master).
I can test the 1.7.x branch...

**Comment by rkorytkowski** [comment]
I confirmed it works as expected for a fresh install of the 1.7.x branch.

**Comment by rkorytkowski** [comment]
I haven't moved forward with building the operator in master. I think I've tried all options listed in https://github.com/kubernetes/kubernetes/issues/79384 but with no avail. I'll wait for @nicolaferraro to be back and help me out. The fix in the operator seems to be straightforward, but I cannot test it being unable to build.

**Comment by heiko-braun** [comment]
@rkorytkowski If In understand you correctly, this problem only exists on master? In that case I'll lower the priority, but would suggest we still look into it.

**Comment by rkorytkowski** [comment]
Yes, it's just on master.

**Comment by fhornaintest** [comment]
I confirm it works with 1.7.8 branch.

Here is the command I used to make it working with DataVirt - > ./.syndesis/bin/syndesis minishift --install --full-reset --open --datavirt --tag 1.7.8

Thank you for your support.

Regards
Frederic

**Comment by rkorytkowski** [comment]
Deleting the `dep-cache` dir and running `docker build . --no-cache` fixed the build issue for me today. The `Dep-cache` dir seems to be a leftover after using `dep`. Anyone who built the operator locally before we moved to go mod should delete that dir as it confuses go mod.

**Comment by rkorytkowski** [comment]
The issue was that Komodo deployment has not been included in the revamped operator code at all.

**Comment by mastepan** [comment]
@rkorytkowski how can QE check this fix? If not needed, please add ignore/QE label. Thanks.

**Comment by rkorytkowski** [comment]
@mastepan opening "Data" from the left side menu should not result in Bad Gateway. It should either show not enabled message or list virtualizations (if any).

"Data" can be enabled by setting datavirt.enabled to 1 in ui configmap and scaling Komodo up or disabled by setting the property to 0 and scaling Komodo down. 

"Data" can be also enabled by providing --datavirt to the install script and should be disabled by default.

Note there's a regression in #6314

**Comment by asmigala** [comment]
On 1.7, everything works as expected.

On current master, when applying the workaround mentioned in #6314 and datavirt is disabled, everything works as expected.

However, there's and issue that datavirt is not enabled even with the `--datavirt` flag ( #6342 ).

Applying both the #6314 workaround and the #6343 patch makes everything work again.

I'm keeping this issue open for now and will verify once both of the above fixes are merged.

**Comment by mkralik3** [comment]
Verified. The Data tab works as expected. When `syndesis-dv` is not running, the UI shows information that `Virtualizations are not enabled`. When `syndesis-dv` is running (e.g. after installation with flag `--datavirt` e.g. `syndesis minishift --install --nodev --project syndesis --test-support --datavirt`), the Data tab contains UI for managing the virtualizations.
