### ISSUE TITLE
E2E & integration tests with happy path

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis#6026]
## This is a...

<pre><code>
[ x ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Describe a couple of happy paths and create E2E and integration tests for them.

**Comment by kahboom** [comment]
@zregvart - I know this is a far stretch, but is there any way we can allow duplicate names for Connections + Integrations (right now each has to be unique, instead of having, say, an ID as the unique constraint)?

I get that I think we are using them for pod names + things like JMX MBean names, but I'm wondering if there is any way the BE can use something like IDs and map names where it needs to? I think we've spoken about this before related to the app, but for tests it's also a bit of a problem. My guess is that this is too much work to do, but figured I'd ask anyway. :)

**Comment by kahboom** [comment]
fwiw, in the meantime I do have a workaround with generating unique names. buuut just wanted to give it a shot anyway :)

**Comment by zregvart** [comment]
I think with our tendency to use names as identifiers this will get us into trouble quickly. See #3951.

**Comment by kahboom** [comment]
Initial setup for popular scenarios is complete.
