### ISSUE TITLE
Home tab title is "System Metrics"

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#6027]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

I'm not sure that the title on the _Home_ tab should be _System Metrics_, I think it used to be _Dashboard_. Did we change this on purpose?

![Screenshot_2019-07-02 Syndesis](https://user-images.githubusercontent.com/1306050/60494239-a9e35000-9cae-11e9-91ad-3ba9666304ae.png)

**Comment by riccardo-forina** [comment]
There was no tab title before but `Syndesis`. Now, when it's set, it's set to the same title as the page, in this case System Metrics.

**Comment by zregvart** [comment]
Just checked the Angular app, it's the same, closing this.

![Screenshot_2019-07-02 Syndesis(1)](https://user-images.githubusercontent.com/1306050/60495654-7d7d0300-9cb1-11e9-966a-fd9fc5aaf783.png)
