### ISSUE TITLE
Rename "build.sh" to "syndesis"

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#603]
... as it now carries much as only 'building' Syndesis (but also installing to minishift, system-test and dev parts).

Question is also if `syndesis` or `syndesis.sh` (or any other name).

I would then also put a delegate script to `tools/bin` as folks seems to like this location, too (not sure whether a pure symlink works for GitHub)

**Comment by zregvart** [comment]
I think we only need to remove the existing `build.sh` I would wait just a bit for https://doc.syndesis.io/#_one_tool_to_rule_them_all to have all the details and then we can close this.

**Comment by gashcrumb** [comment]
Seems like we did this in some fashion, good enough.
