### ISSUE TITLE
[OAuth] Twitter connector validation unreadable error message

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#6036]
See also **https://issues.jboss.org/browse/ENTESB-11447**

## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
As a citizen integrator there is no way I can understand following error message:

![screenshot_20190702_141312](https://user-images.githubusercontent.com/14313995/60511995-b3cb7a00-9cd3-11e9-839a-62f4d21ac8f7.png)

The message appears when I try to create twitter connector with invalid credentials.

**Comment by heiko-braun** [comment]
@mcada Based on the description above I don't think this qualifies for `p0`

**Comment by heiko-braun** [comment]
@gaughan What do you think?

**Comment by gashcrumb** [comment]
It's cosmetic really, the information should be available in the javascript console.  Speaking of which, that'd be nice to capture for this kind of thing.  :smile:

**Comment by asmigala** [comment]
The problem with this is that as a user, I have no idea what I'm doing wrong - the error message doesn't say it's my fault because I supplied incorrect credentials. In other words, if a user runs into this, they will think the product is broken with no workaround.

**Comment by gaughan** [comment]
I agree with it being P1

**Comment by riccardo-forina** [comment]
> The problem with this is that as a user, I have no idea what I'm doing wrong - the error message doesn't say it's my fault because I supplied incorrect credentials. In other words, if a user runs into this, they will think the product is broken with no workaround.

I think we all agree that this isn't ideal and we want to fix this. Chances are that this is a trivial error that's easily fixed having the error in the console handy. Do you mind copy-pasting/screenshotting it for us?

**Comment by mcada** [comment]
There is no error message in console, no network activity. Just the error from the screenshot above.

**Comment by riccardo-forina** [comment]
Right, ok then. I could reproduce it and it's the BE returning an error 401 when using invalid credentials. The notification is about the UI not able the read the response object - since it's empty of course.

I don't think we should fix the notification message tho, it would probably make more sense to disable the button since we can't continue with the process. @syndesisio/uxd 	any suggestion about how to better handle this? Just disabling the button isn't probably enough, we should also say why it's disabled? How?

**Comment by zregvart** [comment]
Kinda relates to #2827

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11447**
