### ISSUE TITLE
[datamapper] data mapper is not loaded correctly on chrome

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#6051]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
I have seen similar issues raised but they were all solved by something else yet this issue is still present on chrome browser:

![screenshot_20190703_104702](https://user-images.githubusercontent.com/14313995/60577593-e92da180-9d7f-11e9-8500-b6cb67a2e3e6.png)

The integration is: Database (select * from contact) -> mapper -> Todo connection (create task)

Todo connection was taken from [here](https://raw.githubusercontent.com/syndesisio/syndesis-qe/master/ui-tests/src/test/resources/swagger/connectors/todo.swagger.yaml) and created via customizations -> upload swagger specification.

This issue is blocking some of QE automated tests.

**Comment by mcada** [comment]
Ok so I just tried it with database(select) -> mapper -> database(insert) and the issue is present, no todo connection required.

**Comment by heiko-braun** [comment]
@riccardo-forina @igarashitm Mind to take a look? I remeber there was an AtlasMap version update yesterday I think ...

**Comment by riccardo-forina** [comment]
> Ok so I just tried it with database(select) -> mapper -> database(insert) and the issue is present, no todo connection required.

What was your `insert` query?

**Comment by riccardo-forina** [comment]
So with `atlasmap-data-mapper` v.1.4.0 this works for me. I'm updating the deps now.

```
yarn why @atlasmap/atlasmap-data-mapper 
yarn why v1.17.0
[1/4] 🤔  Why do we have the module "@atlasmap/atlasmap-data-mapper"...?
[2/4] 🚚  Initialising dependency graph...
warning Resolution field "@patternfly/patternfly@2.6.6" is incompatible with requested version "@patternfly/patternfly@1.0.250"
warning Resolution field "@patternfly/patternfly@2.6.6" is incompatible with requested version "@patternfly/patternfly@^2.8.1"
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@syndesis/atlasmap-assembly#@atlasmap/atlasmap-data-mapper@1.40.0"
info Reasons this module exists
   - "_project_#@syndesis#atlasmap-assembly" depends on it

```

**Comment by riccardo-forina** [comment]
Uhm it looks like that's the latest version @heiko-braun

**Comment by riccardo-forina** [comment]
Here's what I see creating an integration using the Todo connector.
![image](https://user-images.githubusercontent.com/966316/60583810-fa7cab00-9d8b-11e9-99a0-2647da39f270.png)

**Comment by mcada** [comment]
Not the best recording but the issue is visible.
As the input query you can just use `insert into contact values(:#ASDF)`

![out](https://user-images.githubusercontent.com/14313995/60584746-4e888f00-9d8e-11e9-86cf-18e399e75234.gif)

**Comment by riccardo-forina** [comment]
Thanks, I tried again and I can't reproduce it. Tried locally and on staging. Can you check if the iframe where atlasmap is embedded is taking the full height?

**Comment by mcada** [comment]
![screenshot_20190703_125002](https://user-images.githubusercontent.com/14313995/60585893-16cf1680-9d91-11e9-9afc-8b64a0b816ce.png)

**Comment by riccardo-forina** [comment]
I just tried with the branch `1.7.x` and it's working fine for me. Can I ask you to check something else on the rendered html? The wrapper around the iframe and the iframe itself should look something like this:

```html
<section class="pf-c-page__main-section pf-m-no-padding" style="overflow: hidden;"><iframe name="atlasmap-frame" srcdoc="<!doctype html>
<html lang=&quot;en&quot;>
<head>
  <meta charset=&quot;utf-8&quot;>
  <title>Atlasmap</title>
  <base href=&quot;/dm&quot;>

  <meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;>
  <link rel=&quot;icon&quot; type=&quot;image/x-icon&quot; href=&quot;favicon.ico&quot;>
</head>
<body style=&quot;background: transparent;&quot;>
  <app-root></app-root>
  <script type=&quot;text/javascript&quot; src=&quot;/atlasmap-runtime.js&quot;></script>
  <script type=&quot;text/javascript&quot; src=&quot;/atlasmap-polyfills.js&quot;></script>
  <script type=&quot;text/javascript&quot; src=&quot;/atlasmap-styles.js&quot;></script>
  <script type=&quot;text/javascript&quot; src=&quot;/atlasmap-scripts.js&quot;></script>
  <script type=&quot;text/javascript&quot; src=&quot;/atlasmap-vendor.js&quot;></script>
  <script type=&quot;text/javascript&quot; src=&quot;/atlasmap-main.js&quot;></script></body>
</html>

" frameborder="0" allowtransparency="" style="width: 100%; height: 100%; line-height: 0;"></iframe></section>
```

The important bits are the two inline styles applied to the section and iframe elements.

If that looks ok, the next step would be to check the nodes above the section one. The expected styling should be something like this:

![layout-debug](https://user-images.githubusercontent.com/966316/60586857-43842d80-9d93-11e9-9349-d631eb1d0061.gif)

**Comment by mcada** [comment]
Ok so I found out that I did not have the latest-stable chrome version. When I updated it works. Do we still want to investigate why it is not rendered correctly on older version or should I close the issue?

**Comment by heiko-braun** [comment]
It might not related to the version, but the fact that a new installation wiped some cached data or settings.

**Comment by mcada** [comment]
Probably not, I tried cleaning everything and private window - the issue was always present.

**Comment by heiko-braun** [comment]
@mcada based on your latest comment I would suggest we lower the priority?

**Comment by heiko-braun** [comment]
Migrated to https://issues.jboss.org/browse/ENTESB-11446
