### ISSUE TITLE
Datamapper - it's possible to map only 1 item from source

### ISSUE THREAD

**Issue by mastepan** [syndesisio/syndesis#6053]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Let's have an integration 
DB -> Datamapper -> FHIR
(I haven't checked on other integrations)
I want to create 2 mappings from DB to FHIR create.

1. 1st mapping can be done normally.
2. 2nd mapping throws error when selecting item on target side
3. Only 1st mapping been saved when exiting datamapper.
 
EDIT: replaced by correct image
![datamapper37](https://user-images.githubusercontent.com/8707251/60582378-f8651d00-9d88-11e9-9322-673c8e98d3e6.png)

**Comment by heiko-braun** [comment]
@mastepan What version are you testing?

**Comment by heiko-braun** [comment]
@igarashitm Can you take a look at this?

**Comment by heiko-braun** [comment]
@mastepan Looking at the picture it seems you try to map the same source attribute twice?

**Comment by mastepan** [comment]
> @mastepan Looking at the picture it seems you try to map the same source attribute twice?

No, the picture is wrong. Thanks for noticing that.
Testing on 1.7.8 version

**Comment by igarashitm** [comment]
Where can I see the behavior? Is the FHIR connector available on staging?
I haven't ever seen this, it seems like `tns:name<>/tns:family/@value` and `tns:name<>/tns:given/@value` is unexpectedly recognized as a same field, but it doesn't happen with our test documents.
Just a random guess, is there a array/list parent other than `tns:name<>`? if so, nested collection is not supported (atlasmap/atlasmap#435)

**Comment by igarashitm** [comment]
Ah OK it's an AtlasMap bug. if the terminal field name is same, it's recognized as a same field by mistake. Is this p0 by the way? ATM it's only FHIR connector having same name fields like `@value`.

**Comment by heiko-braun** [comment]
@mastepan based on https://github.com/syndesisio/syndesis/issues/6053#issuecomment-508084652, do you think we can lower it to `p1`?

**Comment by igarashitm** [comment]
Filed an issue at AtlasMap - #1078 - I'll fix it for upstream anyway, ping me if we should backport.

**Comment by mastepan** [comment]
> @mastepan based on [#6053 (comment)](https://github.com/syndesisio/syndesis/issues/6053#issuecomment-508084652), do you think we can lower it to `p1`?
If we support FHIR connector then I think this is P0. That also broke FHIR tests

**Comment by heiko-braun** [comment]
@igarashitm based on @mastepan's feedback, please prepare the fix.

**Comment by igarashitm** [comment]
Looking at it - now regression risk looks medium, turned out it affects several public methods.

**Comment by igarashitm** [comment]
Changed my mind. Now I think we should go with a small fix, which basically disables "no multiple mappings to same target" check. Then the mapping behavior depends on runtime (first wins), but it's better than this behavior. We'll have to revisit the same target check separately.

**Comment by mmelko** [comment]
@igarashitm thanks for the fix! Just for the record I hit this also in google-sheets tests. Workaround is to create mapping "backwards" (target-source).
