### ISSUE TITLE
Data tab needs a Tech Preview label

### ISSUE THREAD

**Issue by asmigala** [syndesisio/syndesis#6055]
See also **https://issues.jboss.org/browse/ENTESB-11445**

## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
The Data Virtualization part of Syndesis is Tech Preview in this release, but this is not reflected anywhere in the UI. I suggest a Tech Preview badge on the menu item itself, or in the Data Virtualization page header:

![dv-tp](https://user-images.githubusercontent.com/9480152/60596802-02e3de80-9daa-11e9-9c8a-2ad7383dbaaa.png)

**Comment by heiko-braun** [comment]
@amysueg @dongniwang Can we get a UX suggestion for this? We need need it quickly ...

**Comment by amysueg** [comment]
Design: https://docs.google.com/presentation/d/1Khs8lJV9X3Hm80rOjcMBuytxYGpMFTMNB9huMLjSdOQ/edit#slide=id.g5ba6289e41_0_244 
@lboehling @dongniwang @seanforyou23 Thoughts?

**Comment by gashcrumb** [comment]
I think the second option with the box around it sticks out more which is kinda what we want.  With just the text I find it kinda blends in with the page title and I don't really "see" it as readily.

**Comment by amysueg** [comment]
I agree @gashcrumb 
Let's go ahead with this approach @mcoker 
We can always tweak if necessary but at least we'll have a way to call out that the feature is Tech Preview.

**Comment by mcoker** [comment]
@gashcrumb I'm not sure how to add it to `i18nTitle` on `<SimplePageHeader>`, or if that is the best approach, and I can't seem to get any data to load on my local environment.

The markup I used for that was below, where the BEM block name `virtualizations-page` in `.virtualizations-page__tech-preview` should just represent the component this is added to. This could go inside of the page header `<h1 class="pf-c-title pf-m-2xl">...</h1>`

```
<span class="virtualizations-page__tech-preview" style="
    font-size: 14px;
    margin-left: 16px;
    border: 1px solid black;
    padding: 3px 4px;
">Technical Preview <i class="pficon pficon-info"></i></span>
```

Also the screenshot in the deck and the code above aligns the TP text with the heading text, which means the bottom border of the TP text extends below the heading text.

<img width="951" alt="Screen Shot 2019-07-05 at 1 03 50 PM" src="https://user-images.githubusercontent.com/35148959/60738849-5a5a8980-9f25-11e9-8658-405747c4aa81.png">

Here's what it would look like if we applied `display: flex; align-items: center;` to the `<h1>` that wraps the heading and TP text.

<img width="1036" alt="Screen Shot 2019-07-05 at 1 05 56 PM" src="https://user-images.githubusercontent.com/35148959/60738944-a4436f80-9f25-11e9-9c76-4e85914a942b.png">

Do you want to make this update, or could you give me a pointer on how to make this update? FWIW, my local server doesn't have any data either. I get the "Something is wrong" empty state display with error `Error: Failed to fetch` for integrations, connections, etc.

@amysueg do you have a preference in how that displays?

**Comment by amysueg** [comment]
@mcoker Great work. I prefer the second screenshot, looks better aligned to my eye. Thank you!

**Comment by heiko-braun** [comment]
@mcoker Can you get this into master today?

**Comment by riccardo-forina** [comment]
@mcoker I think one option would be to add a flag `isTechPreview` to the `SimpleHeader` and change its JSX so to render what you need to be rendered when set.

**Comment by mcoker** [comment]
@riccardo-forina thanks! I'll give that a shot.

**Comment by heiko-braun** [comment]
@mcoker any update oin this?

**Comment by mcoker** [comment]
@heiko-braun I submitted a PR yesterday but the build was failing. Looks like there was a fix pushed to fix the build, so I rebased and it's rebuilding now. Hopefully we can merge this when the build finishes. https://github.com/syndesisio/syndesis/pull/6091

**Comment by heiko-braun** [comment]
thanks, I didn't notice that.

**Comment by mcoker** [comment]
@heiko-braun the build passed, just needs to be merged https://github.com/syndesisio/syndesis/pull/6091

**Comment by asmigala** [comment]
The Technology Preview badge only shows up when Data Virtualization is enabled in the `syndesis-ui-config` config map:

![2019-07-16-124755_sel_grim.png](https://images.zenhubusercontent.com/5bbdf3e7bad45f05fe8baab0/2b903ded-7eb3-4007-822a-0200ef55f802)

It does not show up when Data Virtualization is disabled (which is the default on a newly installed syndesis):
![2019-07-16-124823_sel_grim.png](https://images.zenhubusercontent.com/5bbdf3e7bad45f05fe8baab0/330b3b0c-0f94-4335-b3d5-88d3751a768b)

**Comment by heiko-braun** [comment]
> It does not show up when Data Virtualization is disabled 

This does no harm. I am lowering the prio on this one.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11445**
