### ISSUE TITLE
Validate reconnecting Twitter OAuth connection shows "Could not authenticate you."

### ISSUE THREAD

**Issue by mkralik3** [syndesisio/syndesis#6057]
See also **https://issues.jboss.org/browse/ENTESB-11405**

## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Validation Twitter connection shows "Could not authenticate you." after reconnecting (due to new Consumer API keys.). When I refresh the page, the validation is successful. 

![output](https://user-images.githubusercontent.com/16251792/60598589-40963680-9dad-11e9-97db-eb5de732ddfe.gif)

**Step to reproduce:**
- Go to the Settings -> Twitter and fill in Consumer API Key and Consumer API Secret Key.
- Go to the Connections -> Create Connection -> Twitter -> Click on Connect Twitter and fill in user name and password
- Go to the https://developer.twitter.com/en/apps/ and regenerate _Consumer API keys_
- Go to the Settings -> Twitter and update values to the newly generated keys and click on Save
- Go to the Connections -> Twitter and click on Reconnect
- Click on Validate button. The dialog "Could not authenticate you" is shown.
![image](https://user-images.githubusercontent.com/16251792/60596019-6a009380-9da8-11e9-8fb6-0975d0572a57.png)
- Refresh the page and click on Validation button again.
![image](https://user-images.githubusercontent.com/16251792/60596041-784eaf80-9da8-11e9-9712-81f0db83b408.png)

Described also in #5763

**Comment by claudio4j** [comment]
@mkralik3 can you confirm if this problem occurs ? I couldn't reproduce.

![twitter_keys_oauth](https://user-images.githubusercontent.com/836543/63179107-cb5f8780-c021-11e9-8210-6c20ba518835.gif)

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11405**
