### ISSUE TITLE
Allow editing of OpenAPI connector definition

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#6063]
See also **https://issues.jboss.org/browse/ENTESB-11463**

## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Since Apicurio is already used in Syndesis, it would make sense to allow editing of custom connector definitions. Currently it is possible only to edit the host route and base path. 
Right now if user needs to change something that they noticed after publishing an integration, they need to delete the integration, delete the connection and definition; then they can upload the specification again and edit it.

I am sure there is going to be a problem of what are we allowed to modify when the specification is used by a connection that's used in a running (maybe even stopped) integration.
I would propose: 
- allow to edit only when the connector is not used in any integration
- (better option) duplicate the definition and edit that duplicate, with it user can create a new connection to replace the old one and doesn't loose the integrations they created

**Comment by zregvart** [comment]
cc @gaughan

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11463**
