### ISSUE TITLE
Add go to operation list to API provider

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#6067]
See also **https://issues.jboss.org/browse/ENTESB-11404**

## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Probably during the port to react-ui the "Go to operation list" button got forgotten. This was probably not intended, in our testsuite it was used to test the autosaving feature (that I can say works), but now the only way to access the operation list is by clicking the integration name in breadcrumbs or saving the integration (which means 2 button clicks each time I want go to another operation).

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11404**
