### ISSUE TITLE
[Conditional Flow] Configuration required warning in working integration

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#6068]
See also **https://issues.jboss.org/browse/ENTESB-11403**

## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Fresh integration with conditional flow has `Configuration required` warning even though the integration works:

Picture 1: Integrations list
![screenshot_20190704_133751](https://user-images.githubusercontent.com/14313995/60664018-21f17780-9e61-11e9-8da3-a30b72fe0927.png)

Picture 2: Integration detail
![screenshot_20190704_133737](https://user-images.githubusercontent.com/14313995/60664028-29188580-9e61-11e9-83d9-797753753f8f.png)

Picture 3: Warning
![screenshot_20190704_133745](https://user-images.githubusercontent.com/14313995/60664036-2c137600-9e61-11e9-917f-8d779efeb0d5.png)

Picture 4: Edit integration
![screenshot_20190704_134029](https://user-images.githubusercontent.com/14313995/60664096-4e0cf880-9e61-11e9-9f91-f43fa0ae4b36.png)

Picture 5: One conditional flow of the integration
![screenshot_20190704_134051](https://user-images.githubusercontent.com/14313995/60664121-5c5b1480-9e61-11e9-9654-3fc3f1137884.png)

**Comment by mcada** [comment]
Publishing the integration again without any change resolves the issue and the warning is gone.

**Comment by heiko-braun** [comment]
@mcada Why do you think this is blocking?

**Comment by mcada** [comment]
I think this should be fixed in this release.

**Comment by heiko-braun** [comment]
@mcada I understand you point if view, but a warning that doesn't impact the functionality doesn't justify a `p1` from my point if view. 

@gaughan What do you think?

**Comment by gaughan** [comment]
Conditional flow is tech preview in 7.4 I think we can set to a P1, I agree it is pretty ugly

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11403**
