### ISSUE TITLE
Add support for any data source with valid JDBC Driver

### ISSUE THREAD

**Issue by rareddy** [syndesisio/syndesis#6077]
## This is a feature request.

<pre><code>
[X ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
If a user needs to use any other database other than Derby, Postgresql, Oracle, MySQL, the recommendation is to add an "import extension" of the JDBC driver, then use that driver in creating the connection to the source. However, only above-mentioned drivers will work, any others will simply fail. For example, see #5978 Looks like this is similar to #1291 but the issue still exists.

There should be a mechanism to allow any JDBC driver and use its connection based on it in an Integration or Data Virtualization. It would be even helpful if there is a "generic" way the 'import extension mechanism" be extended to allow the JDBC drivers directly instead of forcing the user to build a uber import extension jar, even better to allow a maven repo co-ordinates directly rather than user supplying a physical jar.

**Comment by rareddy** [comment]
@KurtStam FYI, based on the conversation earlier in the week.

**Comment by heiko-braun** [comment]
@rareddy Does this relate to an ENTESB?

**Comment by rareddy** [comment]
No, this is bug on Syndesis, that also would enable data source on DV side. There will be follow on task on DV as https://issues.jboss.org/browse/ENTESB-10900
