### ISSUE TITLE
Stuck validation with Receive Email and Send Email

### ISSUE THREAD

**Issue by jsafarik** [syndesisio/syndesis#6085]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

While validating https://github.com/syndesisio/syndesis/issues/5560, when everything is filled correctly, the validation goes as supposed. But when I try to set `Security Method` to something that's not correct (for example leaving it on `None` when the server and port uses `SSL/TLS`) and click on Validate, the validation just keeps going and never ends (there's no error message or anything). 

While the validation is stuck, a change in the fields is useless since when I try to change the `Security Method` to the right one, the validation is still stuck, leaving me with no other option then to cancel the creation of a connector and start it all over again.

In the meta pod log, there is
```
2019-07-08 07:56:31.266  INFO 1 --- [  XNIO-3 task-6] i.s.c.s.verifier.api.ComponentVerifier   : Verify (PARAMETERS): email === OK
--
  | 2019-07-08 07:57:01.370  INFO 1 --- [  XNIO-3 task-6] i.s.c.s.verifier.api.ComponentVerifier   : Verify (CONNECTIVITY): email === ERROR
  | 2019-07-08 07:57:01.375 ERROR 1 --- [  XNIO-3 task-6] i.s.c.s.verifier.api.ComponentVerifier   : email -->
  | 2019-07-08 07:57:01.375 ERROR 1 --- [  XNIO-3 task-6] i.s.c.s.verifier.api.ComponentVerifier   :    AUTHENTICATION : Exception reading response
```

so this issue seems to be related only to the UI since the meta pod is aware of the error.

**Comment by claudio4j** [comment]
As #6104 is merged, can this issue be closed ?

**Comment by phantomjinx** [comment]
@claudio4j 
It was brought up by QE so needs to be signed-off by them, first. Moving it to done.

**Comment by jsafarik** [comment]
Just tried to verify this with 1.7.10 and still having the same behavior as reported. Console in developer tools shows `Failed to load resource: the server responded with a status of 504 (Gateway Time-out)` and `Uncaught (in promise) Error: Gateway Time-out` and the validation button still keeps spinning, so again, only way to change parameters to the right ones is to cancel the creation and start it all again.

**Comment by phantomjinx** [comment]
@zregvart 
This has been fixed on master with https://github.com/syndesisio/syndesis/pull/6104. I have confirmed it also fixes the problem on 1.7.x branch too.

Can you advise on the procedure for backporting it, if applicable, please?

**Comment by zregvart** [comment]
@phantomjinx first we need to consider this a blocking (`p0`) issue to get it backported to `1.7.x`. Other than that it should be as simple as applying the `backport 1.7.x` label to #6104.

**Comment by heiko-braun** [comment]
@phantomjinx It's not `p0` and hence does not needed, in fact is not allowed, to be backported at this point. We want to keep the changes on `1.7.x` to a minimum to prevent further side effects late in the cycle.

**Comment by phantomjinx** [comment]
@heiko-braun 
That's fine & why I wanted to check.

@jsafarik
Presumably, you'll need to make a note that its an issue in 1.7.x but already fixed in a later version.

Moving to Done.

**Comment by tplevko** [comment]
@heiko-braun should we notify docs team to include this in the release notes as a known limitation?
