### ISSUE TITLE
[Conditional Flow] Highlight currently selected flow in dropdown

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#6086]
See also **https://issues.jboss.org/browse/ENTESB-11462**

## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Highlight currently selected flow - this will resolve the issue when two conditions are the same or when user has multiple default flows. On the following screenshot I am editing default flow. But which one?

![screenshot_20190708_124925](https://user-images.githubusercontent.com/14313995/60804932-05b24b00-a17f-11e9-82b7-8196d6b64ce8.png)

![screenshot_20190708_124932](https://user-images.githubusercontent.com/14313995/60804935-0945d200-a17f-11e9-9076-cb221dff6015.png)

**Comment by christophd** [comment]
@dongniwang can you please have a look from UX perspective how to solve this?

**Comment by dongniwang** [comment]
Would something like this solve the problem? 

![Screen Shot 2019-08-23 at 10 59 25 AM](https://user-images.githubusercontent.com/24943812/63602307-1e42bd00-c595-11e9-8676-968b2ac5695f.png)

**Comment by mcada** [comment]
I would prefer some kind of a border for selected item or different background of the item, but this also works.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11462**
