### ISSUE TITLE
Conditional Flow Enhancements

### ISSUE THREAD

**Issue by christophd** [syndesisio/syndesis#6093]
See also **https://issues.jboss.org/browse/ENTESB-11494**

This epic collects a set of findings and missing features to bring conditional flows feature from tech preview to GA.

Agreed list of features not in scope:
- Nesting conditional flows
- Building conditions from multiple rules (with and/or)
- Reusing/sharing flows between integrations

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11494**
