### ISSUE TITLE
[Conditional flow] Missing tech preview label

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#6096]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Since conditional flow is tech preview for current release we should add `Technical preview` label to it.

![screenshot_20190709_102019](https://user-images.githubusercontent.com/14313995/60871492-29cf6400-a233-11e9-8caa-f008f95e1722.png)

**Comment by heiko-braun** [comment]
@mcoker This seems to be similar to the other items your work on. Can you tackle this as well?
