### ISSUE TITLE
API Provider definition without any paths or operations leads to blank screen

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#6102]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When creating an API provider from scratch, it is possible to click on Save without adding any paths or operations. Which leads to an error in the dev console and a blank screen, where the user has to modify the URL to get back to Syndesis.

![Peek 2019-07-09 13-56](https://user-images.githubusercontent.com/46345469/60886235-bc7efb80-a251-11e9-9bfd-15af486e97c9.gif)

Console stacktrace: 
TypeError: "c.integration.flows is undefined"
    oo OperationsPage.tsx:121
    React 11
    r history.js:153
    notifyListeners history.js:171
    notifyListeners history.js:170
    f history.js:291
    push history.js:379
    confirmTransitionTo history.js:140
    push history.js:353
    e ReviewActionsPage.tsx:68
    s runtime.js:45
    _invoke runtime.js:264
    t runtime.js:98
    r asyncToGenerator.js:3
    c asyncToGenerator.js:25
react-dom.production.min.js:4408

**Comment by zregvart** [comment]
I think this would be resolved when we fix #6101.

**Comment by asmigala** [comment]
Still needs QE verification, reopened

**Comment by mmuzikar** [comment]
Verified by QE.
