### ISSUE TITLE
Empty flow in API Provider doesn't save

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#6109]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
It is possible to create an empty flow in API Provider, but without any modification of the default provided start and end steps, after saving it, it seems like no flow was created. So either it shouldn't be possible to create such flow, or it should be saved.

Also if the operation has response type set, the finish step doesn't report that there is no data supplied.
![image](https://user-images.githubusercontent.com/46345469/60949503-a0cd3100-a2f5-11e9-8281-9d6eb55f7a76.png)

![Peek 2019-07-10 09-33](https://user-images.githubusercontent.com/46345469/60949650-eb4ead80-a2f5-11e9-891b-c0be0ebbcaf4.gif)

**Comment by heiko-braun** [comment]
@riccardo-forina Would you mind to take a first look? Is it a UI thing or BE?

**Comment by riccardo-forina** [comment]
I'm not sure I'm following. An operation is considered implemented if the flow's metadata contains a key `return-code-edited` set to `true`. If you import a new OpenApi definition and do nothing, all the flows will be listed as not implemented, so the button will say "Create flow".

Under the hood, if the integration is published the operations "not created" will still be available and return a `501 not implemented` error.

**Comment by riccardo-forina** [comment]
> Also if the operation has response type set, the finish step doesn't report that there is no data supplied.

Sorry, what do you mean? What's happening and what should happen instead?

**Comment by mmuzikar** [comment]
My question is should the behavior from the GIF be happening? I clearly clicked on Save and the flow wasn't saved. In my point of view that flow should return 200 and empty String.

What's happening is that I am expecting 200 and empty string to be returned. What I get is 500 and no response.

**Comment by riccardo-forina** [comment]
I think it's correct, operations that have not been touched are left untouched, operations that have been edited see their return code automatically set to 200 (if left to the default 501).

CC @nicolaferraro since this logic predates me, and I might have missed some case when porting the logic over to the new UI.

**Comment by mmuzikar** [comment]
Oh I see, so I only have to change the return code manually to save the flow. Issue fixed for me, @nicolaferraro if you feel that this should change feel free to reopen :)
