### ISSUE TITLE
Tagged operations aren't displayed in API Provider

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#6110]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Before migration to react, the operations tagged in API Provider were displayed in the "Review Actions" page. Now there isn't even a section where those operations should be displayed, was this functionality dropped or did you forget to display it?
![image](https://user-images.githubusercontent.com/46345469/60950088-c9a1f600-a2f6-11e9-8359-8ad0aa962322.png)
![image](https://user-images.githubusercontent.com/46345469/60950106-d0c90400-a2f6-11e9-96c7-30d4e9eac6cf.png)

**Comment by zregvart** [comment]
I think we forgot to display the tags. Let's call it an experiment and see if anyone misses it :)

**Comment by mmuzikar** [comment]
@zregvart our tests are first (and maybe last) that missed it :smiley:
