### ISSUE TITLE
Selecting OAuth scheme in API Connector breaks the UI after saving

### ISSUE THREAD

**Issue by asmigala** [syndesisio/syndesis#6123]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When adding an API Connector and selecting OAuth security in Apicurito, trying to save the connector will result in completely blank page and error in the console (see below)

## Steps to reproduce
1. Customizations > API Client Connectors > Create API Connector
2. upload https://github.com/syndesisio/syndesis-qe/blob/master/ui-tests/src/test/resources/swagger/connectors/invalid/kie-server-swagger.json
3. click Review/Edit
4. add OAuth 2 security schema, select password flow, save
5. add security requirement, select the one created in previous step, save
6. click Save on the Apicurio page
7. click Next on the Review Actions page
8. blank page shows

The following is logged in the console:

```
TypeError: "this.props.authenticationTypes is undefined"
    render ui.js:3556
    React 9
react-dom.production.min.js:4408
TypeError: this.props.authenticationTypes is undefined
ui.js:3556
TypeError: "this.props.authenticationTypes is undefined"
    render ui.js:3556
    React 9
react-dom.production.min.js:4408
The connection to wss://syndesis.my-minishift.syndesis.io/api/v1/event/streams.ws/648af59e-083b-4845-92df-f221103014a4 was interrupted while the page was loading.
```

**Comment by heiko-braun** [comment]
@riccardo-forina Mind a first pass review to assess the situation?

**Comment by riccardo-forina** [comment]
So it looks like the BE doesn't return an array of valid auth methods for the UI to render. This is the response object that I get doing what @asmigala 	did:
![image](https://user-images.githubusercontent.com/966316/60988149-54a8dd80-a343-11e9-916d-62caf01ac297.png)
We are missing the `enum` property.

This is what we should be getting:
![image](https://user-images.githubusercontent.com/966316/60988239-75713300-a343-11e9-9b37-46e457c2b19e.png)

**Comment by gaughan** [comment]
Is this in 7.4 now? can we close this issue?

**Comment by zregvart** [comment]
> Is this in 7.4 now? can we close this issue?

Needs to be verified by QE, if its all kosher then QE closes the issue. I'm sure it's in their pipeline.

**Comment by asmigala** [comment]
The connector now shows as having "No Security" when oauth2 is selected

![image](https://user-images.githubusercontent.com/9480152/61521545-b981c900-aa10-11e9-977a-47f7f46faf4a.png)


![image](https://user-images.githubusercontent.com/9480152/61521719-2301d780-aa11-11e9-934b-06a117d402bb.png)

**Comment by asmigala** [comment]
@zregvart do you want me to reopen this one or file a new issue?

**Comment by zregvart** [comment]
This works as expected, we offer only the OAuth flows that we can support, filtering out the ones that we can't support, if that leaves no options the only option is `No Security`.

**Comment by asmigala** [comment]
The UI is no longer broken after saving the change in apicurio, closing
