### ISSUE TITLE
Flaky syndesis installation

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#6126]
## This is a...

<pre><code>
[ ] Feature request
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
I'm trying to reinstall syndesis and the installation process is hanging for a very long time with frequent pods re-creation without a clear explanation about what's wrong.

The command I executed is:

```
syndesis minishift --install --local
```

I see some errors like:

```
syndesis-operator-1-rgrcp syndesis-operator {"level":"error","ts":1562775428.7228918,"logger":"controller","msg":"Error reconciling","action":"*action.installAction","phase":"Installing","error":"roles.rbac.authorization.k8s.io \"syndesis-editor\" is forbidden: attempt to grant extra privileges: }
syndesis-operator-1-rgrcp syndesis-operator Failed to create or replace resource:
syndesis-operator-1-rgrcp syndesis-operator apiVersion: rbac.authorization.k8s.io/v1

```

in the operator logs but that's all.

After a long time, pods are finally up and running so I decided to update the platform with my local changes with the following command:

```
syndesis build --clean --flash -- dependencies --module meta,server --image
```

Just after this command, my pods get deleted and recreated with the operator reporting the same error as above, and after the restart of the syndesis server the following error appeared in syndesis server's logs:

```
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://kubernetes.default.svc/api/v1/namespaces/myproject/pods?labelSelector=syndesis.io/component%3Dintegration. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. pods is forbidden: User "system:serviceaccount:myproject:syndesis-server" cannot list pods in the namespace "myproject": no RBAC policy matched.
```

Please note that this restart is not because of a new image being pushed from my local branch. After some time, I got my new image published and syndesis server up and running but it did not last so long as it got killed bcause:

```
Readiness probe failed: Get http://172.17.0.9:8181/health: dial tcp 172.17.0.9:8181: connect: connection refused
```

Then I restarted minishift giving a little bit more CPU and Memory and once up, my pods started to get recreated now and then.

**Comment by lburgazzoli** [comment]
![syndesis-flaky-install](https://user-images.githubusercontent.com/1868933/60991415-c6d0f080-a34a-11e9-9e21-4a2aa2f2f4b4.gif)

**Comment by lburgazzoli** [comment]
Every now and then, syndesis server fails to connect to the database:

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jsonDB' defined in class path resource [io/syndesis/server/runtime/DataStoreConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.syndesis.server.jsondb.impl.SqlJsonDB]: Factory method 'jsonDB' threw exception; nested exception is org.skife.jdbi.v2.exceptions.UnableToObtainConnectionException: org.postgresql.util.PSQLException: The connection attempt failed
```

**Comment by zregvart** [comment]
See [this comment](https://github.com/syndesisio/syndesis/pull/6075#issuecomment-510035002).

**Comment by lburgazzoli** [comment]
Yes saw that, the main problem is that is not so obvious and there are many error that could lead to different "investigation path". 

Unfortunately the command `syndesis minishift --install` just loops indefinitely without reporting any kind of error/warning.
