### ISSUE TITLE
Links to user doc go to 7.3 doc when they should target 7.4 URLs

### ISSUE THREAD

**Issue by TovaCohen** [syndesisio/syndesis#6127]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

I noticed this behavior in the staging site, and Christoph just confirmed that this is the situation in the latest 1.7.x.  

When I click the ? (Help) icon and then click User Guide, I get the 7.3 user guide at this link: 

https://access.redhat.com/documentation/en-us/red_hat_fuse/7.3/html-single/integrating_applications_with_fuse_online/index

I expected the help icon links would now point to 7.4 titles, with links like this: 

https://access.redhat.com/documentation/en-us/red_hat_fuse/7.4/html-single/integrating_applications_with_fuse_online/index

which would display "404 Not Found" until we publish the 7.4 doc. 

I updated the release number in app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json to 7.4: 

 "project": {
        "name": "Syndesis",
        "version": "7.4"

Also in that file, there are user doc links that contain references to $t(project.version)

My update to the shared-translations.en.json file is in this commit:
https://github.com/syndesisio/syndesis/commit/214b64925d99a20c8b26426f784c0f843eded256

So it looks like I did not update the right file. 
What file are the help links coming from?
And just to be clear, there are three links to user doc and they all have the same problem.

**Comment by christophd** [comment]
@riccardo-forina do you happen to know where this should be changed in the UI?

**Comment by riccardo-forina** [comment]
From this point forward there are a few hardcoded urls https://github.com/syndesisio/syndesis/blob/master/app/ui-react/syndesis/src/app/UI.tsx#L231

Ideally they should take the url from the i18n strings as it was in the angular app:
https://github.com/syndesisio/syndesis/blob/master/app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json#L78

**Comment by christophd** [comment]
@heiko-braun how to handle this regarding backport to 1.7.x? I think it is a nasty thing to link to the old documentation and it is a change with low risk. See PR https://github.com/syndesisio/syndesis/pull/6156

**Comment by mmuzikar** [comment]
Verified by QE
