### ISSUE TITLE
UI - Storybook generation leads to OOM issues

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis#6139]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

**Comment by paoloantinori** [comment]
cc @mdrillin

**Comment by paoloantinori** [comment]
@Ted Jones suggested run "export NODE_OPTIONS=--max_old_space_size=4096" before launching. But there may be a better permanent solution for it

**Comment by mdrillin** [comment]
For me, initial launch of storybook worked ok.  But when I make a code change and save, the out of memory occurs on rebuild...
