### ISSUE TITLE
Rename connection showing old name

### ISSUE THREAD

**Issue by phantomjinx** [syndesisio/syndesis#6147]
<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

1. Open existing connection
2. Click rename button & enter the new name
3. Click the tick button

The old name is redisplayed in the box.
Repeating the steps produces an error that a connection with the new name already exists.
Clicking on "connections" shows the rename has taken place and its literally just the 'UI value' in the opened wizard that isn't updated.

**Comment by riccardo-forina** [comment]
@heiko-braun what priority do we want to give to this? The fix is ready, but it's not risk-free since I had to change something quite low-level.

**Comment by phantomjinx** [comment]
@riccardo-forina 
Got there before me - guessed you probably would :-)
thx!

**Comment by mmuzikar** [comment]
Verified by QE
