### ISSUE TITLE
Template Step cannot handle brackets around symbols at runtime

### ISSUE THREAD

**Issue by phantomjinx** [syndesisio/syndesis#6149]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Creating a language template including punctuation around symbols, eg. ({{name}}), ends up throwing an exception:
```
org.apache.camel.spring.boot.CamelSpringBootInitializationException: java.lang.IllegalArgumentException: java.lang.IllegalStateException: io.syndesis.common.model.integration.step.template.TemplateProcessingException: The template is invalid due to the string '({{name}})'
```

This is due to the preProcessor parsing of the template prior to actual processing, failing to scan and separate out such punctuation.

**Comment by mmuzikar** [comment]
Verified by QE
