### ISSUE TITLE
[Conditional flow] Collection input data shape handling

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#6159]
See also **https://issues.jboss.org/browse/ENTESB-11461**

## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
I can not add conditional flow if previous input data shape is a collection. 

To create integration `database -> split -> conditional flow` I have to first create `database -> log` then add split, delete log and add conditional flow. We could automatically add split step in case of adding conditional flow after collection output data shape. 

One of conditional flow feature requirements was that we can add this step anywhere. This is not true atm - we can not add it after a collection unless we first add split step.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11461**
