### ISSUE TITLE
can't create a new entry in todo app in latest syndesis

### ISSUE THREAD

**Issue by jsafarik** [syndesisio/syndesis#6160]
See also **https://issues.jboss.org/browse/ENTESB-11401**

## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

When using latest syndesis (1.8-SNAPSHOT) and try to create a new entry in todo app in its interface
![image](https://user-images.githubusercontent.com/46523434/61213168-8a174780-a704-11e9-83cf-6ccc38ae2597.png)
and hit `add` button, I get message `Warning: pg_insert(): Table 'todo' doesn't exists in /opt/app-root/src/index.php on line 61
Insert failed:`

The same goes for deleting: `Warning: pg_delete(): Table 'todo' doesn't exists in /opt/app-root/src/index.php on line 82
Insert failed:` 

and updating `Warning: pg_update(): Table 'todo' doesn't exists in /opt/app-root/src/index.php on line 65
Insert failed:`

This seems to be just a frontend problem as working with the table in DB works just fine.

**Comment by paoloantinori** [comment]
Hi @zregvart is this a real bug or have just changed the templates and addons to install the additional components?

**Comment by zregvart** [comment]
Kinda belongs to https://github.com/syndesisio/todo-example we fiddled with database schemas in #5528.

Not sure why https://github.com/syndesisio/todo-example/pull/17 didn't fix it though.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11401**
