### ISSUE TITLE
Flow title is missing in API provider

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#6162]
See also **https://issues.jboss.org/browse/ENTESB-11400**

## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
There used to be the operation title displayed when editing the operation flow. 
![image](https://user-images.githubusercontent.com/46345469/61218394-34e23280-a712-11e9-853f-6ed785eaa64f.png)
![image](https://user-images.githubusercontent.com/46345469/61218354-26941680-a712-11e9-998e-28429f44d8e2.png)
How can I know from these two screenshots which operation I am editing?

**Comment by gashcrumb** [comment]
Can you attach (or link to) the swagger file for this?

**Comment by mcada** [comment]
@mmuzikar the title may be gone but the operation `is` specified, check the other GET operation. You have the `GET /{id}` in the breadcrumb:

![screenshot_20190716_094209](https://user-images.githubusercontent.com/14313995/61275354-10d42f00-a7ae-11e9-9457-60fb6021b9c6.png)

@gashcrumb the swagger is [here](https://raw.githubusercontent.com/syndesisio/syndesis-qe/master/ui-tests/src/test/resources/swagger/connectors/todo.swagger.yaml)

**Comment by riccardo-forina** [comment]
As @mcada 	said, the title is in the breadcrumb. It's not the most visible thing in the world, I agree on that.

**Comment by dongniwang** [comment]
Thanks for opening this issue! Let me spend some time to explore ways to make the flow title more visible.

**Comment by heiko-braun** [comment]
Migrated to https://issues.jboss.org/browse/ENTESB-11400
