### ISSUE TITLE
Cannot login to syndesis

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#6168]
## This is a...

<pre><code>
[ ] Feature request
[*] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
After logging in I get the following screen

<img width="573" alt="Screen Shot 2019-07-15 at 4 06 43 PM" src="https://user-images.githubusercontent.com/35576/61245550-c35ab200-a71a-11e9-9130-7e79ae032781.png">

Logging in the auth pod:

```
2019/07/15 20:03:03 provider.go:593: 200 GET https://172.30.0.1/apis/user.openshift.io/v1/users/~ {"kind":"User","apiVersion":"user.openshift.io/v1","metadata":{"name":"developer","selfLink":"/apis/user.openshift.io/v1/users/developer","uid":"d1a4b0d7-a73a-11e9-a4f7-2a297d346f44","resourceVersion":"2230","creationTimestamp":"2019-07-15T19:57:47Z"},"identities":["anypassword:developer"],"groups":["system:authenticated","system:authenticated:oauth"]}
2019/07/15 20:03:03 provider.go:593: 201 POST https://172.30.0.1/apis/authorization.openshift.io/v1/subjectaccessreviews {"kind":"SubjectAccessReviewResponse","apiVersion":"authorization.openshift.io/v1","namespace":"myproject","allowed":true,"reason":"RBAC: allowed by ClusterRoleBinding \"syndesis-extra-permissions\" of ClusterRole \"syndesis-extra-permissions\" to User \"developer\""}
2019/07/15 20:03:03 oauthproxy.go:676: 172.17.0.1:42398 authentication complete Session{developer@cluster.local token:true}
```

fails on both Safari and Chrome. This is on a fresh install using 
bash <(curl -sL https://syndes.is/start)

Also fails in incognito mode. All pods seem happy:

```
NAME                          READY     STATUS      RESTARTS   AGE
syndesis-db-1-qwhqj           2/2       Running     0          22m
syndesis-meta-1-f9nq4         1/1       Running     0          22m
syndesis-oauthproxy-1-bxgvn   1/1       Running     0          22m
syndesis-operator-1-w64jn     1/1       Running     0          23m
syndesis-prometheus-1-fxknp   1/1       Running     0          22m
syndesis-server-1-2mthp       1/1       Running     1          22m
syndesis-ui-1-b9frv           1/1       Running     0          22m
todo-1-4rrkm                  1/1       Running     0          20m
todo-1-build                  0/1       Completed   0          22m
```

**Comment by KurtStam** [comment]
```
Summary
URL: https://syndesis.192.168.42.164.nip.io/config.json
Status: 404 Not Found
Source: Network
Address: 192.168.42.164:443
```

**Comment by claudio4j** [comment]
@zregvart said about changing a deployment config of syndesis-ui, see if it fixes the problem

```
oc patch dc syndesis-ui --type json --patch "[{\"op\": \"replace\",
\"path\": \"/spec/template/spec/containers/0/volumeMounts/0/mountPath\",
\"value\": \"/opt/app-root/src/config\"}]"
```

**Comment by KurtStam** [comment]
@claudio4j yes that does the trick.

**Comment by christophd** [comment]
@zregvart should that patch be part of the upgrade migration scripts for 7.5? See https://github.com/syndesisio/syndesis/tree/0520031d89a270484b4586152bb766506ac67cad/tools/upgrade/migration/resource

**Comment by zregvart** [comment]
> @zregvart should that patch be part of the upgrade migration scripts for 7.5? See [/tools/upgrade/migration/resource@`0520031`](https://github.com/syndesisio/syndesis/tree/0520031d89a270484b4586152bb766506ac67cad/tools/upgrade/migration/resource)

From what I remember, upgrades replace `DeploymentConfig`/`Service`/`Route`s and keep and upgrade in place `ConfigMap`/`Secret`s, that's why I didn't add a migration.

**Comment by heiko-braun** [comment]
Is this `master` only or does it affect `1.7.x` as well?

**Comment by christophd** [comment]
@heiko-braun this is only on master on 1.7.x we are still using the old `config.json` mount path
