### ISSUE TITLE
master doesn't build with a fresh clone and an empty repo

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#6173]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Using `syndesis build -f -c` results in:

![image](https://user-images.githubusercontent.com/351660/61298464-41b36480-a7ac-11e9-8dec-2acc65a0cc00.png)

well, eventually, a fair bit of stuff builds before this.

**Comment by christophd** [comment]
this is related to https://github.com/syndesisio/syndesis/issues/6013

I think we should remove the system-test execution from the syndesis build until this is fixed

**Comment by christophd** [comment]
good news is that you can safely ignore the error as it happens to be the last module built and it does not have any negative effect on the artifacts built

**Comment by gashcrumb** [comment]
yay!

**Comment by paoloantinori** [comment]
Hi @christophd , does your PR fixes the whole problem? can we close this?

**Comment by christophd** [comment]
@paoloantinori yes that fixes the issue. we can move to done

**Comment by christophd** [comment]
or better close and add `ignore/qe` I guess this is not for verification by QE

**Comment by mastepan** [comment]
closing as ignore/qe label added
