### ISSUE TITLE
Missing empty states views in the lists

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#6177]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Since staging is kinda hosed I finally gave up on it and got minishift running.  And found that we're missing empty states for the integration list on the dashboard:
![image](https://user-images.githubusercontent.com/351660/61314075-c3fe5180-a7c9-11e9-96a8-a025cae3087e.png)

And the integration list page:
![image](https://user-images.githubusercontent.com/351660/61314131-e7c19780-a7c9-11e9-81ba-75e9a0a1da9a.png)

And API client connectors:
![image](https://user-images.githubusercontent.com/351660/61314282-57378700-a7ca-11e9-971a-3663ded81bc0.png)

And extensions too:
![image](https://user-images.githubusercontent.com/351660/61314241-396a2200-a7ca-11e9-8a36-64ca0a60b05a.png)

Note, this is on master.  I feel like we had these in place already.  Unless I'm just losing my mind, that's a definite possibility.  This is on a fresh clone, with a fresh install and fresh build.

**Comment by gashcrumb** [comment]
Hopefully this doesn't affect 1.7.x :crying_cat_face:

**Comment by christophd** [comment]
@gashcrumb it looks exactly the same on 1.7.x

**Comment by heiko-braun** [comment]
@gashcrumb What priority would you assign to this?

**Comment by gashcrumb** [comment]
That's like a super-bummer.

I dunno, seems like a p0 to me, this is the first thing a user will see when logging into the console, so it doesn't give the best first impression, you know?

**Comment by gashcrumb** [comment]
if not a p0 then for sure a p1, and we'd have to release note it somehow, like "sorry our console looks a bit broken when you first log in" :laughing:

**Comment by heiko-braun** [comment]
I tend to agree to p0. Do we have an idea what it takes to fix it?

**Comment by gashcrumb** [comment]
I'm looking into it now as I'm not sure yet how we got here.  Mostly to understand what changes had been needed so I don't introduce some other regression.

There's already empty state components in the code base so I'm hoping it shouldn't be a big fix.

**Comment by tplevko** [comment]
works on 1.7.11

**Comment by gashcrumb** [comment]
@tplevko btw is there a test that would catch this, or one we could have in the future?  It'd be good to hit this earlier rather than later :smile:

**Comment by tplevko** [comment]
@gashcrumb this is a bit tricky - our tests which create integrations (API client connectors, extensions) are looking for "create integration" (or equivalent on the other pages) button, which at least in one occurrence is always present in the page. So there is ATM not really a test, that verifies there are two instances of this button in case it's doesn't contain any integration yet. I believe there wouldn't be too much effort for implementing this as automated test however. I can add this as post-GA task. 
And also closing again (as pure-bot reopened again) :)

**Comment by gashcrumb** [comment]
Ok perfect, thanks!  I think it'd be good to watch out for as it's the first thing a new user sees.  Let us know if you need a test ID or classname on the empty state elements.

**Comment by tplevko** [comment]
Sure, this makes sense, so we'll incorporate it to the suite, will check with guys whether there is something needed. Thanks Stan
