### ISSUE TITLE
[Conditional Flow] datashape change is not propagated into condition

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#6186]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
On following gif I have an integration with SQL -> split -> conditional flow -> log. When I change SQL to different operation, the change is not propagated into the datamapper in one condition flow. I tried similar scenario without split step and the issue was still present. Not even an error is shown in data mapper. 
Workaround is to configure main conditional flow, change nothing and click done. Then datamapper shows correct input. 

![out](https://user-images.githubusercontent.com/14313995/61360683-367d3900-a87f-11e9-9228-b618ec34aed4.gif)

**Comment by christophd** [comment]
Yep, you have to revisit the conditional flow configuration page in order to trigger the shape change propagation to all sub-flows. It should be done automatically but I think this is a valid workaround for now as conditional flows is marked as tech preview for 7.4. 

We may consider to lower the prio to p1 for these reasons. @heiko-braun WDYT?

**Comment by christophd** [comment]
I think this one needs to be tackled in the UI, too so adding @gashcrumb 😄

**Comment by gashcrumb** [comment]
Yup, as you say that data shape is only propagated when the conditional flow step is configured.  I agree on it being a p1 too, that's a workaround we can release note.

**Comment by heiko-braun** [comment]
@christophd What is the workaround?

**Comment by christophd** [comment]
@heiko-braun as workaround the user has to open the conditional flows configuration page once more to get this working as expected.

**Comment by heiko-braun** [comment]
I've changed it to `p1` after talking to @gaughan

**Comment by heiko-braun** [comment]
Migrated to https://issues.jboss.org/browse/ENTESB-11398
