### ISSUE TITLE
[Connections] Invalid credentials lead to Something is wrong page

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#6188]
See also **https://issues.jboss.org/browse/ENTESB-11444**

## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Using connection with invalid credentials in integration ends up with `Something is wrong` page

1. Create a connection with incorrect credentials (kafka or slack are easy for reproducing this issue) 
2. Use created connection in an integration

![screenshot_20190717_153940](https://user-images.githubusercontent.com/14313995/61380629-05662e00-a8aa-11e9-935e-049b9d81f8ab.png)

![screenshot_20190717_154411](https://user-images.githubusercontent.com/14313995/61380634-08f9b500-a8aa-11e9-8f55-194d73198884.png)

**Comment by gashcrumb** [comment]
Hey, can you screenshot the network tab and console for this?

**Comment by mcada** [comment]
Nothing in console. 

![screenshot_20190717_160825](https://user-images.githubusercontent.com/14313995/61382474-25e3b780-a8ad-11e9-83b8-e793b0c7033f.png)

**Comment by gashcrumb** [comment]
While this is not really the way the error should surface, it's expected to get an error for a misconfigured connection.  I think this should be a p1.

Also looking at the code I think it'd be a bit of work to show the error as we'd want it per the design, more than I this is appropriate to do at this stage in the release cycle.

**Comment by heiko-braun** [comment]
Changing to `p1` after talking to Gary

**Comment by heiko-braun** [comment]
@gashcrumb Please look into it nevertheless

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11444**
