### ISSUE TITLE
Consider reduction in duplication of data in an integration's json model

### ISSUE THREAD

**Issue by phantomjinx** [syndesisio/syndesis#6203]
When an integration is exported, the following sections are generated:
- connections
- connectors
- integrations

It would appear that the data for a connector is reproduced 3 times, ie.
- The spec of the connector itself (inside connectors)
- Inside the spec of the requisite connection
- Inside the spec of the integration, inside its requisite connection

Need to confirm if this is merely just the export being too granular or whether its a direct reproduction of the jsonDb record. If the latter then maybe need to consider using some kind of referencing to reduce the duplication.

In addition, maybe consider removal of unnecessary items such as icons. These are svgs converted to base64 so end up being a lot of characters (& repeated 3 times).

For an example of an integration (OData -> Log) see
https://gist.github.com/phantomjinx/02bbc6c6cd60542ddf0e1e8775374140

**Comment by chirino** [comment]
Objects which can be treated like binaries should probably stored using the same strategy we use for storing the extension .jar files.

So icons and openapi documents should likely go in there.  And perhaps the spec data for data shapes.

**Comment by zregvart** [comment]
> Objects which can be treated like binaries should probably stored using the same strategy we use for storing the extension .jar files.
> 
> So icons and openapi documents should likely go in there. And perhaps the spec data for data shapes.

This is what we do now, with one exception and that's the OpenAPI specification configured for the rest-swagger Camel component (component property), we don't have a mechanism for fetching component/endpoint properties outside of the `configuredProperties` on the connector, connection or action.

**Comment by phantomjinx** [comment]
Closing as out of date
see #6444
