### ISSUE TITLE
Repetitive prompts for api provider integration name and description

### ISSUE THREAD

**Issue by TovaCohen** [syndesisio/syndesis#6223]
## This is a...

<pre><code>
[ ] Feature request
[ X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

I'm creating a new api provider integration in staging. I uploaded task-api.json. Every time that I edit a flow and save it, the integration Name, Description, page appears: 

![image](https://user-images.githubusercontent.com/25067106/61671768-0981b980-acb7-11e9-99f5-9dc15a8ca68c.png)

I get this page every time that I click Save for an operation flow. Even if I don't make any changes to the flow. 

## Expected behavior

I expect to be prompted for this just once. 

## Tasks involved / Steps to Reproduce

1.
2.
3.
4.

**Comment by gashcrumb** [comment]
One note, you don't actually have to save after editing each flow, though I know that's not exactly clear.

**Comment by TovaCohen** [comment]
Oh I see, I can use the Operation drop down to move from flow to flow for editing. 
No, that's not clear 
But every time I click Save, I should NOT get the option to enter an integration Name and Description, right?

**Comment by gashcrumb** [comment]
yeah, the current page flow is that save does always take you to the name/description page there, it's a change from the old implementation.

**Comment by TovaCohen** [comment]
Okay, thanks. 
I guess it would be pretty involved to change this behavior, but it doesn't seem like the most user-easy approach. Can I change this issue to a feature request?

**Comment by gashcrumb** [comment]
Sure!

Ideally we actually auto-save, then the workflow changes yet again :smiling_imp:

**Comment by TovaCohen** [comment]
In that case, I'll close this. It's working as designed and there's an improvement plan. 
I'm not documenting this. It's clear enough what the user needs to do. 
Please let me know if auto-save gets implemented!
