### ISSUE TITLE
[Upgrade] Upgrade clears the syndesis-pull-secret link from service accounts

### ISSUE THREAD

**Issue by avano** [syndesisio/syndesis#6225]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
I created the `syndesis-pull-secret` secret with my authentication details and deploy 7.3.1. Now when I do the upgrade, what the upgrade pod does is:

```
...
=== * Update resources (upgrade_40_update_resources)
      - ServiceAccount: force update (delete/create)
        * syndesis-default
        * syndesis-integration
        * syndesis-prometheus
        * syndesis-server
...
```
so it deletes the old SAs with linked secret and replaces them with the ones from the template and those do not have the pull secret linked.

We will need to have this script https://github.com/syndesisio/syndesis/blob/1.6.x/tools/upgrade/migration/resource/any/03_ensure_service_account_setup.sh but not as a migration script (those are called before the SAs are re-created) but as part of the `upgrade_40_update_resources` script, after `apply_resources` call: https://github.com/syndesisio/syndesis/blob/d0c9225266b7dda3f4c1df326ed0583f39618f5a/tools/upgrade/steps/upgrade_40_update_resources#L48-L56

**Comment by heiko-braun** [comment]
@nicolaferraro @lgarciaaco Can the two of you look at this?

**Comment by heiko-braun** [comment]
@avano Is there a workaround?

**Comment by avano** [comment]
@heiko-braun I built my own upgrade image and tested the change proposed in the description and I can open a PR with the change

**Comment by nicolaferraro** [comment]
@avano if you already have a fix, please open the PR.
I think the 1.6 migration script should be slightly changed to work on upstream (where we don't have the pull secret), but it should be ok for 1.7.

**Comment by heiko-braun** [comment]
Fixed with https://github.com/syndesisio/syndesis/pull/6233
