### ISSUE TITLE
Tooltip over input field

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#623]
Do we really need tooltips over input fields:

![image](https://user-images.githubusercontent.com/99080/33653439-740b0270-da6d-11e7-8963-252b10df62a3.png)

I mean it stays active as long as I type in the input field which I personally find quite annoying.

**Comment by dongniwang** [comment]
This should be in syntax hint format instead of tooltip if I remember correctly. @sjcox-rh, please provide input.

**Comment by gashcrumb** [comment]
We don't by default nowadays but have the option.
