### ISSUE TITLE
We should add build env check

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#6231]
I'm running `syndesis build -f` to get a quick compile of all my code after. I ran into 2 issues:

- my go was too old for the install/operator
- Building camel-k, ERROR: $GOPATH has to be set for camel-k build

it takes a long time these days to do a quick compile, so I think we should do a quick env check and fail fast.

**Comment by mmuzikar** [comment]
@KurtStam @phantomjinx is there anything that QE should verify?

**Comment by KurtStam** [comment]
I guess not untill we have this env check in place, then you should see if fail fast.

**Comment by phantomjinx** [comment]
@mmuzikar 
If you look at the PR [comment](https://github.com/syndesisio/syndesis/pull/6322#issue-304758847), it details a list of tests I ran against while adding in the env checks. These could be used as a basis for any QE testing. WDYT?

**Comment by mmuzikar** [comment]
I did a basic verification of running the `syndesis build -f` command, and the env checks worked well for me. I am closing this as verified since if there is an error there should be a new issue opened for that anyways.
