### ISSUE TITLE
Wrong label for SQL Query

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#624]
As the input for the SQL connector (action: "Invoke SQL") can be actually any SQL, the label "Query" is misleading

![image](https://user-images.githubusercontent.com/99080/33653554-b55a136a-da6d-11e7-89f5-ad96989bfe36.png)

**Comment by dongniwang** [comment]
Then what's an appropriate label for this field? 

@sjcox-rh @KurtStam @TovaCohen Please provide input.

**Comment by TovaCohen** [comment]
For the "Invoke SQL" action, I think "SQL Command" is a good label for the input field. 
For the "Periodic SQL Invocation" action, the "Query" label is correct because it must be a SELECT statement, which is commonly referred to as a query. I think I have that right :-) Kurt should confirm.

**Comment by rhuss** [comment]
I would call it "SQL Statement" as in the tooltip shown, as the 'command' is typically understood as the keyword (select, insert, update), but here we allow a full statement (e.g. with 'where' clause)

**Comment by TovaCohen** [comment]
Ahh. Of course. That makes sense. Thanks Roland!

**Comment by amysueg** [comment]
Removed notif/uxd label - since @dongniwang commented.
