### ISSUE TITLE
Convert remaining card views from PF3 to PF4

### ISSUE THREAD

**Issue by seanforyou23** [syndesisio/syndesis#6240]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
We still have [PF3 cards](https://patternfly-react.surge.sh/patternfly-3/?knob-Match%20Height=true&selectedKind=patternfly-react%2FCards&selectedStory=Base%20Card&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs) being used in some places within the UI. PF4 cards are already integrated in some places, we just need to finish swapping them out.

## Expected behavior
All the card views should be [PF4 cards](https://pf4.patternfly.org/components/Card/examples/).

## Screenshot
For example, the connection card grid still uses PF3 cards.

<img width="1644" alt="Screen Shot 2019-07-24 at 10 30 56 AM" src="https://user-images.githubusercontent.com/5942899/61802284-31c80000-adfe-11e9-8783-14c784d6125d.png">

A quick search for instances of `card-pf` CSS class finds occurrences in the following components & their associated stylesheets. This is where we're using patternfly 3 core markup/css.

- [ ] ConnectorConfigurationForm
- [ ] SqlClientForm
- [ ] ViewConfigurationForm
- [ ] IntegrationActionSelectorCard
- [ ] ApiProviderSetInfo
- [ ] ChoiceCardHeader
- [ ] DescribeDataShapeForm
- [ ] IntegrationEditorForm
- [ ] IntegrationEditorNothingToConfigure
- [ ] EditorPageCard
- [ ] IntegrationSaveForm

Another quick search for instances of `<Card`, which catches Card, CardGrid, etc. turns up the following occurrences. This is where we're using patternfly 3 react card components.

- [x] StoryWrapper
- [x] ConnectionCard
- [x] ConnectionsGrid
- [x] ConnectionSetupOAuthCard
- [x] ConnectionDetailsOauthCard
- [x] ConnectionDetailsForm
- [x] OpenApiSelectMethod
- [x] OpenApiReviewActions
- [x] AggregatedMetricCard
- [x] IntegrationDetailMetrics
- [x] ImportPageUI
- [x] DvConnectionSkeleton
- [ ] DvConnectionsGridCell
- [ ] DvConnectionsGrid
- [x] DvConnectionCard
- [x] UptimeMetric
- [x] TopIntegrationsCard
- [x] RecentUpdatesCard
- [x] IntegrationBoard
- [x] Dashboard
- [x] ConnectionsMetric
- [x] ExtensionImportReview
- [x] ExtensionImportCard
- [x] ExtensionDetail
- [x] ApiClientConnectorCreateUpload
- [x] ApiClientConnectorCreateSecurity
- [x] ApiConnectorReview
- [x] ApiConnectorDetailsForm
- [x] ApiConnectorDetailCard
- [x] ConnectorAuthorization
- [x] ConnectionSkeleton
- [x] ConnectionsGridCell

**Comment by amysueg** [comment]
FYI @dongniwang @mcoker @lboehling
