### ISSUE TITLE
[Connectors] Database cleanup

### ISSUE THREAD

**Issue by squakez** [syndesisio/syndesis#6251]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

If you remove a connector (or rename it) as soon as you redeploy the server, you will still have it available in your connections list. It would be nice to have a check on server deploy to check if any connector has been deleted and remove it from database accordingly (plus warning or delete any integration bound to those connectors) maintaining synchronization between the descriptors and database.

**Comment by zregvart** [comment]
How does the user delete/rename a connector though?

**Comment by squakez** [comment]
Well, actually it can happen if during an upgrade of version we decide to discontinue some connector, let's pretend that 7.5 will be removed a connector existing in 7.4 for any reason. Since the DB will still hold previous data it will keep showing that connector.

I am not sure how the upgrades are carried on, but I guess that this would be the expected behavior. Maybe more than a feature should I mark as a bug?

**Comment by zregvart** [comment]
In that case we're missing a [migration script](https://github.com/syndesisio/syndesis/tree/master/app/server/runtime/src/main/resources/migrations).
