### ISSUE TITLE
Cannot see datamapper in CR2

### ISSUE THREAD

**Issue by nicolaferraro** [syndesisio/syndesis#6252]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Data mapper height is wrong.

## Screenshot

![Screenshot from 2019-07-25 16-47-42](https://user-images.githubusercontent.com/4151857/61888203-6a053680-af03-11e9-99cb-ed1487906819.png)

## Tasks involved / Steps to Reproduce

1. Go to an instance with 7.4.0 CR2 installed, e.g. : https://fuse-online-74cr2.b6ff.rh-idev.openshiftapps.com/
2. Create an integration from webhook (specify a datashape with a json instance) to database (add_lead)
3. Add a datamapper step
4. You get the screenshot (I've used chrome)

**Comment by nicolaferraro** [comment]
For completeness:
- I'm using a not so updated version of chrome @riccardo-forina : Version 68.0.3440.106 (Official Build) (64-bit)
- It works on Firefox

**Comment by paoloantinori** [comment]
Webhook -> data mapper -> db

works for me on Chromium 7.4 on Linux, see screenshot

![Screenshot from 2019-07-25 18-09-19](https://user-images.githubusercontent.com/1520602/61890246-5bb91980-af07-11e9-8884-01d176df020e.png)

**Comment by igarashitm** [comment]
I saw this in some other Syndesis issue, couldn't find it. @riccardo-forina do you remember? I think QE guy said it has gone once he updated Chrome to newest.

**Comment by igarashitm** [comment]
Here you go, it's still open - #6051

**Comment by gaughan** [comment]
I think we can take this out of P0 now

**Comment by nicolaferraro** [comment]
I confirm it's related to the version of Chrome.
I works on Chrome 75.

![Screenshot from 2019-07-25 21-40-54](https://user-images.githubusercontent.com/4151857/61903575-13a8ef80-af25-11e9-862f-5976d10414aa.png)

I'll close the issue, please reopen it if you think there's something we should do.
