### ISSUE TITLE
Can't start an integration from a Knative channel

### ISSUE THREAD

**Issue by nicolaferraro** [syndesisio/syndesis#6255]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

This affects master and CR2.

Metadata lookup when starting an integration from a Knative channel fails in the second phase (data shape selection) because of a combo of slightly wrong logic in the connector and behavior change in the new react UI wrt hidden connection fields.

Error got is: `Unsupported Knative type: .`

**Comment by mastepan** [comment]
@nicolaferraro just checking. Is there anything that should be checked by QE?
