### ISSUE TITLE
Split step always adapts 1st output data shape

### ISSUE THREAD

**Issue by christophd** [syndesisio/syndesis#6257]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Split step should adapt the output data shape of the previous step relative to its location in a flow. At the moment split always adapts the output data shape of the 1st step in the flow regardless of its position in the flow.

With this in place you can not use split on steps other than the 1st step in a flow.

**Comment by tplevko** [comment]
Verified
