### ISSUE TITLE
Drop legacyui addon

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis#6263]
## This is a...

<pre><code>
[X] Chore
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

**Comment by chirino** [comment]
see: https://github.com/syndesisio/syndesis/pull/6256#discussion_r307703884

**Comment by zregvart** [comment]
cc @syndesisio/ui
