### ISSUE TITLE
Add option to Syndesis CR that enables DEBUG in all pods

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis#6264]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

**Comment by phantomjinx** [comment]
Not necessary for review by QE as JAVA_DEBUG env var only useful for developmental debugging purposes & switched off by default.
