### ISSUE TITLE
Integration list skeleton doesn't appear while the list is loading

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#6268]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
This was kinda introduced while hastily adding back in the empty state for #6177 but now only the empty state shows for the integration list page and on the dashboard:

![Peek 2019-07-29 08-55](https://user-images.githubusercontent.com/351660/62050278-f69f4580-b1de-11e9-8c9c-cb39caa81d15.gif)

**Comment by heiko-braun** [comment]
@dongniwang Any idea how we could indicate the loading state?

**Comment by dongniwang** [comment]
Is this related to https://github.com/syndesisio/syndesis/issues/5989? 

I think the issue is trying to find out why the loading skeleton doesn't show up when loading. And we are using a skeleton pattern to indicate the loading state.
