### ISSUE TITLE
Mail connector consolidation

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/syndesis#6270]
See also **https://issues.jboss.org/browse/ENTESB-11491**

Collect all pending issues (errors and enhancements) to bring the mail connector to GA

**Comment by phantomjinx** [comment]
@heiko-braun 
Can you describe the consolidation envisaged?

**Comment by heiko-braun** [comment]
@phantomjinx I've updated the description. It's mostly consolidation/bug fixes. Please link any known issues here.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11491**
