### ISSUE TITLE
Create API provider from swagger.json produces endless loop

### ISSUE THREAD

**Issue by christophd** [syndesisio/syndesis#6277]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When creating a new integration as API provider using the todo app swagger.json we get into an endless loop in UI. See this screencast how to reproduce:

![Issue_APIProvider_EndlessLoop](https://user-images.githubusercontent.com/195264/62106555-d090a880-b2a5-11e9-8563-17991b5a1098.gif)

That is on latest master.

**Comment by zregvart** [comment]
Can't reproduce this, reopen if it's still an issue.
