### ISSUE TITLE
Reading AWS S3 file content via Red Hat Fuse online

### ISSUE THREAD

**Issue by soundar-git** [syndesisio/syndesis#6279]
The S3 connector while consuming will return an inputStream, an S3ObjectInputStream for completeness.

So if you pass this to a connector which is defined to work with inputStream as input, like for example Dropbox, you won't have problems.  But we need to pass the S3 file content as the body of HTTP request.  

In this case we need to transform the inputStream into a plain String containing your JSON

**Comment by heiko-braun** [comment]
@paoloantinori @oscerd I think this can be done via an extension, do we have some starting points?

**Comment by oscerd** [comment]
I can have a look.

**Comment by oscerd** [comment]
So, you should be able to use this extension here:

https://github.com/syndesisio/syndesis-extensions/tree/master/syndesis-extension-convert-body

This will convert the s3 content coming from a bucket into a plain string.

**Comment by oscerd** [comment]
I'll wait for a reply but this should be enough
