### ISSUE TITLE
Integration grafana dashboard doesn't show integration name and some metrics

### ISSUE THREAD

**Issue by mkralik3** [syndesisio/syndesis#6281]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
I see running integrations in the Graph for Integration dashboard in the Grafana, however, I don't see any identification which curve is for which integration. 
In the Integration dropdown menu, I have only None. Also, the first row of the metrics doesn't see any data.

![image](https://user-images.githubusercontent.com/16251792/62127843-57a84580-b2d3-11e9-93aa-7f6febec8fc1.png)

Prometheus contains metrics for all integrations (I have three simple timer-to-log integrations):
![image](https://user-images.githubusercontent.com/16251792/62128015-c5ed0800-b2d3-11e9-9b18-8e4c329559d8.png)

**Step to reproduce**
- Install syndesis `syndesis minishift --install --tag 1.7.13`
- Install application-monitoring-operator (clone this [repo](https://github.com/integr8ly/application-monitoring-operator/) (tag 0.0.20) and run `make cluster/install`)
-- When the operator is stuck in the first time. Delete project `application-monitoring` and run the command again.
- Label syndesis project `oc label namespace syndesis monitoring-key=middleware`
- Install Syndesis integrations monitoring configuration:
```
oc project syndesis
BASEURL=https://raw.githubusercontent.com/syndesisio/syndesis/1.7.x/install/addons

for ADDON in syndesis-integration-dashboard.yml \
  syndesis-integrations-service.yml \
  syndesis-integrations-servicemonitor.yml
do
  oc create -f ${BASEURL}/${ADDON}
done
```
- Create three simple integration (timer-to-log with 1-second timer)
- Go to the Grafana and look at Fuse Online - Integration - Camel dashboard.

**Comment by heiko-braun** [comment]
@alexkieling I guess this is a question for you :)

**Comment by alexkieling** [comment]
@heiko-braun Sure. Leave it with me.

**Comment by mkralik3** [comment]
Verified in the [pull request](https://github.com/syndesisio/syndesis/pull/6305).
