### ISSUE TITLE
Unable to map Camel header

### ISSUE THREAD

**Issue by ctron** [syndesisio/syndesis#6286]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Using a data mapper only gives you access to the body, but not to the header fields.

Scenario: AMQP 1.0 message -> Database

Part of the information is in the application properties of the AMQP message, part in the body. Both values should be joined in a single "INSERT" statement.

**Comment by oscerd** [comment]
You can write an extension for this.

**Comment by ctron** [comment]
> You can write an extension for this.

Well … I would say that using a property from a message is a rather basic use case, which should be supported out of the box.

**Comment by oscerd** [comment]
We can discuss on single cases but I don't think we can cover all the possible cases. If you can add more details about your specific case

**Comment by ctron** [comment]
Well, my specific case is that I do receive AMQP 1.0 messages, sent from Eclipse Hono, and they do include additional information in the application properties of the message. Without this information, the message is basically useless.

Maybe adding some kind of transformation to Fuse Online, which transposes the headers + body in some kind of "general purpose" structure like `{"headers":{}, "body": {}}` could be added. Or there could be a way to use something like the "simple" language, when mapping data.

But not having access to the headers, basically renders Fuse Online useless in this context, and I need to revert to plain Java, Go or something else.

**Comment by zregvart** [comment]
The discussion around defining multiple data shapes seems relevant to this. We've hit this limitation a number of times now, most recently in #6226. In HTTP-based connectors we resort to having both the _header_ and _body_ (in Camel terms) as a part of the payload and described in the data shape (we call this unified data shape in this case).

**Comment by lburgazzoli** [comment]
FWIW, there's a number of issues on atlasmap side too related to this topic:

- https://github.com/atlasmap/atlasmap/issues/142
- https://github.com/atlasmap/atlasmap/issues/67
- https://github.com/atlasmap/atlasmap/issues/53
