### ISSUE TITLE
Issue when processing data from S3 to ELK using custom step

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#6309]
See also **https://issues.jboss.org/browse/ENTESB-11554**

## This is an issue raised via eval email list

Background:
We’ve built the extension jar file as instructed.
We are able to import it as an extension in Fuse Online and are able to use it to as a step:
 Integration:
Get obj on S3
Convert body with custom step
Invoke URL ELK

But the job still fails. Can you help check why?

**Comment by gaughan** [comment]
Response:

In tests, you are pointing to this address (details removed and replaced with ?)
https://search-?-?-?-?.?-?-?.?.?.com/finaltest/_search

But there is no index with that name.
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"finaltest","index_uuid":"_na_","index":"finaltest"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"finaltest","index_uuid":"_na_","index":"finaltest"},"status":404}

**Comment by heiko-braun** [comment]
We would need more info on why this exception is raised `index_not_found_exception` to be able to act on this.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11554**
