### ISSUE TITLE
UI dev server - live reloading broken

### ISSUE THREAD

**Issue by seanforyou23** [syndesisio/syndesis#6310]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

The dev server for the UI has stopped functioning properly. The live reloading feature no longer works and in addition, I'm seeing the following error which I believe may be related

`WebSocket connection to 'ws://localhost:3000/sockjs-node/912/0q05jnss/websocket' failed: Invalid frame header`

This increases the time it takes to develop and test features for anyone contributing to the UI.

**Comment by rkorytkowski** [comment]
It doesn't work for me most of the time, but it does deploy some changes for me (like 1 out of 100). I haven't identified any pattern.

**Comment by riccardo-forina** [comment]
#6308 should fix it

**Comment by seanforyou23** [comment]
Closed with https://github.com/syndesisio/syndesis/pull/6308
