### ISSUE TITLE
Better integration update

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#6313]
See also **https://issues.jboss.org/browse/ENTESB-11460**

## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Updating an integration to newer version first terminates the integration then builds new one and deploys it instead of first building the new one and then rolling out latest already prepared deployment. 
This leads to integration service being unavailable for quite some time as it can take few minutes before new integration pod is ready.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11460**
