### ISSUE TITLE
Docker version installed with Fedora does not have all features required

### ISSUE THREAD

**Issue by phantomjinx** [syndesisio/syndesis#6315]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Changes made to the syndesis [build scripts](https://github.com/syndesisio/syndesis/blob/master/install/operator/.lib.sh#L138) utilise a 'recent' docker feature whereby a Dockerfile can be redirected to the docker command via -f, ie.
```
/usr/local/bin/docker build -t "my-test-image" . -f - << EOF
FROM golang:1.12.0
EOF
```
This is a feature apparently implemented back in [2017](https://github.com/moby/moby/issues/27393), where moby is a component of the docker binary.

However, this feature does not work on docker installs available via Fedora's rpm system. Versions from both Fedora 29 & 30 fail with the following error:
```
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/phantomjinx/docker/-: no such file or directory
```

The versioning system of the Fedora docker is a little different. Whereas [docker community-edition (CE)](https://docs.docker.com/install/linux/docker-ce/fedora) starts at 18.09.1, the Fedora version of Docker has a version of 1.13.1.

So,
- Up until this point, it would appear that just have docker installed has been enough to do everything required in the syndesis build scripts;
- Seems to be the first occasion where a feature has been required yet missing from certain versions;

Next,
- Do we specify a specific minimum version in both syndesis script env checks and in documentation?
-- Downside: Forcing many users to uninstall distro-specified version and [install new repository](https://docs.docker.com/install/linux/docker-ce/fedora/) and new version;
- Do we try to keep the scripts as backward compatible as possible?
-- Downside: Reverting features and maintaining backward compatibility.

**Comment by lburgazzoli** [comment]
There is a downside of replacing distro specific version with the one from docker: they do provide repositories for newer fedora release with huge delays. I do not know if it still holds true but docker-ce didn't had support for SElinux

Should we investigate using buildah ?

**Comment by chirino** [comment]
Just `cat > tmpfile << EOF` and the. Feed the tmpfile to docker.

**Comment by gashcrumb** [comment]
Theoretically in more recent fedora versions you can install `podman` and do `alias docker=podman` and most things should "just work".  I haven't personally tried that with our build though :smile:

**Comment by gashcrumb** [comment]
and also that means not bothering with that old docker package, I can only think it's in there for some odd compatability purpose.

**Comment by phantomjinx** [comment]
@gashcrumb 
Right, though that would require some kind of documentation to that affect. We can avoid the problem at the moment by going with the solution [above](https://github.com/syndesisio/syndesis/issues/6315#issuecomment-518628775) but over time am wondering how much are those nominally installed docker rpms going to be an issue.

**Comment by lburgazzoli** [comment]
Just found out that fedora provides moby-engine:

```
$ docker version
Client:
 Version:           18.06.3
 API version:       1.38
 Go version:        go1.12
 Git commit:        d7080c1
 Built:             Thu Mar 28 16:22:13 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          dev
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.12
  Git commit:       d7080c1
  Built:            Thu Mar 28 16:21:35 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

Which looks a little bit "fresh" than the docker package

**Comment by phantomjinx** [comment]
Install scripts returned to be backward compatible with older docker versions.
Other options for Fedora have been identified.

Any testing to be performed might install an old docker version and execute the install scripts and determine if the error message does not appear.
