### ISSUE TITLE
Templates don't accept other file types than txt

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#6316]
See also **https://issues.jboss.org/browse/ENTESB-11394**

## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
AFAIK there is no known description of file extensions that the template steps allow to be uploaded. The only mention of uploading files is "Click browse to upload, navigate to a file, and upload it. ". To me this means whatever the extension is, it should be allowed to be uploaded. Restricting users to only uploading certain types of files doesn't make sense to me in this use case since most users are going to write those files themselves, so if there is any restriction regarding this. It should be mentioned somewhere in the UI & there could also be a filter in the file upload dialog.

![image](https://user-images.githubusercontent.com/46345469/62616635-55b43700-b910-11e9-91cc-9c7a7f57412a.png)
(the file input button is there as a workaround for automated tests, don't worry it's not visible :D)

Testing files:
[template1.txt](https://github.com/syndesisio/syndesis/files/3471943/template1.txt)
[template.txt](https://github.com/syndesisio/syndesis/files/3471944/template.txt)
SIDE NOTE: Github does the same thing of restricting only certain types of files, but informs the user in various ways that the file is not supported
![image](https://user-images.githubusercontent.com/46345469/62536924-83857700-b84f-11e9-8266-c9ff66e48bba.png)
If I still upload wrong file type: 
![image](https://user-images.githubusercontent.com/46345469/62536959-9a2bce00-b84f-11e9-94de-535405c96c02.png)
ping: @phantomjinx

**Comment by mmuzikar** [comment]
This is also certainly regression, because in the automated tests the files were of .tpl extension and there was never an issue with that.

**Comment by heiko-braun** [comment]
@phantomjinx Any ideas?

**Comment by phantomjinx** [comment]
PR -> https://github.com/syndesisio/syndesis/pull/6363

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11394**
