### ISSUE TITLE
Template editor doesn't report errors correctly

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#6317]
See also **https://issues.jboss.org/browse/ENTESB-11393**

## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
![image](https://user-images.githubusercontent.com/46345469/62539253-14128600-b855-11e9-8801-e067d542bad0.png)
Earlier the message was `{{wrongid1}}' does not conform to the format {{xyz}} at line: 3, column: 12`, now the message `'' does not conform to the format   at line...` doesn't report much to the user. (But the line numbers are now correct :tada: #5273 )

**Comment by heiko-braun** [comment]
Migrated to https://issues.jboss.org/browse/ENTESB-11393
