### ISSUE TITLE
Database Invoke stored procedure action dropdown is empty in configuration

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#6318]
See also **https://issues.jboss.org/browse/ENTESB-11392**

See also **https://issues.jboss.org/browse/ENTESB-11391**

## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
The invoke stored procedure action configuration form dropdown is empty when I click on the configure button of once added step.
## Steps to reproduce
Create DB stored procedure action: 
![image](https://user-images.githubusercontent.com/46345469/62540465-f98ddc00-b857-11e9-9d94-a51c972707e9.png)
And then click on the configure button of the step you created in previous step:
![image](https://user-images.githubusercontent.com/46345469/62540439-ebd85680-b857-11e9-874b-2de42a6a44f8.png)
The dropdown is now empty.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11391**

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11392**
