### ISSUE TITLE
Create new connection - connection list items are way too large

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#6319]
See also **https://issues.jboss.org/browse/ENTESB-11390**

## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
You can probably see what's wrong in the GIF:
![Peek 2019-08-06 15-10](https://user-images.githubusercontent.com/46345469/62542606-64d9ad00-b85c-11e9-93e4-fa8ae9c857d9.gif)
Something made the connector cards way too wide and the loading icon looked also somewhat enlarged? (I am almost sure I remember it being a spinning circle, not a huge grey circle :smiley: )

**Comment by gashcrumb** [comment]
@seanforyou23?

There's some work in progress converting the cards to pf4, I think this is likely related.

**Comment by seanforyou23** [comment]
Related to https://github.com/syndesisio/syndesis/issues/6240 - will address this in the next batch of card upgrades.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11390**
