### ISSUE TITLE
A-MQ template to deploy broker in user's namespace

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis#632]
Initial issues for [the template](https://github.com/jboss-openshift/application-templates/blob/master/amq/amq63-basic.json) tracked in the JIRA:
https://issues.jboss.org/browse/IPAAS-345 

@rhuss opened to track A-MQ template work. Not sure about labels though :)

**Comment by rhuss** [comment]
thanks ;-) I still owe the team an explanation for the labels. At least there are many and they are colorful :)
