### ISSUE TITLE
"Top 5 by messages errors" panel in the Integration-home grafana dashboard doesn't show data

### ISSUE THREAD

**Issue by mkralik3** [syndesisio/syndesis#6327]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Grafana integrations home dashboard doesn't show any data in the `Top 5 by messages errors` panel even though one integration is still failing.
![image](https://user-images.githubusercontent.com/16251792/62619990-64065100-b918-11e9-8946-91d2a09212b3.png)
![image](https://user-images.githubusercontent.com/16251792/62620014-72546d00-b918-11e9-8dfb-8549ccd23ecf.png)
Integration for debugging (every 30 seconds the integration wants to create an invalid item in DB which causes an error):
[integrationWithError-export.zip](https://github.com/syndesisio/syndesis/files/3476765/integrationWithError-export.zip)

**Comment by heiko-braun** [comment]
@alexkieling More feedback from QE :)

**Comment by mkralik3** [comment]
Verified. 
![image](https://user-images.githubusercontent.com/16251792/63016296-945b6b80-be93-11e9-8ca4-0436ebec956a.png)
