### ISSUE TITLE
User is able to select any step when replacing the finish step

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#6328]
See also **https://issues.jboss.org/browse/ENTESB-11389**

## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When I delete the Finish step, I can choose any step I'd like.
This is what I have by default:
![image](https://user-images.githubusercontent.com/46345469/62621104-5e5e3a80-b91b-11e9-866f-232d5c9cc6fd.png)
After adding log and deleting it:
![image](https://user-images.githubusercontent.com/46345469/62621128-703fdd80-b91b-11e9-8e15-593e66124a83.png)
After adding DB invoke procedure and deleting it:
![image](https://user-images.githubusercontent.com/46345469/62621163-864d9e00-b91b-11e9-854f-ed883aeee108.png)
After adding split after the starting DB step:
![image](https://user-images.githubusercontent.com/46345469/62621200-9ebdb880-b91b-11e9-84b3-263b1fd559af.png)

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11389**
