### ISSUE TITLE
Task : Update respective fuse artifacts to 7.4 versions once 7.4 is GA and available

### ISSUE THREAD

**Issue by cunningt** [syndesisio/syndesis#6339]
See also **https://issues.jboss.org/browse/ENTESB-11571**

## This is a...

[x] task

## Description

Update respective Fuse artifacts in app/pom.xml to the 7.4 versions once 7.4 is GA and available.     This came up in #6292 with updating kubernetes-client - I should do a review of all of the Fuse components and update the ones that make sense.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11571**
