### ISSUE TITLE
Allow some integrations to scale

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#6341]
See also **https://issues.jboss.org/browse/ENTESB-11553**

## This is a...

<pre><code>
[x] Feature request
[x] Field Request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Alow some integrations to scale based on type.
For example, if im using Kafka, scaling should be allowed.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11553**
