### ISSUE TITLE
[master] Komodo is not deployed even with --datavirt

### ISSUE THREAD

**Issue by asmigala** [syndesisio/syndesis#6342]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
On master, installing using the `syndesis` tool with `--datavirt` flag does not deploy komodo, not even the image stream is created.

This is due the following section in the deployed CR:

```
  spec:
    addons:
      komodo: null
```

**Comment by heiko-braun** [comment]
@rkorytkowski mind to take a look? I assume this broke with the recent changes @chirino did.

**Comment by asmigala** [comment]
@heiko-braun this was a simple fix, see #6343

**Comment by mkralik3** [comment]
Verified, after run `syndesis minishift --install --nodev --project syndesis --test-support --datavirt`, the `syndesis-dv` pod is running.
