### ISSUE TITLE
Refactor the operator templates to use values from CR directly instead of Env

### ISSUE THREAD

**Issue by asmigala** [syndesisio/syndesis#6347]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
As a followup to #6345 , we should change the template such as https://github.com/syndesisio/syndesis/blob/master/install/operator/pkg/generator/assets/infrastructure/03-syndesis-ui.yml.mustache to read values directly from the CR rather than use the `Env` var.
This will need rewriting the template from mustache to the go template format

```
Luis Garcia Acosta

I have the feeling it is a design to keep it so, that if the EnvVar is present, it should not be overwritten. The solution within what is implemented is to use the Cr variables for the templates and not the EnvVar, like at 

https://github.com/syndesisio/syndesis/blob/master/install/operator/pkg/generator/assets/infrastructure/02-syndesis-image-streams.yml.tmpl#L12
```
@lgarciaaco

**Comment by lgarciaaco** [comment]
Thanks @asmigala !!
