### ISSUE TITLE
Consolidate fields allowed in syndesis CR

### ISSUE THREAD

**Issue by lgarciaaco** [syndesisio/syndesis#6356]
As we move toward an operator full supporting CR, we have to update documentation in some aspects:

- Description of all suported CR fields
- Documentation on how to install syndesis for customers
- Documentation on how to install syndesis for development
- Documentation on how to debug installation steps

**Comment by KurtStam** [comment]
Can we add comments in the CR? And can we add all possible config options in it? I'm thinking like a linux config file, where values are commented out if not in use.

**Comment by TovaCohen** [comment]
Will this have an impact on the Fuse Online installation doc that we provide here: 
https://access.redhat.com/documentation/en-us/red_hat_fuse/7.4/html/installing_and_operating_fuse_online_on_openshift_container_platform/installation-of-fuse-online-on-ocp_ocp

**Comment by lgarciaaco** [comment]
> Will this have an impact on the Fuse Online installation doc that we provide here:
> https://access.redhat.com/documentation/en-us/red_hat_fuse/7.4/html/installing_and_operating_fuse_online_on_openshift_container_platform/installation-of-fuse-online-on-ocp_ocp

@TovaCohen yes!!

**Comment by claudiocampisi** [comment]
Is there a way to have some documentation for syndesis CR before it will be published officially. Actually i need to know how to provide http proxy information when building integrations.

**Comment by heiko-braun** [comment]
@lgarciaaco Can you help @claudiocampisi ?

**Comment by lgarciaaco** [comment]
@claudiocampisi is this of any help: https://github.com/syndesisio/syndesis/blob/master/install/operator/README.md

**Comment by claudiocampisi** [comment]
Thanks @lgarciaaco, i already read that readme file. I was wondering how to configure S2IConfiguration component in order to specify http proxy environment information
