### ISSUE TITLE
"No Data Available" as uptime when the published integration has not been triggered yet

### ISSUE THREAD

**Issue by mkralik3** [syndesisio/syndesis#6357]
See also **https://issues.jboss.org/browse/ENTESB-11388**

## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When no message comes to the integration, upltime is still set to "No Data Available". For example, when I have a integration Webhook to Log and I don't call webhook (e.g. for hour), the Uptime is still "No Data Available". When I call webhook, the Uptime is alredy shown.

Step to reproduce:

- Create and publish integration Webhook-to-log
- Wait e.g. 5 minutes
- Go to the Metrics tab in that integration. (Uptime is set to "No Data Available")
- Trigger Webhook
- Go to the Metrics tab in that integration. Uptime shows correct value.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11388**
