### ISSUE TITLE
provide a web api to query used versions of Apache Camel, Spring Boot and Syndesis

### ISSUE THREAD

**Issue by lhein** [syndesisio/syndesis#636]
in the eclipse tooling's Tech Extension wizard we currently let the user specify those versions manually. A more convenient way to do that would be to just ask for a URL of the syndesis instance and then trigger some web api to query the versions to be used.

**Comment by paoloantinori** [comment]
I was thinking about implementation:
Probably it makes sense to provide this as a static file, published at build time. 
For most if not all of is information, it's a static information, that probably can avoid a live query to the system. In this way it will have much less impacts on performances.

**Comment by lhein** [comment]
With the latest tooling we only need the syndesis version.

**Comment by valdar** [comment]
I'd a shoot with this one, refactored the `/api/v1/version` endpoint:
- plain/text  GET on that will answer with the syndesis version running on the server (i.e. `1.4-SNAPSHOT`).
- application.json GEt on the same endpoint will answer with something like:
```json
{
    "camelatlasmap-version": "1.35.0",
    "build-id": "",
    "spring-version": "4.3.12.RELEASE",
    "syndesys-version": "1.4-SNAPSHOT",
    "springboot-version": "1.5.8.RELEASE",
    "commit-id": "0e22841110b9fe59bbfffaffac746e96246e25bf",
    "camel-version": "2.21.0",
    "atlasmap-version": "1.35.0"
}
```
All the versions are added at build time to the `runtime.jar` `MANIFEST.MF` and read once during syndesis-server initialization.

**Comment by zregvart** [comment]
Would it be better if we were to create a Syndesis BOM with the individual versions we use? I'm afraid that every solution that tries to list the relevant versions of dependencies will end be hard to maintain. With the BOM we would only need the Syndesis version and all other dependencies would be present in the BOM.

**Comment by oscerd** [comment]
Why not? It works fine.

**Comment by valdar** [comment]
@zregvart so basically you are asking to remove the second endpoint that produce a json with the details and just leave the first one?
Probably from the tooling perspective they don't need all the dependencies but just the major one; once we come with a reasonable list I don't think will change that often...

**Comment by zregvart** [comment]
> @zregvart so basically you are asking to remove the second endpoint that produce a json with the details and just leave the first one?

No, I'm arguing that the approach taken will end up costing us more to maintain. The existing endpoint that returns JSON is used by the UI and there is no need to remove it.

> Probably from the tooling perspective they don't need all the dependencies but just the major one; once we come with a reasonable list I don't think will change that often...

Isn't it then better to maintain this list in a way that it can be used directly by build tools rather than coming up with our own dependency management mechanism?

**Comment by valdar** [comment]
@zregvart ok so in the light of the discussion here and on the PR, I'll rearrange the PR to keep the old informations returned by the endpoint. Then we need another issue to produce the BOM so that, summing up the syndesis main version and the corresponding BOM, the tooling can have the info requested.

**Comment by zregvart** [comment]
@valdar there is a related issue here: https://github.com/syndesisio/syndesis/issues/1198

**Comment by valdar** [comment]
Updated the PR as per what has been discussed:
I'd a shoot with this one, refactored the `/api/v1/version` endpoint:
- plain/text  GET on that will answer with the syndesis version running on the server (i.e. `1.4-SNAPSHOT`).
- application/json GET on the same endpoint will answer with something like:
```json
{
    "build-id": "",
    "commit-id": "2772b5bb5bbc4ed849f3c6527ef8afbd3c5d9860",
    "version": "1.4-SNAPSHOT"
}
```
Once the main Syndesis version has been retrieved, that can be used to get the corresponding BOM (once provided by #1198) containing all the dependencies.
