### ISSUE TITLE
PublicAPI: Duplicate tag after import when tag already exists but integration not

### ISSUE THREAD

**Issue by mkralik3** [syndesisio/syndesis#6360]
See also **https://issues.jboss.org/browse/ENTESB-11387**

## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When I import exported integration with a tag which already exists in the Syndesis, the tag is duplicated. This happens only when the integration which will be imported is not in the Syndesis.
E.g.
I create Integration1 and tag1. I add tag1 to the Integration1 and export zip file according to that tag.
`curl .../integrations/tag1/export.zip -O`
After that, I delete Integration1. The tag1 still persist in the Syndesis ( fix for https://github.com/syndesisio/syndesis/issues/5917).
I import back the exported zip file
`curl .../integrations -F data=@export.zip -F environment=second`
After that, the tag1 is duplicated.
![image](https://user-images.githubusercontent.com/16251792/62922759-77983880-bdac-11e9-89f0-54e79c51c022.png)

However, when I do the same steps but I don't delete the integration, the tag1 is not duplicated after importing. So it looks that this issue is caused by https://github.com/syndesisio/syndesis/issues/5917 fix.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11387**
