### ISSUE TITLE
Display Issue data mapper in Safari

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#6361]
Looks like this - always..

<img width="1354" alt="Screen Shot 2019-08-13 at 9 55 32 AM" src="https://user-images.githubusercontent.com/35576/62924528-95679c80-bdb0-11e9-8057-e324424ddf44.png">

**Comment by gaughan** [comment]
This may be the same as seen in an older version of chrome?
Also, safari is not supported.

**Comment by igarashitm** [comment]
Yes looks like a same issue that was seen with old Chrome.
