### ISSUE TITLE
Manage CI/CD UI doesn't check duplicates

### ISSUE THREAD

**Issue by mkralik3** [syndesisio/syndesis#6362]
See also **https://issues.jboss.org/browse/ENTESB-11386**

## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When I want to create a new tag with the same name as has the existed tag, I am able to click on Save button (however the tag is not created because the backend returns `400 "developerMsg":"Duplicate environment tag1"`).

When I want to rename a tag to the same name as has another tag, I am able to click on Save button and in the UI I see two duplicated tags.
![image](https://user-images.githubusercontent.com/16251792/62937432-e5545c80-bdcc-11e9-8bdd-d0b3e1ee8acd.png)

In the 1.7.x, the dialog for creating/updating the tag was checking whether the name is already used. 
In the left side of the images is master, in the right side is 1.7.13 (CR3)
Creating the tag with the same name:
![image](https://user-images.githubusercontent.com/16251792/62937209-3a43a300-bdcc-11e9-9de8-27f7446cf927.png)
Updating to the same name:
![image](https://user-images.githubusercontent.com/16251792/62937332-96a6c280-bdcc-11e9-95d7-b087874222da.png)

The UI should check the duplicities as before.
The endpoint `PUT .../api/v1/public/environments/<tag>` should check whether the name in params is not already used by another tag.

Step to reproduce:
- Go to Manage CI/CD page
- Create tag with name _tag1_
- Try to create _tag1_ again
- Create tag with name _tag2_
- Try to rename _tag2_ to _tag1_

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11386**
