### ISSUE TITLE
Kafka Connector - add support for SSL

### ISSUE THREAD

**Issue by dudash** [syndesisio/syndesis#6368]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
I have a Kafka cluster that is utilizing TLS and the brokers are secured via JKS. If I export the ca.crt I can connect to the cluster with a kakafcat command like this:
```kafkacat -b my-cluster-kafka-bootstrap-kafka-demo.apps.openshift.redhatgov.io:443 -t some-topic -d broker -X ssl.ca.location=./ca.crt -X security.protocol=ssl```

I would like to be able to connect to this Kafka cluster using Syndesis or Red Hat Fuse Online but there is no obvious place to configure ssl properties [see Kafka config reference here](http://kafka.apache.org/22/documentation.html#consumerconfigs)

**Comment by roller1187** [comment]
This feature is becoming ever more relevant. Are there any updates on this?

**Comment by zregvart** [comment]
@squakez this was implemented in #8103 right? Can we close this?

**Comment by squakez** [comment]
That's correct. Any feedback about that would be great.
