### ISSUE TITLE
UI Changes for ActiveMQ connector per UX design

### ISSUE THREAD

**Issue by dhirajsb** [syndesisio/syndesis#637]
UX design has brought up some changes that need to be made to the UI based. The AMQ icon needs to be added, some action options must be enabled/disabled based on other options.

**Comment by dhirajsb** [comment]
@seanforyou23 there is also a problem with action filtering:

- the `Start Step` in an Integration should only show `Subscribe for messages` action
- the `Finish Step` in an integration should only show `Publish messages` action, or at the very least filter out `Subscribe for messages`

**Comment by seanforyou23** [comment]
Thanks for pointing this out @dhirajsb. I'll use the pattern property on the action to make this determination. Does this only apply for activemq connectors?

**Comment by zregvart** [comment]
Every action regardless of connector type should have a `pattern` property with `"From"` or `"To"` values.

See #253

**Comment by seanforyou23** [comment]
Perfect, thank helps. Thanks @zregvart!

**Comment by jimmidyson** [comment]
@seanforyou23 Any news on this? Is this going to be done for TP3 this week or defer to TP4?

**Comment by seanforyou23** [comment]
@jimmidyson progress has been slower than expected. I believe I'll still be only partially complete by the end of day today. If it's ok, I'd like to defer to TP4. A chance I'll still have it out in time, but it's down to the wire at this point and I just can't say for sure that I'll have it wrapped up in time. Apologies, the dynamic forms plugin we use has gotten the best of me this week.

**Comment by zregvart** [comment]
I'd rather see smaller tasks that we can plan and deliver so let's split this into individual issues for all tasks that we need and close this one. Having this as a open-ended issue doesn't really help us plan or discuss or surface any tech debt issues that need to be addressed for all connectors/actions.

Some of these issues can be addressed by bigger work addressing our tech debt around dynamic forms (in #843).

@dhirajsb @seanforyou23 what do you think?

**Comment by gashcrumb** [comment]
One the PR that fixes #886 lands the UI will support specifying control orders.  Ideally we should drive this from the backend, for the moment though I've added a client-side tweak:

https://github.com/syndesisio/syndesis/pull/919/files#diff-28b4a582e947fd283b192ca194ed84b5R45

We could drive this from the backend by adding a `controls` property alongside the `properties` descriptor, just needs to be an array of strings and sets the order of form controls via property IDs.  Also there's wildcard support, so any form left out just gets appended without a problem.  I think probably for tp4 it'd be good to start adopting this in the descriptors.

**Comment by rhuss** [comment]
What is the state of this issue ? Should it be split into smaller issues for TP4  ? 

I'm moving this issue to Sprint 23 for now.

**Comment by seanforyou23** [comment]
@rhuss still in progress, there are a few issues that remain. I will split these into smaller issues and continue working on them for TP4.

**Comment by seanforyou23** [comment]
The below issues represent work that remains for this, all but one, which is creating a new form control component to capture time in milliseconds. @gashcrumb can you point me to this issue? I think I remember you saying it was already created, but can't find it.

https://github.com/syndesisio/syndesis/issues/992
https://github.com/syndesisio/syndesis/issues/991
https://github.com/syndesisio/syndesis/issues/990
https://github.com/syndesisio/syndesis/issues/887

Feel free to close this issue.
