### ISSUE TITLE
FHIR action page stuck loading

### ISSUE THREAD

**Issue by mastepan** [syndesisio/syndesis#6372]
See also **https://issues.jboss.org/browse/ENTESB-11385**

See also **https://issues.jboss.org/browse/ENTESB-11384**

## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
1. add FHIR connection when creating an integration
2. select a FHIR action
- loading the action page stucks

![FHIR_stuck](https://user-images.githubusercontent.com/8707251/63017969-f1f1b700-be97-11e9-91da-076d26049240.png)

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11384**

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11385**
