### ISSUE TITLE
[operator] Migrate the install process from fuse online install to the operator binary

### ISSUE THREAD

**Issue by lgarciaaco** [syndesisio/syndesis#6378]
The operator binary is able to install the operator and required resources in openshift. Once the operator is installed, a user can define via the CR the specifics of each component. 

The steps to install syndesis via the operator binary are:
```
[lgarciaa@lgarciaa operator]$ ./dist/linux-amd64/operator install cluster
cluster resources were installed successfully
[lgarciaa@lgarciaa operator]$ oc get crds | grep syndesis
syndesises.syndesis.io                                      2019-08-15T09:54:25Z
[lgarciaa@lgarciaa operator]$ ./dist/linux-amd64/operator install operator --image syndesis/syndesis-operator:latest
operator was installed successfully
[lgarciaa@lgarciaa operator]$ oc get pods
NAME                         READY     STATUS      RESTARTS   AGE
syndesis-operator-1-deploy   0/1       Completed   0          55s
syndesis-operator-1-dvnkd    1/1       Running     0          47s
[lgarciaa@lgarciaa operator]$ oc apply -f  deploy/crds/syndesis_v1alpha1_syndesis_cr.yaml 
syndesis.syndesis.io/example created
[lgarciaa@lgarciaa fuse-online-install]$ oc get pods | grep Running
syndesis-db-1-745xg            2/2       Running     0          27m
syndesis-meta-1-fqrqs          1/1       Running     0          27m
syndesis-oauthproxy-1-vt2g4    1/1       Running     0          27m
syndesis-operator-1-dvnkd      1/1       Running     0          29m
syndesis-prometheus-1-hld8f    1/1       Running     0          27m
syndesis-server-1-7ttp4        1/1       Running     0          27m
syndesis-ui-1-l7nhw            1/1       Running     0          27m
todo-1-4g96r                   1/1       Running     0          23m
[lgarciaa@lgarciaa fuse-online-install]$
```
And within the CR, a user can specify, among other options, which addons to install or the tags for individual components:
https://github.com/syndesisio/syndesis/blob/4633f383374865d80b7fd44b4b55126da1ffb574/install/operator/deploy/crds/syndesis_v1alpha1_syndesis_cr.yaml#L43-L44

I dare to say that with this working, the current [release](https://github.com/syndesisio/fuse-online-install/blob/master/release.sh) and [install](https://github.com/syndesisio/fuse-online-install/blob/master/install_ocp.sh) process from fuse-online-install repository are obsolete and can be migrated to the operator binary.

**This ticket is about to identify, discard and implement the few functionalities that are still missing in the operator, that are carried by the before mentioned scripts.**

The install script have few options and maybe not all should be migrated, imho. This is what the `install_ocp.sh` script has to offer:
```
-s  --setup                   Install CRDs clusterwide. Use --grant if you want a specific user to be
                              able to install Fuse Online. You have to run this option once as cluster admin.
-u  --grant <user>            Add permissions for the given user so that user can install the operator
                              in her projects. You have to run this as cluster-admin
    --cluster                 Add the permission for all projects in the cluster
                              (only when used together with --grant)
    --route                   Route to use. If not given, the route is trying to be detected from the currently
                              connected cluster.
   --console <console-url>    The URL to the openshift console
   --force                    Override an existing installation if present

-p --project <project>        Install into this project. The project will be deleted
                              if it already exists. By default, install into the current project (without deleting)
-w --watch                    Wait until the installation has completed
-o --open                     Open Fuse Online after installation (implies --watch)
   --camel-k <version>        Install camel-k operator version <version>
                              (version is optional)
   --camel-k-options "opts"   Options used when installing the camel-k operator.
                              Use quotes and start with a space before appending the options.
   --datavirt                 Install Data Virtualizations.
   --help                     This help message
-v --verbose                  Verbose logging
```
Here what the operator can currently do, what it can not do, and few comments on options that we might not need to migrate:
- [x] `--setup` equivalent to `operator install cluster`
- [ ] `-u  --grant <user>` not implemented yet, tbd
- [ ] ` --cluster` not implemented yet, tbd
- [x] `--route` can now be defined in the CR (_Spec.RouteHostname_)
- [ ] `--console <console-url>` I am not sure what is this for and whether it can be dropped
- [x] ` --force` This is deleting all resources before creation, not implemented yet, tbd
- [ ] `--project <project>` this merely drop and create a namespace, I don;t think we need to migrate it
- [x] `-w --watch` equivalent to `-w`
- [ ] `-o --open` not implemented yet, tbd
- [ ] `--camel-k <version>` and `--camel-k-options` install the camel-k operator. Maybe this is better done as documentation, pointing the user to where to get the operator from. Definitely not something the syndesis operator should take care of
- [x] `--datavirt` can now be defined in the CR (_Spec.Addons.Komodo_)

From here I would define the tasks as:
* Implement `--grant <user>` flag to grant a user the required permissions to install syndesis. Eventually clusterwide?
* Implement `--force` flag which deletes the app
* Implement `--open` flag which would open the url once syndesis is installed

**Comment by chirino** [comment]
instead of --force, I'd rather have an uninstall command.
The --console should drive a CR config option.  Actually there's a bunch of CR config options someone might want to set.  Perhaps a -f syndesis.yaml  would be a better way to give users fine grained control of all the syndesis options?

**Comment by heiko-braun** [comment]
> instead of --force, I'd rather have an uninstall command.

+1

**Comment by lgarciaaco** [comment]
After discussions, I want to migrate the minimal needed features and add afterwards in case someone miss anything. With the implementation of `grant` and `uninstall` I feel like moving forward to the upgrade process
