### ISSUE TITLE
Can't select Log step during create integration

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis#6393]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

In running some first-trial [E2E tests](https://github.com/syndesisio/syndesis/pull/6275) I noticed I can no longer use the Log step when creating an Integration. Confirmed on staging, using Chrome.

The page goes blank when selecting "Log" and in the browser console I get the following error:
```
auto-form.js:22 Uncaught TypeError: Cannot read property 'contextLoggingEnabled' of undefined
    at auto-form.js:22
    at Array.reduce (<anonymous>)
    at sanitizeValues (auto-form.js:14)
    at getInitialValues (auto-form.js:210)
    at AutoForm (auto-form.js:823)
[..]
```

and

```
index.js:1437 The above error occurred in the <AutoForm> component:
    in AutoForm (at WithConfigurationForm.tsx:127)
    in WithConfigurationForm (at ConfigureStepPage.tsx:80)
    in Route (created by WithRouteData)
    in WithRouteData (at ConfigureStepPage.tsx:55)
    in WithIntegrationHelpers (at ConfigureStepPage.tsx:53)
    in ConfigureStepPage (at EditorApp.tsx:214)
[..]
```

## Screenshot/GIF

![Kapture 2019-08-16 at 11 46 03](https://user-images.githubusercontent.com/3844502/63163017-1b3b5000-c01c-11e9-97e1-cdd3dd0bda5a.gif)

Eventually the blank page seems to display the error as well:

<img width="1122" alt="Screenshot 2019-08-16 11 53 10" src="https://user-images.githubusercontent.com/3844502/63163196-a4528700-c01c-11e9-83a4-81041379d82d.png">

## Steps to Reproduce
1. Go to Create Integration.
2. Select SQL or AMQ as start connection. Configure.
3. Select Log as end step.

**Comment by gashcrumb** [comment]
Rebase, I fixed this yesterday.

**Comment by kahboom** [comment]
Ah, gotcha. I did check on staging but didn't delete cookies + clear cache so that's probably it.

**Comment by kahboom** [comment]
Reopening, I had already rebased, but just to be sure I deleted cookies, cleared application data, and even tested on staging in incognito with the same issue.

**Comment by gashcrumb** [comment]
I think maybe you didn't do a full rebuild after rebasing?  [This was the fix](https://github.com/syndesisio/syndesis/pull/6383/commits/bb0af82cb9c50ed450658f53684ad7847174b2c5) for that issue it was done in the auto-form package, so you'd have to rebuild that package.

**Comment by elvisisking** [comment]
I was getting same error as @kahboom (and *swear* I did a build before). But since then, I've got latest and did `yarn --force` and `yarn build` and **poof** error is gone @gashcrumb :)
