### ISSUE TITLE
test operator install against vanilla OCP 4.1 cluster

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis#6414]

**Comment by chirino** [comment]
we have only tested it works against minishift, could we verify if this also works against a vanilla OCP 4.1 cluster?

Even if we can get it to work, is it doing the right thing?  Since OLM is available, shouldn't the operator install be installing a OLM manifests instead of installing the operator and the crds manually?

**Comment by lgarciaaco** [comment]
@chirino I have tested this in both scenarios: including the operator in the catalog, and with `operator install ...`.

I used CRC for the tests.
