### ISSUE TITLE
Step number is not being shown on the add to integration screen 

### ISSUE THREAD

**Issue by dongniwang** [syndesisio/syndesis#6457]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
This is the add to integration screen. And step numbers do not show up here. 
<img width="1419" alt="Screen Shot 2019-08-23 at 10 52 27 AM" src="https://user-images.githubusercontent.com/24943812/63601972-82b14c80-c594-11e9-9955-62816e02df21.png">

This is the IVP where you can see step numbers next to the step name. E.g. 1. Webhook
<img width="336" alt="Screen Shot 2019-08-23 at 10 53 22 AM" src="https://user-images.githubusercontent.com/24943812/63601975-85ac3d00-c594-11e9-8373-f893ac5ef934.png">

Should add the step numbers to the Add to integration screen. Can follow the same convention we have for the IVP. 

cc: @gashcrumb

**Comment by gashcrumb** [comment]
I think it shouldn't be a problem to stick the index number in front of the name.
