### ISSUE TITLE
FuseOnlineDatabaseInstanceDown alert never fires

### ISSUE THREAD

**Issue by StevenTobin** [syndesisio/syndesis#6475]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
The FuseOnlineDatabaseInstanceDown alert found here https://github.com/syndesisio/syndesis/blob/1.7.x/install/addons/syndesis-db-prometheus-rule.yml#L24 never seems to fire. The query pg_up{job="syndesis-db"} seems to return no data if the syndesis-db pod is scaled to 0 rather than 1 as it seems to expect

A solution could be to merge the two alerts into

sum(pg_up{job="syndesis-db"}) by(namespace, pod, instance) == 0 or absent(up{job="syndesis-db"}) == 1

**Comment by zregvart** [comment]
@alexkieling can you have a look at this?

**Comment by alexkieling** [comment]
@zregvart sure, I'll have a look

**Comment by alexkieling** [comment]
@StevenTobin, when syndesis-db is scaled to 0 and disappears from the list of Prometheus targets, the FuseOnlinePostgresExporterDown alert should start firing. I believe the FuseOnlineDatabaseInstanceDown alert only fires when the database is down but still available for scrapping by Prometheus.

**Comment by StevenTobin** [comment]
Ah ok, I understand. I killed the postgres process in the pod and the alert started to fire. My mistake in testing incorrectly.
