### ISSUE TITLE
[operator] external database connection string option in syndesis custom resource

### ISSUE THREAD

**Issue by aidenkeating** [syndesisio/syndesis#6477]
See also **https://issues.jboss.org/browse/ENTESB-11573**

## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Currently, the Syndesis operator will provision a Postgres database as part of it's setup.

There is not a way in the Syndesis custom resource to specify that you'd like the operator to not provision this in-cluster Postgres and instead use an external Postgres instance, for example one hosted on AWS, by providing connection string info in the Syndesis CR.

The feature request would be to add an a boolean option to the [`db` object](https://github.com/syndesisio/syndesis/blob/master/install/operator/deploy/crds/syndesis_v1alpha1_syndesis_crd.yaml#L42) in the Syndesis CR, for example `externalDb`.

When set to `true` the operator would skip provisioning the in-cluster Postgres and attempt to look for a `Secret` in the Namespace with an expected name, for example `syndesis-database`. This Secret should contain connection details for an external Postgres instance (username, password, database, host and port)

The name of the Secret could then be overridden if needed with an optional `externalDbSecret` attribute in the `db` object.

For example:

```
db:
    externalDb: true # the operator won't provision a Postgres instance
    externalDbSecret: my-secret-name # the operator will look for a Secret named my-secret-name instead of syndesis-database
```

This would still be backwards compatible as `externalDb` can be treated as `false` when it is not specified in the custom resource.

Any suggestions about this would be appreciated. I'd be happy to put together a PR around this.

**Comment by zregvart** [comment]
I think we could do this by adding a modifying the `DbConfiguration` struct:

https://github.com/syndesisio/syndesis/blob/c9a543aa0bc7d11db06a15efc883c9dde9cf30ae/install/operator/pkg/apis/syndesis/v1alpha1/syndesis_types.go#L91-L97

And add `Provision` boolean (`true` by default), if set to `false` the database related objects are not created. Then it would be up to the user to avail the database via Service or Endpoint, so it can be discovered via DNS discovery as it is now.

I'm not too sure on how the database password would be provided in this case perhaps then the `POSTGRESQL_PASSWORD` would not be added to the `syndesis-global-config` Secret and an secret (say. `syndesis-custom-config`) with empty `POSTGRESQL_PASSWORD` would be generated instead. The person installing Syndesis would then need to update this `syndesis-custom-config` Secret with the password provisioned.

cc @chirino @lgarciaaco

**Comment by chirino** [comment]
We also need to make sure the backup and restore process works with the external dB.

**Comment by aidenkeating** [comment]
@zregvart I'm not understanding the reasoning for leveraging Service or Endpoint instead of allowing the end-user to provide the connection string directly via the CR and simply updating the required Secrets/env vars that are currently pointing to the internal postgres service?

Have I missed an issue that would mean this couldn't happen?

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11573**
