### ISSUE TITLE
Jest failures in packages/ui when adding @patternfly/react-table as a dependency

### ISSUE THREAD

**Issue by elvisisking** [syndesisio/syndesis#6485]
Here is the branch where I am adding react-table: [output-table](https://github.com/elvisisking/syndesis/tree/output-table)

The following commands work fine: `yarn install`, `yarn build`, `yarn storybook`. The story I wrote with the table in it displays fine. Also connecting to staging using this branch works fine too. The table shows up and no errors in console.

But when I run `git push origin output-table` a `yarn test` gets run and the errors appear and the `push` fails. Running `yarn test` on its own you get two of the following errors:

```
 FAIL  __tests__/AppLayout.spec.tsx
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /Users/dan/Development/repos/syndesis-good/app/ui-react/node_modules/lodash-es/lodash.js:10
    export { default as add } from './add.js';
    ^^^^^^

    SyntaxError: Unexpected token export

      at ScriptTransformer._transformAndBuildScript (../../node_modules/@jest/transform/build/ScriptTransformer.js:471:17)
      at ScriptTransformer.transform (../../node_modules/@jest/transform/build/ScriptTransformer.js:513:25)
      at Object.<anonymous> (../../node_modules/@patternfly/react-table/dist/js/components/Table/base/evaluate-transforms.js:8:17)
```
Both test failures are from files I did not touch in this branch.

Well, after the F2F, using the the PF4 table now is probably not required (still waiting for new UX design), I would like to get this branch merged and tagged so I can go back to it when the requirement for a table is back.

@kahboom was able to reproduce this error. And @seanforyou23 said he had some ideas.

Here is a link I found that **remotely** sounds related. It is a closed issue on `nrwl/nx` repo that is using angular, but could have some value. See [hopefully useful nrwl/nx issue](https://github.com/nrwl/nx/issues/812)

**Comment by seanforyou23** [comment]
@elvisisking I think this one was resolved with https://github.com/syndesisio/syndesis/pull/6514, right? Can you confirm when you have time? Thx!

**Comment by elvisisking** [comment]
Just tested and you are right @seanforyou23. Looks like it is fixed.
