### ISSUE TITLE
Implement REST endpoint to delete a custom connector

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#652]
We need REST operation to fetch a single custom connector by id.

UX [API Connector List](https://github.com/syndesisio/syndesis/blob/master/ux/designs/apiconnector/apiconnector.md#api-connector-list)
UI #271

**Comment by jimmidyson** [comment]
Out of interest, why are custom connectors treated differently to normal connectors after creation?

**Comment by jimmidyson** [comment]
As in, can't they just be filtered by tags/property?

**Comment by zregvart** [comment]
> Out of interest, why are custom connectors treated differently to normal connectors after creation?

I wish I could give you a straight answer to that, seems that Custom Connectors are not exactly alike Connectors in general. For instance I'm not sure we'll ever allow deleting or updating of (Plain) Connectors.

If we add endpoints specific to custom connectors then we can, at a nice point in the future, detect if the Connector being manipulated is a Custom Connector or a (Plain) Connector and based upon that decide if we want to proceed.

Right now, we are not in that rosy future.

**Comment by zregvart** [comment]
> As in, can't they just be filtered by tags/property?

The simplest way is by using Connector Group, which is how I did it for #647 (see https://github.com/syndesisio/syndesis/pull/647/commits/73c67b160fb8e1024ed25b0e99a10f5d21e3f917)

**Comment by zregvart** [comment]
@jimmidyson I've assigned this over to you, should not be much of an issue, for the first implementation we can go ahead and just implement `Deleter` on `ConnectorHandler`
