### ISSUE TITLE
Error: Bad Gateway. while try creating New connection. on fuse 7.4

### ISSUE THREAD

**Issue by neetu1989** [syndesisio/syndesis#6522]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

**Comment by Delawen** [comment]
Hi @neetu1989 can you explain a bit more the steps you were doing when you got this error? What kind of connection was it?

**Comment by KurtStam** [comment]
@neetu1989 please reopen if you can provide us with more details. Thx --Kurt
