### ISSUE TITLE
[operator] migrate upgrade out of the upgrade pod

### ISSUE THREAD

**Issue by lgarciaaco** [syndesisio/syndesis#6526]
Currently the operator is not involved on much of the logic going on with the upgrade, the heavy lifting is done by the upgrade pod. Resources are located [here](https://github.com/syndesisio/syndesis/tree/master/tools/upgrade)

What the upgrade pod is doing:

1. Backup resources from openshift
2. Scale down deployments
3. Backup resources from db
4. Run migration scripts
5. Scale down everything to 0
6. Migrate stateful resources (ConfigMap, Secrets, PersistentVolumeClaims)
7. Restart all

I wonder how much of this we can take out. For instances it seems to me that the migration scripts should be ran by syndesis and not by the operator. syndesis-server should check on startup the database version and if it is an older one, try to migrate them.

1, 2, 5, 6 and 7 can be migrated to the operator. We might want 4 to be done by syndesis? I think 3 we should create an addon for it, and we would also have regular backups

**Comment by lgarciaaco** [comment]
@zregvart @chirino thoughs?

**Comment by zregvart** [comment]
> syndesis-server should check on startup the database version and if it is an older one, try to migrate them.

We have this already.

**Comment by lgarciaaco** [comment]
> > syndesis-server should check on startup the database version and if it is an older one, try to migrate them.
> 
> We have this already.

Is it the same as https://github.com/syndesisio/syndesis/blob/f2f0c050bcea5db3e17e6248420499c7040c636e/tools/upgrade/steps/upgrade_10_migrate_db#L84-L87

**Comment by zregvart** [comment]
Somewhat, the code from syndesis-cli invokes migration from syndesis-server:

https://github.com/syndesisio/syndesis/blob/f2f0c050bcea5db3e17e6248420499c7040c636e/app/server/cli/src/main/java/io/syndesis/server/cli/command/migrate/MigrateCommand.java#L100-L106

vs

https://github.com/syndesisio/syndesis/blob/78b251b7d5dddc9e2fe74479c4cedf4f6c1b5661/app/server/runtime/src/main/java/io/syndesis/server/runtime/Migrations.java#L87-L100

**Comment by avano** [comment]
for `3 - moving to addon` - looks good to me, would it be possible to invoke the backup from the operator before starting the upgrade (besides the regular backups)?

**Comment by lgarciaaco** [comment]
> for `3 - moving to addon` - looks good to me, would it be possible to invoke the backup from the operator before starting the upgrade (besides the regular backups)?

we could make it that way

**Comment by lgarciaaco** [comment]
@zregvart would you agree that the migration script step can be removed from the upgrade process because the new syndesis would pick it up? I wont remove it from now since it is not harmful and it will generate more work and testing, but maybe something we think of for 7.6

**Comment by zregvart** [comment]
@lgarciaaco I think the reason behind migrations being separate from server startup is that you can still restore the database if the migration fails, we would effectively loose that ability.

**Comment by lgarciaaco** [comment]
> @lgarciaaco I think the reason behind migrations being separate from server startup is that you can still restore the database if the migration fails, we would effectively loose that ability.

Why? we keep the database backup in place as pre step. This is about the migration, which comes afterwards.

**Comment by zregvart** [comment]
@lgarciaaco have a look at the [original proposal](https://github.com/syndesisio/syndesis/blob/master/project/proposals/971-upgrade.adoc#231-migrate-database) it describes that rollback is performed in case of errors with database migrations and a `NOTE` about running migrations from within server vs outside of server pod.
