### ISSUE TITLE
Error report 

### ISSUE THREAD

**Issue by tmielke** [syndesisio/syndesis#6527]
See also **https://issues.jboss.org/browse/ENTESB-11572**

## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Using version 1.17.fuse-740001-redhat-00002, when publishing an integration there is a "View Logs" link next to the progress bar. Clicking on it, opens a new browser tab that says:

![Screenshot 2019-09-05 at 14 08 21](https://user-images.githubusercontent.com/1889892/64340676-02a0d300-cfe7-11e9-8435-bcaf07469d91.png)

**Comment by zregvart** [comment]
@tmielke can you provide some more details, for example the URL in the browser at the point the error is shown, how you installed. One thing of note would be if the `syndesis-ui-config` ConfigMap's entry for `config.json` contains any value for `consoleUrl`.

@lgarciaaco can you check if the `OPENSHIFT_CONSOLE_URL` environment variable is initialized with a value?

https://github.com/syndesisio/syndesis/blob/d0ff5cead55b288c71ce1dd36229d6562e05da86/install/operator/pkg/generator/assets/infrastructure/03-syndesis-ui.yml.mustache#L111

I think there's a fair chance that it's empty.

Related to #3076 (cc @heiko-braun @paoloantinori)

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11572**
