### ISSUE TITLE
Container image tag issue in the release build

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#6557]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

From the [recent daily release](https://ci.fabric8.io/view/syndesis/job/syndesis-release-daily/577/consoleText).

```
16:18:50 ======================================================
16:18:50 Building image with Docker
16:18:50 ======================================================
16:18:51 invalid argument "syndesis/syndesis-operator:1.8.1-20190910:latest" for t: Error parsing reference: "syndesis/syndesis-operator:1.8.1-20190910:latest" is not a valid repository/tag: invalid reference format
```

**Comment by lgarciaaco** [comment]
Related: https://github.com/syndesisio/syndesis/pull/6545
