### ISSUE TITLE
SQL Connector - Incorrect column type inference in Data Mapper 

### ISSUE THREAD

**Issue by evanshortiss** [syndesisio/syndesis#6576]
## This is a...

<pre><code>
[x] Bug report
</code></pre>

## Description

I created a Kafka connection that accepts JSON per schema:

```json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "meterId": {
            "type": "number"
        },
        "timestamp": {
            "type": "number"
        },
        "status": {
            "type": "string"
        }
    }
}
```

I then write it to Postgres with the following table structure:

```
CREATE TABLE meter_status_evals01 ( id serial NOT NULL PRIMARY KEY, meter_id serial NOT NULL references meter_info(id), timestamp TIMESTAMP NOT NULL, status_text text NOT NULL );
```

And the insert SQL:

```
INSERT INTO meter_status_evals01 (meter_id, timestamp, status_text) VALUES (:#meter_id, to_timestamp(:#timestamp), :#status_text);
```

This of course requires a Data Mapper. The bug occurs here. For some reason the Data Mapper thinks `status_text` is of type `INTEGER` and `timestamp` is of type `STRING`.

I can fix the issue by changing the insert SQL to:

```
INSERT INTO meter_status_evals01 (meter_id, status_text, timestamp)VALUES (:#meter_id, :#status_text, to_timestamp(:#timestamp));
```

The type inferences seems linked to the alphabetical ordering, but the link isn't clear to me. 

<img width="520" alt="Screenshot 2019-09-12 at 11 36 50 AM" src="https://user-images.githubusercontent.com/1303687/64781039-d989c080-d559-11e9-83bb-84be66cd1af3.png">
<img width="927" alt="Screenshot 2019-09-12 at 11 47 18 AM" src="https://user-images.githubusercontent.com/1303687/64781040-d989c080-d559-11e9-9f64-b6df82a6b073.png">

**Comment by KurtStam** [comment]
Hmm @evanshortiss So the database type of the  timestamp column is TIMESTAMP and and the [timestamp function](https://www.postgresql.org/docs/10/functions-datetime.html#FUNCTIONS-DATETIME-TABLE) takes a double precision int. 

So I think are expecting to map to an Integer in the data mapper (String will work too, as long as it is an integer number). This is going to be hard to support as we're venturing into database specific implementation here using functions. This will get even more interesting if the [two argument](https://www.postgresql.org/docs/10/functions-formatting.html) version is used.

I'm afraid in cases like these we would need to provide an option to set a custom dataShape. I will see what happens can 'gracefully degrade' and set default the type to String.

**Comment by KurtStam** [comment]
This fails pretty quickly as "(" is one of the splitter characters to break down the SQL statement and so:

> VALUES (:#meter_id, to_timestamp(:#timestamp), :#status_text) 

is broken into 

> VALUES, :#meter_id, to_timestamp, :#timestamp, :#status_text

so yeah.. if this works it's completely accidental.

The only way this works the right way is if you remove to function call like:

> VALUES (:#meter_id, :#timestamp, :#status_text) 

You then will have to make sure to insert a support string format for the time.

@igarashitm Does AtlasMap support a INT -> TIMESTAMP transformation at the moment?

info on the function to_timestamp(double precision)
timestamp with time zone
Convert Unix epoch (seconds since 1970-01-01 00:00:00+00) to timestamp to_timestamp(1284352323) | 2010-09-13 04:32:03+00

and if not, would we want to support that?

**Comment by KurtStam** [comment]
@evanshortiss a workaround would be to create a Stored Procedure.

**Comment by igarashitm** [comment]
AtlasMap doesn't have `TIMESTAMP` type for JSON schema. It should be translated to string or number.

**Comment by igarashitm** [comment]
If you just want to format from epoch millisecs into human readable `STRING`, we can add a `formatDateTimeFromEpochMillis()` transformation which applies to `NUMBER` field. Currently we don't have it OOTB.

**Comment by igarashitm** [comment]
Also in a bit longer term, we will need to consider supporting date/time format support in JSON schema.
https://github.com/atlasmap/atlasmap/issues/1216
https://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.7.3.1
It then requires field type to be string instead of number though.

**Comment by KurtStam** [comment]
@evanshortiss wdyt? Personally I like atlasmap/atlasmap#1217

**Comment by evanshortiss** [comment]
@KurtStam thanks for looking into this. Let me summarise my understanding as someone not familiar with this ecosystem:

1. The `to_timestamp` function is part of the PSQL syntax
2. Syndesis parses the SQL text/input into some format internally to prepare a query
3. The parser uses `(` as a splitter
4. Using abitrary PSQL (or MySQL etc. flavors) functions is not supported by the parser

The solution being suggested is a built-in function `formatDateTimeFromEpochMillis` that can be parsed and executed. This would allow Syndesis users to use a `TIMESTAMP` column, but with the caveat they must send data to the Connector as an integer with millis since epoch?

**Comment by igarashitm** [comment]
Correct, in this case you have to send that millisecs decimal to the Data Mapper step. That is atlasmap/atlasmap#1217.
atlasmap/atlasmap#1216 is to treat timestamp column directly in the SQL connector behind the scene and deliver as, say `DATE_TIME_TZ` type of field instead.
Sure allowing SQL functions in SQL connector would be yet another option.

**Comment by evanshortiss** [comment]
@igarashitm thanks for the clarification. This seems like reasonable workaround if specific SQL functions can't be supported 👍
