### ISSUE TITLE
Provide REST API endpoint for details about custom connector

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#659]
We need a REST API endpoint (perhaps a `/connectors/{id}/details` that returns `ConnectorSummary` for a created connector. We already have a `ConnectorSummary.Builder::createFrom(Connector)` method that we can use.

We'll deal with validations when we have implemented those.

This is for [API Connect detail](https://github.com/syndesisio/syndesis/blob/master/ux/designs/apiconnector/apiconnector.md#api-connector-details) screen, for the lower part (_Swagger Actions Review_).

**Comment by deeleman** [comment]
How much information will be bundled inside each Custom Connector graph? How does it translate to actual Kbs pulled from a GZipped response from the API?

Our goal is to migrate to a reactive functional app shortly and in those scenarios we'd rather fetch as much data as possible, persist it in our store and replace it only when something happens (either a user data interaction or a push notification from the server).

In that sense, would it make more sense to fetch all the available custom connector data in one shot? If the overall data size footprint is not too high, I'd say to take this path, instead of performing roundtrips to the server on  a per custom connector basis.

**Comment by zregvart** [comment]
Right now we don't store the result of the validation with the Connector. Well, TBH we don't perform any validation at all, currently. So at least for the validation part of the summary we need to re-validate each time that endpoint is invoked. We might end up saving the validation results with the Connector and that would make it available in one go. Until then this would be the only way.

Ironically, since we don't perform any validation, the other part of the summary (count of operations by tag), is derived from the data available in the connector, so it can be derived in entirety from the connector data.

**Comment by deeleman** [comment]
I see. A workaround for the future, once we manage to get Redux in full swing on the UI end, would be to persist the connector graph clientside and only fetch the validation status details upon checking the detail component. This obviously does not prevent us from executing that server roundtrip but at least reduces the overall Http call footprint.

Iterating on that, having that validation status update directly notified by means of a Web Socket would be just awesome, provided you plan to run validation checks on a regular basis. That would allow to update the store eagerly and then be able to display "Not Valid" labels at the list itself.

One last note: The detail page shows off exactly the same data scheme for the "Connector name" (????) options and the "Swagger actions review" than the create wizard. It would make our lives easier to have the same data scheme than the return message of the `/api/v1/custom/connectors/swagger-connector-template/validation` POST response (please remember that we agreed on merging both the `validation` and `info` responses)

**Comment by zregvart** [comment]
@jimmidyson do you think we can add this information needed for the [API Connector details page](https://github.com/syndesisio/syndesis/blob/master/ux/designs/apiconnector/apiconnector.md#api-connector-details) as part of the `Connector` model? That would mean adding a property `summary` to `Connector` of type `ConnectorSummary` if the `connectorGroup` matches one of known Connector generators, generated by the `ConnectorGenerator::info`?

This way it could be served from the existing endpoint `GET /api/v1/connectors/{id}`.
