### ISSUE TITLE
Fix mongodb tests

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#6611]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Seems that our builds are [failing due to tests in mongodb connector](https://app.circleci.com/jobs/github/syndesisio/syndesis/119196).

[build.log](https://github.com/syndesisio/syndesis/files/3619708/build.log)

@squakez can you have a look?

**Comment by KurtStam** [comment]
@squakez feel free to assign other people if you need help with this.

**Comment by KurtStam** [comment]
<img width="422" alt="Screen Shot 2019-09-17 at 10 22 28 AM" src="https://user-images.githubusercontent.com/35576/65024502-4a9fee00-d935-11e9-9452-149ee3e98938.png">

**Comment by squakez** [comment]
Okey, I think it may because I changed the embedded server to start as a cluster. Going to have a look at that
