### ISSUE TITLE
syndesis-db fails to pull during 'syndesis install'

### ISSUE THREAD

**Issue by SvenC56** [syndesisio/syndesis#6755]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
I get this error message:
```
Failed to pull image "172.30.1.1:5000/openshift/postgresql@sha256:d459c9bb18ec7de443fbe4dd31cff26bdc6fdc681363922e97ae2f40e64a93c1": rpc error: code = Unknown desc = Error response from daemon: unknown: unable to pull manifest from docker.io/centos/postgresql-95-centos7:latest: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 172.30.0.2:53: read udp 172.17.0.5:57543->172.30.0.2:53: i/o timeout
```

I tried to change the DNS to the Google nameservers but this did not resolve the issue. I am running:
* Ubuntu 19.04
* Docker version 19.03.2, build 6a30dfca03
* oc v3.11.0+0cbc58b
* kubernetes v1.11.0+d4cacc0
* features: Basic-Auth GSSAPI Kerberos SPNEGO

Is this issue related to Syndesis or Docker/ OpenShift?

Thank you.

**Comment by zregvart** [comment]
Two observations: you're trying to run on Kubernetes, which is currently a work in progress (we support OpenShift currently), as you have diagnosed it looks like it's a DNS issue you need to fix that first there's not much this project can help you with.

Thank you for kicking the tiers...

**Comment by SvenC56** [comment]
Hi @zregvart,

thanks for your feedback. I was using OKD as I was not aware that it's much different in comparison to OpenShift.
Besides that, I was able to make the whole thing working. I pushed the postgresql container manually to the registry. Now it's working.

**Comment by SvenC56** [comment]
@zregvart hi I have just one question. OKD is an upstream version of Openshift, right? So basically they are technically the same?

So Syndesis should be running on OKD, right?

**Comment by zregvart** [comment]
@SvenC56 yes Syndesis should run without any changes on OKD.

**Comment by heiko-braun** [comment]
@SvenC56 The original problem, failing to pull the db image from `openshift/postgresql` should be resolved with this PR https://github.com/syndesisio/syndesis/pull/7760

Previously, we did assume that the postgres image is present in the openshift namespace, which might not be the case for OKD. With that change in place, it should pull from docker hub, if I am not mistaken.

**Comment by SvenC56** [comment]
Great news, thanks :)
