### ISSUE TITLE
datamapper doesn't see data through  'step connection' in integration.

### ISSUE THREAD

**Issue by Stefan365** [syndesisio/syndesis#681]
If I use 3 connections(START - STEP - FINISH)
and START connection is "select * from contact",
I can see data from that select in datamapper 1 (between START and STEP)
but not in datamapper 2 (between STEP and FINISH)
If I choose INSERT/UPDATE/DELETE in STEP, I see no input in datamapper 2
see also #403

**Comment by zregvart** [comment]
I think this is as designed, data shape is not passed between steps and the INSERT/UPDATE/DELETE does not provide a shape (produces no result). I think this can be closed.

cc @KurtStam @kcbabo

**Comment by KurtStam** [comment]
Y going to close this as it is in fact how it works today. It should hopefully change soon: https://github.com/syndesisio/syndesis/issues/893
