### ISSUE TITLE
Tech extension: wrong ID shown on import/update page

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#683]
An extension has two IDs:

1. id 
2. extensionId

The first one is auto generated by the platform and it should not be shown to the user as the UI does at the moment:

![image](https://user-images.githubusercontent.com/1868933/33828409-49d3b490-de6c-11e7-8014-26a725941f18.png)

Instead the install/update page should shown `extensionId` as id, below a partial extension json:

```json
{
  "name": "Syndesis Extension",
  "description": "A simple Syndesis Extension",
  "extensionId": "com.github.lburgazzoli:syndesis-extensions",
  "version": "1.0.0-SNAPSHOT",
  "tags": [
    "experimental",
    "feature"
  ],
  ...
}
```

**Comment by lburgazzoli** [comment]
@syndesisio/ui-api can anyone have a look ?

**Comment by zregvart** [comment]
Seems easy enough:

https://github.com/syndesisio/syndesis/blob/cecfaa3b26f5c68c930d14f5b0d7b4f2103000bc/app/ui/src/app/customizations/tech-extensions/import/tech-extension-import.component.html#L102

I think this one needs updating also on the details page:

https://github.com/syndesisio/syndesis/blob/cecfaa3b26f5c68c930d14f5b0d7b4f2103000bc/app/ui/src/app/customizations/tech-extensions/detail/tech-extension-detail.component.html#L35
