### ISSUE TITLE
Postgresql failed to start up

### ISSUE THREAD

**Issue by honghuac** [syndesisio/syndesis#6852]
## This is a...

<pre><code>
[ x] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
</code></pre>

## Description
I tried installing Fuse Online (Syndesis v1.7.25)

Postgresql failed to start up. Syndesis Db pod log contains this error message:
https://gist.github.com/honghuac/45c771d1cc62f88a159d04e41dd24a30

As a result, the syndesis-server pod fails to load.

**Comment by zregvart** [comment]
Can you check the images for the syndesis-db on the image stream can be downloaded?

**Comment by honghuac** [comment]
@zregvart I noticed that a `imagepullsecret` is being used in the Fuse Online installation process of Integreatly. This secret seems to contain the necessary credential data for image pulls.

Is this now also a pre-requisite (ie: setting up the `imagepullsecret`) in setting up a Fuse Online instance?

**Comment by zregvart** [comment]
Yes it is have a look at the [README](https://github.com/syndesisio/fuse-online-install/blob/master/README.md).

**Comment by honghuac** [comment]
It works beautifully, with that secret in place.
