### ISSUE TITLE
Status of https://github.com/syndesisio/syndesis/blob/master/install/syndesis.yml ?

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/syndesis#6863]
Should this file be removed?

**Comment by KurtStam** [comment]
It it the template that was created from the mustache fragments. Since those are now gone I guess we have no way of maintaining it?

**Comment by zregvart** [comment]
It needs to be removed, it's scar tissue at this point.

**Comment by lgarciaaco** [comment]
It is removed already
