### ISSUE TITLE
Duplicate connection message missing

### ISSUE THREAD

**Issue by squakez** [syndesisio/syndesis#6880]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Creating a new connection using an existing name shows a generic `bad request` notification.

![image](https://user-images.githubusercontent.com/23169723/66469792-d1557000-ea88-11e9-9df5-3c3d2b4ef6ca.png)

I suggest to use a specific message error as we got the value in the POST /connection/ response:
```
[{"error":"UniqueProperty","message":"Value 'MongoDB' is not unique","property":"create.obj.name"}]
```

**Comment by gashcrumb** [comment]
I don't think we carried forward the validation that was happening in the old UI for this.
