### ISSUE TITLE
Add support for building and installation in CRC OCP 4.1 cluster

### ISSUE THREAD

**Issue by dhirajsb** [syndesisio/syndesis#6905]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Allow developers to build and install Syndesis in a CRC cluster.

**Comment by christophd** [comment]
I already have added a `crc` subcommand to the syndesis binary ([tools/bin/commands/crc](tools/bin/commands/crc)) that should work the same way as the `minishift` subcommand. 

We need to sort out some issues though with Syndesis running on CRC. Here are my findings so far:
* 8GB of minimum required memory is difficult to manage with 16GB total available memory on the host (I came up with running CRC not on my laptop but on another computer in my local network which works out quite ok)
* Certificates expire after 30 days and the whole CRC cluster setup needs to be done from scratch again (see https://github.com/code-ready/crc/issues/11)
* Initial VM disk-size (30GB) too small for Syndesis (see https://github.com/code-ready/crc/issues/127)
* Missing possibility to connect to the CRC Docker daemon

Many of these problems are already addressed and may not be related to CRC but OCP4 in general.

**Comment by christophd** [comment]
@phantomjinx can you please add your findings here, too.

**Comment by dhirajsb** [comment]
@christophd thanks for putting the CRC script together. I installed it directly to see any other problems I could find.  Some of my observations:

* Needed to bump memory in my CRC instance to 10GB to be able to install Syndesis. It wasn't able to start all syndesis pods without it. It of course slows down everything else on my 16GB laptop.
* I haven't run into disk size issue yet, but I only added a couple of simple integrations so far. So maybe that could change with more complex integrations. 
* I fixed a couple of minor issues with building with go 1.13.1 and an issue in version check with CRC oc client in #6906 
* The db pod wouldn't start because postgresql tag for 9.5 was missing for some reason in my CRC installs `openshift` namespace, which I fixed with
    `oc tag registry.redhat.io/rhscl/postgresql-95-rhel7:latest openshift/postgresql:9.5`

**Comment by dhirajsb** [comment]
On Mac OS X I had issues with old OTP VPN connections when installing CRC. Even though the services were marked inactive, CRC installer kept trying to start them and failed with a generic error, which didn't provide much information. 

So you might have to delete any such connections if they fail to start with CRC.

**Comment by phantomjinx** [comment]
> @phantomjinx can you please add your findings here, too.

Created a 2nd [issue](https://github.com/syndesisio/syndesis/issues/6918) by mistake so copying to here:

$ crc version
version: 1.0.0-rc.0+34371d3
OpenShift version: 4.2.0-0.nightly-2019-09-26-192831 (embedded in binary)

    Encountered error with oc version checks in syndesis scripts (corrected in PR-6919)
    Postgresql 9.5 is not available from crc by default so upgrade to 9.6 (PR-6919)
    Found 1st install failed with Postgresql 9.6 reporting "insufficient memory"
        Limit / requirement set at 512MB
        Lowered limit to 100MB and installed correctly
        Logged issue & followed suggestion to increase memory of CRC from 12GB to 16GB which was successful in running all syndesis pods
        With Postgresql being able to run on only 8GB, it remains to be seen whether this was a one-off or whether such steep memory limits are required for syndesis (shouldn't be!)
    Cannot login with developer account & unable therefore to route to syndesis application

PR -> https://github.com/syndesisio/syndesis/pull/6919

**Comment by dhirajsb** [comment]
@phantomjinx so PostgreSQL 9.6 requires a lot more memory than 9.5? I was able to run the db pod locally with a 10GB CRC cluster.

**Comment by dhirajsb** [comment]
@phantomjinx looks like we fixed the same issue with version too #6919

**Comment by phantomjinx** [comment]
> @phantomjinx so PostgreSQL 9.6 requires a lot more memory than 9.5? I was able to run the db pod locally with a 10GB CRC cluster.

Actually, silly thing was that I was able to run up 9.6 with only a 100MB requirement. It was just weird that syndesis-db would not come up with 512MB requirement. Anyway, seems to have been an anomaly since it hasn't happened since.

**Comment by lgarciaaco** [comment]
@dhirajsb can we close this issue?

**Comment by dhirajsb** [comment]
Closing since we have support for CRC in syndesis build scripts. CRC itself has issues running in low resource machines, which are out of scope for this issue.
