### ISSUE TITLE
Quickstart script; more checks

### ISSUE THREAD

**Issue by assimbly** [syndesisio/syndesis#6932]
## Description

When following the quickstart (https://github.com/syndesisio/syndesis-quickstarts/blob/master/README.md#syndesis-quickstarts), it would be good when the bash script has more checks/information. For example:

1) Is MiniShift on the path?
2) If MiniShift is not on the path, ask to download/install minishift:

https://gist.github.com/steinwaywhw/a4cd19cda655b8249d908261a62687f8

3) Check (or set by script) if other things like rights and kvm are setup (https://docs.okd.io/latest/minishift/getting-started/setting-up-virtualization-environment.html#for-linux)

4) I currently get the following error:

-- Starting Minishift VM ....... FAIL E1004 11:24:51.647162    3143 start.go:494] Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: virError(Code=8, Domain=44, Message='invalid argument: could not find capabilities for domaintype=kvm '). Retrying.
Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: virError(Code=8, Domain=44, Message='invalid argument: could not find capabilities for domaintype=kvm ')

This on Fedora 30 where Minishift and installed according the website. The Fedora instance is running in Virtualbox. Is it possible to install/run Syndesis from with Virtualbox?

**Comment by zregvart** [comment]
I think there should be a line drawn between the prerequisites such as minishift and the Syndesis, otherwise we end up maintaining tooling for supporting projects outside of our sphere.

We could and I think for a degree we do check for prerequisites, this can be improved. Those checks should be limited to the basic availability of those tools, further checks, such as the ones in 3. should not be in scope of this project.

For the issue you're facing you might to consult the minishift issue tracker, for example the issue https://github.com/minishift/minishift/issues/1630 seems relevant.

**Comment by assimbly** [comment]
Thanks for the link.

On the prerequisites. I understand the reasoning. Actually this is seen by a lot of (especially Linux) web projects for local installation (while for desktop apps one can just use the package manager). For web/microservices projects it bothers me every time as the installation takes more time and leads to mistakes (bitnami was created for this reason). If you buy a car, you normally just want to drive away and not first bring the gasoline and build the road. 

Thinking from an user point of view I want to use Syndesis to work on integrations. Installation should be as easy and straightforward as possible (even if it's a complete container cluster). Better checks or some automation would be certainly welcome.

**Comment by zregvart** [comment]
I disagree on the need to extensively work on installing and setting up prerequisites as a part of Syndesis installation. I see a clear line between the responsibilities of Syndesis vs responsibilities of setting up dependencies needed to run OpenShift via minishift.

To extend your analogy, if I sell you the car do I also need to pave the road to your house?

That being said, we're working on easier ways for the getting started experience by providing the installation via operator from operatorhub.io and a standalone version that would not require you to run Syndesis on OpenShift for design time tasks.

And this feedback is valuable, it shows that there's further need for better getting started experience and it validates our commitment to it.

**Comment by assimbly** [comment]
"installation via operator from operatorhub.io and a standalone version that would not require you to run Syndesis on OpenShift for design time tasks."

Great to hear

"if I sell you the car do I also need to pave the road to your house?"

In my country yes (the parking lot as well), ask Kurt on this one :)

**Comment by KurtStam** [comment]
Here is a thought, maybe we can add a `check-environment`script that we can offer to run (y/n) if the install.sh returns anything not 0?
