### ISSUE TITLE
Syndesis s2i cannot resolve camel version that is built within pipeline

### ISSUE THREAD

**Issue by cunningt** [syndesisio/syndesis#695]
Syndesis s2i does a maven build within the Dockerfile.    It seems that this cannot resolve the camel version that we've built inside the pipeline that is hosted on the ea repository (in this case, 2.21.0.fuse-000007).   

I'm not sure what the correct fix here is - can we add the EA repository as a `<repository/>` here?

`[INFO] F8: Removing intermediate container 94393f01f722
[INFO] F8: Step 4/5 : RUN cd /tmp/artifacts/m2/project  && mvn --batch-mode -Dmaven.repo.local=/tmp/artifacts/m2 package -DskipTests -e -Dfabric8.skip=true  && rm -rf /tmp/artifacts/m2/project  && chgrp -R 0 /tmp/artifacts/m2  && chmod -R g=u /tmp/artifacts/m2
[INFO] F8: ---> Running in fbc828d93927
[INFO] F8: [91m[0m
[INFO] F8: [INFO] Error stacktraces are turned on.
[INFO] F8: [INFO] Scanning for projects...
<cut>
[INFO] F8: [ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Could not find artifact org.apache.camel:camel-spring-boot-dependencies:pom:2.21.0.fuse-000007 in central (https://repo.maven.apache.org/maven2) @ line 39, column 19
[ERROR] 'dependencies.dependency.version' for org.apache.camel:camel-spring-boot-starter:jar is missing. @ line 177, column 17
 @
[INFO] F8: [ERROR] The build could not read 1 project -> [Help 1]
[INFO] F8: org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Could not find artifact org.apache.camel:camel-spring-boot-dependencies:pom:2.21.0.fuse-000007 in central (https://repo.maven.apache.org/maven2) @ line 39, column 19`

**Comment by zregvart** [comment]
Done with #811
