### ISSUE TITLE
Connector "pipe" actions

### ISSUE THREAD

**Issue by squakez** [syndesisio/syndesis#6978]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
While working on documentation tasks I noticed that UI is not handling any connector action marked with the `pipe` pattern ([this is the only example found in our code base](https://github.com/syndesisio/syndesis/blob/master/app/connector/activemq/src/main/resources/META-INF/syndesis/connector/activemq.json#L293)).

## How to reproduce
Create a timer to log integration and then try to add a `pipe` action between them, at the moment the only one available is the activemq `io.syndesis.connector:connector-activemq-request`. This is not shown in the list of actions.

**Comment by zregvart** [comment]
Some discussion on this in #1993

**Comment by squakez** [comment]
Thanks @zregvart, I had a look on those conversation and I think the feature was introduced in old UI: https://github.com/iocanel/syndesis/commit/4bde21aa963d385e4d1a03dac6ae62544d42cf59

@gashcrumb can you have a look to confirm if that was ported to react-ui? From the [code line](https://github.com/syndesisio/syndesis/blob/master/app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts#L373) you provided to me yesterday it seem it was not the case. Should consider this a regression?

**Comment by gashcrumb** [comment]
Yeah, that'll need to be adapted to that function I linked to.

**Comment by squakez** [comment]
Thanks for confirming that. I've changed the description to report as a regression. Please, let me know if I can help with that.

**Comment by gashcrumb** [comment]
I wonder how exactly this manifests in the UI today.  Looking at the logic I don't see that there'd be a problem.

**Comment by squakez** [comment]
Going to add steps to reproduce the issue in the main description. Actually the action `io.syndesis.connector:connector-activemq-request` is never exposed by the UI. As far as I understood the `pipe` should be presented when it's an action between 2 steps.
