### ISSUE TITLE
DB Connector: SQL parser doesn't recognize parameters for LIKE

### ISSUE THREAD

**Issue by Stefan365** [syndesisio/syndesis#698]
e.g. 
this is ok:
```
DELETE FROM TODO WHERE task = :#task
```

but datamapper cannot recognize these parameters:
```
DELETE FROM TODO WHERE task LIKE ':#task'
DELETE FROM TODO WHERE task LIKE '%:#task%'
```

**Comment by KurtStam** [comment]
I think you got an error? This error should have been shown at the action configuration time (see also https://github.com/syndesisio/syndesis/issues/718). So it's nothing to do with the datamapper, but with our parser instead. That said, will try to fix it.

**Comment by Stefan365** [comment]
I don't see any error in web console.
It seems parser doesn't have problem with query, but I have problem with the parser.
If I create datamapper step subsequently,
the parameter task has not been recognized (probably because located inside single quotes).
Kindly see attached pictures.
![no_quotes](https://user-images.githubusercontent.com/2714974/34005141-4024b148-e0fa-11e7-91a1-3b1ddada0217.png)
![quotes](https://user-images.githubusercontent.com/2714974/34005149-4483d75a-e0fa-11e7-8ac9-2b02dc3aab87.png)

**Comment by KurtStam** [comment]
@Stefan365 as far as your datamapper screenshots, you can only get at the moment because of #718.  So now you arrive at the datamapper with an invalid dataShape. You can verify the error in your console when saving the action config (but bc of #718, it keeps going)

**Comment by Stefan365** [comment]
@KurtStam this is my result with 
DELETE FROM TODO WHERE task LIKE ':#task' 
(see picture)
It is not clear to me how to infiltrate '%' in input parameter. 
![quotes2](https://user-images.githubusercontent.com/2714974/34005846-86df929a-e0fc-11e7-8c17-ae16029b242f.png)
e.g. you want to delete all todos which tasks contains first_name (from Contact). how do you proceed?

**Comment by KurtStam** [comment]
@Stefan365 Like I said before the inputDataShape was calculated incorrectly. This is what my commit fixes. So with that fix you should be able to issue exactly what you did:
`DELETE FROM TODO WHERE task LIKE ':#task'`
where you can make `task` to `firstName`. I think in the datamapper you maybe able to enhance that value to concatenate it with `%` signs. You cannot do it in the query.

**Comment by KurtStam** [comment]
Please reopen if this is still an issue for you.

**Comment by Stefan365** [comment]
hi @KurtStam ,
I see this behavior again. 
if I put e.g. DELETE FROM TODO WHERE task LIKE ':#task' as target connection action.
I don't have option to add Data Mapper step, since ':#task' is not visible for DM. If I change it to :#task, parameter is recognized as should be.

Checked on CR1(see https://gist.github.com/dsimansk/b839cbd39e553ec4680bcd8a3b47c3ff) and Syndesis master branch.

**Comment by Stefan365** [comment]
@KurtStam one more thing,
IMHO If I look at ... LIKE '%:#param'... vs. ... LIKE ':#param' + padStringLeft '%' in datamapper 
I'm finding first option more user friendly than the second one (as a user how should I know, there is some 'padStringLeft' option in DM? moreover if I'm familiar with SQL regex)

Is there any possibility to allow  " '%:#param' syntax" in the future?

**Comment by KurtStam** [comment]
@Stefan365 You're right, I mistyped above, there are not supposed to be any quotes.

At the moment finding a parameter relies on the fact that it starts with `:#`. So if we use a prefix `%` we're mixing a variable name with SQL syntax. Not sure Camel itself even supports that. That said I'm sure we can sort of 'preprocess' the statement if we really want to support it, but it's not that easy.

**Comment by Stefan365** [comment]
@KurtStam In that case (no quotes only) LIKE cannot be used at all.
Just one question, did it never work? I'm quite sure it worked (LIKE ':#param') for some time period.

**Comment by KurtStam** [comment]
@Stefan365 I added this test back then:

https://github.com/syndesisio/syndesis/blob/master/app/connector/sql/src/test/java/io/syndesis/connector/sql/common/SqlParserTest.java#L148-L155

and it's tested with Oracle, Postgresql, Mysql and Derby.

**Comment by KurtStam** [comment]
@Stefan365 I would say that if the Camel SQL component starts supporting it, then we should add support for it too. Can you open a ticket with the Camel project?

**Comment by Stefan365** [comment]
hi @KurtStam since July I don't work for RedHat, contact please someone else from syndesis-qe team.
