### ISSUE TITLE
Better cooperation between Dev and QE

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#7]
Development should have more insights in QE. It is especially important that developer can run QE tests on their own easily or at least where to look at our development environment. QE tests need better visibility. 

Developers should also help QE to automate test, ideally already when implementing features. This should happen in an agile and flexible way.

**Comment by rhuss** [comment]
Also, we need a review process for the BDD stories written by QE. The review can be done by engineering, but also PM.

Suggestion: Use regular GitHub PR review process and actively assigning an engineer / pm ? // @dsimansk

**Comment by dsimansk** [comment]
@rhuss yes PR review all the way. 
So for two main scenarios, API connector and Tech extensions, I've create tasks to create such a scenario. Those task already have an assigne to work on. I'd image that draft BDD scenario will follow after submitting feature proposal PR. Preferably during feature proposal review to accommodate mutual feedback, wdyt? And feature guard would carry-on the review or add more eyes etc.?

**Comment by gashcrumb** [comment]
Does this need to stay open?
