### ISSUE TITLE
UXD for visual indicator when data types don't match

### ISSUE THREAD

**Issue by kcbabo** [syndesisio/syndesis#700]
We should have some visual indicator in the UI when data types don't match.  For example, when setting up Twitter to Salesforce, the output data from Twitter does not match the input data for Salesforce.  This may not be obvious to the end user, yet we have all the information we need to make the user aware.  I suspect this will become really important with tech extensions as they are type-aware and the user really has no knowledge of what's happening inside.

Some suggestions:
- All steps/connections in an integration flow should have a visual indicator of input and output types.  This could be a hover, click, whatever.
- When the current data shape does not match the input shape of a step/connection, a visual indicator should be displayed indicated that the situation must be resolved (e.g. data mapping, data type step, etc.).

@rhuss @gashcrumb @amysueg : UXD and UI components here.  I don't think any backend work is required.

**Comment by igarashitm** [comment]
@dongniwang had a question if we want to suggest adding datamapper step to the users. I think there are 2 options for users there, 
* #1110 add datamapper
* #1136 change data shape via action config

How do we want to suggest these 2 options to the users would be an UXD thing.

**Comment by amysueg** [comment]
thanks, @dongniwang , let me know if you want to discuss ideas for this.

**Comment by kcbabo** [comment]
Maybe we do it this way ...

If a step (which includes connections) in a flow requires a specific data type and no data type is provided, then we notify the user that the connection requires a specific data type and the current data is untyped (with a link to doc on setting data type in action config).

If a step in a flow requires a specific data type and a different data type is provided, then we notify the user that a data mapping step is required to resolve the difference.

These two approaches are complementary.  In the case where a user starts with JMS (typeless) and finishes with Salesforce, they would first see a notification that a data type needs to be specified and once that's complete they would see a follow-up message that a data mapping is required.  That matches the reality as the user needs to perform two separate tasks to resolve the issue.

**Comment by igarashitm** [comment]
Thanks Keith, that sounds promising. I was not really aware that only typeless connection have an option to define a data shape in action config.

**Comment by dongniwang** [comment]
Hi @kcbabo and @igarashitm, I have a few questions:
- Is the data shape associated with each connection OR connection actions? Could different connection actions have different data types? 
- Can you give me some examples what data type information we want to show to the users? Is it like .xml .json OR something else? I'm trying to access how much space we need to display that information, so it would really helpful to get some real examples. 

Thank you!

**Comment by kcbabo** [comment]
> Is the data shape associated with each connection OR connection actions? Could different connection actions have different data types?
Connection action.  Different actions on a connection could have different data types.

**Comment by dongniwang** [comment]
@kcbabo thanks for the clarification! 

Then what are some of the example data types we want to display to the users then? Is it just simply ".json" OR "string"? 

cc: @igarashitm

**Comment by igarashitm** [comment]
That sounds like we need to file yet another issue, "Visualize data types for each Action". Do we need to assign some fancy name for the data shapes? Or just "Step 1 / Action 1 / output" is enough?

BTW, from UI model perspective, there is only one `Action` for each `Step` (connection is a kind of Step here). I don't completely understand those multiplexity here, @gashcrumb could you help me?

**Comment by kcbabo** [comment]
@dongniwang are you asking for sample data to show to users or just to validate the UI/UX flow?

**Comment by kcbabo** [comment]
@igarashitm From a user perspective, the can select a connection as a step.  Once they do that, there are a set of actions available on that connection.   Once they select the action, then they have an option of specifying data types if they want.

**Comment by dongniwang** [comment]
@kcbabo  - sample data to show to users. I'm trying to understand how much real estate we need to display the information. 

What do you mean by "validate the UI/UX flow"?

**Comment by kcbabo** [comment]
Let's step back a second.  I think we said the user will have the following three mechanisms for specifying data type:

- Upload a file containing data type information 
- Specify a URL containing data type information
- Enter the data type information directly

The third scenario is the only time where sample data would be helpful.  Most times it will be copy/paste.  If we want to show examples, then we would need examples of the following:

- JSON schema
- JSON instance document
- XML schema
- XML instance document

If we want to show examples of all the above, I suggest we pick a specific example entity with a limited number of fields and use that for all types.  For example, Person object with firstName and lastName fields.  Here's an example of what that looks like for JSON schema:
http://json-schema.org/examples.html

Should be trivial for someone to create JSON instance, XML schema and XML instance document equivalents of that.

**Comment by dongniwang** [comment]
@kcbabo - Ah, my bad, I misunderstood your question! You're right, I'm not asking to show example schema type document. And based on UX design PR #1194, we have the copy/paste function already. 

I'm actually asking based on what you've described below 
> All steps/connections in an integration flow should have a visual indicator of input and output types. This could be a hover, click, whatever.

What is an input/output type? What exactly are we showing to users when hover, click or whatever? 

Is it something like "Input data type: .string" "output data type: .xml"?

**Comment by dongniwang** [comment]
And to @igarashitm - We now have the design for describe data as part of action config. [here](https://github.com/syndesisio/syndesis/blob/master/ux/designs/describe-data/describe-data.md).

**Comment by kcbabo** [comment]
Ah - these type names are already defined and used within the UI as part of the data shape model.  Tomo should be able to provide you an example of what that looks like today.  If it's too ugly for normal users, we can talk about cleaning it up a bit (maybe only showing a subset of the information).

**Comment by igarashitm** [comment]
In short, it's not well defined yet.

`DataShape.type` holds full class name for Java type (e.g. `io.atlasmap.java.test.TestOrder`), and AtlasMap is showing the last part (e.g. `TestOrder`) as a label, and tooltip shows the full classname.

It seems we don't have any for JSON and XML in Syndesis today. We can add a short & readable name for each JSON/XML data types in Syndesis(deployment.json), like `Salesforce` or `Database`. More fancier label could be baked into Action configuration, like `Salesforce Contact` or `Database select * from ...` and like that maybe?

And then we'll need some info which Step that data shape belongs to, so user can see which one needs to be updated. Just put it on a line between the Steps?

**Comment by kcbabo** [comment]
I thought the connection in the flow is supposed to declare this?  When we add a data mapper step in the UI, how does it know that the source JSON is a Salesforce Contact for example?

Adding @gashcrumb for UI perspective

**Comment by gashcrumb** [comment]
So when the data mapper step is loaded currently we scan the integration relative to where in the flow that step is, find `action` instances within `step` objects (for connections and extensions), and look in that `action` object for the data shapes.  

ATM it's still only the most immediate previous and subsequent data shape, there's an open item to add support for multiple previous steps.

**Comment by kcbabo** [comment]
So I think the only missing piece is actually showing that information to the user for each step, right?

**Comment by gashcrumb** [comment]
@igarashitm here's the [test](https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/integration/edit-page/current-flow.service.ts#L478-L490)

And also this is where the [scanning is done](https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/integration/edit-page/step-configure/step-configure.component.ts#L188-L200)

**Comment by gashcrumb** [comment]
The only issue I see is that currently we're kinda lazy-loading the datashape from the backend as you open the data mapper.  I'm not confident that we actually have correct type information that the side-panel can display without having to add more calls to the backend to fetch this information.

**Comment by igarashitm** [comment]
OK, so it seems the verifier is returning a `title` which is eventually pushed into DataShape.type, and used for Document label. It's a short string, for example `SQL_PARAM_IN` and `SQL_PARAM_OUT` for database connection.

**Comment by dongniwang** [comment]
I think it would be great for us to display human readable data type information. How can we make that happen? Something like `SQL_PARAM_IN` `SQL_PARAM_OUT` just don't add much value here for the users in my opinion.

**Comment by igarashitm** [comment]
Those seem to be coming from each connector verifier, and we are missing human readable label on its schema. Filed an issue #1245 to introduce human readable label and description.

**Comment by dongniwang** [comment]
UX design PR #1671 is created to address this. Please review.

**Comment by igarashitm** [comment]
#1671 has been merged. Thanks @dongniwang :+1:
