### ISSUE TITLE
Merge teiid-syndesis into syndesis repo

### ISSUE THREAD

**Issue by vhalbert** [syndesisio/syndesis#7035]
<pre><code>
[x ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

Merge the teiid-syndesis repo (UI for DV) into the syndesis repo, see [teiid related jira ](https://issues.jboss.org/browse/TEIIDTOOLS-752)

**Comment by vhalbert** [comment]
Initially, Teiid would like to setup teiid-syndesis as a submodule in syndesis so that the build and integration changes can be worked out for 1.9.    With the goal of 1.10, teiid-syndesis could possibly be moved into syndesis.

**Comment by zregvart** [comment]
I say, go for it. Try to do a PR that includes the CircleCI configuration also. Depending on how deep you want to integrate, changes to the `tools/bin/syndesis` script will be needed and the strict checks we have setup will require some code to be refactored.

Perhaps do it piecemeal.

**Comment by zregvart** [comment]
There are some bits in here: https://github.com/syndesisio/syndesis/tree/master/tools/monorepo-migration that might help with that, we used those when we migrated over several git repositories into the single one.

**Comment by vhalbert** [comment]
teiid isn't wanting to migrate initially, its wanting to establish it as a sub-module so that you would use the clone recursive option to include teiid-syndesis.

**Comment by vhalbert** [comment]
teiid-syndesis will be introduced at the maven level, by creating a profile that can be used until teiid-syndesis is moved/migrated into syndesis

**Comment by vhalbert** [comment]
PR https://github.com/syndesisio/syndesis/pull/7075

**Comment by vhalbert** [comment]
@zregvart there are problems in the productization process when trying to use submodules, so that is going to be removed.   And it appears that Ramesh [comment ](https://issues.jboss.org/browse/TEIIDTOOLS-752) indicates that he suggest going ahead and moving the teiid-syndesis code into syndesis.   Do you see any issues with doing that now?

**Comment by vhalbert** [comment]
The merge  PR:  https://github.com/syndesisio/syndesis/pull/7192

**Comment by zregvart** [comment]
@vhalbert time to close this, perhaps we can open new issues for any outstanding integration tasks?

**Comment by vhalbert** [comment]
@zregvart yes,   dv is now building in syndesis, the image is also being generated.   the release was just update to include the image in the nightly builds.   The IPaas dev build in product builds was just successful.    So any future issue should have a new issue opened.
