### ISSUE TITLE
Icon generator for custom connectors

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#705]
When creating a new custom connector, for instance via [New API connector wizard](https://github.com/syndesisio/syndesis/blob/master/ux/designs/apiconnector/apiconnector.md#general-connector-info) we should generate a placeholder icon for that the user can use instead of uploading a icon.

We have implemented serving of icons in #475, now we need a initial icon generator. This could be a random generated icon, or it could be a favicon fetched from the remote API/website.

**Comment by rhuss** [comment]
@jimmidyson @zregvart is this issue still something relevant ? Should it be taken over to Sprint 23 ?

**Comment by zregvart** [comment]
Yup, we were hoping on getting this for TP3 but pushed it to TP4 as non-essential.

**Comment by zregvart** [comment]
@syndesisio/uxd we're looking into generating icons if none are uploaded when creating custom API connectors, any guidelines we should abide by?

I see the following constraints, but could be wrong:
 - should be round (circle, we display icons with a blue circle surrounding them)
 - should be sized at 50x50 pixels

Could be based on the [Syndesis glasses icon](https://github.com/syndesisio/syndesis/blob/master/app/ui/src/assets/images/glasses_logo.svg), for instance three concentric circles of alternating color, we can take [colors from patternfly](https://www.patternfly.org/styles/color-palette/) picked at random.

**Comment by dongniwang** [comment]
I thought we're going to use a generic one if users don't upload their own icons. Why do we need to generate icons for them? I probably missed some discussion, cc @amysueg @sjcox-rh here for their input.

**Comment by zregvart** [comment]
@dongniwang that could work also (less things to work on), in a very early brainstorm we came to the idea of generating unique icons for each API connector as a way to distinguish one from another.
I guess the only place this can create a confusion is in the [integration editor navigation](https://github.com/syndesisio/syndesis/blob/master/ux/designs/navigation/navigation_breadcrumb_integration.md) where we don't display the name of the connector (just the name of the action).

**Comment by dongniwang** [comment]
Actually, I thought we're displaying the connection name when users hover over the connection icons. cc @gashcrumb

**Comment by gashcrumb** [comment]
We were at one point in the editor, but apparently now we're not for some reason.

**Comment by zregvart** [comment]
Based on @deeleman's suggestion I made an icon generator to provide icons if the user doesn't provide one, they look like:

![out0](https://user-images.githubusercontent.com/1306050/35214908-05732a2a-ff63-11e7-9ceb-502e17c7a791.png)
![out1](https://user-images.githubusercontent.com/1306050/35214909-05a0e08c-ff63-11e7-93d4-55a2f353f57a.png)
![out2](https://user-images.githubusercontent.com/1306050/35214910-05ba32a8-ff63-11e7-92d1-0d528230970d.png)
![out3](https://user-images.githubusercontent.com/1306050/35214911-05e06018-ff63-11e7-90c0-9b52919158f5.png)
![out4](https://user-images.githubusercontent.com/1306050/35214912-05f9d64c-ff63-11e7-9fa0-11ca5f96e4e1.png)
![out5](https://user-images.githubusercontent.com/1306050/35214913-0612d552-ff63-11e7-9294-3616c2b7f8c0.png)
![out6](https://user-images.githubusercontent.com/1306050/35214915-0649c5a8-ff63-11e7-9f49-e728117582b6.png)
![out7](https://user-images.githubusercontent.com/1306050/35214916-066521b8-ff63-11e7-8492-a096f278cafb.png)
![out8](https://user-images.githubusercontent.com/1306050/35214917-067e8a22-ff63-11e7-9a6c-aaade8e20d63.png)
![out9](https://user-images.githubusercontent.com/1306050/35214918-06965f8a-ff63-11e7-8946-d2f3e8bf61e0.png)
![out10](https://user-images.githubusercontent.com/1306050/35214919-06b0f20a-ff63-11e7-8634-a86a692032a7.png)

The generator is based on a SVG file that is rendered to PNG with a random color from patternfly styles:

[template.svg](https://github.com/syndesisio/syndesis/files/1651511/template.svg.txt)

The single letter is the first letter from the connector name.

@dongniwang does this make sense to you?
