### ISSUE TITLE
Logging is broken in the UI

### ISSUE THREAD

**Issue by RHodzelmans** [syndesisio/syndesis#7052]
## This is a...
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
I have the same issue, when I open my URL:
https://syndesis-fuseonline.apps.jfall2.rhtesting.nl/project/fuseonline/browse/pods/i-jfall-integration-1-build?tab=logs

I tested it in 2 OCP 4.2 AWS clusters:
![ScreenshotOfLink](https://user-images.githubusercontent.com/2842380/67848835-bdd87a80-fb05-11e9-9fc1-91bd6e122448.png)
![ScreenshotOf404](https://user-images.githubusercontent.com/2842380/67848834-bdd87a80-fb05-11e9-83f2-0b46ef137af4.png)

I have the diagnostics, but I'm a little hesitant to attach them to this bug

Is it an regression of [this issue?](https://github.com/syndesisio/syndesis/issues/3617)

**Comment by riccardo-forina** [comment]
No, it's a different thing. Just to be sure I'm getting this right, the problem is that if you click on the "View logs" link you get the 404 error page, right? Can I ask you to copy the URL from the address bar and try opening it in a new tab?

**Comment by riccardo-forina** [comment]
Actually, I take it back. It will not work, the problem I think is in the `consoleUrl` property supplied to the app in its [`config.json` file](https://syndesis-fuseonline.apps.jfall2.rhtesting.nl/config.json).

It's `` but it should be the url of the Okd console instead.

**Comment by RHodzelmans** [comment]
OCP ;-) 

[syndesis.zip](https://github.com/syndesisio/syndesis/files/3788280/syndesis.zip)

**Comment by riccardo-forina** [comment]
Right, that one 😂

**Comment by KurtStam** [comment]
@riccardo-forina is it a UI thing and something you can fix?

**Comment by riccardo-forina** [comment]
It’s a config thing, that `consoleUrl` property requires the right value

**Comment by gashcrumb** [comment]
Yeah, `consoleUrl` is set at installation time.  You can fix it after the fact by modifying the `syndesis-ui-config` config map and fill in the property there, it should include the `/console` bit too.

That being said, the URLs the Syndesis UI calculates to link you over to the pod log is based on the 3.x console, so it's quite brittle, it may not even work for 4.x.  Going forward for this to work properly we need some metadata or API that we can query to build appropriate links.
