### ISSUE TITLE
Include tech extensions sample in this repo

### ISSUE THREAD

**Issue by apupier** [syndesisio/syndesis#707]
Currently they are here:
- https://github.com/lburgazzoli/syndesis-extension-example-xml
- https://github.com/lburgazzoli/syndesis-extension-example

We need to have them in the pipeline too to ensure examples are still working. (can be done in a second step, please create another issue if it is the case)

**Comment by gashcrumb** [comment]
I think we have a separate repo for extensions on purpose...

**Comment by apupier** [comment]
https://github.com/syndesisio/syndesis-extensions dedicated repo has been created (a month later my request)
