### ISSUE TITLE
Camel version bump script

### ISSUE THREAD

**Issue by squakez** [syndesisio/syndesis#7081]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

We actually have a manual procedure to bump camel artifact version that involves changing several files. Recent changes in operator are bringing in more places where to store such information (see #7073), being error prone.

## Acceptance criteria

Have a single command in the `syndesis` CLI to use and automatically update all the places where the camel version is configured.

**Comment by squakez** [comment]
@claudio4j I noticed you worked on it (#7076) after creating the issue here! Do you think can have an other iteration and make sure to include it in `syndesis` CLI as well with related `man` documentation?

**Comment by claudio4j** [comment]
This https://github.com/syndesisio/syndesis/pull/7096 change generates the install/operator/pkg/generator/assets_vfsdata.go and displays a message for the user to add/commit the changes.

**Comment by squakez** [comment]
Good. I think we still need to integrate that script into `syndesis` CLI. Something to allow us calling `syndesis bump --camel <version>` or something like that. The procedure to have the script integrated is explained here: https://syndesis.io/docs/cli/#commands. It would be a very nice addition!
