### ISSUE TITLE
Local operator binary refresh

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#7085]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Right now the `syndesis` shell script downloads the newer version of the `syndesis-operator` binary from GitHub release assets only if there is no `$HOME/.syndesis/bin/syndesis-operator` (see #7084).

After some time the operator binary might get quite old and unable to install Syndesis. Should we make it so that the operator binary is downloaded each time, once in a while (re-download if it's older than a month?), or if the user specifies so on the command line.

Would be also rather cool to have the operator binary have the ability to auto-update itself.

cc @lgarciaaco @phantomjinx @KurtStam

**Comment by lgarciaaco** [comment]
@zregvart there is an option `-f  --force-binary-download` already for that.

**Comment by zregvart** [comment]
We could add a notice that a newer version exits. Perhaps adding auto update / download mechanism to the operator binary could serve us better in the long run.

**Comment by lgarciaaco** [comment]
I still think this doesn't serve much purpose.

**Comment by zregvart** [comment]
I think our story around installing a specific version could be improved, if the goal is to install the latest version by default, then it would make sense for the operator binary to be up to date with the latest. I think this would help us with any issues that we fix in the operator, at least we wouldn't have to tell the users that a newer version fixes the issue they have.

**Comment by lgarciaaco** [comment]
That's once use case, but there might be users that are happy with the current version they have and they don't want an upgrade, specially when the newer version might bring some bugs. Ideally we find a solution that fits both worlds
