### ISSUE TITLE
`syndesis minishift --install --tag` installs `latest`

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#7086]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Seems that when we install like:

```shell
$ syndesis minishift --install --nodev --tag 1.8.12
```

The `latest` version is installed not `1.8.12`.

cc @lgarciaaco

**Comment by ryckowski** [comment]
It looks like there's no priority to fix installation the stable, it's a pity as installation from master is broken so often in the last weeks
