### ISSUE TITLE
MongoDBConnectorCappedCollectionConsumerTest is flaky

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#7115]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

[Daily release failed](
https://ci.fabric8.io/blue/organizations/jenkins/syndesis-release-daily/detail/syndesis-release-daily/652/pipeline) because of failing test in MongoDBConnectorCappedCollectionConsumerTest.

**Comment by zregvart** [comment]
Still an issue according to the [daily release failure](https://ci.fabric8.io/view/syndesis/job/syndesis-release-daily/lastFailedBuild/):

```
[ERROR] Failures: 
[ERROR]   MongoDBConnectorCappedCollectionConsumerTest.repeatMongoTest:90->mongoTest:84 mock://result Received message count. Expected: <1> but was: <2>
```

**Comment by squakez** [comment]
Thanks @zregvart. I'll keep investigating. The problem is that I cannot replicate locally, neither in CircleCI build.

**Comment by zregvart** [comment]
On [Circle CI](https://circleci.com/gh/syndesisio/syndesis/175415) we have a different test that's flaky. Perhaps we could refactor those tests as [integration tests](https://github.com/syndesisio/syndesis/tree/master/app/test/integration-test) and move them to the nightly build. And have only unit tests in the connector?

**Comment by squakez** [comment]
I thought[ embedded mongo library](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo) was quite stable but it seems is not. Let me see if I manage to fix, otherwise I'll refactor and remove the embedded lib.

**Comment by squakez** [comment]
I may take back my words... there were a few flaws in the test cases. @zregvart I think the only way to confirm the issue is fixed is to wait the merge to master and following nightly build, am I correct?

**Comment by zregvart** [comment]
@squakez we can trigger the daily build at any point...

**Comment by squakez** [comment]
Thanks. I'll wait the merge and push the daily to confirm if it's fixed.
