### ISSUE TITLE
Should we delete Connections when deleting a Connector

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#712]
With #657 we have functionality of deleting a connector, should we delete Connections defined for that Connector?

cc @chirino @kcbabo

**Comment by kcbabo** [comment]
I don't think we should allow a connector to be deleted if there are connections using it.  User should clean up connections first, then delete the connector.

BTW, are we going to allow any type of connector to be deleted or just API connectors?

**Comment by zregvart** [comment]
> BTW, are we going to allow any type of connector to be deleted or just API connectors?

We currently do not restrict this on the backend, though the functionality to delete a Connector is available only on the [API Connector list page](https://github.com/syndesisio/syndesis/blob/master/ux/designs/apiconnector/apiconnector.md#api-connector-list)

**Comment by zregvart** [comment]
We now disable the Delete button if the Connector is used, i.e. if there are Connections using the Connector. Done via #847
