### ISSUE TITLE
Provide a specific name for Tech Extension model object json file

### ISSUE THREAD

**Issue by apupier** [syndesisio/syndesis#714]
it will allow to bind json schemas more easily.

**Comment by lburgazzoli** [comment]
@apupier can you give an example of what you'd expect ?

**Comment by apupier** [comment]
currently it is called extension-definition.json

I expect something very specific to Syndesis to avoid naming collisions as far as possible.
Two proposals:
- syndesis-tech-extension-definition.json
- syndesis-extension-definition.json

**Comment by lburgazzoli** [comment]
yeah but it is in a folder named syndesis

**Comment by apupier** [comment]
> yeah but it is in a folder named syndesis

At least Eclipse JSON editor is based on the file name uniquely and I think that I see some Language Server Protocol for JSON doing the same (to check)

**Comment by lburgazzoli** [comment]
ok, it is a little ugly but let's have the following naming:

- syndesis/syndesis-extension-definition.json 
- syndesis/syndesis-extension-definition-schema.json

Is that ok ?

**Comment by apupier** [comment]
ok for me
