### ISSUE TITLE
Timer unexpectedly fires multiple times during startup

### ISSUE THREAD

**Issue by dudash** [syndesisio/syndesis#7156]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
I've built a simple integration triggered by a timer. The timer is set to fire every 1 hour and send a message to a slack channel. However, upon integration start I get unexpected multiple firings of the job. After startup is complete, the timer behaves as expected. 

See the screenshot below.

Was using Fuse Online (as part of Integreatly 1.5.1 which I think means Syndesis 1.7.25).

![cron-msgto-slack](https://user-images.githubusercontent.com/116840/69092559-a7458500-0a1a-11ea-87e9-5528e21cabb0.png)

**Comment by squakez** [comment]
Thanks for the report. Would it be possible to export the integration and post it here? Also the first part of the log would help troubleshooting.

**Comment by dudash** [comment]
Unfortunately, I no longer have that integration or its logs. But I will try to recreate this issue and get logs.

**Comment by dudash** [comment]
I'm not able to recreate this in my new environment. I'm thinking that it's likely it might have been a problem with the pod restarting; and not necessarily syndesis.

**Comment by squakez** [comment]
No problem. I am going to close this for now. Feel free to reopen or open a new issue if the problem come back.
