### ISSUE TITLE
Community install is broken

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#7157]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[*] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Luis  - I can work on this tomorrow, can you let me know why this broke and how to go about fixing it? The binary does not seem to be in the repo anymore.

bash <(curl -sL https://syndes.is/start)
=====================================================================
SYNDESIS QUICKSTART

Hybrid integration on OpenShift made easy
=====================================================================

Prerequisites: Minishift https://www.okd.io/minishift/
Quickstarts: https://github.com/syndesisio/syndesis-quickstarts/blob/master/README.md#4-lets-run-some-quickstarts

This install will reset your current MiniShift. OK to continue [y/N]? y
/var/folders/df/1qgnc1j10yj57p592sjvl8100000gn/T/tmp.EgxeCMUk ~
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   124    0   124    0     0    427      0 --:--:-- --:--:-- --:--:--   426
100 48.1M    0 48.1M    0     0  2634k      0 --:--:--  0:00:18 --:--:-- 3602k
Archive:  ./master.zip
7de2dda1e2eb77a8c37e73ef1c0ce8a04066dc47
   creating: syndesis-master/tools/bin/
   creating: syndesis-master/tools/bin/commands/
   creating: syndesis-master/tools/bin/commands/binaries/
 extracting: syndesis-master/tools/bin/commands/binaries/README.md  
  inflating: syndesis-master/tools/bin/commands/build  
  inflating: syndesis-master/tools/bin/commands/completion  
  inflating: syndesis-master/tools/bin/commands/crc  
  inflating: syndesis-master/tools/bin/commands/dev  
  inflating: syndesis-master/tools/bin/commands/doc  
  inflating: syndesis-master/tools/bin/commands/install  
  inflating: syndesis-master/tools/bin/commands/integration-test  
  inflating: syndesis-master/tools/bin/commands/kamel  
  inflating: syndesis-master/tools/bin/commands/minishift  
  inflating: syndesis-master/tools/bin/commands/release  
  inflating: syndesis-master/tools/bin/commands/release.bats  
  inflating: syndesis-master/tools/bin/commands/system-test  
   creating: syndesis-master/tools/bin/commands/tests/
  inflating: syndesis-master/tools/bin/commands/tests/test-oc-version.sh  
  inflating: syndesis-master/tools/bin/commands/ui  
   creating: syndesis-master/tools/bin/commands/util/
  inflating: syndesis-master/tools/bin/commands/util/camel_k_funcs  
  inflating: syndesis-master/tools/bin/commands/util/common_funcs  
  inflating: syndesis-master/tools/bin/commands/util/maven_funcs  
  inflating: syndesis-master/tools/bin/commands/util/openshift_funcs  
  inflating: syndesis-master/tools/bin/commands/util/openshift_funcs.bats  
  inflating: syndesis-master/tools/bin/commands/util/operator_funcs  
  inflating: syndesis-master/tools/bin/commands/util/operator_funcs.bats  
  inflating: syndesis-master/tools/bin/syndesis  
operator binary not found under /Users/kstam/.syndesis/bin/syndesis-operator, attempting to download...
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
unable to download operator from 
unable to download the operator binary, exit
ERROR: Last command exited with 1
~

**Comment by KurtStam** [comment]
BTW I tried the following.

1. I started a fresh minishift, and waited till it was up
`minishift start`
2. I logged in as admin
`oc login -u system:admin`

Logged into "https://192.168.42.194:8443" as "system:admin" using existing credentials.

You have access to the following projects and can switch between them with 'oc project <projectname>':

    default
    kube-dns
    kube-proxy
    kube-public
    kube-system
  * myproject
    openshift
    openshift-apiserver
    openshift-controller-manager
    openshift-core-operators
    openshift-infra
    openshift-node
    openshift-service-cert-signer
    openshift-web-console

Using project "myproject".

3. I downloaded and ran the operator

` ./syndesis-operator install`

cluster resources were installed successfully
operator was installed successfully
error: Object:
  apiVersion: syndesis.io/v1alpha1
  kind: Syndesis
  metadata:
    name: app
    namespace: myproject
  spec:
    addons: null
: no matches for kind "Syndesis" in version "syndesis.io/v1alpha1"

**Comment by lgarciaaco** [comment]
@KurtStam 

For the error:
```
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
```

I can't reproduce it. The build is broken and the operator is 3 days old, but the install script get the binaries from the latest release or prerelease.

```
curl -s 'https://api.github.com/repos/syndesisio/syndesis/releases?per_page=1'
```

You dont see the binaries for the last days but those arent releases, they are just tags.

For your second try, apparently you have an older version of the custom resource. Try deleting the existing custom resource and doing
```
./syndesis-operator install operator
./syndesis-operator install app
```

**Comment by lgarciaaco** [comment]
I also tried installing from the latest binary
```
[lgarciaa@lgarciaa bin]$ oc login -u kubeadmin -p uitiX-XEnnA-vLk7K-YP4Ik --server=https://api.lgarcia.rhmw-integrations.net:6443
Login successful.

You have access to 52 projects, the list has been suppressed. You can list all projects with 'oc projects'

Using project "default".
[lgarciaa@lgarciaa bin]$ oc delete project syndesis && sleep 30 && oc new-project syndesis
project.project.openshift.io "syndesis" deleted
Now using project "syndesis" on server "https://api.lgarcia.rhmw-integrations.net:6443".

You can add applications to this project with the 'new-app' command. For example, try:

    oc new-app centos/ruby-25-centos7~https://github.com/sclorg/ruby-ex.git

to build a new example application in Ruby.
[lgarciaa@lgarciaa bin]$ ./syndesis-operator install cluster
shared resources were previously installed
[lgarciaa@lgarciaa bin]$ ./syndesis-operator install operator
operator was installed successfully
[lgarciaa@lgarciaa bin]$ ./syndesis-operator install app
syndesis application was installed successfully
[lgarciaa@lgarciaa bin]$ oc get pods
NAME                           READY     STATUS      RESTARTS   AGE
syndesis-db-1-bsb8z            2/2       Running     0          93s
syndesis-db-1-deploy           0/1       Completed   0          102s
syndesis-meta-1-deploy         0/1       Completed   0          112s
syndesis-meta-1-ng68q          1/1       Running     0          102s
syndesis-oauthproxy-1-deploy   0/1       Completed   0          110s
syndesis-oauthproxy-1-f64zm    1/1       Running     0          101s
syndesis-operator-1-deploy     0/1       Completed   0          2m29s
syndesis-operator-1-jm79h      1/1       Running     0          2m21s
syndesis-prometheus-1-deploy   0/1       Completed   0          106s
syndesis-prometheus-1-dqzqd    1/1       Running     0          97s
syndesis-server-1-bhfh9        0/1       Running     1          100s
syndesis-server-1-deploy       1/1       Running     0          110s
syndesis-ui-1-deploy           0/1       Completed   0          113s
syndesis-ui-1-phzjk            1/1       Running     0          104s
[lgarciaa@lgarciaa bin]$ 

```

**Comment by zregvart** [comment]
@lgarciaaco I can see your password there, you might want to change it now.

**Comment by ryckowski** [comment]
It's looks like syndesis minishift --install --nodev is broken every other day and stable 1.8.12 just doesn't work for a few weeks. It frustrates me
