### ISSUE TITLE
[Periodic Invocation of Start Action] Entry widget for milliseconds field.

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis#717]
Create a widget/component/service, or similar solution, that converts milliseconds to seconds, minutes, hours, and days.

![Unit Conversion](https://github.com/syndesisio/syndesis/raw/cac32465b92d780a3f0440c5b542b1ece489ae99/ux/designs/databaseconnection/img/help_dropdown.png)

Full design [here](https://github.com/syndesisio/syndesis/blob/cac32465b92d780a3f0440c5b542b1ece489ae99/ux/designs/databaseconnection/databaseconnection.md#create-an-integration-with-database-as-a-start-connection).

@gashcrumb 
> For some of the upcoming designs we have time periods in the generated form. We'll need to add support for a numeric type that has a unit field along with it. Ideally we should support the possibility to have upper and lower bounds per unit. So for example a field that could be in milliseconds, seconds, minutes, hours, the input should be type number with a select next to it to specify the unit.Changing the unit should update any potential min/max bounds on the input field.

NOTE: We will likely be doing away with ng-dynamic-forms at some point (or at least this is still being discussed here #843 ), so we've decided to put this on hold for now.

cc @KurtStam

**Comment by KurtStam** [comment]
@kahboom since this page is autogenerated, the fields would be stacked. Is that ok? If so we'd have to name them something like period-value and period-unit. wdyt? Alternatively we can use just one field, with human filly syntax: http://camel.apache.org/how-do-i-specify-time-period-in-a-human-friendly-syntax.html

Where do we add lower and upperbound value checks in generated forms?

**Comment by kahboom** [comment]
Pushing this to TP4 or Sprint 22.

**Comment by jimmidyson** [comment]
@KurtStam @kahboom So is this going to be implemented for TP3 or not? Who is doing the UI work?

**Comment by KurtStam** [comment]
@kahboom I'm letting you take this one. I figured TP3 was closed but it seems we have this week to get this in, so I reapplied the TP3 label.

**Comment by kahboom** [comment]
@KurtStam - I thought we discussed that this is automatically generated by that library we have, so the only way to control it is via the API? I think you were going to try changing the fields in the API and seeing if it automatically rendered properly in the UI. Did that work?

If not we'll have to skip the lib and build the form manually, which is fine. Just want to make sure we are on the same page.

**Comment by KurtStam** [comment]
@kahboom yes and then I mentioned above that they appear stacked in the form, to which you replied you'd look into creating a custom widget that would deal with the conversion of the time in milliseconds. Just let me know hoe you want to go about this.

**Comment by kahboom** [comment]
Since it involves this library that is proving to be a PITA and I'm trying to stay focused on the API connector before the company shutdown, this is going to have to wait. If I get a chance to take a look beforehand I will be happy to.

**Comment by KurtStam** [comment]
@kahboom is this going to happen for TP4? Anything I can do to help out?

**Comment by gashcrumb** [comment]
@KurtStam why don't we set the `type` for these properties to `duration`?

I can add a custom template to the form service for these properties, until then it'll show up as a regular text field.

I think for a first pass it might be easiest if we just stick to the value as milliseconds or seconds and then the UI just calculates the value.

**Comment by KurtStam** [comment]
@gashcrumb so at the moment it is a `long` and it it contains `milliseconds`, for a the connectors that poll (like DB, Twitter, JMS, etc). Is that an ok contract for now?

**Comment by gashcrumb** [comment]
Just checking, it comes through with `type` set to `integer`, would it be possible to set that to `duration` instead?  Otherwise I'd have to add a custom hack based on the property name and that's not ideal.

**Comment by KurtStam** [comment]
@gashcrumb sure will give that a try and report back.

**Comment by gashcrumb** [comment]
tx, looking at how to create a custom control in the meantime...

**Comment by gashcrumb** [comment]
Have a function control, now just have to fix up the styling, one thing I noticed though is once the `Period` field is set it doesn't seem like you can set it again, i.e. I initially set it to `30000` when I created the integration, when I go back in and change the value and save that, I can see the `PUT` request contains the value I'd expect, however on the subsequent `GET` request when the integration is fetched again I see the value is back to `30000`.  

Wonder @KurtStam can you verify this when you get a chance?  In the meantime I'm going to fix up the styling and finish this up.

**Comment by gashcrumb** [comment]
Here's where we're at, I could leave the bit I have in place that forces this control if you want to give it a test locally?  I'll get a PR open in a few...

![download](https://user-images.githubusercontent.com/351660/35632682-4ceae906-0675-11e8-9355-e9570b1a1bf5.png)
