### ISSUE TITLE
Add Connection button could be more prominent

### ISSUE THREAD

**Issue by jsight** [syndesisio/syndesis#7175]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

I overlooked the (very helpful) "Create Connection" button in the top right during the creation of an integration.

## Expected behavior

More prominence for this button.

## Screenshot

![Screenshot from 2019-11-20 12-14-29](https://user-images.githubusercontent.com/1181549/69261325-599e5900-0b8f-11ea-92de-5d891aa923e4.png)

I was expecting the list of connections ("API Provider", "PostgresDB", etc) to be the full list of available connection types. One way to make it more obvious that this isn't the case would be to add the "Create Connection" as another box, as if it were an existing connection.

For example, it could look like this:
![Screenshot from 2019-11-20 12-18-59](https://user-images.githubusercontent.com/1181549/69261648-f2cd6f80-0b8f-11ea-9dac-9d5c76ecf8e1.png)

Ideally, this would work in a modal window instead of breaking the current flow.

## Tasks involved / Steps to Reproduce

1.
2.
3.
4.

**Comment by KurtStam** [comment]
@amysueg WDYT?

**Comment by amysueg** [comment]
@KurtStam Seems like we had this design at one point. @dongniwang Do you remember that? We had an empty state in a card to add another connection. Can you resurrect that design?

**Comment by gashcrumb** [comment]
We did, I think it's actually part of the design as well, *however* the problem is currently that create connection button takes you out of the create integration flow, and we can't properly persist an "incomplete" integration really.  This was something we were going to try and address when implementing the bits for the auto-save epic, but it keeps getting pushed back for other things.

**Comment by KurtStam** [comment]
@gashcrumb can you reference the auto-save epic issue?

**Comment by gashcrumb** [comment]
I will certainly try and dig that one up :smile:

**Comment by dongniwang** [comment]
Hey @amysueg @KurtStam and @gashcrumb - The empty card design was in InVision and I just found the marvel link for it https://marvelapp.com/1g9ga87g/screen/58510506. 

![Screen Shot 2019-11-20 at 4 53 38 PM](https://user-images.githubusercontent.com/24943812/69281487-55d1fd00-0bb6-11ea-9521-89ff174f6434.png)


> We did, I think it's actually part of the design as well, _however_ the problem is currently that create connection button takes you out of the create integration flow, and we can't properly persist an "incomplete" integration really. This was something we were going to try and address when implementing the bits for the auto-save epic, but it keeps getting pushed back for other things.

Yeah, I remember this! Let's definitely try to address this in the autosave issues if possible.
