### ISSUE TITLE
Action Configure: Exception Handling

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis#718]
Exception handling in the UI for the DB connector on save.

![Exception Handling](https://github.com/syndesisio/syndesis/raw/cac32465b92d780a3f0440c5b542b1ece489ae99/ux/designs/databaseconnection/img/errors.png)

Full designs [here](https://github.com/syndesisio/syndesis/blob/cac32465b92d780a3f0440c5b542b1ece489ae99/ux/designs/databaseconnection/databaseconnection.md#create-an-integration-with-database-as-a-start-connection).

cc @KurtStam

**Comment by KurtStam** [comment]
At the moment errors on this screen are not shown. To try create an integration, and select the existing Database Connection to the SampleDB. Select the 'Periodic SQL Invocation' action and in the SQL Statement field use a non-existing table (SELECT * FROM KURT). Hit 'Done'. The javascript console will log the following error:

[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (sql-start-connector, line 0)
{
    "errorCode": 500,
    "userMsg": "ERROR: relation \"kurt\" does not exist\n  Position: 15",
    "developerMsg": "Unable to fetch and process metadata"
}

However this error is not shown on the page. In fact we've moved off this page onto the next.

The desired behavior is that the user cannot proceed until the error is cleared.

**Comment by zregvart** [comment]
I think the UI will show the error message if the verifier returns a list of errors.

https://github.com/syndesisio/syndesis/blob/ae70ab045b5f6d3a9d69df9c724cf14b3fdebf24/app/verifier/src/main/java/io/syndesis/verifier/VerifierResponse.java#L36

https://github.com/syndesisio/syndesis/blob/ae70ab045b5f6d3a9d69df9c724cf14b3fdebf24/app/rest/rest/src/main/java/io/syndesis/rest/v1/handler/connection/ConnectorHandler.java#L155-L162

**Comment by KurtStam** [comment]
It seems wrong to me to return errors as a 'valid' HTTP 200. I think it makes much more sense to let the REST framework take care of it and simply throw out the exception, which then turns into a 500 with error msg. Maybe I'm missing something.

**Comment by zregvart** [comment]
Yeah the verifier is not very RESTfull, but that's the contract...

**Comment by KurtStam** [comment]
Time to change the contract?

**Comment by jimmidyson** [comment]
What is outstanding for this for TP3 then? Do we need to change the REST contract and update the UI or just update the REST implementation to return the list of verifier errors correctly?

**Comment by KurtStam** [comment]
@jimmidyson My preference would be to upgrade the contract, but it depends on how pressed for time the UI team is. If they are too busy we can return a list instead.

**Comment by deeleman** [comment]
We've been discussing about agreeing on a common contract for exchanging error messages b/w the API and the UI for ALL API endpoints, so each time the API is force to return an error message, the JSON response returned by that endpoint would featured an agreed property (named `errors` or `apiErrors` or `messages` or whatever you fancy) containing an array of typed error messages, whose type will be always the same no matter what.

Perhaps this case scenario makes a good case to kick start this functionality. I'd suggest to decorate any JSON responses contianing errors with the following interface from now on:

```java
interface ApiErrors {
  errors: {
    status: Integer;
    statusText: String;
    messages: Array<{ userMessage: String; developerMessage: String; }>;
  };
}
``` 

Also, from a UI POV I'd expect a `400 Bad Request` error message instead in this case. Thoughts?

**Comment by KurtStam** [comment]
@zregvart so I guess we need to catch all our exceptions in the adapters like we do for the verifier.  atm we don't catch anything: https://github.com/syndesisio/syndesis/blob/master/app/verifier/src/main/java/io/syndesis/verifier/v1/metadata/SalesforceMetadataAdapter.java

**Comment by KurtStam** [comment]
@zregvart A verifier response can contain the list of errors as you referenced above (see also https://github.com/syndesisio/syndesis/blob/master/app/verifier/src/main/java/io/syndesis/verifier/impl/BaseVerifier.java). However, the metadataAdapter has no such contract and exceptions are managed by the https://github.com/syndesisio/syndesis/blob/master/app/verifier/src/main/java/io/syndesis/verifier/VerifierExceptionMapper.java

In this case the format of the message is
https://github.com/syndesisio/syndesis/blob/master/app/verifier/src/main/java/io/syndesis/verifier/VerifierExceptionMapper.java#L48-L51
so for example:
```
{
    "errorCode": 500,
    "userMsg": "ERROR: relation \"kurt\" does not exist\n  Position: 15",
    "developerMsg": "Unable to fetch and process metadata"
}
```

**Comment by KurtStam** [comment]
OK so looking at this there are 2 small issue really. The metadata adapter is called twice. Once on entering the page and once when 'Done' is clicked. Now

1. If an error happens on entering the page:
<img width="810" alt="screen shot 2017-12-21 at 5 20 34 pm" src="https://user-images.githubusercontent.com/35576/34277421-9d7842d2-e673-11e7-8138-6ae276d4b8b7.png">
the 'Done' button should be disabled at this point. The user should not be able to proceed with an error. The good news is that the error is displayed correctly. I can live with this issue. The next one is more troublesome;

2. When all was fine up until now, the form is filled out and the user clicks 'Done' is clicked and an error comes back, then we should stay at the page and display the error rather then proceeding regardless.
