### ISSUE TITLE
API Connector: Delete

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis#719]
Delete functionality in API Client Connect List page.

![](https://github.com/syndesisio/syndesis/raw/master/ux/designs/apiconnector/img/connectorlist.png)

See full designs [here](https://github.com/syndesisio/syndesis/blob/master/ux/designs/apiconnector/apiconnector.md).

**Comment by rhuss** [comment]
@kahboom Is this still open ?

**Comment by deeleman** [comment]
It's done
