### ISSUE TITLE
API Connector: Custom connector must feature a Swagger Actions Review table

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis#720]
Used in both the Detail and Wizard views.

![](https://raw.githubusercontent.com/syndesisio/syndesis/master/ux/designs/apiconnector/img/connectordetails.png)

See full designs [here](https://github.com/syndesisio/syndesis/blob/master/ux/designs/apiconnector/apiconnector.md).

**Comment by deeleman** [comment]
I'll take over this one once we manage to squash the last bug from #272
