### ISSUE TITLE
syndesis bash completion seems to be broken

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#7206]
## This is a...

<pre><code>
[ ] Feature request
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Trying to enable bash completion for the syndesis script and got this error:

```
$ source <(tools/bin/syndesis completion bash)
/home/lburgazz/work/redhat/dev/syndesis-go/src/github.com/syndesisio/syndesis/tools/bin/commands/release.bats: line 2: ./release: No such file or directory
bash: /dev/fd/63: line 483: syntax error: unexpected end of file
```

**Comment by KurtStam** [comment]
@lgarciaaco regression?

**Comment by lgarciaaco** [comment]
@KurtStam naa it's been broken for a while, it seems to be an option not that many use and that is why we didn't see before.

I vote for removing the the .bats files which we don't have included in ci anyways and were my own try to insert some testing for bash, but to be honest I am not that impressed with it. What do you think?
