### ISSUE TITLE
Error report Syndesis server failed to start "java.lang.NoSuchMethodException: io.syndesis.server.endpoint.v1.handler.support.SupportUtil.<init>()"

### ISSUE THREAD

**Issue by gelonsoft** [syndesisio/syndesis#7214]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Error: java.lang.NoSuchMethodException: io.syndesis.server.endpoint.v1.handler.support.SupportUtil.<init>()
Docker image version: syndesis / syndesis-server : latest DIGEST:sha256:50118c661c4749192bde2f02975db9e5a012de76f22af22399510db52ffff20e
Syndesis server version: v1.9-SNAPSHOT
Log of syndesis server pod: https://pastebin.com/VGW1A5Hq

**Comment by squakez** [comment]
Thanks for reporting, going to have a look!

**Comment by squakez** [comment]
Closed by #7234
