### ISSUE TITLE
Unable to clone syndesis git repo due to question marks in file names ( Invalid argument )

### ISSUE THREAD

**Issue by gelonsoft** [syndesisio/syndesis#7241]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Could you please rename all files and directories with question marks ("?") to simplify syndesis development/contribution on Windows OS. 
By default you can't use "?" in file names or directory names ( also the following reserved chars: <>:"/\|?*  https://docs.microsoft.com/ru-ru/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN ).
<pre><code>
$ git clone git@github.com:syndesisio/syndesis.git
Cloning into 'syndesis'...
remote: Enumerating objects: 35, done.
remote: Counting objects: 100% (35/35), done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 353378 (delta 10), reused 13 (delta 4), pack-reused 353343
Receiving objects: 100% (353378/353378), 137.96 MiB | 3.93 MiB/s, done.
Resolving deltas: 100% (186462/186462), done.
fatal: cannot create directory at 'app/ui-react/syndesis/tapes/create-connection.spec.js/api/v1/connections?per_page=50': Invalid argument
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
</code></pre>

**Comment by gashcrumb** [comment]
@kahboom did you say there was a way we could override the filenames for those integration tests?

**Comment by kahboom** [comment]
@gelonsoft - Hey! Please retest and let me know if you still have any issues. Going to see if I can find a way to test on Windows as well.

**Comment by gelonsoft** [comment]
@kahboom , still have issue cause ":" is also reserved char.
------------------
fatal: cannot create directory at 'app/ui-react/syndesis/tapes/create-integration.spec.js/api/v1/connections/i-LkiT24SvERwF0KppRNIz/actions/i-LkAI0ut-OrgXelAq8JAz:4babf99c-6287-47bb-862c-da7d053338af': Invalid argument
------------------
