### ISSUE TITLE
Add NTLM Auth (choose between Basic and NTLM) for OData Connector

### ISSUE THREAD

**Issue by gelonsoft** [syndesisio/syndesis#7261]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Could you please add NTLM Auth feature for OData connector. Now it uses only Basic auth.

**Comment by heiko-braun** [comment]
@rareddy @bibryam FYI
