### ISSUE TITLE
Dashboard: kebab menu in Top 5 Integration table is not working

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis#733]
When clicking on any action nothing happens. It seems that actions aren't initialized as links in HTML code properly.

![screen shot 2017-12-13 at 09 01 18](https://user-images.githubusercontent.com/5637792/33928062-c4159b50-dfe4-11e7-8119-9b9dfb873e02.png)

**Comment by jimmidyson** [comment]
@syndesisio/ui-api Chances of getting this fixed, or even hidden if too large, for TP3?

**Comment by amysueg** [comment]
Removing notif/uxd label since this is a coding/bug issue.
If this is too large to fix for TP3, then probably hiding the menu is ok for now.
FYI -- in case one of you can quickly address this: @deeleman @kahboom @seanforyou23

**Comment by deeleman** [comment]
I quickly checked the current implementation and could not spot the bug on a first glance. Probs it won't require much time but its not a 5 minutes thingie either

**Comment by zregvart** [comment]
I think I found out the reason why the action menu is not working. It comes down to Angular change detection. To fetch the current state `IntegrationsListComponent::getActionConfig` is invoked:

https://github.com/syndesisio/syndesis/blob/aacb51d40ff7273b6d1d2d38edf427716046c241/app/ui/src/app/integrations/list/list.component.ts#L80-L81

This in turn returns always new instance of `ActionConfig` and that triggers change detection to update the view as old value is not !== with the new value, which removes the menu items (as `<li>` elements) and re-adds them to the DOM.

If I do a trivial cache of the returned `ActionConfig` from `getActionConfig` the menu starts working properly.

I'm trying to find out why this occurs on the dashboard, but not on the integrations list page.

**Comment by jimmidyson** [comment]
Let's hide it for TP3 :)

Kept open for TP4.

**Comment by jimmidyson** [comment]
This actually looks like it is continually updated in the UI - can't even view it in dev tools in chrome, continually updates and is redrawn. Out of my angular skills but sure it's super quick for @deeleman or @kahboom :)

**Comment by zregvart** [comment]
I had a change that helped with this, it created an array of `ActionConfig`s based on `integrations` field and returned that from `getActionConfig`, it also implemented lifecycle method to get notified if `integrations` changes. Not sure if that's a correct solution, let me create a PR so we can discuss it there.

**Comment by zregvart** [comment]
OK, so I tried to crate the PR, but I stumbled on the root cause of this issue. It seems that Angular's change detection is triggered on array that gets modified, I think by ng2-charts. This triggers the repaint. I'll create a PR that I think fixes this.

**Comment by zregvart** [comment]
The PR in #873 should fix this, I'm labeling it for TP3
