### ISSUE TITLE
Run Syndesis failed wit 

### ISSUE THREAD

**Issue by ashenp** [syndesisio/syndesis#7345]
## enviorment
macOS Catalina 10.15.1
## description
when I try to run syndesis with minishift using command below:

./tools/bin/syndesis minishift --install --open --nodev

get Error showing:

Add-on 'admin-user' enabled
Starting minishift ....
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'hyperkit' is supported on this platform ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'hyperkit' hypervisor ...
-- Starting Minishift VM .......................... FAIL E1206 16:21:55.924120    2333 start.go:494] Error starting the VM: Error starting stopped host: IP address never found in dhcp leases file Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory. Retrying.
Error starting the VM: Error starting stopped host: IP address never found in dhcp leases file Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory

**Comment by zregvart** [comment]
Looks like a minishift problem I know there have been some issues on MacOS with minishift, you can also try crc to see if that works better. I.e.

`./tools/bin/syndesis minishift --install --open --nodev`

Or follow up with the [minishift](https://github.com/MiniShift/minishift) project?

We have this documented [here](https://doc.syndesis.io/#syndesis-crc).
