### ISSUE TITLE
app/dv/pom.xml contains custom gpg-plugin/deploy-plugin settings

### ISSUE THREAD

**Issue by cunningt** [syndesisio/syndesis#7348]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

app/dv/pom.xml inherits from syndesis-parent, but has custom gpg-plugin / maven-deploy-plugin / nexus-staging-maven-plugin settings.     It also has custom repositories settings, distributionManagement settings, issueManagement settings, and the connection / developerConnection settings don't seem right for the inclusion in syndesis.

I'm not entirely certain what the deployment scenario here of artifacts is but I think if this is being included as a part of syndesis, all of those settings could be removed from app/dv/pom.xml and we could just use what is set in syndesis-parent.

see: https://github.com/syndesisio/syndesis/blob/master/app/dv/pom.xml#L297-L340

**Comment by vhalbert** [comment]
I'm in the process of removing the "release" and "core-release" profiles in the dv pom.xml.   The image profile needs to remain.

**Comment by vhalbert** [comment]
I'll also remove the repo settings, distroMgmt, issueMgmt and scm, in addition to other plugins that are inherited from the parent pom.

**Comment by vhalbert** [comment]
https://github.com/syndesisio/syndesis/pull/7349
