### ISSUE TITLE
Schedule an integration

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#736]
See also **https://issues.jboss.org/browse/ENTESB-11539**

To schedule an integration we now need to rely on specific connector options which leads to inconsistencies and maintenance cost so it would be nice to have a generic way to configure integration/flow schedulers.

- on UI side , we should have a generic section on the integration/flow editor to define scheduling options
- on model side, the integration model should have an additional type, like:

```java
interface Scheduler { 
    enum Type {
       timer,
       cron
    }

    /**
     * The schedule definition according to the type, i.e.
     *  - timer: "1s"
     *  - cron: "0 0/5 12-18 ? * MON-FRI"
     */
    String getDefinition()

    /**
     * The scheduler type
     */
    Type getType()
}


interface Integration {
    ...
    Optional<Scheduler> getScheduler();
    ....
}
```

- on backend side: as we do not need to expose the routes to end user anymore we can simple generate a standard camel endpoint of type `timer`, `scheduler` or `quartz` according to the configured scheduler type

@rhuss @kcbabo @chirino does it make sense ?

**Comment by kcbabo** [comment]
Makes sense to me.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11539**
