### ISSUE TITLE
Tech extension: Importing extension even when click on cancel button

### ISSUE THREAD

**Issue by lvydra** [syndesisio/syndesis#739]
After uploading tech extension file, on "Review Details and Confirm Import" view, Tech extension is imported even when you click on cancel button.

**Comment by lburgazzoli** [comment]
What do you mean by "is imported" ? 

The process on back-end is:

- receive a blob from UI (when file is uploaded) 
- store the blob
- store the extension meta-data and mark it as "draft"
- return extension details to the UI
- mark extension as "installed" when user click on "import"

So yeah the extension is stored on backend but no one can use it as it is not active.

**Comment by lvydra** [comment]
Even when you click on cancel button extension become visible in syndesis-tech-extensions-list and can be used as step in integration.

**Comment by lburgazzoli** [comment]
Yeah, I've just replicated the issue
