### ISSUE TITLE
ServiceVdbGeneratorTest::shouldRefreshServiceVdb_SingleSource is flaky

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#7393]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

I see this `ServiceVdbGeneratorTest::shouldRefreshServiceVdb_SingleSource` test fail occasionally on downstream CI.

```
[ERROR] shouldRefreshServiceVdb_SingleSource(io.syndesis.dv.server.endpoint.ServiceVdbGeneratorTest)  Time elapsed: 0.031 s  <<< FAILURE!
org.junit.ComparisonFailure: 
expected:<...type="DDL"><![CDATA[[SET NAMESPACE 'http://www.teiid.org/ext/relational/2012' AS teiid_rel;
]CREATE FOREIGN TABLE...> but was:<...type="DDL"><![CDATA[[]CREATE FOREIGN TABLE...>
	at io.syndesis.dv.server.endpoint.ServiceVdbGeneratorTest.shouldRefreshServiceVdb_SingleSource(ServiceVdbGeneratorTest.java:406)

```

**Comment by zregvart** [comment]
@rareddy can you take a look at this. I'm afraid I'm going to have to blacklist this test otherwise.

**Comment by shawkins** [comment]
I'll address this today.

**Comment by shawkins** [comment]
The issue here is a mixing of Teiid versions.  This should be happening on the product branch due to a change in Teiid 13.  We'll be rolling Teiid 13 into the upstream today with https://issues.redhat.com/browse/TEIIDTOOLS-891 which will update this test result as well.

**Comment by shawkins** [comment]
Tried to move to the snapshot version of Teiid Spring Boot, but that we're not picking up those snapshots in the build: https://github.com/syndesisio/syndesis/pull/7434  

This will need to wait until the Teiid Spring Boot 1.3, which @rareddy indicated will likely be tomorrow.

**Comment by zregvart** [comment]
Make sure to remove the test from the [exclusion list](https://github.com/syndesisio/syndesis/blob/master/app/excluded_tests.txt).

**Comment by shawkins** [comment]
Marking as closed.  Master and 1.9.x are now aligned with Teiid versions.
