### ISSUE TITLE
Syndesis on staging showing an error

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#7425]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

![Screenshot_2019-12-17 Integrations - Syndesis](https://user-images.githubusercontent.com/1306050/70978881-e0702400-20b0-11ea-9212-07dfd0a19e4c.png)

Error details are not that helpful:

```
TypeError: t is undefined


    in pe
    in div
    in Mt
    in div
    in Gc
    in div
    in qc
    in Kc
    in div
    in jc
    in t
    in t
    in Unknown
    in I
    in t
    in t
    in withRouter(t)
    in t
    in t
    in div
    in nl
    in t
    in I
    in t
    in div
    in yn
    in article
    in hn
    in t
    in div
    in L
    in div
    in E
    in div
    in oe
    in div
    in te
    in section
    in Hl
    in t
    in I
    in t
    in t
    in t
    in t
    in t
    in t
    in t
    in t
    in t
    in t
    in t
    in t
    in t
    in t
    in t
    in t
    in hi
    in t
    in t
    in t
    in t
    in main
    in div
    in t
    in Unknown
    in t
    in Unknown
    in t
    in t
    in withRouter(t)
    in I
    in Ke
    in t
    in t
    in t
    in Je
    in t
    in t
    in t
    in M
    in t
```

**Comment by riccardo-forina** [comment]
![image](https://user-images.githubusercontent.com/966316/71159603-3d511300-2246-11ea-90a4-9eaa41348190.png)

`TypeError: Cannot read property 'icon' of undefined`

![image](https://user-images.githubusercontent.com/966316/71159638-4cd05c00-2246-11ea-8ca7-31611da5e69e.png)

So there is some busted integration saved there. I'd say this one smells fishy, and empty step like that isn't legal (I think):

![image](https://user-images.githubusercontent.com/966316/71160045-219a3c80-2247-11ea-882b-14dea3f06429.png)

**Comment by zregvart** [comment]
It doesn't look like a valid step to me. To get the staging back I've run `DELETE FROM jsondb WHERE path LIKE '%:i-Lvvrc50kNRw7r6NNLL3z%';`.
