### ISSUE TITLE
Update AMQ UXD for SSL Connections

### ISSUE THREAD

**Issue by dhirajsb** [syndesisio/syndesis#745]
AMQ Connections now support the following properties:

Skip Certificate Check: Skip Certificate check for convenience in only development environments.
Broker Certificate: AMQ Broker X.509 PEM Certificate.
Client Certificate: AMQ Client X.509 PEM Certificate.

The options should be normally hidden, but become visible if user types in a Broker URL with a ```ssl:``` substring, suggesting the Broker uses AMQ SSL protocol. 
The first field is a boolean checkbox. The two PEM Certificate inputs MUST be text areas to allow pasting a PEM certificate that might look something like:
```
-----BEGIN CERTIFICATE-----
MIIDmTCCAoGgAwIBAgIEdiXVvDANBgkqhkiG9w0BAQsFADB9MQswCQYDVQQGEwJV
UzELMAkGA1UECBMCQ0ExEjAQBgNVBAcTCVN1bm55dmFsZTEVMBMGA1UEChMMUmVk
IEhhdCBJbmMuMR8wHQYDVQQLExZNaWRkbGV3YXJlIEVuZ2luZWVyaW5nMRUwEwYD
VQQDEwxEaGlyYWogQm9rZGUwHhcNMTcxMjA2MTkzNDEwWhcNMTgwMzA2MTkzNDEw
WjB9MQswCQYDVQQGEwJVUzELMAkGA1UECBMCQ0ExEjAQBgNVBAcTCVN1bm55dmFs
ZTEVMBMGA1UEChMMUmVkIEhhdCBJbmMuMR8wHQYDVQQLExZNaWRkbGV3YXJlIEVu
Z2luZWVyaW5nMRUwEwYDVQQDEwxEaGlyYWogQm9rZGUwggEiMA0GCSqGSIb3DQEB
AQUAA4IBDwAwggEKAoIBAQChLZciw1PfoS82nd8FkvsM2foVjpQ/b5QqYKyJehIb
B7TnSqzS9jJ+Ovr3nCLoHCVv+nkY5t181/Jyx6gSL6hOF7rKfz8xwj9fcHIIy+1C
kVsU82hlWLmqNc89RQZSH+Mo5dYjBAMAcE6Ub6SXzXU4QciU/eLA4EDq72vETcYf
/xTQDX1OPJV5RwR6BXcmYBBb7MbIknlpCOC9uLx2EQXe6cwWz8mRzDXQMOo2KAfb
5AffHEU1gqpnE+yxuz7pUCbYg8yJnwle1k04y0u5dyPGN3qfWZXNGaywBikKhEx0
VA53YJLiwd3oyW84uMvzozOflnN0zNvmtoaKek1eAulVAgMBAAGjITAfMB0GA1Ud
DgQWBBRzoip8HNqOvEGPHx6+SkM/t4spMDANBgkqhkiG9w0BAQsFAAOCAQEAHDx8
iLmt3JtndIaTPEcIbAuD/HEOPxFrfqij6OI7HoUSgArlxOMnbyBdrCH0eS8nnz3L
i9xT0I5pJnhyFUIBP2neXpt0pDMxeiFiD9qsWWdkFPjFmLIqcjS7I5lMnmOHwDi3
LQdVRRKVRS0uN6w19ALgujm826Oa9cGdMDteEw5PpVsX/JAjDoCw8aOJdn+Km0Q9
C/UwbdjFQw1+lB3sS7lRXnRU0UgRlwCzqFOyuWLprw1G1SFcXKCOrFtgU1VC4rkL
RsNxajOxrOSNoWtCKYktdC6fgjCMcyGuyT6spOEP1NNegX4twvj3W6vzZOOxnlZn
StXO/6Om7rKOh97W0A==
-----END CERTIFICATE-----
```

Also, the property ```Durable``` has been removed from the ```Subscribe for messages``` action, as it automatically creates a durable subscription if a ```Durable Subscription ID``` is provided.

**Comment by dongniwang** [comment]
See PR https://github.com/syndesisio/syndesis/pull/770

**Comment by amysueg** [comment]
Removing notif/uxd label since PR #770 addresses this issue.

**Comment by rhuss** [comment]
As the PR is merged, I'm closing this issue. Feel free to reopen if this is not the case.
