### ISSUE TITLE
[REST Swagger] Failure when executing a 2.0 swagger rest api

### ISSUE THREAD

**Issue by squakez** [syndesisio/syndesis#7460]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When creating a REST API connection from this definition [swagger.json.txt](https://github.com/syndesisio/syndesis/files/3987955/swagger.json.txt), the integration that is using it fails at runtime with the following error: [trace.log](https://github.com/syndesisio/syndesis/files/3987940/trace.log)

Please, notice that it's using swagger version 2.0 and it seems it is related to #7435.

**Comment by zregvart** [comment]
@squakez the issue is:

```
host must be an absolute URI (e.g. http://api.example.com ), given: `user-syndesis-services.192.168.42.139.nip.io
```

When you specify the host it needs to have the scheme and (optionally) port. I think we used to validate this in the UI.

**Comment by christophd** [comment]
Looking at the specification the scheme (http or https) is missing here. This is why the constructed server host URL is not complete.

We should add a validation that scheme is missing or see what has happened to the existing validation.

**Comment by christophd** [comment]
@squakez you should see a warning regarding the missing scheme

This is the validation rule that should raise the warning:
https://github.com/syndesisio/syndesis/blob/master/app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/OpenApiValidationRules.java#L268

**Comment by squakez** [comment]
Thanks @zregvart and @christophd, it was the missing scheme. I'm opening a minor bug as the validation is not reporting the error when the schema is missing.
