### ISSUE TITLE
Unable to clone syndesis git repo due to colon marks in file names ( Invalid argument )

### ISSUE THREAD

**Issue by gelonsoft** [syndesisio/syndesis#7461]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Could you please rename all files and directories with question marks (":") to simplify syndesis development/contribution on Windows OS.
By default you can't use ":" in file names or directory names ( also the following reserved chars: <>:"/|?* https://docs.microsoft.com/ru-ru/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN ).
Similar issue with question marks: https://github.com/syndesisio/syndesis/issues/7241
Git clone error:
<pre><code>
`fatal: cannot create directory at 'app/ui-react/syndesis/tapes/create-integration.spec.js/api/v1/connections/i-LkiT24SvERwF0KppRNIz/actions/i-LkAI0ut-OrgXelAq8JAz:4babf99c-6287-47bb-862c-da7d053338af': Invalid argument`
</code></pre>

**Comment by zregvart** [comment]
@kahboom didn't we already fix all of these?

**Comment by kahboom** [comment]
keep this open, I might need to verify that there aren't some characters missing. I'll dig up the comments about it
