### ISSUE TITLE
[Usage Problem]The integration api with sort params

### ISSUE THREAD

**Issue by Zheaoli** [syndesisio/syndesis#7471]
Hello guys, I try to use the integration API to fetch list of Integrations which the URL path is `/api/v1/integrations`, But I got a problem

When I use this api with `sort` params like `/api/v1/integrations?sort=version`, then the response is  **Cannot find field %s in %s as int or String field** 

I have already checked the IntegrationHandler, from L185-L194, here's the code

```java

    @Override
    public ListResult<IntegrationOverview> list(final UriInfo uriInfo) {
        final DataManager dataManager = getDataManager();
        final ListResult<Integration> integrations = dataManager.fetchAll(Integration.class,
            new ReflectiveSorter<>(Integration.class, new SortOptionsFromQueryParams(uriInfo)),
            new PaginationFilter<>(new PaginationOptionsFromQueryParams(uriInfo)));

        return ListResult.of(integrations.getItems().stream().map(i -> integrationOverviewHelper.toCurrentIntegrationOverview(i))
            .collect(Collectors.toList()));
    }
```

And I have noticed that the error is relational with `ReflectiveSorter`, and the main code is 

```java

    private Comparator<T> createDelegateComparator(Class<T> modelClass, String fieldName) {
        Comparator<T> delegate = getIntComparator(modelClass, fieldName);
        if (delegate != null) {
            return delegate;
        }

        delegate = getStringComparator(modelClass, fieldName);
        if (delegate != null) {
            return delegate;
        }

        throw new IllegalArgumentException(String.format("Cannot find field %s in %s as int or String field",fieldName, modelClass.getName()));
    }
```

That means the `ReflectiveSorter` will find the field with `get` method to get the value from the `Class<T> ` (aka `Integration.class` here), But the `Integration.class` doesn't have the file with `get` method in the type String or Int.

So, how to use the sort param in integrations fetch api ? feel free to tell me if I have missed some detail in docs or code

**Comment by zregvart** [comment]
Yeah that's an issue since `Integration` is an interface and doesn't have fields in it. I wonder why we haven't come across this issue before.
