### ISSUE TITLE
Issue with syndesis installation and startup - minishift: line 193: APP_OPTIONS: unbound variable

### ISSUE THREAD

**Issue by kartikay-nx** [syndesisio/syndesis#7482]
## Description
I am starting my openshift cluster using hypervisor, it is throwing this error "minishift: line 193: APP_OPTIONS: unbound variable". Please refer screenshot.

<img width="717" alt="Screenshot 2019-12-24 at 6 11 00 PM" src="https://user-images.githubusercontent.com/46349050/71413798-d71b2480-2679-11ea-946a-69eb921bffc8.png">

**Comment by ajgraaff** [comment]
I have the same issue.

**Comment by zregvart** [comment]
I think this should be fixed with #7487

**Comment by claudio4j** [comment]
fixed with #7487
