### ISSUE TITLE
Missing connectors should fail the build

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#751]
We fail the build if connectors cannot be found (and make sure there is a test for it).

https://github.com/apache/camel/blob/master/platforms/camel-catalog-maven/src/main/java/org/apache/camel/catalog/maven/DefaultMavenArtifactProvider.java#L108-L112

**Comment by zregvart** [comment]
Also #560, I think it would have caught this.

**Comment by gashcrumb** [comment]
This seems stale, reopen if it isn't with a task...
