### ISSUE TITLE
API provider - return status code are not ok

### ISSUE THREAD

**Issue by ryckowski** [syndesisio/syndesis#7587]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Integration type: API Provider
If there's is any error the only way get known about it is to check option on the configuration page: Include error message in the return body. As always 200 code is returned to the client
Next: I can set codes 200, 401,403, 404 for such case but from semantic point of view there're not valid
Also if my integration calls another rest service that return 404 I cannot pass this code to the client

Not sure if it's a bug but I would expect from rest service to have better support for http codes

**Comment by zregvart** [comment]
This is the current state of the implementation. We're implementing this piece by piece, so it's good that you've reached out as we're looking for feedback on this.

If I'm not mistaking currently we support setting HTTP response status from the API provider and Webhook - based integrations, and returning errors from the SQL connector.

It would seem that for the use case you describe we need to add support for returning errors from the API client connector as well. I thought we have some headway in that also, but I could be mistaking.

**Comment by zregvart** [comment]
You might be interested in this use case @KurtStam

**Comment by KurtStam** [comment]
@ryckowski - are you expecting the full list of HTTP codes? I'd prefer to a sensible shorter list if possible. See also https://issues.redhat.com/browse/ENTESB-13988
