### ISSUE TITLE
Should we add idempotency support to DB connector?

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#759]
With the `-start` DB connectors we'll end up processing same rows multiple times, to prevent that should we implement idempotent consumer pattern in DB `-start` connectors? Is this best handled by the integration runtime?

cc @KurtStam @kcbabo

**Comment by KurtStam** [comment]
I think this is business level logic, so we could only offer it as a config option. At the moment the endusers can also implement themselves by using the onConsume option.

**Comment by kcbabo** [comment]
I agree that idempotency will be a key concern for database connector, but I think it's also a general integration flow concern as well.  It would be great if we had something similar to an idempotent step which allowed the user to configure the details (e.g. cached or persisted, select unique id, etc.).  Does that make sense or am I talking crazy?

**Comment by KurtStam** [comment]
+1 I like the idea of having it as a generic 'filter' step

**Comment by KurtStam** [comment]
Closing this and we can create a new issue to add a specific filter step to filter out duplicates when we are ready to tackle that.
