### ISSUE TITLE
Unable to deploy an integration on openshift 3.7

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#760]
I've set minishift to use openshift 3.7 because of the kubernetes-client issue and now integrations are not more deployed (but built successfully) because of the following error:

    Couldn't deploy version 1: ReplicationController "mentions2todo-1" is 
    invalid: spec.template.spec.containers[0].image: Required value

**Comment by rhuss** [comment]
The reason for this is probably our workaround around broken image triggers in OpenShift. See https://github.com/syndesisio/syndesis/blob/9c51ce8ed5cf19e24c2be24747db7534ee2f6b95/app/rest/openshift/src/main/java/io/syndesis/openshift/OpenShiftServiceImpl.java#L196 where we set an empty image name (actually with a single space which was considered for OpenShift 3.6 as non-empty.

It might be worth to retry whether config change triggers work again. @dsimansk do you remember the details still ? I'm a bit weak in remembering this actually ;-)

**Comment by dsimansk** [comment]
Well, there was a problem with ImageChangeTriggers. You mean to try with this commented-out code and get rid of  `.withImage(" ").withImagePullPolicy("Always").withName(name) `

https://github.com/syndesisio/syndesis/blob/9c51ce8ed5cf19e24c2be24747db7534ee2f6b95/app/rest/openshift/src/main/java/io/syndesis/openshift/OpenShiftServiceImpl.java#L214-L221

But to the context of workaround. There was an issue with triggers in 3.6 version that was reproducible mainly on Fuse Ignite cluster, therefor the workaround. For the 3.7 the fix should be already there. They have rewritten trigger logic, I can dig for the GH issue, should be in some email thread.

**Comment by rhuss** [comment]
I'm a bit worried why the workaround fails to work as we still use ' ' for image names in out initial templates. The must be happening some mangling on the way.
