### ISSUE TITLE
Publish user doc on the syndesis.io community site

### ISSUE THREAD

**Issue by TovaCohen** [syndesisio/syndesis#7654]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X ] Documentation issue or request
</code></pre>

## Description
Syndesis user documentation should be published on the Syndesis community site. 
As Zoran says, the documents have variables in place so we can build those docs upstream without
mentioning downstream product names. So from the standpoint of the content, they're good to go.

There are four documents that can be published to the community site:

- _Syndesis Sample Integration Tutorials_ - `doc/tutorials/master.adoc`
- _Integrating Applications with Syndesis_ - `doc/integrating-applications/master.adoc`
- _Connecting Syndesis to Applications and Services_ - `doc/connecting/master.adoc`
- _Developing OpenAPI Documents and Extensions to Customize Syndesis_ - `doc/customizing/master.adoc`

The source files are in the `syndesis/syndesisio` repo, so I assume that a mechanism would be needed to copy the source files to the `syndesis/syndesis.io` repo.

**Comment by zregvart** [comment]
We could add this as a part of the CI on the `syndesisio/syndesis` repository. For every build on `master` branch we could check if there were changes in the `/docs` directory run Asciidoctor and push the generated HTML files and images to the `gh-pages` branch of the `syndesisio/syndesis.io` repository.

Not sure about keeping multiple versions of the documents, corresponding to each version of Syndesis, that could also be done if needed.

**Comment by zregvart** [comment]
Work in progress [pull request](https://github.com/syndesisio/syndesis.io/pull/158) for the website.
