### ISSUE TITLE
[UXD] Need uxd for SOAP Client connector template and connector

### ISSUE THREAD

**Issue by dhirajsb** [syndesisio/syndesis#7674]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Need a connector template UI for SOAP Client connectors. It will be similar to the OpenAPI connector template screens, with SOAP labels and properties instead of OpenAPI labels and properties on the screen. 

Also needed is a connector configuration screen to configure the generated SOAP client connector. 

The overall UI flow will be similar to the OpenAPI example at https://github.com/syndesisio/syndesis-quickstarts/blob/master/db-2-api-connector/APIConnector.md

The UI flow for creating a connector with options and differences is as follows:

1. User will be able to create a new customization called `SOAP Client Connectors` in Figure 1. The screen will be similar, except references to `API Client` will be replaced with `SOAP Client` and the `OpenAPI specification` replaced with `WSDL 1.1 specification`. 
2. In step 2 in figure 2, user will be able to either upload a WSDL file or provide a URL link to the WSDL document. 
3. Because a WSDL document can have multiple SOAP Services and corresponding Ports (a map with one or more service name keys mapped to one or more port name values), the SOAP Client connector will need an additional screen before Figure 3. It will be called `Select Service` to select values for `service` and `port` configuration properties. The backend is smart enough to auto-select the service and port if the WSDL has only one, so the UI could optionally skip this page. 
The screen will show drop downs for Services and Ports with values like:
{code}
Service : {namespace1}service1
                {namespace2}service2
Port: Port1
         Port2
{code}
4. After the user selects the service and port to use (or auto-selecting the default single service and port), the UI shows Figure 3 with an API summary similar to Open API connectors. There may also be warnings or errors from the backend if there is an error in parsing the WSDL document or connecting to the URL. 
However, this screen will NOT have a 'Review/Edit' button, since a WSDL editor is out of scope at this point. 
5. After Reviewing Actions, the user will see a `Specify Security` page (not shown in the quickstart) to set authentication options. The supported options are:
{code}
- Authentication Type (drop down)
  * None
  * HTTP Basic Authentication
  * WS-Security Username Token
Username: (string)
Password: (string)
Timestamp: (boolean)
{code}
If the type is set to `None`, the other fields should be disabled. The `Timestamp` field is only enabled for `WS-Security Username Token` authentication type. 
6. User will then see a `Review/Edit Connector Details` page like Figure 4 from the quickstart. Instead of the `Host` and `Base URL` field, there will be an 'Address` field for an HTTP(S) address to connect for the SOAP service. The backend will provide values for all the fields from the WSDL. The user may overwrite the address field in the connector, or later in connection configuration UI flow. 
7. After user clicks `Create SOAP Connector`, user should see the new SOAP connector template similar to Figure 5 in the quickstart. 

Creating a SOAP Client connection follows the same UI steps as Figures 7, 8, and 9 from the quickstart. The connection properties for SOAP connections being, in order, `Address, Authentication Type, Username, Password, and Timestamp.`

**Comment by dhirajsb** [comment]
CC @gaughan , @amysueg , @dongniwang

**Comment by dongniwang** [comment]
Is this for upstream or for product? I thought we're using Jira now?

**Comment by dhirajsb** [comment]
@dongniwang I'm adding this feature to master, so that's upstream I guess. But I'll create a JIRA for it too. I added it here out of habit. :)

**Comment by dhirajsb** [comment]
Created JIRA issue https://issues.redhat.com/browse/ENTESB-12842
