### ISSUE TITLE
Error report

### ISSUE THREAD

**Issue by germanoaraujo** [syndesisio/syndesis#7728]
## Salesforce connector

<pre><code>
[X ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

**Comment by zregvart** [comment]
Sorry we need more details: w, please reopen this issue when you can provide some.
Sorry we need more details, including:
 - description of what were you trying to accomplish
 - steps for someone else to take to reproduce the issue
 - any errors that were shown on the screen (screenshots are fine)
 - logs the syndesis-server and syndesis-meta pods
 - logs from the browser console
 - network request/responses resulting in an error from the browser's network inspector

Please reopen this issue when you can provide some. We're working on getting these details filled in automatically in #7547.
