### ISSUE TITLE
Operator install failure: OpenShift 4.3+

### ISSUE THREAD

**Issue by mrhillsman** [syndesisio/syndesis#7808]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
https://bugzilla.redhat.com/show_bug.cgi?id=1777991

Installing on OpenShift 4.3+ fails due to ImageStream tags being used; postgresql:9.5 and php:7.0 neither of which exist in the openshift or syndesis namespace referenced. postgresql 10, 9.6, and latest as well as php 7.3, 7.2, and latest exist.

The syndesis-db and todo CRs fail to get instantiated due to these issues.

**Comment by kevinmershon** [comment]
@mrhillsman You said on the RedHat issue that you were able to edit the imagestream to fix the postgres version. Can you detail how you did that? It appears that the latest Syndesis also does not deploy on OpenShift 4.2X either

**Comment by claudio4j** [comment]
This issue was fixed by https://github.com/syndesisio/syndesis/pull/7760/files
