### ISSUE TITLE
Support OpenShift > 3.6.0

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis#785]
We need to able to support newer versions of OpenShift.

Some other issues have already been open regarding 3.7.0 related bug.

This issue counts as a tracker for the main activity.

Ideally, to avoid breaking people workflow, we have to put together a PR that do:
- [x] upgrades OS to 3.7.0
- [x] upgrades Kubernetes Client to latest 3.x release
- [x] verifies Integration Test pass
- [x] manually verify that an integration can be manually created

**Comment by lburgazzoli** [comment]
@paoloantinori  also https://github.com/syndesisio/syndesis/issues/787
