### ISSUE TITLE
Self containing connectors

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#786]
Beside creating the connector, adding it to syndesis requires some manual activity on different modules:

- dao
- runtime

We should try to reduce this by:

- include connector definition in connector's artifact
- include mapper inspections in connector's definition, i.e.:
```json
"outputDataShape": {
  "kind": "java",
  "type": "twitter4j.Status",
  "specification": "<put the precomputed shape here>"
}
```

Then when building the runtime we can process connectors bom and extract all the information needed by the runtime from connector's artifact.

**Comment by igarashitm** [comment]
Unless syndesis run `mvn install` for the custom connector, we would need external jar support for the Java inspection - atlasmap/atlasmap#29

**Comment by lburgazzoli** [comment]
The initial plan is not to change the behavior of the runtime, so the runtime will include an additional jar with connectors metadata (including inspections) but yeah, supporting custom jar is something we should have,
