### ISSUE TITLE
Replace Infinispan embedded cache with a simpler implementation

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#788]
My understanding is that Infinispan embedded cache is only used by `dao` and `inspector` for simple map like operation (get/put) and the only "functionality" we are leveraging is expiring of entries based on cache size, we can achieve a similar behavior without an additional dependency with something similar to:

```java
    final LinkedHashMap<String, String> cache = new LinkedHashMap<String, String>() {
        @Override
        protected boolean removeEldestEntry(final Map.Entry eldest) {
            return size() > maxSize;
        }
    };
```

@rhuss make sense ?

**Comment by rhuss** [comment]
I'm always happy to slim down things which are left over from a premature optimization, especially when it results in errors in other regions.

@syndesisio/backend  any strong feeling to replace Infinispan for now ?

**Comment by jimmidyson** [comment]
The idea was to move to a clustered cache implementation when we eventually start thinking of scalability, which we will have to do when we move to a multitenant model.

What are the problems we're experiencing using it now?

**Comment by lburgazzoli** [comment]
The idea is to trim down dependencies at the moment so we can create simple "caching" service with a simple implementation and swap it with an infinispan one if when needed.

Would that make sense ?

**Comment by jimmidyson** [comment]
Yes that sounds fine to me.
