### ISSUE TITLE
Tech extension : validate extension

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#794]
See also **https://issues.jboss.org/browse/ENTESB-11538**

We should add rules to validate extension metadata and metadata context i.e.:

- validate versions
- validate xml routes 

We should also have an hook on the platform to block integration from being started if the extension has been updated and the set-up not more correct.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11538**
