### ISSUE TITLE
Add support for multiple data shapes for input/output in actions

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#795]

**Comment by gashcrumb** [comment]
@igarashitm correct me if I'm wrong but basically we only support 1 input and maybe multiple output by design at this stage?

**Comment by igarashitm** [comment]
datamapper is the only one step which accepts multiple input data shapes (=output from  other steps) and produce single output data shape. All other step only consume single input data shape and single output data shape. And I think this gotcha is working pretty well for Syndesis usecases. We might want to close the Epic #796 until we find a valid usecase which doesn't fit current implementation?

**Comment by gashcrumb** [comment]
Agreed!  Let's close this and that one too
