### ISSUE TITLE
ApiProvider HTTP errors fail to flag Integration Activity in error

### ISSUE THREAD

**Issue by sigreen** [syndesisio/syndesis#8001]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
When an integration includes an ApiProvider, return HTTP error codes can be mapped to specific exceptions that occur within the flow.  The HTTP client calling the API receives the correct error code, but unfortunately the error does not appear in the UI Activity Screen.  Instead, the flow halts and is marked as "No Errors".

## Expected behavior
The desired flow would be for an Activity to show that includes the exception message that was thrown, together with the HTTP error code returned and a flag in the UI indicating an error.

## Screenshot

The Activity screen showing "No Errors":

<img width="1370" alt="Screen Shot 2020-03-02 at 11 40 13 AM" src="https://user-images.githubusercontent.com/13749692/75698192-46198880-5c7c-11ea-8cf7-f8d84e84300a.png">

The HTTP client receives an HTTP 500 indicating an error:

```
curl -k $externalURL/api/2 -i
HTTP/1.1 500 Internal Server Error
Content-Type: application/json
Content-Length: 0
Date: Mon, 02 Mar 2020 16:39:42 GMT
Set-Cookie: b7a48d06a03de8255ba2b69e9e7fcf9b=1795108c6d3447739d589d1c54ea8ff4; path=/; HttpOnly; Secure
```

## Request and Response Data
None

## API Endpoints and Schemas
None

## Tasks involved / Steps to Reproduce
1.  Install and test this quickstart: https://github.com/syndesisio/syndesis-quickstarts/tree/master/api-provider
2. Throw an error by searching for a record that does not exist e.g. `curl -k $externalURL/api/999 -i`
3. HTTP client should receive an HTTP 500, but no error will be flagged in the Activity Screen.

**Comment by KurtStam** [comment]
Right because the exception is handled and an Error Response (HTTP 500) is send back to the client the Activity code is flagging this as a 'successful' interaction. I think we should add some logic so that this is flagged as a fail.

**Comment by sigreen** [comment]
In the Integration server log, I see the following:
```
{"exchange":"i-M1R6WL_bqfhvUECqdZ_z","status":"begin"}
{"exchange":"i-M1R6WL_bqfhvUECqdZ_z","step":"i-LzmKKurdexCgwPv3VhOz","id":"i-M1R6WLabqfhvUECqdZbz","duration":190072}
{"exchange":"i-M1R6WL_bqfhvUECqdZ_z","step":"-LzmLJqmfTAdq4stfbU1","id":"i-M1R6WLbbqfhvUECqdZcz","duration":1521825}
{"exchange":"i-M1R6WL_bqfhvUECqdZ_z","status":"done","failed":false}
```

Notice that *failed* is set to *false*, even though an Error Response (HTTP 500) was returned.  IMHO this should be *failed* set to *true*, as @KurtStam mentioned above.
