### ISSUE TITLE
Need to make an edit to have the Next button enabled

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#8037]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

I'm creating an API client connector with OpenAPI specification from:

https://api.apis.guru/v2/specs/googleapis.com/dfareporting/v3.3/openapi.json

Which has values for Authorization URL and Access Token URL.

When I arrive at the step 3 Specify Security, I need to make an edit to either Authorization URL or Access Token URL to have the Next button enabled.

## Expected behavior

Have the Next button enabled since the values are present.

## Screenshot

![Screenshot_2020-03-05 Specify Security - Syndesis](https://user-images.githubusercontent.com/1306050/75968776-38f3d800-5ece-11ea-98f2-c470a7b2f4dc.png)

## Tasks involved / Steps to Reproduce

1. Click through the API Client Connectors workflow with the specification from above
2. Notice that on page 3, the Next is disabled even though the values are filled in

**Comment by gashcrumb** [comment]
This was supposedly fixed in https://github.com/syndesisio/syndesis/pull/7950 I checked your doc with staging and it appeared to work for me.  Have you not built the UI in a bit?

**Comment by zregvart** [comment]
Yeah, that was it. Thanks @gashcrumb.
