### ISSUE TITLE
Connection autodiscovery, dynamic properties override any other static property

### ISSUE THREAD

**Issue by squakez** [syndesisio/syndesis#8046]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

When we configure [connection autodiscovery feature](https://syndesis.io/docs/autodiscovery/), the connection page is refreshing the properties only showing the dynamic ones, removing any other "static" property set.

**Comment by zregvart** [comment]
Good catch @squakez :+1:
