### ISSUE TITLE
UX Design for AWS S3 Connector

### ISSUE THREAD

**Issue by amysueg** [syndesisio/syndesis#805]
Placeholder for UX design work related to AWS S3 connector.

**Comment by amysueg** [comment]
@dongniwang @sjcox-rh @seanforyou23 just fyi

**Comment by dongniwang** [comment]
Just wanted include an update here: 
- performed a round of UX review. 12/19
- waiting for latest UI demo video to finish final UX review. 

cc: @TovaCohen @amysueg

**Comment by gashcrumb** [comment]
I guess this was done :-)
