### ISSUE TITLE
Integration save loops to edit page instead of returning list page

### ISSUE THREAD

**Issue by squakez** [syndesisio/syndesis#8058]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

When you create an integration and save without publishing, you will return back to the edit page, instead of to the integration list page. It creates a sort of loop and you can go back by either canceling or using other menu links.

![image](https://user-images.githubusercontent.com/23169723/76325103-38e94300-62e7-11ea-9169-d9d4787c4761.png)

**Comment by gashcrumb** [comment]
If you don't publish then it *should* go back to the "root" of the editor in this case, as saving without publishing was taken to mean that the user simply wants to persist work but maybe continue making changes.

If saving results in staring at this "Save the integration" page then yeah, that's definitely a problem.

**Comment by squakez** [comment]
Thanks for the clarification @gashcrumb . The fact is that the integration is really saved, so, if I cancel or go back to the list using the breadcrumbs it's there in the "saved" status. As a user I'd expect a save to bring me back to the list (it's just my personal feedback). Feel free to close if that's an expected behavior then.
