### ISSUE TITLE
UX Design for ability to add connectors to extensions

### ISSUE THREAD

**Issue by amysueg** [syndesisio/syndesis#806]
Placeholder for UX work related to the epic #803 
@dongniwang @sjcox-rh @seanforyou23

**Comment by amysueg** [comment]
No UI needed, per Luca. Embedded in the Maven plug-in.

**Comment by lburgazzoli** [comment]
@amysueg sorry I may have misunderstood, this is not yet solved but it is likely not to require any change :)

**Comment by amysueg** [comment]
reopening as I closed the wrong one.

**Comment by lburgazzoli** [comment]
@dongniwang @gashcrumb @kahboom 

About design I think the only updates that are required are:

- **Extension List** should include connectors deployed through extensions (we are still working on the underlying metadata) and it may be nice to have different icons to show the extension type, wdyt ?
- **Extension List** user should be able to filter extension providing step or actions
- **Extension Details** should display "Supported Steps" for step extension and "Supported Actions" for connector extension

**Comment by dongniwang** [comment]
@lburgazzoli Thanks for the information. 

About having icons for extension type, are we thinking about generic ones? And do we allow users to upload their own icons? If that's the case, it would be similar to what we have for API client connector https://github.com/syndesisio/syndesis/blob/master/ux/designs/apiconnector/apiconnector.md#api-connector-list

**Comment by lburgazzoli** [comment]
As a first iteration I would just have a different icon to visually distinguish between step extensions and connector extensions.

Later on we can go the api client connector way as well as use an icon embedded in the generated extension jar. 

@dongniwang @gashcrumb @kahboom make sense ?

**Comment by sjcox-rh** [comment]
@lburgazzoli so are you just looking for a generic icon for step extensions, and another generic icon for connector extensions? If so, I can go ahead and do that. I just want to make sure we don't want a unique icon for each step and connecter extension added.

**Comment by dongniwang** [comment]
Thank you @sjcox-rh for the offering. I'm actually working on updating the extension page with the new requirements. And I think I have found an approach (introducing a column for extension type) to solve this problem without creating icons. I'll create a PR once I'm finished with the design, and maybe we can review that together and see if that addresses the issue? @lburgazzoli

**Comment by lburgazzoli** [comment]
That's fine for me.

**Comment by lburgazzoli** [comment]
@dongniwang as #1171 has been merged, can we close this issue once @nicolaferraro PR #1179 get merged ?

**Comment by dongniwang** [comment]
PR #1171 and #1179 merged, closing this issue.
