### ISSUE TITLE
Typo in title of panel

### ISSUE THREAD

**Issue by amysueg** [syndesisio/syndesis#807]
In the Customize area, when the "API Client Connectors" tab is selected, the title of the panel is "API Client Connector". That title is missing the final "s" (it should be plural, and match the tab). Low priority item, but reflects poorly on overall quality. Thanks.
<img width="269" alt="titletypo" src="https://user-images.githubusercontent.com/31700119/34053471-fdd851fa-e194-11e7-8cb9-1c0c76f5c57e.png">

**Comment by dsimansk** [comment]
@deeleman @kahboom one of you might want to pick it up along with updates to API Connector wizard?
