### ISSUE TITLE
Solidify Definitions and Expectations of Labels and Statuses

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis#809]
We discussed a few issues that are related to the agile methodology and how we follow it, what the expectations are, how we label items, etc.

Topics of interest:

1. Large undertakings that are not necessarily features, such as solving critical architectural problems, but improve the sustainability of the project, are not usually Epics. Technical previews and sprints seem to be driven by feature requirements, which is a practice that creates a brittle architectural foundation and builds technical debt.
    - What should we expect of Epics if they are mostly for features, and how can we ensure that the development process accommodates scalability, growth, and maintainability for (hopefully) the possibility of multitenancy and increasing feature requests in the future?
    - Should epics spawn other epics that are not features, or that are branches of existing Epics that perhaps were originally too broad?
2. When it becomes clear that an Epic is too broad of a scope, we tend to create Issues. An example here is the [API Connector](https://github.com/syndesisio/syndesis/issues/183) and all of which it entails. As you can see, it becomes a bit unwieldy and difficult to see the progress of. It seems that Epics should sometimes spawn other Epics. I hate to say it, but maybe we do need a "Feature" label that issues pertain to, and those Features could be sprint or release specific (ZenHub had 'Scenarios' but this does not make any sense at all in terms of wording). An example would be the API Client Connector Wizard.

Currently:
- Epic: API Client Connector (targets a TP release)
    - All Issues

Perhaps something like this would work?
- Epic: API Client Connector (spans multiple sprints, possibly TPs)
  - Feature 1: API Client Connector Wizard (~1-3 sprints, who knows?)*
    - Issue: REST: Page-Specific Endpoints (e.g. Sprint 22)
    - Issue: UX: Page-Specific Designs (e.g. Spint 22)
    - Issue: UI: Step 1 (e.g. Sprint 21)
    - Issue: UI: Step 2 - Security (e.g. Sprint 22)
    - Issue: UI: [..]
  - Feature 2: API Client Connector List
    - Issue: REST: Page-Specific Endpoints (e.g. Sprint 23)
  - Feature 3: API Client Connector Detail
- Epic: Technical Extensions
[..]

_* Anyone that pretends to know is likely guesstimating._

This is driven by the user requirements, not by anything else. But the idea is that the issues are what determine what can or cannot be accomplished in a single sprint, or even release.

It would ensure to management that we have a new feature in each technical preview release, without over-promising that we will have everything API Client Connector (as an example) in a technical preview release before we've even had time to delve into the code and determine how feasible this really is.

**Comment by gashcrumb** [comment]
There's no deliverables here
