### ISSUE TITLE
Improve Development Process

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis#810]
I personally think this should be an Epic, as it's so broad and there are a lot of areas we can improve on here. This was a card in the retrospective that drew my attention. The general comment on it was that we need time to accommodate for QE, UXD, and Docs review after implementing specific features, and that this was a bit of an issue with our current development process.

**Comment by kahboom** [comment]
Much of this is related to other issues due to somewhat of a domino effect. A few examples of some issues raised and things I might suggest to improve efficiency and allow enough time for feature reviews before the end of a sprint or release:

- Independent, yet parallel work.
    - Reducing dependency on other teams when appropriate to allow them to work in parallel. Perhaps contracts or similar could be a good way to do this. (#540)
    - Direction should be clear for everyone. I'm going to be a bit radical here and say that we need the feature development process to be more visualized and easy to track on a team and feature basis. I'm not 100% sure ZenHub does that (maybe?). To me, it needs to be simple, but flexible enough to allow for our ever-expanding team and requirements. If that doesn't already exist, I'd go as far as to suggest we build it.
- Centralized resources and knowledge.
    - Centralizing docs that are easy to collaborate to and even easier to access for everyone.
    - Synchronizing feature design proposals and updates to them, especially to the data structure. It's a lot for feature owners to keep track of and to update on each change. Even when they are updated, collaborators are not notified. Perhaps there is a way to automate this.
    - Keeping build and feature proposal documentation up-to-date. (#146)
- Open communication.
    - Clear understanding of the work process, labels, what is expected in each sprint (#809)
    - I think starting with everyone being in a single chatroom is a good place to start (or documenting how to set up the Matrix bridge between Slack and IRC), also keeping longer discussions to GitHub issues instead of mailing lists/emails or on IRC.

**Comment by gashcrumb** [comment]
It's not possible to improve our development process.

jk, but this issue doesn't have deliverables :-)
