### ISSUE TITLE
Add button doesn't appear when create an integration

### ISSUE THREAD

**Issue by kerplo** [syndesisio/syndesis#8118]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

The flow to create an integration doesn't show the add button, so I cannot add actions to the flow. I clean cache but the problem persists.

## Screenshot

![image](https://user-images.githubusercontent.com/5908155/77327726-eadb3300-6d1b-11ea-93cc-9bc8f72247f4.png)

**Comment by gashcrumb** [comment]
It's from our migration from patternfly 3, looks like patternfly no longers includes font awesome as a dependency, so this surfaced after dropping the pf3 dependency.
