### ISSUE TITLE
Tech extensions: update page displays internal ID

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis#812]
Should we display ID of tech ext. in such a format?

![screen shot 2017-12-18 at 08 39 15](https://user-images.githubusercontent.com/5637792/34094805-114646c0-e3cf-11e7-8b51-650a41a9ae56.png)

**Comment by lburgazzoli** [comment]
Yeah, tha's wrong. I'll fix it

**Comment by jimmidyson** [comment]
Thanks @lburgazzoli!

**Comment by lburgazzoli** [comment]
@syndesisio/ui-api can anyone have a look at this please ?  I can't work on it at the moment. What it is needed is that instead of display `Extension::id` we should display `Extension::extensionId`

**Comment by amysueg** [comment]
@dongniwang  agree with @lburgazzoli  - should use "extensionId" instead of just "id"
