### ISSUE TITLE
Connection does not show up in the Data Virt Tab

### ISSUE THREAD

**Issue by SvenC56** [syndesisio/syndesis#8126]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Documentation issue or request
</code></pre>

## Steps to reproduce

1. `syndesis install --setup --grant admin --cluster`
2. `syndesis login -u admin`
3. `syndesis install --app-options " --addons dv" --tag 1.9.0-20200325 --camel-k -w -o`
4. `git clone https://github.com/syndesisio/syndesis-extensions`
5. Put `ojdbc7.jar` into `syndesis-extensions\syndesis-library-jdbc-driver\lib`
6. `mvn clean install`
7. Import extension
8. Create new connection

## Description

Hey,
I am trying to use the data virtualization option. I imported the extension and created successfully a connection to the oracle db but I wasn't able to see the DB in the Connections Tab of data virtualization. Are there any additional steps to make it available? Somehow I can see the example Postgres DB there.

Thank you.

**Comment by zregvart** [comment]
@rareddy IIRC this should work out of the box. Do we have a bug?

**Comment by SvenC56** [comment]
Just for clarification:

The connection is validated and I can create integrations to gather data.

![1](https://i.imgur.com/PxDzpkG.png)

![2](https://i.imgur.com/hep3wyO.png)

But the connection doesn't seem to be displayed in DV.

**Comment by rareddy** [comment]
Please see issue https://issues.redhat.com/browse/ENTESB-10900 this needs to be resolved to support Oracle datasource
