### ISSUE TITLE
Tech extensions: clicking Cancel on Update page should go to List page

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis#813]
When I have `Update` page of existing extension opened and hit `Cancel` then `Import` page is displayed. It's a bit strange behaviour. Imho it'd be better to go back to `List`.

**Comment by dongniwang** [comment]
@dsimansk Can you please include a screen of the Update page and the Import page so I can understand which pages you're referring to? Thanks!

**Comment by jimmidyson** [comment]
@syndesisio/uxd I totally agree with @dsimansk. Please let us know if you disagree.

@syndesisio/ui-api Can we implement this this week for TP3 please? Hope it's a tiny change.

**Comment by amysueg** [comment]
@dongniwang and I agree, should go back to the Tech Extension list view.

**Comment by dsimansk** [comment]
Order from start to finish.

On `List` page click on `Update`
<img width="1239" alt="screen shot 2017-12-18 at 15 25 52" src="https://user-images.githubusercontent.com/5637792/34110806-08affd6a-e408-11e7-96d5-3cd2fc0ef29a.png">

On `Update` I want to cancel because of...
<img width="1232" alt="screen shot 2017-12-18 at 15 25 59" src="https://user-images.githubusercontent.com/5637792/34110879-461b25d0-e408-11e7-8297-64d96a75778f.png">

And I've landed on `Import Extension`, but I would rather see `List` again.
<img width="1218" alt="screen shot 2017-12-18 at 15 26 10" src="https://user-images.githubusercontent.com/5637792/34110852-302edd16-e408-11e7-812a-07b37813e08d.png">

**Comment by amysueg** [comment]
@dsimansk thanks - we agree, sounds good.

**Comment by akieling** [comment]
@amysueg Is delete a secondary action? If so, would make sense to move it from the inline actions to the drop-down?

**Comment by amysueg** [comment]
Hi @akieling  - thank you for the feedback. Since we only have the Update and Delete actions on the rows, there is no drop-down. If we were to add other actions it would make sense to place it in the drop-down. Thanks again.
