### ISSUE TITLE
Failing MongoDBConnectorCappedCollectionConsumerTest

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#8149]
The build on Friday March 27 failed with:

[...truncated 909.42 KB...] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.36 s - in io.syndesis.connector.mongo.MongoDBConnectorCappedCollectionConsumerAllOptionsTest 
[INFO] Running io.syndesis.connector.mongo.MongoDBConnectorCappedCollectionConsumerTest 
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.434 s <<< FAILURE! - in io.syndesis.connector.mongo.MongoDBConnectorCappedCollectionConsumerTest 
[ERROR] repeatedMongoTest(io.syndesis.connector.mongo.MongoDBConnectorCappedCollectionConsumerTest)  Time elapsed: 2.287 s  <<< FAILURE! 
java.lang.AssertionError: mock://result Received message count. Expected: <1> but was: <2> 
        at io.syndesis.connector.mongo.MongoDBConnectorCappedCollectionConsumerTest.mongoTest(MongoDBConnectorCappedCollectionConsumerTest.java:88) 
        at io.syndesis.connector.mongo.MongoDBConnectorCappedCollectionConsumerTest.repeatedMongoTest(MongoDBConnectorCappedCollectionConsumerTest.java:98)

**Comment by squakez** [comment]
It seems that the mentioned failure log trace is no longer available. However I can see that every process is throwing an error when there is the embedded server shutdown:
```
07:53:55 [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.234 s - in io.syndesis.connector.mongo.MongoDBConnectorCappedCollectionConsumerAllOptionsTest
07:54:06 Exception in thread "Thread-2" java.lang.IllegalStateException: Couldn't kill mongod process!
07:54:06 
07:54:06 ----------------------------------------------------
07:54:06 Something bad happend. We couldn't kill mongod process, and tried a lot.
07:54:06 If you want this problem solved you can help us if you open a new issue.
07:54:06 
07:54:06 Follow this link:
07:54:06 https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues
07:54:06 
07:54:06 Thank you:)
07:54:06 ----------------------------------------------------
07:54:06 
07:54:06 
07:54:06 	at de.flapdoodle.embed.process.runtime.ProcessControl.waitForProcessGotKilled(ProcessControl.java:200)
07:54:06 	at de.flapdoodle.embed.process.runtime.ProcessControl.stop(ProcessControl.java:76)
07:54:06 	at de.flapdoodle.embed.process.runtime.AbstractProcess.stopProcess(AbstractProcess.java:196)
07:54:06 	at de.flapdoodle.embed.mongo.AbstractMongoProcess.stopInternal(AbstractMongoProcess.java:117)
07:54:06 	at de.flapdoodle.embed.process.runtime.AbstractProcess.stop(AbstractProcess.java:177)
07:54:06 	at de.flapdoodle.embed.process.runtime.Executable.stop(Executable.java:80)
07:54:06 	at de.flapdoodle.embed.process.runtime.Executable$JobKiller.run(Executable.java:97)
07:54:06 	at java.lang.Thread.run(Thread.java:748)
07:54:06 [INFO] 
07:54:06 [INFO] Results:
07:54:06 [INFO] 
07:54:06 [INFO] Tests run: 42, Failures: 0, Errors: 0, Skipped: 0
``` 
There is a [pending issue opened on the library](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/268) to fix this issue. I'll try to push the workaround to see if that is also the root cause of our error and have it fixed.
