### ISSUE TITLE
Fix daily builds

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#8151]
The latest successful build is about 5 weeks old. Let's keep a list of the issues are causing this and let's fix them:

#8149 Failing MongoDBConnectorCappedCollectionConsumerTest 
#8150 Cannot build the ReactUI

**Comment by squakez** [comment]
According to [latest build](https://ci.fabric8.io/view/syndesis/job/syndesis-release-daily/799/consoleFull), the MongoDB tests are passing correctly without any exception, so likely the #8155 fixed those. However, let's keep an eye until also the UI is fixed.
