### ISSUE TITLE
Missing daily snapshots

### ISSUE THREAD

**Issue by SvenC56** [syndesisio/syndesis#8160]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Hey,
since two days the daily snapshots are missing. If i run `syndesis install` it installs directly from master if I don't specify the `--tag` arg.
Is there an alternative option to do `syndesis install` from the `1.9.x` branch?

**Comment by zregvart** [comment]
@SvenC56 one option is to [build all images](https://syndesis.io/docs/cli/syndesis/#syndesis-build) and deploy them to your environment.

**Comment by SvenC56** [comment]
Trying to install the latest version is giving me this error:
```bash
[root@server~]# syndesis install  --app-options " --addons dv" --tag 1.9.0-20200401 -w -o
operator binary not found under /root/.syndesis/bin/syndesis-operator, attempting to download...
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
unable to download operator from
unable to download the operator binary, exit
ERROR: Last command exited with 1
```

**Comment by zregvart** [comment]
We've had some mishaps with the daily releases (#8024, #8024) and we have an improvement for the start shell script install in https://github.com/syndesisio/syndesis.io/pull/145. Hopefully we can fix this soon.
