### ISSUE TITLE
Conditional Mapping Expression Error

### ISSUE THREAD

**Issue by SvenC56** [syndesisio/syndesis#8176]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Hey I encountered this behaviour that conditional mapping are not working for me. I get this strange error after the deployment: `TypeError: Cannot read property 'value' of undefined`. If I deploy the app and go to the result I would excpect to get `true` or `false` values. Instead it looks like this:

![image](https://user-images.githubusercontent.com/14073259/78236081-d47e6580-74d9-11ea-8b12-9d7d9ac4b56e.png)

I if query the SQL statement in the Oracle SQL Developer it looks like this:
![image](https://user-images.githubusercontent.com/14073259/78236295-0e4f6c00-74da-11ea-832b-ee68475668c5.png)

I tried to setup conditional mapping like described here: https://access.redhat.com/documentation/en-us/red_hat_fuse/7.5/html/integrating_applications_with_fuse_online/mapping-data_ug

Mapping:
![image](https://user-images.githubusercontent.com/14073259/78235410-e7dd0100-74d8-11ea-9576-f32b9663d8c4.png)

Error after deployment:
![image](https://user-images.githubusercontent.com/14073259/78235541-0fcc6480-74d9-11ea-8045-89e79e4b4e6b.png)

**Comment by zregvart** [comment]
Looks like an [AtlasMap](https://www.atlasmap.io/) issue, should it be [reported there](https://github.com/atlasmap/atlasmap/issues)?

**Comment by SvenC56** [comment]
I created a new issue here: https://github.com/atlasmap/atlasmap/issues/1918

**Comment by zregvart** [comment]
I'll close this, we can reopen if it ends up being non Atlasmap issue or requires a change in Syndesis as well.

**Comment by SvenC56** [comment]
@zregvart Atlasmap Error was fixed here: https://github.com/atlasmap/atlasmap/issues/1918#ref-commit-007bba2

**Comment by zregvart** [comment]
I guess we'll see this in Syndesis 2.0, it's a bit late in the process to bring in a new major release of Atlasmap.
