### ISSUE TITLE
Replace oauth-proxy with keycloak-gatekeeper

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis#8182]
## Description

Investigate using https://github.com/keycloak/keycloak-gatekeeper instead of openshift oauth-proxy.  openshift oauth-proxy was originally made for internal openshift use, and their group does not really like it being used of app level oauth proxying.  But keycloak-gatekeeper is being built for the purpose.  If we can find time, we should see if we can use it to replace the oauth-proxy and if not report back to that project anything that is missing.

**Comment by chirino** [comment]
I've already verified that it supports proxying ws connections.

**Comment by phantomjinx** [comment]
The kubernetes mode of the application now utilises [oauth2-proxy](https://github.com/oauth2-proxy/oauth2-proxy), which allows for authentication against a range of auth [providers](https://oauth2-proxy.github.io/oauth2-proxy/auth-configuration), inc. keycloak. However, at this time [attempts](https://github.com/oauth2-proxy/oauth2-proxy/issues/626) to run-up my own keycloak service and test have not been so successful, although github and google are fine.

Replacing the cut-down oauth-proxy with oauth2-proxy seems a better and less restrictive approach as it allows for many more auth provider integrations.
