### ISSUE TITLE
Add migration scripts for Camel 3 update

### ISSUE THREAD

**Issue by christophd** [syndesisio/syndesis#8210]
We have to make sure that old integrations in DB are working with the new Camel 3 runtime. There may be some migration tasks needed on the integration models.

For instance integrations may refer to `http4` Camel component that has been renamed to `http`

```
"dependencies": [
          {
            "id": "io.syndesis.connector:connector-rest-swagger:2.0-SNAPSHOT",
            "type": "MAVEN"
          },
          {
            "id": "org.apache.camel:camel-rest-openapi:2.23.2.fuse-760011",
            "type": "MAVEN"
          },
          {
            "id": "org.apache.camel:camel-http4:2.23.2.fuse-760011",
            "type": "MAVEN"
          }
        ]
```

We have to add a migration script that automatically fixes these integration models when updating Syndesis.

**Comment by christophd** [comment]
Another finding: everything `org.apache.camel:camel-servlet-starter` needs to be `org.apache.camel.springboot:camel-servlet-starter` in the integration model.json

**Comment by christophd** [comment]
Next finding: `io.syndesis.connector.http.HttpConnectorFactories.Http` has been renamed so all references to this in model.json needs to be fixed

```
"connectorFactory": "io.syndesis.connector.http.HttpConnectorFactories$Http4"
```

**Comment by Delawen** [comment]
Part of this was already migrated by @zregvart on up-40.js and up-41.js.

Adding the missing pieces.
