### ISSUE TITLE
Extension Tab not visible with Camel

### ISSUE THREAD

**Issue by SvenC56** [syndesisio/syndesis#8214]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Documentation issue or request
</code></pre>

## Description

Hey,

I installed the latest stable release `1.9.0` from the release page:

```bash
syndesis install  --app-options " --addons camelk" --camel-k -w -o
```

Now I wanted to add an extension but the tab `Extensions` is not visible to me. Without the `camel-k` option everything is visible to me. Am I missing something? How do I add a JDBC Driver with Camel?

Thank you.

**Comment by zregvart** [comment]
@SvenC56 that's the restriction we have with Camel K in 1.9 see #7790

**Comment by SvenC56** [comment]
Okay thank you for clarification!

**Comment by zregvart** [comment]
I think we can close this now.
