### ISSUE TITLE
Add Syndesis to OperatorHub.io

### ISSUE THREAD

**Issue by Delawen** [syndesisio/syndesis#8218]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Related #8000

We want to add Syndesis to OperatorHub.io.

 https://operatorhub.io/contribute

**Comment by Delawen** [comment]
@lgarciaaco you had things pending. Can you take care of it?

**Comment by michaelwjoyner** [comment]
Woo Hoo!

**Comment by lgarciaaco** [comment]
https://github.com/operator-framework/community-operators/pull/1606
