### ISSUE TITLE
Deploy custom connector with Synthesis 1.9.0

### ISSUE THREAD

**Issue by kerplo** [syndesisio/syndesis#8246]
## This is a...

<pre><code>
[ ] Feature request
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
We are trying to deploy a custom connector with Synthesis 1.9.0. 
Syndesis-operator doesn't use the images of internal docker registry and it downloads them from docker.io. so the version desployed not contains our connector.

We execute the following steps:

- Develop the connector
- Install CRD with `syndesis install --setup --cluster`
- Build all images with `syndesis build -d -c -i -f`
- Build syndesis-operator with `syndesis build -m operator -i`

After this step, syndesis-operator doesn't deploy. If we execute `syndesis install` or `syndesis install --tag 1.9.0` syndesis-operator downloads the images from docker.io.

Previously, with version 1.8.13 we can deploy the connector without any problems.

**Comment by zregvart** [comment]
AFAIK you can build the operator pointing to your own images by modifying [install/operator/build/conf/config.yaml](https://github.com/syndesisio/syndesis/blob/1.9.x/install/operator/build/conf/config.yaml).

Would it not be easier to package your connector as a extension and deploy it that way?
