### ISSUE TITLE
[itest] Can't debug container

### ISSUE THREAD

**Issue by Delawen** [syndesisio/syndesis#8265]
## This is a...

<pre><code>
[ ] Feature request
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

If I try to use the debugging method posted [here](https://github.com/syndesisio/syndesis/blob/master/app/test/integration-test/README.md#debugging%20syndesis), it doesn't suspend the integration container to let me debug. I tried both adding the `.enableDebug()` programatically and adding a `-Dsyndesis.debug.enabled=true` parameter to the `mvn clean verify` command. On both cases (or combined) it just run the test normally.

**Comment by squakez** [comment]
Thanks for reporting.

The issue is because we are running the wrong `mvn` option here: https://github.com/syndesisio/syndesis/blob/master/app/test/test-support/src/main/java/io/syndesis/test/container/integration/SyndesisIntegrationRuntimeContainer.java#L369

Fixing right away...

**Comment by Delawen** [comment]
Thanks! It was making me crazy trying to properly debug stuff :)
