### ISSUE TITLE
`syndesis-operator grant --cluster` error

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#8296]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

If I run `syndesis-operator grant --cluster` I get:

```
error: Object:
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: syndesis-installer-syndesis/syndesis-operator
    namespace: default
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: syndesis-installer
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: syndesis/syndesis-operator
: ClusterRoleBinding.rbac.authorization.k8s.io "syndesis-installer-syndesis/syndesis-operator" is invalid: metadata.name: Invalid value: "syndesis-installer-syndesis/syndesis-operator": may not contain '/'
```

This is with [1.9.0](https://github.com/syndesisio/syndesis/releases/tag/1.9.0)

**Comment by phantomjinx** [comment]
You have missed a --user switch out ...
`syndesis-operator grant --user developer --cluster`

Although, the lack of a `--user <user>` should be better handled.

**Comment by zregvart** [comment]
Not much documentation on this, is there any?

**Comment by lgarciaaco** [comment]
This is probably a bug in [cobra](github.com/spf13/cobra) or something we are missing, because the `user` flag is marked as mandatory:

https://github.com/syndesisio/syndesis/blob/f477ec1b3bd8b8aaaf2ccce12aba775a31f7324e/install/operator/pkg/cmd/internal/grant/grant.go#L55

**Comment by phantomjinx** [comment]
> Not much documentation on this, is there any?

I would say no for 2 reasons:

1. The switches and functionality is the operator has been so fluid, documentation rarely keeps up
2. The operator has tended to be wrapped in other scripts rather than called directly hence direct user interaction has been uncommon.

If we are going to put the operator front and centre then no reason this situation shouldn't change.
