### ISSUE TITLE
crc install with 1.10 won't start

### ISSUE THREAD

**Issue by shawkins** [syndesisio/syndesis#8307]
<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

From master or 1.10.x if I run:

./tools/bin/syndesis crc --install --nodev --project syndesis --tag 1.10.0-20200422

The result is:

Deploying Syndesis operator
ERROR: Last command exited with 1

The 1.9 and 2.0 releases seem to work fine.

**Comment by phantomjinx** [comment]
Think this might be due to #8293, which was only merged this morning (22/4). Building and running from the 1.10.x branch works successfully.

**Comment by shawkins** [comment]
Tested again with seemed to work crc --install --nodev --project syndesis --tag 1.10.0-20200423
