### ISSUE TITLE
Guided Tour Toggle & FTU Only

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis#835]
It disappeared. I remember there was discussion of it always appearing even if you are not a first time user, but I must have missed the memo about it getting disabled completely for now. We need to resolve this by using a flag that determines whether the user is truly a first time user or not (unless that's already in place?).

**Comment by zregvart** [comment]
I definitely see the guided tour when I access the UI on localhost (started via `yarn start`). I don't see it on OpenShift (deployed on minishift locally). In both cases I have `guidedTourState` set to `true` in local storage.
