### ISSUE TITLE
Bump Java version on building

### ISSUE THREAD

**Issue by Delawen** [syndesisio/syndesis#8422]
## This is a...

<pre><code>
[ x ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Bump Java version beyond 8 (11?). Java 8 is not very maintained anymore and we should move on.

Useful for #8269

**Comment by zregvart** [comment]
In #8269 the requirement is that the build system runs on Java 9+, preferably 11. What is the goal of this issue? What use of Java does this target?

**Comment by Delawen** [comment]
When trying to build with Java 11 yesterday I discovered some issues. It looks like @phantomjinx did too (see mailing list). I just wanted an issue to track this.

**Comment by Delawen** [comment]
Maybe the answer is just "use java 9" or maybe we can bump further, just checking.

**Comment by Delawen** [comment]
My problem is similar but on a different class than what @phantomjinx gets:

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project common-util: Compilation failure
> [ERROR] /var/git/syndesis-bump-java-version/app/common/util/src/main/java/io/syndesis/common/util/MavenProperties.java:[18,17] cannot access java.util.Map
> [ERROR]   bad class file: /8/java/util/Map.sig
> [ERROR]     class file has wrong version 55.0, should be 53.0
> [ERROR]     Please remove or make sure it appears in the correct subdirectory of the classpath.
> [ERROR] 


Just checking this is not some dirty local env mixing java versions...

**Comment by squakez** [comment]
As we will require this to enable `camel k` 1.0, I'm adding a label so we will track it more easily under those issues needed to fix for camel k runtime.

**Comment by Delawen** [comment]
great, thanks!
