### ISSUE TITLE
[Camel K] Cannot install Syndesis if a Camel K 1.0 is previously installed in the cluster

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/syndesis#8465]
I am trying the installer binaries from [1] and it fails with:

```
hbraun:Downloads$ ./syndesis-operator install 
error: Object:
  apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    labels:
      app: camel-k
    name: integrationplatforms.camel.apache.org
  spec:
    additionalPrinterColumns:
    - JSONPath: .status.phase
      description: The IntegrationPlatform phase
      name: Phase
      type: string
    group: camel.apache.org
    names:
      kind: IntegrationPlatform
      listKind: IntegrationPlatformList
      plural: integrationplatforms
      shortNames:
      - ip
      singular: integrationplatform
    scope: Namespaced
    subresources:
      status: {}
    version: v1alpha1
: CustomResourceDefinition.apiextensions.k8s.io "integrationplatforms.camel.apache.org" is invalid: spec.version: Invalid value: "v1alpha1": must match the first version in spec.versions
```

Am I doing it wrong?

[1] https://github.com/syndesisio/syndesis/releases/tag/1.10.0-20200514

**Comment by zregvart** [comment]
Most likely Camel K CRD version mismatch, you most likely have a newer version of CamelK CRD installed and we're trying to install [`camel.apache.org/v1alpha1`](https://github.com/syndesisio/syndesis/blob/1.10.0-20200514/install/operator/pkg/generator/assets/addons/camelk/camel-catalog-2.23.2.fuse-760024.yaml.tmpl#L8), perhaps you have [v1](https://github.com/apache/camel-k/blob/master/deploy/crd-integration-platform.yaml#L27) installed

**Comment by squakez** [comment]
I've faced the same issue. As @zregvart pointed out it's due to a newer version of `camelk` installed. You can fix it by uninstalling `camelk` and remove the following crds:
```
$ oc get crd | grep camel
builds.camel.apache.org                                     2020-06-16T10:18:53Z
camelcatalogs.camel.apache.org                              2020-06-16T10:18:53Z
integrationkits.camel.apache.org                            2020-06-16T10:18:53Z
integrationplatforms.camel.apache.org                       2020-06-16T10:18:53Z
integrations.camel.apache.org                               2020-06-16T10:18:53Z
```
Then you can proceed with `syndesis` installation procedure. Please, let me know if that is okey so we can close this issue.

**Comment by squakez** [comment]
I've analyzed this better, and in the light of moving toward `camel k` 1.0 is a limitation we need to fix. Adding to the group of issues we need to solve for camel K.
