### ISSUE TITLE
Bump rollup Version

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis#8503]
Upgrade rollup, it's a major version upgrade that is being pulled in by our fork of `history`: https://github.com/syndesisio/syndesis/tree/master/app/ui-react/packages/history

ref: https://github.com/syndesisio/syndesis/pull/8449

cc @riccardo-forina

**Comment by riccardo-forina** [comment]
Yeah I don’t think we want to ever touch that lib ever again, unless we make it a proper fork. But it would be wiser to find a way that doesn’t rely on a fork of an upstream dep to preserve the app state.
