### ISSUE TITLE
Create "guard rails" for auto-generated UIs

### ISSUE THREAD

**Issue by amysueg** [syndesisio/syndesis#851]
This issue is a placeholder for a UX deliverable that will assist with auto-generated UIs for additional connection screens. We'd like to work with development to look for opportunities to document some basic page elements, their locations, common components, behaviors and so on. 

This is an example of the kind of approach we're thinking of that @catrobson shared with us from Open Shift IO (6-page InVision mockup): https://redhat.invisionapp.com/share/8QACKL3AY#/screens

FYI @sjcox-rh @dongniwang @seanforyou23

**Comment by gashcrumb** [comment]
Has there been any movement on this?  This seems like it's gone stale...

**Comment by dongniwang** [comment]
Do we have a _backlog_ label that we can use for something similar to this?

**Comment by gashcrumb** [comment]
not a label no, but this is definitely deep in the backlog :-)

**Comment by amysueg** [comment]
I still think this is a good idea. Adding @michael-coker  since he joined the team after we created this issue and it might be something he could look at (when the time is right).

**Comment by amysueg** [comment]
I'm going to close this.

We have a new issue to create a connection template #2212 that will work.
