### ISSUE TITLE
[Connection autodiscovery] Always showing a "connection modified" warning

### ISSUE THREAD

**Issue by squakez** [syndesisio/syndesis#8519]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When we use the connection autodiscovery feature (available only for Kafka connector at the moment), we always have a warning notifying the user that the connection changed:

![image](https://user-images.githubusercontent.com/23169723/82542501-5e4dc500-9b52-11ea-91e6-5526ba91e5ce.png)

I guess that the warning simply matches the `connection` json configuration stored in the database against the `integration` json configuration enriched with dynamic properties. This is a bit misleading as the connection did not really change.

**Comment by gashcrumb** [comment]
As background, these messages are driven by the BE, the UI doesn't have any logic to suppress any messages, it just formats them appropriately based on the severity and displays them.

**Comment by squakez** [comment]
Thanks @gashcrumb. It seems that those messages are processed by [bulletins boards ](https://github.com/syndesisio/syndesis/tree/master/app/common/model/src/main/java/io/syndesis/common/model/bulletin)
