### ISSUE TITLE
DefaultValue is not set for the boolean returnBody in the api-provider

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#8637]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[*] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
Both the webhook and the api-connector are setting the defaultValue for 'returnBody' to *true*.

```
"returnBody": {
"order": 3,
"componentProperty": false,
"defaultValue": true,
"deprecated": false,
"displayName": "Include error message in the return body",
"javaType": "Boolean",
"kind": "parameter",
"required": false,
"secret": false,
"type": "boolean"
},
```

When create a new integration with a webhook the check is indeed checked
![unnamed](https://user-images.githubusercontent.com/35576/83754484-53278880-a66c-11ea-8d2f-b7ba776e610d.png)

However it is *not* set when using the api-provider

![unnamed-1](https://user-images.githubusercontent.com/35576/83754570-72261a80-a66c-11ea-905b-dbb3848630d4.png)

To reproduce
1. Create a new integration using the api-provider and configure the final step of any of the flows. See that the returnBody check is not set.

**Comment by KurtStam** [comment]
@kahboom I think something is wrong with the form component. Is this something you can look into?

**Comment by kahboom** [comment]
Sure @KurtStam , I might be a few days as I'm currently working on a few other things, but I'll certainly take a look.

**Comment by gashcrumb** [comment]
Hmm, it's set like that in the generator response in the generated `configuredProperties` object for the step.  In this case then `defaultValue` won't be used at all:

![image](https://user-images.githubusercontent.com/351660/84795238-3886d500-afc5-11ea-86f5-829296d3ba92.png)

**Comment by kahboom** [comment]
cc @KurtStam - I can verify what @gashcrumb has said. We use autoform in this part of the app so that gets generated automatically.

**Comment by KurtStam** [comment]
@kahboom so is autoform not used for same page for webhook? And so this is a limitation of the autoform component that can be fixed?
