### ISSUE TITLE
Re-enable incremental integration pod builds

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#864]
To fix #761 we disabled incremental builds in #863. This has helped. We should find a way to enable incremental builds and not encounter the permission issue untaring in #761.

**Comment by nicolaferraro** [comment]
Also, we should enable incremental builds if they give some advantages in terms of build speed.
If we add more artifacts to the base s2i image, the time spent to download missing artifacts from maven may be less than the time needed to untar+tar the full m2 directory (depending on how many jars we put there).

Incremental builds should theoretically improve the speed of the 2nd build, but they always slow down the first one, as they add a tar of the m2 directory that normally is not done.
