### ISSUE TITLE
May I know when will the 1.10/2.x will be released with soap connector?

### ISSUE THREAD

**Issue by yanxuehe** [syndesisio/syndesis#8680]
May I know when will the 1.10/2.x will be released with soap connector?

thanks very much

**Comment by squakez** [comment]
Hi @yanxuehe. `1.10` is on its way to be released, it would be a matter of some more day.

**Comment by yanxuehe** [comment]
@squakez thanks for your information.

does the 1.10 will support SOAP connector?

is there any way to create a SOAP Connection in 1.9?

Thank you

**Comment by squakez** [comment]
Yes, SOAP will be an important upgrade we've carried on for `1.10`. Unfortunately I don't see an easy way to have soap working with the connectors we support in `1.9`.

**Comment by squakez** [comment]
We released SOAP connector in 1.10: https://syndesis.io/blog/2020/07/23/release-1-10/
