### ISSUE TITLE
OCP4 integration log link failing

### ISSUE THREAD

**Issue by squakez** [syndesisio/syndesis#8684]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
I managed to reproduce this issue on CRC but I think it's related to OCP4 way of managing pod tabs that's different from OCP3. Basically when clicking on integration building/deploying log such as in snapshot:

![Screenshot from 2020-06-11 10-16-11](https://user-images.githubusercontent.com/23169723/84361979-c8dfa700-abcc-11ea-8798-5d456da7370b.png)

We are landing to a 404 page instead of the openshift console log tab as shown in this snapshot:

![Screenshot from 2020-06-11 10-11-52](https://user-images.githubusercontent.com/23169723/84362126-07756180-abcd-11ea-9436-219664a04380.png)

**Comment by gashcrumb** [comment]
Can you check in the `config.json` that the UI fetches if the `consoleUrl` property is empty?  That's the usual reason this behavior is seen.  The trouble has been in the past that there hasn't been a good way to discover the openshift console URL to better support this.

That being said, if the URL structure is different in 4.x then we'll probably also need to better externalize how the link is constructed, currently it's [quite hard coded](https://github.com/syndesisio/syndesis/blob/1277b33d1d520b9673a5899b77449f469dc40379/app/ui-react/syndesis/src/app/App.tsx#L48-L50).

**Comment by squakez** [comment]
Yes, I think we must review the way the link is built. I think we should leverage Kubernetes API in order to retrieve and stream the log on our own therefore being completely decoupled by the platform running.

**Comment by rafamqrs** [comment]
Hello, 

I had the same problem, I'm running OCP 4.7 and the Fuse Online 7.8.0 installed from Operator Hub.
My config.json, i just removed the url of my cluster and replaced by <clusterurl>
{
  "apiBase": "https://syndesis-<clusterurl>",
  "apiEndpoint": "/api/v1",
  "consoleUrl": "",
  "project": "fuse-online",
  "datamapper": {
    "baseMappingServiceUrl": "https://syndesis-<clusterurl>/api/v1/atlas/",
    "baseJavaInspectionServiceUrl": "https://syndesis<clusterurl>/api/v1/atlas/java/",
    "baseXMLInspectionServiceUrl": "https://syndesis<clusterurl>/api/v1/atlas/xml/",
    "baseJSONInspectionServiceUrl": "https://syndesis-<clusterurl>/api/v1/atlas/json/",
    "disableMappingPreviewMode": false
  },
  "features" : {
    "logging": false
  },
  "branding": {
    "appName": "Fuse Online",
    "favicon32": "/favicon-32x32.png",
    "favicon16": "/favicon-16x16.png",
    "touchIcon": "/apple-touch-icon.png",
    "productBuild": true
 }
}
