### ISSUE TITLE
Webhook value setting incorrect when using default values

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#8687]
When the default values are accepted for the webhook config, it is expected that an error condition would result in an HTTP 400, however it is returning a 200. It looks like 'errorResponseCodes' is NOT set when accepting the default values:

```
 "configuredProperties": {
  "contextPath": "hu9mnMVeDlsRMc3BuPBgHbc0V7PylgsjZzyZ2qjvGXzVfGeuey",
  "errorResponseCodes": "{}",
  "httpResponseCode": "200",
  "returnBody": "true"
},
```

while after playing with the settings it is:

```
"configuredProperties": {
"contextPath": "Xu1L9UNOJ9C6FG3hUKGOfwQvG3yqmIjMk6fAIOiiGPsgJnhHpU",
"errorResponseCodes": "{\"SERVER_ERROR\":\"400\"}",
"httpResponseCode": "200",
"returnBody": "true"
},
```

So then it correctly defines: 
`"errorResponseCodes": "{\"SERVER_ERROR\":\"400\"}",`

What the client sees:
```
curl -k https://i-test-myproject.192.168.42.38.nip.io/webhook/Xu1L9UNOJ9C6FG3hUKGOfwQvG3yqmIjMk6fAIOiiGPsgJnhHpU
{"httpResponseCode":200,"category":"SERVER_ERROR","message":"PreparedStatementCallback; ERROR: invalid input syntax for type date: \"Red Hat\"\n  Position: 43; nested exception is org.postgresql.util.PSQLException: ERROR: invalid input syntax for type date: \"Red Hat\"\n  Position: 43","error":"data_integrity_violation_error"}% 
```                                                      

```
curl -k https://i-test-myproject.192.168.42.38.nip.io/webhook/Xu1L9UNOJ9C6FG3hUKGOfwQvG3yqmIjMk6fAIOiiGPsgJnhHpU
{"httpResponseCode":400,"category":"SERVER_ERROR","message":"PreparedStatementCallback; ERROR: invalid input syntax for type date: \"Red Hat\"\n  Position: 43; nested exception is org.postgresql.util.PSQLException: ERROR: invalid input syntax for type date: \"Red Hat\"\n  Position: 43","error":"data_integrity_violation_error"}% 
```

**Comment by KurtStam** [comment]
Hi @kahboom, is this something you can take a look at? See also https://issues.redhat.com/browse/ENTESB-13988

**Comment by gashcrumb** [comment]
If nothing is touched in the form then it'll use whatever the `defaultValue` property setting is, which for webhook appears to be:

![image](https://user-images.githubusercontent.com/351660/84373866-2cf17380-abab-11ea-9245-e3b8b4c5d8c6.png)

**Comment by KurtStam** [comment]
Thx  @gashcrumb that makes a lot of sense.

**Comment by KurtStam** [comment]
The PR was still sitting there: https://github.com/syndesisio/syndesis/pull/8943 - trying to get it merged
