### ISSUE TITLE
Problem with loading components using online version (502 bad gateway)

### ISSUE THREAD

**Issue by oosnmcd** [syndesisio/syndesis#8700]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Hi, 
I was just up to test Red Hat Fusion Online and the loading components don't load retrieving Bad Gateway error, tried no cache load, on different pc's and different internet connections, as tried the google DNS, nothing did work. 
Am I failling to instal something (as I didn't install anything, once it wasn't requested)? Is this a bug on my side?

Bellow there is an image so you can understand what I'm dealing here (it happens with any other component)

<img width="959" alt="Capture error" src="https://user-images.githubusercontent.com/66417760/84671366-323e1d80-af1f-11ea-9008-666fa62f07e3.PNG">

Thanks and regards, 
Nuno.

**Comment by squakez** [comment]
Hello, thanks for reporting the issue. Can you please provide the installation procedure you've done before running the application? Also, is it running on an OCP cluster or a local minishift/crc instance?

**Comment by oosnmcd** [comment]
> Hello, thanks for reporting the issue. Can you please provide the installation procedure you've done before running the application? Also, is it running on an OCP cluster or a local minishift/crc instance?
Hi, thanks for the dispended time to reply to my question. As it was said, I didn't install any component hence it was said in the Quickstart guide that the quickest way to try it would be running it online on Red Hat Fuse, without having to install any component. Am I in need to install any component or deploying it?

**Comment by squakez** [comment]
I see, then it's the Red Hat Fuse managed service you're trying to use. I guess you must raise an issue within the Red Hat Fuse support channel in order to fix that. Syndesis is the community project on which Fuse Online is based.

**Comment by oosnmcd** [comment]
@squakez Yes, I understood that! The only reason I reported it here was because the button "Report the issue" redirects to the syndesis issue page! Thanks for the time disposed!

**Comment by claudio4j** [comment]
Can you open the browser console and see if there are errors ? Also, if you have access to the openshift console, can you look at the syndesis-server pod for errors ?
