### ISSUE TITLE
api-provider errormapping wrong when using defaultValue

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#8705]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

This issue is similar to #8687 but now for the api-provider. There are really 2 issues:

1. The defaultValue set is not used when creating the integration
```

"defaultValue": "{\"SERVER_ERROR\":\"500\"}",

"configuredProperties": {
"errorResponseCodes": "{}",             <--- empty
"httpResponseCode": "200",
"returnBody": "false"
},
```
2. The defaultValue really depends on the number of errors defined in the flow: if there are more connectors in the flow then there will be more errors and thus the defaultValue needs to contain a default value for each error. it is impossible to know this ahead of time. It'd be much better if the UI computes this. It should be something like

```
"configuredProperties": {
"errorResponseCodes": "{\"TRANSIENT_DATA_ACCESS_ERROR\":\"500\",\"SERVER_ERROR\":\"500\",\"CONNECTOR_ERROR\":\"500\",\"DATA_ACCESS_ERROR\":\"500\",\"DUPLICATE_KEY_ERROR\":\"500\",\"ENTITY_NOT_FOUND_ERROR\":\"500\"}",
"httpResponseCode": "200",
"returnBody": "false"
},

```

**Comment by gashcrumb** [comment]
It's more tricky than that.  When the integrations are generated the `configuredProperties` for that step is already filled in:

![image](https://user-images.githubusercontent.com/351660/84783258-0bcbc100-afb7-11ea-9eed-cef209963f9c.png)

so the `defaultValue` setting won't apply in any case.  I might be able to check this value and see if it's an empty object and then adjust it however.

**Comment by gashcrumb** [comment]
actually @KurtStam could we remove that default value that's being put in the configured properties object by the generator?  That alongside some changes I have locally I think would be the cleanest way to tackle this.

**Comment by KurtStam** [comment]
@gashcrumb sure: just remove it from:
https://github.com/syndesisio/syndesis/blob/master/app/connector/api-provider/src/main/resources/META-INF/syndesis/connector/api-provider.json#L129
and
https://github.com/syndesisio/syndesis/blob/master/app/connector/webhook/src/main/resources/META-INF/syndesis/connector/webhook.json#L112

**Comment by gashcrumb** [comment]
I don't think that'll do it, as I'm overriding the `defaultValue` property in the form definition.  Because `errorResponseKeys` has a value in the `configuredProperties` object being given to auto-form, it won't replace that value unless the user changes it.  The *only* time this value would be written is if the setting isn't in the `configuredProperties` object to begin with, so we need to change the API provider generator so that it doesn't write an empty object into that particular property and instead just leaves it completely unset.

**Comment by gashcrumb** [comment]
I could [check at this point](https://github.com/syndesisio/syndesis/blob/cc24f1d8d92b4b7555351ae52c37feb01883f070/app/ui-react/packages/auto-form/src/utils.ts#L172) if it's empty but I dunno that seems a bit low-level.

**Comment by KurtStam** [comment]
@gashcrumb I can take a look at 

> we need to change the API provider generator so that it doesn't write an empty object into that particular property and instead just leaves it completely unset.

I'm assuming we're fixing this for api-provider as well as webhook?

**Comment by gashcrumb** [comment]
Well, give me a bit, am exploring how this would look to sort it in auto-form.
