### ISSUE TITLE
Upgrade PatternFly to latest v4 and React 17

### ISSUE THREAD

**Issue by riccardo-forina** [syndesisio/syndesis#8707]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
[X] Chore
</code></pre>

## Description

https://medium.com/patternfly/patternflys-major-release-everything-you-need-to-know-1f9e50be81e8
https://github.com/patternfly/pf-codemods

This needs to be done in sync with AtlasMap: https://github.com/atlasmap/atlasmap/issues/2186

**Comment by igarashitm** [comment]
I'd like to have this reconsidered, it's almost done in AtlasMap upstream
https://github.com/atlasmap/atlasmap/pull/2752
https://github.com/atlasmap/atlasmap/pull/2779
