### ISSUE TITLE
[Camel K] Syndesis Kamel CLI reset failure

### ISSUE THREAD

**Issue by squakez** [syndesisio/syndesis#8745]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
```
$ syndesis kamel --reset
error: the server doesn't have a resource type "integrationcontext"
```
Likely it's because the CLI is not in synch with latest `camel-k` CRDs.

**Comment by Delawen** [comment]
Waiting for the new version of Camel-K on Syndesis to not redo work later: #8765
