### ISSUE TITLE
Speed up CI through decoupling components execution

### ISSUE THREAD

**Issue by balejos** [syndesisio/syndesis#8756]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
CI is taking too long to execute even when changes are minimal and localized in a component.

This is a request to tweak the CI execution that can limit its scope to the components that have actually changed.
It means that, ideally, if the changes affect only the backend, the front shouldn't be recompiled and tested, and vice-versa.
Additionally, Maven should only work with the dependencies affected

**Comment by Delawen** [comment]
But before merging I would like to do the full build and test.

Would it make sense to have a quick build of parts affected and then, if it doesn't fail, continue?

**Comment by Delawen** [comment]
Or maybe use Circle CI AND Github Actions, each doing a different checks, so they run in parallel?
