### ISSUE TITLE
Bump camel base version to 3.3

### ISSUE THREAD

**Issue by squakez** [syndesisio/syndesis#8764]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Required to target camel k 1.3 runtime.

**Comment by oscerd** [comment]
There is 3.4.0 already out

**Comment by squakez** [comment]
Thanks @oscerd. The upgrade is mostly due to have camel k runtime dependencies aligned. As we're targeting camel k 1.3, and it's using camel 3.3 platform I think that should be the one we have to stick for our base development.
