### ISSUE TITLE
Take prototype jaeger interaction with OLM and extend to other services

### ISSUE THREAD

**Issue by phantomjinx** [syndesisio/syndesis#8784]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
The jaeger operator and operands are provided, where applicable via a subscription to the OLM and OperatorHub. Only in limited standalone use-cases is the jaeger operator now separately installed. Use a similar approach with the Prometheus component and investigate whether such a scenario is applicable for the postgresql database component.

**Comment by squakez** [comment]
Wouldn't this also apply to `camel-k` operator?

**Comment by phantomjinx** [comment]
> Wouldn't this also apply to `camel-k` operator?

Yes.
