### ISSUE TITLE
Support Java Data Shapes in Extensions

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#880]
As today inspection as served as static resources but for extensions, custom connectors, etc they are not known at build time so we may need to load inspections from i.e. the database.

The path to access the static resource is:

    mapper/v1/java-inspections/${componentId}/${full.qualified.class.name}.json

As we are listing only java types, we can get rid of the ${componentId} so it can be more generic and can work with different type of sources (i.e.e extensions) like:

    inspections/${type}/${inspectionId}

where 
- `${type}` for the moment has a single value `java` but can have `json-schema` and so on
- `${inspectionId}` is context dependent so i.e for `java` it is has the following form `${full.qualified.class.name}.json`

**Comment by chirino** [comment]
Extensions could just embed the inspection into the model.   To keep thing simple, I propose we jam the precomputed inspection into a java's data shape 'specification' field.  Example:

```json
"outputDataShape": {
  "kind": "java",
  "type": "twitter4j.Status",
  "specification": "<put the precomputed shape here>"
},
```

This way we don't have to change much.  Just a small tweak in how the UI initializes the atlas mapper.

**Comment by chirino** [comment]
PR https://github.com/syndesisio/syndesis/pull/914 has the change needed in the UI to use the specification field that way.
