### ISSUE TITLE
Upgrade jenkins release-daily build to use jdk 11

### ISSUE THREAD

**Issue by phantomjinx** [syndesisio/syndesis#8804]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Release builds failing due to using jdk 8 rather than jdk 11 for building master branch
Error is:
`invalid flag: --release`

**Comment by claudio4j** [comment]
I added the JDK 11 and changed the syndesis-release-daily. The build doesn't fail on the reported error, but fails on the ui-react stage as it gets killed by OS.
