### ISSUE TITLE
CircleCI nightly job needs to use jdk11

### ISSUE THREAD

**Issue by christophd** [syndesisio/syndesis#8812]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Nightly job for executing the integration tests on CircleCi needs to use jdk11. The nightly job uses the machine executor because of Testcontainers and this VM is using jdk8. We need to find a way to get jdk11 into the machine executor.

The concept of [Orbs in CircleCI](https://circleci.com/docs/2.0/orb-intro/#section=configuration) could help us here. See also this example orb here for installing jdk11 on the machine executor: https://circleci.com/orbs/registry/orb/entur/vm-install-tools

**Comment by Delawen** [comment]
Is it not? https://github.com/syndesisio/syndesis/blob/master/.circleci/config.yml#L42

**Comment by christophd** [comment]
@Delawen unfortunately not the case because we can not use the Docker image. We have to use the VM image instead https://github.com/syndesisio/syndesis/blob/master/.circleci/config.yml#L565
