### ISSUE TITLE
[Data Mapper] Constants and properties with the same name can be created by adding a space in the name

### ISSUE THREAD

**Issue by rkarputs** [syndesisio/syndesis#8826]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
In the Data Mapper user is able to create constants and properties with the same name using spaces in the end of the name.
E.g. when user created three properties (or constants) with names 'test', 'test ', 'test  ' (pay attention on spaces), all of them will be created with identical name. 

## Steps to reproduce
1) Go to the Data Mapper.
2) Click on the '+' button opposite the Properties (or Constants).
3) Specify the name, e.g. 'Test'. Save changes.
4) Add another property (constant) and use the same name but with a space in the end ('Test '). Save changes.

## Actual result
Two properties (constants) with identical name are successfully created.

## Expected result
A validation error, no ability to create properties (constants) with the same name.

**Comment by zregvart** [comment]
@igarashitm looks like this should be fixed in AtlasMap

**Comment by igarashitm** [comment]
Issue moved to [atlasmap/atlasmap #2937](https://github.com/atlasmap/atlasmap/issues/2937) via [**ZenHub**](https://www.zenhub.com/)
