### ISSUE TITLE
[Data Mapper] User is not able to delete / modify a property when it was created with a space in the name

### ISSUE THREAD

**Issue by rkarputs** [syndesisio/syndesis#8827]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When user created a property in the Data Mapper with a space in the name, e.g. 'new test', he is not able anymore to modify its Name / Value / Value Type, all changes just cannot be applied after saving. Also user cannot delete this property.

## Steps to reproduce
1) Go to the Data Mapper.
2) Click on the '+' button in the Properties tab to create a new property.
3) Specify property name with a space, e.g. 'new test'.
4) Click the 'Confirm' button.
5) Try to modify the property (name/value/value type).
6) Try to delete the property.

## Actual result
Nothing happens when trying to modify/delete the property. Changes are not applied.

## Expected result
User is able to modify/delete the property. Or if spaces using is forbidden, user should not have the ability to use them.

**Comment by zregvart** [comment]
@igarashitm one to consider as well

**Comment by igarashitm** [comment]
Issue moved to [atlasmap/atlasmap #2938](https://github.com/atlasmap/atlasmap/issues/2938) via [**ZenHub**](https://www.zenhub.com/)
