### ISSUE TITLE
Document "syndesis system-test"

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#883]
Please add documentation to `syndesis system-test` to https://doc.syndesis.io/#_how_it_works.

The source is in `doc/sdh/build/cmd_system_test.adoc`

**Comment by iocanel** [comment]
merged

**Comment by rhuss** [comment]
thanks @iocanel , but could we have this in the SDH please ? (as described in the issue above). Reason is that we try to consolidate all documentation in a single document so thats its easier to find for us.
