### ISSUE TITLE
I try to create a redis connector, but the camelContext can not load the 'spring-redis' component

### ISSUE THREAD

**Issue by yueraiyu** [syndesisio/syndesis#8831]
## This is a test, 

<pre><code>
@Override
    protected List<Step> createSteps() {
        return Arrays.asList(
                newSimpleEndpointStep("direct", builder -> builder.putConfiguredProperty("name", "start")),
                newEndpointStep("spring-redis", "io.syndesis.connector:connector-spring-redis-ping",
                        builder -> {},
                        builder -> {
                            builder.putConfiguredProperty("host", "127.0.0.1");
                            builder.putConfiguredProperty("port", "6379");
                        })
        );
    }

@Test
    public void testPing(){
        String result = template.requestBody("direct:start", "test", String.class);
        assertEquals("test", result);
    }
</code></pre>

**Comment by oscerd** [comment]
There is no Spring redis connector in Syndesis

**Comment by yueraiyu** [comment]
I want develop a new Syndesis connector, use the [Apache Camel SPRING REDIS component](https://camel.apache.org/components/latest/spring-redis-component.html)

**Comment by oscerd** [comment]
You're welcome to contribute to Syndesis

**Comment by yueraiyu** [comment]
the method createSteps() return two steps, i can't find the code how to load the 'spring-reids' camel component. Can you help me? @oscerd

**Comment by oscerd** [comment]
Take as example the other connector in the project and develop the connector. This is not the way of contributing one new connector.

**Comment by squakez** [comment]
@yueraiyu you can use the tutorial to create a new connector: https://syndesis.io/docs/connectors/create/
