### ISSUE TITLE
OutOfMemory error and long loading integrations on  Sydnesis-server when integration have a lot of FHIR Connections

### ISSUE THREAD

**Issue by HudkovNickola** [syndesisio/syndesis#8832]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[х] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

When there are many FHIR connections in the integration, the integrations take a long time to load on the UI page and you can also get the OutOfMemory error.
Increasing heap saves from OutOfMemory errors, but not from long loading of integrations.
Apparently, the 'FHIR connection' object keeps track of FHIR resource instances and from this, they weigh a lot than other connections. This is just a thought.

![1 (10)](https://user-images.githubusercontent.com/16764373/88170704-d2761900-cc26-11ea-9352-0b3eb9d54aa6.png)

And heap snapshot of loaded integration Page 
![image](https://user-images.githubusercontent.com/16764373/88171325-cfc7f380-cc27-11ea-8d0f-36bb4a98875a.png)

If needed we can provide you heap dumps.

**Comment by Delawen** [comment]
Can you provide an export of the inegration with the FHIR connections? That could help us test it.

**Comment by HudkovNickola** [comment]
[Test Syndesis integration-export.zip](https://github.com/syndesisio/syndesis/files/4959961/Test.Syndesis.integration-export.zip)
Steps to reproduce the error with this integration: 
1. Clon this integration 5 times or more, (open model.json and change ids for unique)
2. Export all integrations.
3. Open the integrations page and refresh a few times.
Expecting: long loading pages and error OutOfMemory
