### ISSUE TITLE
Need mechanism for ordering form controls

### ISSUE THREAD

**Issue by seanforyou23** [syndesisio/syndesis#886]
We need a simple way to drive the order of form controls in our dynamically generated forms. These forms use [ng-dynamic-forms](https://github.com/udos86/ng-dynamic-forms) under the hood.

The order of controls in the form model are retained when the form is rendered, so we're halfway there. 

The problem is that at some point during the service request the shape of the model changes (between where defined in deployment.json and what the forms.service.ts passes to the view layer).

Ultimately the goal is for this to be driven via deployment.json properties, that way the UI doesn't have to make exceptions for individual forms throughout the app.

Adding an ordered array as part of each propertyDefinitionSteps property in deployment.json, and consulting that to re-order the model structure may be a good solution.

This issue is a result of breaking down the remaining work needed for https://github.com/syndesisio/syndesis/issues/637.

**Comment by gashcrumb** [comment]
Is there a particular example where the form definition gets changed between what's shown in the deployment json and in the UI?  It might be worth validating exactly where the property definition gets reordered, i.e. does the form object coming back from the server look right?

It's probably still worth adding an override attribute to the form config object anyways, as there's always the chance we'll want or need to re-order elements in the form.  Adding support for a `controls` attribute would work, i.e. use an array of property IDs that define the order of the form elements, the form service can then use this if available when building the form objects.

**Comment by gashcrumb** [comment]
Just checking the form page when creating a broker connection.  It looks like the form is rendered in the same order as the data comes back from the backend, in my case (snipping out the content of each property value):

```json
      "name": "AMQ",
      "properties": {
        "brokerCertificate": {
        },
        "brokerUrl": {
        },
        "clientCertificate": {
        },
        "clientID": {
        },
        "password": {
        },
        "skipCertificateCheck": {
        },
        "username": {
        }
      },
      "configuredProperties": {},
      "dependencies": []
    },
```

I could add a quick fix so we could fix the order client-side easily enough for a short term fix but I think we should also get the backend to ensure it maintains order as laid out in the deployment json for form configs if possible.

Most likely I'll add support for a 'controls' attribute that's an array of strings using property IDs like we had in `hawtio-forms`, so for example:

```json
MyThing: {
  properties: {
      "one": { },
      "two": {},
      "three": {}   
  },
  controls: ["two", "*"],
}
```

Which would lay out the form like `two`, `one`, `three`, wildcard there being an optional thing.  Then this can be added to the deployment.json as needed to fix the form order.

@jimmidyson @KurtStam thoughts on the backend part of this?

**Comment by deeleman** [comment]
Perhaps turning the `properties` node into an array of named property definition objects might be even simpler. Honoring the sorting order of the array would just suffice then.

**Comment by jimmidyson** [comment]
Just remind me what REST call is being made here?

**Comment by gashcrumb** [comment]
@jimmidyson looks like it's the result of `api/v1/connectors` in the create connection form, when you pick the connector that definition is used to create the form instance.

@deeleman certainly but not a change I'd be comfortable to make in the tp3 timeframe, these form definitions are used throughout the app, and am not sure all of them are defined in the one deployment.json

**Comment by seanforyou23** [comment]
I was able to track the request back to loadAll() in entity.store.ts, the data comes in alphabetical order at this point, which seems to be used from there forward in the UI. If there is a way to retain the order of the JSON from the back-end, may be that a change isn't needed in the UI at all. Possible?

> turning the properties node into an array of named property definition objects
This sounds like a nice way of doing things, using arrays when ordering matters is most intuitive for me.

I'm also a fan of the approach gashcrumb mentioned from hawtio-forms, the end result seems just as effective.

Would either of these approaches be more reusable than the other if we were to, at some point, drop ng-dynamic-forms? Just trying to keep the options open.

**Comment by gashcrumb** [comment]
I'm going to first off add support for a `controls` parameter to the form service that can let us first off locally tweak forms as needed.  We can also then add `controls` to the descriptor objects in the backend which will then let the form order be controlled by the backend.
