### ISSUE TITLE
Create mechanism for conditionally displaying form fields

### ISSUE THREAD

**Issue by seanforyou23** [syndesisio/syndesis#887]
We need a way to conditionally display form fields based on another fields value, and for it to be configuration-driven.

This is needed for the AMQ configure connection flow - https://github.com/syndesisio/syndesis/blob/master/ux/designs/amq/amq.md

There seems to be support for this in ng-dynamic-forms, but the forms.service.ts doesn't know about it yet - https://github.com/udos86/ng-dynamic-forms#related-form-controls.

**Comment by deeleman** [comment]
> We need a way to conditionally display form fields based on another fields value

Angular template syntax will give you all what you need to perform this with no effort.

**Comment by seanforyou23** [comment]
It's a good point deeleman. The making it configurable from json bit is what I'm still trying to think through. I could manually add the form controls and use template syntax to handle displaying the fields, but then the ordering becomes difficult to manage across the board.

Both you and gashcrumb had some good points about it today, so I'm still investigating all the helpful advice. Also, this is related to a general discussion about forms direction that patternfly-ng folks are beginning to have, I'll bring this up tomorrow and see what suggestions/ideas come up.

If nothing else I can always build these forms by hand until we get a solution we feel good about for the long run. Keep you posted!

**Comment by gashcrumb** [comment]
I could see leveraging the form configuration syntax that ng-dynamic-forms supplies as something that's doable in the tp3 timeframe.  Pulling out ng-dynamic-forms and replacing it right now I think is not possible.  I guess the first question is, does this need to be sorted for tp3 or can it wait for tp4?

**Comment by gashcrumb** [comment]
I think leveraging this support is the way to go -> https://github.com/udos86/ng-dynamic-forms#related-form-controls

as we can then add this to the form object definition by adding a `relation` property to a given form control, the form builder service can then add this relation property to the configuration object that's passed into the constructor for a given form control.

**Comment by gashcrumb** [comment]
So basically in these spots:

* https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/common/forms.service.ts#L61-L66
* https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/common/forms.service.ts#L79-L89
* https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/common/forms.service.ts#L79-L89
* https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/common/forms.service.ts#L128-L145
we could add:

```typescript
   relation: field.relation,
```

and then in the deployment.json on a given field:

```json
  "properties": {
     "MyProp": {
        "relation": [
           {
               "action": "HIDDEN",
               "when": [{
                 "id": "OtherProp",
                 "value": "false"
               }]
           }
        ]
     }
   }
```

Looks like `HIDDEN` and `VISIBLE` were added at this point -> https://github.com/udos86/ng-dynamic-forms/commit/2541ab5422464d7f54c56089d2347d5cb3a911cb

So we'd need to update our dependency to at least version 5.0.0 which also added angular 5 support.

**Comment by gashcrumb** [comment]
Currently blocked by https://github.com/syndesisio/syndesis/issues/938

**Comment by seanforyou23** [comment]
Decided to resume this issue without upgrading the forms library as that's dependent on other, bigger upgrades (namely angular core).

Going to try and take deeleman's advice and make this work using a custom template.

**Comment by seanforyou23** [comment]
This work is blocked - https://github.com/udos86/ng-dynamic-forms/issues/335 and https://github.com/udos86/ng-dynamic-forms/issues/253 will help.

I looked into a stop-gap solution for this that didn't rely on the underlying dynamic forms model but quickly realized it isn't the right direction to go. We'd be fighting the library instead of benefitting from it while polluting our forms service with code that may become difficult to maintain.

Enable/disable relation are solid and will land us almost all of what we need from an interactivity standpoint without accruing any additional technical debt. We should resume this work once the visible/hidden feature is natively supported by the library.

**Comment by dhirajsb** [comment]
@seanforyou23 added PR https://github.com/syndesisio/syndesis/pull/1910 to add these fields to properties. Try it by pulling my ui-hints branch and let me know if it works for you.

**Comment by amysueg** [comment]
@seanforyou23 should we close this issue?

**Comment by dhirajsb** [comment]
@gashcrumb should we close this as an initial version of this feature? And create a new one for enhancements?

**Comment by gashcrumb** [comment]
It's not sorted on the UI side as the issue is blocked pending upstream implementation.  I mean it's great that the backend supports the relation property but we don't properly support it in the frontend still, and afaik that is what this issue tracks.

**Comment by dhirajsb** [comment]
@gashcrumb makes sense, will leave it open for ui folks to close.
