### ISSUE TITLE
Sf connector issue, no endpoint could be found

### ISSUE THREAD

**Issue by tplevko** [syndesisio/syndesis#888]
There is an issue when creating the Tw->Sf integration using the [fuse ignite sample integration tutorial.](https://access.redhat.com/documentation/en-us/red_hat_jboss_fuse/7.0-tp/html-single/fuse_ignite_sample_integration_tutorial/) The error I hit in this case is:

```
org.apache.camel.RuntimeCamelException: org.apache.camel.FailedToCreateRouteException: Failed to create route flow1 at: >>> Filter[{io.syndesis.integration.runtime.util.JsonSimplePredicate@6fff46bf} -> [To[atlas:mapping-step-3.json], To[salesforce-create-sobject-3?sObjectName=Contact]]] <<< in route: Route(flow1)[[From[twitter-timeline-1]] -> [Filter[{io.synde... because of No endpoint could be found for: salesforce-create-sobject-3?sObjectName=Contact, please check your classpath contains the needed Camel component jar.
```

The whole log file is also attached.
[twsftest-2.log](https://github.com/syndesisio/syndesis/files/1599749/twsftest-2.log)

The exported integration is also attached.
[twsftest-export.zip](https://github.com/syndesisio/syndesis/files/1599755/twsftest-export.zip)

**Comment by zregvart** [comment]
@lburgazzoli could this be a project generator issue, I see `salesforce-create-sobject-3` in `syndesis.yml` and `salesforce-create-sobject` in `application.properties` (from secret).

<details>
<summary>syndesis.yml</summary>
<pre>
---
flows:
- steps:
  - kind: connector
    componentId: twitter-timeline-1
    componentScheme: twitter-timeline
    properties:
      accessToken: '{{twitter-timeline-1.accessToken}}'
      accessTokenSecret: '{{twitter-timeline-1.accessTokenSecret}}'
      consumerKey: ...
      consumerSecret: ...
      delay: "30000"
      timelineType: MENTIONS
  - kind: filter
    expression: ${body.text} contains '#hello'
    steps:
    - kind: endpoint
      uri: atlas:mapping-step-3.json
    - kind: endpoint
      uri: salesforce-create-sobject-3
      properties:
        sObjectName: Contact
</pre>
</details>

<details>
<summary>application.properties</summary>
<pre>
salesforce-create-sobject.configurations.salesforce-create-sobject-4.refreshToken=...
salesforce-create-sobject.configurations.salesforce-create-sobject-4.clientId=...
twitter-timeline-1.consumerKey=...
twitter-timeline-1.accessTokenSecret=...
twitter-timeline-1.accessToken=...
twitter-timeline-1.consumerSecret=...
salesforce-create-sobject.configurations.salesforce-create-sobject-4.clientSecret=...
</pre>
</details>

**Comment by iocanel** [comment]
I think that this is due to the use of the filter step.
AFAIR, the filter step refactors the steps by moving all following steps as nested. 

Need to have a closer look.
