### ISSUE TITLE
Error report I can't access the logs at Fuse Online

### ISSUE THREAD

**Issue by brunopenha** [syndesisio/syndesis#8916]
## This is a issue when I try to access the logs of the application on Fusion Online (from workshop demo)

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

When I was starting an integration and I clicked in the link "See the logs" I was redirect to a page saying "404"

**Comment by squakez** [comment]
Thanks for reporting. I think this is the same as #8684 - can you confirm it does happen running in an openshift 4 platform?
