### ISSUE TITLE
Can't create an integration using S3 component, no actions showing

### ISSUE THREAD

**Issue by tplevko** [syndesisio/syndesis#904]
"A picture is worth a thousand words"
![s3_integration_no_actions](https://user-images.githubusercontent.com/4180208/34553089-e5dce12e-f125-11e7-8905-c3225e0f1625.png)

**Comment by oscerd** [comment]
Maybe the logs of syndesis-rest are better than a picture.

**Comment by oscerd** [comment]
BTW there were no update on the connector side, so probably it's something from elsewhere.

**Comment by tplevko** [comment]
There is nothing interesting in the syndesis-rest logs, but @dsimansk seems to have identified source of the issue. There are no actions with "from" pattern in the [deployment.json](https://github.com/syndesisio/syndesis/blob/master/app/rest/dao/src/main/resources/io/syndesis/dao/deployment.json#L1836)

**Comment by dsimansk** [comment]
And there was a recent [change](https://github.com/syndesisio/syndesis/pull/871) that introduced action filtering in the UI.

**Comment by oscerd** [comment]
That's the original behavior, the copy object stuff is only a To. The change is not super clear, but I'll take a look there.

**Comment by tplevko** [comment]
@oscerd I meant to highlight the polling action, sorry for misdirection.

**Comment by oscerd** [comment]
Yeah, sorry. I didn't understand. I don't know why there is a To in the polling action

**Comment by oscerd** [comment]
I'm fixing it :-)

**Comment by tplevko** [comment]
Thanks for the quick fix! :+1:

**Comment by oscerd** [comment]
Sorry for the misunderstanding :-)
