### ISSUE TITLE
Tech Extensions to Extensions renaming leftover in URL

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis#907]
I've noticed that the UI impl still uses `customizations/tech-extensions` as a reference for the Extensions page. Should it be renamed also to keep consistency?

@jimmidyson I've set the TP3 label. If you feel like this is super minor, just go ahead and move it further.

**Comment by jimmidyson** [comment]
Agree we should change this - let me submit a quick PR. Should be simple enough to review.
