### ISSUE TITLE
[Feature Request] An integration platform as a microservice platfrom.

### ISSUE THREAD

**Issue by MingningShao** [syndesisio/syndesis#9079]
Hi, Team
Syndesis works as an integration platform for SOA/ESB, some legacy systems.
Well, lots company want move to the cloud for their legacy system, most of them are monoliths.
But it's hard...
Syndesis can provide the capability to integrate them.
So, if Syndesis can provide a secondary development environment for those systems, just regard them as components, or do some new API development.
A new microservice for a new use case with legacy system without distill or refactor.
A whole lifecycle/platform for legacy system modernize or integration.
That's interesting.

**Comment by squakez** [comment]
Thanks for submitting the request @MingningShao. Some time ago I wrote about a possible way to look at [Syndesis as a microservices orchestrator](https://developers.redhat.com/blog/2020/03/25/low-code-microservices-orchestration-with-syndesis/). You can already leverage most of the features offered by the platform to go in that direction.
