### ISSUE TITLE
Integrations: infinite loading loop when Twitter Mention action is selected 

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis#908]
When I'm trying to create integration with Twitter Mention action there's infinite loading loop without any particular error in `syndesis-rest` or browser console. Also the response for twitter-mention is returned correctly with HTTP 200 code.

But e.g. Twitter Search behaves normally and when selected the details form is displayed.

```
{
  "componentScheme": "twitter-timeline",
  "connectorCustomizers": [],
  "inputDataShape": {
    "kind": "none"
  },
  "outputDataShape": {
    "kind": "java",
    "type": "twitter4j.Status"
  },
  "propertyDefinitionSteps": [],
  "configuredProperties": {
    "timelineType": "MENTIONS",
    "delay": "30000"
  }
```

![screen shot 2018-01-04 at 09 58 58](https://user-images.githubusercontent.com/5637792/34556271-fa01ed10-f135-11e7-9ce1-04265d8b3cf8.png)

**Comment by gashcrumb** [comment]
I probably broke this yesterday as I think about it since 'mention' doesn't have any form configuration as I recall.
