### ISSUE TITLE
Integrations: Done button is disabled for Invoke Stored Procedure action

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis#909]
`Invoke Stored Procedure` actions has only dropdown for procedure name parameter, hence there's no sql command input to validate the `Done` button is disable without any chance to proceed further.

<img width="500" alt="screen shot 2018-01-04 at 10 09 46" src="https://user-images.githubusercontent.com/5637792/34556654-7c4d54e8-f137-11e7-83bc-c88c6bbbfa02.png">

**Comment by jimmidyson** [comment]
@gashcrumb Could you look at this ASAP please?

**Comment by dsimansk** [comment]
To provide more details, imho this issue is caused by changes for issue https://github.com/syndesisio/syndesis/issues/718 and in PR https://github.com/syndesisio/syndesis/pull/885.

**Comment by jimmidyson** [comment]
I think this is to do with https://github.com/syndesisio/syndesis/blob/master/app/rest/dao/src/main/resources/io/syndesis/dao/deployment.json#L1359-L1372 - a required property with no default that is hidden so cannot be set...

@KurtStam I assume that should be changed to required=false or removed totally?

**Comment by gashcrumb** [comment]
Yeah, the form is behaving as designed :-)

Having a required hidden property doesn't make much sense but it's allowed.

**Comment by KurtStam** [comment]
The template is a parameter that is required to be set, but it's created by the verifier, so it's preset. The user shouldn't see (and modify) it, which is why it's hidden.
