### ISSUE TITLE
Integrations: infinite loading loop when S3 to S3 Copy Object action is selected

### ISSUE THREAD

**Issue by tplevko** [syndesisio/syndesis#912]
I experience similar, but not quite the same issue as in https://github.com/syndesisio/syndesis/issues/908.
The waiting for integration is also indefinite, but there is also an error in the browser console, as can be seen on the screenshot: 
![s3_integration_waiting](https://user-images.githubusercontent.com/4180208/34563563-56c7c444-f153-11e7-9791-4944e26527f4.png)

**Comment by gashcrumb** [comment]
Just tested this with the attached PR in place, I think this will be fixed too once this PR is merged.
