### ISSUE TITLE
The execution time duration  is wrong in an intergation start with a connection which have bulitin  timer(sql-start-connector)

### ISSUE THREAD

**Issue by ashenp** [syndesisio/syndesis#9158]
## This is a Bug

When the camel route start with sql connector, the route is like: from(timer:xxxx).

In the IntegrationRouteBuilder, on this condition  the sql connection does not in a pipeline due to code below:
![image](https://user-images.githubusercontent.com/14103968/97299049-4f9cd400-188f-11eb-976a-c4c321cb0d08.png)

the pipeline which means to set flowId  ends the pipeline itself,  it keeps the sql action out of a pipeline, so in the activity tracking process, the first step ends with a duration,  but the real sql does not begin to execute, the duration is just about the time cost  in the camel-timer component

**Comment by zregvart** [comment]
@ashenp looks like you have this figured out, feel free to create pull request to fix this.
