### ISSUE TITLE
How to connect to kafka which is hosted somewhere else

### ISSUE THREAD

**Issue by rahul-sharma-js** [syndesisio/syndesis#9193]
How can I connect to Kafka which is not hosted in same cluster as syndesis. Lets say I want to connect to cloudkafka.com kafka instance using below details. How can I do that?

Username: xxxxxx
Password: yyyyyy
Topic prefix: hqwr3qei-
Servers: tricycle-01.srvs.cloudkafka.com:9094, tricycle-02.srvs.cloudkafka.com:9094, tricycle-03.srvs.cloudkafka.com:9094

There is no option to enter username and password in syndesis kafka connector

**Comment by squakez** [comment]
Hi @rahul-sharma-js, kafka connector is working within any kafka service exposed either internally or externally to the cluster. There is no support for authentication (ie, SASL), we only provide TLS encryption at the moment. During next release, on `1.x` branch, we are going to provide an extension for the downstream camel kafka component parameters, so, you should be able to set it up accordingly. Keep it tuned.
