### ISSUE TITLE
error: unable to retrieve the complete list of server APIs:

### ISSUE THREAD

**Issue by vacheli** [syndesisio/syndesis#9207]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
syndesis-operator

error: unable to retrieve the complete list of server APIs: servicecatalog.k8s.io/v1beta1: the server is currently unable to handle the request

The pod don't access servicecatalog.k8s.io/v1beta1; Beacuse of network is forbiddened.

**Comment by zregvart** [comment]
Hi, that looks like an issue with the way permissions/cluster is setup on your end. Perhaps you can attach the whole operator log and explain the steps you took to install the operator (via OperatorHub, scripts, ...).
