### ISSUE TITLE
How to build locally modified connector and push it into minishift

### ISSUE THREAD

**Issue by kovel** [syndesisio/syndesis#9208]
How to build locally modified connector and push it into minishift

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Documentation issue or request
</code></pre>

**Comment by zregvart** [comment]
Have a look at the [connector development guide](https://syndesis.io/docs/connectors/create/#integrating-a-new-connector-with-existing-connectors). In particular you need to add it to the S2I module and rebuild/push that image.
