### ISSUE TITLE
supported K8s clustering

### ISSUE THREAD

**Issue by zhangzhen108** [syndesisio/syndesis#9227]
Does this project support K8S clustering?
because our systems are integrated with the K8S.

**Comment by zregvart** [comment]
Hi @zhangzhen108, not sure what you mean by "Kubernetes clustering", we can install and run on a Kubernetes cluster, see [the README](https://github.com/syndesisio/syndesis/blob/master/install/kubernetes/README.md). This is part of the 2.0 (master branch) and hasn't been released as stable, so if you can provide any feedback on this this would help us improve.

**Comment by zhangzhen108** [comment]
Does Version 2.0 support running With Kubernetes Clustering？ When do you plan to release a stable version of 2.0?

**Comment by zregvart** [comment]
@zhangzhen108 we intend to ship 2.0 with full installing and running on Kubernetes. Not sure when we'll finish or how much is still left to do. You can try running from the linked documentation and provide feedback on what is not working or missing for you.

**Comment by zhangzhen108** [comment]
I see. Thank you

**Comment by zhangzhen108** [comment]
We installing it on Kubernetes，but the program reported an error,the error is the lack of crd.
How can I solve it?

**Comment by zregvart** [comment]
@zhangzhen108 in the README I've linked to prior, you'll find instructions on [how to install Syndesis](https://github.com/syndesisio/syndesis/blob/master/install/kubernetes/README.md#syndesis-install) on Kubernetes. There are prerequisites on doing that, so please go through the README carefully.
