### ISSUE TITLE
Migrate community jobs to github actions

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#9274]
The [fabric8 CI](https://fabric8-ci.fusesource.com/) instance isn't going to be around much longer.  There's some jobs on this instance that are still run for PR builds etc. that need a new home, maybe they could be moved to github actions.

The ones that definitely need to move are:

- syndesis-circleci-to-quay
- the *-release jobs (?)

**Comment by zregvart** [comment]
We no longer need the `syndesis-circleci-to-quay` or the newer `syndesis-github-to-quay`, and the work on getting the release ported to GitHub Actions is [underway](https://github.com/zregvart/syndesis/tree/pr/release-via-github-actions), in the interim we can do manual releases if needed.
