### ISSUE TITLE
API connector: swagger file in yaml format

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis#929]
@zregvart has create an API definition for our Todo app. But our wizard seems a bit picky about yaml file format. Should we just stick with json for now? 

https://github.com/syndesisio/todo-example/blob/master/swagger.yaml

For the GH's raw link:
<img width="739" alt="screen shot 2018-01-05 at 14 58 46" src="https://user-images.githubusercontent.com/5637792/34612209-0297ea12-f229-11e7-9ef6-2aaf998ae117.png">

For direct Minishift link to Todo:
<img width="745" alt="screen shot 2018-01-05 at 15 00 03" src="https://user-images.githubusercontent.com/5637792/34612261-4a10938a-f229-11e7-917a-58915d23c124.png">

**Comment by dsimansk** [comment]
Exception on syndesis-rest for yaml file parsing: https://gist.github.com/dsimansk/a1345b52d113452be024c2b9a7bca2c5h

**Comment by dsimansk** [comment]
My previous gist is missing, here's the fresh one for the reference:
https://gist.github.com/dsimansk/8b5d3683c5a838a75335724dd7a1b22c

**Comment by zregvart** [comment]
In #949 I opted to fix YAML validation issue and did not take the TLS trust issue under consideration, I feel we need to have a global TLS settings and include the OpenShift signer CA by default in there.

**Comment by dsimansk** [comment]
@zregvart I couldn't reproduce the TLS error on Ignite cluster, only on my Minishift with self-generated cert. I'd assume that on properly configured cluster CA are imported correctly.
