### ISSUE TITLE
API connector: no actions to Start integration with 

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis#930]
All the actions imported from Swagger definition seems to have property pre-set `"pattern": "To"`. That inherently means that non actions is shown for Start of the integration.

Example of getPetById from http://petstore.swagger.io/. 
```
 {
    "id": "io.syndesis:rest-swagger-connector:1.2-SNAPSHOT:-L25NxnJs0XHQzqXVWMo:getPetById",
    "name": "Find pet by ID",
    "description": "Returns a single pet",
    "descriptor": {
      "connectorId": "-L25NxnJs0XHQzqXVWMo",
      "camelConnectorGAV": "io.syndesis:rest-swagger-connector:1.2-SNAPSHOT",
      "camelConnectorPrefix": "swagger-operation",
      "connectorCustomizers": [],
      "inputDataShape": {
        "kind": "json-schema",
        "specification": "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"type\":\"object\",\"properties\":{\"parameters\":{\"type\":\"object\",\"properties\":{\"petId\":{\"type\":\"integer\",\"title\":\"petId\",\"description\":\"ID of pet to return\"}}}}}"
      },
      "outputDataShape": {
        "kind": "json-schema",
        "specification": "{\"type\":\"object\",\"required\":[\"name\",\"photoUrls\"],\"properties\":{\"id\":{\"type\":\"integer\",\"format\":\"int64\"},\"category\":{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"integer\",\"format\":\"int64\"},\"name\":{\"type\":\"string\"}},\"xml\":{\"name\":\"Category\"}},\"name\":{\"type\":\"string\",\"example\":\"doggie\"},\"photoUrls\":{\"type\":\"array\",\"xml\":{\"name\":\"photoUrl\",\"wrapped\":true},\"items\":{\"type\":\"string\"}},\"tags\":{\"type\":\"array\",\"xml\":{\"name\":\"tag\",\"wrapped\":true},\"items\":{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"integer\",\"format\":\"int64\"},\"name\":{\"type\":\"string\"}},\"xml\":{\"name\":\"Tag\"}}},\"status\":{\"type\":\"string\",\"description\":\"pet status in the store\",\"enum\":[\"available\",\"pending\",\"sold\"]}},\"xml\":{\"name\":\"Pet\"},\"$schema\":\"http://json-schema.org/schema#\",\"title\":\"Pet\"}"
      },
      "propertyDefinitionSteps": [],
      "configuredProperties": {
        "operationId": "getPetById"
      }
    },
    "tags": ["pet"],
    "actionType": "connector",
    "dependencies": [{
      "type": "MAVEN",
      "id": "io.syndesis:rest-swagger-connector:1.2-SNAPSHOT"
    }],
```

<img width="923" alt="screen shot 2018-01-05 at 15 07 27" src="https://user-images.githubusercontent.com/5637792/34612591-cd4c0dd2-f22a-11e7-85a0-f85769bfdee1.png">

**Comment by gashcrumb** [comment]
That connection shouldn't even show up then at the choose a connection step IMO

**Comment by gashcrumb** [comment]
On that note created https://github.com/syndesisio/syndesis/issues/935

**Comment by dsimansk** [comment]
@gashcrumb agreed, but in this particular case. There're actions from API imported that could be used as Start of integration, but aren't configured with a From pattern property.

@zregvart fyi could this issue be addressed in backend to decide if an action should be created with From or To pattern. There was a recent change and UI integration editor now filters actions based on the pattern property.

**Comment by zregvart** [comment]
> @zregvart fyi. Could this issue be addressed in backend to decide if an action should be created with From or To pattern? There was a recent change and UI integration editor now filters actions based on the pattern property.

REST APIs can only be a _To_, same as SQL-based connectors. Though all connectors can be periodically triggered if we specify schedule properties (like in SQL connector). We might support two cases: _From_ and _To with scheduling_ for starting step.

**Comment by dsimansk** [comment]
@zregvart yep, makes sense now. Sorry, I haven't realized that initially. Scheduling in general is a timer right(clean&simple)? Do we want to support it? :)

I guess this issue just boils down to #935 then.

**Comment by zregvart** [comment]
> Do we want to support it?

I think there are use cases that this is required, like take data from this SaaS service and put it in this database. Might be just a UI issue, if a _To_ action is chosen as start, offer to specify scheduler properties. We can tag actions/connectors that support this.

**Comment by gashcrumb** [comment]
Maybe instead of `From` and `To` we should have gone with `In`, `Out` and `InOut`, where the latter could be used and the backend could selectively add scheduler config during action configuration.

**Comment by zregvart** [comment]
I moved this to TP4, lets see what we can come up with.

**Comment by gashcrumb** [comment]
BTW, we hide connections that don't have any actions that specify `To` at this stage, I dunno, does this issue still need to be open or is there a more specific issue that should be created from this one?

**Comment by zregvart** [comment]
Lets go with #736 and close this.
