### ISSUE TITLE
API connector: swagger file upload doesn't work

### ISSUE THREAD

**Issue by mastepan** [syndesisio/syndesis#931]
I can select a file from my HDD but nothing happens after that. I can't continue to the next wizard step when creating a new API connector.
![uploadswagger](https://user-images.githubusercontent.com/8707251/34612894-edfd7970-f22b-11e7-98a2-fd7a40fd38cb.png)

**Comment by mastepan** [comment]
Also Connector image in the next wizard step can't be uploaded. It may be a similar problem..

**Comment by deeleman** [comment]
> I can select a file from my HDD but nothing happens after that. 

There is no multipart upload support in that step. @jimmidyson is looking into a quick fix for that ATM.

> Also Connector image in the next wizard step can't be uploaded. 

Support there is properly implemented (although the detail page which is meant to display that information is still a WIP. See #720 ). What error are you getting? Thanks.

**Comment by jimmidyson** [comment]
Endpoint implemented in #934.

**Comment by deeleman** [comment]
UI upload functionality implemented i #936
