### ISSUE TITLE
Connections with no 'from' actions (or whatever pattern is) shouldn't be shown in the beginning step position

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#935]
In the editor currently I think you can pick a connection at the start position of the integration that has no actions that actually belong at the beginning of an integration flow.

I think connections like this should be either hidden altogether at this step or grayed out with a tooltip that explains why the connection cannot be selected. 

Same goes for connections at the end of an integration, if the connection has actions that only produce messages but does not accept messages those connections shouldn't be available to pick at that step either. 

 This would prevent the surprising realization after picking such a connection that you cannot pick any actions :-)

@dongniwang WDYT, hidden or grayed out?

**Comment by dongniwang** [comment]
I think grayed out with a tooltip explaining why would be great here. Hiding those connections may cause confusion to the users.

**Comment by gashcrumb** [comment]
+1 no connection and no explanation will give people anxiety :-)

**Comment by gashcrumb** [comment]
This was implemented but we hide connections that can't be selected vs disabling them.
