### ISSUE TITLE
Upgrade ng-dynamic-forms

### ISSUE THREAD

**Issue by seanforyou23** [syndesisio/syndesis#938]
While upgrading ng-dynamic-forms as part of https://github.com/syndesisio/syndesis/pull/897 it was realized that several other peer dependencies will need to be upgraded at the same time, as they share dependencies.

Possibly more, but these seem to be the main libraries needing an upgrade.

ng-dynamic-forms
ngx-chips
ngx-bootstrap
rxjs

**Comment by gashcrumb** [comment]
This may need to formally wait for #378 and #377 as the attached PR brings in updates to angular and angular-cli that yield more fun things to solve :-)
