### ISSUE TITLE
media type problem

### ISSUE THREAD

**Issue by zhangzhen108** [syndesisio/syndesis#9388]
I used API provider to generate an interface, requiring that the media type of interface input should be application/x-www-form-urlencoded, but the mapping source could not be found during data mapping.
  example:
     
![image](https://user-images.githubusercontent.com/29484154/109146264-90095180-779e-11eb-8925-cddb455f4f6a.png)

  data mapper:
    
![image](https://user-images.githubusercontent.com/29484154/109146343-ac0cf300-779e-11eb-8ff9-e258af8849f5.png)

  Does the media type support application/x-www-form-urlencoded type?

**Comment by zregvart** [comment]
@zhangzhen108 yes, that is correct we only support `application/json` and `application/xml` at the moment.

**Comment by zhangzhen108** [comment]
thanks!
 
 I have another question.

 does the data mapper support header paramter to header paramter?
  
    Integrations:

    
![image](https://user-images.githubusercontent.com/29484154/109446151-1a420600-7a7c-11eb-91b5-aaedbce97658.png)

   data mapper:
   
   
![image](https://user-images.githubusercontent.com/29484154/109446213-32b22080-7a7c-11eb-9e7a-4d0ab151ce92.png)


  but I receive accessToken is null, why?

**Comment by zregvart** [comment]
> does the data mapper support header paramter to header paramter?

It's opaque to the mapper where a value appears, a HTTP request in Syndesis is internalized as a JSON or XML payload in Camel message body, and any query, path or header parameters are passed within the `parameters` element of that. The API provider and API clients functionality takes into account the OpenAPI/Swagger document and sets the given parameters. You can look in the activity tracking and see the JSON or XML of the request.

> but I receive accessToken is null, why?

Difficult to tell with the amount of information provided here, was the parameter passed in (via HTTP header, query or path parameter)? Perhaps if you share a bit more details, including how you invoke the API, export of the integration we might be able to help you.

**Comment by zhangzhen108** [comment]
![image](https://user-images.githubusercontent.com/29484154/109484563-8c860b00-7abb-11eb-8954-2b30ad637277.png)

  I found out it was intercepted here, but I don't know why

**Comment by zhangzhen108** [comment]
![image](https://user-images.githubusercontent.com/29484154/109484813-d7a01e00-7abb-11eb-9b96-2b720bce4828.png)

 The isWhiteListed method returns false.  The applyFilterToCamelHeaders method return true.
 So header is not added.

 Can you tell me how to configure it to carry headers?

 integration :
[syndesis-medicine-shop-record-save-export.zip](https://github.com/syndesisio/syndesis/files/6060875/syndesis-medicine-shop-record-save-export.zip)
![image](https://user-images.githubusercontent.com/29484154/109486291-a3c5f800-7abd-11eb-942f-53d2c13cb695.png)

**Comment by zregvart** [comment]
@zhangzhen108 I think you found a bug. I've created #9397 to fix this. Can we follow up there and close this discussion here?

**Comment by zhangzhen108** [comment]
yes,I can do it

**Comment by zregvart** [comment]
Let's focus on fixing the issue in #9397 if you want to reach out we're also chatting on [Gitter](https://gitter.im/syndesisio/community) and there is a [Google group](https://groups.google.com/g/syndesis).
