### ISSUE TITLE
Integrated publishing issues

### ISSUE THREAD

**Issue by zhangzhen108** [syndesisio/syndesis#9409]
Does each project currently generated consist of only one integration?
 Is an integration just an application too resource-intensive?

**Comment by zregvart** [comment]
> Does each project currently generated consist of only one integration?

There is no notion of a "project" in Syndesis, one can design an Integration, and that Integration is deployed as a single Pod.

> Is an integration just an application too resource-intensive?

Not sure what you mean here, amount of resources consumed by an Integration pod is in direct correlation to what the Integration does and how often it does that.

**Comment by zhangzhen108** [comment]
Deploy one HTTP endpoint in one pod, then deploy 100 PODS and 100 HTTP endpoints in one pod, then deploy 1 POD.Which is the better resource?

**Comment by zregvart** [comment]
> Deploy one HTTP endpoint in one pod, then deploy 100 PODS and 100 HTTP endpoints in one pod, then deploy 1 POD.Which is the better resource?

That also depends on what those HTTP endpoints are doing, but in general due to the overhead of JVM it's always better to group functionality together.

**Comment by zhangzhen108** [comment]
Deploy one integration in one pod, then 100 identical integrations in one pod, then 100 identical integrations in one pod, then 1 pod.Which is the better resource?
     I also feel that grouping is better, in fact, there is the concept of application. Is deployment of grouping integration now supported? Is there a follow-up development plan?

**Comment by zregvart** [comment]
> Is deployment of grouping integration now supported? Is there a follow-up development plan?

The unit of design and deployment is single Integration, we have no plans (currently) on supporting grouping Integrations together.

**Comment by zregvart** [comment]
Discussion ended
