### ISSUE TITLE
Extensions: Import page is called Update when creating fresh extension

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis#948]
Shouldn't be the title`Import` for the first time importing the extension jar and `Update` for the update of existing one?

![screen shot 2018-01-08 at 12 49 41](https://user-images.githubusercontent.com/5637792/34669544-7ae6ce84-f472-11e7-8058-eeeb43f62494.png)

**Comment by gashcrumb** [comment]
yep :-)
