### ISSUE TITLE
Link to user doc for TP3

### ISSUE THREAD

**Issue by TovaCohen** [syndesisio/syndesis#955]
In TP2, in the Ignite UI, when the user selected the help icon and then "Documentation" (in the upper right) the target is:

https://access.redhat.com/documentation/en-us/red_hat_jboss_fuse/7.0-tp/html-single/fuse_ignite_sample_integration_tutorial/

For TP3, this needs to change to a landing page that provides links to two books:
- Sample Integration Tutorials
- Integrating Applications with Ignite

The second title is where the user will find the doc for API connectors, extensions, DB connector, AMQ connector and so on. 

@fbolton  can we say now what the link will be for the landing page?

**Comment by fbolton** [comment]
It ought to be:
https://access.redhat.com/documentation/en-us/red_hat_jboss_fuse/?version=7.0-tp

This is the splash page for all 7.0 TP docs (not just the Ignite docs).

**Comment by TovaCohen** [comment]
Hmmm. I wonder if we will make the Ignite user work too hard to find the doc.
Maybe it would be better to provide two links from the Ignite help menu:
   Sample Integration Tutorials 
   User Guide
   Contact Us
and provide a direct link to each book. @kcbabo what would you like to see?
I think I will also make sure that there is a link from each book to the other book.

**Comment by kcbabo** [comment]
Yeah, maybe best to just have multiple doc links in the Ignite UI.

**Comment by TovaCohen** [comment]
Okay then the two links would be:

**Sample Integration Tutorials** > https://access.redhat.com/documentation/en-us/red_hat_jboss_fuse/7.0-tp/html-single/fuse_ignite_sample_integration_tutorials/

**User Guide** > https://access.redhat.com/documentation/en-us/red_hat_jboss_fuse/7.0-tp/html-single/integrating_applications_with_ignite/

Note that the TP3 URL for the tutorials has an "s" at the very end. The TP2 tutorial URL did not have this "s".
