### ISSUE TITLE
Navigating between steps when editing integration doesn't work

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#961]
When trying to navigate between steps with one of the steps open unexpectedly the same step is shown. Funny, the document location seems to be the same when navigating directly.

I made a video:

![step-routing](https://user-images.githubusercontent.com/1306050/34710372-4bf3c6dc-f51b-11e7-9cf8-4bce73d1034d.gif)

**Comment by gashcrumb** [comment]
Hmm, while in a step you shouldn't be able to navigate to another step by design, will have to look into how this crept in.
