### ISSUE TITLE
http Integration problem

### ISSUE THREAD

**Issue by suoxun** [syndesisio/syndesis#9627]
Can I connect the incoming and outgoing parameter forwarding of multiple HTTP requests in an integration.

Now I can create two HTTP connections to forward the input and output parameters. Multiple parameters will fail.

**Comment by zregvart** [comment]
Perhaps you can look into REST API provider support and REST API clients, they offer much better handling of parameters as they rely on the OpenAPI documents instead of ad-hoc parameter names. See https://syndesis.io/manual/integrating-applications/#trigger-integrations-with-api-calls_ug and https://syndesis.io/manual/connecting/#create-rest-api-connection_rest

**Comment by suoxun** [comment]
> Perhaps you can look into REST API provider support and REST API clients, they offer much better handling of parameters as they rely on the OpenAPI documents instead of ad-hoc parameter names. See https://syndesis.io/manual/integrating-applications/#trigger-integrations-with-api-calls_ug and https://syndesis.io/manual/connecting/#create-rest-api-connection_rest

Now I have a requirement that I need to consume data through Kafka and then forward it to the third-party interface (the third-party interface will forward more than 2 outgoing and incoming parameters). Because API provider is only the interface of the generated project, not the third-party interface. My needs are as follows:(although multiple connections can be made, only the first two third-party HTTP interfaces have input parameter and output parameter mapping.)

![image](https://user-images.githubusercontent.com/48100625/120878959-863f8780-c5f2-11eb-9d91-cf1918c8e44d.png)

If this is the case, is it possible to use API provider to make some connections in the middle, or syndesis does not support the forwarding of multiple third-party HTTP connections.(I personally think that although API provider can realize multiple connections, it is only an internal interface, which does not meet the requirements of calling external interfaces.)

**Comment by zregvart** [comment]
No exactly sure what is asked here. You can add a Data Mapper step in between connection actions (like Invoke URL) if you provide a data shape for them, based on the screenshot you provided there is no data shape defined. The HTTP connector doesn't handle the header or query parameters as neatly as the Custom API connector does, so using those will be an issue. And one other thing, in the Data Mapper you can use data from previous steps, not sure if that's what you need but perhaps it can be useful for you. The requirement for that is that data shapes are defined, this is the cornerstone of using the Data Mapper effectively.

**Comment by suoxun** [comment]
> No exactly sure what is asked here. You can add a Data Mapper step in between connection actions (like Invoke URL) if you provide a data shape for them, based on the screenshot you provided there is no data shape defined. The HTTP connector doesn't handle the header or query parameters as neatly as the Custom API connector does, so using those will be an issue. And one other thing, in the Data Mapper you can use data from previous steps, not sure if that's what you need but perhaps it can be useful for you. The requirement for that is that data shapes are defined, this is the cornerstone of using the Data Mapper effectively.

In fact, when I configure three HTTP external interfaces for connection forwarding, only the first and second connections can be mapped. The second and third connections have no mapping（ Even if you click Add s step, the mapping will not appear.)

As shown in the figure below:

![image](https://user-images.githubusercontent.com/48100625/120992850-95226780-c7b5-11eb-9cd7-53d6eb71f0bc.png)

**Comment by zregvart** [comment]
Not sure if this another 2.x issue, on the latest 1.12.x I can add the the Data mapping step in all those cases. Note that the warning icon (the yellow triangle with the exclamation mark) is only added to emphasize that the input to that step has a different data shape than the previous step.
This is the same screenshot from my test integration:
![Screenshot_2021-06-07 Save or Add Step - Syndesis - DEVELOPMENT](https://user-images.githubusercontent.com/1306050/121068534-afb40b00-c7cc-11eb-84d8-7b39a0f5bd6a.png)

**Comment by suoxun** [comment]
> Not sure if this another 2.x issue, on the latest 1.12.x I can add the the Data mapping step in all those cases. Note that the warning icon (the yellow triangle with the exclamation mark) is only added to emphasize that the input to that step has a different data shape than the previous step.
> This is the same screenshot from my test integration:
> ![Screenshot_2021-06-07 Save or Add Step - Syndesis - DEVELOPMENT](https://user-images.githubusercontent.com/1306050/121068534-afb40b00-c7cc-11eb-84d8-7b39a0f5bd6a.png)

Thank you very much.

**Comment by zregvart** [comment]
I’m closing this feel free to reopen or create a followup issue if you think something was left out.
