### ISSUE TITLE
SQL placeholder bug

### ISSUE THREAD

**Issue by suoxun** [syndesisio/syndesis#9632]
When I use the sql placeholder, the following error occurs: (I filled in the sql according to the example on the official website)

Invalid SQL, the number of columns (0) should match the number of number of input parameters (1). Unable to fetch and process metadata

![image](https://user-images.githubusercontent.com/48100625/121183056-3ed92580-c896-11eb-8f9e-58dbdafff228.png)

When I don't take placeholders, there is no problem with the sql statement, as shown in the following figure:

![image](https://user-images.githubusercontent.com/48100625/121183458-aabb8e00-c896-11eb-8385-a19710872b93.png)

I tried several database connections, SQL statements are no problem, but once the use of a placeholder when there will be the above error.

**Comment by zregvart** [comment]
Can you provide the database details name/version and the JDBC driver name/version? A `CREATE` DDL would help also.

This error is reported from this bit of code:

https://github.com/syndesisio/syndesis/blob/ada45287a9c75b290dd217b1574d3f057c5c853f/app/connector/sql/src/main/java/io/syndesis/connector/sql/common/DbMetaDataHelper.java#L149-L153

Seems that no metadata can be found for the `testOne` table, is it spelled correctly? In some cases database objects can be case-sensitive (e.g. if quoted when created), so that might cause issues. It could also be this table resides in a different schema or that the user used to connect to the database doesn't have permissions to access it.

**Comment by suoxun** [comment]
> Can you provide the database details name/version and the JDBC driver name/version? A `CREATE` DDL would help also.
> 
> This error is reported from this bit of code:
> 
> https://github.com/syndesisio/syndesis/blob/ada45287a9c75b290dd217b1574d3f057c5c853f/app/connector/sql/src/main/java/io/syndesis/connector/sql/common/DbMetaDataHelper.java#L149-L153
> 
> Seems that no metadata can be found for the `testOne` table, is it spelled correctly? In some cases database objects can be case-sensitive (e.g. if quoted when created), so that might cause issues. It could also be this table resides in a different schema or that the user used to connect to the database doesn't have permissions to access it.

Database: MySQL database
Version number：5.7.18
The jdbc driver is：jdbc:mysql://xxx:3306/xxx?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&autoReconnect=true

Database DDL：

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for testOne
-- ----------------------------
DROP TABLE IF EXISTS `testOne`;
CREATE TABLE `testOne`  (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '姓名',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 3 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for testTwo
-- ----------------------------
DROP TABLE IF EXISTS `testTwo`;
CREATE TABLE `testTwo`  (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '姓名',
  `task` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '测试task',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 9 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

SET FOREIGN_KEY_CHECKS = 1;

I tried to use lowercase to write SQL statements, and the result is that errors will be reported when using or not using a placeholder, as shown in the figure：

![image](https://user-images.githubusercontent.com/48100625/121484574-ed4da980-ca01-11eb-8642-b1663a155908.png)
![image](https://user-images.githubusercontent.com/48100625/121484721-13734980-ca02-11eb-85ed-e6466de7eb6d.png)

**Comment by suoxun** [comment]
> > Can you provide the database details name/version and the JDBC driver name/version? A `CREATE` DDL would help also.
> > This error is reported from this bit of code:
> > https://github.com/syndesisio/syndesis/blob/ada45287a9c75b290dd217b1574d3f057c5c853f/app/connector/sql/src/main/java/io/syndesis/connector/sql/common/DbMetaDataHelper.java#L149-L153
> > 
> > Seems that no metadata can be found for the `testOne` table, is it spelled correctly? In some cases database objects can be case-sensitive (e.g. if quoted when created), so that might cause issues. It could also be this table resides in a different schema or that the user used to connect to the database doesn't have permissions to access it.
> 
> Database: MySQL database
> Version number：5.7.18
> The jdbc driver is：jdbc:mysql://xxx:3306/syndesis_test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&autoReconnect=true
> 
> Database DDL：
> 
> SET NAMES utf8mb4;
> SET FOREIGN_KEY_CHECKS = 0;
> 
> -- Table structure for testOne
> 
> DROP TABLE IF EXISTS `testOne`;
> CREATE TABLE `testOne` (
> `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
> `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '姓名',
> PRIMARY KEY (`id`) USING BTREE
> ) ENGINE = InnoDB AUTO_INCREMENT = 3 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;
> 
> -- Table structure for testTwo
> 
> DROP TABLE IF EXISTS `testTwo`;
> CREATE TABLE `testTwo` (
> `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
> `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '姓名',
> `task` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '测试task',
> PRIMARY KEY (`id`) USING BTREE
> ) ENGINE = InnoDB AUTO_INCREMENT = 9 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;
> 
> SET FOREIGN_KEY_CHECKS = 1;
> 
> I tried to use lowercase to write SQL statements, and the result is that errors will be reported when using or not using a placeholder, as shown in the figure：
> 
> ![image](https://user-images.githubusercontent.com/48100625/121484574-ed4da980-ca01-11eb-8642-b1663a155908.png)
> ![image](https://user-images.githubusercontent.com/48100625/121484721-13734980-ca02-11eb-85ed-e6466de7eb6d.png)

I think the table should have no permissions or structure problems. If these are problematic, then the sql statement: SELECT * FROM testOne WHERE id = 1 should also be wrong. The result is that this SQL can be integrated without problems.

**Comment by suoxun** [comment]
> Can you provide the database details name/version and the JDBC driver name/version? A `CREATE` DDL would help also.
> 
> This error is reported from this bit of code:
> 
> https://github.com/syndesisio/syndesis/blob/ada45287a9c75b290dd217b1574d3f057c5c853f/app/connector/sql/src/main/java/io/syndesis/connector/sql/common/DbMetaDataHelper.java#L149-L153
> 
> Seems that no metadata can be found for the `testOne` table, is it spelled correctly? In some cases database objects can be case-sensitive (e.g. if quoted when created), so that might cause issues. It could also be this table resides in a different schema or that the user used to connect to the database doesn't have permissions to access it.

Database: MySQL database
Version number：5.7.18
The jdbc driver is：jdbc:mysql://xxx:3306/syndesis_test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&autoReconnect=true

Database DDL：

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- Table structure for testOne

DROP TABLE IF EXISTS testOne;
CREATE TABLE testOne (
id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
name varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '姓名',
PRIMARY KEY (id) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 3 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- Table structure for testTwo

DROP TABLE IF EXISTS testTwo;
CREATE TABLE testTwo (
id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
name varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '姓名',
task varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '测试task',
PRIMARY KEY (id) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 9 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

SET FOREIGN_KEY_CHECKS = 1;

I tried to use lowercase to write SQL statements, and the result is that errors will be reported when using or not using a placeholder, as shown in the figure：

https://user-images.githubusercontent.com/48100625/121484574-ed4da980-ca01-11eb-8642-b1663a155908.png
https://user-images.githubusercontent.com/48100625/121484721-13734980-ca02-11eb-85ed-e6466de7eb6d.png

I think the table should have no permissions or structure problems. If these are problematic, then the sql statement: SELECT * FROM testOne WHERE id = 1 should also be wrong. The result is that this SQL can be integrated without problems.

**Comment by suoxun** [comment]
> Can you provide the database details name/version and the JDBC driver name/version? A `CREATE` DDL would help also.
> 
> This error is reported from this bit of code:
> 
> https://github.com/syndesisio/syndesis/blob/ada45287a9c75b290dd217b1574d3f057c5c853f/app/connector/sql/src/main/java/io/syndesis/connector/sql/common/DbMetaDataHelper.java#L149-L153
> 
> Seems that no metadata can be found for the `testOne` table, is it spelled correctly? In some cases database objects can be case-sensitive (e.g. if quoted when created), so that might cause issues. It could also be this table resides in a different schema or that the user used to connect to the database doesn't have permissions to access it.

Database: MySQL database
Version number：5.7.18
The jdbc driver is：jdbc:mysql://xxx:3306/syndesis_test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&autoReconnect=true

Database DDL：

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- Table structure for testOne

DROP TABLE IF EXISTS testOne;
CREATE TABLE testOne (
id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
name varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '姓名',
PRIMARY KEY (id) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 3 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- Table structure for testTwo

DROP TABLE IF EXISTS testTwo;
CREATE TABLE testTwo (
id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
name varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '姓名',
task varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '测试task',
PRIMARY KEY (id) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 9 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

SET FOREIGN_KEY_CHECKS = 1;

I tried to use lowercase to write SQL statements, and the result is that errors will be reported when using or not using a placeholder, as shown in the figure：

**Comment by suoxun** [comment]
> Can you provide the database details name/version and the JDBC driver name/version? A `CREATE` DDL would help also.
> 
> This error is reported from this bit of code:
> 
> https://github.com/syndesisio/syndesis/blob/ada45287a9c75b290dd217b1574d3f057c5c853f/app/connector/sql/src/main/java/io/syndesis/connector/sql/common/DbMetaDataHelper.java#L149-L153
> 
> Seems that no metadata can be found for the `testOne` table, is it spelled correctly? In some cases database objects can be case-sensitive (e.g. if quoted when created), so that might cause issues. It could also be this table resides in a different schema or that the user used to connect to the database doesn't have permissions to access it.

Database: MySQL database
Version number：5.7.18
The jdbc driver is：jdbc:mysql://xxx:3306/syndesis_test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&autoReconnect=true

Database DDL：

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- Table structure for testOne

DROP TABLE IF EXISTS testOne;
CREATE TABLE testOne (
id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
name varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '姓名',
PRIMARY KEY (id) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 3 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- Table structure for testTwo

DROP TABLE IF EXISTS testTwo;
CREATE TABLE testTwo (
id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
name varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '姓名',
task varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '测试task',
PRIMARY KEY (id) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 9 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

SET FOREIGN_KEY_CHECKS = 1;

I tried to use lowercase to write SQL statements, and the result is that errors will be reported when using or not using a placeholder, as shown in the figure：

![image](https://user-images.githubusercontent.com/48100625/121484574-ed4da980-ca01-11eb-8642-b1663a155908.png)
![image](https://user-images.githubusercontent.com/48100625/121484721-13734980-ca02-11eb-85ed-e6466de7eb6d.png)

I think the table should have no permissions or structure problems. If these are problematic, then the sql statement: SELECT * FROM testOne WHERE id = 1 should also be wrong. The result is that this SQL can be integrated without problems.

**Comment by zregvart** [comment]
In #9635 I've added an integration tests for this scenario. The test passes locally for me with MySQL version 8.0.25 and JDBC driver version 8.0.23 (inherited from Testcontainers). You can also have a look at the test to see if there is something off, I think it should reproduce this situation.

Version 5.7.18 is quite old and I don't think it's good for the project to test against it. I suspect the issue could be with older version of MySQL or JDBC driver. You can try with newer version to confirm.
