### ISSUE TITLE
Maven build problem

### ISSUE THREAD

**Issue by suoxun** [syndesisio/syndesis#9639]
Download the source code of version 1.12x to the local. When building maven, it was found that camel-spring-boot-dependencies:pom:2.23.2.fuse-790029 could not be found, as shown below:

![image](https://user-images.githubusercontent.com/48100625/121838736-14aabc00-cd0b-11eb-91ed-9659f4be60ff.png)

I searched a lot of Maven addresses, but I couldn't find this version. What is the URL address in the Maven settings file？
My URL is as follows:

![image](https://user-images.githubusercontent.com/48100625/121838959-96024e80-cd0b-11eb-80ca-13acdf570e05.png)

**Comment by zregvart** [comment]
Those dependencies can be found in the JBoss EA and Red Hat GA repositories. They're declared here:

https://github.com/syndesisio/syndesis/blob/d418d5c914e53ec9b9777c29746d54bffe9db7c9/app/pom.xml#L3786-L3795
