### ISSUE TITLE
for list problem

### ISSUE THREAD

**Issue by suoxun** [syndesisio/syndesis#9641]
I now want to pass in a list through the Provided API, and then loop this list for storage operations, but when I operate this connection, I find that the storage can only be one row of data, as shown below:

![image](https://user-images.githubusercontent.com/48100625/122050665-42305c00-ce16-11eb-93a6-e8880a411b70.png)
![image](https://user-images.githubusercontent.com/48100625/122050703-4fe5e180-ce16-11eb-88f5-1073de6de10c.png)
![image](https://user-images.githubusercontent.com/48100625/122050728-57a58600-ce16-11eb-89de-7518d500fb80.png)

The input parameters of Provided API are:

[{"idDto":1,"nameDto":"name1"},{"idDto":2,"nameDto":"name2"},{"idDto":3,"nameDto":"name3"},{"idDto":4,"nameDto":"name4"}]

The warehousing result is displayed as:

![image](https://user-images.githubusercontent.com/48100625/122051222-eca87f00-ce16-11eb-9ab1-d47d4f2c591f.png)

The result I want is to loop this collection when storing, and each piece of data is stored separately, as shown in the figure below:

![image](https://user-images.githubusercontent.com/48100625/122051535-4a3ccb80-ce17-11eb-9336-50e9f448ad2b.png)

Can syndesis do it?

**Comment by zregvart** [comment]
Try adding a [split step](https://syndesis.io/manual/integrating-applications/#add-split-step_collection). IIRC data shape needs to be a collection, which seems your request is -- being an array.

**Comment by suoxun** [comment]
> Try adding a [split step](https://syndesis.io/manual/integrating-applications/#add-split-step_collection). IIRC data shape needs to be a collection, which seems your request is -- being an array.

When my Provided API is an array, I want to split the array, and then add this split, but the split shows that there is no split step, as shown in the figure below:

overall:

![image](https://user-images.githubusercontent.com/48100625/122149042-0507b080-ce8e-11eb-9c51-5b5c83b0ed10.png)

Provided API:

![image](https://user-images.githubusercontent.com/48100625/122149238-56b03b00-ce8e-11eb-83fb-2031f7a6f8b4.png)
![image](https://user-images.githubusercontent.com/48100625/122149347-8101f880-ce8e-11eb-9667-06fc3fb87a32.png)

Split:

![image](https://user-images.githubusercontent.com/48100625/122149408-98d97c80-ce8e-11eb-87f7-c465b0c7c357.png)

How to split this array

**Comment by suoxun** [comment]
> > Try adding a [split step](https://syndesis.io/manual/integrating-applications/#add-split-step_collection). IIRC data shape needs to be a collection, which seems your request is -- being an array.
> 
> When my Provided API is an array, I want to split the array, and then add this split, but the split shows that there is no split step, as shown in the figure below:
> 
> overall:
> 
> ![image](https://user-images.githubusercontent.com/48100625/122149042-0507b080-ce8e-11eb-9c51-5b5c83b0ed10.png)
> 
> Provided API:
> 
> ![image](https://user-images.githubusercontent.com/48100625/122149238-56b03b00-ce8e-11eb-83fb-2031f7a6f8b4.png)
> ![image](https://user-images.githubusercontent.com/48100625/122149347-8101f880-ce8e-11eb-9667-06fc3fb87a32.png)
> 
> Split:
> 
> ![image](https://user-images.githubusercontent.com/48100625/122149408-98d97c80-ce8e-11eb-87f7-c465b0c7c357.png)
> 
> How to split this array

sorry sorry sorry 
The split has taken effect！
but I still don't understand why the prompt:

There are no properties to configure for this step.

**Comment by zregvart** [comment]
Looks like #2568 has not fixed this case.

**Comment by suoxun** [comment]
When an http connects to a db, Split will fail. The video is as follows:

https://user-images.githubusercontent.com/48100625/122377552-c1996900-cf97-11eb-8380-b95e877d834c.mp4

The purpose I want is:
1. Split the list parameter of the http parameter
2. The string type parameter after split is mapped to the name of sql

As shown below:

![image](https://user-images.githubusercontent.com/48100625/122379149-2b664280-cf99-11eb-83c3-e0a0da22b2c5.png)
![image](https://user-images.githubusercontent.com/48100625/122378479-92cfc280-cf98-11eb-8474-a7593e78c38c.png)
![image](https://user-images.githubusercontent.com/48100625/122378894-f0640f00-cf98-11eb-91e4-ab325e10a8bc.png)

The actual situation is how I operate and there is no split effect.

**Comment by zregvart** [comment]
You can't split on non top-level collections, meaning

```json
{
  "list":[
     ...
  ]
}
```
will not work, while:

```json
[
  ...
]
```
should.
