### ISSUE TITLE
Incoming parameter problem

### ISSUE THREAD

**Issue by suoxun** [syndesisio/syndesis#9643]
I have a need for a timer to enter parameters. For example, a timer calls another interface every time it is executed, and passes two paging parameters, the current page and the page size, to this interface. I think there is no parameter passing function in the Timer component in synthesis. May I ask how I want to achieve this requirement and how does synthesis do it?

![image](https://user-images.githubusercontent.com/48100625/122342144-d580a300-cf76-11eb-93d4-c9755ca013f9.png)

**Comment by zregvart** [comment]
You can use a [property or a constant](https://docs.atlasmap.io/#alternatives-for-supplying-source-values-that-are-missing) in the mapping step.

**Comment by suoxun** [comment]
> You can use a [property or a constant](https://docs.atlasmap.io/#alternatives-for-supplying-source-values-that-are-missing) in the mapping step.

According to your guidance, I have found the Timer custom parameter, but this parameter seems to be fixed. For example, in a connection between a Timer and https, I want the parameter "pageNum" to be automatically incremented by 1 every time the Timer is triggered, which means that the parameter will automatically change every time.

![image](https://user-images.githubusercontent.com/48100625/122354925-0915fa00-cf84-11eb-8a41-3bdc2ce93fce.png)
