### ISSUE TITLE
Header problem

### ISSUE THREAD

**Issue by suoxun** [syndesisio/syndesis#9663]
I know that API Provider can set the Header parameter. If it is HTTP, I also need to set the Header parameter. Does Syndesiss support it?

**Comment by zregvart** [comment]
The HTTP connector doesn't have that ability. You can use [custom REST API client](https://syndesis.io/manual/connecting/#connecting-to-api-clients_connectors) connectors, should be fairly straightforward, and in the editor you can configure any headers or parameters you need.
