### ISSUE TITLE
Import/Export API

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#967]
Create an API for export / importing which can be used from the outside.

Beside separating this from the 'internal' API between UI and Rest, one non-functional requirement is probably also how to authenticate.

more to come.

**Comment by aileenc** [comment]
Removing from TP4

**Comment by paoloantinori** [comment]
pending discussion on oauth issues

**Comment by gaughan** [comment]
@rhuss Definitely a candidate for 7.3, hopefully, it fits.

**Comment by heiko-braun** [comment]
closed as duplicate of #3701
