### ISSUE TITLE
Add 1.11 and 1.12 to community-operators on OperatorHub

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#9689]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Last version available for install on OpenShift is 1.9, this is because for 1.11 and 1.12 we placed the configuration in `upstream-community-operators` instead of `community-operators`.

Ref. https://operator-framework.github.io/community-operators/contributing-where-to/

**Comment by phantomjinx** [comment]
New location of openshift/OKD community OperatorHub -> https://github.com/redhat-openshift-ecosystem/community-operators-prod/tree/main/operators

see https://github.com/operator-framework/community-operators/#repository-is-obsolete

**Comment by phantomjinx** [comment]
Migration started....
https://github.com/k8s-operatorhub/community-operators/pull/98
https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/89
