### ISSUE TITLE
Teams & Roles

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#969]
See also **https://issues.jboss.org/browse/ENTESB-11552**

Support multiple users with different roles

**Comment by zregvart** [comment]
@kcbabo would you create a story for this or would a list of roles and what we want each role to be limited to suffice? Could you also think about how we would store/maintain membership to these roles, would this be something internal to Syndesis, tied to OpenShift or tied to some Enterprise environment (think LDAP).

**Comment by kcbabo** [comment]
This got kicked from TP4, right?

**Comment by zregvart** [comment]
> This got kicked from TP4, right?

Even better, I'll remove it from the TP4 and work on something else :)

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11552**
