### ISSUE TITLE
Failed to pull image "centos/postgresql-12-centos7": rpc error: code = Unknown desc = error pinging docker registry registry-1.docker.io: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io on IP:PORT: server misbehaving

### ISSUE THREAD

**Issue by tianlong19910404** [syndesisio/syndesis#9690]
Failed to pull image "centos/postgresql-12-centos7": rpc error: code = Unknown desc = error pinging docker registry registry-1.docker.io: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io on 172.15.32.30:53: server misbehaving

exec command ./syndesis install -p ceshisyndesis --app-options " --addons todo" -w 
report err 
syndesis-operator-79d5ffd8c5-bcnkf   0/1     Init:ErrImagePull       0          3m19s
Waiting for syndesis-operator - Sleeping 10s ...
![image](https://user-images.githubusercontent.com/12064063/126124425-862ae11c-2c74-4b15-bb21-ce9471e65fb2.png)

**Comment by tianlong19910404** [comment]
Now what what should i do?

**Comment by zregvart** [comment]
That looks like an issue with your network, DNS or proxy, rather than an issue with Syndesis.
