### ISSUE TITLE
can not  git clone from github  with windows

### ISSUE THREAD

**Issue by fengzhigu2000** [syndesisio/syndesis#9692]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Hello, I take the liberty to write a letter; however, I still want to make some suggestions of my own; I am a Chinese programmer, and more programmers in China use the windows operating system, but synedsis is not for the windows operating system Very friendly; for example, there are a lot of folders containing ":" in the ui-react directory, so it is impossible to clone from github on windows. The other is whether the overall deployment process can be written in more detail, especially in the local development, construction, deployment process and command line operations; I have a lot of problems during the use, but it is not special in bash To understanding.
     I also hope that the overall code structure can be clearer and spring:run can be better.

**Comment by zregvart** [comment]
Thanks for the feedback. I thought we fixed the issue with `:` in filenames in #7461, but I guess we did not, I think we fixed this now for good in #9693.

Most (all?) of us use Unix machines, so we get blindsighted for any issues when running on Windows. If you haven't yet read through we have extensive [documentation on the `syndesis`](https://syndesis.io/docs/cli/syndesis/) shell script, though the [day-to-day guide](https://syndesis.io/docs/cli/day_to_day/) does need to be refreshed.

We're happy to accept any contributions to the documentation or code to make it easier for folk to work on Windows.
