### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by zhaoding-git** [syndesisio/syndesis#9695]
## This is a...
When I choose a database connector, for example, the data source information is oracle. However, filling in nested sql statements will report: Table' select' does not exist in schema' test'. Unable to fetch and process metadata.
Is nested sql not supported?

**Comment by zregvart** [comment]
@zhaoding-git can you specify the version you're using and provide the full query or a simplified query that can be used to reproduce the issue?
In general, the SQL connector supports _simple_ queries and our recommendation is to use stored procedures for complex queries.

**Comment by zhaoding-git** [comment]
@zregvart 
version: 2.0-SNAPSHOT
sql: SELECT t.* FROM (SELECT * FROM test)  t
the issue: Table 'SELECT' does not exist in schema 'null'. Unable to fetch and process metadata.

**Comment by zregvart** [comment]
You're using 2.x which is not actively developed. In 1.12.x via #9584 we improved SQL parsing. I've noticed that we don't have a test for nested SQL statements so in #9696 I've added a test for that use case.

Your options are to use 1.12.x or to remain on 2.x and use a stored procedure instead.
