### ISSUE TITLE
About database Paging

### ISSUE THREAD

**Issue by zhaoding-git** [syndesisio/syndesis#9697]
**version**: 
  2.0-SNAPSHOT
**sql**: 
  select * from (select rownum, t.* from table_name t) where rownum > :#startIndex and rownum <= :#endIndex
**question**: 
  For example, I want to do paging query on oracle database, how to enter the parameter? How did mysql get involved?

**Comment by zregvart** [comment]
Any parameter that is named in the query should be present in the data shape and thus available for mapping. If you're getting an error or the parameter is not present in the mapping then this is a bug.

Note that ongoing development is on 1.x versions only.
