### ISSUE TITLE
Autocomplete to pick a property in basic filter not working

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#970]
To reproduce create an Integration with Twitter connection as a start and add a basic filter step. The `path` property (first one on the left) should offer autocomplete.

In the Twitter to Salesforce [sample integration docs](https://access.redhat.com/documentation/en-us/red_hat_jboss_fuse/7.0-tp/html-single/fuse_ignite_sample_integration_tutorial/index#t2sf-add-basic-filter-step) we make a note of the autocomplete, is this a **blocker**?

Seems that the `<datalist>` for `path` is not populated with the result from shape inspection. Not sure if the error below is related.

<details>
<summary>console error</summary>
ERROR ErrorcolumnNumber: 48645fileName: "https://syndesis.192.168.42.178.nip.io/polyfills.37f8c6bb16e03e965027.bundle.js"lineNumber: 1message: "No component factory found for t. Did you add it to @NgModule.entryComponents?"ngComponent: function t()originalStack: "g@https://syndesis.192.168.42.178.nip.io/polyfills.37f8c6bb16e03e965027.bundle.js:1:48645\nZ@https://syndesis.192.168.42.178.nip.io/vendor.717ef79426402b8f00f2.bundle.js:1:36043\n/oeL/</oa</t.prototype.resolveComponentFactory@https://syndesis.192.168.42.178.nip.io/vendor.717ef79426402b8f00f2.bundle.js:1:103724\n/oeL/</oa</t.prototype.resolveComponentFactory@https://syndesis.192.168.42.178.nip.io/vendor.717ef79426402b8f00f2.bundle.js:1:103674\n2YgE/a</t.prototype.attach@https://syndesis.192.168.42.178.nip.io/vendor.717ef79426402b8f00f2.bundle.js:1:207216\nNynv/Re</t.prototype.show@https://syndesis.192.168.42.178.nip.io/vendor.717ef79426402b8f00f2.bundle.js:1:1094236\nNynv/Ra</e.prototype.showTourStep@https://syndesis.192.168.42.178.nip.io/vendor.717ef79426402b8f00f2.bundle.js:1:1289753\nNynv/re</t.prototype.showStep@https://syndesis.192.168.42.178.nip.io/vendor.717ef79426402b8f00f2.bundle.js:1:1079567\nNynv/re</t.prototype.setCurrentStep@https://syndesis.192.168.42.178.nip.io/vendor.717ef79426402b8f00f2.bundle.js:1:1079287\nNynv/re</t.prototype.goToStep/</<@https://syndesis.192.168.42.178.nip.io/vendor.717ef79426402b8f00f2.bundle.js:1:1079020\neFQL/</</S</w</t.prototype.invokeTask@https://syndesis.192.168.42.178.nip.io/polyfills.37f8c6bb16e03e965027.bundle.js:1:56655\nonInvokeTask@https://syndesis.192.168.42.178.nip.io/vendor.717ef79426402b8f00f2.bundle.js:1:36837\neFQL/</</S</w</t.prototype.invokeTask@https://syndesis.192.168.42.178.nip.io/polyfills.37f8c6bb16e03e965027.bundle.js:1:56568\neFQL/</</S</b</n.prototype.runTask@https://syndesis.192.168.42.178.nip.io/polyfills.37f8c6bb16e03e965027.bundle.js:1:51544\nt/this.invoke@https://syndesis.192.168.42.178.nip.io/polyfills.37f8c6bb16e03e965027.bundle.js:1:57616\ne@https://syndesis.192.168.42.178.nip.io/polyfills.37f8c6bb16e03e965027.bundle.js:1:42863\n"stack: "g@https://syndesis.192.168.42.178.nip.io/polyfills.37f8c6bb16e03e965027.bundle.js:1:48645\nZ@https://syndesis.192.168.42.178.nip.io/vendor.717ef79426402b8f00f2.bundle.js:1:36043\n/oeL/</oa</t.prototype.resolveComponentFactory@https://syndesis.192.168.42.178.nip.io/vendor.717ef79426402b8f00f2.bundle.js:1:103724\n/oeL/</oa</t.prototype.resolveComponentFactory@https://syndesis.192.168.42.178.nip.io/vendor.717ef79426402b8f00f2.bundle.js:1:103674\n2YgE/a</t.prototype.attach@https://syndesis.192.168.42.178.nip.io/vendor.717ef79426402b8f00f2.bundle.js:1:207216\nNynv/Re</t.prototype.show@https://syndesis.192.168.42.178.nip.io/vendor.717ef79426402b8f00f2.bundle.js:1:1094236\nNynv/Ra</e.prototype.showTourStep@https://syndesis.192.168.42.178.nip.io/vendor.717ef79426402b8f00f2.bundle.js:1:1289753\nNynv/re</t.prototype.showStep@https://syndesis.192.168.42.178.nip.io/vendor.717ef79426402b8f00f2.bundle.js:1:1079567\nNynv/re</t.prototype.setCurrentStep@https://syndesis.192.168.42.178.nip.io/vendor.717ef79426402b8f00f2.bundle.js:1:1079287\nNynv/re</t.prototype.goToStep/</<@https://syndesis.192.168.42.178.nip.io/vendor.717ef79426402b8f00f2.bundle.js:1:1079020\neFQL/</</S</w</t.prototype.invokeTask@https://syndesis.192.168.42.178.nip.io/polyfills.37f8c6bb16e03e965027.bundle.js:1:56655\nonInvokeTask@https://syndesis.192.168.42.178.nip.io/vendor.717ef79426402b8f00f2.bundle.js:1:36837\neFQL/</</S</w</t.prototype.invokeTask@https://syndesis.192.168.42.178.nip.io/polyfills.37f8c6bb16e03e965027.bundle.js:1:56568\neFQL/</</S</b</n.prototype.runTask@https://syndesis.192.168.42.178.nip.io/polyfills.37f8c6bb16e03e965027.bundle.js:1:51544\nt/this.invoke@https://syndesis.192.168.42.178.nip.io/polyfills.37f8c6bb16e03e965027.bundle.js:1:57616\ne@https://syndesis.192.168.42.178.nip.io/polyfills.37f8c6bb16e03e965027.bundle.js:1:42863\n"zoneAwareStack: "g@https://syndesis.192.168.42.178.nip.io/polyfills.37f8c6bb16e03e965027.bundle.js:1:48645\nZ@https://syndesis.192.168.42.178.nip.io/vendor.717ef79426402b8f00f2.bundle.js:1:36043\n/oeL/</oa</t.prototype.resolveComponentFactory@https://syndesis.192.168.42.178.nip.io/vendor.717ef79426402b8f00f2.bundle.js:1:103724\n/oeL/</oa</t.prototype.resolveComponentFactory@https://syndesis.192.168.42.178.nip.io/vendor.717ef79426402b8f00f2.bundle.js:1:103674\n2YgE/a</t.prototype.attach@https://syndesis.192.168.42.178.nip.io/vendor.717ef79426402b8f00f2.bundle.js:1:207216\nNynv/Re</t.prototype.show@https://syndesis.192.168.42.178.nip.io/vendor.717ef79426402b8f00f2.bundle.js:1:1094236\nNynv/Ra</e.prototype.showTourStep@https://syndesis.192.168.42.178.nip.io/vendor.717ef79426402b8f00f2.bundle.js:1:1289753\nNynv/re</t.prototype.showStep@https://syndesis.192.168.42.178.nip.io/vendor.717ef79426402b8f00f2.bundle.js:1:1079567\nNynv/re</t.prototype.setCurrentStep@https://syndesis.192.168.42.178.nip.io/vendor.717ef79426402b8f00f2.bundle.js:1:1079287\nNynv/re</t.prototype.goToStep/</<@https://syndesis.192.168.42.178.nip.io/vendor.717ef79426402b8f00f2.bundle.js:1:1079020\neFQL/</</S</w</t.prototype.invokeTask@https://syndesis.192.168.42.178.nip.io/polyfills.37f8c6bb16e03e965027.bundle.js:1:56655\nonInvokeTask@https://syndesis.192.168.42.178.nip.io/vendor.717ef79426402b8f00f2.bundle.js:1:36837\neFQL/</</S</w</t.prototype.invokeTask@https://syndesis.192.168.42.178.nip.io/polyfills.37f8c6bb16e03e965027.bundle.js:1:56568\neFQL/</</S</b</n.prototype.runTask@https://syndesis.192.168.42.178.nip.io/polyfills.37f8c6bb16e03e965027.bundle.js:1:51544\nt/this.invoke@https://syndesis.192.168.42.178.nip.io/polyfills.37f8c6bb16e03e965027.bundle.js:1:57616\ne@https://syndesis.192.168.42.178.nip.io/polyfills.37f8c6bb16e03e965027.bundle.js:1:42863\n"__proto__: Object { … } vendor.717ef79426402b8f00f2.bundle.js:1:32153
<details>

**Comment by dsimansk** [comment]
@gashcrumb @kahboom @deeleman wdyt, is it possible to fix this issue for TP3?

**Comment by gashcrumb** [comment]
Getting an env going to have a look...

**Comment by gashcrumb** [comment]
Hmm, I don't see any `paths` in the response:

```
{
  "paths": [],
  "ops": [
    {
      "label": "equals",
      "operator": "=="
    },
    {
      "label": "equals (ignores case)",
      "operator": "=~"
    },
    {
      "label": "not equals",
      "operator": "=="
    },
    {
      "label": "",
      "operator": "<"
    },
    {
      "label": "",
      "operator": "<="
    },
    {
      "label": "",
      "operator": ">"
    },
    {
      "label": "",
      "operator": ">="
    },
    {
      "label": "contains",
      "operator": "contains"
    },
    {
      "label": "contains (ignore case)",
      "operator": "~~"
    },
    {
      "label": "not contains",
      "operator": "not contains"
    },
    {
      "label": "matches",
      "operator": "regex"
    },
    {
      "label": "not matches",
      "operator": "not regex"
    },
    {
      "label": "in",
      "operator": "in"
    },
    {
      "label": "not in",
      "operator": "not in"
    }
  ]
}
```

@zregvart can you look at the network tab and verify?  It's the request to `/options` and it occurs as the basic filter page loads, that `paths` property is what fills in the typeahead.

It's called with these parameters:

```
{
  "kind": "java",
  "type": "twitter4j.Status"
}
```

and this URL -> `https://syndesis.192.168.42.12.nip.io/api/v1/integrations/filters/options`

**Comment by zregvart** [comment]
Yup, `paths` is `[]` on my end, let me have a look on the backend.

**Comment by zregvart** [comment]
Hmm I'm a bit confused here, on `/integrations/filters/options` endpoint we either consider values from JSON Schema if the shape is `json-schema` or perform a remote invocation of Atlasmap. Atlasmap no longer bundles connector JARs so `twitter4j.Status` is not available that way.

During build time we have a Maven plugin that generates static JSON files with inspections, these are available at: `https://syndesis.....nip.io/mapper/v1/java-inspections/twitter/twitter4j.Status.json`, and I can't find that we use this from the back end.

Did the UI use these inspections and stopped?

Is the cleanest implementation of this to add another `Inspector` for those static JSON files, so as the end result we would have these on the `/integrations/filters/options` endpoint?

**Comment by zregvart** [comment]
So this:

https://github.com/syndesisio/syndesis/blob/aacb51d40ff7273b6d1d2d38edf427716046c241/app/ui/src/app/store/integration-support.service.ts#L30

and this:

https://github.com/syndesisio/syndesis/blob/aacb51d40ff7273b6d1d2d38edf427716046c241/app/ui/src/app/store/integration-support.service.ts#L65-L74

**Comment by gashcrumb** [comment]
I don't think the UI ever used these inspections, for this page it's been just this endpoint AFAIK.

**Comment by gashcrumb** [comment]
My guess is this has been broken since the mapper stopped bundling those jars :-)

**Comment by zregvart** [comment]
Found this: https://github.com/syndesisio/syndesis-rest/issues/466 I'll create a new `Inspector` for this, seems we never added one.

**Comment by lburgazzoli** [comment]
@zregvart @gashcrumb bear in mind that inspections may not be available from static resources, i.e. the twitter one won't be there anymore and will be part of connector's datashape so inspections are available also for connectors not known at build time (i.e. deployed by a customer).
