### ISSUE TITLE
Cannot run backups due to incorrect image references

### ISSUE THREAD

**Issue by phantomjinx** [syndesisio/syndesis#9716]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
The backup images are referenced in the config.yaml as
```
BackupImage: "crunchydata/crunchy-pgdump:centos7-12.5-4.5.1"
RestoreImage: "crunchydata/crunchy-pgrestore:centos7-12.5-4.5.1"
```
Although, these images are available in docker.io, openshift thinks they are fetched from redhat's own registry. This results in a failure to find the backup image and a failure to backup. This in turn stops any upgrades that might take place from 1.11.

- Create Env Vars for these images in the same way as other operands so that they can be overridden easily in bundle metadata.
- Fully qualify them with docker.io to ensure they are downloaded from the correct registry.

**Comment by svchinche** [comment]
I am also facing the same issue
