### ISSUE TITLE
[External] On-premise installation

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#972]
There must be a kind of package / documentation how to install Syndesis on premise on an arbitrary OpenShift cluster.

**Comment by TovaCohen** [comment]
@chirino @kcbabo 
Hiram, at the sprint planning meeting just now you said that some other group would be working on this. Who should I get in touch with to find out about what the user doc requirements are for this story?

**Comment by kcbabo** [comment]
@TovaCohen a bit early to focus on this topic.  Let's see how the initial validation goes and then we should have some good data on what needs to be documented.

**Comment by TovaCohen** [comment]
Here's a link to the doc issue for collecting the information that will need to be documented:
https://issues.jboss.org/browse/FUSEDOC-2406

**Comment by paoloantinori** [comment]
we had to confirm the name of the team and people that will take of this

**Comment by kcbabo** [comment]
Marek on the QE team is leading the validation of on-premise installation.

**Comment by TovaCohen** [comment]
Google document with initial draft:
https://url.corp.redhat.com/install-ignite-on-ocp 

Doc issue:
https://issues.jboss.org/browse/FUSEDOC-2485

**Comment by heiko-braun** [comment]
@rhuss is this done? According to the zenhub board it should be ...

**Comment by rhuss** [comment]
Yes, think so.
