### ISSUE TITLE
Issue using an API Client Connector

### ISSUE THREAD

**Issue by wassimd** [syndesisio/syndesis#9721]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

I created a swagger API client (https://api.hubspot.com/api-catalog-public/v1/apis/crm/v3/objects/contacts), after configuring the API key, and when I try to configure the integration, I get a blank page, any idea. 

## Screenshot

https://www.loom.com/share/afa14dc705da470197c511d8eaadb68c

No special log on console or pod logs 

## Version 
Syndesis: 1.13.0-20210902
Build ID:
Commit ID: 3b7b680cca4470ea1623db01ed2baf5591f83328

**Comment by zregvart** [comment]
Looks like an issue in the UI code.
