### ISSUE TITLE
Waiting for syndesis-operator - Sleeping 10s ...

### ISSUE THREAD

**Issue by Mars-2030** [syndesisio/syndesis#9744]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

HI 
1. I Have installed minishift successfully and worked really fine
2. installed the openshift-cli  and its also working fine
3. I also installed the syndesis cli and  run this command (`sudo ln -s $(pwd)/syndesis /usr/local/bin`)
4. I run this command   `syndesis minishift --install --full-reset --nodev --open --openshift-version=v3.10.0 --vm-driver virtualbox  --network-nameserver 8.8.8.8`
also tried this `syndesis minishift --install --full-reset --nodev --open  --vm-driver VirtualBox`

it start the minishift and it seems everything working fine but it stops at this point 

`Using project "myproject".

Deploying Syndesis operator

Waiting for syndesis-operator to be scaled to 1
Waiting for syndesis-operator - Sleeping 10s ...
NAME                         READY     STATUS    RESTARTS   AGE
syndesis-operator-1-deploy   0/1       Pending   0          2s
syndesis-operator-1-deploy   0/1       Pending   0         2s
syndesis-operator-1-deploy   0/1       ContainerCreating   0         2s
syndesis-operator-1-bl8xx   0/1       Pending   0         2s
syndesis-operator-1-bl8xx   0/1       Pending   0         2s
syndesis-operator-1-bl8xx   0/1       Init:0/1   0         2s
syndesis-operator-1-deploy   1/1       Running   0         7s
Waiting for syndesis-operator - Sleeping 10s ...
Waiting for syndesis-operator - Sleeping 10s ...
syndesis-operator-1-bl8xx   0/1       PodInitializing   0         24s
Waiting for syndesis-operator - Sleeping 10s ...
syndesis-operator-1-bl8xx   1/1       Running   0         36s
syndesis-operator-1-deploy   0/1       Completed   0         41s
syndesis-operator-1-deploy   0/1       Terminating   0         41s
syndesis-operator-1-deploy   0/1       Terminating   0         41s
Waiting for syndesis-operator - Sleeping 10s ...
Waiting for syndesis-operator - Sleeping 10s ...
`

and here is the --verbose 

You have one project on this server: "myproject"

Using project "myproject".
++(minishift:153): minishift::run(): echo 'Deploying Syndesis operator'
Deploying Syndesis operator
+++(minishift:154): minishift::run(): hasflag --nodev
+++(common_funcs:8): hasflag(): filters=--nodev
+++(common_funcs:9): hasflag(): for var in '"${ARGS[@]}"'
+++(common_funcs:10): hasflag(): for filter in '$filters'
+++(common_funcs:11): hasflag(): '[' minishift = --nodev ']'
+++(common_funcs:9): hasflag(): for var in '"${ARGS[@]}"'
+++(common_funcs:10): hasflag(): for filter in '$filters'
+++(common_funcs:11): hasflag(): '[' --install = --nodev ']'
+++(common_funcs:9): hasflag(): for var in '"${ARGS[@]}"'
+++(common_funcs:10): hasflag(): for filter in '$filters'
+++(common_funcs:11): hasflag(): '[' --full-reset = --nodev ']'
+++(common_funcs:9): hasflag(): for var in '"${ARGS[@]}"'
+++(common_funcs:10): hasflag(): for filter in '$filters'
+++(common_funcs:11): hasflag(): '[' --nodev = --nodev ']'
+++(common_funcs:12): hasflag(): echo true
+++(common_funcs:13): hasflag(): return
++(minishift:154): minishift::run(): '[' true ']'
+++(minishift:155): minishift::run(): /Users/mariam/.syndesis/bin/syndesis-operator install operator
++(minishift:155): minishift::run(): result='operator was installed successfully'
++(minishift:160): minishift::run(): check_error 'operator was installed successfully'
++(common_funcs:85): check_error(): local 'msg=operator was installed successfully'
+++(common_funcs:86): check_error(): contains_error 'operator was installed successfully'
+++(common_funcs:72): contains_error(): local 'msg=operator was installed successfully'
+++(common_funcs:77): contains_error(): awk 'BEGIN {exit !index(toupper(ARGV[2]), toupper(ARGV[1]))}' ERROR 'operator was installed successfully'
+++(common_funcs:80): contains_error(): echo NO
++(common_funcs:86): check_error(): '[' NO == YES ']'
++(minishift:162): minishift::run(): wait_for_deployments 1 syndesis-operator
++(openshift_funcs:327): wait_for_deployments(): local replicas_desired=1
++(openshift_funcs:328): wait_for_deployments(): shift
++(openshift_funcs:329): wait_for_deployments(): local dcs=syndesis-operator
++(openshift_funcs:332): wait_for_deployments(): watch_pid=6226
++(openshift_funcs:331): wait_for_deployments(): oc get pods -w
++(openshift_funcs:333): wait_for_deployments(): for dc in '$dcs'
++(openshift_funcs:334): wait_for_deployments(): echo 'Waiting for syndesis-operator to be scaled to 1'
Waiting for syndesis-operator to be scaled to 1
+++(openshift_funcs:335): wait_for_deployments(): get_replicas syndesis-operator
+++(openshift_funcs:346): get_replicas(): local dc=syndesis-operator
++++(openshift_funcs:347): get_replicas(): oc get deployment -o name
++++(openshift_funcs:347): get_replicas(): grep syndesis-operator
+++(openshift_funcs:347): get_replicas(): local hasDc=
+++(openshift_funcs:348): get_replicas(): '[' -z '' ']'
+++(openshift_funcs:349): get_replicas(): echo 0
+++(openshift_funcs:350): get_replicas(): return
++(openshift_funcs:335): wait_for_deployments(): local replicas=0
++(openshift_funcs:336): wait_for_deployments(): '[' -z 0 ']'
++(openshift_funcs:336): wait_for_deployments(): '[' 0 -ne 1 ']'
++(openshift_funcs:337): wait_for_deployments(): echo 'Waiting for syndesis-operator - Sleeping 10s ...'
Waiting for syndesis-operator - Sleeping 10s ...
++(openshift_funcs:338): wait_for_deployments(): sleep 10
NAME                         READY     STATUS    RESTARTS   AGE
syndesis-operator-1-deploy   0/1       Pending   0          2s
syndesis-operator-1-deploy   0/1       Pending   0         2s
syndesis-operator-1-deploy   0/1       ContainerCreating   0         2s
syndesis-operator-1-7bs8r   0/1       Pending   0         2s
syndesis-operator-1-7bs8r   0/1       Pending   0         2s
syndesis-operator-1-7bs8r   0/1       Init:0/1   0         2s
syndesis-operator-1-deploy   1/1       Running   0         3s
+++(openshift_funcs:339): wait_for_deployments(): get_replicas syndesis-operator
+++(openshift_funcs:346): get_replicas(): local dc=syndesis-operator
++++(openshift_funcs:347): get_replicas(): oc get deployment -o name
++++(openshift_funcs:347): get_replicas(): grep syndesis-operator
+++(openshift_funcs:347): get_replicas(): local hasDc=
+++(openshift_funcs:348): get_replicas(): '[' -z '' ']'
+++(openshift_funcs:349): get_replicas(): echo 0
+++(openshift_funcs:350): get_replicas(): return
++(openshift_funcs:339): wait_for_deployments(): replicas=0
++(openshift_funcs:336): wait_for_deployments(): '[' -z 0 ']'
++(openshift_funcs:336): wait_for_deployments(): '[' 0 -ne 1 ']'
++(openshift_funcs:337): wait_for_deployments(): echo 'Waiting for syndesis-operator - Sleeping 10s ...'
Waiting for syndesis-operator - Sleeping 10s ...
++(openshift_funcs:338): wait_for_deployments(): sleep 10
+++(openshift_funcs:339): wait_for_deployments(): get_replicas syndesis-operator
+++(openshift_funcs:346): get_replicas(): local dc=syndesis-operator
++++(openshift_funcs:347): get_replicas(): grep syndesis-operator
++++(openshift_funcs:347): get_replicas(): oc get deployment -o name
+++(openshift_funcs:347): get_replicas(): local hasDc=
+++(openshift_funcs:348): get_replicas(): '[' -z '' ']'
+++(openshift_funcs:349): get_replicas(): echo 0
+++(openshift_funcs:350): get_replicas(): return
++(openshift_funcs:339): wait_for_deployments(): replicas=0
++(openshift_funcs:336): wait_for_deployments(): '[' -z 0 ']'
++(openshift_funcs:336): wait_for_deployments(): '[' 0 -ne 1 ']'
++(openshift_funcs:337): wait_for_deployments(): echo 'Waiting for syndesis-operator - Sleeping 10s ...'
Waiting for syndesis-operator - Sleeping 10s ...
++(openshift_funcs:338): wait_for_deployments(): sleep 10
+++(openshift_funcs:339): wait_for_deployments(): get_replicas syndesis-operator
+++(openshift_funcs:346): get_replicas(): local dc=syndesis-operator
++++(openshift_funcs:347): get_replicas(): grep syndesis-operator
++++(openshift_funcs:347): get_replicas(): oc get deployment -o name
+++(openshift_funcs:347): get_replicas(): local hasDc=
+++(openshift_funcs:348): get_replicas(): '[' -z '' ']'
+++(openshift_funcs:349): get_replicas(): echo 0
+++(openshift_funcs:350): get_replicas(): return
++(openshift_funcs:339): wait_for_deployments(): replicas=0
++(openshift_funcs:336): wait_for_deployments(): '[' -z 0 ']'
++(openshift_funcs:336): wait_for_deployments(): '[' 0 -ne 1 ']'
++(openshift_funcs:337): wait_for_deployments(): echo 'Waiting for syndesis-operator - Sleeping 10s ...'

and stays like this forever I am not sure why  syndesis-operator-1-deploy   is terminated

Note: I am trying to install the quick start syndesis on minishift and using macOS bigSur 11.5
I would appreciate your help

**Comment by claudio4j** [comment]
Can you check the pods with `oc get pods` ? If there is any error, you can see by using `oc logs pod/<pod name>` 
Also, out of curiosity, can you use the latest openshift in minishift, as you are using an outdated v3.10.0.

**Comment by wassimd** [comment]
Hello, try allowing more memory anc CPU to syndesis. This resolved similar issue for me.
`sudo tools/bin/syndesis  minishift --install --full-reset --nodev --open --memory 40GB --cpus 20 --disk-size=60GB `
