### ISSUE TITLE
File upload parameter type problem

### ISSUE THREAD

**Issue by zengpengQu** [syndesisio/syndesis#9770]
In the version of syndesis 2.0-snapshot, API provider is used to upload files. In the body of the post request of API provider 3. X, when multipart / form data is selected for media types, how to select the corresponding type? Or is there another way?

**Comment by wassimd** [comment]
![image](https://user-images.githubusercontent.com/14020609/139558424-942bcbf6-02b2-4771-8691-9c5d4577ad54.png)
