### ISSUE TITLE
Upgrade Fabric8 Kubernetes client

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#9773]
For OpenShift 4.9 compatibility the API version of CRDs needs to be `v1`, see #9772. I think we need to support both `apiextensions.k8s.io/v1beta2` and `apiextensions.k8s.io/v1` at the same time.

**Comment by mkralik3** [comment]
@zregvart `apiextensions.k8s.io/v1beta2` doesn't exist. There was probably a typo before #9772 there (in KafkaMetaDataRetrieval). I think that `v1beta1` is a valid version for OCP3 ( and kubernetes < v1.16 )
