### ISSUE TITLE
API connector: button name for the wizard's last step 

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis#997]
The proposed [UX design](https://github.com/syndesisio/syndesis/blob/master/ux/designs/apiconnector/apiconnector.md#general-connector-info) has `Create Connector` button in top right corner and still features `Next` button. 

I've been wondering if it isn't better to have just one of `Create | Create Connector | Done` button at the bottom of the form.

<details>
<summary>Current state</summary>

![screen shot 2018-01-10 at 08 29 10](https://user-images.githubusercontent.com/5637792/34760572-adef3ffe-f5e0-11e7-88dc-090844a4d24a.png)

</details>

**Comment by deeleman** [comment]
I recall we agreed to remove the top right button after an impromptu casual chat with UXD.

Agreed with replacing _Next_ by something like _Create Connector_ or anything that clearly conveys that such view is merely the last step in the create process.

**Comment by deeleman** [comment]
Perhaps we'd need someone from @syndesisio/uxd to add their feedback here.

**Comment by dongniwang** [comment]
If I recall correctly, we talk about keeping just "Cancel" at the top right corner, and replacing "Next" in the form area to "Create Connector". 

cc: @sjcox-rh @amysueg @seanforyou23 @gashcrumb

**Comment by deeleman** [comment]
> If I recall correctly, we talk about keeping just "Cancel" at the top right corner, and replacing "Next" in the form area to "Create Connector".

Shall I proceed then? :)

**Comment by dongniwang** [comment]
@deeleman go ahead please. And thank you for tagging us!
