### ISSUE TITLE
API connector: default params can't be overwritten in wizard

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis#999]
In todo-example, there's only generic [hostname](https://github.com/syndesisio/todo-example/blob/master/swagger.json#L11) declaration for obvious reasons. However, when I follow the API connector wizard to the last step and customize those parameters my changes aren't reflected on a connector itself.

E.g. when I want to create new connection, there're still only defaults. as provided in swagger file.

![screen shot 2018-01-10 at 09 54 53](https://user-images.githubusercontent.com/5637792/34763735-71238556-f5ec-11e7-8d84-9b5d4a76c090.png)

And in detail view also

![screen shot 2018-01-10 at 09 56 27](https://user-images.githubusercontent.com/5637792/34763771-8dce3886-f5ec-11e7-9437-e8c2f67ccb20.png)

**Comment by zregvart** [comment]
What I see:

- [ ] When creating new custom API connector if `host` and `basePath` are specified in `configuredProperties` they are not honored in the created connector (backend issue)
- [ ] When editing `Host` or `Base URL` on the details page changes are not reflected on the connector (backend issue)

I can see the changes made to `host` and `basePath` persisted when editing Connection created for custom API Connector.

**Comment by dsimansk** [comment]
@zregvart custom API connector detail is fixed now. But when creating new Connection for the custom connector, I still see it initialised with default values.

![screen shot 2018-01-10 at 15 33 13](https://user-images.githubusercontent.com/5637792/34777746-9bf8726c-f61b-11e7-9a89-d06f0400c25b.png)
